### PR TITLE
[RFC] ci: Travis: upgrade OSX images (10.1 => 10.2)

### LINKED ISSUE #10213: ci: looping in "Re-running CMake..." / "ninja: error: manifest 'build.ninja' still dirty after 100 tries"
Builds on Travis might fail to run cmake (https://travis-ci.org/neovim/neovim/jobs/545198646):

```
ci/before_script.sh
cache directory                     /Users/travis/.ccache
primary config                      /Users/travis/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/Cellar/ccache/3.7.1/etc/ccache.conf
stats updated                       Thu Jun 13 12:18:08 2019
cache hit (direct)                   480
cache hit (preprocessed)               0
cache miss                            94
cache hit rate                     83.62 %
called for link                      123
called for preprocessing              82
autoconf compile/link                328
cleanups performed                     0
files in cache                       230
cache size                          10.5 MB
max cache size                       5.0 GB
Using third-party dependencies from Travis cache (last update: Jun 12 23:18:33 2019).
Configuring with '-DDEPS_DOWNLOAD_DIR:PATH=/Users/travis/build/neovim/neovim/deps-downloads -DUSE_BUNDLED_GPERF=OFF'.
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
==============================================================================
[0/1] Re-running CMake...
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
[0/1] Re-running CMake...
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
[0/1] Re-running CMake...
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
ninja: error: manifest 'build.ninja' still dirty after 100 tries
The command "ci/before_script.sh" failed and exited with 1 during .
```

Only have seen this with OSX builds on Travis, and restarting them might fix it then.
With https://travis-ci.org/neovim/neovim/builds/545198641 both OSX jobs failed due to this - I've restarted one of them.

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neovim/neovim/issues/10213#issuecomment-503361663

Maybe fixes https://github.com/neovim/neovim/issues/10213.

### CODE REVIEW

**Comment by blueyed** [comment]
Build time looks the same, have not compared logs yet.

**Comment by blueyed** [comment]
Running this again (rebased), ran into an issue with the build cache?!:

```
Install neovim npm package

/Users/travis/.nvm/versions/node/v10.15.0/bin/neovim-node-host -> /Users/travis/.nvm/versions/node/v10.15.0/lib/node_modules/neovim/bin/cli.js

+ neovim@4.5.0

added 18 packages from 24 contributors in 2.856s

/Users/travis/build/neovim/neovim/node_modules/neovim -> /Users/travis/.nvm/versions/node/v10.15.0/lib/node_modules/neovim

travis_time:end:2d8f7564:start=1561364884566590000,finish=1561364916228753000,duration=31662163000
[0Ktravis_fold:end:install
[0Ktravis_fold:start:before_script
[0Ktravis_time:start:1cdd1d49
[0K$ ci/before_script.sh

Statistics zeroed

Using third-party dependencies from Travis cache (last update: Jun 24 00:49:29 2019).

cp: /Users/travis/.cache/nvim-deps/./build/src/libuv-build/test/fixtures/load_error.node: No such file or directory

cp: /Users/travis/.cache/nvim-deps/./build/src/libuv-build/test/fixtures/empty_file: No such file or directory

travis_time:end:1cdd1d49:start=1561364916241470000,finish=1561364921874073000,duration=5632603000
[0K[31;1mThe command "ci/before_script.sh" failed and exited with 1 during .[0m



Your build has been stopped.
```

**Comment by blueyed** [comment]
@justinmk 
Looks like the nvim-deps script is broken?
https://travis-ci.org/neovim/neovim/jobs/549616487#L363

**Comment by justinmk** [comment]
@blueyed I cleared travis cache for this PR and the master branch, then restarted the build. 

cache script is here: https://github.com/neovim/neovim/blob/master/ci/before_cache.sh
That directory is stored implicitly by `.travis.yml`: https://github.com/neovim/neovim/blob/master/.travis.yml#L133-L139

**Comment by blueyed** [comment]
It appears to not handle symlinks correctly: https://github.com/neovim/neovim/pull/10331

**Comment by blueyed** [comment]
Re https://github.com/neovim/neovim/blob/50293953a31f909056b250f6138f1fbb380921a2/ci/before_cache.sh#L20-L21: isn't the Travis cache updated/handled for successful builds always anyway?

**Comment by blueyed** [comment]
Failed again - but indicates that cache was updated already / not really deleted?!

Cherry-picked https://github.com/neovim/neovim/pull/10331 into it now.

**Comment by blueyed** [comment]
One of the osx jobs failed:
```
[ RUN      ] TermClose event triggers when long-running terminal job gets stopped: -- Output to stderr:
Vim: Caught deadly signal 'SIGHUP'
Vim: Finished.
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:63 (message):
  functional tests failed with error: SIGPIPE
FAILED: CMakeFiles/functionaltest 
```
Restarted.

It seems the cp-cache fix proved itself to be working here.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
