### PR TITLE
[RFC] vim-patch:8.0.0493

### PR DESCRIPTION
**Pull request by ckelsel**
#### vim-patch:8.0.0493: crash with cd command with very long argument

Problem:    Crash with cd command with very long argument.
Solution:   Check for running out of space. (Dominique pending, closes vim/vim#1576)

https://github.com/vim/vim/commit/15618fa643867cf0d9c31f327022a22dff78a0cf

### CODE REVIEW

**Comment by ckelsel** [comment]
```
=================================================================
==7990==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4ee4e3 in malloc /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67:3
    #1 0xf51731 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
    #2 0xf51959 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
    #3 0xc7f8c5 in ff_create_stack_element /home/travis/build/neovim/neovim/src/nvim/file_search.c:1169:21
    #4 0xc7e091 in vim_findfile_init /home/travis/build/neovim/neovim/src/nvim/file_search.c:508:10
    #5 0xc8c6e6 in find_file_in_path_option /home/travis/build/neovim/neovim/src/nvim/file_search.c:1524:27
    #6 0xc8ca03 in find_directory_in_path /home/travis/build/neovim/neovim/src/nvim/file_search.c:1375:10
    #7 0xc8d3d6 in vim_chdir /home/travis/build/neovim/neovim/src/nvim/file_search.c:1628:22
    #8 0xb53556 in ex_cd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7239:9
    #9 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #10 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #11 0xb07ea5 in do_cmdline_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:280:10
    #12 0x90f564 in f_assert_fails /home/travis/build/neovim/neovim/src/nvim/eval.c:6854:3
    #13 0x7e4f94 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6373:11
    #14 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #15 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #16 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #17 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #18 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3
    #19 0x7e48bb in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6358:11
    #20 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #21 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #22 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #23 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #24 0x8385f1 in ex_execute /home/travis/build/neovim/neovim/src/nvim/eval.c:19474:7
    #25 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #26 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #27 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3
    #28 0x7e48bb in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6358:11
    #29 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11

Indirect leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x4ee8e7 in realloc /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:98:3
    #1 0xf51d21 in xrealloc /home/travis/build/neovim/neovim/src/nvim/memory.c:169:15
    #2 0xd30e13 in ga_grow /home/travis/build/neovim/neovim/src/nvim/garray.c:98:14
    #3 0x125d7c0 in addfile /home/travis/build/neovim/neovim/src/nvim/path.c:1403:3
    #4 0x125af7b in gen_expand_wildcards /home/travis/build/neovim/neovim/src/nvim/path.c:1251:9
    #5 0x1266e97 in expand_wildcards /home/travis/build/neovim/neovim/src/nvim/path.c:2018:12
    #6 0xc835ab in vim_findfile /home/travis/build/neovim/neovim/src/nvim/file_search.c:769:11
    #7 0xc8c45e in find_file_in_path_option /home/travis/build/neovim/neovim/src/nvim/file_search.c:1500:21
    #8 0xc8ca03 in find_directory_in_path /home/travis/build/neovim/neovim/src/nvim/file_search.c:1375:10
    #9 0xc8d3d6 in vim_chdir /home/travis/build/neovim/neovim/src/nvim/file_search.c:1628:22
    #10 0xb53556 in ex_cd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7239:9
    #11 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #12 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #13 0xb07ea5 in do_cmdline_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:280:10
    #14 0x90f564 in f_assert_fails /home/travis/build/neovim/neovim/src/nvim/eval.c:6854:3
    #15 0x7e4f94 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6373:11
    #16 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #17 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #18 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #19 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #20 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3
    #21 0x7e48bb in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6358:11
    #22 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #23 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #24 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #25 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #26 0x8385f1 in ex_execute /home/travis/build/neovim/neovim/src/nvim/eval.c:19474:7
    #27 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #28 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #29 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3

Indirect leak of 52 byte(s) in 1 object(s) allocated from:
    #0 0x4ee4e3 in malloc /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67:3
    #1 0xf51731 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
    #2 0xf51959 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
    #3 0x125d68b in addfile /home/travis/build/neovim/neovim/src/nvim/path.c:1392:15
    #4 0x125af7b in gen_expand_wildcards /home/travis/build/neovim/neovim/src/nvim/path.c:1251:9
    #5 0x1266e97 in expand_wildcards /home/travis/build/neovim/neovim/src/nvim/path.c:2018:12
    #6 0xc835ab in vim_findfile /home/travis/build/neovim/neovim/src/nvim/file_search.c:769:11
    #7 0xc8c45e in find_file_in_path_option /home/travis/build/neovim/neovim/src/nvim/file_search.c:1500:21
    #8 0xc8ca03 in find_directory_in_path /home/travis/build/neovim/neovim/src/nvim/file_search.c:1375:10
    #9 0xc8d3d6 in vim_chdir /home/travis/build/neovim/neovim/src/nvim/file_search.c:1628:22
    #10 0xb53556 in ex_cd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7239:9
    #11 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #12 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #13 0xb07ea5 in do_cmdline_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:280:10
    #14 0x90f564 in f_assert_fails /home/travis/build/neovim/neovim/src/nvim/eval.c:6854:3
    #15 0x7e4f94 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6373:11
    #16 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #17 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #18 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #19 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #20 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3
    #21 0x7e48bb in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6358:11
    #22 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #23 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #24 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #25 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #26 0x8385f1 in ex_execute /home/travis/build/neovim/neovim/src/nvim/eval.c:19474:7
    #27 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #28 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #29 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3

Indirect leak of 51 byte(s) in 1 object(s) allocated from:
    #0 0x4ee4e3 in malloc /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67:3
    #1 0xf51731 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
    #2 0xf51959 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
    #3 0xf51f2d in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
    #4 0xf520ae in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
    #5 0xf53758 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
    #6 0x1712c53 in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:66:20
    #7 0xc7fefc in ff_create_stack_element /home/travis/build/neovim/neovim/src/nvim/file_search.c:1182:23
    #8 0xc7e091 in vim_findfile_init /home/travis/build/neovim/neovim/src/nvim/file_search.c:508:10
    #9 0xc8c6e6 in find_file_in_path_option /home/travis/build/neovim/neovim/src/nvim/file_search.c:1524:27
    #10 0xc8ca03 in find_directory_in_path /home/travis/build/neovim/neovim/src/nvim/file_search.c:1375:10
    #11 0xc8d3d6 in vim_chdir /home/travis/build/neovim/neovim/src/nvim/file_search.c:1628:22
    #12 0xb53556 in ex_cd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7239:9
    #13 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #14 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #15 0xb07ea5 in do_cmdline_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:280:10
    #16 0x90f564 in f_assert_fails /home/travis/build/neovim/neovim/src/nvim/eval.c:6854:3
    #17 0x7e4f94 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6373:11
    #18 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #19 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #20 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #21 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #22 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3
    #23 0x7e48bb in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6358:11
    #24 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #25 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #26 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #27 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #28 0x8385f1 in ex_execute /home/travis/build/neovim/neovim/src/nvim/eval.c:19474:7
    #29 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5

Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x4ee4e3 in malloc /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67:3
    #1 0xf51731 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
    #2 0xf51959 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
    #3 0xf51f2d in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
    #4 0xf520ae in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
    #5 0xf53758 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
    #6 0x1712c53 in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:66:20
    #7 0xc80026 in ff_create_stack_element /home/travis/build/neovim/neovim/src/nvim/file_search.c:1186:22
    #8 0xc7e091 in vim_findfile_init /home/travis/build/neovim/neovim/src/nvim/file_search.c:508:10
    #9 0xc8c6e6 in find_file_in_path_option /home/travis/build/neovim/neovim/src/nvim/file_search.c:1524:27
    #10 0xc8ca03 in find_directory_in_path /home/travis/build/neovim/neovim/src/nvim/file_search.c:1375:10
    #11 0xc8d3d6 in vim_chdir /home/travis/build/neovim/neovim/src/nvim/file_search.c:1628:22
    #12 0xb53556 in ex_cd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7239:9
    #13 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #14 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #15 0xb07ea5 in do_cmdline_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:280:10
    #16 0x90f564 in f_assert_fails /home/travis/build/neovim/neovim/src/nvim/eval.c:6854:3
    #17 0x7e4f94 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6373:11
    #18 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #19 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #20 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #21 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #22 0x819242 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21328:3
    #23 0x7e48bb in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6358:11
    #24 0x7f96b8 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6120:11
    #25 0x7f22a1 in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2735:9
    #26 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
    #27 0xb01b93 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
    #28 0x8385f1 in ex_execute /home/travis/build/neovim/neovim/src/nvim/eval.c:19474:7
    #29 0xb1f92c in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
```

**Comment by justinmk** [comment]
In https://github.com/neovim/neovim/pull/7960 I found numerous older patches that should have been ported first. It's really important that we try to port oldest patches first. Otherwise it makes things much more difficult.

**Comment by ckelsel** [comment]
@justinmk Yes, you are right. I port patches from the oldest , from 1 to 493 (now)

**Comment by janlazo** [comment]
Is it still blocked?

**Comment by justinmk** [comment]
perhaps rebase and see if the LeakSanitizer error still exists.

**Comment by janlazo** [comment]
Do Vim CI builds run LeakSanitizer?

**Comment by chrisbra** [comment]
> Do Vim CI builds run LeakSanitizer?

It does:
https://github.com/vim/vim/blob/414998023fbff15cce20ef01a54d0366370ad8b6/.travis.yml#L22-L25

**Comment by janlazo** [comment]
@ckelsel Can you try checking the return value of `add_pathsep`?

**Comment by janlazo** [comment]
https://github.com/vim/vim/blob/7c365fb190225d98af818daf195dc19921fe01ca/src/misc2.c#L4444-L4450

This was removed in nvim but there's no `STRLEN(str) < MAXPATHL` check to avoid errors?

**Comment by justinmk** [comment]
@janlazo `(temp == NULL || wc_path == NULL)` cannot happen because `vim_strsave` and `xmalloc` never fail. `STRLEN(str) < MAXPATHL` might be a good idea, though I don't see it in Vim's code.

**Pull request closed without merging**
