### PR TITLE
[RDY] Small modeline cleanup

### PR DESCRIPTION
**Pull request by ghost**
'foldenable' is already the default, so setting it is unneeded for
people that want folds, and unwanted for people who use 'nofoldenable'.

Also bring `fold.c`'s modeline in line with `terminal.c`'s.

### CODE REVIEW

**Comment by glts** [comment]
Seems reasonable to me.

Since you are also touching the modeline of an unrelated file, perhaps consider bringing the modeline of `fold.c` in line with that of `terminal.c`. These two are then the only remaining modelines in the C source as far as I can see.

**Comment by Pyrohh** [comment]
:+1: done

**Comment by glts** [comment]
I don't yet qualify to say the magic words, but I tried the change and it Looks Good To Me.

**Comment by splinterofchaos** [comment]
LGTM, too :+1: 

Actually, I thought long ago it was decided to remove all modelines.

**Comment by Pyrohh** [comment]
> Actually, I thought long ago it was decided to remove all modelines.

That's a good point,is there any reason not to remove the remaining two modelines outright? Perhaps people want folds, but don't want the file to open with all folds collapsed (at least that's what happens for me).

**Comment by glts** [comment]
@Pyrohh I think `foldmethod=marker` might make sense for files with actual fold markers in the source. Otherwise you'd always have to set that manually. (And remember that toggling is just `zi`, super simple.)

**Comment by Pyrohh** [comment]
@glts `zi` is quite nice, I suppose it's fine to leave the foldmethod (unless someone thinks it should be a `local-vimrc`).

**Comment by Pyrohh** [comment]
I just removed the modelines, given that was also done for every other file a while ago. I'll set this to ready given its size.

**Comment by Pyrohh** [comment]
@philix do you still hold the same view you said in https://github.com/neovim/neovim/pull/629#issuecomment-41495036? I don't use modelines, but it seems like that's something that should be set in a vimrc or local ftplugin.

**Comment by philix** [comment]
> @philix do you still hold the same view you said in #629 (comment)? I don't use modelines, but it seems like that's something that should be set in a vimrc or local ftplugin.

I still do. I don't see the problem of leaving them on the `fold.c` file. As I said, someone spent the time to add nice folding markers to that file.

**Comment by Pyrohh** [comment]
> I still do. I don't see the problem of leaving them on the fold.c file. As I said, someone spent the time to add nice folding markers to that file.

Sounds good, I reverted the relevant changes.

**Comment by philix** [comment]
LGTM

**Pull request merged**
