### PR TITLE
[RFC] Rename execute() function to feed_command

### PR DESCRIPTION
**Pull request by ZyX-I**
This function bothered me for quite some time: it is inefficient, known to hide some bugs (by allowing to easily ignore error messages) and yet used in a number of cases where it is not needed. This PR renames execute() to feed_command() and replaces its usages with either feed_command or command. Added a bunch of wait()s just in case when using command().

### CODE REVIEW

**Comment by justinmk** [comment]
Agreed completely. `feed_command` is much better name. 

But it also bothers me that `feed()` actually calls `nvim_input()` (nothing to do with `feedkeys()`!). I plan to rename `helpers.feed()` to `helpers.input()`.

**Comment by ZyX-I** [comment]
Travis clint failure is not relevant, it is single-includes. Restarted build. PR should be ready now regardless of the result.

**Comment by justinmk** [comment]
In `012_directory_spec.lua` I see:

```lua
meths.set_option('swapfile', true)
curbufmeths.set_option('swapfile', true)
```

Since https://github.com/neovim/neovim/pull/6405 it shouldn't be needed to explicitly set the global option, `nvim_buf_set_option` will update the global option.

**Comment by justinmk** [comment]
What do you think about (in a later PR) removing `feed_command()` entirely? Seems to me we should be explicit and use `helpers.feed(':foo<CR>')` (rename to `helpers.input()`).

**Comment by ZyX-I** [comment]
`feed_command()` has multiple arguments and cares about escaping. That would not be straightforward and as you said name is already explicit enough.

**Comment by ZyX-I** [comment]
Missing `~` is intentional, nobody will thank test code if it will pollute a home directory. I would not have done that if $HOME was set in the test, but it was not. Also test is successfull without `~`, so no need to bother with $HOME.

**Comment by ZyX-I** [comment]
> Since #6405 it shouldn't be needed to explicitly set the global option, nvim_buf_set_option will update the global option.

#6405 does not look like something which does this strange thing. `nvim_buf_set_option` *must not* update the global option, by using this function you explicitly request setting buffer-local option. And in fact after applying

```Patch
diff --git a/test/functional/api/vim_spec.lua b/test/functional/api/vim_spec.lua
index 8f9f155..4473aef 100644
--- a/test/functional/api/vim_spec.lua
+++ b/test/functional/api/vim_spec.lua
@@ -168,6 +168,10 @@ describe('api', function()
       nvim('set_option', 'shiftwidth', 20)
       eq('20', nvim('command_output', 'setglobal shiftwidth?'):match('%d+'))
       eq('8', nvim('command_output', 'setlocal shiftwidth?'):match('%d+'))
+
+      helpers.curbufmeths.set_option('lisp', true)
+      helpers.curbufmeths.set_option('lisp', false)
+      eq(true, nvim('get_option', 'lisp'))
     end)
 
     it('most window-local options have no global value', function()
```

test still passes.

**Pull request merged**
