### PR TITLE
[RFC] Delete test86 and 87

### PR DESCRIPTION
**Pull request by ghost**
The python-client has it's own test suite, and this isn't even run: see the `has('nvim') call` at the top of the tests.

Taken from https://github.com/bfredl/neovim/commit/1acf4ace5224cf12472d2b086f55a74714491d6f with minor modifications. #2929 seems to be frozen (or waiting for review), so I figured there's no harm in cherry-picking this low-hanging fruit (no pun intended).

### CODE REVIEW

**Comment by justinmk** [comment]
I remembered #2929 yesterday and was planning to get it moving. There's no rush to remove those tests in the meantime..

**Comment by bfredl** [comment]
What #2929 needs is converting test 58/59 to lua test (I tried to debug it in place, but it is hopeless). I will look into it in the weekend if no one beats me to it.

**Comment by Pyrohh** [comment]
> There's no rush to remove those tests in the meantime..

Of course, but the tests don't seem to be related to #2929 at all, so it makes more sense to separate it out IMO, hence the PR.

**Comment by lucc** [comment]
@bfredl I started to work on test 59 a while ago.  will open a WIP PR now so you can see what I have tried. Yes it it is a mess :)

**Comment by bfredl** [comment]
> Of course, but the tests don't seem to be related to #2929 at all, so it makes more sense to separate it out IMO, hence the PR.

:+1: It was originally needed to run the oldtests locally, but not anymore. Now that you've done the necessary cleanup, why not go ahead and merge this.

**Comment by Pyrohh** [comment]
Merged, thanks.

**Pull request closed without merging**
