### PR TITLE
Work on tidying up the code

### PR DESCRIPTION
**Pull request by NyanHelsing**
Worked on code alignment, using consistent commenting.

### CODE REVIEW

**Comment by Pyrohh** [comment]
Hi @HalcyonChimera,

I'm not sure if we're accepting any purely stylistic PRs, and besides that, the coding style used here doesn't match ours. Please see https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#coding-style, which also comments on stylistic PRs.

**Comment by HalcyonChimera** [comment]
I see what you're saying; to have so many changes would make it difficult to track changes through Git. I argue that the style was egregious; edging on unreadable. The major things that I felt needed cleaning up were the single line if statements which, along with only a two-space indentation, lacked curly braces; which makes it difficult to discern the structure at first glance. As a coder new to this project, being able to grok the code to get up to speed is an important factor. As I'm reading through files; I will try to limit changes to the worst offenders, but I honestly raised an eyebrow reading this - I was somewhat shocked that such a influential text editor as vim looked like this behind the scenes.

**Comment by philix** [comment]
> Just finished perusing nvim's style guide. I'll submit another PR with a little less noise, more meaningful changes, and the right style.

Please don't submit PRs with big style changes. They probably won't be reviewed before the code you restyled is changed by another contributor rendering your PR really hard to merge correctly and not worth the risk. This should be told to avoid your time being wasted on a PR that we won't be able to merge.

> As a coder new to this project, being able to grok the code to get up to speed is an important factor.

Reviewing other PRs is the best way to understand the code enough to be able to contribute. Vim's codebase is really convoluted but one can contribute without understanding how the whole thing ties together.

**Comment by HalcyonChimera** [comment]
Just want to say thanks for the feedback; I submitted a new PR with something I'm expecting should be more in line what you were talking about.

**Pull request closed without merging**
