### PR TITLE
refactor(lsp): deprecate get_client_by_id

### PR DESCRIPTION
**Pull request by justinmk**
This is WIP, wondering if there is any strong objections to this.

The `get({filter})` pattern is generally preferred and aliases to its special cases should be avoided.

### CODE REVIEW

**Comment by MariaSolOs** [comment]
No objections from my side.

**Comment by lewis6991** [comment]
I was thinking about this too, but `get_client_by_id` is just too simple and useful. Yes, `get_clients` can do the same thing, but it comes with too much additional friction IMO.

**Comment by justinmk** [comment]
> If you desperately want to avoid an alias, then I think it would be better to remove `id` as a filter, and potentially rename it to `get_client` to allow for potential future overloads in the future.

What about an overload like `get_clients(id: int)`?

**Comment by lewis6991** [comment]
I wouldn't call that an improvement over what we have now as it still returns a table that needs to be indexed.

The only way I think we can remove this in a way that benefits the system, would be to also remove the applications for it's use.

We currently use it in our code as opposed to upval'ing the client object to check if a client is still valid. If we could add better state tracking to the clients, then we can change our APIs to pass objects around instead of IDs. This would eliminate most uses of `get_client_by_id`. There would be a bunch of breaking changes along the way, so needs a thought out plan.

**Comment by mfussenegger** [comment]
I agree with Lewis, having a method that returns a single client instead of the table is useful - and that's despite Lua's `nil[1] -> nil` behavior making the list lookup less painful than it would be in other languages. There is value in a type carrying the information at there is at most one result.

Besides - the method's implementation is a single line, [it's used a lot](https://github.com/search?utf8=%E2%9C%93&q=get_client_by_id+language%3Alua&type=code) and would cause a lot of churn. I'd rather use up the budget for user's tolerance for changes of more impactful stuff.

**Comment by justinmk** [comment]
> Besides - the method's implementation is a single line, [it's used a lot](https://github.com/search?utf8=%E2%9C%93&q=get_client_by_id+language%3Alua&type=code) and would cause a lot of churn. I'd rather use up the budget for user's tolerance for breaking changes of more impactful stuff.

Implementation cost is often not the main cost. Rather, the presence of a single case is used to justify proliferation and sets the expectation of similar pattern in other modules. Its mere presence is confusing and counterproductive.

That is the primary purpose of most deprecations. Because the implementation cost is usually a sunk cost. Thus keeping the programmatic functionality around for back-compat is often worthwhile and cheap. But deprecating it--removing it from docs and human-visible surface area--gives a valuable signal about recommended patterns, reduces code review time, etc.

If we take that approach, then users won't be bothered by plugin breakage. Is there still an objection?

**Comment by justinmk** [comment]
> If we were to design this today from scratch, I'd probably want to add it again, but go with `get_client(id)` that raises an error if missing instead of nil.

That sounds fine to me. So if we agree that for new APIs this is the recommended pattern, then that answers the main question. 

I'm ok with not deprecating `get_client_by_id` to avoid churn, based on the strong objections. But going forward, for new Lua APIs, I'll document the preferred pattern as `get[_foo]` with a filter and non-filter overload.

**Pull request closed without merging**
