### PR TITLE
feat(cmdline): treesitter highlighting on the cmdline

### PR DESCRIPTION
**Pull request by rudiejd**
Opening this while I try to work on https://github.com/neovim/neovim/issues/26346. Mostly just researching right now

Problem: the cmdline doesn't have syntax highlighting
Solution: Use treesitter for syntax highlighting on the cmdline

I found a hacky way to get syntax highlighting working for the cmdwin (`set syntax=vim`)  but a proper way to do this probably involves exposing the cmdline buffer such that we can start treesitter there. However, we would have to expose the cmdline buffer to lua as an actual buffer in this case

### CODE REVIEW

**Comment by rudiejd** [comment]
The main lift here seems to be maknig cmdbuff in `CmdlineInfo` a `buf_T`, since right now it's just a string. I'm going to see if I can create a scratch buffer like we do in the cmdwin, but just do that for every cmdline. Open to any better ideas 😅

**Comment by clason** [comment]
@rudiejd sorry for the bot. Are you still working on this?

**Comment by rudiejd** [comment]
@clason no problem! Nope, I was pretty lost and I think @luukvbaal  volunteered to take this over

**Comment by luukvbaal** [comment]
> I think @luukvbaal volunteered to take this over

I did, I continued hacking away at it had a cmdline replacement close to finished.
But in working out the last kinks I came to the conclusion that this feature may be best paired with a replacement/merged floating window for the message grid which may need further design decisions.

I might do some full-time (funded) work on this soon, possibly pivoting to an ext_cmdline/message implementation after all...

**Pull request closed without merging**
