### PR TITLE
[RFC] Fix clang analysis warnings. (9)

### PR DESCRIPTION
**Pull request by elmart**
Set warning count back to zero.

### CODE REVIEW

**Comment by elmart** [comment]
@tarruda Last commit I requested your help for (a previous version of https://github.com/elmart/neovim/commit/39355e3f4a05993b3586a33bf82677500da8de72) is already fixed here. So don't worry about that anymore. After pushing this, I haven't found the previous version of the commit, so I have posted here instead of there, just to let you know. Thx.

**Comment by tarruda** [comment]
First errored test is a race condition: #2130. @bfredl fixed in #2221 but it wasn't merged yet(feel free to cherry pick the commit) 

Test61 has been failing sporadically for some time now, hopefully we can fix the indeterminism it once its migrated(I haven't looked closely at the error yet)

**Comment by elmart** [comment]
@tarruda I've added the commit you mentioned, but it still fails with a new failing functional test:
```
Failure -> ...vis/build/neovim/neovim/test/functional/job/job_spec.lua @ 200
jobs jobwait will run callbacks while waiting
...vis/build/neovim/neovim/test/functional/job/job_spec.lua:215: Expected objects to be the same.
Passed in:
(table): {
  [1] = 'notification'
  [2] = 'wait'
  [3] = {
    [1] = {
      [1] = '4'
      [2] = '5'
      [3] = '7' } } }
Expected:
(table): {
  [1] = 'notification'
  [2] = 'wait'
  [3] = {
    [1] = {
      [1] = '4'
      [2] = '5'
      [3] = '6'
      [4] = '7' } } }
```
Was the commit I added the only one needed from #2221, as I supposed?
Also, note that the only build failing is linux gcc. Maybe some valgrind interaction?

**Comment by tarruda** [comment]
@elmart this test error was introduced by #2247, I'm working on a fix so feel free to ignore it

**Comment by elmart** [comment]
Ok. I was just writing you to say another unrelated PR (#2228) was failing with the same error.

Well, thanks very much! Your help was very much appreciated.

**Comment by elmart** [comment]
To reviewers:
Travis test failure is not because of this PR, so review can start here.

**Comment by tarruda** [comment]
@elmart You can rebase/push this PR now, the `jobwait` test problem should be fixed

**Comment by tarruda** [comment]
You can remove the indeterminism fix commit, #2221 has been merged.

**Comment by elmart** [comment]
@tarruda Removed the commit and repushed. I'll wait for some review before pushing.

**Comment by elmart** [comment]
@oni-link Addressed last two comments on possible leaks and repushed.

**Comment by oni-link** [comment]
LGTM.

**Comment by justinmk** [comment]
Merged

**Pull request closed without merging**
