### PR TITLE
scripts/vim-patch.sh: list previous missing Vim patches

### PR DESCRIPTION
**Pull request by blueyed**
Example output:
```console
% scripts/vim-patch.sh -m v8.1.0105
=== getting missing patches for 31 files ===
[1/31] runtime/doc/change.txt: v8.1.0105: all tab stops are the same
[2/31] runtime/doc/options.txt: v8.0.1455: if $SHELL contains a space then 'shell' is incorrect
[3/31] runtime/doc/various.txt: v8.1.0105: all tab stops are the same
[4/31] runtime/optwin.vim: v8.0.1743: terminal window options are named inconsistently
[5/31] src/Makefile: v8.0.1123: cannot define a toolbar for a window
[6/31] src/beval.c: v8.1.0105: all tab stops are the same
[7/31] src/beval.h: v8.1.0105: all tab stops are the same
[8/31] src/buffer.c: v8.0.1119: quitting a split terminal window kills the job
[9/31] src/charset.c: v8.1.0105: all tab stops are the same
[10/31] src/edit.c: v8.0.1356: using simalt in a GUIEnter autocommand inserts characters
[11/31] src/evalfunc.c: v8.0.1123: cannot define a toolbar for a window
[12/31] src/ex_cmds.c: v8.0.1287: temp file used for viminfo may have wrong permissions
[13/31] src/feature.h: v8.0.1531: cannot use 24 bit colors in MS-Windows console
[14/31] src/gui_beval.c: v8.1.0105: all tab stops are the same
[15/31] src/gui_w32.c: v8.1.0105: all tab stops are the same
[16/31] src/hardcopy.c: v8.1.0105: all tab stops are the same
[17/31] src/message.c: v8.1.0105: all tab stops are the same
[18/31] src/misc1.c: v8.0.1531: cannot use 24 bit colors in MS-Windows console
[19/31] src/ops.c: v8.0.1587: inserting from the clipboard doesn't work literally
[20/31] src/option.c: v8.0.1455: if $SHELL contains a space then 'shell' is incorrect
[21/31] src/option.h: v8.0.1491: the minimum width of the popup menu is hard coded
[22/31] src/proto/misc1.pro: v8.1.0105: all tab stops are the same
[23/31] src/proto/option.pro: v8.0.1554: custom plugins loaded with --clean
[24/31] src/screen.c: v8.0.1123: cannot define a toolbar for a window
[25/31] src/structs.h: v8.0.0902: cannot specify directory or environment for a job
[26/31] src/testdir/Make_all.mak: v8.0.1123: cannot define a toolbar for a window
[27/31] src/testdir/gen_opt_test.vim: v8.0.1531: cannot use 24 bit colors in MS-Windows console
[28/31] src/testdir/test_breakindent.vim: v8.1.0105: all tab stops are the same
[29/31] src/testdir/test_vartabs.vim: v8.1.0105: all tab stops are the same
[30/31] src/version.c: v8.0.0902: cannot specify directory or environment for a job
[31/31] src/workshop.c: v8.1.0105: all tab stops are the same
=== Missing previous Vim patches ===
v8.0.0902: cannot specify directory or environment for a job
v8.0.1119: quitting a split terminal window kills the job
v8.0.1123: cannot define a toolbar for a window
v8.0.1287: temp file used for viminfo may have wrong permissions
v8.0.1356: using simalt in a GUIEnter autocommand inserts characters
v8.0.1455: if $SHELL contains a space then 'shell' is incorrect
v8.0.1491: the minimum width of the popup menu is hard coded
v8.0.1531: cannot use 24 bit colors in MS-Windows console
v8.0.1554: custom plugins loaded with --clean
v8.0.1587: inserting from the clipboard doesn't work literally
v8.0.1743: terminal window options are named inconsistently
scripts/vim-patch.sh -m v8.1.0105  6.91s user 0.76s system 102% cpu 7.512 total
```

This could also be used with e.g. `-P` to notify about other patches that should be done first.

### CODE REVIEW

**Comment by justinmk** [comment]
Cool. I guess it's too late, but next time I would strongly encourage putting more logic into vimpatch.lua . This bash script is getting too big.

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
> I guess it's too late, but next time I would strongly encourage putting more logic into vimpatch.lua . This bash script is getting too big.

Yeah, but OTOH this is the kind of thing shell scripts are good for (parsing/handling output from other commands), and there's a lot of logic/processing there already that can be re-used etc.  Also it's better to keep adding new functionality there, instead of having two separate scripts.
I can see what you mean, but I think it is fine to stick with the shell script here in general.

**Comment by janlazo** [comment]
@blueyed Does this filter for patches that match criteria at https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#types-of-not-applicable-vim-patches? We don't need the `gui_*`, `*.proto`, `beval*` files.

**Comment by justinmk** [comment]
> to reduce the number of previous patches? We don't need the `gui_*`, `*.proto`, `beval*` files.

I would assume that this skips anything already matched by `vimpatch.lua` (which checks `git log --grep=...`. Else this feature would be far too noisy.

**Comment by norcalli** [comment]
Did someone say rewrite it in Lua? I have actually rewritten a good number of shell scripts in Lua that had become too unwieldy and it save a lot of lines. Lua already has `io.popen` builtin for reading output. The only thing it didn't support well was reading and writing from a command, but we have both `luv` and `vim.fn.system()` to do that. I'd say it's pretty ergonomic.

I can try to port over the logic later if you want @justinmk.

**Comment by justinmk** [comment]
> Lua already has `io.popen` builtin for reading output and it gets you 90% of the way

yeah, and not even that is needed with Nvim Lua since `vim.fn.system` is far more robust as you mentioned.

Regarding "pipe"/stream ergonomics, it would be nice to have something like that in Nvim Lua (like node.js's `.pipe()` for example). But rewriting `vim-path.sh` entirely could be a time-sink, and is low priority for now. Just we should avoid snowballing it into a 500 LOC monster.

Meanwhile let's move forward on this PR?

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
> Meanwhile let's move forward on this PR?

I need to revisit regarding exlcusion/filtering of diffs, which does not appear to happen in `vimpatch.lua`, but `vim-script.sh` already, doesn't it?  https://github.com/neovim/neovim/blob/b9c9283f729c60d98634587190eb14c6bbf428e5/scripts/vim-patch.sh#L171-L214

**Comment by justinmk** [comment]
> I need to revisit regarding exlcusion/filtering of diffs, which does not appear to happen in `vimpatch.lua`, but `vim-script.sh` already, doesn't it?

Doesn't happen in vimpatch.lua yet, but if it required rewriting a bunch of code...

**Comment by blueyed** [comment]
> why does it need to be revisited anyway?

I think it would be good to exclude files being ignored with `preprocess_patch` ("Patch surgery") also here, and for that it would be best to share the `na_src` and `na_doc` "lists" with that function, but that's not trivial/easy.

I think it's good to merge/use this as-is already, and improve it later then.

**Comment by janlazo** [comment]
Ubuntu Xenial

```
$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ ./scripts/vim-patch.sh -l > missing-patches.txt 
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 11 (delta 6), reused 11 (delta 6), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/vim/vim
   5398955..1500a42  master     -> origin/master
 * [new tag]         v8.2.0037  -> v8.2.0037
 * [new tag]         v8.2.0036  -> v8.2.0036
./scripts/vim-patch.sh: line 402: tokens[*]: unbound variable
```

**Comment by blueyed** [comment]
@janlazo 
Is this enough to fix it?

```diff
diff --git i/scripts/vim-patch.sh w/scripts/vim-patch.sh
index 483264415..b5806311c 100755
--- i/scripts/vim-patch.sh
+++ w/scripts/vim-patch.sh
@@ -399,9 +399,11 @@ declare -A tokens
 declare -A vim_commit_tags

 _set_tokens_and_tags() {
+  set +u  # Avoid "unbound variable" with bash < 4.4 below.
   if [[ -n "${tokens[*]}" ]]; then
     return
   fi
+  set -u

   # Find all "vim-patch:xxx" tokens in the Nvim git log.
   for token in $(list_vimpatch_tokens); do
```

**Comment by janlazo** [comment]
@blueyed Yes

**Comment by blueyed** [comment]
@janlazo pushed in 5f1aec5.

**Comment by janlazo** [comment]
@blueyed `usage()` doesn't mention `-m`.

**Comment by blueyed** [comment]
> @blueyed `usage()` doesn't mention `-m`.

@janlazo 
Thanks for pointing it out.  Feel free to fix it yourself - but I've marked it in my inbox and will come back to it later otherwise.

**Pull request merged**
