### PR TITLE
[RFC] Fix redrawing issues with narrow screen and remove extra wait in resize tests

### PR DESCRIPTION
**Pull request by bfredl**
Screen size is part of screen state, so treat it as such, instead of some kind of precondition for even doing screen tests.

Saves ~10 seconds in UI tests in local testing.

### CODE REVIEW

**Comment by bfredl** [comment]
the `has minimum width/height` test is very suspicious, the first expectation is clearly wrong, but it is equally wrong if 2 lines is set explicitly instead, so the bug is likely not caused by ui layer logic (intended vs actual height), rather somewhere in the screen.c layout code.

**Comment by bfredl** [comment]
In general, nvim will behave erratically when modemsg doesn't fit on a line, best tried with `i<c-o>v` to get a modemsg significantly longer than `MIN_COLUMNS`.

Latest commit tries to fix it by truncating instead, changed test shows change of behavior (to the better), also this test is hopefully not in-deterministic anymore.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
restarted appveyor, only  `nodejs_spec` failed there. Please merge this if it's ready!

**Comment by bfredl** [comment]
added comment, let's run the tests once more (to check indeterminism).

**Comment by bfredl** [comment]
This one was interesting:
```
[----------] Running tests from /Users/travis/build/neovim/neovim/test/functional/ui/spell_spec.lua
[ RUN      ] 'spell' joins long lines #7937: ERR
test/functional/helpers.lua:202: test/functional/ui/screen.lua:324: Add Screen:_handle_curs
stack traceback:
	test/functional/helpers.lua:202: in function 'run'
	test/functional/ui/screen.lua:284: in function 'wait'
	test/functional/ui/screen.lua:213: in function 'expect'
	...is/build/neovim/neovim/test/functional/ui/spell_spec.lua:38: in function <...is/build/neovim/neovim/test/functional/ui/spell_spec.lua:27>
-- Output to stderr:
Uncaught Error: .../nvim-deps/usr/share/lua/5.1/nvim/msgpack_rpc_stream.lua:84: invalid msgpack-rpc string
stack traceback:
	[C]: in function 'receive'
	.../nvim-deps/usr/share/lua/5.
```

Highlight `_handle_curs` which likely means stream was corrupted right after first 4 bytes in update name. Ref #8102

**Pull request merged**
