### PR TITLE
[RFC] migrate legacy tests

### PR DESCRIPTION
**Pull request by rainerborene**
more tests coming.

### CODE REVIEW

**Comment by rainerborene** [comment]
@tarruda merge #1993 when you've time.

**Comment by tarruda** [comment]
Great!

**Comment by rainerborene** [comment]
@tarruda ready to review and merge.

**Comment by rainerborene** [comment]
@tarruda just to remember you to also merge #2046 and #2074 pull requests.

**Comment by tarruda** [comment]
> @tarruda just to remember you to also merge #2046 and #2074 pull requests.

:+1: assigned them to myself and will have a look later this week

**Comment by justinmk** [comment]
merged.

before this PR:

```
$ make && time make oldtest
real    0m55.022s
user    0m6.867s
sys     0m3.233s

$ time make functionaltest
real    0m10.000s
user    0m6.291s
sys     0m2.051s
```

after this PR:

```
$ make clean && make && time make oldtest
real    0m49.376s
user    0m6.764s
sys     0m3.170s

$ time make functionaltest
227 successes / 0 failures / 0 errors / 2 pending : 0.0 seconds
real    0m10.904s
user    0m6.902s
sys     0m2.250s
```

So, new functional tests seem to be about 5x faster than the legacy tests. Thanks @rainerborene !

**Comment by justinmk** [comment]
Hmm, you added 10 tests, but only 8 were found by busted (increase from 221 => 229).

**Comment by tarruda** [comment]
@justinmk :+1: Thanks for taking care of this

**Comment by rainerborene** [comment]
I usually run tests using the `TEST_FILE` environment variable. Thanks for fixing @justinmk

**Pull request closed without merging**
