### PR TITLE
WIP: run luv callbacks in a coroutine

### PR DESCRIPTION
**Pull request by lewis6991**
Yield from this coroutine will schedule it onto the mian event loop.

---

Not sure if this is a good idea or not.

### CODE REVIEW

**Comment by lewis6991** [comment]
Implementing this in Lua with something like the following might be simpler:

```lua
function vim.schedule_thread(fn)
  local thread = coroutine.create(fn)

  local function step(...)
    local ret = { coroutine.resume(thread, ...) }
    local status = ret[1]
    if not status then
      error(ret[2])
    end
    local args = vim.F.pack_len(unpack(ret, 2, table.maxn(ret)))
    vim.schedule(function()
      step(vim.F.unpack_len(args))
    end)
  end

  return step
end
```

**Comment by bfredl** [comment]
IMO we should try a pure Lua approach first (except possibly a few lines of C to hook into it from the luv pcall wrapper, I haven't made up my mind if I like that or not, might depend on the overhead of starting a co-routine every time)

**Comment by lewis6991** [comment]
Yeah I agree. I'm not even sure if we should do this at all instead of just providing a stdlib function so it is opt-in.

**Comment by lewis6991** [comment]
Not convinced this is worth pursuing.

**Pull request closed without merging**
