### PR TITLE
[RDY] vim-patch:8.2.0865 syntax: Add option to improve folding with attached braces

### PR DESCRIPTION
**Pull request by bradking**
With `foldmethod=syntax` the foldlevel of a line is computed based on syntax items on the line.  Previously we always used the level of the syntax item containing the start of the line.  This works well in cases such as:

```c
if (...) {
  ...
}
else if (...) {
  ...
}
else {
  ...
}
```
which folds like this:

```
+---  3 lines: if (...) {---------------------------
+---  3 lines: else if (...) {----------------------
+---  3 lines: else {-------------------------------
```

However, the code:

```c
if (...) {
  ...
} else if (...) {
  ...
} else {
  ...
}
```

folds like this:

```
+---  7 lines: if (...) {---------------------------
```

We can make the latter case fold like this:

```
+---  2 lines: if (...) {---------------------------
+---  2 lines: } else if (...) {--------------------
+---  3 lines: } else {-----------------------------
```

by choosing on each line the lowest fold level that is followed by a higher fold level.

Add a syntax command

```
:syntax foldlevel [start | minimum]
```

to choose between these two methods of computing the `foldlevel` of a line.

### CODE REVIEW

**Comment by jamessan** [comment]
Thanks for the thorough PR, @bradking.  Have you considered submitting this upstream to Vim?

**Comment by bradking** [comment]
> Have you considered submitting this upstream to Vim?

I tried back in 2016 and 2017 and after one round of initial feedback my post of the revised version got no response.

**Comment by jamessan** [comment]
> I tried back in 2016 and 2017 and after one round of initial feedback my post of the revised version got no response.

Yeah, this is typical.  It _is_ in Vim's [todo.txt](https://github.com/vim/vim/blob/a5d0077efbced85fcc63f203937b13efd55d036f/runtime/doc/todo.txt#L1455-L1456).  Might be worth prodding the thread again or turning the patch into a PR.

Just to be clear, getting it integrated upstream isn't a requirement, but for something this generic it would be nice to have it upstream.

**Comment by bradking** [comment]
I've opened upstream vim PR 6087 for this.

**Comment by bradking** [comment]
@jamessan shall I close this PR for now pending a decision in upstream vim?  We probably shouldn't merge it here in case names are bikeshedded over there.

**Comment by jamessan** [comment]
No, we can leave it open.  Let's see what happens with the Vim PR.  If there's no response to it, we'll probably just merge the changes here.  If Vim ends up merging later on, then we can consider what to do if there's any divergence.

**Comment by bradking** [comment]
The upstream vim PR for this was merged!  IIUC you have a [process](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) for merging upstream vim patches to neovim.  I'm happy to convert this PR to do that, but a direct contribution here will put the code under APLv2.  Which is preferred?  Is there some way I should reference the upstream vim patch number?

Also, the upstream PR was closed by a commit that made the main change but did not include the update to `runtime/syntax/vim.vim`.  I've opened vim/vim#6182 for the latter.

**Comment by jamessan** [comment]
>  Is there some way I should reference the upstream vim patch number?

Yeah, you can just amend your commit and add `vim-patch:8.2.0865` to the message.

> Also, the upstream PR was closed by a commit that made the main change but did not include the update to `runtime/syntax/vim.vim`.

That's because runtime files are maintained by many different people.  For example, the vim syntax file is maintained [by Charles Campbell](https://github.com/vim/vim/blob/ea6561af92eeb26fa0b4966575da7cadd98af1cd/runtime/syntax/vim.vim#L3).

Bram aggregates updates to the files and periodically commits the changes [in bulk](https://github.com/vim/vim/commit/388a5d4f20b4b64341d1604aa238cab85827b892).  Similarly, we periodically sync the changes from Vim.

It's probably best to just drop that commit from this PR.

**Comment by bradking** [comment]
@jamessan thanks.  I updated this PR to mention `vim-patch:8.2.0865` in the commit message and to drop the `runtime/syntax/vim.vim` part of the change.

**Comment by jamessan** [comment]
Bram made some additional changes that we should include.

* Centralized definition of "Illegal argument" error string as `e_illegal_arg`
* Added test to `test_syntax.vim`

We should incorporate these.  In particular, including the Vim test will simplify future merges.

It's up to you if you want to re-work this PR or [use vim-patch.sh](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim) to create a new PR.

**Comment by bradking** [comment]
Ah, I'd originally written the test in `test_syntax.vim` for upstream vim and then removed it when creating this PR since I'd ported the test to neovim's suite.  I'll add it back to `test_syntax.vim` so we have both and to simplify future merges.  I'll also update for the `e_illegal_arg` consolidation.

**Comment by jamessan** [comment]
>  I'll add it back to `test_syntax.vim` so we have both

I don't think we need it in both places.  That's just more we would need to update if they have to change.

**Comment by bradking** [comment]
@jamessan thanks. I updated this PR to apply the `e_illegal_arg` refactoring first, then apply `vim-patch:8.2.0865` with the upstream `test_syntax.vim` form of the test, and then add one more commit to remove the upstream test and replace it with a nvim-style test.  That way the upstream patch is faithfully preserved in nvim's history and a separate commit records the conversion of the test.

**Comment by jamessan** [comment]
> then add one more commit to remove the upstream test and replace it with a nvim-style test.

No need for that.  The upstream tests are fine.  We still get code coverage and it reduces overhead on managing future changes.

**Comment by bradking** [comment]
> The upstream tests are fine. We still get code coverage and it reduces overhead

Okay, I rewound the branch here to drop the test conversion commit.

**Comment by bradking** [comment]
I've rebased on current `master`.  The commits now act as an import of the upstream patch as `vim-patch:8.2.0865`, and use the upstream's test case.

**Comment by jamessan** [comment]
Thanks.  Will merge once CI completes.

**Comment by bradking** [comment]
@jamessan thanks.  CI is finished, though it looks like there are some unrelated failures.

**Comment by jamessan** [comment]
>  CI is finished, though it looks like there are some unrelated failures.

The OpenBSD one looks like an infrastructure issue, but I'm not sure what's going on with [Appveyor](https://ci.appveyor.com/project/neovim/neovim/builds/33688819/job/1aannik36xf6e6sq?fullLog=true).

Would you mind running `git commit --amend --no-edit` and then force pushing, so we get another CI run?

**Comment by bradking** [comment]
@jamessan I pushed the amended commit and CI is now happy except for the OpenBSD infrastructure problem.

**Comment by jamessan** [comment]
Thanks, @bradking!

**Comment by bradking** [comment]
@jamessan thanks for working through this with me and merging the change!

For reference, in the above discussion we decided to leave out my commit that converts the upstream vim test into a neovim-style test.  To preserve that change for future reference, I posted the commit in #12529 and immediately closed it.

**Pull request merged**
