### PR TITLE
eval: fix assertion failure in garbage collection

### LINKED ISSUE #12387: Crash: Assertion failed
Version:

NVIM v0.5.0-532-g2ca8f02a6

Error:

Assertion failed: (saved_copyID != copyID && saved_copyID != copyID - 1), function _typval_encode_nothing_convert_one_value, file ../src/nvim/eval/typval_encode.c.h, line 367.
 

Crash report:
```
Process:               nvim [3209]
Path:                  /usr/local/bin/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [2973]
Responsible:           iTerm2 [1393]
User ID:               501

Date/Time:             2020-05-27 14:05:16.565 -0400
OS Version:            Mac OS X 10.15.5 (19F96)
Report Version:        12
Bridge OS Version:     4.5 (17P5290)
Anonymous UUID:        2403CF6E-0822-407E-C09C-8393DB421D0C

Sleep/Wake UUID:       5BE2A97C-8AFA-46B4-BA3A-26D34E0780E8

Time Awake Since Boot: 9900 seconds
Time Since Wake:       9100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (saved_copyID != copyID && saved_copyID != copyID - 1), function _typval_encode_nothing_convert_one_value, file ../src/nvim/eval/typval_encode.c.h, line 367.
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff7212b33a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff721e7e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff720b2808 abort + 120
3   libsystem_c.dylib             	0x00007fff720b1ac6 __assert_rtn + 314
4   nvim                          	0x000000010c9c326e _typval_encode_nothing_convert_one_value + 1486
5   nvim                          	0x000000010c9c1ee8 encode_vim_to_nothing + 104
6   nvim                          	0x000000010c984ae9 vars_clear + 105
7   nvim                          	0x000000010c9cc7e0 free_unref_funccal + 144
8   nvim                          	0x000000010c97a35e garbage_collect + 6542
9   nvim                          	0x000000010cb1639c os_inchar + 332
10  nvim                          	0x000000010cbd3eb1 state_enter + 241
11  nvim                          	0x000000010ca813aa main + 14842
12  libdyld.dylib                 	0x00007fff71fe3cc9 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff72129766 kevent + 10
1   nvim                          	0x000000010c85b5a8 uv__io_poll + 920 (kqueue.c:214)
2   nvim                          	0x000000010c849da1 uv_run + 433 (core.c:376)
3   nvim                          	0x000000010c9ce4e9 loop_poll_events + 281
4   nvim                          	0x000000010cbfdb9d tui_main + 765
5   libsystem_pthread.dylib       	0x00007fff721e8109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff721e3b8b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000011c839dc0  rcx: 0x00007ffee33d36a8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee33d36d0  rsp: 0x00007ffee33d36a8
   r8: 0x000000000000016f   r9: 0xcccccccccccccccd  r10: 0x000000011c839dc0  r11: 0x0000000000000246
  r12: 0x0000000000000307  r13: 0x000000000c971000  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff7212b33a  rfl: 0x0000000000000246  cr2: 0x000000011054dd86
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x10c82b000 -        0x10ccdfff7 +nvim (0) <DD642D58-6D7A-3B35-AB53-3E59C07B10DD> /usr/local/bin/nvim
       0x10ce8a000 -        0x10ce93fff +libintl.8.dylib (0) <65B896DF-857E-3C34-ABA1-8B7B45DB34F8> /usr/local/opt/gettext/lib/libintl.8.dylib
       0x11c76f000 -        0x11c800eff  dyld (750.5) <26346F4C-B18E-31A1-9964-30736214F1BF> /usr/lib/dyld
    0x7fff37f65000 -     0x7fff383e4ffb  com.apple.CoreFoundation (6.9 - 1676.105) <6AF8B3CC-BC3F-3869-B9FB-1D881422364E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff6eaf3000 -     0x7fff6eaf5ff7  libDiagnosticMessagesClient.dylib (112) <27220E98-6CE2-33E3-BD48-3CC3CE4AA036> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6efc9000 -     0x7fff6efcafff  libSystem.B.dylib (1281.100.1) <DC04B185-E3C9-33AF-B450-EF3ED07FB021> /usr/lib/libSystem.B.dylib
    0x7fff6f2af000 -     0x7fff6f301fff  libc++.1.dylib (902.1) <AD0805FE-F98B-3E2F-B072-83782B22DAC9> /usr/lib/libc++.1.dylib
    0x7fff6f302000 -     0x7fff6f317ffb  libc++abi.dylib (902) <771E9263-E832-3985-9477-8F1B2D73B771> /usr/lib/libc++abi.dylib
    0x7fff6f318000 -     0x7fff6f318fff  libcharset.1.dylib (59) <FF23D4ED-A5AD-3592-9574-48486C7DF85B> /usr/lib/libcharset.1.dylib
    0x7fff6fd81000 -     0x7fff6fd83fff  libfakelink.dylib (149.1) <122F530F-F10E-3DD5-BBEA-91796BE583F3> /usr/lib/libfakelink.dylib
    0x7fff6fda2000 -     0x7fff6fe92fff  libiconv.2.dylib (59) <F58FED71-6CCA-30E8-9A51-13E9B46E568D> /usr/lib/libiconv.2.dylib
    0x7fff6fe93000 -     0x7fff700eafff  libicucore.A.dylib (64260.0.1) <7B9204AC-EA14-3FF3-B6B9-4C85B37EED79> /usr/lib/libicucore.A.dylib
    0x7fff70e29000 -     0x7fff70e5cfde  libobjc.A.dylib (787.1) <CA836D3E-4595-33F1-B70C-7E39A3FBBE16> /usr/lib/libobjc.A.dylib
    0x7fff713df000 -     0x7fff713e2ffb  libutil.dylib (57) <D33B63D2-ADC2-38BD-B8F2-24056C41E07B> /usr/lib/libutil.dylib
    0x7fff71505000 -     0x7fff71517ff3  libz.1.dylib (76) <DB120508-3BED-37A8-B439-5235EAB4618A> /usr/lib/libz.1.dylib
    0x7fff71dc5000 -     0x7fff71dcaff3  libcache.dylib (83) <A5ECC751-A681-30D8-B33C-D192C15D25C8> /usr/lib/system/libcache.dylib
    0x7fff71dcb000 -     0x7fff71dd6fff  libcommonCrypto.dylib (60165.120.1) <C321A74A-AA91-3785-BEBF-BEDC6975026C> /usr/lib/system/libcommonCrypto.dylib
    0x7fff71dd7000 -     0x7fff71ddefff  libcompiler_rt.dylib (101.2) <652A6012-7E5C-3F4F-9438-86BC094526F3> /usr/lib/system/libcompiler_rt.dylib
    0x7fff71ddf000 -     0x7fff71de8ff7  libcopyfile.dylib (166.40.1) <40113A69-A81C-3397-ADC6-1D16B9A22C3E> /usr/lib/system/libcopyfile.dylib
    0x7fff71de9000 -     0x7fff71e7bfe3  libcorecrypto.dylib (866.120.3) <5E4B0E50-24DD-3E04-9374-EDA9FFD6257B> /usr/lib/system/libcorecrypto.dylib
    0x7fff71f88000 -     0x7fff71fc8ff0  libdispatch.dylib (1173.100.2) <201EDBF3-0B36-31BA-A7CB-443CE35C05D4> /usr/lib/system/libdispatch.dylib
    0x7fff71fc9000 -     0x7fff71ffffff  libdyld.dylib (750.5) <7E711A46-5E4D-393C-AEA6-440E2A5CCD0C> /usr/lib/system/libdyld.dylib
    0x7fff72000000 -     0x7fff72000ffb  libkeymgr.dylib (30) <52662CAA-DB1F-30A3-BE13-D6274B1A6D7B> /usr/lib/system/libkeymgr.dylib
    0x7fff7200e000 -     0x7fff7200eff7  liblaunch.dylib (1738.120.8) <07CF647B-F9DC-3907-AD98-2F85FCB34A72> /usr/lib/system/liblaunch.dylib
    0x7fff7200f000 -     0x7fff72014ff7  libmacho.dylib (959.0.1) <D91DFF00-E22F-3796-8A1C-4C1F5F8FA03C> /usr/lib/system/libmacho.dylib
    0x7fff72015000 -     0x7fff72017ff3  libquarantine.dylib (110.40.3) <D3B7D02C-7646-3FB4-8529-B36DCC2419EA> /usr/lib/system/libquarantine.dylib
    0x7fff72018000 -     0x7fff72019ff7  libremovefile.dylib (48) <B5E88D9B-C2BE-3496-BBB2-C996317E18A3> /usr/lib/system/libremovefile.dylib
    0x7fff7201a000 -     0x7fff72031ff3  libsystem_asl.dylib (377.60.2) <1170348D-2491-33F1-AA79-E2A05B4A287C> /usr/lib/system/libsystem_asl.dylib
    0x7fff72032000 -     0x7fff72032ff7  libsystem_blocks.dylib (74) <7AFBCAA6-81BE-36C3-8DB0-AAE0A4ACE4C5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff72033000 -     0x7fff720bafff  libsystem_c.dylib (1353.100.2) <935DDCE9-4ED0-3F79-A05A-A123DDE399CC> /usr/lib/system/libsystem_c.dylib
    0x7fff720bb000 -     0x7fff720beffb  libsystem_configuration.dylib (1061.120.2) <EA9BC2B1-5001-3463-9FAF-39FF61CAC87C> /usr/lib/system/libsystem_configuration.dylib
    0x7fff720bf000 -     0x7fff720c2fff  libsystem_coreservices.dylib (114) <3D0A3AA8-8415-37B2-AAE3-66C03BCE8B55> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff720c3000 -     0x7fff720cbfff  libsystem_darwin.dylib (1353.100.2) <6EEC9975-EE3B-3C95-AA5B-030FD10587BC> /usr/lib/system/libsystem_darwin.dylib
    0x7fff720cc000 -     0x7fff720d3fff  libsystem_dnssd.dylib (1096.100.3) <0115092A-E61B-317D-8670-41C7C34B1A82> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff720d4000 -     0x7fff720d5ffb  libsystem_featureflags.dylib (17) <AFDB5095-0472-34AC-BA7E-497921BF030A> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff720d6000 -     0x7fff72123ff7  libsystem_info.dylib (538) <851693E9-C079-3547-AD41-353F8C248BE8> /usr/lib/system/libsystem_info.dylib
    0x7fff72124000 -     0x7fff72150ff7  libsystem_kernel.dylib (6153.121.1) <84D09AE3-2DA8-3F6D-ACEC-DC4990B1A2FF> /usr/lib/system/libsystem_kernel.dylib
    0x7fff72151000 -     0x7fff72198fff  libsystem_m.dylib (3178) <436CFF76-6A99-36F2-A3B6-8D017396A050> /usr/lib/system/libsystem_m.dylib
    0x7fff72199000 -     0x7fff721c0fff  libsystem_malloc.dylib (283.100.6) <D4BA7DF2-57AC-33B0-B948-A688EE43C799> /usr/lib/system/libsystem_malloc.dylib
    0x7fff721c1000 -     0x7fff721ceffb  libsystem_networkextension.dylib (1095.120.6) <6DE86DB0-8CD2-361E-BD6A-A34282B47847> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff721cf000 -     0x7fff721d8ff7  libsystem_notify.dylib (241.100.2) <7E9E2FC8-DF26-340C-B196-B81B11850C46> /usr/lib/system/libsystem_notify.dylib
    0x7fff721d9000 -     0x7fff721e1fef  libsystem_platform.dylib (220.100.1) <736920EA-6AE0-3B1B-BBDA-7DCDF0C229DF> /usr/lib/system/libsystem_platform.dylib
    0x7fff721e2000 -     0x7fff721ecfff  libsystem_pthread.dylib (416.100.3) <77488669-19A3-3993-AD65-CA5377E2475A> /usr/lib/system/libsystem_pthread.dylib
    0x7fff721ed000 -     0x7fff721f1ff3  libsystem_sandbox.dylib (1217.120.7) <20C93D69-6452-3C82-9521-8AE54345C66F> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff721f2000 -     0x7fff721f4fff  libsystem_secinit.dylib (62.100.2) <E851113D-D5B1-3FB0-9D29-9C7647A71961> /usr/lib/system/libsystem_secinit.dylib
    0x7fff721f5000 -     0x7fff721fcffb  libsystem_symptoms.dylib (1238.120.1) <25C3866B-004E-3621-9CD3-B1E9C4D887EB> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff721fd000 -     0x7fff72213ff2  libsystem_trace.dylib (1147.120) <A1ED1D3A-5FAD-3559-A1D6-1BE4E1C5756A> /usr/lib/system/libsystem_trace.dylib
    0x7fff72215000 -     0x7fff7221aff7  libunwind.dylib (35.4) <253A12E2-F88F-3838-A666-C5306F833CB8> /usr/lib/system/libunwind.dylib
    0x7fff7221b000 -     0x7fff72250ffe  libxpc.dylib (1738.120.8) <68D433B6-DCFF-385D-8620-F847FB7D4A5A> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 9
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7370
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=407.0M resident=0K(0%) swapped_out_or_unallocated=407.0M(100%)
Writable regions: Total=116.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=116.3M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                            98.9M      108 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        2 
Stack                             16.0M        2 
VM_ALLOCATE                        964K        9 
__DATA                            2371K       51 
__DATA_CONST                        24K        2 
__LINKEDIT                       389.7M        4 
__OBJC_RO                         32.2M        1 
__OBJC_RW                         1892K        2 
__TEXT                            17.3M       49 
__UNICODE                          564K        1 
shared memory                       12K        3 
===========                     =======  ======= 
TOTAL                            616.1M      240 
```

### PR DESCRIPTION
**Pull request by erw7**
fixes #12387, #12430

Lists with `CopyID+1` linked only from `previous_funccal` may be removed in the garbage collection. Therefore, the terms of the assertions are not correct. This can be confirmed by the following (The `l:x` with `CopyID+1` of the first function call needs to be removed by garbage collection):

```vim
func! s:f()
  let l:x = [1]
  let g:x = l:
endfunc

for _ in range(2)
  call s:f()
endfor
call garbagecollect()
```

### CODE REVIEW

**Comment by tjdevries** [comment]
Awesome work tracking this down!

Do you want to add a test somewhere for this:

```
nvim -u NORC
:func! Test()
:  let l:x = [1]
:  let g:x = l:
:endfunc
:call Test()
:call Test()
:call garbagecollect()
```

That you posted in the issue?

**Comment by erw7** [comment]
> Do you want to add a test somewhere for this:

I added the test to `eval/let_spec.lua`. Please let me know if there is anything more appropriate.

> That you posted in the issue?

https://github.com/neovim/neovim/issues/12430#issuecomment-638822533

**Review by tjdevries — APPROVED** [review]
LGTM, although I'm not sure why the assert was there before (just pinging @teto to check this as well to make sure it's fine). Since all other tests pass, I'm assuming it was just a spurious assert.

**Comment by erw7** [comment]
> @erw7 do you have a preferred way to be contacted ? could you lurk on the https://gitter.im/neovim/neovim this week ?

Email is best. I don't see https://gitter.im/neovim/neovim much.

**Comment by erw7** [comment]
> LGTM, although I'm not sure why the assert was there before (just pinging @teto to check this as well to make sure it's fine). Since all other tests pass, I'm assuming it was just a spurious assert.

Unlike vim, neovim seems to use `copyID` to manage self-references. This may be the assert needed to do so. We might want to check with @ZyX-I.

**Comment by teto** [comment]
@erw7 I don't know your mail, could you drop it on gitter via PM ? it would be great if @justinmk  could comment on this since git blame refers to that PR. The PR is probably fine but I want to ook into some more.

**Comment by tjdevries** [comment]
Check with core, this seems fine to merge. Thanks again @erw7

**Pull request merged**
