### PR TITLE
feat(iter): add reduce

### LINKED ISSUE #23251: vim.iter: pass more state to callback functions
### Problem

For callbacks of functions like `Iter:find()`, `Iter:filter()`, (~~future?: `Iter:reduce()`~~  `Iter:fold()`), it's useful to know

1. the "previous" element
2. the result of the previous callback

This allows the callback to compare / reason about observed elements and results.

### Expected behavior

Using [javascript's reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#parameters) as inspiration, we could pass these args:

- `i`: current index
- `prev_val`: previous value (maybe not needed because of `i` ?)
- `result` (or `accum`?): Result of the previous callback. On first call, `initial_val` if specified, otherwise the first value of the iterator (`iter[1]`).

### PR DESCRIPTION
**Pull request by glepnir**
Fix #23251

### CODE REVIEW

**Comment by gpanders** [comment]
We already have `:fold()`, `:reduce()` is redundant.

_If_ we need to make any changes, those should be done to `:fold()`. But for what it's worth I agree with @lewis6991's [comment](https://github.com/neovim/neovim/issues/23251#issuecomment-1517989094).

**Comment by glepnir** [comment]
reimplement like scala reduce ?

**Comment by gpanders** [comment]
>reimplement like scala reduce ?

No. Scala's [reduce](https://www.scala-lang.org/api/2.13.3/scala/collection/immutable/List.html#reduce[B%3E:A](op:(B,B)=%3EB):B) is less flexible than ours. We accept any function with any accumulator value. Scala uses only a binary operator.

An "accumulator" value and the current value of the iterator is all that is needed to implement a fold/reduce function. We already support this.

Re #23251:

> For callbacks of functions like Iter:find(), Iter:filter(), (future?: Iter:reduce()), it's useful to know
> 
> - the "previous" element
> - the result of the previous callback

Can this not already be achieved with the API that we have? I don't want to pass a bunch of state to every stage of the iterator pipeline if it's not needed. It complicates the API and makes things more cumbersome/verbose/confusing. Instead if these things are needed the iterator itself should be able to support it.

> Using [javascript's reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#parameters) as inspiration, we could pass these args:
> 
> * `i`: current index
> * `prev_val`: previous value (maybe not needed because of i ?)
> * `result` (or accum?): Result of the previous callback. On first call, initial_val if specified, otherwise the first value of the iterator (iter[1]).

We already support this:

- Current index can be injected into the iterator pipeline with `:enumerate()`
- `prev_val` and `result` are already supported by `:fold()`. The "accumulator" in `fold` can be _anything_, including a state table:

  ```lua
  local t = vim.iter({ 1, 2, 3, 4, 5 }):fold({}, function(acc, v)
    local last = acc.last
    acc.last = v
    if not acc.result then
      acc.result = 0
    end
    acc.result = acc.result + last + v
  end)
  vim.print(t.result)
  -- 25
  ```

**Comment by justinmk** [comment]
Also `:help Iter:fold()` specifically mentions "reduce" as a synonym so that users can find it. It may be worth adding an extra help tag like `iter-reduce`.

**Pull request closed without merging**
