### PR TITLE
TermEnter, TermLeave autocommands

### PR DESCRIPTION
**Pull request by usama54321**
Partial work on #8428 by adding autocommands for TermEnter and TermLeave events.

### CODE REVIEW

**Comment by justinmk** [comment]
can you write some tests? https://github.com/neovim/neovim/blob/master/test/README.md#guidelines-for-writing-tests

**Comment by usama54321** [comment]
I've added some basic tests. Since the autocmds, are really specific, I could not think of any other tests

**Comment by janlazo** [comment]
Any vim patches related to these events?

**Comment by jamessan** [comment]
The only `:term` related event that Vim has is `TerminalOpen`.

**Comment by janlazo** [comment]
Vim doesn't have a use-case for `TerminalLeave` or is it covered by other autocmd?

**Comment by chrisbra** [comment]
> Vim doesn't have a use-case for TerminalLeave or is it covered by other autocmd?

I guess nobody has yet brought up a good use case yet.

**Comment by justinmk** [comment]
- Missing docs. I wrote some.
- Enhanced the tests.
`TermLeave` happens _after_ `TermClose`, which is weird. But doesn't need to block this.

**Pull request merged**
