### PR TITLE
feat(tui): remove vtpcon

### LINKED ISSUE #20666: TUI: remove vtpcon (Windows 8)
### Feature already in Vim?

_No response_

### Feature description

suggested by @erw7 in https://github.com/neovim/neovim/pull/20634#issuecomment-1279701733 : 

> `vtpcon` has lost its usefulness because of the implementation of many features of `xterm` in `conpty`. In addition, Windows 8.1 will be EOL on 1/10/2023. Therefore, `windows.ti` and all changes related to it should be removed in 0.9.

### PR DESCRIPTION
**Pull request by lsvmello**
Resolves #20666.

Windows 8.1 is EOL, therefore vtpcon is not needed anymore.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Should win32con also be removed?

**Comment by lsvmello** [comment]
> Should win32con also be removed?

According to [this](https://learn.microsoft.com/en-us/windows/console/legacymode) Windows 10 still supports legacy mode and EOL of Windows 10 is [October 14, 2025](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-22h2-end-of-support-update).

**Review by justinmk — APPROVED** [review]

**Comment by zeertzjq** [comment]
Oops, pushed to wrong remote :(

**Review by zeertzjq — CHANGES_REQUESTED** [review]
This doesn't look correct. With `builtin_vtpcon` removed it now falls back to `builtin_ansi` inside PowerShell, which is much worse.

**Comment by justinmk** [comment]
> This doesn't look correct. With `builtin_vtpcon` removed it now falls back to `builtin_ansi` inside PowerShell, which is much worse.

Can reopen the PR if the author addresses this.

**Pull request closed without merging**
