### PR TITLE
Implement `vim.img.protocol()` to detect preferred graphics protocol

### PR DESCRIPTION
**Pull request by chipsenkbeil**
Implements `vim.img.protocol()` that can be used to detect the preferred graphics protocol.

This is a reverse-engineered copy of how `timg` implements graphics protocol support, and relies on a couple of terminal queries, hence we implement `vim.img._terminal.query()` and `vim.img._terminal.graphics.detect()` to support figuring out if the terminal supports iterm2, kitty, or sixel protocols and mirrors the logic from `timg`.

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/neovim/neovim/pull/31398).
* __->__ #31398
* #31397
* #31396
* #31395
* #31394
* #31393
* #31392

### CODE REVIEW

**Comment by clason** [comment]
That is a metric butt ton of parallel PRs.  Is that strictly necessary?

**Comment by chipsenkbeil** [comment]
> That is a metric butt ton of parallel PRs. Is that strictly necessary?

This was meant to go to my fork, not neovim itself. Is there a way to delete these? Just close all of them out?

**Comment by dundargoc** [comment]
This looks like an excellent tool for annoying people. Thanks for the recommendation.

**Comment by clason** [comment]
Oh god what have you wrought?!

**Pull request closed without merging**
