### PR TITLE
runtime: backport IPv6 support to resolv.vim

### PR DESCRIPTION
**Pull request by paper42**
from commits bc93cebb692f47488d66f078d1728031e9be35e7 and
b17893aa940dc7d45421f875f5d90855880aad27 from vim

### CODE REVIEW

**Comment by bfredl** [comment]
Question: would these changes also make sense for https://github.com/vim/vim  `runtime/syntax/resolv.vim` ? We try to avoid forking runtime files when not needed.

**Comment by bfredl** [comment]
(alternatively if these changes are already in vim/vim, reference the vim commit in the commit message here)

**Comment by PaperMountainStudio** [comment]
These changes are "backported" (not sure if this is the best word) from vim, so I referenced the commits as you suggested, thanks. @bfredl

**Comment by bfredl** [comment]
ok, if there is no other earlier changes to this very file, this is probably good to go.

**Comment by PaperMountainStudio** [comment]
Yes, no earlier changes since 2016.

**Comment by bfredl** [comment]
failures look unrelated, let's try again.

**Comment by janlazo** [comment]
All good?

**Comment by PaperMountainStudio** [comment]
> It would be easier to review if each commit matches the file change from only 1 Vim commit hash.
@janlazo I can do it if you want, but you can also copy the file from vim's master and diff it with this PR.

**Comment by janlazo** [comment]
@PaperMountainStudio It's fine. I compared the combined diff from Vim with your changes. They look the same.

**Pull request merged**
