### PR TITLE
[RFC] vim-patch: Mark patches as NA.

### PR DESCRIPTION
**Pull request by fwalch**
- https://code.google.com/p/vim/source/detail?r=v7-4-589 only modifies removed `os_win32.c`
- https://code.google.com/p/vim/source/detail?r=v7-4-586 modifies Makefile
- https://code.google.com/p/vim/source/detail?r=v7-4-584 modifies a test to source `small.vim`
- https://code.google.com/p/vim/source/detail?r=v7-4-583 modifies a test to source `small.vim`
- https://code.google.com/p/vim/source/detail?r=v7-4-571 modifies an `ifdef` for tiny features
- https://code.google.com/p/vim/source/detail?r=v7-4-570 modifies removed `if_ruby.c`

### CODE REVIEW

**Comment by Hinidu** [comment]
Yesterday I found that https://code.google.com/p/vim/source/detail?r=v7-4-451 is also NA because it looks like `system()` rewritten by @aktau doesn't have bug fixed in that patch.

**Comment by fwalch** [comment]
> Yesterday I found that https://code.google.com/p/vim/source/detail?r=v7-4-451 is also NA because it looks like system() rewritten by @aktau doesn't have bug fixed in that patch.

:+1: Tried with `:call system('ls', '')`, which triggers an error with Vim 7.4.373, but doesn't in current Neovim and Vim 7.4.580.

**Comment by aktau** [comment]
Indeed, `system()` never uses tempfiles in the Neovim implementation, only pipes.

**Comment by justinmk** [comment]
LGTM, thanks!

**Pull request merged**
