### PR TITLE
vim-patch:8.1.{86,347}

### PR DESCRIPTION
**Pull request by janlazo**

### CODE REVIEW

**Comment by blueyed** [comment]
ASAN build has memory related errors: https://travis-ci.org/neovim/neovim/jobs/548455397

**Comment by janlazo** [comment]
```
Failed: F /tests/oldtests|test_alot :: Nvim exited with non-zero code
=================================================================
==31110==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 148 byte(s) in 2 object(s) allocated from:
    #0 0x50ac78 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x50ac78)
    #1 0x1e0b609 in uv__strdup /home/travis/nvim-deps/build/src/libuv/src/uv-common.c:57
```
Would upgrading libuv it?

**Comment by blueyed** [comment]
We're using the latest: https://github.com/blueyed/neovim/blob/101128d461508818f53a4c3cfb2ca5fc72a71613/third-party/CMakeLists.txt#L131

**Comment by blueyed** [comment]
Might be flaky(?) - so a restart might fix it, but better to pastebin the log then, or just wait for somebody to investigate into it.

**Comment by janlazo** [comment]
Maybe 8.1.0846 will  resolve it

**Comment by erw7** [comment]
If `dlopen()` fails, `uv__dlerror()` is called in the [this part](https://github.com/libuv/libuv/blob/0b29acb0cab7baeb6af77aa9ae259b4c6ebf000a/src/unix/dl.c#L37) of `uv_dlopen()`. Memory is allocated [here](https://github.com/libuv/libuv/blob/0b29acb0cab7baeb6af77aa9ae259b4c6ebf000a/src/unix/dl.c#L73) in `uv__dlerror()`. Therefore, even if `uv_dlopen()` fails, it is necessary to call `uv_dlclose()`. I think it will be fixed in the next patch.

```diff
diff --git a/src/nvim/os/dl.c b/src/nvim/os/dl.c
index bbd0424a8..f0fadb16f 100644
--- a/src/nvim/os/dl.c
+++ b/src/nvim/os/dl.c
@@ -54,6 +54,7 @@ bool os_libcall(const char *libname,
   // open the dynamic loadable library
   if (uv_dlopen(libname, &lib)) {
       EMSG2(_("dlerror = \"%s\""), uv_dlerror(&lib));
+      uv_dlclose(&lib);
       return false;
   }
```

**Comment by janlazo** [comment]
@erw7 It works. Thanks for the help.

**Pull request merged**
