### PR TITLE
[WIP] test,win: test,win: adjust test when using ConPTY

### PR DESCRIPTION
**Pull request by erw7**

### CODE REVIEW

**Comment by janlazo** [comment]
Can we merge the feature check for now and disable the terminal tests in the CI environment on Windows builds? Wondering is `has('conpty')` is enough to check for 24-bit color support in Vim plugins such as fzf.

https://github.com/junegunn/fzf.vim/issues/1152#issuecomment-720284500

**Comment by erw7** [comment]
ConPTY varies in completeness depending on the version of Windows. So I don't know if the test that passes in my environment will pass in all environments. All tests that do not pass in CI have been changed to pending.

> Can we merge the feature check for now and disable the terminal tests in the CI environment on Windows builds?

Do you mean to merge without including https://github.com/neovim/neovim/pull/13177/commits/1fca028534463c70869770af874ce2412377bcaf? I think it's safe to merge regardless of https://github.com/neovim/neovim/pull/13177/commits/1fca028534463c70869770af874ce2412377bcaf. But functional/ex_cmds/mksession_spec.lua, which is not supposed to be related to this change, does not pass.

**Comment by erw7** [comment]
> Wondering is `has('conpty')` is enough to check for 24-bit color support in Vim plugins such as fzf.

I think so. However, in the case of vim, you need to be careful. The `has('conpty')` will not return true until the first successful terminal execution by ConPTY.

```vim
vim -Nu NORC
:set termwintype=conpty
:echo has('conpty')
0
:terminal
<C-\><C-n>
:echo has('conpty')
1
```

**Comment by janlazo** [comment]
Isn't that a bug? Why is `has('conpty')` affected by `termwintype`?

**Comment by erw7** [comment]
> Isn't that a bug? Why is `has('conpty')` affected by `termwintype`?

I checked again. The `termwintype` has no effect on `has('conpty')`. However, `has('compty')` does not return true until you run the terminal once in the vim.

> Wondering is `has('conpty')` is enough to check for 24-bit color support in Vim plugins such as fzf.

In the vim, the conditions for 24-bit color are `&termwintype == 'conpty' && has('conpty')`. However, it seems that in the future (when the `conpty` is deemed stable) they will change to use `conpty` even if `termwintype` is empty.

**Comment by Sebastian-byte** [comment]
I really need this 😅

**Comment by justinmk** [comment]
is this still needed? CI is passing; is that because we temporarily disabled the relevant tests?

**Comment by erw7** [comment]
> is this still needed? CI is passing; is that because we temporarily disabled the relevant tests?

Yes. The current CI will pass because the OS is Windows Server 2016 (It does not have a `conpty`, so testing has been done using `winpty` as before).

**Comment by clason** [comment]
There _are_ newer runners, fwiw: Windows Server 2019 and 2022 (beta). Might be worth upgrading if we can then simplify the tests?

**Comment by erw7** [comment]
> Might be worth upgrading if we can then simplify the tests?

This fixes a failure in a test with a `conpty` that is not currently being tested. Therefore, unfortunately, I don't think it will simplify the test. CI started to fail due to a problem with the MSYS2/MinGW package, so we tried to use a new runner and discovered the problem with testing with `conpty`. Since then, the package issue has been resolved without using the new runner, so this has become a lower priority, but it will need to be fixed eventually.

**Pull request closed without merging**
