### PR TITLE
[RFC] build: patch msgpack to work on FreeBSD until a proper fix is upstream

### PR DESCRIPTION
**Pull request by jszakmeister**
I'm generally not into patching sources and prefer to have things fixed upstream, but it seems like msgpack is kind of lagging a bit.  So, I think it's probably a good idea to patch msgpack for the time being.

### CODE REVIEW

**Comment by Pyrohh** [comment]
Would you mind adding the OpenBSD line as well (from https://github.com/msgpack/msgpack-c/pull/221)?

**Comment by jszakmeister** [comment]
Sure thing.  I didn't think we had anyone on OpenBSD using Neovim yet.  I'll re-roll it soon.

**Comment by Pyrohh** [comment]
Maybe I should open up a different issue, but on OpenBSD I can build msgpack-c separately with this patch, but neovim still can't (I get the same error on your branch and master). I'm not sure if you've encountered this, but I get the error `make: don't know how to make sw`.

**Comment by jszakmeister** [comment]
Do you have more of the log output you can show?  I wonder if it's a BSD make vs. gmake issue.

**Comment by Pyrohh** [comment]
Here's the whole log, the error is near to the bottom: https://gist.github.com/anonymous/89d9b7f3571eff1f5a3b

**Comment by Pyrohh** [comment]
If it's of any help, here's the notes I took while getting it to build:
```
'automake-1.15' & 'libtool' are for libuv

  # pkg_add gmake cmake automake-1.15 libtool
  $ export AUTOCONF_VERSION=2.69
  $ export AUTOMAKE_VERSION=1.15
  $ gmake
```

**Comment by jszakmeister** [comment]
@Pyrohh I made it far enough to discover that there's some make-related issues here.  It looks like BSD make is being invoked over GNU make to do the msgpack build.  There's some environment variables being forced in that appear to be affecting things.  You can sidestep the issue by installing Ninja (`pkg_add ninja`) and it will use Ninja to build msgpack instead.

You will also need to install unzip (`pkg_add unzip`) so that luarocks can unpack a rock, but luarocks ultimately fails installing the neovim client.  I'm not sure why though, and I hope you can carry it forward and help figure it out (I've never used OpenBSD before this morning, so I figure it best to leave it in more capable hands).

All of that said, the patch introduced in this PR does work as intended.

**Comment by Pyrohh** [comment]
Thanks for the advice, I'll be sure to try that.

**Comment by jszakmeister** [comment]
The fix is upstream now.  Closing in favor of #2022.

**Pull request closed without merging**
