### PR TITLE
terminal: TextChangedT (or TermOutput)

### PR DESCRIPTION
**Pull request by Shougo**
I have added `TextChangedT` autocmd.

It is useful to complete automatically in terminal window.

スクリーンショット_2022-10-11_09-07-58

`ddc.vim` + `pum.vim` terminal auto completion in `deol.nvim`.

### CODE REVIEW

**Comment by jamilraichouni** [comment]
Great to see that! Would be really awesome to have completion (e. g. snippets) in shells like zsh, Python, IPython and many more!

**Comment by Shougo** [comment]
Note: It conflicts with shell auto completion.

**Comment by Shougo** [comment]
I have added the screenshot.

**Comment by justinmk** [comment]
- Looks like this is analogous to `TexChanged`/`TexChangedI`, so perhaps it should be named `TexChangedT` ?  https://github.com/neovim/neovim/issues/5018 (for reference: `TermChanged` is a legacy event name.)
- See also https://github.com/neovim/neovim/pull/5134 , which made some effort to pass along the changed text.
- Also or instead, we could support adding handlers to the terminal job: https://github.com/neovim/neovim/issues/5023

**Comment by Shougo** [comment]
> Looks like this is analogous to TexChanged/TexChangedI, could be named TexChangedT ?

OK.

**Comment by Shougo** [comment]
> Also or instead, we could support adding handlers to the terminal job: https://github.com/neovim/neovim/issues/5023

It may be better.  But it is not implemented for a long time yet.

**Comment by Shougo** [comment]
> See also https://github.com/neovim/neovim/pull/5134 , which made some effort to pass along the changed text.

I have tested it but it seems broken like this.

```
[1]    12256 IOT instruction (core dumped)  ~/src/neovim/build/bin/nvim
```

**Comment by Shougo** [comment]
Renamed.

**Comment by justinmk** [comment]
Not sure if you saw my (quick) edit to https://github.com/neovim/neovim/pull/20567#issuecomment-1273945712 , but I'm thinking that a `TermFoo` event name is probably better. The name is not the main challenge here though :) I think for this event to be very useful, we'd want to pass along the region (rows/columns) that contains the changed text, in `v:event`.

**Comment by Shougo** [comment]
I think `TextChangedT` is better...

> I think for this event to be very useful, we'd want to pass along the region (rows/columns) that contains the changed text, in v:event.

Well, it is hard to detect the difference...
And other TextChanged events does not have the feature.

**Comment by justinmk** [comment]
> And other TextChanged events does not have the feature.

The `']` and `'[` marks are set. That is what we want for :terminal also.

> Well, it is hard to detect the difference...

Why? `terminal.c:refresh_screen()` looks like it could make a pretty reasonable guess.

**Comment by Shougo** [comment]
Well, I have confused by the two statements.

> Looks like this is analogous to TexChanged/TexChangedI, could be named TexChangedT ?

> TermFoo is probably the right choice, because:

**Comment by Shougo** [comment]
> Why? terminal.c:refresh_screen() looks like it could make a pretty reasonable guess.

Well, I have tested the function.  But it is not called when I input texts to terminal buffer.

**Comment by justinmk** [comment]
> > Looks like this is analogous to TexChanged/TexChangedI, could be named TexChangedT ?
> 
> > TermFoo is probably the right choice, because:

"Could" was only a suggestion, for reference :) 
"Probably the right choice" was intended as a stronger signal.

**Comment by Shougo** [comment]
Oh, it is hard to get the nuance for me.

I have seen your comment, I think the first sentence is important.

**Comment by justinmk** [comment]
> Well, I have tested the function. But it is not called when I input texts to terminal buffer.

Input is different. Is this event emitted for screen change, or user input? 2 different events.

**Comment by Shougo** [comment]
> Input is different. Is this event emitted for screen change, or user input? 2 different events.

The event is for screen change, but to input texts causes the screen changes.

**Comment by jamilraichouni** [comment]
> I have added the screenshot.

So this means it'll be handy/ needed to be able to toggle (enable/ disable) the even via some keymap when it is bound to a completion engine with popup menu etc.

**Comment by Shougo** [comment]
Yes.  You need define the maps.

**Comment by Shougo** [comment]
I have ported the patch to Vim.

**Pull request closed without merging**
