### PR TITLE
[RDY] api: {get,set}_option should {get,set} global value for local options

### PR DESCRIPTION
**Pull request by yagebu**
- [x] make get_option return global value for local options
- [x] make set_option allow setting global value for local options

### CODE REVIEW

**Comment by justinmk** [comment]
:+1:

**Comment by yagebu** [comment]
Since `set_option` (via `set_option_to`) calls `get_option_value_strict` to determine what kind of option it is `set_option` works as intended too with only the first commit.

**Comment by justinmk** [comment]
LGTM! Is this ready?

**Comment by yagebu** [comment]
Yes.

**Comment by justinmk** [comment]
Thanks a lot. Before this those functions were basically useless :)

**Pull request merged**
