### PR TITLE
[RFC] Update R runtime files

### PR DESCRIPTION
**Pull request by jalvesaq**
indent/r.vim      : change shiftwidth to 2 and minor bug fixes.
indent/rhelp.vim  : move the position of the test if the script was already sourced
indent/rmd.vim    : minor bug fix
indent/rnoweb.vim : minor bug fix
syntax/r.vim      : minor bug fixes and improvement (distinguish = from ==)

### CODE REVIEW

**Comment by justinmk** [comment]
Since you're the maintainer, LGTM.

**Comment by jalvesaq** [comment]
Yes, I am. The syntax/r.vim is already in Vim, and the changes in the indent files will be updated the next time that Bram updates the runtime files.

**Comment by Pyrohh** [comment]
> Since you're the maintainer, LGTM.

Yes indeed, LGTM.

**Comment by fwalch** [comment]
Thanks @jalvesaq!

**Pull request merged**
