### PR TITLE
[RFC] vim-patch:7.4.1606

### PR DESCRIPTION
**Pull request by munyari**
Problem:    Having type() handle a Funcref that is or isn't a partial
            differently causes problems for existing scripts.
Solution:   Make type() return the same value. (Thinca)

https://github.com/vim/vim/commit/953cc7fb139dc2ba8590f8b03a095b63f4e1208f

### CODE REVIEW

**Comment by justinmk** [comment]
There are some earlier patches which added support for "partials", so this won't build until those get merged.

**Comment by munyari** [comment]
@justinmk anything I could do to help with those patches?

**Comment by Shougo** [comment]
@munyari OK.

1577, 1580, 1581, 1582, 1585, 1586, 1589, 1590, 1608, 1638, 1639, 1644, 1645.
How!, It is very huge patches like package feature!

**Comment by jamessan** [comment]
Merging of the partials feature is being tracked by #5065.  Closing this, since the whole patch set needs to be integrated.

**Pull request closed without merging**
