### PR TITLE
[RFC] CONTRIBUTING: Mention the wiki's troubleshooting & FAQ articles

### PR DESCRIPTION
**Pull request by ghost**
We have the pages, so we might as well use them :smile:

I'm seeing a lot of trivial issues recently that could be avoided if we mention this.

### CODE REVIEW

**Comment by dougblack** [comment]
Looks good to me.

**Comment by Pyrohh** [comment]
@fwalch can you take a peek at this?

**Comment by fwalch** [comment]
LGTM :+1:

**Comment by Pyrohh** [comment]
Thanks

**Pull request merged**
