### PR TITLE
[OLD] Update syntax/vim.vim

### PR DESCRIPTION
**Pull request by ghost**
Based on #2276.

added:
- `:tnoremap`
- `:tmap`
- `:tunmap`
- `TermOpen`

removed:
- termcap code options
- `'compatible'`
- `'cp'`
- `'invcompatible'`
- `'invcp'`
- `'nocompatible'`
- `'nocp'`

### CODE REVIEW

**Comment by chrisbra** [comment]
Perhaps you like to make a new syntax file specifically for nvim? So that Vims native options are still being correctly highlighted?

**Comment by fmoralesc** [comment]
@chrisbra :+1: That is a good idea, and will make things simpler too. Having `runtime/syntax/vim/nvim.vim` file would work, right?

**Comment by Pyrohh** [comment]
Why not just put the nvim specific defs at the bottom, separate from the vanilla vim ones?

> Having runtime/syntax/vim/nvim.vim file would work, right?

I'm not sure, because there's no `ft=nvim`... or so I think.

**Comment by fmoralesc** [comment]
> I'm not sure, because there's no ft=nvim... or so I think.

That's why `syntax/vim/nvim.vim` might work, at least with ftplugins you can put additional code in files in a name called after the ft. So with that file the filetype is still `vim`, but the nvim extensions are added. Can you test if it does that? I'm not sure.

**Comment by Pyrohh** [comment]
> So with that file the filetype is still vim, but the nvim extensions are added.

Yes, but that's my point: this breaks the assumption that each syntax definition accounts for exactly one filetyp; however, I'm not sure if that assumption currently holds true.

**Comment by fmoralesc** [comment]
No, it doesn't. For example, web.vim sources cweb.vim, groovy.vim sources groovyid.vim, etc. We could do the same with a `syntax/nvim.vim` file sourced by `vim.vim`, but if we use the syntax/vim/nvim.vim`

**Comment by Pyrohh** [comment]
> For example, web.vim sources cweb.vim, groovy.vim sources groovyid.vim

Ah, my mistake.

> but if we use the syntax/vim/nvim.vim we can just use the file from upstream vim untouched

The reason I don't want to do that is because we haven't just added defs, but we've removed them as well. Can you undefine a syntax definition? Sorry if this is tedious for you, but I'm obviously not very experienced in Vimscript :sweat:.

**Comment by fmoralesc** [comment]
You can use `syn clear def` to remove a definition, I think (@chrisbra should know for sure).  But you are right, since we have removed stuff, it's not as easy.

**Comment by chrisbra** [comment]
Am 2015-06-24 21:50, schrieb Felipe Morales:
> You can use syn clear def to remove a definition, I think (@chrisbra
> [1] should know for sure). But you are right, since we have removed
> stuff, it's not as easy.

correct.

**Comment by fmoralesc** [comment]
Hm. I was thinking of this, and I believe we shouldn't remove things available in vim but not available in nvim. Instead, we might add new groups to detect incompatible viml idioms and highlight those as errors. For example:
~~~ vim
syn keyword vimOnlyOption contained	t_AF t_AL t_cd t_Ce t_cm t_cs 
hi def link vimOnlyOption Error
~~~
We should also mark nvim specific things as such, and link as appropriate
~~~ vim
syn keyword nvimCommand tnoremap
hi def link nvimCommand vimCommand
~~~
Something similar could be used in vim.

**Comment by Pyrohh** [comment]
I haven't though too much about the first suggestion, but this I'm skeptical of:

> We should also mark nvim specific things as such, and link as appropriate

Do you mean the color used to highlight would also be different? If so, then I don't agree, as it would make it seem like nvim specific things were somehow different (besides not being available in vim), e.g., that `tnoremap` being highlighted differently than `nnoremap` doesn't make sense to me.

**Comment by fmoralesc** [comment]
No, in neovim `tnoremap` would be highlighted the same as `nnoremap` (that's what that `hi def link nvimCommand vimCommand` command does), but `t_Co` et al would be highlighted as an error. 

If we mark `tnoremap` as an nvim only command, then vim_dev can use that same rule with the opposite meaning: in vim it could be shown as an error, but `t_Co` et all would show just like before, just by changing the `hi` definitions.

**Comment by Pyrohh** [comment]
Ah, alright; I'll implement that soon-ish.

**Comment by fmoralesc** [comment]
Thanks; sorry to make things more complicated ;)

**Comment by Pyrohh** [comment]
Thanks for looking into this @fmoralesc.

This PR has been obviated by #2902.

**Pull request closed without merging**
