### PR TITLE
[WIP] options: set default &scrolloff to 1

### PR DESCRIPTION
**Pull request by fmoralesc**
This changes the default of &scrolloff to 1, as per #2676. 

Since there is a discussion on this setting, I'm not planning to request merging right away. I opened this mainly to take care of some of the concerns about it that were brought up (documentation-wise, mostly).
- [x] Change the default of `&scrolloff` to 1.
- [x] Update the documentation (the default needed to be emphasized).
- [x] Fix functional legacy tests (simply set `&scrolloff` to 0 in those)
- [x] Fix functional tests 
- [x] Fix old tests

### CODE REVIEW

**Comment by fmoralesc** [comment]
Note: the behavior in the
~~~ vim
noremap <expr> H 'H' . eval('&scrolloff') . '<C-u>'
noremap <expr> L 'L' . eval('&scrolloff') . 'j'
~~~
mappings can also be obtained by removing line 4516 in `src/nvim/normal.c`.

~~~ diff
      curwin->w_cursor.lnum = curbuf->b_ml.ml_line_count;
  }

- cursor_correct();     /* correct for 'so' */
  beginline(BL_SOL | BL_FIX);
}

~~~

**Comment by justinmk** [comment]
Not feeling good about this change. Unless there is overwhelming popular support for it, I think it is better to take the zero-energy position.

**Comment by Pyrohh** [comment]
> Not feeling good about this change. Unless there is overwhelming popular support for it, I think it is better to take the zero-energy position (i.e. leave things as they were).

I agree. I use a custom scrolloff value myself, but this doesn't seem like a good idea for the same reasons said in https://github.com/neovim/neovim/issues/2676#issuecomment-102783594.

**Comment by glts** [comment]
About these mappings: you can drop the `eval()` and replace `<C-u>` with `k`. (Tip: never use a count with `<C-D>`/`<C-U>`, it breaks them for the current window.)

    noremap <expr> H 'H' . &scrolloff . 'k'

**Comment by Pyrohh** [comment]
@fmoralesc I'm curious, why keep this open? I ask because #2676 has a bold REJECTED notice next to scrolloff, presumably added by you.

**Comment by fmoralesc** [comment]
@Pyrohh Just timing, gee... Can't I go to the loo? (I pushed the changes to the mappings just as a documentation thing, in case someone wants to revive this one).

**Comment by fwalch** [comment]
> Just timing, gee... Can't I go to the loo?

:joy:

**Comment by Pyrohh** [comment]
Heh, sorry. I don't mean to rush you, I just didn't want to forget about it.

**Comment by fmoralesc** [comment]
**I'll never forget it**. /jk

**Pull request closed without merging**
