### PR TITLE
fix(ui): do not invalidate msg_grid rows used for cmdline

### LINKED ISSUE #22154: abort() by 'resize -1' with 'cmdheight=0 redrawdebug=invalid'
### Describe the bug

`resize -1` leads to abort() if options `cmdheight=0 redrawdebug=invalid` are set.

### Steps to reproduce

nvim --clean
set cmdheight=0 redrawdebug=invalid
resize -1

### Expected behavior

resize works

### Actual behavior

nvim is terminated by abort(3).

abort() is called at line 427 in ui_compositor.c.
https://github.com/neovim/neovim/blob/8fbe75b3dda7ab3b9e6df0d5406539bde4c80887/src/nvim/ui_compositor.c#L425-L428

### Neovim version (nvim -v)

NVIM v0.9.0-dev-877+g228684d2f-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu-22.04, macOS (Mojave etc.)

### Terminal name/version

gnometerminal, Apple's Termial.app

### $TERM environment variable

xterm-256color

### Installation

build from source

### PR DESCRIPTION
**Pull request by ghost**
Do not invalidate first `p_ch` `msg_grid` rows in `update_screen` when scrolling the screen down after displaying a message, because they may be used later for drawing cmdline.

fixes #22154

### CODE REVIEW

**Comment by bfredl** [comment]
Hmm, ideally the commandline will be redrawn as the event which causes these lines to next touch the compositor. This is handled correctly if you do `set ch=0` and then `set ch=1`. 

But regardless, a test (which fails on master) would be very useful.

**Comment by zeertzjq** [comment]
#20360 may be related

**Comment by nwounkn** [comment]
The problem is when the screen is scrolled down during `UPD_NOT_VALID` redraw https://github.com/neovim/neovim/issues/22154#issuecomment-1678773839  

> But regardless, a test (which fails on master) would be very useful.  

Where should I put it?

**Comment by justinmk** [comment]
> > a test (which fails on master) would be very useful.
> 
> Where should I put it?

This looks like a good place: https://github.com/neovim/neovim/blob/5a363ccac8ff5889332bafbf68e7e8d20bca316c/test/functional/ui/cmdline_spec.lua#L1007

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
> It seems to be useless, considering that cmdline is drawn on `msg_grid`, which is above `default_grid`, so last `p_ch` `default_grid` rows aren't visible.

Is that code from before `msg_grid` was implemented? Or is it relevant for certain UIs (`:help ui-options`)?

**Pull request merged**
