### PR TITLE
fix(lsp): filetype matching to documentSelector in dynamic capabilities

### PR DESCRIPTION
**Pull request by mliszcz**
The filetype option may contain multiple file type names (dot-separated).
We now allow the document selector to match any of those names.

### CODE REVIEW

**Comment by mliszcz** [comment]
An example use case:

I'm using https://github.com/gustafj/vim-ttcn which assumes 'filetype=ttcn' for TTCN-3 files.

I'm also using https://github.com/nokia/ntt language server. For some dynamic capabilities they send:
```
      ["textDocument/formatting"] = { {
          id = "TEXTDOCUMENT_FORMATTING",
          method = "textDocument/formatting",
          registerOptions = {
            documentSelector = { {
                language = "ttcn3",
                pattern = "**/*.ttcn3",
                scheme = "file"
              } }
          }
        } },
```

I just learned that to satisfy both the plugin (for basic syntax highlighting) and the LS (dynamic capabilities) I can put multiple components into the filetype option, like:
```
autocmd BufRead,BufNewFile *.ttcn3 set filetype=ttcn.ttcn3
```

**Review by glepnir — APPROVED** [review]

**Review by mfussenegger — COMMENTED** [review]
I'm not sure about this. `lsp.start_client` takes a `get_language_id` function to map from buffer & filetype to LSP languageId. That's also used in TextDocumentItem payloads. See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem

I suspect it would make sense to integrate that in the dynamic capability check too to match the other components which use it. 

And this could also use a test case to avoid regressions.

**Comment by mliszcz** [comment]
@mfussenegger just to double check if I understand you correctly - the dynamic capability matching should look like:

```diff
- if filter.language and ft ~= filter.language then
+ if filter.language and get_language_id(bufnr, ft) ~= filter.language then
```

If yes, I think we should also update `get_language_id` to split the filetype by dot and return the first component. Right?

**Comment by mfussenegger** [comment]
>  I think we should also update get_language_id to split the filetype by dot and return the first component. Right?

No you'd provide a `get_language_id` implementation that returns ttcn3 for ttcn filetypes. You could then also create a PR to lspconfig to do that by default.

See https://github.com/neovim/nvim-lspconfig/blob/eb1b53162755888ff75e495797071644d983bff7/lua/lspconfig/server_configurations/ltex.lua#L24 for an example where this is used

**Comment by mliszcz** [comment]
I just pushed an updated version. Will add the tests in the coming days.

**Comment by mfussenegger** [comment]
I added a fixup to extend a testcase to cover the change. Thanks for the PR

**Pull request merged**
