### PR TITLE
Apply stylua to test files

### PR DESCRIPTION
**Pull request by catlee**
Should the test lua files be formatted the same way as the runtime sources?

This PR enables stylua formatting for `test/**/*.lua`, assuming this is something we want to do?

### CODE REVIEW

**Comment by clason** [comment]
These test files were not formatted deliberately, as some of the test rely on the specific (manual) formatting.

**Comment by zeertzjq** [comment]
This adds too many unnecessary line breaks and is clear undesirable.

**Comment by justinmk** [comment]
I do think we should eventually do this, but maybe the stylua settings can be adjusted to be less intrusive. And will need to be done in smaller batches.

> These test files were not formatted deliberately, as some of the test rely on the specific (manual) formatting.

We could exclude those files as needed.

**Comment by clason** [comment]
Stylua is an "opinionated formatter", so there's not much to adjust there. Possibly the line length can be tuned (disabled) locally, but I'd have to check whether `stylua` can handle multiple conflicting configuration files.

**Pull request closed without merging**
