### PR TITLE
[RFC] Remove redundant casts

### PR DESCRIPTION
**Pull request by tonyo**
I removed several redundant casts. Thanks for detecting them go to the CLion IDE.

### CODE REVIEW

**Comment by justinmk** [comment]
Nice. Can't wait to get nvim into a jetbrains product :)

**Comment by jszakmeister** [comment]
:+1:

**Comment by Pyrohh** [comment]
Mmmm, these kind of cleanups are great. Thanks @rev112!

**Comment by rev112** [comment]
:smile_cat:

**Pull request merged**
