### PR TITLE
build: update uncrustify to 0.76

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by lewis6991** [comment]
The config for formatting case labels appears to not work. Probably best to wait for 0.77

**Comment by dundargoc** [comment]
Not a bug, so won't get fixed in 0.77. I made a workaround to make uncrustify ignore formatting for attributes. This workaround no longer works since 0.76 as you noticed. We can remove it, but then attributes won't be correctly formatted.

**Comment by bfredl** [comment]
The messing up of labels _outside_ of a case statement is surely a bug, though?

**Comment by dundargoc** [comment]
I'd still say no, as the workaround is changing how uncrustify parses the C file. I don't think we have a legitimate case here that we can bring up with the uncrustify team.

What we could do is ask for a new option to specify formatting for attributes perhaps?

**Review by dundargoc — APPROVED** [review]
This looks amazing! What a smart trick to use class colons as a workaround!

**Review by dundargoc — APPROVED** [review]
This looks great! Thank you!

**Review by luukvbaal — APPROVED** [review]

**Review by bfredl — APPROVED** [review]
:shipit:

**Pull request merged**
