### PR TITLE
Refactor msg_make

### PR DESCRIPTION
**Pull request by alkino**
Here is an easter eggs. Do we remove it completely?

### CODE REVIEW

**Comment by fmoralesc** [comment]
Hi, @alkino. Do you know when and how is this code triggered? It seems both pointless and annoying (it plugs in the `:make` and `:grep` paths, from what I can tell).

**Comment by bfredl** [comment]
try `:make coffee`

**Comment by fmoralesc** [comment]
@bfredl Ah, I remember now! `coffee` should be replaced by 'tea' and 'milk by sugar' by 'lemon and ice', but that' just my opinion.

**Comment by bfredl** [comment]
Heresy! (But seriously, if this "feature" was just removed bcuz "less
LOCs!" or "readable codebase", I wouldn't miss it)
Den 6 sep 2015 6:07 em skrev "Felipe Morales" <notifications@github.com>:

**Comment by alkino** [comment]
Endly remove it.

**Comment by fmoralesc** [comment]
LGTM.

**Comment by justinmk** [comment]
I don't want to get into the business of removing every bit of personality from Vim. 

There are no tests for `:make`. Write some tests and then this becomes valuable :)

**Comment by fmoralesc** [comment]
> I don't want to get into the business of removing every bit of personality from Vim. 

Dunno. With other easter eggs there is at least some chance of people finding them (like the holy grail), but this? The obfuscation of the code doesn't help the case either. 

Besides, this easter egg was obviously introduced by the evil people at the Coffee Consumption Committee (I now suspect @bfredl is a part of it). We have to keep vigilant, this remained in the codebase for way too long. Or are you saying you are on of *them*, @justinmk? 

are you doing all you can?

**Comment by fmoralesc** [comment]
Now, to be serious, @justinmk''s suggestion is very good. :+1:

**Comment by justinmk** [comment]
@fmoralesc are you doing coffee right now? Lol.

**Comment by bfredl** [comment]
Being neovim, we should have rplugin provider for beverage of choice... But `:grep coffee` makes no sense whatsoever, I think that is Bug of this Feature. (Interestingly, I can't neither in recent vanilla vim.)

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/pull/3295#issuecomment-138133686

**Pull request closed without merging**
