### PR TITLE
refactor(plines): move "plines" (size of printed lines) family of function to own file

### PR DESCRIPTION
**Pull request by bfredl**
This is in preparation for upcoming feature changes which will allow decorations to change the vertical and horizontal size of displayed text.

These functions are responsible for calculating the displayed size of buffer text without needing to redraw it. Previously they where spread around in weird places, like misc1.c (to be deleted) and charset.c (mixed up with low-level unicode charset info).

### CODE REVIEW

**Comment by MunifTanjim** [comment]
After this is merged, I'm getting this error when trying to build from source:

```
$ make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local

mkdir -p build
touch build/.ran-third-party-cmake
ninja  -C .deps
ninja: Entering directory `.deps'
[3/3] cd /home/shaikat/Dev/github/neovim/neovim/.deps && /usr/bin/cmake -E touch .third-party
ninja  -C build
ninja: Entering directory `build'
[3/126] Building C object src/nvim/CMakeFiles/nvim.dir/charset.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/charset.c.o
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto -fno-fat-lto-objects   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/charset.c.o -MF src/nvim/CMakeFiles/nvim.dir/charset.c.o.d -o src/nvim/CMakeFiles/nvim.dir/charset.c.o   -c ../src/nvim/charset.c
In file included from ../src/nvim/charset.c:28:
../src/nvim/plines.h:7:11: fatal error: plines.h.generated.h: No such file or directory
    7 | # include "plines.h.generated.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[4/126] Building C object src/nvim/CMakeFiles/nvim.dir/cursor.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/cursor.c.o
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto -fno-fat-lto-objects   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/cursor.c.o -MF src/nvim/CMakeFiles/nvim.dir/cursor.c.o.d -o src/nvim/CMakeFiles/nvim.dir/cursor.c.o   -c ../src/nvim/cursor.c
In file included from ../src/nvim/cursor.c:16:
../src/nvim/plines.h:7:11: fatal error: plines.h.generated.h: No such file or directory
    7 | # include "plines.h.generated.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/126] Building C object src/nvim/CMakeFiles/nvim.dir/change.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/change.c.o
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto -fno-fat-lto-objects   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/change.c.o -MF src/nvim/CMakeFiles/nvim.dir/change.c.o.d -o src/nvim/CMakeFiles/nvim.dir/change.c.o   -c ../src/nvim/change.c
In file included from ../src/nvim/change.c:25:
../src/nvim/plines.h:7:11: fatal error: plines.h.generated.h: No such file or directory
    7 | # include "plines.h.generated.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[7/126] Building C object src/nvim/CMakeFiles/nvim.dir/edit.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/edit.c.o
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto -fno-fat-lto-objects   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always  -Wno-conversion -MD -MT src/nvim/CMakeFiles/nvim.dir/edit.c.o -MF src/nvim/CMakeFiles/nvim.dir/edit.c.o.d -o src/nvim/CMakeFiles/nvim.dir/edit.c.o   -c ../src/nvim/edit.c
In file included from ../src/nvim/edit.c:44:
../src/nvim/plines.h:7:11: fatal error: plines.h.generated.h: No such file or directory
    7 | # include "plines.h.generated.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[11/126] Building C object src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto -fno-fat-lto-objects   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always  -Wno-conversion -MD -MT src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o -MF src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o.d -o src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o   -c ../src/nvim/eval/funcs.c
In file included from ../src/nvim/eval/funcs.c:50:
../src/nvim/plines.h:7:11: fatal error: plines.h.generated.h: No such file or directory
    7 | # include "plines.h.generated.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[16/126] Building C object src/nvim/CMakeFiles/nvim.dir/eval.c.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:90: nvim] Error 1
```

🤔

**Comment by clason** [comment]
You need to `make cmake`

**Comment by vigoux** [comment]
Or, `make disclean && make`

**Comment by MunifTanjim** [comment]
Thanks so much! 😄 I was using one of my scripts to install Neovim. That buggy script was working up until now, that's what got me confused.

Thanks!

**Pull request merged**
