### PR TITLE
fix(lsp): event LspDetach is not executed at stop_client #18677

### LINKED ISSUE #18677: LspDetach is not executed at `vim.lsp.stop_client`
### Neovim version (nvim -v)

b3453ea4a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian sid

### Terminal name/version

kitty

### $TERM environment variable

screen-256color

### Installation

from source

### How to reproduce the issue

Assumming that we have attached LSP client 1 to the current buffer let
```vim
:au LspDetach echom 'Detached'
:lua vim.lsp.stop_client(1)
```
and see no message. 

Currently in `dispatch.on_exit` we have `LspDetach` inside a loop through `all_buffer_active_clients` which is [cleared ](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L1194) from `client_id` for each buffer before. Probably we need to execute `LspDetach` directly in `client.stop`.

### Expected behavior

LspDetach is executed at `stop_client` 

### Actual behavior

LspDetach is not executed at `stop_client`

### PR DESCRIPTION
**Pull request by przepompownia**
Closes #18677

### CODE REVIEW

**Comment by przepompownia** [comment]
Maybe some tests are needed. I tested #18711 manually on
https://github.com/przepompownia/vim-arctgx/blob/0538265aed6c5f34afc628f5ee0290579fb0434e/lua/arctgx/lsp.lua#L46-L84

**Comment by przepompownia** [comment]
@gpanders probably you're right but currently 
```lua
client_ids[client_id] = nil
```
in the loop inside `client.stop` gives the same effect as detaching. After quick commenting
```lua
  function client.stop(force)
    lsp.diagnostic.reset(client_id, all_buffer_active_clients)
    changetracking.reset(client_id)

    for bufnr, client_ids in pairs(all_buffer_active_clients) do
      -- nvim_exec_autocmds('LspDetach', {
      --   buffer = bufnr,
      --   modeline = false,
      --   data = { client_id = client_id },
      -- })

      client_ids[client_id] = nil
    end
    return

    -- local handle = rpc.handle
    -- if handle:is_closing() then
    --   return
    -- end
    -- if force or not client.initialized or graceful_shutdown_failed then
    --   handle:kill(15)
    --   return
    -- end
    -- -- Sending a signal after a process has exited is acceptable.
    -- rpc.request('shutdown', nil, function(err, _)
    --   if err == nil then
    --     rpc.notify('exit')
    --   else
    --     -- If there was an error in the shutdown request, then term to be safe.
    --     handle:kill(15)
    --     graceful_shutdown_failed = true
    --   end
    -- end)
  end
```
highlighting is not available in my example although the server is still alive. 

It seems to me that your argument can be used both to my change and existing cleaning quoted above.

**Comment by przepompownia** [comment]
How to run `test/functional/plugin/lsp_spec.lua` separately without rebuilding nvim binary? At the moment I found that `TEST_FILE=test/functional/plugin/lsp_spec.lua make functionaltest` runs the test separately but additionaly rebuilds the binary before.

**Comment by mfussenegger** [comment]
> @mfussenegger is there some reason we need to do these things in both client.stop() as well as client.on_exit()?

Not that I know of. Would be nice to get rid of redundant logic there.

**Pull request closed without merging**
