### PR TITLE
neovim on illumos/smartos

### PR DESCRIPTION
**Pull request by papertigers**
This updates lua-client based on neovim/lua-client#7

For SunOS we also need to link with socket and include limits.h

Finally this will not work without a newer libuv thanks to this patch from a few days ago: libuv/libuv#210

So until libuv cuts a new release with the PR merged in from above this can probably sit here waiting to be merged in.

### CODE REVIEW

**Comment by justinmk** [comment]
So libuv supports Solaris? Very cool.

We have a pretty non-intrusive CLA, if you have a moment: https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#pull-requests

**Comment by papertigers** [comment]
I sure hope it would support illumos ;)  Given that node.js is heavily dependent on it and smartos is the best place to run node with all its fancy debugging features (dtrace/mdb).

Taking a look at the CLA now.

**Comment by Happy-Dude** [comment]
@justinmk, libuv was originally a Joyent project -- who just happened to start node.js and also SmartOS, a distribution of illumos, which happens to be the spiritual successor of OpenSolaris :)

**Comment by papertigers** [comment]
@justinmk signed.

**Comment by papertigers** [comment]
squashed.

**Comment by papertigers** [comment]
Also in regards to libuv: https://github.com/libuv/libuv/releases/tag/v1.4.1
Do you want the bump in libuv version in a new PR?

**Comment by aktau** [comment]
We should test if Libuv 1.4.1 is broken with current master as 1.4.0 was
with the master of a week ago. I have a feeling it might be fixed since
@tarruda changed the input from tty to pipe but I might be mistaken. Would
link in the bug report in the neovim bug tracker  + bisected Libuv commit
that caused it but I'm on a phone.

Am Dienstag, 24. Februar 2015 schrieb Michael Zeller :

**Comment by Pyrohh** [comment]
This is for 1.4.0, but it's probably still relevant: https://github.com/neovim/neovim/issues/1914#issuecomment-75378246

**Comment by aktau** [comment]
> This is for 1.4.0, but it's probably still relevant: #1914 (comment)

Right, that's the one I was referring to. My bad.

**Comment by papertigers** [comment]
Can this be pulled in or do you need something else from me?

**Comment by justinmk** [comment]
merged, thanks. @jszakmeister do you have any plans for a solaris build?

**Comment by jszakmeister** [comment]
@justinmk Not necessarily, but if someone can edit the wiki and include directions and what you need to do to build for Solaris, I can create a VM and add it as a slave.  I'm still trying to work out some of the details for my build  farm.

**Comment by tarruda** [comment]
hmmm, I think solaris build might not be working since we now make use of [forkpty](https://github.com/neovim/neovim/blob/master/src/nvim/os/pty_process.c). The implementation of this function seems to be simple though, and tmux has its own compatibility replacement so we might be able to simply copy it.

**Comment by papertigers** [comment]
When was the forkpty stuff introduced?
All of my testing has been on illumos and _not_ solaris (there is 5 years of divergence here).

I have been successful building nvim on illumos provided I stick in a new build of libuv.a

**Comment by justinmk** [comment]
Ok. I didn't think we planned to support solaris but there seems to be interest in it. But if it becomes a burden we might need to reconsider.

**Comment by papertigers** [comment]
And forkpty is mia currenlty:
https://www.illumos.org/issues/5386

**Comment by tarruda** [comment]
> When was the forkpty stuff introduced?

Here: https://github.com/neovim/neovim/commit/d7e560e5b309578f142c23467d566877cb54ee9a

we can easily include compatibility replacement if required. [here](https://github.com/freebsd/freebsd/blob/master/lib/libutil/pty.c) is how freebsd implements it, and [here](https://github.com/ThomasAdam/tmux/blob/master/compat/forkpty-sunos.c) is the sunos version used by tmux

**Comment by papertigers** [comment]
Yea we can definitely use the tmux version since tmux works just fine for us.  Eventually I will try and get forkpty into illumos.

**Comment by aktau** [comment]
Since Illumos appears to be a modern, rather well-behaved UNIX that's supported by both libuv and luajit, I see no reason why we can't support it. Didn't check our other dependencies, but the posts above seem to indicate they also build on Illumos (no idea why they wouldn't, since it's terminal + POSIX stuff).

**Pull request closed without merging**
