### PR TITLE
fix(build): distinguish vim.mpack from global require'mpack'

### LINKED ISSUE #23213: Build failure if lua51-mpack is present as a system library
### Problem

Hi, since this patch: 1e60e8c0406f6b4b51c51abb5f53e25bd52fee5e

On Arch Linux, with the *neovim-git* AUR package, if you have the *lua51-mpack* library installed on your system, it'll be used instead of the bundled library when building. This results in an error, because the system library is incompatible with the bundled one:
```ninja
[6/403] cd /home/vk/.local/aur/neovim-git/src/build/src/nvim && /usr/bin/cmake -D NVIM_VERSION_MAJOR=0 -D NVIM_VERSION_MINOR=10 -D NVIM_VERSION_PATCH=0 -D NVIM_VERSION_PRERELEASE=-dev -D OUT.../neovim-git/src/build/cmake.config/auto/versiondef_git.h -D NVIM_SOURCE_DIR=/home/vk/.local/aur/neovim-git/src/neovim -P /home/vk/.local/aur/neovim-git/src/neovim/cmake/GenerateVersion.cmake
-- Using NVIM_VERSION: v0.10.0-dev-133+gdbcd1985d1
[164/403] Generating auto/api/private/dispatch_wrappers.generated.h, auto/api/private/funcs_metadata.generated.h, ../../api_metadata.mpack, auto/lua_api_c_bindings.generated.c, auto/keysets_defs.generated.h
FAILED: src/nvim/auto/api/private/dispatch_wrappers.generated.h src/nvim/auto/api/private/funcs_metadata.generated.h api_metadata.mpack src/nvim/auto/lua_api_c_bindings.generated.c src/nvim/auto/keysets_defs.generated.h /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/api/private/funcs_metadata.generated.h /home/vk/.local/aur/neovim-git/src/build/api_metadata.mpack /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/lua_api_c_bindings.generated.c /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/keysets_defs.generated.h 
cd /home/vk/.local/aur/neovim-git/src/build/src/nvim && /usr/bin/luajit /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/generators/preload.lua /home/vk/.local/aur/neovim-git/src/neovim /home/vk/.local/aur/neovim-git/src/build/lib/libnlua0.so /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/generators/gen_api_dispatch.lua /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/api/private/funcs_metadata.generated.h /home/vk/.local/aur/neovim-git/src/build/api_metadata.mpack /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/lua_api_c_bindings.generated.c /home/vk/.local/aur/neovim-git/src/build/src/nvim/auto/keysets_defs.generated.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/autocmd.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/buffer.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/command.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/deprecated.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/extmark.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/keysets.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/options.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/tabpage.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/ui.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/vim.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/vimscript.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/win_config.h /home/vk/.local/aur/neovim-git/src/neovim/src/nvim/api/window.h /home/vk/.local/aur/neovim-git/src/build/include/api/autocmd.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/buffer.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/command.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/deprecated.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/extmark.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/options.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/tabpage.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/ui.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/vim.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/vimscript.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/win_config.h.generated.h /home/vk/.local/aur/neovim-git/src/build/include/api/window.h.generated.h
/usr/bin/luajit: ...-git/src/neovim/src/nvim/generators/gen_api_dispatch.lua:196: attempt to call field 'encode' (a nil value)
stack traceback:
	...-git/src/neovim/src/nvim/generators/gen_api_dispatch.lua:196: in main chunk
	[C]: at 0x562ef7b5acd0
```
The AUR package already removed the mpack dependency, but users could still want to install it manually.

The reason why the system lib gets precedence is that the bundled lib gets APPENDED to `package.cpath` and so the system one is found first. I tried looking into this, but was unable to to tell Lua to always load the bundled lib (the "loader" mechanism is quite confusing for me :( )

### Steps to reproduce

1) Install lua51-mpack as a system library
2) Try to build neovim through the AUR *neovim-git* package.
3) Build fails, because the wrong lua library is loaded

### Expected behavior

The build process correctly loads the bundled library instead of the system one

### Neovim version (nvim -v)

1e60e8c0406f6b4b51c51abb5f53e25bd52fee5e

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

neovim-git AUR package

### PR DESCRIPTION
**Pull request by bfredl**
problem: the api of vim.mpack is not compatible with a system provided mpack
solution: don't require 'mpack' directly from he system path

fixes #23213 (hopefully, with distros you can never be really sure)

### CODE REVIEW

**Comment by mcepl** [comment]
Hmm, not yet:
```
[   31s] [ 92%] Generating syntax/vim/generated.vim
[   31s] cd /home/abuild/rpmbuild/BUILD/neovim/build/runtime && /usr/bin/luajit /home/abuild/rpmbuild/BU
ILD/neovim/src/nvim/generators/preload.lua /home/abuild/rpmbuild/BUILD/neovim /home/abuild/rpmbuild/BUIL
D/neovim/build/lib/libnlua0.so /home/abuild/rpmbuild/BUILD/neovim/scripts/genvimvim.lua /home/abuild/rpm
build/BUILD/neovim/src/nvim /home/abuild/rpmbuild/BUILD/neovim/build/runtime/syntax/vim/generated.vim /h
ome/abuild/rpmbuild/BUILD/neovim/build/funcs_data.mpack
[   31s] /usr/bin/luajit: attempt to index a userdata value
[   31s] stack traceback:
[   31s]        [C]: at 0x7f967cc49250
[   31s]        [C]: in function 'require'
[   31s]        /home/abuild/rpmbuild/BUILD/neovim/scripts/genvimvim.lua:1: in main chunk
[   31s]        [C]: at 0x558888a9e110
[   31s] make[2]: *** [runtime/CMakeFiles/runtime.dir/build.make:96: runtime/syntax/vim/generated.vim] E
rror 1
[   31s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/neovim/build'
[   31s] make[2]: *** Waiting for unfinished jobs....
```
That’s on openSUSE/Tumbleweed with lua51-mpack-1.0.6-5.2 and the current master.

**Review by dundargoc — APPROVED** [review]

**Comment by bfredl** [comment]
@mcepl please try master once again

**Comment by betaboon** [comment]
reporting back from nixos: this fixes the build failure

**Comment by mcepl** [comment]
> @mcepl please try master once again

Yes, [my package](https://build.opensuse.org/package/show/home:mcepl:neovim/neovim) builds again with master. Thank you!

**Pull request merged**
