### PR TITLE
Fix verbose completion messages

### PR DESCRIPTION
**Pull request by cbarrete**
The documentation states that Vim should "give messages about what it is
doing" regarding "Every searched tags file and include file" for
'verbose' values greater or equal to 5.

### CODE REVIEW

**Comment by Shougo** [comment]
LGTM

**Comment by cbarrete** [comment]
Can someone have a look at this? I'm happy to iterate if something is not right yet.

**Comment by teto** [comment]
looks LGTM. @jamessan ?

**Comment by jamessan** [comment]
No objections from me.  Cc @brammool since this looks like it applies upstream too.

**Comment by brammool** [comment]
On a fast system these messages can indeed be distracting.  On a slow system, or when there is a lot of searching to do, it is useful to have an idea what is going on.  Otherwise it might seem that Vim is stuck.
What works best is have a central function to pass the current status, and then only output something every second or so.  If completion is done within a second then nothing shows, if some form of completion is slow then the user gets a hint about what the time is being spend on.

**Comment by cbarrete** [comment]
I don't really have time to look into this right now but I'd argue that this PR aligns the behavior with the docs and is an improvement in general. Users on slow systems can simply not silence messages about "what [Vim] is
doing", which is the current behavior.

**Pull request closed without merging**
