### PR TITLE
fix(lsp): SignatureHelp docstring is not escaped

### LINKED ISSUE #16563: SignatureHelp documentation string not escaped in markdown conversion
### Neovim version (nvim -v)

NVIM v0.6.0

### Language server name/version

clangd 13

### Operating system/version

Arch Linux

### :checkhealth

_No response_

### Steps to reproduce using "nvim -u minimal_init.lua"

Only changed 2 lines in `minimal_init.lua`: 
```lua
  local name = 'clangd'
  local cmd = { 'clangd'} -- needed for elixirls, omnisharp, sumneko_lua
```
then open a file with 
```cpp
#include<functional>
int main(){
  int a{1};
  int b{2};

  std::swap(a, b);
//             |---- put cursor here and <c-k> for signatureHelp
}
```

**clangd reply**
```
{
  activeParameter = 1,
  activeSignature = 0,
  signatures = { {
      documentation = "\n  @brief Swaps two values.\n  @param  __a  A thing of arbitrary type.\n  @param  __b  Another thing of arbitrary type.\n  @return   Nothing.\n  ",
      label = "swap(_Tp &__a, _Tp &__b) -> typename enable_if<__and_<__not_<__is_tuple_like<_Tp>>, is_move_constructible<_Tp>, is_move_assignable<_Tp>>::value>::type",
      parameters = { {
          label = { 5, 13 }
        }, {
          label = { 15, 23 }
        } }
    } }
}
```

### Expected behavior

I think the above-mentioned `clangd` reply should be handled correctly. 

From looking at the documentation of [`SignatureInformation`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#signatureInformation) the `documentation`  field is allowed to either be `string` or `MarkupContent`

I've locally played around a bit, and the conversion happens here:
https://github.com/neovim/neovim/blob/730a9514dcf540c4921bbe45c1c8849f773bae39/runtime/lua/vim/lsp/util.lua#L818-L820

So one could fix it with the following change:      
```lua
  if signature.documentation then
    if type(signature.documentation) == 'string' then
      signature.documentation = {kind = 'plaintext', value=signature.documentation}
    end
    vim.lsp.util.convert_input_to_markdown_lines(signature.documentation, contents)
  end
```

Which seems to work for my specific case.

image

I'm happy to turn this into a PR but wasn't sure if this is maybe a bit too hacky, or if I'm missing something in respect to the LSP spec or it's implementation in neovim, thus figured I'd start with an issue :blush: 

### Actual behavior

The documentation is interpreted as Markdown, thus the double underscores mess with formatting.

image

### Log file

_No response_

### PR DESCRIPTION
**Pull request by hassec**
Fix #16563

### CODE REVIEW

**Comment by mjlbach** [comment]
I don't like shimming the plaintext into markup content. I'd rather we just separately handled the case of plaintext.

**Comment by hassec** [comment]
Thanks @mjlbach for having a look :)  

I was trying to keep this as minimal as possible, with the hope of maybe having this back-ported to 0.6?     
That said, I'm happy to make some more changes if you like, but I'm not really sure if I fully understand your objection yet.
Do you mind giving me some more guidance as to how you would have fixed this?  

As far as I understand it so far:        
Isn't a reply of type `MarkupContent` with `kind==plaintext` already a `plaintext` reply shimmied into a markup content?
And given that plaintext is already correctly handled if it comes wrapped in a `MarkupContent` object, what's the downside of transforming a plain `string` reply into such an object inside the handler?   
It would ensure that a plaintext reply is handled the same across all LSPs no matter if they send a `string` or `MarkupContent` with `kind == plaintext`.   

Also, while I have you, I want to take the opportunity to say: Thanks a million for lspconfig and all the time you spend helping people in the neovim community! I've learned a lot from your posts on reddit! :+1: :+1: :+1:

**Comment by hassec** [comment]
gentle ping @mjlbach

**Comment by justinmk** [comment]
@hassec this seems worth trying, can you rebase ?

**Comment by hassec** [comment]
@justinmk, I just pushed a rebased version

**Comment by justinmk** [comment]
Nice, thanks. This is covered by a test which is now failing and needs to be updated.

I pushed an update.

```
FAILED   test/functional/plugin/lsp_spec.lua @ 3002: LSP lsp.util.convert_signature_help_to_markdown_lines can handle negative activeSignature
test/functional/plugin/lsp_spec.lua:3018: Expected objects to be the same.
Passed in:
(table: 0x7f813719de18) {
  [1] = '```cs'
  [2] = 'TestEntity.TestEntity()'
  [3] = '```'
 *[4] = '<text>'
  [5] = ''
  [6] = '</text>' }
Expected:
(table: 0x7f813719deb0) {
  [1] = '```cs'
  [2] = 'TestEntity.TestEntity()'
  [3] = '```'
 *[4] = '' }
```

**Pull request merged**
