### PR TITLE
ci: bump openbsd image

### PR DESCRIPTION
**Pull request by teto**
seems like 6.5 is not supported anymore.

### CODE REVIEW

**Comment by tjdevries** [comment]
https://github.com/neovim/neovim/pull/12418 You can just make this change or cherry pick the commit if you want. Should make test not flaky (I thought 10x was enough to make it not flaky, but now it's 50x). Can also just make it longer as well if you want.

**Comment by teto** [comment]
I've opened this PR before seeing https://github.com/neovim/neovim/issues/12339. Seems like 6.5 images disappeared so I bumped it to 6.7. I am not sure why we pinned the package versions but I kept it that way. Nevertheless there are still 2 failures:
- an intermittent one regarding vim.wait (@tjdevries patch doesn't seem to be enough but increasing too much the timeout kinda makes the test irrelevant so maybe we could just disable it on BSD)
- a recurrent one test/functional/ui/spell_spec.lua @vext01 would you mind having a look at that one ? it passes on other CIs.

**Comment by tjdevries** [comment]
Honestly, let's just remove the flaky test @teto  for vim.wait -- it's rather useless anyway. It is better proven by the tests that check for global variables being set in other threads (which exist).

**Comment by vext01** [comment]
Can you link me to the output of the failing build for that spelling issue
you want me to look at?

**Comment by teto** [comment]
@tjdevries well if that's fine, let's do that.

@vext01 see https://builds.sr.ht/~jmk/job/224343#task-functionaltest-609 it happens all the time on openbsd but I dont see the failure on the other platforms.

**Comment by tjdevries** [comment]
@teto do you want to do it in this PR or a different one for `vim.wait`

**Comment by vext01** [comment]
I don't have much faith in my ability to fix this, as I don't know the first thing about lua or neovim's internals, but I'm actually having issues running the tests.

After building neovim, I should be able to run the test with `gmake functionaltest-lua`, right?

```
$ gmake functionaltest-lua
...
make[1]: Entering directory '/home/edd/source/neovim/.deps/build/src/lua'
Please do
   make PLATFORM
where PLATFORM is one of these:
   aix ansi bsd freebsd generic linux macosx mingw posix solaris
See INSTALL for complete instructions.
gmake[1]: Leaving directory '/home/edd/source/neovim/.deps/build/src/lua'
[8/12] Performing install step for 'lua'
FAILED: build/src/lua-stamp/lua-install 
cd /home/edd/source/neovim/.deps/build/src/lua && /usr/local/bin/gmake INSTALL_TOP=/home/edd/source/neovim/.deps/usr install && /usr/local/bin/cmake -E touch /home/edd/source/neovim/.deps/build/src/lua-stamp/lua-install
```

If I manually enter the lua directory and do `gmake bsd` and try again:
```
$ gmake functionaltest-lua
...
Error -> error loading module 'luv' from file '/home/edd/source/neovim/.deps/usr/lib/lua/5.1/luv.so':
	Cannot load specified object
/home/edd/source/neovim/test/functional/preload.lua
...tons of failures.
```

Looks like there is a problem with the dependencies not being built properly, or am I doing something wrong?

It might be more fruitful for someone who knows the codebase too ssh into one of the failing sr.ht builds and have a prod around:
https://drewdevault.com/2019/08/19/Introducing-shell-access-for-builds.html

**Comment by teto** [comment]
instructions are in `.builds/openbsd.yml`, it does seem to build on 6.7 with these instructions (which do not run `functionaltest-lua`). I will see if I can get you access to that CI. @BK1603 uses openbsd too

**Comment by vext01** [comment]
> I will see if I can get you access to that CI.

No need, I think I can just paste the manifest into my sr.ht account.

**Comment by vext01** [comment]
How do you run just that one test in isolation?

**Comment by teto** [comment]
`make functionaltest TEST_FILE=test/functional/ui/spell_spec.lua` should be enough

**Comment by vext01** [comment]
Thanks! Looking in to this now.

**Comment by vext01** [comment]
Hi folks,

I've not managed to get all that far with this tonight, but here's the basic issue.

In `Screen:_handle_grid_line()` loops over a line of text (that I assume) we got from the terminal. I think each element represents a character, but should be of type table, presumably to allow for non-ascii characters.

The test crashes because it tries to unpack something which is not a table, but rather is a raw integer.

We can see this in the output from the build [linked above](https://builds.sr.ht/~jmk/job/224343#task-functionaltest-609):

Elided:
```
..., { "t" }, { " ", 0 }, { "i" }, { "n" }, { "\0" }, 16, 0, 0, 0, 0, 0, 0, ...
```

It all goes wrong when we hit (in this case) `16`, but also note the NULL terminator character that precedes it? My guess it that whatever loads up this data structure, was supposed to stop at the NULL, and the remainder of the line is garbage.

The garbage part is also non-deterministic: re-running the test gives new garbage.

I'm out of time tonight, but if someone can point me at where that code is that loads in these grid lines, I can try another time.

**Comment by teto** [comment]
I'll merge what I have there and hopefully we can fix the remaining issue.

**Comment by tjdevries** [comment]
We could move the test to pending until we actually fix it? Would be nice to have green check marks again :'(

**Comment by teto** [comment]
we already killed one test for that, I would feel bad putting it into pending (no one knows when we will revert it :) ).

**Pull request merged**
