### PR TITLE
Vim -> Neovim. Author of neovim: Thiago de Arruda

### PR DESCRIPTION
**Pull request by ghost**
Rename vim to neovim at start page, also replace author name of Vim by Thiago de Arruda cause he is initial author of Neovim

### CODE REVIEW

**Comment by aktau** [comment]
Neovim, though the brainchild of Thiago, is not made solely by him. First of all it's still foremost based on the work of Bram Moolenaar (et alia, as stated in the version file before your commit). I consider the first version to be more correct than the proposed one.

**Comment by tarruda** [comment]
> Neovim, though the brainchild of Thiago, is not made solely by him. First of all it's still foremost based on the work of Bram Moolenaar (et alia, as stated in the version file before your commit). I consider the first version to be more correct than the proposed one.

:+1:

**Comment by MarcWeber** [comment]
Maybe we could call Thiago "maintainer". Eg by Bram, forked and maintained by Thiago or such. This would make sense so that confusion is avoided. Some people might eventually use neovim in place of vim in the future.

**Comment by aktau** [comment]
> Maybe we could call Thiago "maintainer". Eg by Bram, forked and maintained by Thiago or such. This would make sense so that confusion is avoided. Some people might eventually use neovim in place of vim in the future.

As we diverge further and further from vanilla vim internally, it might indeed become appropriate to change it into something like "by Thiago de Arruda and the Neovim team, based on Vim by Bram Moolenaar et al." or what you suggested. If nothing else than to disavow Bram's hand in any errors we introduce. I'm not entirely content with the phrase I proposed, but I'm sure someone more linguistically mind will come up with something concise.

**Comment by tarruda** [comment]
> As we diverge further and further from vanilla vim internally, it might indeed become appropriate to change it into something like "by Thiago de Arruda and the Neovim team, based on Vim by Bram Moolenaar et al." or what you suggested. If nothing else than to disavow Bram's hand in any errors we introduce. I'm not entirely content with the phrase I proposed, but I'm sure someone more linguistically mind will come up with something concise.

I think we should leave things as they are, there's little to gain by making these changes and it will almost certainly generate criticism.

**Comment by vanesyan** [comment]
Ok, I understand :) Sorry to trouble you)

**Comment by elmart** [comment]
>  I think we should leave things as they are, there's little to gain by making these changes and it will almost certainly generate criticism.

There will always be critics and fans, no matter what you do. Life's that way. Therefore, I would go for the *correct* thing, no matter what people outside the project can think.

So, IMO, clearly stating that Neovim is something based on vim, but done by different authors, is not an exercise of pride or arrogance, but simply a necessary and informative statement about project's history, as well as an exercise of responsibility, as it acts as a disclaimer on neovim's changes for vim's original authors.

If you don't want your name there, along with that of Bram and others, I fully respect that. I don't like, in fact, proper names in such a prominent place (I would leave them for a credits.txt file). But then, we should go for  something like:
 
NEOVIM - by the Neovim team - based on Vim - by Bram et al.

Leaving things as they are is the worst option, IMO, as it can in fact be misguiding about Neovim's inception, and who is responsible of changes introduced by it.

Sorry, but that's my view on it. ;-)

**Comment by vanesyan** [comment]
So I think as @elmart. For me, when I started neovim for the first time, I'd wondered of title:

                                     by Bram Moolenaar et al.
                         Vim is open source and freely distributable

I was confused.

**Comment by tarruda** [comment]
>  But then, we should go for something like:

> NEOVIM - by the Neovim team - based on Vim - by Bram et al.

Now that you mention it, one of these days I remember looking at the intro screen and it used to say: "Modified by Neovim contributors", I wonder what happened to that

**Comment by justinmk** [comment]
Changing the current verbiage to say "based on Vim by Bram..." instead of "by Bram..." should be sufficient. It's already clear that this is not Vim because we changed the name to NVIM.

> I wonder what happened to that

There was some special global `modified_by` or something like that, which I think was removed.

**Comment by trusktr** [comment]
Vim doesn't mention anything about [Bill Joy or Chuck Haley](http://en.wikipedia.org/wiki/Vi) in that intro screen, so following that same pattern, the initial post in this thread makes sense.

But I don't like that pattern. Why not say something like (in order of relative contribution time)

```
NeoVim
By Chuck Haley, Bill Joy, Bram Moolenaar, and Thiago de Arruda
```

That's at least more accurate. Or something more generic and simple like the following.

```
NeoVim
By Thiago de Arruda and the NeoVim community.
NeoVim is based on Vim by Bram Moolenaar.
Vim is based on Vi by Bill Joy.
Vi is based on Ex by Bill Joy and Chuck Haley.
See :help history for more.
```

```
NeoVim
Based on Vim, Vi, and Ex.
Would you like to know more? :help history
```

And :help history can have all the nice history starting from the 70's up until now.

**Comment by trusktr** [comment]
Full example:

```
NeoVim
Based on Vim, Vi, and Ex.
Would you like to know more? :help history

type  :q<Enter>               to exit
type  :help<Enter>  or  <F1>  for on-line help
type  :help version<Enter>   for version info
```

**Comment by fwalch** [comment]
I might be wrong, but Vim didn't use actual code from Vi, did it? So it isn't really comparable to the relationship between Vim and Neovim.

**Comment by trusktr** [comment]
@fwalch Oh, is that true?

**Comment by trusktr** [comment]
What does "based on" imply?

**Comment by trusktr** [comment]
Vi and Ex are the reason Vim exists, and Vim is the reason NeoVim exists. The example is saying "based on", so it doesn't necessarily imply code usage. The history can explain all that. :D It's more about the overall historical movement than the specific code.

**Comment by justinmk** [comment]
Vim used code from `stevie`, originally. Don't know what the license was though.

**Pull request closed without merging**
