### PR TITLE
fix(translation): po file for Russian

### LINKED ISSUE #17759: segfault with `:function` for Russian locale
### Neovim version (nvim -v)

v0.7.0-dev+1275-g00effff56; also the same for v0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Kali GNU/Linux 5.16.0

### Terminal name/version

LXTerminal 0.4.0

### $TERM environment variable

xterm256-color

### Installation

no matter

### How to reproduce the issue

    nvim --clean
    :function foobar

### Expected behavior

    E128: Function name must start with a capital or "s:": foobar

### Actual behavior

Application crash.

### PR DESCRIPTION
**Pull request by matveyt**
Closes #17759

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
commit lint doesn't like a capital letter after the colon; maybe `fix(translation): po file for Russian`?

**Comment by matveyt** [comment]
Is there any way to re-run linter check except adding dummy commit?

**Comment by clason** [comment]
The linter checks the actual commit, not the PR title -- so you have to amend the commit and force-push in any case, sorry.

**Comment by dundargoc** [comment]
> Is there any way to re-run linter check except adding dummy commit?

"git commit --amend" to change commit message.

"git push --force" to force push your change, which will re-run the linter.

**Comment by clason** [comment]
Sorry, you _do_ need to keep the `fix(translation): ` part...

**Comment by matveyt** [comment]
Okay, at least now it looks like it's passing on. Sorry to bother all of you but if you commit once per year or so you keep forgetting all this stuff.

**Comment by clason** [comment]
No worries, thanks for you patience!

**Pull request merged**
