### PR TITLE
[WIP] Run clang-format on src/nvim/{*.c,*.h}

### PR DESCRIPTION
**Pull request by in42**
I have run clang-format on the all *.c and *.h files in src/nvim.

I can also add checking of clang-format in the build process so that all PRs have to pass clang-format before getting merged.

This can help in maintaining a consistent style across the codebase, thus making the code more readable.

### CODE REVIEW

**Comment by in42** [comment]
@bfredl Which files should I look at, if want to add clang-format to the build process? Also the clang-format style and the lint style seem to be at odds with each other.

**Comment by jamessan** [comment]
> I have run clang-format on the all *.c and *.h files in src/nvim.

Any particular reason why?  We've avoided doing this for ~6 years already, gradually changing the style as we touch parts of the code.

**Comment by in42** [comment]
> > I have run clang-format on the all *.c and *.h files in src/nvim.
> 
> Any particular reason why? We've avoided doing this for ~6 years already, gradually changing the style as we touch parts of the code.

Oh ok, I thought it will be easier to read if the same style is followed throughout the code. Why running clang-format throughout the code was avoided though?

**Comment by jamessan** [comment]
> Why running clang-format throughout the code was avoided though?

It's a _massive_ change with not much benefit.  When the repository was created and the other comprehensive formatting changes were made (tabs -> spaces, de-#ifdef, etc.), that would have been a good time to do this.

Now, it just clutters the git history and would introduce conflicts for most of the outstanding PRs.  IMHO, the disruption isn't worth the gain.

> Also the clang-format style and the lint style seem to be at odds with each other.

Now this _would_ be a good thing to reconcile if there are obvious changes we can make to the clang-format style to have it align with clint.

**Comment by in42** [comment]
> Now, it just clutters the git history and would introduce conflicts for most of the outstanding PRs. IMHO, the disruption isn't worth the gain.

Git can ignore whitespaces changes such as this, though. E.g. `git blame -w`
One advantage of clang-format over clint is that clang-format can be applied automatically, i.e. one can just run clang-format on their patch using this: http://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting and don't have to manually edit the patch. `clint` does not do this as far as I know. clint can't also format the whole codebase, I think.
This may cause large conflicts with outstanding PRs though.

> Now this would be a good thing to reconcile if there are obvious changes we can make to the clang-format style to have it align with clint.

Ok, I will look into this.

**Comment by dundargoc** [comment]
Closing as we've decided to use `uncrustify` as our current formatter of choice.

**Pull request closed without merging**
