### PR TITLE
docs: added more references

### PR DESCRIPTION
**Pull request by max397574**

### CODE REVIEW

**Comment by vigoux** [comment]
Hi, I think that those parts of the docs are actually auto-generated, so you'll need to edit the doc comments instead of editing the doc file directly.

**Comment by max397574** [comment]
Where are the doc comments?

**Comment by vigoux** [comment]
In the `runtime/lua/vim/lsp/util.lua` file, grep for the function names after that, you can use the `@see` tag in the doc comments to notify that.

**Comment by max397574** [comment]
@vigoux Ok now?

**Comment by vigoux** [comment]
You seem to have only added two, while your original PR added three, is it normal ?

**Comment by max397574** [comment]
There was one which was in the file where the docs get generated from but which wasn't in the docs.

**Comment by vigoux** [comment]
To generate the docs you can run `./scripts/gen_vimdoc.py -t lsp` and see if that updates and add your links.

**Comment by max397574** [comment]
sometimes there are 3 - es (`---@param description`) and sometime only two (`--@param `) which should I use / is there a difference

**Comment by max397574** [comment]
As far as I see it works the way I did it

**Review by vigoux — APPROVED** [review]

**Comment by gpanders** [comment]
> sometimes there are 3 - es (`---@param description`) and sometime only two (`--@param `) which should I use / is there a difference

Use 3: https://github.com/neovim/neovim/pull/15255

**Comment by max397574** [comment]
@gpanders  Should I change the other ones in the file two 3 as well?

**Comment by max397574** [comment]
I could just go through the file and insert a 3th one everywhere I just see 2

**Comment by vigoux** [comment]
Just change the one you added to use 3 dashes.

**Review by vigoux — APPROVED** [review]

**Comment by max397574** [comment]
How can I change the commit messages (some checks are failing because of this)?

**Comment by clason** [comment]
`git commit --amend` and then `git push -f`

**Comment by max397574** [comment]
I messed up sth. I'll open a new pr with the correct changes only @vigoux

**Pull request closed without merging**
