### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by zeertzjq**

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by clason** [comment]
Why?

**Comment by zeertzjq** [comment]
It will make applying Vim runtime updates harder.

**Comment by clason** [comment]
I have to port the runtime updates for these files manually anyway, so it's not a big difference -- and regresses a useful feature.

**Comment by zeertzjq** [comment]
I've dropped that commit.

**Pull request merged**
