### PR TITLE
fix(lsp): avoid `Invalid window id` error when unsetting `b:lsp_floating_preview`

### PR DESCRIPTION
**Pull request by mamekoro**
This PR improves the changes made by PR #31303

Problem 1:
The variable we want to unset here is `lsp_floating_preview`, not `lsp_floating_window`.

Solution 1:
Change `lsp_floating_window` to `lsp_floating_preview`.

---

Problem 2:
`local buf = vim.w[winnr].buf_hold_win` throws the following error when `winnr` is an invalid window ID.

```text
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1347
: scoped variable: Invalid window id: 1002
stack traceback:
        [C]: in function '__index'
        /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1347: in function </usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1339>
```

Solution 2:
Check if `winnr` is valid: `if api.nvim_win_is_valid(winnr) then ... end`

### CODE REVIEW

**Comment by mamekoro** [comment]
There's another bug that `winnr` is invalid at the time `close_preview_window()` is called, resulting in `b:lsp_floating_preview` not being unset.

This bug needs further investigation, so I'll open another issue.

**Comment by justinmk** [comment]
This looks a bit different than https://github.com/neovim/neovim/pull/31303 which was merged. Is any part of this still needed after https://github.com/neovim/neovim/pull/31303 ?

**Comment by mamekoro** [comment]
This PR adds a new `if` block (`if api.nvim_win_is_valid(winnr) then ... end`) to avoid `Invalid window id` error when accessing `vim.w[winnr].buf_hold_win` as shown in the first comment.

**Comment by glepnir** [comment]
win var is obtained before win close. So it should be valid. Where else is the window closed? Maybe I overlooked it. So it should be the right place to find out where it is closed other than this function.

**Comment by mamekoro** [comment]
> Aha, maybe multiple events are registered for close flaoting. But we schedule the closing logic in the next time loop in the callback, and the delete of augroup is wrapped by pcall. So it continues to run. Could you try it to see if it works?

Yes, it eliminates the `Invalid window id` error, but `b:lsp_floating_preview` is still present in some cases.

---

I edited `runtime/lua/vim/lsp/utils.lua` and tested various ways to close the floating window opened by pressing `K` or running `:lua vim.lsp.buf.hover()`.

The purpose is to understand which methods of closing the preview will make `winnr` invalid.

I reused `minimal_init.lua` used in the original issue (#31289).

In short, when I close the preview using the following method, `winnr` is invalid in `close_preview_window()` and `b:lsp_floating_preview` is not deleted.

- Run `:only` in the main window
- Run `:close` in the preview
- Run `:bdelete` in the preview
- Press `q` in the preview

My impression is that it would be simpler and better to create an autocmd for `WinClosed` instead of defining `vim.w[winnr].buf_hold_win`.  `WinClosed` is triggered before the window is removed, so the window ID should be valid in its callback function.

<details>
<summary>diff: runtime/lua/vim/lsp/util.lua</summary>

The purpose of this edit is to log what is happening.

```diff
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index ae0f9c43e..349ecbe3f 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -1336,7 +1336,19 @@ end
 ---@param winnr integer window id of preview window
 ---@param bufnrs table? optional list of ignored buffers
 local function close_preview_window(winnr, bufnrs)
+  print(
+    string.format(
+      'close_preview_window: entered. winnr = %s, bufnrs = %s',
+      winnr,
+      vim.inspect(bufnrs)
+    )
+  )
+  print('close_preview_window: nvim_list_wins() =', vim.inspect(api.nvim_list_wins()))
+
   vim.schedule(function()
+    print('close_preview_window: schedule: entered')
+    print('close_preview_window: schedule: nvim_list_wins() =', vim.inspect(api.nvim_list_wins()))
+
     -- exit if we are in one of ignored buffers
     if bufnrs and vim.list_contains(bufnrs, api.nvim_get_current_buf()) then
       return
@@ -1344,11 +1356,24 @@ local function close_preview_window(winnr, bufnrs)

     local augroup = 'preview_window_' .. winnr
     pcall(api.nvim_del_augroup_by_name, augroup)
+
+    print('close_preview_window: schedule: winnr =', winnr)
+    print('close_preview_window: schedule: windows =', vim.inspect(api.nvim_list_wins()))
+
     if api.nvim_win_is_valid(winnr) then
+      print('close_preview_window: schedule: winnr is valid')
+
       local buf = vim.w[winnr].buf_hold_win
+      print('close_preview_window: schedule: buf_hold_win =', buf)
+
       if buf and api.nvim_buf_is_valid(buf) then
+        print('close_preview_window: schedule: buf_hold_win is valid')
         vim.b[buf].lsp_floating_preview = nil
+      else
+        print('close_preview_window: schedule: buf_hold_win is NOT valid')
       end
+    else
+      print('close_preview_window: schedule: winnr is NOT valid')
     end
     pcall(api.nvim_win_close, winnr, true)
   end)
@@ -1370,6 +1395,7 @@ local function close_preview_autocmd(events, winnr, bufnrs)
   api.nvim_create_autocmd('BufEnter', {
     group = augroup,
     callback = function()
+      print('event = BufEnter')
       close_preview_window(winnr, bufnrs)
     end,
   })
@@ -1378,7 +1404,8 @@ local function close_preview_autocmd(events, winnr, bufnrs)
     api.nvim_create_autocmd(events, {
       group = augroup,
       buffer = bufnrs[2],
-      callback = function()
+      callback = function(ev)
+        print('event =', ev.event)
         close_preview_window(winnr)
       end,
     })
```

</details>

<details>
<summary>Tests and results</summary>

## Test 1. Move the cursor in the main window

1. Press `K` to open the preview.
2. Move the cursor in the main window by pressing j, k, etc.

    This operation prints the following, and closes the preview.

    ```text
    event = CursorMoved
    close_preview_window: entered. winnr = 1002, bufnrs = nil
    close_preview_window: nvim_list_wins() = { 1000, 1002 }
    close_preview_window: schedule: entered
    close_preview_window: schedule: nvim_list_wins() = { 1000, 1002 }
    close_preview_window: schedule: winnr = 1002
    close_preview_window: schedule: windows = { 1000, 1002 }
    close_preview_window: schedule: winnr is valid
    close_preview_window: schedule: buf_hold_win = 1
    close_preview_window: schedule: buf_hold_win is valid
    ```

3. Run `:echo b:lsp_floating_preview`

    This results in `E121: Undefined variable: b:lsp_floating_preview`.
    `b:lsp_floating_preview` has been deleted.

## Test 2. Move the cursor to the preview, then run `:close`

1. Press `K` to open the preview.
2. Press `K` again to move the cursor to the preview.

    This operation prints the following:

    ```text
    event = BufEnter
    close_preview_window: entered. winnr = 1002, bufnrs = { 2, 1 }
    close_preview_window: nvim_list_wins() = { 1000, 1002 }
    close_preview_window: schedule: entered
    close_preview_window: schedule: nvim_list_wins() = { 1000, 1002 }
    ```

3. Run `:close` in the preview.

    This operation prints the following, and closes the preview.

    ```text
    event = BufEnter
    close_preview_window: entered. winnr = 1002, bufnrs = { 2, 1 }
    close_preview_window: nvim_list_wins() = { 1000 }
    event = CursorMoved
    close_preview_window: entered. winnr = 1002, bufnrs = nil
    close_preview_window: nvim_list_wins() = { 1000 }
    close_preview_window: schedule: entered
    close_preview_window: schedule: nvim_list_wins() = { 1000 }
    close_preview_window: schedule: entered
    close_preview_window: schedule: nvim_list_wins() = { 1000 }
    close_preview_window: schedule: winnr = 1002
    close_preview_window: schedule: windows = { 1000 }
    close_preview_window: schedule: winnr is NOT valid
    ```

4. Run `:echo b:lsp_floating_preview`

    This results in `1002`.
    `b:lsp_floating_preview` is present.

## Test 3. Move the cursor to the preview, then run `:bdelete`

The same as Test 2.

## Test 4. Move the cursor to the preview, then press `q`

The same as Test 2.

## Test 5. Move the cursor to another window

1. Create a new window with `:new`.
2. Move back the cursor to the main window.
3. Press `K` to open the preview.
4. Press `CTRL-W_w` to move the cursor to another window.

    This operation prints the following, and closes the preview.

    ```text
    event = BufEnter
    close_preview_window: entered. winnr = 1003, bufnrs = { 3, 1 }
    close_preview_window: nvim_list_wins() = { 1001, 1000, 1003 }
    close_preview_window: schedule: entered
    close_preview_window: schedule: nvim_list_wins() = { 1001, 1000, 1003 }
    close_preview_window: schedule: winnr = 1003
    close_preview_window: schedule: windows = { 1001, 1000, 1003 }
    close_preview_window: schedule: winnr is valid
    close_preview_window: schedule: buf_hold_win = 1
    close_preview_window: schedule: buf_hold_win is valid
    ```

5. Run `:echo b:lsp_floating_preview`

    This results in `E121: Undefined variable: b:lsp_floating_preview`.
    `b:lsp_floating_preview` has been deleted.

## Test 6. Close the preview by running `:only` in the main window

1. Press `K` to open the preview.
2. Run `:only` in the main window.

    This operation prints nothing, and closes the preview.

3. Run `:echo b:lsp_floating_preview`

    This results in `1002`.
    `b:lsp_floating_preview` is present.

4. If I move the cursor after `:only`, the following is printed:

    ```text
    event = CursorMoved
    close_preview_window: entered. winnr = 1002, bufnrs = nil
    close_preview_window: nvim_list_wins() = { 1000 }
    close_preview_window: schedule: entered
    close_preview_window: schedule: nvim_list_wins() = { 1000 }
    close_preview_window: schedule: winnr = 1002
    close_preview_window: schedule: windows = { 1000 }
    close_preview_window: schedule: winnr is NOT valid
    ```

5. Run `:echo b:lsp_floating_preview`

    This results in `1002`.
    `b:lsp_floating_preview` is still present after `CursorMoved`.

</details>

**Comment by glepnir** [comment]
thanks for provide these stpes . I noticed that the problem was that buf var was not cleared when we closed the float with only or I guess fclose command. Because we only delete buf var in the registered autocmd event callback. Good discovery. I overlooked this. WinClosed is a good idea. But check if it has been defined, because here we receive an existing 
`local floating_winnr = opts._update_win`.

**Comment by mamekoro** [comment]
Closing in favor of  #31319

**Pull request closed without merging**
