### PR TITLE
fix(PVS/V583): The '?:' operator always returns one and the same value

### PR DESCRIPTION
**Pull request by dundargoc**
Not entirely sure if this is the correct fix, because the code itself
would make sense if STATUS_HEIGHT had another value. Is it to make it
possible to change the value of it in the future perhaps?

### CODE REVIEW

**Comment by dundargoc** [comment]
@famiu Mind taking a look?

**Comment by famiu** [comment]
> @famiu Mind taking a look?

As you guessed, it is in fact to make it possible to change the value of `STATUS_HEIGHT` in the future. Feel free to change that (and also the `resize_frame_for_status` function) if you feel like changing the value would never be necessary

**Comment by dundargoc** [comment]
I don't mind it really, I'm just not sure if the most "correct" solution would be to remove the ternary operator (like how it is currently) or just add an ignore directive/comment on those lines. I'll ask an unrelated third party on their opinion.

Thanks for your input :)

**Comment by gpanders** [comment]
My unrelated third-party opinion is that I agree with these changes. If and when the day comes that we want to change `STATUS_HEIGHT` it’s a trivial refactor, but for now this is a good simplification (YAGNI or whatever).

**Review by gpanders — APPROVED** [review]

**Pull request merged**
