### PR TITLE
docs: add documentation about lpeg operators

### PR DESCRIPTION
**Pull request by altermo**
I copied the docs from https://www.inf.puc-rio.br/~roberto/lpeg and edited the ones that didn't feel right.

I don't know copyright much, so it may need to be edited to include a notice about the document's origin (and that the docs was edited).

### CODE REVIEW

**Comment by wookayin** [comment]
Thanks for the contribution, but I'm not sure this should be included in the defgroup-pre. It'd be ideal if these can come after the `vim.lpeg` Lua methods.

So we'll need some new ways to add literal docs (non-function-docs) in the generator; I've written something which is unpushed yet, so that might be an option. Or we can also add dummy meta-methods for documenting operators, as the current vimdoc generator doesn't recognize operator overloading, 

Helptags feels a bit verbose, this is something we can discuss and decide. Also, what are the changes you've made? Would you mind listing explicitly here?

**Comment by altermo** [comment]
For the differences:
+ Remove `(this pattern is equivalent to * in the original PEG notation)` (and its variants)
+ Moved line about how `-patt` equals `"" - pat` from documentation `patt1 - patt2` to `-patt`
+ Removed sentences about operator identity element
+ Removed sentences about how the operator is equal to a set operation if both patterns are character sets.
+ Removed sentence about how to get the patterns compliment.
+ Removed some parenthesized text.
+ In `^`, removed doc about its equivalence in PEG notation.
+ In `^`, replaced the equivalent to some PEG notation, with equivalent to a regex notation.
+ In `/`, instead of having one paragraph pre-type, added line about how different types do different things, and started each sentence with what type it acts on.
+ In `%`, removed examples and note about when not to use it.
+ Other smaller changes.

**Comment by MariaSolOs** [comment]
AFAIK we've been using the types (and docs) from https://github.com/LuaCATS/lpeg. Deviating from that documentation would increase the maintenance work.

**Comment by altermo** [comment]
Maybe the better solution is to do as it was done with `_meta/re.lua`, though that would require reworking the whole `_meta/lpeg.lua` file so maybe not.

**Comment by altermo** [comment]
Closing this as I'm not planning to complete this in the near future.

**Pull request closed without merging**
