### PR TITLE
feat!: remove deprecated functions

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
Mark as `feat!`, just to be safe?

**Review by lewis6991 — APPROVED** [review]

**Review by MariaSolOs — APPROVED** [review]

**Comment by wookayin** [comment]
Would we also need to remove corresponding entries from doc/deprecated.txt?

**Comment by dundargoc** [comment]
> Would we also need to remove corresponding entries from doc/deprecated.txt?

Pretty sure that's not a thing. I don't remember ever removing something from `deprecated.txt`. I mean, we could start doing it I guess, but I think it'd make more sense to do it in a separate, dedicated PR.

**Comment by wookayin** [comment]
I'd suggest that we consider doing that as a routine release workflow --- it'd be helpful for [helpful.vim](https://github.com/tweekmonster/helpful.vim). I'm fine with either removing together here (for the atomicity) or as a separate PR.

**Pull request merged**
