### PR TITLE
vim-patch:8.2.{4714,4733}

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.2.4714: using g:filetype_dat and g:filetype_src not tested

Problem:    Using g:filetype_dat and g:filetype_src not tested.
Solution:   Add a test. (Patrick Meiser-Knosowski, closes vim/vim#10117)
https://github.com/vim/vim/commit/a8034a4886843fbf10bd59a6f55ec723da515b8e

#### vim-patch:8.2.4733: HEEx and Surface do need a separate filetype

Problem:    HEEx and Surface do need a separate filetype.
Solution:   Revert 8.2.4729. (closes vim/vim#10147)
https://github.com/vim/vim/commit/4232dff815db1a727cb1aea26783267d8bd731c3

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by zeertzjq** [comment]
Oh, `filetype.lua` doesn't work with these...

**Comment by clason** [comment]
Not all `filetype.vim` checks have been ported yet. But if the variables are used in `autoload/dist/ft.vim`, then they should work with `filetype.lua`.

**Comment by zeertzjq** [comment]
Oh, I know.

**Comment by clason** [comment]
Sorry, then what do you mean by "filetype.lua doesn't work with these..."?

**Comment by zeertzjq** [comment]
It is unrelated to `filetype.lua`. It is a bug in the test. I don't know why it only fails when using `filetype.lua`.

**Comment by zeertzjq** [comment]
<>https://github.com/vim/vim/pull/10143

**Comment by clason** [comment]
Because the relevant `filetype.vim` checks aren't ported yet, and the fallthrough to `filetype.vim` doesn't help if the filetype is already incorrectly detected. 

In particular, `filetype.lua` is missing the equivalent of
```vim
" Innovation Data Processing
au BufRead,BufNewFile upstream.dat\c,upstream.*.dat\c,*.upstream.dat\c	setf upstreamdat
au BufRead,BufNewFile fdrupstream.log,upstream.log\c,upstream.*.log\c,*.upstream.log\c,UPSTREAM-*.log\c	setf upstreamlog
au BufRead,BufNewFile upstreaminstall.log\c,upstreaminstall.*.log\c,*.upstreaminstall.log\c setf upstreaminstalllog
au BufRead,BufNewFile usserver.log\c,usserver.*.log\c,*.usserver.log\c	setf usserverlog
au BufRead,BufNewFile usw2kagt.log\c,usw2kagt.*.log\c,*.usw2kagt.log\c	setf usw2kagtlog
```

**Review by clason — APPROVED** [review]

**Pull request merged**
