### PR TITLE
[RDY] vim-patch: Small patches

### PR DESCRIPTION
**Pull request by fwalch**
Marked 522 as NA, since it only modifies code inside a windows `IFDEF`.
### 514

``` diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -6918,6 +6918,8 @@ stop_insert(end_insert_pos, esc, nomove)
        curwin->w_cursor = tpos;
        else
        {
+       /* reset tpos, could have been invalidated in the loop above */
+       tpos = curwin->w_cursor;
        tpos.col++;
        if (cc != NUL && gchar_pos(&tpos) == NUL)
            ++curwin->w_cursor.col; /* put cursor back on the NUL */
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    514,
+/**/
     513,
 /**/
     512,
```
### 517

``` diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -4456,6 +4456,10 @@ win_line(wp, lnum, startrow, endrow, noc
            /* TODO: is passing p for start of the line OK? */
            n_extra = win_lbr_chartabsize(wp, line, p, (colnr_T)vcol,
                                    NULL) - 1;
+           if (c == TAB && n_extra + col > W_WIDTH(wp))
+           n_extra = (int)wp->w_buffer->b_p_ts
+                      - vcol % (int)wp->w_buffer->b_p_ts - 1;
+
            c_extra = ' ';
            if (vim_iswhite(c))
            {
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    517,
+/**/
     516,
 /**/
     515,
```

### CODE REVIEW

**Comment by fwalch** [comment]
Mark 7.4.591 as NA as well, since it only adds a feature check to a test (https://code.google.com/p/vim/source/detail?r=v7-4-591).

**Comment by Hinidu** [comment]
LGTM :+1:

**Comment by fwalch** [comment]
Thanks! Marking RDY.

**Comment by justinmk** [comment]
merged, thanks

**Pull request closed without merging**
