### PR TITLE
[RDY] vim-patch: 30+ patches

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Comment by ZyX-I** [comment]
Ported patch summaries are still useless. Should not `vim-patch.sh` copy summaries from vim commits?

**Comment by justinmk** [comment]
Yes.

**Comment by justinmk** [comment]
Seems like `tabpage_close_other` is freeing `aucmd_win` now. Bleh.

**Comment by justinmk** [comment]
UBSAN issue is back, seems racy?

**Comment by justinmk** [comment]
This is as "ready" as it will get. ASAN is satisified with https://github.com/neovim/neovim/pull/6323/commits/7214d0bc846179a862e8d3061d00270a6caa0d7b . 

Can revisit this once we catch up to vim-patches 8.0.04xx, and possibly remove https://github.com/neovim/neovim/pull/6323/commits/7214d0bc846179a862e8d3061d00270a6caa0d7b.

**Review by jamessan — APPROVED** [review]

**Comment by janlazo** [comment]
Reverted the assertion for tabonly in https://github.com/neovim/neovim/pull/14532 in order to test patch v8.2.1000. Vim has lots of autocmd patches in Vim 8.2.x to address crashes. Can't port them all because Neovim crashes on the tests from some of those patches.

**Pull request merged**
