### PR TITLE
docs: add security policy

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
I'll have to dig through our discussions, but this is _not_  a good security policy: vulnerabilities should never be disclosed in public. We want a dedicated `security@neovim.io` address, or at least point people to a private Matrix channel like https://matrix.to/#/!FeLvdvlKTPCHTzjupS:matrix.org.

**Comment by dundargoc** [comment]
This PR isn't possible without a mail address.

**Comment by justinmk** [comment]
We could list personal email addresses for now (I'm ok to list mine, not sure about others), or DM https://twitter.com/neovim

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/security/advisories we also have this thing now.

**Comment by justinmk** [comment]
> https://github.com/neovim/neovim/security/advisories we also have this thing now.

Ah, that's probably good enough.

**Pull request merged**
