### PR TITLE
vim-patch:8.1.{10,230,315,330,514,517,518,1327,1347,1758,2072,2074,2091,2095,2103}

### PR DESCRIPTION
**Pull request by janlazo**

### CODE REVIEW

**Comment by blueyed** [comment]
Build failures are the same as with https://github.com/neovim/neovim/pull/11096 - i.e. due to that patch.

**Comment by janlazo** [comment]
```
[  ERROR   ] 1 error, listed below:
[  ERROR   ] test/functional/terminal/tui_spec.lua @ 561: TUI paste: exactly 64 bytes #10311
test/functional/ui/screen.lua:587: Row 1 did not match.
Expected:
  |*zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzz end{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |
Actual:
  |* endzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzzzzzz{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:587: in function '_wait'
	test/functional/ui/screen.lua:370: in function 'expect'
	test/functional/terminal/tui_spec.lua:569: in function <test/functional/terminal/tui_spec.lua:561>
```
@blueyed Flaky test?

**Comment by blueyed** [comment]
@janlazo yes, created https://github.com/neovim/neovim/issues/11110.

**Comment by justinmk** [comment]
LGTM. waiting for appveyor CI.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
