### PR TITLE
[RDY] Stop time watcher on timer_pause

### LINKED ISSUE #8188: paused timers consume CPU
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently?  Cannot reproduce in vim 8.1542
- Operating system/version: Arch linux/recent
- Terminal name/version: konsole/17.12.3
- `$TERM`: xterm-256color

### Steps to reproduce:

Here is an example init.vim:
```vim
set nocompatible

if 0     " toggle to enable vim-airline
	let &rtp  = '~/.config/nvim/bundle/vim-airline,' . &rtp
endif

filetype plugin indent on
syntax on 

function! CallBack(tid)
	echo 'callback'
endfunction

let g:timer = timer_start(10, 'Callback',
            \ {'repeat': -1})

call timer_pause(g:timer, 1)

nnoremap <space> :<c-u>call timer_stop(g:timer)<cr>
```

run:
```
nvim -u init.vim init.vim
```
and `htop` or similar.

This is probably related to: https://github.com/neovim/neovim/issues/7871, though that was primarily about a memory leak.

### Actual behavior

- Without vim-airline, neovim consumes 1%--2% CPU.  Pressing space to stop the timer makes the CPU go to 0%.

- With vim-airline, neovim consumes 10%--12% CPU.  Again, pressing space makes the CPU go to 0%.  

To emphasize, I am not claiming this is any bug in vim-airline, but the presence of vim-airline exacerbates the issue many-fold, which may help in determining the cause.

### Expected behaviour

There should be no CPU activity when timers are paused.  In vim, there is apparently no cost to having timers paused.

### PR DESCRIPTION
**Pull request by coditva**
Fix #8188 as suggested by @bfredl [here](https://github.com/neovim/neovim/issues/8188#issuecomment-376448227).

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. Did you confirm that the idle behavior described in #8188 is present before this patch, and not present after?

**Comment by UtkarshMe** [comment]
@justinmk Yes! With and without airline.

**Comment by justinmk** [comment]
LGTM, @bfredl ?

**Comment by bfredl** [comment]
LGTM. Maybe cycle travis once or twice, just to see that timer test flakiness does not obviously increase?

**Comment by UtkarshMe** [comment]
@bfredl How do I do that?

**Comment by bfredl** [comment]
Amend your commit (no code hange needed; it will change the time) and force push the branch.

**Comment by justinmk** [comment]
I already re-ran travis once. One failure does look related:

```
From test_timers.vim:
Found errors in Test_paused():
First run:
function RunTheTest[35]..Test_paused line 20: Expected range 0 - 60, but got 63
Second run:
function RunTheTest[35]..Test_paused line 20: Expected range 0 - 60, but got 68
```

**Comment by UtkarshMe** [comment]
Running the test locally, I get the value to be `51` almost always, and `52` once.

Does this mean that `timer_pause` is taking too long to pause the timer? Or that the timer is running for more time than is intended?

**Comment by justinmk** [comment]
It should be fine to just bump the range a bit.

NB the `WaitFor()` function called by that test, is based on `reltime()` which in Nvim is implemented differently (more precise, always monotonic) than Vim.

**Pull request merged**
