### PR TITLE
fix(build): export symbols on Windows

### LINKED ISSUE #15063: Windows: luajit ffi calls to Nvim core functions broken
- `nvim --version`:
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"
```
- Operating system/version:  Windows 10

### Steps to reproduce

While hitting a [telescope bug](https://github.com/nvim-telescope/telescope.nvim/issues/706) (duplicate [here](https://github.com/nvim-telescope/telescope.nvim/issues/968)) I looked into why luajit ffi calls were failing only on windows.

To repro the bug call a neovim core function using ffi.  I put this in `init.lua`

```lua
local ffi = require('ffi')
ffi.cdef [[
typedef unsigned char char_u;
char_u *__stdcall shorten_dir(char_u *str);
int printf(const char *fmt, ...);
]]

ffi.C.printf("Hello %s!", "world")
local filepath = "C:\\Users\\joe\\.vim\\plugged\\telescope.nvim\\lua\\telescope\\path.lua"
local c_str = ffi.new("char[?]", #filepath + 1)
ffi.copy(c_str, filepath)
ffi.string(ffi.C.shorten_dir(c_str))
ffi.C.printf(c_str)
```

Running nvim on windows gives error `cannot resolve symbol 'shorten_dir': The specified procedure could not be found.`.  I'm told it works on unix.

Adding `__declspec(dllexport)` to the function definition in `src/nvim/path.c` like so fixes the issue.

```c
__declspec(dllexport) char_u *shorten_dir(char_u *str)
```

The above telescope bug can be easily fixed by providing a pure lua version of `shorten_dir`.  However calling neovim core functions from lua could still be useful.  Could we add a `#define` that is set to `__declspec(dllexport)` on windows?  Then marking all neovim core functions with this define? (or selectively export functions that could be useful in lua)

### PR DESCRIPTION
**Pull request by famiu**
Second take on #15989, this time modifying the header generator instead of tampering with the build system.

Closes #15063

### CODE REVIEW

**Comment by famiu** [comment]
The Windows CI checks are showing as queued again, quite problematic. Either way, I don't really see any reason for them to fail this time, personally. I think this PR is ready for review

**Comment by famiu** [comment]
> Seems that the msvc 32 job and that test also fails consistently on my fork. I have no immediate idea of how these changes are causing that. thinking

Would you say it's safe to ignore it, then?

**Comment by famiu** [comment]
In any case, I'll actually squash and rebase this against upstream because I have a hunch that that might fix the issues

**Comment by famiu** [comment]
It seems that actually didn't fix the issue. But looking into the code of the test itself, it seems the test being flaky on MSVC_32 is perfectly normal, so I'd assume it's fine to ignore it. With that said, I think this is ready to be reviewed now.

**Comment by bfredl** [comment]
Error in msvc_32 looks unrelated. Commits need to be squashed. @famiu

**Comment by bfredl** [comment]
doesn't look too involved, let's give it a try.

**Comment by famiu** [comment]
> Does this allow the unit tests to run on Windows CI? #7786 cc @janlazo

It probably does, wouldn't know unless I try though

**Pull request merged**
