### PR TITLE
fix(health): do not run external processes in a shell

### LINKED ISSUE #17267: Weird text in :checkhealth & using neovim as manpager
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

I havent got vim installed

### Operating system/version

Arch Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

compiled from source

### How to reproduce the issue

just open nvim and run :checkhealth 

### Expected behavior

Show me my health status in text I can read

### Actual behavior

unreadable nonsense I have attached an image of what im talking about because im not very good with words also by the way it does the same thing with and without tmux...
maim-full-20220201-215508

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #17267

### CODE REVIEW

**Comment by zeertzjq** [comment]
It is worth writing a test for this?

**Comment by clason** [comment]
if you think about asking, the answer is always _yes_ ;)

**Comment by zeertzjq** [comment]
I wrote a test that fails without the changes. It takes several seconds to run though.

**Comment by clason** [comment]
Maybe disable the provider checks for that test? Those are the ones that take time, at least locally. Or just test a single component -- `:checkhealth nvim` should be pretty fast, and include all the relevant bits.

**Comment by clason** [comment]
OK, then maybe disable all but one provider via `let g:loaded_perl_provider = 0` etc.?

**Comment by zeertzjq** [comment]
Indeed. I disabled perl and python3 providers and the test now only takes less than 0.2 seconds.

**Comment by zeertzjq** [comment]
For the test to fail on master, I think it requires `node` and one of `npm` and `yarn` to be in `PATH`, or `ruby` and `gem` to be both in `PATH`.

**Pull request merged**
