### PR TITLE
fix(treesitter): clear callbacks when destroying language tree

### PR DESCRIPTION
**Pull request by HiPhish**
Recursively removes all registered callbacks from a LanguageTree and its children.  Without this cleanup it is possible for callbacks to accumulate; for example if there is an autocommand to register a callback when attaching to a buffer and the user executes `:edit` the callback will be registered again.  With this change the user can `destroy` the parser when it is detached from the buffer to release the references to the callback functions.

### CODE REVIEW

**Comment by clason** [comment]
Can you describe (in the commit message and the PR description) _what_ this fixes?

**Comment by HiPhish** [comment]
> Can you describe (in the commit message and the PR description) _what_ this fixes?

It fixes the `destroy` method doing nothing. In [HiPhish/nvim-ts-rainbow2](https://github.com/HiPhish/nvim-ts-rainbow2) I register a callback for when the buffer is changed. When the buffer is detached I `destroy` the parser again, but that method does not do anything, even though the documentation says that "Any Cleanup logic should be performed here". Thus the callbacks start accumulating.

**Comment by lewis6991** [comment]
Do they *actually* accumulate though? Once handles are freed on the language tree, the garbage collector should free all the callbacks.

**Comment by HiPhish** [comment]
> Do they _actually_ accumulate though?

Yes, they do, but I was wrong about when it happens. If a buffer is edited by another process like a code formatter callbacks start building up. Maybe I was fixing the problem in the wrong place. I'll come up with a minimal example and open an issue.

**Comment by HiPhish** [comment]
I have opened an issue over at nvim-treesitter, that place seems more appropriate: https://github.com/nvim-treesitter/nvim-treesitter/issues/4994

I guess you can close this PR if what I have implemented does not make any sense.

**Comment by clason** [comment]
I don't see how nvim-treesitter is relevant here; that only handles queries and parser installation.

**Comment by HiPhish** [comment]
Doesn't nvim-treesitter also handle the attaching and detaching and the whole concept of "modules"?

**Comment by clason** [comment]
Not for highlighting. (And modules will be removed soonish.)

**Comment by HiPhish** [comment]
So should I open an issue here?


> And modules will be removed soonish.

Should I then make the plugin standalone independent of nvim-treesitter? There is nothing in the nvim-treesitter documentation indicating that modules are obsolete.

**Comment by clason** [comment]
> So should I open an issue here?
> 
> > And modules will be removed soonish.
> 
> Should I then make the plugin standalone independent of nvim-treesitter? There is nothing in the nvim-treesitter documentation indicating that modules are obsolete.

Long-term, yes. The point right now is that if there is an issue, it needs to be solved on the Neovim side (as this is what handles the low-level language tree).

**Comment by lewis6991** [comment]
It's not clear there is an issue this fixes, so I'm going to close this.

**Pull request closed without merging**
