### PR TITLE
Add support for wl-clipboard when running Wayland

### LINKED ISSUE #9213: Wayland clipboard support
- `nvim --version`: NVIM v0.3.1
- Vim (version: ) behaves differently? No. Also doesn't work under Wayland.
- Operating system/version: Archlinux, gnome-shell 3.30.1 running on wayland 1.16.0-1
- Terminal name/version: Guake 3.3.2-2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# use v to select a range of text
# press "+y
```

### Actual behaviour
Nothing is copied

### Expected behaviour
Text are copied clearly

### More information
There is a project similar to `xclip`, but in wayland named [`wl-clipboard`](https://github.com/bugaevc/wl-clipboard). I was wondering if Neovim can add support to this program.

### PR DESCRIPTION
**Pull request by ainola**
Fixes #9213

### CODE REVIEW

**Comment by ainola** [comment]
To clarify why I added the --no-newline flag, it's to not add a newline automatically:

       -n, --no-newline
              Do not append a newline character after the pasted clipboard content. This option is automatically enabled for non-text content types.

**Comment by ainola** [comment]
Uh, hold on that. This isn't working as I thought it was and I believe that xclip took priority because I had an xwayland server running.

**Comment by the42** [comment]
I am confused whether the patch implements wayland clipboard support or not?

**Comment by ainola** [comment]
See https://github.com/neovim/neovim/commit/05f9c7c2f7f52a5b4b1a72a49dab99dc21195c7d

If one has wl-clipboard installed then yes, if works with compatible Wayland desktops

**Pull request closed without merging**
