### PR TITLE
[RDY] vim-patch:8.0.{998,1383,1792},8.1.{231,235}

### LINKED ISSUE #2867: "vim -?" should display help page, same as "vim -h"
It's commonplace to type "<command_name> -?" to get help on a command-line program.  Vim should support this as well.

While this may be a much more common pattern for MS-DOS/Windows programs than in Unix programs, it's such a common practice that it all but precludes using "-?" as a command-line argument that does something besides "print program usage help to the terminal".

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0998: strange error when using K while only spaces are selected**

Problem:    Strange error when using K while only spaces are selected.
            (Christian J. Robinson)
Solution:   Check for blank argument.
https://github.com/vim/vim/commit/a4f99f5a8b827162a26ca4e4d59f4f224503398a

**vim-patch:8.0.1383: local additions in help skips some files**

Problem:    Local additions in help skips some files. (joshklod)
Solution:   Check the base file name length equals.
vim/vim@35c5e81

**vim-patch:8.0.1792: MS-Windows users expect -? to work like --help**

Problem:    MS-Windows users expect -? to work like --help.
Solution:   Add -?. (Christian Brabandt, closes vim/vim#2867)
vim/vim@c3e8169

**vim-patch:8.1.0231: :help -? goes to help for -+**

Problem:    :help -? goes to help for -+.
Solution:   Add -? to list of special cases. (Hirohito Higashi)
vim/vim@a5bc38b

**vim-patch:8.1.0235: more help tags that jump to the wrong location**

Problem:    More help tags that jump to the wrong location.
Solution:   Add more exceptions and a table for "expr-" tags. (Hirohito
            Higashi)
vim/vim@3bf5e6a

### CODE REVIEW

**Comment by janlazo** [comment]
Lint build failure

```
src/nvim/ex_cmds.c:4709:  Missing space before }  [whitespace/braces] [5]
src/nvim/ex_cmds.c:4710:  Missing space after {  [whitespace/braces] [5]
src/nvim/ex_cmds.c:4711:  Missing space before }  [whitespace/braces] [5]
```

I do not want to fix these errors atm (unless I go all the way with `const`).

**Comment by justinmk** [comment]
Restarted appveyor build, which took 1 hr...

**Comment by janlazo** [comment]
Travis failure
```
[----------] Running tests from /home/travis/build/neovim/neovim/test/functional/core/startup_spec.lua
[ RUN      ] startup output to pipe: has("ttyin")==1 has("ttyout")==0: 39.17 ms OK
test/helpers.lua:95: cannot open ./Xtest-tmpdir/nvim8ykiID: No such file or directory
stack traceback:
	test/helpers.lua:95: in function 'glob'
	test/helpers.lua:273: in function 'check_cores'
	test/functional/helpers.lua:750: in function <test/functional/helpers.lua:745>
```

Lint bulid failed because of false positive. `"/*"` is treated as a comment.

**Comment by justinmk** [comment]
That travis failure is a bug in `check_cores`. It's supposed to ignore `Xtest-tmpdir` ... :(

**Pull request merged**
