### PR TITLE
Windows: remove env var if set to empty string

### PR DESCRIPTION
**Pull request by erw7**
Seprated from #10662.

### CODE REVIEW

**Comment by blueyed** [comment]
`Test_WindowsHome` passes.

(
However, the commit message appears to trigger another failure:
```
From test_environ.vim:
Found errors in Test_external_env():
function RunTheTest[37]..Test_external_env line 16: Expected '' but got 'APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED=On Windows, set FOO=deletes the environment variable FOO, and there is\\nno way to set an empty environment variable other than calling the API.\\nAlso in vim, let $ FOO='''' deletes the environment variable. Because of\\nthese things, nvim has been changed to do the same.\\nTest_WindowsHome () requires this change.\n'
```
https://github.com/neovim/neovim/blob/45d678529369710a9b0fc0b6a3ede580e53d65cc/src/nvim/testdir/test_environ.vim#L37-L43
https://ci.appveyor.com/project/neovim/neovim/builds/26614641/job/4bhl8hg57ndc64vj?fullLog=true#L17111
)

**Comment by blueyed** [comment]
> let result = system('set | grep ^FOO=') 

So this is not anchored to the beginning of the line on Windows?

**Review by blueyed — APPROVED** [review]
Commit message should be edited - use backticks for identifiers when merging.

**Comment by justinmk** [comment]
> > let result = system('set | grep ^FOO=')
> 
> So this is not anchored to the beginning of the line on Windows?

In cmd.exe, `^` is the [escape char](https://ss64.com/nt/syntax-esc.html) (like `\` in unix shells).

Does Vim ship `grep.exe` now...?

**Comment by blueyed** [comment]
Vim uses `let result = system('set | findstr "^FOO="')`.
Via https://github.com/blueyed/vim/commit/ddd3308782e931a2c390d692cb23c40d8169bd6f and https://github.com/blueyed/vim/commit/c974022c31e790136c62586eb0b0ace2d02d2afb

**Pull request merged**
