### PR TITLE
Add cmd mods and count to `:InspectTree`

### LINKED ISSUE #22656: `vim.treesitter.inspect_tree()` does not respect `'splitright'`
### Problem

With the option `splitright` set, new window should split to the right of the current window. `vim.treesitter.inspect_tree()` opens on the left.

(nvim-treesitter/playground however works as expected and splits on the right)

### Steps to reproduce

I couldn't get treesitter to start with `nvim --clean`, but:

```
$ nvim +'h news'
:set splitright
:lua vim.treesitter.inspect_tree()
```

### Expected behavior

Inspection tree opens on the right

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1222+gf01f18cdf-dirty

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2 3.4.19

### $TERM environment variable

tmux-256color

### Installation

homebrew upgrade --fetch-HEAD neovim

### PR DESCRIPTION
**Pull request by yochem**
Also changes the default of the `command` option of `vim.treesitter.inspect_tree()` from `topleft 60vnew` to `60vnew`.

See discussion at #22656. Closes #22656.

Do I need to write documentation for `:InspectTree`? That it accepts a count as window size and the modifiers?

### CODE REVIEW

**Comment by yochem** [comment]
After seeing that the call-regen-api-docs/regen-api-docs failed, I ran `./scripts/gen_vimdoc.py`, but got this error:

```
Traceback (most recent call last):
  File "/private/tmp/neovim/./scripts/gen_vimdoc.py", line 1263, in <module>
    main(Doxyfile, args)
  File "/private/tmp/neovim/./scripts/gen_vimdoc.py", line 1136, in main
    fail(f'no sections for target: {target} (look for errors near "Preprocessing" log lines above)')
  File "/private/tmp/neovim/./scripts/gen_vimdoc.py", line 344, in fail
    raise RuntimeError(s)
RuntimeError: no sections for target: api (look for errors near "Preprocessing" log lines above)
```

Anybody an idea?

**Comment by clason** [comment]
Do you have doxygen installed?

**Comment by yochem** [comment]
Yes I have: 

```
$ doxygen -V
1.9.6
```

**Comment by clason** [comment]
That was my idea.

**Comment by clason** [comment]
You can of course also edit the treesitter.txt file manually to match.

**Comment by clason** [comment]
The first should be enough, and works fine for me.

**Comment by yochem** [comment]
> You can of course also edit the treesitter.txt file manually to match.

Current solution. Let's see if it works

**Comment by ii14** [comment]
I have no idea if that will help, but maybe try rebuilding neovim? It's used in the script.

**Comment by yochem** [comment]
Thanks! I indeed tried to rebuild neovim (by just running `make`), but that didn't help

**Review by justinmk — APPROVED** [review]

**Pull request merged**
