### PR TITLE
shada: Save current cursor position before saving jumps

### PR DESCRIPTION
**Pull request by ZyX-I**
Ref https://github.com/neovim/neovim/issues/5078#issuecomment-233178212

### CODE REVIEW

**Comment by justinmk** [comment]
Some shada tests are failing.

**Comment by justinmk** [comment]
@ZyX-I Does this address https://github.com/neovim/neovim/issues/5875 / https://github.com/neovim/neovim/issues/3472

**Comment by ZyX-I** [comment]
This does not deal with numbered marks.

**Comment by justinmk** [comment]
```
error: [m[Kalways_inline function might not be inlinable [-Werror=attributes]
 static ShadaEntry shada_get_buflist(khash_t(bufset) *const removable_bufs)
```

**Comment by justinmk** [comment]
QB failure looks like an intermittent unrelated failure:

```
Uncaught Error: ...ated/.deps/usr/share/lua/5.1/nvim/msgpack_rpc_stream.lua:84: invalid msgpack-rpc  string
18:31:20,166 WARN  -     test/functional/ex_cmds/global_spec.lua:53: in function <test/functional/ex_cmds/global_spec.lua:49
```

It's failing [here](https://github.com/neovim/neovim/blob/9009c20edb066811417aa1a044e643f1d4050f7c/test/functional/ex_cmds/global_spec.lua#L53) (note: that test was changed, now lives in `ctrl_c_spec.lua`). I wonder if nvim printed something to the stdout pipe or died for some reason.

**Pull request merged**
