### PR TITLE
feat(lsp)!: support multiple clients in goto methods

### LINKED ISSUE #30737: LSP: jump_to_location: "Cursor position is out of buffer"
### Problem

Context: I'm working in a Typescript React project, and I have the following line:

`import s|tyle from page-styles/home.module.scss`

My cursor is on style and when I press `gd`, I get the following error:

```
   Error  11:53:21 msg_show.lua_error Error executing vim.schedule lua callback: .../username/nvim-macos/share/nvim/runtime/lua/vim/lsp/util.lua:1142: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	.../username/nvim-macos/share/nvim/runtime/lua/vim/lsp/util.lua:1142: in function 'jump_to_location'
	...e/nvim-macos/share/nvim/runtime/lua/vim/lsp/handlers.lua:443: in function 'handler'
	...ame/nvim-macos/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

It takes me to the file nonetheless but it shows this error only once. When I press `gd` again it doesn't pop up anymore.

Inside the `util.lua` file under the `show_document` function, I commented out this line (line 1142):

`--api.nvim_win_set_cursor(win, { row + 1, col })`

Now I don't get the error at all. However, when I want to `gd` to some other thing like `React.useState`, it takes me to the declaration file, but doesn't take me to the declared function.

### Steps to reproduce

With this line (line 1142 in util.lua) commented out: `--api.nvim_win_set_cursor(win, { row + 1, col })`

"|" is going to be the user's cursor.

CSS/SCSS Files GoTo Definition: 
1. `import s|tyle from page-styles/home.module.scss` (or anything involving css/scss files)
2. press `gd` (goto Definition)
3. Correctly goes to file without error

For Typescript files:
1. `import R, { useEffect, use|State } from 'react'
2. press `gd`
3. No error
4. Either it doesn't go to the file or takes me to the wrong line in the `react/index.d.ts` file

### Expected behavior

Goto definition of file without showing "Cursor position is out of buffer" error.

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.0

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by mfussenegger**
Relates to:

- https://github.com/neovim/neovim/issues/30034
- https://github.com/neovim/neovim/issues/17712
- https://github.com/neovim/neovim/issues/16363

Closes:

- https://github.com/neovim/neovim/issues/26936 (but only provides bufnr
  and method)
- https://github.com/neovim/neovim/issues/22318

Might fix: https://github.com/neovim/neovim/issues/30737

### CODE REVIEW

**Review by MariaSolOs — APPROVED** [review]
Could we add a test for this? :)

**Comment by mfussenegger** [comment]
> Could we add a test for this? :)

done. Looks like this was generally not tested.

**Comment by MariaSolOs** [comment]
> done. Looks like this was generally not tested.

Thx! LGTM

**Comment by zeertzjq** [comment]
Is it intended that these methods no longer set tagstack?

**Comment by mfussenegger** [comment]
> Is it intended that these methods no longer set tagstack?

No that wasn't intentional. I missed that it did that. I'll follow up on re-adding that.

**Comment by mfussenegger** [comment]
> > Is it intended that these methods no longer set tagstack?
> 
> No that wasn't intentional. I missed that it did that. I'll follow up on re-adding that.

Done with https://github.com/neovim/neovim/pull/30927

**Pull request merged**
