### PR TITLE
[RFC] clang-format configuration

### PR DESCRIPTION
**Pull request by justinmk**
Recommend by @oni-link at:
https://github.com/neovim/neovim/pull/487#issuecomment-39935391

These settings seem OK based on some brief testing. If anyone knows better, let me know.

### CODE REVIEW

**Comment by ZyX-I** [comment]
I checked it on `shada.h` and got

```C
--- src/nvim/shada.h    2015-12-20 03:42:55.378746400 +0300
+++ /proc/self/fd/11    2016-03-02 12:56:05.993023448 +0300
@@ -5 +5 @@
-# include "shada.h.generated.h"
+#include "shada.h.generated.h"
@@ -7 +7 @@
-#endif  // NVIM_SHADA_H
+#endif // NVIM_SHADA_H
```

**Comment by ZyX-I** [comment]
Though wait, I found it complaining about invalid style, even though `clang-format --help` explicitly allows `-style=src/.clang-format`.

**Comment by ZyX-I** [comment]
So this diff is for LLVM style.

**Comment by ZyX-I** [comment]
`clang-format -style=file` produces

```Patch
--- src/nvim/shada.h    2015-12-20 03:42:55.378746400 +0300
+++ /proc/self/fd/11    2016-03-02 13:00:41.677062756 +0300
@@ -5 +5 @@
-# include "shada.h.generated.h"
+#include "shada.h.generated.h"
```

**Comment by ZyX-I** [comment]
And *very* huge diff on shada.c: https://bpaste.net/show/b0296b55fadc.

**Comment by ZyX-I** [comment]
And here is what linter thinks about formatted file:

```
src/nvim/shada.c.f.c:445:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:445:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:452:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:452:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:485:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:485:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:782:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:783:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1010:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:1010:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:1016:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:1020:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1021:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1022:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:1116:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1267:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1270:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1272:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1273:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1274:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1275:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1276:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1270:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1272:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1273:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1270:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1272:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1273:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1275:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1276:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1329:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1330:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1353:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1407:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1408:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1463:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1463:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1475:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1477:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1718:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1719:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1733:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1734:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1755:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1756:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1765:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1766:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1767:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1768:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1769:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1770:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1771:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1772:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1773:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1774:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1776:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1778:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1779:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1778:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1779:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1816:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1817:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1818:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1819:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1821:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1823:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1824:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1823:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1824:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1837:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1838:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1849:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1850:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1851:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1853:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1854:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1855:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1854:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1855:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1879:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1880:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1882:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1885:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1886:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1887:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1888:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1886:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1887:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1888:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1888:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:1895:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:1900:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2095:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2112:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2113:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2114:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2115:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2201:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2202:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2203:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2204:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2205:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2212:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2213:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2263:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:2264:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:2361:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2361:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2501:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
src/nvim/shada.c.f.c:2598:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2610:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2629:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2631:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2633:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2649:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:2655:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2657:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2661:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2723:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2725:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2731:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2760:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2762:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2766:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2775:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2777:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2780:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:2878:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2879:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2883:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2878:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2879:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:2883:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3051:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3052:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3053:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3054:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3053:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3054:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3119:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3120:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3121:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3272:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3275:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3350:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
src/nvim/shada.c.f.c:3389:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3390:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3391:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3408:  An else should always have braces before it  [readability/braces] [5]
src/nvim/shada.c.f.c:3412:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3418:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3419:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3425:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:3426:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:3428:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:3445:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:3446:  Missing space after {  [whitespace/braces] [5]
src/nvim/shada.c.f.c:3449:  Missing space before }  [whitespace/braces] [5]
src/nvim/shada.c.f.c:3531:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3560:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3694:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3709:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3710:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]
src/nvim/shada.c.f.c:3771:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3772:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3778:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3779:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3885:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3948:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/shada.c.f.c:3949:  Inner expression indentation should be 4  [whitespace/indent] [2]
Total errors found: 170
```

**Comment by ZyX-I** [comment]
Changing `ContinuationIndentWidth: 2` to 4 reduces number of linter errors to 133.

**Comment by ZyX-I** [comment]
Have not found a way to tell it to format initializer lists with spaces. It has SpacesInAngles, CStyleCastParenthesis, ContainerLiterals, Parenthesis, SquareBrackets, but nothing for brace initializers.

**Comment by ZyX-I** [comment]
Original .clang-format file results in 194 errors printed by clint.py.

**Comment by justinmk** [comment]
@ZyX-I Thanks. I was thinking at least it would be useful for formatting regions, as a start.

**Comment by justinmk** [comment]
Added `ContinuationIndentWidth: 4` and `SpacesInSquareBrackets: true`.

**Pull request merged**
