### PR TITLE
ci: coverage for Lua (without Windows, using luacov)

### PR DESCRIPTION
**Pull request by blueyed**
Pulled out of https://github.com/neovim/neovim/pull/10426.
Windows is not working there (likely a Codecov issue), and it is good to have a base for when adding it.

### CODE REVIEW

**Comment by blueyed** [comment]
luacov is slowing the coverage job down - taking >25min already.
cluacov is meant to help here, but I wanted to try plain luacov since I got the impression cluacov might have issues with line offsets.

**Comment by blueyed** [comment]
This takes > 40min already..

```
[----------] Running tests from test/unit/mbyte_spec.lua
[ RUN      ] mbyte utf_ptr2char: 14595.31 ms OK
[ RUN      ] mbyte utf_char2bytes for chars 0x0 - 0xfff: 480951.19 ms OK
[ RUN      ] mbyte utf_char2bytes for chars 0x1000 - 0x1fff: 485898.82 ms OK
[ RUN      ] mbyte utf_char2bytes for chars 0x2000 - 0x2fff: 483671.63 ms OK
[ RUN      ] mbyte utf_char2bytes for chars 0x3000 - 0x3fff: 
```

**Comment by blueyed** [comment]
Travis gcov:

> Ran for 33 min 4 sec

Quite slower.  cluacov should help, but I'd like to compare if results are the same.

Hopefully codecov reports here, and then I'll push cluacov again.

**Comment by h-michael** [comment]
@blueyed 
When I run `make functionaltest BUSTED_ARGS='-coverage'`, I get an error like this:
```
-- Output to stderr:
busted: error: LuaCov not found on the system, try running without --coverage option, or install LuaCov first

CMake Error at /home/neovim/cmake/RunTests.cmake:85 (message):
  functional tests failed with error: 1
```

I'm running `luarocks install cluacov` before doing this.

```
$ luacov -h
LuaCov 0.13.0 - coverage analyzer for Lua scripts
```

How did you run luacov debugging on your local machine?
By the way, I use Arch linux.

**Comment by h-michael** [comment]
I could run once with this workaround for the time being. :)

```diff
diff --git a/third-party/cmake/BuildLuarocks.cmake b/third-party/cmake/BuildLuarocks.cmake
index 7551c52ec..dd1f03ba5 100644
--- a/third-party/cmake/BuildLuarocks.cmake
+++ b/third-party/cmake/BuildLuarocks.cmake
@@ -129,6 +129,14 @@ add_custom_command(OUTPUT ${ROCKS_DIR}/lpeg
 add_custom_target(lpeg DEPENDS ${ROCKS_DIR}/lpeg)
 list(APPEND THIRD_PARTY_DEPS lpeg)

+# cluacov
+add_custom_command(OUTPUT ${ROCKS_DIR}/cluacov
+  COMMAND ${LUAROCKS_BINARY}
+  ARGS build cluacov ${LUAROCKS_BUILDARGS}
+  DEPENDS cluacov)
+add_custom_target(cluacov DEPENDS ${ROCKS_DIR}/cluacov)
+list(APPEND THIRD_PARTY_DEPS cluacov)
+
 if((NOT USE_BUNDLED_LUAJIT) AND USE_BUNDLED_LUA)
   # luabitop
   add_custom_command(OUTPUT ${ROCKS_DIR}/luabitop
```

**Comment by blueyed** [comment]
@h-michael 
Make sure to use the same LuaRocks for busted/luacov (if bundled, use `.deps/usr/bin/luarocks`).
I.e. if bundled, you should install it there (that's what your workaround is doing).

**Comment by h-michael** [comment]
@blueyed I see. Thanks :)

**Pull request merged**
