### PR TITLE
[RFC] vim-patch: mark some patches as NA

### PR DESCRIPTION
**Pull request by cztchoice**
The head of vim patches goes to 729 ([vim commit list](https://code.google.com/p/vim/source/list)) and I mark some obvious NA patches(between 713 and 729) as NA

Follow @jusga suggest below(https://github.com/neovim/neovim/pull/2672#issuecomment-102631515), mark 705, 681, 679, 677, 676, 674, 669, 663, 657 as NA.
Follow the advice in https://github.com/neovim/neovim/pull/2624#issuecomment-100563929 by @justinmk 

NA patches
- [patch 7.4.728](https://github.com/vim/vim/commit/dce1a496bdb61784f2b725c754b90b613bef8bcb)
- [patch 7.4.727](https://github.com/vim/vim/commit/47eaebe4a0223727e572ef4ff63cc79df819bdfc)
- [patch 7.4.726](https://github.com/vim/vim/commit/9edbede50ed1d18cba926c62bc29751ca1aa72cb)
- [patch 7.4.724](https://github.com/vim/vim/commit/ea5a8df970e037adeab0124f8cc8bd68984cdf27)
- [patch 7.4.720](https://github.com/vim/vim/commit/f4e02f7c79d4d0148e243fd45056b3e0d227333d)

### CODE REVIEW

**Comment by oni-link** [comment]
LGTM.

**Comment by jusga** [comment]
While you're at it you could also mark the following patches as NA:
* https://github.com/vim/vim/commit/v7-4-705 modifies removed file `if_ruby.c`
* https://github.com/vim/vim/commit/v7-4-681 modifies removed file `gui_w32.c`
* https://github.com/vim/vim/commit/v7-4-679 modifies removed file `os_win32.c`
* https://github.com/vim/vim/commit/v7-4-677 modifies build files
* https://github.com/vim/vim/commit/v7-4-676 modifies build files
* https://github.com/vim/vim/commit/v7-4-674 modifies removed file `os_win32.c`
* https://github.com/vim/vim/commit/v7-4-669 NetBeans interface
* https://github.com/vim/vim/commit/v7-4-663 NetBeans interface
* https://github.com/vim/vim/commit/v7-4-657 adds a cast to fix a compiler warning

**Comment by cztchoice** [comment]
@jusga mark the patch you suggest  as NA

@oni-link Sorry for disturb you, I add a commit, can you review it again? Thanks.

**Comment by Pyrohh** [comment]
Hi @cztchoice,

Could you please make the commit message follow this style, or similar: https://github.com/glts/neovim/commit/a0a60e6e97625393bdcbfd2639b471955a103532

As it is, there's nothing in the commit messages, making it harder to review because everyone has to manually look up all these patches (and related, `git {log,blame}` becomes less useful).

**Comment by Pyrohh** [comment]
Besides that, these two commits can most likely be squashed given their relation, and I don't think that bumping the patch head needs to be mentioned either (it's only a side effect of marking things NA, not the primary reason for the commit).

**Comment by oni-link** [comment]
Besides what @Pyrohh said, LGTM.

**Comment by cztchoice** [comment]
@Pyrohh squash them and change the commit message.
Thank you for your advice. Can you please review it again?

**Comment by glts** [comment]
LGTM, too.

**Comment by Pyrohh** [comment]
Merged, thanks everyone.

**Pull request closed without merging**
