### PR TITLE
[RDY] Fix functional test suite hang when a test fails

### PR DESCRIPTION
**Pull request by tarruda**
[ref](https://github.com/neovim/neovim/issues/1519#issuecomment-68635088)

### CODE REVIEW

**Comment by tarruda** [comment]
@jszakmeister @elmart @justinmk How is this branch on OSX?

**Comment by bfredl** [comment]
This fixes some failures when enabling "strict mode" (#1835) for mouse testing :+1:

**Comment by tarruda** [comment]
> This fixes some failures when enabling "strict mode" (#1835) for mouse testing :+1:

Great, I'm gonna merge this since this will probably fix [this error](https://github.com/neovim/neovim/pull/1572#issuecomment-71183179) reported by @fwalch

**Comment by elmart** [comment]
Will check tomorrow. Not at home now.

**Comment by elmart** [comment]
But I think test were not hanging for me on Yosemite.

**Comment by jszakmeister** [comment]
:+1: This did the trick @tarruda!  Thank you!

Just the "ctrl left click" mouse spec test fails now, and no hangs (though I did try to induce one by making several tests fail).

**Pull request merged**
