### PR TITLE
[WIP] Enable -Wconversion: charset.c

### PR DESCRIPTION
**Pull request by codonnell**
Just creating this PR now so no one tries to duplicate my work.

### CODE REVIEW

**Comment by codonnell** [comment]
I'd love some advice about how to handle some details of this conversion.

This file modifies a global array, `chartab`. This array consists of unsigned chars, each of which is used as a byte to store a few attributes of the character. Some bit arithmetic is done with mask constants to set attributes. These masks are macros (eg. `#define CT_ID_CHAR 0x20`), so they default to `int` type. Would it be a better to add a cast to the macros or change the type of the array itself?

**Comment by elmart** [comment]
On a quick glance, I'd say the optimal thing would be to redefine constants to character constants. This is, `#define CT_ID_CHAR 0x20` to `#define CT_ID_CHAR '\x20'`.
I haven't carefully looked at the code, though. So, if that poses any problem, please report.

**Comment by codonnell** [comment]
Thanks; I'll give that a try.

**Comment by codonnell** [comment]
If the masks are unsigned chars, the compiler complains about the expression `1 + CT_ID_CHAR`. Since there are no unsigned char literals, the only way to avoid a warning would be `(char_u)(1) + CT_ID_CHAR`, which is pretty ugly.

**Comment by Pyrohh** [comment]
Given that just booleans have been changed so far, I'll close this. Feel free to reopen @codonnell if/when you plan on working on this.

**Pull request closed without merging**
