### PR TITLE
tests: Use our own output handler on travis

### PR DESCRIPTION
**Pull request by ZyX-I**
Reasoning:

1. gtest is better then something like utfTerminal, yet it is way too verbose.
2. gtest cannot be configured to show colors always.
3. Actually I am going to add a CMake target which will allow running tests 
   (especially, functional tests) in parallel, but this is not going to work 
   well with any of the default output handlers. Build in this case must be more 
   or less silent, yet debuggable. New handler does not support this in this 
   commit though.
4. Constructing a regex to search for failures should be easier with new variant (just `FAIL$` and `ERR$`).

Output looks like this:

successfull output

or this:

all kinds

### CODE REVIEW

**Comment by ZyX-I** [comment]
If travis output will be nice then this may be considered ready: no parallel building in this PR. Not sure whether changes for AppVeyor are welcome: there output should be the same as on screenshots, except that without any colors, providing less benefits thus.

Also what do you think about *duplicating* error messages in the summary? The result would look like this:

duplicate error descriptions

, except that imagine a few hundred additional lines between last failure and suite end.

Note: *must* duplicate and not leave errors only in one place or developers will miss errors if busted crashes.

**Comment by justinmk** [comment]
This will be really nice. One regression is that the [plain text](https://s3.amazonaws.com/archive.travis-ci.org/jobs/220380832/log.txt) version is more noisy now. I never use the travis colored version because it is extremely slow. 

I can live with that. But OTOH colors aren't really important for the individual test listings: there are so many tests, no one visually inspects them, only searches them. So omitting colors there saves log file size, and makes the log files less noisy when viewed via `:edit https://s3.amazonaws.com/archive.travis-ci.org/jobs/220380832/log.txt`.

- "nvim" not "neovim"
- I don't think `busted/` deserves a top-level directory, but I guess it avoids extra configuration. Eventually it might be worth sending upstream to busted...

**Comment by ZyX-I** [comment]
It appears that between 2.0.rc12-1 and 2.0.rc11-0 a refactoring was made: https://github.com/Olivine-Labs/busted/commit/e206c9ccf24dd6e714513d2f573f1c1226e93948.

**Comment by justinmk** [comment]
Do we need to upgrade busted? (Would rather do that than have code that depends on the older version)

**Comment by ZyX-I** [comment]
@justinmk I usually inspect the result either from browser (where I could use colors to visually find failures because browser search is not as good as less with PCRE support and I usually find something which is not a failure in addition to failures) or from `travis logs --interactive … | less`. In both cases colored test are easier to work with and this is not tainting searches. Local tests were using `utf` handler from some very very old issue (not sure how it was named there), but that lacks e.g. per-file and per-test timing and also errors are not printed right there.

**Comment by ZyX-I** [comment]
(From browser: I mean, from travis web interface, not string logs. I actually do not know an easy way to get the link, except for going to that interface, entering the job and finding that somewhere in the header: could just as well stay in the interface.)

**Comment by ZyX-I** [comment]
@justinmk Actually I do not know where you are getting this links from. “Link in the header” which travis provides is https://api.travis-ci.org/jobs/220386954/log.txt?deansi=true (also without `?deansi=true`: note you can have logs without colors here!), not something on amazonaws, some our bot/whatever copies logs there?

**Comment by ZyX-I** [comment]
In web interface that is not as good:

dim not working properly

, yet better then what it was before. Also more lines do not wrap.

**Comment by ZyX-I** [comment]
About upstream: note that one of the targets is adding silent and log options to `nvim` output handler: to silence busted so it would not mess the screen up when doing parallel build, yet still be able to determine where busted hang (local builds only, even if enabled on travis it better mess up the screen then fail the build); errors still printed always: normally they do not risk messing anything up. I am very unsure this would be accepted, busted upstream was talking about using threads for parallel builds and not willing to provide even separate processes like we have in unit tests.

**Comment by ZyX-I** [comment]
I mean that it is less likely to be accepted because of being part of the solution to “we want to run tests in parallel” problem which threads should solve as well: who wants merging code which aims at solving the problem in a different way then you aim to solve it?

**Comment by justinmk** [comment]
https://api.travis-ci.org/jobs/220386954/log.txt?deansi=true for me redirects to s3.amazonaws link given above (and I don't have any browser extensions). `deansi=true` stopped working, for me, 1+ years ago.

Maybe I can find some tool that performs "deansi". Not a big deal anyways.

**Comment by ZyX-I** [comment]
@justinmk Just pipe to less: it will not remove colors, but it will show them as colors and not as escapes (assuming you provide it with proper arguments). Or use travis gem, if you pipe its output not to a tty (or use explicit `--no-interactive`) it will strip out colors. Do not dump our builds to terminal though, oldtests may mess things up.

**Comment by ZyX-I** [comment]
It appears that there are no busted on AppVeyor now:

```
[ 95%] Generating usr/bin/busted.bat
call usr\2.2\luarocks.bat build https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc12-1/busted-2.0.rc12-1.rockspec CC=C:/msys64/mingw32/bin/gcc.exe LD=C:/msys64/mingw32/bin/gcc.exe
Using https://luarocks.org/luasystem-0.2.1-0.src.rock... switching to 'build' mode
C:/msys64/mingw32/bin/gcc.exe -O2 -c -o src/core.o -IC:/projects/neovim/.deps/usr/include/luajit-2.0/ src/core.c -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
C:/msys64/mingw32/bin/gcc.exe -O2 -c -o src/compat.o -IC:/projects/neovim/.deps/usr/include/luajit-2.0/ src/compat.c -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
C:/msys64/mingw32/bin/gcc.exe -O2 -c -o src/time.o -IC:/projects/neovim/.deps/usr/include/luajit-2.0/ src/time.c -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
C:/msys64/mingw32/bin/gcc.exe -shared -o system/core.dll src/core.o src/compat.o src/time.o C:/projects/neovim/.deps/usr/lib/lua51.dll -lm
Updating manifest for C:/projects/neovim/.deps/usr/lib/luarocks/rocks
luasystem 0.2.1-0 is now built and installed in C:/projects/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)
Using https://luarocks.org/lua_cliargs-3.0-1.src.rock... switching to 'build' mode
Updating manifest for C:/projects/neovim/.deps/usr/lib/luarocks/rocks
lua_cliargs 3.0-1 is now built and installed in C:/projects/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)
Checking stability of dependencies on the absence of
lua_cliargs 2.5-5...
Updating manifest for C:/projects/neovim/.deps/usr/lib/luarocks/rocks
busted 2.0.rc12-1 is now built and installed in C:/projects/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)
Checking stability of dependencies on the absence of
busted 2.0.rc11-0...
Removing busted 2.0.rc11-0...
Removal successful.
Missing dependencies for busted:
luasystem >= 0.2.0-0
lua_cliargs == 3.0-1
Will not remove lua_cliargs 2.5-5.
Removing it would break dependencies for: 
busted 2.0.rc11-0
Use --force to force removal (warning: this may break modules).
```

It already removed busted, WTF is that thinking of by failing the removal of lua_cliargs with that reason?!

**Comment by ZyX-I** [comment]
@justinmk Can you remove AppVeyor cache? It should do the trick if I am not mistaking, forcing luarocks to do its job using other means is not the best idea I think. Also can I have access to remove cache myself?

**Comment by justinmk** [comment]
APPVEYOR_CACHE_SKIP_RESTORE seems to have worked. I don't see a UI to delete cache, see https://www.appveyor.com/docs/build-cache/#remove-cache-entry-from-build-config

> Not sure whether changes for AppVeyor are welcome: there output should be the same as on screenshots, except that without any colors, providing less benefits thus.

It would be an improvement on AppVeyor since it reduces the number of lines in the logs. If AppVeyor  had built-in support for TAP then gtest _would_ be useful there, but it doesn't.

> Also what do you think about duplicating error messages in the summary? 

I think that would be helpful.

**Comment by ZyX-I** [comment]
I removed the new `fix!` commit and added a commit which alters AppVeyor output handler. Hope it will not use cache in a state from the previous commit.

**Comment by justinmk** [comment]
I think [this line](https://github.com/neovim/neovim/blob/master/appveyor.yml#L10) should be changed to:

    - .deps -> third-party/**

**Comment by justinmk** [comment]
No longer [WIP]?

**Comment by ZyX-I** [comment]
I do not want to add anything else to the PR.

**Pull request merged**
