### PR TITLE
build: downgrade luarocks version from 3.9.2 to 3.8.0

### LINKED ISSUE #22752: Update windows build instructions
### Problem

Building mpack dependency requires md5sum, openssl or md5:

    Error: Failed producing checksum: no MD5 checker tool available, please install md5sum, openssl or md5 in your system

### Steps to reproduce

Build with MSVC Powershell:
```
cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build .deps
```

### Expected behavior

Avoid dependency or update build instructions @dundargoc

Fix typo https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc-powershell step 3:
```diff
- cmake -B build -G Ninja CMAKE_BUILD_TYPE=RelWithDebInfo
+ cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo
```

### Neovim version (nvim -v)

NVIM v0.9.0-dev-701+g34b973b1d9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 11

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

### PR DESCRIPTION
**Pull request by dundargoc**
Luarocks 3.9.0+ gives a false "Error: Failed producing checksum: no MD5
checker tool available" error, even if luarocks itself is bundled with a
MD5 checker.

Fixes https://github.com/neovim/neovim/issues/22752.

### CODE REVIEW

**Comment by dundargoc** [comment]
I think @erw7 has pretty much identified the problem in https://github.com/luarocks/luarocks/issues/1443#issuecomment-1483816481. The problem with that is that even if we solve this problem in luarocks there's no telling how long it'll take before they cut a new release.

**Comment by justinmk** [comment]
Let's include @erw7 's [analysis](https://github.com/luarocks/luarocks/issues/1443#issuecomment-1483816481) in the commit message . The references to Luarocks commits/code will be useful when we revisit this in the future, especially if the issue is not resolved for awhile.

**Comment by clason** [comment]
Just to be sure: 3.8.0 is the last good version? We can't at least bump part of the way?

**Comment by dundargoc** [comment]
Unfortunately not.

**Comment by dundargoc** [comment]
Hmm, actually, wonder why this is only triggered for mpack and not any other rocks. We might be able to change something in the mpack rock instead to work around this issue?

**Comment by dundargoc** [comment]
Solved by https://github.com/neovim/neovim/pull/22872

**Pull request closed without merging**
