### PR TITLE
ci/travis: macOS: switch ruby version

### PR DESCRIPTION
**Pull request by justinmk**
Travis macOS builds are failing because of neovim-ruby gem dependencies.
Switch default ruby to a newer version to make the builds pass.

### CODE REVIEW

**Comment by justinmk** [comment]
```
RVM is not a function, selecting rubies with 'rvm use ...' will not work.
You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.
/Users/travis/.rvm/bin/rvm: line 66: shell_session_update: command not found
```

**Comment by janlazo** [comment]
Try upgrading rubygems as well so it matches with the ruby from rvm.

**Comment by justinmk** [comment]
can you give the exact command you mean?

Note that https://github.com/neovim/neovim/pull/7820/commits/e2523f217d86f1d646b4fb205923eb299da5d1ab worked.

**Comment by janlazo** [comment]
I thought `rvm gem update --system` in before_install.sh and `rvm gem install neovim` in install.sh were required to get the right ruby + rubygems combination.

**Comment by justinmk** [comment]
So now it's installing correctly, but even after doing the dance _also_ in `before_script.sh`, something is still wrong:

```
[32m[2m[----------][0m[0m [1m1[0m test from [36m/Users/travis/build/neovim/neovim/test/functional/provider/ruby_spec.lua[0m [2m(17.98 ms total)[0m
```

At this point I don't care, there's nothing about ruby_spec.lua that needs macOS testing. We can just skip it there.

**Comment by justinmk** [comment]
31mPlease note that `rvm gem ...` was removed, try `gem update --system` or `rvm all do gem update --system` instead

**Comment by justinmk** [comment]
@janlazo Thanks! I'm going to skip it for now. PR appreciated if you feel like giving it a try. I left the `macos_rvm_dance` shell function in there for future use.

**Comment by janlazo** [comment]
Does the ruby version have to 2.2.5? https://docs.travis-ci.com/user/installing-dependencies/#using-homebrew-without-addon-on-older-macos-images mentions 2.3 for homebrew. https://github.com/neovim/neovim-ruby/blob/master/.travis.yml has `ruby-head` and `2.5` so we can use the latest stable version of ruby to avoid updating the version every year.

**Comment by mhinz** [comment]
@janlazo 

If you're referring to `macos_rvm_dance()`, we don't use it anymore. It should be removed. Feel free to add `rvm: 2.5` to our macOS jobs on Travis.

**Pull request merged**
