### PR TITLE
[RFC] tests: Fix test setup/teardown in path_spec.lua

### PR DESCRIPTION
**Pull request by glts**
Typo in `path_spec.lua` test.

@splinterofchaos, could you please check?

### CODE REVIEW

**Comment by splinterofchaos** [comment]
Oops, I really should have been more careful. Nice catch.

Actually, could you change the `lfs.mkdir`s to
```lua
before_each(function() lfs.mkdir('CamelCase') end)
after_each(function() lfs.rmdir('CamelCase') end)
```
*that*`'s what I should have done. Thanks.

**Comment by glts** [comment]
@splinterofchaos done, thanks.

**Comment by splinterofchaos** [comment]
LGTM :+1:

**Comment by Pyrohh** [comment]
LGTM

**Comment by justinmk** [comment]
merged

**Pull request closed without merging**
