### PR TITLE
vim-patch:7.4.1967

### LINKED ISSUE #867: Automatic regular expression engine selection matches incorrectly on long line
Using the following regular expression:

```
\%(|\u.*\)\@<=[^|\t]\+$
```

I get a match in this line with default settings, or when I force automatic selection with \%#=0:

```
        xxxxxxxxxxxx    xxxx xxxxxx xxxxxxx x xxxxxxxxx xx xxxxxx xxxxxx xxxxx xxxxxxx xx xxxx xxxxxxxx xxxx xxxxxxxxxxx xxx xxxxxxx xxxxxxxxx xx xxxxxx xx xxxxxxx xxxxxxxxxxxxxxxx xxxxxxxxx  xxx xxxxxxxx xxxxxxxxx xxxx xxx xxxx xxx xxx xxxxx xxxxxxxxxxxx xxxx xxxxxxxxx xxxxxxxxxxx xx xxxxx xxx xxxxxxxx xxxxxx xxx xxx xxxxxxxxx xxxxxxx x xxxxxxxxx xx xxxxxx xxxxxxx  xxxxxxxxxxxxxxxxxx xxxxxxx xxxxxxx xxx xxx xxxxxxxx xxxxxxx  xxxx xxx xxxxxx xxxxx xxxxx xx xxxxxx xxxxxxx xxx xxxxxxxxxxxx xxxx xxxxxxxxx xxxxxx xxxxxx xxxxx xxx xxxxxxx xxxxxxxxxxxxxxxx xxxxxxxxx  xxxxxxxxxx xxxx xx xxxxxxxx xxx xxxxxxxxxxx xxxxx
```

However, if I force the engine to either 1 or 2, there is no match, as expected.

Tested in 7.4.1862, with patch 1848 reverted. I will try again in a more recent Vim when I get time to compile it later today, but I took a quick look at the patch list and didn't see anything that appears relevant since then.

### PR DESCRIPTION
**Pull request by brcolow**
Problem:    Falling back from NFA to old regexp engine does not work properly.
            (fritzophrenic)
Solution:   Do not restore nfa_match. (Christian Brabandt, closes vim/vim#867)

https://github.com/vim/vim/commit/6747fabc7348bf5f41ccfe851e2be3e900ec8ee0

### CODE REVIEW

**Comment by Shougo** [comment]
The commit is empty.
It is already included in neovim?

**Comment by Shougo** [comment]
LGTM

**Comment by brcolow** [comment]
Hmm test64 (the altered test) seems to fail on Travis.

**Comment by jamessan** [comment]
> Hmm test64 (the altered test) seems to fail on Travis.

This is because nvim defaults to `'autoindent'`, unlike vim, so the `o-1-` command in the test is maintaining the hanging indent of the `  !     xxx?x...` line.  I would suggest adding `:set noautoindent` near the top of the test file.

**Comment by justinmk** [comment]
>  I would suggest adding :set noautoindent near the top of the test file.

In fact we should probably update the legacy test runner (`src/nvim/testdir/runtest.vim`) to mimic Vim defaults. Not in this PR of course, but, some day.

**Comment by jamessan** [comment]
Merged in 01f10284.  Thanks!

**Pull request closed without merging**
