### PR TITLE
[RFC] vim-patch:8.0.0074

### PR DESCRIPTION
**Pull request by submagr**
Problem:    Cannot make Vim fail on an internal error.
Solution:   Add IEMSG() and IEMSG2(). (Domenique Pelle)  Avoid reporting an
            internal error without mentioning where.

https://github.com/vim/vim/commit/95f096030ed1a8afea028f2ea295d6f6a70f466f

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. But https://github.com/neovim/neovim/pull/7306 exists, and I think the changes there would be preferred if it were completed ...

**Comment by submagr** [comment]
Yeah, I saw that. But thought it was left there and nobody was working on it. Is there some way, I can complete those changes (which I've tried to do in this pr)

**Comment by justinmk** [comment]
> (which I've tried to do in this pr)

Oh, didn't know that. I'll have a closer look then.

**Comment by submagr** [comment]
Can somebody help me with the build failures? I am not able to pinpoint the reason.

**Comment by KillTheMule** [comment]
Here are the build failures:

Travis (32bit):
```

[1m[35m[  FAILED  ][0m[0m [36m...uild/neovim/neovim/test/functional/lua/commands_spec.lua[0m @ [36m101[0m: [1m:luado command works correctly when changing lines out of range[0m
...uild/neovim/neovim/test/functional/lua/commands_spec.lua:103: Expected objects to be the same.
Passed in:
(string) '
E322: line number out of range: -1487501793427455 past the end
E320: Cannot find line 6179531188080738306'
Expected:
(string) '
E322: line number out of range: 1 past the end
E320: Cannot find line 2'

stack traceback:
	...uild/neovim/neovim/test/functional/lua/commands_spec.lua:103: in function <...uild/neovim/neovim/test/functional/lua/commands_spec.lua:101>
```

Appveyor(32bit)
```

[  FAILED  ] C:/projects/neovim/test/functional\lua\commands_spec.lua @ 101: :luado command works correctly when changing lines out of range
C:/projects/neovim/test/functional\lua\commands_spec.lua:103: Expected objects to be the same.
Passed in:
(string) '
E322: line number out of range: 4294967297 past the end
E320: Cannot find line 4294967298'
Expected:
(string) '
E322: line number out of range: 1 past the end
E320: Cannot find line 2'
stack traceback:
	C:/projects/neovim/test/functional\lua\commands_spec.lua:103: in function <C:/projects/neovim/test/functional\lua\commands_spec.lua:101>
```

Appveyor (64bit gcov)

```
[  FAILED  ] C:/projects/neovim/test/functional\core\channels_spec.lua @ 60: channels can use stdio channel
.\test\functional\helpers.lua:110: Expected objects to be the same.
Passed in:
(table) {
  [1] = 'notification'
  [2] = 'stderr'
 *[3] = {
    [1] = 3
   *[2] = {
'
'
'
'
'
'
'
'
'
'
'
'
'
'
      [15] = '' } } }
Expected:
(table) {
  [1] = 'notification'
  [2] = 'stderr'
 *[3] = {
    [1] = 3
   *[2] = {
     *[1] = '*dies*' } } }
stack traceback:
	.\test\functional\helpers.lua:110: in function 'expect_twostreams'
	C:/projects/neovim/test/functional\core\channels_spec.lua:92: in function <C:/projects/neovim/test/functional\core\channels_spec.lua:60>
```

Appveyor 64bit-gcov also has the `gcd mismatch` error, I think that's not relevant.

**Comment by submagr** [comment]
Thanks. 
I don't know how to build and test for the 32-bit environment. Can you please provide the details. (I've searched the wiki but not able to find 32-bit relevant information). Also, I've checked the failing test by running the following command: 
`TEST_FILE=test/functional/lua/commands_spec.lua make functionaltest`
All 16 tests were passing locally

**Comment by KillTheMule** [comment]
I don't know either, maybe get a 32bit Docker container and compile in that? Maybe someone more competent than me, say @ZyX-I, can chime in.

**Comment by justinmk** [comment]
#7306 doesn't have that build failure, and its tree definitely has the `commands_spec.lua` test.
#7306 also doesn't have the lint issues present in this PR. 

So what was actually improved vs #7306?

**Comment by submagr** [comment]
You commented on #7306 about indentation issues. Also in nvim/options.c:2306, #7306 forget to update. I've taken these issues into the account.

I've raised the new PR because the pr #7306 was not active for quite a time. For the build failure issue, I am currently looking at the problem.

**Comment by jamessan** [comment]
The 32-bit build failures are because `IEMSGN`/`emsgn`/`iemsgn` are using `long` while the format strings are using `%" PRId64`, not `%ld`.  This means they're always expecting a 64-bit value, but `long` is only 32-bits for the Linux 32-bit build.  Note that `EMSGN` is correctly using `int64_t`.

I've updated #7306 to address the couple of issues that were outstanding, since the `emsgf`/`emsgfv` refactoring done there helps avoid duplicate code.

Thanks for the interesting in helping Neovim.  I'm going to close this PR now that the other one is updated.

**Pull request closed without merging**
