### PR TITLE
[WIP] Align help text time expectation for tutorial on 30 minutes

### PR DESCRIPTION
**Pull request by moret**
Hi maintainers!

This PR will align the time expectation for the tutorial on 30 minutes, as I noticed it's saying both 20 and 30 on different locations. I chose 30 minutes in order to round up to the oldest and highest time references. I hope I chose the right number, but I'll be happy to change them all to another number if needed, just let me know!

### CODE REVIEW

**Comment by vigoux** [comment]
Hi, I think this has actually also been fixed in vim too by the following commit : https://github.com/vim/vim/commit/d1caa941d876181aae0ebebc6ea954045bf0da24.
This would make this PR a `vim-patch` one.

**Comment by moret** [comment]
hmmm, I see, cool that it has already been addressed upstream. I'm not familiar with the project, could you help me think on how can I proceed now? Is there something I can help with the `vim-patch` or is it an automatic task done from time to time? In other words, should I close this and just wait or I may still make something manually? 8)

**Comment by janlazo** [comment]
Update your commit similar to the commits in https://github.com/neovim/neovim/pull/13037. Include the full link of https://github.com/vim/vim/commit/d1caa941d876181aae0ebebc6ea954045bf0da24.

Do not use vim-patch.sh because it is for complete ports of Vim commits.

**Comment by moret** [comment]
I'll close it as it seems I'm not managing my time well enough to return to it, and to clean up the backlog. I'll reopen if possible at a later date. Thank you a lot for the replies!

**Pull request closed without merging**
