### PR TITLE
runtime: include msmtp.vim

### PR DESCRIPTION
**Pull request by ghost**
Add msmtp syntax file to the runtime.

### CODE REVIEW

**Comment by janlazo** [comment]
Did you try to upstream this at https://github.com/vim/vim? I can merge this PR if you are the maintainer.

**Comment by janlazo** [comment]
https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=scripts/vim/msmtp.vim;h=02b75687e78ca1676235ca514bccbca4ab721b00;hb=HEAD is the current version of the syntax file.

**Comment by loicreynier** [comment]
I am not the maintainer of the syntax file but I can subscribe to the maintainer's RSS feed to monitor the changes and push the updates here.

When installing msmtp the syntax file is only placed in `/usr/share/vim/addons/syntax/msmtp.vim` and is not readable by neovim by default. I though it was best to add it here.

**Comment by janlazo** [comment]
Neovim cannot include runtime files in official builds without approval from the maintainer. Inclusion to Vim's runtime typically includes a request to relicense the runtime file to the Vim license (see `:h license`). I don't see a license mentioned in the syntax file so I'm assuming it's licensed under GPL 3 based on https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=COPYING;h=94a9ed024d3859793618152ea559a168bbcbb5e2;hb=HEAD

neovim cannot read that by default but you can update `runtimepath` in your init.vim to include a directory for that syntax file.

**Comment by jamessan** [comment]
> When installing msmtp the syntax file is only placed in /usr/share/vim/addons/syntax/msmtp.vim and is not readable by neovim by default. I though it was best to add it here.

It sounds like you're using the syntax file provided by a Debian package. I would suggest filing a bug against the Debian package asking the maintainer to switch from vim-addon-manager to dh-vim-addon, and also enable neovim support.

**Comment by loicreynier** [comment]
I contacted the maintainers in the beginning of the week, I do not have any news yet. If they accept to relicense the runtime under the Vim license I will try to upstream it at https://github.com/vim/vim. Thank you all for your help.

**Pull request closed without merging**
