### PR TITLE
[RFC] Learn "--server location" command line option.

### PR DESCRIPTION
**Pull request by splinterofchaos**
Partially related to pull #1277--it would be convenient to have an alternative to `$NVIM_LISTEN_ADDRESS`, and possibly replace it. However, I don't yet know the precise strategy that should be used, so right now I just want to propose a way to override it.

As an example, I use nvim as a git editor, but when I `:!git commit`, I see "Failed to start server: address in use", so to work without error, I have to configure git like this:

``` bash
$ git config --global core.editor 'env NVIM_LISTEN_ADDRESS=/tmp/git-nvim nvim'
```

I'd rather:

``` bash
$ git config --global core.editor 'nvim --server /tmp/git-nvim'
```

### CODE REVIEW

**Comment by splinterofchaos** [comment]
Been a while since I've worked on this. Is it still relevant? Has anything changed in this area since October?

**Comment by tarruda** [comment]
> Been a while since I've worked on this. Is it still relevant? Has anything changed in this area since October?

I have been thinking about adding a `serverlisten()` vimscript function and let users start the server manually(in vimrc for example). This would be more flexible for plugins and is still possible to listen on startup with `nvim +'let server_addr = serverlisten()'`

**Comment by splinterofchaos** [comment]
I think I can work on that if you're busy. Just to make sure I understand, "still possible to listen on startup with ..." means this would replace `NVIM_LISTEN_ADDRESS`, probably via `vim_tempname()`, or maybe the user could optionally supply an address as an argument.

It looks like `server_start()` and `_stop()` won't need any modification, and no need to store additional state since `serverlisten()` would return the address.

**Comment by tarruda** [comment]
> I think I can work on that if you're busy

:+1: that would be great.

> Just to make sure I understand, "still possible to listen on startup with ..." means this would replace NVIM_LISTEN_ADDRESS, probably via vim_tempname(), or maybe the user could optionally supply an address as an argument.

> It looks like server_start() and _stop() won't need any modification, and no need to store additional state since serverlisten() would return the address.

I meant that supplying a vimscript function gives users the same flexibility as a `--server location` command line option since vimscript can be executed at startup with `--cmd`/`-c`/`+`. Plus it allows plugins to open additional ports if required.

I think we should keep `NVIM_LISTEN_ADDRESS` since it gives msgpack-rpc access to programs running under Neovim, but only set it when `serverstart` is called(the first time). We can still let the user specify the address(unix or tcp) with optional arguments to the function(which defaults to whats returned by `vim_tempname`). Calling `serverstop` unsets the environment variable.

**Comment by splinterofchaos** [comment]
> I think we should keep NVIM_LISTEN_ADDRESS...

that's what I thought.

Having a rather frustrating error with the servers map. Here's the output from `.nvimlog` after repeatedly trying `call serverlisten('lol')` then `serverstop('lol')`:
```
2015/04/01 09:36:25 [error @ server_stop:218] 13281 - Not listening on lol
2015/04/01 09:36:28 [error @ server_start:110] 13281 - Already listening on lol
2015/04/01 09:36:29 [error @ server_stop:218] 13281 - Not listening on lol
2015/04/01 09:36:31 [error @ server_start:110] 13281 - Already listening on lol
2015/04/01 09:36:32 [error @ server_stop:218] 13281 - Not listening on lol
2015/04/01 09:36:34 [error @ server_start:110] 13281 - Already listening on lol
2015/04/01 09:36:35 [error @ server_stop:218] 13281 - Not listening on lol
```
So `pmap_get(cstr)(servers, "lol")` in `server_stop()` always returns `NULL` and `pmap_has(cstr)(servers, "lol)` always returns `true` in `server_start()`. Having never worked with pmap before, I'm not sure how it should be use... it's almost as if it maps the address of the string instead of the string itself... but it occurs to me that if we don't expect to run more than one or two servers, a `garray` might be simpler and more efficient. Also, `server_stop()` is currently dead code. Would it be ok to just switch to a garray?

**Comment by tarruda** [comment]
> .. but it occurs to me that if we don't expect to run more than one or two servers, a garray might be simpler and more efficient. Also, server_stop() is currently dead code. Would it be ok to just switch to a garray?

:+1:

**Comment by Pyrohh** [comment]
@splinterofchaos did you leave this open on purpose? #2331 says it "replaces" this PR, so just wanted to make sure.

**Comment by splinterofchaos** [comment]
@Pyrohh thank, forgot to close it.

**Pull request closed without merging**
