### PR TITLE
fix(lsp): ensure buffer is not attached more than once

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes regression introduced in #28030

If an LSP server is restarted, then the associated `nvim_buf_attach`
call will not detach if no buffer changes are sent between the client
stopping and a new one being created. This leads to `nvim_buf_attach`
being called multiple times for the same buffer, which then leads to
changetracking sending duplicate requests to the server (one per
attach).

To solve this, introduce separate tracking (client agnostic) on which
buffers have had calls to `nvim_buf_attach`.

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]
:+1:

**Review by justinmk — APPROVED** [review]

**Comment by mfussenegger** [comment]
Looks like there's still something wrong with the attach mechanism.

Just got this error on a `:e!`:

```
Error executing lua callback: ...ev/neovim/neovim/runtime/lua/vim/lsp/_changetracking.lua:202: attempt to index local 'buf_state' (a nil value)
stack traceback:
        ...ev/neovim/neovim/runtime/lua/vim/lsp/_changetracking.lua:202: in function 'reset_buf'
        ...ev/neovim/neovim/runtime/lua/vim/lsp.lua:567: in function <dev/neovim/neovim/runtime/lua/vim/lsp.lua:564>
```

Then tried closing all buffers (`:bd`) and re-opening them, but they wouldn't attach anymore. `vim.lsp.get_clients()` showing:

```
   attached_buffers = { true,
      [67] = true,
      [68] = true,
      [208] = true,
      [1028] = true,
      [1035] = true,
      [1036] = true,
      [1038] = true,
      [1042] = true,
      [1043] = true
    },
```

**Comment by lewis6991** [comment]
That suggests the detach callback isn't triggering, weird.

**Comment by lewis6991** [comment]
I wonder if it is lines 546-548 not causing the detach event, however I'd expect `:bd` to cause a detach event regardless.

**Comment by mfussenegger** [comment]
Unfortunately I wasn't able to reproduce it again, but https://github.com/neovim/nvim-lspconfig/issues/3129 sounds also a bit like what I was seeing and if I'm reading the git log right `v0.10.0-dev-3026+ga41546d4a` included the change here already.

**Comment by lewis6991** [comment]
I haven't been able to produce anything my end. `:bd` works fine for me. Perhaps the buffers were still attached because you got an error which prevented the attached table from being updated.

**Comment by iurimateus** [comment]
Did you try with multiple clients attached?

**Comment by lewis6991** [comment]
I just tried with multiple versions LuaLS attached, and no issues.

Going to need something more specific to work off.

**Pull request merged**
