### PR TITLE
vim-patch:5be4ceecea55

### PR DESCRIPTION
**Pull request by willelz**
Update runtime files.
https://github.com/vim/vim/commit/5be4ceecea5520265066eac972460ebb1cdf05e7

### CODE REVIEW

**Comment by KillTheMule** [comment]
Quick headsup, neovim is missing older runtime patches than this (e.g. https://github.com/vim/vim/commit/30e9b3c4256710781c3bd64efb33f138e4e074b3). Runtime patches should very much be applied in order, so it would definitely make sense to look which is the most recent one included in neovim and work your way from there.

There's also the non-runtime patches to consider, because runtime code could can (and will) use features from the core. I don't think there's a good process for that, but I think the patch script can help you assess the situation.

**Comment by willelz** [comment]
You’re right.

**Comment by janlazo** [comment]
fbIt's fine to cherry-pick runtime patches. I allowed it in https://github.com/neovim/neovim/pull/12497  but you can't use `vim-patch:` in the commit message and runtime patches for the modified files must be applied in order.

**Comment by willelz** [comment]
Thank you. I'll try it.

**Pull request closed without merging**
