### PR TITLE
Prefer the static jemalloc library by default on OSX

### PR DESCRIPTION
**Pull request by jamessan**
When neovim is dynamically linked against jemalloc on OSX, users are
hitting the deadlock described in jemalloc/jemalloc#895.

### CODE REVIEW

**Review by mhinz — APPROVED** [review]

**Comment by mhinz** [comment]
I tested it locally with `make CMAKE_EXTRA_FLAGS=-DUSE_BUNDLED_JEMALLOC=OFF DEPS_CMAKE_FLAGS=-DJEMALLOC_USE_STATIC=OFF` and it disables jemalloc indeed.

Maybe add a `TODO`, so we can remove this workaround in the future. (Or someone takes the time to benchmark system malloc vs. jemalloc on a few platforms, so we know if this dependency is actually useful.)

@ilovezfs

If we merge this PR, jemalloc can be removed from the homebrew-core formula.

**Comment by jamessan** [comment]
> If we merge this PR, jemalloc can be removed from the homebrew-core formula.

It could, but we'll want to re-enable jemalloc again once it's working better, which would mean re-adding jemalloc at that point.  I'd probably just leave jemalloc in the formula to avoid churn.

> Maybe add a TODO, so we can remove this workaround in the future.

That's why I referenced the jemalloc issue.  Once that issue is fixed and released, we should be able to drop this change.

**Comment by mhinz** [comment]
> I'd probably just leave jemalloc in the formula to avoid churn.

I think most people use homebrew to install the bottle (a prebuilt binary) instead of building from source.

I thought one would have to bump a number in the formula anyway, so the bottle is rebuilt, but there doesn't seem to be any kind of number in the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/neovim.rb).

But then the bottle is built from the latest release. So, if we want homebrew users to take advantage of this PR, we might have to do a bugfix release and rebuilt the bottle.

@ilovezfs hopefully knows what to do.

**Comment by ilovezfs** [comment]
It is possible to link jemalloc statically in Homebrew if it's absolutely necessary, but it's quite unclear to me why that should be necessary.

This PR seems like overkill.

**Comment by mhinz** [comment]
@ilovezfs See https://github.com/neovim/homebrew-neovim/issues/219#issuecomment-313707372

**Comment by jamessan** [comment]
> but it's quite unclear to me why that should be necessary.

https://github.com/jemalloc/jemalloc/issues/895 is why it's necessary.  Static linking somehow avoids that jemalloc bug, thus preventing people from running into issues like https://github.com/neovim/neovim/issues/5681 and https://github.com/neovim/neovim/issues/6972.

**Comment by ilovezfs** [comment]
So let's link it statically in Homebrew.

**Comment by ilovezfs** [comment]
I think you could fix this in CMake by detecting the location of the static library, and then specifying the full path to it.

The issue is that without specifying it manually, you're using the dynamic lib just because it happens to be there. We're not actually actively doing anything in the formula to pick the dylib over the static library.

**Comment by jamessan** [comment]
That relies on there always being a static library available.  Is that always the case on OSX?

**Comment by ilovezfs** [comment]
>That relies on there always being a static library available. Is that always the case on OSX?

In Homebrew, given the bug you pointed to, there's no way we'd remove the static library. I cannot speak for MacPorts or NixOS, but I cannot imagine they would feel differently.

**Comment by jamessan** [comment]
Maybe something like this would be better

```diff
diff --git a/cmake/FindJeMalloc.cmake b/cmake/FindJeMalloc.cmake
index 820ceeed4..f139196a3 100644
--- a/cmake/FindJeMalloc.cmake
+++ b/cmake/FindJeMalloc.cmake
@@ -27,6 +27,9 @@ find_path(JEMALLOC_INCLUDE_DIR jemalloc/jemalloc.h
 if(JEMALLOC_USE_STATIC)
   list(APPEND JEMALLOC_NAMES
     "${CMAKE_STATIC_LIBRARY_PREFIX}jemalloc${CMAKE_STATIC_LIBRARY_SUFFIX}")
+elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
+  list(INSERT JEMALLOC_NAMES 0
+    "${CMAKE_STATIC_LIBRARY_PREFIX}jemalloc${CMAKE_STATIC_LIBRARY_SUFFIX}")
 endif()
 
 list(APPEND JEMALLOC_NAMES jemalloc)
```

so we have the static library as the first name checked.

**Comment by ilovezfs** [comment]
Yes, it works:

Before:
```
JEMALLOC_LIBRARY:FILEPATH=/usr/local/lib/libjemalloc.dylib
```

After:
```
JEMALLOC_LIBRARY:FILEPATH=/usr/local/lib/libjemalloc.a
```

And if I `brew unlink jemalloc`:
```
JEMALLOC_LIBRARY:FILEPATH=/usr/local/Cellar/jemalloc/5.0.1/lib/libjemalloc.a
```

**Comment by mhinz** [comment]
There you go. That's the way I wanted it from the beginning, forcing static linking instead of disabling jemalloc. :-P

I like the diff from the last comment (plus the message from the original commit).

**Comment by ilovezfs** [comment]
If it does choose the dylib, you may want to hard fail the build, but that may be addressing a scenario that won't actually happen in the wild.

**Comment by jamessan** [comment]
Good discussion. :) Updated accordingly.

**Comment by ilovezfs** [comment]
I think you may want to take this up with NixOS: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/neovim/default.nix#L132-L136

**Comment by ilovezfs** [comment]
Once this is merged, do you want to tag a new release? Or should we just apply the commit as a patch until your next release?

**Comment by mhinz** [comment]
@ilovezfs So how is the bottle rebuild process working? Does it need a new release?

**Comment by ilovezfs** [comment]
Either we add `revision 1` to the formula, and apply the commit as a patch, or you tag a new release. I have a slight preference for the latter, of course.

**Comment by jamessan** [comment]
> I think you may want to take this up with NixOS:

That's adjusting the path of the dynamic library, but if we're no longer dynamically linking against jemalloc, then it shouldn't be an issue.

> Once this is merged, do you want to tag a new release?

We're not going to make a release just for this.  The problem has existed for awhile and master isn't ready for release.

**Comment by ilovezfs** [comment]
>That's adjusting the path of the dynamic library, but if we're no longer dynamically linking against jemalloc, then it shouldn't be an issue.

Right but this change will probably break their package :)

>We're not going to make a release just for this. The problem has existed for awhile and master isn't ready for release.

Not a problem.

**Comment by ilovezfs** [comment]
voilà https://github.com/Homebrew/homebrew-core/pull/15393

**Comment by ilovezfs** [comment]
MacPorts will also need the patch applied and the revision bumped.
https://github.com/macports/macports-ports/blob/master/editors/neovim/Portfile

**Comment by jamessan** [comment]
Ping @raimue.

**Comment by mhinz** [comment]
Yay, thanks everyone!

**Comment by ecbrodie** [comment]
For those who have installed neovim via `brew install neovim`, what's the best way to immediately pick up these new changes? A simple `brew update && brew upgrade` doesn't do the trick for me. Do I need to specify a flag to install the updated version?

**Comment by jamessan** [comment]
@ecbrodie https://github.com/Homebrew/homebrew-core/pull/15393 hasn't been merged, so I don't think there's anything to do yet.

**Comment by ilovezfs** [comment]
I've now shipped https://github.com/Homebrew/homebrew-core/pull/15393. If you want to poke at it, `brew update && brew upgrade neovim`

**Comment by raimue** [comment]
Thanks for the heads-up. MacPorts still has jemalloc @4.2.1_1, which seems unaffected. Static linking is not an option as it leads to non-reproducible builds. The best I could do would be to disable jemalloc.

**Comment by mhinz** [comment]
@raimue 

It seems that the jemalloc devs found [the root cause](https://github.com/jemalloc/jemalloc/issues/895#issuecomment-313827407) already. Maybe you can just wait a bit longer and then update the jemalloc port to the future release that fixes the dynamic linking bug.

**Pull request merged**
