### PR TITLE
vim-patch:8.2.3399: Octave files are not recognized

### PR DESCRIPTION
**Pull request by clason**
Problem:    Octave files are not recognized.
Solution:   Detect Octave files. (Doug Kearns)
https://github.com/vim/vim/commit/deba5eb195d6ac70171d4973091fa884809fa3fa

### CODE REVIEW

**Comment by clason** [comment]
Octave syntax files are part of https://github.com/vim/vim/commit/6c391a74fe90190796ca0b0c010112948a6e75d7 (hidden among @dundargoc's typo barrage ;))

**Review by justinmk — APPROVED** [review]

**Comment by seandewar** [comment]
Already in #15580 but feel free to port this if its easier :smile:

**Comment by clason** [comment]
Guess we should coordinate better ;)

I think it's better to keep PRs focused by topic -- only combine multiple patches if they are touching the same code and are "atomic" (meaning later patches fix issues with the original code in the first patch).

It also helps to add PR descriptions -- even if that's just a copy&paste from the commit messages.

In this case, I'd prefer to have this patch in a separate PR since that makes it easier to coordinate with the corresponding runtime update port (which I hope to get to in the next few days) -- or is there a specific reason you included this patch in your PR?

**Comment by clason** [comment]
Okie, thank you!

**Pull request merged**
