### PR TITLE
runtime: Add TeX conceal for \left and \right pipe

### PR DESCRIPTION
**Pull request by leun4m**
Previously on TeX the cchar conceal for

```tex
\left| \right| \left\| \right\|
```
was not implemented, so I thought I could fix that.
Not much of a change just a little enhancement.

### CODE REVIEW

**Comment by teto** [comment]
we prefer to just merge the vim runtime rather than maintaining our fork. Please see with the .tex maintainer how to merge this improvement. 

Thanks.

**Comment by leun4m** [comment]
Oh sorry was not aware of that. Makes sense though.
Thanks anyway.

**Comment by leun4m** [comment]
Just a little update in case anyone would ever stumble across this wondering what happened to this.
I contacted the maintainer of vim runtime and the changes I desired got real in the following commit:

https://github.com/vim/vim/commit/65e0d77a66b7e50beb562ad554ace46c32ef8f0f#diff-9aa7419d9504f85f995d943175f49e46

**Comment by tjdevries** [comment]
If you're interested in getting these merged to nvim, I would expect that it's possible. Not sure if you're interested in doing that or not thought :)

**Comment by leun4m** [comment]
Well, what would be the best way to do that?

**Comment by tjdevries** [comment]
This would be a bit out-of-order, so I'm not  sure if it's possible to do or recommended, but we merge those changes from vim to neovim outlined here: 

https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

I will tag our experts on patch merging.

cc @janlazo @erw7 in case these changes should not be ported yet.

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/commit/0d852bdc69b0293695c391e316c65183b88b83ef is the latest runtime patch for `tex.vim` files that was merged to neovim.
Cherry-pick only `tex.vim` changes from the following patches:

https://github.com/vim/vim/commit/1d9215b9aaa120b9d78fee49488556f73007ce78#diff-9aa7419d9504f85f995d943175f49e46
https://github.com/vim/vim/commit/388a5d4f20b4b64341d1604aa238cab85827b892#diff-9aa7419d9504f85f995d943175f49e46
https://github.com/vim/vim/commit/65e0d77a66b7e50beb562ad554ace46c32ef8f0f#diff-9aa7419d9504f85f995d943175f49e46

Apply the patches in order as shown in the commit history at https://github.com/vim/vim/commits/65e0d77a66b7e50beb562ad554ace46c32ef8f0f/runtime/syntax/tex.vim

Do not use `./scripts-vim-patch.sh` for generating the commit message so that script does not filter out those patches when searching for unmerged patches. Add a reference to the original patch so the Vim commit hash can be grepped.

It's ideal to merge them in order but it's time-consuming to resolve conflicts on incompatible documentation and plugins. Changes to the `tex.vim` files don't seem to use specific Vim 8.1+ syntax so it should be safe to merge on master.

**Comment by tjdevries** [comment]
Thanks @janlazo that's super helpful! Always appreciate your help :heart:

**Pull request closed without merging**
