### PR TITLE
docs: options.txt: cosmetic change

### PR DESCRIPTION
**Pull request by camoz**

### CODE REVIEW

**Comment by dundargoc** [comment]
Questionable IMO. I don't think this is a clear improvement, sorry.

**Comment by camoz** [comment]
Did you see that right now gg is missing quotes?

**Comment by dundargoc** [comment]
I missed that. Stop mixing fixes with stylistic changes lol. I'll include it. Thanks!

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/22953

**Pull request closed without merging**
