### PR TITLE
Fix recoverymode / -r

### LINKED ISSUE #11181: "nvim -r" (recovery mode) not working
The command `nvim -r` fails to display any text or outputs junk console codes, depending on the term setting. When run in tmux (with `TERM=tmux-256color` or `TERM=xterm-kitty`), it outputs nothing. When run in kitty without a tmux session, it outputs the sequence `^[]11;rgb:3f3f/3f3f/3f3f^[\` and displays `execute: 3f3f/3f3f/3f3f` below the new prompt. I installed a few other terminal emulators and had similar problems.

- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
I installed vim and did not see the same behavior.

- Operating system/version:
Arch Linux, kernel 5.3.5, libvterm is version 0.1.git5.4a5fa43-1

- Terminal name/version:
kitty version 0.14.6-1, but similar behavior with xterm and urxvt

- `$TERM`:
`tmux-256color` and `xterm-kitty`, as mentioned above.

### Steps to reproduce using `nvim -u NORC`
From a kitty terminal window (with or without tmux), run `nvim -u NORC -r`. No output will be displayed in the tmux case, and a junk control sequence will be displayed when no tmux session is used.

Running `TERM=ansi-256color nvim -u NORC -r` produces the correct output in the tmux case, but without tmux, the code `^[]11;rgb:3f3f/3f3f/3f3f^[\` and `execute` message are both still displayed (along with the correct output).

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neovim/neovim/issues/11181

### CODE REVIEW

**Comment by blueyed** [comment]
@bfredl 
Is it easily possible to skip using a fullscreen grid here?
(i.e. display it directly)

`vim -r` does not use a more-prompt in the first place also.

**Comment by blueyed** [comment]
Using headless mode appears to fix it.

**Comment by blueyed** [comment]
Happy to add a test if that's the way to go.

**Comment by blueyed** [comment]
Should I add a test?
Might be not trivial given my attempt in https://github.com/neovim/neovim/pull/11174 to test behavior with regard to a child process.  There might be an easier way to test this though.

**Comment by justinmk** [comment]
Let's skip the test if it's complicated. If we later take the approach I described above , a screen test should be enough.

**Pull request merged**
