### PR TITLE
[WIP] Fix lockup

### LINKED ISSUE #7244: Neovim locks up on substitute when set inccommand=nosplit and set gdefault
- `nvim --version`: NVIM v0.2.1-855-gcb912a3ed
- Operating system/version: Linux 4.12.5-gentoo
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
echo '{' | nvim -u NORC -c "set inccommand=nosplit | set gdefault" -
:s/{\n
```

### Actual behaviour
Neovim is unresponsive and eats 100% of one of my CPU cores until C-c is sent.

### Expected behaviour
No lock up.

### PR DESCRIPTION
**Pull request by KillTheMule**
Attempt to fix https://github.com/neovim/neovim/issues/7244.

### CODE REVIEW

**Comment by glacambre** [comment]
It seems to fix the issue for :s/{\n but unfortunately the following still locks for me:
```
echo -ne '{\n\n{' | build/bin/nvim -u NORC -c "set inccommand=nosplit | set gdefault" -
:%s/
```

**Comment by KillTheMule** [comment]
Yeah, you're right, thanks for testing. I can reproduce, but things look a bit weird... I can actually type `:%s/{\n` until the lockup occurs. Then, if I press `<C-C>`, then replace the brackets with the letter `a`, no lockup occurs. If I then replace the letter `a` by the letter`b`, the lockup occurs again, only that I can just type `:%s/` until the lockup. Undoing get me no lockup, but going back to the bracket makes it appear again...

Weird stuff! Might be connected to the order in which I'm doing things...

**Comment by glacambre** [comment]
How did you come to the conclusion that the lines you added were needed? I took a quick look using gdb and it seems that neovim gets stuck in nfa_regmax (src/nvim/regexp_nfa.c:5027). But I know nothing about the code so I might be very wrong here.

**Comment by KillTheMule** [comment]
> How did you come to the conclusion that the lines you added were needed? I took a quick look using gdb and it seems that neovim gets stuck in nfa_regmax (src/nvim/regexp_nfa.c:5027). But I know nothing about the code so I might be very wrong here.

(Note: Got a post notification via email, I can't see your answer here, so I'm quoting it).

When I ran your case through gdb, it was stuck in this loop: https://github.com/KillTheMule/neovim/blob/e72bb7ba6303c7b56e508c99056de66d706d19b4/src/nvim/ex_cmds.c#L3419. This also makes sense because the loop contains a breakcheck, that's why we can interrupt with `<C-c>`. Then I run a nonblocking case through the debugger and noticed a different behavior here, which really fit well: Final newline in the match, no second delimiter, and this code isn't run in the "no second delimiter" case, so I just added it and tried, and voila :) I did not fully understand it, in particular wrt gdefault, but wanted to get it out to you to try fast. Too fast, indeed ;)

I'll dive in again tonight or so.

**Comment by KillTheMule** [comment]
Closed in favor of https://github.com/neovim/neovim/pull/7231.

**Pull request closed without merging**
