### PR TITLE
[RFC] highlight: fix screen refresh #7489

### PR DESCRIPTION
**Pull request by nateozem**
included tests as requested 
* test invalid value for `cterm` 
* test for existing name of highlight group.

### CODE REVIEW

**Comment by nateozem** [comment]
First time adding test cases to this project. Please let me know if I done it incorrectly and would need to make necessary adjustments.

**Comment by justinmk** [comment]
Thanks! Can you include the explanation on commit message

**Comment by nateozem** [comment]
I've fix the commit messages by rebasing and force push the new commits. Please let me know if this is what you have wanted. Next time, I would know better.

**Comment by justinmk** [comment]
Thanks, merged.

FWIW vim patch 8.0.1072 would avoid this indirectly, because it avoids redraw if `:highlight` command did not change anything. Would be nice to merge that patch.

**Pull request closed without merging**
