### PR TITLE
vim-patch:8.0.0672: synconcealed() seqnr changes too often

### LINKED ISSUE #7589: Calling synID() breaks third return value from synconcealed()
- `nvim --version`: v0.2.1 (from the Arch Repos) and d6f9d1df0
- Vim (version: 8.0, patches 1-1297, also from Arch Repos) behaves differently? YES
- Operating system/version: Arch Linux (uname -a: `Linux tp 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`
- Terminal name/version: [termite](https://github.com/thestinger/termite/) v12 (from Arch Repos)
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

We need a minimal config folder with a simple syntax file, so:

```
mkdir -p testfolder/syntax
cp example.vim testfolder/syntax
cp test.vim test.txt testfolder/
cd testfolder
```
with these files:

*example.vim* syntax file:
```vim
syn match tutorSampleTextMark /^--->/ conceal cchar=→
```
the *test.vim* script to demonstrate the problem
```vim
if !has('nvim')
  se nocp
endif
set cole=2
syntax on
filetype on

let lnum = 1

for cnum in range(1, len(getline(lnum)))
  echo synconcealed(lnum, cnum)
  " TODO Comment the following line in or out to see the bug:
  echo synID(lnum, cnum, 1)
endfor

quitall!
```
and the *test.txt* data file:
```
--->
vim: ft=example
```

### Actual behaviour

The output from `nvim --headless -u NONE --cmd 'se rtp+=.' -S test.vim test.txt` is:
```
"test.txt" "test.txt" 2L, 21C
[1, '→', 1]
88
[1, '→', 2]
88
[1, '→', 3]
88
[1, '→', 4]
88
```

### Expected behaviour

The output from `vim -T dumb -u NONE --cmd 'se rtp+=.' -S test.vim test.txt` is:
```

"test.txt" 2 lines, 21 characters
[1, '→', 1]
87
[1, '→', 1]
87
[1, '→', 1]
87
[1, '→', 1]
87
```

If the synID() call in test.vim is commented out both nvim and vim produce this output:

```
"test.txt" "test.txt" 2L, 21C
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
```

In my opinion this demonstrates that a call to `synID()` will somehow mess up the third return value from `synconcealed()` which per the docs should be
```
[...] a unique number representing the
specific syntax region matched. This allows detection of the
beginning of a new concealable region if there are two
consecutive regions with the same replacement character.
```

### PR DESCRIPTION
**Pull request by justinmk**
- continues https://github.com/neovim/neovim/pull/7685
- closes https://github.com/neovim/neovim/issues/7589

Blocked by the issue described below.

### CODE REVIEW

**Comment by justinmk** [comment]
Test failure looks related to @tweekmonster behavior change. Do you have time to look at this?

```
[1m[31m[  ERROR   ][0m[0m [36m...is/build/neovim/neovim/test/functional/ui/mouse_spec.lua[0m @ [36m814[0m: [1mui/mouse/input on concealed text (level 1) click on wrapped lines[0m
test/functional/ui/screen.lua:307: Row 2 did not match.
Expected:
  |{c:Y}rem ip{c:X}um do{c: } {c:X}it {c: }     |
  |*, con{c:X}^etetur {c:X}adip{c:X}cin{c:X}  |
  |elitr.                   |
  |{c:X}tet {c: }ta ka{c:X}d {c:X}ber{c:X}en    |
  |, no {c:X}ea takimata {c:X}anctu{c:X}|
  | e{c:X}t.                    |
  |                         |
Actual:
  |{c:Y}rem ip{c:X}um do{c: } {c:X}it {c: }     |
  |*, con{c:X}e^tetur {c:X}adip{c:X}cin{c:X}  |
  |elitr.                   |
  |{c:X}tet {c: }ta ka{c:X}d {c:X}ber{c:X}en    |
  |, no {c:X}ea takimata {c:X}anctu{c:X}|
  | e{c:X}t.                    |
  |                         |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:307: in function 'wait'
	test/functional/ui/screen.lua:221: in function 'expect'
	...is/build/neovim/neovim/test/functional/ui/mouse_spec.lua:829: in function <...is/build/neovim/neovim/test/functional/ui/mouse_spec.lua:814>

[1m[31m[  ERROR   ][0m[0m [36m...is/build/neovim/neovim/test/functional/ui/mouse_spec.lua[0m @ [36m911[0m: [1mui/mouse/input on concealed text (level 2) click on wrapped lines[0m
test/functional/ui/screen.lua:307: Row 2 did not match.
Expected:
  |{c:Y}rem ip{c:X}um do {c:X}it        |
  |*, con{c:X}^etetur {c:X}adip{c:X}cin{c:X}  |
  |elitr.                   |
  |{c:X}tet ta ka{c:X}d {c:X}ber{c:X}en     |
  |, no {c:X}ea takimata {c:X}anctu{c:X}|
  | e{c:X}t.                    |
  |                         |
Actual:
  |{c:Y}rem ip{c:X}um do {c:X}it        |
  |*, con{c:X}e^tetur {c:X}adip{c:X}cin{c:X}  |
  |elitr.                   |
  |{c:X}tet ta ka{c:X}d {c:X}ber{c:X}en     |
  |, no {c:X}ea takimata {c:X}anctu{c:X}|
  | e{c:X}t.                    |
  |                         |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:307: in function 'wait'
	test/functional/ui/screen.lua:221: in function 'expect'
	...is/build/neovim/neovim/test/functional/ui/mouse_spec.lua:926: in function <...is/build/neovim/neovim/test/functional/ui/mouse_spec.lua:911>


 [1m13[0m SKIPPED TESTS
 [1m2[0m ERRORS
-- Output to stderr:

CMake Error at /home/travis/build/neovim/neovim/cmake/RunTests.cmake:53 (message):
  Running functional tests failed with error: 1.
```

**Comment by justinmk** [comment]
@tweekmonster I tried this patch, doesn't seem to help:

```diff
diff --git a/src/nvim/syntax.c b/src/nvim/syntax.c
index 40479e05dd5b..08669cf7436c 100644
--- a/src/nvim/syntax.c+++ b/src/nvim/syntax.c@@ -1600,7 +1600,7 @@ get_syntax_attr (     current_id = 0;
     current_trans_id = 0;
     current_flags = 0;
-    current_seqnr = 0;+    current_seqnr = 1;     return 0;   }
-
@@ -2044,7 +2044,7 @@ syn_current_attr (
   current_id = 0;
   current_trans_id = 0;
   current_flags = 0;
-  current_seqnr = 0;
+  current_seqnr = 1;
   if (cur_si != NULL) {
     for (int idx = current_state.ga_len - 1; idx >= 0; --idx) {
       sip = &CUR_STATE(idx);
```

I'll stop here, hoping you can take a  look.

**Comment by tweekmonster** [comment]
@justinmk I'll see what I can find out.  Currently working on #5822

**Comment by tweekmonster** [comment]
I have no idea what's going on.  All I can see is that the test is actually wrong, but I don't know why it passes without this change.

**Comment by justinmk** [comment]
Oh, cool. Let's change the test then.

**Comment by justinmk** [comment]
Is the test failure "actual" correct?

**Comment by tweekmonster** [comment]
I'm sorry I was confusing myself last night because I was working on the mouse issue.  The tests are fine.  It looks like this change fixes a bug that didn't need to be addressed in `mouse_adjust_click()`.

This causes the tests to pass with or without this PR:

```diff
diff --git a/src/nvim/mouse.c b/src/nvim/mouse.c
index d908a022f..796ff1585 100644
--- a/src/nvim/mouse.c
+++ b/src/nvim/mouse.c
@@ -646,10 +646,11 @@ static int mouse_adjust_click(win_T *wp, int row, int col)
         if (row > 0 && i == start_col) {
           // Check if the current concealed character is actually part of
           // the previous wrapped row's conceal group.
-          last_matchid = syn_get_concealed_id(wp, wp->w_cursor.lnum,
-                                              i - 1);
-          if (last_matchid == matchid) {
-            bcol++;
+          if (wp->w_p_cole == 3) {
+            last_matchid = syn_get_concealed_id(wp, wp->w_cursor.lnum, i - 1);
+            if (last_matchid == matchid) {
+              bcol++;
+            }
           }
         } else if (wp->w_p_cole == 1
                    || (wp->w_p_cole == 2
```

I can submit a PR with the fix above, but #5822 would basically wipe it out when I incorporate the fix above.  Your call.

**Comment by tweekmonster** [comment]
Actually just noticed that `if (wp->w_p_cole == 3)` would never be true at this point.  The actual fix is to keep it from doing anything if `row > 0 && i == start_col`.

**Pull request closed without merging**
