### PR TITLE
ci: friendship ended with Cirrus CI, now QEMU is my best friend

### PR DESCRIPTION
**Pull request by dundargoc**
Cirrus CI has introduced monthly limits on CI usage, which no longer
makes it a viable alternative for us. More information:
https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/

This PR is a WIP as I don't know what the best path forward is for us
yet. I will investigate how other projects deal with this problem and
experiment different ideas.

### CODE REVIEW

**Comment by amaanq** [comment]
I've had good experiences w/ this: https://github.com/vmactions/freebsd-vm

**Comment by dundargoc** [comment]
I tested that for a bit when looking for alternatives for sourcehut CI. 2 downsides:

1. It's kinda slow. That said I have no idea if a custom implementation would be faster.

2. It requires macos, which is a limited resource in github actions.

It's a convenient alternative though, so I will keep it in mind.

**Comment by bfredl** [comment]
For reference, I had some success with these instructions: https://til.simonwillison.net/docker/emulate-s390x-with-qemu 

>  This is the first command to run. It does something magical to your Docker installation:

> `docker run --rm --privileged multiarch/qemu-user-static:register --reset`

> Having run that command, the following command drops you into a shell in an emulated s390x machine running Ubuntu Focal:

> `docker run -it multiarch/ubuntu-core:s390x-focal /bin/bash`


This allowed me to set up and compile neovim with the normal ubuntu instructions. The only change was to PREFER_LUA instead of luajit as luajit HEAD is known to be broken on s390x (there are unmerged patches, as an alternative)

**Comment by justinmk** [comment]
As a workaround, we could enable the cirrus CI only for master pushes instead of PRs?

**Comment by dundargoc** [comment]
> As a workaround, we could enable the cirrus CI only for master pushes instead of PRs?

We can try it, but I suspect this won't be effective. The problem with master-only runs is that's even if it does fail, we won't get the necessary feedback needed to deal with it in a timely manner. It can potentially go weeks or months before we realize that freebsd runs are broken. A CI status indicator on the README isn't likely to solve this either, as it'd be too easy to mistakenly think the errors are due to flaky tests. I think a better strategy is to prioritize the tests which we believe are the most important instead, such as e.g. skipping oldtests.

**Comment by dundargoc** [comment]
There is no real reason for this anymore I feel like. If cirrus CI starts becoming a problem again we can simply remove freebsd CI, alternatively use an optional virtualization workflow.

**Pull request closed without merging**
