### PR TITLE
[RDY] vim-patch:8.2.{1345,1488}

### LINKED ISSUE #12285: Visual selection drawn incontinuously
- `nvim --version`: v0.4.3–v0.5.0-nightly
- `vim -u DEFAULTS` (version: ) behaves differently? No ([Reported.](https://github.com/vim/vim/issues/6053))
- Operating system/version: Arch Linux
- Terminal name/version: `urxvt`
- `$TERM`: `rxvt-unicode-256color`

### Steps to reproduce using `nvim -u NORC`

1. `nvim -u NORC +'set scrolloff=7' +44 https://raw.githubusercontent.com/metashell/metashell/master/test/system/mdb/test_continue.cpp`
2. (Ensure that initial `winheight(0) == 40`.)
3. Press <kbd>V</kbd> then <kbd>CTRL-D</kbd> 7 times. (Sometimes also enough pressing once and standing on line 43/44… there are various possible circumstances.)

### Actual behaviour

screenshot

### Expected behaviour

Visual selection drawn continuously. <kbd>CTRL-L</kbd> fixes the issue so I think it’s just some miscalculation around `'scrolloff'`.

### PR DESCRIPTION
**Pull request by aufarg**
Fixes #12285

### CODE REVIEW

**Comment by aufarg** [comment]
For 8.2.1488 when I tried to run the test manually it fails before the change, but with the automated test it works even without the change. I'm not sure why.

**Comment by janlazo** [comment]
Include the screendump tests even if they are skipped.

**Comment by aufarg** [comment]
@janlazo Updated to include the screendump tests.

**Review by janlazo — APPROVED** [review]
LGTM

**Pull request merged**
