### PR TITLE
[WIP] avoid macOS hang

### PR DESCRIPTION
**Pull request by justinmk**
This is an attempt to narrow down the cause of macOS build hangs on travis.

### CODE REVIEW

**Comment by justinmk** [comment]
@oni-link It appears that https://github.com/neovim/neovim/pull/4646 is causing the macOS builds to hang. Specifically the [tests commented-out here](https://github.com/neovim/neovim/pull/5002/commits/fa8a5ad0bcb9bd71c069c43a4004349c4798c9c6).

**Comment by oni-link** [comment]
Is it enough to comment out the two `flush_stream();` lines [here](https://github.com/neovim/neovim/pull/4646/files#diff-89f96344a6610f20b684b4d71368eaabR389) to make travis happy?

**Comment by oni-link** [comment]
It looks like it could be a problem with function `uv_recv_buffer_size()` , see #5029. Removing this function in `flush_stream()` makes the macOS tests pass.

**Comment by justinmk** [comment]
@oni-link Very interesting. I will re-run that build a couple times to be sure.

**Pull request closed without merging**
