### PR TITLE
LSP: Added no_wait option.

### PR DESCRIPTION
**Pull request by Thiago4532**
On the issue #12478 they are discussing some methods to fix slow closing when using nvim-lsp, so I've decided to implement two new options to let the user choose which closing method they want to use for a specific LSP client. The two methods are:

```
no_wait: (boolean) Do not wait the language server to exit before closing NeoVim.
force_exit: (boolean) Kill the language server instead of waiting them to close.
```

I don't know if this the best way to solve this, but is the most user-friendly way that I can think.

### CODE REVIEW

**Comment by mjlbach** [comment]
> I don't know if this the best way to solve this, but is the most user-friendly way that I can think.

I disagree, because this could leave user buffers in irrecoverable states if the server is force-quit in the middle of a reformatting operation or code-action. TJ may feel differently, but I don't feel comfortable merging this.

**Comment by Thiago4532** [comment]
> I disagree, because this could leave user buffers in irrecoverable states if the server is force-quit in the middle of a reformatting operation or code-action. TJ may feel differently, but I don't feel comfortable merging this.

I agree with you, I don't think force_exit is the best way to handle this problem, but I wrote that to let the user decide which option best suits them. Maybe warning about this and orphan language servers on documentation is a good way to prevent normal users from let them language servers on a bad state.

**Comment by Thiago4532** [comment]
> I disagree, because this could leave user buffers in irrecoverable states if the server is force-quit in the middle of a reformatting operation or code-action. TJ may feel differently, but I don't feel comfortable merging this.

Sorry if I didn't explain it properly, but the user can choose if they want to force_exit, but the default option is to wait the Language Server to close before quitting neovim.

**Comment by Thiago4532** [comment]
I don't think force_exit option is necessary, but `no_wait` can be really useful, the result is basically the same as #14180, but it's optional per language-server, so `jedi-language-server` won't be affected. Because of that, I've decided to remove `force_exit` from the PR.

**Pull request closed without merging**
