### PR TITLE
[RFC] Split third-party recipes into multiple files

### PR DESCRIPTION
**Pull request by equalsraf**
Any chance we can split the build recipes in third-party/CMakelists.txt into multiple files? It would help a lot for cleaning up #810, otherwise CMakeLists.txt just turns into a huge mess.

One thing I would like to do is prevent the recipes from poluting the global scope - in #810 I am wrapping the recipes in CMake functions, it is not a very lean way to do it, so I welcome any suggestion (@jszakmeister any ideas?)

### CODE REVIEW

**Comment by jszakmeister** [comment]
I'm at working, so I don't really have time to look this over at the moment, but I certainly don't mind breaking it into smaller pieces if it helps you get the Windows port going @equalsraf.

I'll have to look at what's going on more closely in #810 to really say anything else, but at the moment I'm pretty swamped with work stuff and a few other responsibilities.  So they best I can say is I'll have a look when I get a chance.  Sorry I can't be more helpful at the moment!

**Comment by jszakmeister** [comment]
@equalsraf I think this is a fine place to start.  I believe this is going to be just like any other part of the system: we'll revisit it a few times before we land a solution that's more ideal.  But I think this is fine direction to move in.

Note: there's apparently a conflict with this on master now.  Can you rebase it when you get a chance?  I probably won't get much opportunity to look at it again until Sunday, so take your time... there's no rush.  Thanks!

**Comment by equalsraf** [comment]
My idea was to change the recipes into something like [this](https://github.com/equalsraf/neovim/blob/tb-scope-isolation/third-party/cmake/BuildLibuv.cmake), turning the recipes into reusable functions.

But maybe its better to keep this PR simple and just split the files - otherwise we end up getting a merge conflict everytime someone touches CMakeLists.txt.

**Comment by jszakmeister** [comment]
Grrr...  I'm pretty sure I didn't get an email from GitHub with your comment and more stuff has landed. :-(  @equalsraf can you rebase again.  @justinmk can you keep an eye out for this too?  The change is good, but we keep merging stuff in that conflicts.  I just did it myself. :-(  If @equalsraf gets this rebased, we should turn around and merge it.  I'll try and keep an eye out too, but day job often interferes.

**Comment by justinmk** [comment]
Ok

**Comment by jszakmeister** [comment]
Thank you @equalsraf!

**Comment by equalsraf** [comment]
No problem. Sorry about the delays I've pretty busy on my end.

**Pull request merged**
