### PR TITLE
Changes for new VTermColor struct (libvterm 0.1)

### LINKED ISSUE #9393: :terminal : latest libvterm allows us to avoid "palette index" hack
via @leonerd :

> latest libvterm has changes to VTermColor API - new functions required otherwise colours will be all wrong. But as a plus side: you now get per-cell index information if available

related https://github.com/neovim/neovim/pull/7406 https://github.com/neovim/neovim/issues/4099  https://github.com/neovim/neovim/issues/4696  https://github.com/neovim/neovim/issues/7018  https://github.com/neovim/neovim/pull/7406 https://github.com/neovim/neovim/issues/8301

### PR DESCRIPTION
**Pull request by leonerd**
Fixes #9393

### CODE REVIEW

**Comment by justinmk** [comment]
note to self:

- [ ] if we take this change as-is we will need to set minimum libvterm version `find_package(LibVterm ??? REQUIRED)`
- [ ] the bundled dep already pulls the latest libvterm: https://github.com/neovim/libvterm/commit/3f62ac6b7bdffda39d68f723fb1806dfd6d6382d

**Comment by justinmk** [comment]
CI fails to build on all systems.

```
../src/nvim/terminal.c:169:27: error: no member named 'rgb' in 'VTermColor'
  default_vt_fg = RGB_(fg.rgb.red, fg.rgb.green, fg.rgb.blue);
                       ~~ ^
../src/nvim/macros.h:151:25: note: expanded from macro 'RGB_'
#define RGB_(r, g, b) ((r << 16) | (g << 8) | b)
```

**Comment by leonerd** [comment]
For reference from IRC:

```
13:03 <JustinMKeyesGitt> so what's the most recent bzr number we can tell homebrew is safe to update to ?
13:03 <LeoNerd> 726 for now
13:03 <LeoNerd> Once you've merged my PR, 727
```

**Comment by blueyed** [comment]
Force-push was for revert (due to causing a conflict with master).

For this to work we need to update the libvterm version (https://github.com/neovim/neovim/pull/9494/commits/ba204ad8b80462e04c1f3939da3ec17a336843ad).

I can push that here, but needs a rebase then also (which would be good anyway).

@leonerd 
Please let me know if I can do it here.

**Comment by blueyed** [comment]
> * if we take this change as-is we will need to set minimum libvterm version `find_package(LibVterm ??? REQUIRED)`

libvterm has no versioning, has it?  (i.e. I have `/usr/lib/libvterm.so.0.0.0` here)
(this also explains https://github.com/neovim/neovim/issues/10179#issuecomment-501268774 now better)

**Comment by blueyed** [comment]
Went ahead and rebased it (old head: 9b4244a33).

(Missing) versioning is still an issue.
Do we need / can we do runtime detection for this then?  (if not version gets added/bumped)

**Comment by blueyed** [comment]
Note that there are (new) warnings, and If I remember correctly one of them was reported to be significant on the Launchpad tracker.

```
[13/21] Performing install step for 'libvterm'
make[1]: Entering directory '…/Vcs/neovim/.deps/build/src/libvterm'
install -d …/Vcs/neovim/.deps/usr/include
install -m644 include/vterm.h include/vterm_keycodes.h …/Vcs/neovim/.deps/usr/include
install -d …/Vcs/neovim/.deps/usr/lib/pkgconfig
sed -e "s,@PREFIX@,…/Vcs/neovim/.deps/usr," -e "s,@LIBDIR@,…/Vcs/neovim/.deps/usr/lib," -e "s,@VERSION@,0.0," <vterm.pc.in >…/Vcs/neovim/.deps/usr/lib/pkgconfig/vterm.pc
TBL src/encoding/DECdrawing.tbl
TBL src/encoding/uk.tbl
CC src/encoding.c
CC src/keyboard.c
CC src/mouse.c
CC src/parser.c
src/parser.c: In function ‘vterm_input_write’:
src/parser.c:153:51: warning: ‘string_start’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  153 |         more_string(vt, string_start, bytes + pos - string_start);
      |                                       ~~~~~~~~~~~~^~~~~~~~~~~~~~
CC src/pen.c
CC src/screen.c
CC src/state.c
src/state.c: In function ‘request_status_string’:
src/state.c:1567:14: warning: ‘reply’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1567 |         reply--;
      |         ~~~~~^~
CC src/unicode.c
src/unicode.c:306:12: warning: ‘mk_wcswidth_cjk’ defined but not used [-Wunused-function]
  306 | static int mk_wcswidth_cjk(const uint32_t *pwcs, size_t n)
      |            ^~~~~~~~~~~~~~~
src/unicode.c:215:12: warning: ‘mk_wcswidth’ defined but not used [-Wunused-function]
  215 | static int mk_wcswidth(const uint32_t *pwcs, size_t n)
      |            ^~~~~~~~~~~
CC src/vterm.c
LINK libvterm.la
install -d …/Vcs/neovim/.deps/usr/lib
libtool --quiet --mode=install install libvterm.la …/Vcs/neovim/.deps/usr/lib/libvterm.la
libtool --quiet --mode=finish …/Vcs/neovim/.deps/usr/lib
CC bin/unterm.c
CC bin/vterm-ctrl.c
CC bin/vterm-dump.c
install -d …/Vcs/neovim/.deps/usr/bin
libtool --quiet --mode=install install bin/unterm bin/vterm-ctrl bin/vterm-dump …/Vcs/neovim/.deps/usr/bin/
make[1]: Leaving directory '…/Vcs/neovim/.deps/build/src/libvterm'
```

**Comment by blueyed** [comment]
And those in nvim:
```
../src/nvim/terminal.c: In function ‘terminal_open’:
../src/nvim/terminal.c:258:11: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
           (uint8_t)(color_val >> 16) & 0xFF,
           ^
../src/nvim/terminal.c:259:11: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
           (uint8_t)(color_val >> 8) & 0xFF,
           ^
../src/nvim/terminal.c:260:11: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
           (uint8_t)(color_val >> 0) & 0xFF);
           ^
cc1: all warnings being treated as errors
```

**Comment by blueyed** [comment]
Runs into https://github.com/neovim/neovim/issues/10179 now: https://travis-ci.org/neovim/neovim/jobs/549222823#L4938

**Comment by blueyed** [comment]
On AppVeyor:
```
[  ERROR   ] 2 errors, listed below:
[  ERROR   ] ...jects/neovim/test/functional\terminal\highlight_spec.lua @ 118: :terminal highlight has lower precedence than editor #9964
test\functional\ui\screen.lua:554: Row 1 did not match.
Expected:
  |*{N_child:^child nvim                    }|
  |{N_child:line 2                        }|
  |{N_child:                              }|
  |                              |
Actual:
  |*{UNEXPECTED foreground = tonumber('0x0cf0f0'), background = tonumber('0x0b0000'):^child nvim                    }|
  |{UNEXPECTED foreground = tonumber('0x0cf0f0'), background = tonumber('0x0b0000'):line 2                        }|
  |{UNEXPECTED foreground = tonumber('0x0cf0f0'), background = tonumber('0x0b0000'):                              }|
  |                              |
To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  
stack traceback:
	test\functional\ui\screen.lua:554: in function '_wait'
	test\functional\ui\screen.lua:366: in function 'expect'
	...jects/neovim/test/functional\terminal\highlight_spec.lua:139: in function <...jects/neovim/test/functional\terminal\highlight_spec.lua:118>
[  ERROR   ] C:/projects/neovim/test/functional\ui\hlstate_spec.lua @ 177: ext_hlstate detailed highlights work with :terminal
test\functional\ui\screen.lua:554: Row 2 did not match.
Expected:
  |^tty ready                               |
  |*x {5:y z}                                   |
  |{1: }                                       |
  |                                        |
  |                                        |
  |                                        |
  |                                        |
  |                                        |
Actual:
  |^tty ready                               |
  |*x {UNEXPECTED foreground = tonumber('0x0ef0f0'):y z}                                   |
  |{1: }                                       |
  |                                        |
  |                                        |
  |                                        |
  |                                        |
  |                                        |
To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  
stack traceback:
	test\functional\ui\screen.lua:554: in function '_wait'
	test\functional\ui\screen.lua:366: in function 'expect'
	C:/projects/neovim/test/functional\ui\hlstate_spec.lua:205: in function <C:/projects/neovim/test/functional\ui\hlstate_spec.lua:177>
```

**Comment by justinmk** [comment]
> Do we need / can we do runtime detection for this then? (if not version gets added/bumped)

For now let's just assume that we have the current libvterm HEAD. Later, maybe we can check some `VTERM_VERSION` constant if such a thing exists.

**Comment by blueyed** [comment]
Yes, this could be made conditional on compile time (based on if the struct exist) I guess.

There are a few issues here though anyway:

1. https://github.com/neovim/libvterm/commit/f07afc7763dd63b03f8e3f985bff20f2b2815877 appears to be buggy (at least with our tests - reverting it makes them not hang)
2. ASAN reports an issue
3. existing functionaltests (terminal highlight) are failing - have not checked if they need to just be adjusted, or uncovered a problem here.

**Comment by justinmk** [comment]
> There are a few issues here though anyway:

Yes, that's why this is stalled since january :/

**Comment by blueyed** [comment]
Well, those issues were not known back then, were they?
Let's see if @leonerd can shed some light.

**Comment by leonerd** [comment]
@blueyed 

> libvterm has no versioning, has it? (i.e. I have /usr/lib/libvterm.so.0.0.0 here)

Correct. Right now it's still a random mess of half-finished ideas and there are bits of API I *know* I need to fix and change, as right now it limits a lot of things. It's not yet in a state where I'm prepared to call it a "real" 0.1.

For my own purposes doing versioning between the libvterm0 and pangoterm debian packages, I just stick to the `0+bzrNNN` version numbers.

Hopefully sometime I'll get around to doing all the actual API changes I want to make to call it a 0.1. Most of my non-Perl time has been taken up getting libtickit to where it is now.

**Comment by leonerd** [comment]
Small update: I drew a totally arbitrary line in the sand and decided that what I had committed as of that point, is now v0.1. So v0.1 is now a stable, if quite arbitrary, point. No doubt there'll be another one along sometime.

**Comment by blueyed** [comment]
Rebased, removing already merged 918a012d.

**Comment by bfredl** [comment]
Some failures that are larger than just invalid colors:
```
test/functional/ui/screen.lua:587: Row 4 did not match.

Expected:

  |ab^c                                               |

  |{4:~                                                 }|

  |{5:==========                                        }|

  |*rows: 2, cols: 50                                 |

  |{2: }                                                 |

  |{1:==========                                        }|

  |                                                  |

Actual:

  |ab^c                                               |

  |{4:~                                                 }|

  |{5:==========                                        }|

  |*:set laststatus=0                                 |

  |{2: }                                                 |

  |{1:==========                                        }|

  |                                                  |
```

Though something close to the expected state but with wrong colors could been an intermediate state, we could debug this with `screen:redraw_debug()`.

**Comment by blueyed** [comment]
There's also a leak reported now:
```
=================================================================
==15878==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x5636e160017a in malloc (/home/daniel/Vcs/neovim/build/bin/nvim+0xaae17a)
    #1 0x5636e2d1bc1b in default_malloc /home/daniel/Vcs/neovim/.deps/build/src/libvterm/src/vterm.c:14:15

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```
/cc @leonerd

**Comment by bfredl** [comment]
I'm going through the various test failures to see which are spurious and which are actual issues.

- test/functional/terminal/buffer_spec.lua @ 160: :terminal buffer handles loss of focus gracefully

Test is broken, `feed_command('set laststatus=0')` did not work as expected (command was just echoed into empty space). Irrelevant to the functionality under test, so just delete it and update expectation.

- test/functional/terminal/tui_spec.lua @ 92: TUI accepts resize while pager is active

Code/test was fixed recently on master, error might disappear on rebase.

- test/functional/terminal/window_spec.lua @ 152: :terminal with multigrid resizes to requested size

**broken behavior**. `tty-test` doesn't use any coloring with "rows: 10, cols: 20", so this should be entirely unchanged. But this output is completely missing for some reason. Did libvterm change resize handling in 0.1?

- test/functional/terminal/highlight_spec.lua @ 193: :terminal highlight with custom palette will use the custom color

**broken behavior**, palette is not updated? `vterm_state_set_palette_color(state, i, &color)` not working?

**Comment by bfredl** [comment]
Part of the issue seems to be post-0.1 libvterm changes that will require changes in nvim. Trying with libvterm 0.1 on travis.

**Comment by bfredl** [comment]
Fixed some color issues. Remaining issues (will look into ASAP)

- simplify handling of default rgb colors. We should be able to eliminate the dummy `VTerm` instance in `terminal_init`
- Do not hardcode the value of `'termguicolors'` at the time of `terminal_open` (broken since three years or something)
- Patch `vterm->tmpbuffer` memory leak in libvterm 0.1.

**Comment by blueyed** [comment]
> * Patch `vterm->tmpbuffer` memory leak in libvterm 0.1.

This should be done in libvterm itself, no?

**Comment by bfredl** [comment]
@blueyed Yes, why would it not be?

**Comment by bfredl** [comment]
Tests are now passing.

**Comment by justinmk** [comment]
I think we should stick to the `nvim` branch in https://github.com/neovim/libvterm/ rather than creating a new `v0.1` branch. Otherwise that complicates the notes at https://github.com/neovim/neovim/wiki/Deps#forks . So `v0.1` branch now needs to be merged into the `nvim` branch, and we should delete the `v0.1` branch, we don't want to maintain extra branches.

**Comment by dsturnbull** [comment]
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/neovim/HEAD-b735583 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DLIBLUV_INCLU
==> make install
Last 15 lines from /Users/david/Library/Logs/Homebrew/neovim/07.make:
                                              ~~~~~ ^
/tmp/neovim-20190911-99159-11trx6u/src/nvim/macros.h:154:47: note: expanded from macro 'RGB_'
#define RGB_(r, g, b) ((r << 16) | (g << 8) | b)
                                              ^
/tmp/neovim-20190911-99159-11trx6u/src/nvim/terminal.c:601:32: error: no member named 'indexed' in 'VTermColor'
                     ? cell.fg.indexed.idx + 1 : 0);
                       ~~~~~~~ ^
/tmp/neovim-20190911-99159-11trx6u/src/nvim/terminal.c:603:32: error: no member named 'indexed' in 'VTermColor'
                     ? cell.bg.indexed.idx + 1 : 0);
                       ~~~~~~~ ^
5 errors generated.
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
```

Does the macOS brew need to be updated somehow?

**Comment by justinmk** [comment]
@dsturnbull when was the last time you built HEAD from homebrew? AFAIK it has been broken for months because they consider `--head` to be unsupported. When Nvim 0.4 is released then `--head` should work again in homebrew.

**Comment by bfredl** [comment]
@justinmk do as you like. I just used `v0.1` to be able to at all push the commit into the repo (I don't think git supports anonymous pushes)

**Comment by bfredl** [comment]
Also pulling from the bzr upstream in a local git repo and then pushing it to the `neovim/libvterm` repo (rather than reimporting it from scratch) should fix the "history reset" issue. I always get proper fast-forward pulls when updating `libvterm` and `pangoterm` master branches locally using `git-bzr-remote`.

**Comment by blueyed** [comment]
@bfredl @justinmk 
I think the issue discussed in  https://github.com/neovim/libvterm/commit/b45b648cab73f9667bde7c0c6045b285e22b3ecd#commitcomment-34041965 might only have happened once (e.g. when switching the method of how it gets done).

**Pull request merged**
