### PR TITLE
refactor(api): use a keyset for highlight dicts

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by lewis6991** [comment]
Must be missing testcases.

**Comment by clason** [comment]
*quod licet iovi* :]

**Comment by clason** [comment]
Sorry, that sounded like a complaint, which it wasn't meant to be. I just wanted to check whether I was missing something before opening a PR. (For example, the non-support for `inverse` may have been intentional.)

**Comment by bfredl** [comment]
@clason Sure those are valid questions, they just don't have anything to with this PR. at all. Usually _new_ considerations are better asked in a new issue/PR or chat than necroing an old PR doing something unrelated to the same subsystem.

> To be clear, there is no regression (of course) for the "old" :highlight.

There is no regression to the API either.

**Comment by clason** [comment]
Fair, I'll keep that in mind. There was just a report that claimed to have bisected to this PR, which I probably should not have taken at face value.

**Comment by bfredl** [comment]
@clason also fair. A bisect is of course a valid thing to note right here, but it is good to _link_ such a report in such a case, rather than leave a vague implication :]

**Comment by clason** [comment]
'twas in chat, which makes it hard to link ;) In any case, this was not the right venue for a check, which is duly noted. Follow-up discussion can happen at https://github.com/neovim/neovim/pull/17377  :)

**Comment by clason** [comment]
To be clear (and just recording this for posterity since chat is ephemeral), it was an X+Y problem:

1. strikethrough via `nvim_set_hl` has never worked but just silently failed to apply;
2. with this PR, the unsupported attribute is now an error.

Point 2 is what triggered the report. I apologize for the poor communication here and promise to do better in the future.

**Pull request merged**
