### PR TITLE
[RFC] vim-patch:7.4.1986,version.c:,mark,NA,patches,(#5621)

### PR DESCRIPTION
**Pull request by PurinLord**
#### vim-patch:7.4.1986

Problem:    Compiler warns for loss of data.
Solution:   Use size_t instead of int. (Christian Brabandt)

https://github.com/vim/vim/commit/fef524bbff9aa186838c35212b2f89f61d627cf8

#### version.c: mark NA patches (#5621)

### CODE REVIEW

**Comment by brcolow** [comment]
The commit corresponding to 7.4.1986 is empty. Is this intentional?

**Comment by PurinLord** [comment]
I'm sorry I'm new to big git project. What commit? I put "version.c: mark NA patches (#5621)" as the commit tile. Is that ok?
Also, do I have to fix the unsuccessful build problem? because all I changed was de NA comment en vercion.c

**Comment by FriedSock** [comment]
I think @brcolow is referring to commit `	60a2aa8`. Id recommend using an interactive rebase to remove the commit from the branch: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

However, patch 7.4.1986  is part of an existing WIP PR that you linked to, so we should probably close this.

**Comment by PurinLord** [comment]
So next time I should remove the commit from the vim patch, and then put an appropriate commit for nvim before I push the patch??

**Comment by jamessan** [comment]
If you're marking a Vim patch as NA, then there's no need to run `vim-patch.sh` to patch it.  Just modify `version.c` to mark it as NA.  Also, we try to mark a bunch of patches as NA at once (c.f., #5743, #5380, etc.).

**Pull request closed without merging**
