### PR TITLE
vim-patch:8.1.{0846,0878,0884,2358},8.2.{0305,0352,0687,3797}

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.1.0846: not easy to recognize the system Vim runs on

Problem:    Not easy to recognize the system Vim runs on.
Solution:   Add more items to the features list. (Ozaki Kiichi, closes vim/vim#3855)
https://github.com/vim/vim/commit/39536dd557e847e80572044c2be319db5886abe3

Some doc changes have already been applied. Some others are N/A.
"moon" was removed in patch 8.2.0427 so I did not add it.

#### vim-patch:8.1.0878: test for has('bsd') fails on some BSD systems

Problem:    Test for has('bsd') fails on some BSD systems.
Solution:   Adjust the uname match. (James McCoy, closes vim/vim#3909)
https://github.com/vim/vim/commit/a02e3f65c52a2c8c987e7dcac5df1f8db9a7b0de

#### vim-patch:8.1.0884: double check for bsd systems

Problem:    Double check for bsd systems.
Solution:   Delete the old line.
https://github.com/vim/vim/commit/af630d4f7f8daa7edbda0b607d32d39a5feae9d9

#### vim-patch:8.1.2358: tests fail on Cirrus CI for FreeBSD

Problem:    Tests fail on Cirrus CI for FreeBSD.
Solution:   Fix a test and skip some. (Christian Brabandt, closes vim/vim#5281)
https://github.com/vim/vim/commit/9134f1ecd41207045db3cb47f0269497980395ad
    
Skip test_normal.vim: already applied in #11483.

#### vim-patch:8.2.0305: relativenumber test fails on some systems

Problem:    Relativenumber test fails on some systems. (James McCoy)
Solution:   Clear the command line.
https://github.com/vim/vim/commit/8040a7147f5b896a702d1684e7831df107490f45

#### vim-patch:8.2.0352: FreeBSD: test for sourcing utf-8 is skipped

Problem:    FreeBSD: test for sourcing utf-8 is skipped.
Solution:   Run the matchadd_conceal test separately to avoid that setting
            'term' to "ansi" causes problems for other tests. (Ozaki Kiichi,
            closes vim/vim#5721)
https://github.com/vim/vim/commit/36ddf9383181f93b080eb26121bdff37e394d2db

#### vim-patch:8.2.0687: some tests do not work on FreeBSD

Problem:    Some tests do not work on FreeBSD.
Solution:   Enable modeline.  Use WaitFor() in more cases. (Ozaki Kiichi,
            closes vim/vim#6036)
https://github.com/vim/vim/commit/41d4299f26cc98e253f9c63f8adc9dbb9d49ed5c

#### vim-patch:8.2.3797: no good reason to limit the message history in tiny version

Problem:    No good reason to limit the message history in the tiny version.
Solution:   Always use 200.
https://github.com/vim/vim/commit/1e78deb0779bc403a914712f0842a65d2949dfdf

Some of patch 8.1.0846 and patch 8.1.2358 were ported in #11483, which accidentally marked these two patches as fully ported.

### CODE REVIEW

**Comment by zeertzjq** [comment]
I don't know whether that `"sun"` should be added. `"moon"` was removed in patch 8.2.0427 so I did not add it.

**Comment by jamessan** [comment]
> I don't know whether that `"sun"` should be added. `"moon"` was removed in patch 8.2.0427 so I did not add it.

`"moon"` was just an easter egg for non-Solaris systems.  Prior to 8.2.0427, `:echo has("moon")` would be true on systems where there was no sun.  Leaving out `"moon"` is fine, but we _should_ have `"sun"` (as you do).

**Comment by jamessan** [comment]
* Missing 8.1.0846's doc change about [blob slicing](https://github.com/vim/vim/blob/39536dd557e847e80572044c2be319db5886abe3/runtime/doc/eval.txt#L699)

Otherwise, looks good.

**Comment by zeertzjq** [comment]
Thanks. I found the wrong section when grepping and thought it was already applied.

**Pull request merged**
