### PR TITLE
[RFC] Generate list of VimL functions as well

### PR DESCRIPTION
**Pull request by ZyX-I**
I have also played with replacing bidirectional search with using hashes: https://github.com/ZyX-I/neovim/tree/gen-eval-funcs-hash, but do not like the result and want to ask whether it is worth messing with further (e.g. by reimplementing khash.h in lua or doing this in some DSL and compiling both to lua and C). Details on why I did not like it are in comment message.

### CODE REVIEW

**Comment by tarruda** [comment]
I wonder if it would be worth to split the function/command implementations/declarations into multiple  cmake submodules. 

We could start by extracting all code/declarations for math-related functions into  a new cmake submodule. The same could be done for other functions/commands that belongs to a certain group or topic(eg: job control, msgpack-rpc).

While it would not be trivial with a plain cmake build system, the fact that we already depend on lua to build can be an advantage for implementing this. For example, each submodule could contain a lua file/table containing declarations of the functions/commands defined in the module, which would then be discovered by the top-level command/function generator script to include its declarations/implementations into the final C arrays that gets compiled with the rest of the code.

This would open the path for splitting eval.c, ex_cmds.c, ex_cmds2.c(and possible its lua successors in @ZyX-I translator branch).

**Comment by ZyX-I** [comment]
@tarruda You mean, write those in some DSL and compile to the whatever is the current “backend” (be it C at first now or translator later)?

**Comment by tarruda** [comment]
> @tarruda You mean, write those in some DSL and compile to the whatever is the current “backend” (be it C at first now or translator later)?

No, I mean to use the same format that is currently used to declare ex commands(in master branch) and function(this PR) but in a more modular way: Instead of a single file containing all declarations and a single file containing all implementations, split those in submodules. For example, consider this directory tree:

* src
  * nvim
    * math
      * declarations.lua
      * math.c
    * job
      * declarations.lua
      * job.c

each nvim subdirectory contains both a declarations file(same format as eval.lua in this PR) and a C file containing the implementation. The top-level generator would discover this during build and generate a single table from all of them. This kind of layout could improve overall project modularization by splitting big files like eval.c, and as a bonus we'd get vim build-time feature selection without any `#ifdefs` in the main code(For example, one could potentially disable the job control feature by simply blacklisting the job directory from the generator script)

This concept could easily be migrated to the viml->lua branch(it would actually be simpler, since the viml functions are implemented in lua and not C and there's no need for declarations)

**Comment by justinmk** [comment]
> Instead of a single file containing all declarations and a single file containing all implementations, split those in submodules. For example, consider this directory tree:

Why? 

> each nvim subdirectory contains both a declarations file(same format as eval.lua in this PR) and a C file containing the implementation. The top-level generator would discover this during build and generate a single table from all of them. This kind of layout could improve overall project modularization by splitting big files like eval.c, and as a bonus we'd get vim build-time feature selection without any #ifdefs in the main code(For example, one could potentially disable the job control feature by simply blacklisting the job directory from the generator script)

This seems like massive over-engineering. What is the gain here?

I have been thinking a lot about dependencies in recent years.

- Joe Armstrong (Erlang author): [Why do we need modules at all?](http://erlang.org/pipermail/erlang-questions/2011-May/058768.html)
- Rick Hickey: [The Value of Values](http://www.infoq.com/presentations/Value-Values)

On the Neovim project alone, dependencies and non-mainstream choices have cost us non-trivial work and time--though I also recognize that being too conservative would have prevented some productive changes as well.

More generally, OOP religion often drives modularization beyond what is actually useful and often turns simple systems into over-engineered burdens. For C in particular[1] super-hierarchies of folders and clever build systems are not idiomatic, and in my observation are counter-productive. E.g. [git](https://github.com/git/git) has a pretty flat hierarchy.

Large modules are only a problem if the functions **share state**. Since C doesn't have objects, shared state in a module is not common (and we should continue to avoid it). But a big file like eval.c is not _per se_ a problem if it only contains functions which do not share state. Breaking it up into modules won't help the _actual problem_ of Vim's global state. 

[1] cf. Java, where hierarchies are ever-present, and the tooling and type system allow the developer to shrug it off--not the case in C.

**Comment by ZyX-I** [comment]
I neither see what is the advantage of the very big bunch of small files, except for making navigation between them more clumsy. Using DSL at least makes some sense: you

1. Abstract over actual implementation.
2. Move large portion of code out of eval.c.

Also what’s the point of readding feature selection while I always thought that feature selection was intentionally *removed* from Neovim as we are not targeting systems where this makes any sense (the only purpose for removing features I know is making binary smaller and faster which does not matter on the modern PC).

**Comment by justinmk** [comment]
> Also what’s the point of readding feature selection while I always thought that feature selection was intentionally removed from Neovim

Strongly agree. Moreover feature selection means a combinatorial number of configurations to test.

**Comment by ZyX-I** [comment]
This is now part of #4934.

**Pull request closed without merging**
