### PR TITLE
fix(winbar): allow winbar to display a ruler

### LINKED ISSUE #18645: winbar does not update when the cursor moves
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1709-g69853a622 (nightly https://github.com/neovim/neovim/commit/69853a622a1fa9b920171657a255648e532bd444)

### Vim (not Nvim) behaves the same?

`winbar` is neovim specific only

### Operating system/version

macOS 12.3.1

### Terminal name/version

kitty terminal 0.24.3

### $TERM environment variable

xterm-kitty

### Installation

brew install neovim --HEAD

### How to reproduce the issue

Add this piece of code in `init.vim`

```
let g:cnt = 0
function AddOne()
  let g:cnt = g:cnt + 1
  echom g:cnt
endfunction

set winbar=%{AddOne()}
```

Use a counter to test whether `winbar` gets updated when we move the cursor. 

Then open any file and move the cursor. The counter value is unchanged when we move the cursor.

### Expected behavior

The updates of `winbar` should be the same with `statusline`, i.e., when we move the cursor, `winbar` should update. 

When we use `winbar` to display the treesitter context (like nvim-gps) or LSP symbols, it should update along with the cursor movement. Otherwise, we have to use `autocmd CursorMoved * set winbar=...` to update the `winbar`.

### Actual behavior

winbar does not update when the cursor moves.

### PR DESCRIPTION
**Pull request by bfredl**
fixes https://github.com/neovim/neovim/issues/18645

### CODE REVIEW

**Comment by rockyzhang24** [comment]
I think this is ready to merge 🥳😊.

**Comment by rockyzhang24** [comment]
Hi @bfredl sorry to ask could you please merge this? Thanks a lot.

**Comment by rockyzhang24** [comment]
I just built neovim using this PR to test. The `winbar` update issue when the cursor moves was solved. It works very well.

**Comment by dundargoc** [comment]
@rockyzhang24 great to see you're excited for this fix :). Please don't rush the author though. This will get merged when it's finished and not before, and @bfredl is the best person to determine this :). Please be patient.

**Comment by rockyzhang24** [comment]
@dundargoc Okay. Sincerely apologize.

I asked that because I wanted to decide whether I needed to remove neovim installed from brew and built it using this PR by myself, or wait for the merge and update it via brew. I didn't mean to push the author. So sorry about that.

**Comment by rockyzhang24** [comment]
Good job @bfredl Really appreciate your hard work.

**Pull request merged**
