### PR TITLE
[RFC] vim-patch:7.4.1673

### PR DESCRIPTION
**Pull request by munyari**
Problem:    The justify plugin has to be copied or sourced to be used.
Solution:   Turn it into a package.

https://github.com/vim/vim/commit/2946d0236dc9e23ec0050feacdb959b9ae5672a8

Justification for changes that do not carry over
- `Filelist` does not exist in neovim
- neovim does not have a `README.txt` in `runtime/macros`

See #5040

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! Missing change to version.c, though.

**Comment by munyari** [comment]
@justinmk you mean adding 1673 to `src/nvim/version.c`?

**Comment by justinmk** [comment]
Uncommenting it, yes.

**Comment by munyari** [comment]
done

**Comment by KillTheMule** [comment]
You should squash those commits into one. Rebase freely in a PR :)

**Comment by munyari** [comment]
I think it should be good now

**Pull request merged**
