### PR TITLE
Add libiconv and gettext tools to bundled dependencies

### PR DESCRIPTION
**Pull request by b-r-o-c-k**
Building the gettext tools doesn't actually require many dependencies, as I had previously thought. The documentation isn't very clear about which ones are actually required, so after further investigation I found that the only one really needed is libiconv. This works out well because libiconv is also needed for Neovim.

### CODE REVIEW

**Comment by janlazo** [comment]
Can you test with all builds enabled?

**Comment by janlazo** [comment]
Is this ready? All Appveyor builds (except gcov) passed.

**Comment by justinmk** [comment]
The `string(REPLACE` stuff looks like hell to maintain, but I suppose we won't need to change gettext/iconv versions for a long time.

Otherwise this is great! It fixes the build and allows us to remove the `DYNAMIC_ICONV` handling: #3457

**Comment by justinmk** [comment]
merged without d573f2f88f3762def4aaef51512b94bc39a61937 . Thanks @b-r-o-c-k !

**Pull request closed without merging**
