### PR TITLE
build(deps): bump luv to HEAD

### PR DESCRIPTION
**Pull request by clason**
- build(deps): bump Luv to HEAD - [093a977b8](https://github.com/neovim/neovim/pull/22832/commits/2d840b6b77db3ee39f3aed4b37037df6e697b518)
- docs(luvref): update to version bump

### CODE REVIEW

**Comment by clason** [comment]
TSAN failure is reproducible and due to recent thread changes @bfredl

**Comment by zhaozg** [comment]
> TSAN failure is reproducible and due to recent thread changes @bfredl

If luv introduce new bugs,  please let me know or open issue at https://github.com/luvit/luv/issues

**Comment by zhaozg** [comment]
Add a new luv new PR, https://github.com/luvit/luv/pull/641.

Maybe resolve this issue.

**Comment by clason** [comment]
@zhaozg that seems to have fixed it, thanks!

**Pull request merged**
