### PR TITLE
ci: add backport PR action

### PR DESCRIPTION
**Pull request by mjlbach**
You can trigger the backport action by marking a PR with the label `backport <branchname>` or by writing a comment containing /backport on a merged pull request.

See here for usage:

https://github.com/zeebe-io/backport-action#usage

We would need to adjust our labels to `backport release-0.5` or use the `\backport` command after applying the label, which will re-trigger the action.

### CODE REVIEW

**Comment by mjlbach** [comment]
Needs squash, but LMK what you think.

**Review by justinmk — APPROVED** [review]
yes pleaseeeee

**Comment by justinmk** [comment]
Not a blocker but would be great if we could prefix the PR titles with `backport: ...`. Maybe the commit messages too?

**Comment by mjlbach** [comment]
@jamessan Gave me a think emoji on matrix so I wanted to hear his thoughts haha. This is the same action used by nixpkgs fwiw.

**Review by jamessan — APPROVED** [review]

**Comment by mjlbach** [comment]
There's a bug in the latest version of the backport action, I filed an upstream issue https://github.com/zeebe-io/backport-action/issues/175

**Review by dundargoc — APPROVED** [review]
Looks good.

**Pull request merged**
