### PR TITLE
vim-patch:8.1.2019: 'cursorline' always highlights the whole line

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.1.2019: 'cursorline' always highlights the whole line

Problem:    'cursorline' always highlights the whole line.
Solution:   Add 'cursorlineopt' to specify what is highlighted.
            (closes vim/vim#4693)
https://github.com/vim/vim/commit/410e98a70bc00ea4bed51e55a8fe20e56a72c087

I also tired to port 8.1.2029, but could not make low priority screenline highlighting work.

### CODE REVIEW

**Review by janlazo — APPROVED** [review]
LGTM

**Comment by janlazo** [comment]
Patch v8.1.2029 requires follow-up patches because of the `TODO` comment.

**Comment by zeertzjq** [comment]
> Patch v8.1.2029 requires follow-up patches because of the `TODO` comment.

That should be 8.1.2214.

**Comment by zeertzjq** [comment]
I ported 8.1.2029 and 8.1.2214 in #15226.

**Pull request merged**
