### PR TITLE
win_viewport event for buffer range and buffer cursor pos

### LINKED ISSUE #8854: API/UI: emit scroll event
It's not possible to detect window scroll right now, I've request vim to have scroll autocmd, but no response.

Since neovim have buffer update events, maybe it could be easier to have window scroll events for clients.

Scroll event could be used for improve performance, for example, we can add highlight only to visible lines and update the highlight on scroll.

### LINKED ISSUE #11584: API: UI event with real (not screen) cursor position
Currently `grid_cursor_goto`/`cursor_goto` is telling only the screen position. There is no way to get real cursor position without resorting to `nvim_win_get_cursor()`. This is big headache when you can't blindly render what you've got in `grid_lines` event and you need to maintain cursor position in external text document.

something like `grid_cursor_pos` with `[grid, line, column]` arguments would work

also related #11369

### PR DESCRIPTION
**Pull request by bfredl**
fixes #11584 and fixes #8854  

Needs non-dummy tests for various situations, as well as better docs.

### CODE REVIEW

**Comment by bfredl** [comment]
issue reported by @hasufell on gitter:

> I think the viewport doesn't update when you scroll beyond the viewable area. E.g. if you scroll so far down that line 2000 for example is the last one and the only one you see in your window.
basically, in that stage, bottom should be 2001 and top should be 1999

**Comment by hasufell** [comment]
I think the event fires only when the cursor changes the current line. Ideally it should fire on any change to the values that are passed in.

**Comment by bfredl** [comment]
some places were missing, it might be better now. But I will do more testing myself later.

**Comment by hasufell** [comment]
> some places were missing, it might be better now. But I will do more testing myself later.

Seems to work better now.

**Comment by bfredl** [comment]
TODO: `nvim_win_set_viewport` (probably separate PR)

**Comment by asvetliakov** [comment]
Very exited! This is crucial step for external integrations

**Comment by jgehrig** [comment]
Very cool! I am excited to see where this goes...

Several GUIs get user feedback that scrollbars are an important missing feature. Currently, there isn't a good API. This would make such features less hacky and easier to implement!

**Comment by bfredl** [comment]
Sorry for the delay. I'm going to merge this to master soon. There are probably more edge cases that need handling but the best way to discover them is to get UI:s to try this on master.

**Comment by jgehrig** [comment]
No worries, thanks for checking this in!

I will implement this for neovim-qt and let you know of any edge cases I find.

**Comment by bfredl** [comment]
Failure in big endian build (unrelated):

```
[----------] Running tests from test/functional/terminal/edit_spec.lua

[ RUN      ] :edit term://* runs TermOpen event: 5.09 ms OK

[ RUN      ] :edit term://* runs TermOpen early enough to set buffer-local 'scrollback': 10548.43 ms FAIL

test/functional/terminal/edit_spec.lua:69: Row 1 did not match.

Expected:

  |*96: foobar          |

  |                    |

  |^[Process exited 0]  |

  |                    |

Actual:

  |*75: foobar          |

  |                    |

  |^[Process exited 0]  |

  |                    |

To print the expect() call that would assert the current screen state, use

screen:snapshot_util(). In case of non-deterministic failures, use

screen:redraw_debug() to show all intermediate screen states.  

stack traceback:

	test/functional/ui/screen.lua:583: in function '_wait'

	test/functional/ui/screen.lua:362: in function 'expect'

	test/functional/terminal/edit_spec.lua:69: in function <test/functional/terminal/edit_spec.lua:38>

[----------] 2 tests from test/functional/terminal/edit_spec.lua (10794.33 ms total)
```

**Comment by jgehrig** [comment]
@bfredl Looks good so far, thanks!

For implementing a scrollbar it is useful to have to total buffer size. Do you think it is worthwhile to add that as a data field to `win_viewport`?

Most clients use something like`line('$')` and `autocmd` to get this information, so there is a workaround available. However without buffer size, `win_viewport` alone cannot be used to implement something like a scrollbar.

**Comment by glacambre** [comment]
@bfredl is there anything in this PR that breaks compatibility with/would expose bugs in existing GUIs? Firenvim's testsuite has been failing a lot these last two weeks and bisecting blames commit 6ca7ebb34 (while Firenvim works flawlessly with 4139678f9).

**Comment by justinmk** [comment]
@glacambre see also https://github.com/neovim/neovim/issues/12104

**Pull request merged**
