### PR TITLE
fix(input): do no reinterpret mouse keys with ALT modifiers

### LINKED ISSUE #13846: nvim_input_mouse("left", "release", "A", …) leaves insert mode
- `nvim --version`: NVIM v0.5.0-dev+1053-g459a6c845

### Steps to reproduce using `nvim -u NORC`

Using any gui (reproduced with Firenvim and Goneovim), enter insert mode and click somewhere while pressing `Alt`.

### Actual behaviour
Neovim leaves insert mode.

### Expected behaviour
Neovim stays in insert mode. This is the behavior Neovim has in v0.4.4. I'll try to bisect when I have time.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #13846

Remove check for MOD_MASK_META as it is for `<T-` which never appears in TUI.
Make small changes to docs.

### CODE REVIEW

**Comment by justinmk** [comment]
wait, does this regress #8226 #13042 ? Those were intentional compromises to address #8213 . These were the "compromise" I refer to in https://github.com/neovim/neovim/issues/18991#issuecomment-1158320469 

see https://github.com/neovim/neovim/issues/15869#issuecomment-932743861

Those changes were covered by tests, I'm surprised CI isn't failing?

**Comment by zeertzjq** [comment]
MOD_MASK_META is for `<T-`. `<M-` is MOD_MASK_ALT.

**Comment by zeertzjq** [comment]
Hmm, maybe docs needs to be tweaked a bit, but not removed.

**Comment by zeertzjq** [comment]
The terminology here is indeed a bit confusing. The `<T-` modifier isn't documented anywhere in Vim. I'm not sure if it is possible to make it less confusing.

**Pull request merged**
