### PR TITLE
vim-patch:8.0.0466

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0466: still macros that should be all-caps**

Problem:    There are still a few macros that should be all-caps.
Solution:   Make a few more macros all-caps.
https://github.com/vim/vim/commit/8820b48654b62472821d9b155fe03ab7ac13a05c

### CODE REVIEW

**Comment by janlazo** [comment]
```
src/nvim/edit.c:1476:  if should always use braces  [readability/braces] [5]
src/nvim/edit.c:1478:  An else should always have braces before it  [readability/braces] [5]
src/nvim/edit.c:2775:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 2774  [whitespace/alignment] [2]
src/nvim/edit.c:2776:  Use true instead of TRUE.  [readability/bool] [4]
src/nvim/edit.c:3740:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 3735  [whitespace/alignment] [2]
src/nvim/edit.c:3741:  Use true instead of TRUE.  [readability/bool] [4]
src/nvim/edit.c:3742:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/nvim/edit.c:3763:  Use true instead of TRUE.  [readability/bool] [4]
src/nvim/edit.c:3764:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/nvim/ex_docmd.c:6771:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/ex_getln.c:4155:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/if_cscope.c:500:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 499  [whitespace/alignment] [2]
src/nvim/if_cscope.c:1262:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 1261  [whitespace/alignment] [2]
src/nvim/mark.c:694:  if should always use braces  [readability/braces] [5]
src/nvim/mark.c:806:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 805  [whitespace/alignment] [2]
src/nvim/mark.c:807:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 805  [whitespace/alignment] [2]
src/nvim/menu.c:828:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/message.c:1038:  if should always use braces  [readability/braces] [5]
src/nvim/message.c:1515:  Do not use preincrement in statements, use postincrement instead  [readability/increment] [5]
src/nvim/message.c:1555:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/normal.c:2936:  if should always use braces  [readability/braces] [5]
src/nvim/screen.c:6657:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/search.c:4379:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 4377  [whitespace/alignment] [2]
src/nvim/search.c:4380:  Use true instead of TRUE.  [readability/bool] [4]
src/nvim/syntax.c:3594:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/syntax.c:7752:  for should always use braces  [readability/braces] [5]
src/nvim/syntax.c:7754:  for should always use braces  [readability/braces] [5]
src/nvim/tag.c:538:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 537  [whitespace/alignment] [2]
src/nvim/tag.c:539:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 537  [whitespace/alignment] [2]
src/nvim/tag.c:576:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/tag.c:963:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 962  [whitespace/alignment] [2]
src/nvim/version.c:1986:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Total errors found: 32
```

**Comment by ckelsel** [comment]
You can run `make lint` before create PR

**Comment by ckelsel** [comment]
```
src/nvim/edit.c:3743:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/nvim/menu.c:828:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
src/nvim/message.c:1555:  Inner expression indentation should be 4  [whitespace/indent] [2]
src/nvim/search.c:4377:  Missing space before asterisk in char*  [whitespace/operators] [2]
Total errors found: 4
ninja: build stopped: subcommand failed.
make: *** [clint-full] Error 1
```

**Comment by janlazo** [comment]
@ckelsel I'm on Windows and I'm not done with #8405.

**Pull request merged**
