### PR TITLE
Remove unneeded global WantQueryMouse

### PR DESCRIPTION
**Pull request by steveno**

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM, thanks.

**Comment by justinmk** [comment]
please squash, and prefix the commit message with `globals.h:` for context.

**Comment by justinmk** [comment]
Also please remove `FEAT_MOUSE_DEC` from `config/config.h.in` in this PR.

**Comment by steveno** [comment]
Do you get notified I pushed the update??

**Comment by justinmk** [comment]
Not exactly, but I often sort PRs by "recently updated". It never hurts to leave a comment though.

**Pull request merged**
