### PR TITLE
vim-patch:8.2.3676: unused runtime file

### PR DESCRIPTION
**Pull request by clason**
Problem:    Unused runtime file.
Solution:   Remove rgb.txt.
https://github.com/vim/vim/commit/309ce251897512d42da2b0df0ff100dc303e688a

### CODE REVIEW

**Comment by chrisbra** [comment]
Has vim patch 8.2.3562 been already been merged? Else nvim still needs rgb.txt

**Comment by clason** [comment]
Neovim doesn't bundle a Win32 GUI, and as far as I can see doesn't reference `rgb.txt` anywhere in the repo. The colors themselves are defined directly in `syntax.c`.

**Comment by jamessan** [comment]
I agree that we can merge this without v8.2.3562, but we _do_ still need that patch to be ported, IMO.  It's not specific to GUIs.  We use the `guibg` and related attributes for `termguicolors`.

**Review by jamessan — APPROVED** [review]

**Comment by clason** [comment]
Yes, I was only talking about _this_ file (and patch) being specific to Win32 GUI; the other patch is a different matter of course.

**Pull request merged**
