### PR TITLE
Fix loading remote plugin error

### PR DESCRIPTION
**Pull request by Shougo**
I have fixed `E121: Undefined variable: g:deoplete#_channel_id` fatal error after @ZyX-I changes merged.

The hint by @zchee.  Thank you!
https://github.com/zchee/neovim/commit/b3597f54f7da2871a572477f0f1fff5fd15240e1

### CODE REVIEW

**Comment by Shougo** [comment]
After ZyX JSON changes, `:UpdateRemotePlugins` behavior is changed.

```
% cat ~/.nvim/.init.vim-rplugin\~
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/shougo/work/denite.nvim/rplugin/python3/denite', [
      \ {'sync': v:true, 'name': '_denite', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'Denite', 'type': 'command', 'opts': {'nargs': '*'}},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/shougo/work/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:true, 'name': '_deoplete', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins
```

`v:true` or `v:false` is generated.  It is not intended behavior, so the error is occurred.
It must be converted to 1 or 0.

**Comment by bfredl** [comment]
Isn't it better to change remote/define.vim:136 to `', '.string(a:sync)` ? `opts` is already handled the same way here and the old code only worked because `if "1"` is true and `if "0"` if false (yay implicit conversion).

**Comment by bfredl** [comment]
>  It is not intended behavior, so the error is occurred. It must be converted to 1 or 0.

Come on, let's use booleans now that we got 'em :)

**Comment by Shougo** [comment]
@bfredl It cannot be changed.
Because, `string(v:true)` is `v:true` instead of `1`.

**Comment by Shougo** [comment]
The remote plugin handler routine should be refactored for supporting boolean.  But it is not now.

**Comment by bfredl** [comment]
> Because, string(v:true) is v:true instead of 1.

Why not? `if v:true` is true. At least it works when I test it.

**Comment by bfredl** [comment]
> The remote plugin handler routine should be refactored for supporting boolean.

That refactor, in the case of sync, is my suggestion above :)

**Comment by Shougo** [comment]
@bfredl I can get the error, I have tested it...

**Comment by bfredl** [comment]
Maybe I was unclear, this is the patch:
```diff
index dd24829..d2c65eb 100644
--- a/runtime/autoload/remote/define.vim
+++ b/runtime/autoload/remote/define.vim
@@ -133,7 +133,7 @@ function! remote#define#FunctionOnHost(host, method, sync, name, opts)
   exe 'autocmd! '.group.' FuncUndefined '.a:name
         \ .' call remote#define#FunctionBootstrap("'.a:host.'"'
         \ .                                 ', "'.a:method.'"'
-        \ .                                 ', "'.a:sync.'"'
+        \ .                                 ', '.string(a:sync)
         \ .                                 ', "'.a:name.'"'
         \ .                                 ', '.string(a:opts)
         \ .                                 ', "'.group.'"'
```

It fixes it for me, and is consistent with `a:opts`

**Comment by Shougo** [comment]
Did.  But same error.  Did you executed `:UpdateRemotePlugins`?

```
diff --git a/runtime/autoload/remote/define.vim b/runtime/autoload/remote/define.vim
index dd24829..1f99db9 100644
--- a/runtime/autoload/remote/define.vim
+++ b/runtime/autoload/remote/define.vim
@@ -30,7 +30,7 @@ function! remote#define#CommandOnHost(host, method, sync, name, opts)
   exe s:GetCommandPrefix(a:name, a:opts)
         \ .' call remote#define#CommandBootstrap("'.a:host.'"'
         \ .                                ', "'.a:method.'"'
-        \ .                                ', "'.a:sync.'"'
+        \ .                                ', "'.string(a:sync).'"'
         \ .                                ', "'.a:name.'"'
         \ .                                ', '.string(a:opts).''
         \ .                                ', "'.join(forward_args, '').'"'
@@ -94,7 +94,7 @@ function! remote#define#AutocmdOnHost(host, method, sync, name, opts)
   let bootstrap_def = s:GetAutocmdPrefix(a:name, a:opts)
         \ .' call remote#define#AutocmdBootstrap("'.a:host.'"'
         \ .                                ', "'.a:method.'"'
-        \ .                                ', "'.a:sync.'"'
+        \ .                                ', "'.string(a:sync).'"'
         \ .                                ', "'.a:name.'"'
         \ .                                ', '.string(a:opts).''
         \ .                                ', "'.escape(forward, '"').'"'
@@ -133,7 +133,7 @@ function! remote#define#FunctionOnHost(host, method, sync, name, opts)
   exe 'autocmd! '.group.' FuncUndefined '.a:name
         \ .' call remote#define#FunctionBootstrap("'.a:host.'"'
         \ .                                 ', "'.a:method.'"'
-        \ .                                 ', "'.a:sync.'"'
+        \ .                                 ', "'.string(a:sync).'"'
         \ .                                 ', "'.a:name.'"'
         \ .                                 ', '.string(a:opts)
         \ .                                 ', "'.group.'"'
```

**Comment by bfredl** [comment]
it is not the same, you need to remove the `.'"'`

**Comment by Shougo** [comment]
It worked.  Thanks.

**Pull request merged**
