### PR TITLE
eval: Replace internal_refcount hack with proper copyID setting

### PR DESCRIPTION
**Pull request by ZyX-I**

### CODE REVIEW

**Comment by tarruda** [comment]
LGTM, but do you have a similar idea for #3588? In that case the list is local so some other kind of method to prevent garbage collection is needed(see how @oni-link used `lv_watch`)

**Comment by oni-link** [comment]
LGTM.

**Comment by justinmk** [comment]
@ZyX-I can you rebase this?

**Comment by ZyX-I** [comment]
@justinmk Rebased. Note: linter will fail because it was not updated after #3807.

**Pull request merged**
