### PR TITLE
Fix #13715: Weird prompt buffer behavior in neovim but not in vim

### LINKED ISSUE #13715: Weird prompt buffer behavior in neovim but not in vim
- `nvim --version`: 
NVIM v0.5.0-dev+1012-gfe1ebea33-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/rishabh/git/neovim/build/config -I/home/rishabh/git/neovim/src -I/home/rishabh/git/neovim/.deps/usr/include -I/usr/include -I/home/rishabh/git/neovim/build/src/nvim/auto -I/home/rishabh/git/neovim/build/include
Compiled by root@acid-burn

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
- `vim -u DEFAULTS` (version: ) behaves differently?
Yes
- Operating system/version: Arch Linux
- Terminal name/version: ST
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set buftype=prompt<CR>
ihello<ESC>a<BS><BS>
<ESC>Iab

```

### Actual behaviour
3rd line gives `hello` and `l` and `o` are not deleted by backspace in the buffer
4th line gives ^bahello (^ represents the position of the cursor)

### Expected behaviour
3rd line gives `hel`
4th line gives ab^hello (^ represents position of cursor)

### In terms of functional tests
```lua
  it('Insert at start using I', function()
    screen:expect([[
      ^                         |
      ~                        |
      ~                        |
      ~                        |
      [Prompt]                 |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
    feed("i")
    feed("hello<BS><BS>")
    screen:expect([[
      % hel^                    |
      ~                        |
      ~                        |
      ~                        |
      [Prompt] [+]             |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
    feed("<Esc>I")
    feed("ab")
    screen:expect([[
      % ab^hel                  |
      ~                        |
      ~                        |
      ~                        |
      [Prompt] [+]             |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
  end)

end)
```

If if we put these tests in `test/functional/prompt_buffer_spec.lua`, these tests fail. However, these should not fail intuitively.

Even the actual behavior of the second test is different from what we would get in practice:
```
Expected:
  |*% ab^hel                  |
  |~                        |
  |~                        |
  |~                        |
  |[Prompt] [+]             |
  |other buffer             |
  |~                        |
  |~                        |
  |~                        |
  |                         |
Actual:
  |*% ^abhel                  |
  |~                        |
  |~                        |
  |~                        |
  |[Prompt] [+]             |
  |other buffer             |
  |~                        |
  |~                        |
  |~                        |
  |                         |
```

The actual behavior we get is `^bahel`

This is not there in case of vim.

### PR DESCRIPTION
**Pull request by ljmf00**
Fixes #13715.

### CODE REVIEW

**Comment by janlazo** [comment]
Patch 8.1.0035 and related patches weren't ported. Perform a full port instead if needed to fix #13715

**Comment by ljmf00** [comment]
> Patch 8.1.0035 and related patches weren't ported. Perform a full port instead if needed to fix #13715

It seems it was ported, according to commit [`287b359` (#15072)](https://github.com/neovim/neovim/pull/15072/commits/287b3597516c0dbb5b2800aa109d06a648788f9a)

**Comment by seandewar** [comment]
> It seems it was ported, according to commit [`287b359` (#15072)](https://github.com/neovim/neovim/pull/15072/commits/287b3597516c0dbb5b2800aa109d06a648788f9a)

That commit is from a PR that wasn't merged.

**Comment by seandewar** [comment]
Test failures and lint errors (`make lint`) need addressing.

https://builds.sr.ht/~jmk/job/609422#task-functionaltest-1430

**Comment by ljmf00** [comment]
> Patch 8.1.0035 and related patches weren't ported. Perform a full port instead if needed to fix #13715

I'm not going to add the other changes since:
1. They fail the test suite.
2. I don't know what they are doing.
3. I don't know how to fix them.

The fact that I'm not familiar with vim codebase makes it difficult to introduce the other changes, although the current code fixes the described issue and is fairly understandable to me why. If you are willing to add those changes, please consider either co-author this patch or make a patch on top of mine.

**Comment by seandewar** [comment]
> Well, introducing the rest of the changes, as suggested seems to break unrelated tests.

That suggests (if it's not a mistake in the port) additional patches or Nvim-specific changes are also required.
Sometimes porting patches can be a bit messy, and there seems to have been a few unsuccessful attempts in the past unfortunately.

At the very least, if @janlazo is fine with a partial port, the commit description will need to be corrected (v8.1.0035 was never ported), and you'll need to abide by the [conventional commit format](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-messages).

**Comment by seandewar** [comment]
Superseded by #16421, but thanks for the effort.

**Comment by ljmf00** [comment]
> Superseded by #16421, but thanks for the effort.

Thanks for that! :smiley:

**Pull request closed without merging**
