### PR TITLE
vim-patch:8.0.1238, 8.0.1250 (bugfix)

### LINKED ISSUE #2267: IncSearch highlighting remains active after using `C-g` in an empty search command line
- `vim --version`: 8.0.1238
- Operating system/version: Linux/Ubuntu 16.04
- Terminal name/version: rxvt-unicode 9.22
- `$TERM`: xterm-256color

Start Vim like this to edit 2 files:

    vim --clean +'set incsearch hlsearch | colo desert' -O file1 file2

Search for a pattern in the 1st window. Then, press `/` to begin a new search, but don't write anything, just press `C-g` a few times to cycle between the matches of the last search (`:h c^g`). Validate the search or hit Escape to cancel. The highlighting due to the `'incsearch'` option stays active. And if you go to the next window, it follows a region of text surrounding the cursor.

Here's a [gif to illustrate](https://imgur.com/a/rui9i) (here the colorscheme is `desert`, in which the `IncSearch` highlight group seems to be green).

### PR DESCRIPTION
**Pull request by osa1**
### 1238

Problem:    Incremental search only shows one match.
Solution:   When 'incsearch' and and 'hlsearch' are both set highlight all
            matches. (haya14busa, closes vim/vim#2198)

https://github.com/vim/vim/commit/2e51d9a0972080b087d566608472928d5b7b35d7

### 1250 (fixes a bug introduced with 1238 + another bug)

Problem:    'hlsearch' highlighting not removed after incsearch (lacygoill)
Solution:   Redraw all windows. Start search at the end of the match.  Improve
            how CTRL-G works with incremental search. Add tests. (Christian
            Brabandt, Hirohito Higashi, haya14busa, closes vim/vim#2267)

https://github.com/vim/vim/commit/f8f8b2eadbaf3090fcfccbab560de5dbd501833d

### CODE REVIEW

**Comment by osa1** [comment]
This is ready for reviews. Updated the tests and added a new check. Let me know if you want me to add a test.

**Comment by osa1** [comment]
I just realized that this feature is currently buggy (the same bug exists in vim HEAD): if I split the window, start incremental search, I see the search term highlighted in both splits. But when I cancel the search only one of them restored to the old state.

What's the policy here? Should we fix it here? Should we wait for vim to fix it and then port the patch?

**Comment by Shougo** [comment]
It should be reported in Vim issues.

**Comment by osa1** [comment]
Relevant vim issue: https://github.com/vim/vim/issues/2267

**Comment by lacygoill** [comment]
For the feature to work, `'hlsearch'` needs to be enabled, but [some people](https://github.com/neovim/neovim/issues/4429#issuecomment-195881274) may not want to enable it permanently, so the help at `:h 'is` suggests these 2 autocmds:

    augroup vimrc-incsearch-highlight
      autocmd!
      autocmd CmdlineEnter [/\?] :set hlsearch
      autocmd CmdlineLeave [/\?] :set nohlsearch
    augroup END

They rely on the `CmdlineEnter`, `CmdlineLeave` events. I don't know if the patch include them, so I thought it was worth mentioning it.

**Comment by bfredl** [comment]
That would be #7422

**Comment by osa1** [comment]
How should we proceed here?

- This patch brings its own bugs but @haya14busa already [has a solution](https://github.com/vim/vim/issues/2267#issuecomment-340743665) (I also tested it). We can merge this, and wait for vim's fix for the bug, and then port it, or we can just apply @haya14busa's patch in this PR.

- As @lacygoill noted, we may need `CmdlineEnter` and `CmdlineLeave` events for this to work for people who don't want to enable `hlsearch`. I wasn't aware that neovim doesn't have these commands, so I directly copied the documentation from the patch which mentions these commands. We can either remove that documentation and merge it, or wait for #7422 before merging this. (maybe @bfredl can give us an update on that)

Any ideas?

**Comment by KillTheMule** [comment]
Imho merging this before #7422 is asking for trouble. I'd also wait for upstream to fix the known problems.

**Comment by bfredl** [comment]
As this is a "visual" feature that automatically applies existing configurations (`hlsearch`+`incsearch`), let's wait until it works without issues.

**Comment by osa1** [comment]
The issues seem to be fixed in the vim upstream: https://github.com/vim/vim/commit/f8f8b2eadbaf3090fcfccbab560de5dbd501833d . I'll add this patch to the PR.

**Comment by justinmk** [comment]
Mind rebasing?

**Comment by osa1** [comment]
Done.

**Comment by justinmk** [comment]
Travis failure is unrelated, fixed by https://github.com/neovim/neovim/commit/9baa7ca37ff75921820fe5539f962a4e51f632ce

**Comment by osa1** [comment]
Rebased again but it somehow got worse (QuickBuild also fails now). `make test` passes on my laptop.

**Comment by justinmk** [comment]
CI should be in better shape now, after another rebase.

@bfredl Do you see any problem with merging Vim's CmdlineEnter/CmdlineLeave impl as a temporary measure, so that we can move forward with this?

**Comment by bfredl** [comment]
@justinmk But  #7422 is _already_ the closest possibly you could get to the "vim implementation". It must be different because of heavily refactored state logic. I guess what you really want is  #7422 minus `v:event` for now

**Comment by justinmk** [comment]
@osa1 There were a few follow-up patches (not complicated IIRC), if you have some time to include them we can move forward here.

**Comment by osa1** [comment]
@justinmk, I found 3 related patches and included those. Are those what you had in mind? Otherwise let me know which patch do you want and I'll include that as well.

**Comment by osa1** [comment]
Ping @justinmk. Can we merge this?

**Comment by osa1** [comment]
(fixed lint errors and rebased)

**Comment by bfredl** [comment]
Is it intentional behavior that `/X<ESC>` (aborted search, X can be any non-empty string) resets `:noh` for the previous, unrelated search pattern ? (vim does the same, but that doesn't imply it is "right", the code looks like this is supposed to be saved and restored)

**Comment by osa1** [comment]
Restoring `:noh` when search is cancelled sounds like the right thing to do to me, but you'll have to ask Bram about it for details.

**Comment by lacygoill** [comment]
@bfredl I may have misunderstood, but maybe the issue you're describing comes from the code given in the help in the [first commit](https://github.com/neovim/neovim/pull/7463/commits/41394d82365b504c89bb4da9ed5adc11c6f619f0) implementing the feature:

    augroup vimrc-incsearch-highlight
      autocmd!
      autocmd CmdlineEnter [/\?] :set hlsearch
      autocmd CmdlineLeave [/\?] :set nohlsearch
    augroup END

It resets `'hls'` when you leave the command-line, no matter the state of the option when you entered the same command-line. To preserve the state of `'hls'`, you could try something like this:

    augroup vimrc_incsearch_highlight
        au!
        au CmdlineEnter [/\?] call s:toggle_hls(1)
        au CmdlineLeave [/\?] call s:toggle_hls(0)
    augroup END

    fu! s:toggle_hls(on_enter) abort
        if a:on_enter
            let s:hls_on = &hls
            set hls
        else
            if exists('s:hls_on')
                exe 'set '.(s:hls_on ? '' : 'no').'hls'
                unlet! s:hls_on
            endif
        endif
    endfu

**Comment by bfredl** [comment]
@lacygoill If I had used an autocmd I would have mentioned it. My remark wasn't about the option `set [no]hlsearch`, which is always on,  rather the temporary `:nohlsearch` flag. Full steps:

- Do search `/XXX<cr>`, now `XXX` is highlighted
- Turn off highlighting with `:nohlsearch`
- Now begin search `/YYY` (no return!), now `YYY` is highlighted as expected
- Press `<Esc>`, this correctly resets the search pattern to `XXX` but (incorrectly?) starts highlighting `XXX` again, even if the new search had nothing to do with `XXX` pattern.

**Comment by justinmk** [comment]
Looks like this is missing 8.0.1210. I will see if I can port it quickly.

**Comment by osa1** [comment]
You authored the whole patch? :confused:

**Comment by justinmk** [comment]
No, only the merge commit.

**Comment by brcolow** [comment]
@osa1 - https://github.com/neovim/neovim/commits?author=osa1

**Pull request merged**
