### PR TITLE
refactor(lsp): move completion logic into _completion module

### PR DESCRIPTION
**Pull request by mfussenegger**
To reduce cross-chatter between modules and for https://github.com/neovim/neovim/issues/25272
Also preparing for https://github.com/neovim/neovim/issues/25714

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
But note that some plugins may use these utility functions. Best to rip the band-aid off, though, and provide them instead with a better, official, completion API.

(A discussion about how plugins are supposed to extend/replace/hook into the completion and snippet API should follow.)

**Comment by MariaSolOs** [comment]
I _really_ don't want to start a fight but I feel like we're missing a step here.

These functions are being used by widely-used plugins (like `nvim-cmp`), which are recommended in "startup setups" like `kickstart.nvim`. With this change I get a (somewhat concerning for a beginner user) that a soon-to-be-removed function is being used whenever I request completions. Whenever this has happened in the past I've been eager to contribute the update to the plugin (e.g. when all of the `health.report_X` functions got replaced by `vim.health.X`) but in this case plugins are being told not to use something anymore yet we don't have a suitable replacement yet, so I cannot do that.

Because of this I'm leaning towards following [our guidelines](https://github.com/neovim/neovim/blob/3a3e0251267a99eec6cfb2a058f9e992d01107fd/MAINTAIN.md#deprecating-and-removing-features) and softly deprecating these APIs until we have a public replacement.

**Comment by wookayin** [comment]
What's the alternative of the deprecated API `vim.lps.util.parse_snippet` ?

**Comment by mfussenegger** [comment]
`extract_completion_items` is really just `return result.items and result.items or result`, there won't be any replacement for that kind of trivial logic. If the server uses `defaultItems` and once we start supporting it and opt-in to the capability, you likely can't use it anymore anyway.

`text_document_completion_list_to_complete_items` won't see a replacement either, because exposing a public API at that level is just too constraining and hinders us from improving the built-in functionality. It even gets in the way of addressing bugs.


The way `parse_snippet` was used questionable, and I'd like a longer discussion before we expose something similar.
It turned a snippet simply into text, which defeats the main point of using snippets.

For example, in c++ with clangd if you type `std::th` you get the candidates:

- `this_thread`
- `thread`
- `throw_with_nested(Tp && t)`

The last one is a snippet that looks like `throw_with_nested(${1:Tp &&t})`

If you selected that, you end up with `throw_with_nested(Tp &&tt)|` with the cursor at the end, and then you have to backtrack to edit the argument. The user experience would probably be better to just insert `throw_with_nested` instead, to not interrupt the typing flow. Or give the option to expand the snippet properly via `vim.snippet.expand` (which is kinda the plan)


What we can _consider_ is to expose a `parse` function that returns the AST. That would let plugin authors do whatever they want, and also apply transformations and stuff like that. But I wouldn't do that yet, but only after we've used it in anger for a bit and are confident it will stay as it is.


> Because of this I'm leaning towards following our guidelines and softly deprecating these APIs until we have a public replacement.

I've been advocating for this soft-deprecation in other places, (Like with `get_active_clients()`, which has a huge reach). In this case I opted to fast track it, because the functions are more niche (targeting only completion), and I don't want to drag this out longer than necessary.

**Comment by clason** [comment]
> I'm not sure if we want to target beginners with nightly builds.

This. We need to allow ourselves to make radical breaking changes _during the development cycle_, if it's clear that it's a temporary situation that will be resolved (with a better state of things) before the next release.

The alternative would be to keep that huge refactor in a single PR and merge it only once it's fully done, but those tend to turn into Kaneda-style tentacle monsters and die.

**Comment by MariaSolOs** [comment]
@mfussenegger I agree with your comments on `extract_completion_items` and `text_document_completion_list_to_complete_items`.

With regards to `parse_snippet`, `nvim-cmp` uses it for the vim completion `word` (which is the same usage we have today). I agree that this function shouldn't be used as the snippet text to insert and instead `vim.snippet.expand` should be used in that case, but having to parse the snippet AST to define the completion word feels a tad inefficient, and in those cases the "dummy logic" of just returning a string representation of the snippet feels appropriate.

> This. We need to allow ourselves to make radical breaking changes during the development cycle, if it's clear that it's a temporary situation that will be resolved (with a better state of things) before the next release.

@clason fair. I don't want us to slow down, but IMO suddenly deprecating (with a noticeable user impact) a function that doesn't have a suitable replacement yet feels a bit off. After all we're still using `parse_snippet`, so we don't know how to address the deprecation either.

**Comment by mfussenegger** [comment]
To add from chat:  `vim.fn.matchstr(text, "\\k*"` could be a replacement. 

Not sure yet how well it works in general, but for `throw_with_nested(${1:Tp &&t})` it returns `throw_with_nested` which I think is an improvement over the previous behavior for the reasons outlined in my previous comment.

**Pull request merged**
