### PR TITLE
vim-patch:partial 04fb91668482

### PR DESCRIPTION
**Pull request by clason**
Update runtime files
https://github.com/vim/vim/commit/04fb916684829f6aa12f33f14d0d0023b458f200

skip: doc/usr_41.txt (rewritten to focus on vim9script)

### CODE REVIEW

**Review by seandewar — APPROVED** [review]
LGTM.

It's kinda hard to see if we should include some of the changes in that file that are still somewhat relevant (there's a few!). Like https://github.com/vim/vim/commit/04fb916684829f6aa12f33f14d0d0023b458f200#diff-39ce7fc6897bf0e742a197cdeee45ecef2d3590ece65cce1047b6864d0e4efa8L40-R41, https://github.com/vim/vim/commit/04fb916684829f6aa12f33f14d0d0023b458f200#diff-39ce7fc6897bf0e742a197cdeee45ecef2d3590ece65cce1047b6864d0e4efa8R54-R60, and others (like omitting `:` before ex-cmds in script files). :thinking:

**Comment by clason** [comment]
Yes, there are non-vim9script-related changes lumped in -- but nothing really big, so I wasn't too eager to comb through it line by line and apply the relevant changes manually. 

Especially if going forward, we want to replace this with our own Lua-centric plugin guide anyway? Newcomers should be nudged towards scripting Neovim in Lua ;)

**Comment by seandewar** [comment]
Sounds good to me :+1:. Regardless, I don't see anything major in that file that need-be included (though I haven't combed through it as finely as I usually would try to this time :smile:)

**Comment by clason** [comment]
OK; I'll mark it `partial` to indicate that a potentially applicable change was skipped so we can revisit later.

**Pull request merged**
