### PR TITLE
tui: schedule event instead of <FocusGained> pseudokey

### LINKED ISSUE #4840: Focus events cause redraw
The command `nvim -u NORC -c 'echom "foo"' -c 'mess'` in tmux (with `set focus-events on`), will not stop at the hit-ENTER prompt.
Also, if you then manually call `:mess` the output will be removed (as if Enter was pressed) when focus is lost again.
- Neovim version: v0.1.5-329-g748898b
- Vim behaves differently? yes
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode
- `$TERM`: tmux-256color

### LINKED ISSUE #6164: getchar() is getting the internal bytes for FocusGained/FocusLost
in nvim, unlike in vim, getchar() is getting the internal bytes for FocusGained/FocusLost.

I just test this in `nvim -u NORC`.
1. open two termite windows in i3-wm
2. open nvim via `nvim -u NORC` in one of them
3. run `:echo getchar()`
4. move to another windows, you will see `<80><fd>a ` output.

### PR DESCRIPTION
**Pull request by justinmk**
- `eventloop: schedule event instead of <FocusGained> pseudokey`: This commit works in some cases. But there's a subtle problem because of the  different event-loop scheduling mechanisms. `loop_schedule(&main_loop, ...)` puts the event on `fast_events` which is processed at a different stage than a pseudokey on the input queue would be processed.
- `eventloop: FocusGained: schedule the schedule`: this commit convinces the event subsystem to put the event on `main_loop.events` by scheduling a handler _which then_ enqueues another handler directly.

fixes #6164
fixes #4840

### CODE REVIEW

**Comment by justinmk** [comment]
Currently some UIs (oni, neovim.app) call `:doautocmd FocusGained` to "notify" nvim of focus. Other UIs (nvim-qt, VimR) send the `<FocusGained>` pseudokey.

This PR removes `<FocusGained>`, so focus behavior in the latter UIs will break.

**Comment by justinmk** [comment]
@equalsraf @qvacua This will require a change in neovim-qt and VimR.

The VimR change is similar to what we do for the built-in UI (TUI): just call `aucmd_schedule_focusgained()`.

Neovim-Qt change, for the time being, needs to call `nvim_command('doautocmd Focus{Gained,Lost}')`.

**Comment by zackhsi** [comment]
@justinmk what is the recommendation for terminal nvim users? The reload-on-focus I used to have is no longer there.

**Comment by jamessan** [comment]
This shouldn't have changed any visible behavior.  I can confirm that nvim is still reacting to `FocusLost`/`FocusGained` in xterm.

```vim
au FocusLost * echom 'Bye'
au FocusGained * echom 'Hi'
```

Then change focus and you should see Bye/Hi in `:messages`.

**Comment by zackhsi** [comment]
Hmm, you are right. When I switch tabs away from then back to, I see the messages.

But when I background and foreground nvim, I get nothing? Is there a separate trigger I should be looking for to detect backgrounding/foregrounding?

**Comment by jamessan** [comment]
See #3648 and #2127.

**Comment by zackhsi** [comment]
https://github.com/neovim/neovim/issues/3648#issuecomment-199085369 is a lifesaver, thanks :)

**Pull request merged**
