### PR TITLE
ci: enable CI_BUILD on windows

### PR DESCRIPTION
**Pull request by dundargoc**
This will ensure warnings are treated as errors when using MSVC.

Also fix const correctness warnings. The warnings in mbyte.c are false
positives that triggers this warning on MSVC v19.32 and lower, which our
CI still use. The (void *) casts can be removed once the CI MSVC version
has been upgraded to v19.33 or higher.

### CODE REVIEW

**Comment by dundargoc** [comment]
The MSVC shipped with Visual Studio 2019 gives incorrect  "warning C4090: 'function': different 'const' qualifiers" warnings, which currently prevents us from treating windows warnings as errors. We can either deprioritize the warning level for only the warning C4090 or wait until we upgrade the runner image to windows 2022 and then hope the new MSVC has sobered up.

**Comment by dundargoc** [comment]
Uh, people better than me at C convinced me that it's incorrect. I forgot the exact reasons.

@bfredl @ii14 halp

**Comment by dundargoc** [comment]
I recall bfredl mentioning it's incorrect, but it was a while ago so maybe I missed something.

@bfredl could you take a look when you have time and check if the warning is correct?

**Comment by ii14** [comment]
C4090 warning produces false positives on older MSVC versions: https://godbolt.org/z/5K7YWbbPd

**Comment by jamessan** [comment]
In your example, @ii14, changing to `free((char **)p);` eliminates the diagnostic, as I suggested earlier.

**Comment by ii14** [comment]
@jamessan Yes, but it's still a false positive - the freed memory isn't const (mutable pointer to const data) and the code is correct. Looks like it was fixed in MSVC v19.33, because it compiles just fine on that. It's the exact same problem with `const list_T **ptrs` in mbyte.c.

**Comment by jamessan** [comment]
Agreed, but it's a simple workaround to avoid the issue, and doesn't change the semantics.

**Comment by ii14** [comment]
Can't we just disable C4090 on MSVC? I think `/wd4090` should disable it. It's unreliable, and we still have GCC and Clang to check const correctness.

**Comment by jamessan** [comment]
If _every_ C4090 diagnostic is a false positive, then disabling it makes sense. Otherwise, I would lean towards applying the workaround.

**Comment by ii14** [comment]
No, I believe it's checking const in general, so it's just this that's a false positive. I suppose another option would be to use compiler pragmas to disable this warning for that part of code?

**Comment by dundargoc** [comment]
Full list of warnings:

```
D:\a\neovim\neovim\src\nvim\main.c(886): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\nvim\mbyte.c(2751): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\nvim\mbyte.c(2765): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\nvim\mbyte.c(2776): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(784): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(803): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1340): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1563): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1575): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1580): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1597): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1602): warning C4090: 'function': different 'const' qualifiers
D:\a\neovim\neovim\src\cjson\lua_cjson.c(1607): warning C4090: 'function': different 'const' qualifiers
```

**Comment by dundargoc** [comment]
> If every C4090 diagnostic is a false positive, then disabling it makes sense. Otherwise, I would lean towards applying the workaround.

The one in `main.c` isn't a false positive.

**Comment by dundargoc** [comment]
I think all of these warnings are correct except the ones in `mbyte.c`. That'd be 10/13 are correct. Should we just fix these and slap on a pragma on the false ones and call it a day?

**Comment by dundargoc** [comment]
@dundargoc sounds good 👍

**Pull request merged**
