### PR TITLE
refactor: format files with uncrustify

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Review by justinmk — APPROVED** [review]
LGTM but will wait for a few more files?

**Comment by dundargoc** [comment]
Yeah, suspected it might be too few lines. I'll add the os/ files when I get back home.

**Comment by dundargoc** [comment]
Added all `os/*.c` files. Let me know if I should add more/less files.

**Review by justinmk — APPROVED** [review]
LGTM, waiting for CI

**Pull request merged**
