### PR TITLE
[RFC] tests: Migrate legacy test 42.

### PR DESCRIPTION
**Pull request by lucc**
I will squash this later.  Do you think 62b0bb0 is ok?

### CODE REVIEW

**Comment by lucc** [comment]
part of #1286

**Comment by justinmk** [comment]
> Do you think 62b0bb0 is ok?

I don't quite understand the original intention. Why do you think those lines aren't needed?

**Comment by lucc** [comment]
Because the test doesn't fail without them :)

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim/commit/92e43945627ac71ef160e3ecde1bf2913385c7d1

**Pull request closed without merging**
