### PR TITLE
docs: remove "not in vi" notes

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
Are these docs that are already diverged from upstream?

**Comment by zeertzjq** [comment]
Many `not in Vi` notes have already been removed previously.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
I guess we have long passed the point where these are Vim docs with Neovim additions, so alignment with upstream is no longer a primary concern.

**Comment by dundargoc** [comment]
I now see that there are two unpatched vim commits that removes all "not in vi" comments, so I can convert this to a vim patch?

**Comment by zeertzjq** [comment]
IMO no.

**Review by zeertzjq — APPROVED** [review]

**Review by seandewar — APPROVED** [review]

**Pull request merged**
