### PR TITLE
build(deps): bump LibUV to HEAD

### PR DESCRIPTION
**Pull request by clason**
adds `io_uring` support on Linux ~~and native `copyfile` support on macOS~~ (~~thanks~~ sorry @lewis6991!)

### CODE REVIEW

**Comment by clason** [comment]
[Test failure on macOS](https://github.com/neovim/neovim/actions/runs/4573008337/jobs/8072923559?pr=22833#step:12:7493) is reproducible; likely due to https://github.com/libuv/libuv/pull/3654

**Comment by justinmk** [comment]
any notable changes?

**Comment by clason** [comment]
macOS test still fails on `test/old/test_writefile.vim` (locally reproducible) 😭

**Comment by lewis6991** [comment]
ffs, I'm sure I tested this. Does it fail for the same reason?

**Comment by clason** [comment]
Yes, same (old) test. The functional test passes, now.

**Comment by lewis6991** [comment]
Oh so there were two tests? I thought it was just one.

**Comment by lewis6991** [comment]
Does the oldtest fail because of the symlink copying?

**Comment by clason** [comment]
No, it's something about conversion to `utf-16`.

**Comment by clason** [comment]
OK, here's a minimal version of this regression:
1. `cat foo >> foo`
2. `touch bar`
3. `nvim --clean`
4. `lua vim.loop.fs_copyfile('foo', 'bar', { ficlone = true })`
5. `:e bar`

master:
```
foo
```

this PR:
```
```

**Comment by clason** [comment]
@dundargoc the `bump_deps.lua` script seems to need changes to respect the recent `CACHE STRING` for `LIBUV_URL`.

**Comment by nojnhuh** [comment]
It seems that since this change, nvim hangs forever with high CPU on `:q` and never exits when LSP `workspace/didChangeWatchedFiles` is engaged (at least on linux, haven't tested any other platform). I can't tell exactly where it's getting stuck and I haven't found exactly which libuv change is the culprit, but nothing jumps out to me as immediately obvious: https://github.com/libuv/libuv/compare/62c2374a8c005ce9e42088965f8f8af2532c177b...15e81386bf9a285cada688c5faf67b3ed1319dcf?expand=1

**Comment by clason** [comment]
Can you open a new issue with more details (especially your exact platform)?

**Comment by clason** [comment]
If you could bisect the libuv changes, that would be great:
1. clone the libuv repo
2. edit the `cmake.deps/deps.txt` to point the `LIBUV_URL` to the checked out repo (this will ignore the SHA)
3. `git bisect bad` in the libuv repo
4. for every step, `rm .deps/build/src/libuv-stamp/download-libuv.cmake; make` in the neovim repo and test.

**Comment by aktau** [comment]
I experience the same issue. Kernel is ChromeOS M113's 5.15.103-17409 inside of a Crostini container. Unfortunately I haven't figured out how to run Linux perf inside of this container. Perhaps it's something to do with the recently merged io_uring support.

**Comment by nojnhuh** [comment]
Opened #23595

**Comment by clason** [comment]
So that's now 2 out 2 big changes in that libuv that broke Neovim (one already had to be reverted)...

**Comment by nyngwang** [comment]
> It seems that since this change, nvim hangs forever with high CPU on :q and never exits when LSP workspace/didChangeWatchedFiles is engaged [...]

Well, I think I just encountered this when using [oil.nvim](https://github.com/stevearc/oil.nvim), which make use of `vim.loop`! More details have been provided there https://github.com/stevearc/oil.nvim/discussions/105!

**Comment by clason** [comment]
@nojnhuh @mfussenegger could you try building with https://github.com/libuv/libuv/pull/3991 and see if that fixes the hang?

**Pull request merged**
