### PR TITLE
build(cmake): update FindLuv.cmake

### PR DESCRIPTION
**Pull request by ChrisJStone**
Add fedora specefic funtion so cmake can find luv header and library files

### CODE REVIEW

**Comment by cryptomilk** [comment]
On PPC64 or S390x there is no luajit. This is why there is a lua 5.1 luv available on Fedora ...

**Comment by ChrisJStone** [comment]
@cryptomilk Should I use luajit or lua 5.1? In my issue you mentioned I want to use luajit-devl. I have both installed and neovim builds to both.

**Comment by cryptomilk** [comment]
You need to check 5.1 path too but prefer luajit ...

**Comment by clason** [comment]
If at all possible, you should build against LuaJIT (2.1.0-beta3 branch) and not PUC Lua.

**Comment by clason** [comment]
And I strongly suspect that I speak for the whole team when I say that we don't want distro-specific snippets in our build scripts. That sets a _very_ bad precedent.

If your environment deviates from the (reasonable) default expected by our scripts, you should patch them yourself.

**Comment by ChrisJStone** [comment]
@clason Seems to me you all ready have a "distro-specific" snippet considering I'm basing my work off function(ubuntu) in FindLuv.cmake

**Comment by clason** [comment]
Yes, because _we_ build on Ubuntu (Github Actions).

**Comment by ChrisJStone** [comment]
Then might I suggest that the comment be updated to state that it was done specifically for that reason. That way there is no confusion as to why it was done.

**Comment by cryptomilk** [comment]
> If at all possible, you should build against LuaJIT (2.1.0-beta3 branch) and not PUC Lua.

I repeat: There is no luajit on `ppc64` nor `s390x`!

**Comment by clason** [comment]
Well, yes, that's why I wrote "if at all possible". If it's not possible, you don't have a choice: PUC Lua 5.1 (accept no substitute).

**Comment by jamessan** [comment]
> Yes, because _we_ build on Ubuntu (Github Actions).

The change should probably have been made in the CI scripts, then.  That would both provide an example of how to affect this setting without patching and made clear it was being done for our CI.

**Comment by dundargoc** [comment]
I think there's a much simpler workaround for this. Don't put in too much work into this, I will look into restructuring how we find the libraries.

**Comment by ChrisJStone** [comment]
I've done what I can do.

**Comment by dundargoc** [comment]
I've removed traces of OS-specific code [here](https://github.com/neovim/neovim/pull/23938). I can add the path suffixes `luajit-2.1` as well, but it sounded like it's not needed anymore?

**Pull request closed without merging**
