### PR TITLE
[RFC] os_nodetype: impl with libuv

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Comment by sethjackson** [comment]
@justinmk can you rebase this? Also in #810 the `S_ISBLK` check has been guarded (equalsraf@a71a7b6) because as @equalsraf notes there are no block devices on Windows.

**Comment by justinmk** [comment]
Will do.

**Comment by equalsraf** [comment]
Ping rebase, @justinmk other than testing on windows, whats missing here (assuming the BLK/DIR is left as is)?

**Comment by justinmk** [comment]
Just need to find the time.

**Pull request merged**
