### PR TITLE
feat(ui): allow conceal to be defined in decorations

### PR DESCRIPTION
**Pull request by bfredl**
- [x] wire it up to tree-sitter
- [x] allow hl group be changed from `Conceal`, because we can

### CODE REVIEW

**Comment by bfredl** [comment]
update: if `conceal` is set to a char and `hl_group` is also set, it will be used instead of `Conceal` for the cchar.

**Comment by bfredl** [comment]
Concealing in tree-sitter now works. use a `set!` directive like this:
```
("return" @keyword.return
 (set! conceal "R"))
```

 and  `(set! conceal "")` for conceal without cchar.

**Comment by graelo** [comment]
Thanks a lot for this!

If someone looking for a few examples, I've created this for Python: https://gist.github.com/graelo/2d1f5bc6775432a5c8eb6d6c8b624011

**Comment by sisrfeng** [comment]
A short (personal) conclusion for those who are interested in the newest  `conceal` feature:
1. Currently the best usage example in nvim (with tree sitter) is shown above by user graelo.
2. Some people advise improved `cchar` , namely `cstr`, in the (upstream) vim repo, but Vim Creator Bram Moolenaar seems not to be quite interested in  it. So we may not get `cstr` in a short time.
3. Neorg is a good real  (but a little complex) example for using  the conceal feature.
4. (For  advanced developers)  `src/nvim/screen.c` should be the key file related to `conceal`.

**Pull request merged**
