### PR TITLE
build(nix): update flake.lock

### PR DESCRIPTION
**Pull request by jmbaur**
Flake lock file updates:

Updates:
• Updated input 'flake-utils':
    'github:numtide/flake-utils/ff7b65b44d01cf9ba6a71320833626af21126384' (2023-09-12)
  → 'github:numtide/flake-utils/4022d587cbbfd70fe950c1e2083a02621806a725' (2023-12-04)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/e92039b55bcd58469325ded85d4f58dd5a4eaf58' (2023-11-29)
  → 'github:nixos/nixpkgs/54aac082a4d9bb5bbc5c4e899603abfb76a3f6d6' (2023-12-19)

### CODE REVIEW

**Comment by teto** [comment]
May I ask why ? It's always nice to provide some motivation/context to help the maintainer decide whether to merge.
I've tested the main targets with succcess

**Review by teto — APPROVED** [review]

**Comment by jmbaur** [comment]
> May I ask why ? It's always nice to provide some motivation/context to help the maintainer decide whether to merge. I've tested the main targets with succcess

Sorry about that! Meant to get back to this.

The dev shell does not work with the current flake on master, but does work with this update.
Here is the error:
```
luajit2.1-nvim-client> Error: Could not satisfy dependency mpack: No results matching query were found for Lua 5.1.
error: builder for '/nix/store/rdacd24iam4pwgh0sd39sgdqs5j5ghac-luajit2.1-nvim-client-0.2.4-1.drv' failed with exit code 1;
       last 10 log lines:
       > Missing dependencies for nvim-client 0.2.4-1:
       >    mpack (not installed)
       >
       > nvim-client 0.2.4-1 depends on lua >= 5.1 (5.1-1 provided by VM)
       > nvim-client 0.2.4-1 depends on mpack (not installed)
       > Warning: Failed searching manifest: Failed downloading https://luarocks.org/manifest-5.1 - no downloader tool available, please install wget or curl in your system
       > Warning: Failed searching manifest: Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest-5.1 - no downloader tool available, please install wget or curl in your system
       > Warning: Failed searching manifest: Failed downloading https://luafr.org/luarocks/manifest-5.1 - no downloader tool available, please install wget or curl in your system
       >
       > Error: Could not satisfy dependency mpack: No results matching query were found for Lua 5.1.
```

**Comment by dundargoc** [comment]
That should be added to commit message. In general, always aim to mention the problem that is being solved.

**Comment by bfredl** [comment]
As a non-nix user, I'd like to interject for a moment.

I don't really see the point of maintaining these files (nix.flake and flake.lock) as part of our repo. Apparently these files are not nearly close to be "self contained" in any sense of the word, but depend on hash references to custom specific versions of the Nixpkgs repo. To me this just begs the question: why doesn't these files just _live_ inside these commits of the nixpkgs repo?

Then changes to these files would be possible to review as PR:s which contain the actual contents of the files, not as inscrutable hashes one need to be blessed with Special Nix Knowledge to know how to figure out what they even mean.

Interjection over.

**Comment by teto** [comment]
> I don't really see the point of maintaining these files (nix.flake and flake.lock) as part of our repo. Apparently these files are not nearly close to be "self contained" in any sense of the word, but depend on hash references to custom specific versions of the Nixpkgs repo.

The nix package is kinda similar to flatpak/docker. You can run the latest nvim with it. The added benefit is that it gives you also a dev environment with `nix develop ./contrib` (or `nix develop 'github:neovim/neovim?dir=contrib` if you haven't cloned it yet). Ofc the build breaks may break when we update dependencies but that's part of the deal: it's best effort, no new pipelines etc.

I understand if the team wants to remove it since it's not a core aspect of neovim but I guess nix builds makes for the most reproducible builds, making debugging easier. I use the `nix develop` to develop on neovim (less recently) but there are other users. 
I feel like it is low maintainance (@dundargoc let me know if you disagree), just let me deal with those PRs. If I get hit by a bus, feel free to nuke the files.

**Comment by bfredl** [comment]
This **completely** misses the point of my question. The question **WAS NOT** "why would anyone want to build neovim with Nix?"

The question was why should 10% of the code needed to build neovim with Nix live in neovim/neovim while 90% of that code lives in Nixpkgs? Wouldn't it be simpler for the Neovim team AND the Nix team if 100% of this code lives in the Nix repos?

**Comment by teto** [comment]
> he Nix team if 100% of this code lives in the Nix repos?

the nixpkgs repo makes available but like most official repos, it doesn't provide build instructions for dev versions (you would have twice the number of packages to describe). In that regard 

The advantage of having the flake directly in the nix repo is that you reference commits directly:
`nix run 'github:neovim/neovim?dir=contrib&rev=242261d4e77806cdb4559c2be58613113a393a4e'`
(or not `nix run 'github:neovim/neovim?dir=contrib` gets latest version). 
This could work with instance for a sufficiantly updated fork `github.com/nix-community/neovim`. 
But the other aspect I find interesting as well is for development. The flake can get you a development environment with all the dependencies in a manner I find sexier than other approaches (you are in your shell, not a docker image etc). The flake provides differents targets so it can configure the build system with asan, debug symbols etc. 
 
My perception is that it doesn't impact the neovim team much since the nix fixes are brought by nix users. Several reports from the nix users have allowed to detect problems with the build system that would  have happened on any distrib.
If it's a bother to the team let's take the flake down like we took down the deb build, I understand it's not at the core of neovim business.

**Comment by teto** [comment]
maybe more relevant: 
nix can't download arbitrary stuff from the web, it needs a hash for it, which is why you cant have a "dev" version in nixpkgs. nixpkgs can not reference "master" of neovim, it can only reference specific commits. And bumping the commits daily or even weekly would not be allowed for nixpkgs but this could be done in another repository.it would be sad to lose the ability to build arbitrary neovim commits via the nix cli only (one would need a wrapper script to build in "pure"/reproducible mode)

**Pull request merged**
