### PR TITLE
N/A Vim9 patches

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by clason** [comment]
Marking these as N/A implies that we are not going to be merging vim9script support, even in the future. I'm not sure we have firmly committed to that policy yet? (Even though there's currently no plan -- and indeed little appetite -- to do so, this is a somewhat stronger statement.)

**Comment by seandewar** [comment]
I wouldn't do this; many v9 patches contain partially applicable code, and in some cases, there are directly applicable patches that have the Vim9 label in error.

**Comment by clason** [comment]
And vice versa, not every vim9 patch is explicitly labeled as such...

**Comment by lewis6991** [comment]
Agreed. I was a bit rash with this.

**Pull request closed without merging**
