### PR TITLE
normal: Don't exit CTRL-O mode after processing K_EVENT

### LINKED ISSUE #10035: CursorHold exits `i<ctrl-o>` mode
- `nvim --version`: https://github.com/neovim/neovim/commit/5c13f368c650f7a66e562d573d91266d2d8e3264
- Vim (version: ) behaves differently? didn't check
- Operating system/version: linux
- Terminal name/version: pangotem
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:au Cursorhold * let x = 1
type i<c-o>


```

### Actual behaviour

Ctrl-O mode is left after one 'updatetime' 

### Expected behaviour

Ctrl-O mode should remain until the user typed a key.

By suggestion of  @mnarrell on gitter.

### PR DESCRIPTION
**Pull request by bfredl**
fixes #10035

### CODE REVIEW

**Comment by justinmk** [comment]
this would regress 943bedfc86abb2c6ac20079c1c3a4baac1bd726e

**Comment by bfredl** [comment]
@justinmk I'm working on a check that handles both :)

**Comment by bfredl** [comment]
How would https://github.com/neovim/neovim/issues/7254#issuecomment-480569366 fix anything? It would just break everything that relies on CA_COMMAND_BUSY . We need to check if the `restart_edit` came from the event or from the normal state itself.

**Comment by bfredl** [comment]
Latest push makes both `Ctrl-O` and `:startinsert` work.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
