### PR TITLE
feat(lua): enable stack traces in error output

### LINKED ISSUE #16226: Print lua stack trace in :source and :luafile
### Feature already in Vim?

nil

### Feature description

Say you have a file, `1.lua`:
```lua
local function b() error('error') end
local function a() b() end
a()
```
When you `:source` it, vim prints just:
```
:so 1.lua
Error detected while processing /path/to/1.lua:
E5113: Error while calling lua chunk: 1.lua:1: error
```
Similar thing happens with `:lua require '...'`.
Could we add a stack trace like when you run `lua 1.lua`?:
```
$ lua 1.lua
lua: 1.lua:1: error
stack traceback:
	[C]: in function 'error'
	1.lua:1: in function 'b'
	1.lua:2: in function 'a'
	1.lua:3: in main chunk
	[C]: ?
```
This will make troubleshooting lua scripts a lot easier. And evaluating vim script already has a simple stack trace.

### PR DESCRIPTION
**Pull request by gpanders**
Closes #16226.

### CODE REVIEW

**Comment by ii14** [comment]
For the sake of completeness, can this also be added to `nlua_typval_exec`? It's used mainly by `ex_lua` and a couple of other things. There is also `ex_luado`.

**Comment by dmitmel** [comment]
What about pcall usages in the Lua code of runtime?

**Comment by gpanders** [comment]
CI errors seem like regular ole flakiness for the given platforms

**Comment by dmitmel** [comment]
Do these two instances need replacing or not?

https://github.com/neovim/neovim/blob/aac15cf4ade5cb67000abe171ff8e2060b78907e/src/nvim/lua/xdiff.c#L105

https://github.com/neovim/neovim/blob/912a6e5a9c58fce74134f9f8c2801373928e8289/src/cjson/lua_cjson.c#L1516

**Pull request merged**
