### PR TITLE
vim-patch:8.2.1741: pathshorten() only supports using one character

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.2.1741: pathshorten() only supports using one character

Problem:    pathshorten() only supports using one character.
Solution:   Add an argument to control the length. (closes vim/vim#7006)
https://github.com/vim/vim/commit/6a33ef0deb5c75c003a9f3bd1c57f3ca5e77327e

Cherry-pick a line in test from patch 8.2.0634.
Use Nvim's config paths in docs.

`shorten_dir()` returning a pointer looks a bit confusing here, as it is actually the same pointer passed to it, and it doesn't really reduce much code, so change it back to `void`.

Assigning `rettv->vval.v_string = NULL` is not needed if a pointer is within 64 bits. While this is usually the case, I'm not sure if it can be taken for granted.

### CODE REVIEW

**Review by kylo252 — COMMENTED** [review]
There are other changes that we're missing because `filepath.c` doesn't exist. Shouldn't we fix that first?

**Comment by zeertzjq** [comment]
> There are other changes that we're missing because `filepath.c` doesn't exist. Shouldn't we fix that first?

But Vim doesn't have path.c either.

**Comment by kylo252** [comment]
> But Vim doesn't have path.c either.

I'm not really sure what the best solution here is, but take a look at how different `modify_fname()` is for example.

**Comment by zeertzjq** [comment]
I'm not sure either.

**Review by seandewar — APPROVED** [review]

**Pull request merged**
