### PR TITLE
vim-patch:9.0.0814: aws config files are not recognized

### PR DESCRIPTION
**Pull request by clason**
Problem:    Aws config files are not recognized.
Solution:   Use "confini" for aws config files. (Justin M. Keyes,
            closes vim/vim#11416)
https://github.com/vim/vim/commit/436e5d395fd629c8d33b5cf7b373aad007f16851

### CODE REVIEW

**Comment by zeertzjq** [comment]
Should be `vim-patch:436e5d395fd629c8d33b5cf7b373aad007f16851`

**Comment by clason** [comment]
Why?

**Comment by zeertzjq** [comment]
Should be `vim-patch:436e5d395fd6`

**Comment by zeertzjq** [comment]
Patch 9.0.0813 is N/A anyway, but the commit message need to mention `vim-patch:436e5d395fd6` to mark the correct patch as ported.

**Review by zeertzjq — APPROVED** [review]

**Comment by smjonas** [comment]
In the commit message, `neovim/neovim#11416` is used instead of `vim/vim#11416`. Otherwise LGTM.

**Review by zeertzjq — APPROVED** [review]

**Review by smjonas — APPROVED** [review]

**Pull request merged**
