### PR TITLE
fix(treesitter): redraw added/removed injections properly

### LINKED ISSUE #23286: [TS] Missing tree change event in Markdown
If I have a Markdown file with an embedded language (for example Lua) and I move a line out of the code block no tree change event will be reported for the embedded language. Here is an example Markdown document:

    ```lua
    print 'This is an injected language'
    print({{{{{{{{{{{}}}}}}}}}}})
    ```

Here are the corresponding minimal file type settings (`ftplugin/markdown.lua`) for use with nvim-treesitter:

```lua
local ts = vim.treesitter
ts.start()
local parser = ts.get_parser(nil, nil)

parser:for_each_child(function(p, lang)
	p:register_cbs {
		on_changedtree = function(changes, tree)
			print(lang, vim.inspect(changes))
		end,
	}
end, true)
```

As you can see, whenever a change in one of the trees happens a message with the language and the range of the change is printed. However, when I put my cursor on line `3` and press `dd` the only message I get is `markdown {}`. If I then press `p` to put the line down below the fence I do get the proper message `markdown { { 3, 0, 4, 0 } }`

The same thing happens if I use `:move` to move the line instead of deleting it. I place the cursor again on line `3` and execute `:move 4` to move the line down. The only message I get is `markdown { { 3, 0, 4, 0 } }`.

Putting the line back into the fenced code block does produce the proper messages:

- `:move 2` produces `markdown { { 2, 5, 2, 29 } }` and `lua { { 2, 0, 2, 29 } }`
- pressing `P` on line `3` (after `dd` to delete the second Lua line) produces the same output
- pressing `p` on line `2` (after `dd` to delete the second Lua line) produces the same output

The lack of an event is an issue in my plugin HiPhish/nvim-ts-rainbow2 because `:move` preserves the extmarks which should be cleared when the `on_changedtree` event is fired. However, since no Lua event is fired the Lua the extmarks are preserved. See here: https://github.com/HiPhish/nvim-ts-rainbow2/pull/32#issuecomment-1518943328

### PR DESCRIPTION
**Pull request by lewis6991**
When injections are added or removed make sure to:
    - invoke 'changedtree' callbacks for when new trees are added.
    - invoke 'changedtree' callbacks for when trees are invalidated
    - redraw regions when languagetree children are removed

### CODE REVIEW

**Comment by clason** [comment]
@lewis6991 is this ready? can you say something about the performance impact?

**Comment by lewis6991** [comment]
It is ready.

This will make perf a bit worse for large files, but only because it exacerbates current inefficiencies which we will address in the future.

Probably the most important thing here is the test which will prevent us from regressing when we optimise further.

**Comment by clason** [comment]
> This will make perf a bit worse for large files, but only because it exacerbates current inefficiencies which we will address in the future.

Can this be quantified? Just a rough idea for the record.

**Comment by lewis6991** [comment]
So basically:
- `changedtree` callbacks are now called each time a tree is created and removed, not just changed.
- Callbacks are now called recursively on children (injections)

This means `changedtree` will be called a lot more often. The TS highlighter just calls `nvim__buf_redraw_range()` in these callbacks which is quite cheap. However, in the extreme case where there are 200k injections, this change will cause 200k callbacks to be called.

This is made worse further by the fact that whenever an injection is added or removed, we currently refresh **ALL** injections, meaning we call these callbacks 2x #no of injections; once for when they are removed and once for when they are added again.

So it's hard to say what the actual impact of this will be, but for very large files it might be noticeable.

However I think this will be needed before #22420, as I'm currently seeing redraw issues as the callbacks aren't being called.

**Comment by clason** [comment]
Let's give this a bit of a workout on master for a while before backporting it, then, so we can see the impact.

(In general, correctness before performance, of course.)

**Pull request merged**
