### PR TITLE
nvim_buf_call to call function in the context of another buffer

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by bfredl** [comment]
Merged. More test cases will be added according to what ppl actually end up using this for (probably `termopen()` first for my own part).

**Comment by tjdevries** [comment]
does this trigger autocmds or no when entering and leaving the buffer? (I didn't check what the code does. you can tell me to read source if you want)

**Comment by bfredl** [comment]
It should not. This is a workaround for functions that do not take curbuf as an arg even if they should, like `termopen()` et cetera, not a means to modally enter a buffer (I has another WIP for that).

**Comment by tjdevries** [comment]
Excellent. That's exactly what I was hoping you'd say :)

I will be using this in telescope then, I can remove a big HACKS section :)

**Pull request merged**
