### PR TITLE
remove trailing tabs

### PR DESCRIPTION
**Pull request by paddor**

### CODE REVIEW

**Comment by bfredl** [comment]
can you check the parts of the docs shared with vim/vim if the extra spaces are there also?

**Comment by paddor** [comment]
Why does that matter?

**Comment by bfredl** [comment]
to avoid rebase conflicts when merging runtime patches :]

**Comment by paddor** [comment]
```
vim  $ ag '\t$' **.txt
runtime/doc/tips.txt
542:

runtime/doc/usr_12.txt
301:    /

runtime/doc/vim9.txt
739:
```

Vim only has a trailing tab in two documentation files. The one in `runtime/doc/usr_12.txt` is by design.

**Comment by bfredl** [comment]
cool, nothing to upstream then. Merged, thanks!

**Comment by paddor** [comment]
Thanks

**Pull request merged**
