### PR TITLE
fix(lsp): show diagnostics when removing trailing new line

### LINKED ISSUE #25014: LSP: diagnostics are hidden after formatting with no change
### Problem

If a call to `vim.lsp.buf.format()` results in no change in the buffer contents, diagnostics that were previously visible for the buffer are hidden.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local pattern = "lua"
local cmd = { "/path/to/bin/lua-language-server" }
-- Add files/folders here that indicate the root of a project
local root_markers = { ".git", ".editorconfig" }
-- Change to table with settings if required
local settings = {
  runtime = { version = "LuaJIT", path = vim.split(package.path, ";") },
  workspace = { library = { vim.env.VIMRUNTIME }, checkThirdParty = false },
}

vim.api.nvim_create_autocmd("FileType", { pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
    vim.lsp.start({ name = "bugged-ls", cmd = cmd, root_dir = root_dir, settings = settings })
  end,
})
```

1. Load Neovim with this init.lua, then open a Lua file with the contents `local x =  y`.
2. Observe that diagnostics appear.
3. Run `:lua vim.lsp.buf.format()`
4. Observe that the file is formatted (extra space is removed) and diagnostics reappear.
5. Run `:lua vim.lsp.buf.format()`
6. Observe that the file is unchanged and the diagnostics disappear.

### Expected behavior

The diagnostics do not disappear when the file is unchanged by reformatting.

### Neovim version (nvim -v)

0.9.1

### Language server name/version

LuaLS 3.7.0 (but this is a Neovim bug)

### Operating system/version

Linux

### Log file

_No response_

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #25014

### CODE REVIEW

**Comment by glepnir** [comment]
Seems a little unreasonable and intrusive. Maybe #22598 can handle this or a autocmd hook

**Comment by MariaSolOs** [comment]
@glepnir I'm indeed unsure about this fix, but could you please elaborate on what you find wrong about it?

**Comment by glepnir** [comment]
This function is used in many lsp method handlers. The single function only handles textEdits and not some extra stuff. It might be reasonable to provide a callback or do something on https://github.com/neovim/neovim/pull/22598

**Comment by MariaSolOs** [comment]
@glepnir alright, I'll close this then.

**Pull request closed without merging**
