### PR TITLE
fix(man.lua): return support of all sections

### LINKED ISSUE #23485: Bugs in man script
### Problem

Hi there!

I've found that man.lua author assumed that man pages sections:
1) can be only number: https://github.com/neovim/neovim/blob/master/runtime/lua/man.lua#L742
2) can be only single character: https://github.com/neovim/neovim/blob/master/runtime/lua/man.lua#L586

Both assumptions are wrong: there are so many variations:

```ShellSession
$  ls /usr/share/man/man* -1d
/usr/share/man/man0p/
/usr/share/man/man1/
/usr/share/man/man1p/
/usr/share/man/man2/
/usr/share/man/man2type/
/usr/share/man/man3/
/usr/share/man/man3const/
/usr/share/man/man3head/
/usr/share/man/man3p/
/usr/share/man/man3type/
/usr/share/man/man4/
/usr/share/man/man5/
/usr/share/man/man6/
/usr/share/man/man7/
/usr/share/man/man8/
/usr/share/man/mann/
```

There is not only "most common" `<num>p` sections (which already fails at both this places), but there is also "n" section (still single char, but not a number), and `<num><word>` sections

And if "n" section is "abused" by only tcl/tk-related manpages,
the "worded" ones is part of "default" `man-pages` package.
and "<num>p" ones is even part of "more standard" `man-pages-posix` package.

So, both assumptions are wrong.

Although, on my system it is enough to fix only `1)` to make man in neovim work as expected, I think `2)` should be fixed a well.

Althouth(2), if fix for `1)` is pretty simple (just remove `tonumber()` around `args[1]`) and I can send PR with it in any moment, I'm not sure if changing `man?/` to `man[^/]+/` would be acceptable fix for `2)` :man_shrugging: 

If yes, I can make PR with both fixes ASAP (maybe, after pause about 4-6 hours after posting this ticket)

### Steps to reproduce

`nvim --clean`
`:Man 1p man`
or
`:Man 3type uint8_t`

### Expected behavior

It should open manpage, but not show error that there is no such man page

### Neovim version (nvim -v)

HEAD

### Vim (not Nvim) behaves the same?

no, 9.0.1403

### Operating system/version

any

### Terminal name/version

any

### $TERM environment variable

any

### Installation

any

### PR DESCRIPTION
**Pull request by msva**
Current behaviour of `:Man` is to only work with "number" sections. This is caused by wrong assumptions about existing man sections.

Also, there was similar assumption about dirs in paths. Although, it looks like it doesn't trigger on my system, it is still not right, so fixed too.

fixes #23485

### CODE REVIEW

**Comment by msva** [comment]
By the way, looks like "old" behaviour in `paths` was broken at all:
`man?/` would match only `ma/`+`man/`, and not even `man[0-9]`.

**Comment by zeertzjq** [comment]
`man?` doesn't match `ma`. It matches `man` followed by any character:
```
						*wildcard* *wildcards*
Wildcards in {file} are expanded, but as with file completion, 'wildignore'
and 'suffixes' apply.  Which wildcards are supported depends on the system.
These are the common ones:
	`?`	matches one character
	`*`	matches anything, including nothing
	`**`	matches anything, including nothing, recurses into directories
	[abc]	match 'a', 'b' or 'c'
```

**Comment by msva** [comment]
Well, yes.
I somewhy switched interpretation context to lua patterns, instead of vimscripts globbing.

Then pattern should be fixed to escape the slash.

I'll fix it in few moments.

**Comment by msva** [comment]
(I also merged commits from master)

**Comment by zeertzjq** [comment]
There may be a problem with this PR: it is no possible to view a man page with spaces without specifying a section number.

Related comment: https://github.com/neovim/neovim/pull/22503#issuecomment-1454260924

**Comment by msva** [comment]
Actually, it works[1] for me even in current state, so it don't brake the thing that was fixed by that PR.

Although, as I tested, looks like it works, because other logic in the `man.lua` make it somehow understand even constructions like `CREATE(TABLE)`.


I found a condition that brakes that logic: `Man acl set fd` (there is two `_`'s in original string)

So, I fixed this if-branch to test for proper condition.

I'll make some tests and push it.

**Comment by msva** [comment]
done

**Comment by msva** [comment]
Also, made `stylua` happy.

**Pull request merged**
