### PR TITLE
feat(lsp): vim.lsp.config

### LINKED ISSUE #14616: `ts` not recognized for syntax highlights in the fancy_floating_markdown popup
- `nvim --version`: v0.5.0-dev+1345-g6dd04ed5f
- Operating system/version: Centos 8 Linux
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color

When using the LSP hover typescript code blocks are not syntax highlighted when ` ```ts` is used, but only when  ` ```typescript` is. This means that any language server using ` ```ts` fails to render any syntax highlighting. `ts` is the most commonly used.

In my `init.vim` I have:
```
let g:markdown_fenced_languages = [ 'typescript', 'ts=typescript' ]
```
Which works fine for Markdown files using ` ```ts`:

Screenshot from 2021-05-22 14-52-19

But in the LSP hover for Deno that uses ` ```ts` code blocks I get no highlighting:
Screenshot from 2021-05-22 08-44-30

### PR DESCRIPTION
**Pull request by folke**
This PR adds `vim.lsp.config` that can configure various aspects of the built-in LSP client through `vim.lsp.setup({...})`

## Usage

The following example, configures borders for all `floating_preview`s and uses custom symbols for diagnostics signs, and completion item kinds.

```lua
vim.lsp.setup({
  floating_preview = { border = "single" },
  diagnostics = {
    signs = { error = " ", warning = " ", hint = " ", information = " " },
    display = {
      underline = true,
      update_in_insert = false,
      virtual_text = { spacing = 4, prefix = "●" },
      severity_sort = true,
    },
  },
  protocol = {
    completion_items = {
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = " ",
      Enum = "了 ",
      EnumMember = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = "ﰮ ",
      Keyword = " ",
      Method = "ƒ ",
      Module = " ",
      Property = " ",
      Snippet = "﬌ ",
      Struct = " ",
      Text = " ",
      Unit = " ",
      Value = " ",
      Variable = " ",
    },
  },
})

```

## Other

* fix for `vim.tbl_deep_extend`: would fail with `vim.tbl_deep_extend("force", {a=true}, {a={b= 1}})` 
* Supersedes #14617
* Fixes #14616

### CODE REVIEW

**Comment by David-Else** [comment]
Did you mean that this pull request fixes itself?

> fixes #14681

**Comment by folke** [comment]
> Did you mean that this pull request fixes itself?
> 
> > fixes #14681

Right, should be #14617 😅

**Comment by dsully** [comment]
Wouldn't users (like myself) still want to configure custom completion items this way? Or is there a better approach?

**Comment by dsully** [comment]
Nothing, and that is what I do right now. Just making sure I understood your comment.

**Pull request closed without merging**
