### PR TITLE
Kbtree sanity

### PR DESCRIPTION
**Pull request by bfredl**
Some changes to kbtree to make it possible to step through in a debugger, and make it slightly easier to read.

Probably doesn't make sense to merge right now, but after the initial extmark #5031 is done I might experiment with some changes to make it more effective to our use case:

- Use relative positioning of child nodes to speed up adjustment.
- safe references to nodes (to enable efficient lookup, without the current double-tree indirection of extmark).
- Detailed support for ranges like atom:s marker-index https://github.com/atom/superstring/blob/master/src/core/marker-index.h. (i e efficient multiline bufhl support)

### CODE REVIEW

**Comment by justinmk** [comment]
somewhat related, https://github.com/attractivechaos/klib/issues/117 suggests a potential improvement to kvec.

**Comment by bfredl** [comment]
> somewhat related, attractivechaos/klib#117 suggests a potential improvement to kvec.

But it seems nvim has already done those in our private copy.

**Comment by bfredl** [comment]
Added some comments to the algorithms, especially for how `kb_delp_aux` works, if I understood things correctly.

**Comment by bfredl** [comment]
Resolved. `src/nvim/marktree.[ch]`

**Pull request closed without merging**
