### PR TITLE
[WIP] Trusty on Xenial

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by janlazo** [comment]
What's this for?

**Comment by blueyed** [comment]
To catch issues like https://github.com/neovim/neovim/pull/10363#issuecomment-508916959 on CI (older CMake).

Currently it fails:
```
FAILED: /usr/lib/ccache/gcc -m32 -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Iconfig -I../src -isystem /home/travis/nvim-deps/usr/include -Isrc/nvim/auto -Iinclude -I/home/travis/nvim-deps/usr/include/luajit-2.0 -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector --param ssp-buffer-size=4 -Wno-array-bounds -Werror -funsigned-char -MD -MT src/nvim/CMakeFiles/nvim.dir/os/time.c.o -MF src/nvim/CMakeFiles/nvim.dir/os/time.c.o.d -o src/nvim/CMakeFiles/nvim.dir/os/time.c.o   -c ../src/nvim/os/time.c
../src/nvim/os/time.c: In function ‘os_utime’:
../src/nvim/os/time.c:51:38: error: conversion to ‘uint64_t’ from ‘int32_t’ may change the sign of the result [-Werror=sign-conversion]
   STRICT_ADD(rv, tm.tv_usec, &rv, uint64_t);
                                      ^
cc1: all warnings being treated as errors
[227/262] Building C object src/nvim/CMakeFiles/nvim.dir/os_unix.c.o
```

Not sure how to proceed - looks like a bug with an older gcc?

We could also install the minimal CMake version somehow maybe, or just wait for reports about it?

**Comment by justinmk** [comment]
> We could also install the minimal CMake version somehow maybe

+1 that would be best. Could just get a binary and use absolute path.

**Comment by blueyed** [comment]
Ok, could use `https://cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.sh` (`--prefix /usr/local --skip-license`) (via https://cmake.org/files/v2.8/).
Should be done after the cache update (https://github.com/neovim/neovim/pull/10412).

**Comment by blueyed** [comment]
Closing in favor of https://github.com/neovim/neovim/pull/10445.

**Pull request closed without merging**
