### PR TITLE
[WIP] New decorations API (extend nvim_buf_set_extmark)

### PR DESCRIPTION
**Pull request by bfredl**
Extend `nvim_buf_set_extmark` to also set decorations. Decorations are visual properties added upon an extmark. Currently the supported decorations are:

- virtual text added at the EOL of the extmark.
- highlight the byte extent of the extmark.

This corresponds to the existing functionality of `nvim_buf_add_highlight` and `nvim_buf_set_virtual_text`. These two functions will thus be deprecated. More functionality is planned soon, like more highlight styles (highlight the region after EOL, numhl without sign API) and virtual text formats (inline virtual text? text in sign column or number column? i e direct API support for signs ).

NB: the current proposal _breaks_ the `nvim_buf_set_extmark` API. Most usage of extmarks will not need to set the id in advance, and this should thus not be promoted to a mandatory arg. This function is only on master and never stabilized. By github code search 4 plugins have used this API so far, and will be very simple to fix. (the breakage is a lot less than with `nvim_open_win`/`set_config` we also changed on master).

I will also extend `nvim_buf_get_extmarks` to return information in the same dict format (thus `nvim_buf_get_virtual_text` can be removed, as it is not in a stable release). But I will wait a bit and see if there is any opinions on the proposed format.

### CODE REVIEW

**Comment by yatli** [comment]
Could this be used to allow UI elements?
Like a button, a color palette, an image, or a clickable virtual text that opens a popup.

**Comment by hkupty** [comment]
Really looking forward to this, for [acid](https://github.com/clojure-vim/acid.nvim).
Current support for virtualtext is a bit quirky to me, so any improvement on that area will greatly impact user experience.

**Comment by adelarsq** [comment]
I'm looking forward for inline decorations, so would be possible better previews (for Markdown, colors, etc) and better support for [code lens](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup).

**Comment by bfredl** [comment]
replaced by #12816

**Pull request closed without merging**
