### PR TITLE
[Backport release-0.8] fix(treesitter): properly restore 'syntax'

### PR DESCRIPTION
**Pull request by clason**
Backport of #21358

### CODE REVIEW

**Comment by clason** [comment]
Closing for now (can't mark as draft for some reason) since problems with this fix were reported. Will add fixup commits and reopen if possible.

**Comment by clason** [comment]
@zeertzjq I was just about to backport the fixup commit :(

**Comment by zeertzjq** [comment]
Hmm, I thought the branch can always be restored.

**Comment by clason** [comment]
Only for a little while.

**Pull request closed without merging**
