### PR TITLE
msgpack-gen: Fix for Lua 5.1.

### PR DESCRIPTION
**Pull request by fwalch**
goto statement was only introduced in Lua 5.2.

cc @bfredl

### CODE REVIEW

**Comment by bfredl** [comment]
Hmm, why don't we run `functionaltest-lua` on the supported lua version?

**Comment by fwalch** [comment]
From what I can see, `functionaltest-lua` *are* run with Lua 5.1. The build process will still prefer LuaJIT (which supports goto) to invoke the gen-msgpack script, though.

**Comment by bfredl** [comment]
Would #4858 fix that?

**Comment by fwalch** [comment]
No, in #4858 `luajit` is still the first entry in the list.. I could change that to use Lua 5.1, as it's the "least capable", to maybe catch such errors.

#4858 is because LuaJIT is now not required anymore for building, but `lua` might be anything (e.g. 5.3 on Arch Linux), so we also need to consider alternative executable names.

This PR here is mainly to fix the Ubuntu PPA build, where Lua 5.1 is used during the build.

**Pull request merged**
