### PR TITLE
feat(filetype): detect vdm dialects

### PR DESCRIPTION
**Pull request by donbex**
This small PR adds support for the [VDM](https://en.wikipedia.org/wiki/Vienna_Development_Method) languages: VDM-SL, VDM++ and VDM-RT.

### CODE REVIEW

**Comment by smjonas** [comment]
Sorry for being nitpicky, but can you sort the additions to the `filetype.lua` table alphabetically by the table value (and also insert them at the correct position)? 

Also, filetype updates need to go through Vim first. Please create a PR on the Vim repo, the patch will then be ported to Neovim.

**Comment by clason** [comment]
Thank you, but all filetype detection changes have to go through Vim since we want to be compatible (and use the same test suite).

Please open a PR upstream, and we will port the changes once they are merged.

**Comment by donbex** [comment]
Will do. I did look for documentation about adding new filetype detection and didn't find a mention of this, sorry.

**Comment by donbex** [comment]
For reference, this is the Vim PR: https://github.com/vim/vim/pull/11004

**Pull request closed without merging**
