### PR TITLE
ci: bump ubuntu and macos to latest stable versions

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
I think we decided _not_ to do that when I bumped the runners recently.

**Comment by dundargoc** [comment]
I thought that was only for the release job?

**Comment by clason** [comment]
Mostly, yes, but I thought there was also an argument about testing for a broader range (e.g., the `functionaltest-lua` one)?

@jamessan

**Comment by jamessan** [comment]
My reasoning was to not have two changes being tested in CI at the same time -- PR's changes and potential change in image. The change in image should be intentional and vetted on its own.  There's usually a fair amount of overlap between an image being available and it being promoted to "latest", so we have time to do that work.

The release workflows are different, since there we're trying to produce images that work in the broadest number of environments, and therefore want to stay on older releases. If they had an `ubuntu-oldest` alias, that would be best. :⁠-⁠)

**Comment by dundargoc** [comment]
> The change in image should be intentional and vetted on its own. There's usually a fair amount of overlap between an image being available and it being promoted to "latest", so we have time to do that work.

I think that is naive. The last windows runner update which we had to fix in a panic at the last minute shows this isn't how it plays out in reality. Either the CI fails because the runners are updated or the CI fails because the runners are deprecated (or if we're lucky, someone happened to warn us right before it got hit with brownouts).

**Comment by jamessan** [comment]
> The last windows runner update which we had to fix in a panic at the last minute shows this isn't how it plays out in reality.

We knew that was coming for a long time, and there had been multiple attempts at moving to the new image. However, no one followed through on the changes until we were forced to.

I put most of the blame on me for that, because I kept saying I was trying to update the image but didn't have the time or motivation to actually triage and fix the issues.

Next time, I won't give the false impression that the work is already being handled.

I still think the approach I describe is the better way to handle it. Using a latest image doesn't prevent the "fix things in a panic" situation. It just forces it to happen sooner.

The only way to avoid that, with either image choice, is to pay attention to what GH is doing and vet that we work on a new image before it's automatically changed.

That's my $0.02. I won't argue with whatever decision is made, since I won't be doing the work to fix it.

**Comment by dundargoc** [comment]
> I put most of the blame on me for that,

Nonsense, no one else but you was even willing to touch that thing :)

Regardless, I see your point about this not solving any root issues but rather just shifts the timeline of events. And allowing us to choose when to upgrade on our own terms is still nice...

OK, you have convinced me :). But should we at least have the policy that we bump to the latest available version explicitly? This way we'll have the most amount of time to fix the issues at least.

I've also asked the runner-images team for the possibility of adding "oldest" labels for our release jobs and awaiting their response.

**Comment by dundargoc** [comment]
Conclusions from this issue:

- On `ci` workflow we run latest stable, non-beta, version, but we set it explicitly i.e. not with the `-latest` labels *unless otherwise specified*. It's fine to test older versions if it's purposeful, but write a comment next to the `runs-on` or somewhere else appropriate so we know why it should be the older version.

- On `release` workflow we run the oldest, non-deprecated, versions. This is to maximize the number of environments the releases can work in. It would be optimal if Github actions had `-oldest` labels to avoid having to manually bump these, but until then we just explicitly set the runners. There shouldn't really be a reason to not run the oldest, non-deprecated runner for these barring extraordinary situations.

Of course this isn't a hard rule, I just want *some* sort guideline (and hopefully avoid repeating the same discussion in 6 months :) or so).

**Comment by justinmk** [comment]
> Conclusions from this issue:


feel free to stub that out in MAINTAIN.md, we can massage it later

**Pull request merged**
