### PR TITLE
refactor(api): add nvim_option_get, deprecate nvim_get_option_value / nvim_get_option_info2

### PR DESCRIPTION
**Pull request by justinmk**
## Problem

There is no reason for `nvim_get_option_value` and `nvim_get_option_info2` to be separate APIs.

## Solution

Introduce `nvim_option_get`.
Deprecate `nvim_get_option_value` and `nvim_get_option_info2`.

todo

- [ ] benchmark
- [ ] tests
- [ ] replace old references
- [ ] docs + news
- [ ] cleanup implementation

### CODE REVIEW

**Comment by lewis6991** [comment]
I'm not really a fan of APIs with polymorphic return types as it makes it difficult/impossible to add accurate type annotations. Can we reconsider this?

**Comment by justinmk** [comment]
> Getting an option value will now incur the cost of a dictionary and a table allocation, along with fetching all the option info which is seldom used compared to the value.

I will provide benchmarks to see if this matters. I suspect resolving an option value is the main cost, not the option properties.

> I'm not really a fan of APIs with polymorphic return types as it makes it difficult/impossible to add accurate type annotations.

 `nvim_get_option_value`  returns `Object`, how does this PR regress anything?

**Comment by lewis6991** [comment]
> Getting an option value will now incur the cost of a dictionary and a table allocation, along with fetching all the option info which is seldom used compared to the value.

Just to note, one way to avoid the dictionary allocation is to add a `lstate` argument to the function, and if present, build the table directly onto the Lua stack and avoid the arena middle-man.

We did this for `nvim_buf_get_lines` and it resulted in a 30% gain in performance. Not magnitudes, but still worth doing.

---

> nvim_get_option_value returns Object, how does this PR regress anything?

Sorry, I wasn't sure on the exact direction of this, but can see the value is a `value` field in a returned object.

---

One thing that was nice about `nvim_get_option_value` was it that it had symmetry with `nvim_set_option_value`. With this PR we will end up with: `nvim_get_option` and `nvim_set_option_value` which feels a little off. Maybe we could rename `nvim_set_option_value` to just `nvim_set_option`?

With all that said, my preference would be to just leave things as they are, but I appreciate the arguments for doing this and hopefully the perf loss is negligible.

**Comment by clason** [comment]
> With all that said, my preference would be to just leave things as they are, but I appreciate the arguments for doing this and hopefully the perf loss is negligible.

I second this; it feels premature to take a wrench to API names when the API itself is still under heavy (re)construction. There's no guarantee that we won't have to introduce an `nvim_get_option2` later if we do this now. Much better to look at the final state and make a holistic decision.

**Comment by justinmk** [comment]
> Maybe we could rename `nvim_set_option_value` to just `nvim_set_option`?

or `nvim_option_set`, yes.

> it feels premature to take a wrench to API names when the API itself is still under heavy (re)construction.

My motivation is to get this done before 0.10 release. If the function takes `opts` and returns `Dict`, it's future-proof. So this is just about naming (and avoiding _proliferation_ of clumsy names like `foo_info` and `foo_value`, though I am also working on automation to enforce naming conventions).

**Comment by bfredl** [comment]
> Just to note, one way to avoid the dictionary allocation is to add a lstate argument to the function, and if present, build the table directly onto the Lua stack and avoid the arena middle-man.

> We did this for nvim_buf_get_lines and it resulted in a 30% gain in performance. Not magnitudes, but still worth doing.

This was over the old status quo of using _nested allocations_ and xfree panic, not compared to the arena pattern. Especially with Dictionaries the overhead of the Arena is much lower, as static key names are not copied to the arena. Though as a newer complement using typed `dict(foo)` retvals work now for direct lua table construction without needing `lstate` special casing (which still will be worth it in some micro-optimization cases, but for anything regarding options I suspect arena/keydict will be good enough).

**Comment by justinmk** [comment]
Based on the reactions it looks like there is no support for doing this, at least currently. But then I'm wondering what are we waiting for? What potential changes to the "final holistic state" could there be that would make this premature?

**Comment by clason** [comment]
> I thought we are already on a clear path to our options handling, and I don't see any potential for a more ideal function signature (i.e. extra parameters or changed return-value structure).

Clear goal, but the road is twisty. Don't expect the expected; expect the unexpected. I am worried that we'll hit a roadblock somewhere that will force us to change tack, or that the needed changes will have unforeseen performance impacts that will invalidate your current analysis.

**Pull request closed without merging**
