### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by justinmk** [comment]
Now that Vim has a "popup" family of functions, all "balloonexpr" stuff is N/A. "balloon" was always awkward, and no one will use it now that "popup" is available.

```
vim-patch:8.0.0396: 'balloonexpr' only works synchronously
```

**Comment by janlazo** [comment]
vim-patch:8.1.1973: cannot build without the quickfix feature
vim-patch:8.1.1975: MS-Windows GUI responds slowly to timer
vim-patch:8.1.1976: Travis log always shows test output

**Comment by bstaletic** [comment]
This PR breaks a check like `if v:version == 800 && has('patch1436')` (or the simpler `if has('patch-8.0.1436')` because `v:version` is still 800, yet the "patch 1436" included in https://github.com/neovim/neovim/pull/10099 is actually 8.**1**.1436.

More specifically, it breaks YouCompleteMe, which performs [a check](https://github.com/ycm-core/YouCompleteMe/blob/master/plugin/youcompleteme.vim#L57-L64) which now reaches the `!has( 'python_compiled' ) && !has( 'python3_compiled' )` part of the condition and so YCM exits.

**Comment by justinmk** [comment]
8.0.1436 was marked NA in bd1158f3ab16d80d6327. I suppose we could add special cases in `eval_has_provider()` for the `python{,3}_{compiled,dynamic}` junk.

**Comment by bstaletic** [comment]
> 8.0.1436 was marked NA in bd1158f.

I didn't manage to find that one. Thanks.

> I suppose we could add special cases in eval_has_provider() for the python{,3}_{compiled,dynamic} junk.

Does that still mean that YCM will need ycm-core/YouCompleteMe#3484 to restore neovim support?

**Comment by justinmk** [comment]
> Does that still mean that YCM will need [ycm-core/YouCompleteMe#3484](https://github.com/ycm-core/YouCompleteMe/pull/3484) to restore neovim support?

No, we'll handle `python{,3}_{compiled,dynamic}` as if the `_xx` part is truncated, since it makes zero difference in Nvim. https://github.com/neovim/neovim/pull/10980

**Pull request merged**
