### PR TITLE
[WIP] Change to expand Windows style environment vars in options

### PR DESCRIPTION
**Pull request by erw7**
Separated from #10662.

Although not described in `:h :set_env`, vim expands Windows style environment variables such as `%FOO%` with specific string options. Until now nvim has excluded this feature. This PR enables settings such as `set shell=%ComSpec%`.

### CODE REVIEW

**Comment by justinmk** [comment]
Usually % is the current filename, so this adds ambiguity and seems unnecessary. But , will merge it if you can add test coverage.

**Comment by blueyed** [comment]
> with specific string options

Could mention that this is for `P_EXPAND`.

For reference: it seems to have been remove in d2c3592da, and was likely broken in 03d47965c then ("refactor: split some more functions from misc1.c").

I've not looked into details (compared the new file from this PR), but this code should be aligned (more) to what Vim is doing.

**Comment by blueyed** [comment]
> will merge it if you can add test coverage.

This could be achieved by either enabling and already existing test, or submitting one to Vim in case it is not tested there yet.

**Comment by justinmk** [comment]
Is this fixing a problem that you've encountered in e.g. a plugin or your config? Is it difficult to write a test?

**Comment by erw7** [comment]
https://github.com/neovim/neovim/pull/10667#issuecomment-517654906  is correct and it is not documented feature in vim, so I will close this.

**Pull request closed without merging**
