### PR TITLE
feat(vim._with): allow specifying scope-specific options

### LINKED ISSUE #29253: `vim._with()` does not properly restore global-local options
### Problem

When using `options` context in `vim._with()`, it can result into unwanted side effects.

### Steps to reproduce

1. Create the 'script.lua' file with the following content:
    ```lua
    vim.go.commentstring, vim.bo.commentstring = '- %s', '-- %s'

    _G.log = {}
    table.insert(_G.log, { 'Before', go = vim.go.commentstring, bo = vim.bo.commentstring })
    vim._with({ options = { commentstring = '## %s' } }, function()
      table.insert(_G.log, { 'Inside', go = vim.go.commentstring, bo = vim.bo.commentstring })
    end)
    table.insert(_G.log, { 'After', go = vim.go.commentstring, bo = vim.bo.commentstring })
    ```
2. `nvim --clean -- script.lua`
3. `:source`
4. `:=log`.

The output now (notice difference in `go` values):

```
:=log
{ { "Before",
    bo = "-- %s",
    go = "- %s"
  }, { "Inside",
    bo = "## %s",
    go = "## %s"
  }, { "After",
    bo = "-- %s",
    go = "-- %s"
  } }
```

### Expected behavior

Both global and local option values are the same after executing `vim._with()` as they were before it.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-200+g9afa1fd35

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.9.3-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

### PR DESCRIPTION
**Pull request by dundargoc**
Replace `options` context with `o`, `bo`, `wo` and `go` contexts. This
allows users to specify which scope the option should work on.

Also add `env` context for changing `vim.env`.

Closes https://github.com/neovim/neovim/issues/29253.

---

Alternative to https://github.com/neovim/neovim/pull/29268

Will add tests once we're fairly sure about the design/function signature.

### CODE REVIEW

**Comment by dundargoc** [comment]
> I like #29268 because it is DWIM. Could we use the DWIM approach for `o` (analogous to `vim.o`)?

Done.

**Comment by echasnovski** [comment]
> I like #29268 because it is DWIM. Could we use the DWIM approach for `o` (analogous to `vim.o`)?

It is not quite flexible enough for a general "context". Using `buf` and/or `win` in context does not necessarily imply that caller wants/needs temporary options be for that buffer / window.

For example there might be the following cases:
- Explicitly set in context global option, even though there is `buf` / `win`.
- Set one context option locally while the other - globally.

Using `bo`, `wo`, `go` contexts allows caller to be explicit and independent of whether `buf` / `win` is set in context. Plus opens a door for a more aligned `env` context (for environment variables).

**Comment by echasnovski** [comment]
I think the upside of this design is also an ability for quite concise and expressive basic implementation (takes care only for options):

```lua
_G.with = function(context, f)
  -- Save and set
  local cache = { bo = {}, env = {}, go = {}, o = {}, wo = {} }
  for scope, scope_cache in pairs(cache) do
    for name, context_value in pairs(context[scope] or {}) do
      scope_cache[name] = vim[scope][name]
      vim[scope][name] = context_value
    end
  end

  -- Execute
  local ok, res = pcall(f)

  -- Restore
  for scope, scope_cache in pairs(cache) do
    for name, cached_value in pairs(scope_cache) do
      vim[scope][name] = cached_value
    end
  end

  -- Return
  if not ok then error(res, 0) end
  return res
end
```

**Comment by justinmk** [comment]
> Using `buf` and/or `win` in context does not necessarily imply that caller wants/needs temporary options be for that buffer / window.

using `o` does imply that?

**Comment by dundargoc** [comment]
Superseded by https://github.com/neovim/neovim/pull/29280

**Pull request closed without merging**
