### PR TITLE
[RFC] doc: Remove todo.txt

### PR DESCRIPTION
**Pull request by ghost**
refs #2911, discussed briefly in #2608 and #2553

It's not documentation in the same sense as the majority of files in
`runtime/doc`, so is of little use to most users and should probably not
be installed alongside the "real" documentation.

It may be full of good ideas, but it's also full of things which are no
longer applicable to Nvim, such as references to platforms we no longer
support (e.g., MS-DOS), Vi compatibility, Autoconf, the Perl interface,
etc.

If someone is looking for things to fix or improve, the GitHub issue
tracker should prove useful, and, unlike todo.txt, the issues are
generally much more relevant to Nvim.  Besides all that, removing
todo.txt makes porting runtime patches a bit easier.

With that said it should be clear that I'm pretty biased in favor of doing this,
so what does everyone else think?

### CODE REVIEW

**Comment by ZyX-I** [comment]
I do not care. In any case that list served no good: it does not have the links and I never feeled like Bram has much respect for it.

**Comment by equalsraf** [comment]
:+1 in general todo.txt is not that useful.

The only other reference I found is in [syntax_conceal_spec.lua](https://github.com/neovim/neovim/blob/536c0ba27e79929eb30850d8e11f2ed026930ab3/test/functional/ui/syntax_conceal_spec.lua#L163), maybe [its this](https://github.com/neovim/neovim/blob/632408af4a3baa987cc13005675bba63675825cb/runtime/doc/todo.txt#L697)

**Comment by Pyrohh** [comment]
> The only other reference I found is in syntax_conceal_spec.lua, maybe its this

I saw that too, although I think the description in the test file is adequate.

**Comment by justinmk** [comment]
I agree there's no reason to ship this with user docu. It's probably fine to remove it.

**Comment by Pyrohh** [comment]
It doesn't sound like it will be missed, so that settles it.

**Pull request merged**
