### PR TITLE
[WIP/RFC] ci: Travis: remove Flaky stage

### PR DESCRIPTION
**Pull request by blueyed**
Having a separate stage for it prevents it to run with e.g. (expected)
lint failures, and would then result in missing coverage.

### CODE REVIEW

**Comment by justinmk** [comment]
It's very rare that we have expected lint failures. I'm not sure it's worth removing the stage, which is there to avoid running those builds if the first stage fails. That saves time/resources.

**Comment by blueyed** [comment]
I see, but it is rather bad not having coverage for PRs, and for base builds on master (for coverage diff comparison) due to this.

Can we then have coverage via an existing job already then?  It would slow that job down, but the overall outcome might be positive still, if another job can be removed instead.

**Comment by justinmk** [comment]
We have coverege already through travis. Coverage from appveyor only covers the few Windows-only codepaths. It's not really a high priority.

**Comment by blueyed** [comment]
> We have coverage already via travis.

But not when lint is failing - it is only done via one job, from the flaky stage.

**Comment by justinmk** [comment]
> But not when lint is failing - it is only done via one job, from the flaky stage.

It's not worth spending time to fix that case.

**Pull request closed without merging**
