### PR TITLE
[RFC] always wait for UI with --embed, unless --headless is supplied

### PR DESCRIPTION
**Pull request by bfredl**
Testing an alternative to #8754, see https://github.com/equalsraf/neovim-qt/pull/463#issuecomment-423238627 https://github.com/equalsraf/neovim-qt/pull/463#issuecomment-423242590 and below.

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by bfredl** [comment]
Added some docs. I also noted, if/when this initialization becomes standard, detection of either TUI or external UI can be done inside `VimEnter`.

**Comment by justinmk** [comment]
Should mention in following-head wiki page.

**Comment by bfredl** [comment]
I will mention it in following-HEAD when it is on HEAD, just as I did with #8754.

**Comment by bfredl** [comment]
I also adding the following to the wiki page:

For an UI that wants to do additional initialization after init.vim the following pattern can be used: Before `nvim_ui_attach` send a single `nvim_command` request with the command `"autocmd VimEnter * call rpcrequest(1, 'vimenter')"`. In the `vimenter` method handler the UI can then safely execute any requests, and nvim will only enter normal mode when this handler returns.

**Pull request merged**
