### PR TITLE
fix(treesitter): correct region for string parser

### LINKED ISSUE #18790: Treesitter: `tsparser:parse()` fails if lua string includes `!` in `vim.cmd`
### Neovim version (nvim -v)

0.8.0-dev+329-gf31a10204

### Vim (not Nvim) behaves the same?

N/A (treesitter)

### Operating system/version

Ubuntu 20.04

### Terminal name/version

wsltty

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

- nvim-treesitter version: `a10b603` (depends lua parser and query)
- minimal.lua
```lua
local path_to_nvim_treesitter = [[/home/notomo/.vim/packages/pack/optpack/opt/nvim-treesitter]]
vim.opt.runtimepath:prepend(path_to_nvim_treesitter)
vim.cmd([[runtime plugin/nvim-treesitter.lua]])
vim.cmd([[TSUpdateSync lua]]) -- assert latest

local str = [[vim.cmd("!echo")]]
local language = "lua"
local tsparser = vim.treesitter.get_string_parser(str, language)
tsparser:parse()
```
- command
```
build/bin/nvim --clean --headless +'luafile ./minimal.lua'
```

### Expected behavior

`tsparser:parse()` does not fail.

### Actual behavior

```
$ build/bin/nvim --clean --headless +'luafile ./minimal.lua'
Parsers are up-to-date!
Error detected while processing command line:
E5113: Error while calling lua chunk: ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:115: Ranges can only be made from 6 element long tables or nodes.
stack traceback:
        [C]: in function 'set_included_ranges'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:115: in function 'parse'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:149: in function 'parse'
        ./minimal.lua:9: in main chunk^C
```

from eab4d03a3

### PR DESCRIPTION
**Pull request by clason**
fixes injections for string parsers after https://github.com/neovim/neovim/commit/eab4d03a3264b2afaf803ed839fa25bc4e7acedd

fixes #18790 

@vigoux @theHamsta

### CODE REVIEW

**Comment by clason** [comment]
@theHamsta could you take a look at this?

**Comment by clason** [comment]
@lewis6991 maybe you can give this a lookover?

**Review by vigoux — APPROVED** [review]

**Comment by vigoux** [comment]
Looks pretty good to me, do you have a test case for that to add ?

**Comment by clason** [comment]
Not easily (I'm not very familiar with treesitter tests), but maybe I can convert the MRE from https://github.com/neovim/neovim/issues/18790.

**Comment by clason** [comment]
No, looks like you need a parser with injections to test this easily.

**Pull request merged**
