### PR TITLE
[WIP] nvim_put

### PR DESCRIPTION
**Pull request by bfredl**
maybe should be nvim_win_put if an ui drops data over a specific window. Or maybe it should just do atomic(set_current_window, nvim_put) in that case....

### CODE REVIEW

**Comment by bfredl** [comment]
works in insert mode, but redo doesn't work (neither in normal nor insert mode)

**Comment by bfredl** [comment]
redo could be implemented as such: put the contents in the drop register, and add `"~p` (resp. `<c-r><c-o>~` ) to the redo buffer. But it won't work if one puts several different texts during the same insert mode.

**Comment by bfredl** [comment]
Alternatively consider it a low-level primitive and let redo be implemented by the plugin using this. But `"~` would make sense for UI initiated put.
.

**Comment by justinmk** [comment]
> But it won't work if one puts several different texts during the same insert mode.

Could it be a linked list?

BTW where is insert-mode implied? What happens if nvim_put is called in some other mode?

**Comment by bfredl** [comment]
implied how? It just doesn't do anything special on insert mode (except CURSEND on the latest push). Make `"~` a linked list how? Or yet a set of numbered registers?

**Comment by bfredl** [comment]
> What happens if nvim_put is called in some other mode?

It does what we want it to do. In visual mode we can either do nothing special (except adjusting cursor/VIsual), most flexible for plugins, or simulate the delete implicit in `vp`, most convenient for UIs. I guess in cmdline mode it should also emulate `<c-r><c-r>`.

**Pull request closed without merging**
