### PR TITLE
Add lemonade support for clipboard feature

### PR DESCRIPTION
**Pull request by Shougo**
I have added lemonade support for neovim clipboard feature.
It is useful for remote server neovim.

https://github.com/pocke/lemonade

### CODE REVIEW

**Comment by justinmk** [comment]
This is cool. Technically it is unnecessary because nvim server and client could work over TCP, but that would require us to address https://github.com/neovim/neovim/issues/4443 if we wanted to enable this out-of-the-box. 

So this is a good middle ground in the meantime. It would be really nice if this could be installed as a vim plugin which downloads the binaries (and verifies the SHA sums).

@Shougo Can you change the commit message to:

    clipboard: support "lemonade" tool

**Comment by bfredl** [comment]
This is ok for now, but we need a good option for this when we switch to binary clipboard providers. Eventually we should have binary plugins for X11, windows and OSX so the vimscript provider will be removed in its present state. While putPre autocommand would be good to react to or modify a register being put (like the motion type) I'm not sure it is best to define a source, I mean it should replace the default provider shipped in the runtime so only one source will be active. Rather I would imagine options `clip_star_func` and `clip_plus_func` (or whatever mechanism we prefer to vim options) taking vimscript functions with interfaces similar to the existing vimscript provider (very ideally the interface for vimscript or binary implementation should be shared somehow) and also runtime helper functions abstracting the common case "shell commands to implement selection operations", so this plugin would be like

`call clip#set_plus_system_commands('lemonade copy', 'lemonade paste')`

**Comment by Shougo** [comment]
> @Shougo Can you change the commit message to:

Did.

**Comment by Shougo** [comment]
Thank you.

**Comment by assaf758** [comment]
it seems there is some issue here. I tried to define  in nvim:
nnoremap <leader>cfp :redir @+> \| echo expand("%:p") \| redir END<CR> 

the string (file path) is copied to the clipboard but usually it is truncated

**Comment by wsdjeg** [comment]
@assaf758 if you want to use clipboard for current file path or the file in github repo, see
https://github.com/wsdjeg/DotFiles/blob/master/config/nvim/autoload/zvim/util.vim#L58-L89

**Comment by jam1015** [comment]
currently getting error `clipboard: error invoking lemonade: read tcp [::1]:33346->[::1]:22: read: connection reset by peer
`

dont' know about networking, currently investigating, might post issue on the lemonade repo

**Comment by jam1015** [comment]
this is really old, but I'm getting a large assortment of networking errors trying to use lemonade; it is not nearly as 'out of the box' functional as tools like `xclip`.  The errors happen both when I'm trying to use neovim and just using lemonade from the terminal.

**Pull request merged**
