### PR TITLE
coverity/155968: resource leak

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Review by jamessan — APPROVED** [review]

**Comment by jamessan** [comment]
Why not simply ensure that `dir` is freed?

While using `NameBuff` avoids the extra memory churn, it's an odd side-effect to have it change `NameBuff`. Is is possible that there may be a reason to use `os_setenv_append_path` in a context that's already populated useful information in `NameBuff`, which would then be overwritten?

**Comment by jamessan** [comment]
This is what I was going to do, until I saw your PR. :)

```diff
--- a/src/nvim/os/env.c
+++ b/src/nvim/os/env.c
@@ -870,8 +870,7 @@ bool os_setenv_append_path(const char *fname)
     return false;
   }
   const char *tail = (char *)path_tail_with_sep((char_u *)fname);
-  const char *dir = (char *)vim_strnsave((char_u *)fname,
-                                         (size_t)(tail - fname));
+  char *dir = (char *)vim_strnsave((char_u *)fname, (size_t)(tail - fname));
   const char *path = os_getenv("PATH");
   const size_t pathlen = path ? strlen(path) : 0;
   const size_t newlen = pathlen + strlen(dir) + 2;
@@ -884,9 +883,11 @@ bool os_setenv_append_path(const char *fname)
       xstrlcat(temp, ENV_SEPSTR, newlen);
     }
     xstrlcat(temp, dir, newlen);
+    xfree(dir);
     os_setenv("PATH", temp, 1);
     xfree(temp);
     return true;
   }
+  xfree(dir);
   return false;
 }
```

**Comment by justinmk** [comment]
> Is is possible that there may be a reason to use os_setenv_append_path in a context that's already populated useful information in NameBuff, which would then be overwritten?

I don't know the rules about that. Are they written somewhere? My inference was that NameBuff/IOBuff should only be used where low-level `xstr*`, `mem*`, etc., operations are done in-between. 

Of course, one could argue that `os_` functions are low-level. And I would agree... But this function is really special-purpose, it's unlikely to be used anywhere else, _and_ it's small enough that inspection will reveal its use of NameBuff without trouble. (That's a cop-out, but that's life in C I guess.)

**Comment by justinmk** [comment]
Another option is to give env.c (or the `os/*` layer) its own buffer, like @ZyX-I did with os/fileio: https://github.com/neovim/neovim/blob/0c7751f6ab86e61e6ac447b1439f6f683f8c119f/src/nvim/os/fileio.c#L161-L162

**Comment by jamessan** [comment]
> Another option is to give env.c (or the os/* layer) its own buffer

That sounds like a good idea for another PR.

> But this function is really special-purpose, it's unlikely to be used anywhere else

That sounds like even more reason to not bother with optimizing it to use `NameBuff`, and just making the obvious `xfree` calls.

> it's small enough that inspection will reveal its use of NameBuff without trouble

I shouldn't need to read the source of library functions to know how to use them.  If it's going to use `NameBuff`, that should be documented IMO.  TIL `option_expand` returns a pointer to `NameBuff`.

**Comment by justinmk** [comment]
> That sounds like even more reason to not bother with optimizing it to use NameBuff, and just making the obvious xfree calls.

The intention wasn't an optimization but rather to avoid having to maintain multiple free() calls at various return sites.

> I shouldn't need to read the source of library functions to know how to use them.

I definitely agree. I did say it was a cop-out :)

**Comment by justinmk** [comment]
Introduced `os_buf` for use by `os/*` layer.

**Review by jamessan — APPROVED** [review]

**Pull request merged**
