### PR TITLE
fix(marktree): preserve ordering in `marktree_move`

### LINKED ISSUE #25157: bug: `:%s/` can crash Neovim with `lua-language-server` after #13243
### Problem

I'm not too familiar with how to get a stack trace and/or attach a debugger, but the repro should be reliable.

I'm using `RelWithDebInfo`.

### Steps to reproduce

1. Checkout https://github.com/llllvvuu/neovim/tree/25155-repro
2. `nvim --noplugin --clean -u minimal.lua runtime/lua/vim/shared.lua`, where `minimal.lua` is:
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = { 'lua' },
  callback = function()
    vim.lsp.start({
      name = 'lua_ls',
      cmd = {'lua-language-server'},
      root_dir = vim.fs.dirname(vim.fs.find({'.git', '.luacheckrc' }, { upward = true })[1]),
    })
  end,
})
```
3. Try to do: `/Node<CR>V3j:s/Node/Tree`. This should crash when you type the first letter of "Tree".

I'm not sure what the role of the LSP is, but I suspect this has to do with the edge case of updating multiple locations at once.

### Expected behavior

Whether or not the LSP is proper or malformed, Neovim should handle it gracefully.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1089+g1c4a93b59

### Vim (not Nvim) behaves the same?

NVIM v0.10.0-dev-1089+g1c4a93b59

### Operating system/version

13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by llllvvuu**
`marktree_move` is making the tree out of order at:

https://github.com/neovim/neovim/blob/be10d65bfafe056025ffffa2c1131712b9a493a5/src/nvim/marktree.c#L1188

Because `key` is at the new position, and `x->key[new_i]` is also at the new position, this comparison spuriously returns true, which causes `x->key[i]` to be updated in-place even when it needs to be moved.

This causes crashes down the line, since the ordering of `MTNode.key` is an invariant that must be preserved.

Co-Authored-By: bfredl <bjorn.linse@gmail.com>
Fixes: #25157

### CODE REVIEW

**Comment by bfredl** [comment]
https://github.com/bfredl/neovim/tree/splicetree here is a tests which fails on master (plus some more, the marktree_move one is the one which needs to be fixed). The original version of this patch seems to be enough to fix it, there should be no reason to avoid the fast path for `(key.pos.row == newpos.row && key.pos.col == newpos.col)`.  that's one of the invariants this preserves (just updating the decoration state of the same key at the same pos shouldn't cause any structural change to the tree).

**Comment by llllvvuu** [comment]
That was a brainfart from me, I meant to return, not go to the slow path. Check the branch now and let me know if the new version makes more sense.

My original idea of `key_cmp(x->key[itr->i], x->key[new_i])` was unfortunately incorrect because it doesn't handle somethiing like [1, 3, 3] and you want to move the last 3 to a 2

**Comment by llllvvuu** [comment]
Thanks for writing the tests, I'll add them to this branch as well and see if I can demonstrate what I mean in https://github.com/neovim/neovim/pull/25186#issuecomment-1722193482 (or prove myself wrong)

**Comment by llllvvuu** [comment]
OK, I added a unit test that also illustrates https://github.com/neovim/neovim/pull/25186#issuecomment-1722193482

(i'm sure there's always more coverage to be had, but we'd need the luxury of coverage-guided fuzzing, which is gold standard for this kind of tricky C code)

**Comment by clason** [comment]
> we'd need the luxury of coverage-guided fuzzing, which is gold standard for this kind of tricky C code

Sounds like something someone would accrue great merit for setting it up (hint, hint) ;)

**Comment by bfredl** [comment]
looks alright, just need some lint adjustments to (my) lua code
```diff
diff --git a/test/unit/marktree_spec.lua b/test/unit/marktree_spec.lua
index ce6acf3603..0d6ae44b32 100644
--- a/test/unit/marktree_spec.lua
+++ b/test/unit/marktree_spec.lua
@@ -382,7 +382,7 @@ describe('marktree', function()
     eq(2000, tree[0].n_keys)
     ok(tree[0].root.level >= 2)
 
-    for i = 1,10 do
+    for _ = 1,10 do
       lib.marktree_splice(tree, 0, 0, 0, 100, 0, 0)
       check_intersections(tree)
     end
@@ -403,7 +403,7 @@ describe('marktree', function()
     local iter = ffi.new("MarkTreeIter[1]")
     for i = 1,1000 do
       local which = i%2
-      local p = lib.marktree_lookup_ns(tree, ns, ids[i], which, iter)
+      lib.marktree_lookup_ns(tree, ns, ids[i], which, iter)
       lib.marktree_move(tree, iter, 1+which, 500+i)
       if i % 10 == 1 then
         check_intersections(tree)
@@ -521,7 +521,7 @@ describe('marktree', function()
     ok(tree[0].root.level >= 3)
     check_intersections(tree)
 
-    for i = 1,10 do
+    for _ = 1,10 do
       for j = 3, 8 do
         lib.marktree_splice(tree, j, 0, 0, 200, 0, 0)
         check_intersections(tree)
```

**Pull request merged**
