### PR TITLE
ci: test only a single macos version

### PR DESCRIPTION
**Pull request by dundargoc**
The differences in MacOS releases are smaller since they're now upgraded yearly, meaning the need to test each version is reduced.

### CODE REVIEW

**Comment by clason** [comment]
Note that deprecation ends August 30, but the corresponding runners already have reduced availability which impacts CI times. So there is something to be gained for not waiting until the last minute.

(Also, @carlocab)

**Comment by carlocab** [comment]
Yes, Catalina and Big Sur are different enough to warrant having two separate CI runs, while Big Sur and Monterey probably are not.

Having only a single `macos-11` run makes sense.

**Comment by clason** [comment]
How will Homebrew handle the deprecation, by the way? Will you just drop 10.15?

**Comment by carlocab** [comment]
`homebrew-core` runs on self-hosted machines, so we're not affected by the deprecation. GitHub macOS CI isn't really that suitable for us anyway: it's filled with a lot of pre-installed stuff, so you don't get a clean build environment, plus there's a 6-hour timeout on CI runs.

We'll wait until Ventura has been released to drop our Catalina builds.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Looks good to me; only question is whether to target `macos-12` here (and for release) instead, and I think "no".

**Review by justinmk — APPROVED** [review]

**Pull request merged**
