### PR TITLE
vim-patch:partial:d899e5112079

### PR DESCRIPTION
**Pull request by seandewar**
Noticed a new rt update and had a bit of time. Hopefully you don't mind me snatching this one @clason :smile:  
I'll address reviews in the morn :zzz:

Update runtime files
https://github.com/vim/vim/commit/d899e51120798d3fb5420abb1f19dddf3f014d05

- Skip vimhelp.vim stuff (syntax/help.vim, syntax.txt; v8.2.4891).
- Skip :let heredoc eval stuff (eval.txt; v8.2.4770).
- Skip uk.cp1251.po.
- Skip `*hl-CurSearch*` change (syntax.txt):
  - Vim's CurSearch works differently (Nvim's uses current cursor pos).
    Dunno know how applicable the redrawing comment is to Nvim...
  - Might be preferred to move it under `*hl-Search*` like Vim?

### CODE REVIEW

**Review by zeertzjq — DISMISSED** [review]
See comment below

**Comment by zeertzjq** [comment]
Wait a minute

**Comment by zeertzjq** [comment]
I still cannot understand what this describes:
> When possible the name is highlighted in the used colors.  If this makes it
unreadable use Visual selection.

Isn't the name always highlighted using `Normal` even in latest Vim?

**Comment by seandewar** [comment]
`vimhelp.vim` is used to insert text props to highlight the groups in syntax.txt.
Do note however that you need to specify the full path to the runtime dir in VIMRUNTIME for it to work (at least last time I checked it)

**Comment by zeertzjq** [comment]
Oh, I thought it was referring to `:highlight`.

**Review by zeertzjq — APPROVED** [review]

**Comment by seandewar** [comment]
Haha no worries -- I originally thought the same until I remembered about that random vimhelp.vim patch :laughing:

**Review by clason — APPROVED** [review]

**Pull request merged**
