### PR TITLE
Fix multiple typos

### PR DESCRIPTION
**Pull request by hansrajdas**
* Below spellings are corrected:
  * definitons -> definitions
  * revison -> revision
  * perfomance -> performance
  * presense -> presence
  * follwed -> followed

### CODE REVIEW

**Comment by vigoux** [comment]
If that's for hacktoberfest, I'll quote the doc over there directly :

```
Don't: open pull requests with minor text edits on other people's repositories

If you're looking for a faster way to open four PR's and win, there's a better way!
```

Maybe you could add more typos in this pr?

**Comment by hansrajdas** [comment]
Sure, I can add more typos to this PR. For now, I went through below directories and found these typos:
* `neovim/scripts`
* `neovim/src/nvim/api`

I am sure, there would be more. Will get back to you in couple of days!

On a side note, if this hacktober thing is causing lot of PRs, it would be a good idea to delete `hacktoberfest` tag from this repository: https://hacktoberfest.digitalocean.com/hacktoberfest-update. Many standard repositories(like this) never added this tag to there repository, pointing out some below:
* https://github.com/vim/vim
* https://github.com/python/cpython
* https://github.com/elastic/elasticsearch
* https://github.com/kubernetes/kubernetes

**Comment by vigoux** [comment]
Good, thanks for your contribution, do you think we can merge that ?

**Comment by hansrajdas** [comment]
> Good, thanks for your contribution, do you think we can merge that ?

Give me some more time please, still working and able to find spells. I will mark you when done.

**Comment by vigoux** [comment]
Feel free to ping when it's done, and thank you very much to take some time fixing all of these !

**Comment by hansrajdas** [comment]
@vigoux: We are over 10 fixes, I think we are good to go ahead with merging. Please take a look

**Review by vigoux — APPROVED** [review]
While this is good, the changes in `tree_sitter/*` should be upstreamed too.

**Comment by hansrajdas** [comment]
Sorry, if I misunderstood your last comment but I couldn't locate corresponding directory and files(`tree_sitter/*`) in upstream project: https://github.com/vim/vim

**Comment by bfredl** [comment]
The upstream in that case is github.com/tree-sitter/tree-sitter

**Comment by hansrajdas** [comment]
> The upstream in that case is https://github.com/tree-sitter/tree-sitter

Thank you @bfredl 
Patched, PR: https://github.com/tree-sitter/tree-sitter/pull/762

**Comment by vigoux** [comment]
Awesome! Just saw the pr, can you remove your changes to the `tree_sitter` directory? Just to avoid divergence.

**Pull request merged**
