### PR TITLE
ci: try running coverity on PRs

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by dundargoc** [comment]
Benefit: prevent coverity bot: https://github.com/neovim/neovim/pull/28799#issuecomment-2122531283

**Comment by justinmk** [comment]
Unless coverity changed something, there used to be a (very low) limit, that's why we didn't do this.

**Comment by dundargoc** [comment]
Bleh. This makes coverity a dealbreaker for me personally, because there will be preemptive assert spamming in fear of triggering new coverity warnings as well as coverity warning complaints 6 months after a PR has been merged. The false-positive rates are also pretty high. But I understand that we don't want to get rid of it right now without any equivalent replacement (assuming codeql and clang-tidy/clang-analyzer doesn't cover the majority of the warnings?).

**Comment by dundargoc** [comment]
Related discussion: https://github.com/neovim/neovim/issues/1621

**Pull request closed without merging**
