### PR TITLE
tui: disable BCE almost always

### LINKED ISSUE #7618: tui + termguicolors: Text-glitches since v0.2.1
Glitches appear on the screen (TUI) when I scroll, switch tab, and do anything that involves rerendering for many symbols of text-matrix. I reproduced it with `v0.2.1`, `v0.2.2` and also latest nightly `v0.2.3-dev` 9b6bf8f. With `v0.2.0` it isn't happening. Every version built from this repo by this commands:

```bash
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/foo/bar/baz"
make install
``` 

Termite v12, Neovim v0.2.2:
selection_005
selection_006
selection_007

Konsole v16.12.3, Neovim v0.2.2:
selection_008
selection_009

My config: https://github.com/unclechu/neovimrc/ 89cc8b9

- `nvim --version`: 
```
NVIM v0.2.2
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/build/config -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/src -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/.deps/usr/include -I/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/build/src/nvim/auto -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.2-from-git/build/include
Compiled by unclechu@fedorafarm25

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/unclechu/neovim-v0.2.2-from-git/share/nvim"

Run :checkhealth for more info
```
- Vim (version: `v0.2.0`) behaves differently?
```
NVIM v0.2.0
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/build/config -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/src -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/build/src/nvim/auto -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/build/include
Compiled by unclechu@fedorafarm25

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/unclechu/neovim-v0.2.0-from-git/share/nvim"
```
- Operating system/version: *Fedora release 25 (Twenty Five)*
- Terminal name/version:
  - Termite v12
  - Konsole v16.12.3
- `$TERM`: *xterm-256color*

### PR DESCRIPTION
**Pull request by justinmk**
Update: ef195e8 _always_ disables BCE except for "real xterm". 

Summary:

- Nvim 0.2.0 did not implement BCE. 
- Nvim 0.2.1 enabled BCE aggressively.
- Nvim 0.2.3+ (after this PR) disables BCE (like 0.2.0) in all cases except when the `$XTERM_VERSION` env var is defined.

ref #4210 #4421 #7035 #7337 #7381 #7425 #7618

### CODE REVIEW

**Comment by justinmk** [comment]
Updated to disable BCE _always_ except for "real xterm". We didn't bother with BCE in 0.2.0

**Comment by mqudsi** [comment]
Oh my, that comment on Kitty #160 is quite the interesting read. This looks like a good solution; I'm going to apply the patch and see how it works out on Windows.

My workaround in the meantime has been `autocmd colorscheme * :highlight Normal ctermbg=0` (must be set prior to `colo` in `init.vim`) which forces the background color of the scheme to the same background color as the terminal.

**Comment by justinmk** [comment]
@vxid re https://github.com/kovidgoyal/kitty/issues/160 : could you try latest Nvim master, (which includes https://github.com/neovim/neovim/pull/7640 ) and say what `:echo &term` reports?

**Comment by vxid** [comment]
@justinmk Thanks for the followup. I had disabled `relativenumber` for the past week given the bug but it seems to work fine now (no lines disappearing).

Nvim from master echoes `kitty-xterm` while the arch packages echoes `nvim`.

**Comment by blueyed** [comment]
@justinmk 
Thank you!

**Comment by mqudsi** [comment]
@justinmk these latest changes also fix the scrolling issues I've been having under conhost/W10 as well. I'll test further and comment on the relevant issue, though.

**Pull request merged**
