### PR TITLE
fix(tag): ex command "[count]tag" jumps to newer entries

### PR DESCRIPTION
**Pull request by muniter**
Using the ex `:[count]tag` is supposed to jump to [count] newer
entry in the tagstack `:h tagstack`, this fixes the function `do_tag` to
actually follow this behavior. By refactoring the logic used in `:pop`
or CTRL-T to move to an item using the `tagstackidx`.

Previous to this changes jumping to newer entries in tagstack using
`:[count]tag` wasn't always possible because `do_tag` was searching for
the tag to then move to it, instead of moving forward in the tagstack.
Therefore unable to find tags that don't exist in a 'tagfile' or without
a 'tagfunc'. This is the case for tags defined using `settagstack` like
`vim.lsp.util.jump_to_location()` which is used for requests like:

- "textDocument/definition"
- "textDocument/declaration"
- "textDocument/typeDefinition"
- "textDocument/implementation"

Now there's a way to move to older items in the tagstack with `:pop` and
CTRL-T and to newer items in the tagstack with `:[count]tag`

### CODE REVIEW

**Comment by gpanders** [comment]
Should this be sent upstream and then patched into Nvim? I think Vim would benefit from this fix as well.

**Comment by muniter** [comment]
I was planning to send the patch to vim after merging. Giving priority to nvim since we are using tags a lot with lsp. I was also thinking on refactoring a bit here since the logic used for moving to the tag is the same as moving to a named mark, so I believe this is surely duplicate code and will try and replace it with some function that probably does this in `move.c` and don't know how much the codebases differ here. 

I would like to continue developing here since I know how to set up the environment, write the test and interact with the mantainers. When the PR is done you guys could decide if you want to merge first in upstream and then port the patch (something I'm not yet experienced on doing).

**Comment by clason** [comment]
In principle it is better to first merge upstream and then port (if possible) since that's our workflow, but there have also been instances where vanilla vim has included one our PRs after we merged it. (We then just have to remember to mark that patch as N/A.)

Maybe somebody can remember a specific instance to see how that went?

**Comment by muniter** [comment]
I saw this helpful when we didn't have an Lsp `tagfunc`. I still think is the better behavior, but I want to work on other things.

**Pull request closed without merging**
