### PR TITLE
vim-patch:f0b03c4e98f8

### PR DESCRIPTION
**Pull request by nono**
Update runtime files
https://github.com/vim/vim/commit/f0b03c4e98f8a7184d8b4a5d702cbcd602426923

### CODE REVIEW

**Comment by jamessan** [comment]
The upstream patch has some changes to doc/quickfix.txt, which aren't included here.  Looking at the context, it seems they may rely on some earlier patches (possibly normal source patches).

**Comment by nono** [comment]
For `doc/quickfix.txt`, it's only some typos fixes that were already fixed in Neovim or no longer relevant.

For the options in `doc/eval.txt`, it seems that Bram Moolenaar has pushed the documentation before the code (`NOT IMPLEMENTED YET!`). I was not sure what to to do about that. Do you think I should take this part of the  documentation in this pull request?

**Comment by jamessan** [comment]
> For `doc/quickfix.txt`, it's only some typos fixes that were already fixed in Neovim or no longer relevant.

We're missing parts that are present in that doc.  For example, the `*quickfix-parse*` isn't present in Neovim.  That section (and others) were added by [v8.0.1384](https://github.com/vim/vim/commit/74240d3febd1e3bc7cf086c647c9348b20716c33).  There may be other relevant commits that are missing, too.

> Do you think I should take this part of the documentation in this pull request?

No.

**Comment by justinmk** [comment]
The haskell changes were already included in 942f3587c38a83cf6486a0b779765b54a164849 (we need to merge runtime updates strictly in chronological order).

I'll merge the rest of this separately. Thanks.

**Pull request closed without merging**
