### PR TITLE
ci: only request review on open non-draft PRs

### PR DESCRIPTION
**Pull request by zeertzjq**

### CODE REVIEW

**Comment by clason** [comment]
Maybe we can also only trigger it on non-draft PRs?

**Comment by zeertzjq** [comment]
Is this not working or just GitHub showing self-contradictory information about a workflow?

**Comment by dundargoc** [comment]
You can't test the workflow in a pull request if that's what you mean.

**Comment by zeertzjq** [comment]
GitHub shows [this](https://github.com/neovim/neovim/actions/runs/1836633629/workflow) as the workflow file, so it is wrong.

**Comment by dundargoc** [comment]
Huh, my bad. Must've missed that then.

**Comment by dundargoc** [comment]
Github is drunk. I'm like 95% sure it's showing the wrong workflow file. Anyway, I tested in my own repo, seems to work fine.

**Review by dundargoc — APPROVED** [review]
LGTM

**Pull request merged**
