### PR TITLE
perf(treesitter): filter out trees outside the visible range early

### PR DESCRIPTION
**Pull request by tomtomjhj**
Problem:
Treesitter highlighter's on_line was iterating all the parsed trees, which can be quite a lot when injection is used. This may slow down scrolling and cursor movement in big files with many comment injections (e.g., lsp/_meta/protocol.lua).

Solution:
In on_win, collect trees inside the visible range, and use them in on_line.

NOTE:
This optimization depends on the correctness of on_win's botline_guess parameter (i.e., it's always greater than or equal to the line numbers passed to on_line). The documentation does not guarantee this, but I have never noticed a problem so far.

~~Fixes~~ related https://github.com/nvim-treesitter/nvim-treesitter/issues/5057 (this issue is about a single big block comment, and the current PR is about many single-line comments)

### CODE REVIEW

**Comment by wookayin** [comment]
Interesting work. There appears to be some bugs in determining visible range with the current viewport -- when I reload the buffer (`:edit`), highlights of some injected nodes are gone.

<details>
<summary>Screenshot</summary>

CleanShot 2023-12-17 at 02 07 59


</details>

**Comment by tomtomjhj** [comment]
Can reproduce. I'll investigate

**Comment by tomtomjhj** [comment]
the problem seems to be that `nvim__buf_redraw_range` doesn't go through on_win first

**Comment by tomtomjhj** [comment]
fixed

**Comment by lucario387** [comment]
From what I can tell, this will resolve nvim-treesitter/nvim-treesitter#5057. It is much better scrolling through large files with `comment` parser downloaded

**Comment by clason** [comment]
Try that (with nvim-treesitter's macro injection), too ;)

https://raw.githubusercontent.com/torvalds/linux/master/drivers/gpu/drm/amd/include/asic_reg/dcn/dcn_3_2_0_sh_mask.h

Is this something we can add a test for? (Maybe a benchmark?)

**Comment by tomtomjhj** [comment]
> https://raw.githubusercontent.com/torvalds/linux/master/drivers/gpu/drm/amd/include/asic_reg/dcn/dcn_3_2_0_sh_mask.h

It's still unusably slow in most cases, but there are some improvements. `G`-ing on that file is now quite fast.

> Is this something we can add a test for? (Maybe a benchmark?)

There was a wip PR with that: https://github.com/neovim/neovim/pull/23070

**Comment by clason** [comment]
>  but there are some improvements. G-ing on that file is now quite fast

I'll take it :) Incremental progress is still progress 👍 

> There was a wip PR with that: https://github.com/neovim/neovim/pull/23070

Yes, and I was wondering whether it would make sense to include (bits of) the test part of it? (Not a blocker if not.)

**Comment by lewis6991** [comment]
LGTM!

I do wonder if we should use `on_line` at all and just do everything in `on_win`? @bfredl

**Comment by tomtomjhj** [comment]
I just recalled that I rebased #23070 a few months ago and abandoned it as it didn't have noticeable improvement IIRC. Re-rebased: https://github.com/tomtomjhj/neovim/tree/lazy-injection. I can make a PR for this.

**Comment by tomtomjhj** [comment]
> I do wonder if we should use on_line at all and just do everything in on_win

I think on_line is not invoked for lines that don't need to be redrawn, so it should be faster than doing everything in on_win.

**Comment by lewis6991** [comment]
Note that `on_line` isn't actually drawing anything. It is simply adding marks to the marktree and by doing it in `on_line` it ends up placing duplicate marks for the same ast node. If we do it in `on_win` we can say add one mark for an entire block instead of adding N marks for each line. It would also potentially put less pressure on the iterator.

**Review by lewis6991 — APPROVED** [review]

**Comment by bfredl** [comment]
> Note that on_line isn't actually drawing anything. It is simply adding marks to the marktree and by doing it in on_line it ends up placing duplicate marks for the same ast node. If we do it in on_win we can say add one mark for an entire block instead of adding one mark per line. It would also potentially put less pressure on the iterator.

Hmm this sounds like a bug (or at least sub-optimal impl). later calls to `on_line` should keep the state of the iterator(s) and not "revisit" already handled matches (even in more complex multi-tree situations).

Regardless, I am not against more "batched" operation which might help performance, and in some cases do _everything_ in on_win (or equivalently the first call to on_line ). But I do think we might hit other perf issues if we are forced to _always_ do everything in the first call tho, in a case with a large viewports an a _lot_ of matches we still might want multiple callbacks per viewport to keep `decor_state->active` reasonably sized.

**Comment by tomtomjhj** [comment]
> Note that on_line isn't actually drawing anything.

Yes, but IIUC `on_line` is called only for the lines that are scheduled to be redrawn. For example, lines that are edited will be redrawn. Also, `on_bytes` and `on_changedtree` explicitly request redrawing of affected lines with `nvim__buf_redraw_range`. For untouched lines, `on_line` won't be invoked, avoiding unnecessary mark updates, which is why I believe it's better to keep using `on_line`. But I don't know much about the internals of redrawing, so I might be missing something. 

> Hmm this sounds like a bug (or at least sub-optimal impl). later calls to on_line should keep the state of the iterator(s) and not "revisit" already handled matches (even in more complex multi-tree situations).

IIUC this is what the current implementation does. See `state.iter` and `state.next_row`. So far, I have never noticed (with `:Inspect`) duplicate marks for the same node.

**Comment by lewis6991** [comment]
> Yes, but IIUC on_line is called only for the lines that are scheduled to be redrawn. For example, lines that are edited will be redrawn. Also, on_bytes and on_changedtree explicitly request redrawing of affected lines with nvim__buf_redraw_range. For untouched lines, on_line won't be invoked, avoiding unnecessary mark updates, which is why I believe it's better to keep using on_line. 

Yes, but just because `on_line` is only called for the required lines doesn't necessarily mean it is more efficient since it will incur an additional overhead of being called for each individual line.

Removing `on_line` might not be the best path forward, but there is still probably some more work we can move to `on_win` to reduce some of the per line overhead.

At some point I'll try and flamegraph this to see if there's any more low hanging fruit here.

> But I don't know much about the internals of redrawing, so I might be missing something.

The internal marktree is pretty efficient since it's all low level C. Minimising time spent is Lua and doing more in the marktree _might_ be a beneficial trade-off.

**Comment by lewis6991** [comment]
This is causing highlighting errors for me when I side-scroll text in the buffer.

image
image

**Pull request merged**
