### PR TITLE
refactor(options): remove `get_option_value_strict`

### PR DESCRIPTION
**Pull request by famiu**
Problem: `get_option_value_for` can perfectly replace `get_option_value_strict`, making the latter redundant.

Solution: Remove `get_option_value_strict`

### CODE REVIEW

**Comment by famiu** [comment]
@zeertzjq @justinmk would it be alright to make a "breaking change" to `nvim_get_option` so that using an invalid scope doesn't error (e.g. using `kOptReqWin` on a buf option)? Is it fine since `nvim_get_option` is deprecated? If so, we could remove `option_has_scope` as well

**Comment by lewis6991** [comment]
I think that would be a breaking change, so we should mark this PR as so and add a news entry. It's deprecated so the risk is very low.

LGTM otherwise.

**Comment by famiu** [comment]
> I think that would be a breaking change, so we should mark this PR as so and add a news entry. It's deprecated so the risk is low.
> 
> LGTM otherwise.

Actually I think it's fine for now. Let's keep `option_has_scope` for now and maybe we can deal with it in a followup PR

**Comment by zeertzjq** [comment]
Memory leak: #32361

**Pull request merged**
