### PR TITLE
[RDY] Store last search direction when writing ShaDa files

### LINKED ISSUE #3580: ShaDa reverses search direction of last pattern
Since the switch to ShaDa, resuming a forward search after quitting and restarting nvim will turn that search into a backward search. Maybe it's actually unrelated but I started noticing it soon after that PR was merged...

Steps to reproduce:
```
echo 'test test' > test
nvim -u NONE -i test.shada test
# in nvim: /t:q
nvim -u NONE -i test.shada test
# in nvim: n
# will show: search hit TOP, continuing at BOTTOM
```

### PR DESCRIPTION
**Pull request by ZyX-I**
Fixes #3580.

Note that there is behaviour change compared to Vim: Vim does not store the direction, it always assumes “forward”.

Blocked by #3270 (new key support was added also to runtime files from #3270). Also bringing that PR to attention: I would really like to see it in _before_ the release since it contains support code for one of the major features. Also because #3580 is only a minor inconvenience.

Feel free to cherry-pick last commit without changes to files from #3270 if latter is unacceptable for some reason.

### CODE REVIEW

**Comment by fmoralesc** [comment]
@ZyX-I can you rebase this? I just merged the ShaDa editing plugin

**Comment by ZyX-I** [comment]
@fmoralesc Rebased.

**Comment by fmoralesc** [comment]
Thanks, @ZyX-I. LGTM, I'll mark as RDY and wait for someone else to comment, but I think we can merge this.

**Comment by mhinz** [comment]
:+1:

**Comment by fmoralesc** [comment]
OK, merging.

**Pull request merged**
