### PR TITLE
build: BuildLuv: set/pass WITH_LUA_ENGINE

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neovim/neovim/pull/10438

### CODE REVIEW

**Comment by justinmk** [comment]
should also remove the comment here: https://github.com/neovim/neovim/blob/c4750be06dc6e28260741d01ac3c876ae4a55527/third-party/CMakeLists.txt#L41-L43

Before this change, `USE_BUNDLED_LUAJIT` was _already_ used to decide the "lua engine" here: https://github.com/neovim/neovim/blob/c4750be06dc6e28260741d01ac3c876ae4a55527/third-party/cmake/BuildLuarocks.cmake#L53-L69

So this change isn't really changing semantics. However, maybe we want to give an error if both `USE_BUNDLED_LUA=on` and `USE_BUNDLED_LUAJIT=on` ? (Unless this is backwards-incompatible>

**Comment by blueyed** [comment]
> does this close #10438 ?

Yes, it's meant to be a better approach to it.

> However, maybe we want to give an error if both `USE_BUNDLED_LUA=on` and
> `USE_BUNDLED_LUAJIT=on` ?

Not sure.  While it could prevent confusion, it is valid to use both LuaJIT,
but then explicitly Lua via `PREFER_LUA` for the functionaltest (main
projects).

I.e. it is OK to build both LuaJIT and Lua in third-party, but it would still
prefer LuaJIT there then for other bundled projects.

**Comment by blueyed** [comment]
> Before this change, `USE_BUNDLED_LUAJIT` was _already_ used to decide the "lua engine" here

That's only for rocks though.
It's certainly code that could/should be shared / factored out then maybe.

**Comment by blueyed** [comment]
@fwalch 
Does this work for you?

What is your build setup?  Using bundled Luv only?

**Comment by fwalch** [comment]
> Does this work for you?

I think this should work, yes.

> What is your build setup? Using bundled Luv only?

I would use bundled Luv with system Lua, yes. Basically [this `local.mk`](https://git.launchpad.net/neovim-ppa/tree/local.mk?id=0e437c00053d60155b4ab1c56885fd007bf2263f).

**Pull request merged**
