### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by dundargoc**
This is where typo fixes are collected.

### CODE REVIEW

**Comment by pedro757** [comment]
Maybe it's possible to add missing "prefix" option to the diagnostic docs
image
image

**Comment by dundargoc** [comment]
I don't use diagnostics so I wouldn't know where to start. If you have an idea on what it should say you could send a PR maybe?

**Comment by kawarimidoll** [comment]
I found typo that `idenfitier` on *ts-predicate-vim-match?* and *ts-predicate-offset!* in treesitter.txt.
Please fix them.

https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt#L215
https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt#L270

**Comment by clason** [comment]
> I found typo that `idenfitier` on _ts-predicate-vim-match?_ and _ts-predicate-offset!_ in treesitter.txt. Please fix them.
> 
> https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt#L215 https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt#L270

PR welcome!

**Comment by dundargoc** [comment]
> I found typo that `idenfitier` on _ts-predicate-vim-match?_ and _ts-predicate-offset!_ in treesitter.txt. Please fix them.
> 
> [`master`/runtime/doc/treesitter.txt#L215](https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt?rgh-link-date=2021-12-17T13%3A13%3A27Z#L215) [`master`/runtime/doc/treesitter.txt#L270](https://github.com/neovim/neovim/blob/master/runtime/doc/treesitter.txt?rgh-link-date=2021-12-17T13%3A13%3A27Z#L270)

I'll fix it. Thank you.

**Pull request merged**
