### PR TITLE
Remove useless FEAT_BROWSE ifdef

### PR DESCRIPTION
**Pull request by ghost**
The only thing this affected was the return value of
has('browsefilter').

### CODE REVIEW

**Comment by equalsraf** [comment]
LGTM

**Comment by Pyrohh** [comment]
@justinmk are you setting up a branch for 0.1.0 now? I'm not sure where this should be committed :)

**Comment by justinmk** [comment]
Can you check previous discussion about FEAT_BROWSE ?

ATM I am thinking only bug fixes should be sent to stable branch. More details on that later.

**Comment by equalsraf** [comment]
@justinmk  you mean #2160? This PR only removes the ifdef the feature is unchanged.

**Pull request merged**
