### PR TITLE
options: prefix "!" to 'viminfo' by default

### PR DESCRIPTION
**Pull request by fmoralesc**
Re: https://github.com/neovim/neovim/issues/2676

### CODE REVIEW

**Comment by justinmk** [comment]
Merged

**Comment by bounceme** [comment]
just curious, but why would someone want this?

**Comment by justinmk** [comment]
@bounceme Same reason one wants registers preserved: to persist arbitrary data.

**Comment by ZyX-I** [comment]
AFAIR I once used this to preserve input() history in one plugin.

Note: I do know that input() history is preserved. But it is only good as long as you have only one plugin which uses input(), normally you do not want history from different plugins mixed.

**Pull request closed without merging**
