### PR TITLE
win_update: fix redraw regression introduced in 6e9ea5ad

### PR DESCRIPTION
**Pull request by blueyed**
Before 6e9ea5adc `win_ins_lines` would return `FAIL` for `i/line_count == 0`.

Handle this by checking it in the outer `if`.

Ref: https://github.com/neovim/neovim/commit/6e9ea5ad#commitcomment-35084669

TODO:

- [x] test
- [x] move test?

### CODE REVIEW

**Comment by blueyed** [comment]
@bfredl 
Does it make sense?
Any pointer(s) for a test?

**Comment by bfredl** [comment]
@blueyed Why not use the example files for a test? You can insert the text into two temporary buffers and link them using `:diffthis`

**Comment by blueyed** [comment]
@bfredl 
Ok.  But I've meant more like where this should go within the test suite.
It might even make sense to have an oldtest for this, upstreaming it to Vim then.

**Comment by bfredl** [comment]
> . But I've meant more like where this should go within the test suite.

`test/functional/ui/diff_spec.lua` I presume?

> It might even make sense to have an oldtest for this, upstreaming it to Vim then.

But vim and nvim screen tests are completely different and not compatible with each other.

**Comment by blueyed** [comment]
Oh, missed your comment.
Have put it in test/functional/ui/screen_basic_spec.lua for now.

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
@justinmk 
This should also go into 0.4.3 - what's the procedure for it, add this PR to the milestone?
Should we cherry-pick things to the release-0.4 branch?

**Pull request merged**
