### PR TITLE
chore(doc): remove reference to vim.lsp.callbacks

### PR DESCRIPTION
**Pull request by teto**
too old now, can be confusing. waiting a bit in case I or someone finds some other old doc to remove

### CODE REVIEW

**Review by mjlbach — APPROVED** [review]

**Comment by mjlbach** [comment]
There's nothing in the docs, but still some references in test/functional/plugin/lsp_spec.lua

**Comment by mjlbach** [comment]
```
test/functional/plugin/lsp_spec.lua
217:      local expected_callbacks = {
224:          -- once the server initializes. It can't accept lua callbacks or
236:          eq(table.remove(expected_callbacks), {...})
242:      local expected_callbacks = {
258:          eq(table.remove(expected_callbacks), {...}, "expected callback")
268:      local expected_callbacks = {
285:          eq(table.remove(expected_callbacks), {...}, "expected callback")
291:      local expected_callbacks = {
310:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
346:      local expected_callbacks = {
364:          eq(table.remove(expected_callbacks), {...}, "expected callback")
370:      local expected_callbacks = {
398:          eq(table.remove(expected_callbacks), {...}, "expected callback")
404:      local expected_callbacks = {
439:          eq(table.remove(expected_callbacks), {...}, "expected callback")
445:      local expected_callbacks = {
472:          eq(table.remove(expected_callbacks), {...}, "expected callback")
478:      local expected_callbacks = {
512:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
521:      local expected_callbacks = {
558:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
567:      local expected_callbacks = {
601:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
610:      local expected_callbacks = {
649:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
658:      local expected_callbacks = {
698:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
707:      local expected_callbacks = {
747:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
757:      local expected_callbacks = {
792:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
801:      local expected_callbacks = {
843:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
852:      local expected_callbacks = {
895:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected callback")
906:      local expected_callbacks = {
925:          eq(table.remove(expected_callbacks), {err, method, params, client_id}, "expected handler")
```

**Comment by janlazo** [comment]
@teto Any updates? Is this ready?

**Comment by teto** [comment]
I messed up and pushed a follow up commit directly to master in a senile move. This is ready for review. I was fine with the mention to callback but renamed them to on_handler anyway. Is that what you wanted @mjlbach ?

**Comment by mjlbach** [comment]
Yes, still a bunch of "expected callback" strings if you grep the test file

**Comment by XVilka** [comment]
OpenBSD failure looks unrelated and probably should be restarted:
```
[#530681] 2021/06/22 09:58:16 Booting image openbsd/6.7 (default) on port 22157
Unknown base image 'openbsd/6.7'
[#530681] 2021/06/22 09:58:16 Processing post-failed triggers...
[#530681] 2021/06/22 09:58:16 Sending webhook...
[#530681] 2021/06/22 09:58:17 Webhook response: 200
[#530681] 2021/06/22 09:58:17 Sent build status to GitHub
[#530681] 2021/06/22 09:58:17 Error: boot: exit status 1
```

**Comment by mjlbach** [comment]
@teto can you rebase/replace the remaining references and we can merge this?

**Pull request merged**
