### PR TITLE
Use inclusive language

### PR DESCRIPTION
**Pull request by ursi**

### CODE REVIEW

**Comment by justinmk** [comment]
Send it upstream to Vim.

**Comment by ursi** [comment]
will do 👍

**Comment by ursi** [comment]
It appears we'll have to make these changes on our end vim/vim#5709.

**Comment by ursi** [comment]
@justinmk It appears we'll have to make these changes on our end vim/vim#5709.

**Comment by ursi** [comment]
Okay never mind. I guess they did it anyway 👍

**Pull request closed without merging**
