### PR TITLE
[RFC] Small fixes.

### PR DESCRIPTION
**Pull request by elmart**
A couple of small fixes:
- Bad assert, signaled by @Hinidu [here](https://github.com/neovim/neovim/pull/1794#commitcomment-9234697)
- Coverity problem introduced at https://github.com/elmart/neovim/commit/04c0658024a98a0586997f0ea8af1e3f774cc83e.

### CODE REVIEW

**Comment by Hinidu** [comment]
> Bad assert, signaled by @Hinidu here

LGTM

> Coverity problem introduced at elmart@04c0658.

I'm not sure that this warning deserves the fix. I think the analogous warning could be received on 32-bit platform for ```getdigits_int```. AFAIK Coverity has the ability to mark the issues as false positives.

**Comment by elmart** [comment]
> I think the analogous warning could be received on 32-bit platform for getdigits_int. 

In fact, this kind of "always true" warnings are often signaled **by the compiler** itself (clang/gcc).  Therefore, we are forced to fix them because of our warning-is-error policy in travis build.
But, for some reason, this one is not being caught by compilers, only by coverity.
So, as we usually fix them for the mentioned reasons, I wouldn't do an exception with this one.

> AFAIK Coverity has the ability to mark the issues as false positives.

When you mark something as false positive, it gets the "Dismissed" status.
We haven't established an official policy on this, but my personal practice up until now has been trying to eliminate the issue if possible (which sets a "Fixed" status), and leaving as "Dismissed" only those for which we can reason it's not an issue, but fixing it is very difficult / cumbersome.

Note, however, that this one in not a false positive. It's a real (but harmless) issue. We consider false positives those issues for which the signaled error path cannot occur, for reasons we know but coverity doesn't.

Thanks for reviewing!.

**Comment by Hinidu** [comment]
Ok, I understood your intention.
What do you think about the same problem with ```getdigits_int``` but on 32-bit platform? Don't you want add the same fix because Coverity don't complain about this issue?
I thought about your fix a bit and I don't understand why this expression is not always true in the same circumstances as the previous one. I think Coverity/compiler can be smart enough to find that ```sizeof(number) <= sizeof(long)``` is always true.

**Comment by elmart** [comment]
> What do you think about the same problem with getdigits_int but on 32-bit platform? Don't you want add the same fix because Coverity don't complain about this issue?

Well, this was admittedly a case of just-shut-up-the-warning ;-)
I could definitely add the other check. That would improve symmetry and follow principle-of-least-surprise.
The point is I'm not sure if we would get an "always false" warning then. I can't check until tomorrow (I've already wasted my 2-per-day coverity build quota).

> I thought about your fix a bit and I don't understand why this expression is not always true in the same circumstances as the previous one. I think Coverity/compiler can be smart enough to find that sizeof(number) <= sizeof(long) is always true.

You're right. I don't understand it either. But I've checked it works (I have a personal project fork in coverity so that I can check my fixes really work before sending them to neovim). I suppose the implementation of that doesn't cover all possible expressions.

**Comment by elmart** [comment]
Ok, I have added the corresponding check for `getdigits_int()` and checked it int my personal neovim fork at coverity.

As I feared, it introduces a new issue. I can't see which issue it is (viewing defect not allowed in my personal fork), but the only change with respect to the previous build is:
```
diff --git a/src/nvim/charset.c b/src/nvim/charset.c
index 024f4eb..d7ec082 100644
--- a/src/nvim/charset.c
+++ b/src/nvim/charset.c
@@ -1695,7 +1695,8 @@ intmax_t getdigits(char_u **pp)
 int getdigits_int(char_u **pp)
 {
   intmax_t number = getdigits(pp);
-  assert(number >= INT_MIN && number <= INT_MAX);
+  assert(sizeof(number) <= sizeof(int)
+         || (number >= INT_MIN && number <= INT_MAX));
   return (int)number;
 }
```
So, new issue must be an "alway true" warning because of the sizeof comparison.

Then, at this point, we can:
- Leave things as they are. This is, fix the warning, though not in the most elegant way.
- Remove last commit, and mark the warning at coverity's site. This is, dismiss the warning.

I personally think we should fix fixable things, but also understand other views on this.

Opinions?

**Comment by elmart** [comment]
Rebased

**Comment by justinmk** [comment]
[This post](http://stackoverflow.com/a/27041208/152142) suggests `sizeof(number + 0)` may be enough to make the warning go away, but coverity probably won't fall for that.

Can we guard the `assert()` statement in a `#if FOO > BAR` macro as mentioned in that post?

```
#if INT_MAX < ...
assert(sizeof(number) <= sizeof(int) ...
#endif
```

**Comment by elmart** [comment]
Done.

**Comment by Hinidu** [comment]
Great! I like this approach too.

**Comment by elmart** [comment]
Yes. I was trying to avoid preprocessor, not to make the thing so verbose, but in the end I convinced myself that this approach, though being more verbose, conveys meaning more clearly, and it's more correct (it doesn't rely on tricky coverity behaviour). I will use this style from now on.

**Comment by elmart** [comment]
> Perhaps it should be named SIZEOF_INTMAX_T in the line with SIZEOF_OFF_T?

Done.

**Comment by Hinidu** [comment]
LGTM :+1:

**Comment by justinmk** [comment]
Glad we found a pattern for this, it is needed elsewhere.

**Pull request merged**
