### PR TITLE
refactor(lsp): move workspace folder logic into the client

### PR DESCRIPTION
**Pull request by lewis6991**
- Changed `reuse_client` to check workspace folders in addition to
  root_dir.

### CODE REVIEW

**Comment by lewis6991** [comment]
@mfussenegger I saw your feedback on https://github.com/neovim/neovim/pull/20779#pullrequestreview-1152265645 but didn't really understand it.

1. How does changing the default `reuse_client` break uses of `vim.lsp.start()`?

> If reuse_client returns true, vim.lsp.start checks if the root_dir or workspace_folders from the config are different then the one from the client. If so, it extends the clients workspace_folders. This allows users to provide a different reuse_client function - e.g. if a client is known to handle multiple projects with a single language server instance, they could call start with something like reuse_client = function(client, config) return client.name == config.name) end.

This means by default, that `vim.lsp.start()` won't be reused even if the client supports multiple workspaces. Why would this be desirable? Surely this kind of stuff should be automatic and not something the general user should configure?

**Comment by mfussenegger** [comment]
> Why would this be desirable? Surely this kind of stuff should be automatic and not something the general user should configure?

Because there's a difference between opening multiple separate projects and opening a single project spanning different root folders. 
If we change lsp.start to always auto extend to workspace folders if the server supports it, we change the behaviour from the first use case to the second.

Granted, for language servers that are mostly single file (like css), or for cases like luals for plugin development the second scenario might make more sense, but for other languages it's rarer.

As a compromise, maybe we could expose an alternative reuse_client function to make it convenient to opt into multi-root behaviour. `lsp.start(... reuse_client = vim.lsp...)`

> Tbh, I'm not really sure of the purpose of the workspace functions in vim.lsp.buf as workspace folders are client specific, not buffer specific.

They don't really make much sense. We should deprecate them and replace them with methods on the client

**Comment by mfussenegger** [comment]
> Ok, I'll pivot this PR to deprecate these.

On second thought, maybe it's actually not that wrong.

E.g. looking at vscode, they have a "Add folder to workspace" menu-option that leads to a file/directory dialog. I'm not entirely sure what they then do afterwards, but I assume the selected folders always end up being reported as workspace folder to all active language servers too?

The `add_workspace_folder` kinda mirrors that, but imho they shouldn't be buffer specific, but global (given we have no workspace or project concept), so they'd probably need to be in `vim.lsp` and optionally support client filtering?


> [...] and accepts root_dir if it exists within some other root_dir. I'm not 100% sure the latter is sound either.

I'm not sure either. Ad-hoc I can't think of a scenario where you'd want to have a workspace folder that's a child of another workspace folder. Sounds more like a misconfiguration scenario to me.

**Comment by lewis6991** [comment]
> E.g. looking at vscode, they have a "Add folder to workspace" menu-option that leads to a file/directory dialog. I'm not entirely sure what they then do afterwards, but I assume the selected folders always end up being reported as workspace folder to all active language servers too?

Yes I believe that's true, however I believe in vscode "workspace" means "project", so when you do "add folder to workspace", it is adding a folder to the current project, and the current severs are encapsulated to that project. 

To open another project you need to run "New window" which will open a new workspace/project.

> The add_workspace_folder kinda mirrors that, but imho they shouldn't be buffer specific, but global (given we have no workspace or project concept), so they'd probably need to be in vim.lsp and optionally support client filtering?

Not quite as it isn't project scoped like it is in vscode. Unless we want to add the restriction that each Nvim instance should represent a specific project. For now we can probably leave that sort of stuff to third party plugins until we can come up with a better proposal to support multiple projects.

> I think the Client:.. methods are good enough for programatic access, but for ad-hoc use it seems a bit too low level. Another alternative could be to go ahead with the lsp.buf. function deprecation but add something like :LspWorkspaceAddFolder.

That was the intention. Is ad-hoc use important? It's not something I would personally be keen on using, but if it is, then we probably shouldn't deprecate this functions since buffers are about the only thing we scope. I don't think global functions are a good idea, again unless we introduce the above restriction.

> Not sure if we want to open that box, as there are also a few other command candidates (LspStop /  LspRestart could be added in core already - there's no need for a registry to implement them)

I totally think we should add those. Personally, I'd prefer `:Lsp stop`/`:Lsp restart`, but I'm already bikeshedding so that should be discussed separately.

> I'm not sure either. Ad-hoc I can't think of a scenario where you'd want to have a workspace folder that's a child of another workspace folder. Sounds more like a misconfiguration scenario to me.

Hmm ok, I'll back that off too.

**Comment by mfussenegger** [comment]
> however I believe in vscode "workspace" means "project", so when you do "add folder to workspace", it is adding a folder to the current project, and the current servers are encapsulated to that project.
> To open another project you need to run "New window" which will open a new workspace/project.

Yes, that's how I understood it as well.


> Not quite as it isn't project scoped like it is in vscode. Unless we want to add the restriction that each Nvim instance should represent a specific project. For now we can probably leave that sort of stuff to third party plugins until we can come up with a better proposal to support multiple projects.

> That was the intention. Is ad-hoc use important? It's not something I would personally be keen on using, but if it is, then we probably shouldn't deprecate these functions since buffers are about the only thing we scope. I don't think global functions are a good idea, again unless we introduce the above restriction.

Good point about the project scoping.
I don't really know if ad-hoc use is important, but after this discussion I'd tend to keep the lsp.buf functions for now (no deprecation).

> Personally, I'd prefer :Lsp stop/:Lsp restart, but I'm already bikeshedding so that should be discussed separately.

No strong opinions and either is fine for me. In my plugins/dotfiles I tend to go with dedicated commands per action, but that's mostly because the command completion system has no sub-command concept. These are the ones I currently use:

https://github.com/mfussenegger/dotfiles/blob/1d205713cdb10e2f89a228170f4b23e921142fe1/vim/.config/nvim/lua/me/lsp.lua#L210-L249

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
