### PR TITLE
Support rgba background detection

### LINKED ISSUE #10159: urxvt: always insert some text on startup
- `nvim --version`:
0.4.0 only, installed by appimage or yaourt.
```
NVIM v0.4.0-964-gf6f9e4a23
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-b8b84ff4-b35e-442b-8065-8504a5437683

Features: +acl +iconv +tui 
```
- Vim (version: ) behaves differently?
- Operating system/version:
Manjaro / Linux kernel 4.19.45-1-MANJARO
- Terminal name/version:
Appears on:
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
Doesn't appear on
```
xfce4-terminal 0.8.7.4 (Xfce 4.13)
```
- `$TERM`:
Appears on `rxvt-unicode-256color`
Does't appear on `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
If start by `nvim` or `nvim emptyfile`, it will insert text `:0000/2aff/35ff/cccc` and turn to insert mode;
If start by `nvim existsfile`, it will insert text `g:0000/2aff/35ff/cccc` at the file's beginning and turn to insert mode.
And I have to press `<ESC>` twice to escape this insert mode, while I just need to press once to escape insert mode later. 
This phenomenon seems to appear only on urxvt terminal.

After startup, it looks like this (the left is urxvt, and the right is xfce-terminal)
图片

### PR DESCRIPTION
**Pull request by HarmtH**
Resolves #10159

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
Awesome, one lint issue:

> src/nvim/tui/input.c:454:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 453  [whitespace/alignment] [2]

**Comment by blueyed** [comment]
functionaltest failed:

    [  ERROR   ] ...d/neovim/neovim/test/functional/ui/searchhl_spec.lua @ 150: search highlighting is preserved during :terminal activity
    test/functional/ui/screen.lua:554: Row 1 did not match.
    Expected:
      |*  {3:foo} bar baz       {3:│}                   |
      |  bar baz {2:foo}       {3:│}                   |
      |  bar {2:foo} baz       {3:│}                   |
      |                    {3:│}                   |
      |{1:~                   }{3:│}                   |
      |{5:[No Name] [+]        }{3:term               }|
      |/foo^                                    |
    Actual:
      |*  {3:foo} bar baz       {3:│}xxx                |
      |  bar baz {2:foo}       {3:│}                   |
      |  bar {2:foo} baz       {3:│}                   |
      |                    {3:│}                   |
      |{1:~                   }{3:│}                   |
      |{5:[No Name] [+]        }{3:term               }|
      |/foo^                                    |
    To print the expect() call that would assert the current screen state, use
    screen:snapshot_util(). In case of non-deterministic failures, use
    screen:redraw_debug() to show all intermediate screen states.  
    stack traceback:
            test/functional/ui/screen.lua:554: in function '_wait'
            test/functional/ui/screen.lua:366: in function 'expect'
            ...d/neovim/neovim/test/functional/ui/searchhl_spec.lua:168: in function <...d/neovim/neovim/test/functional/ui/searchhl_spec.lua:150>

**Comment by blueyed** [comment]
Thank you!

**Comment by blueyed** [comment]
Just for reference/info: the tests need to cycle between light/dark: https://github.com/neovim/neovim/pull/10229.

**Pull request merged**
