### PR TITLE
vim-patch:8.0.0678 closing a window does not trigger resizing

### LINKED ISSUE #1707: :set equalalways not respected anymore.
As described in https://github.com/neovim/neovim/issues/6748 `:set equalalways` doesn't work anymore. Here's how to reproduce the bug:
```
vim -c "set equalalways | vs | windo sp" -c "sp | wincmd J | close" 
```

### LINKED ISSUE #6748: Non-proportional window resizing on window close
- `nvim --version`: NVIM v0.2.1-182-g6e4e70f
- Vim (version: ) behaves differently? Can't test right now.
- Operating system/version: Linux 4.9.6-gentoo-r1
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: xterm-256color

### Actual behaviour
With the following window layout:
```
---------
¦ a ¦ b ¦
---------
¦ c ¦ d ¦
---------
¦   e   ¦
---------
```
Closing the window 'e' will result in this layout:
```
---------
¦ a ¦ b ¦
¦   ¦----
----¦   ¦
¦ c ¦ d ¦
---------
```
### Expected behaviour
I expected the layout to be proportional:
```
---------
¦ a ¦ b ¦
---------
¦ c ¦ d ¦
---------
```
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c "vs | windo sp" -c "sp | wincmd J | close" 
```

I believe this behaviour has been introduced in the last three months as I don't recall this happening before. I wanted to try it on previous versions but somehow couldn't get them to build.

### PR DESCRIPTION
**Pull request by justinmk**
Closes #6748

Problem:    When 'equalalways' is set and closing a window in a separate
            frame, not all window sizes are adjusted. (Glacambre)
Solution:   Resize all windows if the new current window is not in the same
            frame as the closed window. (closes vim/vim#1707)

https://github.com/vim/vim/commit/8eeeba8c025ff844e6514c4a60cec11bf1fc1b35

### CODE REVIEW

**Comment by justinmk** [comment]
@bfredl new PRs are failing QB on some kbtree-related warnings:

```
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:238:28: error: array subscript is below array bounds [-Werror=array-bounds]
17:29:22,832 WARN  - kp = __KB_KEY(key_t, x)[i]; \
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
17:29:22,832 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
17:29:22,832 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
17:29:22,832 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:239:23: error: array subscript is below array bounds [-Werror=array-bounds]
17:29:22,832 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 1); \
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
17:29:22,832 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
17:29:22,832 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
17:29:22,832 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:243:28: error: array subscript is below array bounds [-Werror=array-bounds]
17:29:22,832 WARN  - kp = __KB_KEY(key_t, x)[i]; \
17:29:22,832 WARN  - ^
17:29:22,832 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
17:29:22,832 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
17:29:22,832 WARN  - ^
```

**Comment by chrisbra** [comment]
Note, the patch is not completely correct yet, it accesses freed memory.

**Comment by bfredl** [comment]
Hmm didn't I silence `-Werror=array-bounds` ...

**Comment by justinmk** [comment]
There were some follow up patches I think. ...

**Comment by jamessan** [comment]
The one mentioned patch was already part of the PR, and I don't see any other patches that are obviously related.  If more are needed, then there can be more PRs.  I'm trying to whittle down the pending Vim PRs.

**Pull request merged**
