### PR TITLE
Use luajit2 instead of luajit on big endian machines

### PR DESCRIPTION
**Pull request by juru1234**
Because we do not build neovim for IBM s390x architecture ourselves (Linux distributions do this for us) and we want to enable luajit support on our architecture, this patch ensures that luajit2 instead of luajit is used on big endian architectures.

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but no. We only officially support LuaJIT and (where that is not available) PUC Lua.

You are very welcome to make these changes downstream, like every other distribution.

**Comment by XVilka** [comment]
@julianruess there were several attempts on getting s390 mainlined to LuaJIT, you can check their PRs and maybe revive the effort.

**Comment by clason** [comment]
I believe what's missing there is someone sponsoring Mike Pall for adding (and keeping!) support for a new architecture.

**Comment by dundargoc** [comment]
I still stand by what [I said before](https://github.com/neovim/neovim/issues/23603#issuecomment-1546619027):

> I don't think we can officially take on a third lua alternative (lua, luajit and luajit2) from a maintenance standpoint. Lua is supposed to be the fallback in cases where luajit isn't available.

Even supporting just lua and luajit can be time consuming with a bunch of nasty edge cases, and adding luajit2 on top of this doesn't sound fun.

That said I think this can be solved without our involvment. I don't see a reason why distributions can't opt to choose luajit2 instead of lua on big endian systems. We have (for better or worse) zero control how distributions choose to build neovim. If you suggest this to the neovim package maintainer for a distro and they agree with you then that should solve your problem IMO.

**Comment by clason** [comment]
Also, I find it a bit disingenuous to make this PR without linking to your previous issue, which ended with a clear resolution against the very change your propose here.

**Comment by julianruess** [comment]
The last issue was a suggestion to replace luajit with luajit2 on all architectures. This one only affects big endian architectures. There was no clear resolution against this.

**Comment by clason** [comment]
I'm sorry, but what part of "we won't support s390x" and "we won't add support for a third Lua runtime" was unclear? In any case, you should have linked the issue and explained why this PR is different.

**Comment by clason** [comment]
(Don't get me wrong, we'd _love_ if Neovim had first-class support on s390x. But _we_ can't make this happen for lack of manpower and infrastructure. If _you_ volunteer to maintain that support on a long enough time horizon, we'd be happy to reconsider.)

**Comment by julianruess** [comment]
https://github.com/neovim/neovim/issues/23603

"This seems to work fine when I did a quick test. Of course, we can't make any guarantees that this'll continue to work in the future, and any issues with this setup will be instaclosed with "we don't support that, so don't do that". But if this is a risk you're fine with then that is also a possibility."

What I don't understand is that even today you're not able to test neovim (without luajit) on s390x, right? So what prevents you from adding a few lines that you also cannot test?

**Comment by clason** [comment]
> What I don't understand is that even today you're not able to test neovim (without luajit) on s390x, right? So what prevents you from adding a few lines that you also cannot test?

Because we haven't added anything _specific_ that we can't test. If it works, fine, enjoy the freebie, but no guarantees. And we won't make _any_ changes to our build scripts (which are a house of cards already) that we can't test.

**Comment by dundargoc** [comment]
> What I don't understand is that even today you're not able to test neovim (without luajit) on s390x, right? So what prevents you from adding a few lines that you also cannot test?

I don't feel comfortable adding code we don't intend to maintain. If this breaks in the future we'll still need to either fix it or remove it. We're responsible that all code works at the end of the day.

I also feel you haven't done a good case as to why PUC lua isn't sufficient for your use case. I get the impression PUC lua (in general) gets a bad rep due to have insanely fast luajit is, but it is by no means slow.

Most importantly: I want to emphasize that distributions modify our build scripts however they want and that we have no control on what they do. Even if we merge this there is nothing stopping distros to just replace luajit2 with lua on big endian systems if they want to.

For curiosity: which distributions are you thinking about?

**Comment by julianruess** [comment]
We want to migrate some setups from vim to neovim because it is awesome what is possible with it and it has a better community.

I tried to build neovim by hand on s390x and it failed because it cannot install the luajit dependency. Should that be the case when following the default neovim build instructions when PUC lua is the default? Because of this I thought we need luajit. Nevertheless I played around with some modern package managers like lazy.nvim or packer.nvim and it seems that they require luajit. Are there also plugins right now (or in the future) that require luajit? This just seemed to me that we're not really future proof by just using PUC lua.

Yes, we can also ask the Linux distributions (Suse, Red Hat, Ubuntu, Fedora) to build neovim with luajit2 for us but this is a lot of effort and hard to handle.

**Comment by clason** [comment]
Yes, some plugins require LuaJIT (for FFI); in this case you need to manually edit the `deps.txt` file like we showed you; then a simple `make` should go through.

> Yes, we can also ask the Linux distributions (Suse, Red Hat, Ubuntu, Fedora) to build neovim with luajit2 for us but this is a lot of effort and hard to handle.

Yes, but that is effort with a much greater payoff, not just for you (and required even if we make the requested change, since distributions in general do not use our build scripts for dependencies).

**Comment by folke** [comment]
@julianruess fyi: I have multiple widely used plugins that require LuaJIT.
`lazy`, `noice`, `flash` and `edgy`

**Comment by julianruess** [comment]
It is easier for us to have changes upstream and tell the distributions "just build as upstream". But you're right, this is not the right place here to make this change. I'm currently in discussions with the distributions and I'll let you know if there will be decisions regarding replacing luajit with luajit2 not only on s390x. Sorry for the inconvenience :-)

**Comment by clason** [comment]
> It is easier for us to have changes upstream and tell the distributions "just build as upstream". 

Oh, you sweet summer child... 

(Again, just to be clear: **no** distro "just builds as upstream". The fact alone that we statically link our dependencies means they torch our build scripts with fire.)

> decisions regarding replacing luajit with luajit2 for all packages

I don't think that will be acceptable, as LuaJIT is the source of truth here and gets faster security updates (and is the one tested by us). I see LuaJIT2 only as a reasonable (for now) drop-in replacement for those very few architectures which they support but LuaJIT doesn't.

**Comment by dundargoc** [comment]
> I tried to build neovim by hand on s390x and it failed because it cannot install the luajit dependency. Should that be the case when following the default neovim build instructions when PUC lua is the default?

Luajit is the default, not PUC lua. PUC lua is meant as a fallback/replacement when luajit can't be used. If you mean that PUC lua should be chosen by default on s390x then I guess that's a fair point.

> Nevertheless I played around with some modern package managers like lazy.nvim or packer.nvim and it seems that they require luajit.

I'm fairly sure packer.nvim does not require luajit. What makes you think it does?

> Are there also plugins right now (or in the future) that require luajit?

It looks like anything by folke will require luajit. Other than that a luajit requirement is rare. We don't govern how plugins are developed so I can't tell you how future plugins will be like.

> This just seemed to me that we're not really future proof by just using PUC lua.

I don't understand what you mean. A single plugin author decided to have luajit as a requirement for their plugins. How can we possibly draw meaningful conclusions from this?

> Yes, we can also ask the Linux distributions (Suse, Red Hat, Ubuntu, Fedora) to build neovim with luajit2 for us but this is a lot of effort and hard to handle.

I asked so *I* could contact the relevant distribution. If you and your team really use 5 different linux distros then I guess that's out of the question regardless.

I think this issue is at the end of the road and that there's not much we can do. You should already be able to download neovim on s390x with your distros package manager, although with PUC lua. Most plugins will work just fine with that. If that's not sufficient then we've already provided a way for you to manually install neovim with luajit2. Why are these workarounds not sufficient?

**Comment by dundargoc** [comment]
If you're serious about this and do want to see it through (and you have the resources for it) then the best way is to fund Mike Pall to fix luajit for the s390x system.

**Pull request closed without merging**
