### PR TITLE
docs(help.txt): Add a tag to the neovim api.

### PR DESCRIPTION
**Pull request by muniter**
Probably one of the most searched help files, one of the best features! and It is not on the main help file.

Also, should treesitter.txt be added? Or wait until 0.6?

### CODE REVIEW

**Comment by muniter** [comment]
@dundargoc Good bot, only documentation tag.

**Comment by dundargoc** [comment]
> Also, should treesitter.txt be added? Or wait until 0.6?

Pinging @vigoux.

**Comment by bfredl** [comment]
master is what will become 0.6, so let's do it now.

**Comment by muniter** [comment]
Done. 👍🏽

**Review by vigoux — APPROVED** [review]

**Comment by muniter** [comment]
I force pushed to comply with the commit linter.

**Pull request merged**
