### PR TITLE
[RFC] defaults: revert wildmode to 'full'

### PR DESCRIPTION
**Pull request by fmoralesc**

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! I updated https://github.com/neovim/neovim/issues/2676 as well.

**Comment by Pyrohh** [comment]
I don't mind this change, but what's the reasoning behind this? I guess this was discussed on Gitter and I missed it.

**Comment by justinmk** [comment]
Some people complained about it, and I haven't heard from anyone who actually _likes_ the change. Only reason the change was originally merged was because I had assumed it was part of vim-sensible and that I was the only one who didn't like it :) Turns out, it is not part of vim-sensible, and there isn't a strong argument in favor of changing the Vim default, so as always we want to keep the Vim defaults where possible.

**Comment by fmoralesc** [comment]
I didn't like it from the start, but the whole discussion about it in #2676 was in favour of `longest:list`, so I just took it from the community input... :p

**Comment by Pyrohh** [comment]
Thanks, that's fair.

> so as always we want to keep the Vim defaults where possible.

Indeed. I'm sure that mindset is appreciated by those who use both Nvim and Vim; the `if has('nvim')` blocks I've seen so far have usually been quite small..

**Comment by justinmk** [comment]
Also considered (and rejected) on vim_dev: https://groups.google.com/forum/#!topic/vim_dev/gL5DXac4NaU

**Pull request merged**
