### PR TITLE
[RDY] Remove deadcode due to nonnullret funcs.

### PR DESCRIPTION
**Pull request by elmart**
Review all invocations of functions declared as FUNC_ATTR_NONNULL_RET,
and remove redundant checks for null/not-null.

### CODE REVIEW

**Comment by aktau** [comment]
:+1: I really love these sorts of code and complexity reductions! I remember @philix doing some huge NULL-check commits. Are these new introductions of non-NULL-ness or just things that were overseen the first time? (which would be no surprise, seeing how much cleanup this codebase needs).

**Comment by elmart** [comment]
> Are these new introductions of non-NULL-ness or just things that were overseen the first time?

I think most of them are still leftovers (I mean, not introduced by new code).
And there are more. I've just fixed the ones I've seen "clear" enough.
There are others within very involved code (usually employing the n-iteration pattern), for which is difficult to reason at the present state. When that code is refactored, more of this cleanup will be possible.

**Comment by elmart** [comment]
Travis build is failing, but I'm not sure if because of this PR.
Changing to WIP, as I can't investigate it more until tomorrow.

**Comment by aktau** [comment]
> I think most of them are still leftovers (I mean, not introduced by new code).
And there are more. I've just fixed the ones I've seen "clear" enough.
There are others within very involved code (usually employing the n-iteration pattern), for which is difficult to reason at the present state. When that code is refactored, more of this cleanup will be possible.

Alright, great news.

**Comment by elmart** [comment]
Fixed problems and repushed. Grouped commits on the function(s) returning non-null responsible of the simplified expression.

**Comment by aktau** [comment]
LGTM!

**Comment by oni-link** [comment]
LGTM.

**Comment by elmart** [comment]
Repushed. Marking RDY when Travis passes.

**Comment by elmart** [comment]
Ok, thx guys.

**Comment by justinmk** [comment]
Awesome!

**Comment by philix** [comment]
> :+1: I really love these sorts of code and complexity reductions! I remember @philix doing some huge NULL-check commits. Are these new introductions of non-NULL-ness or just things that were overseen the first time? (which would be no surprise, seeing how much cleanup this codebase needs).

@aktau @justinmk @elmart BTW, I really want to continue doing cleanups of the codebase and helping with Neovim, but for the next two months I have to focus on school work and my job interview for a big Silicon Valley tech company.

**Comment by aktau** [comment]
> @aktau @justinmk @elmart BTW, I really want to continue doing cleanups of the codebase and helping with Neovim, but for the next two months I have to focus on school work and my job interview for a big Silicon Valley tech company.

I had to stop for a tiny bit too because of job/country move and getting through legal issues too, but in the end it's alright. So relax and focus on the interview (though I must say that coding on Neovim was likely one of the things that gave me enough chops to get through some parts of my interviews). Good luck!

**Pull request merged**
