### PR TITLE
[RDY] Miscellaneous fixes

### PR DESCRIPTION
**Pull request by tarruda**
Some errors during helptags can be caused by duplicate/wrong tags after documentation cleanup. Suggest the removal of the "doc" directory.

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!

Could the vim command to generate help tags also be made more verbose / less silent, e.g. by removing the `-s`?

**Comment by tarruda** [comment]
I don't think removing `-s` would help much. Did you test it?

**Comment by blueyed** [comment]
No, it's probably related to (Neo)Vim not doing any/much output in that case anyway.

I'll test it when I should be running into it again.

**Comment by tarruda** [comment]
> I'll test it when I should be running into it again.

You can probably reproduce the bug by adding a duplicate tag in a help doc

**Pull request merged**
