### PR TITLE
[RFC] :digraphs color

### PR DESCRIPTION
**Pull request by jalvesaq**
Highlight the digraphs shown with the command :digraphs.
The original patch was posted in vim_dev list some time ago.

### CODE REVIEW

**Comment by jalvesaq** [comment]
I am not the author of this patch. I have seen it some time ago and have used it since then in Vim (http://comments.gmane.org/gmane.editors.vim.devel/39733).

There is one difference between the original patch and this pull request: the color chosen for the highlight is `HLF_CONCEAL` (which results in the same color of Special characters highlight group) and not `HLF_D` (color used to highlight directories).

**Comment by justinmk** [comment]
Cool, but why not create a new highlight group? What if I don't want digraphs highlighted but I *do* want concealed chars highlighted?

Also, could you add a couple screen tests? (Just copy https://github.com/neovim/neovim/blob/master/test/functional/ui/syntax_conceal_spec.lua to a new file, `test/functional/ui/digraph_highlight_spec.lua` and use it as a base to work from)

**Comment by jalvesaq** [comment]
I agree that it could be better if the digraphs had their own highlight group, but I don't know how to create one. I simply applied a patch that was created by another person. My only change was to choose another color. I am sorry, but I also don't understand the lua tests well enough to change them, and I would be grateful if someone could do these things for me. Perhaps I should have opened an issue, and not made a pull request.

**Comment by justinmk** [comment]
It's no problem. Others might want to pick this up.

**Comment by justinmk** [comment]
This only affects `:digraphs`, it's low-risk. `hl-SpecialKey` (`HLF_8`) seems more appropriate so I change it to that.

**Pull request closed without merging**
