### PR TITLE
Improve error msg

### PR DESCRIPTION
**Pull request by ColeFrankenhoff**
Fix for issue [ #26988](https://github.com/neovim/neovim/issues/26988). Improve error message by changing generic e474 to hardcoded string for e475.

This is my first pr, any feedback would be much appreciated!

### CODE REVIEW

**Comment by wookayin** [comment]
Thank you for your (first) contribution!

- First of all, please make sure to read https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md which has helpful information for you: especially pull requests, lint, commit messages, etc. Also please try to have more descriptive title of the PR.
- Tests will also be fixed and needed for all the changed behaviors. It'd be helpful for you to run tests locally (see https://github.com/neovim/neovim/blob/master/test/README.md) before pushing.
- In general, you should not hard-code E475 error message strings. Search for `e_invarg2` or `semsg(_(e_invarg2), ...)`, and how it's done in other places.

**Comment by zeertzjq** [comment]
These messages look a bit too verbose.

**Comment by ColeFrankenhoff** [comment]
Appreciate it! Will take another look at contributing.md, and fix the issues you mentioned. Sorry for not reading the docs carefully enough the first time around.

I'm not sure semsg would work here without some amount of refactoring elsewhere. Unlike most of the codebase, set_chars_option returns a char* with its error value. 

At first I wanted to return an error using e_invarg2, but what I tried (returning a value created with snprintf and the specific error message) seemed more messy than just hard-coding strings. I couldn't figure out a good way to use the global error values without semsg. 

Is there a good way to do this, or should I change the set_chars_option function to use semsg for error logging and return an int (OK or FAIL)?

**Comment by zeertzjq** [comment]
Hmm, half of these message are wrong, so I'm closing this. Please see https://github.com/vim/vim/pull/13877

**Comment by ColeFrankenhoff** [comment]
Gotcha. Sorry to waste your time.

**Pull request closed without merging**
