### PR TITLE
update haskell related runtime files

### LINKED ISSUE #13797: update haskell related runtime
the haskell syntax plugin for instance is about 2 years out of date
`" Last Change:		2018 Mar 29 by Marcin Szamotulski`
vs
`" Last Change:		2020 Oct 4 by Marcin Szamotulski <profunctor@pm.me>`
effected files:
```
runtime/syntax/haskell.vim
runtime/ftplugin/haskell.vim
runtime/autoload/haskellcomplete.vim
runtime/syntax/chaskell.vim
runtime/syntax/lhaskell.vim

runtime/syntax/cabal.vim
runtime/syntax/cabalconfig.vim
runtime/syntax/cabalproject.vim
```

i tried making the patch for this myself, but I don't feel confident enough to make this patch since it's probably got its tendrils in other places as well

### PR DESCRIPTION
**Pull request by goolord**
resolves https://github.com/neovim/neovim/issues/13797
the commits which updated these files had there tendrils in many places, so this pr just copies the files from vim's `master` directly

### CODE REVIEW

**Comment by janlazo** [comment]
I can merge this PR after the commit messages are updated to be similar to other `runtime/` commits. Example PRs: https://github.com/neovim/neovim/pull/13718, https://github.com/neovim/neovim/pull/13558, https://github.com/neovim/neovim/pull/13523

**Comment by goolord** [comment]
done, hopefully to satisfaction

**Comment by janlazo** [comment]
You should not combine changes from multiple runtime patches into 1 commit. It makes it hard to audit where runtime changes came from. `runtime/cabal: <commit-hash>` implies a 1-1 port of the `cabal` files from the `<commit-hash>`.

```sh
$ ./scripts/vim-patch.sh -L -- 'runtime/*cabal*'
4f4d51a942cc2c6b3e936ee0f93f00c2d000065c
23515b4ef7580af8b9d3b964a558ab2007cacda5
```

suggests that 2 commits are required for cabal runtimes.

In the vim codebase,

```sh
git show 4f4d51a942cc2c6b3e936ee0f93f00c2d000065c -- 'runtime/*cabal*'
```

shows a diff for `runtime/syntax/cabal.vim`. Thereforce, `runtime/cabal: 4f4d51a942cc2c6b3e936ee0f93f00c2d000065c` should port `runtime/syntax/cabal.vim` only.

Refer to https://github.com/neovim/neovim/pull/13835 on zsh runtime files were ported.

**Comment by goolord** [comment]
closing in favor of https://github.com/neovim/neovim/pull/14048

**Pull request closed without merging**
