### PR TITLE
fix(lsp): fix lookup of boolean values in workspace/configuration

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix lookup of boolean (false) values in workspace/configuration requests.

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]

**Comment by fredrikekre** [comment]
Lint error in `src/nvim/indent_c.c` looks unrelated, but doesn't happen on the master branch. Maybe it is fixed after my last rebase?

**Comment by zeertzjq** [comment]
You didn't rebase on the latest master branch.

**Comment by fredrikekre** [comment]
The last rebase was 3 days ago, but just rebased again on master now.

**Comment by mjlbach** [comment]
Should handle/return vim.NIL internal to that lookup function?

**Comment by fredrikekre** [comment]
Yea, maybe that is cleaner. I will update the PR.

**Review by mjlbach — APPROVED** [review]

**Comment by fredrikekre** [comment]
Is it helpful if I'd make a manual backport and make a PR to the release branch in cases like this? I don't know the procedure for this repo.

**Comment by clason** [comment]
The failure is due to the lack of PR description (hint, hint).

**Comment by fredrikekre** [comment]
I see, thought the patch just didn't apply cleanly.

**Pull request merged**
