### PR TITLE
feat!: remove vimballs

### PR DESCRIPTION
**Pull request by dundargoc**
Vimball is an outdated feature that is rarely used these days. It is not
a maintenance burden on its own, but it is nonetheless dead weight and
something we'd need to tell users to ignore when they inevitably ask
what it is.

See: https://github.com/neovim/neovim/pull/21369#issuecomment-1347615173

### CODE REVIEW

**Comment by clason** [comment]
What is gained by removing this?

(A "vimball" is an archive file format for installing plugins, before packages were a thing. It was Vim's answer back then to the perennial cry "we need a builtin plugin manager!" that still persists to this day.)

**Comment by zeertzjq** [comment]
How will one be able to achieve this without vimball?
```
	Vimball is intended to make life simpler for users of plugins.  All
	a user needs to do with a vimball is: >
		vim someplugin.vba
		:so %
		:q
```

**Comment by clason** [comment]
I think it's not a good idea to remove the text from `usr_05.txt`, as this illustrated how to _use_ installed packages. Better to replace `vimball` with another bundled one, for example `justify`.

**Comment by dundargoc** [comment]
> How will one be able to achieve this without vimball?

I don't understand? They won't be able to use vimballs if we remove support for vimballs. Isn't that expected?

**Comment by zeertzjq** [comment]
@jamessan

**Comment by clason** [comment]
Related issue: https://github.com/neovim/neovim/issues/17737

**Comment by bfredl** [comment]
From discussion in chat: `Vimuntar` command and `tar#Vimuntar()` function should also be removed (install a .tar file as-if it was a vimball, _not_ a generic untar mechanism).

Other than that, there is no reference to "vimball" in the runtime outside of the vimball plugin itself (except for version history comment in cabal.vim).

**Comment by jamessan** [comment]
But how will people test out new versions of Dr. Chip's plugins?

**Comment by clason** [comment]
Summary of discussions: I think there's broad consensus that this is a feature not worth keeping around (even though it's self-contained and thus not a noticeable maintenance problem).

However, I also think it would be better to do this as part of a general, concerted, "runtime spring cleaning" after the 0.9.0 release which drops obsolete plugins or replaces them with more modern (Neovim-specific) alternatives. I'll open a tracking issue about this in the next few days.

**Comment by clason** [comment]
rebase and good to merge?

**Pull request merged**
