### PR TITLE
feat(option): add previewpopup option

### LINKED ISSUE #9920: Floating window workflow
First of all, sorry if this has been suggested before, I haven't found anything about it, but there's a lot of issues on here regarding floating windows, and it's a tricky subject to search...

I recently wrote a short [blog article](https://www.zingiber.nl/blog/hacking-neovims-new-floating-windows/) about a simple, generic workflow tweak that leverages floating window support. In short, I really liked the idea of using floating windows on top of (both literally and figuratively) regular split windows. It would basically allow me to toggle an additional floating window that i could use for whatever buffer (scratch, terminal, any file) I wanted at the time. This allows for a lot of flexibility in my workflow. The article shows a very simple (and quite hacky) plugin, that implemented this the way i pictured it.

I linked this article on the subreddit, and I was asked to open an issue regarding my suggested workflow. For completeness sake, this is how I described it in the article:

- one simple keyboard mapping that shows a floating window over all the other split windows
- by default, it will simply show the buffer that was active when using the keyboard mapping
- opening other files, loading other buffers etc. should work the same as always (vim-vinegar is excellent for this)
- this floating window can be closed normally, or by hitting the mapping again
- closing the window won't actually delete the buffer, and when hitting the mapping again, will pull up the buffer you last looked at

- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### PR DESCRIPTION
**Pull request by glepnir**
Problem: we don't have previewpopup option like vim.

Solution: add `previewpopup` option and relate command like pedit and psearch will use float window.

https://github.com/neovim/neovim/assets/41671631/47447ca7-69e5-41cb-aa69-8b676e429748

Fix #9920

### CODE REVIEW

**Comment by glepnir** [comment]
emm unitest and oldtest are complaining. .

**Comment by dundargoc** [comment]
I reran the test. Basically that output shows up if the test fails for some reason.

**Comment by glepnir** [comment]
thanks i think i know why :)

**Comment by glepnir** [comment]
@bfredl  ptal :)

**Comment by bfredl** [comment]
Hmm, it is not clear to me what problem this solves. Maybe someone who actually uses the pedit/ptag functionality (either directly or as part of a plugin) could chime in if the new behaviors make sense.

**Comment by glepnir** [comment]
Achieved compatibility with vim. We are missing this option. It's just that it is used in the prepare_tagpreview function. So if the command uses this function and sets previewpopup, it will use a floating window instead.

**Comment by glepnir** [comment]
this also should close https://github.com/neovim/neovim/issues/9920 . 

> we might want to add ex commands to natively support this workflow

but as @bfredl  comment we want a different way to do this ?

**Comment by glepnir** [comment]
i think now is ready for review..

**Comment by wookayin** [comment]
Continued in #26799

**Pull request closed without merging**
