### PR TITLE
[RFC] runtime: rewrite matlab.vim indent file

### PR DESCRIPTION
**Pull request by lesurp**
```
changes:
1. add all the block-ending keywords to the indentkeys variable
2. remove the "explicitly joined" condition (not sure was the point is)
3. add a matlab-section check (if a line starts with a '%% ')
4. use the a:lnum rather than v:lnum in the indent function itself
5. correctly de-indent on block-ending keywords, and stop "trusting the
user"!
```

Hi! I noticed the indenting for Matlab/Octave files isn't working properly (and had a rather convoluted logic...), hence this PR.

Note that this was done with Octave in mind (regarding the keywords). Therefore we may want to remove the Octave specific keywords (if there are any, I don't have a Matlab license to check...). I think it is however safe to assume most people using vim to edit *.m files are Octave users. Besides, considering the indent file was completely unusuable before, I don't think anyone else cares..!

I also don't know what those lines are for:
```vimscript
  " Give up if this line is explicitly joined.
  if getline(a:lnum - 1) =~ '\\$'
    return -1
  endif
```
Maybe this is actually useful...

Next step is to add split-line indenting but that's a non-trivial change so another time maybe.

Please tell me if you have any feedback!

### CODE REVIEW

**Comment by zgpio** [comment]
Note that `shiftwidth` is 2.

**Comment by pLesur** [comment]
Hmm right. There doesn't seem to be any global guidelines regarding code formatting (or I have missed it), and browsing through the indent files the formatting there doesn't seem to be consistent either.
I guess I will change my indenting to the original one (`shiftwidth=2`)

**Comment by KillTheMule** [comment]
Hey, thanks for contributing! Although I must say, I do hate matlab ... :dagger: 

Anyways, this is a runtime file, and as such we usually don't keep our own versions around, but follow vim. I would suggest first contacting the maintainer of the file, and then vim upstream... BUT it seems the file has been updated in vim somewhat recently, see [here](https://github.com/vim/vim/commits/master/runtime/indent/matlab.vim).

So, yeah, what you should do is contact the new maintainer, get some consensus, and then send the corresponding PR upstream to vim. We will eventually merge that into neovim. Thanks!

**Comment by pLesur** [comment]
Oh OK I see that makes sense. I'm gonna close this PR then, thanks for your time :)

Reading through the latest `matlab.vim` on the vim repo, I realized that Octave uses `endif` `endfor` etc. while Matlab only supports the use of `end` to close blocks. Thence I tried again neovim's after replacing my block-endings and it turns out it works correctly for Matlab files but not for pure Octave ones.

I'll try to submit my patch on the vim repo, however it will likely be refused as it is (technically) backward incompatible with Matlab. If you use `endif` as an identifier in your code you probably deserve to have a broken indentation though...

Or I'll just make a plugin called 'no_matlab_only_octave'

**Pull request closed without merging**
