### PR TITLE
build(deps): bump tree-sitter to HEAD - eb970a83a

### PR DESCRIPTION
**Pull request by clason**
Includes https://github.com/tree-sitter/tree-sitter/pull/1952, which should prevent infinite loops with injections.

@folke

### CODE REVIEW

**Comment by folke** [comment]
# Fixes

- [ ] https://github.com/nvim-treesitter/nvim-treesitter/issues/4037
- [ ] https://github.com/LazyVim/LazyVim/discussions/43
- [ ] https://github.com/folke/noice.nvim/issues/286

# Probably Fixes

- [ ] https://github.com/neovim/neovim/issues/21275

**Comment by clason** [comment]
#21275 is a different issue, that still happens

**Comment by folke** [comment]
> #21275 is a different issue, that still happens

yep you're right. It's also not causing a hang.

**Comment by folke** [comment]
That lua issue I added was fixed in the parser, but the underlying issue seems to be the one fixed in the treesitter PR

**Pull request merged**
