### PR TITLE
[RFC] ui_compositor.c: fix insert at

### PR DESCRIPTION
**Pull request by Billy4195**
Fix the insert at loop bug.

cc @bfredl

### CODE REVIEW

**Comment by justinmk** [comment]
Nice catch! This in the PVS report, so please follow the commit message format mentioned [here](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#pvs-studio). In this case I would do:

    PVS/V501: ui_compositor: identical sub-expressions

**Comment by bfredl** [comment]
Thanks! In general, multiple floats is not well tested, it is on the TODO list...

**Comment by Billy4195** [comment]
@justinmk I have run the functional test locally, and it doesn't show any error.
Does `test/functional/ex_cmds/digraphs_spec.lua` relate to this PR?
The QuickBuild failed in this test case

**Comment by justinmk** [comment]
No. `digraphs_spec` is a known issue.

**Pull request merged**
