### PR TITLE
vim-patch:8.2.{1665,1726,1872,1893,1921,2280,2813}: `matchfuzzy` and friends

### PR DESCRIPTION
**Pull request by seandewar**
A few test changes are needed due to v8.2.1183 not being ported yet.

Supersedes #12995.

### CODE REVIEW

**Comment by tani** [comment]
@seandewar Thank you for a nice pull request. I am looking forward to using this function in neovim.
One question is what problem remained? I would like to help you if possible.

**Comment by tani** [comment]
@seandewar I see. Thank you for replying to me, and developing an awesome editor. cheers!

**Comment by zeertzjq** [comment]
I resolved the merge conflits.

**Comment by zeertzjq** [comment]
Hmm, I just found out that a part of <https://github.com/vim/vim/commit/b0d45e7f5354375edd02afafde3bd37dac1515ff#diff-b3aeef96275167ddcc1e5fee6d51b8f2018f9359f921d86ad6e7035ca80f20e9> was not ported in <https://github.com/neovim/neovim/commit/2ca59638ba04d11c397496d4f12f4d24e3461f0e#diff-b3aeef96275167ddcc1e5fee6d51b8f2018f9359f921d86ad6e7035ca80f20e9>.

**Review by zeertzjq — COMMENTED** [review]
Perhaps assertions can be used in place of some removed NULL checks for the results of `tv_list_find()` or `tv_dict_find()`?

**Review by zeertzjq — APPROVED** [review]

**Comment by seandewar** [comment]
I've added some asserts for the `li` NULL checks, as those are the ones I'm most confused about (fmatchlist should always have 3 items if retmatchpos is true, and N/A allocation failures are already checked by Vim before :shrug:).

I also added some other small changes; here's the diff before I rebased on master:

```diff
diff --git a/src/nvim/search.c b/src/nvim/search.c
index 9f18193fb..b64d641a9 100644
--- a/src/nvim/search.c
+++ b/src/nvim/search.c
@@ -4811,7 +4811,7 @@ the_end:
 /// There is not an explicit bonus for an exact match. Unmatched letters receive
 /// a penalty. So shorter strings and closer matches are worth more.
 typedef struct {
-  int idx;  // used for stable sort
+  int idx;  ///< used for stable sort
   listitem_T *item;
   int score;
   list_T *lmatchpos;
@@ -5177,6 +5177,7 @@ static void fuzzy_match_in_list(list_T *const items, char_u *const str, const bo
     list_T *l;
     if (retmatchpos) {
       const listitem_T *const li = tv_list_find(fmatchlist, 0);
+      assert(li != NULL && TV_LIST_ITEM_TV(li)->vval.v_list != NULL);
       l = TV_LIST_ITEM_TV(li)->vval.v_list;
     } else {
       l = fmatchlist;
@@ -5193,6 +5194,7 @@ static void fuzzy_match_in_list(list_T *const items, char_u *const str, const bo
     // next copy the list of matching positions
     if (retmatchpos) {
       const listitem_T *li = tv_list_find(fmatchlist, -2);
+      assert(li != NULL && TV_LIST_ITEM_TV(li)->vval.v_list != NULL);
       l = TV_LIST_ITEM_TV(li)->vval.v_list;
       for (i = 0; i < len; i++) {
         if (ptrs[i].score == SCORE_NONE) {
@@ -5203,6 +5205,7 @@ static void fuzzy_match_in_list(list_T *const items, char_u *const str, const bo
 
       // copy the matching scores
       li = tv_list_find(fmatchlist, -1);
+      assert(li != NULL && TV_LIST_ITEM_TV(li)->vval.v_list != NULL);
       l = TV_LIST_ITEM_TV(li)->vval.v_list;
       for (i = 0; i < len; i++) {
         if (ptrs[i].score == SCORE_NONE) {
@@ -5261,7 +5264,7 @@ static void do_fuzzymatch(const typval_T *const argvars, typval_T *const rettv,
   }
 
   // get the fuzzy matches
-  tv_list_alloc_ret(rettv, kListLenUnknown);
+  tv_list_alloc_ret(rettv, retmatchpos ? 3 : kListLenUnknown);
   if (retmatchpos) {
     // For matchfuzzypos(), a list with three items are returned. First
     // item is a list of matching strings, the second item is a list of
diff --git a/src/nvim/search.h b/src/nvim/search.h
index c7eb083d9..53059cc1e 100644
--- a/src/nvim/search.h
+++ b/src/nvim/search.h
@@ -55,7 +55,7 @@
 #define SEARCH_STAT_DEF_MAX_COUNT 99
 #define SEARCH_STAT_BUF_LEN 12
 
-// Maximum number of characters that can be fuzzy matched
+/// Maximum number of characters that can be fuzzy matched
 #define MAX_FUZZY_MATCHES 256
 
 /// Structure containing offset definition for the last search pattern
```

**Comment by seandewar** [comment]
Lol why did the windows checks cancel themselves? 😆

**Review by zeertzjq — APPROVED** [review]

**Pull request merged**
