### PR TITLE
win,option: fix runtimepath issue on Windows

### LINKED ISSUE #12793: Wrapping comment lines (reStructuredText) not working correctly in Neovim
- `nvim --version`: **NVIM v0.5.0-635-g8c49e3d50**
- `vim -u DEFAULTS` (version: ) behaves differently? **YES**
- Operating system/version: **Windows 10 x64**

NeoVim behaves differently with Vim. With https://github.com/gu-fan/riv.vim (reStructuredText plugin) installed, NeoVim does not wrap commented lines with `gwip` as expected. Vim in the same situation and same configuration wraps correctly.

The correct wrapping comes from RIV behaviour, standard `rst.vim` files do not provide this wrapping feature (tested — Vim without RIV does not wrap commented strings as expected, does not care about `comments=fb:..` in `ftplugin\rst.vim` and such).

### Partial solution

Delete `neovim\share\nvim\runtime\ftplugin\rst.vim`, `neovim\share\nvim\runtime\indent\rst.vim`, `neovim\share\nvim\runtime\syntax\rst.vim`.

I suppose this is some kind of loaded options priority error: Vim with standard `rst.vim` plugins loads RIV and works fine, Neovim loads RIV but some options are not set correctly, resulting in erroneous working.

### PR DESCRIPTION
**Pull request by erw7**
Fix a problem that `XDG_CONFIG_DIRS` and `XDG_DATA_DIRS` could not be handled correctly because the colon is used as a delimiter for environment variables on Windows.

- [x] Fix test.
- [x] Fix `stdpath()`

### CODE REVIEW

**Comment by jamessan** [comment]
> because the colon is used as a delimiter

s/colon/semicolon/

**Review by jamessan — APPROVED** [review]
Aside from the commit message, looks good.

**Comment by justinmk** [comment]
Nice find. We could enable these tests on windows perhaps, after updating them to use semicolon: https://github.com/neovim/neovim/blob/9bb552875d205d2f869c66137563f93b77a6d08e/test/functional/options/defaults_spec.lua#L293-L294

**Comment by justinmk** [comment]
Thanks @erw7 , this might fix some very old bugs. 

I squashed the commits since they all make sense as 1 commit, especially the test changes.

**Pull request merged**
