### PR TITLE
vim-patch:1d9215b9aaa1

### PR DESCRIPTION
**Pull request by supermarin**
Update runtime files.
https://github.com/vim/vim/commit/1d9215b9aaa120b9d78fee49488556f73007ce78

For the reference, this is a follow up on: https://github.com/neovim/neovim/pull/12067

### CODE REVIEW

**Comment by supermarin** [comment]
cc/ @h-michael

**Comment by supermarin** [comment]
Ping, any action needed from me?

**Comment by h-michael** [comment]
@supermarin Sorry for late reply.

The vim-patch PR must meet the following:

> The pull request title should include vim-patch:8.0.xxxx (no whitespace)

> The commit message should include:
>
>    A token indicating the Vim patch number, formatted as follows:
>    vim-patch:8.0.0123 (no whitespace)
>    A URL pointing to the Vim commit:
>        vim/vim/commit/c8020ee825b9d9196b1329c0e097424576fc9b3a
>    The original Vim commit message, including author

https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#pull-requests

**Comment by supermarin** [comment]
@h-michael thanks, wasn't sure if [RDY] was needed or not in the PR title and added it a few days ago. Removed it back to just `vim-patch:1d9215b9aaa1` and reordered commit message to have original ref first and the original commit message afterwards.

**Comment by supermarin** [comment]
@h-michael @marvim /ping

**Comment by h-michael** [comment]
@supermarin There are many "Update runtime" commits before this commit.
So I think that we should merge those patches at first before merge this for avoiding conflict.

```sh
~/g/s/g/h/neovim (master) > bash scripts/vim-patch.sh -l | grep "Update runtime"
  • 30e9b3c4256710781c3bd64efb33f138e4e074b3: Update runtime files
  • 8fe1000e9c3438d0ff36cf2340f0f0e48f8fb89f: Update runtime files
  • 5be4ceecea5520265066eac972460ebb1cdf05e7: Update runtime files.
  • 2e693a88b24dc6b12883fad78ff2cb9cd4469c98: Update runtime files.
  • 96f45c0b6fc9e9d404e6805593ed1e0e6795e470: Update runtime files
  • 1ff14ba24c4d85c008d7abe5e140dbb497ffea8d: Update runtime files.
  • 5ef1c6a4838a9629b793f3ae676f72a764171b00: Update runtime files
  • 574ee7bc1246070dba598f9561a2776aa1a10d07: Update runtime files
  • 09c6f265b21065ffa9437837b1d0955137175e45: Update runtime files.
  • 403f3eb4c1890826a5b3b5922c0e8e45be79a476: Update runtime files.
  • 0c0734d527a132edfb4089be48486586424b3f41: Update runtime files
  • 91359014b359cf816bf943fe2c7d492996263def: Update runtime files.
  • c08ee7476b19f9b4de5df287797af87c4e3fba0a: Update runtime files.
  • 95a9dd1efc5ae3221865f4970053a5708557e682: Update runtime files.
  • 5666fcd0bd794dd46813824cce63a38bcae63794: Update runtime files.
  • 2963456ff2b740244b3a064785fe681b1998d75e: Update runtime files.
  • 8024f936368336241406137a2fa78ed5ee9000a6: Update runtime files.
  • ade0d39468014fd55d30f7647a1ac104baff4bc5: Update runtime files.
  • 1d9215b9aaa120b9d78fee49488556f73007ce78: Update runtime files.
  • 560979ed4f0216f902a2c247e937f00a27dcb198: Update runtime files.
  • ebdf3c964a901fc00c9009689f7cfda478342c51: Update runtime files.
  • bc93cebb692f47488d66f078d1728031e9be35e7: Update runtime files.
  • eab6dff19f387469a200011bc6cf3508f5e43a4a: Update runtime files
  • b17893aa940dc7d45421f875f5d90855880aad27: Update runtime files
  • ff78155aa1755aced96a3b343e81939c94aac721: Update runtime files
  • 191acfdecabfbd2a74867e77004196fb3b4a8c14: Update runtime files
  • d1caa941d876181aae0ebebc6ea954045bf0da24: Update runtime files
  • 2c7f8c574f1f8723d59adca3fec8fb89c41cf8c9: Update runtime files
```

**Comment by supermarin** [comment]
@h-michael how would you prefer to go about this? can they all go in one PR or each needs to be separate?

**Comment by h-michael** [comment]
I think it's preferable to make PR one by one from the old one.

**Comment by supermarin** [comment]
@h-michael that's 27 PRs. I can open them only if you (or someone else) will commit to 1 day SLA for reviewing. If it takes another month per PR, it won't go anywhere.

**Comment by supermarin** [comment]
@h-michael just went down the road of applying the old patches one by one, and figured it'll take me way longer that someone who has more context on what's been deprecated, removed, etc in neovim vs vim8. There are conflicts in every single patch, mostly because neovim removed some features and moved things around.

Without merging this patch, Swift support is half-baked in (see https://github.com/neovim/neovim/pull/11747). Neovim knows about Swift files, but can't apply syntax coloring without the runtime files that are missing.

If there's a chance you can merge this as a one-off that'd be awesome, otherwise we can close this one.

**Comment by justinmk** [comment]
yeah, i'll try to merge the runtime stuff soon.

**Comment by supermarin** [comment]
Thanks @justinmk!

**Comment by supermarin** [comment]
@justinmk just checked, seems like this is still not merged. anything I can do about it to help?

**Pull request closed without merging**
