### PR TITLE
build(deps): bump tree-sitter-python to 0.20.4

### PR DESCRIPTION
**Pull request by SanchayanMaity**

### CODE REVIEW

**Comment by clason** [comment]
Do the queries need to be updated?

**Comment by SanchayanMaity** [comment]
> Do the queries need to be updated?

Works fine here with just this update. Was getting an error with highlight otherwise.

**Comment by clason** [comment]
That means something must have changed, since the bundled queries don't error with 0.20.3 (of course).

Please test with a clean config, without nvim-treesitter.

**Comment by lucario387** [comment]
For references, nvim-treesitter/nvim-treesitter#5256, nvim-treesitter/nvim-treesitter#5268

**Comment by SanchayanMaity** [comment]
> That means something must have changed, since the bundled queries don't error with 0.20.3 (of course).
> 
> Please test with a clean config, without nvim-treesitter.

Ya, you are right. I missed the update to nvim-treesitter. Without that it works fine. Also, referenced by lucario387.

What is the next step? Do I need to close this?

**Comment by lucario387** [comment]
> What is the next step? Do I need to close this?

Just port the queries from `nvim-treesitter` to here and it's okay

**Comment by clason** [comment]
Only port the change; the queries here are deliberately not identical to the ones in nvim-treesitter (especially the injections).

If you prefer, you can also close your PR and wait for the next round of scheduled parser bumps.

**Review by clason — APPROVED** [review]

**Pull request merged**
