### PR TITLE
[RFC] Minor improvement to inccomand substitution

### PR DESCRIPTION
**Pull request by KillTheMule**
As long as we're only previewing, we can stop looking for matches after we got enough lines for the preview buffer. Should improve performance on large files with a lot of matches.

Note: Could not check locally right now, but really wanted to create this PR to force myself to get it done, wanted to do it for a while :)

### CODE REVIEW

**Comment by bfredl** [comment]
Nice! Can the substitution be "resumed" somehow when we get around to implement scrolling in the preview window? Or maybe should just restart it...

**Comment by KillTheMule** [comment]
Hmm, dunno, the 'trick' here is to only compute what you really need to show. If you change what you need to show by scrolling, there's basically 2 options: 1) Precompute anything anyways (just as it is now) or 2) have some kind of callback when scrolling. For 2) you could compute the proper arguments to do_sub, but doing it on every scroll line... hrmm, sounds laggy. Maybe some kind of config options for the maximum number of lines shown?

The failure of https://github.com/neovim/neovim/blob/master/test/functional/ui/inccommand_spec.lua#L983 is expected, what should I do with that test? Make a bigger file?

**Comment by justinmk** [comment]
>The failure of https://github.com/neovim/neovim/blob/master/test/functional/ui/inccommand_spec.lua#L983 is expected, 

Ha! Maybe by searching for something that's very far down the file? Or join the lines to make a very long line--does your perf improvement help there?

**Comment by KillTheMule** [comment]
No, won't help with long lines. I'll try that :)

**Comment by KillTheMule** [comment]
Uhh that got weird. I tried slowing down the test, but now it errors out with 'invalid msg-rpc string'. Could someone have a look?

**Comment by KillTheMule** [comment]
Ok, I've put up a version that works for me locally, crossing my fingers :)

**Comment by justinmk** [comment]
Merged. Nice change @KillTheMule

**Pull request closed without merging**
