### PR TITLE
Fix helptags generation when prefix is not /usr

### PR DESCRIPTION
**Pull request by tanderson92**
full disclosure, this may not be completely correct -- I tried using CMAKE_INSTALL_DATAROOTDIR and CMAKE_INSTALL_DATAROOTDIR but they don't do what is intended.

### CODE REVIEW

**Comment by justinmk** [comment]
I don't see how this fixes anything... and it won't be good on windows.

**Comment by tanderson92** [comment]
Consider the following case when I am cross-compiling:

binaries go to /usr/x86_64-pc-linux/gnu/bin, but architecture-independent data should go to /usr/share. Perhaps you know better than I how to install things correctly in this situation, because autotools can handle this just fine.

**Comment by justinmk** [comment]
What was the result of `CMAKE_INSTALL_DATAROOTDIR `?

**Comment by tanderson92** [comment]
The result is that even when passing -DCMAKE_INSTALL_DATAROOTDIR=/usr/share/ -DCMAKE_INSTALL_FULL_DATAROOTDIR=/usr/share/  to cmake the ${CMAKE_INSTALL_FULL_DATAROOTDIR} variable is unset in GenerateHelptags.cmake, so the expansion does not work.

**Comment by justinmk** [comment]
I don't think we can make this change as you have proposed it. Hopefully CMAKE_INSTALL_DATAROOTDIR can be figured out. In the meantime you could use a local.mk... https://github.com/neovim/neovim/wiki/Building-Neovim#custom-makefile

**Comment by justinmk** [comment]
You could keep it open to discussion, if you want.

**Comment by tanderson92** [comment]
We're going to try to come up with a better solution; we were hoping you guys knew what cmake was doing and why it ignored user options.

**Comment by justinmk** [comment]
Right, @jszakmeister @equalsraf  @fwalch know more than I, so maybe give it a few days.

**Comment by equalsraf** [comment]
> ${CMAKE_INSTALL_FULL_DATAROOTDIR} variable is unset in GenerateHelptags.cmake

I had to `include(GNUInstallDirs)` in GenerateHelptags.cmake for the variable to be set. 

Initially I tried to change set CMAKE_INSTALL_PREFIX and CMAKE_INSTALL_FULL_DATAROOTDIR, but this did not work - it seems CMAKE_INSTALL_FULL_DATAROOTDIR must always be under CMAKE_INSTALL_PREFIX (or its just built from CMAKE_INSTALL_DATAROOTDIR?).

So instead try something like -DCMAKE_INSTALL_BINDIR=x86_64-pc-linux/gnu/bin. Or use a relative path for -DCMAKE_INSTALL_DATAROOTDIR=../../share

**Comment by tanderson92** [comment]
The problem is rather that the script GenerateHelptags.cmake is not run in the same environment as the configure step is, so the -D commands will have no effect. For a real fix, see my other pull request I made that is actually workable.

**Comment by equalsraf** [comment]
> The problem is rather that the script GenerateHelptags.cmake is not run in the same environment

True for external variables, but should be ok for some CMake vars like CMAKE_INSTALL_PREFIX. Setting CMAKE_INSTALL_DATAROOTDIR=../share/ causes the generated cmake_install.cmake to have these paths hardcoded, so for *this particular case* it works. 

ref #2741

**Comment by tanderson92** [comment]
Feel free to suggest another change that works.. ref #2741 is what the cmake developers recommended I do in this particular situation.

Keep in mind that I would like to be able to adjust CMAKE_INSTALL_DATAROOTDIR from the command line; will your method allow for that?

**Comment by equalsraf** [comment]
The only thing I did here was

```
cmake -DCMAKE_INSTALL_PREFIX=/home/raf/Code/neovim/TEST/prefix -DCMAKE_INSTALL_DATAROOTDIR=../share/ ..
```

**Comment by tanderson92** [comment]
I contend that the inability to pass absolute paths to a buildsystem is a sure sign of a broken build config.

**Comment by equalsraf** [comment]
> I contend that the inability to pass absolute paths to a buildsystem is a sure sign of a broken build config.

Good point :)

**Pull request closed without merging**
