### PR TITLE
ci: Travis: remove clang-tsan from allowed failures [skip appveyor]

### PR DESCRIPTION
**Pull request by blueyed**
While it still might be flaky sometimes, it is far better than the
osx jobs in general, and due to it being allowed to fail, we are not
getting aware of more recent (flaky) issues due to building tags during
make-install, which might indicate a more generic problem.

### CODE REVIEW

**Comment by blueyed** [comment]
It appears to be stable (as expected).
Good to go?

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
TSan is failing lately, with no visibility except `exit 1` AFAICT. Example: https://travis-ci.org/neovim/neovim/builds/571736381

**Comment by blueyed** [comment]
@justinmk 
Seems to happen here: https://github.com/neovim/neovim/blob/0c952c1c8b4eca74998d1cabbe798f3f7eaa5f03/ci/common/build.sh#L87-L88 (at least for https://api.travis-ci.org/v3/job/571840150/log.txt).
`asan_check` does nothing for TSan.

**Comment by blueyed** [comment]
I am seeing it with 5ad67af3c1884cd81a06986c4516c8a210bd7418 also:
```
==================
WARNING: ThreadSanitizer: data race (pid=30251)
  Write of size 4 at 0x558884012838 by main thread:
    #0 main /home/daniel/Vcs/neovim/build/../src/nvim/main.c:361:14 (nvim+0x400e79)

  Previous read of size 4 at 0x558884012838 by thread T1:
    #0 tui_grid_resize /home/daniel/Vcs/neovim/build/../src/nvim/tui/tui.c:891:23 (nvim+0x6cc29a)
    #1 ui_bridge_grid_resize_event /home/daniel/Vcs/neovim/build/src/nvim/auto/ui_events_bridge.generated.h:159:3 (nvim+0x6e78e1)
    #2 multiqueue_process_events /home/daniel/Vcs/neovim/build/../src/nvim/event/multiqueue.c:150:7 (nvim+0x2cda61)
    #3 loop_poll_events /home/daniel/Vcs/neovim/build/../src/nvim/event/loop.c:66:3 (nvim+0x2cbc68)
    #4 tui_main /home/daniel/Vcs/neovim/build/../src/nvim/tui/tui.c:423:12 (nvim+0x6cf7e0)
    #5 ui_thread_run /home/daniel/Vcs/neovim/build/../src/nvim/ui_bridge.c:102:3 (nvim+0x6e7417)

  Location is global 'starting' of size 4 at 0x558884012838 (nvim+0x00000089b838)

  Thread T1 (tid=30253, running) created by main thread at:
    #0 pthread_create <null> (nvim+0x101184)
    #1 uv_thread_create_ex <null> (libuv.so.1+0x1be18)
    #2 tui_start /home/daniel/Vcs/neovim/build/../src/nvim/tui/tui.c:170:10 (nvim+0x6cbe0d)
    #3 ui_builtin_start /home/daniel/Vcs/neovim/build/../src/nvim/ui.c:115:3 (nvim+0x6e1f05)
    #4 main /home/daniel/Vcs/neovim/build/../src/nvim/main.c:356:7 (nvim+0x400e33)

SUMMARY: ThreadSanitizer: data race /home/daniel/Vcs/neovim/build/../src/nvim/main.c:361:14 in main
==================
ThreadSanitizer: reported 1 warnings
```

**Pull request merged**
