### PR TITLE
vim-patch:8.1.{2029,2117,2214},8.2.3204

### LINKED ISSUE #7716: 'cursorline': highlight screen line instead of text line
- `nvim --version`: v0.2.3-99-g873af01
- Vim (version: ) behaves differently? no
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set cursorline

```

### Actual behaviour
Longer lines that wrap around the screen have the `cursorline` highlight applied to all screen lines instead of only the screenline the cursor is actually on.

### Expected behaviour
Since the primary benefit of `cursorline` is to help in locating the cursor in a buffer, and as far as I can tell, it serves no benefit to extend that past the current screen line to the remainder of the physical line.

In addition, `cursorcolumn` doesn't make sense outside the context of screen lines, and `cursorcolumn` and `cursorline` obviously go hand-in-hand and logic that applies to one should extend to the other.

### LINKED ISSUE #13356: Is cursorlineopt on the roadmap?
Just wondering if `cursorlineopt` will be added to Neovim anytime soon.
I just downloaded the head to see if it exists already, and no joy.
-Chris

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.1.2029: cannot control 'cursorline' highlighting well

Problem:    Cannot control 'cursorline' highlighting well.
Solution:   Add "screenline". (Christian Brabandt, closes vim/vim#4933)
https://github.com/vim/vim/commit/017ba07fa2cdc578245618717229444fd50c470d

#### vim-patch:8.1.2117: CursorLine highlight used while 'cursorline' is off

Problem:    CursorLine highlight used while 'cursorline' is off.
Solution:   Check 'cursorline' is set. (cloes vim/vim#5017)
https://github.com/vim/vim/commit/49474ca12236776bb56aeb9d39bd6592e28157c7

#### vim-patch:8.1.2214: too much is redrawn when 'cursorline' is set

Problem:    Too much is redrawn when 'cursorline' is set.
Solution:   Don't do a complete redraw.
https://github.com/vim/vim/commit/11a58af66fa5c442f0a22c5d59beabf187ed4e89

#### vim-patch:8.2.3204: display garbled when 'cursorline' is set and lines wrap

Problem:    Display garbled when 'cursorline' is set and lines wrap. (Gabriel
            Dupras)
Solution:   Avoid inserting lines twice.
https://github.com/vim/vim/commit/c9e7e344ed390d2a22afb88001b6aa80832d2541

Close #13356
Close #7716

### CODE REVIEW

**Comment by janlazo** [comment]
You skipped in-between patches like v8.1.2117.

**Comment by zeertzjq** [comment]
Oops, I didn't understand what that patch does at the first glance. I understand it now.

**Comment by zeertzjq** [comment]
It seems some tests need to be modified.

**Comment by zeertzjq** [comment]
`Test_cursorline_screenline()` is always skipped, and I just found some existing inconsistency regarding `cursorlineopt=screenline` (<https://github.com/vim/vim/pull/8684>). Maybe tests can be added after the inconsistency is resolved.

**Comment by janlazo** [comment]
Did you check patch v8.2.3204?

**Comment by zeertzjq** [comment]
I checked it, but I was not clear what problem it solves.

**Review by janlazo — APPROVED** [review]
LGTM. Not sure about the low priority attribute. Would be nice to have a lua screen test based on the Vim screendump test to test cursorlineopt.

**Pull request merged**
