### PR TITLE
docs(luaref): fix tag

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/26779

**Comment by clason** [comment]
You were too quick; CI failed like a Christmas tree on that.

**Comment by clason** [comment]
And now I cannot reopen...

**Comment by dundargoc** [comment]
Duplicate tags. Just fix on my PR

**Comment by clason** [comment]
Nah, this requires more changes.

**Pull request closed without merging**
