### PR TITLE
fix(clang: 'Logic error'): avoided dereferencing a null pointer

### PR DESCRIPTION
**Pull request by carlosguealv**

### CODE REVIEW

**Comment by clason** [comment]
Please do not merge `master` into a PR branch; you should instead `git rebase master`.

**Comment by carlosguealv** [comment]
@clason, how can I git rebase master? Also, should I only work on src/nvim then?

**Comment by clason** [comment]
You should be working on a feature branch: fork the repo, clone, `git checkout -b mybranch`, make changes, then sync your fork -- easiest via the Github website -- pull and (with your branch checked out) `git rebase master`.

I think it's easiest in this case to start over. 

On the actual code, I defer to @bfredl and @dundargoc -- in general, I think it's a good idea to ask on https://matrix.to/#/#neovim-dev:matrix.org before going on a clang warning fixes spree ;)

**Comment by carlosguealv** [comment]
I will be closing this pull request and start working on something else, thank you for the information!

**Pull request closed without merging**
