### PR TITLE
ci(lintcommit): allow colon in commit message scope

### LINKED ISSUE #21464: Allow ex-commands such as `:grep` to be used as commit scope
Currently, the commit linter fails if an ex-command with ":" is used as a commit scope. For example

```
feat(:grep): read from pipe
```

will fail. This is because the commit linter naively assumes that a colon is only used to separate the commit type and scope from the rest of the message. In other words, it assumes that scopes can't have a colon in them.

### PR DESCRIPTION
**Pull request by crazymerlyn**
Close #21464

### CODE REVIEW

**Comment by dundargoc** [comment]
`fix` is for user-facing bugs. This should be `build(lintcommit):` or `ci(lintcommit):`.

**Comment by crazymerlyn** [comment]
Updated the commit message

**Comment by justinmk** [comment]
`M._test()` has test cases, please add a test case there. 

Top of the file mentions how to run the tests.

**Comment by crazymerlyn** [comment]
Added a test case and simplified the implementation

**Comment by dundargoc** [comment]
@justinmk I couldn't run the tests by following the top level commands on master. Has something changed or am I holding it wrong?

**Comment by justinmk** [comment]
> couldn't run the tests by following the top level commands on master. Has something changed or am I holding it wrong?

Works for me. Make sure you start from the top-level directory, since the require() path depends on that.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
