### PR TITLE
fix(treesitter): `language.add` - only register parser if it exists

### LINKED ISSUE #24531: treesitter: language.add() overrides existing ft_to_lang mapping (typescriptreact=tsx)
### Problem

`nvim-treesitter` will register `tsx` lang for `typescriptreact` filetype, see https://github.com/nvim-treesitter/nvim-treesitter/blob/4c4d586a05e236d8199ab6faab8cb733a9b5bd24/lua/nvim-treesitter/parsers.lua#L1588

all `nvim-treesitter`'s plugins depend on this to work properly, otherwise issues like this will happen: https://github.com/nvim-treesitter/nvim-treesitter/issues/5146

Here is how this issue triggered:

1. `nvim-treesitter` is loaded, and register `tsx` lang for filetype `typescriptreact`.
2. on buffer of typescriptreact file, some plugin called `vim.treesitter.start(bufnr, vim.bo.filetype)` which is equal to `vim.treesitter.start(123, 'typescriptreact')`. Like `mini.files` did in this: https://github.com/echasnovski/mini.nvim/blob/ddb435633319d06a466c74833ef340839b931bfe/lua/mini/files.lua#L1948
3. following call stack will override `vim.treesitter.language#ft_to_lang`: [`LanguageTree.new`](https://github.com/neovim/neovim/blob/d086bc1e8590a92a70c414bd60e1e988bbdd3c0a/runtime/lua/vim/treesitter/languagetree.lua#L109) -> [language#add](https://github.com/neovim/neovim/blob/d086bc1e8590a92a70c414bd60e1e988bbdd3c0a/runtime/lua/vim/treesitter/language.lua#L85).

Because `LanguageTree.new` just called `language.add(lang)` which is `language.add("typescriptreact")`, and `language` module doesn't check that `ft_to_lang` already has a key named `typescriptreact` and a value `tsx`, it just override it.

here are some stacktrace log to prove it:

```txt
stack traceback:
^I/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:133: in function 'get_parser'
^I/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:462: in function </usr/local/share/nvim/runtime/lua/vim/treesitter.lua:460>
^I[C]: in function 'pcall'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1948: in function 'update_fun'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1872: in function 'buffer_update'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1666: in function 'view_ensure_proper'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1445: in function 'explorer_refresh_depth_window'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1253: in function 'explorer_refresh'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:688: in function 'open'
^I/private/tmp/init.lua:40: in function </private/tmp/init.lua:37>
tsx-----
stack traceback:
^I/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:133: in function 'get_parser'
^I/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:462: in function </usr/local/share/nvim/runtime/lua/vim/treesitter.lua:460>
^I[C]: in function 'pcall'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1948: in function 'update_fun'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1872: in function 'buffer_update'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1666: in function 'view_ensure_proper'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1445: in function 'explorer_refresh_depth_window'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1253: in function 'explorer_refresh'
^I/private/tmp/.repro/plugins/mini.files/lua/mini/files.lua:1741: in function ''
^Ivim/_editor.lua: in function <vim/_editor.lua:0>
typescriptreact-----
```

You can see first `tsx----` already there.

The debug code in vim.treesitter.language.lua

```
function M.register(lang, filetype)
  vim.validate({
    lang = { lang, 'string' },
    filetype = { filetype, { 'string', 'table' } },
  })

  for _, f in ipairs(ensure_list(filetype)) do
    if f ~= '' then
      if ft_to_lang[f] ~= nil then
        print(ft_to_lang[f] .. '-----')
      end
```

### Steps to reproduce

run `nvim --version`:

```
NVIM v0.10.0-dev-745+g20bfdbe83
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

minimal init.lua config file to repro, plugin required `mini.files`.

```lua
vim.g.mapleader = ' '
-- vim.loader.disable()
vim.opt.swapfile = false

local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { 'nvim-lua/plenary.nvim' },
  { 'stevearc/dressing.nvim', opts = {} },
  {
    "echasnovski/mini.files",
    commit = "2b3e9d27434273367e26f3",
    lazy = true,
    keys = {
      {
        "-",
        function()
          local path = nil
          path = vim.api.nvim_buf_get_name(0)
          require("mini.files").open(path, true)
        end,
        desc = "Open mini.files (directory of current file)",
      },
    },
    enabled = true,
    opts = {
      windows = {
        preview = true,
        width_nofocus = 30,
        width_preview = 60,
      },
      options = {
        -- Whether to use for editing directories
        -- Disabled by default in LazyVim because neo-tree is used for that
        use_as_default_explorer = true,
      },
      mappings = {
        go_in_plus = '<CR>',
      }
    },
  },
  {
    'nvim-treesitter/nvim-treesitter',
    commit = "82c948653909d8c1582f283",
    build = function()
      if #vim.api.nvim_list_uis() == 0 then
        -- update sync if running headless
        vim.cmd.TSUpdateSync()
      else
        -- otherwise update async
        vim.cmd.TSUpdate()
      end
    end,
    lazy = true,
    event = { 'BufRead', 'BufNewFile' },
    -- event = 'VeryLazy',
    keys = {
      -- { "<Enter>",    desc = "Init Increment selection" },
      -- { "<Enter>",    desc = "node node incremental selection",      mode = "x" },
      { "<BS>",       desc = "Decrement selection",                  mode = "x" },
      { '<leader>cr', desc = 'Smart rename/nvim-treesitter-refactor' },
    },
    dependencies = {
      'yioneko/nvim-yati',
    },
    init = function()
      vim.opt.smartindent = false
    end,
    config = function()
      require('nvim-treesitter.install').prefer_git = true
      require('nvim-treesitter.configs').setup({
        -- parser_install_dir = parser_install_dir,
        ensure_installed = { 'typescript', 'tsx', 'javascript' }, -- one of "all", or a list of languages
        sync_install = true,                                      -- install languages synchronously (only applied to `ensure_installed`)
        auto_install = true,
        ignore_install = {},                                      -- list of parsers to ignore installing
        yati = {
          -- https://github.com/yioneko/nvim-yati
          enable = true,
          disable = false,
          default_lazy = true,
          default_fallback = 'auto',
          -- if ts.indent is truee, use below to suppress conflict warns.
          suppress_conflict_warning = true,
        },
      })

      vim.cmd('do User TreesitterLoaded')
    end,
  },
  -- add any other pugins here
}

require('lazy').setup({
  spec = plugins,
  root = root .. '/plugins',
  defaults = {
    lazy = false,
  },
  state = root .. '/lazy/state.json',
  performance = {
    cache = {
      enabled = false,
    }
  }
})

-- add anything else here
vim.opt.termguicolors = true
vim.cmd([[colorscheme default]])
```

## steps to trigger this

1. put `init.lua` in `/tmp`
2. `nvim -u init.lua`, wait for the lazy to setup, quit nvim if needed.
3. just open a `.tsx` file to let nvim-treesitter download the all the parsers. (tsx etc)
4. after all above steps is done, quit nvim.
5. create `a.tsx`, `b.tsx`, files.
6. run `nvim -u init.lua`, press `-` to open `mini.files`, move cursor and press `<enter>` to open `a.tsx`.
7. press `-` again to open `mini.files`, move cursor and press `<enter>` to open `b.tsx`.
8. press `-` again to open `a.tsx`.
9. try to write some code, or press `o` to enter an new line to trigger `nvim-yati` treesitter based indent plugin.
10. some errors will show.

### Expected behavior

Since `nvim-treesitter` already register `tsx` lang to `vim.treesitter.language#ft_to_lang`, does vim have to override it ?

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

xterm-256

### Installation

build from repo

### PR DESCRIPTION
**Pull request by llllvvuu**
Fixes: #24531

### CODE REVIEW

**Review by lewis6991 — APPROVED** [review]

**Comment by llllvvuu** [comment]
> In fact, I would like to see a bit more of a refactor here that separates checking, adding, and registering parsers and languages, removing the need for kludges like
> https://github.com/neovim/neovim/blob/a49924a318520a3b5c2f210f22a8d450165e89b5/runtime/lua/vim/treesitter/languagetree.lua#L726-L732
> 
> (Not necessarily in this PR.)

That function body looks fine actually; even with `treesitter.load()`, it's not D.R.Y.-able since it doesn't tell you whether the parser needs to be read from disk. We could probably bring back #25146 and also move your function into `language.lua` if there's interest (you'll have to campaign vs https://github.com/neovim/neovim/pull/25146#issuecomment-1718881609;  I have no horse in the race)

**Comment by lucario387** [comment]
@clason Can this be backported to 0.9? I think fixing unwanted behaviors with register is good for stable users

**Comment by llllvvuu** [comment]
IDK if it's too late for the bot, but if you want a backport I opened one: https://github.com/neovim/neovim/pull/25165

**Comment by lucario387** [comment]
#25143 can't be backported, that's for sure

**Comment by clason** [comment]
> IDK if it's too late for the bot

It's not; you can slap the `backport` label on merged PRs. The bot doesn't like squash-merges, though.

**Pull request merged**
