### PR TITLE
Bump Vim version to 8.0 and applied patches

### PR DESCRIPTION
**Pull request by jamessan**
I'll update this periodically as more patches get applied.  If people
want to do scans for NA patches, post a comment and I'll maintain a
separate commit for those.

### CODE REVIEW

**Comment by Shougo** [comment]
From my NA lists:

0005: test_Netbeans
0006: ex_cmds.h
0007: documentation for Vim8
0009: Appveyor
0010: Crypt
0011: Flaky tests
0012: libcall
0013: Flaky tests
0014: test_crypt
0015: ch_status
0016: ch_status
0018: channel
0021: GUI
0022: channel
0024: channel
0027: channel
0028: timer
0029: Windows
0030: mouse support
0036: channel
0038: OPEN_CHR_FILES
0039: viminfo
0045: channel
0048: job
0050: job
0051: job
0054: job
0059: Make_VMS
0061: ifdef
0065: ifdef
0067: VMS
0070: Make_MinGW
0071: job
0072: Windows
0076: channel
0077: Travis
0080: Travis
0082: configure
0087: channel
0089: GTK 3.22.2
0093: Makefile
0094: Win32
0095: GUI GTK
0097: channel
0098: channel in Windows
0103: channel
0105: channel
0107: channel
0108: channel
0113: Windows
0114: Windows
0115: Make_Cygwin
0117: Makefile
0120: channel
0122: channel
0123: SUN_SYSTEM
0129: Makefile
0130: configure

**Comment by Shougo** [comment]
From my NA lists:

0138: small build
0141: Appveyor
0142: termguicolors
0144: GVimExt
0145: test in Windows
0146: termguicolors
0152: test_channel
0161: small
0162: GUI GTK
0163: if_ruby
0166: channel, JSON
0169: JSON
0170: JSON
0171: js_decode()
0173: EBICTIC
0174: locale in Windows
0175: iconv in Windows
0180: JSON
0183: channel
0187: if_ruby
0191: if_ruby
0192: if_cscope
0193: ifdef
0199: ifdef
0211: FEAT_MULTIBYTE
0213: Netbeans
0216: JSON
0217: if_cscope ifdef
0221: ifdef
0228: bracketed paste
0230: bracketed paste
0231: bracketed paste
0238: bracketed paste
0239: Travis CI
0240: Travis CI
0241: mch_memmove()
0245: Makefile
0246: mch_memmove()
0248: vim_strcat()
0249: Travis CI
0260: ifdef

**Comment by jamessan** [comment]
I've reviewed most of the patches up through 8.0.0300.  Some of the patches (especially the bracketed paste ones) I haven't marked NA because they should be reviewed more closely to see whether there are relevant changes to our functionality that we should make.

This is about all I'll do for now (in bulk), so once our last few 7.4 patches are merged I'll merge this PR.  I might squeeze in a change to vim-patch.sh to adjust the commit messages it generates, but that could also be done separately.

**Comment by Shougo** [comment]
The next review is under 8.0.600?

**Comment by justinmk** [comment]
+1

**Comment by blueyed** [comment]
Thanks for this.

However, there is some behavior change with regard to dumping objects with a self reference: https://github.com/neomake/neomake/pull/1460/files.

To be really Vim 8.0 compatible this should get addressed maybe?

**Comment by jamessan** [comment]
The change in the PR (included below for context) is the right way to handle this.  When nvim doesn't support something that you're checking by version, not feature, then you should handle nvim first.

```diff
--- a/tests/utils.vader
+++ b/tests/utils.vader
@@ -590,10 +590,10 @@ Execute (neomake#utils#fix_self_ref):
   catch /^Vim(let):E724:/
     let exception = v:exception
   endtry
-  if has('patch-7.4.1644')
-    AssertEqual str_obj, "{'foo': 1, 'bar': {'self_ref': {...}}}"
-  elseif has('nvim')
+  if has('nvim')
     AssertEqual exception, 'Vim(let):E724: unable to correctly dump variable with self-referencing container'
+  elseif has('patch-7.4.1644')
+    AssertEqual str_obj, "{'foo': 1, 'bar': {'self_ref': {...}}}"
   else
     AssertEqual exception, 'Vim(let):E724: variable nested too deep for displaying'
   endif
```

The behavior you're seeing is intentional, as I understand it (@ZyX-I can confirm).

**Pull request merged**
