### PR TITLE
fix(filetype): make sure buffer is valid before call nvim_buf_call

### PR DESCRIPTION
**Pull request by hiberabyss**
In some cases, there may be following error:

image

### CODE REVIEW

**Comment by hiberabyss** [comment]
The failed CI seems have nothing to do with the PR.

**Comment by gpanders** [comment]
Why would the buffer id be invalid in a BufNewFile autocommand? This seems like a bug somewhere else that should be fixed instead of just burying it.

Can you provide a reproduction case for the error you provided?

**Comment by hiberabyss** [comment]
> So it deletes the `file:30` buffer and reopens a new buffer `file` at line `30`.

The behavior make sense since buffer `file` at line `30` is the actual need.

Seems there is reasonable scene which may cause invalid buffer id.

**Comment by lewis6991** [comment]
I'm trying to see if fileline can reuse the buffer, but I'm not sure if it's possible.

**Comment by gpanders** [comment]
>If we decide that deleting buffers in BufNewFile should not be supported, then we enforce this internally and raise an error. Otherwise, I think this PR is ok.

Yea, I think ideally if a buffer is deleted or becomes invalid in one autocommand then later autocommands shouldn't fire at all.

**Review by gpanders — APPROVED** [review]

**Pull request merged**
