### PR TITLE
Fixed +1-1 in util.lua

### PR DESCRIPTION
**Pull request by jimman2003**
No point in adding and then subtracting I believe ;)

### CODE REVIEW

**Comment by mjlbach** [comment]
would be nice to have a test.

**Comment by jimman2003** [comment]
Let me figure this out :)...

**Comment by mjlbach** [comment]
(It was a joke just to clarify 😆 )

**Comment by jimman2003** [comment]
oh ok!..

**Comment by janlazo** [comment]
Was it suppose to be `i + 1`? Hard to believe it was merged in, joke or not.

**Comment by mjlbach** [comment]
I missed this during review, it was my mistake.

**Pull request merged**
