### PR TITLE
[RFC] deps: Don't pin deps, update busted: 2.0 rc8 -> rc10

### PR DESCRIPTION
**Pull request by ghost**
This [removes the dependency on ansicolors](https://github.com/Olivine-Labs/busted/pull/373):

[See this link](https://github.com/Olivine-Labs/busted/compare/v2.0.rc8-0...a6233a277da4e118f663606d54da8df88a27c076) for a changelog between the two versions.

### CODE REVIEW

**Comment by fwalch** [comment]
> This removes the dependency on ansicolors

Speaking of dependencies, the rest of them should probably be checked against the current versions that busted uses (https://github.com/Olivine-Labs/busted/blob/v2.0.rc10-0/busted-2.0.rc10-0.rockspec#L20-L30). E.g. we install luassert 1.7.6, but busted requires at least 1.7.8 according to their rockspec.

**Comment by Pyrohh** [comment]
> E.g. we install luassert 1.7.6, but busted requires at least 1.7.8 according to their rockspec.

Speaking of that, why do we explicitly install them? Why not just let luarocks handle the dependencies?

**Comment by fwalch** [comment]
@Pyrohh Found https://github.com/equalsraf/neovim/commit/585e5d32a3402bffa971ae8124fc64004ab92e61, hope that answers your question.

**Comment by Pyrohh** [comment]
@fwalch Thanks for finding that, although I wonder if that's still needed.

**Comment by Pyrohh** [comment]
@fwalch I pushed a (test) commit which removes our bundled deps, not sure what you think.

**Comment by Pyrohh** [comment]
Everything passed... nice.

**Comment by Pyrohh** [comment]
I cleaned up this PR and set it to RFC.

**Comment by justinmk** [comment]
@tarruda  is this OK with you?

**Comment by justinmk** [comment]
@Pyrohh Feel free to merge this (reminder to remove TEMPORARY commit). If we want to go back to manually managing busted's deps we can always revert that specific commit.

**Comment by justinmk** [comment]
@Pyrohh Actually I'll merge this now so that I can close #3031

**Comment by justinmk** [comment]
Merged

**Comment by Pyrohh** [comment]
Thanks @justinmk.

**Comment by tarruda** [comment]
> Speaking of that, why do we explicitly install them? Why not just let luarocks handle the dependencies?

The answer lies in @585e5d32a3402bffa9 description:

> busted depends on a number of libraries that sometimes introduce crashing bugs.
The new custom target makes sure only stable versions of those dependencies are
installed.

In other words, I pinned the dependencies because they sometimes are updated in a non-backwards compatible way breaking the whole installation. Take for example busted 2.0 rc10, which [depends](https://github.com/Olivine-Labs/busted/blob/1bb62381c3d7386d6b7790319387969cfbaa73a2/busted-2.0.rc10-0.rockspec#L22) on cliargs >= 2.5.0: Even if we never change our dependency on busted version 2.0rc10, there's still a possibility the installation will break, simply because nothing in the rockspec binds cliargs API to a version that is compatible to the one busted 2.0 rc10 uses. So if a new version is released, 3.0 for example, and it has a breaking API change, all new installations of busted will be broken. 

Even if luarocks provided a way to place an upper limit on the version(maybe it does) and busted limited the cliargs version to 2.*(which should be compatible if cliargs authors follow the rules of semantic  versioning), there's still the possibility that another busted dependency can depend on a different/incompatible version of cliargs(or any direct busted dependency), which is another type of dependency hell that would break installation.

AFAIK this is a limitation of luarocks module system and there's little we can do except pin all packages to versions that are known to work. The only way a package manager can prevent this kind of havoc is by having a node.js-like module system, where multiple versions of the same package can exist in the same process, resulting in a fully compatible dependency graph.

So, unless we are ok with the possibility of the luarocks step eventually breaking our build, we must pin all package versions.

**Comment by justinmk** [comment]
@tarruda Good explanation, thanks.

**Pull request closed without merging**
