### PR TITLE
Update bug_report.yml

### PR DESCRIPTION
**Pull request by xeruf**
Some wordings tripped me off when reporting a bug

### CODE REVIEW

**Comment by zeertzjq** [comment]
IMO you made things more confusing.

**Comment by clason** [comment]
Yes, I have to agree -- that is not really an improvement: 
1. "parity" is unusual in this context and may be unknown to non-native English speakers
2. the separation of platform and installation method is intentional; depending on the issue, one or the other is much more important, and having them separate (and mandatory) makes it much less likely that either is missing.

**Comment by zeertzjq** [comment]
Replacing the slash in `Operating system/version` with a space indeed makes sense though.

**Comment by clason** [comment]
> Replacing the slash in `Operating system/version` with a space indeed makes sense though.

"Operating system and version" would be even better.

**Review by f1nn1711 — APPROVED** [review]

**Comment by xeruf** [comment]
> Vim (not Nvim) behaves the same?

This is not even a correct English sentence.

And when I am on Arch, the installation method is obvious. Having too many mandatory fields could ward off valuable reports.

**Comment by zeertzjq** [comment]
> And when I am on Arch, the installation method is obvious.

What do you mean? There are many installation methods on Arch. I have used at least four.

**Comment by xeruf** [comment]
For a package in the official repos, that will be used unless specified otherwise. It is about sensible defaults.

**Comment by clason** [comment]
No, it's about important information and clear communication.

**Pull request closed without merging**
