### PR TITLE
chore(clang): Fix 'Dead nested assignment' warning.

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by justinmk** [comment]
Are we maintaining the `xdiff/` module? That is a third-party thing.

**Comment by dundargoc** [comment]
> Are we maintaining the `xdiff/` module? That is a third-party thing.

I suspected as much. Should I try to patch it upstreams?

**Comment by justinmk** [comment]
> I suspected as much. Should I try to patch it upstreams?

Maybe, though they might have a different lint policy/conventions. We should probably ignore xdiff/ in our analysis, treat it like any other third-party dep.

**Comment by dundargoc** [comment]
I've tried to make scan-build ignore xdiff locally with the --exclude flag to no avail. I tested over 10 different paths (xdiff, xdiff/\*, src/nvimxdiff, \*\*/xdiff, nvim/xdiff etc., including the absolute path) and none of them worked. I read up on the documentation and searched online but came up short. I've either missed something cruical or the exclude flag straight up does not work as it's supposed to.

I haven't checked up on how bot-ci is built up, is there a way to exclude some warnings from showing up on the report?

**Comment by justinmk** [comment]
worst case we could filter out the lines in the generated report... https://github.com/neovim/doc/blob/ca8b2feb5515c9efa17dc7125a0930773ed7b62f/ci/clang-report.sh#L52

**Comment by dundargoc** [comment]
Shoot me. I just realized --exclude only excludes the error from showing up on the report. The warning will still show up on the terminal like usual. I guess we can close this issue and I can make a PR to the bot-ci repo?

**Pull request closed without merging**
