### PR TITLE
fix(terminal): fix resize crash with pending scrollback

### LINKED ISSUE #14887: Changing `set number` before calling `nvim_open_term` crashes Neovim
- `nvim --version`: 
```
$ nvim --version
NVIM v0.5.0-dev+1420-gc78816eb6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/cam/projects/neovim/build/config -I/home/cam/projects/neovim/src -I/home/cam/projects/neovim/.deps/usr/include -I/usr/include -I/home/cam/projects/neovim/build/src/nvim/auto -I/home/cam/projects/neovim/build/include
Compiled by root@cam-thinkpad

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```
- Operating system/version: Ubuntu 20.04
- Terminal name/version: GNOME terminal
- `$TERM`: xterm-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`
A strange interaction between the `number` option and `nvim_open_term` causes Neovim to crash when the buffer used in `nvim_open_term` is not active in the window.

```
:set number

# Paste into buffer and run with :luafile %
local buf_id = vim.api.nvim_create_buf(true, true)
vim.api.nvim_win_set_option(0, "number", false)
local chan_id = vim.api.nvim_open_term(buf_id, {})
local line = "a"
local lines = {}
for i=0,80,1 do
   table.insert(lines, line)
end
vim.fn.chansend(chan_id, lines)
vim.api.nvim_win_set_buf(0, buf_id)
```

### Actual behaviour
Neovim crashes with error:
```
E317: pointer block id wrong
```

### Expected behaviour
No crash.

### PR DESCRIPTION
**Pull request by seandewar**
`refresh_scrollback` assumes pending scrollback rows exist only if the
terminal window height decreased (or the screen was full).
    
However, after accumulating scrollback, it's possible in some cases for
the terminal height to increase before `refresh_scrollback` is called via
invalidation (especially when the terminal buffer isn't initially
displayed in a window before `nvim_open_term`), which may crash.
    
As we'll have enough room for some scrollback rows, just append them to
the top of the buffer until it fills the window, then continue with the
previous logic for any remaining scrollback rows if necessary.

---

Closes #14887?
Seems to fix the issue, but I'm not sure if this is the best approach.

The mechanism for the crash was:

1. Buffer created for the terminal isn't initially displayed in a window before it's given to `nvim_open_term`, so the size is misconfigured.
  _`:h nvim_open_term` recommends showing the buffer in a properly configured window first._
2. `terminal_check_size` sets a small terminal height (5 rows from the dummy window used by `aucmd_prepbuf` in `terminal_open`).
3. `number` is changed, but the redraw logic in `win_update` (which also calls `terminal_check_size`) won't run until the next normal mode iteration.
  _Seems that `foldcolumn` and `signcolumn` are redrawn differently, and don't call `terminal_check_size` when modified? 🤔_
4. Lines are fed to the terminal, invalidating it. Due to its small size, there are pending scrollback lines.
5. Terminal buffer is now displayed in the current window (it presumably has more than 5 rows 😄).
6. The normal mode iteration occurs after the script has run.
7. Redraw logic from changing `number` runs. It calls `terminal_check_size`, which sets the height of the terminal to that of the current window.
8. Terminal `refresh_timer_cb` fires soon. `refresh_scrollback` is called too late, as the terminal height increased before refreshing the pending scrollback.
9. Because there's pending scrollback, `refresh_scrollback` assumes the buffer has more rows than the terminal's height. Memline row indexing breaks. Crash.

### CODE REVIEW

**Comment by seandewar** [comment]
Updated to include the case in https://github.com/neovim/neovim/issues/14887#issuecomment-968196737 but idk how ideal this fix is as I'm unfamiliar with a lot of the terminal stuff

**Review by gpanders — APPROVED** [review]

**Comment by gpanders** [comment]
@zeertzjq You've spent a lot of time with the terminal emulator recently, do you want to take a look?

**Comment by eyalk11** [comment]
https://github.com/neovim/neovim/issues/16458 related?

**Comment by zeertzjq** [comment]
> #16458 related?

Most likely not.

**Review by zeertzjq — APPROVED** [review]

**Pull request merged**
