### PR TITLE
feat(lsp): option to offset color column

### PR DESCRIPTION
**Pull request by vantaboard**
Utilizing virtual text, color columns can be generated alongside inlay hints.

Before:
Peek 2023-06-21 04-19

After:
Peek 2023-06-21 04-18

### CODE REVIEW

**Comment by clason** [comment]
No comment on the contents, but we do NOT do gitmoji. If you'd like your contribution to be taken seriously, please drop them. We _do_ use conventional commits though, so these are required.

**Comment by justinmk** [comment]
Thanks for the clear demo. 

This is a lot of code for a rather special case. Why should it be optional? Should virtual text handle this by itself, rather than special-casing this in the LSP layer?

**Comment by luukvbaal** [comment]
This is a very roundabout to go about fixing this problem. I think it should be handled in `drawline.c`, this seems to work:
```diff
+++ b/src/nvim/drawline.c
@@ -899,6 +899,7 @@ static void handle_inline_virtual_text(win_T *wp, winlinevars_T *wlv, ptrdiff_t
       VirtTextChunk vtc = kv_A(wlv->virt_inline, wlv->virt_inline_i);
       wlv->p_extra = vtc.text;
       wlv->n_extra = (int)strlen(wlv->p_extra);
+      wlv->vcol_off += wlv->n_extra;
       wlv->extra_for_extmark = true;
       wlv->c_extra = NUL;
       wlv->c_final = NUL;
```

**Comment by luukvbaal** [comment]
Yeah the above breaks the following test: `test/functional/ui/decorations_spec.lua @ 1900: decorations: inline virtual text cursor position is correct with virtual text attached to hard tabs`.
Different solution is necessary but the point is that it should be handled by `drawline.c` directly, not through virtual text.

**Comment by luukvbaal** [comment]
This works, not sure if it can be done without adding an extra field to store the virtual text offset in the current line.
```diff
+++ b/src/nvim/drawline.c
@@ -82,6 +82,7 @@ typedef struct {
   int col;                   ///< visual column on screen, after wrapping
   int boguscols;             ///< nonexistent columns added to "col" to force wrapping
   int vcol_off;              ///< offset for concealed characters
+  int virt_text_off;         ///< offset for inline virtual text

   int off;                   ///< offset relative start of line

@@ -899,6 +900,7 @@ static void handle_inline_virtual_text(win_T *wp, winlinevars_T *wlv, ptrdiff_t
       VirtTextChunk vtc = kv_A(wlv->virt_inline, wlv->virt_inline_i);
       wlv->p_extra = vtc.text;
       wlv->n_extra = (int)strlen(wlv->p_extra);
+      wlv->virt_text_off += wlv->n_extra;
       wlv->extra_for_extmark = true;
       wlv->c_extra = NUL;
       wlv->c_final = NUL;
@@ -913,6 +915,7 @@ static void handle_inline_virtual_text(win_T *wp, winlinevars_T *wlv, ptrdiff_t
         if (virt_text_len > wlv->skip_cells) {
           int len = mb_charlen2bytelen(wlv->p_extra, wlv->skip_cells);
           wlv->n_extra -= len;
+          wlv->virt_text_off -= len;
           wlv->p_extra += len;
           wlv->n_attr -= wlv->skip_cells;
           // Skipped cells needed to be accounted for in vcol.
@@ -1139,7 +1142,7 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool number_onl
   bool is_concealing  = false;
   int did_wcol        = false;
   int old_boguscols = 0;
-#define VCOL_HLC (wlv.vcol - wlv.vcol_off)
+#define VCOL_HLC (wlv.vcol - wlv.vcol_off - wlv.virt_text_off)
 #define FIX_FOR_BOGUSCOLS \
   { \
     wlv.n_extra += wlv.vcol_off; \
```

**Comment by clason** [comment]
@luukvbaal nice, can you make a PR so we can see what CI (and @bfredl) thinks?

**Comment by clason** [comment]
Closing in favor of #24090.

**Comment by vantaboard** [comment]
> Closing in favor of #24090.

Awesome! Thanks for the feedback! New PR looks awesome

**Comment by justinmk** [comment]
> Should virtual text handle this by itself, rather than special-casing this in the LSP layer?

Decided against, reasoning provided here: https://github.com/neovim/neovim/pull/24090#issuecomment-1605988426

**Pull request closed without merging**
