### PR TITLE
[RDY] Update Ukrainian translation

### PR DESCRIPTION
**Pull request by sakhnik**
Update Ukrainian translation in a trackable way.
Supposedly, few people are able to review Ukrainian here, so I'll put RDY if no formal comments.

### CODE REVIEW

**Comment by justinmk** [comment]
Looks like cleanup.vim was not used this time? In https://github.com/neovim/neovim/pull/5343 it seemed like we decided it should be used. Many lines were removed there, but now they're being added back here?

**Comment by sakhnik** [comment]
Right, I'm going to apply it now.

2016-11-07 5:50 GMT-05:00 Justin M. Keyes <notifications@github.com>:

**Comment by sakhnik** [comment]
Anyone?

**Comment by justinmk** [comment]
Looks good, thanks for the eval.c fix as well.

BTW I think we could remove the `*.cp1251.po` files, I'll do that in another PR.

**Pull request merged**
