### PR TITLE
fix: #12976

### PR DESCRIPTION
**Pull request by tjdevries**
When you stop insert, you gotta stop ins completion. It's that simple :)

### CODE REVIEW

**Comment by tjdevries** [comment]
Unit tests via video: https://clips.twitch.tv/SmallTardyAnteaterYee

We just need GPT-3 to confirm that we have found and fixed the problem.

**Comment by bfredl** [comment]
upstream https://github.com/vim/vim/issues/7013

**Comment by Happy-Dude** [comment]
Upstream patch: https://github.com/vim/vim/commit/d0e1b7103c14eb0d175c6b245b4b6ed93a204da9

**Comment by Happy-Dude** [comment]
Just to keep in-the-loop; there may be edge cases to the upstream patches. See https://github.com/vim/vim/issues/7035

**Comment by mrdgo** [comment]
Any plans on when this will be merged?

**Comment by zeertzjq** [comment]
No longer needed as #17102 was merged.

**Pull request closed without merging**
