### PR TITLE
Codecov: enable changes status

### PR DESCRIPTION
**Pull request by blueyed**
This helps to identify unexpected changes.

### CODE REVIEW

**Comment by justinmk** [comment]
Going to revert this for the moment, because it doesn't seem to be doing anything useful, and it fails PRs which otherwise would succeed. For example  https://github.com/neovim/neovim/pull/8971 failed, but the "codecov/changes" website doesn't even load (and I've tried in many other different PRs to load this webpage, never have seen it successfully load).

**Comment by blueyed** [comment]
@justinmk 
Codecov appears to be in trouble since a few days for me also.. /cc @stevepeak

Normally the codecov/changes status is a good indicator that e.g. some code is not covered anymore - but I see that it is not very useful when you cannot view it.

But anyway, it does not really fail a PR - admins can override statuses always, but it could/should not be a required status in the Github repo's settings maybe also.

**Comment by justinmk** [comment]
@blueyed on the codecov settings page in GitHub, I see this FAQ:

> How does pricing work? Only paid users can view reports and post statuses/comments.

> But anyway, it does not really fail a PR - admins can override statuses always, but it could/should not be a required status in the Github repo's settings maybe also.

Nothing is required, but I would like to avoid "red" PRs. We need more "green" PRs, there are too many false positives.

**Comment by blueyed** [comment]
> How does pricing work? Only paid users can view reports and post statuses/comments.

That would be something new/surprising.  Only affects private projects etc probably?!

Yay for green PRs! ;)

**Comment by blueyed** [comment]
FWIW codecov works in some repos for me still, e.g. https://codecov.io/gh/neomake/neomake/compare/28f6991f3546195e764052d5e1c731432ac8f706...a3cfc31ccfc54c7bf29a6f0eef9747740079373d/diff.

**Pull request merged**
