### PR TITLE
tui: enable NVIM_TUI_ENABLE_CURSOR_SHAPE by default

### PR DESCRIPTION
**Pull request by justinmk**
This is a temporary step until the [TUI respects 'guicursor'](https://github.com/neovim/neovim/issues/2583#issuecomment-272988384).

- `NVIM_TUI_ENABLE_CURSOR_SHAPE=0` disables cursor shape-changing.
- `NVIM_TUI_ENABLE_CURSOR_SHAPE=1` enables _non-blinking_ cursor with mode-specific shapes.
  - This is the default now.
- `NVIM_TUI_ENABLE_CURSOR_SHAPE=2` enables _blinking_ cursor with mode-specific shapes.

cc @leonerd

### CODE REVIEW

**Comment by leonerd** [comment]
I've been trying this out now, and it's not quite sufficient on its own. In default state for me, no value of `$NVIM_TUI_ENABLE_CURSOR_SHAPE` ever blinks.

I tracked down why. This is because my terminfo's `cursor_normal` string specifically turned off cursor blink:

    $ infocmp -1L | grep cursor_normal
            cursor_normal=\E[?12l\E[?25h,

Having now removed that with another update to my `fix-my-terminfo` script, I've removed the `CSI ? 12 l` from terminfo, at which point this patch now works as described.

I don't know what the longer-term approach to this problem should be. Should users be expected to further customise their terminfo - already downvoted around the Backspace/Delete/Ctrl-H issue. Should neovim be ignoring this value too?

**Comment by jamessan** [comment]
> This is because my terminfo's cursor_normal string specifically turned off cursor blink:

Ah, that's probably where nvim's value for the default cursor came from.  Our own [fix_terminfo] was already changed to tell unibilium to use `\e[?25h` for the [normal cursor], so I wonder why that's not helping here.

[fix_terminfo]: https://github.com/neovim/neovim/blob/25427ae892ccbb537a718c8abfbd4c79d9f94091/src/nvim/tui/tui.c#L820
[normal cursor]: https://github.com/neovim/neovim/blob/25427ae892ccbb537a718c8abfbd4c79d9f94091/src/nvim/tui/tui.c#L847

**Comment by leonerd** [comment]
You mean this line?

https://github.com/neovim/neovim/blob/25427ae892ccbb537a718c8abfbd4c79d9f94091/src/nvim/tui/tui.c#L847

A call to `unibi_set_if_empty()`. My string won't be empty though. It already had a value, just a different value.

**Comment by jamessan** [comment]
> A call to unibi_set_if_empty(). My string won't be empty though.

Ah, right, so maybe if it's set we should be checking the existing value for `\e[?12l` and remove that to actually fix it.

**Comment by leonerd** [comment]
> Ah, right, so maybe if it's set we should be checking the existing value for \e[?12l and remove that to actually fix it.

That's exactly what I do in `fix-my-terminfo` ;)

    my $cursor_normal = $terminfo_strs{cursor_normal};
    $cursor_normal =~ s/\e\[\?12[hl]//;

**Comment by Lourens-Rich** [comment]
Please, write about this changes in HEAD page on wiki. Becouse after release people to be creating many questions.

**Comment by KnownAsDon** [comment]
**I am sorry for opening this issue again** but I wanted to say that either I am doing something wrong or something or the steps have changed because tahis does not work for me in neovim version 0.2.2. I tried putting `set NVIM_TUI_ENABLE_CURSOR_SHAPE=0` or `let NVIM_TUI_ENABLE_CURSOR_SHAPE=0` in my init.vim file and neither of them is not working for me. Now I am kinda new to vim and neovim...been using them for only about a few months so if I am doing something wrong **I definetly could accept some tips** :).

**Comment by justinmk** [comment]
@KnownAsDon Sounds like you read an old blog post or outdated answer somewhere.  `NVIM_TUI_ENABLE_CURSOR_SHAPE` was removed long ago.  

For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.

**Pull request merged**
