### PR TITLE
API: nvim_exec: fix script-scope

### PR DESCRIPTION
**Pull request by justinmk**
- handle script-scope (`s:`, `<SID>`) variables and functions

TODO:

- Does `nvim_exec` need other options, e.g. the "silent" flag from
  `execute()`?
- If nvim_exec is done in a script, the "Last set by" field should not
  be "anonymous". Also for the traceback script name and line number.

Example:

    foo.vim:

        call nvim_exec('set wrap',v:true)

    :source foo.vim
    :verbose set wrap?

### CODE REVIEW

**Comment by bfredl** [comment]
> Does nvim_exec need other options, e.g. the "silent" flag from
execute()?

I guess we could make it a opts dict already, `nvim_exec("noisy command", {'output': v:true})` doesn't seem toe bad. And I was thinking about adding some kind of "name" param later to set the script name optionally.

**Comment by norcalli** [comment]
I think the name param makes sense. Anecdotally, when I tried to use `nvim_exec` and I got an error about a second param being needed (when I tried to guess the signature), I assumed that the second param was going to be a script name. So that might be a point in its favor. We'd still want to try to do a best effort name, though, as justin said.

**Comment by justinmk** [comment]
Definitely will add that. Going to see about fixing script-scope first.

**Comment by in42** [comment]
`eval.c` has many checks of the form `current_sctx.sc_sid > 0` whereas for `nvim_exec` has `sid = SID_STR` which is lesser than zero, so this error may be due to that. Also in the `do_source` implementation which is used in the `:source` command, a new script_item is created for the script file, which is not present in the `nvim_exec` implementation, so that could also be the source of the error.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/15994

**Pull request closed without merging**
