### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by blueyed** [comment]
#### DirChanged patches, originated in Neovim - not checked for details though

vim-patch:8.0.1459: cannot handle change of directory
vim-patch:8.0.1460: missing file in patch

**Comment by janlazo** [comment]
@blueyed https://github.com/neovim/neovim/issues/9909 is open so `DirChanged` patches are not N/A (yet).

**Comment by justinmk** [comment]
funny problem: since we're almost done with 8.0.x (awesome!), we need to wait until we have at least one 8.0.x patch before merging this PR, else @marvim won't have anything to push to the next PR...

**Comment by janlazo** [comment]
Enough patches to merge? I added a 8.0.x patch.

**Comment by janlazo** [comment]
Patches like 8.2.0337 that replace `snprintf` with `vim_snprintf` are N/A?

**Comment by justinmk** [comment]
> Patches like 8.2.0337 that replace `snprintf` with `vim_snprintf` are N/A?

Sure. I don't see why that would be needed.

**Pull request merged**
