### PR TITLE
fix(api): nvim_set_option_value for global-local options

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by clason** [comment]
Can we add a test for that? This (window global-local options) seems like something with a lot more coverage in our tests, given how counter-intuitive the whole thing is...

**Comment by lewis6991** [comment]
Totally! I had to leave my computer so I just threw this up as a draft quickly.

**Comment by lewis6991** [comment]
I put a full explanation in the commit message. Can people review this and double check it is correct.

**Comment by kevinhwang91** [comment]
Work for me. Without this patch, Lua ecosystem has been broken since https://github.com/neovim/neovim/commit/58d028f64bb0ddc80b6201906880182d14ad9a3c

**Pull request merged**
