### PR TITLE
[RFC] os_resolve_shortcut

### PR DESCRIPTION
**Pull request by justinmk**
@#810 is merged into this PR in order to test the changes.

Fixes https://github.com/neovim/neovim/issues/460

### CODE REVIEW

**Comment by justinmk** [comment]
This seems to be working to some degree. This prints the contents of the link target:

    nvim.exe --headless +"echo readfile(resolve(expand('~/Desktop/test.lnk',1)))" +"q"

@equalsraf I see some commits related to enabling functional tests, but I don't see test results in appveyor. But I'll go ahead and make a basic functional test for this.

**Comment by equalsraf** [comment]
@justinmk I'll be mostly away until next week. I tested this earlier, but kept running into this [assertion](https://github.com/neovim/neovim/blob/master/src/nvim/charset.c#L1734) but perhaps its unrelated.

> @equalsraf I see some commits related to enabling functional tests, but I don't see test results in appveyor.

The functional tests are not running in appveyor, they would end up blocking. There is also some problem with luv holding us (for now its disabled 7ccd8f288774b60908ff9869d48df3265f334661), but I'm waiting on https://github.com/neovim/neovim/pull/4771 before trying to fix it

**Comment by equalsraf** [comment]
Disregard my previous comment its working now.

**Comment by justinmk** [comment]
Tested the mingw64 artifact from https://github.com/neovim/neovim/pull/5133 on Windows 7:

    nvim.exe --headless +"echo readfile(resolve(expand('~/Desktop/test.lnk',1)))" +"q"

**Pull request merged**
