### PR TITLE
feat(lsp)!: rename vim.lsp.get_active_clients to get_clients

### PR DESCRIPTION
**Pull request by mfussenegger**
Soft deprecation (no warning yet), as this will likely cause some churn in
plugins and there should be at least one version released plugin authors can
switch to the new version.

I'm also not sure if this is fully warranted, but I think it does improve the
API, so long-term maybe it is?

### CODE REVIEW

**Comment by glepnir** [comment]
The previous name was straightforward.  `get_clients` is ambiguous. if can return inactive clients  then `get_clients `would fit

**Comment by gpanders** [comment]
Does `get_` add any semantic value? What about simply `vim.lsp.clients()`?

**Comment by justinmk** [comment]
> Does `get_` add any semantic value? What about simply `vim.lsp.clients()`?

- For these standard modules we should probably use common verbs in most cases. Unless we plan to deprecate the other `vim.lsp.get_*` functions, the conventions become very unclear.
- As a user, looking at what's available on a module, it's very very useful to see which things are "read only" (`get_`), else there's no hint about which functions cause side effects.

**Comment by mfussenegger** [comment]
Given that there have been no strong objections I'd go ahead and merge this in a couple days. Last chance to speak up

**Review by justinmk — APPROVED** [review]

**Pull request merged**
