### PR TITLE
Add OpenBSD as an expected OS for opening char devices

### LINKED ISSUE #7542: Unicode test failure on neovim-0.2.1/OpenBSD
```
NVIM v0.2.1
Build type: Release
Lua 5.1
Compilation: /usr/ports/pobj/neovim-0.2.1/bin/cc -O2 -pipe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/usr/ports/pobj/neovim-0.2.1/build-amd64/config -I/usr/ports/pobj/neovim-0.2.1/neovim-0.2.1/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/ports/pobj/neovim-0.2.1/build-amd64/src/nvim/auto -I/usr/ports/pobj/neovim-0.2.1/build-amd64/include
Compiled by edd@wilfred.home

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

When running the old tests:

```
Test results:


From test_startup_utf8.vim:
Found errors in Test_read_fifo_utf8():
function RunTheTest[13]..Test_read_fifo_utf8 line 24: Expected ['テスト', '€ÀÈÌÒÙ'] but got []
TEST FAILURE
```

Any ideas?

Thanks

### PR DESCRIPTION
**Pull request by jamessan**
Closes #7542

Does this fix the issue for you, @vext01?

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by jamessan** [comment]
The second commit is an attempt to not have to name every BSD.  If that works, then I'll squash it.

**Comment by justinmk** [comment]
Couldn't find `sys/param.h` on my linux system. No objection, but I think it makes sense in this case _not_ to squash the commits.

**Comment by jamessan** [comment]
> Couldn't find sys/param.h on my linux system.

Umm, that's strange.

**Comment by justinmk** [comment]
yeah I didn't look very hard, found it with `find /usr -wholename '*sys/param.h'`.

**Comment by jamessan** [comment]
Note to self: Add `vim-patch:8.0.1357` to commit.

**Pull request merged**
