### PR TITLE
fix(filetype): detect files with racket extension as racket

### PR DESCRIPTION
**Pull request by SanchayanMaity**
Files with extension rkt, rktd and rktl are racket filename extensions.

### CODE REVIEW

**Comment by smjonas** [comment]
Thanks for the PR! Changes to the filetype detection logic have to go to through Vim first. So please create a PR on the Vim repo - we will then port the changes over to Neovim.

**Comment by SanchayanMaity** [comment]
> Thanks for the PR! Changes to the filetype detection logic have to go to through Vim first. So please create a PR on the Vim repo - we will then port the changes over to Neovim.

Sorry, a bit confused. This change is for `filetype.lua`. How does vim come into the picture?

**Comment by smjonas** [comment]
`fileytpe.lua` and `filetype/detect.lua` are basically ports of Vim's `filetype.vim` and `scripts.vim` to Lua (we ported them mainly due to performance reasons). To avoid divergence between Vim's and Nvim's filetype detection systems we require changes to go through Vim first.

**Comment by clason** [comment]
To be clear: we still follow Vim's **logic** (which filetypes are detected and how) even though the **implementation** is now different. As @smjonas said, this means the old procedure is unchanged: New or changed filetypes **must** be made as a PR to Vim, which we'll then port as a matter of course.

**Pull request closed without merging**
