### PR TITLE
[RFC] Remove runtime/tools/

### PR DESCRIPTION
**Pull request by mhinz**
This directory contains old (at least 10+ years) scripts that mainly filter
output of other old programs to make them conformant with an 'errorformat'
from 10+ years ago.
## 

What do you think?

### CODE REVIEW

**Comment by tarruda** [comment]
:+1:

**Comment by justinmk** [comment]
LGTM. the unicode script is being addressed by zyx in another PR. Other things like the visual studio script would suffice as an inline example in the docs.

**Comment by mhinz** [comment]
I admit that unicode script is probably is only one to argue about.

@ZyX-I What do you think?

**Comment by Pyrohh** [comment]
I noticed that this can be removed:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3ab7062..2879b57 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -290,9 +290,7 @@ install_helper(
 
 file(GLOB_RECURSE RUNTIME_PROGRAMS
   RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
-  runtime/*.pl runtime/*.awk runtime/*.sh
-  runtime/tools/ref
-  runtime/tools/vimm)
+  runtime/*.awk runtime/*.sh)
 
 foreach(PROG ${RUNTIME_PROGRAMS})
   get_filename_component(BASEDIR ${PROG} PATH)

```

**Comment by splinterofchaos** [comment]
LGTM :+1: 

Looks like much better solutions exist now for what most of these tools intended to do.

**Comment by justinmk** [comment]
merged

**Comment by ZyX-I** [comment]
@mhinz That script is very inconvenient to use and it uses old code style. My PR has usual lua generator which is located in `scripts/`. I do not see why it should be kept.

**Pull request closed without merging**
