### PR TITLE
build: bundle markdown treesitter parser by default

### PR DESCRIPTION
**Pull request by dundargoc**
Problem: Manually styling Markdown documentation in LSP results (hover,
signature help) is cumbersome.

Solution: Bundle a Markdown tree-sitter parser and make @folke upstream
his implementation from noice.nvim.

New problem: This means that we introduce C++ as a new requirement for building our dependencies (but not for Neovim itself!)

### CODE REVIEW

**Comment by lewis6991** [comment]
I'm not sure how I feel about introducing c++. We should see if the scanner in the parser can be adapted to c.

**Comment by clason** [comment]
Note that this is just one of many parsers with a scanner.cc; I don't think it's feasible to rewrite all of them and get that accepted...

**Comment by clason** [comment]
Yes. There are _many_ parsers, is my point. Testing the waters here is very much intended.

**Comment by justinmk** [comment]
> New problem: This will make C++ an official build dependency of Neovim.

In the past we've had other _bundled_ deps that require C++, no? So if the system / package manager provides this treesitter shared library, Nvim can load it, but Nvim itself doesn't require C++ to build.

The distinction is important: this isn't a door to introducing C++ source files in Nvim itself. And the distinction isn't just academic, because if we have e.g. a CI that delivers treesitter parsers https://github.com/neovim/neovim/issues/22313 which are fetched at runtime, again C++ is not required to build Nvim itself.

Perhaps we should block this until https://github.com/neovim/neovim/issues/22313 is resolved. Why is markdown important enough to add to our build system instead of resolving https://github.com/neovim/neovim/issues/22313 ?

**Comment by clason** [comment]
> Perhaps we should block this until https://github.com/neovim/neovim/issues/22313 is resolved.

I don't think this will be solved in the foreseeable future; I certainly don't see a path forward, and upstream is not moving.

> Why is markdown important enough to add to our build system instead of resolving https://github.com/neovim/neovim/issues/22313 ?

As the PR description states: this will allow us to drop our custom, fickle, manual styling of Markdown responses from LSP. It will also give us a known "difficult" parser for stress-testing our treesitter integration (injections etc.) -- it has already surfaced a bug in our LanguageTree implementation.

Finally, we have to deal with parsers that use C++ sooner or later -- if not this one, then Python.

**Comment by justinmk** [comment]
> As the PR description states: this will allow us to drop our custom, fickle, manual styling of Markdown responses from LSP. It will also give us a known "difficult" parser for stress-testing our treesitter integration (injections etc.)

I missed the LSP part, makes sense.

> Finally, we have to deal with parsers that use C++ sooner or later

We also have to address https://github.com/neovim/neovim/issues/22313  sooner or later ;)

**Comment by lewis6991** [comment]
Parse successfully ported to C 🚀 . We can now further punt the C++ problem to the next parser.

**Comment by clason** [comment]
such as 
* https://github.com/tree-sitter/tree-sitter-bash/blob/master/src/scanner.cc
* https://github.com/tree-sitter/tree-sitter-python/blob/master/src/scanner.cc

:P

**Comment by clason** [comment]
@dundargoc I'll wait for a new release of the parser, then open up a new PR that cherry-picks the still needed changes (split parser) and adds the queries.

**Comment by lewis6991** [comment]
> such as
> 
>     * [tree-sitter/tree-sitter-bash@`master`/src/scanner.cc](https://github.com/tree-sitter/tree-sitter-bash/blob/master/src/scanner.cc?rgh-link-date=2023-03-02T16%3A56%3A01Z)
> 
>     * [tree-sitter/tree-sitter-python@`master`/src/scanner.cc](https://github.com/tree-sitter/tree-sitter-python/blob/master/src/scanner.cc?rgh-link-date=2023-03-02T16%3A56%3A01Z)
> 
> 
> :P

Just looking at those. They use C++ for the same reason as markdown (for `vector`, `string` for bash serving the same purpose as a general stack object).

Would be even easier to port, but I don't know if such PR would be accepted.

**Comment by clason** [comment]
> Would be even easier to port, but I don't know if such PR would be accepted.

Can't hurt to ask; I would assume tree-sitter to be interested in anything that would increase chance of adoption?

(Only if you want to, of course. We're entering the territory of diminishing returns with these parsers (plus json).)

**Comment by clason** [comment]
superseded by #22448  -- thanks, Dundar! 

(thundar.)

**Pull request closed without merging**
