### PR TITLE
fix(lint): remove redundant ternary operator

### PR DESCRIPTION
**Pull request by kylo252**
The value of `new_len` will never be '0' since `replacement.size` is checked against that early on.

### CODE REVIEW

**Comment by justinmk** [comment]
1. there is also `replacement.items[replacement.size-1]` a few lines up. So if we're certain that `replacement.size > 0` then we should `if (replacement.size == 0) { abort(); }` in the appropriate place.
2. there is also `replacement.size > 1` on line 653, that can be removed then?

**Comment by justinmk** [comment]
yep but it's not really obvious that `replacement = scratch` means "size > 0"

**Comment by bfredl** [comment]
so write a comment, like `scratch always have lenght 1` ?

**Comment by justinmk** [comment]
> so write a comment, like `scratch always have lenght 1` ?

Sounds good. I think a 1-line `assert()` serves the same purpose with the benefit of being "alive", if we want to avoid the verbosity of `if ... abort()`. I only mention this for reference, feel free to choose either way here.

**Pull request merged**
