### PR TITLE
[RDY] "abstract_ui" fixes and improvements(continuation)

### PR DESCRIPTION
**Pull request by tarruda**

### CODE REVIEW

**Comment by tarruda** [comment]
@oni-link @fwalch @bfredl @Tranquility can you guys update this and neovim/python-client#74 for one more review? I have made some enhancements that should improve performance and compatibility with existing color schemes

**Comment by fwalch** [comment]
> I have made some enhancements that should improve performance and compatibility with existing color schemes

The color scheme I use (sjl/badwolf) works now! :+1:

The only thing that doesn't work as before (with `nvim`) is the suspend functionality. I often use Ctrl-Z to suspend nvim, execute something on the command line and use `fg` to go back into nvim again. Now of course that doesn't work (out-of-the-box, at least), because suspending kills pynvim. Can this be fixed easily?

**Comment by bfredl** [comment]
My color scheme now works, except that italics don't (`term=italic cterm=italic` is being set, but ignored by the cli frontend ), it did last iteration.
Also just noted `set title` doesn't work, I suppose this is the matter of adding a `update_title` ui event. But otherwise it seems to work pretty smooth :+1:

**Comment by bfredl** [comment]
Adding `gui=italic` doesn't help.

**Comment by tarruda** [comment]
> Can this be fixed easily? If not, I'll try to use the --listen and --connect options for now.

Yes, it should be straightforward to fix, I'm gonna give it a shot now.

> My color scheme now works, except that italics don't (term=italic cterm=italic is being set, but ignored by the cli frontend ), it did last iteration.

I also had noticed this, I may be wrong but this could be libtickit using the wrong sequences for italic. cc @leonerd

**Comment by Tranquility** [comment]
Except for the slow shell output I can see no more problems :+1:

**Comment by tarruda** [comment]
Implemented suspend and set_icon/title on the latest version. Tagging RDY

**Comment by tarruda** [comment]
Title still isnt working on the tickit_ui. @leonerd, is [this](https://github.com/tarruda/python-client/blob/ui-prototypes/neovim/ui/tickit_ui.py#L350-L351) the correct way of setting the title with libtickit?

**Comment by justinmk** [comment]
The comments at the top of `ui.c` are totally outdated AFAICT:

```
 *
 * VIM - Vi IMproved▸   by Bram Moolenaar
 * ...
 * ui.c: functions that handle the user interface.
 * 1. Keyboard input stuff, and a bit of windowing stuff.  These are called
 *    before the machine specific stuff (mch_*) so that we can call the GUI
 *    stuff instead if the GUI is running.
 * 2. Clipboard stuff.
 * 3. Input buffer stuff.
 */
```

There's almost no original Vim code in `ui.c`.

**Comment by leonerd** [comment]
@tarruda: that looks correct, yes. setctl_str().
You might want to set the ICON or ICONTITLE property though

**Comment by fwalch** [comment]
> Implemented suspend

Works fine, thanks! :+1:

**Comment by tarruda** [comment]
> @tarruda: that looks correct, yes. setctl_str().
You might want to set the ICON or ICONTITLE property though

Turns out it wasn't working because of a mistake I made. Fixed now, thanks.

**Comment by bfredl** [comment]
Almost there, `set title` doesn't work in `urxvt`. it works if I change `TERM=xterm` (still running in `urxvt`). 
Now I get nondeterministically on startup (once in three tries, approx)
```
Traceback (most recent call last):
  File "neovim/ui/ui_bridge.py", line 93, in apply_updates
    handler(*args)
  File "neovim/ui/tickit_ui.py", line 321, in _nvim_scroll
    self._screen.scroll(count)
AttributeError: 'NoneType' object has no attribute 'scroll'
```

**Comment by bfredl** [comment]
But resizing the terminal window is smoother than the builtin terminal gui (including vanilla vim). :+1: Italics also works with `TERM=xterm`, but unfortunately, this setting also kills the scrolling/resizing speedup. I think, the terminal entry libtickit uses for `urxvt` is simply incomplete.

**Comment by bfredl** [comment]
Also `TERM=misspelledterminalname` causes a segfault (where it should print an error message and exit)

**Comment by bfredl** [comment]
Scrollwheel always scrolls the focused window, unlike the builtin tui where the hovered window is scrolled. (I think the later is more correct)

**Comment by oni-link** [comment]
Loading a file in terminal nvim and decreasing the terminal width to about 10 chars crashes nvim.
Tried it in xterm and urxvt.

**Comment by leonerd** [comment]
@bfredl: libtickit has "special" handling for TERM=xterm (or rather, anything it recognises that might be xterm-like), because "xterm" is now more a general specification of how terminals should work, than a specific implementation. Any terminal that is known xterm-like uses a different driver that isn't controlled by terminfo.

An upshot of this is that the xterm driver can use many more abilities that known xterm-alikes have, such as italics/strikethrough, arbitrary scrolling regions, nicer mouse encodings, etc... These are abilities that the termcap/terminfo file format simply cannot express, so the generic terminfo-based driver does not have an ability to use italics, etc..

**Comment by bfredl** [comment]
@leonerd Can I somehow specify to libtickit to use the union of the known capabilities of xterm and urxvt? Or is the table of "known xterm-like terminals" just missing the entry `TERM=rxvt-unicode-256color` ?

**Comment by leonerd** [comment]
@bfredl unfortunately that won't help at all. It's not that rxvt isn't known to be xterm-like. It's that rxvt is /specifically/ known to be not-xtermlike. It acts somewhat differently to the emerging de-facto standard that every other terminal is conforming to.
It's also not just a matter of a union of capabilities - rxvt uses /different/ control strings to use these features than the other terminals do.

**Comment by bfredl** [comment]
Well, running urxvt in `TERM=xterm` mode mostly works, except that scrolling is horribly slow (compared to when `TERM=urxvt`) Perhaps this should be regarded as a bug in urxvt.
Should maybe try find another terminal then (It's just that I like its particular feature set: good unicode and font capabilities, at least pseudo-truecolor, good input method support, etc)

**Comment by leonerd** [comment]
@bfredl: At the risk of being accused of self-trumpet-blowing, I could suggest pangoterm? ;)
  https://launchpad.net/pangoterm

As to scrolling and othersuch: I don't have an easy way to look into that, not being an rxvt user myself. The difference in scrolling though is likely to simply be the difference between using the 'xterm' driver with its known ability to always use DECSTBM/DECSLRM, vs. rxvt on the 'terminfo' driver just having to go with what terminfo says. It might be that your terminfo file doesn't include the stbm string.

**Comment by tarruda** [comment]
> @bfredl: libtickit has "special" handling for TERM=xterm (or rather, anything it recognises that might be xterm-like), because "xterm" is now more a general specification of how terminals should work, than a specific implementation. Any terminal that is known xterm-like uses a different driver that isn't controlled by terminfo.

> An upshot of this is that the xterm driver can use many more abilities that known xterm-alikes have, such as italics/strikethrough, arbitrary scrolling regions, nicer mouse encodings, etc... These are abilities that the termcap/terminfo file format simply cannot express, so the generic terminfo-based driver does not have an ability to use italics, etc..

@leonerd I currently use a custom terminfo database(a combination of screen-256 and urxvt) that is identifier by "tmux" in my `~/.terminfo directory`. Even though my `$TERM` is set to a string that is not standard(tmux) vim is capable of rendering italics due to how it uses terminfo.

So there must be something missing in how libtickit uses terminfo, otherwise it should be capable of rendering italics just like vim right?

**Comment by tarruda** [comment]
> Well, running urxvt in TERM=xterm mode mostly works, except that scrolling is horribly slow (compared to when TERM=urxvt) Perhaps this should be regarded as a bug in urxvt.

I couldn't reproduce this, but currently I don't use the terminal builtin scrolling facility through libtickit(the scroll region is always redrawn), so it could be the cause.

**Comment by bfredl** [comment]
@leonerd Will definitely try it. 
@tarruda Scrolling gets slow for `urxvt`+ `TERM=xterm`when using a 256-colorscheme (that happens to set the background). But you're right, it is redrawing a large part of the screen in general that gets slow, and not specifically scrolling.

**Comment by leonerd** [comment]
@tarruda interesting; I don't think terminfo strictly /has/ support for italics? At least, it's not any of the boolean flags supported by the SGR wrapper. Do you know how vim pulls that information out? Maybe it's something different I didn't know about

**Comment by leonerd** [comment]
Ahah! Seems unibilium has gained 'enter_italics_mode' and 'exit_italics_mode' since I last looked at it. I guess using those would be the thing.

**Comment by leonerd** [comment]
@tarruda, @bfredl Try applying this patch to libtickit and rebuilding, and see if italics now works.
http://pastie.org/private/e0rqidgbm7tylqkndi4mha

Annoyingly I don't have an italics-capable terminal that isn't TERM=xterm to test myself.

**Comment by bfredl** [comment]
how do I force rebuild a deps lib? `make` says `builing target libtickit` but doesn't do anything (even if I `make clean` inside `libtickit` and remove `.deps/usr/lib/libtickit*`

**Comment by bfredl** [comment]
Managed to fix it. Italics now works :+1:

**Comment by tarruda** [comment]
@leonerd the patch fixes for the problem, thanks

I wonder if it would be possible to use a similar approach to detect if the terminal supports rgb colors(in the future when libtickit itself adds support). If yes, I could forward use that information as a parameter to `ui_attach` and have gui color schemes working with terminals, similarly to the patch @ZyX-I sent to vim_dev some time ago.

**Comment by tarruda** [comment]
> Loading a file in terminal nvim and decreasing the terminal width to about 10 chars crashes nvim.
Tried it in xterm and urxvt.

Is this still happening after @7e3a6a06 ?

**Comment by oni-link** [comment]
@tarruda, no problems anymore with resizing terminal nvim.

**Comment by tarruda** [comment]
> @tarruda, no problems anymore with resizing terminal nvim.

Great, merging as soon as the tests  are finished

**Comment by leonerd** [comment]
@tarruda: I really don't think there's terminfo slots for RGB8 colour support. The way to detect those is just to try it and query back to see if it was set or not. Like most things really.
However, I don't know if it would be safe to do that from the terminfo driver, only the xterm driver.

**Comment by bfredl** [comment]
:+1: Scrollwheel now works as expected. I guess I will just hack libtickit for the moment to use the xterm sequences for setting the title in urxvt :P Though I still get the `AttributeError` I posted above occasionally. (something racy in initialization?)

**Pull request merged**
