### PR TITLE
fix(events): don't expand `args.file` for Lua callback

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  In an autocommand Lua callback whether `args.file` is expanded
          depends on whether `expand('<afile>')` has been called.
Solution: Always use the unexpanded file name for `args.file`.

Related to #31306 and vim/vim#16106. This doesn't provide `sfname`, but
at least makes `args.file` have a consistent value.

### CODE REVIEW

**Review by justinmk — APPROVED** [review]
Nice

**Comment by clason** [comment]
Backport?

**Comment by zeertzjq** [comment]
Wait for some time to see if anything breaks

**Comment by clason** [comment]
As long as we don't forget.

**Pull request merged**
