### PR TITLE
third-party: remove msvc-compat/unistd.h  [skip travis]

### PR DESCRIPTION
**Pull request by blueyed**
This was added in fa6f89205 (via
https://github.com/neovim/neovim/pull/8084).

This is meant to check if it is still required, and should the be moved
upstream if so.

/cc @b-r-o-c-k

### CODE REVIEW

**Comment by b-r-o-c-k** [comment]
Here's the upstream PR:
https://github.com/mauke/unibilium/pull/34

MSVC doesn't have `unistd.h` so added it because I thought it would be used by other dependencies, but unibilium is the only one that needs it. If you want to remove it, I could replace it with a simple patch that changes the line `#include <unistd.h>` to `#define ssize_t int` inside `uniutil.c`.

**Comment by blueyed** [comment]
@b-r-o-c-k 
Thanks for the info (and sorry for missing the PR)!
We are about to use a (friendly) fork of unibilium anyway (https://github.com/neovim/neovim/issues/10302), so we should get it into there via your PR.
Is that OK, up to date?  Can it be shorter?

**Comment by b-r-o-c-k** [comment]
I haven't tested the CMakeLists.txt on any platform besides Windows and it could be made shorter by removing the compatibility header and replacing it with a typedef only for MSVC.  I will fix these things and create a new PR for the fork.

**Comment by blueyed** [comment]
Rebased on https://github.com/neovim/neovim/pull/10677 for testing.

**Comment by blueyed** [comment]
Thanks, @b-r-o-c-k ! :)

**Pull request merged**
