### PR TITLE
Sort oldfiles in the marks_spec tests to avoid random ordering errors.

### PR DESCRIPTION
**Pull request by jszakmeister**
According to @ZyX-I in #3594, ordering is not important so let's use
@tarruda's fix by sorting the results.

### CODE REVIEW

**Comment by tarruda** [comment]
:+1:

**Comment by jszakmeister** [comment]
@tarruda I hope you don't mind me picking up your patch.

On a side note, is the QB instance helpful?  I originally I really don't want to spend time running it if folks aren't finding it useful, and it seems that things are trending that way since everyone treats QB errors as things to be ignored.  I don't mind--and I certainly won't be offended--if we'd rather just nix it all together.  I just don't want to generate noise and spend time on something that isn't worthwhile--time is precious after all! :-)

**Comment by tarruda** [comment]
> On a side note, is the QB instance helpful? I originally I really don't want to spend time running it if folks aren't finding it useful, and it seems that things are trending that way since everyone treats QB errors as things to be ignored. I don't mind--and I certainly won't be offended--if we'd rather just nix it all together. I just don't want to generate noise and spend time on something that isn't worthwhile--time is precious after all! :-)

It is very useful and I really appreciate that you are running it. There's no other verification for freebsd, and it is nice to run linux and OSX tests in another environment that possibly has different performance impacts than travis.

The only weakness is that sometimes it is difficult to determine the cause of failures in QB, this is where travis really shines: the colored terminal output really simplifies identifying the interesting log parts. But this is a small disadvantage that is completely compensated by having more test coverage, so keep up the good work!

Also, I've been meaning to ask: 

- What VPS provider you use for QB?
- Do you run your own virtual machines for FreeBSD/OSX or are they managed directly by the VPS provider?

**Comment by jszakmeister** [comment]
> The only weakness is that sometimes it is difficult to determine the cause of failures in QB, this is where travis really shines: the colored terminal output really simplifies identifying the interesting log parts. But this is a small disadvantage that is completely compensated by having more test coverage, so keep up the good work!

Yeah, I've got a ticket in with PMEase about some of that--especially reducing the noise at the top of the overview page.  If you scroll down--and the tests have actually run--you should see the tests report at the bottom for each platform.  It's usually pretty simple to find the problem from there.  But now that it uses TAP, it's also easier to see in the logs, and the tap report will spit out the failure too.

> Also, I've been meaning to ask:
> 
> * What VPS provider you use for QB?

I'm running the server on a Linode instance.  I've been using Linode for quite some time.  They're good guys and I like their service.

> * Do you run your own virtual machines for FreeBSD/OSX or are they managed directly by the VPS provider?

At the moment, they're my own virtual machines.  I have a fairly beefy box I run them on, though I don't want to keep them on it forever--I have other things I want to do with that box.  I've looked at possibly spinning up AWS instances--QB does support thiss--but I've not done a lot in the AWS realm, and I'm not sure what the final costs would look like.  They're all pretty clean installs with the exception of making the build agent run on start-up, and all the necessary tooling, of course. :-)  I'm paying for stuff out-of-pocket at the moment, so it was the cheap way to go. :-)

**Pull request merged**
