### PR TITLE
fix(treesitter): make sure injections don't return empty ranges

### LINKED ISSUE #23409: Vimdoc freezes without `injection.include-children`
### Problem

Without `injection.include-children` set, opening help file with treesitter attached to it completely freezes neovim

### Steps to reproduce

- Clone neovim from source
- Go to runtime/queries/vimdoc/injections.scm
- Remove `(#set! injection.include-children)`
- `make install`
- nvim --clean
- `:h nvim_create_autocmd()`
- `:lua vim.treesitter.start()`

### Expected behavior

Neovim to not freeze after the attaching treesitter

### Neovim version (nvim -v)

NVIM v0.10.0-dev-233+g066db5e7c-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux linux 6.2.13-zen-1-zen

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from source

### PR DESCRIPTION
**Pull request by lewis6991**
When an injection has not set include children, make sure not to add
the injection if no ranges are determined.

This could happen when there is an injection with a child that has the
same range as itself. e.g. consider this Makefile snippet

```make
foo:
  $(VAR)
```

Line 2 has an injection for bash and a make variable reference. If
include-children isn't set (default), then there is no range on line 2
to inject since the variable reference needs to be excluded.

This caused the language tree to return an empty range, which the parser
now interprets to mean the full buffer. This caused makefiles to have
completely broken highlighting.

Fixes #23409

### CODE REVIEW

**Comment by lucario387** [comment]
Maybe unrelated, but from my testing, this fixes #23409

**Review by justinmk — APPROVED** [review]

**Comment by clason** [comment]
Was about to say, that sounds mighty familiar...

**Comment by lewis6991** [comment]
You can check if it is this bug by running:

```lua
local function check_ts_bug()
  for _, child in pairs(vim.treesitter.get_parser():children()) do
    if #vim.tbl_filter(function(t) return #t==0 end, child:included_regions()) == 0 then
      return true
    end
  end
  return false
end
```

**Comment by lucario387** [comment]
> You can check if it is this bug by running:

Running the function above returns false while I'm in `:h api`, without `include-children` in the queries file, and with treesitter enabled

**Comment by lewis6991** [comment]
Try again, there was a mistake. Had to change `==` to `>`. Basically the function is checking there are no empty ranges.

**Comment by lucario387** [comment]
> Are the injection queries correct? Is include-children needed in that case?

The injections query that I used is 
```diff
((codeblock
  (language) @injection.language
-  (code) @injection.content)
- (#set! injection.include-children))
+  (code) @injection.content))
```
With the query above, it no longer parses vimdoc injections.

**Comment by lewis6991** [comment]
> Edit: It fixes the issue of freezing, but the highlights are completely gone now. So partially fixed, not fully

I just checked this, and vimdoc `codeblock` nodes have `line` children. So `include-children` is needed for vimdoc code blocks.

**Pull request merged**
