### PR TITLE
docs(insert): mark vim code blocks as such

### PR DESCRIPTION
**Pull request by ribru17**

### CODE REVIEW

**Comment by clason** [comment]
Sorry, but we try not to touch the help pages taken from Vim beyond correcting factual inaccuracies due to divergence (otherwise I would have done this a long time ago...)

**Comment by ribru17** [comment]
I see; would this be a valid PR to vim (and then a patch here)?

**Comment by clason** [comment]
> I see; would this be a valid PR to vim (and then a patch here)?

No, because they don't use language injections. Until we finally decide to take ownership of _all_ docs and rewrite them according to _our_ (stricter) vimdoc spec, they will have to stay as they are.

**Comment by ribru17** [comment]
Got it, thanks

**Pull request closed without merging**
