### PR TITLE
[RFC] Fix display of clip register in :registers

### PR DESCRIPTION
**Pull request by rogual**
It was showing up as `"|` instead of `"+`.

### CODE REVIEW

**Comment by bfredl** [comment]
This only restores `"+` and not `"*`. Please see #2077 that will display both. But I see you updated the comment about registers which I had forgotten in #2077 :+1:

**Comment by rogual** [comment]
OK! what happens now, do we close this and wait for #2077 to be merged instead?

**Comment by bfredl** [comment]
closing in favour for #2244 (@rogual I split this part out as the rest of #2077 has unmet dependencies)

**Comment by bfredl** [comment]
Fixed on master now

**Pull request closed without merging**
