### PR TITLE
fix(prompt): emit change event for prompt newline

### PR DESCRIPTION
**Pull request by icholy**
See #24972

### CODE REVIEW

**Comment by zeertzjq** [comment]
Can you add a test in `test/functional/lua/buffer_updates_spec.lua`?

**Comment by icholy** [comment]
I'm trying to reproduce this with the following code:

``` lua
-- create prompt buffer
local buf = vim.api.nvim_create_buf(true, true)

-- attach listener
vim.api.nvim_buf_attach(buf, true, {
  on_lines = function (_, _, _, firstline, lastline, _, _)
	vim.print("on_lines", { firstline = firstline, lastline = lastline })
  end
})

-- convert it to a prompt
vim.api.nvim_buf_set_name(buf, '[repl]')
vim.bo[buf].buftype = 'prompt'
vim.bo[buf].buflisted = false
vim.bo[buf].filetype = 'repl'
vim.fn.prompt_setprompt(buf, 'repl> ')
vim.fn.prompt_setcallback(buf, vim.print)

-- send some keys
vim.api.nvim_set_current_buf(buf)
vim.api.nvim_feedkeys("i\n", "n", true)
```

But it the `firstline` is coming out correctly.

**Comment by zeertzjq** [comment]
I tried to add a test for this and it seems there is a missing call to `on_bytes`:
```
on_bytes: total bytecount of buffer is wrong
Expected objects to be the same.
Passed in:
(number) 5
Expected:
(number) 6
```
I think it should use `appended_lines_mark()` instead.

**Comment by icholy** [comment]
Closing in favor of #28260

**Pull request closed without merging**
