### PR TITLE
refactor: add pure attribute to pure functions

### PR DESCRIPTION
**Pull request by dundargoc**
This will allow the GCC compiler to make further optimizations.

### CODE REVIEW

**Comment by dundargoc** [comment]
Ignored dependencies and the regexp files.

Also skipped `sign.c` because the `FUNC_ATTR_PURE` macro didn't work there. I'm guessing it's related to the header generation.

**Comment by gpanders** [comment]
If we mistakenly mark a function as pure, does gcc/clang correctly detect this?

**Comment by theHamsta** [comment]
@dundargoc I'm guessing you applied them everywhere where GCC warned (like on my machine). So there seems to be some local analysis, but I suppose it can only tell when functions are pure but I think it is more difficult to tell the contrary.

**Comment by dundargoc** [comment]
> If we mistakenly mark a function as pure, does gcc/clang correctly detect this?

It doesn't seem like it :/ . It seems to only give a warning if it's used in a `void` function.

I did analyze some functions it suggested as pure and they indeed seemed pure, but I'm not sure how reliable the attribute suggestions are. There doesn't seem to be a lot of information on it.

**Comment by zeertzjq** [comment]
Why are many functions that use global variables marked as pure?

**Comment by dundargoc** [comment]
> __attribute__((pure)): The function may read, but doesn’t modify any global state.

I think global variables are fine so long they're not modified.

**Comment by gpanders** [comment]
Hmm in that case I wonder if it might be better to do this in stages? Reviewing ~300 functions for "purity" is a lot, it would be much easier to audit them in chunks (kind of like you did for the uncrustification).

**Comment by dundargoc** [comment]
Agreed.

The one line in [the documentation](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) that stood out to me is

> Interesting non-pure functions are functions with **infinite loops** or those depending on **volatile memory or other system resource**, that may change between consecutive calls (such as the standard C feof function in a multithreading environment).

I still haven't checked if the compiler is able to identify this and refrain from suggesting the `pure` attribute. Regardless, good to keep in mind. I'm writing this just as for my future self as others :)

One thing I wish the documentation touched on is if pure functions can call non-pure functions (instinctively I'd say no, since the global state is still changed inside the function, just more levels down.). Curiously they make this clear in the `const` case:

> a function that calls a non-const function usually must not be const itself.

**Comment by dundargoc** [comment]
Note to self: there are too many large-scale refactoring PRs conflicting with each other. Focus on removing `char_u` as well as enabling `-Wconversion` for all files before doing this.

**Comment by dundargoc** [comment]
I don't believe in this PR anymore. These attributes are poorly documented and their supposed benefits have yet to be demonstrated at all. If anything we should remove these and stop cosplaying as compiler writers.

**Pull request closed without merging**
