### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by janlazo** [comment]
vim-patch:8.1.0727: compiler warning for sprintf() argument

**Comment by willelz** [comment]
vim-patch:8.0.0506: can't build with ANSI C
vim-patch:8.0.0730: terminal feature only supports Unix-like systems
vim-patch:8.0.0742: terminal feature does not work on MS-Windows
vim-patch:8.0.0745: multi-byte characters in a terminal don't display well
vim-patch:8.0.0758: possible crash when using a terminal window
vim-patch:8.0.0771: cursor in terminal window not always updated in GUI
vim-patch:8.0.0778: in a terminal the cursor may be hidden
vim-patch:8.0.0802: last line of terminal window has no color
vim-patch:8.0.0812: terminal window colors shift when 'number' is set
vim-patch:8.0.0853: crash when running terminal with unknown command
vim-patch:8.0.0871: status line for a terminal window always has "[+]".
vim-patch:8.0.0872: no mouse scroll with a terminal window
vim-patch:8.0.0886: crash when using ":term ls"
vim-patch:8.0.0903: early return from test function
vim-patch:8.0.0915: wrong initialisation of global

**Comment by janlazo** [comment]
8.0.0504 is followed by vim-patch 8.0.0506 so they should be resolved together with 8.0.0514 and 8.0.0572. 
For terminal patches, I suggest we start from vim-patch:8.0.0693 and discuss which parts of Vim's implementation and testing of `+terminal` and `:Termdebug` are relevant. This includes 8.0.0903 for `test_terminal.vim` and 8.0.0915 for winpty I don't see `+terminal` in https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#types-of-not-applicable-vim-patches.

**Comment by janlazo** [comment]
`scripts/vim-patch.sh` doesn't ignore `runtime/defaults.vim` and https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#types-of-not-applicable-vim-patches doesn't mention it.  I assume vim-patch:8.1.0948 is N/A because `runtime/default.vim` is not included in the repo.

**Comment by justinmk** [comment]
Added `:terminal` and `defaults.vim` to https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#types-of-not-applicable-vim-patches

> For terminal patches, I suggest we start from vim-patch:8.0.0693 and discuss which parts of Vim's implementation and testing of `+terminal` and `:Termdebug` are relevant

Sounds good! But in general, IMO I'm perfectly fine marking them all N/A. When the time comes to add features to `:terminal`, we won't forget to take a look at Vim's `:terminal`, as far as user interface goes. I don't think there's anything in the implementation that is relevant to us.

**Comment by xiongmao86** [comment]
All following commits are about bracketed paste on vim terminal.
vim-patch:8.0.0210: no support for bracketed paste
vim-patch:8.0.0230: bracketed paste does not support line breaks
vim-patch:8.0.0231: bracketed paste mode is not tested
vim-patch:8.0.0232: paste does not work when 'esckeys' is off
vim-patch:8.0.0238: bracketed paste does not disable autoindent
vim-patch:8.0.0296: bracketed paste can only append, not insert
vim-patch:8.0.0303: bracketed paste does not work in Visual mode
vim-patch:8.0.0569: bracketed paste is still enabled in a shell command
vim-patch:8.0.1299: bracketed paste does not work well in terminal window
vim-patch:8.1.0224: hang in bracketed paste mode when t_PE not encountered

**Comment by janlazo** [comment]
IIRC, bracketed paste is WIP so I didn't include them in the previous version.c PRs unless the patch was for `term.c` only. There are open issues for the following search: https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+bracketed+paste. Is bracketed paste suppose to be handled within the TUI only?

> When the time comes to add features to :terminal, we won't forget to take a look at Vim's :terminal, as far as user interface goes

User interface here means the documented Vim API in `:help`, including `++opt`, or just the visible behavior of `:terminal` when the user runs it?

**Comment by janlazo** [comment]
Vim graduated `FEAT_MBYTE` in the following patches. Not sure if they are completely N/A.
vim-patch:8.1.0805: too many #ifdefs
vim-patch:8.1.0806: too many #ifdefs
vim-patch:8.1.0809: too many #ifdefs
vim-patch:8.1.0810: too many #ifdefs
vim-patch:8.1.0811: too many #ifdefs

**Comment by xiongmao86** [comment]
I was doubting its referential value, I should’ve ask first. I am not sure bracketed paste is only about tui, since 8.0.0233 says test fails in GUI, perhaps GUI is also involve.

Thank you for reminding the issues, I’ll try to read terminal.c first and take a stab on the issue.

**Comment by janlazo** [comment]
@willelz You can include 8.0.0514. 8.0.0572 makes it N/A.

**Comment by janlazo** [comment]
vim-patch:8.0.0592 was not detected in 5a836d4767b76b0a5f5576f91c7022d4e106f814
I guess it's N/A or merged now.

**Comment by janlazo** [comment]
@xiongmao86 Can you check if any patch in https://gist.github.com/janlazo/cea7acf2711e89a9bc4f7c79612c6e54#bracketed-paste is N/A? If https://github.com/neovim/neovim/pull/4448 or similar PR gets merged, then we may need to keep only the test files from these patches.

**Comment by xiongmao86** [comment]
Sure, thank you @janlazo.  These commits doesn't contain test:
vim-patch:8.0.0210: no support for bracketed paste
vim-patch:8.0.0228: pasting in xterm on the command line has PasteStart
vim-patch:8.0.0230: bracketed paste does not support line breaks
vim-patch:8.0.1299: bracketed paste does not work well in terminal window

**Comment by LTKills** [comment]
vim-patch:8.0.506: can't build with ANSI C

**Comment by janlazo** [comment]
vim-patch:8.0.0709 is relevant because it adds a new function that later patches depend on. Not sure about the new macro. Vim's libvterm changes are N/A but anything to do with `eval.c`, `message.c` are relevant.

**Comment by xiongmao86** [comment]
v8.0.0569 is pertain to bracketed paste, and doesn't contain test.

**Comment by janlazo** [comment]
@xiongmao86 That patch is marked N/A in an earlier commit, b659841570d0f1bf51e45ba47ebabc80c84e80ef. Check https://neovim.io/doc/reports/vimpatch/ or `src/nvim/version.c`.

**Comment by xiongmao86** [comment]
Ah, thank you for pointing out, @janlazo. So adding comments here will no immediately effect ‘vim-patch.sh -l’?

**Comment by janlazo** [comment]
@xiongmao86 Updates for `version.c` in this PR come from commits containing `vim-patch`, including the merge commit from previous version.c PRs such as https://github.com/neovim/neovim/commit/10f29f79f4e8240254b916160ae5bb17ff56d161. Comments in this PR are for coming up with a list of N/A commits that will be included in the body of the merge commit.

**Comment by janlazo** [comment]
@justinmk Was https://github.com/vim/vim/commit/eb93f3f0e2b2ae65c5c3f55be3e62d64e3066f35 merged already, including the runtime changes?

**Comment by justinmk** [comment]
> @justinmk Were [vim/vim@eb93f3f](https://github.com/vim/vim/commit/eb93f3f0e2b2ae65c5c3f55be3e62d64e3066f35) and [vim/vim@8f4aeb5](https://github.com/vim/vim/commit/8f4aeb5572d604d1540ee0cb7e721b5f0cc6d612) merged already, including the runtime changes?

@janlazo I merged the first one, and the other one is NA.

**Comment by blueyed** [comment]
> Vim graduated `FEAT_MBYTE` in the following patches. ~Not sure if they are completely N/A.~ Probably relevant just for the test changes not checking for `+multi_byte`.
> ~vim-patch:8.1.0805: too many #ifdefs~
> ~vim-patch:8.1.0806: too many #ifdefs~
> ~vim-patch:8.1.0809: too many #ifdefs~
> ~vim-patch:8.1.0810: too many #ifdefs~
> ~vim-patch:8.1.0811: too many #ifdefs~

Only 8.1.0811 appears to contain changes to tests (testdir), added the others to https://github.com/neovim/neovim/pull/10115#issuecomment-500120604.

**Pull request closed without merging**
