### PR TITLE
test: unskip working Windows tests

### PR DESCRIPTION
**Pull request by dundargoc**
Some tests that were previously not working have started to work again
for unspecified reasons, so let's enable them.

### CODE REVIEW

**Comment by lewis6991** [comment]
Iconv is absolutely used

**Comment by dundargoc** [comment]
shush, I'm experimenting

**Comment by clason** [comment]
macos universal release build, I could have told you that ;)

**Comment by dundargoc** [comment]
I wasn't referring to iconv as a whole, just the variable `ICONV_LIBRARY`. Anyway, I'll just pivot this into a generic "delete as much cmake code as possible" PR.

**Comment by dundargoc** [comment]
Yes, ICONV_LIBRARY is being used.

**Review by justinmk — APPROVED** [review]
nice!

**Pull request merged**
