### PR TITLE
ci(provider): skip perl provider tests on macos

### PR DESCRIPTION
**Pull request by dundargoc**
```
--> Working on Eval::Safe
Fetching http://www.cpan.org/authors/id/M/MA/MATHIAS/Eval-Safe/Eval-Safe-0.02.tar.gz ... OK
! Configure failed for Eval-Safe-0.02. See /Users/runner/.cpanm/work/1654113036.13488/build.log for details.
! Installing the dependencies failed: Module 'Eval::Safe' is not installed, Module 'MsgPack::Raw' is not installed, Your Perl (5.018004) is not in the range '5.022'
```

### CODE REVIEW

**Comment by justinmk** [comment]
what exactly was the failure? This is what I found in the build logs, it looks like maybe we just need a newer perl?

```
--> Working on Eval::Safe
Fetching http://www.cpan.org/authors/id/M/MA/MATHIAS/Eval-Safe/Eval-Safe-0.02.tar.gz ... OK
! Configure failed for Eval-Safe-0.02. See /Users/runner/.cpanm/work/1654113036.13488/build.log for details.
! Installing the dependencies failed: Module 'Eval::Safe' is not installed, Module 'MsgPack::Raw' is not installed, Your Perl (5.018004) is not in the range '5.022'

**Comment by dundargoc** [comment]
Nah, both homebrews and the default perl on the system is newer than required, I don't think it's just about a simple version bump. Don't remember the failure message.

**Comment by justinmk** [comment]
We need to mention a reference or failure details when we make changes. Otherwise this is less likely to ever get fixed, or if someone asks why in the future we have no answer except "didn't work".

**Comment by dundargoc** [comment]
I just remembered why I didn't write anything: I have no clue what the error/failure is. It says 

> ! Installing the dependencies failed: Your Perl (5.018004) is not in the range '5.022', Module 'Eval::Safe' is not installed, Module 'MsgPack::Raw' is not installed.

but I know that's not true, so something funky is up. I could have mentioned this but didn't want to write misleading information in the commit.

**Pull request merged**
