### PR TITLE
Update csscomplete to latest CSS standard

### PR DESCRIPTION
**Pull request by othree**
The origin csscomplete is very old, and only supports CSS 2.1.
I have [update it to latest CSS standard](https://github.com/othree/csscomplete.vim). (based on [MDN CSS reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference))
It will be great if this change can commit to the neovim's runtime folder.

### CODE REVIEW

**Comment by justinmk** [comment]
@othree Thanks. As @chrisbra mentioned it would be best if you assumed maintainership of the CSS files for Vim upstream. Bram has been pretty responsive regarding runtime files updates, so I don't think there would be much delay: simply send an email to the vim_dev mailing list declaring that you want to maintain the CSS files.

If for some reason Bram/vim_dev drag their feet then we would consider forking it here, but in the near-term, we don't know how well-tested these changes are. How many people are using them?

**Comment by othree** [comment]
I am doing the process to commit to upstream~~

**Comment by justinmk** [comment]
Thanks.

**Comment by justinmk** [comment]
Assuming everything proceeded after the initial vim_dev introduction, we can wait for upstream.

**Comment by othree** [comment]
Yes, I have contact with original author.
And doing some modification.

**Pull request closed without merging**
