### PR TITLE
native X11 clipboard implementation

### PR DESCRIPTION
**Pull request by bfredl**
Reuses code from vim:s X11 clipboard implementation. **Note** latest code is in  https://github.com/bfredl/nvim-x11
- [x] yank
- [x] put
- [x] selection types (incl blockwise)
- [ ] autoselect
- [ ] sane error handling (== don't crash nvim on any X error)
- [ ] modular design (that allows implementations for OS X and windows)
- [x] use binary plugin (`.so`) so that nvim executable doesn't depend on `libX11.so`
  - [ ] sane event loop integration for binary plugins
- [ ] daemonization
- [ ] tests (reuse from #2077)
- [ ] code style

### CODE REVIEW

**Comment by justinmk** [comment]
> don't crash nvim on any X error)
 
:+1: 
 
> binary plugin (.so) so that nvim executable doesn't depend on libX11.so

:+1:

**Comment by equalsraf** [comment]
> binary plugin (.so) so that nvim executable doesn't depend on libX11.so

Probably too late for the discussion on this, but wouldn't it make more sense to run a helper process that talks to Neovim via msgpack-rpc? i.e. a long lived process like the plugin hosts that gets called to set/get the clipboard, and notifies neovim when the clipboard changes, etc.

**Comment by ZyX-I** [comment]
@equalsraf Setting/getting is the wrong way to think about X11 clipboard. One does not set clipboard, it tells X server “I own the clipboard now”. When needed server requests owner “what is the clipboard contents, text please” (it may actually request different types of content).

For this reason msgpack-rpc is not the best way of handling the clipboard: what if Neovim is blocked by some long-running function? It is logical to have a separate event loop for the X11 clipboard thus, just blocking either main thread or specifically necessary structures (applicable only when using clipboard=autoselect\*, for other actions main thread does not need to be bothered) when actually getting the clipboard contents.

Also for this reason one cannot notify when clipboard changes neither on Neovim side when it is owner (notification with a separate process communicating via msgpack-rpc is useless without pushing the whole clipboard contents and pushing the whole clipboard content is not the thing you want to do with `clipboard=autoselect*`) nor on other side when Neovim does not own it: the only way to determine that something changed is polling the clipboard because X server provides a way to find when *owner* changes, not changes to clipboard content X server never knows.

**Comment by bfredl** [comment]
Acually, binary plugin could just be lua .so module. Only thing we need is a lua helper function "call this callback when this fd is ready for reading", ideally at highest asyncness so pasters don't hang because we're at a "press RETURN" prompt...

**Comment by bfredl** [comment]
I implemented binary plugin concept here: https://github.com/bfredl/nvim-x11 . It is a hack though: it steals the address of the main uv loop through the symbol `main_loop`. Also lua  cannot directly find a `.so` relative itself, so `autoload` function needs to tell lua about the path.

@justinmk I'm not sure if we should integrate this into the main repo/build system, or if we want a separate neovim/nvim-x11 repo. The point of the later would be to semi-formalize the concept of binary plugin through luajit ffi. Not that it currently is a good example, but at least it something that could be improved to be...

**Comment by justinmk** [comment]
> separate neovim/nvim-x11 repo. The point of the later would be to semi-formalize the concept of binary plugin through luajit ffi.

I'd vote for that. I'm not at all excited about bringing X11 into the picture. We've come so far with the jobs-based approach, and its flexibility has been useful. Not to mention, how does Wayland fit into this?

**Comment by bfredl** [comment]
How does xsel not bring X11 into the picture? 

> We've come so far with the jobs-based approach, and its flexibility has been useful.

I can't remember that I ever argued against removing the jobs-based provider. How does _adding an option_ remove flexibiltity? And we "come so far" by adding plenty of workarounds for the missing functionality...

> Not to mention, how does Wayland fit into this?

Someone either writes a job provider _or_ a binary provider for wayland. So the possibilities for Wayland strictly increases.

**Comment by bfredl** [comment]
And BTW I'm not sure of the distribution model, but distros can  safely package `nvimX11.so` in the main `neovim` package. If libXt is missing the `ffi` load fails, and we can default back to some other provider.

**Comment by bfredl** [comment]
Though "autoload shadowing" does not allow provider fallback, rather support of non-job implementations should probably be added to the default provider, then it could just check for availibility _and_ load-ability of `libnvimX11.so` just as for the various executables.

**Comment by lewis6991** [comment]
Can this now be considered obsolete now we have OSC52 support?

**Comment by zeertzjq** [comment]
How are these two related?

**Comment by lewis6991** [comment]
They both implement clipboard integration. If we now have OSC52, do we really need X11?

**Comment by lilydjwg** [comment]
@lewis6991 this should resolve #2325 but OSC 52 can't. IIRC OSC 52 works the same way as clipboard providers---support only copy & paste text. The full clipboard support, however, has things like content type, ownership & transfer on demand.

**Comment by lewis6991** [comment]
Fair enough, however this PR currently adds a build dependency on X11 which I'm sure we wouldn't do today since we also support MacOS and Windows.

**Comment by clason** [comment]
Also wayland is a thing now.

**Pull request closed without merging**
