### PR TITLE
runtime/autoload/health/provider.vim: syntax/style fixes

### PR DESCRIPTION
**Pull request by blueyed**
Fixes "E488: Trailing characters: ) (SyntaxError)" and other style
issues.

What about running https://github.com/Kuniwak/vint/ in general in CI?

### CODE REVIEW

**Comment by justinmk** [comment]
> What about running https://github.com/Kuniwak/vint/ in general in CI?

Definitely would be nice. Just a matter of someone configuring it and probably doing a lot of cleanup on the existing code. Plus we would need to agree on some standards.

**Comment by blueyed** [comment]
> We could start with a bare minimum, to find syntax issues like this

Yeah - in the end it just shows that this code was totally uncovered in tests.

**Comment by justinmk** [comment]
Testing that codepath would be difficult :) There are about 10 different failure modes covered by CheckHealth, depending on the environment, network, etc.

**Comment by blueyed** [comment]
FreeBSD seems to have triggered it (reported on IRC by @raichoo).

**Pull request merged**
