### PR TITLE
[RFC] vim-patch:8.1.{1352,1353}

### LINKED ISSUE #4392: undofile() result different from actual undo file
With `undodir` other than `'.'`, opening a file at path `//tmp/foo` results in an undo file named `%tmp%foo`: the path is normalized before replacing path separators with `%`. On the other hand, `undofile('//tmp/foo')` returns `%%tmp%foo`. Shouldn't these two things be the same?

**To Reproduce**
1. Run `vim --clean`
2. `:set undofile undodir=/tmp`
2. `:e //tmp/foo`
3. Insert some text
4. Save file `:x`

Find the created undo file at `/tmp/%tmp%foo`.

Then compare against running `:echo undofile('//tmp/foo')`.

**Environment (please complete the following information):**
 - Vim 8.1, patches 1-1186
 - OS: Linux

### LINKED ISSUE #10030: undofile() result different from actual undo file
- `nvim --version`: v0.3.5 release build
- Vim (version: 8.1) behaves the same
- Operating system/version: Linux

Opening a file at path `//tmp/foo` results in an undo file named `%tmp%foo`: the path is normalized before replacing path separators with `%`. On the other hand, `undofile('//tmp/foo')` returns `%%tmp%foo`. Shouldn't these two things be the same?

To reproduce:

`nvim -u NORC`

```
:set undofile
:e //tmp/foo
" write something
ibar<Esc>
:x
```

Find the created undo file at `~/.local/share/nvim/undo/%tmp%foo`.

Then compare against running `:echo undofile('//tmp/foo')`.

### PR DESCRIPTION
**Pull request by frangio**
#### vim-patch:8.1.1352: undofile() reports wrong name

Problem:    Undofile() reports wrong name. (Francisco Giordano)
Solution:   Clean up the name before changing path separators. (closes vim/vim#4392,
            closes vim/vim#4394)
https://github.com/vim/vim/commit/e9ebc9a91cac357fd4888f4b71fdff7d97b41160

#### vim-patch:8.1.1353: undo test fails on Mac

Problem:    Undo test fails on Mac.
Solution:   Expect "private" on the Mac.
https://github.com/vim/vim/commit/2b39d806f04c1a474b6d689a7970253850d4adb8

Fixes #10030.

### CODE REVIEW

**Comment by frangio** [comment]
Hm, sorry about this mess... `vim-patch.sh -s` generated it. Did I do something wrong? I had applied only patch 8.1.1352.

**Comment by KillTheMule** [comment]
Looks good now though :+1:

Lint failure is not yours. Travis reports


```

From test_undo.vim:

Found errors in Test_undofile():

function RunTheTest[35]..Test_undofile line 32: Expected '/tmp/%tmp%file' but got '/tmp/%private%tmp%f
```

though, did you run that locally? You can do so via `make test`. Seems macos only though, you have mac by chance?

**Comment by justinmk** [comment]
seems like undofile() is resolving the symlink whereas vim does not.

**Comment by chrisbra** [comment]
Isn't that Vim Patch 8.1.1353?

**Comment by frangio** [comment]
Good catch. I'll apply 8.1.1353 too.

**Comment by justinmk** [comment]
Oops, I pushed a fixup before seeing latest comments. Feel free to take it out. @frangio note that in 8.1.1353, `has('osx')` will fail. Might as well add "osx" to `has()`:

```diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index 82dc0116eb83..132450f7a1cb 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -10830,6 +10830,7 @@ static void f_has(typval_T *argvars, typval_T *rettv, FunPtr fptr)
 #ifdef __APPLE__
     "mac",
     "macunix",
+    "osx",
 #endif
     "menu",
     "mksession",
```

**Comment by frangio** [comment]
To be honest none of those fixes felt right to me. I changed `/tmp` to `/` to avoid the potential symlink. Does this sound reasonable to you all?

Given this I'm not sure it's even necessary to check `isdirectory('/')`, I'd imagine that's a given in all systems.

**Comment by justinmk** [comment]
on windows `/` might expand to `c:/`. Diverging from Vim's tests makes merges more difficult later, so it should be avoided where possible.

**Comment by frangio** [comment]
That makes sense. Applying both patches then.

**Comment by justinmk** [comment]
Thanks!

**Pull request merged**
