### PR TITLE
[RFC] tests: migrate legacy test breakindent.

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by lucc** [comment]
Is `exists("+breakindent")` always true in neovim? (see local function in test file and pending call)

**Comment by fmoralesc** [comment]
Yes, it is always true in neovim.

**Comment by lucc** [comment]
thanks @fmoralesc  I removed the check.

**Comment by lucc** [comment]
ref for a better overview: #1286

**Comment by KillTheMule** [comment]
LGTM :+1: You might also want to merge https://github.com/KillTheMule/neovim/commit/9e15eaffee7b75b1759e97f6a55dd7e9b8c52874. Or should I make a separate PR for that?

Details: See https://github.com/KillTheMule/neovim/commit/bfb750673ae8bd5d7f59f6a65ec4b8faa6683329. The `testpatches/new` directory contains patches that  break functionality tested here. Read about `testpatches/old` in https://github.com/KillTheMule/neovim/blob/bfb750673ae8bd5d7f59f6a65ec4b8faa6683329/testnotes.txt. Run with `new_test.sh`, will apply patches separately and run the test, giving a summary.

I did some side-by-side comparison too, for good measure, but nothing came off of that.

**Comment by justinmk** [comment]
Thank you @lucc and @KillTheMule

**Pull request merged**
