### PR TITLE
Lua: vim.fn_wrap

### PR DESCRIPTION
**Pull request by tjdevries**
This is a step 1 of implementing better Lua <-> VimL interop. In general, I've seen this question on gitter a lot:

> This `vim.fn.prompt_setcallback(buf, function(text) print(text) end)` doesn't work
> This `vim.fn.jobstart(...)` doesn't work

I'm proposing this as the first step in making this work. You can now use `vim.wrap_fn` to recursively transform your functions to pass between Lua & vim (so it handles functions being inside of tables and what not). It's obviously slower and somewhat of a hack as compared to `vim.fn`, but that's why it has a different name :)

I'm suggesting that we can merge this in at some point, and then as time goes on find a more elegant way to convert between Lua & Vim functions (it will probably be some table like this with garbage collection and what not, but that would have taken a lot more time) and then we just drop that in as a replacement for `vim.wrap_fn`. At some point, if it's performant enough and good, we can just do `vim.wrap_fn = vim.fn` and call it a day.

Anyway, tested it a bit myself life and it seems to work well and I added a test to show that the behavior is working and gives results that you'd expect (as in, actually calls the lua function).

Thanks!

### CODE REVIEW

**Comment by justinmk** [comment]
what is it doing in 1 sentence? docstring and 1-line example would be helpful. 

suggest naming it `fn_wrap` , then it is more discoverable and more clearly analogous to `vim.fn`. (Also we already have `schedule_wrap`, so there is existing pattern)

**Comment by tjdevries** [comment]
@justinmk I've updated it to both delete old, inaccessible functions and just overrode `vim.fn`.

Thoughts on new impl? It does add some overhead to all `vim.fn` calls though... Want me to move it back to fn_wrap?

**Comment by prabirshrestha** [comment]
What about this implementation that I sent to vim? https://github.com/vim/vim/pull/6246. It auto converts lua functions to vim lambda so besides `vim.fn.*` calls it call also be used for passing and getting return values to and from vimscript.

I wasn't aware of this PR when I started on vim PR to do the same.

**Comment by tjdevries** [comment]
Closed in favor of: https://github.com/neovim/neovim/pull/12507

**Pull request closed without merging**
