### PR TITLE
feat(terminfo): bump built-in terminfo entries

### PR DESCRIPTION
**Pull request by mhinz**

### CODE REVIEW

**Comment by mhinz** [comment]
Can we have a general `NOLINT` for this file? Apparently it only works per line so far, but there will always be lines like:

```
//  initialize_color=\E]4;%p1%d;rgb\072%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\,
```

**Comment by mhinz** [comment]
I'm waiting for https://github.com/neovim/neovim/pull/18574. If it gets merged, then I'll remove `NOLINT` from both `scripts/update_terminfo.sh` and `src/nvim/tui/terminfo_defs.h`.

**Review by justinmk — APPROVED** [review]

**Comment by mhinz** [comment]
Ok, we need to keep the NOLINT because of `Missing space after ,  [whitespace/comma]`.

Also changed the commit message from `chore` to `feat`.

**Comment by justinmk** [comment]
> Ok, we need to keep the NOLINT because of `Missing space after , [whitespace/comma]`.

Can we remove that clint.py rule? It should be covered by uncrustify.

 Then we don't need to revisit this terminfo change again!

**Review by justinmk — APPROVED** [review]

**Pull request merged**
