### PR TITLE
docs: enforce the terminology 'treesitter', not 'tree-sitter'

### PR DESCRIPTION
**Pull request by wookayin**
See https://github.com/neovim/neovim/pull/27067#discussion_r1460320632:

It's the "tree-sitter" project, but "treesitter" in our code and docs.

### CODE REVIEW

**Review by clason — APPROVED** [review]
One could argue that "tree-sitter library" is still correct, but that would increase the chance of confusion.

@justinmk who made the original call

**Comment by wookayin** [comment]
It seems that this might be a bit controversial, so I will leave this open (and as draft) a little longer and wait for other core dev's input.

Note: All the other occurrences of `tree-sitter` should be literal string indicating the `tree-sitter` project itself. Note that the very first line of `treesitter.txt`

> Nvim integrates the `tree-sitter` library for incremental parsing of buffers:
> https://tree-sitter.github.io/tree-sitter/

is also a literal string "tree-sitter" referring to the original name of the "tree-sitter" library/project.

**Review by MariaSolOs — APPROVED** [review]

**Comment by wookayin** [comment]
Darn, I pressed the wrong button (I should never press the sync-branch button). Github and Refined Github suck -- can't revive the PR :|, so re-opened #27110.

**Comment by MariaSolOs** [comment]
> Darn, I pressed the wrong button (I should never press the sync-branch button). Github and Refined Github suck -- can't revive the PR :|, so re-opened #27110. Sorry for the trouble.

No worries <3

**Pull request closed without merging**
