### PR TITLE
ci: enable bot webhook

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Comment by justinmk** [comment]
test

**Comment by justinmk** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285604/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285605/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285606/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285607/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285608/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285609/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285610/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285611/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285612/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285613/log.txt

**Comment by marvim** [comment]
[linux / ? [u'CI_TARGET=lint']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285604/log.txt)
[linux / gcc-5 ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285605/log.txt)
[linux / gcc-5 [u'FUNCTIONALTEST=functionaltest-lua']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285606/log.txt)
[linux / gcc-5 -m32 [u'BUILD_32BIT=ON']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285607/log.txt)
[linux / clang-3.6 [u'GCOV=llvm-cov-3.6 CLANG_SANITIZER=ASAN_UBSAN CMAKE_FLAGS="$CMAKE_FLAGS -DUSE_GCOV=ON"']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285608/log.txt)
[linux / clang-3.6 [u'CLANG_SANITIZER=MSAN']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285609/log.txt)
[linux / clang-3.6 [u'CLANG_SANITIZER=TSAN']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285610/log.txt)
[osx / clang ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285611/log.txt)
[osx / gcc-4.9 ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285612/log.txt)
[linux / ? [u'BUILD_MINGW=ON']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285613/log.txt)

**Comment by marvim** [comment]
[linux / ? [u'CI_TARGET=lint']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285604/log.txt)
[linux / gcc-5 ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285605/log.txt)
[linux / gcc-5 [u'FUNCTIONALTEST=functionaltest-lua']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285606/log.txt)
[linux / gcc-5 -m32 [u'BUILD_32BIT=ON']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285607/log.txt)
[linux / clang-3.6 [u'GCOV=llvm-cov-3.6 CLANG_SANITIZER=ASAN_UBSAN CMAKE_FLAGS="$CMAKE_FLAGS -DUSE_GCOV=ON"']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285608/log.txt)
[linux / clang-3.6 [u'CLANG_SANITIZER=MSAN']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285609/log.txt)
[linux / clang-3.6 [u'CLANG_SANITIZER=TSAN']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285610/log.txt)
[osx / clang ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285611/log.txt)
[osx / gcc-4.9 ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285612/log.txt)
[linux / ? [u'BUILD_MINGW=ON']](https://s3.amazonaws.com/archive.travis-ci.org/jobs/133285613/log.txt)

**Comment by blueyed** [comment]
Interesting!
Would be helpful to get to logs faster etc.
Do you have plans/ideas to work on this more?

**Comment by justinmk** [comment]
Yes. I need to post the script I have which finds the @marvim comment. That's the most annoying part (using GH API). Goal is to avoid ever having more than one comment from @marvim : if comment exists, update the existing one. Update only open PRs, and avoid spamming GH API.

**Comment by justinmk** [comment]
- Here's an old WIP script I started: https://github.com/neovim/bot-ci/issues/53
- Updated issue description: https://github.com/neovim/bot-ci/issues/53

**Pull request closed without merging**
