### PR TITLE
[RFC] vim-patch:7.4.{629,695,696,701} Mark as included

### PR DESCRIPTION
**Pull request by jusga**
The patches https://github.com/vim/vim/commit/v7-4-629, https://github.com/vim/vim/commit/v7-4-695 and https://github.com/vim/vim/commit/v7-4-696 deal with coverity issues which were fixed by #1947.

The patch https://github.com/vim/vim/commit/v7-4-701 fixes a compiler warning for an uninitialized variable introduced in 695.

---

```
Problem:    Coverity warning for Out-of-bounds read.
Solution:   Increase MAXWLEN to 254. (Eliseo Martínez)
```

https://github.com/vim/vim/commit/v7-4-629

Original patch:

``` diff
diff --git a/src/nvim/spell.c b/src/nvim/spell.c
--- a/src/nvim/spell.c
+++ b/src/nvim/spell.c
@@ -311,9 +311,10 @@
 # include <time.h> /* for time_t */
 #endif

-#define MAXWLEN 250        /* Assume max. word len is this many bytes.
+#define MAXWLEN 254        /* Assume max. word len is this many bytes.
                   Some places assume a word length fits in a
-                  byte, thus it can't be above 255. */
+                  byte, thus it can't be above 255.
+                  Must be >= PFD_NOTSPECIAL. */

 /* Type used for indexes in the word tree need to be at least 4 bytes.  If int
  * is 8 bytes we could use something smaller, but what? */
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    629,
+/**/
     628,
 /**/
     627,
```

---

```
Problem:    Out-of-bounds read, dectected by Coverity.
Solution:   Remember the value of cmap for the first matching encoding.  Reset
            cmap to that value if first matching encoding is going to be used.
            (Eliseo Martínez)
```

https://github.com/vim/vim/commit/v7-4-695

Original patch:

``` diff
diff --git a/src/nvim/hardcopy.c b/src/nvim/hardcopy.c
--- a/src/nvim/hardcopy.c
+++ b/src/nvim/hardcopy.c
@@ -2513,13 +2513,18 @@ mch_print_init(psettings, jobname, force
     props = enc_canon_props(p_encoding);
     if (!(props & ENC_8BIT) && ((*p_pmcs != NUL) || !(props & ENC_UNICODE)))
     {
+   int cmap_first;
+
    p_mbenc_first = NULL;
    for (cmap = 0; cmap < (int)NUM_ELEMENTS(prt_ps_mbfonts); cmap++)
        if (prt_match_encoding((char *)p_encoding, &prt_ps_mbfonts[cmap],
                                    &p_mbenc))
        {
        if (p_mbenc_first == NULL)
+       {
            p_mbenc_first = p_mbenc;
+           cmap_first = cmap;
+       }
        if (prt_match_charset((char *)p_pmcs, &prt_ps_mbfonts[cmap],
                                   &p_mbchar))
            break;
@@ -2527,7 +2532,10 @@ mch_print_init(psettings, jobname, force

    /* Use first encoding matched if no charset matched */
    if (p_mbchar == NULL && p_mbenc_first != NULL)
+   {
        p_mbenc = p_mbenc_first;
+       cmap = cmap_first;
+   }
     }

     prt_out_mbyte = (p_mbenc != NULL);
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    695,
+/**/
     694,
 /**/
     693,
```

---

```
Problem:    Not freeing memory when encountering an error.
Solution:   Free the stack before returning. (Eliseo Martínez)
```

https://github.com/vim/vim/commit/v7-4-696

Original patch:

``` diff
diff --git a/src/nvim/regexp_nfa.c b/src/nvim/regexp_nfa.c
--- a/src/nvim/regexp_nfa.c
+++ b/src/nvim/regexp_nfa.c
@@ -3156,6 +3156,7 @@ post2nfa(postfix, end, nfa_calc_size)
            if (stackp < stack)         \
            {                   \
            st_error(postfix, end, p);  \
+           vim_free(stack);        \
            return NULL;            \
            }

@@ -3632,10 +3633,16 @@ post2nfa(postfix, end, nfa_calc_size)

     e = POP();
     if (stackp != stack)
+    {
+   vim_free(stack);
    EMSG_RET_NULL(_("E875: (NFA regexp) (While converting from postfix to NFA), too many states left on stack"));
+    }

     if (istate >= nstate)
+    {
+   vim_free(stack);
    EMSG_RET_NULL(_("E876: (NFA regexp) Not enough space to store the whole NFA "));
+    }

     matchstate = &state_ptr[istate++]; /* the match state */
     matchstate->c = NFA_MATCH;
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    696,
+/**/
     695,
 /**/
     694,
```

---

```
Problem:    Compiler warning for using uninitialized variable. (Yasuhiro
            Matsumoto)
Solution:   Initialize it.
```

https://github.com/vim/vim/commit/v7-4-701

Original patch:

``` diff
diff --git a/src/nvim/hardcopy.c b/src/nvim/hardcopy.c
--- a/src/nvim/hardcopy.c
+++ b/src/nvim/hardcopy.c
@@ -2513,7 +2513,7 @@ mch_print_init(psettings, jobname, force
     props = enc_canon_props(p_encoding);
     if (!(props & ENC_8BIT) && ((*p_pmcs != NUL) || !(props & ENC_UNICODE)))
     {
-   int cmap_first;
+   int cmap_first = 0;

    p_mbenc_first = NULL;
    for (cmap = 0; cmap < (int)NUM_ELEMENTS(prt_ps_mbfonts); cmap++)
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    701,
+/**/
     700,
 /**/
     699,
```

### CODE REVIEW

**Comment by oni-link** [comment]
LGTM.

**Comment by Pyrohh** [comment]
Merged, thanks @jusga and @oni-link.

**Comment by Pyrohh** [comment]
@jusga I just realized that you haven't signed the CLA, but I'm not really sure if it's needed. @justinmk you said small contributions don't need a signature, but I don't know what defines small.

**Comment by jusga** [comment]
@Pyrohh, I just signed the CLA.

**Comment by Pyrohh** [comment]
Thanks

**Comment by Shougo** [comment]
@Pyrohh If the code is from Vim, the contiributors don't have to sign CLA.  Because, it is under Vim License.
If not, the contributors must sign the CLA.

**Pull request closed without merging**
