### PR TITLE
[RFC] vim-patch:7.4.2212

### LINKED ISSUE #974: Mark "double quote" does not saved in file ".viminfo" since patch 7.4.320.
Prepare:

``` bash
git clone https://github.com/vim/vim
cd vim

# Compile two versions of vim

git checkout v7.4.319
make
cp ./src/vim ../vim-7.4.319

git checkout v7.4.320
make
cp ./src/vim ../vim-7.4.320

cd ..

# Create test file
seq 3 > test_file.txt

```

Content of "~/.vimrc":

``` vim
set nocompatible

autocmd BufReadPost *
   \ if
   \    line( "'\"" ) > 1
   \    &&
   \    line( "'\"" ) <= line( '$' )
   \ |
   \    execute 'normal! g`"'
   \ |
   \ endif
```

Directories "~/.vim", "/usr/local/share/vim", "/usr/share/vim" does not exists.

Begin of test.

``` bash

# Remove file "~/.viminfo"
rm -f ~/.viminfo

# Run vim
./vim-7.4.319

```

Type ":tabnew test_file.txt" and press Enter.
Cursor will be in line 1.
Press "j" (or "Down arrow"), "ZQ", "ZQ".
Vim will store mark "double quote" in file "~/.viminfo" and exit.

Run vim:

``` bash
./vim-7.4.319
```

Vim will read file "~/.viminfo".

Type ":tabnew test_file.txt" and press Enter.

End of test.

If you run executable "./vim-7.4.319",
after execute given steps
cursor will be at line 2 (as expected).

If you run executable "./vim-7.4.320",
after execute given steps
cursor will be at line 1 (bug).

Bug: since vim patch 7.4.320,
when using given steps (":tabnew" and "ZQ"),
mark "double quote"
not saved in file "~/.viminfo".

### PR DESCRIPTION
**Pull request by gregorias**
Problem:    Mark " is not set when closing a window in another tab. (Guraga)
Solution:   Check all tabs for the window to be valid. (based on patch by
            Hirohito Higashi, closes vim/vim#974)

https://github.com/vim/vim/commit/e59215c7dcae17b03daf39517560cfaa03314f5a

### CODE REVIEW

**Comment by gregorias** [comment]
Let me know what's the practice with *.vim test files. As I have written in #5500 - [wiki](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) discourages porting them. So, are there no tests written at all for these backporting patches?

**Comment by justinmk** [comment]
> wiki discourages porting them. So, are there no tests written at all for these backporting patches?

Sorry if it's not clear, but the wiki discourages porting them _to lua_. The .vim test files certainly should be ported over (into `src/nvim/testdir`).

**Comment by gregorias** [comment]
Thanks Justin, I will port that test soon and update this PR.

**Comment by gregorias** [comment]
The `.vim` test can not be ported as is, because it tests the legacy .viminfo functionality. I have written a lua version of that test instead.

**Comment by gregorias** [comment]
This is superseded now by #5500

**Pull request closed without merging**
