### PR TITLE
makes :e without arguments a no-op in terminal buffers

### PR DESCRIPTION
**Pull request by fmoralesc**
prevents issue #2779

TODO: really solve the issue...

### CODE REVIEW

**Comment by TheSoftwareGuy** [comment]
fixes issue here as well, at least technically, because I wouldn't consider this issue fully fixed

**Comment by fmoralesc** [comment]
Of course not, this was really just a test ;)

**Comment by TheSoftwareGuy** [comment]
ok, I guess the next step is to determine what ":e" should do in terminal mode.

**Comment by fmoralesc** [comment]
BTW, I'm closing this, I only opened the PR so the test was more readily available.

**Pull request closed without merging**
