### PR TITLE
feat(lsp): add exit_timeout flag

### PR DESCRIPTION
**Pull request by mjlbach**
* This flag allows customizing the time before sending kill -15 to the
  server. If set to 0, neovim exits immediately after sending
  request('shutdown'). Defaults to 500 ms.

### CODE REVIEW

**Comment by mjlbach** [comment]
Right now, it will block on the longest timeout. We could store the elapsed time, and then check against each server.

**Review by mfussenegger — APPROVED** [review]
> There's still the question of what 0 means, do we just send close and be done with it or kill the server? I assume the former.

I guess we could also use `-1` as a sentinel value to skip the kill and have `0` be a "no delay". But not sure if we gain anything by that.

I'm fine with it either way.

**Comment by mjlbach** [comment]
> I guess we could also use -1 as a sentinel value to skip the kill and have 0 be a "no delay". But not sure if we gain anything by that.

We could also have the sentinel value be `false`

**Comment by mjlbach** [comment]
@dimbleby Thanks, the fact that it closed so quickly helped me catch a small bug. Should close more slowly now :P (unless you use the flag)

**Comment by mjlbach** [comment]
@dimbleby Can you try this out with the flag and let me know that it works for your usecase?
```
flags = {
  exit_timeout = false
}
```

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
