### PR TITLE
[RFC] vim-patch:7.4.1847

### PR DESCRIPTION
**Pull request by lonerover**
**vim-patch:7.4.1847**
Problem:    Getting an item from a NULL dict crashes.  Setting a register to a
            NULL list crashes. (Nikolai Pavlov, issue vim/vim#768)  Comparing a NULL
            dict with a NULL dict fails.
Solution:   Properly check for NULL.

https://github.com/vim/vim/commit/13ddc5c35921efa69e980284117b6db6465e019c

### CODE REVIEW

**Comment by lonerover** [comment]
Test failed, because of missing test_null_dict() and test_null_list() in eval.c. They were brought in vim-patch 7.4.1838, market as NA in https://github.com/neovim/neovim/pull/5743. Should we add 
these two functions now?

**Comment by mhinz** [comment]
Hmm, I think the entire 7.4.1838 should be added then, yup.

@jamessan What do you think?

**Comment by jamessan** [comment]
We've been excluding the `test_*` functions as gross hacks that shouldn't be part of the user's API.  In some cases, we've been able to get coverage via other means, but not all.

**Comment by mhinz** [comment]
Oh, I didn't realise they were hardcoded in that patch.

I guess we should simply omit the tests then, eh?

**Comment by justinmk** [comment]
We already define `v:_null_dict` and `v:_null_list`, so in this case we don't need test_null_dict/test_null_list.

**Comment by jamessan** [comment]
Just needs the lint issues fixed:

```
src/nvim/eval.c:5168:  if should always use braces  [readability/braces] [5]
src/nvim/eval.c:6661:  if should always use braces  [readability/braces] [5]
```

**Comment by jamessan** [comment]
Lint checks gradually expand around parts of the code that have been touched, so your previous lint fixes triggered more:

```
src/nvim/eval.c:5169:  Use false instead of FALSE.  [readability/bool] [4]
src/nvim/eval.c:5171:  if should always use braces  [readability/braces] [5]
```

You can run `make clint LINT_FILE=src/nvim/eval.c` locally to verify the lint checks are clean after a round of lint cleanups.

Although not a big deal for this PR, common practice is to port whatever upstream patches are being handled in a PR and then have a final "lint" commit so the functional changes are separate from the stylistic changes.

**Comment by jamessan** [comment]
Merged in 3b793d04.  Thanks!

**Pull request closed without merging**
