### PR TITLE
fix(terminal): correctly forward mouse events

### LINKED ISSUE #16371: No mouse release events in terminal mode
### Neovim version (nvim -v)

NVIM v0.6.0-dev+600-gf71be1f87

### Vim (not Nvim) behaves the same?

no, vim 8.2 does send mouse release events

### Operating system/version

macOS 11.3.1

### Terminal name/version

kitty but tested on many

### $TERM environment variable

xterm-kitty but tested on many

### Installation

brew neovim-nightly

### How to reproduce the issue

1. install go
2. download [tcell mouse demo](https://github.com/gdamore/tcell/blob/master/_demos/mouse.go)
3. run `:set mouse=a`
2. open a terminal in nvim using `:term`
2. run `go run mouse.go`
3. select an area with the mouse

### Expected behavior

After releasing the mouse button the selected area should be green.
In both vim and a plain terminal this behaviour can be observed

### Actual behavior

The area only becomes green after triggering some other mouse event (tcell assumes that event is a mouse release)

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #16371.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Tests are hard to write...

**Comment by zeertzjq** [comment]
Test fails if I revert the change:
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] test/functional/terminal/mouse_spec.lua @ 63: :terminal mouse when the terminal has focus with mouse events enabled by the program will forward mouse press, drag and release to the program
test/functional/terminal/mouse_spec.lua:96: Row 6 did not match.
Expected:
  |line27                                            |
  |line28                                            |
  |line29                                            |
  |line30                                            |
  |mouse enabled                                     |
  |*         #$#{1: }                                     |
  |{3:-- TERMINAL --}                                    |
Actual:
  |line27                                            |
  |line28                                            |
  |line29                                            |
  |line30                                            |
  |mouse enabled                                     |
  |*      @$#{1: }                                        |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:595: in function '_wait'
	test/functional/ui/screen.lua:362: in function 'expect'
	test/functional/terminal/mouse_spec.lua:96: in function <test/functional/terminal/mouse_spec.lua:63>


 1 FAILED TEST
```

**Review by erw7 — APPROVED** [review]
I checked `terminal.c` of vim and found the same process, so I think this change is fine.

**Comment by bfredl** [comment]
@zeertzjq LGTM, rebase?

**Comment by zeertzjq** [comment]
Hmm, CI seems to be encountering some Internet problems.

**Comment by zeertzjq** [comment]
Lint is probably gonna time out. It's been checking out for 25 minutes. I ran `./src/clint.py src/nvim/terminal.c` locally and it doesn't report anything wrong.

**Comment by zeertzjq** [comment]
Oh, CI passed.

**Comment by Kavantix** [comment]
Would be nice to have a build with this fix 😇

**Comment by zeertzjq** [comment]
ping @bfredl

**Comment by bfredl** [comment]
Thanks!

**Pull request merged**
