### PR TITLE
API: Avoid overrun when formatting error-message

### PR DESCRIPTION
**Pull request by justinmk**
When we build an API String internally (e.g. cstr_to_string), typically
we NUL-terminate it.  But we don't do that for incoming String
arguments. (Should we?)

### CODE REVIEW

**Comment by justinmk** [comment]
@bfredl I considered modifying `gen_api_dispatch.lua` (or whatever) to NUL-terminate and increment `String.size` of all incoming `String` parameters. But maybe that's too surprising because then the size & data do not match the original msgpack payload. Any opinion on this?

**Comment by justinmk** [comment]
I should have mentioned that I noticed this because on my machine this shows garbage after the method name:

```
:let c = sockconnect('pipe', v:servername, {'rpc':1})
:echo rpcrequest(c, 'foo')                           

Invalid method: foo<90>
```

**Comment by bfredl** [comment]
Hmm, are you sure that doesn't use an internal channel (check with `nvim_get_chan_info(c).internal`), and not msgpack?

**Comment by justinmk** [comment]
@bfredl after reverting the `api_set_error(... "... %.*s"` changes, this test fails:

```lua
    expect_err('Invalid method: bogus$',
               request, 'bogus')
```

`request` performs RPC from the Lua client, so I guess method names aren't NUL-terminated by msgpack-C (even though [the spec](https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md) defines a method as "a string" which implies "not BIN"). 

The earliest place I see to ensure NUL-termination is in `msgpack_rpc_get_handler_for`, because that inspects the result popped from `msgpack_unpacker_next`. 

But now I wonder if we should depend on msgpack-C implicitly doing this. Also AFAICT libmpack doesn't NUL-terminate msgpack-RPC strings (@tarruda can you confirm).

**Comment by bfredl** [comment]
> The earliest place I see to ensure NUL-termination is in msgpack_rpc_get_handler_for,

The earliest place is where we construct API object values from msgpack to start with.

> Also AFAICT libmpack doesn't NUL-terminate msgpack-RPC strings.

It doesn't for the simple reason that libmpack doesn't allocate anything at all, it would be up to us to use xmallocz when copying data from libmpack's buffer.

**Comment by bfredl** [comment]
I just looked the code, and `msgpack_rpc_to_string` already uses xmemdupz, i e it allocates an extra NUL at string.data[string.size], just as expected. So I don't think we can blame msgpack-c for any trouble.

**Comment by bfredl** [comment]
Looking a bit more, it seems `msgpack_rpc_get_handler_for` does its own unsafe conversion to `String` (I would have assumed all conversion was done using a single consistent code path.) I think `map_get` doesn't care as it uses `size`, the only thing that would be need to be fixed is the `api_set_error` inside that function, all other "fixed" api_set_error calls can be reverted (as parameter String:s are already NUL-terminated).

**Pull request merged**
