### PR TITLE
fix: correctly capture uri scheme on windows 

### LINKED ISSUE #15261: LSP with clangd not recieving autocompletion -- Problem with file URI scheme apparently
### Neovim Version

NVIM v0.6.0-dev+80-gc818d8df3

### Language server name/version:

Built-in LSP

### Operating system/version:

Windows 10 21H1

### Checkhealth

```markdown
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.

health#compe#check
========================================================================
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>     compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>          compe#confirm("<CR>")`)
  - INFO: `compe#close` is not mapped
  - INFO: `compe#scroll` is not mapped
```

### Steps to reproduce

-- install packer
local fn = vim.fn

local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

vim.cmd [[set packpath=/tmp/nvim/site]]

local function load_plugins()
  local use = require('packer').use
  require('packer').startup {
    function()
      use 'wbthomason/packer.nvim'
      use 'neovim/nvim-lspconfig'
    end,
    config = { package_root = '/tmp/nvim/site/pack' },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'debug'
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'clangd'
  local cmd = { 'clangd', '--clang-tidy', '--background-index', '--all-scopes-completion', '--header-insertion=iwyu', '--completion-style=detailed', '--log=verbose', '--query-driver=D:\\Code\\Compilers\\TDM-GCC-64\\bin\\g*', '--cross-file-rename' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if fn.isdirectory(install_path) == 0 then
  fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd 'autocmd User PackerComplete ++once lua load_config()'
else
  load_plugins()
  _G.load_config()
end

### Expected behavior

Have some completion from LSP clangd Server using <c-x><c-o> in insert mode

### Actual behavior

Don't have any completion from LSP.

### Link to uploaded log file

https://gist.github.com/dantearaujo1/96d886081a01559a1ebee80eb9c339ba

### PR DESCRIPTION
**Pull request by mjlbach**
Closes: #15261
* Why are we matching to determine if the filepath is windows? Can't we just use uv.os_uname?

* I feel like some of these uri functions are a little redundant, one saves like 2 lines.
* I wish we had pcre as a dep, because then we could use the vscode regex (I'm not translating it into a vim regex)

cc @donbex

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Is it possible to add a test for this?

> Why are we matching to determine if the filepath is windows? Can't we just use uv.os_uname?

Is it conceivable that someone running neovim under Linux or MacOS has to deal with windows URIs for whatever reason?

**Comment by mjlbach** [comment]
> Is it conceivable that someone running neovim under Linux or MacOS has to deal with windows URIs for whatever reason?

I don't think so. I guess it's fine, it makes tests easier. I just want to minimize any match/regex calls in hot paths.

**Review by mfussenegger — APPROVED** [review]

**Comment by adelarsq** [comment]
Nice! Thanks for the fix. I will test this on the next week with Dart LSP, where I notice this problem.

**Comment by justinmk** [comment]
> * I wish we had pcre as a dep, because then we could use the vscode regex (I'm not translating it into a vim regex)

PCRE to Lua pattern? https://stackoverflow.com/questions/42499870/lua-lrex-lib-pcre-pattern-matching

Is "Javascript regex" exactly equal to PCRE ? 

> * I feel like some of these uri functions are a little redundant, one saves like 2 lines.

yeppp... ;)

> * Why are we matching to determine if the filepath is windows? Can't we just use uv.os_uname?

I wonder about WSL <=> nvim win32 scenarios. Not sure though.

**Pull request merged**
