### PR TITLE
refactor: format files with uncrustify

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by lockejan** [comment]
Why is it a good idea to run a formatter against old code? This completely overwrites authored code changes of the past. 🤔

**Comment by muniter** [comment]
@lockejan https://github.com/neovim/neovim/pull/15653

**Comment by justinmk** [comment]
> Why is it a good idea to run a formatter against old code? This completely overwrites authored code changes of the past. 🤔

It completely doesn't. Besides being available in `git log` search, https://github.com/neovim/neovim/pull/15653 also allows `git blame` to effectively ignore these style-only changes.

Also give that the project has style guidelines, these changes are required anyway.

**Comment by lockejan** [comment]
> > Why is it a good idea to run a formatter against old code? This completely overwrites authored code changes of the past. 🤔
> 
> It completely doesn't. Besides being available in `git log` search, #15653 also allows `git blame` to effectively ignore these style-only changes.
> 
> Also give that the project has style guidelines, these changes are required anyway.

Wow, thanks for the explanation and refs guys. I wasn't aware of git-blame-ignore-revs. 🤯🚀 Now it makes sense and I even learned a new thing about git.

**Pull request merged**
