### PR TITLE
runtime: ignore more autocmds in man plugin

### LINKED ISSUE #8939: :Man doesn't work with vim-projectionist
- `nvim --version`:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/config -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/include
Skompilowany przez brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

       vimrc systemu: "$VIM/sysinit.vim"
   odwet dla $VIM-a: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: `Darwin Niuniobook.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
- Terminal name/version: iTerm2
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

- Install [projectionist](https://github.com/tpope/vim-projectionist)
- Run `nvim +Man\ true`

### Actual behaviour

Fails with error that it cannot close last window. If there are more than one window it fails due to unknown `-l` flag in macOS man.

### Expected behaviour

It should display window with manpage for `true`.

### PR DESCRIPTION
**Pull request by dm1try**
fix #8939

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for looking into this! 

But, reviewing c8ee0be7451ed5bf02a87270fa47fbb1372aa85d suggests that this 'eventignore' was only a  workaround to avoid [man.vim's _own_ re-initialization](https://github.com/neovim/neovim/blob/c8ee0be7451ed5bf02a87270fa47fbb1372aa85d/runtime/plugin/man.vim#L12), which is achieved by `BufReadCmd`. 

Ignoring other events certainly prevents problems with plugins like projectionist.vim, but it  also prevents plugins (or user's config) from doing things the user actually wants. `BufReadCmd` is a special-case that is safe to ignore.

So the question is, what is projectionist.vim doing that causes man.vim to try to close the window? 

Are you able to reproduce the issue?

**Comment by dm1try** [comment]
> but it also prevents plugins (or user's config) from doing things the user actually wants

yeah, I was thinking about this and could not imagine any practical usage in the context of "man" plugin

> Are you able to reproduce the issue?

yep, but I did not dig into this; I used `:noautocmd Man true`  and then exclude some "autocmd" from "projectionist"
btw, after the initialization with `:noautocmd` next man commands work fine

>So the question is, what is projectionist.vim doing that causes man.vim to try to close the window?

will look into this one more time a little bit later today

**Comment by dm1try** [comment]
ok, I improved my neovim debugging skills a little bit =)

first, this issue is easily reproducible on macOS, because of `-l` flag of `man` tool which is absent on this OS(but I think is just hidden on different os). there is a [special check](https://github.com/neovim/neovim/blob/master/runtime/autoload/man.vim#L25-L27) which set `s:localfile_arg = v:false`; so the first call to `man` set this flag to false if OS does not support it(by catching the exception), then next calls use the flag; by default `s:localfile_arg = v:true`

the funny thing that with loaded "projectionist" plugin `s:localfile_arg` on a subsequent request to `man`  is **true** despite the fact that is was just set to `false`. why?! because the call to `ProjectionistDetect(expand('<afile>:p'))` actually **reloads**[[1](https://github.com/tpope/vim-projectionist/blob/master/plugin/projectionist.vim),[2](https://github.com/tpope/vim-projectionist/blob/master/plugin/projectionist.vim#L36-L40)] the "man" plugin from runtime.
"projectionist" detection logic does not play nice with URI of man buffer:
`call ProjectionistDetect(expand('<afile>:p'))` => `ProjectionistDetect(expand('man://curl'))` => ... `s:load("man")`

**Comment by justinmk** [comment]
Nice, can you try adding a [guard](https://github.com/neovim/neovim/blob/5d2af7e45200c1e3337624449fe2be0906d1c7cf/runtime/plugin/man.vim#L3-L6) to that file? But use a script-local variable (`s:loaded_man`) in this case.

**Comment by dm1try** [comment]
> However that logic in projectionist seems like it will break a lot of plugins, which generally should be able to assume that autoloaded files are not going to be reloaded.

agreed, should be fixed also; I do not use "projectionist" atm; it looks like it's [a fresh addition](https://github.com/tpope/vim-projectionist/commit/ee508617e37932117f7e57ee62bc97540b7b2e9f) 
so there is already an issue in "projectionist" repo =)

**Pull request merged**
