### PR TITLE
fix(lsp): shrink the reported changed lines range down to actually modified lines before computing diff in incremental syncer

### PR DESCRIPTION
**Pull request by dmitmel**
(This was initially devised as my fix for #16274, but I figured that it is still good to include in addition to #16308)

It is known that `on_lines` callback sometimes receives "inefficient" events whose firstline/lastline ranges are wider that the actual range of lines which were modified by a text change. This used to cause crashes in `sync.compute_diff` because it would assume that the lines pointed to by firstline and lastline+new_lastline were the actual boundaries of the changed text and that there was some difference between `curr_lines[firstline]` and `prev_lines[firstline]`, which is not always the case, as evident from #16274. The fix in #16308 handles this, but essentially just checks if the first and last lines of the change range are different, and if they are the same, it skips just those ones. My PR improves this further by skipping all lines from the start (firstline and forwards) and end (lastline+new_lastline and backwards) of the reported range to find the actual boundaries if the change range (i.e. shrinking the range), and can detect if an on_lines event was emitted with no real changes at all.

I have also included a seemingly unrelated change in the `on_reload` handler. The thing is that this PR causes a rare bug in the `on_reload` implementation appear more frequently (stashed didChange events, which apply to the previous state of the buffer, are not flushed or forgotten before didClose and didOpen, and so can be sent for the new state when the debounce timer runs out). Strictly speaking, this is the scope of #16431, so once that PR is done the line with `changetracking.flush` can be removed without any concerns, but the bug was annoying enough and the fix was simple enough that I included it here for now. I can delete the line though, ofc.

I also want to mention that I have been test-driving the changes I've made to `lsp/sync.lua` through a monkey-patch for the past couple of weeks, and it works perfectly fine.

<details>

```lua
local lsp_sync_available, lsp_sync = pcall(require, 'vim.lsp.sync')
if lsp_sync_available then
  local orig_compute_diff = lsp_sync.compute_diff
  function lsp_sync.compute_diff(prev_lines, curr_lines, firstline, lastline, new_lastline, offset_encoding, line_ending)
    for _ = firstline + 1, math.min(lastline, new_lastline) do
      if prev_lines[firstline + 1] ~= curr_lines[firstline + 1] then
        break
      end
      firstline = firstline + 1
    end
    if lastline == new_lastline and firstline == new_lastline then
      return nil
    end
    for _ = math.min(lastline, new_lastline), firstline + 1, -1 do
      if prev_lines[lastline] ~= curr_lines[new_lastline] then
        break
      end
      lastline = lastline - 1
      new_lastline = new_lastline - 1
    end
    return orig_compute_diff(prev_lines, curr_lines, firstline, lastline, new_lastline, offset_encoding, line_ending)
  end
end
```

</details>

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
a) Please don't mix multiple changes into a PR. It makes reviewing code more difficult. The changes you included are already addressed by another PR

b) I don't like that we add performance optimization workarounds  like this. If the range reported by `on_lines` is bigger than it needs to be, the question is why is it bigger and if we can fix that. (And help any plugin using this, instead of just the LSP use-case)

**Comment by dmitmel** [comment]
> a) Please don't mix multiple changes into a PR. It makes reviewing code more difficult. The changes you included are already addressed by another PR

I'm sorry, I'll remove that line right away (plus the other PR has just been merged).

> b) I don't like that we add performance optimization workarounds like this. If the range reported by `on_lines` is bigger than it needs to be, the question is why is it bigger and if we can fix that. (And help any plugin using this, instead of just the LSP use-case)

There are many things that cause the inefficient events, even very simple ones, such as `nvim_buf_set_lines(_, firstline_param, lastline_param, _, _)` always causing an `on_lines` event for the range `firstline_param` to `lastline_param` (see https://github.com/neovim/neovim/issues/16274#issuecomment-966703878). Also, efficiency is not a correctness guarantee given for `on_lines` (yet?), only that if the receiving end applies the events the order they were sent, it will result in the equivalent state of the buffer. The 0.6.0 release is close, so in the meantime I think that what I propose is a reasonable solution.

**Comment by dmitmel** [comment]
@mjlbach and me have come to the conclusion that this optimization is not worth it ([link to the Matrix chat](https://app.element.io/#/room/#nvim-dev:matrix.org/$vLZ6YUhv1LeyfSa2iuJjPkIe5AhtNP7ugEwXJFuh2kY)). Although I still wrote a benchmark which measures the improvement on all `compute_diff` invocations, but obviously, it needs data points from real editing, so I'll collect those over the next couple of days and will reopen the PR if the results are deemed significant.

**Comment by mjlbach** [comment]
If someone shows me a real world scenario of moderate frequency in which this optimization results in a tangible performance I will change my mind. Of note, I am planning on removing the on_lines sync code in favor of on_bytes in the 0.7 release cycle which should be universally faster
________________________________

**Pull request closed without merging**
