### PR TITLE
[WIP] vim-patch:7.4.2200

### PR DESCRIPTION
**Pull request by romgrk**
**vim-patch:7.4.2200**

Problem:    Cannot get all information about a quickfix list.
Solution:   Add an optional argument to get/set loc/qf list(). (Yegappan
            Lakshmanan)

https://github.com/vim/vim/commit/d823fa910cca43fec3c31c030ee908a14c272640

### CODE REVIEW

**Comment by romgrk** [comment]
Missing: 
 - tests: Should I port those directly or write them in lua?
 - doc: will update when the question below is answered

I've kept compatibility with the current Neovim implementation; if `{what}` is a string, it is used as the title. What do we do with that?

Closes https://github.com/neovim/neovim/issues/5314

**Comment by Shougo** [comment]
> tests: Should I port those directly or write them in lua?

You don't have to convert the tests to lua.
It is just wast of time.

**Comment by romgrk** [comment]
Oh, forgot to mention. I also commented out the part that handles the `winid`, because we haven't included those yet.

**Comment by romgrk** [comment]
@Shougo the tests in the patch are in `test_quickfix.vim`, but that file doesn't exist here.

**Comment by Shougo** [comment]
> @Shougo the tests in the patch are in test_quickfix.vim, but that file doesn't exist here.

It should be included, but neovim must include patches for quickfix.

We should include `winid` patches before it.

**Comment by romgrk** [comment]
Besides the fold things, the following test fails:
```
Failure → ...rk/github/neovim/test/functional/viml/errorlist_spec.lua @ 32

errorlist_spec.lua@32:
    exc = exc_exec('call setqflist([], "r", {})')
    eq('Vim(call):E731: using Dictionary as a String', exc)
```
Should be deleted I guess?

**Comment by Shougo** [comment]
new quickfix test is added in Vim 7.4.1614.
It is not included in neovim.

This is winid patches.
It should be included.
https://github.com/neovim/neovim/pull/5257

**Comment by Shougo** [comment]
> Should be deleted I guess?

No.  Many of quickfix patches are not included.
I have already listed.
neovim must include them before it.

**Comment by romgrk** [comment]
Ok, I was lost with all the commits, but actually we do have the `winid` thing already. (vim patch 1557)
However, `window_S.w_id` was changed to `window_S.handle` by https://github.com/neovim/neovim/commit/a2d25b7bf81728d913e7b317d33997c8b8268af2#diff-aea5ac6a6784947c12e7550683f5938dR937.

**Comment by romgrk** [comment]
And `test_quickfix.vim` was “included” by https://github.com/neovim/neovim/commit/da9b6b1de0120a86501293242073fbebe78395b7

**Comment by blueyed** [comment]
@romgrk 
Yes, winid came with 0d93cd6c.
Can you rebase this, please?

**Comment by romgrk** [comment]
Done. Still missing the tests and docs, quite busy.

**Comment by jamessan** [comment]
Continued this in #6188.

**Pull request closed without merging**
