### PR TITLE
build: add LTO information to --version output

### PR DESCRIPTION
**Pull request by sys9kdr**
# Problem

The current `nvim -V1 -v` and `:verbose version` outputs in Neovim lack information about LTO.

By default, Neovim build enables LTO without any special configuration, like so:

```console
make CMAKE_BUILD_TYPE=RelWithDebInfo
```

build/compile_commands.json includes LTO options `-flto=auto -fno-fat-lto-objects`:

```json
{
  "directory": "/home/username/workspace/neovim/build",
  "command": "/usr/bin/cc -DHAVE_UNIBILIUM -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -DUNIT_TESTING -D_GNU_SOURCE -Dnvim_EXPORTS -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src -isystem /home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -isystem /home/username/workspace/neovim/.deps/usr/include -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -o src/nvim/CMakeFiles/nvim.dir/main.c.o -c /home/username/workspace/neovim/src/nvim/main.c",
  "file": "/home/username/workspace/neovim/src/nvim/main.c",
  "output": "src/nvim/CMakeFiles/nvim.dir/main.c.o"
},
```

However, this is not reflected in `:verbose version`, which currently shows:

```
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result-Wimplicit-fallthrough -fdiagnostics-color=always -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/username/workspace/neovim/.deps/usr/include -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src
```

It should be includes LTO information like `-flto`.

# Solution

I tweaked the CMake configuration to add LTO build information. This results in the following output in `:verbose version`:

```
Compilation: /usr/bin/cc -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/username/workspace/neovim/.deps/usr/include -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src
```

This can be useful debugging info for users and developers.

Please let me know if any other details should be included in the description!

### CODE REVIEW

**Comment by justinmk** [comment]
> Please let me know if any other details should be included in the description!

Adding the details to the commit message would be ideal

**Review by justinmk — APPROVED** [review]

**Comment by dundargoc** [comment]
This doesn't look right. `flto` is always shown, even for debug builds.

**Comment by sys9kdr** [comment]
@dundargoc Thanks for confirming.

Maybe `CMAKE_C_COMPILE_OPTIONS_IPO` contains the default LTO settings for each platform instead of the actual settings.

Should I write code to check the LTO status and separate the process according to true/false?

**Comment by sys9kdr** [comment]
@dundargoc  With https://github.com/neovim/neovim/pull/26554/commits/4bb9498fac4e724a2c8741d28fdfd5378ae1fcef , I added check Debug or not.
It may not be ideal code, but at least it should work as expected.

If there are no problems, I will organize commits, add details, and force push so that we can merge.
If there are any problems, I will do what I can to fix them.

Debug:

```console
$ rm -rf build && make
# ...
$ ./build/bin/nvim -V1 -v
NVIM v0.10.0-dev-e4302e1-dirty
Build type: Debug
LuaJIT 2.1.1702233742
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -DNVIM_LOG_DEBUG -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/username/workspace/neovim/.deps/usr/include -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

RelWithDebInfo: 

```console
$ rm -rf build && make CMAKE_BUILD_TYPE=RelWithDebInfo
# ...
$ ./build/bin/nvim -V1 -v
NVIM v0.10.0-dev-e4302e1-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Compilation: /usr/bin/cc -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/username/workspace/neovim/.deps/usr/include -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by dundargoc** [comment]
I know I mentioned debug, but ignore that lol. I think it's more correct to check if `ENABLE_LTO` is true instead of debug build. It's possible to use LTO even with debug.

**Comment by sys9kdr** [comment]
> I know I mentioned debug, but ignore that lol. I think it's more correct to check if ENABLE_LTO is true instead of debug build. It's possible to use LTO even with debug.


```diff
diff --git a/cmake.config/CMakeLists.txt b/cmake.config/CMakeLists.txt
index 6b3a2fc..be64538 100644
--- a/cmake.config/CMakeLists.txt
+++ b/cmake.config/CMakeLists.txt
@@ -145,7 +145,7 @@ if(C_FLAGS_VERSION_OUTPUT)
   string(PREPEND C_FLAGS_VERSION_OUTPUT " ")
 endif()

-if(NOT CMAKE_BUILD_TYPE MATCHES "Debug")
+if(ENABLE_LTO)
   set(C_LTO_VERSION_OUTPUT ${CMAKE_C_COMPILE_OPTIONS_IPO})
   if(C_LTO_VERSION_OUTPUT)
     string(REPLACE ";" " " C_LTO_VERSION_OUTPUT "${C_LTO_VERSION_OUTPUT}")
```

**Comment by dundargoc** [comment]
Yeah, that change looks good

**Comment by sys9kdr** [comment]
Sorry, I accidentally posted while typing.

> I know I mentioned debug, but ignore that lol. I think it's more correct to check if ENABLE_LTO is true instead of debug build. It's possible to use LTO even with debug.

I don't know why, but `ENABLE_LTO` is `true` even in debug.

updated cmake.cofig/CMakeLists.txt:

```diff
diff --git a/cmake.config/CMakeLists.txt b/cmake.config/CMakeLists.txt
index 6b3a2fc..be64538 100644
--- a/cmake.config/CMakeLists.txt
+++ b/cmake.config/CMakeLists.txt
@@ -145,7 +145,7 @@ if(C_FLAGS_VERSION_OUTPUT)
   string(PREPEND C_FLAGS_VERSION_OUTPUT " ")
 endif()

-if(NOT CMAKE_BUILD_TYPE MATCHES "Debug")
+if(ENABLE_LTO)
   set(C_LTO_VERSION_OUTPUT ${CMAKE_C_COMPILE_OPTIONS_IPO})
   if(C_LTO_VERSION_OUTPUT)
     string(REPLACE ";" " " C_LTO_VERSION_OUTPUT "${C_LTO_VERSION_OUTPUT}")
```

debug:

```
NVIM v0.10.0-dev-4bb9498-dirty
Build type: Debug
LuaJIT 2.1.1702233742
Compilation: /usr/bin/cc -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -DNVIM_LOG_DEBUG -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/username/workspace/neovim/.deps/usr/include -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

relwithdebinfo:

```
NVIM v0.10.0-dev-4bb9498-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Compilation: /usr/bin/cc -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/username/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/username/workspace/neovim/.deps/usr/include -I/home/username/workspace/neovim/build/src/nvim/auto -I/home/username/workspace/neovim/build/include -I/home/username/workspace/neovim/build/cmake.config -I/home/username/workspace/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by sys9kdr** [comment]
my cmake version `cmake version 3.28.0`

**Comment by dundargoc** [comment]
Oh yeah, looking at the code that won't work either. Hmm, let me take a look at this more thoroughly, give me some time.

**Comment by dundargoc** [comment]
Sorry, I will close this down as the version generation needs a severe refactor, and also because implementing this requires insane cmake generator expression shenanigans that I wouldn't wish on my worst enemies. But please do try out my PR to see if it works as expected.

Supersed by https://github.com/neovim/neovim/pull/26582.

**Comment by sys9kdr** [comment]
Yeah, it looks good. I am free from the LTO issue and the infernal CMake version strings.

**Pull request closed without merging**
