### PR TITLE
Cursor position is not maintained when lines are added

### PR DESCRIPTION
**Pull request by hashinclude**
Code for this was removed in #9674. Re-added it.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for the effort! Can you say what steps reproduce the issue? And maybe add a test?

See `test/functional/example_spec.lua` for an example. You can [run the test](https://github.com/neovim/neovim/blob/master/test/README.md#running-tests) like this:

    TEST_FILE=test/functional/example_spec.lua make functionaltest

Also I wonder if `reset_lnums` from https://github.com/vim/vim/commit/a68e59590905da9b4448ff1fcac929ad1a18da9e could be used instead, somehow. Could try that in a separate commit.

**Comment by hashinclude** [comment]
Thanks!

I added some tests.
Regarding reproducing the issue, we use an internal plugin at work to auto insert imports at the top of the file. This issue was causing the cursor to go to the previous line after the import was inserted on top.

**Comment by bfredl** [comment]
Thanks! It would be nice to also have the following test: split the window in two (with same buffer) and check the cursor is moved correctly in both current and non-current window (with the same operations as the added test).

**Comment by justinmk** [comment]
Merged

**Pull request closed without merging**
