### PR TITLE
vim-patch:7.4.{1000, 1001, 1030, 1282, 1284}

### PR DESCRIPTION
**Pull request by KillTheMule**
This started off as a port of 7.4.1282, but needed additional patches. I collected the smallest possible set that made sense.

I will need some help integrating https://github.com/KillTheMule/neovim/blob/vim-patch-1282/src/nvim/testdir/test_viml.vim into the build system, I'll try to find someone on gitter.

I could not reproduce the issue of 7.4.1282 (neither in vim nor nvim), so I could not write a test.

### CODE REVIEW

**Comment by KillTheMule** [comment]
Am I handling version.c correctly? I'm jumping off https://github.com/Shougo/neovim/commit/7261ae985f6a42fcd9d121febb9eb9c07de0c20f looking for patches to port, but I'm basing changes to version.c on current master... Makes sense somewhat, but might make merging harder later on.

**Comment by KillTheMule** [comment]
I'm stumped. The travis failure look really weird, but made me realize there's `make oldtest`, and sure enough, test49.vim fails. It's testing the exact thing that was fixed in the patch (so it should be ok before and fail after this patch, which I confirmed). Latest vim still contains this exact test, but it passes (patch still applied). Is there something different about viml exception handling in nvim compared to vim?

I have no idea how to go on, and my viml is barely existant, so I'd be grateful for any hint.

 Explanation: test49.vim fails at Test 65: https://github.com/neovim/neovim/blob/master/src/nvim/testdir/test49.vim#L6524, the numbers indicate that https://github.com/neovim/neovim/blob/master/src/nvim/testdir/test49.vim#L6594 evaluated to true, which means the wrong catch clause at https://github.com/neovim/neovim/blob/master/src/nvim/testdir/test49.vim#L6576 did not eat the exception, but threw its own, so that https://github.com/neovim/neovim/blob/master/src/nvim/testdir/test49.vim#L6586 caught it. Which is pretty much is what this patch is supposed to make happen (otherwise, the wrong catch clause would have 'eaten' the exception so that https://github.com/neovim/neovim/blob/master/src/nvim/testdir/test49.vim#L6586 can't catch anything and the finally clause only is applied).

**Comment by Shougo** [comment]
> src/nvim/ex_eval.c:1379:  if should always use braces  [readability/braces] [5]

Still lint failed.

> Am I handling version.c correctly? I'm jumping off Shougo@7261ae9 looking for patches to port, but I'm basing changes to version.c on current master... Makes sense somewhat, but might make merging harder later on.

LGTM.

Yes, my changes should be included...
The reviewer is needed.

**Comment by KillTheMule** [comment]
I know about the linter, but I'll have to wait for tonight to fix.

Maybe it would make sense to first merge https://github.com/Shougo/neovim/commit/7261ae9  and then I'd simply rebase.

**Comment by KillTheMule** [comment]
Ok, I think this is done. I have added test_viml.vim to the build (make oldtest). There is a test failure in server_spec.lua, but that's on current master as well, and seems unrelated. Everything else passes, at least locally, so I'll remove the [WIP].

I don't understand the failures on the default build, if they point to a mistake I made please point that out, all I see is java errors because of missing tap files (whatever that is...).

**Comment by justinmk** [comment]
@KillTheMule Thanks for this. I have updated the wiki to note that vim-patch PRs should not bother to convert new-style tests. The new-style tests are good enough and it's a useful benchmark for us to know that we are passing (a subset of) exactly the same test-suite as Vim.

**Pull request merged**
