### PR TITLE
feat: use nvim_buf_set_extmark for vim.highlight        

### LINKED ISSUE #13647: on_yank highlighting gets overshadowed by vim.lsp.buf.document_highlight() highlighting
- `nvim --version`:NVIM v0.5.0-dev+965-gd0668b36a-dirty
- Operating system/version: MacOS Mojave 10.14.6
- Terminal name/version: Kitty
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

The following config

```lua
vim.lsp.gopls.setup {
    on_attach = function(client)
        vim.api.nvim_command [[ hi LspReferenceText guibg=#ffff00 ]]
        vim.api.nvim_command [[autocmd CursorHold  <buffer> lua vim.lsp.buf.document_highlight()]]
        vim.api.nvim_command [[autocmd CursorHoldI <buffer> lua vim.lsp.buf.document_highlight()]]
        vim.api.nvim_command [[autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()]]
        vim.api.nvim_command [[ autocmd TextYankPost * lua require'vim.highlight'.on_yank() ]]
    end
}
```

And with nvim-lspconfig loaded.

### Actual behaviour

When yanking a line where `document_highlight` has applied highlighting to symbols on that line, the yank highlighting does not supersede the highlighting that was already applied first by `document_highlight()`.

In the screenshot below, my cursor was held on `Println` which triggered `document_highlight` that applied the yellow highlighting, then I did `yy` which triggered `on_yank` and applied the pink highlighting on the line. However the second pink highlighting does not replace the yellow highlighting.

Screen Shot 2020-12-30 at 2 58 25 PM
Screen Shot 2020-12-30 at 2 58 20 PM

### Expected behaviour

I would expect the pink highlighting from `on_yank` to replace the `yellow` highlighting since it was applied second.

I also noticed that the `on_yank` highlighting doesn't fully highlight the `<tab>` at the start of the line. We can ignore that for now though.

I looked into it a bit this morning but they both seem to be using `vim.highlight.range`, tn or tmrw I'll try debugging a bit more and update here if I find anything. If anyone has an idea though let me know.

### PR DESCRIPTION
**Pull request by mjlbach**
Closes https://github.com/neovim/neovim/issues/13647                                                                                                                                        
                                                                                                  
Depends on #17001
                                                  
This allows customizing the priority of the highlights.                                                                                                                                     
                                                                                                                                                                                            
* Add default priority of 50                                                                                                                                                                
* Use priority of 60 for highlight on yank         
* Use priority of 40 for highlight references (LSP)

### CODE REVIEW

**Comment by mjlbach** [comment]
Test failures are because diagnostics are set out of range.

**Comment by mjlbach** [comment]
```lua
-- Test
local api = vim.api

local function exthighlight(bufnr, ns, higroup, start, finish, rtype, inclusive, priority)
  rtype = rtype or 'v'
  inclusive = inclusive or false
  priority = priority or 50

  -- sanity check
  if start[2] < 0 or finish[1] < start[1] then return end

  local region = vim.region(bufnr, start, finish, rtype, inclusive)
  for linenr, cols in pairs(region) do
    local end_row
    if cols[2] == -1 then
      end_row = linenr + 1
      cols[2] = 0
    end
    api.nvim_buf_set_extmark(bufnr, ns, linenr, cols[1], {
      hl_group = higroup,
      end_row = end_row,
      end_col = cols[2],
      priority = priority
    })
  end

end

local function highlight(bufnr, ns, higroup, start, finish, rtype, inclusive)
  rtype = rtype or 'v'
  inclusive = inclusive or false

  -- sanity check
  if start[2] < 0 or finish[1] < start[1] then return end

  local region = vim.region(bufnr, start, finish, rtype, inclusive)
  for linenr, cols in pairs(region) do
    api.nvim_buf_add_highlight(bufnr, ns, higroup, linenr, cols[1], cols[2])
  end

end

local bufnr = 0
local yank_ns = api.nvim_create_namespace('hlyank')
api.nvim_buf_clear_namespace(bufnr, yank_ns, 0, -1)

local higroup = "IncSearch"
exthighlight(bufnr, yank_ns, higroup, { 0,0 }, { 0, 10 }, nil, nil, 40)
highlight(bufnr, yank_ns, higroup, { 0,0 }, { 0,10 }, nil, nil)

```

**Comment by clason** [comment]
Do we want to change the interface to the standard `(foo, bar, { baz=quux })` pattern, i.e., move most of the options to keyword-style arguments? (Those functions are _old_...)

**Comment by mjlbach** [comment]
> Do we want to change the interface to the standard (foo, bar, { baz=quux }) pattern, i.e., move most of the options (regtype, inclusive, priority) to keyword-style arguments? (Those functions are old...)

I would like to, but I think it can be done in a separate PR.

**Comment by mjlbach** [comment]
Note, highlight_on_yank is broken for some reason.

**Comment by mjlbach** [comment]
@bfredl this should be good to go

@gpanders are you ok with the diagnostic test changes? It's not necessary for this PR anymore, so I can revert back.

**Comment by gpanders** [comment]
> @gpanders are you ok with the diagnostic test changes?

Yes it looks fine to me.

**Review by clason — APPROVED** [review]

**Pull request merged**
