### PR TITLE
feat: add vim.text module

### PR DESCRIPTION
**Pull request by gpanders**

### CODE REVIEW

**Comment by max397574** [comment]
wasn't there recently a discussion whether the `vim.base64`, the `vim.mpack` and the `vim.json` should be moved into a module together?
Perhaps when adding another encoding/decoding thing it could be considered creating such a module and moving those functions inside it.

**Review by justinmk — APPROVED** [review]
The intention for `vim.text` is things like `dedent()`/`indent()` and other common text operations (which are not already well-provided for by existing Vim functions) could live in here.  See also: https://github.com/neovim/neovim/issues/25272#issuecomment-1729294143

**Comment by clason** [comment]
Do we want to move the markdown conversion utility function here already, as we discussed? @MariaSolOs @mfussenegger

**Comment by gpanders** [comment]
> Do we want to move the markdown conversion utility function here already, as we discussed? @MariaSolOs @mfussenegger

Let's please do this in a separate PR so that we can unblock https://github.com/neovim/neovim/pull/26064.

**Pull request merged**
