### PR TITLE
ci: add dependabot to auto-update github actions

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
Reference:
* https://github.com/neovim/neovim/pull/22330

image
image

Edit: Added images to show Dependabot's PRs.

### CODE REVIEW

**Comment by clason** [comment]
Can you add a description what this action does (check and warn, open update PRs, merge them etc)?

Do we really want "daily"? How often do we expect these updates? (Other projects use a weekly schedule to avoid being flooded with automated PRs.)

We probably also want to integrate this into our other CI (avoid triggering some other actions, which you can do with `github.actor == 'dependabot[bot]'`).

**Comment by dundargoc** [comment]
> Edit: Added images to show Dependabot's PRs.

Those are some dank images. I'm convinced.

**Comment by fsouza** [comment]
> Do we really want "daily"? How often do we expect these updates? (Other projects use a weekly schedule to avoid being flooded with automated PRs.)

in my experience, running `github-actions` daily is fine. "daily" becomes annoying for things like npm and pip.

**Pull request merged**
