### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by sakhnik**

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! Is a file missing from the commit? Or why so many deletions?

Can any Ukrainian speaker give this a look?

**Comment by sakhnik** [comment]
Apparently, cleanup.vim deleted comments with references to the source code.
Besides that, I removed obsolete unused messages.

**Comment by sakhnik** [comment]
It was a bad idea to rebase

**Comment by justinmk** [comment]
Looks like a merge rather than a rebase. try `git fetch --all && git rebase upstream/master`

**Comment by sakhnik** [comment]
Yes, mixed things up completely. So I forked again to have clean history in my origin, created a dedicated branch, and resubmitted another pull request.

**Pull request closed without merging**
