### PR TITLE
fix(tui): fix possible deadlock issue

### LINKED ISSUE #15943: deadlock with :suspend
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

unsure since the issue is not reliably reproduced.

### Operating system/version

Fedora Linux 34

### Terminal name/version

GNOME Terminal 3.40.3 using VTE 0.64.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

Official Fedora build

### How to reproduce the issue

I'm not totally sure how to reproduce the issue, because it can't be reproduced reliably. But it has happened to me about 3 times now. As far as I can tell, it usually occurs after I've switched to a different window (alt+tab) and done some work and then come back to my terminal window running neovim. When it happens, neovim is hung and completely unresponsive.

### Expected behavior

neovim continues working normally without deadlock

### Actual behavior

neovim deadlock:

```
(gdb) t a a bt

Thread 2 (Thread 0x7fe16c0e2640 (LWP 93187) "nvim"):
#0  0x00007fe1799eda8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x7fe1640111f8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007fe1799edaef in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7fe1640111f8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007fe1799e72c0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fe1640111a8, cond=0x7fe1640111d0) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x7fe1640111d0, mutex=0x7fe1640111a8) at pthread_cond_wait.c:619
#4  0x00007fe179a8806d in uv_cond_wait () from /lib64/libuv.so.1
#5  0x0000556b3633fe3a in tinput_flush (input=input@entry=0x7fe164010f18, wait_until_empty=wait_until_empty@entry=true) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/tui/input.c:169
#6  0x0000556b363413c9 in tinput_read_cb (stream=<optimized out>, buf=<optimized out>, count_=<optimized out>, data=0x7fe164010f18, eof=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/tui/input.c:632
#7  0x0000556b361e5b32 in read_event (argv=argv@entry=0x7fe16c0de320) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/event/rstream.c:194
#8  0x0000556b361e5c20 in invoke_read_cb (stream=stream@entry=0x7fe164011000, count=count@entry=1, eof=eof@entry=false) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/event/rstream.c:207
#9  0x0000556b361e6df7 in read_cb (uvstream=<optimized out>, cnt=1, buf=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/event/rstream.c:135
#10 0x00007fe179a89548 in uv.read () from /lib64/libuv.so.1
#11 0x00007fe179a89b98 in uv.stream_io () from /lib64/libuv.so.1
#12 0x00007fe179a8e7de in uv.io_poll.part () from /lib64/libuv.so.1
#13 0x00007fe179a78598 in uv_run () from /lib64/libuv.so.1
#14 0x0000556b361e1a6d in loop_poll_events (loop=0x7fe16c0e1820, ms=-1) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/event/loop.c:62
#15 0x0000556b36342fd8 in tui_main (bridge=0x556b37c379d0, ui=0x556b37c1c260) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/tui/tui.c:456
#16 0x0000556b36345935 in ui_thread_run (data=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/ui_bridge.c:105
#17 0x00007fe1799e1299 in start_thread (arg=0x7fe16c0e2640) at pthread_create.c:481
#18 0x00007fe179739353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fe179613d80 (LWP 93186) "nvim"):
#0  0x00007fe1799eda8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x556b37c37b78, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007fe1799edaef in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x556b37c37b78, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007fe1799e72c0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x556b37c37b28, cond=0x556b37c37b50) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x556b37c37b50, mutex=0x556b37c37b28) at pthread_cond_wait.c:619
#4  0x00007fe179a8806d in uv_cond_wait () from /lib64/libuv.so.1
#5  0x0000556b36346425 in ui_bridge_suspend (b=0x556b37c379d0) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/ui_bridge.c:186
#6  0x0000556b3633ce80 in ui_call_suspend () at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/x86_64-redhat-linux-gnu/src/nvim/auto/ui_events_call.generated.h:53
#7  0x0000556b36203854 in ex_stop (eap=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/ex_docmd.c:6738
#8  0x0000556b361fc647 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fff468cc4f8, flags=flags@entry=10, cstack=cstack@entry=0x7fff468cc580, fgetline=fgetline@entry=0x0, cookie=cookie@entry=0x0) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/ex_docmd.c:1969
#9  0x0000556b361fd0fa in do_cmdline (cmdline=<optimized out>, fgetline=fgetline@entry=0x0, cookie=cookie@entry=0x0, flags=flags@entry=10) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/ex_docmd.c:599
#10 0x0000556b361ff174 in do_cmdline_cmd (cmd=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/ex_docmd.c:287
#11 0x0000556b3628b0e0 in nv_suspend (cap=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/normal.c:6607
#12 0x0000556b36284e18 in normal_execute (state=0x7fff468ccb30, key=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/normal.c:1148
#13 0x0000556b3631e7df in state_enter (s=0x7fff468ccb30) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/state.c:69
#14 0x0000556b36280773 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/normal.c:464
#15 0x0000556b36255d22 in main (argc=1183632544, argv=<optimized out>) at /usr/src/debug/neovim-0.5.1-1.fc34.x86_64/src/nvim/main.c:562

```

### PR DESCRIPTION
**Pull request by erw7**
fixes #15943.

### CODE REVIEW

**Comment by bfredl** [comment]
what's the status of this? do we want to include it in 0.6 (reasonable if it is just a bugfix)? In that case a rebase would be good :)

**Comment by erw7** [comment]
I don't know why the next call results in paste, then input mode. This is not what my change was intended to do. Therefore, I hesitate to merge this.

```lua
feed_data('i\027[200~pasted from terminal\027[20')
feed_data('1~')
```

This is a bug fix, but I don't think the problem in #15943 will occur in normal use (In my environment, the threshold for reproducing the phenomenon using the https://github.com/neovim/neovim/issues/15943#issuecomment-938361258 was in the `range (10~15)`. I tried to reproduce the phenomenon by changing the key repeat settings and other settings on the actual keyboard, but I could not. neovim tries to suspend when @jonner use `Alt+tab` to switch windows, but it doesn't usually do this, so I think his environment may be special). So, I don't think there is any need to rush the merge.

**Comment by jonner** [comment]
I've since reproduced this a couple more times and it's not alt-tab that's causing it, I think. It seems related to using ctrl-z to background the application so that I can do something in the terminal. This generally works fine, and I use it regularly. But occasionally it deadlocks nvim. There must be some sort of a race condition somewhere.

**Comment by erw7** [comment]
@jonner This problem occurs when multiple keystrokes(In my envrionment 10~15) are sent following `ctrl-z (^Z)` in a short period of time (100 μsec order?). As I wrote in https://github.com/neovim/neovim/pull/15990#issuecomment-955193528, I don't think it's possible with human input, but if this happens in your environment, it means it can happen with actual keyboard input.

As a workaround until this problem is solved, increasing `Repeat delay` or slowing down `Repeat speed` in the keyboard settings may have an effect.

**Comment by jonner** [comment]
Thanks for the tip. 

By the way, I don't know if this is related or not, but I thought I'd mention it. There's one other thing that annoys me about nvim compared to vim. I often tend to quit nvim with `:q`and then try to immediately type a shell command (for example, `cd new-directory`). I often find that it takes a little while for nvim to exit which results in my first few keystrokes bring 'eaten'. So what ends up showing on the terminal is something like `$ ew-directory`. This never happened with vim. It always seemed to exit immediately and I never had any keystrokes eaten. I only mention this in case it is somehow related and triggers any ideas.

**Pull request closed without merging**
