### PR TITLE
[RFC] fixing 2 occurrences of incorrect usage of sizeof

### PR DESCRIPTION
**Pull request by chrisosaurus**
I found 2 locations in the codebase where we were using sizeof on the wrong type

These 2 issues were raised by coverity (109019 and 62618)/

This is my first PR to this project, I have signed the CLA.

### CODE REVIEW

**Comment by mkfifo** [comment]
I am thinking that the xmalloc call in mentioned in ef3ff54249cdc41a776667f0efc365aefc8ec85f would be suitable to convert into an xcalloc call, stylistically would this offend anyone?

**Comment by oni-link** [comment]
@mkfifo, the first `st_len` entries of `sorttab` are overwritten and the code does not depend on the rest of the field set to `NULL`. So why initialize `sorttab`?

**Comment by mkfifo** [comment]
@oni-link you are right, after looking at the code closely I am confident there is no way for it to be uninitialized when read (thanks to `todo` being the size and stepping down while `todo > 0`).
Changing from `xmalloc` to `xcalloc` in this case would be purely stylistic, so I won't bother.

Leaving patch as is.

Any idea why the build is failing? I am not sure if that is caused by me, trying to decipher the page http://neovim-qb.szakmeister.net/build/860 was a nightmare.

**Comment by jszakmeister** [comment]
@mkfifo It's better to look at the [Step Status](http://neovim-qb.szakmeister.net/build/860/step_status) page.  It looks like the functional tests are hanging.  Unfortunately, that's probably due to something landing on master, as they're hanging on master too.

**Comment by splinterofchaos** [comment]
LGTM :+1:

**Comment by Pyrohh** [comment]
These can most likely be squashed into one commit, unless you plan on mentioning the individual coverity IDs for each fix (that should probably be done given how coverity fixes are usually dealt with).

**Comment by fwalch** [comment]
Following up on @Pyrohh's comment, [here](https://github.com/neovim/neovim/wiki/Contributing#coverity-conventions) are the commit message guidelines for coverity fixes.

**Comment by mkfifo** [comment]
Thanks for those, I missed the coverity guidelines.
I have rewritten the messages, rebased onto current master, and pushed.

Where can I find a page describing the various labels? I assume "send to vim_dev" means this bug most likely also exists in vim?

**Comment by Pyrohh** [comment]
> Where can I find a page describing the various labels?

I don't think we have one :sweat:
Most of them should be self explanatory, but perhaps a wiki page could be created documenting some of the less obvious ones... not sure.

> I assume "send to vim_dev" means this bug most likely also exists in vim?

It's usually more general, as it can apply to any questions we send to vim_dev (which aren't necessarily about bugs).

**Comment by mkfifo** [comment]
@Pyrohh thanks for that
Just poking around the vim source I can confirm one of the bugs exists there too

    ufunc_T	**sorttab;
    sorttab = (ufunc_T **)alloc((unsigned)(sizeof(ufunc_T) * todo));

should be

    eval.c:23167:    sorttab = (ufunc_T **)alloc((unsigned)(sizeof(ufunc_T *) * todo));

**Comment by mkfifo** [comment]
Is it fine for me to report this myself to vim_dev? or has this already been done?

**Comment by mkfifo** [comment]
ahh I misread that label, I read it as SEND to vim_dev, it is SENT to vim_dev >.>

**Comment by justinmk** [comment]
@mkfifo Feel free

**Comment by mkfifo** [comment]
Found the issue reported already https://groups.google.com/forum/#!topic/vim_dev/DKgGPTyCh7U

**Comment by mkfifo** [comment]
have rebased onto master and pushed again, hopefully this will solve those travis ci issues (which were occurring on master when I last rebased)

**Comment by Pyrohh** [comment]
LGTM

**Comment by oni-link** [comment]
The first line in a commit message should be shorter. Perhaps reuse parts of the coverity report?
```
CID 62618 (#1 of 1): Wrong sizeof argument (SIZEOF_MISMATCH)

suspicious_sizeof: Passing argument 168UL /* sizeof (ufunc_T) */ * todo to function xmalloc and then casting the return value to ufunc_T ** is suspicious.
```

```
CID 109019 (#1 of 1): Sizeof not portable (SIZEOF_MISMATCH)

suspicious_sizeof: Passing argument 8UL /* sizeof (char const **) */ to function xcalloc and then casting the return value to char ** is suspicious. In this particular case sizeof (char const **) happens to be equal to sizeof (char const *), but this is not a portable assumption.
```
Otherwise LGTM.

**Comment by mkfifo** [comment]
@oni-link thanks for the feedback, pushed with new shorter first lines and used the coverity descriptions in the body of the commit message.

**Comment by Pyrohh** [comment]
Thanks @mkfifo.

**Pull request merged**
