### PR TITLE
build: find unibilium without relying on libfindmacros

### PR DESCRIPTION
**Pull request by dundargoc**
This will remove the warning about the find module not providing a
version.

### CODE REVIEW

**Comment by jamessan** [comment]
> This will remove the warning about the find module not providing a
> version.

Wouldn't the fix be to provide a version from the find module?  After all, we're requiring a specific minimum version, so how is that being checked if the module isn't detecting the version?

**Comment by dundargoc** [comment]
Ideally yes, but I couldn't find a cross-platform way to determine the the version of unibilium. The `unibilium.h` file doesn't have any indication about which version it is.

**Comment by clason** [comment]
As we have already forked unibilium, we could just do that ourselves?

**Comment by dundargoc** [comment]
Yes, but I think we'll have to bump the minimum required version of unibilium to that version as previous versions won't have this way of determining the version.

**Comment by dundargoc** [comment]
I don't know how distros usually package these, maybe we can always rely on the .pc file being available and parse that?

**Comment by clason** [comment]
> Yes, but I think we'll have to bump the minimum required version of unibilium to that version in that case as this won't work on previous versions.

Why? Our build scripts are at best a Pirate's Code for distros -- they'll ignore or edit them at will anyway.

Minimum version is only relevant if _Neovim_ itself relies in newer features (or bugfixes) in a library.

**Comment by dundargoc** [comment]
Because if we add code to unibilium to help us determine the version, then that method will only be available in a newer unibilium version and not the older ones. This includes version 2.0.0, which is our current minimum. This means trying to determine whether the version is 2.0.0 or older won't be possible with this method.

**Pull request merged**
