### PR TITLE
build(luarc): remove deprecated {3rd} syntax

### PR DESCRIPTION
**Pull request by dundargoc**
Vendor https://github.com/LuaCATS/luv.

### CODE REVIEW

**Comment by mrcjkb** [comment]
@dundargoc feel free to assign me so I can pick this up later :smile:

**Comment by dundargoc** [comment]
Sure, although I think this is good to go as is tbh. The type stuff from luals works as expected.

**Comment by mrcjkb** [comment]
> Sure, although I think this is good to go as is tbh. The type stuff from luals works as expected.

Woops, I didn't realise this was a PR :man_facepalming:

**Comment by dundargoc** [comment]
The peoples in the dev chat were not a fan, and we concluded we can worry about this when luals removes this/it becomes a problem.

**Pull request closed without merging**
