### PR TITLE
feat(lsp): configurable log path

### PR DESCRIPTION
**Pull request by kylo252**
Add `vim.lsp.set_log_path()`

### CODE REVIEW

**Comment by mjlbach** [comment]
What is the utility/usecase for this?

**Comment by kylo252** [comment]
> What is the utility/usecase for this?

The most important one would be for debugging. We can now add a line like this to [minimal_init.lua](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua)

```lua
vim.lsp.set_log_path("/tmp/nvim/lsp.log")
```

Meaning that I can actually still use my normal config while debugging an issue, since the default logs are not mangled anymore. You can also set a `trace` log level on the fly, without worrying about deleting the default log file. I've noticed performance issues when that file is over 10 MB or so.

**Comment by mjlbach** [comment]
> I've noticed performance issues when that file is over 10 MB or so.

That should not be the case.

Anyways, mixed, idk what @mfussenegger thinks. For core logs we use an environmental variable.

**Comment by kylo252** [comment]
> For core logs we use an environmental variable.

Actually, that's the reason I grabbed  `get_parent` from [plenary](https://github.com/nvim-lua/plenary.nvim/blob/1c31adb35fcebe921f65e5c6ff6d5481fa5fa5ac/lua/plenary/path.lua#L590), we can actually use this:
```lua
local nvim_log = os.getenv("NVIM_LOG_FILE")
filepath = path_join(get_parent(nvim_log), 'lsp.log')
```
But I didn't pull the trigger on this version because I was worried it's not that intuitive.

**Comment by clason** [comment]
I think lspconfig should not do its own thing and risk having log files scattered all over the place. The right approach is to introduce a `stdpath('log')` function to core and allow changing that via the same methods as the other standard paths.

**Comment by kylo252** [comment]
> I think lspconfig should not do its own thing and risk having log files scattered all over the place. 

I'm not sure what you mean, I just referenced the `minimal_init` as a use-case. It's a pretty generic command otherwise.

> The right approach is to introduce a `stdpath('log')` function to core and allow changing that via the same methods as the other standard paths.

Aren't all the items in that list supposed to be conforming with XDG? We're already using `stdpath(cache)`  but there's no way to easily override that without changing `$XDG_CACHE_DIR`, which in turn will have side effects on other tools invoked from within Neovim.

Ref: https://github.com//neovim/neovim/blob/2bd8f2fb5ee958e210efa27286a8fe0c27b8dbbc/runtime/doc/starting.txt#L1320

**Comment by mfussenegger** [comment]
> > I've noticed performance issues when that file is over 10 MB or so.
> 
> That should not be the case.
> 
> Anyways, mixed, idk what @mfussenegger thinks. For core logs we use an environmental variable.

No strong opinions, but Justin had, see comments on https://github.com/neovim/neovim/pull/12150

**Comment by mjlbach** [comment]
I don't think it's worth the added complexity and don't think it's urgent enough until there is a more structured logging mechanism in core.

**Comment by tristan957** [comment]
My use case is that I would like to place logs in the syslog instead of a file on disk. I like viewing logs though journalctl.

**Pull request closed without merging**
