### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by zeertzjq** [comment]
This line should need to be fixed as well:
<https://github.com/neovim/neovim/blob/fff8827908494a9c4bd5de10c409189929b3db56/src/nvim/lua/vim.lua#L457>

**Comment by gpanders** [comment]
Merge before release tomorrow

**Comment by gpanders** [comment]
@mjlbach @mfussenegger I made some (minor) changes to some LSP docs, mostly just marking functions `@private` so that they don't show up in the docs. Please give it a review as soon as you can.

**Comment by mjlbach** [comment]
Looks fine to me

**Pull request merged**
