### PR TITLE
vim-patch:8.1.{1237,1796}

### PR DESCRIPTION
**Pull request by janlazo**
I included changes that should go to `src/usercmd.c` but that does not exist in `src/nvim/` yet.

### CODE REVIEW

**Comment by janlazo** [comment]
Are we missing `man` patches?

```
4875[ RUN      ] :Man man.lua: highlight_line() clears backspaces from text and adds highlights: 17.60 ms OK
4876==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16493 ====================
4877= =================================================================
4878= ==16493==ERROR: AddressSanitizer: SEGV on unknown address 0x000001d548f0 (pc 0x000000455084 bp 0x000000000000 sp 0x7ffd0e9dc4b0 T0)
4879= ==16493==The signal is caused by a WRITE memory access.
4880=     #0 0x455083 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10
4881=     #1 0x455083 in AtomicallySetQuarantineFlagIfAllocated /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:554
4882=     #2 0x455083 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:631
4883=     #3 0x4fb97b in __interceptor_free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:129:3
4884=     #4 0x10669a4 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:119:3
4885=     #5 0x12c54e8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2306:5
4886=     #6 0x12c4a0d in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
4887=     #7 0x1069639 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:650:3
4888=     #8 0x1378fc5 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
4889=     #9 0x11460bd in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:557:5
4890=     #10 0xb02c1e in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
4891=     #11 0xafc017 in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:66:3
4892=     #12 0x1360fa3 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:167:5
4893=     #13 0x10e5f79 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2747:5
4894=     #14 0x14ffb44 in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6316:5
4895=     #15 0x14e01eb in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6390:16
4896=     #16 0x14ddf22 in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6560:12
4897=     #17 0x148bf58 in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6706:10
4898=     #18 0x143f5d7 in vim_regexec_string /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7250:16
4899=     #19 0x14402b7 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7302:10
4900=     #20 0xa05ba3 in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12952:15
4901=     #21 0x96fb15 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:13230:3
4902=     #22 0x8a5160 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6536:11
4903=     #23 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
4904=     #24 0x9489f8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
4905=     #25 0x94502a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
4906=     #26 0x942af5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
4907=     #27 0x93e2eb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
4908=     #28 0x93d783 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
4909=     #29 0x93cc33 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
4910=     #30 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
4911=     #31 0x89ee16 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3489:9
4912=     #32 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
4913=     #33 0x8a93c0 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
4914=     #34 0x8a9886 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
4915=     #35 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
4916=     #36 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
4917=     #37 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
4918=     #38 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
4919=     #39 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
4920=     #40 0x9489f8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
4921=     #41 0x94502a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
4922=     #42 0x942af5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
4923=     #43 0x93e2eb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
4924=     #44 0x93d783 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
4925=     #45 0x93cc33 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
4926=     #46 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
4927=     #47 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
4928=     #48 0x8aa093 in eval_for_line /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2662:7
4929=     #49 0xca2885 in ex_while /home/travis/build/neovim/neovim/build/../src/nvim/ex_eval.c:967:14
4930=     #50 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
4931=     #51 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
4932=     #52 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
4933=     #53 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
4934=     #54 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
4935=     #55 0x9489f8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
4936=     #56 0x94502a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
4937=     #57 0x942af5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
4938=     #58 0x93e2eb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
4939=     #59 0x93d783 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
4940=     #60 0x93cc33 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
4941=     #61 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
4942=     #62 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
4943=     #63 0x8a93c0 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
4944=     #64 0x8a9886 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
4945=     #65 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
4946=     #66 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
4947=     #67 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
4948=     #68 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
4949=     #69 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
4950=     #70 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
4951=     #71 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
4952=     #72 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
4953=     #73 0xbc5938 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
4954=     #74 0xbc053e in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2365:9
4955=     #75 0xbbfd95 in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2443:15
4956=     #76 0xbc01fb in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2487:12
4957=     #77 0xbc0511 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2535:10
4958=     #78 0xf46bae in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1354:5
4959=     #79 0xf38956 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:384:3
4960=     #80 0x7f9a0e2d582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
4961=     #81 0x453db8 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x453db8)
4962= 
4963= AddressSanitizer can not provide additional info.
4964= SUMMARY: AddressSanitizer: SEGV /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
4965= ==16493==ABORTING
4966=====================================================================================================
4967test/helpers.lua:156: assertion failed!
4968
4969stack traceback:
4970	test/helpers.lua:156: in function 'check_logs'
4971	test/functional/helpers.lua:864: in function <test/functional/helpers.lua:860>
```

**Comment by justinmk** [comment]
That `exit_event` failure is a known issue: https://github.com/neovim/neovim/pull/8814

**Comment by janlazo** [comment]
I thought it was a different case this time.

**Comment by bfredl** [comment]
Is it really the same failure? Here we are asking nvim to quit even before VimEnter. I suspect this is caused by effectively `clear() ` twice in a row without using the instance in between.

Maybe we can get rid of that.

**Comment by blueyed** [comment]
It appears to at least happen more often recently.

**Pull request merged**
