### PR TITLE
third-party: use neovim/unibilium

### LINKED ISSUE #9071: TUI: pos1/end do not work in tmux when server was started with kitty (because of $TERMINFO)
When the tmux server gets started from kitty, `<Home>`/`<End>` is not recognized in Neovim.

I am using `tmux -f /dev/null -L new` to use tmux defaults and ensure there is a new session.

When running `tmux -f /dev/null -L new new nvim` from a urxvt terminal, Home/End keys are working, and also when attaching to this server from kitty (`tmux -f /dev/null -L new new nvim`).

But they are not recognized when the tmux server is started from a kitty terminal.

There are differences when using `nvim -V3log` (left is started from kitty, right is from urxvt):
```
< &term: builtin_screen
< Description: GNU Screen with 256 colors
< Aliases: screen-256color
---
> &term: screen
> Description: VT 100/ANSI X3.64 virtual terminal
> Aliases: screen
3661c3661
<   max_pairs                 pairs      = 65536
---
>   max_pairs                 pairs      = 64
3786a3787
>   E3                        = 
3788d3788
<   TS                        = 
3790,3800d3789
<   kDC3                      = 
<   kDC4                      = 
<   kDC5                      = 
<   kDC6                      = 
<   kDC7                      = 
<   kDN                       = 
<   kDN3                      = 
<   kDN4                      = 
<   kDN5                      = 
<   kDN6                      = 
<   kDN7                      = 
3803,3813d3791
<   kLFT3                     = 
<   kLFT4                     = 
<   kLFT5                     = 
<   kLFT6                     = 
<   kLFT7                     = 
<   kRIT3                     = 
<   kRIT4                     = 
<   kRIT5                     = 
<   kRIT6                     = 
<   kRIT7                     = 
<   kUP                       = 
```

So in the case of kitty `&term` is `builtin_screen`, while `screen` otherwise.

Related code:
https://github.com/blueyed/neovim/blob/b697e40347bffc3cf398075a7596b79a9a58fffe/src/nvim/tui/tui.c#L210-L218

In the case of kitty `terminfo_from_builtin` is used, while it is not for urxvt.

The problem appears to be in `unibi_from_term`, which uses `$TERMINFO` (which gets set by kitty), but `screen` is not in there (only xterm-kitty).

This is https://github.com/mauke/unibilium/issues/36.

However, this means that the `builtin_screen` is not behaving like when `TERM=screen` is handled correctly, although I cannot see it from the diff above.

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neovim/neovim/issues/10302
Fixes https://github.com/neovim/neovim/issues/9071.

### CODE REVIEW

**Comment by blueyed** [comment]
Reproducible / constant ASAN failure here?!  (https://github.com/neovim/neovim/issues/8813)
```
[ RUN      ] :Man man.lua: highlight_line() clears backspaces from text and adds highlights: 21.14 ms OK
5080==================== File /home/travis/build/neovim/neovim/build/log/ubsan.18029 ====================
5081= =================================================================
5082= ==18029==ERROR: AddressSanitizer: SEGV on unknown address 0x000001d54910 (pc 0x000000455084 bp 0x000000000000 sp 0x7ffda42c6cd0 T0)
5083= ==18029==The signal is caused by a WRITE memory access.
5084=     #0 0x455083 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10
5085=     #1 0x455083 in AtomicallySetQuarantineFlagIfAllocated /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:554
5086=     #2 0x455083 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_allocator.cc:631
5087=     #3 0x4fb97b in __interceptor_free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:129:3
5088=     #4 0x10669a4 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:119:3
5089=     #5 0x12c54e8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2306:5
5090=     #6 0x12c4a0d in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
5091=     #7 0x1069639 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:650:3
5092=     #8 0x1378fc5 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
5093=     #9 0x11460bd in exit_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:557:5
5094=     #10 0xb02c1e in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:150:7
5095=     #11 0xafc017 in loop_poll_events /home/travis/build/neovim/neovim/build/../src/nvim/event/loop.c:66:3
5096=     #12 0x1360fa3 in os_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/os/input.c:167:5
5097=     #13 0x10e5f79 in line_breakcheck /home/travis/build/neovim/neovim/build/../src/nvim/misc1.c:2747:5
5098=     #14 0x14ffb44 in nfa_regmatch /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6316:5
5099=     #15 0x14e01eb in nfa_regtry /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6390:16
5100=     #16 0x14ddf22 in nfa_regexec_both /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6560:12
5101=     #17 0x148bf58 in nfa_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp_nfa.c:6706:10
5102=     #18 0x143f5d7 in vim_regexec_string /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7250:16
5103=     #19 0x14402b7 in vim_regexec_nl /home/travis/build/neovim/neovim/build/../src/nvim/regexp.c:7302:10
5104=     #20 0xa05ba3 in find_some_match /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:12952:15
5105=     #21 0x96fb15 in f_matchstr /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:13230:3
5106=     #22 0x8a5160 in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6536:11
5107=     #23 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
5108=     #24 0x9489f8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
5109=     #25 0x94502a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
5110=     #26 0x942af5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
5111=     #27 0x93e2eb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
5112=     #28 0x93d783 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
5113=     #29 0x93cc33 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
5114=     #30 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
5115=     #31 0x89ee16 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3489:9
5116=     #32 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
5117=     #33 0x8a93c0 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
5118=     #34 0x8a9886 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
5119=     #35 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
5120=     #36 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
5121=     #37 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
5122=     #38 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
5123=     #39 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
5124=     #40 0x9489f8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
5125=     #41 0x94502a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
5126=     #42 0x942af5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
5127=     #43 0x93e2eb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
5128=     #44 0x93d783 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
5129=     #45 0x93cc33 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
5130=     #46 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
5131=     #47 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
5132=     #48 0x8aa093 in eval_for_line /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2662:7
5133=     #49 0xca2885 in ex_while /home/travis/build/neovim/neovim/build/../src/nvim/ex_eval.c:967:14
5134=     #50 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
5135=     #51 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
5136=     #52 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
5137=     #53 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
5138=     #54 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
5139=     #55 0x9489f8 in eval7 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4380:15
5140=     #56 0x94502a in eval6 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:4090:7
5141=     #57 0x942af5 in eval5 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3938:7
5142=     #58 0x93e2eb in eval4 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3674:7
5143=     #59 0x93d783 in eval3 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3592:7
5144=     #60 0x93cc33 in eval2 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3523:7
5145=     #61 0x89e648 in eval1 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3450:7
5146=     #62 0x89da72 in eval0 /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:3410:9
5147=     #63 0x8a93c0 in ex_let_const /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1590:9
5148=     #64 0x8a9886 in ex_let /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:1531:3
5149=     #65 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
5150=     #66 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
5151=     #67 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
5152=     #68 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
5153=     #69 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
5154=     #70 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
5155=     #71 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
5156=     #72 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
5157=     #73 0xbc5938 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
5158=     #74 0xbc053e in source_callback /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2365:9
5159=     #75 0xbbfd95 in do_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2443:15
5160=     #76 0xbc01fb in do_in_path_and_pp /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2487:12
5161=     #77 0xbc0511 in source_in_path /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2535:10
5162=     #78 0xf46bae in load_plugins /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1354:5
5163=     #79 0xf38956 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:384:3
5164=     #80 0x7f60c1d8082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
5165=     #81 0x453db8 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x453db8)
5166= 
5167= AddressSanitizer can not provide additional info.
5168= SUMMARY: AddressSanitizer: SEGV /tmp/final/llvm.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
5169= ==18029==ABORTING
5170=====================================================================================================
5171test/helpers.lua:156: assertion failed!
5172
5173stack traceback:
5174	test/helpers.lua:156: in function 'check_logs'
5175	test/functional/helpers.lua:864: in function <test/functional/helpers.lua:860>
5176
5177[ RUN      ] :Man man.lua: highlight_line() clears escape sequences from text and adds highlights: 19.88 ms OK
5178
```

**Comment by blueyed** [comment]
Also in https://github.com/neovim/neovim/pull/10683 though, so more related to changes on master already.

**Comment by blueyed** [comment]
@justinmk 
What's the plan here?
Should we go with commits from unibilium master for now, or create a release already?

**Comment by justinmk** [comment]
@blueyed after https://github.com/neovim/unibilium/issues/9 and @erw7 's patch (or the alternative `unibi_override` patch--whatever unblocks #9094) are included we could tag a release.

IIRC @jamessan suggested a particular tag format to indicate that this was  fork? Something like `v2.1.0-nvim` ? Or is `v2.1.0` ok?

**Comment by jamessan** [comment]
I specifically recommended against a different versioning style. We're continuing upstream maintenance. If mauke does show up again, they can make a release with a higher version number rolling back the changes if they aren't wanted, or adjusting them as needed.

**Comment by blueyed** [comment]
@justinmk 
Should we merge this already (using current unibilium master), getting this used/tested already?

**Comment by justinmk** [comment]
@blueyed  sure

**Pull request merged**
