### PR TITLE
fix(lsp): incremental sync overrun

### LINKED ISSUE #16274: tracking issue: new incremental sync (luansnip, 'index out of range', undos)
### Neovim version (nvim -v)

0.6.0 commit 2ecf0a4

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.0

### Terminal name/version

iterm 3.5

### $TERM environment variable

xterm-256color

### Installation

build from source

### How to reproduce the issue

Install `texlab` LSP server from https://github.com/latex-lsp/texlab and download https://gist.github.com/clason/b9b64a8ceb67d00c245dc58743bb053c

Then

1. `nvim --clean -u minimal test.tex`, wait for `Ready!` to show up
2. `set ft=tex` (needed since vim defaults to `plaintex` for empty `.tex` files)
2. `eq<tab>foo<tab>` (note that a literal tab is inserted instead of jumping to the next placeholder)
3. `<esc>u`

### Expected behavior

no error (as before https://github.com/neovim/neovim/commit/2ecf0a4c6183bba1c65d440711038f040d355fef)

### Actual behavior

```
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:66: index out of range
stack traceback:
        [C]: in function 'str_utfindex'
        /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:66: in function 'byte_to_utf'
        /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:100: in function 'align_position'
        /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:222: in function 'compute_end_range'
        /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:351: in function 'compute_diff'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:366: in function 'incremental_changes'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:398: in function 'fn'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:163: in function 'for_each_buffer_client'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1084: in function </usr/local/share/nvim/runtime/lua/vim
/lsp.lua:1076>
```

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #16274

@mfussenegger if you have the bandwidth to dogfood this with me, at least tests pass.

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]
> if you have the bandwidth to dogfood this with me

Will do
Change itself looks good

**Comment by clason** [comment]
Yep, that seems to fix the issue for me!

**Comment by mjlbach** [comment]
If you could use this for a bit longer and LMK if there are any breakages that would be awesome :)

**Comment by tjdevries** [comment]
Was running into this problem with doing some multi-line edits w/ formatting from external program, used this PR and it works for me now.

(no opinions on code, can look if you want me too)

**Comment by mjlbach** [comment]
@tjdevries if you want to at some point audit the code please LMK :)

**Pull request merged**
