### PR TITLE
feat(lsp): hide layout in codelenses in virtual text (#28794)

### LINKED ISSUE #28794: layout that is part of a code lens should be filtered and not displayed
### Problem

I am having issues with code lenses, in particular code lenses that would insert multiple lines when executing include the layout of the lens, i e 
- there are often multiple and different amounts of spaces
- symbols, in particular ^@ are inserted 

### Steps to reproduce using "nvim -u minimal_init.lua"

- 

### Expected behavior

I expect, that if there are multiple consecutive white space tokens in code lenses, neovim replaces them with exactly one space. This matches the behaviour of e g vscode. 

Thanks in advance! 

### Neovim version (nvim -v)

0.9.5

### Language server name/version

hls 2.9.0.0

### Operating system/version

nixos 24.05 pre release 

### Log file

_No response_

### PR DESCRIPTION
**Pull request by MangoIV**
Problem: layout i.e. whitespace that is part of codelenses is currently displayed as weird symbols and large amounts of spaces

Solution: replace all consecutive whitespace symbols with a single space character when trying to display codelenses as virtual text

This closes #28794

### CODE REVIEW

**Comment by MangoIV** [comment]
```

       > /build/d1hgm0pkhphps2f56blf4hfbjzdcjlwy-source/src/nvim/lua/treesitter.c: In function 'node_child_containing_descendant':
       > /build/d1hgm0pkhphps2f56blf4hfbjzdcjlwy-source/src/nvim/lua/treesitter.c:1095:18: error: invalid initializer
       >  1095 |   TSNode child = ts_node_child_containing_descendant(node, descendant);
       >       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
``` 
I currently get this problem when trying to build with nix, so I couldn't verify that this works yet...

**Comment by clason** [comment]
Tree-sitter 0.22.6 is required; make sure Nix has the correct dependency. If you make a PR, **always** use the provided build scripts.

**Comment by MangoIV** [comment]
thank you, I was using what is in `./contrib` building locally seemed fine but I wanted to playtest with my actual config.

**Review by justinmk — APPROVED** [review]

**Comment by clason** [comment]
>  I was using what is in ./contrib

That is in contrib for a reason; it's known to be broken and slated for removal.

**Comment by MangoIV** [comment]
force pushed to make the linter happy

**Comment by MangoIV** [comment]
image

image

much better

**Comment by MangoIV** [comment]
@clason as soon as treesitter 0.22.6 I also have a fix for the nix code, should that be upstreamed or do you not want that as it's going to be removed anyway?

**Comment by MangoIV** [comment]
should `news.txt` get an update with this PR or is this not "important enough"

**Comment by MangoIV** [comment]
wrt release, this is going into `0.11`? or can I expect it to land in a minor version?

**Comment by clason** [comment]
Features are not backported in general, so this will be 0.11 only.

**Comment by clason** [comment]
> @clason as soon as treesitter 0.22.6 is merged to nixpkgs I also have a fix for the nix code, should that be upstreamed or do you not want that as it's going to be removed anyway?

Thank you but no thank you; it will be removed, and the upstream flake will get the fix.

**Comment by MangoIV** [comment]
thank you!

**Comment by MangoIV** [comment]
Wow! Thank you for your work guys, this was a really cool experience to contribute

**Pull request merged**
