### PR TITLE
[RDY] Create new mode() value for terminal-mode ('t')

### PR DESCRIPTION
**Pull request by HarmtH**
This can be usefull in custom statuslines. For example, it makes my vim-airline able to show I'm in terminal-mode.

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM. Can you sign the CLA?

**Comment by tarruda** [comment]
:+1:

**Comment by Pyrohh** [comment]
@HarmtH could you amend this to your commit?

```
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 1d18a61..a2ff12e 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -4561,6 +4561,7 @@ mode([expr])	Return a string that indicates the current mode.
 			i	Insert
 			R	Replace |R|
 			Rv	Virtual Replace |gR|
+			t	Terminal
 			c	Command-line
 			cv	Vim Ex mode |gQ|
 			ce	Normal Ex mode |Q|
```

**Comment by Pyrohh** [comment]
just realized, and `{Nvim}` tag might be better next to it:

```
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 1d18a61..a2ff12e 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -4561,6 +4561,7 @@ mode([expr])	Return a string that indicates the current mode.
 			i	Insert
 			R	Replace |R|
 			Rv	Virtual Replace |gR|
+			t	Terminal {Nvim}
 			c	Command-line
 			cv	Vim Ex mode |gQ|
 			ce	Normal Ex mode |Q|
```

**Comment by Pyrohh** [comment]
LGTM

**Comment by Pyrohh** [comment]
Just a reminder that the CLA was signed.

**Comment by justinmk** [comment]
merged, thanks.

Just FYI, `mode()` is pretty useless in Vim. I hope we can fix it in Neovim. But in the meantime I expect this might not behave as expected...

**Comment by vheon** [comment]
@justinmk I use `mode()` for my [vim-cursormode](/vheon/vim-cursormode) (which basically is `guicursor` for my iTerm2 setup) if you drop `mode()` is there a way to support `guicursor` with neovim?

**Pull request closed without merging**
