### PR TITLE
fix: prevent double free by replacing xfree with XFREE_CLEAR

### LINKED ISSUE #16287: [crash] double free detected in tcache 2
### Neovim version (nvim -v)

NVIM v0.6.0-dev+561-g03b805aee

### Vim (not Nvim) behaves the same?

Cannot tell as the plugin I am using does not support vim

### Operating system/version

Manjaro Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

1. nvim -u vimrc foo.c
2. :CocFzfList symbols
3. press escape
4. :CocFzfList symbols
5. press escape
6. wait for a couple of seconds

vimrc:
```vim
call plug#begin('./plugins')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', {'dir': '~/.fzf','do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'antoinemadec/coc-fzf', {'commit': '2d9deb2a3b05a0c09f01edda0a4abd542cb3eebd'}
call plug#end()
```

foo.c:
```c
int main(int argc, char *argv[])
{
  return 0;
}
```

### Expected behavior

No crash.

### Actual behavior

Crash with message: 
```
free(): double free detected in tcache 2
{                                       Aborted (core dumped)
```

Coredump:
```
> coredumpctl dump 19062
           PID: 19062 (nvim)
           UID: 1000 (antoine)
           GID: 1000 (antoine)
        Signal: 6 (ABRT)
     Timestamp: Thu 2021-11-11 17:47:30 CET (1min 5s ago)
  Command Line: nvim -u vimrc foo.c
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (antoine)
       Boot ID: 07ec2911b24b4666834e355378a3ff3c
    Machine ID: 2dcc56548c094a528229dd447dbc4b2a
      Hostname: antoine-inspiron137368
       Storage: /var/lib/systemd/coredump/core.nvim.1000.07ec2911b24b4666834e355378a3ff3c.19062.1636649250000000.zst (present)
     Disk Size: 1.0M
       Message: Process 19062 (nvim) of user 1000 dumped core.

                Found module linux-vdso.so.1 with build-id: 48639d17f4288910298f29eaecfe352a95f6c659
                Found module libnss_files.so.2 with build-id: 1a36dfc01d3a1010b2ee79766a24a8090a3266d5
                Found module libresolv.so.2 with build-id: c915c72668282861a813f7ea3c0780f37b681dc0
                Found module libkeyutils.so.1 with build-id: ac405ddd17be10ce538da3211415ee50c8f8df79
                Found module libkrb5support.so.0 with build-id: adf65240a4d2aba772d7a0772b4d015469934113
                Found module libcom_err.so.2 with build-id: eb61ef71c8b97846db759fb89a115405cff6dd30
                Found module libk5crypto.so.3 with build-id: eb8220b8f36675aac769450be4cb6bb7f97ec38a
                Found module libkrb5.so.3 with build-id: 72d26767c5cb1097db75a5f5bff88860233c902b
                Found module libgssapi_krb5.so.2 with build-id: e6e098ad51ce7bdd3dbe902d7b0f69a90f8a9e08
                Found module libtirpc.so.3 with build-id: 5bef2adfdee3df283f593b3e2d37b6dac405256a
                Found module ld-linux-x86-64.so.2 with build-id: 040cc3dd10461562f177df39e3be2f3704258c3c
                Found module libc.so.6 with build-id: 4b406737057708c0e4c642345a703c47a61c73dc
                Found module libgcc_s.so.1 with build-id: 7f8508bb914546ada778809b64b99d234337d835
                Found module libutil.so.1 with build-id: af6d8200064ee6e6a01252884d166b44f0a6121b
                Found module libm.so.6 with build-id: 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                Found module libdl.so.2 with build-id: 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                Found module libnsl.so.3 with build-id: 059e45eb1f084e0bb3143f0c4c364a6ade7d50b1
                Found module libpthread.so.0 with build-id: 07c8f95b4f3251d08550217ad8a1f31066229996
                Found module librt.so.1 with build-id: 75484da2d6f1515189eefa076e0a40328834cd16
                Found module nvim with build-id: a7af43909d7d48517d02813abce3cfa9d17b93f7
                Stack trace of thread 19062:
                #0  0x00007f0b3e239d22 raise (libc.so.6 + 0x3cd22)
                #1  0x00007f0b3e223862 abort (libc.so.6 + 0x26862)
                #2  0x00007f0b3e27bd28 __libc_message (libc.so.6 + 0x7ed28)
                #3  0x00007f0b3e28392a malloc_printerr (libc.so.6 + 0x8692a)
                #4  0x00007f0b3e285408 _int_free (libc.so.6 + 0x88408)
                #5  0x00007f0b3e2889e8 __libc_free (libc.so.6 + 0x8b9e8)
                #6  0x0000563d76dd2e1b vars_clear_ext (nvim + 0x123e1b)
                #7  0x0000563d76e0ddf8 free_unref_funccal (nvim + 0x15edf8)
                #8  0x0000563d76dc941e garbage_collect (nvim + 0x11a41e)
                #9  0x0000563d76f07b27 os_inchar (nvim + 0x258b27)
                #10 0x0000563d76f94f0d state_enter (nvim + 0x2e5f0d)
                #11 0x0000563d76ecc56b normal_enter (nvim + 0x21d56b)
                #12 0x0000563d76d445ad main (nvim + 0x955ad)
                #13 0x00007f0b3e224b25 __libc_start_main (libc.so.6 + 0x27b25)
                #14 0x0000563d76d4582e _start (nvim + 0x9682e)

                Stack trace of thread 19063:
                #0  0x00007f0b3e2fb92e epoll_wait (libc.so.6 + 0xfe92e)
                #1  0x0000563d77043457 uv__io_poll (nvim + 0x394457)
                #2  0x0000563d7702fc34 uv_run (nvim + 0x380c34)
                #3  0x0000563d76fbe73e tui_main (nvim + 0x30f73e)
                #4  0x00007f0b3e548259 start_thread (libpthread.so.0 + 0x9259)
                #5  0x00007f0b3e2fb5e3 __clone (libc.so.6 + 0xfe5e3)
Refusing to dump core to tty (use shell redirection or specify --output).
```

### PR DESCRIPTION
**Pull request by dundargoc**
Closes #16287

### CODE REVIEW

**Review by gpanders — APPROVED** [review]

**Comment by dundargoc** [comment]
@gpanders Just as a heads up, @erw7 has proposed a [different solution](https://github.com/neovim/neovim/issues/16287#issuecomment-968056648), which is a vim-patch. I'm pretty sure both of our proposed solutions aren't mutually exclusive, but still wanted to give a heads up.

**Comment by gpanders** [comment]
Yes, I saw that. I think this change is still valuable as well, but let's wait for @bfredl to weigh in.

**Comment by erw7** [comment]
If the following comments are followed, this change will have no effect. If the code does not follow it, this change is incomplete.   Because simply clearing `ht_array` with `XFREE_CLEAR()` may result in a NULL pointer deref in `hash_lookup()`. Therefore, it is more complete to call `hash_init()` instead of `XFREE_CLEAR()`. I don't know why the original code doesn't call `hash_init()`, but it may be because of the cost of calling `hash_init()`, which is useless.


https://github.com/neovim/neovim/blob/2ef9d2a663db35c73b93606dbe882ca697072cc3/src/nvim/hashtab.c#L55-L57

**Comment by dundargoc** [comment]
Well, @erw7 is more experienced than me and he wants to go with another route and that's good enough for me.

**Comment by erw7** [comment]
There seems to be some kind of misunderstanding. I am not opposed to initializing `hashtab_T` here. I am just suggesting that it is better to use `hash_init()` because `XFREE_CLEAR()` has incomplete initialization.

**Pull request closed without merging**
