### PR TITLE
[RFC] run/configure clang-format

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neovim/neovim/issues/11236

This is meant to see what it looks like, and allows us to discuss/tweak the format.

TODO:

- [x] exclude `src/nvim/xdiff`

### CODE REVIEW

**Comment by justinmk** [comment]
Would be easier to discuss if it's done on only a few files.

**Comment by e-kwsm** [comment]
I think it is good to place `.clang-format` file.

**Comment by blueyed** [comment]
> I think it is good to place `.clang-format` file.

We have one already, that we can adjust: https://github.com/neovim/neovim/blob/master/.clang-format

@e-kwsm 
Any experience with that?

**Comment by dundargoc** [comment]
Closing as we've decided to use `uncrustify` as our current formatter of choice.

**Pull request closed without merging**
