### PR TITLE
Update Runtime Files For Zsh

### PR DESCRIPTION
**Pull request by saadparwaiz1**
Please let me know if I messed up in porting the files, and I'll try to fix the issue

### CODE REVIEW

**Comment by janlazo** [comment]
You didn't have to split up the changes of each runtime commit although it makes the PR easier to review. Test failure suggests that there is a missing vim patch to update tests in `src/nvim/testdir/`.

**Review by janlazo — APPROVED** [review]
LGTM aside from the test failure.

**Comment by janlazo** [comment]
Rebase on master branch when https://github.com/neovim/neovim/pull/13852 is merged.

**Comment by teto** [comment]
should be good now.

**Comment by saadparwaiz1** [comment]
Thank you for the review. I have rebased the branch now :)

**Comment by e-kwsm** [comment]
I'm facing the following error (NVIM v0.5.0-dev+cc1851c9f):

```ShellSession
$ nvim --headless -u NORC -c 'setf zsh' -cq
Error detected while processing /opt/neovim/share/nvim/runtime/ftplugin/zsh.vim:
line   30:
E666: compiler not supported: zsh
```

**Comment by e-kwsm** [comment]
The error does not occur after clean build. Sorry for the noise.

**Pull request merged**
