### PR TITLE
Langremap after map

### PR DESCRIPTION
**Pull request by hardenedapple**
Some tests for 'langremap' and a functionality change.

This is splitting PR #6494 into two parts, that PR will keep changes related
to the `'langremap'` behaviour w.r.t macros, while this one will introduce the
majority of tests and fix a separate bug.

The commit message of the functional change explains the problem (copied
and pasted into this message for convenience).
The problem is demonstrated in the `applies when deciding whether to map recursively`
and `does not stop applying 'langmap' on first character of a mapping` tests.

    Make 'langnoremap' apply directly after a map
    
    We were initially checking whether to apply 'langmap' translation based
    on typebuf.tb_maplen.
    This gets set to 0 on the last byte of a map when the del_typebuf()
    function is called, which means that the option was not working for the
    last character of a mapping.
    For this reason, we switched to using KeyTyped to decide whether to
    apply the transformation or not in commit 53da57d27.
    Substituting one for the other isn't enough, because KeyTyped isn't set
    until vgetorpeek() is returning.
    This means 'langmap' translations are not applied when searching for
    characters to map in the vgetorpeek() function if the *previous* key was
    not typed.
    
    We can't assert that both hold, as we would then *not* apply the
    transformation when looking for a map starting with the first typed key
    after a previously expanded map (as KeyTyped would be `false` from the
    previously expanded map, and not yet reset).
    
    Hence we assert that if we are looking for the mapping while in
    vgetorpeek(), the map length should be zero, otherwise, KeyTyped must be
    `true`.
    
    This is implemented by checking for the variable `vgetc_busy`.

### CODE REVIEW

**Comment by chrisbra** [comment]
What bug does this fix?

**Comment by chrisbra** [comment]
CC @brammool

**Comment by hardenedapple** [comment]
@chrisbra 
The clearest demonstration:

#### Setup
`vim -u NONE`
With the text file
```
iii www
iii www
iii www
```
Settings of
`set nolangremap`
`nmapclear`
`set langmap=iw,wi`
`nmap w j`

#### Action
Press `i` , your cursor moves down because of the following transformations
- `i` gets translated to `w` with `LANGMAP_ADJUST` inside `vgetorpeek()`
- `w` gets mapped to `j` from `nmap`
- `j` is returned from `vgetorpeek()` and used in the rest of vim.

Press `i` a second time, having not pressed anything since the previous keypress.
Your cursor moves one word forwards because of the following transformations:

- `i` does not get translated to `w` with `LANGMAP_ADJUST` when checking for maps
in `vgetorpeek()`, because `KeyTyped` is still set to `false` from the previous `nmap`.
- `i` is returned from `vgetorpeek()`, and is used in the rest of vim.
- As `i` is returned, `vgetorpeek()` sets `KeyTyped` to `true` to mark that this is not the
result of a mapping.
- In `normal_execute()`, `LANGMAP_ADJUST` is used to apply `'langmap'` to the key
to decide what action should be taken.
- Because `KeyTyped` is now `true`, this `LANGMAP_ADJUST` is applied, and `i` gets
transformed to `w` before execution.

**Comment by chrisbra** [comment]
thanks. That looks odd indeed.

**Comment by justinmk** [comment]
Thanks @hardenedapple ! Would be good to rebase https://github.com/neovim/neovim/pull/6494 ASAP.

**Pull request merged**
