### PR TITLE
feat(treesitter): include inline extmarks and semantic highlights in foldtext

### PR DESCRIPTION
**Pull request by willothy**
This PR makes the default treesitter foldtext respect inline extmarks / inlay hints, as well as LSP semantic tokens (via the highlight extmarks).

I've been wanting to attempt this for a while since the only other way to get this appearance seems to be `nvim-ufo`, but I like to use treesitter for folding.

Implementation is definitely WIP and needs to be optimized, which is why I've marked this as a draft (also no docs, tests etc. yet).

Here's what it looks like:

https://github.com/neovim/neovim/assets/38540736/d632b765-d770-4320-94f0-7143a1a5f9f8

Current nvim behavior for comparison:

https://github.com/neovim/neovim/assets/38540736/83a78798-59e5-40a1-9bf0-542a0f1a3482

### CODE REVIEW

**Comment by zeertzjq** [comment]
The function is called `vim.treesitter.foldtext()`. I don't think it's a good idea to include LSP stuff in it.

**Comment by willothy** [comment]
> The function is called `vim.treesitter.foldtext()`. I don't think it's a good idea to include LSP stuff in it.

I do agree that it's slightly counter-intuitive, but users shouldn't need to re-implement the entire treesitter fold module to achieve this appearance... imo that is more important than the semantics of where LSP vs treesitter things should be.

Also, there is nothing from LSP directly referenced; inline extmarks and highlight extmarks (maybe overlay should be included as well?) could come from anywhere and not necessarily LSP. LSP just happens to be the primary provider of those kinds of extmarks.

I don't think it would make sense to have a separate foldtext function for LSP either, right?

If you think this shouldn't be in core though I understand the logic, no worries :)

**Comment by clason** [comment]
I think the LSP thing is a red herring -- we want _any_ extmark highlights applied, no matter where they come from. In fact, it might make sense to _remove_ the treesitter special casing here and move it to, e.g., `vim.highlight.foldtext()` (or even `vim.foldtext()`; lots of bikes to shed here).

@lewis6991

**Comment by zeertzjq** [comment]
Yes, but do everyone want inlay hint to also show in 'foldtext'?

**Comment by willothy** [comment]
> Yes, but do everyone want inlay hint to also show in 'foldtext'?

I agree on this one, and it's definitely important to take those users into consideration, but as @clason said I don't really see someone wanting inlay hints but not wanting them in folds. If someone has inlay hints disabled, they won't show up here either way.

**Comment by lewis6991** [comment]
IMO we should not do this at all and reopen https://github.com/neovim/neovim/pull/20750

**Comment by willothy** [comment]
> IMO we should not do this at all and reopen #20750.

That's good with me, definitely would make things simpler! Do the changes in that PR allow for extmarks to be shown in foldtext?

> This is really just a lot of unnecessary Lua code

Definitely agree, and if this moves forwards it can definitely be slimmed down a lot. I wanted to open a discussion as soon as I had something working to see if there was interest :)

**Comment by lewis6991** [comment]
> That's good with me, definitely would make things simpler! Do the changes in that PR allow for (inline) extmarks to be shown in foldtext?

Yes, it just renders the buffer as normal but with the additional folded highlight applied.

**Comment by willothy** [comment]
> Yes, it just renders the buffer as normal but with the additional folded highlight applied.

That's definitely a better way to get the same result! I'll go ahead and close this :)

**Comment by rockyzhang24** [comment]
> I've been wanting to attempt this for a while since the only other way to get this appearance seems to be nvim-ufo, but I like to use treesitter for folding.

Maybe off-topic, but just to be clear, `nvim-ufo` supports both LSP and treesitter. It even supports creating any folding strategies (called provider in `nvim-ufo`). Highly recommend it 👍

**Comment by willothy** [comment]
> Maybe off-topic, but just to be clear, `nvim-ufo` supports both LSP and treesitter. It even supports creating any folding strategies (called provider in `nvim-ufo`). Highly recommend it 👍

I used it for quite a long time and have had a lot of issues with code automatically folding, random/unpredictable errors and similar. Finally got frustrated so I switched to a modified version of treesitter's foldexpr, which just works with no hassle. I don't really see the point in depending on an additional plugin with ~4500LOC since the changes here (which I use in my own config) make the appearance options of nvim-ufo somewhat redundant. Is there something I'm missing that treesitter folding can't do that nvim-ufo can?

**Comment by rockyzhang24** [comment]
>  Is there something I'm missing that treesitter folding can't do that nvim-ufo can?

Please allow me to paste a [link](https://www.reddit.com/r/neovim/comments/187atwy/comment/kbgykyl/?utm_source=share&utm_medium=web2x&context=3) of a comment I left on a reddit post. This is an example that I defined a folding behavior to fold the diff chunks in diff and git filetypes that have no treesitter parser.

**Comment by willothy** [comment]
> Please allow me to paste here the [link](https://www.reddit.com/r/neovim/comments/187atwy/comment/kbgykyl/?utm_source=share&utm_medium=web2x&context=3) of a comment I left on a reddit post. This is an example that I defined a folding behavior to fold the diff chunks in diff and git filetypes that have no treesitter parser.

That's pretty cool, thanks! Definitely an interesting use case for folds, I'll give it a try if I can get it to work smoothly with my config :)

**Comment by rockyzhang24** [comment]
> That's pretty cool, thanks! Definitely an interesting use case for folds, I'll give it a try if I can get it to work smoothly with my config :)

Great. Perhaps because I only use some basic essential plugins, I have not encountered any errors in my daily use of `nvim-ufo`. If you get random errors as you said, just open an issue and its author is quite responsive.

**Pull request closed without merging**
