### PR TITLE
feat(lsp): add `vim.lsp.diagnostic.set_qflist()` function.

### PR DESCRIPTION
**Pull request by mrcjkb**
See #14830.

Doesn't have any test cases yet.
Would probably need some refactoring.

### CODE REVIEW

**Comment by clason** [comment]
You know that there's already https://github.com/neovim/neovim/blob/f76f72a27bb0c60c9e60a5bba30d94fd5541595a/runtime/lua/vim/lsp/util.lua#L1667-L1676 ?

**Review by mfussenegger — COMMENTED** [review]
What do you think of instead improving the docs for `diagnostics_to_items` to show some example snippets, e.g. something like this?

```lua
vim.fn.setqflist({}, 'r', {
  title = 'Language Server';
  items = vim.lsp.util.diagnostics_to_items(
    vim.lsp.diagnostic.get_all(),
    function(d) return d.severity == vim.lsp.protocol.DiagnosticSeverity.Warning end
  )
})
vim.cmd('copen')
```


I know this mirrors `set_loclist`, but I feel like all the `util.set_qflist`, `util.set_loclist` and `diagnostics.set_loclist` functions are already too much. Especially `util.set_loclist` and `util.set_qflist` are just a 1 line wrapper around `vim.fn.setqflist`.

I fear this tendency to add convenience functions for every conceivable use-case is ending up exploding the number of functions.


Anyways, let's see what @mjlbach has to say

**Comment by MrcJkb** [comment]
Sounds good to me.

**Comment by mjlbach** [comment]
I think I'm ok with this if you factor out all of the shared logic into a function, which makes set_qflist and set_loclist into 5 line functions. I think it's ok to have these helper functions because they would be commonly mapped by users, but I also echo @mfussenegger's concern about configuration bloat. We already make it incredibly easy to compose your own utility functions.

**Comment by MrcJkb** [comment]
> I think I'm ok with this if you factor out all of the shared logic into a function, which makes set_qflist and set_loclist into 5 line functions. I think it's ok to have these helper functions because they would be commonly mapped by users, but I also echo @mfussenegger's concern about configuration bloat. We already make it incredibly easy to compose your own utility functions.

Done.
Please note that for `set_qflist`, I changed the default `opts.workspace` option to `true`. For me, it makes more sense for the quickfix list to be populated with workspace-wide diagnostics by default.

**Comment by MrcJkb** [comment]
@mjlbach would you be okay if I added a `Diagnostic.message` predicate to the `opts` parameter?
 I noticed that some language servers publish diagnostics with `DiagnosticSeverity='Information'` for `TODO` and `FIXME` comments. With a predicate, this would provide a convenient way to add project-wide `TODO` comments to the qf/loc-lists.

**Comment by mjlbach** [comment]
I don't understand the utility of the predicate or what you would be using the predicate for.

Just FYI this PR will have to wait until 0.5.1 (via backport), I'm still not sure about the interface as well.

**Comment by MrcJkb** [comment]
> I don't understand the utility of the predicate or what you would be using the predicate for.

My use case would be to create commands with which I can add `TODO` or `FIXME` comments to the quickfix list by filtering the diagnostics by their message contents accordingly. For example:

```lua
vim.lsp.diagnostic.set_loclist({
  filter_predicate = function(diagnostic)
    return string.find(diagnostic.message, 'TODO')
  end
})
```
Though I can see how the interface may become somewhat bulky, given the current `severity` and `severity_limit` options.

**Comment by mjlbach** [comment]
Is this not duplicating functionality provided by `:help Cfilter`?

**Comment by MrcJkb** [comment]
> Is this not duplicating functionality provided by `:help Cfilter`?

Ah, thank you. I did not know about `Cfilter`.

**Comment by mjlbach** [comment]
Lets get this merged. I think it's a bit confusing to have a non-standard option for open, I would just do `opts.open`

**Comment by MrcJkb** [comment]
> Lets get this merged. I think it's a bit confusing to have a non-standard option for open, I would just do `opts.open`
> 
> The PR also needs a rebase.

The merge conflicts are resolved.
I have applied your suggestion for `opts.open` rather than `opts.open_qflist` and `opts.open_loclist`, respectively.
But this is would be a breaking change. Maybe I should add a (undocumented) `opts.set_qflist` parameter to the `set_loclist` function for the purpose of backward compatibility?

**Comment by mjlbach** [comment]
@mfussenegger I know we have had concerns about adding too many utility functions/accessors, so wdyt?

**Comment by mfussenegger** [comment]
I'm still -0.1 on this because I think `vim.fn.setqflist` + `vim.lsp.util.diagnostics_to_items` + `vim.lsp.diagnostic.get_all()` should be good enough, but I can also see that `vim.lsp.diagnostic.set_qflist` is more ergonomic for use in mappings and so on, so fine for me to go ahead and merge it :)

**Comment by mjlbach** [comment]
I'm merging for now, but I'm going to open a tracking issue about cleaning up the diagnostic api

**Pull request merged**
