### PR TITLE
[RFC] Fix clang analysis warnings. (7)

### PR DESCRIPTION
**Pull request by elmart**
This should get rid of existing clang warnings.

### CODE REVIEW

**Comment by elmart** [comment]
@tarruda Just to let you know I'm taking care of this, so that we don't repeat work.

**Comment by elmart** [comment]
@tarruda BTW, they seemed to have nothing to do with your changes. It seems that just somehow, code changes sometimes make the checker check different paths that weren't previously examined.

**Comment by tarruda** [comment]
@elmart thanks for you amazing dedication in fixing these problems

**Comment by elmart** [comment]
You know, being spanish, I'm in the business of bug-fighting... Get it? ;-)
Amazing is what you've done in #2016.
Thanks, @tarruda.

**Comment by tarruda** [comment]
> You know, being spanish, I'm in the business of bug-fighting... Get it? ;-)

:smile:

**Comment by elmart** [comment]
@justinmk I'd like to get this merged before the next coverity run. Could you have a look? It's only two easy commits to review.

**Comment by tarruda** [comment]
> @justinmk I'd like to get this merged before the next coverity run. Could you have a look? It's only two easy commits to review.

Will it be troublesome for you if I merge #1997 before this?

**Comment by elmart** [comment]
> Will it be troublesome for you if I merge #1997 before this?

No. They're just two simple commits. I think I can easily fix any merge conflict that could happen after you've merged that.

Regarding #1997, I haven't reported yet, because since I installed it, I've only worked for a couple of hours, so I still don't know. But I've had no problems until now.

**Comment by elmart** [comment]
In fact, I've just successfully rebased these two commits on top of #1997's tip without merge conflicts. Did you expect problems?

**Comment by tarruda** [comment]
> In fact, I've just successfully rebased these two commits on top of #1997's tip without merge conflicts. Did you expect problems?

No, I just asked because of your request: `@justinmk I'd like to get this merged before the next coverity run`

**Comment by elmart** [comment]
That was because, though this PR is on clang warnings, it also (indirectly) fixes a coverity issue. And I wanted to check that it effectively does, in the next coverity run.

When you asked for this to wait for #1997, I thought you said that because there were merge conflicts between them.

Now I've seen there aren't. So I understand you probably meant for this to wait so that any other possible warnings caused by #1997 are included here.

I have no problem with that. I can wait, or I can merge this and make another PR for new warnings if they happen.

**Comment by tarruda** [comment]
> I have no problem with that. I can wait, or I can merge this and make another PR for new warnings if they happen.

very well.

I will merge #1997 because I don't think its a dangerous PR despite the line count, the real breaking changes were already performed in #1820

**Comment by elmart** [comment]
I think so, too. :+1: 
I'll check locally for new warnings once #1997 is merged.

**Comment by elmart** [comment]
It seems there are no new warnings. :+1: 
Repushed. This can be merged once reviewed.

**Comment by justinmk** [comment]
LGTM

**Pull request merged**
