### PR TITLE
Backupdir default

### PR DESCRIPTION
**Pull request by murphy66**
Fix for #11860

Changed the default options for 'backupdir', 'undodir' and 'viewdir' to have trailing "//". Also removed the '.' from the default from 'backupdir' and it is now autocreated if needed. Modified documentation and tests accordingly.

### CODE REVIEW

**Comment by teto** [comment]
related https://github.com/neovim/neovim/pull/11968

`//` seems like a better default but removing the current folder may be more surprising. I dont use the feature so I'll defer to @jamessan for a better judgement

**Comment by jamessan** [comment]
> removing the current folder may be more surprising

Agreed.  That should be kept.  The default behavior for backups is solely to have a backup if the save of the main file to disk fails.  As soon as that save is completed the backup file is removed, so I don't see the need to prioritize putting them in a central location.

**Comment by teto** [comment]
thanks for updating. Could you fix the linting issues please ? you can try locally by rebasing on master and running `make clint` otherwise check the travis failed jobs
```
src/nvim/fileio.c:2793:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]

src/nvim/fileio.c:2794:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 2793  [whitespace/alignment] [2]

src/nvim/fileio.c:2796:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 2795  [whitespace/alignment] [2]

src/nvim/fileio.c:2797:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 2795  [whitespace/alignment] [2]

src/nvim/option.c:768:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 767  [whitespace/alignment] [2]

src/nvim/option.c:770:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 769  [whitespace/alignment] [2]

src/nvim/option.c:772:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 771  [whitespace/alignment] [2]
```

**Comment by justinmk** [comment]
diff is hard to read. can you try `git rebase -i origin/master` (in the list of commits , just delete all commits that aren't yours)

**Comment by teto** [comment]
opening a new PR is not needed: run:
1. git fetch --all
2. git rebase origin/master   (here you may need to solve a conflict, you can read on it on the internet, or for a deep dive use fugitive as in http://vimcasts.org/episodes/fugitive-vim-resolving-merge-conflicts-with-vimdiff/),
3. git push -f

**Comment by gpanders** [comment]
@murphy66 Are you still interested in pushing this PR through? If not, I'll adopt it.

**Pull request closed without merging**
