### PR TITLE
add new HTML 5 tags (used the official reference https://dev.w3.org…

### PR DESCRIPTION
**Pull request by jorgesumle**
…/html5/html-author/#comparison-of-html-4.01-and-html5-elements)

... also removed trailing whitespaces.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for the help! 

We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

- Please send this change to the maintainer, [listed at the top of the file](https://github.com/neovim/neovim/pull/5633/files#diff-9ce269b367810a6f3cc1e5f3871789b3R3).
- Also send the change to https://github.com/vim/vim, mentioning that you already sent the change to the maintainer.

**Comment by jorgesumle** [comment]
I've already sent the pull request to Vim (https://github.com/vim/vim/pull/1263) and the email. If it gets merged, you should reopen and merge.

**Comment by jorgesumle** [comment]
Support for HTML 5 tags has been added in Vim: https://github.com/vim/vim/commit/bc2eada5424bff06f7eb77c032ecc067da52b846

But that commit also changed some other runtime files, so I guess that this feature has to wait for Neovim, until we get to patch 8.0.0142 (https://neovim.io/doc/reports/vimpatch/).

**Comment by Shougo** [comment]
Yes, we should merge other commits.

**Pull request closed without merging**
