### PR TITLE
[RFC] vim-patch:8.0.0286

### PR DESCRIPTION
**Pull request by ckelsel**
Problem:    When concealing is active and the screen is resized in the GUI it
            is not immediately redrawn.
Solution:   Use update_prepare() and update_finish() from
            update_single_line().

https://github.com/vim/vim/commit/c10f0e7cb0f35eea489b038e56c87b818eee975b

### CODE REVIEW

**Comment by ckelsel** [comment]
image

**Comment by justinmk** [comment]
when check_logs fails that means somewhere in the logs there's a ASAN failure. Here it is:

```
[32m[2m[----------][0m[0m Running tests from [36m/home/travis/build/neovim/neovim/test/functional/legacy/089_number_relnumber_findfile_spec.lua[0m
[32m[2m[ RUN      ][0m[0m setting 'number' and 'relativenumber' is working: [2m10.37 ms[0m [1m[32mOK[0m[0m
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.16034 ====================
= 
= =================================================================
= ==16034==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 32640 byte(s) in 68 object(s) allocated from:
=     #0 0x5113c6 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x5113c6)
=     #1 0xfdfa04 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xfdfbc4 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0x13fb8fb in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6500:10
=     #4 0x13b3c2f in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7159:12
=     #5 0x153187b in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #6 0x1535d8b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #7 0x148e28e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #8 0x14b3e45 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #9 0x14b347e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #10 0x11abe3a in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1298:5
=     #11 0x11a833c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #12 0x17be073 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:26:35
=     #13 0x10eeaaf in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #14 0xecc627 in main /home/travis/build/neovim/neovim/src/nvim/main.c:569:3
=     #15 0x2af898e20f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Direct leak of 8640 byte(s) in 18 object(s) allocated from:
=     #0 0x5113c6 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x5113c6)
=     #1 0xfdfa04 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xfdfbc4 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0x13fb8fb in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6500:10
=     #4 0x13b3c2f in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7159:12
=     #5 0x153187b in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #6 0x1535d8b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #7 0x148e28e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #8 0x14b3e45 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #9 0x14b347e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #10 0x11abd04 in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1295:7
=     #11 0x11a833c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #12 0x17be073 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:26:35
=     #13 0x10eeaaf in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #14 0xecc627 in main /home/travis/build/neovim/neovim/src/nvim/main.c:569:3
=     #15 0x2af898e20f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Indirect leak of 544 byte(s) in 68 object(s) allocated from:
=     #0 0x5113c6 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x5113c6)
=     #1 0xfdfa04 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xfdfbc4 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0xfe0063 in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
=     #4 0xfe0158 in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
=     #5 0xfe0fb2 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
=     #6 0x17c00bd in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:59:20
=     #7 0x13fc999 in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6530:19
=     #8 0x13b3c2f in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7159:12
=     #9 0x153187b in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #10 0x1535d8b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #11 0x148e28e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #12 0x14b3e45 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #13 0x14b347e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #14 0x11abe3a in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1298:5
=     #15 0x11a833c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #16 0x17be073 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:26:35
=     #17 0x10eeaaf in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #18 0xecc627 in main /home/travis/build/neovim/neovim/src/nvim/main.c:569:3
=     #19 0x2af898e20f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Indirect leak of 144 byte(s) in 18 object(s) allocated from:
=     #0 0x5113c6 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x5113c6)
=     #1 0xfdfa04 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xfdfbc4 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0xfe0063 in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
=     #4 0xfe0158 in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
=     #5 0xfe0fb2 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
=     #6 0x17c00bd in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:59:20
=     #7 0x13fc999 in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6530:19
=     #8 0x13b3c2f in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7159:12
=     #9 0x153187b in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #10 0x1535d8b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #11 0x148e28e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #12 0x14b3e45 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #13 0x14b347e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #14 0x11abd04 in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1295:7
=     #15 0x11a833c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #16 0x17be073 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:26:35
=     #17 0x10eeaaf in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #18 0xecc627 in main /home/travis/build/neovim/neovim/src/nvim/main.c:569:3
=     #19 0x2af898e20f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= SUMMARY: AddressSanitizer: 41968 byte(s) leaked in 172 allocation(s).
=====================================================================================================
./test/helpers.lua:95: assertion failed!

stack traceback:
	./test/helpers.lua:95: in function 'check_logs'
	./test/functional/helpers.lua:698: in function <./test/functional/helpers.lua:694>
```

**Comment by janlazo** [comment]
Is this still failing?

**Comment by ckelsel** [comment]
```
= 
= =================================================================
= ==16683==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 41080 byte(s) in 79 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0x141d8db in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6500:10
=     #4 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #5 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #6 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #7 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #8 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #9 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #10 0x11c5b7a in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1298:5
=     #11 0x11c207c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #12 0x17e0db3 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:28:35
=     #13 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #14 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #15 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Direct leak of 13000 byte(s) in 25 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0x141d8db in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6500:10
=     #4 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #5 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #6 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #7 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #8 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #9 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #10 0x11c5a44 in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1295:7
=     #11 0x11c207c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #12 0x17e0db3 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:28:35
=     #13 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #14 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #15 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Direct leak of 2600 byte(s) in 5 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0x141d8db in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6500:10
=     #4 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #5 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #6 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #7 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #8 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #9 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #10 0x11b90f9 in n_opencmd /home/travis/build/neovim/neovim/src/nvim/normal.c:7043:9
=     #11 0x1178b26 in nv_open /home/travis/build/neovim/neovim/src/nvim/normal.c:7880:5
=     #12 0x1151ae0 in normal_execute /home/travis/build/neovim/neovim/src/nvim/normal.c:1136:3
=     #13 0x17e13a0 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:67:26
=     #14 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #15 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #16 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Direct leak of 520 byte(s) in 1 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0x141d8db in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6500:10
=     #4 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #5 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #6 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #7 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #8 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #9 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #10 0x1b42a31 in win_goto /home/travis/build/neovim/neovim/src/nvim/window.c:3481:5
=     #11 0x1b457c1 in win_goto_hor /home/travis/build/neovim/neovim/src/nvim/window.c:3615:5
=     #12 0x1b3f786 in do_window /home/travis/build/neovim/neovim/src/nvim/window.c:247:18
=     #13 0xc281a4 in ex_wincmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7364:5
=     #14 0xbade99 in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
=     #15 0xb8c5c1 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
=     #16 0x87b8b7 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21282:3
=     #17 0x8458e8 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6369:11
=     #18 0x85b6f3 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6131:11
=     #19 0x853e6b in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2748:9
=     #20 0xbade99 in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
=     #21 0xb8c5c1 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
=     #22 0x116ab1b in nv_colon /home/travis/build/neovim/neovim/src/nvim/normal.c:4552:18
=     #23 0x1151ae0 in normal_execute /home/travis/build/neovim/neovim/src/nvim/normal.c:1136:3
=     #24 0x17e13a0 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:67:26
=     #25 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #26 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #27 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Indirect leak of 711 byte(s) in 79 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0xffc5c3 in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
=     #4 0xffc6b8 in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
=     #5 0xffd512 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
=     #6 0x17e2f8d in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:59:20
=     #7 0x141e979 in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6530:19
=     #8 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #9 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #10 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #11 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #12 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #13 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #14 0x11c5b7a in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1298:5
=     #15 0x11c207c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #16 0x17e0db3 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:28:35
=     #17 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #18 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #19 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Indirect leak of 225 byte(s) in 25 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0xffc5c3 in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
=     #4 0xffc6b8 in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
=     #5 0xffd512 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
=     #6 0x17e2f8d in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:59:20
=     #7 0x141e979 in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6530:19
=     #8 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #9 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #10 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #11 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #12 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #13 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #14 0x11c5a44 in normal_redraw /home/travis/build/neovim/neovim/src/nvim/normal.c:1295:7
=     #15 0x11c207c in normal_check /home/travis/build/neovim/neovim/src/nvim/normal.c:1338:5
=     #16 0x17e0db3 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:28:35
=     #17 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #18 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #19 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Indirect leak of 45 byte(s) in 5 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0xffc5c3 in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
=     #4 0xffc6b8 in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
=     #5 0xffd512 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
=     #6 0x17e2f8d in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:59:20
=     #7 0x141e979 in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6530:19
=     #8 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #9 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #10 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #11 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #12 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #13 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #14 0x11b90f9 in n_opencmd /home/travis/build/neovim/neovim/src/nvim/normal.c:7043:9
=     #15 0x1178b26 in nv_open /home/travis/build/neovim/neovim/src/nvim/normal.c:7880:5
=     #16 0x1151ae0 in normal_execute /home/travis/build/neovim/neovim/src/nvim/normal.c:1136:3
=     #17 0x17e13a0 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:67:26
=     #18 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
=     #19 0xee7ee4 in main /home/travis/build/neovim/neovim/src/nvim/main.c:572:3
=     #20 0x2af716d94f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
= 
= Indirect leak of 9 byte(s) in 1 object(s) allocated from:
=     #0 0x511c76 in malloc (/home/travis/build/neovim/neovim/build/bin/nvim+0x511c76)
=     #1 0xffbf64 in try_malloc /home/travis/build/neovim/neovim/src/nvim/memory.c:87:15
=     #2 0xffc124 in xmalloc /home/travis/build/neovim/neovim/src/nvim/memory.c:121:15
=     #3 0xffc5c3 in xmallocz /home/travis/build/neovim/neovim/src/nvim/memory.c:196:15
=     #4 0xffc6b8 in xmemdupz /home/travis/build/neovim/neovim/src/nvim/memory.c:214:17
=     #5 0xffd512 in xstrdup /home/travis/build/neovim/neovim/src/nvim/memory.c:429:10
=     #6 0x17e2f8d in vim_strsave /home/travis/build/neovim/neovim/src/nvim/strings.c:59:20
=     #7 0x141e979 in nfa_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp_nfa.c:6530:19
=     #8 0x13d4eef in vim_regcomp /home/travis/build/neovim/neovim/src/nvim/regexp.c:7149:12
=     #9 0x1553ddb in search_regcomp /home/travis/build/neovim/neovim/src/nvim/search.c:193:23
=     #10 0x155833b in last_pat_prog /home/travis/build/neovim/neovim/src/nvim/search.c:464:9
=     #11 0x14b059e in start_search_hl /home/travis/build/neovim/neovim/src/nvim/screen.c:5532:5
=     #12 0x14d6165 in update_prepare /home/travis/build/neovim/neovim/src/nvim/screen.c:469:3
=     #13 0x14d579e in update_single_line /home/travis/build/neovim/neovim/src/nvim/screen.c:532:5
=     #14 0x1b42a31 in win_goto /home/travis/build/neovim/neovim/src/nvim/window.c:3481:5
=     #15 0x1b457c1 in win_goto_hor /home/travis/build/neovim/neovim/src/nvim/window.c:3615:5
=     #16 0x1b3f786 in do_window /home/travis/build/neovim/neovim/src/nvim/window.c:247:18
=     #17 0xc281a4 in ex_wincmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:7364:5
=     #18 0xbade99 in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
=     #19 0xb8c5c1 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
=     #20 0x87b8b7 in call_user_func /home/travis/build/neovim/neovim/src/nvim/eval.c:21282:3
=     #21 0x8458e8 in call_func /home/travis/build/neovim/neovim/src/nvim/eval.c:6369:11
=     #22 0x85b6f3 in get_func_tv /home/travis/build/neovim/neovim/src/nvim/eval.c:6131:11
=     #23 0x853e6b in ex_call /home/travis/build/neovim/neovim/src/nvim/eval.c:2748:9
=     #24 0xbade99 in do_one_cmd /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:2242:5
=     #25 0xb8c5c1 in do_cmdline /home/travis/build/neovim/neovim/src/nvim/ex_docmd.c:609:20
=     #26 0x116ab1b in nv_colon /home/travis/build/neovim/neovim/src/nvim/normal.c:4552:18
=     #27 0x1151ae0 in normal_execute /home/travis/build/neovim/neovim/src/nvim/normal.c:1136:3
=     #28 0x17e13a0 in state_enter /home/travis/build/neovim/neovim/src/nvim/state.c:67:26
=     #29 0x11085ff in normal_enter /home/travis/build/neovim/neovim/src/nvim/normal.c:466:3
= 
= SUMMARY: AddressSanitizer: 58190 byte(s) leaked in 220 allocation(s).
==================================================
```
yes @janlazo

**Comment by janlazo** [comment]
Still broken without #8662?

**Comment by janlazo** [comment]
I suspect that this patch does not depend on 8.0.0643 and related regexp patches. Like 8.0.0493, there is a missing `xfree` in screen.c or in one of the higher-level functions because `xmalloc` shouldn't fail or cause any leaks.

**Comment by janlazo** [comment]
regexp patches were merged recently on master so do something to restart the build here.

**Comment by justinmk** [comment]
@ckelsel could you rebase?

**Comment by ckelsel** [comment]
#8853

**Pull request closed without merging**
