### PR TITLE
feat(api): support abbreviations in nvim_set_keymap

### LINKED ISSUE #19198: [Feature request]: API to create abbreviations
### Feature already in Vim?

No

### Feature description

You can create a command with: `api.nvim_create_user_command()`
You can create an autocmd with: `api.nvim_create_autocmd()`
You can create an augroup with: `api.nvim_create_augroup()`
You can create a keymapping with: `vim.keymap.set` / `api.nvim_set_keymap()`

It would nice to be able to create abbreviations with the neovim API.

### PR DESCRIPTION
**Pull request by bfredl**
closes #19198

### CODE REVIEW

**Comment by clason** [comment]
Is this done apart from docs and news.txt entry?

**Comment by bfredl** [comment]
@clason yes.

**Comment by max397574** [comment]
the easiest way which I normally use is to just install that version (or just use bob to switch to it) and then look for changes in the helpfile. These days often there are news.txt entries which you can check for their existance.
This is unrelated to this pr though and should be discussed in a discussion.

**Comment by clason** [comment]
> Is this available in NVIM v0.9.4?

No. If it doesn't have a `backport` label, it's not in a patch release and will only be in the next minor release.

> Also, How does one check if a given PR which is merged in latest stable build?

Check `news.txt`.

**Pull request merged**
