### PR TITLE
runtime: Patch filetype.vim

### PR DESCRIPTION
**Pull request by champignoom**
see [wiki](https://en.wikipedia.org/wiki/ConTeXt) and [mailing list](https://mailman.ntg.nl/pipermail/ntg-context/2020/096906.html)

### CODE REVIEW

**Comment by janlazo** [comment]
Send this upstream. When it is merged, then update your commit to include the Vim commit hash like  https://github.com/neovim/neovim/pull/13132 and https://github.com/neovim/neovim/pull/12497.

**Comment by champignoom** [comment]
[Sent to upstream](https://github.com/vim/vim/pull/7263), waiting for the merge.

**Comment by champignoom** [comment]
Patched by upstream https://github.com/vim/vim/commit/faebda8cc1ecc4d6a197e06e968df46a2841ed79

**Comment by janlazo** [comment]
Redo this PR as a vim-patch PR for patch 8.2.1964 with `./scripts/vim-patch.sh`.

**Comment by champignoom** [comment]
redone at https://github.com/neovim/neovim/pull/13242

**Pull request closed without merging**
