### PR TITLE
test: move exec_lua logic to separate module

### PR DESCRIPTION
**Pull request by lewis6991**
Also make exec_lua wrap _G.print so messages can be seen
in the test output.

### CODE REVIEW

**Comment by justinmk** [comment]
I guess this is fine because it's a rare case and we already decided it can't be lifted into the Nvim stdlib. 

But in general, we shouldn't have lots of test-only modules. Most stuff should be lifted into Nvim stdlib, or stay put in `testnvim.lua`.

**Comment by zeertzjq** [comment]
> Also make exec_lua override _G.print so messages can be seen in the test output.

Why replace existing function instead of adding a new one?

**Comment by lewis6991** [comment]
What's the problem with overriding `print`?

**Comment by lewis6991** [comment]
No it's not obvious. What utility does nvim print have inside an exec_lua block?

**Comment by zeertzjq** [comment]
Writing to the messages area and `:messages`

**Comment by lewis6991** [comment]
That's not a particularly strong case when `:messages` is cumbersome to use in tests, but I can call the original function so it is wrapped. That would have been a more obvious suggestion.

**Comment by lewis6991** [comment]
> But in general, we shouldn't have lots of test-only modules. Most stuff should be lifted into Nvim stdlib

Yes, you've made this position abundantly clear 😉 . Though, adding to the stdlib implies publicly exposing and adding unnecessary surface area, which I'm generally against.

> or stay put in testnvim.lua / testutil.lua.

I disagree. Test infrastructure code is just normal code that needs to be managed and structured like anything else. Placing it in a large flat file does not make sense here and makes `testnvim.lua` harder to understand.

Additionally, by placing this in a module, means the remote Nvim session can `require` this module directly without us having to serialize the module and send it over RPC.

**Comment by justinmk** [comment]
> Though, adding to the stdlib implies publicly exposing and adding unnecessary surface area, which I'm generally against, doubly for test code.

We have the `_` lever, assuming that some test util may be useful for other internal things besides tests. That was the origin of `shared.lua`.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
