### PR TITLE
TEST/WIP: Revert "vim-patch:8.1.1318: code for text changes is in a "misc" file"

### PR DESCRIPTION
**Pull request by blueyed**
Reverts neovim/neovim#10171

Testing if QuickBuild was affected by the merge really.
Ref: https://github.com/neovim/neovim/pull/10171#issuecomment-520068923

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, Quickbuild is not triggered for an empty "rebuild [skip travis] [skip appveyor]" commit?

**Comment by justinmk** [comment]
quickbuild does not run if files didn't change.

**Comment by blueyed** [comment]
Still nothing?

**Comment by blueyed** [comment]
Passed: http://neovim-qb.szakmeister.net/build/24240 - amended.

**Comment by blueyed** [comment]
What is the best way to trigger a rebuild then?
Feel free to close this - we should maybe look at the test failure instead then.
If it would be triggered reliably, it could be bisected then maybe.

**Comment by justinmk** [comment]
why couldn't this be bisected?

**Comment by bfredl** [comment]
I guess we could revert one of lint commits at a time and see if it helps.

**Comment by blueyed** [comment]
> why couldn't this be bisected?

Isn't it flaky?

And quickbuild not building is not heloing there in general.. 
Where can I see why it is not building?
Currently probably because it is master itself..
Should it show up in http://neovim-qb.szakmeister.net/queue?
(I do not really feel like debugging this - and would rather go / start from the failing test)
(I also still have problems finding failed tests in quickbuild's UI)

**Pull request closed without merging**
