### PR TITLE
feat(lsp): more support for vim.lsp.ListOpts.loclist

### PR DESCRIPTION
**Pull request by tom-anders**
This PR mostly applies some suggestions mentioned in #28483 to the test of `buf.lua` and `handlers.lua`. 

Also, I noticed that the `loclist` field of `vim.lsp.ListOpts` was used in some places, but it wasn't actually documented. So I fixed that and also added support for `loclist` in a place where it was missing up to now

### CODE REVIEW

**Review by MariaSolOs — APPROVED** [review]

**Review by justinmk — APPROVED** [review]
LGTM, nice cleanup. Needs conflicts resolved

**Comment by tom-anders** [comment]
(rebased to fix merge conflicts)

**Comment by justinmk** [comment]
try `make doc` and `make formatlua`

**Comment by tom-anders** [comment]
Ah, I was missing a `()` in `news.txt`, fixed now

**Pull request merged**
