### PR TITLE
[RFC] Normalise some struct names in buffer_defs.h

### PR DESCRIPTION
**Pull request by Yamakaky**
It compiles after each commit.

### CODE REVIEW

**Comment by yagebu** [comment]
Information does not have a plural, so it should be `WindowInformation` instead of `WindowInformations`, same for `QuickfixInfos`. It's also probably better to make them consistent, so both with Info or both with Information.

**Comment by glts** [comment]
As somebody who's been porting some Vim patches, I'm a bit torn about such pull request, to be quite honest with you. I'm absolutely for cleaning up *everything* ultimately, but it does lead us firmly away from old Vim (which is also good I suppose :smile:) and the patches.

If these changes are going to be accepted I think it would at least be a good service to patch porters to document such renamings in the wiki, probably somewhere as a note about merging patches. Anyway, curious to hear the project team's view on this.

Two personal notes about the names:
* I'd keep it short where reasonable `WindowInformations` -> `WindowInfo`, `ArgumentList` -> `ArgList`, and so on.
* I like your camelcasing of acronyms/abbreviations ('script ID' -> `ScriptId`). Google Java style has a good description plus rationale of this convention https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s5.3-camel-case

**Comment by Yamakaky** [comment]
Maybe we could even improve vim-patch.sh to automatically translate the struct names.
Sorry for Infos, my english isn't perfect ^^

**Comment by Pyrohh** [comment]
> Anyway, curious to hear the project team's view on this.

I like this because it makes struct names more in line with [the project guidelines](http://neovim.io/develop/style-guide.xml?showone=Type_Names#Type_Names) (which is already being done in places like `msgpack_rpc/channel.c`), while also being much more informative IMO.

I agree with @glts though: some of the names are too long. `arg` and `info` are just as informative in a programming context, IMO. Perhaps even `win` could be used as well, due to how frequently it appears.

> I like your camelcasing of acronyms/abbreviations ('script ID' -> ScriptId). Google Java style has a good description plus rationale of this convention https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s5.3-camel-case

I think the linked text brings up a pretty good point. I'd much rather have `XmlHttpBla` then `XMLHTTPBla` just for the sake of English correctness.

**Comment by justinmk** [comment]
It's too early for this type of refactoring. The existing names aren't that bad.

The extra friction this will cause is not worth it for the next couple of years.

**Comment by elmart** [comment]
Up to now, we have restrained ourselves to do this kind of changes, because it makes merging upstream patches more difficult.

At some point, when we think we can "unplug" from upstream, we will fully embrace this kind of refactoring, to fulfil one of our main goals (full code refactoring to make it more understandable). But that time hasn't come yet.

That said, I think this is something we could reconsider if we are able to improve patch-merging script so that it is aware of renames and performs them automatically. That would require battle-testing the script, and making sure everybody knows about that and maintains discipline to update script when performing a new rename, though.

**Comment by Yamakaky** [comment]
That's what I thought afterwards.

**Comment by Pyrohh** [comment]
> Maybe a file listing all the renames, and feed sed with it ?

That sounds like a good idea, and make sure the replacements are done word wise (something like `grep`'s `-w` option).

**Comment by Yamakaky** [comment]
It just have to take care not to change common names, like window. Maybe only print names that changed and propose a replacement ?

**Comment by Pyrohh** [comment]
> Maybe only print names that changed and propose a replacement ?

Sure, an interactive search and replace sounds like a good idea.

**Comment by justinmk** [comment]
Merging patches isn't the only problem. We often need to refer to Vim source when fixing a bug or seeing the previous implementation. If all the names are changed this is a cognitive burden.

Note that if we change the implementation of a function such that the original Vim source is no longer of interest--as we have done in many cases--then this concern is no longer valid. I'm only speaking of the notion of changing a bunch of type names & field names for which the majority of the relevant logic is still maintained by Bram and Christian.

**Pull request closed without merging**
