### PR TITLE
[RDY] plugin/matchit: create stub for matchit.vim

### PR DESCRIPTION
**Pull request by fmoralesc**
Re: compatibility issues with users doing `:so
$VIMRUNTIME/macros/matchit.vim`. (https://github.com/neovim/neovim/issues/2918)

### CODE REVIEW

**Comment by fwalch** [comment]
You could add "Fixes #2918" to the commit message.

**Comment by fmoralesc** [comment]
Done. I think this is RDY, I'll mark it as such.

**Comment by Pyrohh** [comment]
Merged, but I added a comment to the file so users know why it's there. Thanks all.

**Comment by fmoralesc** [comment]
Thanks, @Pyrohh.

**Pull request closed without merging**
