### PR TITLE
[RFC] build: Misc. small improvements

### PR DESCRIPTION
**Pull request by ghost**
Regarding the wildcard commit:

We already depend on GNU Make (for the main `Makefile`), so I figured there wouldn't be much harm in using this, as it removes the possibility that something is never added to the docs because it's missing/mispelled.

### CODE REVIEW

**Comment by Pyrohh** [comment]
Added some more commits, one addressing a small issue from #2426

**Comment by Pyrohh** [comment]
@jszakmeister could you take a look at this when you get a chance?

**Comment by justinmk** [comment]
:+1: Nice changes. I think there might be some hesitation about the wildcard, although maybe that is only related to cmake.

**Comment by Pyrohh** [comment]
I added https://github.com/Pyrohh/neovim/commit/74fbd10e5753063dc65e9d230b4e8fce0b08fc4e (see the commit message) for information.

> Nice changes. I think there might be some hesitation about the wildcard, although maybe that is only related to cmake.

Thanks :), but I don't follow... how does CMake relate to this?

**Comment by justinmk** [comment]
What I mean is that there was some debate on whether we should use a wildcard for our main build. Because cmake doesn't detect new files. But I am not sure if Makefile has the same issue.

**Comment by Pyrohh** [comment]
> What I mean is that there was some debate on whether we should use a wildcard for our main build. 

The wildcard is reevaluated each make invocation (no caching), so I'm pretty sure it will work (it worked just now when I tested it locally).

> Because cmake doesn't detect new files.

I admit I'm still unsure what you mean by that. Isn't the Makefile just invoked by cmake, so cmake's cache would have no effect on how the Make invocation operates?  (besides any build target passed as an argument to `make`)

**Comment by justinmk** [comment]
>  Isn't the Makefile just invoked by cmake, so cmake's cache would have no effect on how the Make invocation operates? 

I think so, but I never make assumptions with cmake ("magic" pops up in many unexpected places). 

Anyways LGTM.

**Comment by jszakmeister** [comment]
> I think there might be some hesitation about the wildcard, although maybe that is only related to cmake.

Yeah, that's a CMake thing.  It can prevent CMake from detecting when files have been added or removed, and so it will fail to rebuild correctly.  Here's a good answer about it: http://stackoverflow.com/questions/10914607/how-to-collect-source-files-with-cmake-without-globbing

> The wildcard is reevaluated each make invocation (no caching), so I'm pretty sure it will work (it worked just now when I tested it locally).

If you accidentally remove a file, the glob won't detect that something has disappeared and should have been built.  OTOH, it's annoying to have to touch something every time you add or remove a file.  In general though, it is really best to avoid it for source files.  In practice, globbing occurs quite frequently. :-)

> Isn't the Makefile just invoked by cmake, so cmake's cache would have no effect on how the Make invocation operates?

I don't believe we invoke make anywhere but the third-party builds.  I don't believe we're using that Makefile in the current CMake build at all.  It'd be nice for any remaining functionality to be converted and the Makefile dropped though.

**Comment by jszakmeister** [comment]
FWIW, it looks good to me.

**Comment by Pyrohh** [comment]
> I don't believe we invoke make anywhere but the third-party builds. I don't believe we're using that Makefile in the current CMake build at all. It'd be nice for any remaining functionality to be converted and the Makefile dropped though.

That makes sense, I grepped for it being used and found nothing. When it it converted, do you think it'd make sense for another CMakeLists.txt inside `runtime/doc`? I don't know if recursive make is in any way comparable to recursive CMake, hence the question.

> FWIW, it looks good to me.

Great, I'll merge after the tests.

**Comment by Pyrohh** [comment]
Weird, Linux:GCC build stalled... everything else looks good though so I'll merge.

**Comment by justinmk** [comment]
> I don't believe we invoke make anywhere but the third-party builds. I don't believe we're using that Makefile in the current CMake build at all.

Technically true, but just to be clear, it is used in bot-ci. https://github.com/neovim/bot-ci/blob/master/ci/user-docu.sh

**Comment by justinmk** [comment]
Also *technically*, the wildcard picked up a new file: https://github.com/neovim/doc/commit/22ba671bccfc1d4b5882e46ff61aa4f4af148588#diff-8b890ae6b695f51f50c87557e00797bd

which is actually redundant with index.html, for the purposes of generating the HTML site. No big deal though :)

**Comment by elmart** [comment]
IMHO, we shouldn't merge until being able to check build passes. Even if failure is unrelated (in principle), we could be inadvertently composing bugs. Better not to hurry up.

**Comment by Pyrohh** [comment]
@justinmk I can look into that, but if it has no downside besides existing than I suppose it's a waste of time (no big deal as you said).

@elmart I agree with you in general, but I merged this because it's all very straightforward IMO. Are you saying we should just be consistent about only merging things until verified by Travis? If you have any worries/questions about specific items in this PR then please say so.

**Comment by justinmk** [comment]
@Pyrohh No I was just noting it out of curiosity. It's not a problem.

**Pull request merged**
