### PR TITLE
feat: add CursorLineSign and CursorLineFold highlights

### LINKED ISSUE #14473: Add new highlight groups: CursorLineSign and CursorLineFold
I'd like to have the same colors for `CursorLineNr` and for `SignColumn` (if `SignColumn` is the current line). Currently my neovim  looks like this:
44f85035c321f2a74d519dc93b20def686198dc7
It is not possible to define a different color for the current `SignColumn`

Based on this question:
https://neovim.discourse.group/t/cursorlinenr-and-signcolumn-highlight/416

### PR DESCRIPTION
**Pull request by gpanders**
CursorLineSign and CursorLineFold are similar to CursorLineNr, but apply to the sign and fold columns, respectively.

Add a new attribute to the `sign_define()` function, "culhl", that defines the highlight used for the sign when the cursor is on the same line and the 'cursorline' setting is enabled.

Closes #14473.

### CODE REVIEW

**Comment by gpanders** [comment]
This just needs tests.

**Comment by vigoux** [comment]
Hi, I thinks this could be a candidate for upstreaming to vim. 

cc @janlazo because you are the expert for that.

**Comment by gpanders** [comment]
I sent a patch upstream: https://github.com/vim/vim/pull/9201

I'll leave it up to @janlazo and the other experienced Vim patchers (@zeertzjq @seandewar) on how they want to handle this PR. If it's accepted by Vim we can either port the patch over, but since the code is already written for Neovim (just needs a rebase) we could also just use this as-is.

**Comment by seandewar** [comment]
:+1: Personally I'd wait a lil to see if Bram has any relevant comments or changes, then convert to a vim-patch.

That said, any upstream changes could be applied in a future vim-patch PR if you were to merge as-is.

**Comment by gpanders** [comment]
Merged in Vim https://github.com/vim/vim/commit/e413ea04b716effb28eb49dbc98ad3f9f761545a

**Comment by zeertzjq** [comment]
Related: <https://github.com/vim/vim/commit/39f7aa3c3124065b50f182b1d2f7ac92a0918656>

**Comment by gpanders** [comment]
Closing in favor of #16541.

**Pull request closed without merging**
