### PR TITLE
[RFC] Update XDG fallback values for Windows

### PR DESCRIPTION
**Pull request by ghost**
The previous defaults were including the nvim suffix, causing it to apear twice
in the final path.
- kXDGDataHome is $APPDATA, e.g. Neovim configuration should be stored under
  c:\Users\username\AppData\Roaming\nvim\
- kXDGDataHome is $LOCALAPPDATA
- kXDGCacheHome is $TEMP

cc @sethjackson @equalsraf

### CODE REVIEW

**Comment by sethjackson** [comment]
I don't believe that we can do this in this manner.

There was some discussion about this awhile back and I never got around to digging into it yet
which is why I didn't open a PR for this commit.

See https://github.com/neovim/neovim/pull/3242#issuecomment-154898397

cc @justinmk @ZyX-I

**Comment by ZyX-I** [comment]
ConfigHome and DataHome have nvim suffix followed by config or data to make resulting directories be different *and* still use application subdirectory for `$APPDATA`. Config and data being in one location may be unexpected.

**Comment by equalsraf** [comment]
Watch out,  the commit message does not match the change - both kXDGConfigHome and kXDGDataHome are **LOCALAPPDATA** in this commit. 

LOCALAPPDATA is the sane default, the problem is that Windows does not distinguish between application user settings vs data.

Its `get_xdg_home(var)` that appends `nvim` to the path, how about appending something different for XDGDataHome in Windows - i.e. both kXDGConfigHome and kXDGDataHome are LOCALAPPDATA, but 

    get_xdg_home(kXDGConfigHome) -> %LOCALAPPDATA%/nvim
    get_xdg_home(kXDGDataHome) -> %LOCALAPPDATA%/nvim-data

**Comment by Pyrohh** [comment]
Thanks for all the feedback, but I'll close this. I cherry picked this under the impression that there wasn't much work needed, but that doesn't seem to be the case.

**Comment by justinmk** [comment]
> Its get_xdg_home(var) that appends nvim to the path, how about appending something different for XDGDataHome in Windows 

:+1:

**Pull request closed without merging**
