### PR TITLE
parse_msgpack: improve error messages

### PR DESCRIPTION
**Pull request by blueyed**
This inlines is_valid_rpc_response to handle the two error cases with
distinct (and improved) error messages.

Came across this when breaking neovim-python-client (missing `import datetime`):

```
2018-04-24 17:47:33,215 [DEBUG @ msgpack_stream.py:_on_data:59] 9348 - waiting for message...
2018-04-24 17:47:33,216 [DEBUG @ msgpack_stream.py:_on_data:64] 9348 - unpacker needs more data...
2018-04-24 17:47:33,216 [DEBUG @ base.py:_on_error:175] 9348 - EOF
2018-04-24 17:47:33,216 [ERROR @ base_events.py:default_exception_handler:1266] 9348 - Exception in callback _UnixReadPipeTransport._call_connection_lost(None)
handle: <Handle _UnixReadPipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 456, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/asyncio.py", line 48, in connection_lost
    self._on_error(exc.args[0] if exc else 'EOF')
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/base.py", line 177, in _on_error
    self.stop()
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/base.py", line 152, in stop
    self._stop()
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/asyncio.py", line 123, in _stop
    datetime.datetime.now(), os.getpid()))
NameError: name 'datetime' is not defined
2018-04-24 17:47:33,217 [DEBUG @ base.py:_on_error:175] 9348 - EOF
2018-04-24 17:47:33,217 [ERROR @ base_events.py:default_exception_handler:1266] 9348 - Exception in callback _UnixWritePipeTransport._call_connection_lost(None)
handle: <Handle _UnixWritePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 663, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/asyncio.py", line 48, in connection_lost
    self._on_error(exc.args[0] if exc else 'EOF')
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/base.py", line 177, in _on_error
    self.stop()
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/base.py", line 152, in stop
    self._stop()
  File "…/Vcs/neovim-python-client/neovim/msgpack_rpc/event_loop/asyncio.py", line 123, in _stop
    datetime.datetime.now(), os.getpid()))
NameError: name 'datetime' is not defined
```

### CODE REVIEW

**Comment by blueyed** [comment]
Does this make sense?
Should I go forward with fixing the lint issues?

**Comment by bfredl** [comment]
More information in error messages is nice, but this feels a bit ad-hoc. How about having one message template but include the call stack depth as a number?

**Comment by justinmk** [comment]
> I think the error should also include more data, e.g. the raw response, or anything else to see what might have failed:

Ok, but there should be a limit. We don't want to log a 10 MB response, just mention the exact size of the response.

**Comment by blueyed** [comment]
Makes sense.  It should probably log the first 10kb at most, and then the size if it is bigger or in general.

I agree with @bfredl that having a message template would be good - but my C skills are rather limited in this regard, and anybody can feel free to pick this up from here.. :)

**Comment by bfredl** [comment]
stale PR and the code has been changed in other ways. if someone wants an error message with more stack info, open a new PR.

**Pull request closed without merging**
