### PR TITLE
[RFC] event/multiqueue.c: Rename "queue" to "multiqueue".

### PR DESCRIPTION
**Pull request by justinmk**
`lib/queue.h` implements a basic queue. `event/queue.c` implements
a specialized data structure on top of lib/queue.h; it is not a "normal"
queue.

Rename the specialized multi-level queue implemented in event/queue.c to
"multiqueue", to avoid confusion when reading the code.

Before this change one can eventually notice that "macros (uppercase
symbols) are for the normal queue, lowercase operations are for the
multi-level queue", but that is unnecessary friction for new developers
(or existing developers just visiting this part of the codebase). It's also pretty 
annoying to follow even after one notices this.

### CODE REVIEW

**Comment by justinmk** [comment]
This is pretty low-risk. I'll assume there are no objections...

**Comment by Shougo** [comment]
@justinmk The CI lint errors are fixed?

**Comment by justinmk** [comment]
@Shougo Most of them were fixed, but I intentionally ignored the one about the "space after cast" because it's a clint bug. Re-running the bot-ci task now to avoid breaking other PRs.

**Comment by Shougo** [comment]
OK.

**Pull request merged**
