### PR TITLE
docs(tutor): add instruction to reload tutor ...

### LINKED ISSUE #28164: tutor tests become unresponsive on line-number mismatch
### Problem
The line-gutter's test-decorators in `:Tutor` become unresponsive after their line numbers change i.e. due to removal/addition of lines before them.

while this is perfectly understandable: _of course, the test is line number specific"_
but the issue lies in the fact that the tutorial _demands_ lines to be added/deleted

i.e. there's a contradiction in how the tutorial interacts with users, vs how the tests assume it would stay.

### Minimal Steps to reproduce
<sub>I couldn't get the clipboard to work despite `scoop install win32yank` and restart terminal. So, some steps might feel convoluted.</sub>

**Normal conditions:**

0. `nvim -c ':Tutor'` or equivalently `nvim` > `:Tutor`
1. correct the L`333` 
(say by, `332gg` > paste the following correct line > `jdd`)
    - :-) see test pass responsively

**Trigger and buggy behaviour:**

2. `308gg` `dd` `332gg` or better yet, `kdd` (both are equivalent for our purpose)
3. `0i` `f` `<ESC>` (make any change to try to make test fail): 
    - :-( see that the `✓` stays there unresponsively

**Confirmation of the diagnosis/hypothesized cause:**

4. `ki` `<RET>` `<ESC>` to insert a blank line above (i.e. bring the test line number back to '333')
5. `j0a` `<SPC>` `<ESC>` (force refresh the test):
    - :-) see the test fail responsively
6. `0dw` (neutralise edits from step 5, 7):
    - :-) see the test pass responsively

```
Fix the errors on this line and replace them with undo.
```

### Expected behavior

the test indicator on line-gutter `✗✓` stays responsive during at least the normal flow of test...

[image](https://github.com/neovim/neovim/assets/19423063/ea2d586a-0a88-4185-ad19-88555bc48373)

### Solutions?

I am not sure what an ideal, MVC solution can be. Some thoughts come to mind:

**update:** it seems that the best and minimum viable solution can be this 2nd one:

2. provide a quick shortcut command which restarts the test afresh from the line the user is at at the time of invocation
    * would require: a reminder line in tutorial text (after a deleted line) reminding user to start the test afresh
    - no downsides as far as i can see
    - full flexibility
    - not much is required to change, all the functionality required to make it work already exists
    - i.e. true to `MVC`, simple, cost effective and elegant

[fold-marker]: https://neovim.io/doc/user/fold.html#fold-marker "fold-marker"

<details open><summary>alternate solutions considered:</summary>
<p>

1. _[hash-map + array][only-upfront-cost]_ define "named chunk ranges" somehow, & refer to line numbers relative to chunk's start in tests
   <sub>(dictionaries can solve everything eventually 🤣)</sub>
    + <sub>(inspired from `powershell` config)</sub>
    + neo/vim already has [marker-based folding range][fold-marker] which can fit this purpose very well
      nevertheless, it seems non-trivial to use that in this way
    + but once done; the rest will be easy ride
    + full flexibility of attempting tests in any order
	+ no constraints on what is done to lines outside of the test chunk: i.e. full freedom to experiment _and_ edit
        + no need to make sweeping changes to fix the line locations in tests on any line insertions in the tutor

^

0. _[brute-force][continous-cost]_ hard-coding the expected line numbers after the line deletions through test
    - _requires alll the tests_ and _nothing except the tests_ to be done _sequentially_
    - i.e. would also require to save the tutorial buffer, and resume from there the next time
    - overall, toooo much restrictive

</p>
</details> 

Sample from neo/vim's marker based folding range with `{{{<N> ... }}}<N>`: 

```markdown
<!-- Chapter 1. Navigation {{{3 -->


<!-- Chapter 2. Motions {{{3 -->
```

Sample from powershell's named chunks with `#region <name> ... #endregion` :

```powershell
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
If (Test-Path "...\mambaforge\Scripts\conda.exe") {
    (& "...\mambaforge\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
}
#endregion
```

<details>
<summary><h2>Environment</h2></summary>
<p>

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1710088188     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "/mingw64/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

windows 10.0.19045 N/A Build 19045

### Terminal name/version

mintty 3.7.1 (x86_64-pc-msys)

### $TERM environment variable

xterm

### Installation

in msys2 `mingw-w64-x86_64-neovim` pkg via command: `pacboy -S neovim:x`

</p>
</details>

### PR DESCRIPTION
**Pull request by goyalyashpal**
Problem: Any change to line numbers break the line-number based tests
        from *.tutor.json. This is problematic for lessons involving
        unbalanced line deletions or insertions.
Solution: Instruct to reload the tutor, thus discarding any edits.
        Fortunately, only "Lesson 2.6: OPERATING ON LINES" involves
        such line modifications. So, this is needed only there.

Closes: https://github.com/neovim/neovim/issues/28164

### CODE REVIEW

**Comment by goyalyashpal** [comment]
> Invalid commit message: "docs(tutor): add instruction to reload tutor ..."
    Commit: df65fd981ce9d0751faf211835dc6cf0e51e9bfc
    Description ends with a period (".").
https://github.com/neovim/neovim/actions/runs/8557764439/job/23450794908#step:5:16

so, ellipsis are not used in commits with the optional body?
just asking for confirmation before removing these

**Comment by justinmk** [comment]
> so, ellipsis are not used in commits with the optional body?

 your subject ends with "..." , what is the point of that? just remove the "..."

subject is different than body.

**Comment by goyalyashpal** [comment]
> your subject ends with "..." , what is the point of that?

using in git cli, where there's no inbuilt hint regarding whether there's any further body to the commit message or not.
see below:

here in git cli, it's only these explicit ellipsis in commit title/subject which hint regarding "there's more here"

i picked this style from some git-commit message guide some time ago.

```console
$ git log --oneline -n4 --no-decorate
6ae778857 theia: Add version 1.49.1 ...           <~~~
d48d63f0b q-dir: Update to version 11.64
84c3acc8d peazip: Update to version 9.8.0
57301172f notesnook: Update to version 3.0.4
```

[pull]: https://github.com/ScoopInstaller/Extras/pull/13274

**Comment by justinmk** [comment]
Do you plan to finish this? The details about git are off topic.

**Comment by goyalyashpal** [comment]
> Do you plan to finish this?

😆 oh lol. 

* i had shared all my investigation and conclusion as far back as 2024.04.04 (more than a month ago).
* infact, i was awaiting ur response 😅. u asked me to update, which i did. but nobody never answered even then.

just to iterate here again:
* the only feasible way i could think of to solve this is to reload the tutor, 
* and i didn't get any response on how can that be done!

Verbatim quoting: 

> hi @ justinmk
> is it possible to reload/revert the tutor?
> 
> * following this: [edit-a-file](https://neovim.io/doc/user/editing.html#edit-a-file), i tried doing `:e!` inside the `:Tutor`, and it showed me blank. ...
> * i even tried rerunning `:Tutor` inside `:Tutor`, but again showed me blank.
> 
> do you have any other thoughts?
>
> _\- me at https://github.com/neovim/neovim/issues/28164#issuecomment-2037384192_

**Comment by justinmk** [comment]
This is way too much complication for what appears to be a small problem. Either send a PR that fixes it or it's wontfix.

**Pull request closed without merging**
