### PR TITLE
[RFC] version.c: Mark NA patches

### PR DESCRIPTION
**Pull request by jamessan**
- 1727: garbagecollect_for_testing()
- 1761,1762: NA Coverity issue
- 1769: Adding attributes to if_pyth's sys.stdout
- 1781: synIDattr() support for mode=g in terminal
- 1812: Athena/Motif GUI fixes
- 1838: Rename of test functions (e.g., garbagecollect_for_testing()) to start with "test_"
- 1844: More test function renames
- 1888: Calculating sleep time for RealWaitForChar
- 1903,1904,1905,1907,1911,1936: viminfo merging
- 1955: Fix for 64-bit Vim linking against 32-bit Perl due to differing time_t
- 1971: settmode() change for Solaris
- 1996,1999,2000,2005: implementation of execute()
- 2073: Reading rgb.txt
- 2093: Netbeans test
- 2094: GUI color allocation changes
- 2132, 2198: job tests

### CODE REVIEW

**Comment by Shougo** [comment]
1727 is NA, so 1719 is also NA?

**Comment by Shougo** [comment]
> 1996,1999,2000,2005,2008,2009: implementation of execute()

Well.  I think 2008 and 2009 is not NA.
Because, neovim `execute()` is not Vim8 compatible.
For example, Vim8's `execute()` supports silent argument.

**Comment by jamessan** [comment]
> 1727 is NA, so 1719 is also NA?

No, because 1719 has general variable freeing changes.  The relevant parts have been included in #5529 already.

> Well. I think 2008 and 2009 is not NA.
> Because, neovim execute() is not Vim8 compatible.
> For example, Vim8's execute() supports silent argument.

Ah, good catch.

**Comment by Shougo** [comment]
> No, because 1719 has general variable freeing changes. The relevant parts have been included in #5529 already.

I get it.

**Comment by jamessan** [comment]
I think this is good for now.

**Comment by justinmk** [comment]
> 1781: synIDattr() support for mode=g in terminal

Why NA?

**Comment by justinmk** [comment]
> 1888: Calculating sleep time for RealWaitForChar

>  1903,1904,1905,1907,1911,1936: viminfo merging

> 1996,1999,2000,2005: implementation of execute()

I'd say those are "applied" from the perspective of a plugin author or user.

**Comment by jamessan** [comment]
> > 1781: synIDattr() support for mode=g in terminal
> 
> Why NA?

I guess that should be marked applied instead.  We use `ui_rgb_attached()` for the condition that was being modified in that patch.

> 1888: Calculating sleep time for RealWaitForChar

I don't think any user/developer cares about this.  It's an implementation detail that we didn't have to worry about due to using libuv.

>  1903,1904,1905,1907,1911,1936: viminfo merging

While I can kind of see your point here, I think it's better to keep distancing ourselves from viminfo.  We have a completely different implementation, and the more we allow people to ignore that, the more likely they are to run into problems (like trying to use the `n` setting to use the same file).

>     1996,1999,2000,2005: implementation of execute()

Ok.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
