### PR TITLE
Refactor `diff.c` and add diff parsing unit tests

### PR DESCRIPTION
**Pull request by gregorias**
I have refactored `diff.c` in preparation for tackling (or helping tackle) https://github.com/neovim/neovim/issues/14521 and https://github.com/neovim/neovim/issues/14522.

I believe the refactoring changes I propose are beneficial on their own, and I tried my best to follow develop guidelines at [the wiki](https://github.com/neovim/neovim/wiki).

### CODE REVIEW

**Comment by gregorias** [comment]
The recent force push has introduced asan and tsan failure. I'm looking into this...

**Comment by gregorias** [comment]
OK, I think I found the only problem: in  lua unit tests I was creating `Diff2Hunk**` when I needed `Diff2Hunk*`.

**Comment by gregorias** [comment]
> This needs rebasing

Thanks for looking into this. I'll rebase it within the next week.

**Comment by gregorias** [comment]
I give up on reconciling differences.

**Comment by clason** [comment]
Why did you delete your branch and throw away your valuable changes? People would have been happy to help you!

**Pull request closed without merging**
