### PR TITLE
fix(lsp/codelens): remove unnecessary redraws to reduce flicker

### PR DESCRIPTION
**Pull request by lvimuser**
The idea is to clear the extmarks only when necessary, while also removing some intermediate steps which may cause the line to flicker (incrementally render the whole line, not just the resolved lens). The effect is more perceptible with multiple lenses.

The change hopefully enables users to refresh on `CursorHold` and/or `InsertLeave` and us to optionally insert the virtual text above the line (which is currently unfeasible, because the buffer bounces up and down a lot).

There's still some issues, but I think the experience is better than the current behavior.

The second commit is not part of the PR.

TODO: upload gifs showing the behavior

Current behavior

inline https://user-images.githubusercontent.com/109605931/186282647-123ba5c2-a4dc-459f-86d9-2c8bc31d1dc9.mp4
above https://user-images.githubusercontent.com/109605931/186282660-3349d73c-1e76-41d3-a6e4-918fe04a26a8.mp4

Minimal init:
<details>

```lua

local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"neovim/nvim-lspconfig",
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

local load_config = function()
	vim.lsp.set_log_level("trace")
	require("vim.lsp.log").set_format_func(vim.inspect)
	local nvim_lsp = require("lspconfig")
	local on_attach = function(_, bufnr)
		local function buf_set_option(...)
			vim.api.nvim_buf_set_option(bufnr, ...)
		end

		vim.cmd("hi! LspCodeLens ctermfg=blue")

		vim.api.nvim_create_augroup("lsp_code_lens_refresh", {})
		vim.api.nvim_create_autocmd({ "CursorHold", "InsertLeave", "BufWritePost" }, {
			group = "lsp_code_lens_refresh",
			buffer = bufnr,
			callback = vim.lsp.codelens.refresh,
		})

		vim.defer_fn(vim.lsp.codelens.refresh, 3000)
	end

	-- Add the server that troubles you here
	local name = "fsautocomplete"
	if not name then
		print("You have not defined a server name, please edit minimal_init.lua")
	end
	if not nvim_lsp[name].document_config.default_config.cmd then
		print([[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]])
	end

	nvim_lsp[name].setup({
		on_attach = on_attach,
	})

	print(
		[[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
	)
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
	local packer_group = vim.api.nvim_create_augroup("Packer", { clear = true })
	vim.api.nvim_create_autocmd(
		"User",
		{ pattern = "PackerComplete", callback = load_config, group = packer_group, once = true }
	)
else
	load_plugins()
	require("packer").sync()
	load_config()
end

vim.opt.updatetime = 250
```

</details>

<details>
<summary>Patch lines above (on master, for testing)</summary>

```patch
diff --git a/runtime/lua/vim/lsp/codelens.lua b/runtime/lua/vim/lsp/codelens.lua
index 4fa02c8db..ca06782a0 100644
--- a/runtime/lua/vim/lsp/codelens.lua
+++ b/runtime/lua/vim/lsp/codelens.lua
@@ -7,6 +7,15 @@ local M = {}
 --- to throttle refreshes to at most one at a time
 local active_refreshes = {}

+--- bufnr -> lnum -> padding
+local padding_cache_by_buf = setmetatable({}, {
+  __index = function(t, b)
+    local key = b > 0 and b or api.nvim_get_current_buf()
+    t[key] = {}
+    return rawget(t, key)
+  end,
+})
+
 --- bufnr -> client_id -> lenses
 local lens_cache_by_buf = setmetatable({}, {
   __index = function(t, b)
@@ -26,6 +35,21 @@ local namespaces = setmetatable({}, {
 ---@private
 M.__namespaces = namespaces

+---@private
+local function get_padding_lnum(bufnr, lnum)
+  if not padding_cache_by_buf[bufnr][lnum] then
+    local line = vim.api.nvim_buf_get_lines(bufnr, lnum, lnum + 1, true)[1]
+
+    local _, first = line:find('^%s*.')
+    first = first and first - 1 or 0
+
+    local padding = string.rep(' ', first)
+    padding_cache_by_buf[bufnr][lnum] = padding
+  end
+
+  return padding_cache_by_buf[bufnr][lnum]
+end
+
 ---@private
 local function execute_lens(lens, bufnr, client_id)
   local line = lens.range.start.line
@@ -137,7 +161,12 @@ function M.display(lenses, bufnr, client_id)
       return a.range.start.character < b.range.start.character
     end)
     for j, lens in ipairs(line_lenses) do
-      local text = lens.command and lens.command.title or 'Unresolved lens ...'
+      local padding = ''
+      if j == 1 then
+        padding = get_padding_lnum(bufnr, i)
+      end
+
+      local text = padding .. (lens.command and lens.command.title or 'Unresolved lens ...')
       table.insert(chunks, { text, 'LspCodeLens' })
       if j < num_line_lenses then
         table.insert(chunks, { ' | ', 'LspCodeLensSeparator' })
@@ -145,7 +174,8 @@ function M.display(lenses, bufnr, client_id)
     end
     if #chunks > 0 then
       api.nvim_buf_set_extmark(bufnr, ns, i, 0, {
-        virt_text = chunks,
+        virt_lines = { chunks },
+        virt_lines_above = true,
         hl_mode = 'combine',
       })
     end
@@ -203,13 +233,18 @@ local function resolve_lenses(lenses, bufnr, client_id, callback)
           -- Eager display to have some sort of incremental feedback
           -- Once all lenses got resolved there will be a full redraw for all lenses
           -- So that multiple lens per line are properly displayed
-          api.nvim_buf_set_extmark(
-            bufnr,
-            ns,
-            lens.range.start.line,
-            0,
-            { virt_text = { { lens.command.title, 'LspCodeLens' } }, hl_mode = 'combine' }
-          )
+          api.nvim_buf_set_extmark(bufnr, ns, lens.range.start.line, 0, {
+            virt_lines = {
+              {
+                {
+                  get_padding_lnum(bufnr, lens.range.start.line) .. lens.command.title,
+                  'LspCodeLens',
+                },
+              },
+            },
+            hl_mode = 'combine',
+            virt_lines_above = true,
+          })
         end
         countdown()
       end, bufnr)
```

</details>

### CODE REVIEW

**Comment by lvimuser** [comment]
From the spec: 
> if a client sends a request to the server and the client state changes in a way that it invalidates the response it should do the following:
> - cancel the server request and ignore the result if the result is not useful for the client anymore. If necessary the client should resend the request.
> - keep the request running if the client can still make use of the result by for example transforming it to a new result by applying the state change to the result.

I guess we could transform it instead of making another request, but we don't have that information (from `on_lines`). Thoughts?

**Comment by lvimuser** [comment]
It turned out a bit more complicated than I thought, and I'm not happy with the code, but it works...

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/17016

Looking around I see we have debounce logic in lsp.lua. Can we somehow hook into the [debounce](https://github.com/neovim/neovim/blob/2379699b1e7cd944ad3d8169d9c9d4072d0fb771/runtime/lua/vim/lsp.lua#L626-L653) "tick" in [send_changes()](https://github.com/neovim/neovim/blob/2379699b1e7cd944ad3d8169d9c9d4072d0fb771/runtime/lua/vim/lsp.lua#L606) ?

> Could we not, then, emit events from the didChange handler, after sending the notification to the server? (same idea, but coupled with the provided debounce configuration; I think this matches emacs' lsp-mode and vscode).

Sure, maybe. 

> TODO: upload gifs showing the behavior

A small screenshot showing the UI would help to understand what this is about.

This PR as-is looks like too much code. Why is `extmarks_cache_by_buf` needed? Hope we can avoid more caches.

**Comment by lvimuser** [comment]
> Looking around I see we have debounce logic in lsp.lua. Can we somehow hook into the [debounce](https://github.com/neovim/neovim/blob/2379699b1e7cd944ad3d8169d9c9d4072d0fb771/runtime/lua/vim/lsp.lua#L626-L653) "tick" in [send_changes()](https://github.com/neovim/neovim/blob/2379699b1e7cd944ad3d8169d9c9d4072d0fb771/runtime/lua/vim/lsp.lua#L606) ?

That's what I thought, but I have no idea on the implementation. Autocommands, libuv ([1](https://github.com/luvit/luvit/blob/master/deps/core.lua), [2](https://github.com/luvit/luvit/blob/master/deps/core.lua))? It'd be nice to have something like `LspAfterChange` perhaps.

>
> A small screenshot showing the UI would help to understand what this is about.

I've update the first comment with a screen capture of the current behavior (imo, it's really bad). Note that it only affects lenses which are required to be resolved. If the server sends a resolved lens on the first call (see ocamllsp), then the current implementation works fine.
 
> 
> This PR as-is looks like too much code. Why is `extmarks_cache_by_buf` needed? Hope we can avoid more caches.

Yea, I don't like it either. Hopefully it showcases why something similar is necessary (this PR or not).

It's necessary because the approach is to manually track the extmarks (again, maybe there's a better way), so that we don't have to clear everything on each call (which causes part of the flickers). 

---------

Another change is to not redraw each resolved lens unconditionally. If there's multiple lenses per line, we should wait until all those lenses are resolved, because we can't keep track of its position (and I think should be made regardless of the PR). See 
[3](https://github.com/neovim/neovim/pull/19707/files#diff-1c5e2d595510f83d2e6b841d3a9e6024835af51e5a6557be4e6f7b62d84a27d8R206-R224), [4](https://github.com/neovim/neovim/pull/19707/files#diff-1c5e2d595510f83d2e6b841d3a9e6024835af51e5a6557be4e6f7b62d84a27d8R316-R348).

As an example, the current behavior is 
```
Unresolved ...        | Unresolved ...  (1)
a                                       (2)
a                     | Unresolved ...  (3)
b                                       (4)
a                     | b               (5)
```
And by doing so we can skip those intermediate states/transitions (also, less redraws), going 1 -> 3 -> 5 instead (if we known which lenses are unresolved, otherwise 1 -> 5).

----

Also, some thoughts on [5](https://github.com/neovim/neovim/pull/19707/files#diff-1c5e2d595510f83d2e6b841d3a9e6024835af51e5a6557be4e6f7b62d84a27d8R128-R131) and [6](https://github.com/neovim/neovim/pull/19707/files#diff-1c5e2d595510f83d2e6b841d3a9e6024835af51e5a6557be4e6f7b62d84a27d8R440-R473)?

It would be nice if we could delete an extmark when deleting the corresponding line. `on_lines` is not sufficient because on, e.g. a delete, will be triggered **after** the change, so we might end up deleting more than necessary.

----

Note that VSCode's implementation waits for an additional `400ms` without document/buffer changes before triggering the request (and I think something similar might be necessary, still playing with it). And, I think Emacs' lsp mode triggers on `Idle` (for which there's a timer (defaulting to 500ms) that restarts on any(?) LSP request).

**Comment by mfussenegger** [comment]
I think it would be good to first get proper multi-client support in place before addressing flickering as this seems to introduce quite some additional complexity.

> For some handlers (e.g. documentColor/semanticTokens/codelens/inlayHints), should we consider making the request on on_lines?

If we do something like that it would still have to be opt-in. Not everyone agrees with having code lens enabled

> Another change is to not redraw each resolved lens unconditionally. If there's multiple lenses per line, we should wait until all those lenses are resolved

I think that sounds good. It probably already goes a long way in reducing the flickering while being simpler to implement

**Comment by lvimuser** [comment]
Turns out we didn't need the cache thing. I think this is acceptable now?
I'll upload a video showing the new behavior later.

**Pull request closed without merging**
