### PR TITLE
terminal: absolute CWD in term:// URI

### LINKED ISSUE #11288: Terminal buffer PWD does not survive session restoration
- `nvim --version`:

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: 8.1) behaves differently? No. `vim` appears to suffer from the same problem.
- Operating system/version: macOS 10.14.6 Mojave
- Terminal name/version: iTerm2 3.3.6
- `$TERM`: `xterm-256color`

#### Setup

This creates a few directories and a program that just prints its pwd in a loop

```bash
mkdir foo
mkdir bar
cat > print-pwd.sh <<'EOF'
#!/bin/bash
while true; do
  echo $PWD
  sleep 1
done
EOF
chmod +x print-pwd.sh
```

#### Steps

```
nvim -u NORC
:cd foo
:terminal ../print-pwd.sh
:cd ../bar
:mksession! ~/pwd-session.vim
:qa

nvim -u NORC -S ~/pwd-session.vim
```

### Actual behaviour

The restored terminal buffer prints the path to the `bar` directory.

### Expected behaviour

The restored terminal buffer prints the path to the `foo` directory, the same as it did before closing neovim.

### PR DESCRIPTION
**Pull request by cjlarose**
Fixes #11288

This PR fixes terminal buffer `cwd` restoration from a session by making sure to write the full, absolute path to the `cwd` of any terminal buffer to its `fname`.

~~I haven't fixed tests yet since I'm not sure if this is the right approach from a design perspective. I noticed that the `setfname` procedure does some work to expand the path name to an absolute path for non-terminal buffers (using the procedure `fname_expand`, which it turn calls `fix_fname`), so maybe that's the right place for this change to go instead? It's a little bit awkward for it to go there, though, since it'd have to parse apart the `term://` string to get the `cwd`, then get the absolute path of that `cwd`, and construct a new `term://` string. It's doable, though.~~

~~Anyway, I could use some help in figuring out where to put this logic. Then I'm happy to implement the changes and fix up all the tests.~~

### CODE REVIEW

**Comment by justinmk** [comment]
No objection, we can try it. Long-term we want https://github.com/neovim/neovim/issues/3278

**Comment by cjlarose** [comment]
@justinmk I fixed the failing tests and added a new test. Everything's green!

**Comment by cjlarose** [comment]
Rebased on master

**Review by justinmk — COMMENTED** [review]
Thanks for followup. I pushed some changes, see comments.

**Pull request merged**
