### PR TITLE
fix: v_P behavior for clipboard registers

### LINKED ISSUE #18408: behavior v_P with clipboard=unnamedplus option
### Feature already in Vim?

_No response_

### Feature description

Yesterday I discovered the ability to put text in visual mode without overwriting the register. That was added in #17346. I expected it to work with the clipboard=unnamedplus option as well. In fact v_P and v_p do the same thing. 
The problem is that the unnamed register will keep its state, while the quoteplus will be overwritten. Then when I try to put the text again, nvim will use quoteplus that was overwritten the last time.

p.s. Unfortunately, I was not able to test it in vim

NVIM v0.8.0-dev

### PR DESCRIPTION
**Pull request by Shougo**
Fix #18408

### CODE REVIEW

**Comment by zeertzjq** [comment]
TBH I actually think using the blackhole register is much easier and faster (and it was also your initial implementation), and unlike saving and restoring `y_previous` it works for pasting text deleted using `d`.

**Comment by Shougo** [comment]
@zeertzjq I have tested it.  But it does not work...  Oh no.

**Comment by Shougo** [comment]
If I use `_` register instead, `@-` does not save the changes.
It is intended behavior?

**Comment by zeertzjq** [comment]
Of course use the blackhole register will not change `@-`.

**Pull request closed without merging**
