### PR TITLE
ci: upgrade tree-sitter from 0.15.2 to 0.15.9

### PR DESCRIPTION
**Pull request by blueyed**
Via https://github.com/neovim/neovim/pull/10292 where it might help with build issues then.

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
This does not update tree-sitter-c, which I've hoped would help / be required for https://github.com/neovim/neovim/pull/10292.

**Comment by blueyed** [comment]
@bfredl 
Does it make sense without tree-sitter-c?
Shouldn't tree-sitter-c also get a new release?

**Comment by bfredl** [comment]
@blueyed How does tree-sitter inhibit upgrading luarocks? 

The binary interface between tree-sitter lib and tree-sitter languages should be somewhat stable, so every patch release of tree-sitter doesn't need a corresponding language release.

**Comment by blueyed** [comment]
> How does tree-sitter inhibit upgrading luarocks?

I don't know - but after rebasing that PR it fails to install it there.  https://github.com/neovim/neovim/pull/10292#issuecomment-536739883

Merging this for now then.

**Comment by bfredl** [comment]
Just seems like you bundled two unrelated things together in the same PR. Why not only do the luarocks part in  #10292 ?

**Pull request merged**
