### PR TITLE
ci: correctly label dependencies PRs

### PR DESCRIPTION
**Pull request by vigoux**
Configures the labeler to handle PRs related to third-party.

I saw that when opening #14776.

### CODE REVIEW

**Review by jamessan — APPROVED** [review]

**Comment by teto** [comment]
you could add `topic: build` too.

**Comment by vigoux** [comment]
Isn't `topic: build` more for our build process?

**Comment by teto** [comment]
the third-party folder contains CMakeLists.txt etc and I would include third-party  into our build process. Anything that touches a CMakeList.txt deserves `topic: build` I would say ?

**Comment by vigoux** [comment]
> Anything that touches a CMakeList.txt deserves `topic: build` I would say ?

Yup, I did a little more than that even.

**Review by teto — APPROVED** [review]

**Pull request merged**
