### PR TITLE
fix(lua): show stacktrace for error in vim.on_key() callback

### LINKED ISSUE #31019: vim.on_key callback error display missing stack traceback
### Problem

The display for a `vim.on_key()` callback error does not have a stack traceback.
```
Error executing  vim.on_key Lua callback: vim/_editor.lua:0: Error executing 'on_key' with ns_ids '14'
    Messages: [string ":source (no file)"]:2: in F2()
stack traceback:
        [C]: in function 'error'
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I don't know if this is a general problem with callbacks or specific to `vim.on_key()`

### Steps to reproduce

source the following and  hit any key.
```lua
local function F2()
    error("in F2()")
end
local function F1()
    F2()
end
local function handler()
    F1()
end
vim.on_key(handler)
```

### Expected behavior

Calling `handler` directly produces the following. That's a good place to start.
```
stack traceback:                                                                                    
        [C]: in function 'error'                                                                    
        [string ":source (no file)"]:6: in function 'F2'                                            
        [string ":source (no file)"]:9: in function 'F1'                                            
        [string ":source (no file)"]:12: in function 'handler'                                      
        [string ":source (no file)"]:15: in main chunk                                              
```

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/b34e137e43d359c8db4fb76028dea3b410842aff

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

ubuntu

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

make install

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #31019

### CODE REVIEW

**Comment by errael** [comment]
I tried the PR.

I also tried `vim.keymap.set()` and `nvim_create_automcd()` callbacks, see below; they each only have one `stack traceback`. The `autocmd` looks best. The `keymap` one doesn't indicate that it's coming from a mapping (should I open something about this? And saying which mapping would be great if possible.).

The second `stack traceback` for `on_key()` and the inclusion of `'xpcall'` look weird. 

```
Error executing  vim.on_key Lua callback: vim/_editor.lua:0: Error executing 'on_key' with ns_ids '11'
    Messages: [string ":source (no file)"]:6: in F2()
stack traceback:
        [C]: in function 'error'
        [string ":source (no file)"]:6: in function 'F2'
        [string ":source (no file)"]:9: in function 'F1'
        [string ":source (no file)"]:12: in function <[string ":source (no file)"]:11>
        [C]: in function 'xpcall'
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'error'
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**nvim_create_autocmd()**
```
Error detected while processing OptionSet Autocommands for "*":
Error executing lua callback: [string ":source (no file)"]:2: in F2()
stack traceback:
        [C]: in function 'error'
        [string ":source (no file)"]:2: in function 'F2'
        [string ":source (no file)"]:5: in function 'F1'
        [string ":source (no file)"]:8: in function 'handler'
        [string ":source (no file)"]:13: in function <[string ":source (no file)"]:12>
```

**vim.keymap.set()**
```
E5108: Error executing lua: [string ":source (no file)"]:2: in F2()
stack traceback:
        [C]: in function 'error'
        [string ":source (no file)"]:2: in function 'F2'
        [string ":source (no file)"]:5: in function 'F1'
        [string ":source (no file)"]:8: in function 'handler'
        [string ":source (no file)"]:15: in function <[string ":source (no file)"]:12>
```

**Comment by zeertzjq** [comment]
This should be better now:
```
Error executing vim.on_key() callbacks: vim/_editor.lua:0:
With ns_id 4: [string ":source (no file)"]:2: in F2()
stack traceback:
        [C]: in function 'error'
        [string ":source (no file)"]:2: in function 'F2'
        [string ":source (no file)"]:5: in function 'F1'
        [string ":source (no file)"]:8: in function <[string ":source (no file)"]:7>
        [C]: in function 'xpcall'
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by errael** [comment]
Tried the update. Works for me.

**Comment by errael** [comment]
I just noticed that the `handler()` frame isn't in the trace. But it does give the `ns_id` which is the most important thing

**Pull request merged**
