### PR TITLE
[RFC] Fix #9889

### LINKED ISSUE #9889: :stopinsert should not leave next terminal mode
- `nvim --version`: NVIM v0.4.0-570-gddd0eb6f5
- Vim (version: ) behaves differently? yes
- Operating system/version: Ubuntu 18.04 Linux 4.18.20-041820-generic
- Terminal name/version: MobaXterm v11.1
- `$TERM`: xterm-256color. But in neovim, $TERM is screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
:stopinsert
i
```

### Actual behaviour
Do not enter terminal mode

### Expected behaviour
Enter terminal mode

I think the problem is that `:stopinsert` leave the next terminal mode. And I think [this commit](https://github.com/neovim/neovim/commit/d928b036dc2be8f043545c0d7e2a2b2285528aaa) is the reason.

### PR DESCRIPTION
**Pull request by glacambre**
Sorry for introducing this regression. Hopefully this fixes it and doesn't create new bugs :).

Problem: Using `:stopinsert` while in normal mode in a terminal buffer
prevents neovim from entering insert mode.

Solution: Move `stop_insert_mode = false` from terminal_check to
terminal_enter to be consistent with edit.c, as suggested by @bfredl in
 #9889.

Closes https://github.com/neovim/neovim/issues/9889.

### CODE REVIEW

**Comment by mars90226** [comment]
I think using `:stopinsert` in buffers other than terminal buffer will also cause prevent next terminal buffer entering insert mode. But I don't know if that will make a difference.

**Comment by bfredl** [comment]
@mars90226 That should also be fixed by this patch.

**Comment by bfredl** [comment]
Merged after removing `@` in front of `@bfredl` mention (otherwise one would get email everytime someone rebases neovim master on top of their github branch).

**Comment by glacambre** [comment]
Oh, I wasn't aware of that, thanks for letting me know :).

**Pull request merged**
