### PR TITLE
fix(doc): remove duplicate word

### PR DESCRIPTION
**Pull request by glepnir**

### CODE REVIEW

**Comment by glepnir** [comment]
no problem :)

**Comment by seandewar** [comment]
It's auto-generated from here, so this needs a change too @dundargoc: https://github.com/neovim/neovim/blob/f6232e160b96e2607edcd5afa7207a1e4aadf805/src/nvim/api/extmark.c#L392

**Comment by smjonas** [comment]
Seems like this PR was not included in #20150 @dundargoc

**Comment by dundargoc** [comment]
It's rewind time.

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/20394

**Pull request closed without merging**
