### PR TITLE
[WIP] debug: gcov: use __gcov_flush instead of __gcov_dump

### PR DESCRIPTION
**Pull request by blueyed**
This restores missing coverage again.

Followup to https://github.com/neovim/neovim/pull/10230.
Still fixes https://github.com/neovim/neovim/pull/3926#issuecomment-502343527.

Note that gcc 9.1. supports `%p` for expansion of PID in `-fprofile-dir`, which could be useful here instead / additionally (https://github.com/gcc-mirror/gcc/commit/945d4d55213).

I've also found this in the doc (https://github.com/gcc-mirror/gcc/blob/master/gcc/doc/invoke.texi):

> supports locking, the data files will be correctly updated.  Unless
a strict ISO C dialect option is in effect, @code{fork} calls are
detected and correctly handled without double counting.

Is a strict ISO C dialect option in effect here?

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
Seems like AppVeyor is failing reliably/consistently with executable related tests now..
Will try if https://github.com/neovim/neovim/pull/10209 fixes it, and then we might have kind of an explicit test for it.

**Comment by blueyed** [comment]
Yeah, failed again:
```
[  FAILED  ] C:/projects/neovim/test/functional\eval\executable_spec.lua @ 18: executable() sibling to nvim binary
C:/projects/neovim/test/functional\eval\executable_spec.lua:26: Expected objects to be the same.
Passed in:
(nil)
Expected:
(string) 'arg1=lemon;arg2=sky;arg3=tree;'
```

Will wait for the non-gcov job, and then test #10209.

**Comment by blueyed** [comment]
So it looks like the initial change broke `printargs-test`..!?
Any ideas?  Could not find anything in the build log, but the "(nil)" return result might indicate something already.

Added some diagnostics, let's see.

Otherwise it should be moved into os/pty_process_unix.c (where it started to be necessary from the beginning only).
But it is unclear to me if it should be done with `libuv_process_spawn` on UNIX at least also.

**Comment by justinmk** [comment]
Only pty AFAIR

**Comment by blueyed** [comment]
Pulled the main fix into https://github.com/neovim/neovim/pull/10260 - can be re-used later if debugging this further is necessary.

**Pull request closed without merging**
