### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by ckelsel** [comment]
vim-patch:8.0.0494: build failure with older compiler on MS-Windows

**Comment by janlazo** [comment]
vim-patch:8.0.0304: assign test fails in the GUI

**Comment by justinmk** [comment]
8.0.0449

**Comment by justinmk** [comment]
I did not include the ballon_show patches as NA. We plan to include that feature, also those tests are skipped with a feature-check.

**Pull request merged**
