### PR TITLE
vim-patch:8.0.1281, vim-patch:8.0.1282

### PR DESCRIPTION
**Pull request by justinmk**
saves 3 ms

### CODE REVIEW

**Comment by jamessan** [comment]
Should this also include [8.0.1284](https://github.com/vim/vim/releases/tag/v8.0.1284)?

**Comment by blueyed** [comment]
8.0.1284 can go by itself I think.
@justinmk 
Can you fix the conflicts, please?

**Comment by jamessan** [comment]
@justinmk Going to revisit this soon?

**Comment by justinmk** [comment]
@jamessan Updated. I had wanted to double check past changes to filetype.vim, I think I covered them now. 

Very annoying how GitHub displays the merge from upstream...

**Pull request merged**
