### PR TITLE
[RFC] deps: Update LuaJIT to 2.0.4

### PR DESCRIPTION
**Pull request by fwalch**

### CODE REVIEW

**Comment by fwalch** [comment]
Added the LuaJIT changelog to the commit message per @Pyrohh's suggestion. I think we should start doing this for all our dependency updates.

A passing build (except GCC timeout) that compiled and used the updated LuaJIT is [here](https://travis-ci.org/neovim/neovim/builds/62926824).

**Comment by fwalch** [comment]
:wink:

**Comment by Pyrohh** [comment]
Damn, that's a nice commit message :smirk:
LGTM

**Comment by justinmk** [comment]
> I think we should start doing this for all our dependency updates.

:+1:

**Pull request closed without merging**
