### PR TITLE
feat(lsp): add tcp support

### LINKED ISSUE #11911: LSP with servers using TCP
Some language servers require TCP to work with them.

For example, recently Godot 3.2 was released with LSP support. But LSP works only through Websocket. [This](https://github.com/godotengine/godot/pull/35864#) PR switches Godot's LSP to TCP and now can be suported for the Vim plugins. I tested it with coc.nvim and everything works. Is in possible to add TCP support to the native implementation?

### PR DESCRIPTION
**Pull request by mfussenegger**
The plan is to make it possible to have a fully decoupled transport - in addition to TCP it should also be possible to have a "same process" transport (e.g. that null-ls could utilize) 

Language servers like Godot only support TCP and currently require workarounds
like socat.

Native TCP support will also allow us to use a dummy server in the tests. Opposed to the fake-lsp-server process it would have the advantage that the server behavior could be part of a test case, as a fake tcp server can run in the same process. Currently the expected notifications and responses are split off in a separate file.

Used like:

```lua
vim.lsp.start({ name = 'godot', cmd = vim.lsp.rpc.connect('127.0.0.1', 6008) })
```

closes https://github.com/neovim/neovim/issues/11911

### CODE REVIEW

**Comment by mfussenegger** [comment]
@jose-elias-alvarez Could you have a look at this to check if this would allow null-ls to stop monkey-patching rpc.start?

This PR would allow `cmd` to be a function that will receive the dispatchers and must return a table with `notify`, `request`, `is_closing` and `terminate`. (The `handle` is no longer exposed or used)

**Comment by jose-elias-alvarez** [comment]
From a null-ls perspective this looks great! This should be more or less a drop-in replacement for us (I’m away from a PC for the next week or so but will test this as soon as I can).

**Comment by eschmidscs** [comment]
Hi

I guess I just need some help here. I'm all newbie, lua, neovim, lsp...
I'm trying to use this for a language server that just uses some port available.

So instead of 
```
vim.lsp.start({name="lsp", cmd=vim.lsp.rpc.connect(host, port)})
```
I try to do the following (simplified):
```
vim.lsp.start({
  name="lsp",
  cmd=function()
    start_lsp()
    port=get_lsp_port()
    return vim.lsp.rpc.connect(host, port)
  end
})
```

This fails with
```
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:20: Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/lsp.lua:1283: attempt to index upvalue 'rpc' (a function value)
```

It looks like something local should not be so, but even removing all this did not help.
Can you give me some hint what is wrong?

Or: Is this the completely wrong attempt? How should I get the port after server start? When should the server be started?

**Comment by clason** [comment]
Sorry, but this is not a support forum -- usage questions should be asked on https://app.element.io/#/room/#neovim:matrix.org or https://neovim.discourse.group.

**Comment by eschmidscs** [comment]
I'll ask on discourse. I started here because it seems directly related to this PR (at least on how to use the tcp stuff).

**Comment by neovim-discourse** [comment]
This pull request has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/starting-order-for-tcp-based-lsp-lua-error-attempt-to-index-upvalue/3108/1

**Pull request merged**
