### PR TITLE
[RFC] vim.c: use FOR_ALL_* sugar

### PR DESCRIPTION
**Pull request by justinmk**
Just a small line reduction.

### CODE REVIEW

**Comment by justinmk** [comment]
OS X builds may need to be put back on 'ignore' until we can figure out the 'unprotected call' error.

**Comment by tarruda** [comment]
> OS X builds may need to be put back on 'allowed failures' until we can figure out the 'unprotected call' error.

Did this happen on the functional tests? If it was on the unit tests only maybe [this line](https://github.com/neovim/neovim/blob/master/test/functional/helpers.lua#L3) will fix it

**Comment by tarruda** [comment]
Maybe [this](http://lua-users.org/lists/lua-l/2011-08/msg00803.html) is the problem

**Comment by oni-link** [comment]
LGTM.

**Comment by justinmk** [comment]
merged

**Pull request closed without merging**
