### PR TITLE
ci(labeler): add runtime label if filetype.lua is changed

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
Is it possible to do this in a more structured manner? I'd say anything under `runtime` should be labelled "runtime" _unless_ it has a more specific label (like "documentation" or "provider" etc.) based on a specific file or subdirectory?

**Comment by zeertzjq** [comment]
Maybe the "lua" label should be applies to fewer files?

**Comment by clason** [comment]
> Maybe the "lua" label should be applied to fewer files?

Good idea, but then we need to decide on a clear description for that label explaining _which_ files (or concepts) it applies to. (It currently has no description, which is not good...)

**Comment by dundargoc** [comment]
> Is it possible to do this in a more structured manner? I'd say anything under `runtime` should be labelled "runtime" _unless_ it has a more specific label (like "documentation" or "provider" etc.) based on a specific file or subdirectory?

Absolutely. Let me experiment/test on a few solutions and I'll update once I feel I have a good enough solution.

**Pull request closed without merging**
