### PR TITLE
chore: PVS/V751: ignore warning

### PR DESCRIPTION
**Pull request by dundargoc**
There's already an ignore directive but it's placed on the wrong line.
This commit should correct it.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! I don't think this is classified as "chore", it is a bug fix. The "chore" prefix doesn't really add anything and actually is just noise.

**Comment by bfredl** [comment]
I don't think it is a bug fix if doesn't change any behavior. Though we probably want a better label for "making static analysis happy" (still using "bug" if the analysis found an actual bug, of c).

**Comment by clason** [comment]
Probably "refactor", then? ("A code change that neither fixes a bug nor adds a feature.")

**Comment by bfredl** [comment]
yes, that's a better approximation :)

**Pull request merged**
