### PR TITLE
[RDY] PVS/V1001: Remove assignment to unused variable

### PR DESCRIPTION
**Pull request by G-flat**
Fixes PVS warning [V1001](https://www.viva64.com/en/w/v1001/).
Removes assignment to `ns_id` which is unused by the end of `nvim_buf_add_highlight()`.

### CODE REVIEW

**Comment by vigoux** [comment]
Hmmm this actually looked like a typo on the line just below the one used here.
Indeed, looking at the documentation, the function should return the namespace ID used for this operation, chich is `ns_id` here.

**Comment by G-flat** [comment]
> Hmmm this actually looked like a typo on the line just below the one changed here.
> Indeed, looking at the documentation, the function should return the namespace ID used for this operation, chich is `ns_id` here.
Changed.

**Comment by vigoux** [comment]
Hmmm... I think that your original fix is fine in the end, sorry for asking to revert.

**Comment by G-flat** [comment]
> Hmmm... I think that your original fix is fine in the end, sorry for asking to revert.

Reverted.

**Comment by vigoux** [comment]
Yup, there is a conflict in `buffer.c`.

**Review by bfredl — APPROVED** [review]

**Pull request merged**
