### PR TITLE
LSP: make the hover window nomodifiable

### PR DESCRIPTION
**Pull request by cbarrete**

### CODE REVIEW

**Review by teto — APPROVED** [review]

**Comment by teto** [comment]
shouldn't we do that on window creation ? ~ open_floating_preview

**Comment by cbarrete** [comment]
The buffer/window are created in `fancy_floating_markdown` instead, so we don't even call `open_floating_preview`.

**Comment by cbarrete** [comment]
Also `open_floating_preview` already creates `nomodifiable` buffers.

**Comment by teto** [comment]
so lets say in the `M['textDocument/hover']` callback or in `fancy_floating_markdown`. Seems cleaner to set the correct value at creation rather than in subsequent calls.

**Comment by cbarrete** [comment]
Good point. I'll put it in `fancy_floating_markdown` since it should use eventually `open_floating_preview`.

**Comment by clason** [comment]
These float functions are due for a refactor anyway (as you note, hover, preview, and signature should have much larger shared codepath); see @tjdevries massive refactor in https://github.com/neovim/neovim/pull/12333 that should allow addressing this.

**Comment by tjdevries** [comment]
@cbarrete I think you might need to rebase again -- it looks like your history got a little messed up.

**Pull request merged**
