### PR TITLE
Ensure `tstree:parse()` always return trees and changes

### PR DESCRIPTION
**Pull request by bew**
Hello!

While reading the lua source code around treesitter, I noticed the following:

When parsing from an invalidated state, `tstree:parse()` returns the trees and the changes.
https://github.com/neovim/neovim/blob/6cc6e11929ad76a2dc5204aed95cb9ed1dafde23/runtime/lua/vim/treesitter/languagetree.lua#L167

But when calling `tstree:parse()` again, with a valid state, the function returns only the trees.
:point_right: This would change the behavior of calls like `tstree:parse()[1]` expecting to get the list of trees, and instead getting the first tree.
https://github.com/neovim/neovim/blob/6cc6e11929ad76a2dc5204aed95cb9ed1dafde23/runtime/lua/vim/treesitter/languagetree.lua#L99

I believe this is a mistake

---

It seems that none of the functions have their return value type documented, _is that intentional_?
:point_right: it's a bit hard to know what to expect from calling the function, other than trying them..

### CODE REVIEW

**Comment by clason** [comment]
> It seems that none of the functions have their return value type documented, is that intentional?

It's not; documentation is lacking since tree-sitter support is still experimental and in quite a bit of flux.

**Comment by vigoux** [comment]
> I've never used these directly, so I don't have an opinion. But I'd be happy to do the changes if you think it's right

I indeed think it is, but that makes it a breaking change. Though this functionnality was not really used (I think), so it does not matter that much yet.

**Comment by clason** [comment]
bump -- do we still want this for 0.8?

**Comment by vigoux** [comment]
Not sure, I'd rather push that for 0.9 as it is not a really important change feature-wise.

**Comment by clason** [comment]
@lewis6991 is this still relevant after your refactors?

**Comment by lewis6991** [comment]
Yes kind of. I'm not sure what the annotations are but we could go either way. I do see the appeal of returning non-nil.

**Comment by lewis6991** [comment]
> This would change the behavior of calls like tstree:parse()[1] expecting to get the list of trees, and instead getting the first tree.

I don't think this is true. varargs and tables work very differently.

**Comment by clason** [comment]
@bew can you rebase then, so we can test this with our current code/annotations?

**Comment by lewis6991** [comment]
> I think that we'd need to go the other way around: never return the changes an only notify them using the on_changed_tree callback.
>
> The problem is that (as you noticed) it is not guaranteed for a plugin that it'll be the first one to call tstree:parse() and thus get the changes.

I completely agree with this.

**Comment by bew** [comment]
Yeah, the change here is really minimal, good call to move on to another one 👍

**Pull request closed without merging**
