### PR TITLE
feat(events): add new events for wildmenu

### PR DESCRIPTION
**Pull request by glepnir**
add `WildCompleteChanged WildCompleteDone` events for wildmenu.  it's useful to create some callbacks when using wildmenu. any thought.

### CODE REVIEW

**Comment by zeertzjq** [comment]
This will likely break a lot of autocommands.

**Comment by glepnir** [comment]
so create new events like `WildCompleteChanged` and `WildCompleteDone` ?

**Comment by justinmk** [comment]
> This will likely break a lot of autocommands because they don't expect `CompleteChanged` to be triggered there

can we add a `v:event` flag or put a hint in the event "pattern"?

Not in favor of adding new special-case events for this

**Comment by zeertzjq** [comment]
Then I think it's better to make this achievable using `CmdlineChanged`.

**Comment by glepnir** [comment]
> Not in favor of adding new special-case events for this

Yes. I would also like to avoid creating a new time at the beginning. agree use `CmdlineChanged` ?

**Comment by glepnir** [comment]
and then which for wild cancel or apply

**Comment by zeertzjq** [comment]
`CmdlineChanged` is already triggered when wildmenu completion changed. You don't need to trigger it in another place.

**Comment by glepnir** [comment]
emm okay. wild complete adds the current item to cmdline and triggers cmdlinechanged. The previous idea is similar to the trigger mode of complete. It doesn't seem necessary now. Then just need a event for wildcancel and wild apply..

**Comment by glepnir** [comment]
we don't need this.

**Pull request closed without merging**
