### PR TITLE
Add support for .tar.zst files

### PR DESCRIPTION
**Pull request by bashdroid**
Support Zstandard compressed tar files in the tar plugin

### CODE REVIEW

**Comment by janlazo** [comment]
Please upstream this first. Vim has newer runtime files for the tar plugin.

**Comment by bashdroid** [comment]
I reported this at https://github.com/vim/vim/pull/7343.
Still waiting for a response.

**Comment by bashdroid** [comment]
This has been included in https://github.com/vim/vim/commit/23515b4ef7580af8b9d3b964a558ab2007cacda5

**Comment by janlazo** [comment]
Redo this PR like the other merged runtime PRs.

https://github.com/neovim/neovim/pulls?q=is%3Apr+label%3Aruntime+is%3Aclosed

**Comment by bashdroid** [comment]
Not sure if this is as desired. Please let me know if something is missing.

**Comment by janlazo** [comment]
Your commit combined multiple runtime patches when they should be split up like what I did in https://github.com/neovim/neovim/pull/13968 and https://github.com/neovim/neovim/pull/13523.

**Pull request closed without merging**
