### PR TITLE
[RDY] Update libuv to 1.5.0

### PR DESCRIPTION
**Pull request by ghost**
Among other things, there's various Windows related fixes: https://github.com/libuv/libuv/pull/329

### CODE REVIEW

**Comment by Pyrohh** [comment]
Given what happened in #1799, anyone with a Mac should test this.

**Comment by justinmk** [comment]
Hmm. QB says no failed tests, but the build failed in some other way.

Since you built the deps, all other PRs will use the result now, I think? Next time, we should probably wait until we are ready to merge it.

**Comment by Pyrohh** [comment]
> Since you built the deps, all other PRs will use the result now, I think?

Seriously? I've seen this done in other PRs. Eh... I'm not sure.

**Comment by justinmk** [comment]
Sorry, I was wrong. It only builds them for this PR. It calls  https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh but does not call `commit_deps64`.

**Comment by justinmk** [comment]
Saw no problems after moderate usage on OS X 10.10.3. All functional tests passed.

LGTM

**Comment by Pyrohh** [comment]
Thanks for testing. Perhaps one more person should try this out and I'll merge it.

**Comment by fwalch** [comment]
Before merging, don't forget to remove the second commit :-)

**Comment by Pyrohh** [comment]
> Before merging, don't forget to remove the second commit :-)

Heh, got it :)

By the way, If you wanna test this then I bet it can be merged after.

**Comment by fwalch** [comment]
I updated my systemwide LibUV to 1.5 yesterday, didn't encounter any problems so far. Since the tests seem to work (apart from the usual problems *sigh* restarted the GCC-32 build because it stopped after only one minute), I think it should be fine. Maybe wait for the 32-bit build, since that's a bit of a special case.

**Comment by Pyrohh** [comment]
Damn, it failed. I'm incredibly surprised :grin:

**Comment by fwalch** [comment]
> Damn, it failed. I'm incredibly surprised :grin:

Are you sure? I can see a passing gcc-32 build, only the gcc build timed out after 50 minutes.

**Comment by Pyrohh** [comment]
> Are you sure? I can see a passing gcc-32 build, only the gcc build timed out after 50 minutes.

Ah yes, you're right. I'll merge it then.

**Comment by fwalch** [comment]
Sorry for the last minute request, but can you add some commit message explaining why we update (e.g. fixed issues?)

**Comment by Pyrohh** [comment]
:+1: Added https://github.com/libuv/libuv/pull/329

**Comment by fwalch** [comment]
And add a commit message prefix (e.g. `deps: Update to libuv 1.5.0`)?

**Comment by Pyrohh** [comment]
Merged, thanks for the help @fwalch and @justinmk.

**Comment by fwalch** [comment]
There might be a problem (from https://github.com/neovim/homebrew-neovim/pull/58):

```
Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file /tmp/neovim20150508-1014-157w97p/.deps/build/src/libuv/src/unix/stream.c, line 1528.
```

**Comment by Pyrohh** [comment]
Crap, I didn't see that when I tested locally. Do you have a Mac you can reproduce this on?

**Comment by fwalch** [comment]
Nope, just Travis...

**Pull request closed without merging**
