### PR TITLE
Properly handle undo'ing adding spellcheck words

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Closes neovim/neovim#20609 (GitHub).

### CODE REVIEW

**Comment by zeertzjq** [comment]
This does not look like a bug to me. If you really think this is a bug then please send this to Vim and see what Bram thinks about this.

**Comment by ctrlcctrlv** [comment]
How is it not a bug to write the wrong word into the file?

**Comment by ctrlcctrlv** [comment]
Just because the tests say `gooodd` should become `#ooodd` doesn't mean that ought to happen, obviously the right answer is `#gooodd`. This patch may not be perfect depending on whether an undo can replace a line only at the bottom of the file or not.

**Comment by ctrlcctrlv** [comment]
(E.g. in languages like Korean where the words are short it may not be possible to determine what the original word was if you delete a whole character.)

**Comment by zeertzjq** [comment]
It's just a comment and will not be commented out, so why does it matter?

**Comment by ctrlcctrlv** [comment]
Why try to leave a record of what happened if the record is assumed to be wrong? Why not just erase the line in that case?

**Comment by ctrlcctrlv** [comment]
Anyway I make heavy use of vim's spellcheck system so wanted to write a script to re-add deleted good words as rare words but since the record is unreliable I can't do that.

**Comment by clason** [comment]
The key takeaway here is that this code is "owned by" (taken directly from) Vim, so changes should go through there, for various reasons that I can explain on demand.

But note that we are investigating whether to remove the whole spelling subsystem from Neovim and replace it with `hunspell`, see https://github.com/neovim/neovim/pull/20131

**Comment by zeertzjq** [comment]
Anyway, this PR only works if the commented out word is at the end of the file. If this is in the middle of the file this PR will cause the beginning of the next word to be overwritten.

**Comment by ctrlcctrlv** [comment]
I see, thank you @clason. I will ask Bram as was suggested. Sorry, I thought this project was a re-implementation when I started working on the issue.

@zeertzjq I see, I think the fix for that is seeking because I don't think `r+` seeks. I had a few prototype versions that tried to seek but they didn't work either. I thought that this could never catch a word mid-file but you're right it can (and there is a test for it, I should've looked at test output more carefully but just saw a lot of ones I knew to be wrong so assumed faulty tests).

I'll send a better patch upstream to vim.

**Pull request closed without merging**
