### PR TITLE
refactor(cmd): unify execute_cmd more

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Review by zeertzjq — COMMENTED** [review]
The first commit LGTM. The second commit can change behavior. For example, `:1,2help` in cmdwin previously throws `E11`, but after this PR it throws `E481`.

**Comment by lewis6991** [comment]
Rebased and removed the second commit.

**Review by zeertzjq — CHANGES_REQUESTED** [review]
This parses count twice for a command. For example, with this PR `:bwipe 1 2 3` only wipes buffers 2, 3 instead of buffers 1, 2, 3.

**Comment by lewis6991** [comment]
Sorry bad rebase, that example seems to work now.

**Review by zeertzjq — APPROVED** [review]

**Pull request closed without merging**
