### PR TITLE
vim-patch:8.2.4241: some type casts are redundant

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
Is that a (partial) port of your Vim PR?

**Comment by dundargoc** [comment]
> Is that a (partial) port of your Vim PR?

Lol, you noticed. That was my plan initially, but I couldn't realized I couldn't make any equivalent changes so I figured I might as well just make a regular PR for neovim instead of an empty vim-patch.

**Comment by dundargoc** [comment]
So short answer: no.

**Comment by clason** [comment]
The point is that it'll still be good to mark the Vim patch as N/A, and the way that is done is using the "magic words" for it in _different_ PR. So if this is "spiritually" equivalent, it would still be useful to pretend it's a port of that patch (by mimicking the commit message for it, plus a comment that it's not a literal port).

**Review by seandewar — COMMENTED** [review]
:+1: Looks good, I'd also check these:

- Nvim's `sign_getinfo` also has a few pointless casts for `p` (but to `char *` instead)
- `set_num_option`'s `errbuf` casts.
- Remove the brackets around the first arg like Vim: https://github.com/neovim/neovim/blob/815aa9f6425b34f1857a5b4213dff0dce6dda2b9/src/nvim/ex_cmds.c#L1369
- Ditto but for the 3rd arg: https://github.com/neovim/neovim/blob/ed0808412cc5e8b53e4d1d1ad466c4f710a03e66/src/nvim/ops.c#L385

There's also some changes made to a few unported functions like `range_list_materialize`, but I don't think it's too important to match this patch exactly?

**Review by seandewar — APPROVED** [review]
LGTM. There's a few changes to unported things that may be relevant in the future like `range_list_materialize`, `emsg_namelen`, `get_option_fullname`; they're very minor, though. 🤔

**Pull request merged**
