### PR TITLE
build(deps): bump tree-sitter to v0.21.0

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Comment by clason** [comment]
Max flubbed the release _again_... Let's wait a bit and see whether he starts taking the sledge hammer to things before merging.

**Comment by justinmk** [comment]
is there something we can say in the commit message about changes that are relevant to us?

**Comment by clason** [comment]
Hard to say, since changelogs are another thing Max is not interested in. I'll manually trawl the git log and see if something sticks out.

**Comment by clason** [comment]
Nothing, really, for the lib. Relevant changes are in relation to WASM parsers, which we haven't really looked into yet (but which this release makes possible).

**Pull request merged**
