### PR TITLE
Replace gperf with bsearch in find_internal_func

### PR DESCRIPTION
**Pull request by vainiovano**
Replace gperf with bsearch as suggested in the conversation of #10118

### CODE REVIEW

**Comment by bfredl** [comment]
Is `bsearch` faster than (imperfect) hashing though? because otherwise we should just use the existing `PMap(cstr_t)` khash-based lookup.

**Comment by vainiovano** [comment]
A hash map would need memory and time to be initialized. I haven't measured the speed difference of `PMap` and `bsearch`, though.

**Comment by bfredl** [comment]
> A hash map would need memory and time to be initialized

But this is a one-time cost per instance. And our `Map` implementation does not require copying the strings, just setting up the actual hash table.

**Comment by justinmk** [comment]
@vainiovano nicely done!  The travis failure should be fixed by rebasing (after https://github.com/neovim/neovim/commit/06a020af09976e1a9db4da3ece547db32f4153e1 ).

The bsearch implementation is worth having as a reference (i.e., don't remove that commit). But it makes sense to use `PMap`  as mentioned: these lookups are very frequent, which is why ghash was used in the first place.

**Comment by vainiovano** [comment]
Okay. I'll rebase and keep the commit.

**Comment by justinmk** [comment]
great. So just to be clear, do you plan to make the `PMap` change?

**Comment by vainiovano** [comment]
I don't have much time and I don't know how to use PMap. It would be better if someone else did it.

**Comment by norcalli** [comment]
@justinmk @bfredl I could take over to do the PMap change. From looking at the code, it appears that I should use `PMap(String)`, right? Also, since it's not a PHF implementation, should I set the capacity larger than the size of the keys to avoid too much probing?

Or we could drop in a baby phf implementation: https://github.com/wahern/phf. This one coincidentally has a Lua api that could be nice to consider for the Lua stdlib anyway, or we could keep it to the generator. I'm also looking for a pure Lua implementation, but if I can't find one, I can try to implement the CHD in pure Lua. Then again, why reinvent the wheel.

**Comment by bfredl** [comment]
@norcalli Another option that I think ZyX-I considered, was to statically initiate a khash/PMap at compile time using a lua generator. Then we could "fake" perfect hashing by just trying various over-allocations in a resonable range and pick the one with fewest collisions (only "hit" perf is really relevant, "miss" cases are errors/slow path anyway).

**Comment by justinmk** [comment]
I suggest starting with the bare-minimum PMap impl, then feel free to revisit/followup with the optimizations later. Removing the gperf dependency is the big win here.

**Comment by bfredl** [comment]
We implemented our own imperfect compiletime hash function: Hashy mcHashFace. so this is not redundant.

**Pull request closed without merging**
