### PR TITLE
Update runtime/syntax/css.vim [vim/vim@22f1d0e]

### PR DESCRIPTION
**Pull request by zoliky**

### CODE REVIEW

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/9116

Also for future reference we would never merge only 1 file from a runtime update.

**Comment by zoliky** [comment]
Thanks for getting back to me so quickly. I would gladly update all the runtime files, but the documentation thing is not my cup of tea :+1

**Comment by zoliky** [comment]
Thanks for getting back to me so quickly. I would gladly update all the runtime files, but the documentation thing is not my cup of tea.

**Comment by zoliky** [comment]
Thanks for getting back to me so quickly. I would gladly update all the runtime files.

**Comment by justinmk** [comment]
Thanks, but there is an existing PR already (see above).

**Pull request closed without merging**
