### PR TITLE
Disable Nagle's algorithm on TCP sockets

### PR DESCRIPTION
**Pull request by davidgaleano**
I am assuming that for neovim reducing latency is more interesting than optimizing bandwidth
but I do not have any empirical evidence that it would improve anything,
it is a purely speculative suggestion.

### CODE REVIEW

**Comment by teto** [comment]
Makes sense a priori.

**Review by nuntapeecha — APPROVED** [review]

**Comment by justinmk** [comment]
Good idea, thanks. Would you mind use `true` instead of `1`?

**Comment by davidgaleano** [comment]
I don't mind but as the function is declared to accept an int and the file had a C extension I was hesitant to rely on the type conversion, is this standard practice for this project?

**Comment by justinmk** [comment]
It's standard for this project where a boolean is intended and the conversion is widening.

**Pull request merged**
