### PR TITLE
option: Fix typos that may lead to SEGV in some cases

### PR DESCRIPTION
**Pull request by ZyX-I**
Reported by @equalsraf.

### CODE REVIEW

**Comment by ZyX-I** [comment]
@justinmk I got clint failure due to #3306: apparently bot that updates “allowed” list of clint errors did not yet run.

**Comment by tarruda** [comment]
I will fix the clint failure in #3413 which I will merge in less than 30 minutes

**Comment by justinmk** [comment]
@ZyX-I I will fix clint errors later today. Sorry about that.

**Comment by tarruda** [comment]
@justinmk I already fixed the issues in #3413, just waiting the tests to finish before  merging

**Comment by justinmk** [comment]
OSX failure was a gcov quirk.

**Pull request merged**
