### PR TITLE
[RFC] third-party: fix whitespace and naming

### PR DESCRIPTION
**Pull request by jszakmeister**

### CODE REVIEW

**Comment by Pyrohh** [comment]
I like the consistency this brings LGTM.

**Comment by fwalch** [comment]
Since this PR is purely stylistic, a small inconsistency I noticed that could be fixed here as well: remove the "lib" prefix from mentions of "libunibilium", since the project is called just "unibilium".

**Comment by jszakmeister** [comment]
> Since this PR is purely stylistic, a small inconsistency I noticed that could be fixed here as well: remove the "lib" prefix from mentions of "libunibilium", since the project is called just "unibilium".

Sure.  See what you think of the update.

**Comment by fwalch** [comment]
LGTM :+1:

**Comment by jszakmeister** [comment]
Thanks for the review @fwalch and @Pyrohh!

**Comment by jszakmeister** [comment]
Apparently I missed a reference but didn't catch it on my home machine. :-(  I've pushed a fix to master though (to keep everything from breaking).

**Pull request merged**
