### PR TITLE
Missing argument for package.loadlib()

### PR DESCRIPTION
**Pull request by matveyt**
To load Lua binary module (.so / .dll) we must provide init function name as the second argument of `package.loadlib()`, see [the manual](http://www.lua.org/manual/5.1/manual.html#pdf-package.loadlib). Otherwise it will fail.

### CODE REVIEW

**Comment by jamessan** [comment]
Looks like a duplicate of #13441

**Comment by matveyt** [comment]
Uh, I see.
I've fixed an issue with `foo.bar.baz` module name. The code looks more compact to me than in #13441. But if it could be merged into #13441 instead, it's also okay.

**Comment by jamessan** [comment]
> The code looks more compact to me than in #13441. But if it could be merged into #13441 instead, it's also okay.

I'm not as familiar with the Lua side of things, so I'll defer to @bfredl / @tjdevries judgement on which is appropriate.

**Comment by matveyt** [comment]
Had to fix yet another issue to be compatible with Lua 5.1. Hope it became correct now.

**Comment by bfredl** [comment]
I think this handles all cases except nested submodules in the same file, I will work on that later..

**Pull request merged**
