### PR TITLE
perf: tv_clear(): Cache gettext() result.

### PR DESCRIPTION
**Pull request by justinmk**
cc @ZyX-I

### CODE REVIEW

**Comment by justinmk** [comment]
This appears to fix the windows performance issue as well. Which raises a general question: how much more performance could we get by optimizing (avoiding) calls to `gettext`?

**Comment by justinmk** [comment]
@raghur does this fix the perf issue for you on windows?

**Comment by raghur** [comment]
@justinmk - Yes - this looks good.

**Comment by AlexMasterov** [comment]
@justinmk Yes. Thank you for taking care!

But some plugins that use the IO still work slower than with Vim. This is another issue 😄

**Comment by justinmk** [comment]
@AlexMasterov Do you mean `:read` and `:write` or what IO specifically? I just tested system() perf on gvim vs nvim:

    Time for i in range(1,100)|let a=system('dir')|endfor

Nvim is 7x (yes, 700%) faster with system() on Windows (we don't launch a console window, probably some other differences as well).

**Comment by tjdevries** [comment]
Tested the build on windows before and after this and I can say it is markedly faster as well. Thanks Justin. Not sure if I see any IO problems. I still see some slowness in opening up new buffers though. I can investigate more later potentially if necessary.

**Comment by AlexMasterov** [comment]
@justinmk 

These plugins use `readfile()` and `writefile()` (without `S` flag for async).
With `set nofsync` option it again works quickly.

@tjdevries
> I still see some slowness in opening up new buffers though.

Yeah. Try with 'fsync' option disabled.

**Pull request merged**
