### PR TITLE
[RFC] mark patches as NA

### PR DESCRIPTION
**Pull request by wdv4758h**
- [.777](https://github.com/vim/vim/commit/694cac7a352ea66827cd94ed1ccbc2fc5655e9cc) (README)
- [.778](https://github.com/vim/vim/commit/ae2fe73abc954b8fd3dbd7994daa8e31e6690bd0) (Coverity warns)
- [.780](https://github.com/vim/vim/commit/1db43b1145fe466b5d41af6744a08083983de3a9) (Compiler complains)
- [.783](https://github.com/vim/vim/commit/2536d4f396680f079e2cb96f9787a434846b5ce7) (copy_chars, copy_spaces, vim_memset)
- [.788](https://github.com/vim/vim/commit/5cbb8dbc329ab33ce56ea7ce4695778630c4e9ee) (fix build, #ifdef)
- [.794](https://github.com/vim/vim/commit/d4a95c3bc5a70f43db0abd020a15d8a1a65db961) (Make_mvc.mak)
- [.796](https://github.com/vim/vim/commit/33c3a694fca7978cdd28c5e41b498473a08bc05e) (Compiler warns)

### CODE REVIEW

**Comment by Pyrohh** [comment]
Thanks @wdv4758h, I've added more information to the commit message and merged this.

**Comment by justinmk** [comment]
https://github.com/vim/vim/commit/ae2fe73abc954b8fd3dbd7994daa8e31e6690bd0 might be worth including, could knock out a coverity issue. Currently our coverity build is broken for some reason though.

**Comment by oni-link** [comment]
@justinmk, do we perhaps use an old version of the coverity build tool? I tried to upload a new build today and some new things were found, but the shown number of analyzed lines is still small.

**Comment by justinmk** [comment]
@oni-link If I understand correctly we eval the script from coverity every time:

https://github.com/neovim/bot-ci/blob/master/ci/coverity.sh#L26

I was planning to look at it tomorrow.

**Pull request closed without merging**
