### PR TITLE
[RFC] vim-patch: 8.0.0489, 8.0.0491, 8.0.0495, 8.0.0500

### PR DESCRIPTION
**Pull request by lonerover**
#### vim-patch:8.0.0489: clipboard and "* register is not tested

Problem:    Clipboard and "* register is not tested.
Solution:   Add a test for Mac and X11. (Kazunobu Kuriyama)
https://github.com/vim/vim/commit/7dd4850698e37c3ed4a3c3b23f4cdbf1ae6542f8

#### vim-patch:8.0.0491: quotestar test fails when features are missing

Problem:    The quotestar test fails when a required feature is missing.
Solution:   Prepend "Skipped" to the thrown exception.
https://github.com/vim/vim/commit/bfd830d3e2dbd1e9b14c65625f18773074e6ac67

#### vim-patch:8.0.0495: quotestar test uses timer instead of timeout

Problem:    The quotestar test uses a timer instead of a timeout, thus it
            cannot be rerun like a flaky test.
Solution:   Remove the timer and add a timeout. (Kazunobu Kuriyama)
https://github.com/vim/vim/commit/f5610da7a8a5908e747d1ae39dbed1408bbd2644

#### vim-patch:8.0.0500: quotestar test is still a bit flaky

Problem:    Quotestar test is still a bit flaky.
Solution:   Add a slower check for v:version.
https://github.com/vim/vim/commit/4889ad7c6cd46368f553cc1140ca17508e8beaaa

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! Reminder that new oldtests need to be added to `NEW_TESTS` in src/nvim/testdir/Makefile.

Also note that version.c doesn't need to be manually updated, we have a CI job that automates it (and `vim-patch.sh -l` checks git logs instead of version.c).

TBH, I'm not sure we actually need these tests because they will be skipped in all cases, and we already test the clipboard in `tests/functional`. But it's harmless for now.

**Comment by janlazo** [comment]
@justinmk @lonerover 

Intentional Travis failure?

```
make: *** No rule to make target `Test_quotestar.res', needed by `newtestssilent'.  Stop.
make: Leaving directory `/home/travis/build/neovim/neovim/src/nvim/testdir'
++reset

[3g        H        H        H        H        H        H        H        H        H
c[!p[?3;4l[4l>
++fail oldtests F 'Legacy tests failed'
++local test_name=oldtests
++local fail_char=F
++local 'message=Legacy tests failed'
++: F
++: Legacy tests failed
++local 'full_msg=F /tests/oldtests|oldtests :: Legacy tests failed'
++FAIL_SUMMARY='
F /tests/oldtests|oldtests :: Legacy tests failed'
++echo 'F /tests/oldtests|oldtests :: Legacy tests failed'
++echo 'Failed: F /tests/oldtests|oldtests :: Legacy tests failed'
Failed: F /tests/oldtests|oldtests :: Legacy tests failed
++FAILED=1
```

**Comment by justinmk** [comment]
Weird, I tested it locally.

**Comment by justinmk** [comment]
@janlazo fixed https://github.com/neovim/neovim/commit/1642917f9ba873be7be2dae346efb29f64e268a0

**Pull request merged**
