### PR TITLE
vim-patch:9.0.{0190,0191,0192}: cmdheight=0 fixes

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by zeertzjq** [comment]
I'm not saying #17335 will be reverted. I'm just testing that.

**Comment by zeertzjq** [comment]
In Nvim, `w_lines` always has `grid->rows + 1` lines:
```c
  if (grid->rows != rows) {
    wp->w_lines_valid = 0;
    xfree(wp->w_lines);
    wp->w_lines = xcalloc((size_t)rows + 1, sizeof(wline_T));
  }
```

So the invalid memory access mentioned in the patch will not happen.

**Comment by Shougo** [comment]
> I'm not saying https://github.com/neovim/neovim/pull/17335 will be reverted. I'm just testing that.

OK.

> So the invalid memory access mentioned in patch 9.0.0192 will not happen.

OK.

**Comment by Shougo** [comment]
Thank you for the merge.

**Comment by Shougo** [comment]
The patches breaks command line completion.  I will fix it later.

d74f9c3b947677a98103c41e0c4ad8ae54389c4e seems works.

**Comment by Shougo** [comment]
I will fix it in https://github.com/neovim/neovim/pull/19816.

**Pull request merged**
