### PR TITLE
refactor(shada): rework msgpack decoding without msgpack-c

### PR DESCRIPTION
**Pull request by bfredl**
and thus get rid of msgpack-c dependency

### CODE REVIEW

**Comment by clason** [comment]
Don't forget to remove the entry in `deps.txt` as well.

**Comment by clason** [comment]
the macos-14 failure was a flake (but not restricted to CI; I just got hit by it locally):
```
In file included from ././src/nvim/buffer.h:9:
/Users/clason/build/neovim/src/nvim/gettext_defs.h:4:11: fatal error: 'libintl.h' file not found
    4 | # include <libintl.h>  // IWYU pragma: export
      |           ^~~~~~~~~~~
```

**Comment by clason** [comment]
There are mentions of the msgpack dependency in `BUILD.md` and `contrib/local.mk.example` as well.

**Review by dundargoc — APPROVED** [review]

**Comment by dundargoc** [comment]
I think `libmsgpack-dev` should be removed from `.github/workflows/build.yml`. Please confirm.

**Comment by clason** [comment]
@bfredl needs a rebase -- anything left to do here? (eager to see msgpack gone)

**Comment by bfredl** [comment]
Not really, I'm just still in vacation mode lol

**Pull request merged**
