### PR TITLE
[RFC] win,fs.c: Fix is_executable_ext

### PR DESCRIPTION
**Pull request by erw7**
Fix issue that increment expression is executable and pointer ext
pointing out of the buffer, if the pointer ext points to the terminating
NUL.

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks for looking into this.
Why is Neovim using a different method than Vim here in the first place (https://github.com/vim/vim/blob/8d241040310a6a27c28d62fa04558f2bfaa5ebde/src/os_win32.c#L3256-L3328 etc)?

Also a test for this would be nice to have of course - preferably somehow also executable/emulated on non-Windows then.

**Comment by erw7** [comment]
> Why is Neovim using a different method than Vim here in the first place 

Perhaps this is because the feature to find for executable files using `$PATHEXT` was implemented before vim(Ref. https://github.com/neovim/neovim/commit/da4bf813daf1d54c3cdfbeb480b7ce15a7372834).

**Comment by blueyed** [comment]
Should/could we use Vim's method then?  (to have a smaller diff in general, and sharing fixes)

**Comment by blueyed** [comment]
Test failure appears to be due to flakiness (https://github.com/neovim/neovim/issues/10241)?
Will trigger a rebuild.

**Comment by blueyed** [comment]
Just seen another possibly related relevant flaky test:
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] C:/projects/neovim/test/functional\eval\executable_spec.lua @ 18: executable() sibling to nvim binary
C:/projects/neovim/test/functional\eval\executable_spec.lua:26: Expected objects to be the same.
Passed in:
(nil)
Expected:
(string) 'arg1=lemon;arg2=sky;arg3=tree;'
stack traceback:
	C:/projects/neovim/test/functional\eval\executable_spec.lua:26: in function <C:/projects/neovim/test/functional\eval\executable_spec.lua:18>
```
(https://ci.appveyor.com/project/neovim/neovim/builds/25330509/job/q8qjuyvn38i8igsy)

It would be nice to get this fixed/merged.
Do you think we can have an explicit test for this?

**Comment by blueyed** [comment]
Testing this in https://github.com/neovim/neovim/pull/10248 now.

**Comment by blueyed** [comment]
This test should probably get enabled: https://github.com/blueyed/neovim/blob/1d06da257886d4d4ec8075bde51a51d4af5caf68/test/functional/eval/executable_spec.lua#L30-L32

**Pull request merged**
