### PR TITLE
[RDY] lsp: support custom hl groups in show_line_diagnostics

### LINKED ISSUE #12472: LSP: support custom highlights in the floating window for show_line_diagnostics?
Hi there!

While working on some config for the lsp client, I realized that using the same highlight group for the virtualtext and the floating window when invoking show_line_diagnostics. In my case specifically, Pmenu is darker than the virtual text, so I'd like to use different highlight groups x)

We could introduce something like `LspDiagnostics<severity>Floating`, and similar to the Sign groups, we would link them with the regular one, providing backwards compatibility and the ability to customize it.

This is a small change, but I figured I could open an issue before sending a PR, in case someone wants to discuss the idea or implement something more sophisticated.

Any thoughts?

### PR DESCRIPTION
**Pull request by fsouza**
Closes #12472.

### CODE REVIEW

**Comment by tjdevries** [comment]
Can you add documentation for this as well? And also just to confirm, this is so you can change the highlights separately, correct?

**Comment by fsouza** [comment]
@tjdevries yes to both. Will add some docs tomorrow or Tuesday!

Thanks for the feedback!

**Comment by fsouza** [comment]
The CI failure seems to be unrelated 🤔 Should I rebase and push again to retry?

@tjdevries friendly ping 😁

**Comment by tjdevries** [comment]
Thanks for the PR. Ran tests locally & ran them again online. The BSD ones are flaky.

**Pull request merged**
