### PR TITLE
fix(winbar): properly redraw winbar when showcmdloc=statusline

### LINKED ISSUE #23030: WinBar highlights not updated properly when 'showcmdloc' is "statusline"
### Problem

Setting `:set showcmdloc=statusline` seems to prevent the WinBar and WinBarNC highlights from applying correctly when switching between windows.

### Steps to reproduce

1. make a tmp lua init with this:

```lua
vim.o.winbar = 'just some text to show'
vim.o.showcmdloc = 'statusline'
vim.cmd[[hi! WinBar ctermfg=black ctermbg=white]]
vim.cmd[[hi! WinBarNC ctermfg=white ctermbg=black]]
```
2. `nvim --clean -u tmp-init.lua`
3. Open several window splits and move between them

If you then do `:set showcmdloc=` the highlighting works again as intended

### Expected behavior

When cursor enters another window, the highlights for WinBar|NC update to the correct highlights

### Neovim version (nvim -v)

0.10.0 commit gf4136c9d4

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.6.3

### Terminal name/version

Wezterm nightly

### $TERM environment variable

wezterm

### Installation

build from repo

### PR DESCRIPTION
**Pull request by ffflick-gh**
Fixes #23030. I just applied the changes suggested by @luukvbaal . I hope that's OK.

### CODE REVIEW

**Comment by luukvbaal** [comment]
I intended to open a PR myself but failed to write a testcase from the issue that fails on master. If you can manage to do that great, otherwise I will probably look into it again...

**Comment by zeertzjq** [comment]
I previously tried to write a testcase but it didn't failure on master as well.
```diff
diff --git a/test/functional/ui/winbar_spec.lua b/test/functional/ui/winbar_spec.lua
index ece27ec3f..e3fef473d 100644
--- a/test/functional/ui/winbar_spec.lua
+++ b/test/functional/ui/winbar_spec.lua
@@ -114,6 +114,56 @@ describe('winbar', function()
       {2:[No Name]                     [No Name]                     }|
                                                                   |
     ]])
+    feed('<C-W>w')
+    screen:expect([[
+      {6:Set Up The Bars              }│{6:Set Up The Bars               }|
+                                   │                              |
+      {3:~                            }│{3:~                             }|
+      {3:~                            }│{2:[No Name]                     }|
+      {3:~                            }│{5:Set Up The Bars               }|
+      {3:~                            }│^                              |
+      {3:~                            }│{3:~                             }|
+      {3:~                            }│{4:[No Name]                     }|
+      {3:~                            }│{6:Set Up The Bars               }|
+      {3:~                            }│                              |
+      {3:~                            }│{3:~                             }|
+      {2:[No Name]                     [No Name]                     }|
+                                                                  |
+    ]])
+    -- 'showcmdloc' "statusline" should not interfere with winbar redrawing #23030
+    command('set showcmd showcmdloc=statusline')
+    feed('<C-W>')
+    screen:expect([[
+      {6:Set Up The Bars              }│{6:Set Up The Bars               }|
+                                   │                              |
+      {3:~                            }│{3:~                             }|
+      {3:~                            }│{2:[No Name]                     }|
+      {3:~                            }│{5:Set Up The Bars               }|
+      {3:~                            }│^                              |
+      {3:~                            }│{3:~                             }|
+      {3:~                            }│{4:[No Name]          ^W         }|
+      {3:~                            }│{6:Set Up The Bars               }|
+      {3:~                            }│                              |
+      {3:~                            }│{3:~                             }|
+      {2:[No Name]                     [No Name]                     }|
+                                                                  |
+    ]])
+    feed('w')
+    screen:expect([[
+      {6:Set Up The Bars              }│{6:Set Up The Bars               }|
+                                   │                              |
+      {3:~                            }│{3:~                             }|
+      {3:~                            }│{2:[No Name]                     }|
+      {3:~                            }│{6:Set Up The Bars               }|
+      {3:~                            }│                              |
+      {3:~                            }│{3:~                             }|
+      {3:~                            }│{2:[No Name]                     }|
+      {3:~                            }│{5:Set Up The Bars               }|
+      {3:~                            }│^                              |
+      {3:~                            }│{3:~                             }|
+      {2:[No Name]                     }{4:[No Name]                     }|
+                                                                  |
+    ]])
   end)
 
   it('works when switching value of \'winbar\'', function()
```

**Comment by mhmoooods** [comment]
> I previously tried to write a testcase but it didn't fail on master either.

I tried it out, for some reason the winbar updates properly on the first window switch after `set showcmdloc=statusline`, but fails to update properly on subsequent switches. I updated your test case to check for another `<C-W>W`, and it fails on master but works with the fix.

**Comment by luukvbaal** [comment]
This might be a better fix, I think it results in one less statusline redraw:
```diff
+++ b/src/nvim/normal.c
@@ -1997,8 +1997,12 @@ static void display_showcmd(void)
   showcmd_is_clear = (len == 0);

   if (*p_sloc == 's') {
-    win_redr_status(curwin);
-    setcursor();  // put cursor back where it belongs
+    if (showcmd_is_clear) {
+      curwin->w_redr_status = true;
+    } else {
+      win_redr_status(curwin);
+      setcursor();  // put cursor back where it belongs
+    }
     return;
   }
   if (*p_sloc == 't') {
```

**Pull request closed without merging**
