### PR TITLE
fix(lsp): support duplicate params in signature help

### LINKED ISSUE #15022: Active Signature Highlight fails when the server is using labels rather than offsets, and there are multiple equal labels
The active signature parameter highlight (74527a30edf4c71c6376343d5cd23fe0584def01) fails when the server is not using offsets, and there are multiple parameter labels with the same value

Screenshot 2021-07-08 at 09 13 49

### PR DESCRIPTION
**Pull request by folke**
for more info, see the linked issue.

Fixes #15022

### CODE REVIEW

**Comment by urandom** [comment]
Screenshot from 2021-07-09 09-41-23

Looks like it's working

**Review by mjlbach — APPROVED** [review]
LGTM

**Review by urandom — APPROVED** [review]

**Comment by folke** [comment]
This will still fail, but sure if this can even be fixed?

image

**Comment by urandom** [comment]
I think this is too much of an edge case to be worth fixing. Though perhaps you could search backwards to avoid the function name itself. Probably not worth the effort

**Comment by folke** [comment]
@urandom that's clever indeed, but probably not worth the effort indeed.

I do need to set the `plain` option in the find though. Forgot about that. (otherwise we could get errors for special characters part of the label)

**Comment by folke** [comment]
Just pushed two fixes:
* use `plain` for find
* initialize the `offset` to the first `(` or `1` if not found

The second part fixes that edge case I think. Or at least when using function like labels.

**Comment by urandom** [comment]
LGTM, still works with the latest changes

**Comment by mjlbach** [comment]
Hmm should we really hardcode in `(`? would probably be better to use the trigger chars

**Comment by folke** [comment]
> Hmm should we really hardcode in `(`? would probably be better to use the trigger chars

good point. will add this.

I would also remove that message when no signature help is available. We removed that for hover too. wdyt?

**Comment by mjlbach** [comment]
Mixed on removing the feedback I think on one hand it's good so that people know the server is active/the keys are mapped, but I also want to move closer to supporting all of the handlers in response to autocommands. We could do also`config.silent` like urandom had which defaults to false.  Your call.

**Comment by folke** [comment]
I'll add in the `silent` option.

As for the trigger characters:
image

If we use that, then we need to be 100% sure that server will always return at least the trigger character associated with the function start. If in this case it would only have the `,` things could fail.

Maybe I should look into the reverse find instead. Just not as straightforward with Lua. Will look into it

**Comment by mjlbach** [comment]
Hmm if it doesn't, is that not a server bug? Not sure it's our problem :)

**Comment by folke** [comment]
Added the triggerCharacters and a `silent` option

**Comment by urandom** [comment]
Stumbled upon a weird behavior
Screenshot 2021-07-09 at 10 59 50

Once you are past the last parameter, the first one is marked as active. I guess the best possible scenario here is that none are marked as active, however, with varargs this might not work as expected. It's probably better if the last parameter remains active.

**Comment by folke** [comment]
@urandom the behaviour you see is according to the spec.

The spec says that any activeParameter that falls outside of the range of `#signature.parameters` should be interpreted as the first parameter.

It's definitely not ideal, but that's what the specs says we should do.

**Comment by folke** [comment]
Oh wait, this might be something else. Will see what the server returns

**Comment by folke** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_signatureHelp

The relevant part is that about the `activeParameter`.

But I think for showing parameter docs we already `clamped` the active parameter to the `signature.parameters` range, instead of setting it to `0`

Changed it back to work like this.

This is technically not according to the spec, so I'm not 100% sure about this change.

@mjlbach what do you think?

**Comment by mjlbach** [comment]
```
	 * The active signature. If omitted or the value lies outside the
	 * range of `signatures` the value defaults to zero or is ignore if
	 * the `SignatureHelp` as no signatures.
	 *
	 ** Whenever possible implementors should make an active decision about
	   the active signature and shouldn't rely on a default value.**
	 *
	 * In future version of the protocol this property might become
	 * mandatory to better express this.
```

Emphasis mine,  I think we should clamp to the last signature if it doesn't substantially increase code complexity, but should leave a note that this is not "client-side interpretation" of out of range active signatures.

**Comment by folke** [comment]
done

**Pull request merged**
