### PR TITLE
vim-patch:8.2.{1401,1413,4428,4432,4434,4438,4442,4444,4445,4454}: tabpage patches

### PR DESCRIPTION
**Pull request by seandewar**

### CODE REVIEW

**Review by zeertzjq — DISMISSED** [review]

**Comment by zeertzjq** [comment]
Wait, <https://github.com/vim/vim/issues/9813>

**Comment by seandewar** [comment]
Yeah, also saw that the ASAN functiontest froze at a suspicious place. :eyes:

**Comment by seandewar** [comment]
Still timing out the ASAN for some reason :thinking:

**Comment by zeertzjq** [comment]
I found out a case to triggers this in Vim, although Vim segfaults instead: <https://github.com/vim/vim/issues/9817>.

**Comment by zeertzjq** [comment]
<https://github.com/vim/vim/commit/ca0c1caa36823ea8e61184268d7337e79995352f>

So setting `cmdwin_type = 0` is indeed the correct workaround.

**Comment by seandewar** [comment]
Sounds good to me. Thanks for your help!
I'll finish this PR off later once I have some time. :+1:

**Review by zeertzjq — APPROVED** [review]

**Pull request merged**
