### PR TITLE
[RFC] Windows: Ignore EW_ICASE in do_path_expand

### PR DESCRIPTION
**Pull request by sethjackson**
Cherry picked from #810. From equalsraf@01a1290.

### CODE REVIEW

**Comment by equalsraf** [comment]
clint complains over whitespace issues, which is why travis is failing.

Some more context - There is already a similar check in line [585](https://github.com/neovim/neovim/blob/641c6420e146aee1d2c3e75439c3efc5777a6845/src/nvim/path.c#L585).
Seems the `do_path_expand()` function comes from the old `unix_expandpath()` - in Vim there was also `dos_expandpath()` from [misc1.c](https://github.com/vim/vim/blob/7b256fe7445b46929f660ea74e9090418f857696/src/misc1.c#L9879) comment says:

>  NOTE: much of this is identical to unix_expandpath(), keep in sync!

Here is a [diff](https://www.diffchecker.com/byyqmjzf) between the two functions from Vim, that helps spot this and other differences.

**Comment by sethjackson** [comment]
Lint ssues should be fixed now. Not sure why Travis didn't run on the new push though?

**Comment by sethjackson** [comment]
Ping?

**Comment by justinmk** [comment]
To avoid repeating the `strchr` logic, something like this would be preferrable:

```c
                && (vim_strchr((char_u *)"*?[{~$", *path_end) != NULL
#ifndef WIN32
                    || (!p_fic && (flags & EW_ICASE)
                       && isalpha(PTR2CHAR(path_end))))
#endif
    )
    {
       e = p;
    }
```

**Comment by sethjackson** [comment]
We can do that but anything I've tried that doesn't duplicate the `strchr` logic fails to appease lint. :(

**Comment by justinmk** [comment]
@sethjackson We can ignore the lint errors in this case.

**Pull request merged**
