### PR TITLE
[RFC] rstream: Fix read_cb invocation (cherry-pick)

### LINKED ISSUE #3058: Segfault when renaming an open file using NERDTree
Over the last couple of days Neovim has started segfaulting when renaming an open file using [NERDTree](https://github.com/scrooloose/nerdtree) (Is this related to #3045?)

I just reinstalled neovim in order to verify that the problem still exists.

## How to reproduce

```
echo "test" > foo.txt
nvim foo.txt
:NERDTree
mm # to rename foo.txt to bar.txt
The old file is open in buffer 1. Replace this buffer with a new file? (yN)
y
Segmentation fault: 11
```

## nvim --version

```bash
NVIM 0.0.0-alpha+201507210938 (compiled Jul 21 2015 11:09:49)
Commit: fd740a383ae0839b6b50c21639fceae6bc375066
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150721-72700-mhsslr/build/config -I/tmp/neovim20150721-72700-mhsslr/src -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include -I/tmp/neovim20150721-72700-mhsslr/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150721-72700-mhsslr/build/src/nvim/auto -I/tmp/neovim20150721-72700-mhsslr/build/include
Compiled by peter@Peters-New-MacBook-Air.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

### PR DESCRIPTION
**Pull request by fmoralesc**
- Add missing call when the stream is a file
- NULL check because it is possible to call rstream_start with the callback set
  to NULL.

Should fix recently reported segfaults (re: #3045 #2893)

edit: it fixed #3058

### CODE REVIEW

**Comment by oni-link** [comment]
LGTM.

**Comment by mhinz** [comment]
LGTM

**Comment by Pyrohh** [comment]
LGTM, and fixed #3045 for me.

**Comment by fmoralesc** [comment]
Merged.

**Pull request closed without merging**
