### PR TITLE
tests: tui_spec.lua: wait_for_mode with "TUI paste: exactly 64 bytes"

### LINKED ISSUE #11110: Flaky test: tui_spec.lua: TUI paste: exactly 64 bytes
This failed 3+ times already:

```
[  ERROR   ] test/functional/terminal/tui_spec.lua @ 561: TUI paste: exactly 64 bytes #10311
test/functional/ui/screen.lua:587: Row 1 did not match.
Expected:
  |*zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzz end{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |
Actual:
  |* endzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzzzzzz{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:587: in function '_wait'
	test/functional/ui/screen.lua:370: in function 'expect'
	test/functional/terminal/tui_spec.lua:569: in function <test/functional/terminal/tui_spec.lua:561>
```
https://builds.sr.ht/~jmk/job/91950#task-test-release-585

Initially seen in https://github.com/neovim/neovim/pull/11083#issuecomment-534375201 (ref from top comment).

Code: https://github.com/neovim/neovim/blob/fe9d54f418973f59ec88ca05489da6df3609811f/test/functional/terminal/tui_spec.lua#L561-L579

_Originally posted by @blueyed in https://github.com/neovim/neovim/pull/11086#issuecomment-535247575_

### PR DESCRIPTION
**Pull request by blueyed**
Maybe fixes https://github.com/neovim/neovim/issues/11110.

Suggested in https://github.com/neovim/neovim/issues/11110#issuecomment-536160249.

### CODE REVIEW

**Comment by blueyed** [comment]
Still failed on FreeBSD:
```
[ RUN      ] TUI paste: exactly 64 bytes #10311: 3514.34 ms FAIL
test/functional/terminal/tui_spec.lua:609: Row 1 did not match.
Expected:
  |*zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzz end{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |
Actual:
  |* endzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzzzzzz{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:579: in function '_wait'
	test/functional/ui/screen.lua:361: in function 'expect'
	test/functional/terminal/tui_spec.lua:609: in function <test/functional/terminal/tui_spec.lua:600>
```

**Comment by blueyed** [comment]
@justinmk 
Is this what you've meant in https://github.com/neovim/neovim/issues/11110#issuecomment-536160249 after all?

> It might help to wait_for_mode(...) before or after the paste input.

**Comment by justinmk** [comment]
> Is this what you've meant in [#11110 (comment)](https://github.com/neovim/neovim/issues/11110#issuecomment-536160249) after all?

Yes. Maybe there's an actual bug :)

**Comment by justinmk** [comment]
Haven't noticed this failure in quite some time. And the test is not skipped in CI.

**Pull request closed without merging**
