### PR TITLE
Support for JSONC

### LINKED ISSUE #14947: runtime: support JSON5/JSONC
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? No
- Operating system/version: Linux 5.10.0-6-amd64
- Terminal name/version: Alacritty 0.8.0
- `$TERM`: xterm-256color

I see more and more tools using jsonc and json5 formats for their configuration files.  I believe this trend will only increase as NeoVIM should consider supporting this formats

### [jsonc](https://komkom.github.io)
Basically a JSON with C-style line (`//`) and block (`/**/`) comments.
Exiting vim plugin: https://github.com/kevinoid/vim-jsonc

### [json5](https://json5.org) 
Described as a json for humans.
Here is the specifications: https://spec.json5.org
Existing vim plugin for it already: https://github.com/gutenye/json5.vim

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC sample.jsonc
<opened as a plain text>

$ nvim -u NORC sample.json5
<opened as a plain text>
```

### Actual behaviour
opens up as a plain text

### Expected behaviour
Opened as a jsonc/json5 file:
- proper syntax highlighting
- proper error messages
- proper indentation and formatting

### PR DESCRIPTION
**Pull request by IzhakJakov**
Closes #14947

### CODE REVIEW

**Comment by izhakjakov** [comment]
Should I do anything to let authorized users know that this PR is ready for review?

**Comment by clason** [comment]
No, a ping like that is fine. Your PR has the wrong commit message -- it needs to be a single commit with a format like https://github.com/neovim/neovim/pull/15463 (where the commit hash is the one from the vim runtime file update). Please follow that format _exactly_.

**Comment by izhakjakov** [comment]
> No, a ping like that is fine. Your PR has the wrong commit message -- it needs to be a single commit with a format like #15463 (where the commit hash is the one from the vim runtime file update). Please follow that format _exactly_.

Done :)

**Comment by clason** [comment]
Sorry, that's still not correct: you are not porting the vim patch but the (partial) runtime file update (which has a different commit hash, too).

**Comment by izhakjakov** [comment]
I took this information from the ftp://ftp.vim.org/pub/vim/patches/8.2/8.2.3085
I did not see anything else there.  I'll take a look again

**Comment by izhakjakov** [comment]
BTW, you reply really fast.  I appreciate this :)

**Comment by clason** [comment]
But you're not porting that patch -- the runtime files were added in a separate update (which, unfortunately, is _between_ patches so they don't have a number).

**Comment by izhakjakov** [comment]
Found it :)
[90df4b9d423485f7db16e3a65cab4f14edc815ae](https://github.com/vim/vim/commit/90df4b9d423485f7db16e3a65cab4f14edc815ae)

**Comment by izhakjakov** [comment]
I will modify the commit msg now and push it

**Comment by clason** [comment]
No, sorry, the description also needs to be different ("add JSONC runtime files" or somesuch) -- you commit message is the same as for the (different) vim patch.

**Comment by izhakjakov** [comment]
> No, sorry, the description also needs to be different ("add JSONC runtime files" or somesuch) -- you commit message is the same as for the (different) vim patch.

Done.
How about now?

**Comment by clason** [comment]
No need for the vim "Problem/Solution" dance, just describe the commit (like in my Julia PR) :)

**Comment by izhakjakov** [comment]
> No need for the vim "Problem/Solution" dance, just describe the commit (like in my Julia PR) :)

OK will do but looks like some checks are no longer successful so first let it finish and see what else I need to fix.  (might not have time this weekend to finish) :/

**Comment by clason** [comment]
The lint check is not relevant here (the list of known -- and accepted -- errors has not been updated yet). Just go ahead while the rest runs.

**Comment by izhakjakov** [comment]
Yea I was surprised the gcc is failing over `.vim` files :confused:

**Comment by clason** [comment]
Merged; thanks for your patience!

**Comment by izhakjakov** [comment]
> Merged; thanks for your patience!

Thank you!

**Pull request merged**
