### PR TITLE
version.c: mark NA patches

### PR DESCRIPTION
**Pull request by Shougo**
NA list:

1653: matchit packadd
1750: channel
1770: termguicolors
1794: GUI Win32
1805: Makefile
1804, 1945: manpager.vim
1811: channel
2115, 2232, 2278, 2319: defaults.vim

included:

1763: spell

### CODE REVIEW

**Comment by Shougo** [comment]
I have updated the list.

**Comment by jamessan** [comment]
> 1763: spell

Just because it's a spelling change doesn't mean it should be excluded.  We still use the spell checking code.

This one in particular silences a Coverity issue, since the corresponding code is already excluded by an `#if 0`.

**Comment by Shougo** [comment]
I have found the `#if 0` is already added.

**Comment by jamessan** [comment]
> I have found the #if 0 is already added.

Hmm, so it is.  I must've been looking at the wrong code.

**Comment by Shougo** [comment]
I have updated.
7.4.1763 is already included.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
