### PR TITLE
refactor(decoration): format DECORATION_INIT

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by bfredl** [comment]
Is this really worth it? Initialization here is not meant to be interesting, this is literally just different spellings of zero.

**Comment by lewis6991** [comment]
For 5 or 6 fields, this probably isn't worth, but for 19 fields (and counting) passes the threshold for this being worth it on an expression where order matters. `DECOR_PRIORITY_BASE` is not zero, and can easily lead to a bug where someone adds a new field but puts the zero in the wrong place.

For more context, someone asked me [today](https://github.com/lewis6991/gitsigns.nvim/issues/605) about priority with virtual text. They couldn't figure out what the default was, and it even took me a couple looks, since I assumed it was 0.

**Comment by bfredl** [comment]
> and can easily lead to a subtle bug where someone adds a new field but puts the zero in the wrong place making priority default to 0.

This change does not protect against that.

> For more context, someone asked me https://github.com/lewis6991/gitsigns.nvim/issues/605 about priority with virtual text. They couldn't figure out what the default was, and it even took me a couple looks, since I assumed it was 0.

This sounds like a documentation issue (of `nvim_buf_set_extmark`), and not an issue solved by repeating "priority" as a comment just after "priority" in code.

**Comment by lewis6991** [comment]
It makes the code a little easier to grok.

Didn't really think this would warrant any discussion. Thought it would be a simple 1-2-glance-merge situation.

**Comment by bfredl** [comment]
> Didn't really think this would warrant any discussion. Thought it would be a simple 1-2-glance-merge situation.

I didn't mean to be facetious. I'm just saying this fails to improve on the situation it claims to improve. 

A sensible long-term refactor would be more like to change this to not be a 20-field struct to start with, perhaps by dividing it into smaller structs or adopting a more data oriented design where all these fields doesn't need to be allocated together in the first place.

**Comment by lewis6991** [comment]
I think it does improve the situation somewhat (even if small), since there are now two similar blocks that list fields in the same order so moving/removing/adding is just a little bit easier and less error-prone. I had this gripe with the code back when I added sign support, I even remember hitting the exact issue of getting the ordering wrong whilst rebasing at some point and it took me longer than It should have to spot the issue.

I also considered using the `(struct Decoration) {.field = ...., .field2 =....};` syntax, which would remove the risk of ordering, but also doesn't warn against missing fields so I opted to keep with the current syntax.

I agree this approach of adding fields isn't scaling well, and we've even talked about splitting the mark tree to move the sign stuff out. However this is a low effort PR, with zero cost and a small net gain, so I don't see any reason to push back.

**Comment by zeertzjq** [comment]
A downside of adding more comments here: If you reorder some boolean fields you need to reorder the comments.

**Comment by lewis6991** [comment]
Thinking about it, would there be a problem with something like:

```c
#define DECORATION_INIT (struct Decoration) { \
  .priority = DECOR_PRIORITY_BASE,  \
}
```

This will initialise all other fields to 0.

**Comment by bfredl** [comment]
> However this is a low effort PR, with zero cost and a small net gain, so I don't see any reason to push back.

Maybe the cost (except the code being clunkier to deal with) is negligible. What I pushed back is the claim this is relevant to subtle bugs regarding misordered fields, which this doesn't help with at all. `.field = val` syntax at least makes the compiler do some work for us (if not all), if the need to improve this is imminent.

**Comment by lewis6991** [comment]
>  (except the code being clunkier to deal with)

I actually thought it made it easier to work with by being more linewise and explicit. Obviously a difference of opinion.

> What I pushed back is the claim this is relevant to subtle bugs regarding misordered fields, which this doesn't help with at all.

Again, I disagree, see reasons above.

>  if the need to improve this is imminent.

It isn't, and tbh, we're in the loss in regard to any potential gain from the wasted time on this discussion. I'll just close this and move on. Sorry for wasting you time (genuinely).

**Pull request closed without merging**
