### PR TITLE
[RFC] Vim 7.4.9{78,80,81,91}

### PR DESCRIPTION
**Pull request by watiko**
```
patch 7.4.978
Problem:    test_cdo fails when using another language than English.
Solution:   Set the language to C. (Dominique Pelle)
```

https://github.com/vim/vim/commit/c42b9c670ea621d4dac0f216e011a6db576c5136

```
patch 7.4.980
Problem:    Tests for :cdo, :ldo, etc. are outdated.
Solution:   Add new style tests for these commands. (Yegappan Lakshmanan)
```

https://github.com/vim/vim/commit/57d7971b5f1621071176eea81cdb0d1fc50c925d

```
patch 7.4.981
Problem:    An error in a test script goes unnoticed.
Solution:   Source the test script inside try/catch. (Hirohito Higashi)
```

https://github.com/vim/vim/commit/4686b323e4bc0f466500b018959f6c8965f010f9

```
patch 7.4.991
Problem:    When running new style tests the output is not visible.
Solution:   Add the testdir/messages file and show it.  Update the list of
            test names.
```

https://github.com/vim/vim/commit/096c8bb40d51b22a4b1d761baf7bb79fb9e55a28

### CODE REVIEW

**Comment by watiko** [comment]
NeoVim has no compatible default value options on legacy test like `more`. Where is suitable to treat it?

**Comment by justinmk** [comment]
@watiko In case you were thinking of doing a lua test, please be aware of https://github.com/neovim/neovim/pull/3877

> has no-compatible default value options on legacy test like more. Where is suitable to treat it?

Where are you seeing that? We don't generally change anything in the non-lua legacy tests (`src/nvim/testdir/*`). In `dotest.in` there is `set nomore`...

**Comment by watiko** [comment]
Without `set nomore`, `Press ENTER ...` will happen to `test_cdo.vim`. But `nomore` does not fix lua test hanging.

**Comment by watiko** [comment]
@justinmk This PR avoids the lua test hanging and makes Vim's new style patch output error log (this is very helpful for porting).

NOTE: #3877's test is based on outdated legacy test (By this PR, new one will be introduced and be migrated).

**Comment by justinmk** [comment]
LGTM. Verified tests.

**Pull request merged**
