### PR TITLE
Handle 'orphaned signs' on line deletion for signcolumn >= 2

### PR DESCRIPTION
**Pull request by da-x**
Following discussion in #10078 to bring back sign deletion on line removal.

### CODE REVIEW

**Comment by da-x** [comment]
Also added a test and fixed a test today.
CI failures seem unrelated.

**Comment by teto** [comment]
have you been dogfooding/using this PR since then ? it's something I want but didn't have time to review yet.

**Comment by da-x** [comment]
Only partially - I've dogfooded only the reverts to `sign_mark_adjust`. I'll re-adjust my setup and report.

**Comment by teto** [comment]
can you rebase please ?

**Comment by da-x** [comment]
Rebased, now testing locally. Not sure if CI failure is related.

**Review by mhinz — APPROVED** [review]

**Comment by mhinz** [comment]
Recently I started using `signcolumn=auto:2` myself and this PR is certainly an improvement. I played around with a few different sign situations and I couldn't break sign handling. :+1:

In a perfect world, we'd additonally have a buffer of deleted signs and restore them on undo. Currently `ddu` would restore the line without any sign.

**Comment by lewis6991** [comment]
Just to point out this change has broken some [sign speculation logic](https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns.tl#L479) in gitsigns.nvim. It's not really a problem as the speculation was just to make the signs appear that much quicker but just mentioning to point out another use for having access to deleted signs.

**Pull request merged**
