### PR TITLE
ci: Travis: clean up / conditional APT packages

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by justinmk** [comment]
how much time does this save? if it's less than 30 seconds it's not worth the extra complication.

**Comment by blueyed** [comment]
This is meant to get to "have a base of packages", and additionals base on that.
This is also relevant for when installing gcc9 via PPA for example.

It's a quick shot at looking into how this could work.

**Comment by justinmk** [comment]
> This is also relevant for when installing gcc9 via PPA for example.

Why would we do that? It was a source of problems in the past. We had a complicated travis.yml, now we've simplified it. It doesn't make sense to make it complicated again...

**Comment by blueyed** [comment]
Closing for now.

**Pull request closed without merging**
