### PR TITLE
tui/term: do not map bold to bright colors

### LINKED ISSUE #11190: Bold terminal colors wrongly(?) mapped to "intense" color in 256-color terms
I am using a base16-like color theme for my terminal:

My Bash prompt is colored and uses a bold font for username (`[01;32m`) and hostname (`[01;34m`):

This works mostly well ([except in Konsole](https://bugs.kde.org/show_bug.cgi?id=405345), which has a problem similar to this issue).

It also worked well in neovim < 0.4 and stopped working well since neovim 0.4. :)

- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS 10.14, Fedora 29
- Terminal name/version: Terminal.app, iTerm, Konsole
- `$TERM`: xterm-256color
- `:set termguicolors?`: `notermguicolors`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:term<CR>
```

### Actual behaviour

Neovim no longer uses the green/blue colors and sets the font in bold, but uses the "bright green/blue" colors (which is beige in my case).

### Expected behaviour

Use green/blue colors in bold variant (codes `1;32`/`1;34`) instead of the bright variant (codes `92`/`94`).

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neovim/neovim/issues/11190.

### CODE REVIEW

**Comment by blueyed** [comment]
FreeBSD failure is unrelated ("TUI paste: exactly 64 bytes #10311").

**Comment by bfredl** [comment]
Already in #10994,  https://github.com/bfredl/neovim/commit/e1ab7758118236fea9062c491009d123ed55eaac . Though separate PR makes sense if we include it in 0.4.3, but could copy the commit message at least (good to see the reasoning behind it if someone ends up bisecting to it).

**Comment by blueyed** [comment]
Ok, let's take it via your commit then.
Could also ref: https://github.com/neovim/neovim/pull/3333 where it was removed previously already, and https://github.com/neovim/neovim/pull/4274 (https://github.com/neovim/neovim/commit/564f57d1e) where it was added again..

**Comment by blueyed** [comment]
If CI here is green I think we should cherry-pick it to master and release-0.4 then already.
Assuming #10994 takes longer.

**Comment by blueyed** [comment]
Merged yours in b772b86.

**Pull request closed without merging**
