### PR TITLE
pull request #2885 left this out

### PR DESCRIPTION
**Pull request by pvinis**

### CODE REVIEW

**Comment by ZyX-I** [comment]
You need to have *one* commit with descriptive commit message like “menu: Change ex_menu()/special variable type and use stdbool constants”.

**Comment by pvinis** [comment]
ah ok. i will fix it. should i do it in master ir a local branch?

On Παρ, Σεπ 25, 2015 at 11:36, neovim/neovim
<reply@reply.github.com>
wrote:
You need to have one commit with descriptive commit message like “menu: Change ex_menu()/special
variable type and use stdbool constants”.

—
Reply to this email directly or view it on GitHub
[https://github.com/neovim/neovim/pull/3387#issuecomment-143171342] .[https://github.com/notifications/beacon/AAGHiasoqJ1hHYBMWmV3oYuPpvJCbpcbks5o1Q0HgaJpZM4GDsCM.gif]

**Comment by ZyX-I** [comment]
Does not matter. But if you use local branch, you will need to run a different PR, because this requests to pull your master (BTW: it is better to not ever do this because such action freezes your master: you will not able to merge more recent changes from our master without receiving “merge commit should not be in this PR” complaint).

**Comment by pvinis** [comment]
Cool. will be fixed later today then. thanks

-- 
Pavlos Vinieratos


On 25 Sep 2015 at 11:46:16, Nikolai Aleksandrovich Pavlov (notifications@github.com) wrote:

Does not matter. But if you use local branch, you will need to run a different PR, because this requests to pull your master (BTW: it is better to not ever do this because such action freezes your master: you will not able to merge more recent changes from our master without receiving “merge commit should not be in this PR” complaint).

**Comment by pvinis** [comment]
#3389

**Pull request closed without merging**
