### PR TITLE
feat(diagnostic): use `scope = 'line'` by default for `open_float()`

### LINKED ISSUE #16453: Defaults: `scope = 'line'` in `vim.diagnostic.open_float`
### Feature already in Vim?

Not applicable

### Feature description

I've moved from using `vim.lsp.show_line_diagnostics` to using `vim.diagnostic.open_float` since the former is now deprecated.
The default for `open_float` is to put all diagnostics in the floating window, as opposed to just the ones for the current line for `show_line_diagnostics`.

This is very easy to configure so it's not a big deal, but I'd argue that `scope = 'line'` would be a much better default:
1. that's what people like me, moving from `vim.lsp.show_line_diagnostics` would expect
2. I think that buffer-wide diagnostics make much more sense in the qflist/loclist. I fail to see why someone would want to cram possibly many warnings/erros in a floating window: it's harder to read, not actionable (you can't just jump to the error 300 lines further in the buffer from the floating window) and less subjectively less intuitive.
3. more importantly, it's much harder to find the diagnostics corresponding to the current line in a bloated floating window

I'll be happy to submit a PR if the core/LSP team agrees and otherwise interested in learning why `'buffer'` was made default.

Thanks!

### PR DESCRIPTION
**Pull request by cbarrete**
Closes #16453

### CODE REVIEW

**Review by gpanders — APPROVED** [review]
LGTM, and thanks for updating the docs.

**Comment by gpanders** [comment]
There is one failing test in `diagnostic_spec.lua`

```
[  ERROR   ] test/functional/lua/diagnostic_spec.lua @ 1659: vim.diagnostic open_float() can add a prefix to diagnostics
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x01035b1b80) {
  [1] = '1. Syntax error' }
Expected:
(table: 0x0103303bd8) {
  [1] = '1. Syntax error'
 *[2] = '2. Some warning' }
```

**Comment by cbarrete** [comment]
Indeed, sorry about that.
Looks fixed now, I've mixed up some buffer/line open_float calls as well so that we have a bit more coverage.

**Comment by gpanders** [comment]
ASAN timed out, but all functional tests passed before it did so with no warnings, so I’m going to go ahead and merge.

**Pull request merged**
