### PR TITLE
ci: bump ubuntu runner version to ubuntu-24.04

### PR DESCRIPTION
**Pull request by dundargoc**
Also bump clang to version 20.

### CODE REVIEW

**Comment by dundargoc** [comment]
New clang-analyzer warnings that needs to be fixed. It seems we're using enums incorrectly.

**Comment by wookayin** [comment]
I think this would result in bumping up the minimum glibc version (for the CI-released binaries). I'm not sure we'll want this.

**Comment by dundargoc** [comment]
This only bumps the test runner, not release.

**Comment by dundargoc** [comment]
Also glibc doesn't matter, the releases in neovim-releases repo works on ancient glibc versions anyway.

**Comment by dundargoc** [comment]
https://github.com/neovim/neovim/pull/30652

**Comment by clason** [comment]
praise zig 🙌

**Pull request merged**
