### PR TITLE
[RDY] vim-patch:7.4.1549

### PR DESCRIPTION
**Pull request by P4Cu**
#### vim-patch:7.4.1549

Problem:    Test for syntax attributes fails in Win32 GUI.
Solution:   Use an existing font name.

https://github.com/vim/vim/commit/c835293d54c223627c7d4516ee273c21a3506fa1

### CODE REVIEW

**Comment by P4Cu** [comment]
This is my first ever contribution to nvim ;-)
The patch seems to be easy-cake but how I could run tests myself?

**Comment by phanimahesh** [comment]
@P4Cu Did you try `make test`?

**Comment by P4Cu** [comment]
Yes, but the correct target is nvim-test ;-) That's what fails on travis, but the failure is a different story. Would be nice to know how to fix it ;-]

**Comment by jamessan** [comment]
As far as running the test, this is an old-style vim test so you would run `make oldtest`.  However, this test is specifically for the GUI, so it's not going to be tested by nvim.

The test failure in Travis is due to a flaky test.  I've restarted that build.

**Comment by P4Cu** [comment]
Well, flaky tests... They're freakin' everywhere ;-) Thanks!

**Comment by P4Cu** [comment]
I guess it could be merged?

**Comment by Shougo** [comment]
LGTM

**Pull request merged**
