### PR TITLE
build: set CMAKE_C_STANDARD to 99 for all dependencies

### PR DESCRIPTION
**Pull request by dundargoc**
Older gcc versions (4.x) require passing --std=c99 compiler flag to
prevent warnings from being emitted. Instead of setting it for each
dependency, it's easier to just pass the CMAKE_C_STANDARD flag to all
dependencies. This also prevents the scenario of us forgetting to set it
if we add new dependencies.

### CODE REVIEW

**Comment by dundargoc** [comment]
@b1tg @e-kwsm can you try this PR and check that it works without problems?

**Comment by e-kwsm** [comment]
Unfortunately neovim does not compile with /usr/bin/gcc (4.8.5) on CentOS 7 any longer (https://github.com/neovim/neovim/pull/20445#issuecomment-1274117625).

**Comment by dundargoc** [comment]
Uh yes, but that's unrelated to this. I just assumed you bumped to gcc 4.9 or something.

**Comment by e-kwsm** [comment]
I use newer GCC (7 or 8) to build neovim on CentOS.
I try the branch, and the dependencies compile except for libuv.

**Comment by dundargoc** [comment]
That's good enough for me

**Pull request merged**
