### PR TITLE
feat(lsp): add before_init_async field to lsp client

### PR DESCRIPTION
**Pull request by emersonford**
LSP clients may want to run long-running code before initialization. Some examples are:
1. Pull LSP client settings from an external source before initializing.
2. Generate files such as [`rust-project.json`](https://rust-analyzer.github.io/manual.html#non-cargo-based-projects) before initializing `rust-analyzer` for non Cargo based projects.

Currently, if this kind of code is run in `before_init`, it locks up Neovim's main loop and delays Neovim's start up until `before_init` has completed. Given that `rpc.request('initialize', ...)` is already asynchronous, it seems reasonable we can add a version of `before_init` that can be run asynchronously.

example:
```lua
require("lspconfig")["rust-analyzer"].setup({
  before_init_async = function(init_params, config, done)
    local stdout = ''
    vim.fn.jobstart("some cmd to get initializationOptions", 
      on_stdout = function(_, d, _)
        stdout = table.concat(d, "\n")
      end,
      on_exit = function(_, status, _)
         if status == 0 then
           init_params.initializationOptions = vim.fn.json_decode(stdout)
         end
         done()
      end,
    )
  end,
})
```

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
For the first use case one could still do this async within `on_init` and notify the server about the changed settings via `client.notify('workspace/didChangeConfiguration', { settings = settings })`.


For the second use-case, I wonder if this is partly a problem with the lspconfig `setup` design. If you go by the functions that are in core (`start_client` and `buf_attach_client`) nothing would prevent you from doing the work async up-front before calling either `start_client` or `buf_attach_client`.


Because of that I'm kinda mixed on this. Let's see what @mjlbach has to say.

**Comment by mjlbach** [comment]
Same, I don't need think this needs to be an explicit field, maybe just an example that shows in lspconfig how to call a remote function and yield to the main loop with a coroutine.

**Comment by emersonford** [comment]
This would require changes to lspconfig's manager to accomplish the same thing right?

**Comment by emersonford** [comment]
Another follow up to this, suppose in example 2 we did run that work in some "pre-work" method in `lspconfig` before `lspconfig` calls `start_client`. How would the pre-work data then get associated with LSP client? 

Looking at https://github.com/neovim/nvim-lspconfig/blob/3d1baa811b351078e5711be1a1158e33b074be9e/lua/lspconfig/util.lua#L278, `lspconfig` doesn't get a client ID until after `start_client` has been called, which would be after `initialize` has already been sent out. For rust-analyzer, the `rust-project.json` path has to be sent either in `initializationOptions` or in `settings` in the `initialize` call (https://rust-analyzer.github.io/manual.html#non-cargo-based-projects). Neither of these are exposed to `lspconfig`.

**Comment by emersonford** [comment]
@mjlbach @mfussenegger wanted to get y'alls feedback on where to place this functionality:

### Inside of `lspconfig` w/o coroutines
1. As suggested by @mfussenegger, I look at doing the async work before `start_client` in `lspconfig` [here](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/util.lua#L2782).
  This has the problem of `manager.add` being synchronous (it returns `client_id` at the end), thus doing async work before `lsp.start_client` would require significant refactoring of everything that calls `manager.add`.

2. Alternatively, I looked at doing this in `manager.try_add` in `lspconfig` [here](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L230).
  However, I only want this "before init" work to be done when a new client is initialized, not when one is matched on `root_dir`. `manager.try_add` has no knowledge of whether there is an existing client or not (as the matching / initializing is done in `manager.add`), so I'd have to move that logic out of `manager.add` into `manager.try_add`.
  
 ### Inside of `lspconfig` with coroutines
As suggested by @mjlbach, I looked into using coroutines in `lspconfig`. You can't just wrap `M.setup()` in `coroutine.create` as that's only run once; I want this "do async work" done before each new initialization of an LSP client. So I'd imagine you have to wrap `manager.try_add` in a coroutine. This has the problems of:
1. Still requires an explicitly field inside of the `lspconfig` config as `lspconfig` would still need a function pointer to whatever pre-init work you want to do.
2. Would require you to pass the coroutine object inside the coroutine itself (not sure if this is good practice?), so it can get passed to the "do async work" functions.

Maybe I'm misunderstanding how lua coroutines work, but I'd imagine this would look like
```lua
lspconfig["rust-analyzer"].setup({
  ...
  pre_init = function(config, coro)
    vim.fn.jobstart("some_cmd_to_generate_rust_project_json" {
      on_exit = function(_, status, _)
          coroutine.resume(coro)
      end
    })
    coroutine.yield()
  
    config.path_to_rust_project_json = "foobar"
  end
})
```

---  
Which of these are most reasonable to you? I'd like to get working on either of these if this PR isn't acceptable. :)

**Comment by mjlbach** [comment]
> Maybe I'm misunderstanding how lua coroutines work, but I'd imagine this would look like
```
lspconfig["rust-analyzer"].setup({
  ...
  pre_init = function(config, coro)
    vim.fn.jobstart("some_cmd_to_generate_rust_project_json" {
      on_exit = function(_, status, _)
          coroutine.resume(coro)
      end
    })
    coroutine.yield()
  
    config.path_to_rust_project_json = "foobar"
  end
})
```
> Alternatively, with coroutines in this PR, I could remove the explicit before_init_async field and just pass a coro in as a parameter to before_init?


This was basically what I had in mind.

**Comment by emersonford** [comment]
Ah makes sense, once I put together I see how much cleaner this is (and have a bit better understanding of how Lua coroutines work!).

Thanks for the feedback, I submitted the changes. Let me know what you think. :)

**Comment by mjlbach** [comment]
This isn't what I had in mind, I'm not really sure how one can have a generic `async` callback for this (or should we), as the expensive work needs to all be implemented as individual coroutines which yield to the main thread after calling out with jobstart/whatever.

**Comment by emersonford** [comment]
Making sure I'm on the same page, what you're suggesting is not making this `local init_coro` change, but instead documenting that lspconfigs should define something like:
```lua
lspconfig["rust-analyzer"].setup({
  ...
  before_init = function(initialization_params )
    local coro = coroutine.create(function()
      local this_coro = coroutine.running()
      vim.fn.jobstart("some_cmd_to_generate_rust_project_json" {
        on_exit = function(_, status, _)
            coroutine.resume(this_coro)
        end
      })
      coroutine.yield()
    end)
    coroutine.resume(coro)
  
    config.path_to_rust_project_json = "foobar"
  end
})
```
?

**Comment by mjlbach** [comment]
Yes, is there something that doesn't address?

**Comment by emersonford** [comment]
@mjlbach know it's been a minute, but wanted to follow up on this again. Any thoughts? Also happy to discuss this on Matrix or something. :)

**Pull request closed without merging**
