### PR TITLE
feat(api): show more exception info

### PR DESCRIPTION
**Pull request by erw7**
The current implementation does not give enough information from lua about exceptions that occur in the vim script. This is an attempt to improve it. There may be a better way.

As an example, I show the error in #20920. If `... tutor#CheckLine: line 4:` had been displayed, it would have been much easier to determine the cause.

```
nvim --clean test.vim
:Tutor
```

#### After

```
Error detected while processing function tutor#TutorCmd[38]..BufReadPost Autocommands for "*":
Error executing lua callback: .../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: Error executing lua: .../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:22: function tutor#TutorCmd[38]..BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[17]..script /home/erw7/src/github.com/neovim/neovim/runtime/ftplugin/tutor.vim[43]..function tutor#ApplyMarks[7]..tutor#CheckLine: line 4: Vim(let):E158: Invalid buffer name: .
stack traceback:
	[C]: in function 'nvim_cmd'
	.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:22: in function <.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21>
	[C]: in function 'nvim_buf_call'
	.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: in function <.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: in function <.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:10>
```

#### Before

```
Error detected while processing function tutor#TutorCmd[38]..BufReadPost Autocommands for "*":
Error executing lua callback: .../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: Error executing lua: .../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:22: Vim(let):E158: Invalid buffer name: .
stack traceback:
	[C]: at 0x7f0770b5e9e7
	[C]: in function 'nvim_cmd'
	.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:22: in function <.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21>
	[C]: in function 'nvim_buf_call'
	.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: in function <.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:10>
stack traceback:
	[C]: at 0x7f0770b5e9e7
	[C]: in function 'nvim_buf_call'
	.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: in function <.../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:10>
```

#### legacy(`let g:do_legacy_filetype=1`)

```
Error detected while processing function tutor#TutorCmd[38]..BufReadPost Autocommands for "*.tutor"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[17]..script /home/erw7/src/github.com/neovim/neovim/runtime/ftplugin/tutor.vim[43]..function tutor#ApplyMarks[7]..tutor#CheckLine:
line    4:
E158: Invalid buffer name: .
E684: list index out of range: 0
...
```

### CODE REVIEW

**Comment by justinmk** [comment]
The extra info is:

    Error executing lua callback: .../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:21: Error executing lua: .../erw7/src/github.com/neovim/neovim/runtime/filetype.lua:22: function tutor#TutorCmd[38]..BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[17]..script /home/erw7/src/github.com/neovim/neovim/runtime/ftplugin/tutor.vim[43]..function tutor#ApplyMarks[7]..tutor#CheckLine: line 4: Vim(let):E158: Invalid buffer name: .

seems useful. Can/should we add line breaks to the vimscript trace?

**Comment by zeertzjq** [comment]
> if vimscript doesn't do this, I suppose it's out of scope for this PR

It doesn't.

**Comment by zeertzjq** [comment]
I think there needs to be some checks like how `v:throwpoint` is set:
```diff
diff --git a/src/nvim/api/private/helpers.c b/src/nvim/api/private/helpers.c
index d10d17c88..755fd120b 100644
--- a/src/nvim/api/private/helpers.c
+++ b/src/nvim/api/private/helpers.c
@@ -151,7 +151,18 @@ bool try_end(Error *err)
       xfree(msg);
     }
   } else if (did_throw) {
-    api_set_error(err, kErrorTypeException, "%s", current_exception->value);
+    if (*current_exception->throw_name != NUL) {
+      if (current_exception->throw_lnum != 0) {
+        api_set_error(err, kErrorTypeException, "%s: line %d: %s",
+                      current_exception->throw_name, current_exception->throw_lnum,
+                      current_exception->value);
+      } else {
+        api_set_error(err, kErrorTypeException, "%s: %s",
+                      current_exception->throw_name, current_exception->value);
+      }
+    } else {
+      api_set_error(err, kErrorTypeException, "%s", current_exception->value);
+    }
     discard_current_exception();
   }
 
```

**Comment by zeertzjq** [comment]
I wonder if E5500 can be removed as it now looks like redundant information.

**Review by bfredl — APPROVED** [review]

**Pull request merged**
