### PR TITLE
feat(lua): add vim.uniq to stdlib

### PR DESCRIPTION
**Pull request by gpanders**
This is a pure Lua implementation of the `uniq` VimL function.

### CODE REVIEW

**Comment by spywhere** [comment]
This looks like a filter operation with a unique filter function as default.

**Comment by gpanders** [comment]
It could be implemented with filter, but a common pattern is to use uniq in a pipeline, e.g.

```
map(uniq(sort(…)))
```

Doing the same with `filter` requires more boilerplate.

Besides, we already provide Lua versions of `split` and `filter` so having `uniq` provides nice symmetry between the Lua stdlib and VimL.

**Comment by clason** [comment]
I just came across this, and there are (at least) three issues with `vim.fn.uniq`:
1. polyvalent return type (deduped list or `0` if input is not a list), which confuses luals and emmyluals.
2. inability to modify the list in-place due to the well-documented limitations of the bridge (i.e., unlike `uniq(list)`, `vim.fn.uniq(list)` does nothing).
3. `uniq` only removes _adjacent_ duplicates, so `vim.fn.uniq({'a', 'b', 'a', 'b'})` returns the list unchanged.

Since deduplicating lists is a fairly common task, together these do add up to a compelling argument for adding a `vim.list_dedup` to the stdlib.

**Comment by lewis6991** [comment]
> Since deduplicating lists is a fairly common task, together these do add up to a compelling argument for adding a vim.tbl_dedup to the stdlib.

I'm not sure this would make sense for regular tables, `vim.list_uniq()` makes more sense to me. Unless the `tbl_` version just removes duplicate values, without considering the keys.

**Comment by clason** [comment]
Sorry, typo, I meant `list_uniq`.

**Pull request closed without merging**
