### PR TITLE
build(nix): fixed build

### PR DESCRIPTION
**Pull request by teto**
added missing dependencies libiconv

### CODE REVIEW

**Comment by teto** [comment]
@dundargoc I thought I would have to add some tree-sitter grammars to the build but  looks like it works fine without the vim grammar ?  https://github.com/neovim/neovim/blob/master/runtime/doc/news.txt#L51 mentions intl but I didn't need to update it either so maybe it is provided by the default nix build environment, not sure.

**Comment by clason** [comment]
Nothing breaks without tree-sitter parsers -- yet (although some tests won't pass, of course). Officially, we consider an installation without such parsers "broken", though, and won't think twice about requiring them in a feature that is enabled by default (e.g., the query linter).

**Comment by teto** [comment]
> Officially, we consider an installation without such parsers "broken",

which means the current nix install is broken since it doesn't have them :( are these supposed to be copied/symlinked (in which case cmake could detect the grammars and symlink them) in $VIMRUNTIME/parser ? 
We should highlight this during the release else package managers will be confused.

**Comment by clason** [comment]
> which means the current nix install is broken since it doesn't have them :( are these supposed to be copied/symlinked (in which case cmake could detect the grammars and symlink them) in $VIMRUNTIME/parser ?

We should be careful with terminology here:
1. **parsers** are installed by default in `/usr/local/lib/nvim/parser`, but will get picked up anywhere on `runtimepath`. However, order matters; these must be overridable by plugins and user config.
2. **queries** are installed in `$VIMRUNTIME/queries`; same warning about runtimepath order.

> We should highlight this during the release else package managers will be confused.

That has been the stance since 0.8 and communicated to those managers we are in contact with; if package managers didn't get the memo yet, not sure what we can do. Probably let them realize once we _do_ require these in our runtime...

**Comment by dundargoc** [comment]
> mentions intl but I didn't need to update it either so maybe it is provided by the default nix build environment, not sure.

How/whether intl is provided by the system is pretty complicated, but *normally* it should be provided by default. I'd check on macs as well to be sure as they have different detection logic for intl compared to linux.

**Comment by teto** [comment]
I will submit another PR, I didnt expect this to be merged so quickly. I think the build is still failing probably because of the tree-sitter version used in the flake. I notice neovim master uses
`TREESITTER_URL https://github.com/tree-sitter/tree-sitter/archive/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14.tar.gz`
which is not a released version so how does one package neovim 0.9 ? do we need to wait for a tree-sitter release ? For distributions it's hard (by policy) to package random commits.

**Comment by clason** [comment]
> I will submit another PR, I didnt expect this to be merged so quickly. I think the build is still failing probably because of the tree-sitter version used in the flake. I notice neovim master uses
> `TREESITTER_URL https://github.com/tree-sitter/tree-sitter/archive/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14.tar.gz`
> which is not a released version so how does one package neovim 0.9 ? do we need to wait for a tree-sitter release ? For distributions it's hard (by policy) to package random commits.

No, we use the recently released tree-sitter 0.20.8.

**Comment by will** [comment]
The flake is currently failing for me on the v0.9.0 commit (haven't tried in a few months). It seems maybe related to the comments here so I figured I'd post it here before I have it fully figured out. I can open up a new issue, but I'm still poking around to make sure it's not a problem with me first.

```
nix log /nix/store/m56z9wh89nnapjnjla88fnr5sxch8qjp-neovim-unwrapped-1b57a02.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/pj8arx3i07g7djc3lg2kjfiipsj5ja5n-vdm3zahbdggn7ba2s4155a1w87cp1hac-source
source root is vdm3zahbdggn7ba2s4155a1w87cp1hac-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/jnp9n2x9cdvl47da3656illrd3p2qvb5-system_rplugin_manifest.patch
patching file runtime/autoload/remote/host.vim
patching file runtime/plugin/rplugin.vim
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_I>
-- The C compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/fb4rdxr69sy1vsi98z3njxjzdq3rj3ah-clang-wrapper-11.1.0/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Using deployment target
-- CMAKE_INSTALL_PREFIX=/nix/store/z3lc3cc8f1ff6yz56yjggd2hqkr88g17-neovim-unwrapped-1b57a02
-- CMAKE_BUILD_TYPE=Release
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2
-- Checking Lua interpreter: /nix/store/dzvsn7pwsmzi060a640abm5i0vdm7x9l-luajit-2.1.0-2022-10-04-env/bin/luajit
-- Using Lua interpreter: /nix/store/dzvsn7pwsmzi060a640abm5i0vdm7x9l-luajit-2.1.0-2022-10-04-env/bin/luajit
-- Using Lua interpreter for code generation: /nix/store/dzvsn7pwsmzi060a640abm5i0vdm7x9l-luajit-2.1.0-2022-10-04-env/bin/luajit
-- Using Lua compiler: /nix/store/dzvsn7pwsmzi060a640abm5i0vdm7x9l-luajit-2.1.0-2022-10-04-env/bin/luajit -b -s %s -
-- Could NOT find libuv (missing: libuv_DIR)
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for kstat_lookup in kstat
-- Looking for kstat_lookup in kstat - not found
-- Looking for kvm_open in kvm
-- Looking for kvm_open in kvm - not found
-- Looking for gethostbyname in nsl
-- Looking for gethostbyname in nsl - not found
-- Looking for perfstat_cpu in perfstat
-- Looking for perfstat_cpu in perfstat - not found
...skipping...
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/testing.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/textformat.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/textobject.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/input.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/ugrid.c.o
[ 86%] Building C object src/nvim/CMakeFiles/nvim.dir/ui.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/ui_client.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/ui_compositor.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/undo.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/usercmd.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/version.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/viml/parser/expressions.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/viml/parser/parser.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/window.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/cjson/fpconv.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/cjson/lua_cjson.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/cjson/strbuf.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/mpack/conv.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/mpack/lmpack.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/mpack/mpack_core.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/mpack/rpc.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/mpack/object.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xdiffi.c.o
[ 90%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xemit.c.o
[ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xprepare.c.o
[ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xhistogram.c.o
[ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xpatience.c.o
[ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xutils.c.o
[ 95%] Linking C executable ../../bin/nvim
Undefined symbols for architecture arm64:
  "_ts_tree_included_ranges", referenced from:
      _tree_get_ranges in treesitter.c.o
ld: symbol(s) not found for architecture arm64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:4643: bin/nvim] Error 1
make[1]: *** [CMakeFiles/Makefile2:529: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by clason** [comment]
That is exactly what I mentioned above: Neovim requires tree-sitter 0.20.8, which presumably isn't packaged for Nix yet.

**Pull request merged**
