### PR TITLE
fix(ci): disable broken test on slow CI

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by shadmansaleh** [comment]
This happens quite often in linux too .

@mjlbach and I were just discussing today if this should be disabled on linux . GithubCI mostly gets stuck on this test.

**Comment by bfredl** [comment]
likely a resource load thing, with GHA being more loaded with crypto shit^W^Wmore open source projects using it.

**Comment by mjlbach** [comment]
Let's just disable this test globally until we figure out a better solution.

**Comment by mjlbach** [comment]
after updating the commit message this will LGTM

**Pull request merged**
