### PR TITLE
vim-patch:8.2.3283: Julia filetype is not recognized

### PR DESCRIPTION
**Pull request by clason**
Problem:   Julia filetype is not recognized
Solution:   Add filetype detection. (Christian Clason, closes #8700)

includes corresponding runtime files scheduled for next update (https://github.com/vim/vim/pull/8700)

issue: https://github.com/vim/vim/issues/7498
vim-patch: https://github.com/vim/vim/commit/0eec8519424eaea7baebfda979c33dd609a4e3fa

### CODE REVIEW

**Comment by janlazo** [comment]
Patch v8.2.32**83**, not v8.2.32**38**.

**Comment by clason** [comment]
🤦🏻

**Comment by janlazo** [comment]
```
Creating files.
✔ Saved pull request diff to '/home/jan/repo/git/neovim/nvim-8.2.3283.patch'.
✘ Wrong commit message.
  Expected:
vim-patch:8.2.3283: Julia filetype is not recognized

Problem:    Julia filetype is not recognized
Solution:   Add filetype detection. (Christian Clason, closes vim/vim#8700)
https://github.com/vim/vim/commit/0eec8519424eaea7baebfda979c33dd609a4e3fa
  Actual:
vim-patch:8.2.3283: Julia filetype not recognized

Problem: Julia filetype is not recognized
Solution: Add filetype detection. (Christian Clason, closes #8700)
```
Missing **is**.

**Review by janlazo — APPROVED** [review]

**Comment by clason** [comment]
runtime updates are live: https://github.com/vim/vim/commit/6aa57295cfbe8f21c15f0671e45fd53cf990d404

**Pull request merged**
