### PR TITLE
vim-patch:8.1.2302,8.2.{3936,4112}

### LINKED ISSUE #8807: Writing file overwrites '[ and '] marks, despite :lockmarks/:keepmarks
This breaks autosaving functionality that many of us are using.

The `:wall` command and its family overwrite the '[ marks, but we want to avoid this using `:lockmarks` or similar. 

- `nvim --version`: NVIM v0.3.1
- Vim (version: 8.1 ) behaves differently? No
- Operating system/version: MacOS 10.13.6
- Terminal name/version: Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC file.txt<CR>
i abcdef<ESC>
yy
ppppppppppp
kk
`[
`]
:lockmarks wall<CR>
`[
`]
```

### Actual behaviour
Cursor moves to top of file since entire file was written and this overwrites the corresponding marks

### Expected behaviour
Cursor moves toward bottom of file where the last line was pasted

### PR DESCRIPTION
**Pull request by seandewar**
vim-patch:8.1.2302: :lockmarks does not work for '[ and ']

Problem:    :lockmarks does not work for '[ and '].
Solution:   save and restore '[ and '] marks. (James McCoy, closes vim/vim#5222)
vim/vim@f4a1d1c

Test_diff_maintains_change_mark doesn't actually fail without these changes.
This is fixed in v8.2.3936. Ref: https://github.com/vim/vim/pull/9424.

vim-patch:8.2.3936: no proper test for maintaining change mark in diff mode

Problem:    No proper test for maintaining change mark in diff mode.
Solution:   Run the test with internal and external diff. (Sean Dewar,
            closes vim/vim#9424)
vim/vim@ccc1644

Closes #8807

### CODE REVIEW

**Comment by zeertzjq** [comment]
Now that #17086 has been merged, I guess <https://github.com/vim/vim/commit/54c8d229f54e36e89fcd5d84e523fd894d018024> can now be fully ported is this PR?

**Comment by seandewar** [comment]
Thanks for letting me know! I think you're correct; I'll look into adding that patch when I have some time. 👍

**Comment by seandewar** [comment]
Had a look. I don't think it can be ported quite yet as `Test_clipboard_regs` needs `set clipboard=autoselect` and friends to be reimplemented (and a fix for #4773).

The other tests seem okay, so I can do a partial port of the patch for now. 👍

**Comment by zeertzjq** [comment]
<https://github.com/vim/vim/commit/d9b74a2a41e43ca17a9885ec0a58404adff4273f>

**Comment by seandewar** [comment]
Added, cheers!

**Comment by zeertzjq** [comment]
Oops, resolving conflicts GitHub doesn't seem to work well.

**Comment by clason** [comment]
> Oops, resolving conflicts from GitHub Web interface doesn't seem to work well.

I made that very same mistake :D  (I'd have expected a rebase, not a merge commit...)

Easiest way is probably to use the `gh` CLI tool: 

1.  check out `neovim/neovim` repo
2. `gh pr checkout 16820`
3. `git rebase master`
4.  fix the conflicts if necessary
5. `git push -f`

**Review by zeertzjq — APPROVED** [review]

**Pull request merged**
