### PR TITLE
feat: `vim.merge`

### PR DESCRIPTION
**Pull request by folke**
This PR includes `vim.merge`, an utility function that is similar to `vim.tbl_deep_extend` with the **force** option, but also works for other types than tables.

> --- Merges the values similar to vim.tbl_deep_extend with the **force** behavior,
--- but the values can be any type, in which case they override the values on the left.
--- Values will me merged in-place in the first left-most table. If you want the result to be in
--- a new table, then simply pass an empty table as the first argument `vim.merge({}, ...)`

## Note

This PR includes a commit from another PR #15094. Not sure how that works 😅. I assume when the other PR is merged, this will also be able to merge.

### CODE REVIEW

**Comment by clason** [comment]
Can this function be refactored to unify the three (four, counting options) slightly different functions by adding full control over the behavior? I feel this would be a significant net improvement to the API.

**Comment by folke** [comment]
- `force`: is the strategy that should be used
- `keep`: this one should not be needed, since `keep` is the same as `force` with a different order of the arguments
- `error`: shouldn't exist. There's no single place this is used in the whole Neovim code-base
- `options`: should be how merging works. Unless someone can show me a use-case for the new index based list table merging.

Ideally, we should revert the changes to `tbl_deep_extend` and make this function `deprecated`.

Add the more solid `vim.merge` that can work with any type. See https://github.com/folke/lazy.nvim/blob/main/lua/lazy/core/util.lua#L439-L469

**Comment by clason** [comment]
The point is that all possible behaviors can be reasonable in some context, so we should (via an options table, not hard-coded "behavior" strings) support all of them to avoid the next "this function should behave like this, not that, because $FOO" ("it already does, just set `opts = { ... }`").

**Comment by clason** [comment]
> Ideally, we should revert the changes to tbl_deep_extend and make this function deprecated.

Go ahead, but please add better documentation in the process to explain why the behavior is what it is; otherwise we'll be here again in two years' time.

**Comment by folke** [comment]
`tbl_deep_extend` or `vim.merge` can merge multiple tables at once, so not limited to two tables.
This makes it a bit annoying to implement options.

It would mean that even when using the default options, users would still need to add an empty table at the end.

Unless you were thinking of another way?

- `Util.merge(a,b,c, {error = true})`.
- `Util.merge(a,b,c)` -> here we don't know if `c` is a table to merge, or if it's `opts` for the merging
- `Util.merge(a,b,c,{})` -> always need to define an empty `opts` for defaults

**Comment by clason** [comment]
Due to varargs, I think there is a good reason to deviate from API guidelines and put the `opts` table first (even if it's empty). Users or plugins could still create convenience wrappers for (their) "default" behavior if that becomes cumbersome?

I just think having _four_ subtly different functions is something to be avoided (today) even at significant cost.

**Comment by folke** [comment]
That could work, but I'm afraid that will lead to issues with people forgetting to add it. It's also not needed to have it as the first arg, if you always need to add `opts`, then it can also be the last arg as with all other functions.

What about:
- `vim.merge` -> just a shorthand for the other function
- `vim.merge_with_opts` (or any other name)

Since most people just need the merging functionality without any options (where they can switch the order of args for `keep` or `force`). For more advanced use-cases, they can use the other function.

**Comment by clason** [comment]
> Since most people just need the merging functionality without any options (where they can switch the order of args for keep or force). 

I would like to be careful with such assumptions; it has bitten us before. In any case, my proposal is for one big function instead of four or more custom ones; if it turns out that adding a wrapper for one special case really pays off, we can still add that -- the salient point being that it's a wrapper, not a separate function to be implemented and tested.

**Comment by justinmk** [comment]
>  `keep`: this one should not be needed, since `keep` is the same as `force` with a different order of the arguments

great point.

>  `error`: shouldn't exist. There's no single place this is used in the whole Neovim code-base

what about an optional `on_conflict` callback?

> vim.merge -> just a shorthand for the other function
> vim.merge_with_opts (or any other name)

overloads are not hard to do, as long as we don't support varargs (`...)`. varargs is not needed here because it's trivial to add `{}` around any args.

**Comment by clason** [comment]
> varargs is not needed here because it's trivial to add {} around any args.

Careful; that creates a new table, which is not free (and you don't know how large the tables to be handled could be -- think LSP protocol or even payload).

**Comment by clason** [comment]
Regarding `varargs`: How prevalent is the usecase of merging three or more tables? Do we really need to support that over asking users to simply merge the tables iteratively (that _is_ an associative operation given the order, no)?

**Comment by clason** [comment]
After thinking about it more, supporting the full generality of recursive merging behavior is a fool's errand. We should just support 
1. the old `tbl_deep_extend`;
2. the new `tbl_deep_extend`.

The only question is
1. naming;
2. whether we still can subsume these two within a single (better) API.

(Clearly we will revert the recent change for now in either case, but we might also wish to deprecate the function in favor of a new API if that has clear benefits.)

**Comment by folke** [comment]
Do we really need the new type of merging?
Has this ever come up in a feature request? 
That original issue had nothing to do with index based merging.

And the same for `error`, or `on_conflict`. Who needs that?

Also `keep` vs `force`. Same thing.

Would be much better to have a single `merge` function. The use-cases for the index-based list merging and `error` are just not strong enough to warrant additional code for that imo.

**Comment by clason** [comment]
> Do we really need the new type of merging?

Yes, since you cannot assume that a list (which is an accidental property of a _concrete_ table) will correctly determine the desired outcome, so this should be an explicit user choice.

To steal an example from @mfussenegger : Imagine a table indexed by buffer numbers. The keys start at  `1`, then you add `2`, then you add `3`, then you _delete_ `1` -- what then? Should extending the buffer list suddenly behave differently?

**Comment by siduck** [comment]
> 1. naming;
  
`tbl_deep_extend_list`

**Comment by clason** [comment]
Anyway, clearly there is no consensus for a new API, so let's just park this here. I will just leave (mostly as a note to my future self) my current idea for how a practical `vim.merge` could look like:

`vim.merge(tables, opts)`
  Merges two or more Lua tables.
  Parameters:
  * tables      (`table<table>`) List of two or more tables to merge. In case of common keys, the ones that occur later in the list have precedence.
  * opts      (`table`) Options controlling the behavior. Valid keys are
                   - `recursive` (`boolean`) whether common table keys are merged instead of replaced
                   - `listlike` (`merge|concat|union`) whether list-like tables should be treated specially:
                     * `merge` (default) no special treatment (i.e., like the new `tbl_deep_extend`)
                     * `concat` if all values are list-like, concatenate their elements (i.e., the old `tbl_deep_extend`, or `list_extend` if `recursive=false `)
                     * `union`, if all values are list-like, combine their elements, removing duplicates (which is arguably what you want most of the time -- but not always -- when dealing with lists in "config tables")

This would cover `tbl_extend`, `tbl_deep_extend` (old and new), and an improved `list_extend` (which I would still keep as an **in-place** fast path, since it's used as such throughout our code base).

**Comment by mehalter** [comment]
I really like the API above, the only comment I would add is that the old `tbl_deep_extend` is not concatenation, it's simply treats them as unmergable. I like the addition of concatenation and union as those both can be very useful, but there should also be an `ignore` option that emulates the old `tbl_deep_extend` behavior

**Comment by clason** [comment]
I don't think "ignore" is what you want here -- you want to treat them as literals, so overwrite instead of recursing into them?

**Comment by mehalter** [comment]
yeah true, I was thinking ignore in terms of performing "merging" but `overwrite` could be a more clear verb to use there or `literal` to treat them as literals. Thanks!

**Comment by clason** [comment]
Hmm, the issue with `literal` is that a config table is _itself_ a "list", so you'd _never_ recurse after the first tier. The old `tbl_deep_extend` had a more specific behavior (that I'm actually a bit confused that it worked for the "config merging" use case, at least for deeply nested configs).

**Comment by GitMurf** [comment]
> `'union'`, if all values are list-like, combine their elements, removing duplicates (which is arguably what you want most of the time -- but not always -- when dealing with lists in "config tables")

@clason maybe I'm not understanding the options correctly but I do not think this is true for "most" of the time for config tables. I'm thinking of plugin config default options and for user to override with their own options for a list option you would rarely want a union because that means you are always forced to use the default options PLUS any items the user set for the list option. For example, if a default plugin config was:

{ some_option: { "lua", "markdown" } }

and then you want to instead make it TypeScript and python by providing:

{ some_option: { "typescript", "python" } }

the final merged result would end up being (with union flag):

{ some_option: { "lua", "markdown", "typescript", "python" } }

That means users could not set their own config options for list items but could only "add" to the defaults. Or am I not understanding something here? Thanks for your hard work as usual!!

**Comment by folke** [comment]
@GitMurf that would be the `concat` option that @clason documented above.

**Comment by folke** [comment]
One additinal thing I added in lazy's `merge`, is that you can have keys set to `vim.NIL` and that would set the value in the merged table to `nil`. Useful in some cases to unset some default options...

**Comment by GitMurf** [comment]
> @GitMurf that would be the `concat` option that @clason documented above.

@folke my point was to the comment in the `union` description of: `...(which is arguably what you want most of the time -- but not always -- when dealing with lists in "config tables")`

I do not think this is accurate is it? Isn't this more accurate for the `literal` option?

**Comment by clason** [comment]
As long as it's an option, it's on the caller to use the best one for their use case. I don't see any grounds for premature panic here.

**Comment by GitMurf** [comment]
I guess as a follow-up as well, am I understanding it correctly that the only difference between `concat` and `union` is that union will remove the duplicates?

**Comment by folke** [comment]
Ah right, yes, I think the default should proably be `literal` indeed.

Within `lazy.nvim`, I added the option to specify a list of dotted keys whose values should use the `concat` stragegy instead of the `literal` strategy.

**Comment by GitMurf** [comment]
> As long as it's an option, it's on the caller to use the best one for their use case. I don't see any grounds for premature panic here.

My comments are for proper understanding and making sure we are all "speaking the same language" :-) I certainly don't want to raise concerns or give opinions if I don't fully understand or feel like I am not grasping a concept deeply enough or that we are speaking different terms. Not meant to be criticism or panic :) Thanks for all the work you do @clason as I know it is not an easy job!

**Comment by GitMurf** [comment]
> Ah right, yes, I think the default should probably be `literal` indeed.

@folke I agree the default should be `literal` given that is the "old way" and what people are use to (that is just my opinion). But to be clear, the proposal above (I know it isn't a final proposal or anything... but to memorialize where things are at right now) is that `merge` (the "new" way that is now being reverted) is proposed to be the default. Since we were talking about `concat` and `union` it seemed like you were responding to that and were implying that `literal` should be the default instead of concat/union (but none of those are the current proposed default).

Sorry I know I can be verbose but there is a lot of nuance here ;-)

**Comment by clason** [comment]
The default doesn't really matter here.

**Comment by GitMurf** [comment]
> The default doesn't really matter here.

What do you mean? To me the default is one of the most important pieces when this gets implemented isn't it? Given the clear amount of ambiguous and subjective opinions/expectations that have presented themselves on how tbl_deep_extend should work.

I just want to leave this thread of conversation clear and make sure we are all on the same page given we have all put a lot of time into thinking through and discussing this the last 12 hours. So that when you / folke pick this back up (whenever that may be) there are some clear understandings. I promise I am not trying to be difficult and only eager to help :)

**Comment by clason** [comment]
Sigh. The default only determines which option you can omit. It does bot affect achievable behavior in any way.

**Comment by GitMurf** [comment]
> Sigh. The default only determines which option you can omit. It does bot affect achievable behavior in any way.

Fair enough...

Alright I know I am starting to become too verbose and somewhat speaking in circles so I will leave it at my comments and opinions already posted above as I think it is clear ;-) I will hold off on commenting further for either of you to ask me for any feedback, suggestions or testing as this progresses going forward.

Thank you both @clason and @folke (and others) for all your hard work and for letting me participate in the conversation.

**Pull request closed without merging**
