### PR TITLE
feat: only use cterm0-15 for notgc

### LINKED ISSUE #26385: The default colorscheme should only pull from the 0-16 terminals colors with `notermguicolors`
## Problem

With `notermguicolors` the default colorscheme pulls all its colors from the 17-255. This is a bold change from the old default colorscheme which only uses the [0-15 ansi colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). The benefit this had was that it used whatever color palette was defined in the terminal, and thus whatever the user configures themselves. Now the new default colorscheme is quite jaring and completely deviates from the colors used in the terminal.

Note I think it's good to distinguish the two components of a colorscheme which often get conflated:
1. The palette. The actual values for each color, e.g. What is red, blue, etc.
2. How the palette is used.

This issue only wishes to change how palette is determined with `notermguicolors`, not how it is used.

Also note, I believe the old default colorscheme only had issues with 2 which #26334 addresses very well.

## Proposal

The current color palette almost falls into the 16 color space, however it contains 20 colors as it uses 8 colors for gray.

```
Dark:
blue    = "#005078"
cyan    = "#007676"
green   = "#015825"
grey1   = "#0a0b10"
grey2   = "#1c1d23"
grey3   = "#2c2e33"
grey4   = "#4f5258"
magenta = "#4c0049"
red     = "#5e0009"
yellow  = "#6e5600"

Light:
blue    = "#9fd8ff"
cyan    = "#83efef"
green   = "#aaedb7"
grey1   = "#ebeef5"
grey2   = "#d7dae1"
grey3   = "#c4c6cd"
grey4   = "#9b9ea4"
magenta = "#ffc3fa"
red     = "#ffbcb5"
yellow  = "#f4d88c"
```

Therefore we should be able to rework the colorscheme to only use the `cterm0-15` colors and provide a terminal configuration for users who wish use the new Nvim palette. Since the palette requires 4 additional colors either:
- pull these from the 17-255 space.
- merge these shades of grey into white, black, "dark white" and "bright black".

## Other points:
- The current `notermguicolors` differs quite a bit to the `termguicolors` version. If instead we use
the 0-15 space and provide a terminal configuration, then it is possible for the `notermguicolors` version
to much more closely match the `termguicolors` version. If the user wishes.
  - This will be useful for anyone who SSH's into machines that have Neovim but not their default config and/or without the correct terminfo to enable truecolor.
- The 256 color set is not usually configurable in terminals.
   - Wezterm **does allow** defining the full 256 range via OSC escape sequences: https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences
- Defining a background will change/disrupt any setups who use transparent terminals.

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes #26385

NvimDark/LightGrey[1-2] and NvimDark/LightGrey[3-4] have been merged.

Will also try using the 255 space for these.

### Script to set the terminal 0-16 colors to the new Nvim palette via OSC

<details>
<summary>click to expand</summary>

```bash
#! /usr/bin/env bash

blue='#005078'
cyan='#007676'
green='#015825'
black='#0a0b10'
# black='#1c1d23'
# black_bright='#2c2e33'
black_bright='#4f5258'
magenta='#4c0049'
red='#5e0009'
yellow='#6e5600'
blue_bright='#9fd8ff'
cyan_bright='#83efef'
green_bright='#aaedb7'
white_bright='#ebeef5'
# white='#d7dae1'
# white_bright='#c4c6cd'
white='#9b9ea4'
magenta_bright='#ffc3fa'
red_bright='#ffbcb5'
yellow_bright='#f4d88c'

# Reset colors
printf '\x1b]104;\1xb\\'

set_color()        { printf '\x1b]4;%d;%s\x1b\\' "$1" "$2"; }
put_template_var() { printf '\x1b]%d;%s\x1b\\'   "$1" "$2"; }

# 16 color space
set_color 0  $black
set_color 1  $red
set_color 2  $green
set_color 3  $yellow
set_color 4  $blue
set_color 5  $magenta
set_color 6  $cyan
set_color 7  $white
set_color 8  $black_bright
set_color 9  $red_bright
set_color 10 $green_bright
set_color 11 $yellow_bright
set_color 12 $blue_bright
set_color 13 $magenta_bright
set_color 14 $cyan_bright
set_color 15 $white_bright

# foreground / background
put_template_var 10 $white
put_template_var 11 $black

```

</details>

### Comparison

Diff with cursorline disabled.

1: master
2: This PR with Nvim color palette (using the script above). This is much closer to the `tgc` variant.
3. This PR with a github palette: https://github.com/lewis6991/github_dark.nvim/blob/master/theme.sh
4. This PR with a standard ANSI palette. Specifically the "Windows XP" version from https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit

image

Side note: looks like these screenshots reveal some redrawing issue which is only present with `notgc`. I don't have that issue normally.

### CODE REVIEW

**Comment by clason** [comment]
Please also show diff mode.

**Comment by echasnovski** [comment]
And here is how it looks in my terminal emulator (no colors altered beforehand):

screenshot_2023-12-04_17:32:07

Notice the non-existent floating window and too light shade of current line.

Here is the contrast for current line: 

screenshot_2023-12-04_17:32:40

**Comment by echasnovski** [comment]
And yeah, here is the diff (there is text inside green background):

screenshot_2023-12-04_17:45:42

**Comment by lucario387** [comment]
The added diffs looks too bright imo

**Comment by clason** [comment]
Yeah, those are clearly unacceptable. (To be clear, I am sympathetic to this change in general, but these situations _must_ remain reasonably accessible. That was the whole point -- for me -- of updating the colorscheme. I hope you can find a combination of sub-16 colors that works.)

**Comment by justinmk** [comment]
For the bright green diff we can set fg to "black". Also for cursorline, if necessary.

**Comment by echasnovski** [comment]
> For the bright green diff we can set fg to "black". Also for cursorline, if necessary.

For diff that might work but can't be guaranteed.
For cursorline it will override all syntax highlighting except bold/underline/etc. Not sure if this is a good UI.

**Comment by lucario387** [comment]
I think a darker grey for CursorLine might be okay. I assume that will lead to better readability with light colors

**Comment by echasnovski** [comment]
> > Not sure if this is a good UI.
> 
> Something has to give in this restricted (last resort) scenario. "good UI" is certainly not something we can expect here (only strive for, and hope for the best).

I'd expect a `:colorscheme vim` be a true last resort scenario. While `notermguicolors` is the one new users see first, which indeed should have a good UI.

**Comment by clason** [comment]
> While notermguicolors is the one new users see first, which indeed should have a good UI.

Not if `tgc` becomes the default. I don't consider 16c (on modern terminals) an acceptable default. I accept Lewis' use case, but I cannot believe that this is the majority demand.

**Comment by echasnovski** [comment]
**If** `termguicolors` becomes default if that capability is supported (so that stock `nvim` without config and `nvim --clean` are seen by new users with a good default color scheme with fixed set of colors), then it is a completely different story. I myself would be advocating for using only 0-15 colors for `cterm*` and treating them as "last resort" (and more closely to what Vim's is doing).

**Comment by lewis6991** [comment]
> Yeah, those are clearly unacceptable. (To be clear, I am sympathetic to this change in general, but these situations _must_ remain reasonably accessible. That was the whole point -- for me -- of updating the colorscheme. I hope you can find a combination of sub-16 colors that works.)

I hope it's understood that by using 16 colors that YMMV. It will be pretty easy to find an example where it doesn't work if the user doesn't have a well spaced out terminal colorscheme.

Therefore, I've added an example that uses 16 colors with the new Nvim palette in addition to what it looks like with my terminal theme which I've put a lot of time into.

Admittedly the comparison with my github palette is a bit brighter than default but I consider it far from unusable and overall I generally much prefer it. If we go this route, I'll probably just tweak my green color to be a little darker. This will make diff in the CLI nicer too.

There are still some colors we could tweak, but so far I think this is pretty good.

**Comment by justinmk** [comment]
Looks reasonable. What do floats/pmenu look like?

**Comment by echasnovski** [comment]
> Looks reasonable. What do floats/pmenu look like?

The same:

screenshot_2023-12-05_15:50:23

screenshot_2023-12-05_15:50:28

screenshot_2023-12-05_15:51:39

------

My overnight thought is that any of the following routes are reasonable compromise:

1. Leave it as it is, i.e. use only 16-255 colors in `cterm*` to have the curated default palette. This has the advantage of not *depending* on user terminal config and providing uniform experience for new users. The disadvantage is that is does not use terminal config and can not provide tailored user experience.
2. Make `termguicolors` default and have curated default `gui` palette. This will provide a uniform experience for new users with terminals capable of true color.
    At the same time treat `cterm*` as "emergency option" for terminals which do not support true color. I.e. no condition on it to [look like this](https://github.com/neovim/neovim/issues/14790#issuecomment-927200052), to have "good UI", etc. Then it opens a door to a more natural usage of only 8 colors: 7 for foreground and only single background color. This allows eliminating the problem of contrast by relying only on a single assumption of "Red, green, yellow, blue, cyan, magenta, and foreground can be used as foreground with a single base background" (which I feel is quite common). If bold, underline, and reverse `cterm` are allowed, then it can be a reasonably not bad looking UI by "emergency exit" standards.

I personally prefer option 1, but option 2 (with `termguicolors` and curated color scheme being default) is also fine for me.

**Comment by echasnovski** [comment]
> Why can't it look like that? I haven't changed my terminal ANSI colors. It should be possible for the 16-color variant to be close the the "reference colorscheme", except we may need to use magenta and yellow for infrequent tokens such as `Special`, etc.

It was mostly about palette. The background won't be `#1e1e1e`, but the one used for terminal; cyan won't be `#00ffff`, it will be 14, etc.

My idea is to directly use foreground colors in the same way as `gui` default color scheme (so will have "green-cyan-blue" feel), but tweak UI highlight group to use only terminal's foreground and background, and bold/reverse/underline attributes. And diffs to indeed have 0 as foreground color.  I've had some experiments and it looks... fine.

This way it will look like a less capable version of `gui` default color scheme, but truly an "emergency exit" variant with only 8 terminal colors.

**Comment by lewis6991** [comment]
I realised I forgot to include the default ANSI colors in the comparison. I'll add that next.

I agree that if this doesn't work for the default ANSI palette, then this isn't worth doing.

> This way it will look like a less capable version of gui default color scheme, but truly an "emergency exit" variant with only 8 terminal colors.

A truly "emergency exit" variant would just be black/white. I'm not sure we need to go that far. 16 colors seems reasonable to bottom-out at.

**Comment by echasnovski** [comment]
> The goal of the default theme change is to ship a Nvim-themed iconic colorscheme, by default, for the _majority_ of users (who are not tweaking ANSI colors...).

I am fairly positive that _majority_ of users do not use default colors that come with terminal. They do use some sort of theme (be it shipped with terminal emulator, hand made, tokyonight/catppuccin/gruvbox, etc.) because it is what is shown in the tutorials.

And for tweaked colors it is impossible to ship with any expectations because at least background can be very different (purple, pink, brown, etc.).

And different terminal emulators come with different default colors also.

------

Here are the screenshots of the current state of this PR (aa15f02f65d7a1e4cb2324790d7e68c25f33bcac) with stock colors of `st`:

<details><summary>Stock colors of `st` with 16 colors</summary>

screenshot_2023-12-05_17:18:01
screenshot_2023-12-05_17:18:08
screenshot_2023-12-05_17:18:38

With full integrity, I can not say that this is can be used comfortably.

</details>
 
------

> If it looks reasonable (screenshot?) with default terminal settings (default ANSI colors), then sure.

It looks the same as current, but with only background and foreground colors; no shades of grey.

<details><summary>My terminal emulator with 8 colors</summary>

screenshot_2023-12-05_17:35:27
screenshot_2023-12-05_17:35:30
screenshot_2023-12-05_17:35:51

</details>

<details><summary>Default `st` with 8 colors</summary>

screenshot_2023-12-05_17:33:23
screenshot_2023-12-05_17:33:27
screenshot_2023-12-05_17:33:54

</details>

The default blue is not really usable in `st`, but otherwise at least somewhat usable.

**Comment by lewis6991** [comment]
> And yellow, yes. This was to comply with the requirement of "be like reference for 256 colors, allow more shades for true colors".

I don't understand this requirement. What does "be like reference for 256 colors" mean? Is there anything wrong with using yellow for warnings in `notgc`?

**Comment by echasnovski** [comment]
> > And yellow, yes. This was to comply with the requirement of "be like reference for 256 colors, allow more shades for true colors".
> 
> I don't understand this requirement. What does "be like reference for 256 colors" mean? Is there anything wrong with using yellow for warnings in `notgc`?

This was the requirement from @justinmk on the previous (private) iteration of the default color scheme. Here is [the reference](https://github.com/neovim/neovim/issues/14790#issuecomment-927200052).

**Comment by lewis6991** [comment]
What is the requirement though? Why is yellow singled out in `notgc` vs `tgc`.

**Comment by echasnovski** [comment]
> What is the requirement though? Why is yellow singled out in `notgc` vs `tgc`.
> 
> As far as I can tell, the link doesn't mention this.

I've sent you an invite. You can browse the issues ("Roadmap" and "Snapshots" in particular).

**Comment by clason** [comment]
I think the only option that makes most people remotely happy (or at least everyone equally unhappy, which is usually the best we can hope for) is
1. Make `tgc` the default, with (conservative) fallback for unsupported terminals (see @gpanders suggestions)
2. Make `notgc` rely on 0-15 colors, with best-effort at branding and focus on readability (which I consider non-negotiable, including for diffs and visual/cursorline/search) on a standard set of colors (e.g., ANSI -- personal palettes don't count).

For 2., I would _strongly_ suggest starting fresh on this without reliance on (and exegesis of) previous constraints, since the situation has fundamentally changed with `notgc` no longer being the default experience.

**Comment by echasnovski** [comment]
> I think the only option that makes most people remotely happy (or at least everyone equally unhappy, which is usually the best we can hope for) is
> 
>     1. Make `tgc` the default, with (conservative) fallback for unsupported terminals (see @gpanders suggestions)
> 
>     2. Make `notgc` rely on 0-15 colors, with best-effort at branding and focus on readability (which I consider non-negotiable, including for diffs and visual/cursorline/search) on a standard set of colors (e.g., ANSI -- personal palettes don't count).
> 
> 
> For 2., I would _strongly_ suggest starting fresh on this without reliance on (and exegesis of) previous constraints, since the situation has fundamentally changed with `notgc` no longer being the default experience.

I agree. With emphasis on making `tgc` default and `notgc` variant be the best effort with only 0-15 colors optimized for readability and with constraint to look like `gui` variant. Right now my `notgc` variant uses only 8 colors and looks [like this](https://github.com/neovim/neovim/pull/26389#issuecomment-1841058581).

If all parties are ok with this, I can do it myself in the follow up PR for #26369. Which, hopefully, will be done after `termguicolors` becomes default on `master`.

**Comment by clason** [comment]
How do the bundled colorschemes (for example, quiet) look with `t_co=16`? A lot of work went into these at all(!) color levels, and we could do worse than crib from them.

(I don't think we can afford a colored background with terminal colors...)

**Comment by echasnovski** [comment]
> How do the bundled colorschemes (for example, quiet) look with `t_co=16`? A lot of work went into these at all(!) color levels, and we could do worse than crib from them.
> 
> (I don't think we can afford a colored background with terminal colors...)

[No cursor line](https://github.com/neovim/neovim/blob/ca4fe083e5b1a7c2e93cf77aa849fbec72757627/runtime/colors/quiet.vim#L357), [colored background for diffs with black foreground](https://github.com/neovim/neovim/blob/ca4fe083e5b1a7c2e93cf77aa849fbec72757627/runtime/colors/quiet.vim#L359-L362), [`cterm=reverse` for `Pmenu`](https://github.com/neovim/neovim/blob/ca4fe083e5b1a7c2e93cf77aa849fbec72757627/runtime/colors/quiet.vim#L369), [yellow background for `Visual`](https://github.com/neovim/neovim/blob/ca4fe083e5b1a7c2e93cf77aa849fbec72757627/runtime/colors/quiet.vim#L387). This is mostly what I suggest with 8 colors, but `cterm=reverse` for `Visual`.

**Comment by justinmk** [comment]
> but `cterm=reverse` for `Visual`.

reverse is often more trouble than it's worth. why can't we simplfy swap the Normal bg/fg? syntax highlighting is an antifeature for block highlights, which only a few colors are available.

**Comment by echasnovski** [comment]
> > but `cterm=reverse` for `Visual`.
> 
> reverse is often more trouble than it's worth. can we swap the Normal bg/fg? syntax highlighting is an antifeature for block highlights, when only a few colors are available.

That is, of course, possible, but would remove any highlighting inside visual selection. Indeed, if there are only 3 highlighted colors it might not worth much. I guess I'd *slightly* prefer `ctermfg=NONE ctermbg=NONE cterm=reverse` instead of `ctermfg=0 ctermbg=7 cterm=NONE` for `Visual`, but it is not a hard preference at all. Should I include the second one in the future work?

**Comment by echasnovski** [comment]
> > > but `cterm=reverse` for `Visual`.
> > 
> > 
> > reverse is often more trouble than it's worth. can we swap the Normal bg/fg? syntax highlighting is an antifeature for block highlights, when only a few colors are available.
> 
> That is, of course, possible, but would remove any highlighting inside visual selection. Indeed, if there are only 3 highlighted colors it might not worth much. I guess I'd _slightly_ prefer `ctermfg=NONE ctermbg=NONE cterm=reverse` instead of `ctermfg=0 ctermbg=7 cterm=NONE` for `Visual`, but it is not a hard preference at all. Should I include the second one in the future work?

One problem with the second approach would be is that it will be a visual language for `Pmenu`, floating windows and active statusline/tabline. So maybe having simple `cterm=reverse` is a good idea to balance things out?

**Comment by justinmk** [comment]
> One problem with the second approach would be that it will be a visual language for `Pmenu`, floating windows and active statusline/tabline.

I don't see that as a problem. `reverse` usually looks like shit.

**Comment by lewis6991** [comment]
Superseded by https://github.com/neovim/neovim/pull/26540

**Pull request closed without merging**
