### PR TITLE
feat(lsp): add omnifunc sync complete function

### PR DESCRIPTION
**Pull request by inventionate**
This is a first proposal of a synchronous omnifunc complete LSP function based on a longer discussion (#12390). It is also about drawing attention to the topic. The code is currently strongly oriented towards the asychronous implementation. There are many cases where a sync function would be useful. Improvements to the code are welcome.

### CODE REVIEW

**Comment by andreypopp** [comment]
Been using it for some time and it works great. Any plans to review and merge it?

**Comment by mjlbach** [comment]
I'm not sure I see the utility of adding a second (built-in) omnifunc, it duplicates code and then we have to explain the utility/pros/cons of the two implementations. There's no reason users can't copy/paste this into their config, why does it need to be in core?

**Comment by andreypopp** [comment]
> I'm not sure I see the utility of adding a second (built-in) omnifunc, it duplicates code and then we have to explain the utility/pros/cons of the two implementations. There's no reason users can't copy/paste this into their config, why does it need to be in core?

My opinion that this is a core piece of functionality and it belongs to core — this is an omnifunc (the core completion mechanism) interface to LSP (the core piece of neovim functionality now). Also omnicompletion was always sync and there are useful plugins (like mucomplete) which rely on that.

I actually think that the sync behaviour should be the default and async should be "opt in" as async completion often results in poor UX (jumping completion lists, flashing and so on). I can understand that others might not agree here though.

**Comment by mjlbach** [comment]
Yes, but it's a core piece of functionality that we already provide via the async version which AFAIK is allowed by omnifunc, if not compatible with mucomplete. If a user wants this behavior there is nothing stopping them from copy/pasting it as I said.

**Comment by inventionate** [comment]
I also think that the code needs to be refactored as a whole so that code duplication is avoided. As I said, I first wanted to place the topic, which emerged from an issue. I didn't want to change existing code directly, but I'm happy to make a sugg

Nevertheless, I think an integration is very important, in order to make a synchronous lsp omnifunc completion possible without additional config-code. Here I agree with @andreypopp and think that it is unsatisfactory to have only an async function implemented in core.

**Comment by andreypopp** [comment]
> Yes, but it's a core piece of functionality that we already provide via the async version which AFAIK is allowed by omnifunc, if not compatible with mucomplete. If a user wants this behavior there is nothing stopping them from copy/pasting it as I said.

Hm... I think omnicomplete works being async but I don't think this is 100% supported. But still — plugins built around omnicomplete expect it to be sync (mucomplete being a popular one, another one is https://github.com/ervandew/supertab). So the real question is — is this really worth breaking?

By the way, besides UX issues I've already mentioned there's another one which I think is related — the completions inserted with async omnifunc are not repeatable by `.` (fixed when I've started to use the version in this PR, though maybe it's fixable with async version somehow too?).

Some other (though I don't know how important) evidence — another popular LSP client ALE has omnifunc implemented in sync fashion as well to play well with plugins.

**Comment by mjlbach** [comment]
> Hm... I think omnicomplete works being async but I don't think this is 100% supported. But still — plugins built around omnicomplete expect it to be sync (mucomplete being a popular one, another one is https://github.com/ervandew/supertab). So the real question is — is this really worth breaking?

Is what really worth breaking? We added new functionality for the best experience in neovim, I don't see why consideration of supertab/mucomplete should be a factor here. As far as I am concerned there are better alternatives.

> Some other (though I don't know how important) evidence — another popular LSP client ALE has omnifunc implemented in sync fashion as well to play well with plugins.

I don't consider this important. The design considerations of ALE in this respect shouldn't apply to us, we have a very different design/architecture/language/capabilities matrix to consider.

Regardless, I thought about this more and I'm in favor of having *only* the synchronous omnifunc. I'll handle the PR myself though.

**Comment by shabbyrobe** [comment]
Just adding an experience report to this in case it is useful as the discussion here seems to be focusing on plugin compatibility issues now, but I'm having issues with a setup that uses no plugins other than nvim-lspconfig.

I arrived here by way of https://github.com/neovim/neovim/issues/15314 and https://github.com/neovim/neovim/issues/12390 as I'm experiencing the same issues with `completeopt` and `longest` as described in #15314, when using `gopls` via LSP. Copy/pasting the sync version into my config solves the acute problem for me and my preferred `completeopt` behaviour goes back to what I expect, but it all feels a bit creaky, like it'll fall over at a moment's notice and I'll be back to trying things from the documentation that don't do what they say on the tin (i.e. `longest`), and spelunking through git issues all over again.

**Comment by justinmk** [comment]
## Status/Resolution/Summary

- Use cases for synchronous LSP omnicomplete:
    - plugins (like mucomplete) rely on synchronous behavior
    - async behavior can be unexpected UX (no results and then user is confused and doesn't realize they need to try again later)
    - async UI can be poor: jumping completion lists, flickering
- Continued in https://github.com/neovim/neovim/pull/17218

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open an issue if you have new information/topics to discuss._

**Pull request closed without merging**
