### PR TITLE
lsp: move log to xdg_cache_dir

### LINKED ISSUE #13706: Store logs in XDG_CACHE_DIR rather than XDG_DATA_HOME
### Actual behaviour

The current output for logs is `~/.local/share/nvim/log` and the lsp logs is `~/.local/share/nvim/lsp.log`

###  Desired behaviour

We should probably log to `~/.cache/nvim/logs/lsp.log`

cc'ing @teto who brought this up. I can do this

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #13706

@teto

### CODE REVIEW

**Comment by clason** [comment]
Note that `.local/share/nvim/` is where neovim itself writes its log file. I'd be a bit weird to have some logs in one place and others in another?

Wouldn't it make sense to define a `stdpath('log')` first and use that?

**Comment by mjlbach** [comment]
I was thinking about that. I can make a PR

**Comment by clason** [comment]
Would have the benefit of being able to tell people on Gitter "look at the log, it's in `:echo stdpath('log')`" for anything ;)

**Comment by teto** [comment]
to be honest I have no idea why logs are in data, in my mind `stdpath('log') <=> stdpath('cache')` so I dont see the point in adding a new entry in stdpath. I am a bit short on time but would be interesting to find out why logs go to stdpath('data').

**Comment by clason** [comment]
@teto sorry, I didn't mean `stdpath('log')` quite literally; just document somewhere that logs should go in `stdpath('cache')` (or even `stdpath('cache')..'/logs'`).

**Comment by clason** [comment]
As to why `data` instead of `cache`: https://github.com/neovim/neovim/pull/12367#issuecomment-633052061

**Comment by mjlbach** [comment]
Closing in favor of the more expansive PR which add vim.fn.stdpath('log'), moves neovim's logs *and* lsp logs to a subdirectory of that https://github.com/neovim/neovim/pull/13739

**Pull request closed without merging**
