### PR TITLE
build(deps): bump tree-sitter to HEAD - 94a826211

### PR DESCRIPTION
**Pull request by clason**
Checking if the recent breaking changes are breaking for us @ribru17 @amaanq

### CODE REVIEW

**Comment by clason** [comment]
*Yuuup...*

**Comment by lewis6991** [comment]
Caused by https://github.com/tree-sitter/tree-sitter/pull/3703

**Comment by ribru17** [comment]
Functionaltest I can fix, not sure why doc test segfaults though. Will do more digging

**Comment by ribru17** [comment]
Doc test fails because of here: https://github.com/neovim/neovim/blob/master/scripts/gen_help_html.lua#L353. Can fix soon as well, on phone rn

**Comment by lewis6991** [comment]
The functionaltest isn't broken. Upstream is.

**Comment by ribru17** [comment]
Well upstream experienced a *breaking change*, but I wouldn't say it is broken per se. The change was breaking and downstream needs to be updated, this is expected. I have fixed functionaltest but I admit the segfault is going over my head... interestingly `nvim -l scripts/lintdoc.lua` runs perfectly? Wondering what this means in the grand scheme of things

**Comment by lewis6991** [comment]
>  The change was breaking and downstream needs to be updated, this is expected.

Yes, I contest with the breaking change and think it should be reverted.

The functionaltest was trivial to fix, but that's not the issue here.

**Comment by clason** [comment]
Looks like it's no longer breaking, but there's a bunch of API changes we should probably adapt to (after the 0.24 release and bump).

**Comment by ribru17** [comment]
I can put up a PR for this

**Comment by clason** [comment]
I'll merge this then as a release candidate so we can see if this survives in the wild.

**Pull request merged**
