### PR TITLE
refactor(lsp): remove deprecated lsp functions

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Comment by glepnir** [comment]
can we also remove the  deprecated functions which in  diagnostic.lua

**Comment by clason** [comment]
> can we also remove the deprecated functions which in diagnostic.lua

Should be a separate PR because it's a separate subsystem (@gpanders)

**Comment by mfussenegger** [comment]
> can we also remove the deprecated functions which in diagnostic.lua

You mean `_execute_scheduled_display` ? Sure, but this PR is about LSP

**Comment by glepnir** [comment]
> > can we also remove the deprecated functions which in diagnostic.lua
> 
> You mean `_execute_scheduled_display` ? Sure, but this PR is about LSP

yeah this function i make it deprecated.   

@clason okay

**Review by glepnir — APPROVED** [review]

**Pull request merged**
