### PR TITLE
Fix input handling for modified Esc and C-S- mappings

### PR DESCRIPTION
**Pull request by jamessan**

### CODE REVIEW

**Comment by jamessan** [comment]
@glacambre and @nkgm, can you try this branch and verify whether it resolves your issues?

**Comment by glacambre** [comment]
@jamessan Yep, solves my issue, thank you! I tried to fix this issue myself but couldn't get anything that worked - I'm a bit sad to see it was that simple :smile: .

**Comment by jamessan** [comment]
I haven't convinced myself yet that the third commit is the _right_ fix.  I need to look into that some more.

**Comment by nkgm** [comment]
Thanks for the quick fix @jamessan.

From a first look:
* `<S-Esc>` maps work
* `<C-S-x>` maps work
* Problem: Non `tmap`'d alphanumeric and punctuation keys with a native control character do not send the proper raw CSI u codes to neovim terminal in their +Shift form. For example (assume Control+V before each test): `Control+_` => `^_` and `Control+Shift+_` => `^_` **versus** `Control+=` => ` ^[[61;5u` and `Control+Shift+=` => `^[[43;5u`.

**Comment by jamessan** [comment]
Looks like 8.1.2145 and 8.2.1015 might be relevant.

**Comment by numirias** [comment]
Any plans to move forward with this? Not being able to map S- combinations separately seems quite significant and regularly comes up as a bug report on GUI implementations.

I have tested the PR myself (rebased on current master), and these combinations are now correctly recognized and can be mapped distinctly:
```
1. a
2. A (= <S-a>)
3. <C-a> (= <C-A>)
4. <M-a>
5. <C-S-a> (= <C-S-A>)
6. <M-S-a> (= <M-A>)
7. <M-C-a> (= <M-C-A>)
8. <M-C-S-a> (= <M-C-S-A>)
```
Additionally, it may make sense to add a paragraph about combined modifiers to the docs. It's currently stated that `a` in `<M-a>` is case-sensitive, and case-insensitive in `<C-a>`. But combinations are unclear, so, a user may not grasp why case matters in 6. but in 7. it doesn't.

**Pull request merged**
