### PR TITLE
build: gettext [skip ci]

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by clason** [comment]
For context:

(Neo)Vim uses
1. `gettext` for translated messages;
2. `libintl` for getting locales;
3. a single `HAVE_WORKING_LIBINTL` ifdef for both;
4. available `gettext` as a proxy for a working `libintl` (as the latter is a dependency of the former).

This is a problem since
1. `gettext` is optional (if you don't want translations) but
2. `libintl` is not (no locale information -> no encoding information -> inability to allocate message strings correctly).

So the goal is to disentangle the two by
1. making `libintl` a hard runtime dependency;
2. making sure our CMake scripts can find the system `libintl` (yes, even on macOS);
3. removing the guards around the functions requiring `libintl`;
4. replacing the `LIBINTL` guard for the translation functions by a `GETTEXT` guard.

**Comment by ychin** [comment]
I'm quite confused by what you wrote @clason, so just trying to clarify it here.

My understanding is that libintl = gettext, with "libintl" being the header/library name of gettext. I think under glibc (both gettext and glibc are GNU projects) comes with libintl automatically so you don't have to install gettext separately, but on macOS you *do* have to install gettext (e.g. `brew install gettext`) in order to get libintl. If you mandate its existence all your users will have to install gettext, as you won't find a libintl.h and libintl.dylib on macOS otherwise.

> `libintl` is not (no locale information -> no encoding information -> inability to allocate message strings correctly).

Isn't that done by `setlocale()` instead? That is not part of `libintl`. I believe it's part of standard libc.

**Comment by dundargoc** [comment]
I take personal responsibility for any wrong information here lol. I'm still confused on how all of is connected which was the reason for why I created the PR.

It seems that libintl is the library to gettext (aka libcurl to curl), although the terminology is thrown all over the place in neovim codebase.

My confusion likely stemmed from the fact that gettext (the cli program) is completely optional to create the translations while libintl/gettext library is "semi-optional" (i.e. some code is guarded with HAVE_WORKING_LIBINTL).

I don't think anyone knows how this works on mac lol. Part of the PR is to explore how we can simplify this.

Ideally I'd like a solution where we remove the HAVE_WORKING_LIBINTL hack by making the useful parts mandatory and remove the rest. How this will look I don't know at the moment.

**Comment by clason** [comment]
> I don't think anyone knows how this works on mac lol.

Weirdly. The header is part of the system, but the library itself is not and must be installed with `gettext`. On some Linux platforms, `libintl` is instead part of `glibc`.

In any case, the point here is to be clear what is required and for what -- even if `libintl` is distributed with `gettext` on some(!) platforms, it's still `libintl` that we need, not `gettext`.

**Comment by clason** [comment]
> My understanding is that libintl = gettext, with "libintl" being the header/library name of gettext. I think under glibc (both gettext and glibc are GNU projects) comes with libintl automatically so you don't have to install gettext separately

This directly contradicts "libintl == gettext", though, doesn't it?

> Isn't that done by setlocale() instead? That is not part of libintl. I believe it's part of standard libc.

Then it shouldn't be behind a `HAVE_WORKING_LIBINTL` guard. That's exactly my point. (If _nothing_ important turns out to need `libintl`, we don't have to make it required, of course. But the jury is still out on that.)

**Comment by bfredl** [comment]
yes, I made https://github.com/neovim/neovim/pull/25602 partially as a support for the ongoing discussion. The parts moved outside the #ifdefs in that PR is the code which should be kept regardless (it only depends on `setlocale()` which is mandatory on all platforms we support ). 

Then the remaining code inside should ideally not be ifdef:ed either, but that depends on if we want/are able to to require always have a working libintl, i e the _runtime_ component of gettext, regardless of how it is distributed. (Or in a hypothetical scenario where translation support would be dropped, that remaining code would be deleted.)

**Comment by ychin** [comment]
> This directly contradicts "libintl == gettext", though, doesn't it?

I think the other comment about libcurl vs curl is a good comparison. libintl is the runtime/library component of gettext. GNU just decided to include it as part of glibc, but have the command-line tools (in the `gettext` package) available separately. So it depends on what you mean by "gettext" in your sentence. Seems like it specifically refers to the "gettext package in GNU/Linux" here).

> Then the remaining code inside should ideally not be ifdef:ed either, but that depends on if we want/are able to to require always have a working libintl, i e the runtime component of gettext, regardless of how it is distributed. (Or in a hypothetical scenario where translation support would be dropped, that remaining code would be deleted.)

Vim (not Neovim as I'm not familiar enough with Neovim) still has "gettext" as an optional component as can be checked by the "+gettext" feature. That feature actually refers to libintl, as the end user won't really care about the gettext CLI tools (which are only used for building the translation files when building).

FWIW for MacVim, the binaries that we ship link against gettext's libintl statically since on macOS it's not bundled and I don't want users to have to install gettext (seems like none of the macOS software uses it and the system Vim does not have "+gettext" enabled). For building locally though, if you mandate libintl, the user will have to install gettext (probably through Homebrew).

One aspect you may want to keep in mind is also that not all Linux is GNU/Linux. Alpine ships with MUSL instead of glibc and I *think* (I don't actually use Alpine so I don't know) you need to install a separate musl-libintl dependency for it to work.

I have no idea how gettext works on Windows.

Either way, libintl is only used for translating message texts. It depends if you want to consider localized messages as a core requirement.

**Comment by clason** [comment]
But Neovim does not have optional compile time features like Vim. That is the whole point here.

**Comment by ychin** [comment]
Sure, but at compile time CMake is still looking for libintl.h and deciding to build with or without it right? Unless I'm misunderstand the context here.

**Comment by clason** [comment]
Yes, and this is precisely what this is about: deciding whether and how to change that.

**Comment by dundargoc** [comment]
We already bundle gettext for windows, I'm wondering if we should start doing it for mac too (and maybe even linux) to avoid these problems.

**Comment by clason** [comment]
> We already bundle gettext for windows, I'm wondering if we should start doing it for mac too (and maybe even linux) to avoid these problems.

Yes, that would be one possible outcome of this, if we decide a to make libgettext a runtime requirement.

**Comment by ychin** [comment]
> And Neovim GUIs are very different from Gvim, they don't use static binaries (VimR is a bit different, but this uses a forked libnvim, not a stock Neovim).

Right. I forgot Neovide etc just assumes an existing Neovim exists. VimR is the one that I look at the most but it's the odd one out in terms of configuration.

Honestly if you are only concerned about end-user dependency (compared to people who want to build Neovim locally), as I mentioned you can just link against gettext statically by linking against libintl.a on macOS, instead of the dynamic lib libintl.dylib. This will work without needing to bundle anything, and the resulting distribution size will be smaller as well because Vim only uses a very small portion of the library. gettext is LGPL, but I think it's kosher since Neovim is open-source anyway and a user can grab the source code and rebuild Neovim themselves.

Most people install Neovim via Homebrew anyway, and Homebrew already lists gettext as a dependency and therefore Homebrew Neovim has translations working.

On GNU/Linux you shouldn't need to bundle anything because glibc already supports it. It will be more complicated for MUSL.

**Comment by clason** [comment]
Again, this is not at all about how we build with the code we have (which we know how to do, thank you very much), but about _changing_ the code to minimize reliance on a(n optional) dependency (by getting rid of the `ifdef` spaghetti we inherited from Vim).

**Comment by ychin** [comment]
I see, that's fair enough. I was just curious about all these when I saw the issue.

**Comment by dundargoc** [comment]
Superseded by https://github.com/neovim/neovim/pull/25599

**Comment by dundargoc** [comment]
I don't think this can be solved without autotools, which is not an option. Closing.

**Pull request closed without merging**
