### PR TITLE
WIP Fix #11349 - Backups failing for symlink files

### LINKED ISSUE #11349: Setting backupdir with dirs that don't exist and linked files
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.0) behaves differently? Yes. It writes the backup to `/var/tmp` for a symlinked file
- Operating system/version: OS X 10.14.6
- Terminal name/version: iTerm2 3.3.6
- `$TERM`: `xterm-256color`

--------------------------------

Relates (I think) to #10101 (since it's about backups for symlinks).

Having `backupdir` set to a list of dirs where (in order of appearance) the first one does not exist, writing backups for symlink files will fail with `E506`.

When setting the `backupdir` option, the help indicates that it will attempt to create the backup file in the
> first directory in the list where this is possible

If one has this vimrc (only setting the backupdir):

```
set backupdir=~/.this-does-not-exist-tmp/,/var/tmp/
```

and the following files:

```
drwxr-xr-x  4 wspurgin  staff   128B Nov  7 10:17 .
drwxr-xr-x  7 wspurgin  staff   224B Nov  7 10:14 ..
lrwxr-xr-x  1 wspurgin  staff     7B Nov  7 10:14 bar.txt -> foo.txt
-rw-r--r--  1 wspurgin  staff    12B Nov  7 10:17 foo.txt
```

Attempt to edit `bar.txt` and then `:w` the file after it is open

### Actual behaviour

A `E506 Can't write backup file` error occurs when attempting to write `bar.txt`. Note, that if you swap the order of the directory list in `backupdir` (where a directory that exists appears first), there's no `E506`.

### Expected behaviour

I expect it to write the backup file to `/var/tmp` and not `E506`.

### PR DESCRIPTION
**Pull request by wspurgin**
Fixes #11349 

### Problem
Prior to #9709, we only when down the copy route if we could open the file, otherwise we would cycle through the backupdir options until/if we could. After that PR, we moved where the `break` was and if the first encountered backupdir + backup file option can't be written we fail and break out of the backupdir loop.

### Solution

Continue through the loop of backupdir options (still recording the error message if we can't copy), then clear out error messages if we finally succeed

### CODE REVIEW

**Comment by wspurgin** [comment]
Well this was passing prior to #11269 😅 promise. I think it has to do with the guards added for `if backup == NULL)` in that PR

**Comment by wspurgin** [comment]
Traivs failure looks unrelated? Failing in the `lang_spec` over `Locale sv_SE.UTF-8 not supported`? Not sure about that. As for the linting, I'll fix that as long as its okay to pull in the global helpers directly in to the test file.

However the appveyor is failing bc I added a assertion/expectation about the final contents of the symlink file..., but I remember vaguely that Windows has some weirdness around symlinks... probably okay that I remove those intermediary expectations right?

**Comment by wspurgin** [comment]
Any help digging into the "why" behind the travis & appveyor failures would be appreciated. I am very sub-par where Windows is concerned, and I can't duplicate the locale spec failure (nor have I comprehended yet how it relates to this PR) in travis.

**Comment by justinmk** [comment]
travis failure is a UBSAN failure (search the logs for "sanitizer"):

```
[32m[2m[ RUN      ][0m[0m fileio backup symlinked files in first avialable backupdir #11349: [2m34.32 ms[0m [1m[32mOK[0m[0m
==================== File /home/travis/build/neovim/neovim/build/log/ubsan.13780 ====================
= 
= =================================================================
= ==13780==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 48 byte(s) in 1 object(s) allocated from:
=     #0 0x4c5e63 in malloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
=     #1 0x1115d34 in try_malloc /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:71:15
=     #2 0x1115efc in xmalloc /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:105:15
=     #3 0xdcf982 in modname /home/travis/build/neovim/neovim/build/../src/nvim/fileio.c:4362:14
=     #4 0xdc0a68 in buf_write /home/travis/build/neovim/neovim/build/../src/nvim/fileio.c:2784:32
=     #5 0xb6fc68 in do_write /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds.c:1799:14
=     #6 0xb70144 in ex_write /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds.c:1655:11
=     #7 0xc2e39b in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2252:5
=     #8 0xc16f0e in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:621:20
=     #9 0xc1d213 in do_cmdline_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:295:10
=     #10 0x673e65 in nvim_command /home/travis/build/neovim/neovim/build/../src/nvim/api/vim.c:85:3
=     #11 0x58a1d4 in handle_nvim_command /home/travis/build/neovim/neovim/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:2765:3
=     #12 0x11e12da in request_event /home/travis/build/neovim/neovim/build/../src/nvim/msgpack_rpc/channel.c:382:19
=     #13 0xb31a1e in multiqueue_process_events /home/travis/build/neovim/neovim/build/../src/nvim/event/multiqueue.c:157:7
=     #14 0x129bc96 in nv_event /home/travis/build/neovim/neovim/build/../src/nvim/normal.c:8045:3
=     #15 0x124e519 in normal_execute /home/travis/build/neovim/neovim/build/../src/nvim/normal.c:1131:3
=     #16 0x18fac65 in state_enter /home/travis/build/neovim/neovim/build/../src/nvim/state.c:69:26
=     #17 0x1207159 in normal_enter /home/travis/build/neovim/neovim/build/../src/nvim/normal.c:463:3
=     #18 0xf86fe7 in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:577:3
=     #19 0x7fba8418a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
= 
= SUMMARY: AddressSanitizer: 48 byte(s) leaked in 1 allocation(s).
=====================================================================================================
[2mnan ms[0m test/helpers.lua:180: Found runtime errors in logfile(s): /home/travis/build/neovim/neovim/build/log/ubsan.13780

stack traceback:
	test/helpers.lua:180: in function 'check_logs'
	test/functional/helpers.lua:821: in function <test/functional/helpers.lua:817>
```

**Comment by justinmk** [comment]
> appveyor failures would be appreciated. I am very sub-par where Windows is concerned,

https://github.com/neovim/neovim/pull/11269#issuecomment-554854242 shows how to trick AppVeyor into showing hints :) Just compare the value using `eq()`, and the test failure will show the value.

**Comment by wspurgin** [comment]
@justinmk not sure if this is the problem, but libuv `uv_fs_copyfile` uses `CopyFile` on windows and that function is affected by whether the file is a symlink or not:

> If the source file is a symbolic link, the actual file copied is the target of the symbolic link.

>If the destination file already exists and is a symbolic link, the symbolic link is overwritten by the source file.

https://docs.microsoft.com/en-us/windows/win32/fileio/symbolic-link-effects-on-file-systems-functions#copyfile-and-copyfiletransacted

So I'm wondering if, by moving to using libuv's copyfile for backup in #8288 we inherented an issue with symlink copy-on-write? Basically I'm wondering if we aren't creating backups for symlniks bc the original file is actually the "link" to the copy-on-write? basically, with how libuv implements the copyfile for windows, I'm wondering if it inherently means that symlinks on windows wants a change to the original file before the "new path" (the backup in this usecase) is written.

**Comment by wspurgin** [comment]
Following this last test with Appveyor, I'm even more convinced that it has to do with symlinks behavior with `libuv`'s use of `CopyFile` on Windows. Is there are contributor that has deeper Windows knowledge that could help? I'm pretty fair out of my element wrt Windows. Other than the searching I've done, I'm not sure what else to do. This PR works for unix & os-x, but can is there a way for it to continue forward without Windows? Technically master is also failing for symlinked file backups on windows fwiw.

**Comment by janlazo** [comment]
Is this PR still blocked for Windows? Maybe it's fixed now after libuv was updated.

**Comment by wspurgin** [comment]
Hey! I'll check this weekend and bring this PR up-to-date. I'm also hopeful that the libuv update solved this issue.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/issues/11349#issuecomment-855379672

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/18659 and https://github.com/neovim/neovim/pull/18704

**Comment by wspurgin** [comment]
Oof I completely forgot about this... I just made my `dotfiles` init scripts just create the `~/.vim-tmp/` directory and moved on... I'm happy for #18704 to supersede. Last I recall the issue with this fix was that it _does not_ work on Windows.

**Comment by wspurgin** [comment]
If you want to reduce the places to go and look... you can open this PR back up @justinmk and I can take a stab at it again?

**Comment by wspurgin** [comment]
Ah nevermind I see the contributing says to just open a draft PR so I did that instead 😓

**Pull request closed without merging**
