### PR TITLE
[WIP] vim-patch:8.0.0725

### PR DESCRIPTION
**Pull request by gmelodie**
**Problem:**    A terminal window does not handle keyboard input.
**Solution:**   Add terminal_loop().  ":term bash -i" sort of works now.

### CODE REVIEW

**Comment by bfredl** [comment]
What is the problem we are trying to solve here? if it is `<c-w>` / `'termkey'`, then we would consider it NA. ( `tnoremap` can already be used to map any key in terminal mode).

**Comment by justinmk** [comment]
Added to https://github.com/neovim/neovim/pull/9875 as N/A.

@LTKills btw, #9835 was not merged yet..

**Comment by janlazo** [comment]
This patch is required for [vim-patch:8.0.1411](https://github.com/vim/vim/commit/2efb323e875d2852f63e41c40641760d1d6b069f).

**Comment by justinmk** [comment]
Ok.  @LTKills the `.patch` and `.orig` files should not be committed. Those are just for local use.

**Comment by janlazo** [comment]
Test from 8.0.1411 passes without the source code changes :|. If we don't need the terminal changes, then I can create a PR for both patches.

**Comment by justinmk** [comment]
> Test from 8.0.1411 passes without the source code changes :|. 

Maybe not with ASAN, though.

> If we don't need the terminal changes, then I can create a PR for both patches.

Ok. Don't need the terminal changes. [This change](https://github.com/neovim/neovim/pull/9879/files#diff-1eccf36b92bcbcf21463f2d430a5c650R39) also is irrelevant.

**Pull request closed without merging**
