### PR TITLE
[RDY] events: add new Signal event

### PR DESCRIPTION
**Pull request by mhinz**
..which gets triggered when SIGUSR1 is sent to the nvim process.

Closes https://github.com/neovim/neovim/issues/9562

### CODE REVIEW

**Comment by justinmk** [comment]
Seems reasonable to me. A small test would be useful to make sure the codepath is exercised in ASan etc.

There is also SIGUSR2, but should we reserve it for a debugging/development feature?

**Comment by mhinz** [comment]
> There is also SIGUSR2, but should we reserve it for a debugging/development feature?

I think one event for a manually triggered signal is enough. :]

**Comment by bfredl** [comment]
An option would be to name the event `Signal` or something, with `usr1` as the matched mattern. That would leave the field open for further signal autocmd usage in the future, without adding more separate events.

**Comment by mhinz** [comment]
Not sure if we should ever support any more signals. Is there any good use case for that?

If it was only me, I'd probably just call it `Signal` and trigger it only on SIGUSR1.

**Comment by KillTheMule** [comment]
Can't we pass arguments to even handlers? Maybe as vvars? Then it could just be called Signal and `v:signal` could be set to `SIGUSR1`. It trivial to use by not checking `v:signal` for now, but stays extensible that way (no, I don't have a usecase either :)).

**Comment by jamessan** [comment]
> The idea with pattern name is to just simply pass `"SIGUSR1"` or some abbreviation thereof as the second arg to `apply_autocmds` (and third? `CmdlineEnter` does both, so there is probably a reason).

I was going to suggest something similar, but putting the name/number in `v:event`.  However, since names are the only portable identifier, simply using that as the pattern is probably sufficient.

**Comment by mhinz** [comment]
That leaves the question.. is there a signal equivalent on Windows?

**Comment by bfredl** [comment]
No direct correspondence to SIGUSR1. Signals are used for lot less on winnt, essentially only termination. https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/signal?view=vs-2017

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
Tests should almost always be included in the same commit as the related feature/fix.

**Comment by mhinz** [comment]
Okay otherwise? I'll squash and merge via button. :]

**Pull request merged**
