### PR TITLE
[RFC] Reverted colon color code support

### LINKED ISSUE #7473: TUI: kitty: broken 'termguicolors'
- `nvim --version`: 0.2.1-dev
- Vim version:  8.0 ; behaves differently? **Yes.** 
- Operating system/version: Ubuntu 17.10
- Terminal name/version: [kitty](https://github.com/kovidgoyal/kitty/)
- `$TERM`: xterm-kitty

### Actual behaviour

Nvim borks when `termguicolors` is set. 
Vim on the left and nvim on the right. 

2017-11-01-173522_1366x768_scrot

### Expected behaviour
Neovim should display colors similar to vim.

I was told by @kovidgoyal at kovidgoyal/kitty#160 that neovim should be using semicolon as the delimiter instead of colon.

### PR DESCRIPTION
**Pull request by DarkDefender**
Should fix #7473

### CODE REVIEW

**Comment by justinmk** [comment]
Why was xterm-kitty even entering that codepath? Is `true_xterm` broken?

**Comment by DarkDefender** [comment]
I've been sick the past few days with high fever. We'll discuss this further when I get better

**Comment by DarkDefender** [comment]
Is it any point to continue with this discussion now that the kitty issue is closed?

**Comment by justinmk** [comment]
I'd prefer to power through with colon support.

**Pull request closed without merging**
