### PR TITLE
[RFC] syntax: don't process syntax in terminal windows

### LINKED ISSUE #2408: termopen() inside nvimrc returns E315: ml_get: invalid lnum: 41
Adding to my .nvimrc:

    nnoremap <C-t> :new | call termopen('bash') | startinsert

Returns a bug:

    E315: ml_get: invalid lnum: 41
    E315: ml_get: invalid lnum: 41
    E315: ml_get: invalid lnum: 41

Works ok when run from the command line.

### PR DESCRIPTION
**Pull request by splinterofchaos**
fixes #2408

### CODE REVIEW

**Comment by Pyrohh** [comment]
This fixes the issue for me, but will this prevent people writing syntax definitions for terminal buffers, or was that never possible? Am I insane for even suggesting such a thing :)

If it does prevent writing such definitions, it should probably be mentioned in `syntax.txt` and `nvim_terminal_emulator.txt`.

**Comment by ZyX-I** [comment]
@Pyrohh It was possible. More, it was suggested by somebody to extend terminal buffer with syntax highlighting for things like the output of `cat file.py`.

**Comment by splinterofchaos** [comment]
That makes me wonder why there isn't a `vim-cat` utility, though since color-aware programs and shells might compete for dominating colored output, and various shells could be configured to have unpredictable prompts. I don't see how a syntax file for terminals could be written.

I amended the commit with some weak references to the disabling of syntax highlighting.

**Comment by Pyrohh** [comment]
> That makes me wonder why there isn't a vim-cat utility, though since color-aware programs and shells might compete for dominating colored output, and various shells could be configured to have unpredictable prompts

Could you clarify on why you want `vim-cat`? Things like `ls --color` work fine, but I don't think that's what you're talking about.

> I don't see how a syntax file for terminals could be written.

Why not something like:

- `ls --color` inside `:terminal` works normally if no text matches the syntax definitions in use
- If a syntax definition(s) matches a piece of text in the terminal buffer, but the text is already highlighted, then strip said highlighting and apply the nvim specific highlighting.

**Comment by ZyX-I** [comment]
> That makes me wonder why there isn't a vim-cat utility, though since color-aware programs and shells might compete for dominating colored output, and various shells could be configured to have unpredictable prompts. I don't see how a syntax file for terminals could be written.

Terminal color takes precedence over syntax color (at least it did last time I tried). Syntax file for terminal could be written *very* easily if you accept that it is fine to let user tell the syntax file how the prompt looks like. You don’t need to predict all the prompts, you need to make it possible to alter your syntax rules by the person who know how the prompt looks like. It is just one configuration variable.

> Could you clarify on why you want vim-cat? Things like ls --color work fine, but I don't think that's what you're talking about.

I think he wants `pygmentize`, but with proper ftdetect feature (`pygmentize` itself only checks file name, not its contents like Vim does). (`pygmentize` is from pygments python highlighter package.)

**Comment by Pyrohh** [comment]
> I think he wants pygmentize, but with proper ftdetect feature (pygmentize itself only checks file name, not its contents like Vim does). (pygmentize is from pygments python highlighter package.)

Ah, that makes much more sense. Perhaps such a utility could:

- send the file contents it's about to print to nvim (maybe via a named pipe?)
- nvim would then detect the filetype and annotate the text accordingly with escape codes
- nvim would return the new text stream, which would then be printed out

I'm not sure if Nvim currently has the facilities to support this, but if it did then I'd imagine that `vim-cat` could be very short, maybe a few lines of shell script.

**Comment by splinterofchaos** [comment]
> Could you clarify on why you want vim-cat? 

The `pygmentize` + ftdetect + user settings, like @ZyX-I said.

> If a syntax definition(s) matches a piece of text in the terminal buffer, but the text is already surrounded by escape codes, then strip said highlighting and apply the nvim specific highlighting.

That sounds highly undesirable. If I'm unhappy with the way a program colors its text, hopefully it has options for me to fiddle with that. Otherwise, maybe there's an existing colorizor, like does exist for gcc's output. Lastly, I can parse and color the output myself. It just feels like there are better ways to accomplish this than have vim do it automagically.

> I'm not sure if Nvim currently has the facilities to support this, but if it did then I'd imagine that vim-cat could be very short, maybe a few lines of shell script.

Maybe--not sure. Right now, I'm imagining starting nvim with a flag like `--cat`, having it start up almost normally (initialize global state, including providers in case we externalize highlighting at any point, read the `.nvimrc`), but instead of starting the main loop, print one page, page down, print, repeat.

**Comment by ZyX-I** [comment]
> I'm not sure if Nvim currently has the facilities to support this, but if it did then I think that vim-cat could be very short, maybe a few lines of shell script.

NeoVim has more means for inter-process communication. But even with Vim you may use temporary files and my `formatvim` plugin to achieve this result:

```Shell
vim-cat() {
    local tempname="$(mktemp)"
    for arg ; do
        tempname="$tempname" screen -D -m -S vim-cat view -c 'Format format csi to $tempname' -c 'qall!' -- $arg
        cat $tempname
    done
}
```

Note: `formatvim` is pure VimL, I do not think it has any problems with NeoVim.

**Comment by Pyrohh** [comment]
> NeoVim has more means for inter-process communication. But even with Vim you may use temporary files and my formatvim plugin to achieve this result:

Very cool, but I wonder how this could be done in nvim. Perhaps an environment variable such as `NVIM_HIGHLIGHT_IN` could be defined for libvterm slaves, and `vim-cat` could be made to recognize such an environment variable. If the environment variable isn't found, then all arguments could be forwarded to regular `cat`, allowing users to `alias cat=vim-cat` if they wish.

**Comment by gleachkr** [comment]
It might be worth noting that there are some other possibilities that disabling syntax highlighting in terminal windows seems likely to kill. For example, right now it's possible to use neovim get syntax highlighting (and even things like rainbow parentheses---handy for lisp-family languages) in any REPL, or to get syntax highlighting on a man page with any pager you like (just set ft=man). With some tweaking, you could add something like the syntax highlighting that you can get in zsh and fish to your choice of shell. And there might be other use cases that just haven't been thought of yet.

**Comment by splinterofchaos** [comment]
> For example, right now it's possible to use neovim get syntax highlighting (and even things like rainbow parentheses---handy for lisp-family languages) in any REPL, or to get syntax highlighting on a man page with any pager you like (just set ft=man).

That's good motivation for me to second guess the merits of just disabling syntax highlighting in terminals (I thought those things just plain wouldn't work), but at the same time, the issue that inspired this PR is the use of a global static variable in `syntax.c`, `current_lnum`, which doesn't get updated properly when we switch to a terminal buffer and repeatedly calls `ml_get_buf()` with a line number higher than the number of lines in the buffer. This is really just a quick fix and I haven't studied the code well enough to find the proper solution, but we do need one...

**Comment by lazywei** [comment]
How is this going? Still get the error. ping @splinterofchaos

**Comment by splinterofchaos** [comment]
@lazywei Since keeping syntax highlighting in terminals actually does have some utility, I will probably close this PR after finding a better solution, but I haven't had the time yet. I'll be unable to work on this for the next few days, and have other PRs to finalize when I can, so if someone else thinks they can figure it out, it might go a little quicker.

**Comment by jalvesaq** [comment]
I added limited support for syntax highlight for some types of output in the [vimcmdline] plugin. The simplest use is to distinguish between negative and positive numbers, and numbers from text to allow a quicker reading of the output.

In my case, the syntax highlight is really useful for R output. I already use an R package that colorizes the R output, but if the `:term` command is going to work on Windows, their users will benefit from having syntax highlight.

[vimcmdline]: https://github.com/jalvesaq/vimcmdline

**Comment by Pyrohh** [comment]
Thanks for chiming in @jalvesaq. Well it seems like this solution isn't optimal, so I'll close it (please reopen this if you've changed your mind on what you said above @splinterofchaos).

**Pull request closed without merging**
