### PR TITLE
runtime/php: 1c6737b20a5cf71751b180461cea22fc76d8870c

### PR DESCRIPTION
**Pull request by TysonAndre**
Port php syntax file only.

Ref https://github.com/neovim/neovim/issues/12844

https://github.com/TysonAndre/php-vim-syntax/blob/master/examples/php80.php seemed to be highlighted as intended in an older version of neovim as well as a freshly built version using this branch. (e.g. `#[PHP80Attribute]`)
indent files didn't change significantly other than fixing a typo in a comment.

EDIT: Sorry, I'm guessing the build failures are unrelated, and caused by the mac os tests failing, cancelling the other checks?

### CODE REVIEW

**Comment by janlazo** [comment]
@TysonAndre Build failures are unrelated. It's happening in other PRs.

**Comment by chrisbra** [comment]
why have you changed the maintainer line?

**Comment by TysonAndre** [comment]
> why have you changed the maintainer line?

I'm the new maintainer in upstream vim.

This is identical to what's in https://github.com/vim/vim/blob/master/runtime/syntax/php.vim

**Comment by chrisbra** [comment]
ah, okay. I got confused because I thought this was a vim PR. Sorry.

**Comment by janlazo** [comment]
pCan you redo this PR similar to https://github.com/neovim/neovim/pull/13523? Each runtime commit corresponds to a vim commit if applicable.

```sh
$ ./scripts/vim-patch.sh -L -- 'runtime/syntax/php.vim'
5ef1c6a4838a9629b793f3ae676f72a764171b00
47e13953ffdbb9f163b901196dec8c2100b72edd
1c6737b20a5cf71751b180461cea22fc76d8870c
```

There should be 3 commits: each applying the same changes in `runtime/syntax/php.vim` as the vim commit.

**Comment by TysonAndre** [comment]
> There should be 3 commits: each applying the same changes in runtime/syntax/php.vim as the vim commit.

I'm not sure if I did this correctly - scripts/vim-patch.sh still lists the commits as unmerged

**Comment by TysonAndre** [comment]
I see that scripts/vim-patch.sh still reports that the patches that were applied to a file should be reapplied.

I'm assuming that vim-patch expects the commit titles to contain `vim-patch:commithash`, and both the js pr and the php one I based it off of don't contain that string
(vim-patch.sh executes `git -C /path/to/neovim log -E '--grep=vim-patch:[^ ,{]{7,}'`)

Is that expected, since the entire commit isn't being applied, just a single file from it?

```
» ./scripts/vim-patch.sh -l -- runtime/syntax/javascript.vim
Updating Vim sources: /path/to/neovim/.vim-src
Already up to date.
✔ Updated Vim sources.
Vim patches missing from Neovim:
  • 5be4ceecea5520265066eac972460ebb1cdf05e7: Update runtime files.
  • 388a5d4f20b4b64341d1604aa238cab85827b892: Update runtime files

Instructions:
  To port one of the above patches to Neovim, execute this script with the patch revision as argument and follow the instructions, e.g.
  'vim-patch.sh -p v8.0.1234', or 'vim-patch.sh -P v8.0.1234'

  NOTE: Please port the _oldest_ patch if you possibly can.
        You can use 'vim-patch.sh -l path/to/file' to see what patches are missing for a file.
```

**Comment by janlazo** [comment]
@TysonAndre That is intended. Using the `vim-patch:` token in a commit implies that the commit is a **full** port of the vim commit hash. It is difficult to fully port runtime patches so there is a different procedure for partial updates to `runtime/`.

**Review by janlazo — APPROVED** [review]
LGTM

**Pull request merged**
