### PR TITLE
[RFC] update luv and expose uv in nvim

### PR DESCRIPTION
**Pull request by zhaozg**
luv update is precondition of https://github.com/neovim/neovim/pull/9546

- [x] luv ready to update, wait for luv merge PR https://github.com/luvit/luv/pull/327.
- [x] nvim.uv is ready 
- [x] update luv build process

### CODE REVIEW

**Comment by zhaozg** [comment]
The next round will be passed to @andreypopp

**Comment by zhaozg** [comment]
Found bug in luv, so close.

**Comment by justinmk** [comment]
@zhaozg updating to the latest luv is itself quite useful, we are using a somewhat old version. Do you plan to re-open this later?

**Comment by andreypopp** [comment]
Is there more issues with luv than that of the losing lua state as I described in luvit/luv#329?

**Comment by zhaozg** [comment]
Yes, @andreypopp  says right, and I will reopen it after fix something.

**Pull request closed without merging**
