### PR TITLE
fix(codelens): add buffer and line checks before displaying codelens

### LINKED ISSUE #23885: Codelens refresh causes unending stacktrace when deleting a buffer before lenses are resolved
### Problem

When vim.lsp.codelens.refresh is invoked for a buffer, but the buffer is closed before the codelenses can be resolved i.e., the codelens is still in the `Unresolved codelens...`  state, an error is thrown as shown in the screenshot and on pressing `<enter>` the stacktrace just keeps popping up.

Screenshot 2023-06-02 at 1 55 28 PM

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
--- CHANGE THESE
local pattern = 'java'
local cmd = {'jdtls'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', 'mvnw', 'gradlew'}
-- Change to table with settings if required
local settings = {
    java = {
      signatureHelp = { enabled = true },
      contentProvider = { preferred = 'fernflower' },
      completion = {
        matchCase = 'FIRSTLETTER',
        guessMethodArguments = true,
        favoriteStaticMembers = {
          "org.hamcrest.MatcherAssert.assertThat",
          "org.hamcrest.Matchers.*",
          "org.hamcrest.CoreMatchers.*",
          "org.junit.jupiter.api.Assertions.*",
          "java.util.Objects.requireNonNull",
          "java.util.Objects.requireNonNullElse",
          "java.util.AbstractMap.SimpleEntry",
          "java.util.AbstractMap.SimpleImmutableEntry",
          "org.mockito.Mockito.*",
          "org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*",
          "org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*",
          "org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*",
          "org.springframework.test.web.servlet.result.MockMvcResultMatchers.*",
          "org.springframework.test.web.servlet.result.MockMvcResultMatchers.*",
        },
        importOrder = {
          "#",
          ""
        }
      },
      sources = {
        organizeImports = {
          starThreshold = 9999,
          staticStarThreshold = 9999,
        },
      },
      codeGeneration = {
        toString = {
          template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}"
        }
      },
      maven = {
        downloadSources = true,
        updateSnapshots = true
      },
      implementationsCodeLens = {
        enabled = true,
      },
      referencesCodeLens = {
        enabled = true,
      },
      references = {
        includeDecompiledSources = true,
      },
      inlayHints = {
        parameterNames = {
          enabled = true,
        },
      },
      format = {
        enabled = false,
      },
      configuration = {
        updateBuildConfiguration = "interactive"
      }
    }
  }

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'jdtls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

### Expected behavior

Expect no stack trace to be thrown on buffer delete before codelens refresh

### Neovim version (nvim -v)

NVIM v0.9.0

### Language server name/version

jdtls 1.23.0

### Operating system/version

macos big sur

### Log file

_No response_

### PR DESCRIPTION
**Pull request by rohit-s8**
fixes https://github.com/neovim/neovim/issues/23885

### CODE REVIEW

**Comment by glepnir** [comment]
this just avoid error through. did not solve the problem. need to deal with why the line out of range. some data need sync when buffer lines changed.

**Comment by rohit-s8** [comment]
@glepnir the sequence of events to reproduce to this problem is as follows:

vim.lsp.codelens.refresh() -> `Unresolved lens...` shows up in buffer -> :bdelete! before lenses resolve -> exception is thrown.

I assume this happens because the setting of codelens in a buffer occurs asynchronously and if the buffer is deleted before the codelens is retrieved from lsp, the callback will try to add codelenses to a non existent buffer, hence causing the exception.

I would like displaying of codelens to be non intrusive regardless of whether it succeeds/fails rather than have an exception thrown which interrupts my flow. So i just used pcall because it seemed enough. If codelens displays, then very good, otherwise silently ignore.

>some data need sync when buffer lines changed.
I am curious about this. Would be happy to do it the right way but need some guidance since I am new to this.

**Comment by glepnir** [comment]
since you use `bdelte` to delete a buffer when callback invoke the buffer is not valid , seems like need a buffer valid on callback . there already have a pr doing that #23894

**Comment by rohit-s8** [comment]
Unfortunately the PR https://github.com/neovim/neovim/pull/23894 did not solve this issue when I tried it out.

**Comment by glepnir** [comment]
that's so bad . I will try to reproduce it with your step

**Comment by lewis6991** [comment]
I think you also need `api.nvim_buf_is_loaded(bufnr)`

**Comment by rohit-s8** [comment]
@lewis6991 your suggestion worked :tada: 
The code within `codeLens/resolve` handler now looks like
```lua
      client.request('codeLens/resolve', lens, function(_, result)
        if api.nvim_buf_is_valid(bufnr) and api.nvim_buf_is_loaded(bufnr) then
          if result and result.command then
            lens.command = result.command
            -- Eager display to have some sort of incremental feedback
            -- Once all lenses got resolved there will be a full redraw for all lenses
            -- So that multiple lens per line are properly displayed
            api.nvim_buf_set_extmark(
              bufnr,
              ns,
              lens.range.start.line,
              0,
              { virt_text = { { lens.command.title, 'LspCodeLens' } }, hl_mode = 'combine' }
            )
          end
        end
        countdown()
```

Just curious about what should be done now. Should I update my PR with just the above changes or do these changes need to go along with @snowair's PR?

**Comment by justinmk** [comment]
I see that https://github.com/neovim/neovim/pull/23894 also modifies display(). 

@rohit-s8 given that https://github.com/neovim/neovim/pull/23894 has stalled maybe you can continue it here (note the comments in both)

**Comment by rohit-s8** [comment]
I have made changes similar to https://github.com/neovim/neovim/pull/23894 with the following differences:
* use` nvim_buf_is_loaded` instead of just `nvim_buf_is_valid`
* ensure the callback is called within resolve
* also add an additional check to account for an edge case where a codelens line may have been deleted before the resolve request handler is executed (very rare, but this did happen to me once).

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
