### PR TITLE
fix(get_literal): break the loop when the key has a modifier

### LINKED ISSUE #11468: "i_CTRL-v ALT-1 ALT-1 ALT-1" prints <M-o> instead of <M-1>
- `nvim --version`: NVIM v0.5.0-180-g222637c34
- Operating system/version: Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: Doesn't matter, also happens in GUIs
- `$TERM`: Doesn't matter, also happens in GUIs

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:call nvim_input("a<C-v><M-1><M-1><M-1>")
```

### Actual behaviour
`<M-o>` is inserted in the buffer.

### Expected behaviour
`<M-1>` is inserted in the buffer.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #11468

### CODE REVIEW

**Comment by zeertzjq** [comment]
Two of the tests I added fail on `master`:
```
[  ERROR   ] test/functional/editor/mode_insert_spec.lua @ 115: insert-mode Ctrl-V entering character by value is interrupted by invalid character
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(string) 'Lc<C-L><C-F2>πj<C-π><C-F2>😀j<C-😀><C-F2>'
Expected:
(string) 'LcL<C-F2>πjπ<C-F2>😀j😀<C-F2>'
```
```
[  ERROR   ] test/functional/editor/mode_insert_spec.lua @ 120: insert-mode Ctrl-V shows o, O, u, U, x, X, and digits with META/CMD modifiers
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(string) '<D-o><D-O>'
Expected:
(string) '<M-o><D-o><M-O><D-O>'
```

**Comment by bfredl** [comment]
Could this also happen in vim (so a patch there would be relevant) or is this a neovim regression? The orginial issue is not clear.

**Comment by zeertzjq** [comment]
Vim seems to merge some modifiers into the character, so that it becomes the different character, and in this case checking for `mod_mask` should be unnecessary. Vim also only supports `MOD_MASK_CMD` on macOS, so I cannot test that.

**Comment by zeertzjq** [comment]
Oh, the "reset mod_mask when i_CTRL-V_digit is interrupted" seems to be also applicable to Vim.

**Comment by zeertzjq** [comment]
I made a PR at Vim repository: <https://github.com/vim/vim/pull/9610>.

**Comment by zeertzjq** [comment]
I tested `MOD_MASK_CMD` in Vim by removing `#ifdef`s, and found out that the first one is also applicable to Vim for `MOD_MASK_CMD`.

**Comment by zeertzjq** [comment]
Superseded by #17191

**Pull request closed without merging**
