### PR TITLE
ci: AppVeyor: fix cov job, remove duplicate non-cov one

### PR DESCRIPTION
**Pull request by blueyed**
Taken out of https://github.com/neovim/neovim/pull/10198 - coverage might not be good yet, but at least does not fail anymore.  This also allows to remove one of the jobs.

[skip travis]

### CODE REVIEW

**Comment by justinmk** [comment]
> Taken out of #10198 - coverage might not be good yet, but at least does not fail anymore

What do you mean exactly? If coverage is less than 70-80% then this doesn't fix anything, it's sending an empty file.

**Comment by blueyed** [comment]
I've noticed with #10198 that we do not have coverage with both test runs, but thought this should not hold this fix back.

**Comment by blueyed** [comment]
The test run (functionaltests) with coverage is affected by:

> ./buffer.c.gcno:version 'A82*', prefer 'A73*'

This is due to using another gcov than the one used for building (I assume).

The second test run reports/generates no coverage in the first place.

This is something to iron out in #10198 then.

**Comment by justinmk** [comment]
Not sure what that means. Does this fix something or not?

**Comment by blueyed** [comment]
It fixes the MINGW_64-gcov job.  It should be removed from allowed-failues then (which I just did).
By using GCOV_ERROR_FILE the errors due to missing locking support are not spilled into test output anymore, causing failure there.

**Review by justinmk — APPROVED** [review]
LGTM assuming this doesn't send an empty results file to codecov which then pollutes the results.

**Pull request merged**
