### PR TITLE
fix(lsp): do not hardcode version in spec links

### PR DESCRIPTION
**Pull request by MariaSolOs**
The LSP website will redirect these to the current version of the spec.

### CODE REVIEW

**Review by justinmk — APPROVED** [review]
Thank you! This was bugging me :) Others tend to copy what came before so this will be helpful in the future too.

**Comment by mfussenegger** [comment]
I thought the idea behind using the versioned links is to make it clear that that's the reference point we used when we implemented a particular function. (I'm not opposed to the change, just to add some context)

**Comment by MariaSolOs** [comment]
> I thought the idea behind using the versioned links is to make it clear that that's the reference point we used when we implemented a particular function. (I'm not opposed to the change, just to add some context)

That's fair. However I think that at least the user-facing links should point to the latest version of the specs for better documentation (and I hope we don't let the respective implementations far significantly behind that).

**Comment by mfussenegger** [comment]
> I'm okay with reverting the change and more carefully filtering out the changed links BTW.

No need, I'm fine with the change, just wanted to add some context in line with [Chesterton's fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence)

**Comment by MariaSolOs** [comment]
> No need, I'm fine with the change, just wanted to add some context in line with [Chesterton's fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence)

I’ll make sure to check in the future.

**Pull request merged**
