### PR TITLE
[RFC] External ui

### PR DESCRIPTION
**Pull request by dzhou121**
This pull request is inspired by the external popupmenu and try to address the same approach for windows.  

This patch will make neovim to treat each window individually and will output cmdline, tab, wildmenu to API without drawing them. 

It will only have effect when win_external is set by API so tui is still working in the old way. 

The achieved result is shown in this screencast:
https://youtu.be/rzclz1seo0g

### CODE REVIEW

**Comment by justinmk** [comment]
> will output cmdline, tab, wildmenu to API without drawing them.

Nice. Should there be a different `foo_exernal` flag for each of them? Currently there's only `win_external`. @bfredl do you think we should continue to have "granular" opt-in externalized widgets?

@dzhou121 Do you plan to add tests?

**Comment by bfredl** [comment]
Very interesting! I will need to take a deeper look into this, for instance how does this integrate with window `^W` commands?

But at a quick glance, It looks like we could have a separate `cmd_msg_external` that makes messages and command line (including wildmode) external without enabling separate windows. (it will only free the last row in the grid _as if_ `cmdheight=0`). `win_external` will then simply imply `cmd_msg_external`.

**Comment by dzhou121** [comment]
@justinmk @bfredl 

This patch's aim is to external everything that makes sense to be externalised. So probably win_external should be changed to ui_external.

Re window ^W commands, it still let neovim to handle window layout management. But the external API will know the windows' sizes, positions, etc. So the most direct benefit is the line between vertical splits.

**Comment by justinmk** [comment]
There's still the minor question: do we want to allow UIs to opt-in to externalizing only certain pieces? If we put everything behind a single `ui_external` flag then that means UIs must implement *all* externalized widgets instead of only some. If it makes the code/logic significantly simpler then I would lean towards "no granularity". But if it's low-cost to provide granularity then it might be worth doing so. cc  @rhysd @qvacua @rogual @carlosdcastillo

**Comment by teto** [comment]
very cool ! I vote for granularity since it should be simple to provide (bitfield like) while adding a convenience: easier to provide a WIP UI, if some widget is buggy, the dev can disable it in favor of the native etc...

**Comment by qvacua** [comment]
I agree with @teto. The external popup menu does not have a very high priority for me and it'd be nice if it'd be an opt-in such that the "text"-based popup menus would continue to work.

**Comment by chemzqm** [comment]
I do think it's better to just have a single `ui_external` flag, so that the GUI author could make sure to build a consist UI , instead of part of them, which would be confusing for the user, and also affect building the theme for GUI.

I also think the previewWindow should be ui_external, it would useful to avoid redraw when completing.

**Comment by dzhou121** [comment]
I've added floating windows support. And preview-window can be an opt in. You can make it floating or still let Neovim to handle the window layout for it. 

But when you external window layout, you imply external cmdline, tabline as well, because the screen rendering happens at window level. So there's no "screen" for cmdline, tabline any more.

**Comment by dzhou121** [comment]
https://www.youtube.com/watch?v=UgS-B12E0ps

This screencast demonstrates the floating windows capability:

The error information of the syntax is displayed in a floating preview-window and positioned at the cursor by the GUI.

The FZF plugin is using the floating window that can be centered by the GUI.

**Comment by teto** [comment]
The floating window support seems very interesting, While I don't think it can help the Window Manager handle windows instead of nvim (https://github.com/neovim/neovim/issues/2161), I wonder if it could be used to provide UI-enhanced quickfix/location lists as displayed in https://a.fsdn.com/con/app/proj/texstudio/screenshots/errorHighlighting.png . I would love to have a button to toggle warning messages (I have a QFGrep mapping for that but sometimes buttons are a nice to have as well)?

**Comment by dzhou121** [comment]
@teto 

We could have a new wincmd command that can cycle through all floating windows. Something like

wincmd fnext

**Comment by teto** [comment]
As you seem pretty fired up, I wonder if your UI display vim "menus" in any special way ? 
I think that :emenu completion relies on wildmode so if you support wildmode that should cover it (I find the vim-menus quite useful to run rare commands I am sure to forget, yet it's not popular with plugins :/).

To reproduce your screencast, is using https://github.com/dzhou121/envim with this PR enough ?

**Comment by dzhou121** [comment]
@teto

Yes :emenu seems to be working through wildmenu

The screencast was using https://github.com/dzhou121/envim

**Comment by dzhou121** [comment]
A screenshot for externalising statusline

**Comment by teto** [comment]
Have you already thought about column drawing  externalization (line number/folds/signs) ?
I have started working on TUI improvements related on that but for smart UI design, I wonder if neovim experts would envision some more radical changes like using extmarks to advertise the folds ?

**Comment by dzhou121** [comment]
Yes I did. But when you externalise column drawing, how would you deal with the space of the column in neovim? Either externalise the whole windows layout management or still reserve the space but doesn't draw anything there.

**Comment by teto** [comment]
First of all, I believe an UI should be able to choose which columns (line number/folds/marks) to externalize for the same reasons I mentioned earlier (makes addition of UI features more incremental).

If line number drawing is externalized, then how to retrieve the line number display ? the logic can be complex between the different "set number"/"set relativenumber" configurations. Should nvim compute & communicate the result to the UI ? or should the UI duplicate the logic to compute the line display (or access the function via a neovim library ?) ?

At first I thought column externalization would be as simple as skipping the code in screen.c that draw the specific column(s) but it's not possible if neovim wants to handle several UIs with different column externalization preferences. Either neovim should send the characters with some metadata to let the UI decide to skip it or the UI should be able to retrieve the data via another channel (extmarks to get folds for instance ?).
I believe the tiebreaker would be the TUI as it is the most annoying as far as drawing is concerned but I don't know enough to propose an explicit architecture yet.

Ps: I wonder how you envision the future (merging) of this PR ? cherrypicking parts as separate PRs ? Externalizing commandline could be merged quite easily while the floating windows could be a headache IMHO ?

**Comment by dzhou121** [comment]
With the windows externalised, we can include the column width information. Without changing column rendering code, the external UI will know that which part of the window is the column.

Regarding merging this PR, what is the best approach for me?  I've been using this in my daily work and it works pretty well.

**Comment by acornejo** [comment]
I am also curious as to what are the required steps to get this merged. It seems a pitty not to let others enjoy dzhou's work.

**Comment by timeyyy** [comment]
@justinmk How can we make this easier for reviewers to digest? Do we want a p/r per externalized feature?

Following the pattern of #https://github.com/neovim/neovim/pull/4432 might be worthwhile.
commits like 
```
api/ui exteranlize x
api/ui: add tests for externalizing x
api/ui: add documentation for externalizing x
```
I don't think master is so stable so maybe rebasing onto e7de3b5 for the time being

**Comment by justinmk** [comment]
Keeping this rebased on master would be really helpful.  @dzhou121 do you plan to write tests for this?

**Comment by dzhou121** [comment]
@justinmk 

I'll write tests once I know how should I proceed. Do I split the features into multiple PRs or still keep them in this one PR?

**Comment by justinmk** [comment]
@dzhou121 If you can split the features that would be extremely helpful, and will allow us to proceed much more quickly.

**Comment by teto** [comment]
For what is worth, I would vote to externalize command line first as there are some work on providing a sublime-like palette and the 2 combined together would be very cool.

I had a look at the code and dropping the global variables `ScreenLines` etc might lead to an easier refactoring of the monstreous `win_line` function.

**Comment by dzhou121** [comment]
Just submitted a new PR #6162 for cmdline_external

**Comment by dzhou121** [comment]
PR #6168 for wildmenu_external

**Comment by dzhou121** [comment]
PR #6170 for cmdline_external

**Comment by autozimu** [comment]
> PR #6170 for cmdline_external

There seems to be a typo here. Maybe tabline_external?

**Comment by dzhou121** [comment]
@autozimu Thanks for the note. Have edited it.

**Comment by justinmk** [comment]
I believe everything here except floating windows (#6619) has been merged to master. @dzhou121 if there's any thing else here can you extract it to a new PR?

**Comment by bfredl** [comment]
There is still externalizing echo and error messages. It will be needed before external window layout.

**Comment by chandlerc** [comment]
Is anyone continuing to work on this?

**Comment by teto** [comment]
@chandlerc yes some developers are working on this as can be read in the linked PRs

**Comment by bfredl** [comment]
See also #8455 for per-window grids (which also will go a bit further than this, and let clients handle all wincmd:s if they want to)

**Comment by bfredl** [comment]
Thanks @dzhou121 for this substantial contribution. Large parts have been merged and benefited many GUI projects already:

- ext_cmdline  #6162
- ext_wildmenu  #6168
- ext_tabline #6170 

Other parts are continued to be developed in ongoing PRs

- floating windows #6619 
- external messages #7466 

We chose to implement per-window grids using a slightly different approach, as a 2018 GSOC project (#8455). However this PR was first to prototype the idea, and demonstrated that it was feasible with reasonable efforts. 

Closing this. For further general discussion of UI extensions, see #9421.

**Pull request closed without merging**
