### PR TITLE
fix(lsp): expose ContentModified error code to callbacks

### PR DESCRIPTION
**Pull request by rish987**
Currently LSP RPC clears the callback on `ContentModified` error code, considering this "RPC internal". We would like to argue that this isn't completely the case, as the [LSP specification claims that "clients can resend the request if they know how to"](https://microsoft.github.io/language-server-protocol/specification#implementationConsiderations). It's currently being used by the [Lean 4 VSCode extension](https://github.com/leanprover-community/vscode-lean4/blob/d5f1926be34e73af23d551be779a5b98e721e0ba/lean4-infoview/src/infoview/info.tsx#L246), which we're trying to replicate over at Julian/lean.nvim#108.

Also, let me know if these tests look alright!

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]
Makes sense to me. 

@mjlbach or @tjdevries do you know if there were issues in the past that led to the special treatment of ContentModified?

**Comment by rish987** [comment]
(made tests a bit more synchronous)

**Comment by mjlbach** [comment]
No, this predates my involvement. I don't see any issue with the PR, but since this touches a fairly core aspect I'd want @tjdevries's opinion since I think this would have been his doing (or norcalli's/h-michael's)

**Comment by mfussenegger** [comment]
If there is no further input I'd go ahead and merge this. If it causes issues we can still reconsider before it gets released.

**Comment by mjlbach** [comment]
Linux lint is failing

**Comment by rish987** [comment]
@mfussenegger That would be great, thank you! @mjlbach It looks like a clint failure to me? This only touches lua, so it was probably preexisting at the time I made this PR.

**Comment by mjlbach** [comment]
Lualint runs as part of linux lint, just noting it :)

**Pull request merged**
