### PR TITLE
[RDY] vim-patch:8.0.0134

### PR DESCRIPTION
**Pull request by ckelsel**
Problem:    Null pointer access reported by UBsan.
Solution:   Check curwin->w_buffer is not NULL. (Yegappan Lakshmanan)

https://github.com/vim/vim/commit/c4bfedabe057c05f09a455a5851089e177fa9c00

**src/nvim/ex_cmds.c have been merged by someone. while version.c remain unmerged.**

### CODE REVIEW

**Comment by justinmk** [comment]
> src/nvim/ex_cmds.c have been merged by someone. while version.c remain unmerged.

Well,  ZyX noticed the bug and just fixed it.

Can you resolve the conflict?

**Comment by ckelsel** [comment]
fixed,

**Comment by sassanh** [comment]
Actually @tarruda fixed it long ago:
https://github.com/neovim/neovim/commit/f6ace9962d95eb12236083871154c1501f02c556#diff-64502d25491840f7291ee96e905111c1
"Fix errors reported by the undefined behavior sanitizer"

**Comment by sassanh** [comment]
ZyX just linted it.

**Pull request merged**
