### PR TITLE
make all *.h linguist-language as C file

### PR DESCRIPTION
**Pull request by zhaozg**
Make github linguist think *.h  as C file

### CODE REVIEW

**Comment by blueyed** [comment]
What does this do?

**Comment by zhaozg** [comment]
image
github think some c header files as C++ or Objective-C

**Comment by blueyed** [comment]
I see..  looks more like an issue with their detection code then, doesn't it?
I am not sure we should have this just to work around this - assuming that it could be detected properly.
Is there documentation that you should / can do it like that?

**Comment by zhaozg** [comment]
@blueyed https://github.com/github/linguist#overrides

**Pull request merged**
