### PR TITLE
vim-patch:7.4.1477

### PR DESCRIPTION
**Pull request by prollings**
Problem:    Test_reltime is flaky, it depends on timing.
Solution:   When it fails run it a second time.

https://github.com/vim/vim/commit/b5760a1ce5b700fc32b8bd11948ee189a847c59e

### CODE REVIEW

**Comment by KillTheMule** [comment]
This is not needed, we converted `Test_reltime` to https://github.com/neovim/neovim/blob/871fc6c1e17bc1fc1b3a937ff481aca1f0aeff43/test/functional/eval/reltime_spec.lua which would not be affected. As you can see, I dealt with the flakiness by increasing the margin of error, which so far has not shown false positives as far as I can see.

Ping @justinmk would you want to implement re-running that test instead of the increased margin? I'd say we're good for now, it's your call though :)

**Comment by justinmk** [comment]
I definitely think re-running is something that will be useful for some tests. 

> increasing the margin of error, which so far has not shown false positives as far as I can see.

The margin of error is huge, so it will never fail I think :>

**Comment by KillTheMule** [comment]
> The margin of error is huge, so it will never fail I think :>

Seems like it, but using 0.3 instead of 0.1 did not prevent false positives when I tried. Travis is really slow ^^

I myself wouldn't know how to implement re-running a test (other than doing it in the lua code for it), so maybe you could give a hint for prollings.

**Comment by prollings** [comment]
If the test actually tests (ie. can fail), doesn't this patch provide the code to do the retest? Or must it be ported to Lua?

**Comment by justinmk** [comment]
@prollings This patch is still needed for maybe future non-lua tests, but in the specific case of `Test_reltime`, it's not needed (and we need to maybe update the reltime lua test to retry itself, if possible). So just change the line to:

    let s:flaky = []

**Pull request merged**
