### PR TITLE
[RFC] doc/develop.txt pruning

### PR DESCRIPTION
**Pull request by ghost**
I'd like to eventually deal with #2446, but for now this text just serves to confuse, so remove it.
develop.txt as a whole is still quite outdated, but I'm trying to keep the PRs small for ease of review.

### CODE REVIEW

**Comment by mhinz** [comment]
:+1:

**Comment by Pyrohh** [comment]
Does :+1: mean the same as LGTM? I'm not up to date on the lingo, yo.

(I'll wait a few days before merging, I'm just curious what you mean).

**Comment by fmoralesc** [comment]
> Does :+1: mean the same as LGTM? 

:+1:

btw, :+1: 

Are you planning on restoring a coding style guide somewhere in the documentation? It seems like a good idea to have one offline (not that I have ever used it, as you know very well... :p )

**Comment by mhinz** [comment]
> Does :+1: mean the same as LGTM?

Yes. :)

**Comment by Pyrohh** [comment]
> Yes. :)

:+1: 

> Are you planning on restoring a coding style guide somewhere in the documentation? It seems like a good idea to have one offline (not that I have ever used it, as you know very well... :p )

I think so, eventually at least. I'd rather focus on cleaning up stuff for now, as we still have a few completely outdated files.

**Pull request merged**
