### PR TITLE
cmake: only include CPack for AppVeyor builds

### PR DESCRIPTION
**Pull request by blueyed**
This uses an internal `BUILD_CPACK` variable to only include CPack [1]
on AppVeyor.

1: https://cmake.org/cmake/help/latest/module/CPack.html

### CODE REVIEW

**Comment by blueyed** [comment]
@justinmk 
It looks like it's only used there, and helps with avoiding overhead in general.

**Comment by justinmk** [comment]
What overhead?

**Comment by blueyed** [comment]
Does not make much of a difference with disk caches, but saves a bit without.

New:
```
% timeit-shell sh -c 'rm build -rf; echo 3 | sudo tee /proc/sys/vm/drop_caches; make cmake'                                          ⟳(c) ⟳(m) 🐍? (neovim@3.7.4)
1 loop -> 7.06 secs

raw times: 7.14 sec, 7.06 sec, 7.35 sec, 7.11 sec, 7.41 sec

1 loop, best of 5: 7.06 sec per loop
timeit-shell sh -c   29.32s user 9.17s system 89% cpu 43.240 total
```

Old:
```
1 loop -> 7.29 secs

raw times: 7.29 sec, 7.11 sec, 7.25 sec, 7.22 sec, 7.22 sec

1 loop, best of 5: 7.11 sec per loop
timeit-shell sh -c   29.40s user 9.43s system 89% cpu 43.477 total
```

The difference in the resulting build is only the files that ninja looks at for
re-running CMake, but the CPack module itself is not small, and therefore adds
overhead.

Sure, the fastest loops are quite the same 7.06s vs 7.11s.

I've expected it to make a bit more of a difference.

Still, it makes it clear where we use CPack after all.

Feel free to close it.

**Comment by blueyed** [comment]
Closing for now.

**Comment by justinmk** [comment]
Why wouldn't we use cpack on more platforms? Would rather avoid another special case meanwhile.

**Comment by blueyed** [comment]
> Why wouldn't we use cpack on more platforms?

We can.  But then `BUILD_CPACK` / `USE_PACK` would need to be passed.

It's not about special-casing, but only building/configuring things that are used.

**Comment by justinmk** [comment]
> become a real/documented option then.

That is a special case. We already have 30+ build options (special cases, hacks), we should avoid adding more, especially for micro optimizations.

**Pull request closed without merging**
