### PR TITLE
[RFC] input.c: restore double click

### PR DESCRIPTION
**Pull request by sach1t**
Let there be double click :)

(the implementation is very similar to vim... don't process the release events)

### CODE REVIEW

**Comment by sach1t** [comment]
Fixes issue #4887

**Comment by sach1t** [comment]
This was committed under the wrong credentials. I will open a new pull request in a bit.

**Comment by justinmk** [comment]
@sach1t There's no way to delete AFAIK.

**Comment by fwalch** [comment]
Force-pushing to the branch should remove/overwrite the previous commits, I think.

**Comment by sach1t** [comment]
@justinmk and @fwalch No problem and thanks so much for the help. 
I will open a new pull request for this either tonight or tomorrow.

**Pull request closed without merging**
