### PR TITLE
fix(lsp): retrigger diagnostics request on server cancellation

### LINKED ISSUE #30985: LSP: rust_analyzer: -32802: server cancelled the request
### Problem

editor is being interrupted with message `rust_analyzer: -32802: server cancelled the request` while typing on every keystroke after the latest updates of rust-analyzer

### Steps to reproduce using "nvim -u minimal_init.lua"

Just start typing in `main.rs` inside `fn main() {|}` of `cargo new --bin test_project`

```lua
local pattern = 'rust'
local cmd = { '/opt/homebrew/bin/rust-analyzer' }
-- Add files/folders here that indicate the root of a project
local root_markers = { 'Cargo.toml' }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
    pattern = pattern,
    callback = function(args)
        local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
        local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
        vim.lsp.start({
            name = 'rust-analyzer',
            cmd = cmd,
            root_dir = root_dir,
            settings = settings
        })
    end
})
```

### Expected behavior

There is no this message with interrupt

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Language server name/version

rust-analyzer 0.0.0 (3b3a87fe9 2024-10-27)

### Operating system/version

macos 15.1

### Log file

_No response_

### PR DESCRIPTION
**Pull request by gpanders**
Resolves: https://github.com/neovim/neovim/issues/30985

Continuation of https://github.com/neovim/neovim/pull/30999 (credit to @Jesse-Bakker for most of the implementation).

### CODE REVIEW

**Comment by mfussenegger** [comment]
See https://github.com/neovim/neovim/pull/30999#issuecomment-2448300472 I think the re-triggering aspect should be handled too - which might imply that the error needs to be surfaced to the request handler(?)

And having a test case would be great

**Review by mfussenegger — APPROVED** [review]
I think the test case might be easier to read if using the `create_server_definition` approach, but either way is fine.

**Comment by emmanueltouzery** [comment]
I can't find evidence that this was backported to 0.10.x. I believe it should be, as rust is a popular language and its lsp is more or less unusable without this fix. I don't know how risky or not this change is, though.

**Comment by gpanders** [comment]
Backport: https://github.com/neovim/neovim/pull/31427

**Pull request merged**
