### PR TITLE
perf(lua): avoid spairs in vim.validate happy path

### PR DESCRIPTION
**Pull request by lewis6991**
Problem:

`vim.validate` is too slow, mainly because of `vim.spairs`.

Solution:

Collect all errors in via `pairs`, and sort the errors via `spairs`.

### CODE REVIEW

**Comment by lewis6991** [comment]
I have no data on this yet.

**Review by justinmk — APPROVED** [review]
great idea. technically this means we could report the full list of errors instead of only the first one, but that should probably wait until later

**Comment by louisroymond91** [comment]
Sir I’m sorry why are you so agreeing

**Comment by lewis6991** [comment]
Benchmarking this is a little tricky, but from what I can tell this is about 3x faster with my config.

**Pull request merged**
