### PR TITLE
feat(nvim_create_user_command): pass structured modifiers to commands

### PR DESCRIPTION
**Pull request by famiu**
Adds an `smods` key to `nvim_create_user_command` Lua command callbacks,
which has command modifiers but in a structured format. This removes the
need to manually parse command modifiers. It also reduces friction in
using `nvim_cmd` inside a Lua command callback.

### CODE REVIEW

**Comment by clason** [comment]
Bikeshed: `f-mods` in analogy to `f-args` (which are "function arguments", as in "to be used in functions")?

**Comment by famiu** [comment]
> Bikeshed: `f-mods` in analogy to `f-args` (which are "function arguments", as in "to be used in functions")?

that's because in Vim script you need to split arguments with commas to use them as function arguments. Eg:
```vim
command! -nargs=+ MyCommand call MyFunc(<f-args>)`
```

So I don't think that applies here

**Comment by clason** [comment]
It's not a perfect analogy, just meant as a mnemonic device. Otherwise, what does `smods` stand for?

**Comment by famiu** [comment]
> It's not a perfect analogy, just meant as a mnemonic device. Otherwise, what does the "s" in `smods` stand for?

Structured

**Pull request merged**
