### PR TITLE
[RFC] tests/ui: don't ignore character at cursor

### PR DESCRIPTION
**Pull request by bfredl**
Currently screen tests do not test the character that is right under the cursor. The only reason for this I can see is keeping the grid layout but the grid layout is already broken by attr test (and the point of tests is to test stuff and not to look good...)

Before squashing, I could apply the fixup script to any in-progress PR with many screen tests (if any); I already have the necessary fixes for #1930 locally.

### CODE REVIEW

**Comment by bfredl** [comment]
Ping @tarruda @justinmk what do you think of this change ?

**Comment by tarruda** [comment]
LGTM

**Comment by bfredl** [comment]
rebased/squashed.

**Comment by tarruda** [comment]
Merged, thanks

**Pull request closed without merging**
