### PR TITLE
build(deps): bump luajit

### PR DESCRIPTION
**Pull request by clason**
bump bundled LuaJIT to https://github.com/LuaJIT/LuaJIT/commit/c4fe76d50cda24f3529604448f80ff14754599dd

This has a couple of bugfixes and a(nother) workaround for macOS unwind changes.

Nothing major, but more frequent bumps help dealing with the occasional breaking change (which is not always easily apparent from the commit log...)

### CODE REVIEW

**Comment by dundargoc** [comment]
What do you think about cooking up a dependabot-like automation that periodically updates dependencies and creates a PR so we can see if the CI passes?

**Comment by clason** [comment]
What, you want to put me out of my job?

**Comment by clason** [comment]
Seriously, we could do that, but there are only four dependencies that get regular updates:
* LuaJIT
* LibUV
* luv
* tree-sitter

(and the first doesn't release); making update PRs is also pretty trivial. So I'm not sure it's worth the effort?

**Comment by dundargoc** [comment]
> So I'm not sure it's worth the effort?

Hmm, probably not then. OK, just wanted to ask. Thanks.

**Review by lewis6991 — APPROVED** [review]

**Comment by justinmk** [comment]
> Having a `bump-deps.sh` script that works similar to homebrew

👍 that gets us 95% of the way there

**Pull request merged**
