### PR TITLE
Add documentation for some `vim.lsp.buf` functions

### PR DESCRIPTION
**Pull request by cbarrete**

### CODE REVIEW

**Comment by tjdevries** [comment]
hey! Thanks for adding the documentation for these.

Can you actually make the changes in the `lua` files themselves for this? After we merge this: https://github.com/neovim/neovim/pull/12506 you should be able to just run `scripts/gen_vimdocs.py` and regenerate the docs to include the changes you've made here.

I may have actually added docs for a few of these as well -- I don't remember off-hand.

**Comment by cbarrete** [comment]
Sure, do you want me to leave it in the actual docs as well until your PR is merged?

**Comment by tjdevries** [comment]
Yeah, let's leave it for now. If you subscribe to the PR I linked, you should get notified when it gets merged. Ping me here again when it does and after you rebase and we can make sure everything gets set up correctly.

Just wanted to make sure I responded and thanked you for the docs updates, since we really appreciate it, instead of letting you sit waiting for me to fix my PR :)

**Comment by cbarrete** [comment]
@tjdevries the script hits `assert sections` at the `lua` target. I don't have time to look into it now but let me know if it's something that you know about.

**Comment by tjdevries** [comment]
do you have lua or luajit installed on your system (not as part of nvim)? and do you have doxygen installed?

(I should really add those as explicit requirements to the script for other people to use)

**Comment by cbarrete** [comment]
Not sure what was missing last time, it did work fine today.

Also sorry about the git mess, I'm not used to the way GitHub does things. Is it an issue that I pulled from upstream?

**Comment by tjdevries** [comment]
cbarrete, the best way to get the changes is to do the rebase strategy from master onto this branch.

Are you familliar with the strategy? I can help you out w/ some of it if you're interested -- otherwise , we can do the trick of "grab the changes you wanted, delete this branch, and make a new PR from master" :laughing:

**Comment by cbarrete** [comment]
@tjdevries Do you still see something missing here or is it good to go?

**Comment by tjdevries** [comment]
LGTM! Thanks :smile:

**Pull request merged**
