### PR TITLE
fix(lsp): prevent duplicate lines seperated by newlines

### LINKED ISSUE #15246: vim.lsp.buf.hover shows blank line between horizontal lines
### Neovim Version

NVIM v0.6.0-dev+105-g8baf7bce2

### Operating system/version:

Ubuntu 20.04 LTS inside the WSL 2/Windows 10

### Terminal name/version:

Windows Terminal 1.9.1942.0

### TERM environment variable

tmux-256color

### Installation

homebrew

### Steps to reproduce

**Note:** the LSP configuration was extracted from `lspconfig` example configuration.

1. Install _lua-language-server_ inside `~/.local/bin/lua-language-server`
2. Execute Neovim with a _init.lua_ file such as this:
```lua
local packer = require("packer")
local use = packer.use
packer.startup(function()
  use "wbthomason/packer.nvim"
  use "neovim/nvim-lspconfig"
end)

local system_name
if vim.fn.has("mac") == 1 then
  system_name = "macOS"
elseif vim.fn.has("unix") == 1 then
  system_name = "Linux"
elseif vim.fn.has('win32') == 1 then
  system_name = "Windows"
end

local root_path = vim.fn.expand("~").."/.local/bin/lua-language-server"
local binary_path = root_path.."/bin/"..system_name.."/lua-language-server"

local runtime_path = vim.split(package.path, ";")
table.insert(runtime_path, "lua/?.lua")
table.insert(runtime_path, "lua/?/init.lua")

local lspconfig = require("lspconfig")
lspconfig.sumneko_lua.setup({
  cmd = { binary_path, "-E", root_path.."/main.lua" },
  settings = {
    Lua = {
      runtime = {
        version = "LuaJIT",
        path = runtime_path,
      },
      diagnostics = {
        globals = { "vim" },
      },
      workspace = {
        library = vim.api.nvim_get_runtime_file("", true),
      },
      telemetry = {
        enable = false,
      },
    },
  },
})
```
3. Open a Lua file such a this one:
```lua
---Bla bla bla Lorem Ipsum bla bla
---@param text string # Something Something print
---@return nil
local function testFunction(text)
	print(text.."!!")
end

testFunction("Hello World")
```
4. Execute `:lua vim.lsp.buf.hover()` while hovering over the `testFunction` symbol.

### Vim

N/A

### Expected behavior

The blank space between the two horizontal lines shouldn't be displayed.

### Actual behavior

As you can see in the image, there is a blank space between the two horizontal lines.

image

### PR DESCRIPTION
**Pull request by folke**
This PR fixes the check to see if a separator already exists after a code block. It now properly checks for empty lines as well.

Fixes #15246

### CODE REVIEW

**Review by mjlbach — APPROVED** [review]

**Comment by mjlbach** [comment]
@folke I noticed something subtle, this isn't trimming the first new line:
before:
image
after:
image

**Comment by folke** [comment]
Should we trim the first line? It would definitely look better in this case, but that added empty line is what we get from sumneko.

In your before screenshot, the first line is the one we added automatically.

My fix makes sure we no longer add extra lines if another line separated by newlines is present after the code block.

I'm happy to add in extra code to trim empty lines around horizontal lines as well if you think that makes sense. Let me know.

**Comment by mjlbach** [comment]
I can't decide 😆 I think we should default to showing what the language server shows us as you currently have already done, but I can imagine some user is going to point out the visual inconsistency.

**Comment by mjlbach** [comment]
Maybe we instead ask sumneko to change where the separator is placed? I don't think we should be hardcoding in workarounds like this.

**Comment by folke** [comment]
Sumneko actually doubles newlines in other cases too. Let me find some examples.

**Comment by mjlbach** [comment]
Yeah, so I think this is a sumneko problem and we should just merge as-is

**Comment by folke** [comment]
On the other hand, I believe a markdown renderer **does** actually skip newlines around separators.


a

----

b





----

c


Check the source of my comment here

**Comment by folke** [comment]
Apparently it's even required to have a single empty line around the horizontal line :)

https://arcticicestudio.github.io/styleguide-markdown/rules/horizontal-rules.html#empty-lines-before-and-after

So I'd say we strip the empty lines around horizontal rules. Seems to be exactly what renderers do and follows (the very brittle) markdown spec.

**Comment by mjlbach** [comment]
sgtm!

**Comment by folke** [comment]
@mjlbach that change was actually trickier than it should be 😅

I moved the separator stuff in the main loop where we detect code blocks. Otherwise it would have been a mess to need to update the code block highlight ranges.

**Review by mjlbach — APPROVED** [review]

**Pull request merged**
