### PR TITLE
WIP: Add treesitter string parser

### PR DESCRIPTION
**Pull request by tjdevries**
I want to be able to access the Lua bindings for the tree sitter stuff that @bfredl made w/out actually loading text into a buffer (or doing on change, etc.).

I think this PR works... not the prettiest yet though.

@vigoux you might be interested in this.

### CODE REVIEW

**Comment by tjdevries** [comment]
@vigoux Do you want to take over this PR? I don't have time to finish up all the stuff for tree sitter at the moment. You could include it in your ranges PR if you wanted, or separately. You'd just need to pop out the `update runtime` commit that I added in here to get it to work.

Alternatively, we could merge a rougher draft version of this that works and then come back to iterating on it later.

**Comment by vigoux** [comment]
Not sure if I will wee where this pr should go but I can try if you want

**Comment by tjdevries** [comment]
Hey @bfredl or @vigoux could one of you make me a tree sitter string parser? :) I want to be able to use it on files that aren't open please :)

@vigoux it's one of the steps I need for the Lua treesitter thing that I'm working on :)

Thanks.

**Comment by vigoux** [comment]
I'll look into that then!

**Comment by tjdevries** [comment]
@vigoux made this happen in a different PR. Ty buddy :)

**Pull request closed without merging**
