### PR TITLE
fix(clang: 'Uninitialized argument value')

### PR DESCRIPTION
**Pull request by carlosguealv**
Fixed a Logic error of uninitialized argument
value by making an array initialization of { 0 }

### CODE REVIEW

**Comment by zeertzjq** [comment]
Things I have inferred from the code around so far:
- How many times `j` has been incremented is the number of words in the pattern.
- When `matchseq` is false, the number of assigned elements in `matches` is no less than the number of words in the pattern, so no accessing of uninitialized memory should happen.

I haven't looked into the case where `matchseq` is true yet.

**Comment by carlosguealv** [comment]
Yes, you are right about that. I have looked over the false case too, and I don't really understand what fuzzy_match_recursive does. Could you explain it to me please? Thanks in advance!

**Comment by zeertzjq** [comment]
This should be a false positive. Initializing to zero is the easiest way to suppress this. Another way to suppress this is to assert `j` is smaller than the `numMatches` in `fuzzy_match()`, but this requires returning the value of `numMatches` from `fuzzy_match()`.

**Comment by zeertzjq** [comment]
This warning seems gone after #23999

**Pull request closed without merging**
