### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by sakhnik**
I'd like to keep the references to the source code (no cleanup.vim) to allow easier incremental updates in the future.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! You mean, you don't want to run `src/nvim/po/cleanup.vim`, because it prevents incremental updates somehow?

**Comment by justinmk** [comment]
> I see some translations contain the refs, the others don't. Must be the matter of preference.

IIRC that's because we did it "wrong" in the early days. 

@jamessan @fwalch  do you recall if there's a technical reason we should use `src/nvim/po/cleanup.vim` ?

**Comment by sakhnik** [comment]
One more argument pro: if I were to verify someone's translation, I'd prefer the references present in the PO file.

**Comment by justinmk** [comment]
@sakhnik OTOH the references add a lot of churn, so even a small update will change ~1000 lines if the Nvim source has diverged a lot. I'm pretty sure that's why we prefer to remove them.

Ultimately whoever is translating the file is the boss. So if you like it, it's fine with me.

**Comment by sakhnik** [comment]
@justinmk, thanks, I understand that. Conventional practice is to keep them, so let's do so for now.
But I don't mind removing them if it's decided so for all the translations.

**Comment by jamessan** [comment]
> do you recall if there's a technical reason we should use src/nvim/po/cleanup.vim ?

That's what is done upstream, so it eases merges as well as reducing diff noise.

**Comment by justinmk** [comment]
> But I don't mind removing them if it's decided so for all the translations.

@sakhnik If you don't mind, let's do it the same way as in Vim. We will do this for other translations if/when we receive updates for them.

**Comment by sakhnik** [comment]
Done

**Pull request merged**
