### PR TITLE
[RDY] vim-patch:8.0.0101,8.0.0102,8.0.0104,8.0.0106

### LINKED ISSUE #1279: Invalid parameter: dictionary
version 8.0.0101 is report “Invalid parameter: dictionary” when I set dictionary like this:
set dictionary=$HOME/.vim/dict/php.dict

this config can runing in v8.0.3 , I want to know why it can't using now?

### LINKED ISSUE #1284: setting dictionary fails after upgrade to 8.0.101
**PROBLEM:** 
After upgrading to Vim 8.0.101 the folowing line in my .vimrc fails.  
`set dictionary+=/usr/share/dict/words
`
with this error message:
`E474: Invalid argument: dictionary+=/usr/share/dict/words
`
I also get this error message using '=' instead of '+=':
`set dictionary=/usr/share/dict/words
`

**OBSERVATIONS:** 
I get the same error if I manually run the command from inside vim.  This line has been in my .vimrc for over a decade.  On another computer with vim 8.0.94 I do not get this error with the same .vimrc

**ENVIORNMENT:**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 25 2016 13:24:53)
MacOS X (unix) version
Included patches: 1-101
Compiled by Homebrew

Mac OS X 10.10.5 
Homebrew 1.1.1

Note: /usr/share/dict/words is a reachable and readable text file

### PR DESCRIPTION
**Pull request by ckelsel**
vim-patch:8.0.0106

Problem:    Cannot use a semicolon in 'backupext'. (Jeff)
Solution:   Allow for a few more characters when "secure" isn't set.            

https://github.com/vim/vim/commit/0945eaface83e78138fbd40f95cc590bab0e8c86

vim-patch: 8.0.0104
Problem:    Value of 'thesaurus' option not checked properly.
Solution:   Add P_NDNAME flag. (Daisuke Suzuki)

https://github.com/vim/vim/commit/f422bcc7f9615fe91fa69b059cfe4785093d3d4a

vim-patch:8.0.0102
Problem:    Cannot set 'dictionary' to a path.
Solution:   Allow for slash and backslash.  Add a test (partly by Daisuke
                Suzuki, closes vim/vim#1279, closes vim/vim#1284)
    
https://github.com/vim/vim/commit/7554da4033498c4da0af3cde542c3e87e9097b73

vim-patch:8.0.0101
Problem:    Some options are not strictly checked.
Solution:   Add flags for strickter checks.

https://github.com/vim/vim/commit/031cb743ae154cfb727a9b7787bdcb61202ff1c8

### CODE REVIEW

**Comment by KillTheMule** [comment]
Your commits are a bit strange, you've got 8.0.0101 twice, and "fix conflict" is emtpy. Maybe you could also get rid of the merge commit (but that might just be me being pedantic :P). You're also missing some lints.

I tried going through the patches themselves, but I don't fully understand our option handling, so someone else should look at this. Still, you might want to have a look at the useage of `NFNAME` vs. `NDNAME` at line 996 of option.c :)

**Comment by ckelsel** [comment]
@KillTheMule I close 8.0.0101 temporary because which need 8.0.0102,8.0.0104,8.0.0106.

**Comment by ckelsel** [comment]
**Restart build.**

>Error uncompressing cache item: 7z.exe process has exited with code 2. Check C:\Users\appveyor\AppData\Local\Temp\1\build-cache-logs\69731fe8b0155899a53c5aabbdf609f8f85ff800.zip.001.log for details

**Comment by justinmk** [comment]
@ckelsel that build issue should be fixed on master, but this needs to be rebased onto master to get the fix.

**Pull request merged**
