### PR TITLE
[RFC] Some non tagged commits should be NA

### PR DESCRIPTION
**Pull request by Shougo**
Below non tagged commits are NA.

8e77bad: add src/json_test in .gitignore
8211fcb: Travis
1a9f947: Same aboveb
8de7465: Same above
87776a1: Same above
2cb70a2: Same above
471a89: .gitignore
b20617b: Travis

### CODE REVIEW

**Comment by justinmk** [comment]
Why not add them to the commit message in https://github.com/neovim/neovim/pull/5380 ?

**Comment by Shougo** [comment]
I do not use vim-patch.sh for #5380 .
So when I used vim-patch.sh for #5381, the new branch is created...

**Comment by justinmk** [comment]
Ok, I'll squash them then.

**Comment by justinmk** [comment]
Merged, thanks @Shougo

**Comment by Shougo** [comment]
Thank you!

**Pull request closed without merging**
