### PR TITLE
docs(lua): fix, clarify Lua require() docs

### LINKED ISSUE #15480: Lua require() conflict resolution does not match documentation
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Vim does not support Lua

### Operating system/version

Arch Linux, up to date as of 2021-08-25

### Terminal name/version

termite v15

### $TERM environment variable

xterm-termite

### Installation

Arch Linux official repository (community)

### How to reproduce the issue

In an empty directory, run:
```sh
mkdir -p a/lua b/lua
echo "print('a/lua/testpackage.lua')" > a/lua/testpackage.lua
echo "print('b/lua/testpackage.lua')" > b/lua/testpackage.lua

nvim -u NONE "+set rtp+=$PWD/a,$PWD/b" "+lua require('testpackage')"
```

"a/lua/testpackage.lua" is printed to the status line, but the documentation in `lua.txt` suggests the package under `b/` should have been loaded instead.

### Expected behavior

`require('package')` selects the last found `lua/package.lua` under the directories in `runtimepath`, as specified in the documentation (`:help lua`):
https://github.com/neovim/neovim/blob/a373ca1d826b1386f1fa291de70ee5d6bb81ec9b/runtime/doc/lua.txt#L24-L31

### Actual behavior

`require('package')` selects the first found `lua/package.lua` under the directories in `runtimepath`.

This is consistent with how `:runtime` loads the first script found, and is much more intuitive, but the documentation does not match this behaviour. Changing the documentation to match the current behaviour is probably the correct solution here.

### PR DESCRIPTION
**Pull request by Diomendius**
Corrects lua.txt help file to say that require() searches runtimepath
and loads the first module found, not the last.

Also adds additional clarification on require() and module search order.

Closes #15480

I'm not completely sure about where this should fit into the help file's structure, but I've kept it mostly where the original text was, with a summary of `require()` and links to other relevant sections (plus the Lua 5.1 documentation) in place of the original text and further clarification on search order and what exactly `require()` does prepended to the `IMPORTING LUA MODULES` section immediately below.

This information is based on observed behaviour, with some details based on the Nvim or Lua documentation.

It's a little surprising the search order is this:
```
foo/lua/mod.lua
bar/lua/mod.lua
foo/lua/mod/init.lua
bar/lua/mod/init.lua
```
Not:
```
foo/lua/mod.lua
foo/lua/mod/init.lua
bar/lua/mod.lua
bar/lua/mod/init.lua
```
But that's how it currently works. Maybe that's something that should change, though technically it would be a breaking change even if it shouldn't affect most people. (How many people use module overrides, let alone `init.lua` having lowest precedence?)

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by Diomendius** [comment]
I've created a PR to fix the module search order. That PR should be merged before this one so I can update the reference in the docs to reflect the new search order.

**Review by gpanders — APPROVED** [review]

**Comment by gpanders** [comment]
Thanks for updating and clarifying the docs. Can you rebase to resolve the merge conflict?

**Comment by bfredl** [comment]
Note the `init.lua` issue was fixed so that doc change is now redundant.

**Comment by Diomendius** [comment]
I've rebased the branch and made some changes to reflect the corrected search order and to clarify some points I either left out or left unclear. I've kept this as a separate commit to preserve the original for reference. Some of the points of clarification are:
- `.` in the module name is treated as a directory separator in the search path.
- Shared libraries are searched for and loaded, and with strictly lower precedence than Lua scripts.
- Lua's default behaviour for loading modules still applies but is entirely separate to Nvim's custom logic and has strictly lower precedence than `runtimepath`-based search.

I removed some wording mentioning `package.path` and `package.cpath` as I didn't feel this provided enough information on its own for a useful understanding, especially as these variables are not normally relevant to Nvim plugins. The following section in the docs goes into more detail on these already, and the linked Lua 5.1 docs provide a proper explanation.

I added shared libraries to the example search order, assuming a slightly contrived `package.cpath` containing both `.so` and `.dll` in order to illustrate search order when multiple suffixes are present, though I'm not sure any platform has more than one suffix appear in `package.cpath` by default.

In some ways I would prefer not to mention shared libraries at all as this is not normally relevant to Nvim plugins, but Nvim's own module search logic does search for shared libraries itself, so the Lua docs don't cover this aspect of the search order.

One minor nitpick of mine is the phrasing of "The first script found is run", as a shared library is not a script, but I am not happy with "The first module found is run" as an alternative either, as a module is not conceptually something that is run on import, even though that's exactly how Lua behaves. The manner in which shared libraries are loaded is also not mentioned, though I think deferring to the Lua docs for this detail is appropriate.

I did not explicitly specify the way `package.cpath` is parsed for unique suffixes, but I see little benefit in going into too much detail on this.

I also ultimately decided on changing `"foo,bar"` to `` `foo,bar` `` as the following section uses this styling for the values of settings, and it seemed out of place among so many other backtick-delimited literals. If someone else wants to be opinionated on this in a different direction, please feel free.

The following section (under `*lua-package-path*`) seems to cover some of the same points the new section does, though I think it may be outdated. As far as I can tell Nvim does not currently adjust `package.path` or `package.cpath` at all, so this is either figurative or outdated. In particular, the part mentioning reassigning `'runtimepath'` to trigger an update of `package.path` and `package.cpath` seems not to apply to Nvim's current behaviour. Perhaps this section could be updated or removed in the future.

**Review by gpanders — APPROVED** [review]

**Comment by clason** [comment]
@gpanders ping -- this still sounds a useful addition to the docs and doesn't look like it conflicts with the (many, many) doc updates since then; do we want to merge this for 0.7?

**Comment by gpanders** [comment]
> (Assuming this was not invalidated by @bfredl's changes around Lua loading...)

I don't think it was, and I just did a quick test to double check.

**Pull request merged**
