### PR TITLE
Configure gperf to build with `CMAKE_C{XX}_COMPILER`.

### PR DESCRIPTION
**Pull request by bryant**
Noticed that the gperf third-party build was defaulting to gcc.

### CODE REVIEW

**Comment by bfredl** [comment]
Note gperf (just like luarocks) is run build-time and not on the target platform. In the initial code gperf I added `set(GPERF_BUILDARGS CC=${HOSTDEPS_C_COMPILER} LD=${HOSTDEPS_C_COMPILER})` in analogy with luarocks, though I forgot to add a use of it, and then it was removed in #8128 .

**Comment by bryant** [comment]
Would be nice to factor this out rather than duplicating `*_BUILDARGS` across lurocks and gperf.

**Comment by justinmk** [comment]
Let's not worry about that for now :) Is this RDY?

**Comment by bryant** [comment]
gperf needs a CXX as well, so I added host CXX vars. @bfredl let me know if that looks reasonable.

@justinmk Sorry, I'm not intimately familiar with the review process. What further action is needed from me to arrive to RDY?

**Comment by justinmk** [comment]
just let us know when it's ready to merge.

**Comment by bryant** [comment]
Should be ready.

**Comment by bfredl** [comment]
Looks reasonable, merged!

**Pull request merged**
