### PR TITLE
feat(nvim_cmd): accept String for "mods"

### PR DESCRIPTION
**Pull request by famiu**
Allows passing a String to the "mods" key of `nvim_cmd`. This allows
directly using the `mods` value of the `opts` table passed to
`nvim_create_user_command` function callbacks.

### CODE REVIEW

**Comment by justinmk** [comment]
I'm guessing this was discussed in chat, but there always needs to be an explanation in the commit message (and optionally the PR description). We can't find chat messages in the future when we need to reference the reason for a change.

I'm hesitate about this change, because "one obvious way to do things" is helpful to users. This PR introduces a different way. Syntactic sugar isn't a great reason. Vimscript already covers that. One of the main purposes of the API is to be structured.

**Comment by famiu** [comment]
> I'm guessing this was discussed in chat, but there always needs to be an explanation in the commit message (and optionally the PR description). We can't find chat messages in the future when we need to reference the reason for a change.
> 

Will try to keep in mind. Thanks. Going to edit the commit message and PR description in a bit.

> I'm hesitate about this change, because "one obvious way to do things" is helpful to users. This PR introduces a different way. Syntactic sugar isn't a great reason. Vimscript already covers that. One of the main purposes of the API is to be structured. This PR is weakening the structured interface, which also introduces needless variations in the wild.

I guess the biggest benefit is that it allows you to use the `mods` value of the `opts` table that gets passed to `nvim_create_user_command` function callbacks directly in `nvim_cmd`, other than that I agree that there's no major benefit.

**Comment by justinmk** [comment]
> I guess the biggest benefit is that it allows you to use the `mods` value of the `opts` table that gets passed to `nvim_create_user_command` function callbacks directly in `nvim_cmd`

Could we instead change/enhance `nvim_create_user_command` to accept the same structure as `nvim_cmd` ?

**Comment by famiu** [comment]
> > I guess the biggest benefit is that it allows you to use the `mods` value of the `opts` table that gets passed to `nvim_create_user_command` function callbacks directly in `nvim_cmd`
> 
> Could we instead change/enhance `nvim_create_user_command` to accept the same structure as `nvim_cmd` ?

How would that work? If the arguments passed to the command callback is changed then that'd be a breaking API change, wouldn't it?

**Comment by clason** [comment]
You'd have to add a new `mods 2: electric boogaloo` table field to the `args` table.

**Comment by famiu** [comment]
> You'd have to add a new `mods 2: electric boogaloo` table field to the table argument passed to the user command (and mark the current `mods` field as "deprecated" so it can be replaced by the new field in 2.0).

That seems inelegant to me honestly, moreso than this PR. That'd also break the "one obvious way to do things" approach in a way.

**Comment by clason** [comment]
> That seems inelegant to me honestly, moreso than this PR. That'd also break the "one obvious way to do things" approach in a way.

It's the only way to do this, though. And the situation here is different: there's still only one way to _do_ something; there's just a new (additional and clearly better) way to _access_ data.

**Comment by famiu** [comment]
Closing thing PR, will make a new PR that modifies `nvim_create_user_command` instead

**Pull request closed without merging**
