### PR TITLE
[RFC] job: Add optional {flags} parameter.

### LINKED ISSUE #1574: New argument for jobstart() to get JobActivity without newline
I am implementing an option in the [Vim-R-plugin] to run R as a Neovim job and display the R output in a Neovim buffer. So far, I was able to either emulate or substitute with Vim/Neovim commands the most useful features of R Console that depend on libreadline. However, I could not solve a much simpler problem, that does not depend on libreadline at all.

Because output that does not end in a newline character does not generate JobActivity, when R outputs a question not terminated in a new line the question is not displayed. For example, after the command `quit()`, R asks

```
Save workspace image? [y/n/c]:
```

and the user has to type `y`, `n` or `c` right after the colon. But with R running as a Neovim job the question does not trigger a JobActivity event because it does not end in a new line and, thus, it is not displayed in the Neovim buffer.

The solution that I could think of was the addition of an optional argument to `jobstart()` to generate the JobActivity even if the output does not ends in a newline. Is there a better solution?

[Vim-R-plugin]: https://github.com/jcfaria/Vim-R-plugin

### PR DESCRIPTION
**Pull request by splinterofchaos**
fixes #1574

### CODE REVIEW

**Comment by jalvesaq** [comment]
If you want to automate the test, you could put `writefile(getline(1, "$"), fname)` before the command `quit` and check if `fname` contents are:
```

This is the line number 1
This is the line number 2
This is the line number 3
This is the line number 4
```

**Comment by splinterofchaos** [comment]
@jalvesaq Sorry for my slowness. The test works fine for me. I can't reproduce your problem, There are extra newlines (because of the additional empty string), but that's about it.

**Comment by jalvesaq** [comment]
Probably there is something wrong in my code at [Nvim-R]. But this is not an important problem because the R package [nvimcom] outputs messages while being stopped only when it is in debug mode.
[Nvim-R]: https://github.com/jalvesaq/Nvim-R
[nvimcom]: https://github.com/jalvesaq/nvimcom

**Comment by splinterofchaos** [comment]
Closing because the `jobstart()` code has changed and #1574 should no longer be an issue. If we still want to add options for dealing with how newlines are sent, we'll need a fresh look at the issue.

**Pull request closed without merging**
