### PR TITLE
[RFC] Add .nvimlog to .gitignore

### PR DESCRIPTION
**Pull request by sethjackson**
I like doing `git add .` in a branch. Accidentally adding `.nvimlog` is a pain.

`make functionaltest` generates `.nvimlog` for example.

### CODE REVIEW

**Comment by justinmk** [comment]
It's not supposed to appear in the current directory though...

**Comment by sethjackson** [comment]
Yeah I'm not sure what is going on here. `~/.nvimlog` is there too...

But If you:

```shell
cd neovim
rm .nvimlog
make functionaltest
```

It does get generated in the local directory...

**Comment by ZyX-I** [comment]
@sethjackson AFAIR if ~/.nvimlog cannot be edited, ./.nvimlog is used instead. You probably have permission problems with ~/.nvimlog.

**Comment by sethjackson** [comment]
Hmm. This is what I have for `~/.nvimlog`:

`-rw-rw-r--.   1 seth seth 3296185 Dec 31 23:28 .nvimlog`

**Comment by sethjackson** [comment]
I tried with `sudo` too. Same thing. `.nvimlog` gets generated in the current directory.

I noticed that while the tests were running some temporary test files were generated in the local directory also (but get cleaned up later). Maybe the same thing is happening with `.nvimlog`?

All I see in `.nvimlog` is this line:

```
2016/01/01 17:05:27 [error @ call_set_error:743] 73509 - msgpack-rpc: Channel was closed by the client
```

**Comment by justinmk** [comment]
Maybe a test (or the test harness or helper that spawns the nvim session) needs to be fixed.

Would also like to revisit https://github.com/neovim/neovim/pull/3562 if anyone wants to grok that.

**Comment by ZyX-I** [comment]
@sethjackson I was wrong: do not see `./.nvimlog` fallback in the code, there is stderr fallback. Check $HOME environment variable during test.

**Comment by Pyrohh** [comment]
Closing this for now, but please reopen if `.nvimlog` pops up again.

**Comment by cacplate** [comment]
I still get `.nvimlog` in the current directory as well as in `~` when I run `make test` but I don't think this PR is not the solution. This file should have its place and circumvent the problem will not help.

**Comment by sethjackson** [comment]
Yea something is going on in the tests I think. Just haven't had time or interest to look into yet.

**Pull request closed without merging**
