### PR TITLE
vim-patch:9.0.{0196,partial:0202,0204}: indexof()

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:9.0.0196: finding value in list may require a for loop

Problem:    Finding value in list may require a for loop.
Solution:   Add indexof(). (Yegappan Lakshmanan, closes vim/vim#10903)

https://github.com/vim/vim/commit/b218655d5a485f5b193fb18d7240837d42b89812

Co-authored-by: Yegappan Lakshmanan <yegappan@yahoo.com>

#### vim-patch:partial:9.0.0202: code and help for indexof() is not ideal

Problem:    Code and help for indexof() is not ideal.
Solution:   Refactor the code, improve the help. (Yegappan Lakshmanan,
            closes vim/vim#10908)

https://github.com/vim/vim/commit/3fbf6cd355de2212e9227f57d545592aae3f688f

Skip CHECK_LIST_MATERIALIZE and set_vim_var_type().
Use tv_list_uidx() instead of lv_idx.

Co-authored-by: Yegappan Lakshmanan <yegappan@yahoo.com>

#### vim-patch:9.0.0204: indexof() may leak memory

Problem:    indexof() may leak memory.
Solution:   Free allocated values. (Yegappan Lakshmanan, closes vim/vim#10916)

https://github.com/vim/vim/commit/63acae13f57c5ad4c8ec3146d0c458550b9e984e

Co-authored-by: Yegappan Lakshmanan <yegappan@yahoo.com>

### CODE REVIEW

**Comment by zeertzjq** [comment]
Hmm, clint doesn't like `lv_idx`. Not sure what to do here.

**Comment by seandewar** [comment]
Can `tv_list_uidx()` be used?

**Comment by zeertzjq** [comment]
Oh, right. There is an assertion `idx == n`.

**Comment by clason** [comment]
Just in time for the latest runtime update 🤗

**Pull request merged**
