### PR TITLE
refactor(api): deprecate nvim_call_atomic

### PR DESCRIPTION
**Pull request by justinmk**
Use `nvim_exec_lua()` instead

### CODE REVIEW

**Comment by zeertzjq** [comment]
Some APIs are RPC-only (`FUNC_API_REMOTE_ONLY`), especially `nvim_ui_*` APIs, which cannot be used in `nvim_exec_lua`.

**Comment by justinmk** [comment]
Good callout, thanks. But that isn't a blocker, since this only marks the API and won't break anything until Nvim 2.0. This will allow us to get the signal out and address any concerns.

For example, `nvim_buf_detach` is `FUNC_API_REMOTE_ONLY`, but why? We could just change that. Same for the `nvim_ui_*` functions.

Maybe we can change `FUNC_API_REMOTE_ONLY` to allow vimscript/lua to pass an explicit `channel_id`.

**Comment by zeertzjq** [comment]
I think there is another problem that `nvim_exec_lua` has more overhead than `nvim_call_atomic`. `nvim_call_atomic` only involves a `RPC -> API` conversion, while `nvim_exec_lua` requires a `RPC -> API -> Lua -> API` conversion.

**Comment by justinmk** [comment]
> `nvim_exec_lua` has more overhead than `nvim_call_atomic`

True, but we should focus on improving that generally instead of offering a half-baked workaround.

**Comment by zeertzjq** [comment]
> > `nvim_exec_lua` has more overhead than `nvim_call_atomic`
> 
> True, but we should focus on improving that generally instead of offering a half-baked workaround.

But that may be infeasible, as the Lua C API is a fixed interface :(

**Comment by justinmk** [comment]
Examples of general perf improvements:

- the work @bfredl did to avoid allocations
- cache RPC Lua scripts: https://github.com/neovim/neovim/issues/8092

**Pull request merged**
