### PR TITLE
fix(winbar): set w_winrow_off when initializing firstwin size

### LINKED ISSUE #18791: Winbar + laststatus=3 causes tabline issues
### Neovim version (nvim -v)

v0.8.0-dev+329-gf31a10204c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

gnome-terminal 3.44.0

### $TERM environment variable

xterm-256color

### Installation

Chaotic AUR

### How to reproduce the issue

1.) nvim --clean
2.) :set laststatus=3
3.) :set winbar=%f
4.) :tabe
5.) :tabn
6.) :set showtabline=0
7.) :tabe

### Expected behavior

After step 4 the tabline should be visible
After step 5 the tabline should be visible
After step 7 the winbar should be visible

### Actual behavior

After step 4 the tabline is not visible
After step 5 the tabline is visible
After step 7 the winbar is not visible

The tabline does appear after step 5 which may suggest it has something to do with active window logic

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #18791

### CODE REVIEW

**Comment by zeertzjq** [comment]
Will it be better to do this in `win_new_tabpage()` instead?

**Comment by famiu** [comment]
> Will it be better to do this in `win_new_tabpage()` instead?

I personally think doing it in `win_new_tabpage()` is better since that's where `w_winrow` is set

**Comment by zeertzjq** [comment]
`w_winrow_off` isn't usually set at the same place as `w_winrow`. I put it here because there is also:
```c
  firstwin->w_height_inner = firstwin->w_height - firstwin->w_winbar_height;
```

**Comment by famiu** [comment]
> `w_winrow_off` isn't usually set at the same place as `w_winrow`. I put it here because there is also:
> 
> ```c
>   firstwin->w_height_inner = firstwin->w_height - firstwin->w_winbar_height;
> ```

I suppose that makes sense, then

**Pull request merged**
