### PR TITLE
build(deps): bump tree-sitter and treesitter-c to 0.20.1

### PR DESCRIPTION
**Pull request by clason**
This bumps `tree-sitter` from a fixed pre-release commit to v0.20.1, and similarly for `treesitter-c` (the bundled C parser).

Two tests had to be updated to the latest query API.

### CODE REVIEW

**Comment by clason** [comment]
Two test failures:
* test/functional/treesitter/parser_spec.lua @ 230: treesitter parser API can match special regex characters like \ * + ( with `vim-match?`
* test/functional/treesitter/parser_spec.lua @ 320: treesitter parser API allow loading query with escaped quotes and capture them with `lua-match?` and `vim-match?`

**Comment by theHamsta** [comment]
The tests fail because the pattern index changed
```
      for pattern, match in cquery:iter_matches(tree:root(), 0) do
        -- can't transmit node over RPC. just check the name and range
        local mrepr = {}
        for cid,node in pairs(match) do
          table.insert(mrepr, {cquery.captures[cid], node:type(), node:range()})
        end
        table.insert(res, {pattern, mrepr})
```
Probably the pattern index should be removed in the last line of both tests. Sorry, for adding it in the first place!

**Comment by clason** [comment]
Thanks for looking at this!

> Probably the pattern index should be removed in the last line of both tests. Sorry, for adding it in the first place!

I don't know anything about these tests, so a very explicit change suggestion would be helpful. Do you mean just removing the line `table.insert(res, {pattern, mrepr})`, or something else?

**Comment by theHamsta** [comment]
Sorry, there seems to be a real problem here
```
Passed in:
  (table: 0x7fb6c0b62aa8) { }
```
Thought at first sight that only the indices were switched

**Comment by clason** [comment]
Yep, looks like some nodes are just missing (the second failing test makes that clearer).

**Comment by theHamsta** [comment]
Pretty strange. I did a clean build and the tests are failing the same way as on CI. But tree-sitter itself seems to be working normally and also the exact queries from the test still seem to be working.

**Comment by theHamsta** [comment]
This continues to work
```
❯ tree-sitter query foo.scm bar.c
Warning: You have not configured any parser directories!
Please run `tree-sitter init-config` and edit the resulting
configuration file to indicate where we should look for
language grammars.

bar.c
  pattern: 0
    capture: quote, start: (0, 9), text: "\""
  pattern: 0
    capture: quote, start: (0, 15), text: "\""

tree-sitter-c on  master [?] is 📦 v0.20.1 via  v17.0.1 via 🦀 v1.58.0-nightly 
❯ cat foo.scm
((_) @quote (match? @quote "^\"$"))

tree-sitter-c on  master [?] is 📦 v0.20.1 via  v17.0.1 via 🦀 v1.58.0-nightly 
❯ cat bar.c
#include "bar.h"
```

**Comment by theHamsta** [comment]
But using `_` will result in a syntax error. Can you fix the tests?

**Comment by stsewd** [comment]
So, these queries https://github.com/neovim/neovim/blob/fd6df7481a88006fd60bc8980b4db1000ddeda27/test/functional/treesitter/parser_spec.lua#L234 should be written as

```scm
([_] @plus (#vim-match? @plus "^\\\\+$"))
``` 

That way we are able to match any anonymous nodes, otherwise `(_ @plus)` is invalid or `(_)` will only match named nodes. Also, we should use the new syntax for predicates (prefixing with `#`), the other syntax is deprecated.

**Comment by clason** [comment]
Sounds good; if you paste the correct `cquery` argument here, I'll update the tests!

**Comment by clason** [comment]
Looks like changing all `(_)` to `[_]` for these tests did the trick, thanks @stsewd !

(I can still change to the new syntax if somebody tells me exactly what to write ;))

**Comment by stsewd** [comment]
> (I can still change to the new syntax if somebody tells me exactly what to write ;))

the other syntax update would be to change `vim-match?` and friends to `#vim-match?` (pre-fixing `#`), isn't a problem now, but that syntax could be removed in the future.

**Comment by clason** [comment]
Like so?

**Comment by stsewd** [comment]
@clason yes, that's it!

**Comment by clason** [comment]
All checks pass -- even Windows! Now we _have_ to merge ;)

**Comment by stsewd** [comment]
> @stsewd Will this bump have ramifications for nvim-treesitter? Will those queries need to be updated, too?

AFAIK we don't have queries like those, but if we did, it should be easy to fix. (I run the nightly version of tree-sitter locally, and haven't seen any errors)

**Pull request merged**
