### PR TITLE
vim-patch:8.1.0822: peeking and flushing output slows down execution

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.1.0822: peeking and flushing output slows down execution

Problem:    Peeking and flushing output slows down execution.
Solution:   Do not update the mode message when global_busy is set.  Do not
            flush when only peeking for a character. (Ken Takata)

https://github.com/vim/vim/commit/cb574f415486adff645ce384979bfecf27f5be8c

### CODE REVIEW

**Comment by romgrk** [comment]
This patch is messing up [kui.nvim](https://github.com/romgrk/kui.nvim), which outputs to the terminal directly via lua to talk with kitty. By any chance do you have more context on what changed here? I'll read the code but any context would be appreciated.

**Comment by zeertzjq** [comment]
UI is not flash when there is pending input.

**Comment by luukvbaal** [comment]
How does treesitter affect this? From this commit onward, text added by holding down a key is no longer redrawn in a treesitter attached file. Which is quite annoying/unexpected IMO.

Does that just indicate that parsing is too slow to handle my repeat rate? Before this commit text is added but does indeed seem rather laggy, after this commit it is not redrawn at all until I let go of the key.

**Comment by clason** [comment]
(Or, even better, just flush more often, as in the fixup PR.)

**Comment by romgrk** [comment]
I'd love it if this patch went away.

**Pull request merged**
