### PR TITLE
ci: fix stalling Windows builds

### PR DESCRIPTION
**Pull request by mhinz**
As jamessan and janlazo found out, it's probably caused by the use of `:!GZIP=`
on Windows.

But we already clear $GZIP a few lines earlier.

References https://github.com/neovim/neovim/pull/12784

### CODE REVIEW

**Comment by jamessan** [comment]
We're now failing here:

```
 	From test_command_count.vim:
	Found errors in Test_command_count_2():
	function RunTheTest[37]..Test_command_count_2 line 11: Expected 'a' but got ''
```

There was a [change](https://github.com/neovim/neovim/blob/4be0e92db01a502863ac4bb26dd0fee16d833145/src/nvim/testdir/test_command_count.vim#L106) in #12784 to this test, which wasn't in the upstream patch.  Maybe remove that line?

Similar [changes](https://github.com/neovim/neovim/commit/4be0e92db01a502863ac4bb26dd0fee16d833145#diff-a83d928658caaab853c254d9f18c1255c800f8d4ed190de22bbac8faffabffad) where made to test_arglist.vim for no apparent reason.

Can we revert all of those?

**Comment by mhinz** [comment]
Ok, I reverted all changes from `test_arglist.vim` and `test_command_count.vim` for now. It works locally, but let's see what Windows thinks about it.

**Comment by mhinz** [comment]
This original patch is using a [function pointer](https://github.com/vim/vim/commit/701ff0a3e53d253d7300c385e582659bbff7860d#diff-d63764951497182a8a3fd237136b91a72d4b68b1ab264919aa86abd840f26984R7184) and the port uses a [bool](https://github.com/neovim/neovim/pull/12784/files#diff-1b7a1b0f3dbb1d3f4c6520ab4207aeedbbf7e8cfa129d7c710a64e06db20ae9dR5243).

Is that the proper thing to do? It seems to make further porting even harder.

Maybe we should just revert that PR for now. Otherwise we'll merge even more PRs without having a working Win CI.

@janlazo @jamessan @Shougo

**Comment by Shougo** [comment]
The reverting the patch is very sad.
Because v8.1.1378 is really needed for me!

**Comment by Shougo** [comment]
> Someone else can create another MR to re-revert and debug the failing tests.

I need to port it again?  Oh no.

**Comment by janlazo** [comment]
@Shougo Can you cherry-pick your test changes 1-by-1 and only then port your patch? This is to investigate which part of the patch caused the tests to fail. Some test changes seem to be harmless by themselves.

**Comment by jamessan** [comment]
> GZIP environment is not cleared. So I have added the clear. But it does not work in Windows yes.

Yes, it _is_ cleared already by the `let $GZIP = ""` just a couple lines above.

**Comment by Shougo** [comment]
> @Shougo Can you cherry-pick your test changes 1-by-1 and only then port your patch? This is to investigate which part of the patch caused the tests to fail. Some test changes seem to be harmless by themselves.

I will port test changes in the first.

**Comment by Shougo** [comment]
I have ported the test changes before vim-8.1.1378.

**Pull request merged**
