### PR TITLE
[WIP] vim-patch: 7.4.1568,1571,1728

### PR DESCRIPTION
**Pull request by brcolow**
patch 7.4.1568
Problem:    Using CTRL-] in help on option in parentheses doesn't work.
Solution:   Skip the "(" in "('". (Hirohito Higashi)

https://github.com/vim/vim/commit/00f9e0dbbd3472db217d56639fad9346b9eb3b82

patch 7.4.1571
Problem:    No test for ":help".
Solution:   Add a test for what 7.4.1568 fixed. (Higashi Higashi)

https://github.com/vim/vim/commit/8e15ffcde757ffc6cfe8b5e384948b3278e9af33

patch 7.4.1728
Problem:    The help for functions require a space after the "(".
Solution:   Make CTRL-] on a function name ignore the arguments. (Hirohito
            Higashi)

https://github.com/vim/vim/commit/81edd171a9465cf99cede4fa4a7b7bca3d538b0f

---

Question:
Currently facing an issue with the helptags file not being found by `test_help_tagjump.vim`. I tried to fix this issue by adding:

`set tags=../../../build/runtime/doc/tags`

but that doesn't seem to help.

### CODE REVIEW

**Comment by jamessan** [comment]
7.4.1728 is related to this.  Might want to see if it's not too much trouble to pull it in with this.  Also, 7.4.1571 is a corresponding test for 7.4.1568, so it'd be good to merge that too.

**Comment by brcolow** [comment]
Done @jamessan thank you for the suggestions.

**Comment by jamessan** [comment]
Each patch should be a separate commit.

Also, all the CI failed.  There's a [lint issue](https://travis-ci.org/neovim/neovim/jobs/129268936) in the code and the tests failed due to not being able to find the tag file for the help.

I'm not sure off-hand about the best way to handle the missing tag file.  Adding the generated tags file (from build/runtime/doc) to the 'tags' option may be enough.  Someone else may have a better suggestion.

**Comment by justinmk** [comment]
> `set tags=../../../runtime/doc/tags` but that doesn't seem to help.

What about `set tags=../../../build/runtime/doc/tags`?

**Comment by jszakmeister** [comment]
I killed the tests running on QB because it was at 15 hours and counting.

**Comment by brcolow** [comment]
I am currently stuck with this PR as I do not know how to get the helptags to be visible to `test_help_tagjump.vim`. I have tried a bunch of different things but am kind of at an impasse and my time will be limited for a few days. I will squash my changes back to one commit (although jamessan made the good suggestion, and I think justinmk has before him but I too often forget of making each patch a separate commit. When/if I fix this I will do that).

**Comment by jszakmeister** [comment]
> What about set tags=../../../build/runtime/doc/tags?

FYI: we need to be careful about solutions like this since it can break builds for those who don't use Make as their primary mechanism to build.  If you have the path to the nvim binary though, you could formulate the path to the runtime since the binary sits in the build tree.

**Comment by jamessan** [comment]
@brcolow Thanks for all the work you did on this.  I can take a look at picking it up.

**Comment by jamessan** [comment]
> although jamessan made the good suggestion, and I think justinmk has before him but I too often forget of making each patch a separate commit. When/if I fix this I will do that

As an FYI, scripts/vim-patch.sh automates most of this for you.  Every time you use it to merge a patch, an empty commit with the appropriate log message is created.  Then just hack on things until they work, `git commit --amend ...`, and move on to the next patch.

**Comment by justinmk** [comment]
> FYI: we need to be careful about solutions like this since it can break builds for those who don't use Make 

Definitely. My next step would have been to generalize it to avoid brittle assumptions.

**Pull request closed without merging**
