### PR TITLE
fix(highlight): does not set decor attr when in trailcol

### LINKED ISSUE #23869: `listchar` highlight and `:syn` highlight mixed up
### Problem

`listchar` highlight and `:syn` highlight are mixed up.

### Steps to reproduce

```
nvim --clean -S <(tee <<'EOF'
    set list listchars=trail:-
    call setline(1, '   ')
    syn match BoldPink "^.*$"
    hi BoldPink cterm=bold
    hi Whitespace cterm=NONE ctermfg=red ctermbg=NONE " nvim uses this
    hi SpecialKey cterm=NONE ctermfg=red ctermbg=NONE " vim uses this
EOF
)
```
The `-` characters for trailing whitespace are bold, while it shouldn't be.
image

### Expected behavior

image
(vim 9.0.1580)

### Neovim version (nvim -v)

0.10-dev 68e2d722959dadc596edb9320bcdede38659db07

### Vim (not Nvim) behaves the same?

no, vim 9.0.1580

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

ubuntu ppa

### PR DESCRIPTION
**Pull request by glepnir**
Fix #23869

### CODE REVIEW

**Comment by zeertzjq** [comment]
I don't think this makes sense.

**Comment by glepnir** [comment]
is there something wrong with my implementation? I'm not sure either. The extmark may be further to the right of the trailcol. But there are some problems with the value of char_attr that cause the behavior of that issue to be different from vim. Or is it reset_extra_attr? There is some code here that is different from vim. any suggestion thx

**Comment by zeertzjq** [comment]
The difference is that Nvim combines syntax with extmark attributes.

**Comment by glepnir** [comment]
yes. vim use textprop . Do you have some work around on that issue. I would like to learn how you fix it.

**Pull request closed without merging**
