### PR TITLE
docs: fix typo in treesitter.txt

### PR DESCRIPTION
**Pull request by kraftwerk28**

### CODE REVIEW

**Comment by tucnak** [comment]
This patch is completely at odds with philosophy of Neovim, no way this gets accepted!

I say 0/5 stars.

**Comment by nentenpizza** [comment]
This pull request shatters my belief in Neovim.

**Comment by 0xfedcafe** [comment]
Block the merge! Block the merge!!

**Comment by clason** [comment]
Remember, This Is Neovim. No fun allowed!

**Pull request merged**
