### PR TITLE
floats: add MS-DOS mode (borders)

### PR DESCRIPTION
**Pull request by bfredl**
due to popular request.

### CODE REVIEW

**Comment by bfredl** [comment]
note to self: add test for unrelated issue with `gM` and composing chars (not in vim)

**Comment by Shougo** [comment]
Hi, the merge breaks my command line.
The behavior always clears the command line if you change `display` option.

```vim
set display=lastline
```

And it also adds SEGV when I uses defx.nvim actions.

**Comment by tjdevries** [comment]
Also, I think the calculations for popup menu are wrong at the moment.

When I do a window with a border, and I have a coimpletion menu pop up, the row is off by one (with editor at least).

```lua

local bufnr = vim.api.nvim_create_buf(false, true)
local win_id = vim.api.nvim_open_win(bufnr, true, {
  relative = 'editor',
  row = 10,
  col = 10,
  width = 100,
  height = 25,
  border = "double",
  style = "minimal",
})
```

image

**Comment by andymass** [comment]
I'm looking for the Turbo Pascal experience. 😄  I think this feature could sorely use a documentation update.

`:h api-floatwin`
> Currently, floating windows don't support widgets like border or scrollbar.

**Comment by yamatsum** [comment]
Is it possible to use a border with rounded corners like a telescope?

**Pull request merged**
