### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by janlazo** [comment]
vim-patch:8.1.1464: only 4-digit rgb termresponse is recognized

**Comment by blueyed** [comment]
> This pull request is [automated](https://github.com/neovim/bot-ci).

There is no doc there about this, is there?
I think it should explain how comments / these PRs work.


Just noticed that there are two commits with multiple tags (https://github.com/vim/vim/issues/4510), not sure how to handle them here:

1. https://github.com/vim/vim/commit/1ad022a9b81d7829d5dc98cf5b8d0ee410558040 has commit message "patch 8.0.1367", is tagged as both v8.0.1367, and v8.0.1366, and adds 1366 to version.c.
It does not apply to Neovim (for `get_beval_info`), so should be marked as skipped/included.
8.0.1367 was included in f29c2fc4a (empty commit).

2. have not investigated into vim/vim@5d69da4 tag: v8.0.1739, tag: v8.0.1738

(noticed this with https://github.com/neovim/neovim/pull/10137

**Comment by justinmk** [comment]
> Just noticed that there are two commits with multiple tags ([vim/vim#4510](https://github.com/vim/vim/issues/4510)), not sure how to handle them here:

There's not much we can do about that. Noting it here is the best we can do, so thanks.

**Comment by blueyed** [comment]
vim-patch:8.0.0947

**Comment by janlazo** [comment]
There is non-multi-byte dead code so those multi-byte vim-patches are relevant.

**Comment by blueyed** [comment]
@janlazo 
> There is non-multi-byte dead code that checks for `enc_utf8` and `has_mbyte` so those multi-byte vim-patches are relevant.

Do you mean 8.1.0805, 8.1.0806, 8.1.0809, and 8.1.0810?
What dead code do you mean?  Couldn't it be removed then?

**Comment by janlazo** [comment]
Yes. There is code like `if (enc_utf8) { /* relevant code */ } else { /* dead code */ }` present in the codebase.
The dead code can be removed but that makes it harder to apply patches older than 8.1.0805.

**Comment by janlazo** [comment]
Is there enough N/A patches to review so that this can be merged (along with https://github.com/neovim/neovim/pull/10294)?

**Comment by blueyed** [comment]
\o/

@justinmk 
I am wondering about the process here: you've reviewed the comments (how (detailed)?), and put those into the commit message manually?

**Comment by justinmk** [comment]
Yes

**Comment by janlazo** [comment]
Added 8.1.1490 in https://github.com/neovim/neovim/pull/11431. 8.1.{723,1490,2183} go together.

**Pull request merged**
