### PR TITLE
fix(--headless): do not block on press-enter prompts when no UI

### LINKED ISSUE #9358: "Press-Enter" prompt in headless mode
`nvim --headless -c 'echoerr 1'` will display the error and appears to wait for the Enter from the hit-enter prompt:

```
Error detected while processing command line:
1
```

It does not handle any `Enter` presses though, and `Ctrl-C` is required to cancel it.

Without `--headless` it will redraw the screen and displays:

```
Error detected while processing command line:
1
Press ENTER or type command to continue
```

You can use `nvim --headless -c 'echoerr 1' -c q` to work around this, but Neovim should not hang there without `-c q` already.

### LINKED ISSUE #11718: startup: wait for stdioopen() ?
Normally with `--embed` Nvim waits for the UI, in order to avoid the issue reported here. 

- https://github.com/neovim/neovim/wiki/Following-HEAD#20180922 
- `:help --embed`

And with `--headless` Nvim does _not_ to wait for UI to connect (because "headless" implies "no UI"). 

But some UIs like [firenvim](https://github.com/glacambre/firenvim/issues/350) use `--headless` + `stdioopen()`.

Maybe it makes sense for `--embed --headless` to wait for `stdioopen()`?

### PR DESCRIPTION
**Pull request by glacambre**
This commit fixes #9358, where emitting multiple messages with 'echo' or
a single one with 'echom' or 'echoerr' would result in a press-enter
prompt that couldn't be dismissed by pressing enter.

This requires adapting a few tests to spawn a UI before testing whether
press-enter prompts are blocking.

It also fixes #11718, as when combined with #15910 it enables making
sure that neovim never blocks or emits messages on startup.

### CODE REVIEW

**Comment by glacambre** [comment]
@gpanders Github suggested you as reviewer, let me know if you'd prefer me to bother somebody else :)

**Comment by gpanders** [comment]
Anything UI related needs to go through @bfredl.

**Comment by glacambre** [comment]
Cool, thanks :)

**Comment by glacambre** [comment]
@bfredl @gpanders thank you both for looking at this PR so swiftly, I really appreciate it :)

**Pull request merged**
