### PR TITLE
Remove leftover handling of restricted mode.

### LINKED ISSUE #13339: Lingering E145 handling (restricted mode)
In #11996, restricted mode was removed. I noticed that in `runtime/autoload/{man,perl,perl6}.vim` there are some catch commands trying to handle `E145` (I tried `:help E145` and that rabbit hole brought me to #11996).

- [ftplugin/perl6](https://github.com/neovim/neovim/blob/0a95549d66df63c06d775fcc329f7b63cbb46b2f/runtime/ftplugin/perl6.vim#L58)
- [ftplugin/perl.vim](https://github.com/neovim/neovim/blob/0a95549d66df63c06d775fcc329f7b63cbb46b2f/runtime/ftplugin/perl.vim#L55)
- [ftplugin/man.vim](https://github.com/neovim/neovim/blob/0a95549d66df63c06d775fcc329f7b63cbb46b2f/runtime/autoload/man.vim#L16)

 There are also several translation files referencing `E145`. I am not sure if these references/catch commands should be deleted (or replaced by something else in case of the catch commands).

### PR DESCRIPTION
**Pull request by shade-of-noon**
On this PR:
- Remove and refactor runtime scripts which handle E145 (restricted mode error).
- Remove the E145 error message from the Gettext files.

Closes #13339

### CODE REVIEW

**Comment by janlazo** [comment]
You can modify the man plugin and translations but not the filetype plugins that come from Vim.

**Comment by shade-of-noon** [comment]
> You can modify the man plugin and translations but not the filetype plugins that come from Vim.

So should I modify the commits and remove the changes to the Perl ftplugins?

**Comment by janlazo** [comment]
Yes.

**Comment by shade-of-noon** [comment]
> Yes.

Good and done.

**Comment by janlazo** [comment]
Can you squash some of the commits such that perl plugins were not modified?

**Comment by shade-of-noon** [comment]
I deleted the perl related modifications from the commits. I'm not very experienced, I hope I didn't mess up force pushing and all :cold_sweat:.

**Review by janlazo — APPROVED** [review]
LGTM

**Pull request merged**
