### PR TITLE
[RFC] doc: Remove references to Motif GUI support

### PR DESCRIPTION
**Pull request by sethjackson**
We don't support it.

### CODE REVIEW

**Comment by Pyrohh** [comment]
I assume this is WIP because there are still a lot more Motif references?

**Comment by sethjackson** [comment]
Yea. I'll change the tag to RFC when I've got them all.

**Comment by sethjackson** [comment]
@Pyrohh I've removed all references to Motif in `runtime/doc` that I could find save one in `runtime/doc/gui.txt` as I was unsure of what to change that one to. Perhaps you have a suggestion?

Further I've removed `runtime/doc/debugger.txt` but am unsure of whether this is the correct route as I saw some other PRs related to `balloon-eval` which we kept this file in even though we don't currently support that stuff.

If we need to keep `runtime/doc/debugger.txt` then I think we can just remove the (Motif-only) `gui-footer` references and any Motif references in this file.

Thoughts?

**Comment by sethjackson** [comment]
Also I've let the note about GUI/Motif support in `src/nvim/menu.c` alone.

**Comment by Pyrohh** [comment]
Thanks for following up on this, but I'm going on holiday today so won't be able to look at this for a week or so. For now I just have one comment:

> Further I've removed runtime/doc/debugger.txt but am unsure of whether this is the correct route as I saw some other PRs related to balloon-eval which we kept this file in even though we don't currently support that stuff.

I just scanned debugger.txt and removing it seems fine to me, given how outdated it is. If the balloon stuff is eventually reimplemented then reverting a file removal should be easy enough.

**Comment by Pyrohh** [comment]
Any reason why the `debugger.txt` change was reverted? I don't see any comments here so I assume this was discussed elsewhere.

**Comment by sethjackson** [comment]
I shouldn't have. But I guess I messed up my rebase somehow?

**Comment by Pyrohh** [comment]
Maybe, although I've never seen that happen. Anyway, it's no big deal.

**Comment by sethjackson** [comment]
`runtime/doc/debugger.txt` should be removed now.

**Comment by Pyrohh** [comment]
Could you rebase? This looks pretty good to me.

**Comment by sethjackson** [comment]
Rebased.

**Comment by Pyrohh** [comment]
Thanks, committed. There were some broken tags that `gmake html` revealed, hence the other PR.

**Comment by sethjackson** [comment]
Ah ok. I forgot to run `make` inside the doc directory again. Whoops!

**Pull request closed without merging**
