### PR TITLE
treesitter: handle multiple nodes per capture in iter_matches()

### PR DESCRIPTION
**Pull request by andreypopp**
Consider treesitter query like:

    (_ (_)+ @block)

Where @block could capture multiple nodes.

Before this commit `iter_matches()` didn't such case properly - only the latest captured node was stored within a match.

With this commit we handle multiple nodes per capture by collecting them all into a table.

The case with only a single node capture remains the same it is stored directly.

Therefore the following three cases for a capture are now handled:

- no capture - nothing is stored (nil)
- single capture - captured node is stored directly in the match object
- mutliple captures - captured nodes are collected and stored within a table

### CODE REVIEW

**Comment by theHamsta** [comment]
Nice!

Just a small warning that I get
```
../src/nvim/lua/treesitter.c:980:12: warning: unused variable 'query' [-Wunused-variable]
  TSQuery *query = query_check(L, lua_upvalueindex(3));
           ^
```

**Comment by andreypopp** [comment]
@theHamsta yep, just fixed it

**Comment by bfredl** [comment]
replacing `node` with `{node, node}` seems too type-unstable to me. I would rather always make it a table, or if that is too expensive some other kind of consistent representation (I could come up with something concrete for tomorrow :)

**Comment by andreypopp** [comment]
@bfredl agreed about being type-unstable, I initially did it to always produce tables but then thought that it's going to break all 41 usages of `iter_matches` I've found through GitHub Search... and did this instead.

Alternatively we could provide another function which would produce match objects with tables — `iter_matches2` (but with a better name obviously).

The ideal solution would probably be a way to know in advance if capture can produce more than a single node... Does tree sitter provide such API? It's probably possible to infer statically from a query itself...

**Comment by bfredl** [comment]
> @bfredl agreed about being type-unstable, I initially did it to always produce tables but then thought that it's going to break all 41 usages of iter_matches I've found through GitHub Search... and did this instead.

This is gonna break existent users regardless, just more surprisingly.

> Alternatively we could provide another function which would produce match objects with tables — iter_matches2 (but with a better name obviously).

or a `bool` argument to `iter_matches`. would be back-wards compat and still convenient for the old use cases.

> The ideal solution would probably be a way to know in advance if capture can produce more than a single node... Does tree sitter provide such API? It's probably possible to infer statically from a query itself...

I was thinking of this, but i will need to think more tomorrow, or maybe @maxbrunsfeld knows : )

**Comment by maxbrunsfeld** [comment]
Tree-sitter doesn’t provide an API for checking what captures can match and how many times, but it would definitely be possible to add.

**Comment by vigoux** [comment]
@maxbrunsfeld that would be a good addition IMO

**Comment by gpanders** [comment]
Superseded by https://github.com/neovim/neovim/pull/24738.

**Pull request closed without merging**
