### PR TITLE
refactor(packaging): double down on msi for windows

### PR DESCRIPTION
**Pull request by RenFraser**
- Removed NSIS installer.
  - Prevents undefined behaviour when two installations are performed to the same directory (NSIS + MSI).
  - Reduced cost of maintaining two installers that do the same thing.
  - Chose Wix MSI due to its better integration with Windows.
- Added Wix patch file to add neovim binaries to the system path during installation.

### CODE REVIEW

**Comment by RenFraser** [comment]
@justinmk here's the PR to address our [recent discussion](https://github.com/neovim/neovim/pull/17390#discussion_r846849876). I'd ended up adding nvim to the path, which was a nice surprise!

I've tested it locally on Windows 11 by installing the MSI, then opening a new terminal (powershell) and running `nvim`, which opened up nvim and it appears to work just fine.

**Comment by mjlbach** [comment]
Is there a reason this is still marked draft?

**Comment by RenFraser** [comment]
> Is there a reason this is still marked draft?

yep, did a sanity check and picked up a small change I had to make. Setting `permanent='no'` in the patch file should be used instead of what I had done (`permanent='yes'`) to remove nvim from the path on uninstallation. It's ready for review now.

**Review by justinmk — APPROVED** [review]

**Comment by RenFraser** [comment]
Hang on a minute. I'm looking at [the commit to add windows packaging](https://github.com/neovim/neovim/commit/087aad3dcd3439bb87832356067e0a9e26eca510) and it looks like there's been a few missed items in this PR. It looks like `release.yml` and `notes.md` require changes to remove NSIS information too. I'd better get to that before we merge anything.

**Comment by RenFraser** [comment]
>Hang on a minute. I'm looking at [the commit to add windows packaging](https://github.com/neovim/neovim/commit/087aad3dcd3439bb87832356067e0a9e26eca510) and it looks like there's been a few missed items in this PR.

@justinmk I've pushed the changes to address the above. Sorry to give you the run around here. The PR should be ready to merge on approval 😅.

**Review by sitiom — COMMENTED** [review]
@RenFraser I noticed the installer icon looks stretched out, and artifacts remain from the background removal (Hopefully the ICNS isn't the same, haven't checked). I don't know how you converted it but here's the Neovim icon extracted from `nvim-qt.exe` using the [IconViewer](https://www.botproductions.com/iconview/iconview.html) utility: [Neovim.zip](https://github.com/neovim/neovim/files/8462647/neovim.zip)

For comparison:
comparison

**Comment by RenFraser** [comment]
@sitiom that looks a lot better! Thanks for the feedback. I'm sure it'd be fine to slip it into this PR. This was my first time generating a `.ico` file. I'll check the `.icns` file as well and see if we can improve it as well.

**Comment by sitiom** [comment]
Just found out the `neovim-qt` icons can be found at https://github.com/equalsraf/neovim-qt/tree/master/third-party. Maybe you can use those.

**Comment by itsmeboy0** [comment]
I believe the only thing missing from the MSI is the option to add the start menu and desktop shortcuts for Neovim and Neovim Qt, much like what the Vim installer does (Vim and gVim). Start menu shortcuts are essential to me; I would like to be able to search Neovim from the search bar. I hope it isn't too hard to implement 😅

image

**Comment by justinmk** [comment]
> add the start menu and desktop shortcuts for Neovim

can be a followup PR.

**Pull request merged**
