### PR TITLE
feat(treesitter): add more default groups to highlight map

### PR DESCRIPTION
**Pull request by gpanders**
This covers more default groups listed in :h group-name.

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Where do these capture names come from? AFAIK these are not standard.

**Comment by gpanders** [comment]
Are there standard capture group names? I wasn’t aware if so. I just used the lower case version of the highlight group.

**Comment by clason** [comment]
There are in nvim-treesitter (https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights), which are enforced by CI. 

I think there should be some objective guideline here; otherwise there's no limit to the number of group names people will request.

**Comment by gpanders** [comment]
> otherwise there's no limit to the number of group names people will request.

People can modify `hl_map` themselves, which is exactly what nvim-treesitter does. So I don't think we need to worry about this :)

Of course, I could do the same thing (and I am, for now), but I thought it'd be useful to at least have coverage over all of the "builtin" highlight groups listed in `:h group-name`.

That can be our objective guideline too: in core we only include capture groups for the builtin highlight groups. Anything beyond that can be done externally by plugins.

**Comment by clason** [comment]
> Of course, I could do the same thing (and I am, for now), but I thought it'd be useful to at least have coverage over all of the "builtin" highlight groups listed in :h group-name.

Yes, but the _captures_ for it are still arbitrary -- why these and not others? Are these ever used (outside your own dotfiles, presumably?)

To be clear, I am not against adding stuff, but I'd like some reasoned guideline about _what_ gets added (on both side of the mapping).

**Comment by gpanders** [comment]
>Yes, but the captures for it are still arbitrary -- why these and not others? Are these ever used (outside your own dotfiles, presumably?)

I see your point. I can integrate these with capture groups used by nvim-treesitter to the extent possible (e.g. `text.underline` rather than `underlined`). But some are not used by nvim-treesitter (`typedef` and `storageclass`, for instance). The capture groups are "arbitrary" in a sense, but not entirely since they reflect the underlying highlight group.

I am also happy to introduce the new capture groups to nvim-treesitter as well with a PR to help propagate them into the broader ecosystem.

**Comment by clason** [comment]
@theHamsta ping

**Comment by clason** [comment]
Guess no objections :)

**Comment by gpanders** [comment]
Thanks for your feedback.

>@storageclass might make sense, might be more explicit as @keyword.storageclass
>@todo might make sense but should maybe go into the @text.X

I can make these changes.

>no, @type.definition is just confusing because it refers to C typedef but everyone things of something different

Not necessarily. What about a newtype in Haskell or Rust? Or in Zig one can do something like

```zig
const MyType = u32;
```

which is similar to a C typedef in that it "aliases" a type.

>@debug and @type.attribute are totally unclear what they should be
>@preproc collides with @macro and distinction only makes sense for C, similar @define @type,definition

No arguments here, I don't have any issue reverting these.

**Comment by theHamsta** [comment]
I'm not categorically against this. But I would prefer actually introducing the highlight groups one by one and actually fixating them in the highlights. I assume there won't be many rogue PRs using the new groups so we can also do this discussion for each hl-group when it's used in the query instead of inverting. It's generally preferable to have the actual usage before adding documentation. The usage generally shows ambiguities in the understanding of the hl-groups.

**Comment by clason** [comment]
> Just because there is a highlight group isn't a reason to add a cross-language category. There should be a strong reason to add a new one. It must be clear how a Vim highlight can fit into the already dense Atom namespace and whether a subcategory which is now supported would make more sense (easier to understand purpose, more flexible to configure (top-level vs specifications), compatibility with Atom/Emacs)

I strongly disagree with this reasoning. Our concern is about Neovim highlighting, not Atom/Emacs. (It would be different if we could use upstream queries as-is, but that ship has already sailed, so we might as well go whole hog.) In this sense, it makes complete sense to align with legacy highlight groups which are widely used and form the basis for user expectations.

I also think that cross-language homogenization is a fool's errand -- languages are just too different, and trying to force them into a common corset will make it fit none.

Finally, the main issue here is the lack of documentation (on the Neovim side; nvim-treesitter is a different project and discussion) -- I _really_ want some sort of documented guidance here, both on the general philosophy and the specific captures/highlights. (I had hoped this -- open -- PR would spark that, but there seemed to be no interest.) Also, I wanted these changes in for 0.7, which has a feature freeze tomorrow.

**Comment by theHamsta** [comment]
> I strongly disagree with this reasoning. Our concern is with Neovim highlighting, not Atom/Emacs. (It would be different if we could use upstream queries as-is, but that ship has already sailed, so we might as well go whole hog.) In this sense, it makes complete sense to align with legacy highlight groups which are widely used and form the basis for user expectations.

I don't think a general discussion brings any progress. If something is missing it should be shown with concrete example and all the changes it would imply.

> I also think that cross-language homogenization is a fool's errand -- languages are just too different, and trying to force them into a common corset will make it fit none.

Vim has a very flat organization of the highlight groups basically each syntax construct in every has a name. They link to a chain of default groups but the links are not immediately obvious when looking at the syntax files. The Atom uses a fixed set of captures allowing to use a hierarchy to make them more specific. We happen to use the system of Atom. This system already covers full languages. I think Vim specifics can be easier learned, configured and adopted when they integrate in the current system and make keywords more specific (e.g. `@keyword.XXX`). New contributors can port existing queries and we only tell where something needs to be specialized further. I propose to for language specifics to use this kind specialization and keep the general documentation slim. There is no need to document a certain query in the global namespace when it's understood best in the context of that language. The problem with the argument "my language is special" is that no reason is provided why the captures are chosen in a specific way (mostly "I like this color")

The steps forward for me would be to add those new captures one by one to the queries (each for all the languages at once) and refine docs and their naming if needed. CI needs to be adapted to allow `@language.specific.specializations` when the prefix is documented (`e.g. language.specific`).

For upstream, it needs to be decided whether the idea is to follow nvim-treesitter or to maintain own built-in syntax files. In any case, I'd recommend to use the actual groups in `hlmap` in the queries and by that assure that they are tested in practice and necessary.

**Comment by clason** [comment]
>  New contributors can port existing queries and we only tell where something needs to be specialized further. 

That can be very frustrating, as it feels like you are made to play a game where you have to guess the correct groups ("Highlightle")... Especially where there are no existing queries yet. It makes it much easier for new contributors (and hence more likely for them to do it) if they can be pointed to some document and only finetuning is needed.

I strongly believe that we _do_ need a general documentation, in particular if we switch from the current flat Vim approach to a hierarchical Atom approach (which has its charms, but a) we should do it right or not at all, and b) we need to make that switch explicit). We need some consensus for that, and I don't see how we can get either without a discussion involving all stakeholders.

**Comment by clason** [comment]
OK, maybe (definitely) I wasn't clear enough here -- I should have been much more explicit in distinguishing between captures and highlights.

1. **Captures** clearly follow the Atom model, and that is good. (There's also little Neovim can do about it since they're set by nvim-treesitter, at least for the foreseeable future.) What I would like here is some more explanation about these -- the general structure (for example, the fact that Atom-style is followed as far as possible/reasonable). More guidance/examples on the individual captures wouldn't hurt, either. (I'm speaking from experience here -- if I may be blunt between two Germans: right now, it often feels like the reason for using one specific capture is "because @theHamsta said so", which doesn't much help when selecting the next capture... And the fact that @gpanders picked the "wrong" captures is also an indication that more guidance would be useful.)

2. **Highlight groups** currently follow the Vim model, with a `TS` slapped in front. There is no real reason for this to be the case -- we could just as well set these up "bottom-up" by mimicking the actual captures (like `TSKeywordReturn` for `@keyword.return`). That would also send a signal. When I was speaking about a discussion and decision, _this_ is what I was talking about.

**Comment by theHamsta** [comment]
> (I'm speaking from experience here -- if I may be blunt between two Germans: right now, it often feels like the reason for using one specific capture is "because @theHamsta said so",

Right now often I'm just reminding what the results earlier discussions was. You're right that it would be good to write the results of those issue down in a documentation. The current capture system was mostly designed by @vigoux. He was mostly against adding more captures at some point so every new one was longer discussion and we also used them directly. Before there were large tracking issues for which languages a certain feature was already added and which are using a capture in a different way (e.g. ternary operator, what are tags and attributes). I really want to avoid falling back into times where documentation and certain group of languages diverged and rather have compact changes on a specific topic which is easiest when we fill the added hl-group one by one with live by using them in the queries. A general philosophy description PR or a re-grouping of the names of the captures would also be a targeted topic.

>  (like TSKeywordReturn for @keyword.return). That would also send a signal. When I was speaking about a discussion and decision, this is what I was talking about.

Sounds good. The sub-spacing was mostly applied as a compromise in cases where there was no strong opinion on whether a new capture was really necessary. I have no opinion whether existing also `@storageclass` would be fine for me.

**Comment by clason** [comment]
And for what it's worth, I too find the original Vim highlight groups needlessly C-centric, and would love to use the opportunity to re-think the new `TS` highlight groups. (They would still link to the old groups, of course, for backwards compatibility -- but I hope that we'll extend the default colorschemes to handle `TS` groups directly sooner rather than later...)

**Comment by stsewd** [comment]
If it's worth, I agree with @theHamsta, we should be conservative about adding new captures/highlights, since once introduced other themes may be using them already. Also, the PR on the nvim-treesitter repo introduced those captures, but it didn't make use of them in any language.

**Pull request merged**
