### PR TITLE
tests: harden/fix 'ruby provider RPC call to expand("<afile>") …'

### PR DESCRIPTION
**Pull request by blueyed**
The test was added in [1], but unlike the test for the Python provider
does not explicitly call "bwipeout".

This brings it more in line with the test for the Python provider, and
asserts that the expanded "<afile>" is the expected one.

1: https://github.com/neovim/neovim/commit/189c5abeba4fb508d879ebbf5fa07965c4092cf2

### CODE REVIEW

**Comment by blueyed** [comment]
@justinmk 
Noticed this when looking why it hangs on Travis in https://github.com/neovim/neovim/pull/10479 - which might be due to `help help` therein (but it should set the rtp for it there already).
Therefore the question also is why `:help help` is used in https://github.com/neovim/neovim/commit/189c5abeba4fb508d879ebbf5fa07965c4092cf2 in the first place?

**Comment by justinmk** [comment]
> why `:help help` is used in [189c5ab](https://github.com/neovim/neovim/commit/189c5abeba4fb508d879ebbf5fa07965c4092cf2) in the first place?

Because that was the repro provided in https://github.com/neovim/neovim/issues/5245#issuecomment-256815449 .

**Comment by blueyed** [comment]
But without `bwipeout!` the `BufDelete` appears to not be called in the test..  (unlike when trying it manually).

**Comment by blueyed** [comment]
Works with `command` instead of `feed_command`.
But the `eq('runtime/doc/helphelp.txt', eval('g:bufdelete_called'))` looks weird - I would expect it to be the deleted buffer.  But covered in the help:

> NOTE: When this autocommand is executed, the
> current buffer "%" may be different from the
> buffer being deleted "<afile>" and "<abuf>".

**Comment by blueyed** [comment]
Not really necessary, closing for now.

**Pull request closed without merging**
