### PR TITLE
chore: PUSH_PREVIEW_LINES macro indent

### PR DESCRIPTION
**Pull request by zeertzjq**

### CODE REVIEW

**Comment by clason** [comment]
commit lint doesn't like capitals after the colon ;) suggestion: 
`chore: indent PUSH_PREVIEW_LINES macro`

**Comment by zeertzjq** [comment]
I think this can go into the typo fix PR, so the commit message doesn't matter.

**Comment by clason** [comment]
Hmm, I'd prefer to keep the typo fix PR to actual typos, but don't really mind either way.

**Comment by zeertzjq** [comment]
This PR only changes whitespace, not actual code, so I think it can count as a typo.

**Comment by clason** [comment]
OK

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/17859

**Pull request closed without merging**
