### PR TITLE
refactor(diagnostic)!: replace 'show_*' functions with 'open_float'

### PR DESCRIPTION
**Pull request by gpanders**
`show_line_diagnostics()` and `show_position_diagnostics()` are almost identical; they differ only in the fact that the latter also accepts a column to form a full position, rather than just a line. This is not enough to justify two separate interfaces for this common functionality.

Renaming this to simply `show_diagnostics()` is one step forward, but that is also not a good name as the `_diagnostics()` suffix is redundant. However, we cannot name it simply `show()` since that function already exists with entirely different semantics.

Instead, combine these two into a single `open_float()` function that handles all of the cases of previewing diagnostics in a floating window. Also add a "float" key to `vim.diagnostic.config()` to provide global values of configuration options that can be overridden ephemerally. This makes the preview API consistent with the rest of the diagnostic API.

**This is a breaking change.**

Differences in API usage:

| **Before** | **After** |
| ---- | --- |
| `vim.diagnostic.show_line_diagnostics()` | `vim.diagnostic.open_float(0, {scope="line"})` |
| `vim.diagnostic.show_position_diagnostics()` | `vim.diagnostic.open_float(0, {scope="cursor"})` |
| `vim.diagnostic.goto_next { enable_popup = true, popup_opts = {...}` | `vim.diagnostic.goto_next { float = {...} }` |
| `vim.diagnostic.show_line_diagnostics({opts}, buffer, 17)` | `vim.diagnostic.open_float(buffer, {{opts}, scope="line", pos=17}` |
| `vim.diagnostic.show_position_diagnositcs({opts}, buffer, {row, col})` | `vim.diagnostic.open_float(buffer, {{opts}, scope="cursor", pos={row, col}}` |

### CODE REVIEW

**Comment by clason** [comment]
> **This is a breaking change.**

Worth it :)

**Comment by clason** [comment]
Not perfectly sold on the `where` keyword, though -- that could be mistaken for the location of the _float_ (although that would properly be set in the `options` table)?

But the alternatives I can come up with (`at`, `location`) have the same problem...

**Comment by gpanders** [comment]
> Not perfectly sold on the `where` keyword, though -- that could be mistaken for the location of the _float_ (although that would properly be set in the `options` table)?
> 
> But the alternatives I can come up with (`at`, `location`) have the same problem...
> 
> **EDIT** `from`, maybe?

Maybe `scope`?

**Comment by mjlbach** [comment]
I also prefer float over popup where possible

**Comment by mjlbach** [comment]
Also we should fix the flakey win32 test (unrelated to this PR, just noting). Gradually these windows tests are becoming more and more reliable...

```
2021-10-17T16:39:27.9031288Z   [  FAILED  ] test/functional\core\job_spec.lua @ 877: jobs jobstop() kills entire process tree #6530
2021-10-17T16:39:27.9032173Z   test/functional\core\job_spec.lua:949: retry() attempts: 428
2021-10-17T16:39:27.9033006Z   test\helpers.lua:73: Expected objects to be the same.
2021-10-17T16:39:27.9063321Z   Passed in:
2021-10-17T16:39:27.9063978Z   (boolean) false
2021-10-17T16:39:27.9064556Z   Expected:
2021-10-17T16:39:27.9065103Z   (boolean) true
```

**Comment by kylo252** [comment]
This is looking great already ❤️ 

I'm still not sure about the function name as I feel it can suggest that there's a more detailed diagnostics view, when in most cases the "preview" is all you're gonna get anyway. I think it might be worth it to (re-)consider `vim.diagnostic.show_hover()` instead.

**Comment by justinmk** [comment]
> IMO `show()` and `hide()` are good names for what they do right now; namely, showing persistent decorations for diagnostics (virt text, signs, highlights, etc.). `preview()` is a "preview" in that it only shows ephemerally, it does not persist in the buffer in any way. Besides, the function that `preview()` calls is itself called `open_floating_preview()`, so there's precedent.

'previewwindow' has long-established  semantics in Vim already.  I wonder where `open_floating_preview` came from, it's doc is `Shows contents in a floating window.`. That's literally what `nvim_open_win` does, but "preview" was thrown in the name for some reason, it could  be named `show_float` or `open_float`.  Please don't perpetuate "preview" because of this "precedent". 


> Fair, I still like display/hide and show() from the old style but I may be in the minority.

Those are better than randomly sprinkling "preview" in function names for no reason.

In general though the `:help api` names should be considered first. The verb "open" is establish there. If "show" is needed for some reason, it should be a conscious reason.

**Comment by mjlbach** [comment]
@justinmk Yeah I've never liked preview as a name, or popup becomes of the semantic association with prior vim semantics.

**Review by justinmk — APPROVED** [review]
Looks like a good direction. Thanks @gpanders again for your attention to detail :)

**Review by mjlbach — CHANGES_REQUESTED** [review]
virt textual but then LGTM

**Review by mjlbach — APPROVED** [review]
It's probably a good idea to summon the lsp plugin squad (@ckipp01 @ms-jpq @hrsh7th @akinsho @ckipp01 (who is here) @RRethy @kylo252 @siduck76 @mfussenegger @tami5, sorry if I missed anyone)

Don't want plugins breaking on 0.6 for too long. Also make sure to update the breaking_change issue with a reference to this PR and an example on how to adapt plugins.

**Comment by gpanders** [comment]
> Also make sure to update the breaking_change issue with a reference to this PR and an example on how to adapt plugins.

already got one queued up and ready to go 👍

**Review by mfussenegger — APPROVED** [review]
Nice. Really great improvement :+1:

**Comment by sQVe** [comment]
@gpanders I just tried this out and one thing that no longer acts the same way is that triggering `open_float` doesn't move the cursor into the float. This was something that I thought was really useful for yanking diagnostics etc.

Is there a way to get this functionality?

**Comment by sQVe** [comment]
@gpanders Awesome 🎉 Thank you!

I also noted that `show_header` is supported in `open_float` but not in `goto_next` or `goto_prev`.

**Comment by n3wborn** [comment]
Damned ! Sorry, I didn't think my commit would appear here :/

**Pull request merged**
