### PR TITLE
fix: make i_ctrl-] not activate InsertCharPre

### PR DESCRIPTION
**Pull request by altermo**
Did something wrong on this pull request, so created new one: https://github.com/neovim/neovim/pull/27012

Currently pressing `ctrl-]` in insert-mode activates InsertCharPre. This is probably unintended as `ctr-]` doesn't insert a character but does an action.

### CODE REVIEW

**Comment by altermo** [comment]
Closing this in favour of https://github.com/vim/vim/pull/13853

**Comment by justinmk** [comment]
Thanks. Does this fix an open issue?

**Comment by altermo** [comment]
Yes, this one: https://github.com/altermo/ultimate-autopair.nvim/issues/63

**Comment by altermo** [comment]
I kind of did something wrong, and can't reopen the pull request, so opened a new one https://github.com/neovim/neovim/pull/27012

**Pull request closed without merging**
