### PR TITLE
third-party: upgrade libvterm to v0.1.3

### PR DESCRIPTION
**Pull request by blueyed**
Using https://github.com/neovim/libvterm/commit/e23b82f58cdedcb190f2433557a355a29c583be7.

### CODE REVIEW

**Comment by blueyed** [comment]
Fails to build:
```
[273/282] Building C object src/nvim/CMakeFiles/nvim.dir/terminal.c.o
FAILED: /usr/lib/ccache/gcc-9 -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DUSE_GCOV -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I/home/travis/nvim-deps/usr/include/luajit-2.1 -isystem /home/travis/nvim-deps/usr/include --coverage -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -Werror -MD -MT src/nvim/CMakeFiles/nvim.dir/terminal.c.o -MF src/nvim/CMakeFiles/nvim.dir/terminal.c.o.d -o src/nvim/CMakeFiles/nvim.dir/terminal.c.o   -c ../src/nvim/terminal.c
../src/nvim/terminal.c: In function ‘term_settermprop’:
../src/nvim/terminal.c:709:34: error: incompatible type for argument 2 of ‘buf_set_term_title’
  709 |       buf_set_term_title(buf, val->string);
      |                               ~~~^~~~~~~~
      |                                  |
      |                                  VTermStringFragment {aka struct <anonymous>}
../src/nvim/terminal.c:680:50: note: expected ‘char *’ but argument is of type ‘VTermStringFragment’ {aka ‘struct <anonymous>’}
  680 | static void buf_set_term_title(buf_T *buf, char *title)
      |                                            ~~~~~~^~~~~
```
/cc @leonerd

**Comment by blueyed** [comment]
Looks like a bad merge - will use the tag instead.

**Comment by blueyed** [comment]
@justinmk 
I guess we could also use tarballs from launchpad (https://github.com/neovim/libvterm/pull/5), or are they flaky also?

**Comment by justinmk** [comment]
> I guess we could also use tarballs from launchpad ([neovim/libvterm#5 (comment)](https://github.com/neovim/libvterm/pull/5#issuecomment-571167359)), or are they flaky also?

haven't tried it but why not use our github mirror?

**Review by justinmk — APPROVED** [review]

**Comment by leonerd** [comment]
Your github mirror is (probably?) following development head, rather than 0.1-release branch.

**Comment by blueyed** [comment]
@leonerd 
> Your github mirror is (probably?) following development head, rather than 0.1-release branch.

Yes, I've merged master first.

**Pull request merged**
