### PR TITLE
[RFC] api: vim_set_var() should return the old value

### LINKED ISSUE #2816: Msgpack API: vim_set_var returns null every time
I have been playing around with the Msgpack API. According the the documentation comment for [`vim_set_var`](https://github.com/neovim/neovim/blob/e888c479f3d34a1948c63495328b4184ff2ab874/src/nvim/api/vim.c#L294) should return the old value if there was a value set. However this doesn't appear to happen.

The below is an example where the variable 'a' is set to 1. Checks to make sure that the variable was set to 1. Then reassigns it to 2.  (The code uses the session directly to send requests since I wasn't sure how to demonstrate the last line through the python api)

```
import neovim

vim = neovim.attach('child', argv=['nvim', '--embed'])
print(vim._session.request('vim_set_var', 'a', 1))     # vim.vars['a'] = 1
print(vim._session.request('vim_get_var', 'a'))        # print(vim.vars['a'])
 # Don't know how to do this through the python api
print(vim._session.request('vim_set_var', 'a', 2))
```

Output from running
```
None
1
None
```

The last print statement prints None instead of the old value of 1 which seems to go against what the documentation says.

---

version info
NVIM 0.0.0-alpha+201506091331 (compiled Jun  9 2015 23:06:45)
Commit: 6270d431aaeed71e7a8782411f36409ab8e0ee35

### PR DESCRIPTION
**Pull request by justinmk**
Closes #2816

### CODE REVIEW

**Comment by fdinoff** [comment]
This isn't correct. Its supposed to return the old value if it was set. [Documentation](https://github.com/neovim/neovim/blob/e888c479f3d34a1948c63495328b4184ff2ab874/src/nvim/api/vim.c#L294). Not the new one. (This is consistent with [`Map#put`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-) in java. Which would be my intended use case.

I think the test is supposed to be something like the following (I don't actually know lua so it may be incorrect)
```lua
eq(nil, nvim('set_var', 'lua', {1, 2, {['3'] = 1}}))
eq({1, 2, {['3'] = 1}}, nvim('set_var', 'lua', {1, 2, {['3'] = 3}}))
```

I don't think returning the new value is very useful.

(If it matters I don't really know why the value of put returns the old value. This is just the contract that has been laid out)

**Comment by justinmk** [comment]
Ok, easy enough to change.

**Comment by justinmk** [comment]
Updated

**Comment by fdinoff** [comment]
LGTM, Thank You

**Comment by justinmk** [comment]
Merged

**Pull request closed without merging**
