### PR TITLE
[RDY] Remove outdated and unused manuals

### PR DESCRIPTION
**Pull request by ghost**
`nvim-[lang].1`:
The non-english manuals are completely outdated and still written in
roff, as opposed to mdoc, which is used for `nvim.1`.
Given that, they're nearly useless at the moment, and when/if they are
updated, they should probably be rewritten from scratch using `nvim.1`
as a reference.

`xxd*.1`:
xxd hasn't been in the source tree for a long time, so the manual is of
little use.

`nvimtutor*.1`:
The vimtutor script hasn't ever shipped with nvim, and the consensus
seems to be that it won't, at least in the form of an executable
installed alongside `$(PREFIX)/bin/nvim` (see #2700).

In `nvim.1`, the argument to the `.Os` macro was removed. This was done
because its only purpose was to signify that nvim and nvimtutor
were part of the "Neovim" distribution, i.e., one and the same, which
isn't applicable anymore because `nvimtutor.1` is being removed.
From the `.Os` documentation in `man mdoc`:

```
Os
  Operating system version for display in the page footer.  This is the
  mandatory third macro of any mdoc file.  Its syntax is as follows:

        .Os [system [version]]

  The optional system parameter specifies the relevant operating system or
  environment.  It is suggested to leave it unspecified, in which case
  mandoc(1) uses its -Ios argument or, if that isn't specified either,
  sysname and release as returned by uname(3).

  Examples:
        .Os
        .Os KTH/CSC/TCS
        .Os BSD 4.3

  See also Dd and Dt.
```

### CODE REVIEW

**Comment by fwalch** [comment]
Not really related, but what about removing the non-English manpages? They're just Vim manpages, so probably more confusing than helpful.

**Comment by Pyrohh** [comment]
> Not really related, but what about removing the non-English manpages? They're just Vim manpages, so probably more confusing than helpful.

Sure, they all need to be rewritten anyways.

**Comment by Pyrohh** [comment]
@fwalch I updated the PR. Despite there only being one file left in `man/`, I kept the folder if non-english manuals are added in the future.

**Comment by fmoralesc** [comment]
LGTM.

**Comment by fwalch** [comment]
LGTM.

**Comment by justinmk** [comment]
:+1:

**Comment by Pyrohh** [comment]
Thanks all, merged.

**Pull request closed without merging**
