### PR TITLE
fix(drawline): offset 'colorcolumn' with inline virtual text

### PR DESCRIPTION
**Pull request by luukvbaal**
Supersede #24088

### CODE REVIEW

**Comment by luukvbaal** [comment]
What do you think needs to be discussed @zeertzjq?

	'colorcolumn' is a comma-separated list of screen columns that are
	highlighted with ColorColumn |hl-ColorColumn|.  Useful to align
	text.  Will make screen redrawing slower.

I guess the fact that it will no longer highlight the actual screen column? The option help also mentions it is useful to align text, not offsetting for inline virtual text goes against that.

**Comment by luukvbaal** [comment]
Just noticed there is also a related vim patch: https://github.com/vim/vim/commit/f53e065bce1adff4bff202ed3ba9982ece90b745.
Though this is for virtual text above, not inline.

**Comment by justinmk** [comment]
Can you show a before/after screenshot (not a video)? Based on https://github.com/neovim/neovim/pull/24088 it looked a big ugly to me, but I don't use cursorcolumn so idk what makes the most sense. With a before/after screenshot we could potentially ask users to vote on it.

**Comment by luukvbaal** [comment]
Yeah it's not pretty. I think the argument for is about utility, perhaps @vantaboard can chime in on that.
Before:
image
After:
image

**Comment by vantaboard** [comment]
> Yeah it's not pretty. I think the argument for is about utility, perhaps @vantaboard can chime in on that. Before: image After: image

Definitely utility. It's not pretty, but I am very strict when it comes to line length. Inlay hints are such a nice feature, and I wouldn't be able to use it confidently if I couldn't still rely on it. If anything, you could pretty it up by making the foreground a different color. That would be less jarring.

**Comment by famiu** [comment]
Fwiw, I prefer the current behavior over the behavior that this PR implements. It looks far too disorienting to me. If we want this kind of behavior, I'd at least want it to be configurable (and perhaps even opt-in) so I can keep the current behavior.

**Comment by luukvbaal** [comment]
Yeah I would guess users that use 'colorcolumn' would want to be able to align to the actual buffer content and not decorations. In that case 'colorcolumn' should _include_ concealed text and _exclude_ virtual text but this goes against what Vim does and decided as to how the option should work: https://groups.google.com/g/vim_dev/c/xjHRfUOgSac/m/0bk4zPai7H4J. In that discussion I guess it was determined that it should always be a straight line.

Question is if we want to diverge from that and/or convince Bram that the old behavior for concealed text was actually desirable and should be fixed for virtual text instead...

**Comment by famiu** [comment]
> > If we want this kind of behavior, I'd at least want it to be configurable
> 
> Can turn off inlay hints to make it pretty.
> 
> I'm inclined to go with this change because otherwise the cursorcolumn is rather pointless. Literally what is the point of having it if you can't trust it?

Can't really argue against that, I suppose. At least in my config, I automatically turn off inlay hints in insert mode so it'd only be disorienting in normal mode for me, and I don't really need colorcolumn to tell me anything in normal mode anyway. But that's specific to my config. Considering the general case, I think the utility case does make more sense, despite not being pretty. However, I wonder what behavior other editors with inline virtual text support and colorcolumn/fill-column implement. I think it might be worth trying to be consistent with other editors as well. And there's also the issue with Vim choosing to keep the colorcolumn a straight line (which makes sense imo cause the option is called colorcolumn, which implies a single column).

**Comment by justinmk** [comment]
> In that case 'colorcolumn' should _include_ concealed text and _exclude_ virtual text but this goes against what Vim does and decided as to how the option should work: https://groups.google.com/g/vim_dev/c/xjHRfUOgSac/m/0bk4zPai7H4J

Nice reference. Without reading vim_dev, I can imagine a reason: "if you are in _I care about line length_ mode, then you should disable 'conceal' / virtual text temporarily. Virtual (shifted) text will only become more common..."

OTOH, with 'wrap', colorcolumn is broken on wrapped lines:

image

# Proposal

I think we should merge this and try it out. Can always revert later, it's a small change (and surgical; thank you @luukvbaal ).

**Review by justinmk — APPROVED** [review]

**Comment by famiu** [comment]
> > In that case 'colorcolumn' should _include_ concealed text and _exclude_ virtual text but this goes against what Vim does and decided as to how the option should work: https://groups.google.com/g/vim_dev/c/xjHRfUOgSac/m/0bk4zPai7H4J
> 
> Nice reference. Without reading vim_dev, I can imagine a reason: "if you are in _I care about line length_ mode, then you should disable 'conceal' / virtual text temporarily. Virtual (shifted) text will only become more common..."
> 
> OTOH, with 'wrap', colorcolumn is broken on wrapped lines:
> 
> image
> # Proposal
> I think we should merge this and try it out. Can always revert later, it's a small change (and surgical; thank you @luukvbaal ).

I don't think most people use a dev build of Neovim for us to get a good idea of the general consensus for a change like this until 0.10 is released. Imo, in cases like these where it's entirely a matter of preference. We should either keep both behaviors (by making it configurable) OR we should do some sort of poll to see what the majority prefers and go with that.

**Comment by luukvbaal** [comment]
> I think it might be worth trying to be consistent with other editors as well.

FWIW, it was marked as a bug here: https://github.com/microsoft/vscode/issues/171071

**Comment by justinmk** [comment]
> I don't think enough people use a dev build of Neovim for us to get a good idea of the general consensus

Not true. And we don't need to speculate about number of users when deciding to try things on master.

**Comment by luukvbaal** [comment]
> I think we should merge this and try it out. Can always revert later, it's a small change (and surgical; thank you @luukvbaal ).

Might not be as surgical as it appeared, there seem to be unconsidered edge cases.

**Comment by luukvbaal** [comment]
Should be fixed.

BTW: I noticed that when enabling inlay hints and `'cursorcolumn'`, we seem to be entering an infinite redraw loop, resulting in significant CPU usage. Not sure why but this is being called constantly:
```
#0  changed_line_display_buf (buf=0x55d287ab5700) at /home/luuk/dev/neovim/src/nvim/move.c:587
#1  0x000055d28735bdd5 in decor_redraw (buf=0x55d287ab5700, row1=207, row2=207,
    decor=0x55d288c51910) at /home/luuk/dev/neovim/src/nvim/decoration.c:87
#2  0x000055d28735be4e in decor_remove (buf=0x55d287ab5700, row=207, row2=207,
    decor=0x55d288c51910) at /home/luuk/dev/neovim/src/nvim/decoration.c:99
#3  0x000055d287418107 in extmark_clear (buf=0x55d287ab5700, ns_id=68, l_row=0, l_col=0,
    u_row=2147483646, u_col=2147483647) at /home/luuk/dev/neovim/src/nvim/extmark.c:274
#4  0x000055d2872edf2f in nvim_buf_clear_namespace (buffer=1, ns_id=68, line_start=0,
    line_end=2147483647, err=0x7fff540cc7c0) at /home/luuk/dev/neovim/src/nvim/api/extmark.c:1044
```

**Comment by famiu** [comment]
> can do that too

I think a poll would be great!

**Comment by p00f** [comment]
@luukvbaal I'm thinking of storing whether a hint was applied and only applying the hints that aren't already applied in the decoration provider, instead of clearing and re-applying on every window redraw

**Review by zeertzjq — CHANGES_REQUESTED** [review]
1. `n_extra` is the number of bytes of the virtual text, not the number of cells. The number of cells occupied by the virtual text is its `virt_text_width`.
2. The new behavior in this PR isn't "correct" in any sense when there are TABs after inline virtual text, because inline virtual text causes the length of TABs to change.
3. Even if the two problems above are fixed, the new behavior isn't consistent with how other "alignment" features work, e.g. TABs, blockwise Visual selection, 'textwidth', text formatting.

**Comment by luukvbaal** [comment]
Besides the technical problems, you also seem to be against the change conceptually @zeertzjq. Care to elaborate on that? Don't you agree that 'cursor/colorcolumn' are quite useless to align text currently in lines that contain virtual text?

Again, I have no skin in the game as I don't use these options. I can try to look into verifying the correctness further but I will not do that it is not wanted.

**Comment by zeertzjq** [comment]
In the case of inlay hints the new behavior may be desired, but this is not the only thing that inline virtual text may be used for. Another possible use case of inline virtual text is previewing what text may be inserted by a certain action (ref https://github.com/neovim/neovim/issues/16466#issuecomment-982197398), and in this case the new behavior doesn't make sense and may be annoying.

**Comment by luukvbaal** [comment]
Fair point, probably not worth it then.

@vantaboard maybe your best bet would be to make a plugin that does something similar to your original PR. Perhaps you can make the distinction between inlay hint virtual text or otherwise, and highlight the offset in addition to the builtin 'cursor/colorcolumn' line. Messing with the option value and completely replacing it didn't seem the best idea to me.

**Comment by vantaboard** [comment]
> Fair point, probably not worth it then.
> 
> @vantaboard maybe your best bet would be to make a plugin that does something similar to your original PR. Perhaps you can make the distinction between inlay hint virtual text or otherwise, and highlight the offset in addition to the builtin 'cursor/colorcolumn' line. Messing with the option value and completely replacing it didn't seem like the best idea to me.

Could we make it an API toggle so people can turn it on and off?

**Comment by luukvbaal** [comment]
> Could we make it an API toggle so people can turn it on and off?

Make what an API toggle? 

I think it could make sense to add a flag to extmarks indicating whether inline virtual text should be seen as a "decoration" or a "preview". That way the redraw code could make the distinction whether e.g. 'colorcolumn' should be shifted for a particular extmark. And it could serve as a user config at the same time (given that the extmark providers expose this flag as a configuration variable).

**Pull request closed without merging**
