### PR TITLE
fix(lmpack): fail to encode list-like tables with string keys

### LINKED ISSUE #16837: vim.mpack.encode fails on list-like tables where keys are strings ("1", "2", "3" etc) instead of numbers
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

pacman, official repositories

### How to reproduce the issue

```lua
vim.mpack.encode({ ['1'] = 1 })
vim.mpack.encode({ ['1'] = 1, ['2'] = 3, ['3'] = 4 })
vim.mpack.encode({ ['0'] = 1 })  -- but this one works fine
vim.mpack.encode({ ['1'] = 1, ['3'] = 4 })  -- sparse "lists" don't cause the problem either
vim.mpack.encode({ [1] = 1, ['2'] = 3, ['3'] = 1 })  -- mixed key types also cause the issue
vim.mpack.encode({ [5] = 1, ['2'] = 3, ['3'] = 1 })  -- but this works, so mixed key types are generally allowed
```

### Expected behavior

All of the above cases are encoded as dictionaries with string keys, and the latter two serialize to dictionaries with string and number keys.

### Actual behavior

Cases 1, 2 and 5 throw the following error:

```
E5108: Error executing lua [string ":lua"]:1: can't serialize object of type 0
stack traceback:
        [C]: in function 'encode'
        [string ":lua"]:1: in main chunk
```

### PR DESCRIPTION
**Pull request by ghost**
Problem:
  `vim.mpack.encode` fails to encode a table with some string keys if
  all keys form a sequence 1..n, because `lmpack_objlen` uses
  `lua_isnumber` to determine if a key is a number

  From Lua 5.1 reference manual:

  `int lua_isnumber (lua_State *L, int index);`
  Returns 1 if the value at the given acceptable index is a number or a
  string convertible to a number, and 0 otherwise

Solution:
  Use `lua_type` instead

fixes #16837

### CODE REVIEW

**Comment by clason** [comment]
1. mpack is vendored, so we prefer not to make any changes unless absolutely necessary.
2. we do not support any Lua version but 5.1, so no need for ifdefs.

**Comment by nwounkn** [comment]
Where should I send the fix?

**Comment by clason** [comment]
https://github.com/libmpack/libmpack-lua

**Comment by nwounkn** [comment]
closing

**Pull request closed without merging**
