### PR TITLE
[RFC] unittests: Force GC, fix GC failures in typval_spec

### PR DESCRIPTION
**Pull request by ZyX-I**
Ref #6404.

### CODE REVIEW

**Comment by ZyX-I** [comment]
Unable to locally reproduce problems with GC crash on “[ RUN      ] ./test/unit/helpers.lua @ 724: typval.c list copy() copies list correctly and converts items” even with

```Patch
diff --git a/test/unit/helpers.lua b/test/unit/helpers.lua
index 74f214a..be8253d 100644
--- a/test/unit/helpers.lua
+++ b/test/unit/helpers.lua
@@ -552,6 +552,7 @@ local function child_sethook(wr)
   local trace_only_c = trace_level <= 1
   local prev_info, prev_reason, prev_lnum
   local function hook(reason, lnum, use_prev)
+    collectgarbage()
     local info = nil
     if use_prev then
       info = prev_info
@@ -629,7 +630,7 @@ local trace_end_msg = ('E%s\n'):format((' '):rep(hook_msglen - 2))
 
 local function itp_child(wr, func)
   init()
-  collectgarbage('stop')
+  -- collectgarbage('stop')
   child_sethook(wr)
   local err, emsg = pcall(func)
   debug.sethook()
```

And where are core dumps?

**Comment by ZyX-I** [comment]
Got core dumps from OS X only:

(.6, list item remove)
```
* thread #1: tid = 0x0000, 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff984624ec libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9c5f16df libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffa0d06041 libsystem_malloc.dylib`free + 425
    frame #4: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #5: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #6: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #7: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #8: 0x0000000001b852b4 libnvim-test.so`xfree(ptr=0x0000000000409690) + 36 at memory.c:130
    frame #9: 0x0000000001aca222 libnvim-test.so`tv_list_item_free(item=0x0000000000409690) + 34 at typval.c:67
    frame #10: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #11: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #12: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #13: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #14: 0x000000010000616d luajit`gc_call_finalizer(g=0x00000000000423b8, L=0x0000000000042378, mo=<unavailable>, o=<unavailable>) + 189 at lj_gc.c:473
    frame #15: 0x0000000100005e9f luajit`gc_finalize(L=0x0000000000042378) + 271 at lj_gc.c:507
    frame #16: 0x000000010000695c luajit`gc_onestep(L=0x0000000000042378) + 1292 at lj_gc.c:654
    frame #17: 0x0000000100006bf8 luajit`lj_gc_fullgc(L=0x0000000000042378) + 136 at lj_gc.c:743
    frame #18: 0x0000000100015ae8 luajit`lua_gc(L=0x0000000000042378, what=<unavailable>, data=<unavailable>) + 104 at lj_api.c:1155
    frame #19: 0x0000000100035c9b luajit`lj_cf_collectgarbage(L=0x0000000000042378) + 91 at lib_base.c:455
    frame #20: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #21: 0x00000001000155d6 luajit`lua_pcall(L=<unavailable>, nargs=<unavailable>, nresults=<unavailable>, errfunc=<unavailable>) + 182 at lj_api.c:1052
    frame #22: 0x00000001000020a9 luajit`docall(L=0x0000000000042378, narg=9, clear=0) + 89 at luajit.c:122
    frame #23: 0x00000001000018cd luajit`pmain [inlined] handle_script + 335 at luajit.c:289
    frame #24: 0x000000010000177e luajit`pmain(L=0x0000000000042378) + 1630 at luajit.c:538
    frame #25: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #26: 0x00000001000156e8 luajit`lua_cpcall(L=<unavailable>, func=<unavailable>, ud=<unavailable>) + 40 at lj_api.c:1074
    frame #27: 0x000000010000101b luajit`main(argc=11, argv=0x00007fff5fbfe800) + 59 at luajit.c:566
    frame #28: 0x0000000100000fb8 luajit`_start + 230
    frame #29: 0x0000000100000ed1 luajit`start + 33
```

(.6, list copy)
```
* thread #1: tid = 0x0000, 0x0000000100032766 luajit`lj_alloc_free(msp=<unavailable>, ptr=<unavailable>) + 182 at lj_al
loc.c:1283, stop reason = signal SIGSTOP
  * frame #0: 0x0000000100032766 luajit`lj_alloc_free(msp=<unavailable>, ptr=<unavailable>) + 182 at lj_alloc.c:1283
    frame #1: 0x0000000100032698 luajit`lj_alloc_f(msp=<unavailable>, ptr=<unavailable>, osize=<unavailable>, nsize=<un
available>) + 24 at lj_alloc.c:1388
    frame #2: 0x00000001000062de luajit`gc_sweep(g=0x00000000000423b8, p=<unavailable>, lim=<unavailable>) + 174 at lj_
gc.c:405
    frame #3: 0x00000001000068bd luajit`gc_onestep(L=0x0000000000042378) + 1133 at lj_gc.c:633
    frame #4: 0x0000000100006bf8 luajit`lj_gc_fullgc(L=0x0000000000042378) + 136 at lj_gc.c:743
    frame #5: 0x0000000100015ae8 luajit`lua_gc(L=0x0000000000042378, what=<unavailable>, data=<unavailable>) + 104 at l
j_api.c:1155
    frame #6: 0x0000000100035c9b luajit`lj_cf_collectgarbage(L=0x0000000000042378) + 91 at lib_base.c:455
    frame #7: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #8: 0x00000001000155d6 luajit`lua_pcall(L=<unavailable>, nargs=<unavailable>, nresults=<unavailable>, errfunc
=<unavailable>) + 182 at lj_api.c:1052
    frame #9: 0x00000001000020a9 luajit`docall(L=0x0000000000042378, narg=9, clear=0) + 89 at luajit.c:122
    frame #10: 0x00000001000018cd luajit`pmain [inlined] handle_script + 335 at luajit.c:289
    frame #11: 0x000000010000177e luajit`pmain(L=0x0000000000042378) + 1630 at luajit.c:538
    frame #12: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #13: 0x00000001000156e8 luajit`lua_cpcall(L=<unavailable>, func=<unavailable>, ud=<unavailable>) + 40 at lj_api.c:1074
    frame #14: 0x000000010000101b luajit`main(argc=11, argv=0x00007fff5fbfe800) + 59 at luajit.c:566
    frame #15: 0x0000000100000fb8 luajit`_start + 230
    frame #16: 0x0000000100000ed1 luajit`start + 33
```

(.6, dict watcher add/remove)
```
* thread #1: tid = 0x0000, 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff984624ec libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9c5f16df libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffa0d06041 libsystem_malloc.dylib`free + 425
    frame #4: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #5: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #6: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #7: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #8: 0x0000000001b852b4 libnvim-test.so`xfree(ptr=0x0000000000100bd0) + 36 at memory.c:130
    frame #9: 0x0000000001a83889 libnvim-test.so`partial_free(pt=0x0000000000100140) + 89 at eval.c:4859
    frame #10: 0x0000000001a83824 libnvim-test.so`partial_unref(pt=0x0000000000100140) + 52 at eval.c:4877
    frame #11: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #12: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #13: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #14: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #15: 0x000000010000616d luajit`gc_call_finalizer(g=0x00000000000423b8, L=0x0000000000042378, mo=<unavailable>, o=<unavailable>) + 189 at lj_gc.c:473
    frame #16: 0x0000000100005e9f luajit`gc_finalize(L=0x0000000000042378) + 271 at lj_gc.c:507
    frame #17: 0x000000010000695c luajit`gc_onestep(L=0x0000000000042378) + 1292 at lj_gc.c:654
    frame #18: 0x0000000100006bf8 luajit`lj_gc_fullgc(L=0x0000000000042378) + 136 at lj_gc.c:743
    frame #19: 0x0000000100015ae8 luajit`lua_gc(L=0x0000000000042378, what=<unavailable>, data=<unavailable>) + 104 at lj_api.c:1155
    frame #20: 0x0000000100035c9b luajit`lj_cf_collectgarbage(L=0x0000000000042378) + 91 at lib_base.c:455
    frame #21: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #22: 0x00000001000155d6 luajit`lua_pcall(L=<unavailable>, nargs=<unavailable>, nresults=<unavailable>, errfunc=<unavailable>) + 182 at lj_api.c:1052
    frame #23: 0x00000001000020a9 luajit`docall(L=0x0000000000042378, narg=9, clear=0) + 89 at luajit.c:122
    frame #24: 0x00000001000018cd luajit`pmain [inlined] handle_script + 335 at luajit.c:289
    frame #25: 0x000000010000177e luajit`pmain(L=0x0000000000042378) + 1630 at luajit.c:538
    frame #26: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #27: 0x00000001000156e8 luajit`lua_cpcall(L=<unavailable>, func=<unavailable>, ud=<unavailable>) + 40 at lj_api.c:1074
    frame #28: 0x000000010000101b luajit`main(argc=11, argv=0x00007fff5fbfe800) + 59 at luajit.c:566
    frame #29: 0x0000000100000fb8 luajit`_start + 230
    frame #30: 0x0000000100000ed1 luajit`start + 33
```

(.6, dict item alloc/free)

```
* thread #1: tid = 0x0000, 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff984624ec libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9c5f16df libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffa0d06041 libsystem_malloc.dylib`free + 425
    frame #4: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #5: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #6: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #7: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #8: 0x0000000001b852b4 libnvim-test.so`xfree(ptr=0x00000000004091a0) + 36 at memory.c:130
    frame #9: 0x0000000001acfcb7 libnvim-test.so`_typval_encode_nothing_convert_one_value(ignored=0x0000000000000000, m
pstack=0x00007fff5fbfe010, cur_mpsv=0x0000000000000000, tv=0x00000000038c9238, copyID=52, objname="tv_clear() argument"
) + 151 at typval_encode.c.h:326
    frame #10: 0x0000000001acdf3a libnvim-test.so`encode_vim_to_nothing(ignored=0x0000000000000000, top_tv=0x0000000003
8c9238, objname="tv_clear() argument") + 154 at typval_encode.c.h:638
    frame #11: 0x0000000001aca278 libnvim-test.so`tv_clear(tv=0x00000000038c9238) + 72 at typval.c:1841
    frame #12: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #13: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #14: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #15: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #16: 0x000000010000616d luajit`gc_call_finalizer(g=0x00000000000423b8, L=0x0000000000042378, mo=<unavailable>, o=<unavailable>) + 189 at lj_gc.c:473
    frame #17: 0x0000000100005e9f luajit`gc_finalize(L=0x0000000000042378) + 271 at lj_gc.c:507
    frame #18: 0x000000010000695c luajit`gc_onestep(L=0x0000000000042378) + 1292 at lj_gc.c:654
    frame #19: 0x0000000100006bf8 luajit`lj_gc_fullgc(L=0x0000000000042378) + 136 at lj_gc.c:743
    frame #20: 0x0000000100015ae8 luajit`lua_gc(L=0x0000000000042378, what=<unavailable>, data=<unavailable>) + 104 at lj_api.c:1155
    frame #21: 0x0000000100035c9b luajit`lj_cf_collectgarbage(L=0x0000000000042378) + 91 at lib_base.c:455
    frame #22: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #23: 0x00000001000155d6 luajit`lua_pcall(L=<unavailable>, nargs=<unavailable>, nresults=<unavailable>, errfunc=<unavailable>) + 182 at lj_api.c:1052
    frame #24: 0x00000001000020a9 luajit`docall(L=0x0000000000042378, narg=9, clear=0) + 89 at luajit.c:122
    frame #25: 0x00000001000018cd luajit`pmain [inlined] handle_script + 335 at luajit.c:289
    frame #26: 0x000000010000177e luajit`pmain(L=0x0000000000042378) + 1630 at luajit.c:538
    frame #27: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #28: 0x00000001000156e8 luajit`lua_cpcall(L=<unavailable>, func=<unavailable>, ud=<unavailable>) + 40 at lj_api.c:1074
    frame #29: 0x000000010000101b luajit`main(argc=11, argv=0x00007fff5fbfe800) + 59 at luajit.c:566
    frame #30: 0x0000000100000fb8 luajit`_start + 230
    frame #31: 0x0000000100000ed1 luajit`start + 33
```

(.6, dict item add/remove)

```
* thread #1: tid = 0x0000, 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8ba29f06 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff984624ec libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9c5f16df libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffa0d06041 libsystem_malloc.dylib`free + 425
    frame #4: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #5: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #6: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #7: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #8: 0x0000000001b852b4 libnvim-test.so`xfree(ptr=0x0000000000106f80) + 36 at memory.c:130
    frame #9: 0x0000000001acfcb7 libnvim-test.so`_typval_encode_nothing_convert_one_value(ignored=0x0000000000000000, mpstack=0x00007fff5fbfe010, cur_mpsv=0x0000000000000000, tv=0x0000000002ea79d8, copyID=54, objname="tv_clear() argument") + 151 at typval_encode.c.h:326
    frame #10: 0x0000000001acdf3a libnvim-test.so`encode_vim_to_nothing(ignored=0x0000000000000000, top_tv=0x0000000002ea79d8, objname="tv_clear() argument") + 154 at typval_encode.c.h:638
    frame #11: 0x0000000001aca278 libnvim-test.so`tv_clear(tv=0x0000000002ea79d8) + 72 at typval.c:1841
    frame #12: 0x0000000100005bff luajit`lj_vm_ffi_call + 132
    frame #13: 0x0000000100029979 luajit`lj_ccall_func(L=<unavailable>, cd=<unavailable>) + 2473 at lj_ccall.c:878
    frame #14: 0x000000010003fa6e luajit`lj_cf_ffi_meta___call(L=0x0000000000042378) + 78 at lib_ffi.c:229
    frame #15: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #16: 0x000000010000616d luajit`gc_call_finalizer(g=0x00000000000423b8, L=0x0000000000042378, mo=<unavailable>, o=<unavailable>) + 189 at lj_gc.c:473
    frame #17: 0x0000000100005e9f luajit`gc_finalize(L=0x0000000000042378) + 271 at lj_gc.c:507
    frame #18: 0x000000010000695c luajit`gc_onestep(L=0x0000000000042378) + 1292 at lj_gc.c:654
    frame #19: 0x0000000100006bf8 luajit`lj_gc_fullgc(L=0x0000000000042378) + 136 at lj_gc.c:743
    frame #20: 0x0000000100015ae8 luajit`lua_gc(L=0x0000000000042378, what=<unavailable>, data=<unavailable>) + 104 at lj_api.c:1155
    frame #21: 0x0000000100035c9b luajit`lj_cf_collectgarbage(L=0x0000000000042378) + 91 at lib_base.c:455
    frame #22: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #23: 0x00000001000155d6 luajit`lua_pcall(L=<unavailable>, nargs=<unavailable>, nresults=<unavailable>, errfunc=<unavailable>) + 182 at lj_api.c:1052
    frame #24: 0x00000001000020a9 luajit`docall(L=0x0000000000042378, narg=9, clear=0) + 89 at luajit.c:122
    frame #25: 0x00000001000018cd luajit`pmain [inlined] handle_script + 335 at luajit.c:289
    frame #26: 0x000000010000177e luajit`pmain(L=0x0000000000042378) + 1630 at luajit.c:538
    frame #27: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #28: 0x00000001000156e8 luajit`lua_cpcall(L=<unavailable>, func=<unavailable>, ud=<unavailable>) + 40 at lj_api.c:1074
    frame #29: 0x000000010000101b luajit`main(argc=11, argv=0x00007fff5fbfe800) + 59 at luajit.c:566
    frame #30: 0x0000000100000fb8 luajit`_start + 230
    frame #31: 0x0000000100000ed1 luajit`start + 33
```

(.6, dict copy)

```
* thread #1: tid = 0x0000, 0x000000010003270b luajit`lj_alloc_free(msp=<unavailable>, ptr=<unavailable>) + 91 at lj_all
oc.c:1283, stop reason = signal SIGSTOP
  * frame #0: 0x000000010003270b luajit`lj_alloc_free(msp=<unavailable>, ptr=<unavailable>) + 91 at lj_alloc.c:1283
    frame #1: 0x0000000100032698 luajit`lj_alloc_f(msp=<unavailable>, ptr=<unavailable>, osize=<unavailable>, nsize=<un
available>) + 24 at lj_alloc.c:1388
    frame #2: 0x00000001000062de luajit`gc_sweep(g=0x00000000000423b8, p=<unavailable>, lim=<unavailable>) + 174 at lj_
gc.c:405
    frame #3: 0x00000001000068bd luajit`gc_onestep(L=0x0000000000042378) + 1133 at lj_gc.c:633
    frame #4: 0x0000000100006bf8 luajit`lj_gc_fullgc(L=0x0000000000042378) + 136 at lj_gc.c:743
    frame #5: 0x0000000100015ae8 luajit`lua_gc(L=0x0000000000042378, what=<unavailable>, data=<unavailable>) + 104 at l
j_api.c:1155
    frame #6: 0x0000000100035c9b luajit`lj_cf_collectgarbage(L=0x0000000000042378) + 91 at lib_base.c:455
    frame #7: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #8: 0x00000001000155d6 luajit`lua_pcall(L=<unavailable>, nargs=<unavailable>, nresults=<unavailable>, errfunc
=<unavailable>) + 182 at lj_api.c:1052
    frame #9: 0x00000001000020a9 luajit`docall(L=0x0000000000042378, narg=9, clear=0) + 89 at luajit.c:122
    frame #10: 0x00000001000018cd luajit`pmain [inlined] handle_script + 335 at luajit.c:289
    frame #11: 0x000000010000177e luajit`pmain(L=0x0000000000042378) + 1630 at luajit.c:538
    frame #12: 0x0000000100003cb7 luajit`lj_BC_FUNCC + 52
    frame #13: 0x00000001000156e8 luajit`lua_cpcall(L=<unavailable>, func=<unavailable>, ud=<unavailable>) + 40 at lj_api.c:1074
    frame #14: 0x000000010000101b luajit`main(argc=11, argv=0x00007fff5fbfe800) + 59 at luajit.c:566
    frame #15: 0x0000000100000fb8 luajit`_start + 230
    frame #16: 0x0000000100000ed1 luajit`start + 33
```

**Comment by ZyX-I** [comment]
And got an idea: unit tests do not need core dumps checking after each test, but that must be done after each failing test.

---

Only OS X fails on all those six tests and with core dumps. Linux: no core dumps, only two out of six tests failing.

**Comment by justinmk** [comment]
In recent PRs I noticed that "lint" build fails repeatedly unless I delete the travis cache for the given PR. Will the change to SUCCESS_MARKER fix that?

**Comment by ZyX-I** [comment]
@justinmk I am not sure. I noticed that lint tests never touched success marker, meaning that cache is not used. Since lint jobs need dependencies for quite some time I considered that to be not very good, but yet it did already save something to the cache.

**Comment by ZyX-I** [comment]
@justinmk  I am thinking about making test hang not fail the build. I.e. if check-single-includes happened to fail it should fail. If check-single-includes happened to hang it should be ignored.

**Comment by justinmk** [comment]
@ZyX-I :+1:

**Comment by ZyX-I** [comment]
Got

```
[ RUN      ] ./test/unit/helpers.lua @ 733: typval.c list copy() copies list correctly and converts items
./test/unit/helpers.lua:702: (string) '
...ravis/build/neovim/neovim/test/unit/eval/typval_spec.lua:774: Expected objects to be the same.
Passed in:
(table) {
  [1] = {
    [�] = '�' }
 *[2] = {
   *[1] = '„' }
  [3] = 1
  [4] = '“'
  [5] = {
    [true] = 'NULL string' }
  [6] = {
    [true] = 'NULL list' }
  [7] = {
    [true] = 'NULL dict' } }
Expected:
(table) {
  [1] = {
    [�] = '�' }
 *[2] = {
   *[1] = '�' }
  [3] = 1
  [4] = '�'
  [5] = {
    [true] = 'NULL string' }
  [6] = {
    [true] = 'NULL list' }
  [7] = {
    [true] = 'NULL dict' } }'

stack traceback:
        ./test/unit/helpers.lua:716: in function 'itp_parent'
        ./test/unit/helpers.lua:743: in function <./test/unit/helpers.lua:733>

[  FAILED  ] ./test/unit/helpers.lua @ 733: typval.c list copy() copies list correctly and converts items (89.93 ms)
```

from GCC Mac OS. No idea how one could make it succeed in other builds (including clang Mac OS) and fail there like this.

**Comment by ZyX-I** [comment]
Second build looks like spurious failure:

```
[       OK ] ...is/build/neovim/neovim/test/functional/core/job_spec.lua @ 291: jobs can omit exit callback (6.29 ms)


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by ZyX-I** [comment]
Third build has GC crash where Mac OS/gcc has strange failure.

**Comment by ZyX-I** [comment]
Still why there are no core dumps? Anybody had seen core dumps in linux builds recently?

**Comment by ZyX-I** [comment]
Note: temporary set NVIM_TEST_TRACE_LEVEL=2 in travis settings.

**Comment by justinmk** [comment]
> Anybody had seen core dumps in linux builds recently?

No.

**Comment by ZyX-I** [comment]
Got memory corruption in malloc() wrapper in the third build. This is not making much sense. Though this should be something related to vimconv_T: happens only for tests with conversion. Happens on next allocation after allocating vimconv_T.

Can only suspect that luajit may think that iconv is not available, while it actually is resulting in allocating less memory then needed.

**Comment by ZyX-I** [comment]
Also found that my code may leak whatever resources are pointed to by `iconv_t`.

**Comment by ZyX-I** [comment]
Yes, luajit thinks that there is no vc_fd. But it should be there if I understand right: iconv was found, as well as iconv.h.

**Comment by ZyX-I** [comment]
Luajit simply preprocesses without HAVE_CONFIG_H defined. I do not see why this define needs to be there in the first place, so in place of altering preprocess.lua will remove HAVE_CONFIG_H.

**Comment by ZyX-I** [comment]
Should be ready now.

**Pull request merged**
