### PR TITLE
[wip] ci: add nixos

### PR DESCRIPTION
**Pull request by teto**
shouldn't matter if it fails.

### CODE REVIEW

**Comment by justinmk** [comment]
nice. merge it?

**Comment by teto** [comment]
nope, it' not finished, but the jobs don't appear in the github checks (contrary to BSD ones). Did you do something special to enable the *BSD appear ?

**Comment by justinmk** [comment]
> Did you do something special to enable the *BSD appear ?

i don't think so. and i just checked on sourcehut and didn't find any buttons related to that.

i pasted the yml from this PR into the sourcehut one-off build request form, here's the result: https://builds.sr.ht/~jmk/job/290778

**Comment by teto** [comment]
now that we have a nix flake it's trivial to run on nixos, and I can just update the flake instead. Closing.

**Pull request closed without merging**
