### PR TITLE
vim-patch:8.2.3238: Julia filetype not recognized

### PR DESCRIPTION
**Pull request by clason**
Problem:    Julia filetype is not recognized
Solution:   Add filetype detection. (Christian Clason, closes #8700)

includes corresponding runtime files scheduled for next update (https://github.com/vim/vim/pull/8700)

issue: https://github.com/vim/vim/issues/7498
vim-patch: https://github.com/vim/vim/commit/0eec8519424eaea7baebfda979c33dd609a4e3fa

### CODE REVIEW

**Review by janlazo — CHANGES_REQUESTED** [review]
https://github.com/vim/vim/tree/v8.2.3283 is the Julia patch. Runtime-only patches must be in separate commits.

**Comment by clason** [comment]
So you want me to wait with this until Bram makes the next batch runtime update?

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/14950 You ported the vim syntax separately in here. Do the same for Julia.

**Comment by clason** [comment]
I did no such thing :)

**Comment by clason** [comment]
(That was a different situation: cherry-picking a single runtime file from a batch update.)

**Comment by clason** [comment]
But OK, I'll wait, no problem.

**Pull request closed without merging**
