### PR TITLE
Updated diff.txt text in help.

### PR DESCRIPTION
**Pull request by dundargoc**
Max number of diffs should be eight according to the help section for
diff.txt.

### CODE REVIEW

**Comment by janlazo** [comment]
This should be upstreamed first.

**Comment by DundarGoc** [comment]
@janlazo: I've sent a pull request upstream to the official vim repo. Should I close this one?

**Comment by DundarGoc** [comment]
I'll close this issue for now. I've added a pull request upstream so the fix should eventually come to neovim if they choose to accept it.

**Comment by DundarGoc** [comment]
I'll close this issue for now. I've added a pull request upstream so the fix should eventually come to neovim if they choose to accept it.

**Pull request closed without merging**
