### PR TITLE
[WIP] vim-patch:8.0.{1438,1457,1458,1465},8.1.{484,498}

### LINKED ISSUE #3568: filetype.vim doesn't match /etc/gitconfig
`/etc/gitconfig` is a valid global git configuration file, certainly less frequently used than user git configuration files.  (See https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup numbered list 1.)

Editing it (even with root having syntax highlighting) does not syntax highlight the file.

This is because `filetype.vim` has this code for matching filetype `gitconfig`:

```
au BufNewFile,BufRead *.git/config,.gitconfig,.gitmodules setf gitconfig
au BufNewFile,BufRead *.git/modules/*/config setf gitconfig
au BufNewFile,BufRead */.config/git/config   setf gitconfig
```

Adding an extra line fixes this issue:

`au BufNewFile,BufRead /etc/gitconfig   setf gitconfig`

Notably, the comments in `syntax/gitconfig.vim` already reference this file:

`" Filenames:   gitconfig, .gitconfig, *.git/config
`

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.1438: filetype detection test not updated for change**

Problem:    Filetype detection test not updated for change.
Solution:   Update the test.
https://github.com/vim/vim/commit/0479e910c423d71e2b96bc721feffad5808e767a

**vim-patch:8.0.1457: clojure now supports a shebang line**

Problem:    Clojure now supports a shebang line.
Solution:   Detect clojure script from the shebang line. (David Burgin,
            closes vim/vim#2570)
vim/vim@8fd2ffc

**vim-patch:8.0.1458: filetype detection test does not check all scripts**

Problem:    Filetype detection test does not check all scripts.
Solution:   Add most scripts to the test
vim/vim@ddb3493

**vim-patch:8.0.1465: python2 and python3 detection not tested**

Problem:    Python2 and python3 detection not tested. (Matej Cepl)
Solution:   Add test for detecting python2 and python3.  Also detect a script
            using "js" as javascript.
vim/vim@4bc0bed

**vim-patch:8.1.0484: some file types are not recognized**

Problem:    Some file types are not recognized.
Solution:   Update the file type detection.
vim/vim@3865450

**vim-patch:8.1.0498: /etc/gitconfig not recognized at a gitconfig file**

Problem:    /etc/gitconfig not recognized at a gitconfig file.
Solution:   Add pattern to filetype detection. (closes vim/vim#3568)
vim/vim@d474686

### CODE REVIEW

**Comment by janlazo** [comment]
Need `runtime/filetyp.vim` changes from https://github.com/vim/vim/commit/40962ec9c0e7b8699e101182b06ddd39dc0e1212

**Comment by justinmk** [comment]
@janlazo i'll do a batch of runtime updates in the next day or so.

**Comment by janlazo** [comment]
Any blockers for batching `runtime/` patches up to https://github.com/vim/vim/commit/40962ec9c0e7b8699e101182b06ddd39dc0e1212?

**Comment by justinmk** [comment]
@janlazo see https://github.com/neovim/neovim/pull/9164

**Pull request merged**
