### PR TITLE
Stop terminal buffers from dropping data

### PR DESCRIPTION
**Pull request by radenling**
This should solve the part of #3030 where it cuts off the process output.

### CODE REVIEW

**Comment by brcolow** [comment]
Have you tried contributing this fix to upstream?

**Comment by radenling** [comment]
No, I haven't had time to look into that yet.

**Comment by radenling** [comment]
There doesn't seem to be a good way to apply patches in windows (for which the build fails) so I'll close this and see if I can submit it upstream instead.

**Comment by brcolow** [comment]
If you do, and it would be greatly appreciate if so, can you link this PR to it? Thanks!

**Pull request closed without merging**
