### PR TITLE
ci: AppVeyor: branches: only: master  [skip travis]

### PR DESCRIPTION
**Pull request by blueyed**
Only build PRs for master, and not other branches on the main repo, e.g.
when reverting via GitHub's UI.

Ref: https://www.appveyor.com/docs/branches/

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
@blueyed Reverted. Seems to skip tags also, which breaks our release automation.

https://github.com/neovim/neovim/commit/f9d1e788af45db381b1a228ddb445cd3d354c9a3

**Comment by blueyed** [comment]
@justinmk 
I guess it would need to look like with Travis then:
```
branches:
  only:
    - master
    - /^release-\d+\.\d+$/
```

**Comment by justinmk** [comment]
It needs to match tags as well

**Comment by blueyed** [comment]
@justinmk 
No, it must match the target branch - at least that's how it works on Travis.

Anyway, not a big deal - but I've done it initially to avoid extra builds when reverting via UI (especially since I still cancel AppVeyor builds, and this adds like 1h to the queue).  But not something that we're meant to do (often).

**Pull request merged**
