### PR TITLE
vim-patch:9.0.1268: .clangd and .stylelintrc files don't get a filetype

### PR DESCRIPTION
**Pull request by clason**
Problem:    .clangd and .stylelintrc files don't get a filetype.
Solution:   Use yaml for .clangd and json for .stylelintrc files. (Mark
            Skelton, closes vim/vim#11916)

https://github.com/vim/vim/commit/9c51798a1f3b79ace5ae0551a8bb122025ac94ed

Co-authored-by: Mark Skelton <mdskelton99@gmail.com>

### CODE REVIEW

**Review by zeertzjq — COMMENTED** [review]
missing test for `.stylelintrc`

**Comment by clason** [comment]
Strange that vim-patch missed that!

**Review by zeertzjq — COMMENTED** [review]
```
with file name: .stylelintrc: Expected 'json' but got 'jsonc'
```

**Comment by clason** [comment]
That was my bad (shouldn't try to do this before my first coffee...)

**Review by zeertzjq — APPROVED** [review]

**Review by smjonas — APPROVED** [review]

**Pull request merged**
