### PR TITLE
[RDY] Fix typo: s/_nable_/_enable_/

### PR DESCRIPTION
**Pull request by ilAYAli**

### CODE REVIEW

**Comment by dm1try** [comment]
it looks Vim's heritage and it might not be a typo.
there is a possibility what the author of the code used such name to express the action of switching some menu state `menu_enable_recurse/menu_disable_recurse`

though, I would name it like `menu_set_availability`(or similar, it depends on the state which is changing)

**Comment by justinmk** [comment]
@dm1try that's a good thought and reminds me of the ["halfway" change](https://github.com/neovim/neovim/pull/1850) (which I think we shouldn't have done). But in this case I think it should be "enable".

@ilAYAli can you fix the `make lint` errors? The linter checks adjacent lines (cascading).

**Comment by dm1try** [comment]
> But in this case I think it should be "enable".

 It some kind of the cognitive dissonance for me) because the function can also disable the things
```c
/* Set the (sub)menu with the given name to enabled or disabled.
* Called recursively.
*/
static int menu_nable_recurse(vimmenu_T *menu, char_u *name, int modes, int enable)
```

I've read the implementation and think that it should be named `menu_update_modes` or `menu_modes_onoff`

but because it's not some public API, it's not a big deal for me(as I've already read the implementation :) ).

**Comment by justinmk** [comment]
> It's some kind of the cognitive dissonance for me) because the function can also disable the things

`setFooEnabled()` is very common in Java. 

> I've read the implementation and think that it should be named menu_update_modes or menu_modes_onoff

That loses the "recursive" hint which can be valuable.

**Pull request merged**
