### PR TITLE
refactor(lua): get all extmarks instead of iterating over namespaces

### LINKED ISSUE #22732: `vim.inspect_pos`, `vim.show_pos`, etc.: Can we include buffer-local highlights as well?
### Problem

#21393 added a new API `vim.inspect_pos`, `vim.show_pos`, `:Inspect` which shows:

- Treesitter captures
- Semantic Tokens
- Syntax Highlight Groups
- Extmarks

at some cursor location. While I find this great, but there's one missing item worth including which is buffer-local highlights added through `nvim_buf_add_highlight`. It would be great if we can show what buffer-local highlight items are applied at the current cursor location; it will help develop plugins that involve buffer-local highlights.

### Example

For example, I have a python file where [semshi](https://github.com/wookayin/semshi) adds some buffer-local highlight for semantic tokens:

image

which are highlighted by `semshiImported` hlgroup (which was added via `nvim_buf_add_highlight`)

image

but `vim.inspect_pos()` and `:Inspect` give no information
```
{                              
  buffer = 7,
  col = 7,
  extmarks = {},
  row = 5,
  semantic_tokens = {},
  syntax = {},
  treesitter = {}
}
```

### Expected behavior

Buffer-local highlight groups applied should be also included into the output of `vim.inspect_pos`, `vim.show_pos`, `:Inspect`, etc.

### PR DESCRIPTION
**Pull request by luukvbaal**
Inspector now also includes highlights set in anonymous namespaces.

Close #22732

### CODE REVIEW

**Comment by bfredl** [comment]
Needs a rebase.

**Comment by luukvbaal** [comment]
We now need a name space id->name map in `show_pos()` since the name was not added to the details dict. Do we bother caching this?

**Comment by bfredl** [comment]
`inspect` doesn't need to be hyper-optimized. it is fine to query all namespaces and reverse the mapping each time (so no cache).

**Comment by luukvbaal** [comment]
> Inspector now also includes highlights set in anonymous namespaces.

Added a regression test to attest this.

**Pull request merged**
