### PR TITLE
viml/reltime(): allow negative result

### LINKED ISSUE #10452: reltimestr(reltime(newer_time, older_time)) does not return negative number
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tWk8pe/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wn
o-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-tWk8pe/neovim-0.3.4/build/confi
g -I/build/neovim-tWk8pe/neovim-0.3.4/src -I/usr/include -I/build/neovim-tWk8pe/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-tWk8pe/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce using `nvim -u NORC`

```
let older_time = reltime()
sleep 1m
let newer_time = reltime()
echo reltimestr(reltime(newer_time, older_time))
```

### Actual behaviour
 Very large positive number.

### Expected behaviour
Very small negative number.

I see other issues around the handling of a single `reltime()` which have been correctly closed as wontfix, but the end result of a comparison should be the same for all Vim implementations, no?

### PR DESCRIPTION
**Pull request by justinmk**
- define proftime_T as signed integer
- profile_sub(): allow negative result

closes #10452

### CODE REVIEW

**Comment by blueyed** [comment]
So the case of "os_utime() may go backwards" is OK (ignored) then I assume?

```c
uint64_t uv_hrtime(void) {
  return uv__hrtime(UV_CLOCK_PRECISE);
}
```

Have you considered `uv__hrtime(UV_CLOCK_FAST)` ?
Ref: https://github.com/libuv/libuv/blob/988091dada1c9cbe4d4b88b1844ac6f2ad99d0ef/src/unix/linux-core.c#L426-L456

(it would use `CLOCK_MONOTONIC_COARSE`, but then is Linux specific, and also affected by "quirks" (I understood))

So using `uv_gettimeofday` seems fine, but we should bump the minimum libuv version then (it is quite recent, from April).

**Comment by justinmk** [comment]
> Have you considered `uv__hrtime(UV_CLOCK_FAST)` ?

`uv__` (double underscore) functions are private API.

**Comment by blueyed** [comment]
Sure.  Might be either wrapped/exposed then maybe - I've just wondered if the mechanism of it was considered.

**Comment by aktau** [comment]
I think we should go back to using monotonic time: the `gettimeofday` patch didn't help and causes needless workarounds because it is not monotonic: https://github.com/neovim/neovim/issues/10328#issuecomment-510386392.

**Pull request merged**
