### PR TITLE
[RFC] vim-patch:7.4.{785,795,898}

### PR DESCRIPTION
**Pull request by johanhelsing**
```
Problem:    On some systems automatically adding the missing EOL causes
            problems. Setting 'binary' has too many side effects.
Solution:   Add the 'fixeol' option, default on. (Pavel Samarkin)
```

https://github.com/vim/vim/commit/34d72d4b6c1a2b04a214d8a49b7d22c97bc7a8bc

Original patch:

``` diff
commit 34d72d4b6c1a2b04a214d8a49b7d22c97bc7a8bc
Author: Bram Moolenaar <Bram@vim.org>
Date:   Fri Jul 17 14:18:08 2015 +0200

    patch 7.4.785
    Problem:    On some systems automatically adding the missing EOL causes
                problems. Setting 'binary' has too many side effects.
    Solution:   Add the 'fixeol' option, default on. (Pavel Samarkin)

diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 209e1ba..3b3e104 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -1,4 +1,4 @@
-*options.txt*  For Vim version 7.4.  Last change: 2015 Jul 10
+*options.txt*  For Vim version 7.4.  Last change: 2015 Jul 17


          VIM REFERENCE MANUAL    by Bram Moolenaar
@@ -2671,15 +2671,16 @@ A jump table for the options with a short description can be found at |Q_op|.
            local to buffer
            {not in Vi}
    When writing a file and this option is off and the 'binary' option
-   is on, no <EOL> will be written for the last line in the file.  This
-   option is automatically set when starting to edit a new file, unless
-   the file does not have an <EOL> for the last line in the file, in
-   which case it is reset.  Normally you don't have to set or reset this
-   option.  When 'binary' is off the value is not used when writing the
-   file.  When 'binary' is on it is used to remember the presence of a
-   <EOL> for the last line in the file, so that when you write the file
-   the situation from the original file can be kept.  But you can change
-   it if you want to.
+   is on, or 'fixeol' option is off, no <EOL> will be written for the
+   last line in the file.  This option is automatically set or reset when
+   starting to edit a new file, depending on whether file has an <EOL>
+   for the last line in the file.  Normally you don't have to set or
+   reset this option.
+   When 'binary' is off and 'fixeol' is on the value is not used when
+   writing the file.  When 'binary' is on or 'fixeol' is off it is used
+   to remember the presence of a <EOL> for the last line in the file, so
+   that when you write the file the situation from the original file can
+   be kept.  But you can change it if you want to.

                 *'equalalways'* *'ea'* *'noequalalways'* *'noea'*
 'equalalways' 'ea' boolean (default on)
@@ -3064,6 +3065,17 @@ A jump table for the options with a short description can be found at |Q_op|.
      fold:c    Folded          |hl-Folded|
      diff:c    DiffDelete      |hl-DiffDelete|

+       *'fixendofline'* *'fixeol'* *'nofixendofline'* *'nofixeol'*
+'fixendofline' 'fixeol'    boolean (default on)
+           local to buffer
+           {not in Vi}
+   When writing a file and this option is on, <EOL> at the end of file
+   will be restored if missing. Turn this option off if you want to
+   preserve the situation from the original file.
+   When the 'binary' option is set the value of this option doesn't
+   matter.
+   See the 'endofline' option.
+
                    *'fkmap'* *'fk'* *'nofkmap'* *'nofk'*
 'fkmap' 'fk'       boolean (default off)           *E198*
            global
diff --git a/runtime/optwin.vim b/runtime/optwin.vim
index 55353ce..921ae36 100644
--- a/runtime/optwin.vim
+++ b/runtime/optwin.vim
@@ -954,6 +954,9 @@ call <SID>BinOptionL("bin")
 call append("$", "endofline\tlast line in the file has an end-of-line")
 call append("$", "\t(local to buffer)")
 call <SID>BinOptionL("eol")
+call append("$", "fixeol\tfixes missing end-of-line at end of text file")
+call append("$", "\t(local to buffer)")
+call <SID>BinOptionL("fixeol")
 if has("multi_byte")
   call append("$", "bomb\tprepend a Byte Order Mark to the file")
   call append("$", "\t(local to buffer)")
diff --git a/src/nvim/buffer.c b/src/nvim/buffer.c
index 97c6596..c4d5e34 100644
--- a/src/nvim/buffer.c
+++ b/src/nvim/buffer.c
@@ -547,6 +547,7 @@ buf_clear_file(buf)
     buf->b_shortname = FALSE;
 #endif
     buf->b_p_eol = TRUE;
+    buf->b_p_fixeol = TRUE;
     buf->b_start_eol = TRUE;
 #ifdef FEAT_MBYTE
     buf->b_p_bomb = FALSE;
diff --git a/src/nvim/fileio.c b/src/nvim/fileio.c
index 9965920..fb14dbf 100644
--- a/src/nvim/fileio.c
+++ b/src/nvim/fileio.c
@@ -2623,10 +2623,10 @@ failed:
 #endif

     /*
-     * Trick: We remember if the last line of the read didn't have
-     * an eol even when 'binary' is off, for when writing it again with
-     * 'binary' on.  This is required for
-     * ":autocmd FileReadPost *.gz set bin|'[,']!gunzip" to work.
+     * We remember if the last line of the read didn't have
+     * an eol even when 'binary' is off, to support turning 'fixeol' off,
+     * or writing the read again with 'binary' on.  The latter is required
+     * for ":autocmd FileReadPost *.gz set bin|'[,']!gunzip" to work.
      */
     curbuf->b_no_eol_lnum = read_no_eol_lnum;

@@ -4547,7 +4547,7 @@ restore_backup:
    /* write failed or last line has no EOL: stop here */
    if (end == 0
        || (lnum == end
-           && write_bin
+           && (write_bin || !buf->b_p_fixeol)
            && (lnum == buf->b_no_eol_lnum
            || (lnum == buf->b_ml.ml_line_count && !buf->b_p_eol))))
    {
diff --git a/src/nvim/memline.c b/src/nvim/memline.c
index 91ef270..8cd9b80 100644
--- a/src/nvim/memline.c
+++ b/src/nvim/memline.c
@@ -5361,8 +5361,10 @@ ml_find_line_or_offset(buf, lnum, offp)
    if (ffdos)
        size += lnum - 1;

-   /* Don't count the last line break if 'bin' and 'noeol'. */
-   if (buf->b_p_bin && !buf->b_p_eol && buf->b_ml.ml_line_count == lnum)
+   /* Don't count the last line break if 'noeol' and ('bin' or
+    * 'nofixeol'). */
+   if ((!buf->b_p_fixeol || buf->b_p_bin) && !buf->b_p_eol
+                      && buf->b_ml.ml_line_count == lnum)
        size -= ffdos + 1;
     }

diff --git a/src/nvim/netbeans.c b/src/nvim/netbeans.c
index 68ca301..ea0c017 100644
--- a/src/nvim/netbeans.c
+++ b/src/nvim/netbeans.c
@@ -3802,7 +3802,7 @@ get_buf_size(buf_T *bufp)
        }
    }
    /* Correction for when last line doesn't have an EOL. */
-   if (!bufp->b_p_eol && bufp->b_p_bin)
+   if (!bufp->b_p_eol && (bufp->b_p_bin || !bufp->b_p_fixeol))
        char_count -= eol_size;
     }

diff --git a/src/nvim/ops.c b/src/nvim/ops.c
index 7ad8222..3441f05 100644
--- a/src/nvim/ops.c
+++ b/src/nvim/ops.c
@@ -7052,7 +7052,7 @@ cursor_pos_info()
                       &char_count_cursor, len, eol_size);
            if (lnum == curbuf->b_ml.ml_line_count
                && !curbuf->b_p_eol
-               && curbuf->b_p_bin
+               && (curbuf->b_p_bin || !curbuf->b_p_fixeol)
                && (long)STRLEN(s) < len)
            byte_count_cursor -= eol_size;
        }
@@ -7076,7 +7076,7 @@ cursor_pos_info()
    }

    /* Correction for when last line doesn't have an EOL. */
-   if (!curbuf->b_p_eol && curbuf->b_p_bin)
+   if (!curbuf->b_p_eol && (curbuf->b_p_bin || !curbuf->b_p_fixeol))
        byte_count -= eol_size;

    if (VIsual_active)
diff --git a/src/nvim/option.c b/src/nvim/option.c
index 2e805d7..40dcc8d 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -98,6 +98,7 @@
 # define PV_INC        OPT_BOTH(OPT_BUF(BV_INC))
 #endif
 #define PV_EOL     OPT_BUF(BV_EOL)
+#define PV_FIXEOL  OPT_BUF(BV_FIXEOL)
 #define PV_EP      OPT_BOTH(OPT_BUF(BV_EP))
 #define PV_ET      OPT_BUF(BV_ET)
 #ifdef FEAT_MBYTE
@@ -306,6 +307,7 @@ static char_u   *p_cfu;
 static char_u  *p_ofu;
 #endif
 static int p_eol;
+static int p_fixeol;
 static int p_et;
 #ifdef FEAT_MBYTE
 static char_u  *p_fenc;
@@ -1169,6 +1171,9 @@ static struct vimoption
                {(char_u *)"", (char_u *)0L}
 #endif
                SCRIPTID_INIT},
+    {"fixendofline",  "fixeol", P_BOOL|P_VI_DEF|P_RSTAT,
+               (char_u *)&p_fixeol, PV_FIXEOL,
+               {(char_u *)TRUE, (char_u *)0L} SCRIPTID_INIT},
     {"fkmap",      "fk",   P_BOOL|P_VI_DEF,
 #ifdef FEAT_FKMAP
                (char_u *)&p_fkmap, PV_NONE,
@@ -7781,6 +7786,11 @@ set_bool_option(opt_idx, varp, value, opt_flags)
     {
    redraw_titles();
     }
+    /* when 'fixeol' is changed, redraw the window title */
+    else if ((int *)varp == &curbuf->b_p_fixeol)
+    {
+   redraw_titles();
+    }
 # ifdef FEAT_MBYTE
     /* when 'bomb' is changed, redraw the window title and tab page text */
     else if ((int *)varp == &curbuf->b_p_bomb)
@@ -10176,6 +10186,7 @@ get_varp(p)
    case PV_OFU:    return (char_u *)&(curbuf->b_p_ofu);
 #endif
    case PV_EOL:    return (char_u *)&(curbuf->b_p_eol);
+   case PV_FIXEOL: return (char_u *)&(curbuf->b_p_fixeol);
    case PV_ET: return (char_u *)&(curbuf->b_p_et);
 #ifdef FEAT_MBYTE
    case PV_FENC:   return (char_u *)&(curbuf->b_p_fenc);
@@ -11894,6 +11905,7 @@ save_file_ff(buf)
  * from when editing started (save_file_ff() called).
  * Also when 'endofline' was changed and 'binary' is set, or when 'bomb' was
  * changed and 'binary' is not set.
+ * Also when 'endofline' was changed and 'fixeol' is not set.
  * When "ignore_empty" is true don't consider a new, empty buffer to be
  * changed.
  */
@@ -11912,7 +11924,7 @@ file_ff_differs(buf, ignore_empty)
    return FALSE;
     if (buf->b_start_ffc != *buf->b_p_ff)
    return TRUE;
-    if (buf->b_p_bin && buf->b_start_eol != buf->b_p_eol)
+    if ((buf->b_p_bin || !buf->b_p_fixeol) && buf->b_start_eol != buf->b_p_eol)
    return TRUE;
 #ifdef FEAT_MBYTE
     if (!buf->b_p_bin && buf->b_start_bomb != buf->b_p_bomb)
diff --git a/src/nvim/option.h b/src/nvim/option.h
index 7c7d35a..819473b 100644
--- a/src/nvim/option.h
+++ b/src/nvim/option.h
@@ -962,6 +962,7 @@ enum
     , BV_INC
 #endif
     , BV_EOL
+    , BV_FIXEOL
     , BV_EP
     , BV_ET
     , BV_FENC
diff --git a/src/nvim/os_unix.c b/src/nvim/os_unix.c
index 57c013f..f53faa3 100644
--- a/src/nvim/os_unix.c
+++ b/src/nvim/os_unix.c
@@ -4624,7 +4624,8 @@ mch_call_shell(cmd, options)
                /* Finished a line, add a NL, unless this line
                 * should not have one. */
                if (lnum != curbuf->b_op_end.lnum
-                   || !curbuf->b_p_bin
+                   || (!curbuf->b_p_bin
+                       && curbuf->b_p_fixeol)
                    || (lnum != curbuf->b_no_eol_lnum
                        && (lnum !=
                            curbuf->b_ml.ml_line_count
diff --git a/src/nvim/os_win32.c b/src/nvim/os_win32.c
index b50ab95..1e1214b 100644
--- a/src/nvim/os_win32.c
+++ b/src/nvim/os_win32.c
@@ -4173,7 +4173,8 @@ sub_process_writer(LPVOID param)
        /* Finished a line, add a NL, unless this line should not have
         * one. */
        if (lnum != curbuf->b_op_end.lnum
-       || !curbuf->b_p_bin
+       || (!curbuf->b_p_bin
+           && curbuf->b_p_fixeol)
        || (lnum != curbuf->b_no_eol_lnum
            && (lnum != curbuf->b_ml.ml_line_count
            || curbuf->b_p_eol)))
diff --git a/src/nvim/structs.h b/src/nvim/structs.h
index fedd3b9..2c7f710 100644
--- a/src/nvim/structs.h
+++ b/src/nvim/structs.h
@@ -635,7 +635,7 @@ typedef struct memline
     int        ml_flags;

     infoptr_T  *ml_stack;  /* stack of pointer blocks (array of IPTRs) */
-    int        ml_stack_top;   /* current top if ml_stack */
+    int        ml_stack_top;   /* current top of ml_stack */
     int        ml_stack_size;  /* total number of entries in ml_stack */

     linenr_T   ml_line_lnum;   /* line number of cached line, 0 if not valid */
@@ -1586,6 +1586,7 @@ struct file_buffer
     char_u *b_p_ofu;   /* 'omnifunc' */
 #endif
     int        b_p_eol;    /* 'endofline' */
+    int        b_p_fixeol; /* 'fixendofline' */
     int        b_p_et;     /* 'expandtab' */
     int        b_p_et_nobin;   /* b_p_et saved for binary mode */
 #ifdef FEAT_MBYTE
diff --git a/src/nvim/testdir/Make_amiga.mak b/src/nvim/testdir/Make_amiga.mak
index eba28f8..da47989 100644
--- a/src/nvim/testdir/Make_amiga.mak
+++ b/src/nvim/testdir/Make_amiga.mak
@@ -45,6 +45,7 @@ SCRIPTS = test1.out test3.out test4.out test5.out test6.out \
        test_command_count.out \
        test_erasebackword.out \
        test_eval.out \
+       test_fixeol.out \
        test_increment.out \
        test_insertcount.out \
        test_listchars.out \
@@ -195,6 +196,7 @@ test_command_count.out: test_command_count.in
 test_erasebackword.out: test_erasebackword.in
 test_eval.out: test_eval.in
 test_increment.out: test_increment.in
+test_fixeol.out: test_fixeol.in
 test_insertcount.out: test_insertcount.in
 test_listchars.out: test_listchars.in
 test_listlbr.out: test_listlbr.in
diff --git a/src/nvim/testdir/Make_dos.mak b/src/nvim/testdir/Make_dos.mak
index eecb735..6bb0577 100644
--- a/src/nvim/testdir/Make_dos.mak
+++ b/src/nvim/testdir/Make_dos.mak
@@ -44,6 +44,7 @@ SCRIPTS = test3.out test4.out test5.out test6.out test7.out \
        test_command_count.out \
        test_erasebackword.out \
        test_eval.out \
+       test_fixeol.out \
        test_increment.out \
        test_insertcount.out \
        test_listchars.out \
diff --git a/src/nvim/testdir/Make_ming.mak b/src/nvim/testdir/Make_ming.mak
index 29d931d..faa2294 100644
--- a/src/nvim/testdir/Make_ming.mak
+++ b/src/nvim/testdir/Make_ming.mak
@@ -66,6 +66,7 @@ SCRIPTS = test3.out test4.out test5.out test6.out test7.out \
        test_command_count.out \
        test_erasebackword.out \
        test_eval.out \
+       test_fixeol.out \
        test_increment.out \
        test_insertcount.out \
        test_listchars.out \
diff --git a/src/nvim/testdir/Make_os2.mak b/src/nvim/testdir/Make_os2.mak
index f473d89..b93408c 100644
--- a/src/nvim/testdir/Make_os2.mak
+++ b/src/nvim/testdir/Make_os2.mak
@@ -46,6 +46,7 @@ SCRIPTS = test1.out test3.out test4.out test5.out test6.out \
        test_command_count.out \
        test_erasebackword.out \
        test_eval.out \
+       test_fixeol.out \
        test_increment.out \
        test_insertcount.out \
        test_listchars.out \
diff --git a/src/nvim/testdir/Make_vms.mms b/src/nvim/testdir/Make_vms.mms
index 437f9b1..1c6a56d 100644
--- a/src/nvim/testdir/Make_vms.mms
+++ b/src/nvim/testdir/Make_vms.mms
@@ -4,7 +4,7 @@
 # Authors: Zoltan Arpadffy, <arpadffy@polarhome.com>
 #      Sandor Kopanyi,  <sandor.kopanyi@mailbox.hu>
 #
-# Last change:  2015 Jul 10
+# Last change:  2015 Jul 17
 #
 # This has been tested on VMS 6.2 to 8.3 on DEC Alpha, VAX and IA64.
 # Edit the lines in the Configuration section below to select.
@@ -105,6 +105,7 @@ SCRIPT = test1.out  test2.out  test3.out  test4.out  test5.out  \
     test_command_count.out \
     test_erasebackword.out \
     test_eval.out \
+    test_fixeol.out \
     test_increment.out \
     test_insertcount.out \
     test_listchars.out \
diff --git a/src/nvim/testdir/Makefile b/src/nvim/testdir/Makefile
index 656a744..1a3ff85 100644
--- a/src/nvim/testdir/Makefile
+++ b/src/nvim/testdir/Makefile
@@ -42,6 +42,7 @@ SCRIPTS = test1.out test2.out test3.out test4.out test5.out test6.out \
        test_command_count.out \
        test_erasebackword.out \
        test_eval.out \
+       test_fixeol.out \
        test_increment.out \
        test_insertcount.out \
        test_listchars.out \
diff --git a/src/nvim/testdir/test_fixeol.in b/src/nvim/testdir/test_fixeol.in
new file mode 100644
index 0000000..a881fb1
--- /dev/null
+++ b/src/nvim/testdir/test_fixeol.in
@@ -0,0 +1,40 @@
+Tests for 'fixeol'                         vim: set ft=vim :
+ 
+STARTTEST
+:" first write two test files – with and without trailing EOL
+:" use Unix fileformat for consistency
+:set ff=unix
+:enew!
+awith eol:w! XXEol
+:enew!
+:set noeol nofixeol
+awithout eol:w! XXNoEol
+:set eol fixeol
+:bwipe XXEol XXNoEol
+:"
+:" try editing files with 'fixeol' disabled
+:e! XXEol
+ostays eol:set nofixeol
+:w! XXTestEol
+:e! XXNoEol
+ostays without:set nofixeol
+:w! XXTestNoEol
+:bwipe XXEol XXNoEol XXTestEol XXTestNoEol
+:set fixeol
+:"
+:" Append "END" to each file so that we can see what the last written char was.
+ggdGaEND:w >>XXEol
+:w >>XXNoEol
+:w >>XXTestEol
+:w >>XXTestNoEol
+:"
+:" Concatenate the results
+:e! test.out
+a0:$r XXEol
+:$r XXNoEol
+Go1:$r XXTestEol
+:$r XXTestNoEol
+:w
+:qa!
+ENDTEST
+
diff --git a/src/nvim/testdir/test_fixeol.ok b/src/nvim/testdir/test_fixeol.ok
new file mode 100644
index 0000000..68ac9be
--- /dev/null
+++ b/src/nvim/testdir/test_fixeol.ok
@@ -0,0 +1,10 @@
+0
+with eol
+END
+without eolEND
+1
+with eol
+stays eol
+END
+without eol
+stays withoutEND
diff --git a/src/nvim/version.c b/src/nvim/version.c
index 4907d68..27a19ad 100644
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    785,
+/**/
     784,
 /**/
     783,
```

```
Problem:    The 'fixeol' option is not copied to a new window.
Solution:   Copy the option value. (Yasuhiro Matsumoto)
```

https://github.com/vim/vim/commit/b388be0abf04bba744f390587e8293bfbb1708a4

Original patch:

``` diff
commit b388be0abf04bba744f390587e8293bfbb1708a4
Author: Bram Moolenaar <Bram@vim.org>
Date:   Wed Jul 22 22:19:38 2015 +0200

    patch 7.4.795
    Problem:    The 'fixeol' option is not copied to a new window.
    Solution:   Copy the option value. (Yasuhiro Matsumoto)

diff --git a/src/nvim/option.c b/src/nvim/option.c
index b0f28d2..8e5021c 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -10659,6 +10659,7 @@ buf_copy_options(buf, flags)
 #ifdef FEAT_MBYTE
        buf->b_p_bomb = p_bomb;
 #endif
+       buf->b_p_fixeol = p_fixeol;
        buf->b_p_et = p_et;
        buf->b_p_et_nobin = p_et_nobin;
        buf->b_p_ml = p_ml;
diff --git a/src/nvim/version.c b/src/nvim/version.c
index a29c9fb..7cea9b1 100644
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    795,
+/**/
     794,
 /**/
     793,
```

```
Problem:    The 'fixendofline' option is set on with ":edit".
Solution:   Don't set the option when clearing a buffer. (Yasuhiro Matsumoto)
```

https://github.com/vim/vim/commit/04dfd512293e951479aec2378753b946c39bea87

Original patch:

``` diff
commit 04dfd512293e951479aec2378753b946c39bea87
Author: Bram Moolenaar <Bram@vim.org>
Date:   Tue Oct 13 20:55:50 2015 +0200

    patch 7.4.898
    Problem:    The 'fixendofline' option is set on with ":edit".
    Solution:   Don't set the option when clearing a buffer. (Yasuhiro Matsumoto)

diff --git a/src/nvim/buffer.c b/src/nvim/buffer.c
index 4623e0a..5d4170f 100644
--- a/src/nvim/buffer.c
+++ b/src/nvim/buffer.c
@@ -547,7 +547,6 @@ buf_clear_file(buf)
     buf->b_shortname = FALSE;
 #endif
     buf->b_p_eol = TRUE;
-    buf->b_p_fixeol = TRUE;
     buf->b_start_eol = TRUE;
 #ifdef FEAT_MBYTE
     buf->b_p_bomb = FALSE;
diff --git a/src/nvim/version.c b/src/nvim/version.c
index 71e1a2a..a2aec2c 100644
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    898,
+/**/
     897,
 /**/
     896,
```

### CODE REVIEW

**Comment by justinmk** [comment]
Thank you. Can you convert the test to a lua test? Use the `scripts/legacy2luatest` to get started. See also: https://github.com/neovim/neovim/wiki/Unit-tests#checklist-for-migrating-legacy-tests

**Comment by johanhelsing** [comment]
@justinmk You're welcome, I really want that feature in upstream :)

I tried converting the test using the script, and it seemed like it should work, but I get a SIGPIPE error when running it.

```~/r/neovim (vim-7.4.785 ↩=) env TEST_FILE=test/functional/legacy/fixeol_spec.lua make unittest
ninja  -C .deps
ninja: Entering directory `.deps'
[2/2] cd /home/johan/repos/neovim/...sr/bin/cmake -E touch .third-party
ninja  -C build
ninja: Entering directory `build'
ninja: no work to do.
ninja  -C build unittest
ninja: Entering directory `build'
[1/1] cd /home/johan/repos/neovim/.../repos/neovim/cmake/RunTests.cmake
FAILED: cd /home/johan/repos/neovim/build && /usr/bin/cmake -DBUSTED_PRG=/home/johan/repos/neovim/.deps/usr/bin/busted -DLUA_PRG=/home/johan/repos/neovim/.deps/usr/bin/luajit -DWORKING_DIR=/home/johan/repos/neovim -DBUSTED_OUTPUT_TYPE=utfTerminal -DTEST_DIR=/home/johan/repos/neovim/test -DBUILD_DIR=/home/johan/repos/neovim/build -DTEST_TYPE=unit -P /home/johan/repos/neovim/cmake/RunTests.cmake
-- Output to stderr:

CMake Error at /home/johan/repos/neovim/cmake/RunTests.cmake:39 (message):
  Running unit tests failed with error: SIGPIPE.


ninja: build stopped: subcommand failed.
Makefile:92: recipe for target 'unittest' failed
make: *** [unittest] Error 1```

I tried searching other PRs for similar issues, and I found:

 * https://github.com/neovim/neovim/pull/1798#issuecomment-70371612
 * https://github.com/neovim/neovim/pull/1793#issuecomment-69479126
 * https://github.com/neovim/neovim/pull/1616#issuecomment-65846435
 * https://github.com/neovim/neovim/pull/1572#issuecomment-70364015

I don't understand why this happens, I also have trouble attaching my debugger to the lua test, so I'm not sure how to approach this.

**Comment by fmoralesc** [comment]
@johanhelsing Push the test in a separate commit so we can see what might be going on.

**Comment by johanhelsing** [comment]
@fmoralesc I've added a commit with the failing test.

**Comment by fmoralesc** [comment]
@justinmk travis has been choking on this PR since yesterday, and it seems like I cannot access the travis build details. I remember @Pyrohh had an issue like this the other day, any ideas?

**Comment by fwalch** [comment]
@fmoralesc Well, closing and re-opening does not work. However, it looks like the PR needs to be rebased anyway, as GitHub says there are conflicts.

**Comment by Shougo** [comment]
@johanhelsing 
I think this patch should merge 7.4.898 change.

http://ftp.vim.org/vim/patches/7.4/7.4.898

**Comment by johanhelsing** [comment]
@Shougo Nice catch, Added another commit with vim-patch:7.4.898.

**Comment by johanhelsing** [comment]
@Shougo Turns out 7.4.898 was dependent on 7.4.795, so I included that one as well.

@justinmk I fixed the failing test, and then the linting errors, but suddenly one of the travis jobs failed.

Weirdly enough, the same test passed on my own Travis account, so why did it fail here?
https://travis-ci.org/johanhelsing/neovim/builds/85405586

**Comment by Shougo** [comment]
> @Shougo Turns out 7.4.898 was dependent on 7.4.795, so I included that one as well.

Thanks!

**Comment by johanhelsing** [comment]
@justinmk did you get a chance to look at this?

**Comment by Shougo** [comment]
@johanhelsing This PR has conflicts.  The fix is recommended.

**Comment by johanhelsing** [comment]
@Shougo fixed the conflicts.

**Comment by Shougo** [comment]
:+1:

**Comment by justinmk** [comment]
Thanks @johanhelsing !

**Pull request merged**
