### PR TITLE
Fix clang warnings with glibc 2.25

### PR DESCRIPTION
**Pull request by mrkline**
When building with `-pedantic` (as neovim does),
clang complains about how `assert()` - among other things - is defined.
The Clang devs say that this is a glibc issue; see the thread at
http://lists.llvm.org/pipermail/cfe-dev/2017-April/053382.html for all
the fun details.

At any rate, these problems go away when building with `-std=c99`
instead of `-std=gnu99`. When doing so, `-D_DEFAULT_SOURCE` is also
needed. See:
http://man7.org/linux/man-pages/man7/feature_test_macros.7.html
https://github.com/neovim/neovim/issues/4042
https://github.com/libuv/libuv/issues/891

As a side note, if we do define `-D_DEFAULT_SOURCE`, is
https://github.com/neovim/neovim/pull/4094 still needed?

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for the thorough investigation. Seems ok to me, wondering if more knowledgable people like @jszakmeister @jamessan @aktau know of any adverse implications.

**Comment by mrkline** [comment]
Huh, the CI tests are falling over for seemingly unrelated reasons. One seems to error out during testing, one gives

```
04:37:28,888 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:238:28: error: array subscript is below array bounds [-Werror=array-bounds]
04:37:28,888 WARN  - kp = __KB_KEY(key_t, x)[i]; \
04:37:28,888 WARN  - ^
```

and the MinGW builds can't find some wide character type:

```
C:/projects/neovim/build/include/mbyte.h.generated.h:40:25: error: unknown type name 'WCHAR'
 int utf16_to_utf8(const WCHAR *strw, char **str) FUNC_ATTR_NONNULL_ALL;  // C:/projects/neovim/src/nvim/mbyte.c:1354
                         ^~~~~
```

Is this normal?

**Comment by jamessan** [comment]
The `__KB_KEY` ones are [known](https://github.com/neovim/neovim/pull/6931).  That's the first I've seen the `WCHAR` error.

**Comment by justinmk** [comment]
Maybe mingw needs special case.

**Comment by aktau** [comment]
This seems quite alright, perhaps it'll help us stay closer to C99 too (although [this SO post](https://stackoverflow.com/a/5331540/558819) implies there aren't too many differences, it can't be exhaustive).

As for the `WCHAR` thing, this appears to be a windows specific thing (the standard version appears to be `wchar_t`: https://stackoverflow.com/a/16021141/558819). Looking at some of the code we have:

```c
  char *buf = xmalloc(buf_sz);
  char *pos = buf;

  int r = MultiByteToWideChar(CP_UTF8,
                              0,
                              str,
                              -1,
                              (WCHAR *)pos,
                              wchar_len);
```

I'm not sure why we cast to `WCHAR`. MSDN [says](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx)

```c
int MultiByteToWideChar(
  _In_      UINT   CodePage,
  _In_      DWORD  dwFlags,
  _In_      LPCSTR lpMultiByteStr,
  _In_      int    cbMultiByte,
  _Out_opt_ LPWSTR lpWideCharStr,  // THIS ONE
  _In_      int    cchWideChar
);
```

Which is [defined](https://msdn.microsoft.com/en-us/library/cc230355.aspx) (according to MSDN) as:

```c
typedef wchar_t* LPWSTR, *PWSTR;
```

So it seems to me like this may be legacy holdouts and we'd be better off using `wchar_t` or the direct Windows types `LPWSTR` (although that's really ugly).

**Comment by mrkline** [comment]
@aktau Should I add a commit changing `WCHAR` to `wchar_t`? Strange that switching from `gnu99` to `c99` would make this rear its head.

**Comment by justinmk** [comment]
Sure

**Comment by aktau** [comment]
> @aktau Should I add a commit changing WCHAR to wchar_t? Strange that switching from gnu99 to c99 would make this rear its head.

Luke Justin said, go for it. It seems more correct in either case, I'm not sure where the `WCHAR` comes from.

**Comment by mrkline** [comment]
@aktau It seems to get pulled in by `nvim/os/os_defs.h`, which apparently gets it from some Windows header.

At any rate, let's see how swapping it for `wchar_t` goes.

**Comment by mrkline** [comment]
Hm, now MinGW gives

```
C:\projects\neovim\src\nvim\fileio.c:2690:37: error: 'O_NOFOLLOW' undeclared (first use in this function)
             O_CREAT|O_WRONLY|O_EXCL|O_NOFOLLOW, perm);
                                     ^~~~~~~~~~
```

Perhaps it uses a libc that doesn't support `-D_DEFAULT_SOURCE`. Is it possible that its glibc is pre-2.19? Should I try `-D_GNU_SOURCE` or `-D_POSIX_C_SOURCE`?

**Comment by justinmk** [comment]
`win_defs.h` defines O_NOFOLLOW, and `os_defs.h.h` is already included by `fileio.c`. 

It sounds like the cause of all of these mingw compilation issues is that WIN32 is not defined now.

**Comment by justinmk** [comment]
Also, without `-std=gnu99` will gnu extensions be enabled? We need gnu extensions for function attributes (`func_attr.h`). https://stackoverflow.com/a/38940030/152142

**Comment by mrkline** [comment]
> Perhaps when mingw sees -std=c99 and/or -D_DEFAULT_SOURCE it switches to a mode that does not include Windows headers.

That would be truly bizarre.

> Also, without `-std=gnu99` will gnu extensions be enabled?

From the GCC man page: "When a base standard is specified, the compiler accepts all programs following that standard plus those using GNU extensions that do not contradict it."
Seems we're in the clear there, even with `-std=c99`.

> It may be fixed in glibc.

It isn't in the glibc mainline, and [the only bug I could find](https://sourceware.org/bugzilla/show_bug.cgi?id=21242) related to the problem was created in March and has had no activity since.

If `-std=c99` causes headaches in MinGW and other GCC-based platforms, would it be sane to specify `-std=c99 -D_DEFAULT_SOURCE` for Clang and `-std=gnu99` for all other (presumably) GCC-based toolchains? That seems like a bit of a crappy last-resort, though - I'd like to try to figure out what's up with the Windows headers first, if possible.

**Comment by justinmk** [comment]
> If -std=c99 causes headaches in MinGW and other GCC-based platforms, would it be sane to specify -std=c99 -D_DEFAULT_SOURCE for Clang and -std=gnu99 for all other (presumably) GCC-based toolchains?

Maybe. But even a future version of gcc might start complaining, since the glibc code is a legitimate bug.

Perhaps we should detect the version of glibc and only do the workaround in that case (and only for non-mingw).

**Comment by justinmk** [comment]
@mrkline would you mind rebasing this? Perhaps we should start with just the wchar_t commit.

**Comment by mrkline** [comment]
Sorry for the delay. `wchar_t` commit pushed.

**Comment by mrkline** [comment]
FWIW, I'm no longer seeing these warnings on glibc 2.26, so I presume folks did something to address them.

**Pull request merged**
