### PR TITLE
[RFC] Remove legacy tests for if_mzsch/if_lua

### PR DESCRIPTION
**Pull request by glts**
This removes legacy tests `test70.in` and `test85.in`.

These legacy tests performed very limited smoke testing for the MzScheme and Lua scripting interfaces and are not relevant for Neovim.

### CODE REVIEW

**Comment by Pyrohh** [comment]
This is already done in #2245, although it might make more sense to remove the tests separately as done here.

**Comment by Pyrohh** [comment]
LGTM.

**Comment by Pyrohh** [comment]
LGTM, could you take a peek at this @fwalch? It should be fine to merge after that.

**Comment by fwalch** [comment]
We'll get if_lua support eventually, but I guess it doesn't make sense to keep the tests around until then. So LGTM.

**Comment by Pyrohh** [comment]
merged, thanks!

**Comment by glts** [comment]
@Pyrohh Ah, that was unfortunate. Thanks for merging.

**Pull request closed without merging**
