### PR TITLE
build(deps): bump wasmtime to v26.0.1

### PR DESCRIPTION
**Pull request by clason**
https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.0
https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.1

### CODE REVIEW

**Review by dundargoc — APPROVED** [review]

**Review by lewis6991 — APPROVED** [review]

**Comment by clason** [comment]
I think I prefer to strictly follow tree-sitter's version from here on (unless someone tested this version with 0.24.4 and tells me it's safe).

**Comment by dundargoc** [comment]
> I think I prefer to strictly follow tree-sitter's version from here on

Right. Should we close the PR then or what's the plan?

**Review by dundargoc — CHANGES_REQUESTED** [review]
Confusion

**Comment by clason** [comment]
Nah, I'll keep it up -- always good to have a canary. I'm keeping track of it, so no danger of it getting stale.

**Comment by clason** [comment]
Looks like upstream is not interested in tracking wasmtime, so neither should we. Note to self: when bumping (minor) tree-sitter versions, check which wasmtime they build with.

**Pull request closed without merging**
