### PR TITLE
feat(lsp): allow customizing omnifunc

### LINKED ISSUE #15414: LSP: Add config option to not filter completion results
### Feature already in Vim?

_No response_

### Feature description

Currently, [in `vim.lsp.util.text_document_completion_list_to_complete_items`](https://github.com/neovim/neovim/blob/15b736d6e88dba114294b84a21e463b77a0b2857/runtime/lua/vim/lsp/util.lua#L658-L659), the completion results from the language server are not kept as-is, but instead some preprocessing is performed:

1. Only completions which exactly match the already-typed prefix are kept;
2. The completions are sorted.

While this is probably nice for some language servers that return weird results, this is completely counterproductive when a language server tries to be helpful by returning results with:
- case-insensitive matching
- typo-fixing
- intelligent result ordering so that most likely matches come first
- (maybe other things too)

At least the first three are performed by the Haskell language server.

At least for the Haskell language server in particular, my completion results get _significantly_ more useful when I remove [the two lines linked above](https://github.com/neovim/neovim/blob/15b736d6e88dba114294b84a21e463b77a0b2857/runtime/lua/vim/lsp/util.lua#L658-L659). However, this functionality is probably not in the LSP implementation for nothing. Therefore:

**Request**: A configuration option that allows me to turn off this result filtering and sorting. I don't know how granular this option should be, i.e. if it should be more than just one boolean. A logical option would seem to be two booleans: one to control exact-prefix-match filtering, and one to control sorting.

Thanks for the good work!

### PR DESCRIPTION
**Pull request by mjlbach**
Closes https://github.com/neovim/neovim/issues/15414

vim.lsp.omnifunc now takes two optional arguments:

* remove_unmatched (default true) exclude completion candidates whose prefix does not match
* sort_matches (default true) sort matches by sortText

Users can leverage this by wrapping the template omnifunc function.

```lua
function wrapped_omnifunc(findstart, base)
  opts = { remove_unmatched = false, sort_matches = false }
  return vim.lsp.omnifunc(findstart, base, opts)
end

vim.api.nvim_buf_set_option(0, 'omnifunc', 'v:lua.wrapped_omnifunc')

```

### CODE REVIEW

**Comment by mfussenegger** [comment]
I think we should see if we can utilize things from https://github.com/neovim/neovim/pull/13854 once merged. I didn't look into it in detail, but sounds like there's some overlap on functionality and it would be good if we could avoid special options for LSP if there are generic completion options.

**Comment by mjlbach** [comment]
No worries at all :) We try to report things upstream/fix them there if possible. For now, you should be able to copy/paste the lua code into your config to avoid needing to stay on my branch.

**Comment by chentau** [comment]
#13854 is basically ready for merge, just need the ok from the maintainers. Its worth noting that filterfunc may mess with the ordering of the completion entries; if the user has specified the filterfunc option, then the matches will be sorted again after complete() is called.

**Comment by mjlbach** [comment]
@mfussenegger I still think we should merge this, as to full respect the sort text we should allow not doing prefix matching (otherwise we filter out HLS's ordering)

**Pull request closed without merging**
