### PR TITLE
vim-patch:8.1.2396,8.1.2395,8.1.2394,8.1.2392,8.1.2368,8.1.2388,8.1.2379

### PR DESCRIPTION
**Pull request by dundargoc**
#### vim-patch:8.1.2396: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/e38eab22c1fb950127f0307a9904de6d4561dc70

#### vim-patch:8.1.2395: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/0d6f5d9740dbad1b0207f3ab257de806169dd905

#### vim-patch:8.1.2394: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/63d9e730f726341bf41ee4f4b829253cb9879110

#### vim-patch:8.1.2392: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/6e0ce171e19d0118ecd7c2b16e2a1bd50aa76013

#### vim-patch:8.1.2368: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/c667da5185ce5dce914d2006d62da2be0cedb384

#### vim-patch:8.1.2388: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/4ba37b5833de99db9e9afe8928b31c864182405c

#### vim-patch:8.1.2379: using old C style comments

Problem:    Using old C style comments.
Solution:   Use // comments where appropriate.
https://github.com/vim/vim/commit/217e1b8359447f5550dcb0d1ee43380a90c253c5

### CODE REVIEW

**Comment by dundargoc** [comment]
Ignore clint error, it's a bug.

**Comment by dundargoc** [comment]
@janlazo take a look again please.

**Comment by janlazo** [comment]
`cindent.c` changes apply to indent.c and indent_c.c

**Comment by janlazo** [comment]
I guess you're not using `--fixup` so that it's more obvious which commit is being fixed. It's not obvious to a non-reviewer which patch is being fixed by  https://github.com/neovim/neovim/pull/15930/commits/6088cde28b98c8b498515cc3b18af2b4b20241a5

**Review by janlazo — CHANGES_REQUESTED** [review]
The files I mentioned are missing style changes. Update the comment style of those files and I'll review again.

**Comment by dundargoc** [comment]
> The files I mentioned are missing style changes.

They aren't. `popupmnu.c` has no /**/-style comments, the changes to `cindent.c` has already been applied and the changes to `findfile.c` and `findfile.c` has already been applied thanks to uncrustify.

**Review by janlazo — APPROVED** [review]
You're right. Good job.

**Pull request merged**
