### PR TITLE
build: rename CMake find modules for LibFindMacros

### PR DESCRIPTION
**Pull request by blueyed**
We are using "LIBFOO" prefixes for `LIBFOO_INCLUDE_DIRS` etc, and
therefore need to use this for the PREFIX with LibFindMacros also, so
that `"${${PREFIX}_FIND_VERSION}"` gets handled there properly.

The alternative would be to either manually handle/set the upper/mixed case
variants of those variable additionally, which is not as easy.

Keeping the existing names is useful for packagers.

### CODE REVIEW

**Comment by justinmk** [comment]
does this revert a previous change, and if so can you reference the commit SHAs in the commit message?

BTW what problems/symptoms is this causing currently?

**Comment by blueyed** [comment]
Will add some references.  It affects/relates to the commits where those where ported to LibFindMacros recently.

It is required for handling the minimum version that I wanted to add to #9494.  Will verify that it works as expected with it then.

**Comment by blueyed** [comment]
btw: alternative patch, but it would potentially require updates for packagers then:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 29fef0e5d..f7023341c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -409,10 +409,10 @@ option(FEAT_TUI "Enable the Terminal UI" ON)
 
 if(FEAT_TUI)
   find_package(Unibilium 2.0 REQUIRED)
-  include_directories(SYSTEM ${UNIBILIUM_INCLUDE_DIRS})
+  include_directories(SYSTEM ${Unibilium_INCLUDE_DIRS})
 
-  list(APPEND CMAKE_REQUIRED_INCLUDES "${UNIBILIUM_INCLUDE_DIRS}")
-  list(APPEND CMAKE_REQUIRED_LIBRARIES "${UNIBILIUM_LIBRARIES}")
+  list(APPEND CMAKE_REQUIRED_INCLUDES "${Unibilium_INCLUDE_DIRS}")
+  list(APPEND CMAKE_REQUIRED_LIBRARIES "${Unibilium_LIBRARIES}")
   check_c_source_compiles("
   #include <unibilium.h>
 
@@ -422,8 +422,8 @@ if(FEAT_TUI)
     return unibi_num_from_var(unibi_var_from_num(0));
   }
   " UNIBI_HAS_VAR_FROM)
-  list(REMOVE_ITEM CMAKE_REQUIRED_INCLUDES "${UNIBILIUM_INCLUDE_DIRS}")
-  list(REMOVE_ITEM CMAKE_REQUIRED_LIBRARIES "${UNIBILIUM_LIBRARIES}")
+  list(REMOVE_ITEM CMAKE_REQUIRED_INCLUDES "${Unibilium_INCLUDE_DIRS}")
+  list(REMOVE_ITEM CMAKE_REQUIRED_LIBRARIES "${Unibilium_LIBRARIES}")
   if(UNIBI_HAS_VAR_FROM)
     add_definitions(-DNVIM_UNIBI_HAS_VAR_FROM)
   endif()
@@ -433,7 +433,7 @@ if(FEAT_TUI)
 endif()
 
 find_package(LibVterm REQUIRED)
-include_directories(SYSTEM ${LIBVTERM_INCLUDE_DIRS})
+include_directories(SYSTEM ${LibVterm_INCLUDE_DIRS})
 
 if(WIN32)
   find_package(Winpty 0.4.3 REQUIRED)
diff --git a/cmake/FindLibVterm.cmake b/cmake/FindLibVterm.cmake
index 469494ddf..22ac37c01 100644
--- a/cmake/FindLibVterm.cmake
+++ b/cmake/FindLibVterm.cmake
@@ -1,10 +1,10 @@
 # - Try to find libvterm
 # Once done this will define
-#  LIBVTERM_FOUND - System has libvterm
-#  LIBVTERM_INCLUDE_DIRS - The libvterm include directories
-#  LIBVTERM_LIBRARIES - The libraries needed to use libvterm
+#  LibVterm_FOUND - System has libvterm
+#  LibVterm_INCLUDE_DIRS - The libvterm include directories
+#  LibVterm_LIBRARIES - The libraries needed to use libvterm
 
 include(LibFindMacros)
 
-libfind_pkg_detect(LIBVTERM vterm FIND_PATH vterm.h FIND_LIBRARY vterm)
-libfind_process(LIBVTERM REQUIRED)
+libfind_pkg_detect(LibVterm vterm FIND_PATH vterm.h FIND_LIBRARY vterm)
+libfind_process(LibVterm REQUIRED)
diff --git a/cmake/FindUnibilium.cmake b/cmake/FindUnibilium.cmake
index 0bf27b45e..ce8396834 100644
--- a/cmake/FindUnibilium.cmake
+++ b/cmake/FindUnibilium.cmake
@@ -1,12 +1,12 @@
 # - Try to find unibilium
 # Once done this will define
-#  UNIBILIUM_FOUND - System has unibilium
-#  UNIBILIUM_INCLUDE_DIRS - The unibilium include directories
-#  UNIBILIUM_LIBRARIES - The libraries needed to use unibilium
+#  Unibilium_FOUND - System has unibilium
+#  Unibilium_INCLUDE_DIRS - The unibilium include directories
+#  Unibilium_LIBRARIES - The libraries needed to use unibilium
 
 include(LibFindMacros)
 
-libfind_pkg_detect(UNIBILIUM unibilium
+libfind_pkg_detect(Unibilium unibilium
   FIND_PATH unibilium.h
   FIND_LIBRARY unibilium)
-libfind_process(UNIBILIUM)
+libfind_process(Unibilium)
diff --git a/third-party/cmake/libtermkeyCMakeLists.txt b/third-party/cmake/libtermkeyCMakeLists.txt
index af54c1dae..b1b04ac1a 100644
--- a/third-party/cmake/libtermkeyCMakeLists.txt
+++ b/third-party/cmake/libtermkeyCMakeLists.txt
@@ -8,12 +8,12 @@ if(NOT MSVC)
 endif()
 
 include_directories(${PROJECT_BINARY_DIR}/t)
-include_directories(SYSTEM ${UNIBILIUM_INCLUDE_DIRS})
+include_directories(SYSTEM ${Unibilium_INCLUDE_DIRS})
 
 add_library(termkey termkey.c driver-csi.c driver-ti.c)
 set_target_properties(termkey PROPERTIES
   PUBLIC_HEADER ${PROJECT_SOURCE_DIR}/termkey.h)
-target_link_libraries(termkey ${UNIBILIUM_LIBRARIES})
+target_link_libraries(termkey ${Unibilium_LIBRARIES})
 
 include(GNUInstallDirs)
 install(TARGETS termkey
```

**Comment by justinmk** [comment]
I don't follow how it would affect packagers. We should do whatever avoids forking LibFindMacros, or if we didn't need to fork it then I'm puzzled about why it matters in any case.

**Comment by blueyed** [comment]
> I don't follow how it would affect packagers.

Because they would need to use different casing when specifying paths/vars locally.
(`Unibilium_LIBRARIES` instead of `UNIBILIUM_LIBRARIES`).

> forking LibFindMacros

Neither of the patches does it.  I've thought about filing an issue with them to support our existing use case, but figured that it is also better for us to not mix case unnecessarily in the first place.

**Comment by blueyed** [comment]
Confirmed that this makes `find_package(LIBVTERM 0.2 REQUIRED)` work then with https://github.com/neovim/neovim/pull/9494.

**Comment by blueyed** [comment]
Amended the commit message, I consider it to be ready.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
Would be nice if there were a way to prevent this mistake (throw an error) for future.

**Pull request merged**
