### PR TITLE
ci(release-winget): publish nightly releases

### LINKED ISSUE #79698: [Package Request]: Add Neovim Nightly
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:  neovim.io
Publisher Url:  https://neovim.io
Package Name:  Neovim Nightly
Description:  Vim-fork focused on extensibility and usability
Package Version:  0.8.0-dev-1092-g89b9eab63
Installer URL:  https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.msi

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
* Resolves https://github.com/microsoft/winget-pkgs/issues/79698

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
cc @justinmk

**Review by sitiom — COMMENTED** [review]
Running the Winget Releaser workflow twice will fail because it will attempt to clone the repo again. A workaround like [this](https://github.com/jftuga/less-Windows/blob/39b2f76041e095a367870ed02753d2190bb2bc09/.github/workflows/nightly.yml#L106-L107) would have to be done before running it for the second time (unless you fixed it).

**Comment by vedantmgoyal2009** [comment]
> Running the Winget Releaser workflow twice will fail because it will attempt to clone the repo again. A workaround like [this](https://github.com/jftuga/less-Windows/blob/39b2f76041e095a367870ed02753d2190bb2bc09/.github/workflows/nightly.yml#L106-L107) would have to be done before running it for the second time (unless you fixed it).

It won't because only one step will run at a time, either for stable or nightly.

**Comment by sitiom** [comment]
Then how can you explain [this run](https://github.com/jftuga/less-Windows/actions/runs/3004620022/jobs/4824080275)? By the second step, it attempts to clone winget-pkgs again even it already exists and fails.

**Comment by sitiom** [comment]
> > Running the Winget Releaser workflow twice will fail because it will attempt to clone the repo again. A workaround like [this](https://github.com/jftuga/less-Windows/blob/39b2f76041e095a367870ed02753d2190bb2bc09/.github/workflows/nightly.yml#L106-L107) would have to be done before running it for the second time (unless you fixed it).
> 
> It won't because only one step will run at a time, either for stable or nightly.

I see.

**Pull request merged**
