### PR TITLE
[RFC]: Fix "undercurl" not falling back to "underline" in tui.

### PR DESCRIPTION
**Pull request by skystrife**
This fixes issue #2098.

I think it's this simple?

### CODE REVIEW

**Comment by Pyrohh** [comment]
This fixes the issue you described for me, but I'm not sure it's optimal. Won't this effectively make `undercurl` an alias for `underline`, at least in the tui?

I looked at the unibilium docs/src and found many `unibi_enter_{underline, bold, etc...}_mode` functions, but none for undercurl, so I'm not sure it's meant to be supported currently.

**Comment by skystrife** [comment]
I don't know if it *can* be supported, at least on most terminals. This is from vim's `:help syntax`:

```
"undercurl" is a curly underline.  When "undercurl" is not possible
	then "underline" is used.  In general "undercurl" is only available in
	the GUI.  The color is set with |highlight-guisp|.
```

which is what motivated just directly falling back to underline under the tui.

**Comment by Pyrohh** [comment]
Yes, I saw that help snippet.

Perhaps @tarruda knows if it's feasible to get `undercurl` working in the tui, and if not then that piece of documentation should be changed to mention that `undercurl` is a synonym for for `underline` when using the tui.

**Comment by Pyrohh** [comment]
Besides a [patched version of urxvt](https://github.com/AguirreIF/urxvt-patchs) (I haven't checked if the patch works), I can't find any terminals that support undercurl.

**Comment by tarruda** [comment]
> Perhaps @tarruda knows if it's feasible to get undercurl working in the tui, and if not then that piece of documentation should be changed to mention that undercurl is a synonym for underline when using the tui.

Not many terminals support this

LGTM

**Comment by justinmk** [comment]
merged

**Pull request closed without merging**
