### PR TITLE
[RFC] Move typval code to typval.c.

### PR DESCRIPTION
**Pull request by splinterofchaos**
Better separate code operating of typvals from code evaluating vimL.

I expected this to be a smaller PR, but it ended up being a massive code migration from `eval.c` to a new file, `typval.c` because much of the `typval` code is mutually dependent. With some more work, most files could include `typval.h` and not `eval.h` (it turns out almost every module calls `set_vim_var`, which I didn't touch) but in general, the idea was to give modules more access to the `typval` variant.

This ended up being a lot of work, and there's still more to do, but I'd like a fresh set of eyes to look at these changes before I decide to do any more (in another PR).

### CODE REVIEW

**Comment by Hettomei** [comment]
In any case you remove more than 1800 from eval.c which is obviously a good pull request ;) :+1: 

Too bad that test didn't pass but I didn't understand where it fail.

**Comment by Pyrohh** [comment]
I'm all for these kinds of refactorings, but do you think this particular one makes sense given that eval.c is going away eventually?

**Comment by splinterofchaos** [comment]
Tests are failing because of vim's incredibly complex `#include` system, hopefully partially fixed by the latest commit.

> do you think this particular one makes sense given that eval.c is going away eventually?

I must admit I haven't looked into the specifics of the vimL to lua translator, but unless `typval_T` is going away too, I think having it split off from `eval.c` makes a lot of sense. 

@ZyX-I, will the vimL to lua translation get rid of `typval_T`?

**Comment by justinmk** [comment]
This moves several things into `eval_defs.h` which makes them more "public", so it might not be a gain in encapsulation. Closing this since it's out of date and needs discussion before an update.

**Pull request closed without merging**
