### PR TITLE
Timeyyy/extended_marks merge

### PR DESCRIPTION
**Pull request by Synray**

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks, however a merge would be preferred instead of a rebase in this case, because of the size of the PR, we want the original commits to be identical. It will also avoid conflicts with work that @timeyyy has locally.

**Comment by Abominas** [comment]
Alright, changed this to a merge.

**Comment by justinmk** [comment]
Waiting for @timeyyy to comment.

**Comment by Abominas** [comment]
Since it seems @timeyyy is busy lately, I'll try to fix the failed tests, but not making any major changes in case he returns. Really interested in this PR :).

**Comment by justinmk** [comment]
@Abominas Many of us are, thanks for taking the initiative! I know that @timeyyy has been working on this in the last week, so I would wait for his reply before spending much time on it. There was a tricky bug with khash or kbtree IIRC.

**Comment by timeyyy** [comment]
@Synray, thanks for showing some interest. my local changes are quite messy so i haven't pushed them yet. I'll get around to that today. A big help would be just messing around with vim features and checking that the marks behave as expected.

**Comment by Synray** [comment]
@timeyyy Sounds great, I'll close this PR and do that.

**Pull request closed without merging**
