### PR TITLE
oldtest: windows: revert setting shellslash individually

### PR DESCRIPTION
**Pull request by blueyed**
This reverts commit 6245b4873d5e24fade9aadadf32645bfb3ebfc31.

It should probably use try/finally for resetting it, but maybe is not
necessary at all.

Test_find_complete currently fails on AppVeyor [1].
Test_set_completion passes, but this brings it in line with Vim's
original test.

1: https://ci.appveyor.com/project/neovim/neovim/builds/25196915?fullLog=true#L22602

### CODE REVIEW

**Comment by blueyed** [comment]
>￼ marvim unassigned blueyed 1 hour ago

Why that?
I've meant to use it as a marker that I am looking into this myself (later), but WIP is probably fine for that.  Is that the reason?
Where is the code for marvim btw?

**Comment by bfredl** [comment]
No sure, assignments for PR seems a bit weird. Maybe some projects use it for assignment of reviewer, but I don't think self-assignment by PR opener makes any sense, by default the opener already "owns" the PR.

**Comment by justinmk** [comment]
Maybe it's a bug in [this script](https://github.com/neovim/bot-ci/blob/master/ci/assign-labels.sh) which assigns labels but maybe somehow accidentally clears the "assigned user".

**Comment by janlazo** [comment]
https://github.com/vim/vim/commit/f60b796fa9870bdfc4cdeb91653bac041916077d#diff-6f4701f619362ae985013aeeb1502febR47
Vim uses `set shellslash` while this line is commented out in Neovim's runtest.vim. The reverted commit makes it explicit to be in line with Vim. If anything, Vim should set `shellslash` only when needed and its test suite should cover Windows (shell) defaults.

**Comment by blueyed** [comment]
> Vim uses set shellslash while this line is commented out in Neovim's runtest.vim.

Oh.

I'm inclined to stick to Vim here.

> On the other hand, Vim should set `shellslash` only when needed and its test suite should cover Windows (shell) defaults.

I could imagine that `set shellslash` can be seen as a common ground (not requiring to set it like in these tests, where it should use try/finally anyway likely).

Vim has some specific tests that use `noshellslash` / `+shellslash`:
```
test_findfile.vim
33:  let save_shellslash = &shellslash
35:  set shellslash
119:  let &shellslash = save_shellslash
133:  let save_shellslash = &shellslash
176:  let &shellslash = save_shellslash

runtest.vim
82:set shellslash

test_windows_home.vim
54:  set noshellslash

test_autocmd.vim
891:  let save_shellslash = &shellslash
892:  set noshellslash
905:  let &shellslash = save_shellslash

test_glob2regpat.vim
19:  if exists('+shellslash')

test_getcwd.vim
113:function Test_GetCwd_lcd_shellslash()
118:  if !exists('+shellslash') || &shellslash
```

Do you agree that we should stick to upstream here, i.e. use `set shellslash` in `runtest.vim`?


Just for reference, the changes due to this PR:

With this PR:
```
[00:17:46] Found errors in Test_find_complete():
[00:17:46] function RunTheTest[35]..Test_find_complete line 43: Expected 'Holy Grail' but got 'Jimmy Hoffa'
[00:17:46] function RunTheTest[35]..Test_find_complete line 45: Expected 'Jimmy Hoffa' but got 'E.T.'
[00:17:46] Caught exception in Test_find_complete(): Vim(find):E345: Can't find file "file" in path @ function RunTheTest[35]..Test_find_complete, line 46
```

Before:
```
From test_find_complete.vim:
Executing Test_find_complete()
Executed 1 test
1 FAILED:
Found errors in Test_find_complete():
Caught exception in Test_find_complete(): Vim(find):E345: Can't find file "Xfind/file.txt" in path @ function RunTheTest[35]..Test_find_complete, line 44
```

`Test_set_completion` now fails:
```
[00:17:46] Found errors in Test_set_completion():
[00:17:46] function RunTheTest[35]..Test_set_completion line 25: Pattern './samples/ ' does not match '"set cdpath=.\\XfakeHOME\\ .\\pyxfile\\ .\\samples\\ .\\sautest\\'
[00:17:46] function RunTheTest[35]..Test_set_completion line 30: Pattern './samples/ ./sautest/ ./setup.vim ./shared.vim' does not match '"set tags=.\\Makefile .\\XfakeHOME\\ .\\dotest.in .\\err-…
```

**Comment by janlazo** [comment]
With or without shellslash, it won't make the failing tests pass even if the expected results are in line with Vim. Defaulting to `noshellslash` is in line with the `$SHELL` override in `src/nvim/testdir/setup.vim`.

**Comment by justinmk** [comment]
> On the other hand, Vim should set `shellslash` only when needed and its test suite should cover Windows (shell) defaults.

We can aim for that in the Lua tests, but for Vim tests let's try to follow upstream if it makes things easier.

**Comment by blueyed** [comment]
This is in line now with #10679 (d7b642c).
/cc @erw7

**Comment by erw7** [comment]
I missed it when I changed to use `set shellslash` in #10679. In addition, the following `set shellslash` are no longer needed:

```vim
src/nvim/testdir/test_cd.vim
27:    let shellslash = &shellslash
28:    set shellslash
30:    let &shellslash = shellslash
```

```vim
src/nvim/testdir/test_checkpath.vim
5:  let save_shellslash = &shellslash
6:  set shellslash
30:  let &shellslash = save_shellslash
39:  let save_shellslash = &shellslash
40:  set shellslash
69:  let &shellslash = save_shellslash
81:  let save_shellslash = &shellslash
82:  set shellslash
112:  let &shellslash = save_shellslash
```

```vim
src/nvim/testdir/test_functions.vim
979:  let [save_shell, save_shellslash] = [&shell, &shellslash]
980:  set shell=bash shellslash
994:  set shell=tcsh shellslash
1000:  let [&shell, &shellslash] = [save_shell, save_shellslash]
```

```vim
src/nvim/testdir/test_quickfix.vim
142:  let save_shellslash = &shellslash
143:  set shellslash
152:  let &shellslash = save_shellslash
```

```vim
src/nvim/testdir/test_statusline.vim
89:  let shellslash = &shellslash
90:  set shellslash
93:  let &shellslash = shellslash
```

```vim
src/nvim/testdir/test_true_false.vim
60:  let shellslash = &shellslash
62:  set shellslash
117:  let &shellslash = shellslash
137:  let shellslash = &shellslash
138:  set shellslash
158:  let &shellslash = shellslash
```

**Comment by blueyed** [comment]
@erw7 
Feel free to push it here - or I'll do it eventually (but only later).

**Comment by erw7** [comment]
I think the push destination is wrong, but it becomes "Premission to blueyed/neovim.git denied to erw7". Can you import from the following? Or can you tell me the URL to specify for `git remote add`?

https://github.com/neovim/neovim/compare/master...erw7:av-shellslash

**Comment by blueyed** [comment]
@erw7 
Should be `git@github.com:blueyed/neovim.git` - just like with your own fork, but my username (could also be https I guess).
I'll import it, but good to set up other forks anyway - I usually use "hub remote add -p otheruser" (https://github.com/github/hub).

**Comment by erw7** [comment]
@blueyed Thanks. Both `git@github.com:blueyed/neovim` and `https://erw7@github.com/blueyed/neovim` resulted in an error. Next time I will use the `hub`.

**Comment by blueyed** [comment]
> @blueyed Thanks. Both `git@github.com:blueyed/neovim` and `https://erw7@github.com/blueyed/neovim` resulted in an error. Next time I will use the `hub`.

Ok.  Likely it is due to you not being included as "maintainer" then (for the "Allow edits from maintainers." checkbox) - assuming that it was the correct branch.
As for "hub": it is just a shortcut/wrapper in this case.

Thanks for the patches!

**Review by justinmk — APPROVED** [review]

**Pull request merged**
