### PR TITLE
build(deps): bump tree-sitter to v0.20.2

### PR DESCRIPTION
**Pull request by clason**
update to actual release containing the fix in https://github.com/neovim/neovim/pull/16606

### CODE REVIEW

**Comment by clason** [comment]
@neovim/treesitter @theHamsta @stsewd

**Comment by vigoux** [comment]
I don't think we need to, dependency versions should be pretty stable when we release.

**Comment by vigoux** [comment]
Also, looking at the commits included in this version, it seems that we can force the use of our own allocator functions, which we should do.

**Comment by clason** [comment]
> I don't think we need to, dependency versions should be pretty stable when we release.

Don't need to, but it does mitigate a noticeable performance regression in 0.6.0? On the other hand, at the rate that we're merging cool features, the next release is likely going to be a 0.7.0, so the whole point may be moot :)

**Pull request merged**
