### PR TITLE
lsp: fix textDocument/completion handling

### LINKED ISSUE #11826: LSP: rust-analyzer ignores already typed prefixes
- `nvim --version`: NVIM v0.5.0-357-g405f49a9b
- `vim -u DEFAULTS` (version: ) behaves differently? Language servers are not supported in vim.
- Operating system/version: Arch Linux, everything up to date as of the 6th of February
- Terminal name/version: Termite 15-1
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

```
cargo new --bin ra-test
cd ra-test
nvim -u NORC
:set nocompatible
:filetype off
:set rtp+=~/.vim/bundle/Vundle.vim
:call vundle#begin()
:Plugin 'neovim/nvim-lsp'
:call vundle#end()
:PluginInstall
:q
:filetype plugin indent on
:lua require'nvim_lsp'.rust_analyzer.setup{}
:set omnifunc=v:lua.vim.lsp.omnifunc
:e src/main.rs
Ouse std::sy<C-x><C-o>
```

### Actual behaviour
It shows `self`, `super`, `libc`, `concat!`, etc. in that order, ignoring the prefix `sy`.

### Expected behaviour
It should only show everything starting with `sy` (`sync`, `sys`, `sys_common`), or everything matching `/s.*y.*/` (the aforementioned and `stringify!`), or any other useful metric respecting what the user already wrote.

### PR DESCRIPTION
**Pull request by h-michael**
fix: #11826

### CODE REVIEW

**Comment by h-michael** [comment]
@42triangles Would you try this branch?

**Comment by h-michael** [comment]
@mjlbach I don't use pyls_ms. So would you try this branch?

**Comment by mjlbach** [comment]
This doesn't seem to fix it for me, investigating...

**Comment by h-michael** [comment]
@mjlbach Would you show me sample codes?

**Comment by mjlbach** [comment]
Sure!
```
mkdir test && cd test && git init
pip install --user numpy
echo "import numpy as np\n\nnp.abs" >> main.py
nvim main.py
```
Now try to trigger omnicomplete after np.abs, and you'll see the first completion result is  `__getattr__ Function`

**Comment by mjlbach** [comment]
Weird, seems to be isolated to top level numpy imports... Had similar problems with racer though.

**Comment by h-michael** [comment]
I understand the pyls_ms problem. This is not the same proble of rust-analzer.

**Comment by mjlbach** [comment]
Are we not respecting sortText? I notice the out of order items have sortText="2"

**Comment by h-michael** [comment]
@mjlbach I've fixed it. I should work as expected :)

**Comment by mjlbach** [comment]
Now it works great :)

**Review by justinmk — COMMENTED** [review]
awesome, thanks!

**Comment by justinmk** [comment]
Nice changes! Thanks @h-michael . In the future we should try to add tests for LSP stuff, otherwise it will be fragile...

**Comment by h-michael** [comment]
@justinmk Yeah,  I'll add some test cases for LSP later. 👍

**Pull request merged**
