### PR TITLE
build: use cmake to build libvterm on all platform

### PR DESCRIPTION
**Pull request by dundargoc**
Also remove Libvterm-tbl2inc_c.cmake as it's not required. It's used to
generate files that are already provided by the Libvterm project by
default. It's also not really something we need to concern ourselves
with as it's more of an authoring tool for the Libvterm creator as
mentioned in
https://github.com/neovim/neovim/pull/21986#issuecomment-1403733054.

### CODE REVIEW

**Comment by justinmk** [comment]
would be nice to eliminate that patch, waiting on libvterm to upstream it...

**Comment by clason** [comment]
what patch? we don't apply _any_ patches anymore since last year.

**Comment by clason** [comment]
Yeah, that can just be removed -- the tarball we download contains the generated files already.

**Comment by clason** [comment]
Maybe try removing `libvterm-dev` from the `lintc` setup step? That will install an outdated version anyway (unless you specifically want to test the build preferring bundled deps over installed ones for this dependency).

**Comment by dundargoc** [comment]
As @clason said, I'm very certain `Libvterm-tbl2inc_c.cmake` is not needed as the build works just fine without it. I've also confirmed with both @leonerd and @jamessan that this shouldn't be required, neither for neovim nor debian, as it's already provided by the Libvterm project. The only thing I'm not entirely sure about is if that was ever needed to begin with since it was introduced a while ago. The problem description for the PR is a bit vague. I'll see if I can dig up any relevant reasoning.

(I'll write down my findings in the commit message of course once everything has been sorted out of course.)

**Comment by leonerd** [comment]
This idea seems reasonable. The perl scripts are only used for building the `src/encoding/*.inc` files out of the `.tbl` files anyway, and I regenerated those years ago. They're still in place in case I ever add or change them. But there's no need for downstream users such as neovim to bother with it. It's really there as an authoring tool for me.

To be honest I should probably omit them from the generated source tarball, but eh that's extra effort. You can just ignore them ;)

**Comment by dundargoc** [comment]
> Maybe try removing libvterm-dev from the lintc setup step? 

Maybe if I truly can't find another way to fix this, but I'm not 100% against this.

> That will install an outdated version anyway (unless you specifically want to test the build preferring bundled deps over installed ones for this dependency).

Yes, but I'm curious to find out why this error shows up now and not previously. To my knowledge we currently use an outdated libvterm version for the lintc job, but we don't get any errors (until now). I'll need to investigate a bit more.

**Comment by clason** [comment]
Seems like you fixed it :)

**Comment by dundargoc** [comment]
I couldn't figure out if this was really ever needed, but I suppose it's not relevant as it's definitely not needed anymore.

**Comment by dundargoc** [comment]
> Seems like you fixed it :)

With your help :). Thank you!

**Review by clason — APPROVED** [review]

**Review by justinmk — APPROVED** [review]

**Pull request merged**
