### PR TITLE
refactor(lsp): merge rpc.domain_socket_connect into rpc.connect

### PR DESCRIPTION
**Pull request by mfussenegger**
See discussion in https://github.com/neovim/neovim/pull/26850

### CODE REVIEW

**Review by justinmk — APPROVED** [review]
Nice!

**Comment by mfussenegger** [comment]
@TheLeoP heads up as this will break https://github.com/TheLeoP/powershell.nvim

**Comment by TheLeoP** [comment]
Hey. I just tried testing this and it seems like it introduced a regression. As I stated in [this comment](https://github.com/neovim/neovim/pull/26032#issue-1991183835):

> I'm using vim.schedule on the write transport as a workaround because, on my tests using Powershell Editor Services, Neovim sended the initialization requets before the pipe connection was stablished.

At the time I didn't look too much into it, I guess this may be some kind of race condition because of Windows pipes being slow to connect to(?). But, since `vim.schedule_wrap` was removed from the write handler, I'm no longer able to connect to the LSP using them.

**Comment by mfussenegger** [comment]
> Hey. I just tried testing this and it seems like it introduced a regression. As I stated in [this comment](https://github.com/neovim/neovim/pull/26032#issue-1991183835):
> 
> > I'm using vim.schedule on the write transport as a workaround because, on my tests using Powershell Editor Services, Neovim sended the initialization requets before the pipe connection was stablished.
> 
> At the time I didn't look too much into it, I guess this may be some kind of race condition because of Windows pipes being slow to connect to(?). But, since `vim.schedule_wrap` was removed from the write handler, I'm no longer able to connect to the LSP using them.

Oh, I was wondering what the `vim.schedule_wrap` was for - because there was no fast-loop issue there, so I didn't see a need for it.

Could you try with https://github.com/neovim/neovim/pull/28507 ?

**Pull request merged**
