### PR TITLE
build(deps): bump libuv to HEAD - f00d4b677

### PR DESCRIPTION
**Pull request by clason**
just a smoke test to see whether the recent changes around file watchers and windows events have been breaking before the upcoming release.

### CODE REVIEW

**Comment by clason** [comment]
🙆‍♂️

**Comment by clason** [comment]
Test failures look relevant @lewis6991

**Comment by clason** [comment]
(Release is imminent, so now's a good time to raise the hue and cry.)

**Comment by lewis6991** [comment]
I'm not particularly keen to dive into another one of these rabbit holes atm, so we should probably defer updating until someone can get to the bottom of this.

A basic commit bisection should be simple enough. Debugging that further will be most of the work.

**Comment by clason** [comment]
There's only a dozen commits (fewer if you don't count doc, build, or test) between the first commit here -- which passed -- and the failing commit, so shouldn't take much time. It's virtually guaranteed to be the kqueue one...

**Comment by clason** [comment]
MacOS failures are likely related to https://github.com/libuv/libuv/issues/4468#issuecomment-2291159172 (not sure why `4e310d0` passed in this case, though). Probably needs test adaptations.

**Comment by clason** [comment]
🙆‍♂️

**Comment by clason** [comment]
Looks like the issues are fixed now. Do we want to treat this as an RC and give it a proper try in the wild before the actual release (likely) next week?

**Comment by lewis6991** [comment]
I think so.

**Comment by clason** [comment]
You win some, you lose some... After rebasing on master, I get persistent Nvim crash on `legacy/increment_spec` on Windows. There also seem to be build/link errors with unavailable dlls?

**Comment by clason** [comment]
aaand now it passed again. cursed.

**Comment by clason** [comment]
aaand the crash is back. apparently the bug can tell if automerge is enabled.

**Comment by clason** [comment]
Tests are flakey on master as well, apparently.

**Pull request merged**
