### PR TITLE
[RFC] tests: Migrate legacy test 8.

### PR DESCRIPTION
**Pull request by lucc**
The test produces some "hit enter" prompts and error messages that had to be
dealt with by `feed`ing CTRL-L to nvim.

### CODE REVIEW

**Comment by lucc** [comment]
part of #1286

**Comment by justinmk** [comment]
can the old test be deleted (and Makefile updated)?

**Comment by lucc** [comment]
done

**Review by thebrianbug — CHANGES_REQUESTED** [review]
diff --git a/src/nvim/testdir/Makefile b/src/nvim/testdir/Makefile
index 10d26bd..a9c94ae 100644
--- a/src/nvim/testdir/Makefile
+++ b/src/nvim/testdir/Makefile
@@ -8,7 +8,6 @@ VIMPROG := ../../../build/bin/nvim
 SCRIPTSOURCE := ../../../runtime

 SCRIPTS := \
-           test8.out              \
          test13.out             \
          test14.out             \
          test17.out             \

Remove the test8.out script from the test Makefile

**Comment by bmcilw1** [comment]
Sorry, ^^^^ That above didn't come out that pretty. I hope you get the point though.

**Comment by lucc** [comment]
You could put code tags around the relevant parts or indent it by four spaces. But I got the point, thanks.

**Comment by justinmk** [comment]
Merged. Thanks!

**Comment by lucc** [comment]
I thought the plan to migrate the legacy test was dropped long ago. Is there still interest in some of these? I still have some old PRs to migrate legacy tests open and can try to bring them up to date if that is wanted?

**Comment by justinmk** [comment]
@lucc We will want to merge your open PRs. We changed the policy "going forward" so that people merging vim-patches didn't spend time migrating Vim "new-style" tests. 

> I still have some old PRs to migrate legacy tests open and can try to bring them up to date if that is wanted?

Yes. One thing to note: if an "old style" (`.in`) vim test was migrated in Vim to a "new style" (`.vim)` test, we want to keep the `.vim` _and_ our own `.lua` migrated test. For two reasons: (1) the TSAN build only runs against legacy tests; and (2) it makes it easier to migrate vim patches.

**Comment by lucc** [comment]
Ok.  I have update some of [these PRs](https://github.com/neovim/neovim/pulls/lucc).

**Pull request closed without merging**
