### PR TITLE
Reproducible builds: Honor compilation date in $SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by jamessan**
There is an ongoing effort[0](https://reproducible-builds.org/) to make FOSS software reproducibly
buildable.  In order to make NeoVim build reproducibly, it is necessary
to allow defining the date/time used in longVersionWithDate as part of
the build process.

This commit enables that by adding support for the SOURCE_DATE_EPOCH
spec[1](https://reproducible-builds.org/specs/source-date-epoch/).  When the $SOURCE_DATE_EPOCH environment variable is defined,
it will be used to define the NVIM_VERSION_BUILD_DATE preprocessor
define.

If NVIM_VERSION_BUILD_DATE is not defined, the existing behavior of
relying on the preprocessor's `__DATE__`/`__TIME__` symbols will be used.

### CODE REVIEW

**Comment by jamessan** [comment]
You can see the effect of `$SOURCE_DATE_EPOCH` in my Travis [builds](https://travis-ci.org/jamessan/neovim/builds/95706704) as I added `SOURCE_DATE_EPOCH=0` in the environment.

**Comment by ZyX-I** [comment]
I do not like the idea of using `date`: it is AFAIK not available on Windows. On the other side `strftime` C function is a part of C99 standard which is the standard compiler already must support to compile Neovim. Thus I would suggest compiling a C program, using it and deleting then.

Also see https://cmake.org/Bug/view.php?id=15238: somebody suggested to have `strftime` in CMake. This feature is not still there according to the tracker.

**Comment by jamessan** [comment]
Any tips on how to do that with CMake?  `try_run` should work, but not when cross-compiling.

**Comment by Pyrohh** [comment]
Perhaps we could just remove the use of `__{DATE,TIME}__` in `version.c`? The commit hash is already shown in the `--version` output, so I don't think the date/time is of much help.

**Comment by Pyrohh** [comment]
```diff
diff --git a/src/nvim/version.c b/src/nvim/version.c
index 83a47c2..cf557a9 100644
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -35,8 +35,6 @@
 
 char *Version = VIM_VERSION_SHORT;
 char *longVersion = NVIM_VERSION_LONG;
-char *longVersionWithDate = NVIM_VERSION_LONG \
-                            " (compiled " __DATE__ " " __TIME__ ")";
 #ifdef NVIM_VERSION_COMMIT
 char *version_commit = "Commit: " NVIM_VERSION_COMMIT;
 #endif
@@ -1098,7 +1096,7 @@ void list_version(void)
 {
   // When adding features here, don't forget to update the list of
   // internal variables in eval.c!
-  MSG(longVersionWithDate);
+  MSG(longVersion);
 #ifdef NVIM_VERSION_COMMIT
   MSG(version_commit);
 #endif

```

**Comment by justinmk** [comment]
@Pyrohh I wonder the same thing. That datestamp is often more confusing than useful for end users. Distros like Debian can (and _should_, if they make changes to C source or runtime files)  modify NVIM_VERSION_PRERELEASE to stamp the build as needed.

@jamessan what do you think?

**Comment by jamessan** [comment]
The commit id is only used when building from a git repo, so that's not really relevant here.  NeoVim doesn't include the release date in the version string, so the compilation date is less important.

With Vim, where releases happen once every few years, the compilation date (along with the `Included patches`) help clarify how recent the Vim actually is.  Since the release process for NeoVim is hopefully going to better than with Vim, the extra metadata may indeed not be necessary.

I'll have to think about NVIM_VERSION_PRERELEASE when I get back to working on Debian's packaging.

**Comment by jamessan** [comment]
I'm fine with either approach (eliminate date or allow defining it) as they both achieve the goal of improving reproducibility, so just let me know which way to go.

**Comment by justinmk** [comment]
Let's remove the date.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/pull/3839

**Comment by Pyrohh** [comment]
I'll close this so it's not forgotten about, but please reopen if I've missed something.

**Comment by justinmk** [comment]
@jamessan https://github.com/neovim/neovim/pull/3952 removed the build-date stamp.

**Comment by jamessan** [comment]
:+1: Thanks.

**Pull request closed without merging**
