### PR TITLE
[RFC] Fuzzy match option for completion popup, based on fzy.

### PR DESCRIPTION
**Pull request by mrbiggfoot**
Bring fuzzy matching algorithm from [fzy](https://github.com/jhawthorn/fzy) to completion popup. It can be enabled by `set completeopt+=fuzzy`. Note that the files under `src/nvim/fzy/` dir are copied from `fzy` project with minimal changes intentionally, to make it easier to update them in the future, if needed.

### CODE REVIEW

**Comment by mrbiggfoot** [comment]
Looked at the failures briefly... don't think that they were caused by my diff. Please let me know if it's not the case.

**Comment by mrbiggfoot** [comment]
To make sure it is not overlooked - the algorithm from fzy works only with English characters. That works for me, but may be an issue for many people.

**Comment by mrbiggfoot** [comment]
Keeping it in my for for now, as apparently it's not ready for prime time.

**Comment by justinmk** [comment]
For reference, from our discussion in chat:

* What does this solve that is not possible with `completefunc`?
* `completefunc` doesn't get internal candidates. Can we expose these to `completefunc`? 
  * Or should there be new hooks for matching & sorting the built-in completion candidates (`matchfunc`, `sortfunc`)
* To call a C implementation one may use `libcall()` (VimL function)

**Comment by mrbiggfoot** [comment]
Feel free to use my fork https://github.com/mrbiggfoot/neovim for fuzzy completion functionality.

**Comment by Shougo** [comment]
> What does this solve that is not possible with completefunc?

I think it is possible and it is already implemented by other plugins.
But it increases flicker.

If neovim supports the feature, we get fuzzy matched results without flickering.
So the feature is useful.

> Feel free to use my fork https://github.com/mrbiggfoot/neovim for fuzzy completion functionality.

I will test it with deoplete later.
But it includes some C++ codebase...
It seems hard to merge.

**Comment by Shougo** [comment]
> Feel free to use my fork https://github.com/mrbiggfoot/neovim for fuzzy completion functionality.

I have tested it.
It works well with deoplete.

But if completeopt is `noinsert,fuzzy`, the candidate cursor move to the bottom.
It is non intended behavior.

**Pull request closed without merging**
