### PR TITLE
Folded hl group not applied on folded lines with syntax matches

### PR DESCRIPTION
**Pull request by teto**
address the match part of https://github.com/neovim/neovim/issues/12982

### CODE REVIEW

**Comment by lervag** [comment]
I can confirm that this seems to solve the issue I raised within #12982. Thanks!

One more thing, though; there seems to be one more a glitch in the folded lines, where the foldtext seems to be considered to be "too long" so the `:help lcs-extends` listchars option is activated. Minimal example:

```vim
syntax enable
silent edit test.txt
normal! zM
```

```txt
{{{ test 1

}}}
{{{ test 2

}}}
{{{ test 3

}}}

# vim: fdm=marker
```

Open with `nvim -u test.vim` in a 80 column terminal (I don't expect that to matter) , and you should notice immediately the glitch at the rightmost column. I've attached a screenshot. The glitch goes away if you do `set nolist` after opening the files (but this does not work if you add `set nolist` to the minimal vim file).

**Comment by teto** [comment]
thanks for the feedback, it's very useful as we get to a fold refactoring




































(can't find the screenshot ?) thanks for the bug report,  they are really helpful as we refactor folds. I'll look into it.

**Comment by lervag** [comment]
Sorry, the screenshot is attached now. My mistake! And I'm glad to hear you find the reports useful. I wish I had both more time and more skill to be more actively useful to the neovim community. But little is more than nothing! :)

**Comment by vigoux** [comment]
I think that what @teto wanted to say is that the quality and reproducibility of your reports makes you what you call an "actively usefu" contributor to the neovim community :wink:

**Comment by teto** [comment]
@lervag I can reproduce the issue but in my own example its flaky so I will keep this in mind while further refactoring the folds and merge this fix that is more visible.

**Comment by lervag** [comment]
@teto thanks. Not sure what you mean with "in my own example its flaky so I will keep this in mind while further refactoring the folds and merge this fix that is more visible", but if it means you will keep this type of visual issues in mind while working on the refactoring of the fold code, then I'm glad :)

**Comment by teto** [comment]
just what you said :)

**Pull request merged**
