### PR TITLE
[RFC] vim-patch:7.4.598 and related

### PR DESCRIPTION
**Pull request by glts**
Why merge these patches in one batch:
-   `7.4.445` changed some clipboard stuff, but then
-   `7.4.598` undid these changes and implemented a different solution,
-   `7.4.607` then fixed a compiler warning, and
-   `7.4.608` fixed the test which was broken in 598.

The only real changes were in 598, but the clipboard handling code in `start_global_changes` and `end_global_changes` was removed in Neovim so no changes were actually applied in C. Not 100% sure that this is correct, but I verified that it works as tested in Neovim, just as it does in Vim after 598.

Perhaps someone familiar with the new clipboard handling take a look?

### CODE REVIEW

**Comment by glts** [comment]
@Pyrohh Actually I agree with @fwalch's suggestion in #2271 to not actually distinguish between NA and not NA patches.

It was hard for me to decide which ones to mark NA in this pull request. I could have marked all as NA since the clipboard handling doesn't work like that in Neovim, but I did migrate a test, and the clipboard functionality does work in Neovim, so this stuff is still 'available' so to speak.

**Comment by Pyrohh** [comment]
I think you might be misinterpreting me (or vice versa), but I wasn't talking about whether to mark a patch as NA or included, I just meant that you should mention in the commit message of https://github.com/glts/neovim/commit/43d34d6ec68aa5e8cae1b6873670b53012adfb20 why you only marked it as NA. As it currently is, someone might see that commit and wonder why it mentions a "Problem" and "Solution", but there doesn't seem to be a solution.

**Comment by glts** [comment]
@Pyrohh right, sorry, I overlooked the

> in the commit message

part of your message. Will reword during squash.

**Comment by glts** [comment]
... no, I will just reword (add explanation to) the commit message.

**Comment by glts** [comment]
I added a sentence about why 607 is not applicable as discussed. No more changes from me.

**Comment by Pyrohh** [comment]
Could you take a look at this @bfredl?

**Comment by Pyrohh** [comment]
LGTM

**Comment by Pyrohh** [comment]
cc @bfredl, this seems to be your area of expertise (or so I think)

**Comment by splinterofchaos** [comment]
Does vanilla vim cache the clipboard locally or something? We de it totally differently, offloading that to the provider, but the tests can't hurt.

> It was hard for me to decide which ones to mark NA in this pull request.

My rule of thumb is: Will a plugin writer ever, possibly want to check `has('patch#')` in order to work around a bug? It looks to me like "no" would be the answer for all of these, so we can mark them all NA.

**Comment by glts** [comment]
I haven't touched this in a long time.

I'm not familiar with the clipboard stuff (unfortunately the clipboard integration doesn't really work for me, see open bugs) which is why I'd rather not take care of these patches myself. Closing.

**Pull request closed without merging**
