### PR TITLE
[RFC] Add options to change alignment of number/relativenumber

### PR DESCRIPTION
**Pull request by chocolatemelt**
Currently, number and relativenumber both align right. When used together, the current line number aligns left for readability. However, due to most configs highlighting the current line number, this change in alignment is no longer needed and it becomes more consistent to keep alignment one way.

This pull request adds two options - 'lalign/la' and 'ralign/ra.' lalign/la left aligns all line numbers, while ralign/ra right aligns specifically the current line when both number and relativenumber are set. The options are a little unintuitive but they basically do the opposite alignment of the default behavior. Both options are set to FALSE by default.

### CODE REVIEW

**Comment by justinmk** [comment]
Nice to see someone step up with some code for this. 

Adding two new options for this is really questionable, though.

**Comment by chocolatemelt** [comment]
Yeah, I know - I figured some people out there would appreciate having the option to left align their numbers though, so I added that as a second option. Initially I only did this because having the current line number left aligned really bothered me, which is why my personal build only uses ralign.

**Comment by mhinz** [comment]
I'm quite passionless about this change, since I almost never use line numbers anyway. Usually I'd just wave this through, but I'm unsure if it's really worth introducing 2 new options.

Apart from that, the patch is not correctly indented and the names of the options should involve "number" somehow.

**Comment by justinmk** [comment]
Strongly against this change as-is.

- the option names are very unintuitive
- the options are _extremely_ specific (if every option were like this, Vim would have millions of options)
- adding _more than one_ option for this concept is obnoxious
- the options are separated in the help doc for reason I cannot tell

I don't mean to imply that fixing the above will warrant merging this, though. 

I would be in favor of a more generalized approach like `'lnumfunc'` which sets a function that is passed the line number and returns a string to show in the line number column. This would be evaluated for each line.

**Comment by noahfrederick** [comment]
FWIW, I would rather see effort towards allowing UIs to handle the display of number, sign, and fold columns than baking more options into core. Extensibility should be prioritized over configuration wherever possible.

Meanwhile, if there is something substantively wrong with the display of line numbers currently, it should be changed unconditionally. If not, it should be left alone. I would trade away 80% of Vim's existing options for sensible design if I could.

**Comment by justinmk** [comment]
@noahfrederick I agree, of course.

**Comment by philix** [comment]
Aligning to the left when `number` and `relativenumber` are set is a good default.

screen shot 2016-03-09 at 5 25 38 pm

Let's not clutter Neovim with many configuration options and try to come up with better defaults. IMO the alignment of line numbers is not important to achieve the goal of a great text editor.

**Comment by chocolatemelt** [comment]
@justinmk I believe I separated them for alphabetical order in the help doc, but I might have messed up there. Also, I wasn't entirely sure what I should've named them, but it does make sense to include 'number' in it. That being said I think it may be better to simply just have saner defaults.

With respect to better defaults over additional options, I think it makes more sense to only left align the current line number if highlighting is enabled, since as I understand it the left alignment is to keep the current line number stand out. With highlighting tthe current line number is already being highlighted, and thus no need to break up the line numbers' uniformity otherwise.

**Comment by justinmk** [comment]
Continued at https://github.com/neovim/neovim/pull/4941

**Pull request closed without merging**
