### PR TITLE
[RFC] vim-patch:7.4.1588

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    Old style test for quickfix.
Solution:   Turn test 96 into a new style test.

https://github.com/vim/vim/commit/1ff2b64b11e7d263c6853745d5e594bd8f94b91e

I have added test_quickfix.vim.
Note:  I should remove `test/functional/legacy/096_location_list_spec.lua` file?

### CODE REVIEW

**Comment by jamessan** [comment]
test_quickfix.vim as added as test/functional/legacy/quickfix_spec.lua in da9b6b1d.  Can you merge the new tests into that file?

**Comment by Shougo** [comment]
> test_quickfix.vim as added as test/functional/legacy/quickfix_spec.lua in da9b6b1. Can you merge the new tests into that file?

Well, I can merge it by hand.
But many of quickfix tests are added after the patch.
We must merge them by hand?
I think neovim should merge just test_quickfix.vim.

**Comment by jamessan** [comment]
> Note: I should remove test/functional/legacy/096_location_list_spec.lua file?

Yes, since all of its functionality will be moved to another test.

> We must merge them by hand?

That's what we've been doing so far.  Every change to test_quickfix.vim has been applied to quickfix_spec.lua.  Maybe this started before we decided to just keep the new style tests.

**Comment by Shougo** [comment]
> That's what we've been doing so far. Every change to test_quickfix.vim has been applied to quickfix_spec.lua. Maybe this started before we decided to just keep the new style tests.

I think it seems just wast of our time?
@justinmk  What do you think about it?

https://github.com/neovim/neovim/pull/5440
I think this test merge is OK.  Our assert tests are better than Vim one.
But test_quickfix is not.

**Comment by justinmk** [comment]
`legacy/quickfix_spec.lua` did not diverge from the old test very much, so merging upstream changes to it (such as https://github.com/vim/vim/commit/1ff2b64b11e7d263c6853745d5e594bd8f94b91e) should be the same amount of work.

**Comment by Shougo** [comment]
Added `legacy/quickfix_spec.lua`.

**Comment by jamessan** [comment]
Merged, with a couple indentation fixes.  Thanks!

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
