### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by justinmk** [comment]
vim-patch:8.0.0175: setting language on MS-Windows does not always work
vim-patch:8.0.0185: system() test fails on MS-Windows

**Comment by ckelsel** [comment]
patch 8.0.0424: compiler warnings on MS-Windows

**Comment by ckelsel** [comment]
vim-patch:8.0.0434: clang version not correctly detected

**Comment by ckelsel** [comment]
vim-patch:8.0.0458: potential crash if adding list or dict to dict fails

**Comment by impo** [comment]
vim-patch:8.0.0207: leaking file descriptor when system() fails

**Comment by justinmk** [comment]
@impo this one is closed, see https://github.com/neovim/neovim/pull/7999

**Pull request merged**
