### PR TITLE
Recognise *.ha files as `hare`

### PR DESCRIPTION
**Pull request by WhyNotHugo**
See: https://harelang.org/

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for the help! 

We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

Please send this change to the maintainer, listed at the top of the file: 

And also send the change to https://github.com/vim/vim, mentioning that you already sent the change to the maintainer.

**Comment by WhyNotHugo** [comment]
Will do, thanks.

**Comment by WhyNotHugo** [comment]
See: https://github.com/vim/vim/pull/10630

**Comment by clason** [comment]
Vim (and Neovim) requires a test for that, btw.  Look at previous "recognize foo" PRs to see the required format.

**Pull request closed without merging**
