### PR TITLE
vim-patch:8.0.0{529,623}

### PR DESCRIPTION
**Pull request by janlazo**
**vim-patch:8.0.0529: line in test commented out**

Problem:    Line in test commented out.
Solution:   Uncomment the lines for character classes that were failing before
            8.0.0519. (Dominique Pelle, closes vim/vim#1599)
vim/vim@13489b9

**vim-patch:8.0.0623: error for invalid regexp is not very informative**

Problem:    The message "Invalid range" is used for multiple errors.
Solution:   Add two more specific error messages. (Itchyny, Ken Hamada)
vim/vim@966e58e

### CODE REVIEW

**Comment by janlazo** [comment]
Not sure how to include [vim-patch:8.0.0646](https://github.com/vim/vim/commit/0946326580e6f034fe2c88d041407ea0fde980ab)

**Comment by justinmk** [comment]
@janlazo you mean because we changed some of the `profile_` functions? or why?

**Comment by janlazo** [comment]
@justinmk It's more involved than usual (run vim-patch.sh and copy/paste) because of the ifdefs and the explanation for the patch (make it slower on fast systems?). I don't know how the `profile_` functions work since I started compiling nvim last month so it's still trial-and-error for me.

**Comment by janlazo** [comment]
8.0.0644 and 8.0.0645 depend on 8.0.0643 so I'll leave it for later.

**Pull request merged**
