### PR TITLE
Refactor/reorganize Arabic source

### PR DESCRIPTION
**Pull request by alekulyn**
Moves macro definitions to the header file, adds the inline keyword to static bool functions, and refactors a function.

This would be my first Neovim contribution, so I'm taking baby steps at the moment.  I'll probably be adding more commits later on.

### CODE REVIEW

**Comment by justinmk** [comment]
Baby steps are good. I'm not sure how many arabic users we have, so this is a risky change. There's also [zero (0) test coverage of arabic.c in Vim](https://coveralls.io/github/vim/vim?branch=master) and Neovim. 

> Moves macro definitions to the header file

Why? That puts the defines in any module that imports `arabic.h`, for no reason. Before the change those defines were "private".

**Comment by alekulyn** [comment]
Hmm, good point.  I was actually thinking along the lines of "putting a module's definitions in the header" when I saw the same practice in farsi.h and made the change.  I figured since they are just preprocessor statements, they make no impact on the nvim executable itself.  If compiler performance is a concern, I can just null the first commit and squash that change into the second commit.

Admittedly, the organization the source in the arabic.* files isn't exactly efficient or intuitive at the moment, so any ideas would be appreciated.

**Comment by justinmk** [comment]
It's not a performance concern, but just general "good practice". Things that can be private should be private, to avoid "namespace" collisions, accidental usage. Things that can be isolated should be isolated to the smallest possible scope.

**Comment by alekulyn** [comment]
Yeah, merging vim patches is on my TODO, but the reason I've been looking at arabic.c/h is because I'm interested in implementing bidi.  Though Konsole supports bidi, Arabic doesn't seem to render correctly in it, even if `tbidi` is set.

**Pull request closed without merging**
