### PR TITLE
build: download dependencies with unreliable mirrors from deps repo

### LINKED ISSUE #23493: Unable to build neovim - payment required for libtermkey download
### Problem

I am trying to build neovim, and get this:

```
[  7%] Performing download step (download, verify and extract) for 'libtermkey'
-- verifying file...
       file='/xxxxx/.home/linux/aj_sources/neovim/.deps/build/downloads/libtermkey/libtermkey_0.22.orig.tar.gz'
-- SHA256 hash of
    /xxxxx/.home/linux/aj_sources/neovim/.deps/build/downloads/libtermkey/libtermkey_0.22.orig.tar.gz
  does not match expected value
    expected: '6945bd3c4aaa83da83d80a045c5563da4edd7d0374c62c0d35aec09eb3014600'
      actual: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/xxxxx/.home/linux/aj_sources/neovim/.deps/build/downloads/libtermkey/libtermkey_0.22.orig.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz'
CMake Error at libtermkey-stamp/download-libtermkey.cmake:170 (message):
  Each download failed!

    error: downloading 'https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
          Uses proxy env variable https_proxy == 'localhost:3122'
    Trying 127.0.0.1:3122...

  Connected to (nil) (127.0.0.1) port 3122 (#0)

  allocate connect buffer

  Establish HTTP proxy tunnel to launchpad.net:443

  CONNECT launchpad.net:443 HTTP/1.1

  Host: launchpad.net:443

  User-Agent: curl/7.86.0

  Proxy-Connection: Keep-Alive



  HTTP/1.1 402 Payment Required

  Cache-Control: no-cache

  Pragma: no-cache

  Content-Type: text/html; charset=utf-8

  Proxy-Connection: Keep-Alive

  Connection: Keep-Alive

  Content-Length: 1268



  The requested URL returned error: 402

  CONNECT phase completed

  Closing connection 0



          --- LOG END ---




make[3]: *** [build/src/libtermkey-stamp/libtermkey-download] Error 1
make[3]: Leaving directory `/xxxxx/.home/linux/aj_sources/neovim/.deps'
make[2]: *** [CMakeFiles/libtermkey.dir/all] Error 2
make[2]: Leaving directory `/xxxxx/.home/linux/aj_sources/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/xxxxx/.home/linux/aj_sources/neovim/.deps'
make: *** [deps] Error 2
```

The above happens when I am trying to build the latest version of neovim on my corporate server, at work. And it wasn't like that before. I tried to build neovim at home, and this problem is not happening.

The above suggests that launchpad.net may have recently introduced so sort of IP checks and requires the commerical entities to pay? While I may understand the reasons behind such decision, this adds the whole new level of complexity to the building process. And, while the amount of payment may be reasonable for my company, the amount of paperwork to make it happen may be prohibitive...

So, the question is, are there any alternatives to launchpad, to be used for neovim building?

### Steps to reproduce

make distclean
CC=/path/to/bin/cc make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=/xxxxxx/linux/local

### Expected behavior

Neovim build process downloads all the required dependencies.

### Neovim version (nvim -v)

Commit c14aa66cc

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

Red Hat Enterprise Linux Server release 7.9

### Terminal name/version

tmux

### $TERM environment variable

tmux-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by dundargoc**
Closes https://github.com/neovim/neovim/issues/23493.

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Do we need/want to backport this? Or do we only keep one version of each dep, so bumping on master would break past releases?

**Comment by dundargoc** [comment]
We can backport this, nothing should break. We're downloading the files from a specific commit, so it should always work.

**Comment by dundargoc** [comment]
> We're downloading the files from a specific commit

Uhh, they were supposed to be, I was certain they were lol. My bad. Fixup PR coming up.

**Comment by clason** [comment]
Not needed for master; just make a manual PR to `release-0.9` with the fixed commit.

**Pull request merged**
