### PR TITLE
fix(lsp): set noautocmd in floating windows

### LINKED ISSUE #25099: MatchParen highlight is applied to floating windows
### Problem

`MatchParen` highlights are applied in non-active floating windows, such as the one for LSP hover.

### Steps to reproduce

1. Use the tippy-top of nightly Neovim.
2. In a `lua` file write:
```lua
local foo = {
  bar = 0,
}
```
3. Hover over `bar`.
4. Notice how the parentheses around `field` are underlined (the `MatchParen` highlight is being applied) despite my cursor being in an entirely different window:
image

### Expected behavior

For the `MatchParen` highlight to only be applied in active windows and based on the cursor position.

### Neovim version (nvim -v)

v0.10.0-dev-1074+g4258f4d53

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.5.2

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

From source

### PR DESCRIPTION
**Pull request by MariaSolOs**
Round 2 of trying to fix #25099 :D

### CODE REVIEW

**Comment by lucario387** [comment]
Nitpick: I think the commit log should be in `lsp floating window` :D

**Comment by glepnir** [comment]
duplicate https://github.com/neovim/neovim/pull/15981

**Comment by glepnir** [comment]
And I don't think it's lsp relate issue, if `enter` is false I don't think it should trigger some au events. relate patch https://github.com/neovim/neovim/pull/25078

**Comment by MariaSolOs** [comment]
@glepnir my bad, sorry for the duplicate! I will make sure to check that in the future.

**Comment by MariaSolOs** [comment]
I'll keep this open then, although I expect that #25078 will fix this. I'll try the branch to check.

**Comment by MariaSolOs** [comment]
Confirmed, #25078 fixes this issue as well.

**Pull request closed without merging**
