### PR TITLE
vim-patch:8.2.3461: cannot distinguish Normal and Terminal-Normal mode

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.2.3461: cannot distinguish Normal and Terminal-Normal mode

Problem:    Cannot distinguish Normal and Terminal-Normal mode.
Solution:   Make mode() return "nt" for Terminal-Normal mode. (issue vim/vim#8856)
https://github.com/vim/vim/commit/72406a4bd2896915b6f541e26d41521a59b1f846

~Omit oldtests as Neovim's feedkeys() doesn't immediately enter terminal mode. Use Lua functional tests instead.~

### CODE REVIEW

**Comment by justinmk** [comment]
I _guess_ this is harmless and potentially useful. But semantically and programmatically, normal-mode in a Nvim `:terminal` buffer is like normal-mode in any other 'nomodifiable' buffer.

We can try it.

**Comment by zeertzjq** [comment]
In a `:terminal`, in Normal mode pressing `i` goes to Terminal-mode instead of Insert mode, so it is indeed somehow different from other Normal mode.

If a plugin that intends to support both Vim and Neovim checks if `mode` is `nt` to prevent doing something in Terminal buffer Normal mode (as it is indeed different from other Normal mode), this make that possible.

**Comment by zeertzjq** [comment]
> I _guess_ this is harmless and potentially useful. But semantically and programmatically, normal-mode in a Nvim `:terminal` buffer is like normal-mode in any other 'nomodifiable' buffer.
> 
> We can try it.
> 
> > Omit oldtests as Neovim's feedkeys() doesn't immediately enter terminal mode. Use Lua functional tests instead.
> 
> To avoid merge conflicts and make it easy to compare upstream tests, we generally include even "inert" tests. Just mark them as "skipped".

Is it possible to skip only several lines in a function?

**Comment by zeertzjq** [comment]
<https://github.com/vim/vim/pull/8856#issuecomment-919876326>

> It's true that Normal mode and Terminal-Normal mode differ, especially
> in that commands like "a" and "i" do something very different.  That
> would justify using "nt" for Terminal-Normal mode.

**Comment by justinmk** [comment]
> Is there a way to only mark several lines in a function as skipped?

We just try to find the minimal way. If it's only a couple, commenting them is fine. If it's many, guard them with a `if !has('nvim')` (without indentation)

**Comment by zeertzjq** [comment]
> > Is there a way to only mark several lines in a function as skipped?
> 
> We just try to find the minimal way. If it's only a couple, commenting them is fine. If it's many, guard them with a `if !has('nvim')` (without indentation)

I just found out `has('terminal')` (which guards added tests in original Vim patch) returns `0` in Neovim, so porting the added tests as-is makes Neovim skip them.

**Comment by zeertzjq** [comment]
I'll wait for some more updates from Vim. Converting to draft temporarily.

**Comment by zeertzjq** [comment]
I'll also defer this after #15886

**Comment by zeertzjq** [comment]
I rethought about this. This may not be very useful as there is already `buftype=terminal`. It is true that the behavior of `a` and `i` differ, but the behavior of `a` and `i` are affected by other buffer-local options like `modifiable` as well. I don't think adding a new mode `nt` can tell any new information.

**Comment by zeertzjq** [comment]
Currently the most likely solution to that is to just always call `trigger_modechanged` on buffer/window change and check if mode actually changed.

**Pull request merged**
