### PR TITLE
[RFC] MinGW: Build third-party deps in MinGW

### PR DESCRIPTION
**Pull request by sethjackson**
Cherry picked from #810. From equalsraf@2b53408.

### CODE REVIEW

**Comment by sethjackson** [comment]
Ping?

**Comment by equalsraf** [comment]
Need to clean this one first, there were a bunch of changes in 810 to third-party in the last couple weeks.

**Comment by equalsraf** [comment]
This can be closed, no longer applcable.

**Comment by sethjackson** [comment]
Yup. Been slacking sorry!

**Pull request closed without merging**
