### PR TITLE
fix(eval): callback_call can't handle v:lua function

### PR DESCRIPTION
**Pull request by kevinhwang91**
I think the patch should fix the issue caused by supporting lambda callback function for `qftf` (https://github.com/neovim/neovim/commit/4cb0bf09421e88adb812bb716b56af22bd51353e). But I don't know where the test should write to.
I search `callback_call` in the project, no test case is found.  Any guides are appreciated.

### CODE REVIEW

**Comment by bfredl** [comment]
Hmm how was the `Callback` object created, in this case? Ideally we should change that to store the lua function by reference, which is already supported.

**Comment by kevinhwang91** [comment]
> Hmm how was the `Callback` object created, in this case? Ideally we should change that to store the lua function by reference, which is already supported.

Do you mean parse `v:lua` prefer in the caller (here is `call_qftf_func`) rather than in `callback_call`?

**Comment by bfredl** [comment]
Hmm It is a bit tricky as we are merging values from function calls (`setqflist()`) where we do capture the lua function by value (otherwise `vim.fn.some_func(cb)` won't work) and from options where we currently don't. I'd say we coerce it to a lua reference in `call_qftf_func` if it be reasonable to implement.

**Comment by YorickPeterse** [comment]
I'm running into issues with other callbacks too. For example, `completefunc` no longer seems to work with `v:lua` callbacks. So handling this in the quickfix logic may not be enough.

**Comment by bfredl** [comment]
@YorickPeterse hmm are you sure? completefunc is covered by tests, and seems to work on latest master when I try.

**Comment by YorickPeterse** [comment]
@bfredl Oops you're right!

**Comment by gpanders** [comment]
@kevinhwang91 Are you still interested in pushing this through?

**Comment by gpanders** [comment]
@bfredl This is sufficient as-is to support `v:lua` function names as values for `'quickfixtextfunc'` which brings us to parity with `'omnifunc'` and `'completefunc'`. 

> It is a bit tricky as we are merging values from function calls (setqflist()) where we do capture the lua function by value (otherwise vim.fn.some_func(cb) won't work) and from options where we currently don't. I'd say we coerce it to a lua reference in call_qftf_func if it be reasonable to implement.

I don't follow what you mean here, could you explain? Would you be opposed to merging this one now and doing future improvements in a follow on PR?

**Comment by gpanders** [comment]
Merging this would also allow `v:lua` function references in other places that take callbacks (e.g. `prompt_setcallback`).

**Comment by zeertzjq** [comment]
This has been fixed.

**Pull request closed without merging**
