### PR TITLE
vim-patch:9.0.1393: Cairo files are not recognized

### PR DESCRIPTION
**Pull request by amaanq**
Problem:    Cairo files are not recognized.
Solution:   Add a pattern for Cairo files. (Amaan Qureshi, closes vim/vim#12118)

https://github.com/vim/vim/commit/ff226d49fed2d8fc668084324c7b0f00117c5e74

### CODE REVIEW

**Review by smjonas — APPROVED** [review]

**Review by zeertzjq — DISMISSED** [review]

**Comment by clason** [comment]
Test failure is consistent and can be reproduced locally.

**Comment by clason** [comment]
because the entry is in the wrong table -- should be in `extension`, not `filename`.

**Comment by gpanders** [comment]
Looks like this was incorrectly put in the `filename_checks` tests in Vim too https://github.com/vim/vim/commit/ff226d49fed2d8fc668084324c7b0f00117c5e74

**Comment by zeertzjq** [comment]
I don't think this can be put somewhere else in Vim.

**Comment by amaanq** [comment]
oops...

**Pull request merged**
