### PR TITLE
Add DiagnosticOk (and associated) highlight group

### PR DESCRIPTION
**Pull request by rktjmp**
(This is more of a question to the group, of whether its useful (I think so), but the patch was small enough that it was simpler to create a PR than an issue, _then_ a potential PR.)

The existing groups, Error, Hint, Info, Warn cover many use cases, but neglect the occasion where a diagnostic message should communicate a non-informative (not a Hint or Info) event. DiagnosticOk covers this with a generic green colorscheme.

I think this has value by also providing a _defaultly present_ "ok/good/success" highlight group for plugin developers, where the existing diagnostic groups can cover other needs, while also giving theme developers a common target to ... theme.

### CODE REVIEW

**Comment by gpanders** [comment]
I wonder if making a generic `Success` highlight group would be a better fit here. The only existing use case I can think of for this is the health checks, which currently uses its own `healthSuccess` highlight group. But with a more generic `Success` group, the health checks could link to that, and other plugins could use that as well.

Can you give some specific examples of what a `DiagnosticOk` highlight group would be used for? That would help clarify what the right name should be.

**Comment by rktjmp** [comment]
> Can you give some specific examples of what a DiagnosticOk highlight group would be used for? That would help clarify what the right name should be.

My actual use case is a plugin that runs a set of tasks. The tasks communicate "progress messages" (info) and a final result (ok, error). I am not specifically providing "syntax relevant diagnostics" like an LSP might - which is where the diagnostics groups seems to originate from - but I am providing "diagnostic feedback" per line so it seemed appropriate to link my own groups back to them - except there is no "no error" state.

I thought about submitting with a set of new `UI` groups, `UIOk` (`UISucess`?), `UIError`, `UIInfo` etc, but thought it might get pretty muddy in distinguishing what is a "diagnostic message" and what is a "ui message". An OS popup-warning-dialog telling me I'm "out of disk space" is both diagnostic && ui in my mind, so why duplicate the target groups? (But is a confirm-diaglog a diagnostic?) Probably useful in the the future but a bigger question than extending Diagnostics with basically one missing noun. 


> I'd go even further and suggest folding the healthFoo groups into the DiagnosticFoo groups (with default links for compatibility, of course) -- they seem generally to have a great degree of overlap.

```vim
healthError    xxx links to Error " -> DiagnosticError
healthWarning  xxx links to WarningMsg " -> DiagnosticWarn
healthSuccess  xxx ctermfg=232 ctermbg=82 guifg=#080808 guibg=#5fff00 " -> DiagnosticOk (Success?)
healthBar      xxx cleared " ->  health ui specific
healthHelp     xxx links to Identifier " -> DiagnosticInfo? (This is the "Build type: xxx" text)
" healthHelp could remain as Identifier (probably actually @text?) DiagnosticHint?
```

image

The use-case for Ok/Success in `:checkhealth` is basically the same as mine. I can PR a patch for the `checkhealth` syntax too if desired (dependent on this PR?), the idea makes sense to me.

**Comment by gpanders** [comment]
Thinking about this more I think I do lean toward `DiagnosticOk` rather than `Success`. `:checkhealth` is itself a diagnostic tool, so I also think we should create default links from the `healthXXX` highlight groups to the diagnostic groups.

`healthSuccess` => `DiagnosticOk`
`healthWarning` => `DiagnosticWarn`
`healthError` => `DiagnosticError`

That could be done in a follow up PR though.

**Review by gpanders — APPROVED** [review]

**Review by justinmk — APPROVED** [review]
LGTM, and also still in favor of adding a `Success` highlight. Then we could remove all the `healthFoo` highlights, they don't need custom highlights.

**Comment by clason** [comment]
> LGTM, and also still in favor of adding a `Success` highlight. Then we could remove all the `healthFoo` highlights, they don't need custom highlights.

The (my) idea was to remove `healthFoo` in favor of `DiagnosticFoo`-- in particular, `healthSuccess` would become `DiagnosticOk`; no need for a separate `Success` group.

**Pull request merged**
