### PR TITLE
feat(lua): add `vim.colorscheme`

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by zeertzjq** [comment]
Isn't this `vim.colorscheme`?

**Comment by lewis6991** [comment]
Yes, sorry, I changed my mind about adding to the API and forgot to change the commit message

**Comment by justinmk** [comment]
Why is this needed? We have `vim.cmd()` which also has (or will have) a structured variant based on `nvim_cmd`.

See also https://github.com/neovim/neovim/issues/18201#issuecomment-1107665957

**Comment by lewis6991** [comment]
One of the pieces of feedback I've noticed in general from users is that even though we have gone full Lua, users still need to learn vimscript, which quite frankly nobody wants, especially new users.

`vim.cmd` is an anti-pattern, and we shouldn't be recommending it as the first class way of doing anything in Lua. The command form of colorscheme IMO only exists for interactive use (as do all ex commands). Any command a user would typically write in their config/script should have a Lua equivalent.

Would you prefer we simply add:

```lua
function vim.colorscheme(name)
   if type(name) ~= string then
     error('argument 1 is not a string: ', name)
   end
   vim.api.nvim_cmd({cmd='colorscheme', args={name}}, {})
end
```
?

**Comment by lewis6991** [comment]
From #18201
> Duplicating every random Vim command in Lua achieves nothing, except a lot of useless, manually-written code.
> 
> We are working on a generalized interface to call Vim commands: #14966

Ergonomics always a significant factor when we consider adding things to the Lua lib.

The generalised interface to vim commands is great, but it is very verbose. Again, consider new users and ease of use.

**Comment by muniter** [comment]
Hope is not to noisy to mention here. What If we added some metatable magic to `vim.cmd` so it feels less "stringy" and make it a lot more ergonomic:

```lua
local c = vim.cmd
c.colorscheme 'gruvbox'
```
Can be easily translatable with metatables to `vim.cmd({ cmd = "colorscheme", args = { "gruvbox"})`

Would take making `vim.cmd` a table, and the values it returns functions that *support* overloading. If a table like array is passed use it as the command arguments, else pass it to vim.cmd but take care of the `cmd` field.

**Comment by justinmk** [comment]
No, this is not a strong enough reason for adding a new `vim.xx` surface area. `vim.cmd()` is not an antipattern, it's a reasonable way of calling Ex commands. 

- If one has a need for structure, then `vim.cmd({cmd=...,args=...})` is reasonable.
- If one is just doing basic configuration, `vim.cmd('colorscheme foo')` is perfectly fine.

I don't know where this idea that `vim.cmd()` an antipattern came from, but it isn't aligned with the project goals. Ex commands are a feature of vi, Nvim was forked from a vi-variant, there is absolutely zero reason to start down a path of discouraging their use, and it is very strongly not part of the project vision.

**Comment by justinmk** [comment]
> What If we added some metatable magic to `vim.cmd` so it feels less "stringy" and make it a lot more ergonomic:
> 
> ```lua
> local c = vim.cmd
> c.colorscheme 'gruvbox'
> ```
> 
> Can be easily translatable with metatables to `vim.cmd({ cmd = "colorscheme", args = { "gruvbox"})`

@muniter that could make sense, and aligns with existing patterns for `vim.fn` and `vim.o`. And it's generalized, so we aren't endlessly hand-crafting `vim.xx` wrappers, which I've made very clear is something to be avoided.

**Comment by lewis6991** [comment]
Careful @justinmk, let's not discourage (more) contributors by shutting things down too hastily.

With respect, I must say I really feel your opinion in regards project goals/vision are quite misaligned with a significant portion of how the user base feels. Visions/goals evolve with time and the decision to Lua-fy everything has been a monumental win to the project.

**Comment by justinmk** [comment]
The project goals haven't changed. If users are unhappy with Ex commands that's news to me. Is `:g` an antipattern? What about `:s` ?

**Comment by lewis6991** [comment]
Ex commands are fine, but users don't want to be writing these in scripts, that is what Lua is for. I didn't say ex commands were an anti-pattern, I said `vim.cmd` was, or specifically calling ex commands from a script. This alone has motivated a lot of development into the API over the last 2 years.

Ex commands serve a great purpose for interactive use as:
- they are less verbose to write in a command line
- can implement very precise completion
- have the added features like range, etc.

All reasons unimportant to a user script. 

Conversely ex commands in scripts:
- cannot easily be statically checked by LSP's or linters.
- cannot have completions provided for (e.g. `vim.<tab>` vs `vim.cmd.<tab>`)
- are just uglier
 
Different contexts are allowed to (and should) have different ways of doing something.

Take a look at many of the popular plugins that have been developed in the community. A lot of them implement an Ex command in addition to a Lua API. Specifically look at how I've developed Gitsigns to leverage both paradigms.

I've already demonstrated that reaching 100% Lua coverage of all Neovim features (in #18393) is very feasible and a very finite goal.

**Comment by justinmk** [comment]
> Conversely ex commands in scripts:
> 
> * cannot easily be statically checked by LSP's or linters.
> * cannot have completions provided for (e.g. `vim.<tab>` vs `vim.cmd.<tab>`)
> * are just uglier

Those are good points. Does @muniter 's suggestion address that?

**Comment by lewis6991** [comment]
Potentially, it is at least a nice compromise and provides nice ergonomics. For LSP features, something (or us) would need to generate some form of header file with all the function declartation and emmy lua annotations.

**Comment by justinmk** [comment]
> For LSP features, something (or us) would need to generate some form of header file with all the function declarations

Exposing builtin commands from `nvim_get_commands`, is a planned goal (would be driven by `ex_cmds.lua` probably).

**Comment by lewis6991** [comment]
I think it would be reasonable for us to package the header files into runtime somehow. Currently, users are using generated ones from [lua-dev](https://github.com/folke/lua-dev.nvim/tree/main/types)

**Comment by lewis6991** [comment]
> As a user, having a roughly one-to-one interface sounds nice compared to a bag of hand-crafted variants (except where we are truly adding value by introducing structure / features not possible in an automated way).

In regard to automation. The main issue is that we are trying to map `function -> ex`. To automate, this needs to be reversed to `ex -> function`.

For example we could refactor `ex_colorscheme` in `ex_docmd.c` to call an API function `set_colorscheme`, then the hand-crafted wrapper disappears... kind of.. since we end up leveraging all the API generator.
```c
static void ex_colorscheme(exarg_T *eap)
{
  if (*eap->arg == NUL) {
    char *expr = xstrdup("g:colors_name");
    char *p = NULL;

    emsg_off++;
    p = eval_to_string(expr, NULL, false);
    emsg_off--;
    xfree(expr);

    if (p != NULL) {
      msg(p);
      xfree(p);
    } else {
      msg("default");
    }
  } else if (load_colors((char_u *)eap->arg) == FAIL) {
    semsg(_("E185: Cannot find color scheme '%s'"), eap->arg);
  }
}
```

becomes:

```c

static void ex_colorscheme(exarg_T *eap)
{
   set_colorscheme(eap->arg);
}

static void set_colorscheme(String name)
{
  if (*name == NUL) {
    char *expr = xstrdup("g:colors_name");
    char *p = NULL;

    emsg_off++;
    p = eval_to_string(expr, NULL, false);
    emsg_off--;
    xfree(expr);

    if (p != NULL) {
      msg(p);
      xfree(p);
    } else {
      msg("default");
    }
  } else if (load_colors((char_u *)name) == FAIL) {
    semsg(_("E185: Cannot find color scheme '%s'"), eap->arg);
  }
}

```

We can then map `vim.cmd.colorscheme` to `set_colorscheme`.

API remains the same, but the implementation is way leaner since we avoid the whole cmd stack.

**Comment by justinmk** [comment]
That sounds good! So there's a small perf gain, no maintenance burden, and the interface and docs are still one consistent `vim.cmd.x` interface.

**Pull request closed without merging**
