### PR TITLE
docs: fix nvim_create_autocommand() typo

### PR DESCRIPTION
**Pull request by yochem**

### CODE REVIEW

**Comment by clason** [comment]
These docs are autogenerated; you need to fix the docstring in `vim/lsp.lua` and then run `make doc`.

**Comment by zeertzjq** [comment]
Duplicate of #31432

**Comment by clason** [comment]
Although if you fix this properly, we can go with this over the previous PR.

**Comment by yochem** [comment]
Will do.

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all small documentation fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/31328.

**Pull request closed without merging**
