### PR TITLE
test(lua): add basic profiler

### PR DESCRIPTION
**Pull request by lewis6991**
Nothing special, but effective at finding low hanging fruit.

Usage:

Add this to the very beginning of your init.lua:
```lua
local p = require('vim._profile')
p.profile('vim')

-- Optional for profiling specific regions
p.stop()
p.start()
```

Open Nvim, do some stuff, then run:

```
:ProfileReport [<pat>]
```

---
 Example output:

```
──────────────────────────────────────────────────────────────────────────────────────
name                                                         total    count        avg
──────────────────────────────────────────────────────────────────────────────────────
total                                                    4008.56ms
──────────────────────────────────────────────────────────────────────────────────────
vim.api.nvim_cmd                                          377.88ms       44  8588.25us
vim._with_c                                               373.47ms       18 20748.23us
vim.uv.fs_read                                            276.43ms      254  1088.30us
vim.treesitter._fold.foldexpr                             246.18ms    53784     4.58us
vim.treesitter.languagetree.parse                         200.61ms       83  2417.03us
vim._with                                                 186.82ms        9 20757.67us
vim.treesitter.languagetree._add_injections               164.48ms        6 27412.75us
vim.treesitter.languagetree._get_injections               158.65ms        6 26440.94us
vim.treesitter.foldexpr                                   127.51ms    26892     4.74us
vim.inspect.inspect                                       118.99ms      800   148.74us
vim.treesitter.get_parser                                 113.75ms    26958     4.22us
vim.api.nvim_buf_call                                     110.64ms        2 55320.54us
vim.split                                                  89.31ms    39920     2.24us
vim.treesitter.query.get                                   74.89ms       38  1970.80us
vim.lsp.semantic_tokens.__STHighlighter.process_response   72.55ms        2 36273.21us
vim.treesitter.language.get_lang                           67.71ms    38126     1.78us
vim.call                                                   66.68ms     4853    13.74us
vim.treesitter.query.parse                                 56.02ms       16  3501.16us
vim._ts_parse_query                                        55.71ms       16  3481.96us
vim.lsp.log.debug                                          50.52ms       58   871.11us
vim.loader.find                                            49.44ms      220   224.72us
vim.treesitter.languagetree.for_each_tree                  48.86ms      100   488.56us
vim.treesitter.languagetree._get_injection                 46.47ms    11280     4.12us
vim.uv.fs_scandir                                          43.07ms      129   333.89us
vim.fs.dir                                                 41.63ms       60   693.89us
vim.F.npcall                                               37.95ms        3 12651.51us
vim.str_byteindex                                          37.41ms    73492     0.51us
vim.treesitter.start                                       37.34ms        1 37342.42us
vim.treesitter._create_parser                              37.12ms        1 37120.00us
vim.validate                                               35.07ms   298656     0.12us
vim.gsplit                                                 35.05ms    40052     0.88us
vim.treesitter.get_node_text                               33.05ms    17534     1.88us
vim.treesitter.languagetree._parse_regions                 32.67ms       45   725.95us
vim.system                                                 27.73ms       14  1980.79us
vim.api.nvim_win_text_height                               27.00ms      199   135.66us
vim.api.nvim_set_option_value                              22.78ms      176   129.43us
vim.lsp.client._on_attach                                  19.22ms        1 19218.46us
vim.lsp.client._text_document_did_open_handler             18.92ms        1 18916.46us
vim.treesitter.get_range                                   18.76ms    34514     0.54us
vim.treesitter.query.get_files                             18.48ms       16  1155.18us
vim.lsp.client._notify                                     18.31ms        5  3662.60us
vim.treesitter.highlighter.for_each_highlight_state        17.86ms      517    34.54us
vim.treesitter.languagetree.new                            16.17ms        2  8085.00us
vim.treesitter.highlighter.get_query                       16.11ms       44   366.07us
vim.uv.hrtime                                              14.97ms    38818     0.39us
vim.api.nvim_get_runtime_file                              13.68ms       53   258.09us
vim.api.nvim_buf_set_option                                12.46ms        6  2076.89us
vim.api.nvim_buf_get_lines                                 12.21ms     1648     7.41us
vim.uv.spawn                                               11.79ms       14   842.49us
vim.endswith                                               10.82ms    11852     0.91us
vim.api.nvim_exec_autocmds                                  9.88ms      221    44.69us
```

### CODE REVIEW

**Comment by clason** [comment]
Is this specific to the `vim` module, or could plugins use this as well?

**Comment by lewis6991** [comment]
It can be used on plugins but the interface is a bit weird. `p.profile('vim')` will look at `_G.vim` and walk through it and wrap all the functions it can find.

For deferred modules, I've added a `_submodules` field, so the profiler knows what modules it can walk.

For plugins you could do something like:
```lua
_G.gitsigns = require('gitsigns')
p.profile('gitsigns')
-- or
p.profile('gitsigns', package.loaded)
```

but honestly I've not put that much thought into it. It's just something I've mocked up quickly that I've been able to use surprisingly effectively, so thought I'd share it. I'm aware there's lots of improvments that can be made, e.g. using `jit.p` instead.

**Comment by clason** [comment]
Just curious, this seems quite useful and much more foolproof than jit.p.

**Comment by lewis6991** [comment]
This seems to profile everything.

```lua
local profile = require('vim._profile').profiler
local orig_require = require
_G.require = function(m, ...)
  local r = {orig_require(m, ...)}
  profile(m, package.loaded)
  return unpack(r, 1, table.maxn(r))
end
```

**Comment by clason** [comment]
Could be default behavior (unless you specify a global module to profile)?

**Comment by justinmk** [comment]
Very cool. Do we want a tracking issue to include this as part of `:profile` report?

**Review by justinmk — APPROVED** [review]

**Comment by przepompownia** [comment]
With
```lua
local thisInitFile = debug.getinfo(1).source:match('@?(.*)')
local cwd = vim.fs.dirname(thisInitFile)
local appname = vim.env.NVIM_APPNAME or 'nvim'

vim.env.XDG_CONFIG_HOME = cwd
vim.env.XDG_DATA_HOME = vim.fs.joinpath(cwd, '.xdg', 'data')
vim.env.XDG_STATE_HOME = vim.fs.joinpath(cwd, '.xdg', 'state')
vim.env.XDG_CACHE_HOME = vim.fs.joinpath(cwd, '.xdg', 'cache')
vim.fn.mkdir(vim.fs.joinpath(vim.env.XDG_CACHE_HOME, appname), 'p')
local stdPathConfig = vim.fn.stdpath('config')

vim.opt.runtimepath:prepend(stdPathConfig)
vim.opt.packpath:prepend(stdPathConfig)

local function gitClone(url, installPath, branch)
  if vim.fn.isdirectory(installPath) ~= 0 then
    return
  end

  local command = {'git', 'clone', '--', url, installPath}
  if branch then
    table.insert(command, 3, '--branch')
    table.insert(command, 4, branch)
  end

  vim.notify(('Cloning %s dependency into %s...'):format(url, installPath), vim.log.levels.INFO, {})
  local sysObj = vim.system(command, {}):wait()
  if sysObj.code ~= 0 then
    error(sysObj.stderr)
  end
  vim.notify(sysObj.stdout)
  vim.notify(sysObj.stderr, vim.log.levels.WARN)
end

local pluginsPath = vim.fs.joinpath(cwd, 'nvim/pack/plugins/opt')
vim.fn.mkdir(pluginsPath, 'p')
pluginsPath = vim.uv.fs_realpath(pluginsPath)

--- @type table<string, {url:string, branch: string?}>
local plugins = {
  ['ultimate-autopair'] = {url = 'https://github.com/altermo/ultimate-autopair.nvim'},
}

local origRequire = require
local profile = origRequire('vim._profile')
_G.require = function (m, ...)
  local r = {origRequire(m, ...)}
  profile.profile(m, package.loaded)
  return unpack(r, 1, table.maxn(r))
end

for name, repo in pairs(plugins) do
  local installPath = vim.fs.joinpath(pluginsPath, name)
  gitClone(repo.url, installPath, repo.branch)
  -- vim.opt.runtimepath:append(installPath)
  vim.cmd.packadd({args = {name}, bang = true})
end

local ua = require('ultimate-autopair')

ua.setup({
  cr = {enable = false}
})

-- require('vim.snippet').expand('x')
```
I get the following at the start:
```
.../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:73: attempt to concatenate local 'n' (a boolean value)
stack traceback:
        ...ns/opt/ultimate-autopair/lua/ultimate-autopair/debug.lua:77: in function '__concat'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:73: in function 'profile'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:108: in function 'profile'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:108: in function 'profile'
        ...sues/current/2024-12-02-11.11.06-profiler-31135/init.lua:48: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function 'load_extension'
        ...-autopair/lua/ultimate-autopair/profile/default/init.lua:221: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function 'prepare_extensions'
        ...-autopair/lua/ultimate-autopair/profile/default/init.lua:101: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function <.../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:49>
        ...pt/ultimate-autopair/lua/ultimate-autopair/prof_init.lua:22: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function 'init_conf'
        ...pt/ultimate-autopair/lua/ultimate-autopair/prof_init.lua:28: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function <.../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:49>
        [C]: in function 'xpcall'
        ...ns/opt/ultimate-autopair/lua/ultimate-autopair/debug.lua:97: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function 'run'
        ...ins/opt/ultimate-autopair/lua/ultimate-autopair/init.lua:32: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function 'init'
        ...ins/opt/ultimate-autopair/lua/ultimate-autopair/init.lua:26: in function 'f'
        .../builds/from-src/share/nvim/runtime/lua/vim/_profile.lua:51: in function 'setup'
        ...sues/current/2024-12-02-11.11.06-profiler-31135/init.lua:61: in main chunk
```
`require('vim.snippet').expand('x')` (`require` used intentionally here) does not cause such error.

If I have disabled ultimate-autopair in my real env, Nvim starts without errors (~50 plugins loaded) and `:ProfileReport` shows some result.

**Pull request closed without merging**
