### PR TITLE
ci: give error if no tests were added for feature PRs

### PR DESCRIPTION
**Pull request by dundargoc**
Combine this with the `news.yml` workflow into a new workflow called
`new-feature.yml`.

### CODE REVIEW

**Comment by dundargoc** [comment]
Side-note: the scripting very ad-hoc, but that can be taken care of in an upcoming PR/refactor.

**Comment by zeertzjq** [comment]
What if it is feature for an environment not supported by CI?

**Comment by dundargoc** [comment]
I don't know. Any ideas?

**Comment by zeertzjq** [comment]
#20936 is an example

**Comment by dundargoc** [comment]
* any ideas on how to move forward? Is there a way to detect the situations you described? If not, is this still a good enough approximation for most feature PRs that it's more useful than harmful to have it?

**Comment by dundargoc** [comment]
Unsure if this is a big enough problem that this is required. I'll close it for now.

**Pull request closed without merging**
