### PR TITLE
fix(man): handle absolute paths as `:Man` targets

### PR DESCRIPTION
**Pull request by mqudsi**
Previously, attempting to provide `:Man` with an absolute path as the name would cause neovim to return the following error:

```
Error detected while processing command line:
/usr/local/share/nvim/runtime/lua/man.lua:690: /usr/local/share/nvim/runtime/lua/man.lua:683: Vim:E426: tag not found: nil(nil)
Press ENTER or type command to continue
```

..because it would try to validate the existence of a man page for the provided name by executing `man -w /some/path` which (on at least some Linux machines [0]) returns `/some/path` instead of the path to the nroff files that would be formatted to satisfy the man(1) lookup.

While man pages are not normally named after absolute paths, users shouldn't be blamed for trying. Given such a name/path, neovim would **not** complain that the path didn't have a corresponding man file but would error out when trying to call the tag function for the null-propagated name-and-section `nil(nil)`. (The same underlying error existed before this function was ported to lua, but did not exhibit the lua-specific `nil(nil)` name; instead a tag lookup for `()` would fail and error out.)

With this patch, we detect the case where `man -w ...` returns the same value as the provided name to not only prevent invoking the tag function for a non-existent/malformed name+sect but also to properly report the non-existence of a man page for the provided lookup (the absolute path).

While man(1) can be used to directly read an nroff-formatted document via `man /path/to/nroff.doc`, `:Man /path/to/nroff.doc` never supported this behavior so no functionality is lost in case the provided path _was_ an nroff file.

[0]: `man -w /absolute/path` returning `/absolute/path` observed on an Ubuntu 18.04 installation.

### CODE REVIEW

**Comment by mqudsi** [comment]
Maybe, with the eighth guidance? What kind of test? Which file should it go in? Any existing test I can model this on?

**Comment by lewis6991** [comment]
Try looking at `test/functional/plugin/man_spec.lua` and add a test there. Don't worry if you think it's too difficult, I just think niche problems like this benefit from some test coverage.

**Comment by mqudsi** [comment]
Your test harness and helper libraries are amazing, but there's definitely a huge learning curve! I hope what I added in the latest commit will serve. 

(I've previously rebased and force-pushed to address linter issues, so this should be good to go without squashing if it passes CI and you're happy with it.)

**Comment by zeertzjq** [comment]
This failed Cirrus CI

**Comment by mqudsi** [comment]
Oh I saw that and assumed it was a flaky CI issue because no one mentioned it and because it didn’t seem to actually be the test itself failing so much as a “n I’m on FreeBSD” thing. 

Do you have any ideas why?

**Comment by mqudsi** [comment]
For what it's worth, the man test passes for me under FreeBSD 13 with neovim compiled locally.

**Pull request merged**
