### PR TITLE
[RDY] Factor out float usage & remove '+float' references

### PR DESCRIPTION
**Pull request by ghost**
There is some more float usage in eval.c (a warning which come up with `-Wfloat-equal`), but this won't deal with it under the assumption that eval.c will eventually be replaced.

### CODE REVIEW

**Comment by aktau** [comment]
I had no idea this even existed :). I support the changing of floats to doubles where the precision could be important-ish, but does hardcopy have anything to do with +float?

**Comment by Pyrohh** [comment]
> does hardcopy have anything to do with +float?
It does not. I can easily split this in to two pull requests if needed.

**Comment by aktau** [comment]
No no, that's not needed. I was just inquiring :). The pr is fine as it is.

Am Samstag, 17. Januar 2015 schrieb Michael :

**Comment by Pyrohh** [comment]
It seems like your mail program is talking to me.

**Comment by fwalch** [comment]
> It seems like your mail program is talking to me.

You can [comment on Github issues via email](https://github.com/blog/811-reply-to-comments-from-email).

**Comment by Pyrohh** [comment]
> You can comment on Github issues via email, is that what you mean?

Heh, nah. I was referring to the footer with my name that leaked into @aktau's message.

**Comment by aktau** [comment]
> It seems like your mail program is talking to me.

Damn those mail programs! I'll have to teach it to stay inside next time. But seriously, I responded via mail because that's easier to do on a mobile phone. I was getting some breakfast at the time.

**Comment by fwalch** [comment]
> Heh, nah. I was referring to the footer with my name that leaked into @aktau's message.

Alright, sorry for the noise :-D

The PR looks good from what I can see, I'm only wondering whether `+float` should be removed from `version.c`? Other features are also "always on", but still listed in there.

**Comment by aktau** [comment]
> The PR looks good from what I can see, I'm only wondering whether +float should be removed from version.c? Other features are also "always on", but still listed in there.

I think this has been mentioned before, but the result was unclear. One of the things we were unsure about was if there were tools that were checking the output. Also we need to make sure things that check for `has('float')` will continue to work, because we effectively support it.

At any rate, down with needless `#ifdef`'s! It makes the code [hard to read](http://geoff.greer.fm/vim/#realwaitforchar).

**Comment by Pyrohh** [comment]
> I'm only wondering whether +float should be removed from version.c?

I don't see any reason to keep it, except to keep it for a PR to be made in the near future that would touch all of the `always on` flags for `--version`. The always on feature strings are misleading as they falsely imply that a feature can be enabled/disabled, as well as populating the `--version` output with useless information in the first place.

> One of the things we were unsure about was if there were tools that were checking the output

I think I remember that being mentioned, but I'll have to see it to believe it. I'm not really sure what the use case would be that necessitates such a thing, as a vimscript developer can just use `has('feature')`. I assume a client embedding nvim in itself could test for features via msgpack-rpc, but I don't actually know if that's true.

> Also we need to make sure things that check for has('float') will continue to work, because we effectively support it.

I just checked and it seems to works fine (assuming it's supposed to return `1` and not `true`).

**Comment by justinmk** [comment]
>  if there were tools that were checking the output. 

I recently discovered that https://github.com/dahu/vimple parses the output of `:version` (and breaks in Neovim), but this is just something that plugins are going to have to adapt to. But `has('feature')` will continue to work in Neovim.

>  a PR to be made in the near future that would touch all of the always on flags for --version. The always on feature strings are misleading as they falsely imply that a feature can be enabled/disabled, as well as populating the --version output with useless information in the first place.

:+1:

**Comment by aktau** [comment]
> The always on feature strings are misleading as they falsely imply that a feature can be enabled/disabled

While I agree in principle, Neovim is for all intents and purposes still a Vim. So for someone coming from that world (and we hope there are many), it's still handy to see at a glance which features Neovim does support as opposed to vanilla. Perhaps when Neovim gets a larger userbase we can diverge more.

**Comment by Pyrohh** [comment]
@aktau Maybe, but IIRC there's already a link in README.md to the differences between Neovim and Vim, where it mentions the difference in features.

**Comment by Pyrohh** [comment]
Marking as ready if no one objects.

**Comment by Pyrohh** [comment]
(small bump)

**Pull request merged**
