### PR TITLE
[WIP] add extra string handling functions

### PR DESCRIPTION
**Pull request by aktau**
This is WIP, I'm just putting this in a PR so other people can look and give suggestions.

ref: #859

### CODE REVIEW

**Comment by jszakmeister** [comment]
@aktau This seems to be in an unresolved state, so I'm closing it for now.  If you feel differently, please reopen it.  I know your situation is different today too, so picking it up might be less of an option.

**Comment by aktau** [comment]
Makes sense to close it for now, less admin overhead and all :). :+1: 

It's true that I have less time at the moment, but at least the legal issues have been cleared up. I expect/hope that in a few more months I will get some weekend-time to start contributing once more. Will keep you all appraised.

**Comment by jszakmeister** [comment]
> It's true that I have less time at the moment, but at least the legal issues have been cleared up. I expect/hope that in a few more months I will get some weekend-time to start contributing once more. Will keep you all appraised.

I'm glad to hear that!  I hope things shake loose for you!

**Comment by aktau** [comment]
Funnily enough, it appears that now the Linux kernel is adding a function that more or less has the semantics as `(x)stracpy()` in this PR:

- http://lwn.net/Articles/642665/
- http://lwn.net/Articles/643140/

Not sure if all those pages are readable to non-subscribers, but they should become readable in about a week or so.

I also think it's a saner choice, from both a safety and a performance POV. (Safety because it doesn't try to read over `n` bytes, ever. Although to be fair it's still possibly that the `src` array is both smaller than `n` _AND_ is not NUL-terminated, which would cause trouble, but that's a fringe-fringe case that only `xstrucpy` can solve).

**Pull request closed without merging**
