### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by ckelsel** [comment]
vim-patch:8.0.0304: assign test fails in the GUI

**Comment by ckelsel** [comment]
vim-patch:8.0.0312: failure when a channel receives a split json message

**Comment by ckelsel** [comment]
vim-patch:8.0.0312: failure when a channel receives a split json message

**Comment by ckelsel** [comment]
vim-patch:8.0.0317: no test for setting 'guifont'
vim-patch:8.0.0318: small mistake in 7x13 font name

**Comment by ckelsel** [comment]
vim-patch:8.0.0329: xfontset and guifontwide are not tested

**Comment by ckelsel** [comment]
vim-patch:8.0.0332: GUI test fails on some systems

**Comment by ckelsel** [comment]
vim-patch:8.0.0342: double free with EXITFREE and setting 'ttytype'

**Comment by ckelsel** [comment]
vim-patch:8.0.0348: using shadow dir on Mac lack +clipboard

**Comment by ckelsel** [comment]
vim-patch:8.0.0356: leaking memory when setting 'ttytype'

**Comment by ckelsel** [comment]
vim-patch:8.0.0371: leaking memory when setting v:completed_item

**Comment by ckelsel** [comment]
vim-patch:8.0.0375: the "+ register is not tested

**Comment by ckelsel** [comment]
vim-patch:8.0.0382: warning in tiny build for unused variable

**Comment by ckelsel** [comment]
vim-patch:8.0.0383: misplaced vim/vim#ifdef

**Comment by ckelsel** [comment]
vim-patch:8.0.0384: timer test failed for no apparent reason

**Comment by ckelsel** [comment]
vim-patch:8.0.0403: GUI tests may fail

**Comment by ckelsel** [comment]
vim-patch:8.0.0409: set_progpath is defined but not always used

**Comment by ckelsel** [comment]
vim-patch:8.0.0416: setting v:progpath is not quite right

**Comment by ckelsel** [comment]
vim-patch:8.0.0419: test for v:progpath fails on MS-Windows

**Comment by ckelsel** [comment]
vim-patch:8.0.0438: the fnamemodify test may cause later tests to fail

**Comment by jamessan** [comment]
> vim-patch:8.0.0438: the fnamemodify test may cause later tests to fail

This test still exists, but it's been ported to lua -- test/functional/legacy/fnamemodify_spec.lua.  These changes likely still matter.

**Comment by ckelsel** [comment]
vim-patch:8.0.0441: dead code in vim/vim#ifdef

**Comment by justinmk** [comment]
vim-patch:8.0.0438

**Comment by ckelsel** [comment]
vim-patch:8.0.0447: getting font name does not work on X11

**Comment by ckelsel** [comment]
vim-patch:8.0.0450: v:progpath is not reliably set

**Comment by janlazo** [comment]
vim-patch 8.0.0362: tests fail on MS-Windows

**Comment by janlazo** [comment]
vim-patch 8.0.0809: MS-Windows: tests hang
vim-patch 8.0.0810: MS-Windows: tests still hang
vim-patch 8.0.0811: MS-Windows: test_expand_dllpath fails

**Comment by janlazo** [comment]
vim-patch:8.0.0857: terminal test fails on MS-Windows

**Comment by janlazo** [comment]
vim-patch:8.0.0881: win32.mak no longer included in Windows SDK

**Comment by janlazo** [comment]
vim-patch:8.0.0845: MS-Windows: missing semicolon in terminal code
vim-patch:8.0.0856: MS-Windows: terminal job doesn't take options
vim-patch:8.0.0857: terminal test fails on MS-Windows

**Comment by janlazo** [comment]
vim-patch:8.0.1121: can uncheck executables in MS-Windows installer
vim-patch:8.0.1191: MS-Windows: missing 32 and 64 bit files in installer 
vim-patch:8.0.1472: MS-Windows: nsis installer is a bit slow

**Comment by janlazo** [comment]
vim-patch:8.0.1192: MS-Windows: terminal feature not enabled by default
vim-patch:8.0.1195: can't build on MS-Windows

**Comment by janlazo** [comment]
vim-patch:8.0.1197: MS-Windows build instructions are not up to date
vim-patch:8.0.1234: MS-Windows: composing chars are not shown properly

**Comment by janlazo** [comment]
vim-patch:8.0.0925: MS-Windows GUI: channel I/O not handled right away

**Comment by janlazo** [comment]
vim-patch:8.0.0415: balloon test fails on MS-Windows

**Comment by ckelsel** [comment]
vim-patch:8.0.0456: typo in MinGW test makefile

**Comment by ckelsel** [comment]
vim-patch:8.0.0460: can't build on HPUX

**Comment by ckelsel** [comment]
patch 8.0.0462: failure of an MS-Windows test may go unnoticed

**Comment by ckelsel** [comment]
vim-patch:8.0.0463: side effects from resetting 'compatible' in defaults.vim

**Comment by ckelsel** [comment]
vim-patch:8.0.0464: can't find executable name on Solaris and FreeBSD

**Comment by justinmk** [comment]
> vim-patch:8.0.0304: assign test fails in the GUI

Changes to most old tests should be included. It makes merging easier.

**Comment by justinmk** [comment]
@ckelsel @janlazo Thanks for the notes. Future request: please "edit" a single comment instead of adding a new comment for each patch.

**Pull request merged**
