### PR TITLE
[RFC] 20+ Vim patches which are related to increment and marks

### PR DESCRIPTION
**Pull request by watiko**
```
vim-patch:7.4.1089

Problem:    Repeating CTRL-A doesn't work.
Solution:   Call prep_redo_cmd(). (Hirohito Higashi)
```

https://github.com/vim/vim/commit/ef2b5036b3005f1ce15d146dce72379a9834c56d

```
vim-patch:7.4.1088

Problem:    Coverity warns for uninitialized variables.  Only one is an actual
problem.
Solution:   Move the conditions.  Don't use endpos if handling an error.
```

https://github.com/vim/vim/commit/7ae4fbca552c972eb3645ece02a2807e517610d7

```
vim-patch:7.4.1087

Problem:    CTRL-A and CTRL-X do not work properly with blockwise visual
selection if there is a mix of Tab and spaces.
Solution:   Add OP_NR_ADD and OP_NR_SUB. (Hirohito Higashi)
```

https://github.com/vim/vim/commit/d79e55016cf8268cee935f1ac3b5b28712d1399e

```
vim-patch:7.4.1085

Problem:    The CTRL-A and CTRL-X commands do not update the '[ and '] marks.
Solution:   (Yukihiro Nakadaira)
```

https://github.com/vim/vim/commit/a52dfaed104183c1fa2a3b6e4430b23d86bcbece

```
vim-patch:7.4.1084

Problem:    Using "." to repeat CTRL-A in Visual mode increments the wrong
numbers.
Solution:   Append right size to the redo buffer. (Ozaki Kiichi)
```

https://github.com/vim/vim/commit/e1edc1caba05c553fa60b1cf45a7670b1cfd63fe

```
vim-patch:7.4.1076

Problem:    CTRL-A does not work well in right-left mode.
Solution:   Remove reversing the line, add a test. (Hirohito Higashi)
```

https://github.com/vim/vim/commit/6a3c8aff0439c8406082760c54b26e00ff19a90c

```
vim-patch:7.4.1072

Problem:    Increment test is old style.
Solution:   Make the increment test a new style test. (Hirohito Higashi)
```

https://github.com/vim/vim/commit/450919587d4566ce3d17e685e183d5c17d9c2a11
https://github.com/vim/vim/commit/44132a10aeb45c957959cafb4ac39d3f478be98c

```
vim-patch:7.4.1065

Problem:    Cannot use the "dll" options on MS-Windows.
Solution:   Support the options on all platforms.  Use the built-in name as
the default, so that it's clear what Vim is looking for.
```

https://github.com/vim/vim/commit/25e4fcde767084d1a79e0926bc301c92987c0cce

```
vim-patch:7.4.1029

Problem:    test_increment fails on systems with 32 bit long.
Solution:   Only test with 32 bits.
```

https://github.com/vim/vim/commit/d3343960d7745bd586197a28b9a96d634a292422

```
vim-patch:7.4.1027

Problem:    No support for binary numbers.
Solution:   Add "bin" to nrformats. (Jason Schulz)
```

https://github.com/vim/vim/commit/887c1fea4a114e7170091942d0446c8882701b5b

```
vim-patch:7.0212 Add missing test case

Add test59's test 8-8.
```

https://github.com/vim/vim/commit/8fd89f0fe79e3fe2e1b64a808d1c7caca333af89
https://github.com/vim/vim/commit/0b23879827f9a97af3f621f974f91fa7a6b8c45c

```
vim-patch:7.4.848

Problem:    CTRL-A on hex number in Visual block mode is incorrect.
Solution:   Account for the "0x". (Hirohito Higashi)
```

https://github.com/vim/vim/commit/5adfea1ac63e252556bccce54e92e8e10b58f592

```
vim-patch:7.4.823

Problem:    Cursor moves after CTRL-A on alphabetic character.
Solution:   (Hirohito Higashi, test by Christian Brabandt)
```

https://github.com/vim/vim/commit/25c2f6783a9d5f15e062bd5b085abe7deb121152

```
vim-patch:7.4.807

Problem:    After CTRL-V CTRL-A mode isn't updated. (Hirohito Higashi)
Solution:   Clear the command line or update the displayed command.
```

https://github.com/vim/vim/commit/0bbcb5c8efbfe5f1568f56b24ffd222d915916f6

```
vim-patch:7.4.806

Problem:    CTRL-A in Visual mode doesn't work properly with "alpha" in
'nrformat'.
Solution:   Make it work. (Christian Brabandt)
```

https://github.com/vim/vim/commit/cc218ab3caf983a0dcd3399beb8e1ecfcf0dd25d

```
vim-patch:7.4.782

Problem:    Still a few problems with CTRL-A and CTRL-X in Visual mode.
Solution:   Fix the reported problems. (Christian Brabandt)
```

https://github.com/vim/vim/commit/5d1bc78a2b9fbe3e3112afcde7c80eb19d5989f4

```
vim-patch:7.4.780

Problem:    Compiler complains about uninitialized variable and clobbered
variables.
Solution:   Add Initialization.  Make variables static.
```

https://github.com/vim/vim/commit/1db43b1145fe466b5d41af6744a08083983de3a9

```
vim-patch:7.4.779

Problem:    Using CTRL-A in a line without a number moves the cursor. May
cause a crash when at the start of the line. (Urtica Dioica)
Solution:   Do not move the cursor if no number was changed.
```

https://github.com/vim/vim/commit/3ec326198029d5a59413b3b8b33dbc9c06c4f28b

```
vim-patch:7.4.778

Problem:    Coverity warns for uninitialized variable.
Solution:   Change condition of assignment.
```

https://github.com/vim/vim/commit/ae2fe73abc954b8fd3dbd7994daa8e31e6690bd0

```
vim-patch:7.4.765

Problem:    CTRL-A and CTRL-X in Visual mode do not always work well.
Solution:   Improvements for increment and decrement. (Christian Brabandt)
```

https://github.com/vim/vim/commit/9bb1930af908338b68588e988be9601ad144af07

```
vim-patch:7.4.764

Problem:    test_increment fails on MS-Windows. (Ken Takata)
Solution:   Clear Visual mappings. (Taro Muraoka)
```

https://github.com/vim/vim/commit/6a57cce04801d3e8fe30d0dcd31f9325b38de2fe

```
vim-patch:7.4.754

Problem:    Using CTRL-A in Visual mode does not work well. (Gary Johnson)
Solution:   Make it increment all numbers in the Visual area. (Christian
Brabandt)
```

https://github.com/vim/vim/commit/3a304b23823b089e499063e8211c5695d049f3ba

```
vim-patch:7.4.634

Problem:    Marks are not restored after redo + undo.
Solution:   Fix the way marks are restored. (Olaf Dabrunz)
```

https://github.com/vim/vim/commit/f65aad5554f1d1f972f0bd38059da70e3cdf4c87
https://github.com/vim/vim/commit/35e7594dd429f7a8a06cefd61c3e8d48b9bd74e2

### CODE REVIEW

**Comment by wsdjeg** [comment]
:+1:

**Comment by watiko** [comment]
Sorry, I did not check PRs. There are some precedents. But I have no time to sort out from commits currently.

**Comment by Shougo** [comment]
NIce work.

More C-A patches is available.

7.4.807

**Comment by watiko** [comment]
@Shougo Thanks! I updated PR.

**Comment by Shougo** [comment]
@watiko :+1:

**Comment by watiko** [comment]
This PR contains the #3916 equivalent (7.4.1027) except for a `printf` feature and detailed docs. But if #3916 is merged, I'll modify this PR.

**Comment by watiko** [comment]
This PR revived some removed codes (see #4104). Because They are needed by block-wise Visual select.

**Comment by watiko** [comment]
@lucc Why did you remove `test 8-8` of `test58` in #3207?

cc: @bfredl

**Comment by bfredl** [comment]
because it was in test58 and not in test59 and I (wrongly) assumed they where identical (modulo `&encoding`). Thanks for fixing it :+1:

**Comment by justinmk** [comment]
Not sure if this bug is present in Vim, but there's a problem: repeating the increment depends on the _current_ cursor position. If the cursor is moved up, then the far lines won't get incremented by dot-repeat.

Steps to reproduce:

* insert a blank line, then some numbers:

```

1
2
```

* visually-select the numbers, then use `<c-a>` to increment
* move the cursor to the blank line, then use `.` to repeat the increment
    * only the first number is incremented

**Pull request merged**
