### PR TITLE
fix(decorations): validate botline for on_win

### PR DESCRIPTION
**Pull request by tomtomjhj**
Problem:
Many decoration providers (treesitter injection highlighting, semantic token highlighting, inlay hint) rely on the correctness of the `botline` argument of `on_win` callback. However, `botline` can be smaller than the actual line number of the last displayed line if some lines are folded. In such cases, some decorations will be missing in the lines not covered by `botline`.

Solution:
Validate `botline` when invoking `on_win`.

NOTE:
It seems that the old code was deliberately avoiding this presumably due to performance reasons. However, I haven't experienced noticeable lag after this change, and I believe the cost of botline computation would be much smaller than the cost of decoration providers.

### CODE REVIEW

**Comment by wookayin** [comment]
Related #24794 #13038

So upon `validate_botline`, `botline` will be set to the last visible line in the window (or just off-by-1 below it), right?

Also, there are untouched `botline_guess` in `test/functional/ui/decorations_spec.lua`.

**Comment by tomtomjhj** [comment]
> So upon validate_botline, botline will be set to the last visible line in the window (or just off-by-1 below it), right?

Yes. So the value passed to `on_win` is the 0-indexed line number of the last visible line. 

> Also, there are untouched botline_guess in test/functional/ui/decorations_spec.lua.

fixed

**Comment by tomtomjhj** [comment]
Hmm actually according to `:h getwininfo()`, `botline` ([`w_botline - 1`](https://github.com/tomtomjhj/neovim/blob/df08b910b0a036b4d65f00223a5a21d7dff7b713/src/nvim/eval/window.c#L325)) is the "last complete displayed buffer line". This is not desirable for `on_win` because if the last displayed line is not completely displayed, it may not get appropriate decorations.

**Comment by lewis6991** [comment]
`validate_botline()` is fairly expensive since it goes through the plines logic, but I think it is worth doing nonetheless.

**Pull request merged**
