### PR TITLE
test: review conventions

### LINKED ISSUE #14375: Formalize an extension specification: make configuring neovim as easy as vscode
It would be nice to facilitate GUI based neovim configuration and it should be possible to make this as easy as vscode. In order to support that, we need several components:

1. A central manifest of plugins (vim-awesome?), with some categorization (github tags?) and sorting (stars?)
2. A model template for plugins (https://github.com/norcalli/neovim-plugin) with recommended practices (don't map keys by default is probably the big one)
3. A template for a `specification.json` (originally *.lua, but now I agree with @smolck) which exposes the available options of the plugin, with optional recommended default keybinds for example, in a way that a GUI based client can offer menu based configuration of the plugin.  This is similar to a package.json from a vscode extension. Final name tbd.

I'm making this as a tracking issue, as it gets brought up on IRC regularly and it would be nice to get feedback from plugin authors. I don't believe core should *implement* the GUI based configuration of neovim, but rather provide the infrastructure for plugin/GUI authors .

### LINKED ISSUE #27004: tests: improve test conventions (SUT, helpers.lua)
# Problem

Writing test code requires some "tribal knowledge" that requires the test author to understand which "helper" functions are dispatched to the `nvim` _test session_ (the "[SUT](https://en.wikipedia.org/wiki/System_under_test)") and which functions are handled in the context of the _test runner_.

Contributors must constantly be aware of the difference. Reading and writing tests can be confusing because of this, especially to non-experienced contributors.

# Expected behavior

Make the distinction clear by either extracting SUT functions to `test/sut.lua` or grouping them in a ~~sut~~ `nvim` container.

- [x] Rename `helpers.lua` to `testutil.lua` and change the import convention to (https://github.com/neovim/neovim/pull/28145):
   ```
   local t = require('testutil')
   ...
   t.foo()
   t.bar()
   ```
    - Thus there is no need anymore to do this:
      ```
      local helpers = require('testutil')
      local foo = helpers.foo
      local bar = helpers.bar
      ```
    - Test code can simply use `t.xx()` everywhere to call non-SUT test util functions.
- [ ] SUT functions live on `nvim`. When using SUT functions in test code, the usage looks like:
   ```lua
   nvim.api.nvim_get_commands()  -- instead of helpers.api.nvim_get_commands
   nvim.fn.foo()  -- instead of helpers.fn.foo()
   ```
    - See "Implementation" below.

# Implementation

Almost everything in `test/functional/testutil.lua` involves a "session". So in practice this would mean:

1. Lift any "pure" functionality (functions that don't require the nvim "test session") from `test/functional/testutil.lua` into `test/testutil.lua`.
    - `test/functional/testutil.lua` calls the `nvim` "test session" via RPC.
1. `test/testutil.lua` is no longer "merged" into `test/functional/testutil.lua`.
    - I.e. delete this line: https://github.com/neovim/neovim/blob/fd085d90820149caecf213b299f19e46305043ee/test/functional/testutil.lua#L19
1. Rename `test/functional/testutil.lua` to (e.g.) `…/nvimsession.lua`
1. All test imports now look like:
   ```lua
   -- Test runner functions/utils.
   local t = require('test.testutil')()
   -- Nvim RPC session.
   local nvim = require('test.functional.nvimsession')()
   ```
    - What should the test session be named?
        - ~~nvim? session? sut?~~ We decided on `n`.

# Future

Some questions to consider for the future (out of scope for this issue):

- Should `nvim` be a mirror of the nvim "test session" Lua stdlib? I.e. all `nvim.xx()` calls just dispatch to the Nvim "test session" `vim.xx()` ?
- Currently, we have a global "session": https://github.com/neovim/neovim/blob/f190f758ac58d9cc955368e047b070e0a2261033/test/functional/testutil.lua#L107-L113
    - This makes it less obvious what's going on in the tests.
    - It is weird that "screen" is used as an object in test code while "session" is not. Especially since the "screen" object is strictly tied to a session anyway. You cannot have multiple screens per session.
    - Solution: we could treat the Nvim session same as "screen", so tests would look like:
      ```
      local nvim = require('…/nvimsession.lua')
      local n = nvim.clear()
      n:command(':new foo')
      t.eq(2, n:eval('1+1'))
      ```

# Related

- https://github.com/neovim/neovim/pull/26994
- https://github.com/neovim/neovim/pull/27024

### PR DESCRIPTION
**Pull request by dsaenztagarro**
Resolves #27004

### CODE REVIEW

**Comment by dsaenztagarro** [comment]
@wookayin I can see your reaction being confused... it is my first time working on Neovim code.. can you please explain to me what you find unexpected? 

I'm glad of getting any feedback.. That's in fact the purpose of pushing a draft pull request ASAP..

**Comment by clason** [comment]
Can't speak for wookayin, but right now your PR isn't doing anything meaningful except renaming some files (which isn't the point of the issue you linked to). You may not be aware that maintainers get notified on every single force-push to a PR, so this is quite noisy. The convention is to open a (draft) PR only when you have a MVP done that at least _should_ resolve the issue.

**Comment by clason** [comment]
I can't speak for wookayin, but right now your PR isn't doing _anything_ meaningful. You might not be aware that maintainers get notified on every single force-push, so "doing this live" is _very_ noisy. The convention is to open a (draft) PR only when you have a MVP done that at least _should_ resolve the basic issue (or if you get stuck and need feedback on specific code).

I'm not sure this is actually the best issue to pick as a first contributions, as the test framework (especially unit tests) takes some getting used to.

**Comment by dundargoc** [comment]
> The convention is to open a (draft) PR only when you have a MVP done that at least should resolve the basic issue

Hmm, not to start an unrelated discussion but I don't think this is at all obvious from the CONTRIBUTING.md, it's almost opposite of what it says (since it indicates to me that you should open a PR as fast as possible).

> I'm not sure this is actually the best issue to pick as a first contributions, as the test framework (especially unit tests) takes some getting used to.

100% agree. I removed the `complexity:low` label because of this. I suspect high-grade narcotics were involved when that label was added.

**Comment by clason** [comment]
> Hmm, not to start an unrelated discussion but I don't think this is at all obvious from the CONTRIBUTING.md, it's almost opposite of what it says (since it indicates to me that you should open a PR as fast as possible).

Fair; we might want to temper that. (And I shouldn't have used the word "convention", even though that's what most contributors do.)

**Comment by dsaenztagarro** [comment]
> The convention is to open a (draft) PR **only when you have a MVP done that at least should resolve the basic issue**

Sorry, I wasn't aware of that, since it is not explicitly mentioned in the documentation:

https://github.com/neovim/neovim/blob/2e982f1aad9f1a03562b7a451d642f76b04c37cb/CONTRIBUTING.md?plain=1#L50-L58

Even if I'm used to the Github workflow, my current company Github plan doesn't include *Draft pull request* and so I wasn't aware anyone would get notifications. 

That all said, just some picks:

- I will close this PR to avoid creating more noise to maintainers.
- The only reason I picked this it was because it was originally tagged as a good first issue.
- You may want to split this issue in several parts to avoid affecting so many files in just one PR.

**Comment by clason** [comment]
> The only reason I picked this it was because it was originally tagged as a good first issue.

Yes, sorry, that was on us. Hope you didn't waste too much time, and looking forward to your next PR!

> You may want to split this issue in several parts to avoid affecting so many files in just one PR.

No, it's all or nothing (which is one of the reasons it's not really a good first issue).

**Pull request closed without merging**
