### PR TITLE
fix(healthcheck): update builtins to the new format

### PR DESCRIPTION
**Pull request by muniter**
Make built in healthchecks for lsp and treesitter use Lua, after https://github.com/neovim/neovim/pull/15259

### CODE REVIEW

**Comment by e-kwsm** [comment]
FWIW: a user has to remove `runtime/autoload/health/{lsp,treesitter}.vim` under the install location to avoid `:checkhealth` error:
```
treesitter: health#treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "treesitter" plugin. Exception:
    function health#check[24]..health#treesitter#check, line 2
    Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to call field 'check_health' (a nil value)
```

**Comment by clason** [comment]
That's expected: `make install` does not _remove_ files from the installation directory.

**Comment by kdrahul** [comment]
There were no `lsp.vim` or `treesitter.vim` when I cloned it fresh and built neovim 0.6 today. Yet `:checkhealth` fails and even starts without any colorschemes applied. Is there any way to fix this?

**Comment by muniter** [comment]
> There were no `lsp.vim` or `treesitter.vim` when I cloned it fresh and built neovim 0.6 today. Yet `:checkhealth` fails and even starts without any colorschemes applied. Is there any way to fix this?

It's the other way around `vim.lsp` how to fix depends on how you installed. If from source delete `$VIMRUNTIME` and then install again. 

The issue is that some files in the runtime shouldn't be there.

**Pull request merged**
