### PR TITLE
vim-patch: update diff highlights

### PR DESCRIPTION
**Pull request by clason**
- vim-patch:9.1.0016: default diff highlighting is too noisy
- vim-patch:5f4cc8ea65e8

I have opted to make the new groups the "primary" groups that are explicitly defined in the default colorscheme, as these were added to the "standard list" `:h group-name`.

@echasnovski

### CODE REVIEW

**Comment by echasnovski** [comment]
> I have opted to make the new groups the "primary" groups that are explicitly defined in the default colorscheme, as these were added to the "standard list" `:h group-name`.

Nice!

------

Would you mind moving down both definitions of `Removed` so that paragraph is in alphabetical order? This makes visually searching for group definition slightly easier.

**Comment by echasnovski** [comment]
> I can alphabetize this list, of course. I just thought this way it'd be easier to review. (I can also move them into their own block?)

Thanks! To me having them in the main block is OK, as three groups is kind of small for separate block. But don't mind having them separated with appropriate comment-title.

**Comment by clason** [comment]
Where is `Texted` tho 😠

**Comment by echasnovski** [comment]
@clason, on second thought, maybe it is better to keep `diff` highlights as foreground only? This is closer to what was originally a reference color scheme and indeed looks nicer when looking at diff.

I am thinking maybe this PR should update 'highlight_group.c' something like this:

```diff
diff --git a/src/nvim/highlight_group.c b/src/nvim/highlight_group.c
index 71c44c852..3cf72937a 100644
--- a/src/nvim/highlight_group.c
+++ b/src/nvim/highlight_group.c
@@ -227,6 +227,11 @@ static const char *highlight_init_both[] = {
   "default link DiagnosticSignOk           DiagnosticOk",
   "default link DiagnosticUnnecessary      Comment",
 
+  // Diff
+  "default link Added   DiagnosticOk",
+  "default link Changed DiagnosticInfo",
+  "default link Removed DiagnosticError",
+
   // Text
   "default link @text.literal   Comment",
   "default link @text.reference Identifier",
```

**Comment by clason** [comment]
The actual choice of colors I of course leave to you; I'd prefer/propose to still define them explicitly rather than as links -- especially since the link "changed" <-> "info" is not semantically meaningful: they may happen to have similar colors, but if you change one you may (with high likelihood even) not want to change the other.

**Comment by clason** [comment]
And my point is that

> Both diffAdded and DiagnosticOk are usually defined as "green foreground". 

this reasoning ("usually defined") being faulty is exactly what got us to this point ;) (And "neither green or red" doesn't mean anything.)

So I am quite opposed to linking them needlessly (especially since `Added` and friends are Vim core groups, while `Diagnostics` are secondary Neovim subsystems).

**Comment by echasnovski** [comment]
> So I am quite opposed to linking them needlessly (especially since `Added` and friends are Vim core groups, while `Diagnostics` are secondary Neovim subsystems).

Yeah, this one seems reasonable.

Would you mind then leaving `Diff*` as they were while making `Added`, `Changed`, and `Removed` defined explicitly in the same way as `DiagnosticOk`, `DiagnosticInfo`, and `DiagnosticError`? Preserving the alignment, if possible.

**Comment by echasnovski** [comment]
Thanks! Looks perfect.

**Pull request merged**
