### PR TITLE
fix(treesitter): Don't invalidate parser when discovering injections

### PR DESCRIPTION
**Pull request by Slotos**
When parsing with a range, languagetree looks up injections and adds them if needed. This explicitly invalidates parser, making `is_valid` report `false` both when including and excluding children.

This is an attempt to describe desired<sup>*</sup> behaviour of `is_valid` in tests, with what ended up being a single line change to satisfy them.

--------------

<sup>*</sup> "Not surprising" could be a better description.

### CODE REVIEW

**Comment by Slotos** [comment]
Would merging expectations so that `is_valid(true)` and `is_valid()` are always checked together make tests more descriptive?

**Comment by lewis6991** [comment]
>  If an edit adds a new injection, the tree is invalid until it is reparsed -- including the newly injected range.

Children are only added during `parse()`. Invalidation due to edits happens via a different code path.

**Comment by Slotos** [comment]
I've reworked tests to be more coherent and test a longer lifecycle. Removed invalidation on child removal too.

Those invalidation lines go back to initial commit that added the file. Corresponding implementation in `nvim-treesitter` never had `:invalidate` method nor invalidation routines in `add|remove_child`.

**Review by lewis6991 — APPROVED** [review]
I don't mind going with this. It's an easy revert if there's any issues.

**Comment by lewis6991** [comment]
Once we know it works and there aren't any glaring issues.

**Comment by Slotos** [comment]
Just took a shot at resolving cherry-pick for backport and I think the backport does not make sense unless changes to `parse` are also backported. Right now, it's impossible to parse a region on `release-0.9`, which makes it impossible to create the situation the tests describe.

**Pull request merged**
