### PR TITLE
fix(winbar): allow setting winbar in winhighlight

### LINKED ISSUE #19345: Winbar highlight cannot be set using winhighlight
### Neovim version (nvim -v)

NVIM v0.8.0-dev+2060-g0f1b17788 

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.4

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

1. `nvim --clean`
2. `:setlocal winbar=test`
3. `:setlocal winhighlight=Winbar:Visual`

See error `E474: Invalid argument: winhighlight=Winbar:Visual`

### Expected behavior

Winbar should adopt the highlight `Visual` in that specific window

### Actual behavior

An error is thrown instead

### PR DESCRIPTION
**Pull request by akinsho**
This PR fixes #19345 using the diff kindly provided by @zeertzjq, all credit to him for the fix 👍🏿

### CODE REVIEW

**Comment by akinsho** [comment]
Tested locally to verify that it works

**Comment by akinsho** [comment]
@zeertzjq I actually ran into an issue with the fix I think, when moving from the window where the winhighlight is set to another window with a winbar the winhighlight for *only* the winbar is reset to that of the original window. Does that make sense? (can upload a video later if not)

**Comment by zeertzjq** [comment]
A winbar in an inactive window uses `WinBarNC` instead of `WinBar` as its highlight group, and linking `WinBar` doesn't affect `WinBarNC`.

**Comment by akinsho** [comment]
Ah, ofc sorry I'd forgotten about that behaviour, that was dumb 🤦🏿‍♂️ , verified with `WinBarNC` set it works great. No issue here then 👍🏿

**Review by famiu — APPROVED** [review]

**Pull request merged**
