### PR TITLE
vim.region (or visualtext, or get_visual_selection)

### LINKED ISSUE #16843: lua function to get current visual selection
### Feature already in Vim?

no

### Feature description

wouldn't it be great if there was a lua api function that gives you the current visually selected text?

### PR DESCRIPTION
**Pull request by doubleloop**
closes #16843
related #13896

I decided to reuse existing c logic so that in all cases (block-selection, virtualmode=all, selection=inclusive/exclusive, double-width characters etc) result is consistent with what would be yanked.

Questions:

1. What namespace should be used (`vim.fn.xxx` vs `vim.xxx` vs `vim.api.nvim_xxx`)?
1. Should I make PR directly to vim, if so do I need to rewrite tests?
1. Not sure about the name, is it ok ? I was also considering `get_selected_lines`/`get_selection`, `get_visual_selection` is strange in the way that AFAIK selection can't be not visual.

### CODE REVIEW

**Comment by clason** [comment]
The namespace is not really a choice:
1. If it's exposed via vimscript (`selectedlines()`), it'll (automatically) go into `vim.fn.selectedlines()` -- and should indeed first(!) be offered to Vim.
2. If it's a C function, it should be exposed through the Neovim API (to C, RPC, vimscript, Lua, ...) via `nvim_get_selection`, which will automatically go into `vim.api.nvim_get_selection()` -- but then we really need to think about the signature as this will be under a strict contract (can't change until Neovim 2.0), see `:h api-contract`. 
3. If it's pure Lua, it'll be somewhere under `vim.xxx` -- to be discussed where.

Option 3 doesn't look to be the case, so the choice is between option 1 (submit to Vim, port, and expose through `vim.fn`) or option 2 (add it to the Neovim API and expose through `vim.api`).

**Comment by lewis6991** [comment]
Can't this simply be achieved with something like:

```lua
function get_visual()
  local _, ls, cs = unpack(vim.fn.getpos('v'))
  local _, le, ce = unpack(vim.fn.getpos('.'))
  return vim.api.nvim_buf_get_text(0, ls-1, cs-1, le-1, ce, {})
end
```

Seems preferable to adding ~300 lines of C code.

**Comment by doubleloop** [comment]
@lewis6991 what about virtualedit?

```
ab
cdefgh
ijk
lmnopqrst

    uvwxyz

äƃĉđē'

```

`set virtualedit=all selection=exclusive`

now make block selection from pos 2,2 to 9-20 (1,1-indexed), and try all corners (`o`/`O`)

**Comment by clason** [comment]
That's known to be broken.

**Comment by doubleloop** [comment]
>If it's exposed via vimscript (selectedlines()), it'll (automatically) go into vim.fn.selectedlines() -- and should indeed first(!) be offered to Vim.

https://github.com/vim/vim/pull/11579

>Seems preferable to adding ~150 lines of C code.

Note that most of the code is actually dealing with special cases of virtualedit/inclusive. Any implementation which does not handle this cases is incomplete.

**Comment by clason** [comment]
> Note that most of the code is actually dealing with special cases of virtualedit/exclusive.

Does it handle block selection with multi-byte unicode (emoji, kanji/hanzi)? If so, it would be better to turn this into a generic API to use for `vim.region` so other functions (like `highlight.on_yank`) also get these improvements for free.

**Comment by justinmk** [comment]
Thanks for referencing https://github.com/neovim/neovim/pull/13896 , but  I don't see an explanation of why this PR takes the approach of  a special-purpose function instead of the general-purpose "region" (aka "range": name TBD) interface of https://github.com/neovim/neovim/pull/13896 . Even if you only want to implement visual selection here, this could be done by documenting something like:

    Only visual selection (the '< and '> marks) is supported currently.

**Comment by doubleloop** [comment]
>  it would be better to turn this into a generic API to use for vim.region so other functions (like highlight.on_yank) also get these improvements for free

> I don't see an explanation of why this PR takes the approach of a special-purpose function instead of the general-purpose "region" (aka "range": name TBD)

hmm, to make it work so that `get_visual_selection` (name TBD) do not need to analyze line content any more, `vim.region` would need to return more values other then startcol/endcol, in particular something that allows calculating values which in vim structure is called [startspaces/endspaces](https://github.com/neovim/neovim/blob/master/src/nvim/ops.c#L80).

Not sure if it is obvious what are this values used for so just in case I will give 2 examples where they are needed: a) multiwidth characters in  blockwise-visual, b) virtualedit

Consider buffer:

```vim
set noet sw=0 ts=4 noai
set list listchars=tab:-->,space:⋅
call feedkeys("iaaaaaa\<cr>\<tab>aa\<cr>aaa\<c-v>\<c-a>a\<cr>aaaaaa\<esc>")
```

which would visually look like this
```
aaaaaa
--->aa
aaa^Aa
aaaaaa
```

a) `:call feedkeys("gg02l\<c-v>4jl")` when yanked produces `{'aa', '⋅⋅', 'a⋅', 'aa'}` (I denoted space as `⋅` , note that multiwidth characters which are partially selected are converted to spaces),
line 2: startcol=0, endcol=0 (meaning nothink from the line should be copied to the result), startspaces=2, endspaces=0
line 3: startcol=2, endcol=3, startspaces=0, endspaces=1
b) `set virtualedit=all`, `:call feedkeys("gg0j2lv10l")` when yanked produces `'⋅⋅aa⋅⋅⋅⋅⋅⋅⋅'`
startcol=1, endcol=3, startspaces=2, endspaces=7 

In both cases, information about how many spaces need to be added pre/post area taken from buffer mus be available.

If this additional values are added to `vim.region` result then `highlight.on_yank` could use `<startpos - startspaces, endpos + endspaces>` as positions to hilight (names startspaces/endspaces are from internal structure and are yank specific, in general could be changed for example to fillleft/fillright).

I will prepare PR. IMO it is better to move `vim.region` into c because:
1. it can reuse existing code (otherwise some logic needs to be duplicated), 
1. in lua I could not find easy access to [getvcol](https://github.com/neovim/neovim/blob/4b02291f81b76eda029d4eae1c1d59c1a946a032/src/nvim/charset.c#L913) and [getvvcol](https://github.com/neovim/neovim/blob/4b02291f81b76eda029d4eae1c1d59c1a946a032/src/nvim/charset.c#L1126), `vim.fn.virtcol()` is somehow limited.
1. when `vim.region` is in lua, as far as I understand (correct me if I am wrong) the contents of the line needs to be copied in memory even though what is returned are just indexes. This would be painful for example when you open very big file with single line and try to yank even short text with highlight.on_yank turned on. In c, line can be analyzed readonly.

Questions:
1. What was the idea behind using regtype result as mode, in particular `<CTRL-V>{width}` ? AFAIK register needs to store width because pos1/pos2 of what was yanked may not be available but in case of `vim.region` positions are passed so width is redundant (and not easy to calculate for function caller)?
1. Are you really sure about using (0,0) indexes as input/output positions in `vim.region`? Nvim indexing convention is strange to me given that a) all vim functions return 1,1 indexes, b) lua lists are 1- indexed, c) marks are 1,0 indexed.. some things are end inclusive and some end exclusive.. What is the pattern/guideline ?

**Comment by justinmk** [comment]
> If so, IMO it is better to move `vim.region` into c because:
> 
> 1. it can reuse existing code of op_yank (otherwise some logic needs to be duplicated),
> 2. in lua I could not find easy access to [getvcol](https://github.com/neovim/neovim/blob/4b02291f81b76eda029d4eae1c1d59c1a946a032/src/nvim/charset.c#L913) and [getvvcol](https://github.com/neovim/neovim/blob/4b02291f81b76eda029d4eae1c1d59c1a946a032/src/nvim/charset.c#L1126), `vim.fn.virtcol()` is somehow limited.
> 3. ... In c, line can be analyzed readonly.

I think we are open to the idea of implementing `vim.region` in C. 

> 1. What was the idea behind using regtype result as mode, in particular `<CTRL-V>{width}`

Just based on precedent from existing vim functions.

> Nvim indexing convention is strange

Indexing quirks are inherited from Vim, see `:help api-indexing`.

**Comment by doubleloop** [comment]
Ok, but we should determine what `vim.region` should return. My proposition:

table with elements of the form:
```
{
  lnum=lnum,
  colstart = {col, off, width/colnext},
  colend = {col, off},
}
```
* `col`, `off` are values like in `getpos` (note: in case of blockwise-visual `off` can be positive even without virtualedit)
* `width` / `colnext` need to be known to determine where next character starts (in case colstart is within multiwidht character)
* lnum: IMO indexing the whole table with linenumbers (which are 0-indexed) is potential confusion (it might not be common to see table with 0 index in lua), also I do not know about all future plans but I can imagine situation when range result could in the future return multiple entries for single line (wrapped blockwise-visual ? :P).

> Indexing quirks are inherited from Vim, see :help api-indexing.

I am aware of this part but what do you mean by API? I thought api functions are placed in vim.api.nvim_xxx,   so is `vim.region` considered API function? Why is it in `vim.region` and not `vim.api.nvim_region` ?

**Comment by clason** [comment]
> I am aware of this part but what do you mean by API? I thought api functions are placed in vim.api.nvim_xxx, so is vim.region considered API function? Why is it in vim.region and not vim.api.nvim_region ?

"API functions" specifically are the functions in the Neovim API (`:h api`) that are mostly implemented in C and exposed to Vimscript, Lua (under `vim.api`), and RPC plugins (not all for all consumers, though). These are covered by a strong contract (`:h api-contract`). Anything else under `vim` is implemented in Lua and can change more easily.

**Comment by justinmk** [comment]
@doubleloop 

> lnum: IMO indexing the whole table with linenumbers (which are 0-indexed) is potential confusion (it might not be common to see table with 0 index in lua),

It is, but it works fine with `pairs()`, and we can just show an example in the `vim.region` docs, so let's not make that breaking change.

> also I can imagine situation when range result could in the future return multiple entries for single line (wrapped blockwise-visual ? multiple cursor ? :P).

Yes. Is it possible to augment the result of `vim.region` without breaking changes? If not, perhaps a keyword-args form `vim.region` could be introduced which returns the nested dict shape that you suggested.

**Pull request closed without merging**
