### PR TITLE
[RFC] screen.c: remove references to encoding

### PR DESCRIPTION
**Pull request by romgrk**
- Remove references to `enc_utf8`, `enc_dbcs` & `has_mbyte`

### CODE REVIEW

**Comment by bfredl** [comment]
there are still some references to `enc_dbcs`. If you get rid of all, you should be able to completely remove `ScreenLines2`

**Comment by bfredl** [comment]
There is still a bit of `has_mbyte` and `enc_utf8` as well. Is there a logic to what is removed and not or it is simply WIP?

**Comment by romgrk** [comment]
Yep, I had missed some `has_mbyte`, can't see any `enc_utf8` though. This is RFC.

**Comment by bfredl** [comment]
Looks good now. @justinmk should we ignore linter failures in the huge reindented blocks for now? Not that we shouldn't fix them, just that doing so would be better in the main PR #6567   where they makesure wouldn't be missed due to reindention?

**Comment by teto** [comment]
Looking forward to this kind of small cleanups in screen.c. I would vote for having the linting correct on the first pass as it is straightforward and we don't know when #6567 can/will be merged.

**Comment by bfredl** [comment]
@teto It could be done in multiple passes, there is no reason to do it "one small pass" (this PR) and then "one huge pass" for the rest.

**Comment by zhou13** [comment]
What is the status of this cleanup?

**Comment by bfredl** [comment]
@zhou13 pieces of this has been done in other PRs, mainly #8218 and #7992. A rebase would be needed to extract the remaining changes + maybe some linter fixes.

**Comment by justinmk** [comment]
Merged in #9657.

**Pull request closed without merging**
