### PR TITLE
screen.c: Allow showbreak highlighting to override cursorline.

### LINKED ISSUE #13369: Cursorline background shouldn't override showbreak's.
- `nvim --version`: [`NVIM v0.5.0-869-g71d4f5851`](https://github.com/neovim/neovim/files/5591827/nvim-version.txt)
- `vim -u DEFAULTS`: Vim 8.2 does behave the same, but I noticed some divergence between Neovim and Vim in this respect (as per #4744).
- Operating system/version: Arch Linux
- Terminal name/version: `alacritty 0.7.0-dev`
- `$TERM`: `alacritty`

### Steps to reproduce using `nvim -u NORC`

```
set cursorline showbreak=### listchars+=eol:$ list
hi NonText ctermbg=cyan
hi CursorLine ctermbg=magenta
```

Now insert a long line that wraps the screen. You'll notice that cursorline overrides the background color for showbreak's characters, while the EOL character overrides cursorline's background.

### Expected behaviour

Both showbreak and EOL characters use the NonText group, so I would expect a consistent behavior. In this case, I would expect showbreak's background to override cursorline's; otherwise, depending on theming, showbreak's characters can be confused for normal text.

### PR DESCRIPTION
**Pull request by shade-of-noon**
I also added relevant tests.

Close #13369

### CODE REVIEW

**Comment by shade-of-noon** [comment]
I observed that `make lint` gave me an error (about `screen.c`). I am not sure how to proceed, does this error mean that `screen.c` cannot be modified and that I need to send the patch to Vim first?

**Comment by shade-of-noon** [comment]
Squashed the commits plus one little extra test.

**Comment by bfredl** [comment]
Makes sense to me.

**Comment by teto** [comment]
Makes sense to me too: merging.

**Pull request merged**
