### PR TITLE
[RFC] vim-patch:7.4.2123

### PR DESCRIPTION
**Pull request by lonerover**
Problem:    No new style test for diff mode.
Solution:   Add a test.  Check that folds are in sync.

https://github.com/vim/vim/commit/42093c0ec52e6ff29e80aae65ac6a744c7de79bb

### CODE REVIEW

**Comment by mhinz** [comment]
LGTM, but I'm not sure about the tests.

@justinmk @jamessan Are the Vim's new-style tests supposed to be ported to Lua?

**Comment by jamessan** [comment]
> Are the Vim new-style tests supposed to be ported to Lua?

[Nope](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim#code-differences).

**Review by mhinz — APPROVED** [review]

**Comment by Shougo** [comment]
Related patches: 7.4.2124, 7.2.2126

**Comment by jamessan** [comment]
Covered in #5815.

**Comment by Shougo** [comment]
Oh, OK.

**Pull request merged**
