### PR TITLE
[RDY] runtime: Updated Dockerfile syntax with latest from Vim upstream

### PR DESCRIPTION
**Pull request by jarimayenburg**
Fixes issues with Dockerfile syntax highlighting by taking the latest upstream Vim syntax file

Before:
image

After:
image

### CODE REVIEW

**Comment by janlazo** [comment]
URL to the Vim commit hash is missing in your commit.

**Comment by jarimayenburg** [comment]
I've added the URL to the Vim commit

**Comment by janlazo** [comment]
```
> ./scripts/vim-patch.sh -L -- 'runtime/*dockerfile*'
560979ed4f0216f902a2c247e937f00a27dcb198
ebdf3c964a901fc00c9009689f7cfda478342c51
```

You squashed the changes in both commits. Each ported commit should match 1-1 with the original Vim commit as much as possible.

**Comment by jarimayenburg** [comment]
Should this be solved by applying a vim-patch for these two commits? I started working on that patch, but that introduces all kinds of other changes that depend on changes we don't have.

I also tried to apply just the changes in this file of those commits, but that creates issues if we're ever going to apply these two vim-patches.

Is there a way to do a "partial" vim-patch? Or can we only introduce these changes when the other changes introduced in these commits can also be applied?

**Comment by janlazo** [comment]
Each vim-patch commit must merge all applicable changes from a single Vim commit hash. A vim-patch commit can consist of multiple Vim commits but it must be documented in the commit. If a Vim commit is difficult to merge as a whole, it can be split into smaller commits but the `vim-patch:` token must be omitted in the commit message.

For your case, it will be something like this:

```sh
git checkout master
git pull --rebase neovim master
git clone https://github.com/vim/vim .vim-src # or run ./scripts/vim-patch.sh -l > /dev/null

# for each commit
  cd .vim-src
  git checkout <vim commit>
  cp runtime/syntax/dockerfile.vim ../runtime/syntax/dockerfile.vim
  git checkout master
  cd ..
  git commit
  # runtime/dockerfile.vim: <vim commit>
  #
  # Port dockerfile.vim files only.
  # https://github.com/vim/vim/commit/<vim commit>
```

**Comment by jarimayenburg** [comment]
Thanks so much for your explanation! Should be good to go now.

**Review by janlazo — APPROVED** [review]

**Pull request merged**
