### PR TITLE
ci: add more reviewers based on label

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by dundargoc** [comment]
@clason if you want to add an autocmd label I can add DJ TJ as well.

**Comment by dundargoc** [comment]
With this change treesitter label will have 4 reviewers. It's a lot, but the more the merrier IMO (provided they're semi-active of course)

**Comment by clason** [comment]
the label is `event`, but I'd give TJ some space.

(I manually assign him on stuff related to his PRs, mostly for book keeping.)

**Comment by dundargoc** [comment]
People can add themselves as a reviewer for a label, I shouldn't impose a label on them.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
not part of the Neovim repo, just the node-js client.

**Comment by clason** [comment]
Hey, looks like you can request teams as reviewers now!

**Comment by dundargoc** [comment]
Automatic team reviewers is possible, but the permissions required are too invasive the way they are currently. Let's go with individual reviewers for the time being.

**Pull request merged**
