### PR TITLE
cmake: Check if the compiler understands -Wno-array-bounds

### LINKED ISSUE #7297: Building on OpenBSD 6.1 fails: unrecognized command line option "-Wno-array-bounds"
I followed the [build instructions for OpenBSD](https://github.com/neovim/neovim/wiki/Building-Neovim):

```
doas pkg_add gmake cmake libtool unzip autoconf-2.69p2 automake-1.15p0
export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.15

mkdir .deps
cd .deps
cmake ../third-party/
gmake
cd ..
mkdir build
cd build
cmake ..
gmake
```
On the last step I get this error:
```
[  0%] Building C object src/nvim/CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o
cc1: error: unrecognized command line option "-Wno-array-bounds"
gmake[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:1187: src/nvim/CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:4441: src/nvim/CMakeFiles/nvim.dir/all] Error 2
gmake: *** [Makefile:150: all] Error 2
```
I have GNU make 4.2.1 and cmake 3.7.2.. Short research revealed `-Wno-array-bounds` was introduced with gcc 4.6. I have no idea how to install the newer version. Upgrading the systems default compiler is said to be a bad idea as it may be used during a system update (but that's mere 3rd party "knowledge" on my side).

### PR DESCRIPTION
**Pull request by jamessan**
Closes #7297

### CODE REVIEW

**Comment by jamessan** [comment]
@niko Does this help?

**Comment by niko** [comment]
Yes, it does. Now hitting the next error:

```
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/regexp.c.o
/home/niko/build/neovim/src/nvim/regexp.c: In function 'regmatch':
/home/niko/build/neovim/build/src/nvim/auto/regexp.c.generated.h:77: sorry, unimplemented: inlining failed in call to 'cstrchr': function body not available
/home/niko/build/neovim/src/nvim/regexp.c:4193: sorry, unimplemented: called from here
gmake[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3371: src/nvim/CMakeFiles/nvim.dir/regexp.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:4441: src/nvim/CMakeFiles/nvim.dir/all] Error 2
gmake: *** [Makefile:150: all] Error 2
```
Should I open another issue or add it to #7297?

**Review by justinmk — APPROVED** [review]

**Comment by jamessan** [comment]
> Should I open another issue or add it to #7297?

We can just keep working through it here.  I'll update the PR later today.

**Comment by jamessan** [comment]
@niko How about now? :)

**Comment by niko** [comment]
Works like a charm! Thanks a lot!

**Pull request merged**
