### PR TITLE
tests: executable_spec: enable pending test

### PR DESCRIPTION
**Pull request by blueyed**
Should hopefully work now after efc6d9951b.

### CODE REVIEW

**Comment by blueyed** [comment]
Unfortunately it is not fixed:
https://ci.appveyor.com/project/neovim/neovim/builds/25809968/job/y1c84v4uuu3y6d87#L6961 (MSVC_32)
```
[  FAILED  ] 1 test, listed below:
  [  FAILED  ] C:/projects/neovim/test/functional\eval\executable_spec.lua @ 18: executable() sibling to nvim binary
  C:/projects/neovim/test/functional\eval\executable_spec.lua:27: Expected objects to be the same.
  Passed in:
  (number) 0
  Expected:
  (number) 1
  
  stack traceback:
  	C:/projects/neovim/test/functional\eval\executable_spec.lua:27: in function <C:/projects/neovim/test/functional\eval\executable_spec.lua:18>
```

**Comment by blueyed** [comment]
@janlazo @erw7 
Do you think we can fix this, or should we revert it (to become pending again if it fails)?

**Comment by janlazo** [comment]
Leave it pending. My guess is that it's encoding issue with utf8<->utf16 conversion or codepage (chcp?).

**Comment by blueyed** [comment]
@janlazo 
Ok.
Have you tried running it a few times to see if it's flaky by itself?
Otherwise I could imagine it also being flaky based on some previous state, e.g. maybe even existing files in some (temporary) directory.

**Pull request merged**
