### PR TITLE
feat(treesitter): Support match queries on multiline nodes

### LINKED ISSUE #15833: Treesitter: `#match?` predicate and multiline nodes
### Feature already in Vim?

_No response_

### Feature description

Just realized that the match predicate always returns false for multiline nodes

https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/runtime/lua/vim/treesitter/query.lua#L243-L245

I don't know if there was some discussion about how to support those, but maybe we could at least just try matching the first line? (from start_col till the end of the first line).

Also, looks like vim does support multiline strings in a pattern (`:h string-match`), so maybe we could just extract the text from the node and pass it to vim's match().

### PR DESCRIPTION
**Pull request by lewis6991**
This allows language injection to work with:

```lua
vim.cmd[[
 autocmd ...
]]
```

Resolves: #15833

Related: nvim-treesitter/nvim-treesitter/pull/1922

### CODE REVIEW

**Comment by lewis6991** [comment]
@vigoux

**Comment by stsewd** [comment]
For the multiline support on get_node_text, see https://github.com/neovim/neovim/pull/14999/.

**Comment by vigoux** [comment]
Hey it would be good to get the multi-line get_node_text first.
I'll take time to review this asap.

**Comment by kevinhwang91** [comment]
Work for me, but look like this PR can't be merged in 0.6.0

**Comment by vigoux** [comment]
Hi I think that this is pretty much superseded by #14999, apart from the changes to `vim-match?`, do you mind rebasing on the aforementioned PR so that we get the change history right ?

Thanks again !

**Comment by lewis6991** [comment]
> Hi I think that this is pretty much superseded by #14999, apart from the changes to `vim-match?`, do you mind rebasing on the aforementioned PR so that we get the change history right ?
> 
> Thanks again !

Done.

Note, there were some slight differences in the implementation for `get_node_text`. In the rebase I've gone with mine since I think it is a little more efficient.

**Review by vigoux — APPROVED** [review]

**Pull request merged**
