### PR TITLE
[RFC] vim-patch:8.0.0451,8.0.0452,8.0.0454

### PR DESCRIPTION
**Pull request by ckelsel**
#### vim-patch:8.0.0451: some macros are in lower case

Problem:    Some macros are in lower case.
Solution:   Make a few more macros upper case. Avoid lower case macros use an
            argument twice.
https://github.com/vim/vim/commit/91acfffc1e6c0d8c2abfb186a0e79a5bf19c3f3f

#### vim-patch:8.0.0452: some macros are in lower case

Problem:    Some macros are in lower case.
Solution:   Make a few more macros upper case.
https://github.com/vim/vim/commit/1c46544412382db8b3203d6c78e550df885540bd

#### vim-patch:8.0.0454: compiler warnings for "always true" comparison
 
Problem:    Compiler warnings for comparing unsigned char with 256 always being true. (Manuel Ortega) 
Solution:   Add type cast. 
https://github.com/vim/vim/commit/977d03733601948ab334fec24d0da82bc18c57c3

### CODE REVIEW

**Comment by ckelsel** [comment]
commit 93bf201119f68b0723ee3f240afa48134cc41399                                 
Author: Felipe Oliveira Carvalho <felipekde@gmail.com>
Date:   Wed Apr 22 19:12:26 2015 -0300

    Replace vim_iswhite with ascii_iswhite() defined in ascii.h

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/6297

**Comment by justinmk** [comment]
```
FAILED: /usr/local/clang-5.0.0/bin/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -Iconfig -I../src -isystem /home/travis/nvim-deps/usr/include -Isrc/nvim/auto -Iinclude -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Werror -DEXITFREE -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -fsanitize=undefined -fsanitize-blacklist=/home/travis/build/neovim/neovim/src/.asan-blacklist -MD -MT src/nvim/CMakeFiles/nvim.dir/charset.c.o -MF src/nvim/CMakeFiles/nvim.dir/charset.c.o.d -o src/nvim/CMakeFiles/nvim.dir/charset.c.o   -c ../src/nvim/charset.c
../src/nvim/charset.c:961:11: error: comparison of constant 256 with expression of type 'char_u' (aka 'unsigned char') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
      && !VIM_ISBREAK(s[1])
          ^~~~~~~~~~~~~~~~~
../src/nvim/macros.h:87:29: note: expanded from macro 'VIM_ISBREAK'
#define VIM_ISBREAK(c) ((c) < 256 && breakat_flags[(char_u)(c)])
                        ~~~ ^ ~~~
../src/nvim/charset.c:985:51: error: comparison of constant 256 with expression of type 'char_u' (aka 'unsigned char') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
            && (VIM_ISBREAK(c) || col2 == col || !VIM_ISBREAK(*ps)))) {
                                                  ^~~~~~~~~~~~~~~~
../src/nvim/macros.h:87:29: note: expanded from macro 'VIM_ISBREAK'
#define VIM_ISBREAK(c) ((c) < 256 && breakat_flags[(char_u)(c)])
                        ~~~ ^ ~~~
2 errors generated.

```

**Comment by justinmk** [comment]
The build is still failing. I don't feel confident about these changes. Let's mark the macro-case changes as NA for now, and leave that work to be done incrementally for #6297. 

So only 8.0.0454 is needed, the others are NA.

**Pull request closed without merging**
