### PR TITLE
refactor(diagnostic)!: use existing naming conventions

### PR DESCRIPTION
**Pull request by gpanders**
Prefer naming conventions established by Vim in the "qflist" family of functions:

  1. Use "note" rather than "hint"
  2. Use "text" rather than "message"

Both "hint" and "message" are holdovers from LSP diagnostics, but the `vim.diagnostic` subsystem is broader than LSP and is meant to be used as a general purpose diagnostic API, so establishing consistency with legacy error handling functionality makes sense.

**This is a breaking change.**

### CODE REVIEW

**Review by justinmk — COMMENTED** [review]
"Hint" feels more intuitive and less ambiguous so I wouldn't mind leaving it as-is. What precedent are we referencing for "Note"?

"Text" seems like a clear win though.

**Review by justinmk — APPROVED** [review]
No objection, but let's hear from others. 

Since the "Note" precedent is fairly minor, we might be able to get away with mentioning "hint" in `:help quickfix` wherever "note" is mentioned, if we want to double-down on "Hint" for its intuitiveness.

```
n - note/hint message
...
%N		start of a multi-line note/hint message
```

**Comment by mjlbach** [comment]
I personally prefer "Hint" over note and "message" to "text", but I only feel strongly about the former.

**Comment by gpanders** [comment]
No consensus for a change and release day is upon us.

**Pull request closed without merging**
