### PR TITLE
feat(signs): align signs by priority

### LINKED ISSUE #10106: signcolumn: auto: re-use same column for same type
With e.g. `:set signcolumn=auto:2` and two different plugins displaying signs, it would be nice if signs were trying to be kept in the same columns.

E.g.

```
AABB line1
AA   line2
  BB line3
AA   line4
  BB line5
```

Currently it would look like this:
```
AABB line1
AA   line2
BB   line3
AA   line4
BB   line5
```

This makes it harder to read with e.g. using [vim-gitgutter](https://github.com/airblade/vim-gitgutter) and [coveragepy.vim](https://github.com/alfredodeza/coveragepy.vim).

There have been patches in Vim already for "group"ing of signs, which could be used here, but often plugins will either re-use the same ID, or at least the same text/hl (although those might be several).

### PR DESCRIPTION
**Pull request by lewis6991**
When scanning signs to calculate the sign column width, also store the column which each priority should be drawn at.

Currently works for this code:

```lua
vim.o.signcolumn = 'auto:3'

vim.api.nvim_buf_set_lines(0, 0, -1, false, {'', '', ''})

vim.cmd('sign define SignA text=A')
vim.cmd('sign define SignB text=B')
vim.cmd('sign define SignC text=C')

vim.fn.sign_place(0, '', 'SignA', 1, {lnum = 1, priority=300})
vim.fn.sign_place(0, '', 'SignB', 1, {lnum = 1, priority=200})
vim.fn.sign_place(0, '', 'SignC', 1, {lnum = 1, priority=100})

vim.fn.sign_place(0, '', 'SignB', 1, {lnum = 2, priority=200})
vim.fn.sign_place(0, '', 'SignC', 1, {lnum = 2, priority=100})

vim.fn.sign_place(0, '', 'SignC', 1, {lnum = 3, priority=100})
```

### TODO:

- [x] Make it work for extmark signs.
- [ ] Recalculate `col_pris` when adding/deleting signs that don't invalidate the sign column.

### CODE REVIEW

**Comment by lewis6991** [comment]
This actually works surprisingly well:

image

**Comment by clason** [comment]
Seems to work well! 🚀

**Comment by clason** [comment]
What's the status here? Do we want to track this for 0.8, or give this more time to bake on master?

**Comment by lewis6991** [comment]
The algorithm here is probably good for 95% of use cases, however it starts to behave non-ideally for 10th+ priority signs.

I've got an idea for a different algorithm that should handle 99% of use cases but needs more work and thought.

So it depends how happy we are with what's here. If it's up to me then I'd prefer to defer this to 0.9.

**Comment by clason** [comment]
If we expect this to be changed again later, better to wait for the 0.9 cycle. We can get this in early and collect feedback, then -- if necessary -- replace this with the final implementation for 0.9 release.

**Comment by danrot** [comment]
Is there any chance we can get this soon? I would say that if 95% of the use cases work it is already much better than what we have now, although I don't know too many details 🙈

**Pull request closed without merging**
