### PR TITLE
build: remove luarocks

### PR DESCRIPTION
**Pull request by dundargoc**
Luarocks is no longer needed after
25e51d393a420765d5efd44c1b4be823a5cf280a.

### CODE REVIEW

**Comment by bfredl** [comment]
related: https://github.com/neovim/neovim/pull/25071

**Comment by justinmk** [comment]
Do we have an issue/discussion somewhere with background on this or is it as simple as "Luarocks is an extra, somewhat complex dependency"? I'm looking for references for https://github.com/neovim/packspec/issues/41 and related.

**Comment by dundargoc** [comment]
The background is that the code wasn't being used, and that dead code is a code smell.

If you mean the commits previous to this that are relevant, then it'd be 25e51d393a420765d5efd44c1b4be823a5cf280a and f30844008bdd313b03a19486159f571a067e68b9 that details the benefits.

**Comment by bfredl** [comment]
luarocks is very slow, its servers unreliable, and its caching mechanism is straight up broken.

**Pull request merged**
