### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by janlazo** [comment]
vim-patch:8.2.1107: 'imactivatefunc' and 'imstatusfunc' are not used in the GUI

**Comment by janlazo** [comment]
Merged too early :sweat_smile: . Need to merge a vim-patch:8.0.x patch to create another version.c PR.

**Comment by teto** [comment]
Never too early if that motivates you to send one more patch (sry). let me know when https://github.com/neovim/neovim/pull/12538 is ready

**Comment by janlazo** [comment]
It's been ready for some time. I update it only to rebase or port the latest non-breaking 8.2.x patches.

**Pull request merged**
