### PR TITLE
test: force LC_ALL =en_US.UTF-8

### PR DESCRIPTION
**Pull request by justinmk**
cc @jamessan @ZyX-I @Shougo who IIRC have ran into this issue before.

### CODE REVIEW

**Comment by ZyX-I** [comment]
Why not `$LANG`? And I do not set `C` locale for huge sets of tests and would advise against doing so: C locale by definition only supports “portable character set and control character set”: basically, ASCII only. Anything else should not be expected to be working. So it would be completely logical for the TUI to transform all non-ASCII characters to `?` for displaying while in C locale.

I use `LANG=en_US.UTF-8` when I run into issues with non-English messages.

**Comment by jamessan** [comment]
> I use LANG=en_US.UTF-8 when I run into issues with non-English messages.

The only potential issue with that is it isn't guaranteed to be available.  C is always available as is, at least in recent glibc-based environments, C.UTF-8.  If we're going to require en_US.UTF-8, it should be documented and clearly fail when that expectation isn't met.

**Comment by ZyX-I** [comment]
Did not know that `C.UTF-8` exists. It does not work for me though:

```
% LANG=en_US.UTF-8 python -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
% LANG=C.UTF-8 python -c 'import locale; print(locale.getpreferredencoding())'
ANSI_X3.4-1968
```

Thought I need to specify this in `/etc/locale.gen`, but it does not work, `locale-gen` fails with “cannot open locale definition file `C': No such file or directory” for `C.UTF-8 UTF-8` line in `/etc/locale.gen`. I only have there `en_US.UTF-8`, `ru_RU.UTF-8` and some “interesting” locales I need for testing (six total currently).

**Comment by justinmk** [comment]
In `get_mess_lang()`  LC_ALL and LC_MESSAGES take precedence, so I guess they should also be set, else they could again break the tests.

>  If we're going to require en_US.UTF-8, it should be documented and clearly fail when that expectation isn't met.

We only require it for running tests. Worst than can happen is what already happens on master, right?

**Comment by jamessan** [comment]
Hmm, ok, I thought `C.UTF-8` had been merged upstream, but [I guess not](https://bugzilla.redhat.com/show_bug.cgi?id=902094).

**Comment by jamessan** [comment]
> Worst than can happen is what already happens on master, right?

Which is hard to diagnose and frustrates potential contributors.

**Comment by justinmk** [comment]
the purpose of this PR is to reduce frustration :) I don't know how to go about checking whether a locale is valid, sounds like a diversion I want to avoid for now.

**Comment by bfredl** [comment]
Except for messages, does the tests depend on locale? IIRC mbyte will default to built-in defaults for collating etc instead of locale dependent libc implementation. (I recall tr_TR test, but those are properly conditioned). If only for messages, can't we set messages language directly without relying on glibc locales being present?

**Comment by justinmk** [comment]
> can't we set messages language directly without relying on glibc locales being present?

Sure, like this?

    :lang messages en_US.UTF-8

**Comment by ZyX-I** [comment]
@bfredl `ex_language` uses `setlocale()`. So no.

**Comment by justinmk** [comment]
Hope this helps most people. If anyone has a better way please do send a PR. `:lang messages ...` didn't seem to work when I tried it locally, needs more investigation later ...

**Comment by bfredl** [comment]
@ZyX-I does it so incidentally, or does gettext for language X fundamentally depend on locale X being present?

**Comment by bfredl** [comment]
Surely `:lang messages c` or something like that works to turn off translation without depending on `/etc/locale` ?

**Comment by ZyX-I** [comment]
@bfredl Based on the docs it either uses locale, or `$LANGUAGE` which should be set to a colon-separated list of locale names. Don’t know whether the latter needs actual locales, but docs state it is a GNU extension.

According to docs `C` locale forces gettext to return `msgid` (i.e. `gettext()` argument).

**Pull request merged**
