### PR TITLE
feat(api): evaluate statusline string

### LINKED ISSUE #15849: API function to expand statusline string
### Feature already in Vim?

No

### Feature description

Currently, I'm working on automatic component truncation for my statusline plugin ([`feline.nvim`](https://github.com/famiu/feline.nvim)). But in order to do that I need a way to accurately determine which characters of the statusline strings are going to actually be displayed on the statusline, so I can find the length of the statusline to see if it fits within the window. I'd like if there was an equivalent of `expand()` for Vim statusline strings. One that'd parse the statusline string and return just a normal string containing only the characters that'd be displayed, with all statusline modifiers and such removed. My plugin could then use it to get the length of the statusline and do things like removing statusline components.

Alternatively, there could also be also be a function to check if statusline is being truncated by Neovim, in which case the plugin could detect that and start truncating components when needed.

I know this is probably not going to be very high on the priority list, but I decided to make this Issue anyway. I don't think it'd be that hard to implement since Neovim already parses the statusline while displaying it. I could try to make it myself but sadly I'm not familiar with Neovim's codebase.

### PR DESCRIPTION
**Pull request by famiu**
Previously, there was no way to evaluate a statusline string through the Neovim API. This adds an API function `nvim_eval_statusline` to allow evaluating a statusline string and getting information regarding it.

Closes https://github.com/neovim/neovim/issues/15849

### CODE REVIEW

**Comment by shadmansaleh** [comment]
> it should be more performant to just return the return value of build_stl_str_hl instead of having to calculate it all over again. Though I suppose whether that's worth it is arguable.

That performance improvement is miniscule it won't be noticeable in anyway . Adding a new api function just for that doesn't seem justifiable to me. I feel like api should handle generic use cases instead of specific ones.

Also I don't exactly remember but doesn't String structs store it's length upon creation . 

Also does this need to be exposed over rpc . I'm saying because this can be lua only too like `vim.diff` . Though maintainers will be able to tell you better on this.

**Comment by shadmansaleh** [comment]
I have an idea . How about instead of `nvim_expand_statusline_str(fmt, winid)` we have it as `nvim_expand_statusline_str(fmt, opts)`  .  where opts is like {win = winid} if win isn't provided it runs on curwin . with opts this can later be expended without breaking . We could have sommething like eval_hl = true in opts on which hl_rect will also be handled .

Return value can be a dict that contains evaluated string + processed hl_rect when applicable ( how nvim_get_hl_by_name/id returns dictonaries ) . The cpointers in hl_rect makes no sence out of c . I feel like returning something like a list of { name = hl_name, start = start_pos, end = end_pos } makes more sence ( where hl_name is string of highlight name, start_pos is int start position of hl on evaluated string, similarly end_pos is int end position of hl on evaluated string. But that will require hl_rect to be processed hence it should optin to keep the eval part morew performent .

**Comment by clason** [comment]
Yes. API functions should be future-proofed by taking dicts with optional arguments as far as possible.

**Review by gpanders — CHANGES_REQUESTED** [review]

**Review by gpanders — CHANGES_REQUESTED** [review]

**Comment by gpanders** [comment]
I'm getting a SIGTRAP with the following:

```vim
:set stl=%1*%f
:echo nvim_eval_statusline(&stl, {'highlights': 1})
```

Backtrace:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x18188d360)
    frame #0: 0x000000018188d360 libsystem_c.dylib`__chk_fail_overflow + 24
    frame #1: 0x000000018188d690 libsystem_c.dylib`__snprintf_chk + 60
  * frame #2: 0x0000000100037528 nvim`nvim_eval_statusline(str=<unavailable>, opts=<unavailable>, err=<unavailable>) at vim.c:3013:9 [opt]
    frame #3: 0x0000000100026740 nvim`handle_nvim_eval_statusline(channel_id=9223372036854775808, args=<unavailable>, error=0x000000016fdf7410) at dispatch_wrappers.generated.h:6370:19 [opt]
    frame #4: 0x000000010008e754 nvim`api_wrapper(argvars=<unavailable>, rettv=0x000000016fdf7d70, fptr=(nvim`handle_nvim_eval_statusline at dispatch_wrappers.generated.h:6335)) at funcs.c:276:19 [opt]
    frame #5: 0x000000010008b798 nvim`call_internal_func(fname="nvim_eval_statusline", argcount=2, argvars=0x000000016fdf7730, rettv=0x000000016fdf7d70) at funcs.c:196:3 [opt]
    frame #6: 0x00000001000a7bdc nvim`call_func(funcname=<unavailable>, len=20, rettv=<unavailable>, argcount_in=<unavailable>, argvars_in=<unavailable>, funcexe=0x000000016fdf78f0) at userfunc.c:1592:15 [opt]
    frame #7: 0x00000001000a75b0 nvim`get_func_tv(name="nvim_eval_statusline", len=20, rettv=0x000000016fdf7d70, arg=0x000000016fdf7d80, funcexe=0x000000016fdf78f0) at userfunc.c:459:11 [opt]
    frame #8: 0x00000001000832c8 nvim`eval_func(arg=0x000000016fdf7d80, name=<unavailable>, name_len=<unavailable>, rettv=0x000000016fdf7d70, evaluate=<unavailable>, basetv=0x0000000000000000) at eval.c:3304:13 [opt]
    frame #9: 0x0000000100082528 nvim`eval7(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1, want_string=0) at eval.c:4232:15 [opt]
    frame #10: 0x0000000100081f54 nvim`eval6(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1, want_string=<unavailable>) at eval.c:3903:7 [opt]
    frame #11: 0x0000000100081b88 nvim`eval5(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1) at eval.c:3728:7 [opt]
    frame #12: 0x000000010008191c nvim`eval4(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1) at eval.c:3622:7 [opt]
    frame #13: 0x00000001000817b4 nvim`eval3(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1) at eval.c:3541:7 [opt]
    frame #14: 0x0000000100071228 nvim`eval1 [inlined] eval2(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1) at eval.c:3470:7 [opt]
    frame #15: 0x0000000100071220 nvim`eval1(arg=0x000000016fdf7d80, rettv=0x000000016fdf7d70, evaluate=1) at eval.c:3394:7 [opt]
    frame #16: 0x000000010007e208 nvim`ex_echo(eap=0x000000016fdf7f30) at eval.c:9807:11 [opt]
    frame #17: 0x00000001000c3660 nvim`do_cmdline [inlined] do_one_cmd(cmdlinep=0x000000016fdf7f28, flags=0, cstack=0x000000016fdf8008, fgetline=(nvim`getexline at ex_getln.c:2576), cookie=0x0000000000000000) at ex_docmd.c:1983:5 [opt]
    frame #18: 0x00000001000c2420 nvim`do_cmdline(cmdline=<unavailable>, fgetline=(nvim`getexline at ex_getln.c:2576), cookie=<unavailable>, flags=0) at ex_docmd.c:604:20 [opt]
    frame #19: 0x0000000100161c48 nvim`nv_colon(cap=0x000000016fdf87d8) at normal.c:4817:18 [opt]
    frame #20: 0x000000010015f398 nvim`normal_execute(state=0x000000016fdf8748, key=<unavailable>) at normal.c:1164:3 [opt]
    frame #21: 0x0000000100213bdc nvim`state_enter(s=0x000000016fdf8748) at state.c:68:26 [opt]
    frame #22: 0x0000000100158bb4 nvim`normal_enter(cmdwin=<unavailable>, noexmode=<unavailable>) at normal.c:469:3 [opt]
    frame #23: 0x0000000100123950 nvim`main(argc=<unavailable>, argv=<unavailable>) at main.c:547:3 [opt]
    frame #24: 0x0000000181964420 libdyld.dylib`start + 4
(lldb)
```

Coming from this line:

```c
snprintf(grpname, sizeof(grpname), "User%d", sp->userhl);
```

**Review by gpanders — COMMENTED** [review]
Since it's only six bytes let's just allocate it on the stack (ends up being fewer lines too when you account for the `xfree`).

**Review by gpanders — CHANGES_REQUESTED** [review]
Code looks good to me. Just had the one question about the highlighting and some nit-picking on the docs.

**Review by gpanders — APPROVED** [review]
LGTM! Nice work

I made a couple of (very) minor changes, so be sure to pull before you squash your commits.

**Comment by famiu** [comment]
> LGTM! Nice work
> 
> I made a couple of (very) minor changes, so be sure to pull before you squash your commits.

I also had to make a minor change to the code, though I don't think it really changes much. I'll squash the commits now

**Review by gpanders — APPROVED** [review]

**Comment by famiu** [comment]
This should be ready for merge now

**Review by justinmk — APPROVED** [review]
This looks well-wrought, thank you! And thanks to the reviewers. 

Would you be willing to take over (or start over) https://github.com/neovim/neovim/pull/6607 ? I think UIs would be interested in structured 'statusline' and 'tabline' as UI events.

**Pull request merged**
