### PR TITLE
refactor(highlight): add explicit casting to avoid compiling warning

### PR DESCRIPTION
**Pull request by tanchihpin0517**
This message occurs while compiling:
```
../src/nvim/highlight.c: In function ‘hl_combine_attr’:
../src/nvim/highlight.c:458:27: warning: conversion from ‘int’ to ‘int16_t’ {aka ‘short int’} may change value [-Wconversion]
  458 |     new_en.rgb_ae_attr &= ((~HL_FG_INDEXED)
      |                           ^
../src/nvim/highlight.c:464:27: warning: conversion from ‘int’ to ‘int16_t’ {aka ‘short int’} may change value [-Wconversion]
  464 |     new_en.rgb_ae_attr &= ((~HL_BG_INDEXED)
      |                           ^
../src/nvim/highlight.c:470:27: warning: conversion from ‘int’ to ‘int16_t’ {aka ‘short int’} may change value [-Wconversion]
  470 |     new_en.rgb_ae_attr &= ((~HL_FG_INDEXED)
      |                           ^
../src/nvim/highlight.c:476:27: warning: conversion from ‘int’ to ‘int16_t’ {aka ‘short int’} may change value [-Wconversion]
  476 |     new_en.rgb_ae_attr &= ((~HL_BG_INDEXED)
      |                           ^
```

Therefore I add explicit casting to avoid this and remind developers there are conversions.

### CODE REVIEW

**Comment by zeertzjq** [comment]
`style` is not an allowed commit type. Use `refactor`.

**Comment by tanchihpin0517** [comment]
> `style` is not an allowed commit type. Use `refactor`.

Done.

**Comment by tanchihpin0517** [comment]
Hi, @zeertzjq. I noticed there are some failures in CI testing for Windows. I checked it and it seems that these failures are not related to `highlight.c`. I can't figure out why this happens. Could you give me some advices?

**Comment by bfredl** [comment]
@tanchihpin0517 which compiler (and version) is this?

**Comment by tanchihpin0517** [comment]
I ran on a  virtual machine with ubuntu 20.04 in a M1 Mac.
Here is the compiler info:
```
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Pull request closed without merging**
