### PR TITLE
[RFC] Fix warnings with gcc 6.1

### PR DESCRIPTION
**Pull request by bfredl**
I checked the intentional behavior of do_sub in vim

### CODE REVIEW

**Comment by bfredl** [comment]
It fails on qb-linux64 specifically. Does it have a different compiler version or options than the rest? Ping @jszakmeister

**Comment by jamessan** [comment]
The compilation failure is

```
05:59:57,308 INFO  - cd /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/src/nvim && /usr/bin/gcc -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/config -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src -isystem /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps/usr/include -isystem /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps/usr/include/luajit-2.0 -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/src/nvim/auto -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/include -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -Werror -Wno-conversion -o CMakeFiles/nvim.dir/eval.c.o -c /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/eval.c
05:59:57,462 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/eval.c: In function ‘f_reltime’:
05:59:57,462 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/eval.c:13217:3: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
05:59:57,462 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/eval.c:13217:3: error: ISO C99 does not support ‘_Static_assert’ [-Werror=edantic]
05:59:57,573 WARN  - cc1: all warnings being treated as errors
```

That happened on neovim-qb-slave-ubuntu-12-04-64bit so unless it is using a locally built compiler, that's likely using

```
$ rmadison -u ubuntu gcc | grep precise
 gcc | 4:4.6.3-1ubuntu5 | precise | amd64, i386
```

**Comment by bfredl** [comment]
Hmm, it is wierd that gcc 6.1 still allows `-pedantic` on the command line but not in a pragma. Seems we need to add a version check to use `-pedantic` for gcc 4.x and `-Wpedantic` later (in the pragma, cmdline is fine)

**Comment by jszakmeister** [comment]
@bfredl As @jamessan pointed out, it's running gcc 4.6.3--the stock compiler for Ubuntu 12.04.

**Comment by jamessan** [comment]
Ah, GCC introduced `-Wpedantic` in the 4.8 release.

> The new option -Wpedantic is an alias for -pedantic, which is now deprecated. The forms -Wno-pedantic, -Werror=pedantic, and -Wno-error=pedantic work in the same way as for any other -W option. One caveat is that -Werror=pedantic is not equivalent to -pedantic-errors, since the latter makes into errors some warnings that are not controlled by -Wpedantic, and the former only affects diagnostics that are disabled when using -Wno-pedantic.

**Comment by bfredl** [comment]
yes, we need to check the version, but I made the check for >=6 as to me gcc 6 is the "odd one out" as it allows `-pedantic` as a command line option but for some reason not in a pragma.

**Pull request merged**
