### PR TITLE
docs(spell): cword better than cWORD for :spellrare

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
(I've historically had not much luck PR'ing this project but am quite insane so continue to try anyway hehe)

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
(All three types of commit messages appear in the `git log`, e.g. 0c0a426e40692eabb3e1800cc93135eb70a28334 is `doc(CONTRIBUTING)` while c05b10748cd407d3c1d41d0c949649cec1f3bacc is `doc(dev_style.txt)` so sorry for the noise.)

**Comment by justinmk** [comment]
any reason not to send this to https://github.com/vim/vim ?

**Comment by justinmk** [comment]
There's a deep discussion at https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim but I agree we should have a tl;dr at CONTRIBUTING.md.

Meanwhile, this is a 2-line change. I don't think it costs too much to send a PR upstream.

> Does this project regularly sync its documentation with the upstream vim documentation?

https://github.com/neovim/neovim/commits/master

**Comment by clason** [comment]
>  Does this project regularly sync its documentation with the upstream vim documentation?

Yes, as part of porting the "runtime file updates".

> I think it would really help new contributors if Neovim's maintainers could clarify their relationship to the upstream vim project.

You can always ask first; that's what the chat is for. I think it is stated very clearly everywhere it matters that Neovim is a fork of Vim and that remaining compatibility is a priority goal (even if not the only one).

Of course, for someone without any experience, it is not obvious what this implies. So

> A section something like "Where does my PR go?" for CONTRIBUTING.md would solve a lot of my confusion about this project.

is a reasonable suggestion. The only issue is that it cannot be a full decision tree since it can depend on very specific circumstances as well as (in some cases) calls of judgement.

A TL;DR would be that the following should go to Vim first:

* **runtime files** (everything under `runtime`), with the exception of
  - files that do not exist in Vim (pretty much everything related to Lua)
  - `syntax` and `indent` files, which should go through the maintainer listed on top of the file
* **C source code** if it's a feature that exists in the same form in Vim (in particular, anything involving vimscript and options)

If in doubt, ask on https://matrix.to/#/#neovim-dev:matrix.org

**Comment by justinmk** [comment]
Added a note in CONTRIBUTING.md in https://github.com/neovim/neovim/pull/20720

**Pull request closed without merging**
