### PR TITLE
fix typo in documentation

### PR DESCRIPTION
**Pull request by serpent7776**

### CODE REVIEW

**Comment by teto** [comment]
The same error exists in vim.

**Comment by serpent7776** [comment]
Hi, already submitted [fix for vim](https://github.com/vim/vim/pull/5845)

**Comment by tjdevries** [comment]
@teto looks like it got merged in vim. it can just get merged now or it needs to get merged somehow special with the vim patch stuff?

**Comment by teto** [comment]
this is part of a vim "generate runtime update" 191acfdecabfbd2a74867e77004196fb3b4a8c14, let's follow the traditional vim-patch process to mimimize number of commits. @serpent7776 thanks for the fix, it will get merged with vim patches at a later date.

**Comment by serpent7776** [comment]
For the future: if I my PR will get merged in vim, will be automatically merged to neovim or should I open a separate PR here too? Not sure how merging of vim's PR works here.

**Comment by teto** [comment]
It's not automatic in the sense one has to do it but because bram commits patches in a certain way, it's easier for everyone to stick to the vim commits https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

**Comment by serpent7776** [comment]
Ok, so no need to open separate PR in neovim if it'll be merged in vim.

**Comment by tjdevries** [comment]
Or if you wanted to merge it, you can do it via the link above that teto posted and just implement the patch via the scripts. That'd be very helpful to do it that way!

**Comment by serpent7776** [comment]
ok, noted, thanks

**Pull request closed without merging**
