### PR TITLE
[RFC] Add files generated by PVS-Studio to gitignore

### PR DESCRIPTION
**Pull request by peskal**

### CODE REVIEW

**Comment by ZyX-I** [comment]
Not ignoring them allows to not forget to delete them.

**Comment by peskal** [comment]
Any reason they need to be deleted? My understanding was that they get overwritten anyway. If needed, could something be added to `make clean`?

**Comment by ZyX-I** [comment]
Repository is not a good place for random garbage, which includes anything not under version controls. Individual files are standable, but lots of `*.i` files mess up any way to list directory contents.

**Comment by peskal** [comment]
Got it. Is there already a way to run `./scripts/pvscheck.sh` without generating clutter in the repository or should this be added?

**Comment by justinmk** [comment]
`./scripts/pvscheck.sh -h` has many options including ability to use a different directory.

**Comment by peskal** [comment]
Okay. In retrospect, I'm not sure why I was getting all these files generated to my repo in the first place. My config must have been wonky. I reinstalled and re-ran pvs-studio and the generated files are only added to ../neovim-pvs now

For anyone else who comes across this and needs to know how:

Reinstall with
```
rm -rf ../neovim-pvs
./scripts/pvscheck.sh --pvs detect --deps
```
Then run with `./scripts/pvscheck.sh --recheck`. Error summary will be dumped to `../neovim-pvs/PVS-studio.tsk`

**Pull request closed without merging**
