### PR TITLE
build(deps): use libuv upstream for win32

### PR DESCRIPTION
**Pull request by clason**
New try for #15756 (`mingw-headers-git` just got updated); let's see if CI likes it.

### CODE REVIEW

**Comment by clason** [comment]
Guess I jumped the gun... Will try again tomorrow.

**Comment by clason** [comment]
@erw7 I don't quite understand this: according to https://packages.msys2.org/updates, the updated `headers-git` has made it into the package repo, but according to the CI logs, it is not updated when calling `pacman`. Am I missing a step here, or misunderstanding what you wrote in https://github.com/neovim/neovim/pull/15756#issuecomment-927275474?

**Comment by erw7** [comment]
Sorry, we didn't give `-y` as the command line argument for `pacman` when I looked closer. I think it will succeed if you give it `-y` (`-Syu`) in the next place.

https://github.com/neovim/neovim/blob/8a9f292991bca7d84a987be7b0eb0fd675a8dbb1/ci/build.ps1#L75

I tried to upgrade only `mingw-w64-i686-headers-git` in #15897, but it didn't work. I think the safest thing to do is to wait for the CI runner to be updated.

**Comment by clason** [comment]
Yep, that did the trick! \o/

**Comment by clason** [comment]
@erw7 Just for my understanding: Does this remove support for older Windows versions (7 and 8)?

**Comment by erw7** [comment]
> Just for my understanding: Does this remove support for older Windows versions (7 and 8)?

- Windows 7 support will be removed.
- Support for the following features will be removed from the TUI in Windows 8.1 and 8.
  - Support for mouse.
  - Support for alternate buffers.

**Review by justinmk — APPROVED** [review]
This is a nice technical debt reduction. Thank you @erw7 for all of your help with libuv + Windows.

going further, do we need winpty anymore? https://github.com/neovim/neovim/blob/b4c54ffa2216f46f9f0c456c7c53d3f6a66dad15/cmake/FindWinpty.cmake

1. What would we lose if didn't bundle it?
2. What would we lose if we removed `pty_process_win.c` ?

**Comment by erw7** [comment]
> going further, do we need winpty anymore?

Required to support embedded terminals in Windows 8.1.

> 1. What would we lose if didn't bundle it?
> 2. What would we lose if we removed pty_process_win.c ?

I think `1.` means the removal of embedded terminal support in Windows 8.1. `2.` will remove support for embedded terminals in all versions of Windows.

**Pull request merged**
