### PR TITLE
completion: Avoid flicker

### PR DESCRIPTION
**Pull request by justinmk**
Continues https://github.com/neovim/neovim/pull/4036

### CODE REVIEW

**Comment by Shougo** [comment]
Thank you.

LGTM

**Comment by alexlafroscia** [comment]
I tried this out, it fixes the flickering issue that I was seeing before.

**Comment by Shougo** [comment]
Thank you!

**Comment by Shougo** [comment]
I have ported it in vim_dev.

**Comment by Shougo** [comment]
It is merged in Vim 7.4.1405!

**Comment by wsdjeg** [comment]
how fast .now it is 7.4.1400+，but when will it be 7.5

**Pull request merged**
