### PR TITLE
feat(api): add forward and back mouse buttons

### LINKED ISSUE #26273: Extend nvim_input_mouse to handle X1Mouse and X2Mouse, i.e. navigation buttons
### Problem

The [nvim_input_mouse](https://neovim.io/doc/user/api.html#nvim_input_mouse()) api does not provide the mouse navigation buttons as a possible button to submit events for. This makes it impossible to create mappings for those mouse buttons, which are, as (neo)vim's help text suggests, very useful to map to `<C-O>` and `<C-I>`.

See e.g. https://github.com/neovide/neovide/issues/2148

### Expected behavior

Add "forward" and "back" (or maybe "navforward" and "navback or "x1" and "x2") as possible values to pass to the `button` parameter of `nvim_input_mouse`

### PR DESCRIPTION
**Pull request by agraven**
Fixes #26273 

Tested by running the following commands:
```
nnoremap <X1Mouse> <Cmd>echo "hello"<CR>
lua vim.api.nvim_input_mouse("x1", "press", "", 0, 1, 1)
```
The mapping is triggered as expected

### CODE REVIEW

**Comment by zeertzjq** [comment]
I don't think new terminologies should be introduced, so the buttons should be named `x1` and `x2`.

Also, need to adjust the range check in `check_multiclick()`.

**Comment by agraven** [comment]
> Also, need to adjust the range check in `check_multiclick()`.

Do you mean that
```c
  // For click events the number of clicks is updated.
  if (code == KE_LEFTMOUSE || code == KE_RIGHTMOUSE || code == KE_MIDDLEMOUSE) {
```
should be changed to also match `KE_x1MOUSE` and `KE_X2MOUSE`, or that
```c
  if ((code >= KE_MOUSEDOWN && code <= KE_MOUSERIGHT) || code == KE_MOUSEMOVE) {
    return 0;
  }
```
should be changed somehow? Or something else entirely?

**Comment by zeertzjq** [comment]
Ah, it's the first thing. Not a range.

**Comment by agraven** [comment]
That should do the trick.

**Comment by agraven** [comment]
I noticed, the help docs say
> Currently X1 and X2 only work on Win32 and X11 environments.

But from a skim of the related code I can't find any evidence of that being the case. Is this some sort of (g)vim holdover? If so, should I remove that part of the help text?

**Comment by bfredl** [comment]
In principle yes, although that section is full of platform references which is all obsolete (all nvim core is doing is defining an API, GUI:s are free to use these abstractions as they see fit for any platform), so it might make more sense to do a more general cleanup as a separate doc PR.

**Comment by agraven** [comment]
Makes sense. I'd be happy to make a follow-up PR for the documentation when this is merged then.

**Pull request merged**
