### PR TITLE
feat(filetype): support new init files added in gdb 11

### PR DESCRIPTION
**Pull request by lf-**
See
https://sourceware.org/gdb/onlinedocs/gdb/Initialization-Files.html#Initialization-Files

In particular, it adds (noting the ones relevant to filetype):
- ~/.config/gdb/gdbinit (covered already)
- ~/.config/gdb/gdbearlyinit
- ~/.gdbearlyinit
- (system gdbinit directory)/*.gdb

Submitted to vim here: https://github.com/vim/vim/pull/9956

### CODE REVIEW

**Comment by lf-** [comment]
I believe that this CI failure is spurious, or is at least extremely unlikely it is caused by my change.

**Comment by seandewar** [comment]
Thanks!
Once this is merged upstream, this PR should be converted to a vim-patch PR that ports the patch.

**Review by clason — APPROVED** [review]

**Comment by lf-** [comment]
Message changed.

**Comment by clason** [comment]
Thank you! (Our tooling relies on the exact format of the commit message to determine which patches have been ported already.)

**Pull request merged**
