### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by dundargoc**
Manual backport of https://github.com/neovim/neovim/pull/16506 (sans `nvim_{get,set}_option_value` changes).

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Ooh, Clint does _not_ like this...

**Comment by dundargoc** [comment]
I don't think it's clint this time, the commitlinter can't handle PRs to branches other than master I just realized.

**Comment by zeertzjq** [comment]
clint is reporting a lot of unrelated files...

**Comment by dundargoc** [comment]
Should I fix the clint errors or what's the plan?

**Comment by clason** [comment]
> Should I fix the clint errors or what's the plan?

On master, that would be great, if you wouldn't mind.

For the backport, I only care about the changes that make it into the actual docs -- would dropping everything else from this PR make Clint happy?

**Pull request closed without merging**
