### PR TITLE
tests: termclose_spec: fix flaky SIGTERM test

### PR DESCRIPTION
**Pull request by blueyed**
Followup to https://github.com/neovim/neovim/pull/7217.
Build failure: https://travis-ci.org/neovim/neovim/jobs/322930672#L2958.

### CODE REVIEW

**Comment by blueyed** [comment]
`asan_check` seems to fail with oldtests here?
https://travis-ci.org/neovim/neovim/jobs/322997880#L9090

**Comment by justinmk** [comment]
> asan_check seems to fail with oldtests here?

https://github.com/neovim/neovim/pull/7739 was an attempt to fix that, not sure why it didn't work.

**Comment by blueyed** [comment]
clint fails now?!
Seems to be related to a previous PR / the one you amended?
https://travis-ci.org/neovim/neovim/jobs/322997887#L2729

**Comment by justinmk** [comment]
merged, thanks!

**Pull request closed without merging**
