### PR TITLE
scripts/vim-patch.sh: improve patching (fuzz, unified, exit)

### LINKED ISSUE #10143: vim-patch.sh: less fuzzy?
vim-patch.sh applied vim/vim@1ebff3dc9 with fuzz=2 to `ex_hide`, although it is for `do_sleep`:

```diff
diff --git i/src/nvim/ex_docmd.c w/src/nvim/ex_docmd.c
index f4082fc83..16476d4f8 100644
--- i/src/nvim/ex_docmd.c
+++ w/src/nvim/ex_docmd.c
@@ -6405,6 +6405,11 @@ static void ex_hide(exarg_T *eap)
             win_close(win, false);
         }
     }
+
+    // If CTRL-C was typed to interrupt the sleep, drop the CTRL-C from the
+    // input buffer, otherwise a following call to input() fails.
+    if (got_int)
+       (void)vpeekc();
 }

 /// ":stop" and ":suspend": Suspend Vim.
```

I think we should maybe use `--fuzz=0` (or `--fuzz=1`) with `patch` to be more strict here.  The default is 2.
But that might cause it to be less helpful, i.e. rejecting too many patches then.

What do you think?  Should patch authors just pay enough attention?

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/neovim/neovim/issues/10143

[ci skip]

### CODE REVIEW

**Comment by justinmk** [comment]
Note that appveyor requires [ci skip] in the subject line (to avoid false positives with e.g. `git merge --squash`).

AFAIK increasing context lines may cause more failed patches. Let's try it anyway.

**Comment by blueyed** [comment]
Should have tested this really before: fails with the following now:

> patch: **** backup suffix is empty

**Comment by justinmk** [comment]
Haha, I thought I had already tried all those options, which is why I used `find` instead :0

**Comment by blueyed** [comment]
> AFAIK increasing context lines may cause more failed patches. Let's try it anyway.

Just seen it failing with vim/vim@a8356bc17 (tag: v8.1.1173), but that was good after all, since it showed that https://github.com/neovim/neovim/pull/10157/files#diff-1cd3c71bc19f50d4afd8664066760b96L50 was missing (not strictly, but likely helps to keep patches in order).

**Pull request merged**
