### PR TITLE
vim-patch:d2ea7cf10a4d

### PR DESCRIPTION
**Pull request by stsewd**
Update runtime files
https://github.com/vim/vim/commit/d2ea7cf10a4d026ebd402594d656af7d5c811c24

First time trying to merge a patch from vim :D, please do let me know if something isn't right.

- I didn't port the changes from tutor https://github.com/vim/vim/commit/d2ea7cf10a4d026ebd402594d656af7d5c811c24#diff-99ebc6b7f456528df8d873c46f34540b01652103e104b9195cb9a0b0d7e8a7bd (tracked it down to this file https://github.com/stsewd/neovim/blob/0b4c53fc23581abb14b6d4c567dc08720f509020/runtime/tutor/en/vim-01-beginner.tutor#L907-L907, should I update it here?)
- Didn't port a recommendation about truecolors and tmux https://github.com/vim/vim/commit/d2ea7cf10a4d026ebd402594d656af7d5c811c24#diff-e891ea60176f3f0bf0aa9bcd13c22cdb77f377ea932fe9515f5e0b16df8740da, other references to that part  haven't been ported, so I skipped it as well.
- The changes in termdebug I just followed what logically looks the same, I don't use that plugin.
- vim.vim had more changes but just left what the tool was able to patch, same as https://github.com/neovim/neovim/commit/b1cd67b62e58c7f7d4139416e6813f8f50bc0fd6#diff-7a82881606d3861674909df27974e1c38c3e031d00f486ca01ccff1d9bceed0f

### CODE REVIEW

**Comment by janlazo** [comment]
I worked on this patch before. Updates to 'c.vim' caused some tests to fail for me.

**Comment by justinmk** [comment]
@clason do we still need this?

**Comment by clason** [comment]
Oops, no, I already ported that update in https://github.com/neovim/neovim/commit/79cbbd5179d816a64989243cb1ce85b802a2896f

**Comment by clason** [comment]
Sorry, @stsewd !

**Pull request closed without merging**
