### PR TITLE
[WIP] Buffer Based STL Highlight Groups

### PR DESCRIPTION
**Pull request by tjdevries**
This is the start of an idea I had to make `statusline` easier to use in terms of getting results from individual buffers, rather than the current buffer.

Basically you should be able to combine `%{...}` with other modifiers to evaluate functions in a buffer and use the result as a special kind of statusline item.

For example, in this PR, I added the ability that one can do something like this with the `#` modifier, or the highlight modifier.

```vim

function! SetMyStatusline() abort
  let stl = ''
  " This is the new feature.
  " The result of my_stl#highlight_finder() will be used as a highlight group.
  " This function might check something like: &filetype to determine what kind of file is in the buffer where the stl is evaluated
  " This is currently impossible (at least from what I've looked at).
  let stl .= '%{#my_stl#higlight_finder()}'
  let stl .= '%{some_other_func()}'
  return stl
endfunction

set statusline=%!SetMyStatusline()
```

cc @tweekmonster @justinmk 

What do you think of the idea? I'll add tests and documentation if you think this is good.

### CODE REVIEW

**Comment by justinmk** [comment]
'statusline' is already window-local, isn't it? 

Extending the 'statusline' syntax seems a somewhat obscure way to address this use-case.
What if there were an option (or a mandatory change) that controls when 'statusline' is evaluated?

**Comment by tjdevries** [comment]
Yup, sorry, that was not a good explanation originally :) It was early in the morning my time.

So basically the motivating example is that while you can run functions within `%{func()}` and have that be evaluated in the buffer (i.e. `&filetype` would return the correct filetype for that buffer) you can't _use_ that result to generate a different kind of statusline item. This is because when vim builds the statusline, it does not recursively check if the result is a statusline item.

Here is an example configuration of what I'm talking about.

```vim
function! MyStl() abort
    let stl = ''
    " This works fine for returning results
    " But they won't be reinterpreted. (example below)
    let stl .= 'Activer buf: ' . nvim_buf_get_number(0) . ' '
    let stl .= 'Buf num: ' . '%{nvim_buf_get_number(0)}'

    let stl .= ' || Highlight examples: '
    " This will create a highlight group
    " But it will be the same for ever buffer
    " So switch between a .c file and a .vim file
    " and the statusline will take the highlighting of the filetype
    " of the file you are in.
    let stl .= MyStlHighlighter()
    let stl .= 'desired highlight'
    let stl .= '%* '
    " This will paste the name into the statusline
    " Because Vim doesn't check to see if this is some other kind
    " of statusline group
    let stl .= '%{MyStlHighlighter()}'
    let stl .= 'desire highlight'
    let stl .= '%*'

    " So my suggestion is:
    " let stl .= '%{#MyStlHighlither()}'
    " because you want to add a highlight group (specified by `#`)
    " but have it be evaluated on a buffer by buffer basis

    return stl
endfunction

function! MyStlHighlighter() abort
    if &filetype == 'vim'
        return '%#PreProc#'
    else
        return '%#Function#'
    endif
endfunction

set statusline=%!MyStl()
```

Try that out in vim and maybe it will make more sense what I'm saying. Not sure how else to describe it.

**Comment by justinmk** [comment]
Ah, I get it now. So the plan is to make `%{...}` work with many different modifiers, highlight groups are just the first step.

"extending" the 'statusline' syntax doesn't seem terrible to me since it's already a separate frankenstein DSL.

**Comment by tjdevries** [comment]
Right, and the `<mod>` piece should always just be the same piece as it was for without `%{...}`, so if you wanted to add a separator, you'd do something like `%{=...}`. So it won't really take too much cognitive effort to learn, and it I believe it's impossible to break any old statusline items because these characters are all invalid for naming a function.

**Comment by justinmk** [comment]
@tjdevries does #7875 help with your goal here, and if so can we close this?

**Comment by tjdevries** [comment]
Yeah, we can close this. I think that solution is better than adding to the syntax.

**Pull request closed without merging**
