### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by janlazo** [comment]
Copied from https://github.com/neovim/neovim/pull/12391#issuecomment-635344911

vim-patch:8.0.1543: with 'termguicolors' Normal color doesn't work correctly

vim-patch:8.1.0089: error when ending the terminal debugger
vim-patch:8.1.0557: Termdebug: gdb may use X.Y for breakpoint number
vim-patch:8.1.0575: Termdebug: clearing multi-breakpoint does not work
vim-patch:8.1.0621: terminal debugger does not handle unexpected debugger exit
vim-patch:8.1.1637: after running tests and clean the XfakeHOME directory remains
vim-patch:8.1.2105: MS-Windows: system() may crash
vim-patch:8.1.2116: no check for out of memory
vim-patch:8.1.2149: crash when running out of memory very early
vim-patch 8.1.2242: creating docs tags uses user preferences

vim-patch:8.2.0599: Netbeans interface insufficiently tested
vim-patch:8.2.0673: cannot build Haiku in shadow directory
vim-patch:8.2.0676: pattern in list of distributed files does not match
vim-patch:8.2.0680: PTYGROUP and PTYMODE are unused
vim-patch:8.2.0689: when using getaddrinfo() the error message is unclear
vim-patch:8.2.0702: running channel tests may leave running process behind
vim-patch:8.2.0709: MS-Windows: compiler warning for int vs size_t
vim-patch:8.2.0720: occasional exit when encountering an X error
vim-patch:8.2.0727: MS-Windows: new gcc compiler does not support scanf format
vim-patch:8.2.0740: minor message mistakes
vim-patch:8.2.0741: Python tests fail because of changed message
vim-patch:8.2.0744: the name vim is not capatilized in a message
vim-patch:8.2.0750: netbeans test is a bit flaky
vim-patch:8.2.0756: MS-Windows: still a compiler warning
vim-patch:8.2.0762: buffer is not considered modified after setting crypt key
vim-patch:8.2.0763: GUI test fails without the terminal feature
vim-patch:8.2.0765: In the GUI can't use all the modifiers.
vim-patch:8.2.0767: modifyOtherKeys active when using a shell command in autocmd
vim-patch:8.2.0770: cannot map CTRL-B when using the GUI
vim-patch:8.2.0773: switching to raw mode every time ":" is used
vim-patch:8.2.0776: libvterm code lags behind the upstream version
vim-patch:8.2.0777: terminal test fails
vim-patch:8.2.0778: libvterm code lags behind the upstream version
vim-patch:8.2.0779: tmode_T not used everywhere
vim-patch:8.2.0780: libvterm code lags behind the upstream version
vim-patch:8.2.0783: libvterm code lags behind the upstream version
vim-patch:8.2.0784: libvterm code lags behind the upstream version
vim-patch:8.2.0785: libvterm code lags behind the upstream version
vim-patch:8.2.0786: channel test is flaky on FreeBSD
vim-patch:8.2.0787: libvterm code lags behind the upstream version
vim-patch:8.2.0788: memory leak in libvterm
vim-patch:8.2.0792: build failure with small features
vim-patch:8.2.0794: libvterm code lags behind the upstream version
vim-patch:8.2.0795: libvterm code lags behind the upstream version
vim-patch:8.2.0796: MS-Windows: compiler can't handle C99 construct in libvterm
vim-patch:8.2.0797: MS-Windows: compiler still can't handle C99 construct
vim-patch:8.2.0798: libvterm code lags behind the upstream version
vim-patch:8.2.0799: build fails if snprintf is not available
vim-patch:8.2.0800: errors from failing test are unclear
vim-patch:8.2.0801: terminal test fails on Mac
vim-patch:8.2.0802: libvterm code lags behind the upstream version
vim-patch:8.2.0803: libvterm code lags behind the upstream version
vim-patch:8.2.0804: libvterm code lags behind the upstream version
vim-patch:8.2.0805: terminal key codes test fails on some systems
vim-patch:8.2.0808: not enough testing for the terminal window
vim-patch:8.2.0811: terminal keycode test is flaky
vim-patch:8.2.0813: libvterm code is slightly different from upstream
vim-patch:8.2.0816: terminal test fails when compiled with Athena
vim-patch:8.2.0828: Travis: regexp patttern doesn't work everywhere
vim-patch:8.2.0830: Motif: can't map "!"
vim-patch:8.2.0831: compiler warnings for integer sizes
vim-patch:8.2.0833: mapping <C-bslash> doesn't work in the GUI
vim-patch:8.2.0835: Motif: mapping <C-bslash> still doesn't work
vim-patch:8.2.0837: compiler warning for value set but not used
vim-patch:8.2.0842: MS-Windows: channel tests fail
vim-patch:8.2.0846: build failure with small features
vim-patch:8.2.0849: BeOS code is not maintained and probably unused
vim-patch:8.2.0852: cannot map CTRL-S on some systems
vim-patch:8.2.0854: xxd cannot show offset as a decimal number
vim-patch:8.2.0857: GTK cell height can be a pixel too much
vim-patch:8.2.0870: MS-Windows: Control keys don't work in the GUI
vim-patch:8.2.0872: XIM code is mixed with multi-byte code
vim-patch:8.2.0885: "make shadow" does not link new lua test dir
vim-patch:8.2.0889: using old style comments
vim-patch:8.2.0903: comparing WINVER does not work correctly
vim-patch:8.2.0910: Vim is not reproducibly buildable
vim-patch:8.2.0914: MS-Windows: cannot specify a "modified by" text
vim-patch:8.2.0931: some remarks about BeOS remain
vim-patch:8.2.0939: checking for term escape sequences is long and confusing
vim-patch:8.2.0940: build failure with tiny features
vim-patch:8.2.0941: detecting terminal properties is unstructured
vim-patch:8.2.0944: xxd test leaves file behind
vim-patch:8.2.0962: terminal test sometimes hangs on Travis
vim-patch:8.2.0971: build with tiny features fails
vim-patch:8.2.0978: leaking memory in termcodes test
vim-patch:8.2.0979: a couple of screendump tests fail
vim-patch:8.2.0989: crash after resizing a terminal window
vim-patch:8.2.1010: build failure in libvterm with debug enabled
vim-patch:8.2.1013: channel tests can be a bit flaky
vim-patch:8.2.1017: Appveyor output doesn't show MinGW console features
vim-patch:8.2.1027: GUI: multi-byte characters do not work in a terminal
vim-patch:8.2.1030: reducing size of a terminal window may cause a crash
vim-patch:8.2.1031: build failure with Perl5.32

**Comment by janlazo** [comment]
@teto Can you review the N/A patches I posted to determine if they are really N/A to neovim? If not, can you ask someone to review them?

**Comment by janlazo** [comment]
Not sure if the following patches are N/A:

https://github.com/neovim/neovim/pull/12447
vim-patch:8.0.1454: when in silent mode too much output is buffered

**Comment by teto** [comment]
we can add `vim-patch:8.0.1454: when in silent mode too much output is buffered`  as N/A
these 2 seem to have been applied already in 3a699a790c, so they are not really N/A i suppose, shall we add them manually to version.c:
vim-patch:8.1.0557: Termdebug: gdb may use X.Y for breakpoint number
vim-patch:8.1.0575: Termdebug: clearing multi-breakpoint does not work

**Comment by janlazo** [comment]
> these 2 seem to have been applied already in [3a699a7](https://github.com/neovim/neovim/commit/3a699a790c14f5d5a4cedbd87455e8201604ecfa), so they are not really N/A i suppose, shall we add them manually to version.c:
> vim-patch:8.1.0557: Termdebug: gdb may use X.Y for breakpoint number
> vim-patch:8.1.0575: Termdebug: clearing multi-breakpoint does not work

Mark them "N/A" even if they're not. `vim-patch.sh` cares only that the `vim-patch:${ref}:`, where `${ref}` is the commit hash or tag, is in the commit description. Besides, we cannot upgrade to version 8.1 so that we can edit version.c without breaking tooling because there are relevant 8.0.x patches remaining, such as https://github.com/neovim/neovim/pull/11148.

**Pull request merged**
