### PR TITLE
[RFC] vim-patch:7.4.1673

### PR DESCRIPTION
**Pull request by munyari**
Problem:    The justify plugin has to be copied or sourced to be used.
Solution:   Turn it into a package.

https://github.com/vim/vim/commit/2946d0236dc9e23ec0050feacdb959b9ae5672a8

### CODE REVIEW

**Comment by KillTheMule** [comment]
One nitpick: There are some changes in that vim patch you did not carry over. I assume rightly so, but you should imho write a small justification in the commit and pr message, just so the reviewer and future investigators can see everything is accounted for.

Otherweise LGTM :+1:

**Comment by munyari** [comment]
@KillTheMule my mistake. Justifications:

- `Filelist` does not exist in neovim
- There is no `README.txt` file in `runtime/macros` in neovim

**Comment by KillTheMule** [comment]
Not a mistake for sure, I dont think anybody else does this. Id have done it, so I mentioned it :)

**Comment by munyari** [comment]
woops, I did some git stuff to make the changes to my remote/branches as I discussed in gitter. I'll reopen

**Pull request closed without merging**
