### PR TITLE
Updated instructions on handling an out of date NPM neovim

### PR DESCRIPTION
**Pull request by yatesco**
#8515

### CODE REVIEW

**Comment by justinmk** [comment]
I reviewed https://stackoverflow.com/a/19824154/.

I think actually what we need is the `-g` flag. According to https://docs.npmjs.com/cli/update `npm update -g neovim` should work.

@janlazo any reason to doubt that?

**Comment by justinmk** [comment]
Ah, but `:checkhealth` doesn't distinguish between users that don't have the module yet. So `install -g` is better for now.

**Comment by janlazo** [comment]
Tested  on node 8

```sh
npm install -g neovim@3.5.0

# nothing happens
npm update neovim
npm update -g neovim

# install latest (4.0.x)
npm install -g neovim
```

**Comment by justinmk** [comment]
@janlazo Thanks for checking. Weird...

**Pull request merged**
