### PR TITLE
refactor: click definition functions

### PR DESCRIPTION
**Pull request by luukvbaal**
Need this part of `win_redr_custom()` in `drawline.c` for #20621. Breaking out this refactor to a separate PR as suggested by @lewis6991. Another refactor is pending in https://github.com/vim/vim/pull/11467.

### CODE REVIEW

**Comment by luukvbaal** [comment]
Why does `stl_clear_click_defs()` live in `screen.c` btw? Should these functions be moved to `statusline.c`?

**Comment by zeertzjq** [comment]
That's probably because `tab_page_click_defs` and `tab_page_click_defs` are in `screen.h`. They can probably be moved to `statusline.h` as well.

**Comment by luukvbaal** [comment]
> They can probably be moved to statusline.h as well.

Doing so probably only makes sense if we move `redraw_tabline()` to `statusline.c` as well. Do we want that?

**Comment by zeertzjq** [comment]
> > They can probably be moved to statusline.h as well.
> 
> Doing so probably only makes sense if we move `redraw_tabline()` to `statusline.c` as well. Do we want that?

@bfredl

**Review by lewis6991 — APPROVED** [review]

**Comment by justinmk** [comment]
Waiting on https://github.com/vim/vim/pull/11467 but let's keep things moving to unblock @luukvbaal

**Pull request merged**
