### PR TITLE
Fix plugin which opens ShaDa files

### PR DESCRIPTION
**Pull request by ZyX-I**
Ref #5482.

### CODE REVIEW

**Comment by ZyX-I** [comment]
Should be ready, waiting CI check.

**Comment by ZyX-I** [comment]
One of the jobs errored on

    [  ERROR   ] ...ld/neovim/neovim/test/functional/ex_cmds/ctrl_c_spec.lua @ 13: CTRL-C (mapped) interrupts :global

Should be unrelated, I only changed runtime files and their tests.

**Comment by justinmk** [comment]
> Maybe add new replacement for it which pcall-restarts the test on error and apply it to some tests? 

I added `helpers.retry()` for that purpose, but `pcall` doesn't seem to pickup test "failures"--only "errors".

**Comment by justinmk** [comment]
> [  ERROR   ] ...ld/neovim/neovim/test/functional/ex_cmds/ctrl_c_spec.lua @ 13: CTRL-C (mapped) interrupts :global

That particular test already tries itself 3 times, with different timing values.

In general it seems like the travis "trusty" beta is running on slower hardware. Of course it's not good for our tests to care about that, but the CTRL-C test is extremely sensitive and I haven't thought of yet more ways to make it less so.

**Comment by justinmk** [comment]
Hmm, and QB timed out on `job_spec.lua`. Not related to this PR of course, but the recent spate of QB problems suggests that the unreliability cannot be blamed on travis.

**Pull request merged**
