### PR TITLE
provider: has("python3_dynamic") et al.

### PR DESCRIPTION
**Pull request by justinmk**
Vim added more flags for testing yet more dimensions of its Python situation.  Handle those in eval_has_provider().

```
vim-patch:8.0.1436: not enough information about what Python version may work
Problem:    Not enough information about what Python version may work.
Solution:   Add "python_compiled", "python3_compiled", "python_dynamic" and
            "python3_dynamic" values for has().
```

ref: https://github.com/neovim/neovim/pull/10942#issuecomment-529479500

### CODE REVIEW

**Comment by bfredl** [comment]
What is the concrete difference between "compiled" and "dynamic" python w.r.t observable behaviour to plugins? Are some parts of the API only accessible to compiled builds? Otherwise I don't see why YCM (nor any vim plugin) would want to require `has('python_compiled')` specifically.

**Comment by justinmk** [comment]
I don't know.

**Comment by bfredl** [comment]
Perhaps there are none, the code below hints that YCM supports dynamic loading python, it just refuses to use it on 8.0.1436+ builds for whatever reason. Probably we should just merge this as is.

**Comment by bstaletic** [comment]
I'm not sure what the deal is with `python_dynamic`, but my vim is compiled with `--with-pythoninterp=dynamic` and both `python_dynamic` and `python_compiled` return `1`, even if I force uninstall python, to make `:version` display `+python/dyn` instead of `+python`.

**Comment by bfredl** [comment]
This is all I find:
```
#if defined(FEAT_PYTHON)
	"python_compiled",
# if defined(DYNAMIC_PYTHON)
	"python_dynamic",
# else
	"python",
	"pythonx",
# endif
#endif
#if defined(FEAT_PYTHON3)
	"python3_compiled",
# if defined(DYNAMIC_PYTHON3)
	"python3_dynamic",
# else
	"python3",
	"pythonx",
# endif
#endif
```
Seems like a big mess indeed. Probably the best to let `has("python_whatever")` return TRUE, to give any plugin a chance to run to start with. If it works it works, otherwise the plugin can be disabled.

**Pull request merged**
