### PR TITLE
os_open: return UV_EINVAL on NULL filename arg

### PR DESCRIPTION
**Pull request by justinmk**
ref #4370
ref https://github.com/neovim/neovim/issues/4370#issuecomment-344366571
ref ac055d677aa9eff9fca11cecb5ac7f7a4edb0265

### CODE REVIEW

**Comment by ZyX-I** [comment]
In addition to checking for UV_ENOENT it will raise an error based on uv_strerror. I would say this is more pressing matter: who knows what `-1` actually is, or will be in the future.

Though I would say that UV_EINVAL is more appropriate for this error: the error is not that NULL file does not exist, it is that os_open can’t swallow NULL file. Alternative would not be not returning immediately with UV_EINVAL when NULL was encountered, but actually running uv_fs_open, though with an empty string, and forwarding error from that.

**Comment by ZyX-I** [comment]
BTW, and if it was possible for shada.c to actually put NULL there, then that UV_NOENT would suppress the closest to the source error.

**Comment by jamessan** [comment]
> Though I would say that UV_EINVAL is more appropriate for this error: the error is not that NULL file does not exist, it is that os_open can’t swallow NULL file.

`open(2)` will set `errno` to `EFAULT` ("bad address") in this case, so I would argue `UV_EFAULT` is more faithful.

> Alternative would not be not returning immediately with UV_EINVAL when NULL was encountered, but actually running uv_fs_open

That's not a possibility since `uv_fs_open` asserts that the given path is non-NULL.  That's what we're trying to fix.

It's probably worth adding a comment to that effect just before the NULL check so this isn't reverted later on, since "let's use uv_fs_open's error" is a reasonable idea.

**Comment by ZyX-I** [comment]
> > Alternative would not be not returning immediately with UV_EINVAL when NULL was encountered, but actually running uv_fs_open

> That's not a possibility since uv_fs_open asserts that the given path is non-NULL. That's what we're trying to fix.

You cut my comment at wrong point, the continuation is “though with an empty string”. Not *NULL* string.

**Comment by ZyX-I** [comment]
About UV_EINVAL/UV_EFAULT: I do not have a strong preference over one or the other (mostly because I have not yet encountered UV_EFAULT), but I have strong preference against UV_ENOENT unless it is coming from libuv attempting to open an empty string. Note that last case is not unlikely: `strace -e open cat ''` on my machine shows exactly ENOENT.

**Comment by justinmk** [comment]
Currently `os_stat(NULL)` returns  `UV_ENOENT`. Should it also return `UV_EFAULT` , as os_open?

**Comment by jamessan** [comment]
They should be consistent, whatever the error code is.

**Comment by justinmk** [comment]
glibc returns EINVAL on null fname, so using that. https://github.com/bminor/glibc/blob/master/io/open.c#L35

**Pull request merged**
