### PR TITLE
fix(lsp): when buffer detach remove buffer from client attached buffers

### LINKED ISSUE #20025: when buffer detach buffer should be remove from client attached buffers
### Neovim version (nvim -v)

latest commit

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macos 12.5

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

- nvim - u min.lua
- open two lua file
- press `bd` to delete one
- `LspInfo` check the client attached buffers list

### Expected behavior

buffer should remove from client attched buffers list

### Actual behavior

still exists

Ref https://github.com/neovim/nvim-lspconfig/issues/1659

### PR DESCRIPTION
**Pull request by glepnir**
when buffer detached by using `bd` or `bw` .the buffer should remove from client acttached buffers list

Fix #20025

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Could you add a test case for this?

**Comment by glepnir** [comment]
@mfussenegger  found something wired in `lsp_spec` test . change `basic_init` to any number or string the test always pass.

https://github.com/neovim/neovim/blob/5ac6654334785427886d5698fdbe79577c8c6efe/test/functional/plugin/lsp_spec.lua#L412-L415

**Comment by glepnir** [comment]
nice work. but the ci faild :)

**Comment by mfussenegger** [comment]
There was something weird going on with exec_lua not returning anything. Moving the test case and moving everything into 1 exec_lua call seems to work as a workaround.

**Comment by glepnir** [comment]
good to know :)

**Pull request merged**
