### PR TITLE
[RFC] vim-patch: 7.4.1091

### PR DESCRIPTION
**Pull request by brcolow**
Problem:    When making a change while need_wait_return is set there is a two
            second delay.
Solution:   Do not assume the ATTENTION prompt was given when need_wait_return
            was set already.

https://github.com/vim/vim/commit/b01f357791f88c7083e58cf2b36509dd83f21ea2

### CODE REVIEW

**Comment by jamessan** [comment]
:+1:  Might want to set RFC in the title.

**Comment by justinmk** [comment]
@brcolow Please omit whitespace in the `vim-patch:...` string. And add a space after first line of all git commits. Like this:

```
vim-patch:7.4.1091 #4627                                                                                                                                    
                                                                                                                                                            
Problem:    When making a change while need_wait_return is set there is a two                                                                               
            second delay.                                                                                                                                   
Solution:   Do not assume the ATTENTION prompt was given when need_wait_return                                                                              
            was set already.
```

Note: `./scripts/vim-patch.sh -p 7.4.1091` does all of this for you.

**Comment by justinmk** [comment]
Merged after updating commit message. Thanks

**Comment by brcolow** [comment]
Noted. Thank you.

**Pull request closed without merging**
