### PR TITLE
fix: close floating windows when calling win_close()

### LINKED ISSUE #11440: Upon calling "close", automatically close floating window if it would be the last one in the tab
- `nvim --version`:
```
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Arch x64
- Terminal name/version: kitty
- `$TERM`: xterm-kitty 

### Steps to reproduce using `nvim -u NORC`

```
let g:buf = nvim_create_buf(0, 1)

let winopts = {
    \ 'width': 1,
    \ 'height': 1,
    \ 'relative': 'editor',
    \ 'anchor': 'NE',
    \ 'focusable': 0,
    \ 'row': 1,
    \ 'col': 1 }

tabnew

call nvim_open_win(g:buf, 0, winopts)

close
```

### Actual behaviour

`close` does not behave the same as `tabclose`; the latter does not error if replaced in the above code.

`TabClosed` to get rid of the floating window does not work either.

### Expected behaviour

Either `close` should not error, or `tabclose` changes to match its behavior.

### PR DESCRIPTION
**Pull request by lewis6991**
Rebased version of #14387

~Closes #11440~

### CODE REVIEW

**Comment by lewis6991** [comment]
Timeout on ASAN might be a little short

**Comment by gpanders** [comment]
Running CI again

**Review by gpanders — APPROVED** [review]

**Comment by lewis6991** [comment]
We're all good!

Someone merge?

**Comment by lewis6991** [comment]
Cheers @clason

**Comment by clason** [comment]
Any breakage from this PR, that's on gpanders :P

**Pull request merged**
