### PR TITLE
[RDY] terminal: preserve mode when using <Cmd>wincmd in terminal mode

### LINKED ISSUE #12246: tnoremap <Cmd>wincmd doesn't preserve mode
- `nvim --version`: NVIM v0.5.0-487-g501ef9529

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:tnoremap <A-j> <Cmd>wincmd j<CR>
:term
:sp term://sh
:startinsert
<A-j>
```

### Actual behaviour
The cursor is moved to the bottom split, neovim goes in normal mode.

### Expected behaviour
The cursor is moved to the bottom split, neovim stays in terminal mode because when using `inoremap` and regular buffers, neovim stays in insert mode.

### PR DESCRIPTION
**Pull request by glacambre**
Closes https://github.com/neovim/neovim/issues/12246

### CODE REVIEW

**Comment by glacambre** [comment]
I believe I've made a mistake in the test - I'll double check in 12 hours.

**Comment by glacambre** [comment]
I had indeed made a mistake writing the test (I'm not sure how it managed to pass given that it properly failed on an unpatched neovim). I believe the CI failures aren't mine, so this is probably ready to be merged.

**Comment by coiby** [comment]
I'm afraid this fix may not be complete. After merging this PR with v0.4.3 and build my own neovim, I notice the follow issues exit,

 - I have several tabs with terminal buffers in terminal mode. If I leave terminal mode for one tab and, all the other tabs will also leave terminal mode and vice versa. It seems all terminal buffers share a single state.
 - I have one tab with a terminal buffer and the other one with a normal file buffer. The terminal buffer will always be in normal mode when I switch from the normal file buffer to the terminal buffer regardless of whether the terminal buffer is in normal mode or terminal mode before.

I use the following mappings to make it easier for tab switching,
```
noremap <leader>1 <Cmd>tabn 1<cr>
noremap <leader>2 <Cmd>tabn 2<cr>
noremap <leader>3 <Cmd>tabn 3<cr>
noremap <leader>4 <Cmd>tabn 4<cr>
noremap <leader>5 <Cmd>tabn 5<cr>
noremap <leader>6 <Cmd>tabn 6<cr>
noremap <leader>7 <Cmd>tabn 7<cr>
noremap <leader>8 <Cmd>tabn 8<cr>
noremap <leader>9 <Cmd>tabn 9<cr>
noremap <leader>0 <Cmd>tablast<cr>
tnoremap <leader>1 <Cmd>tabn 1<cr>
tnoremap <leader>2 <Cmd>tabn 2<cr>
tnoremap <leader>3 <Cmd>tabn 3<cr>
tnoremap <leader>4 <Cmd>tabn 4<cr>
tnoremap <leader>5 <Cmd>tabn 5<cr>
tnoremap <leader>6 <Cmd>tabn 6<cr>
tnoremap <leader>7 <Cmd>tabn 7<cr>
tnoremap <leader>8 <Cmd>tabn 8<cr>
tnoremap <leader>9 <Cmd>tabn 9<cr>
tnoremap <leader>0 <Cmd>tablast<cr>
```

**Comment by glacambre** [comment]
On 2020-06-02 11:03, Coiby wrote:
>   * I have several tabs with terminal buffers in terminal mode. If I
>     leave terminal mode for one tab and, all the other tabs will also
>     leave terminal mode and vice versa. It seems all terminal buffers
>     share a single state.

This also happens for regular buffers. Mode is global, not 
tab/window/buffer-local. Changing this is out of the scope of this PR.

If you want buffer-local mode, I've simulated this in my config with a 
TermOpen autocommand 
(https://github.com/glacambre/.dotfiles/blob/b7e81848f6af9c3249b968f8a0f34e64c37393ab/default/.config/nvim/autocommands.vim#L51) 
which creates buffer-local autocommands 
(https://github.com/glacambre/.dotfiles/blob/b7e81848f6af9c3249b968f8a0f34e64c37393ab/default/.config/nvim/functions.vim#L124-L125) 
that set and check a variable to know whether insert mode should be 
entered or not. I choose whether I change these variables or not with 
specific keybindings 
(https://github.com/glacambre/.dotfiles/blob/b7e81848f6af9c3249b968f8a0f34e64c37393ab/default/.config/nvim/keymap.vim#L51-L57).

>   * I have one tab with a terminal buffer and the other one with a
>     normal file buffer. The terminal buffer will always be in normal
>     mode when I switch from the normal file buffer to the terminal
>     buffer regardless of whether the terminal buffer is in normal mode
>     or terminal mode before.

This is expected - mode is global. The terminal buffer being in normal 
mode when entering it from a regular buffer in insert mode is also 
normal as terminal buffers don't actually have an insert mode, only a 
terminal mode.

**Comment by glacambre** [comment]
Thanks for merging this @teto! :)

**Pull request merged**
