### PR TITLE
vim-patch:9.0.0813: Kitty terminal is not recognized

### PR DESCRIPTION
**Pull request by clason**
Problem:    Kitty terminal is not recognized.
Solution:   Recognize Kitty by the termresponse and then do not set
            seenModifyOtherKeys, since Kitty doesn't support that.
            (issue vim/vim#11413)
https://github.com/vim/vim/commit/4bc85f23ed2cf1fab20597ff15cefa675ea5e2c6

### CODE REVIEW

**Comment by clason** [comment]
@justinmk 🥷

**Comment by zeertzjq** [comment]
436e5d395fd629c8d33b5cf7b373aad007f16851

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/20769 (manual)

I did `vim-patch.sh -P 9.0.0814`, but it kept pulling in 9.0.0813 for some reason.

**Comment by clason** [comment]
Ah, Bram messed up the tags again (tagged the previous commit twice).

**Pull request closed without merging**
