### PR TITLE
[RDY] Update Ukrainian translation

### PR DESCRIPTION
**Pull request by sakhnik**
Take 2: 
- Rebase on top of upstream/master
- Fix encoding cp1251 in uk.cp1251.po

The difference is large because cleanup.vim removed references to the source code.

### CODE REVIEW

**Comment by justinmk** [comment]
@sakhnik I don't know what cleanup.vim is, but the comments should not be removed. It makes the file different from the other files and adds noise when comparing to upstream, not to mention reviewing this PR itself.

**Comment by jamessan** [comment]
Actually, removing the line comments brings us inline with upstream.  [cleanup.vim] is a script from upstream that is used to clean up the po files.

> " Vim script to cleanup a .po file:
" - Remove line numbers (avoids that diffs are messy).
" - Comment-out fuzzy and empty messages.
" - Make sure there is a space before the string (required for Solaris).
" Requires Vim 6.0 or later (because of multi-line search patterns).

[cleanup.vim]: https://github.com/vim/vim/blob/master/src/po/cleanup.vim

**Comment by justinmk** [comment]
@jamessan Thanks. That script is from 2006, I wonder why the .po files were not all updated in bulk.

**Comment by sakhnik** [comment]
So I always used clean.vim when updated Ukrainian translation for vim.
Should I keep doing so for neovim? Or forget about it?

2016-09-20 23:49 GMT+03:00 Justin M. Keyes <notifications@github.com>:

**Comment by jamessan** [comment]
> That script is from 2006, I wonder why the .po files were not all updated in bulk.

I'd wager that Bram leaves it up to the maintainers of the po files and he just merges whatever changes they send.

**Comment by jamessan** [comment]
> So I always used clean.vim when updated Ukrainian translation for vim. Should I keep doing so for neovim? Or forget about it?

Upstream's uk.po doesn't have line numbers, so I don't know why ours does.  I'd suggest removing them for uk.po, possibly as a separate commit than your translation updates so that it's easier to see what's relevant.

**Comment by justinmk** [comment]
Thanks @sakhnik

**Pull request merged**
