### PR TITLE
Revert "vim-patch:8.0.1723"

### LINKED ISSUE #10567: command-line window (q:) can not open in visual mode
- `nvim --version`:

```
NVIM v0.4.0-1374-g66149ecff
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/yoshio/src/neovim/build/config -I/home/yoshio/src/neovim/src -I/home/yoshio/src/neovim/.deps/usr/include -I/usr/include -I/home/yoshio/src/neovim/build/src/nvim/auto -I/home/yoshio/src/neovim/build/include
Compiled by yoshio@vlan017-dev01.cnta.local

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/yoshio/neovim/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? yes 

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2019 11:26:13)
Included patches: 1-1729
Compiled by yoshio@vlan017-dev01.cnta.local
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/yoshio/vim/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -ldl  -L/usr/lib -lluajit-5.1   -L/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm      
```

- Operating system/version: `Red Hat Enterprise Linux Server release 7.6 (Maipo)`
- Terminal name/version: 
- `$TERM`: `xterm-color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

# write some lines
# enter visual mode
# select some lines

q:
```

cannot-open-cmdwin

### Actual behaviour

does not open command-line window

### Expected behaviour

open command-line window

### note

I can open command-line window in visual mode with `:<c-f>`.

### PR DESCRIPTION
**Pull request by janlazo**
Close https://github.com/neovim/neovim/issues/10567

I guess vim-patch:8.0.1723 is broken regardless of the compiler version or OS. I can reproduce the problem on Ubuntu 16.04.

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks for addressing this.
However, it appears to work for the reporter in Vim - so either the patch is not correct, missing some later one, or conflicts with something different internally it seems.

**Comment by janlazo** [comment]
It works in Vim because it's reverted in a later patch.

**Comment by blueyed** [comment]
Ah, https://github.com/vim/vim/commit/285e33586 then likely (and others around it, for develop.txt where a note was added later).

**Comment by blueyed** [comment]
Thanks!

**Comment by blueyed** [comment]
Just for reference: I've checked Vim @ v8.0.1723, and could reproduce https://github.com/neovim/neovim/issues/10567 there (causing additional flashing (visual bell?) compared to Neovim).

**Comment by justinmk** [comment]
TSan travis job is failing, and seems to be correlated with this. https://travis-ci.org/neovim/neovim/builds/562397818

**Comment by blueyed** [comment]
It did not fail in this PR though, and I've seen it before.
It seems to fail during generating helptags.
I.e. it is not related to this PR, but likely something else that changed recently.

**Pull request merged**
