### PR TITLE
[RFC] vim-patch:8.0.1493: completion items cannot be annotated

### LINKED ISSUE #2508: Proposal: Additional meta field in completion-items
That would allow providing additional information for `CompleteDone` auto command, like modules needed to be added to import list (source https://github.com/vim/vim/issues/2505#issuecomment-354376933).

Ref #2505

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    Completion items cannot be annotated.
Solution:   Add a "user_data" entry to the completion item. (Ben Jackson,
            coses vim/vim#2608, closes vim/vim#2508)

https://github.com/vim/vim/commit/9b56a57cdae31f7a2c85d440392bf63d3253a158

### CODE REVIEW

**Comment by bfredl** [comment]
I was going to suggest to also sending it to external PUM, but then I noticed it was only a string and not a dict (where we could establish standard keys for styling etc), so it probably doesn't make much sense...

**Comment by justinmk** [comment]
Build failed. You can test it locally like this:

```
TEST_FILE=test_ins_complete.res make oldtest
```

**Comment by Shougo** [comment]
Reproduced the SEGV.
Hm...

**Comment by Shougo** [comment]
I have fixed the errors.

**Comment by Shougo** [comment]
I have tested user_data support.
Reproduced SEGV....

**Comment by Shougo** [comment]
The help is wanted.

**Comment by Shougo** [comment]
You can test it with the latest neosnippet.

**Comment by Shougo** [comment]
I have rebased it into master.

**Comment by justinmk** [comment]
All builds are failing.

**Comment by Shougo** [comment]
I get it.
I have fixed lua tests.

**Pull request merged**
