### PR TITLE
Add snap packaging

### PR DESCRIPTION
**Pull request by kalikiana**
This adds support for building neo**vim** as a classic snap.

### CODE REVIEW

**Comment by justinmk** [comment]
Must this go in a top-level `snap/` directory, or can it go in `contrib/` ?

**Comment by kalikiana** [comment]
@justinmk This is where `snapcraft` will look for it. Moving it in a sub folder would make it less discoverable and difficult to integrate with things like build.snapcraft.io.

**Comment by justinmk** [comment]
@kalikiana can it be a top-level snapcraft.yaml file instead? Having an extra subfolder seems pointless and distracts from the other, more relevant folders.

**Comment by justinmk** [comment]
@kalikiana I registered on https://build.snapcraft.io/user/neovim/neovim and setup snapcraft integration with this github repo. And I requested the "neovim" snap package name, which involved filing a "dispute".

**Comment by kalikiana** [comment]
@justinmk Thanks for picking this up! I never registered the proper name for myself since I'm not a neovim developer. The dispute is presumably the automatic thing because there's a package of the same name in the Ubuntu archive as well and it's a known project.

**Comment by justinmk** [comment]
It's failing to build luajit:

```
==== Building LuaJIT 2.0.5 ====
/usr/bin/make -C src
make[2]: Entering directory '/build/neovim/parts/neovim/build/.deps/build/src/luajit/src'
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
[...]
Makefile:254: *** Unsupported target architecture.  Stop.
make[2]: Leaving directory '/build/neovim/parts/neovim/build/.deps/build/src/luajit/src'
Makefile:109: recipe for target 'src/luajit' failed
make[1]: *** [src/luajit] Error 2
```

Maybe we should not use "bundled" deps.  How to install libraries with the snap yml? We need:

    sudo apt install gperf libluajit-5.1-dev libunibilium-dev libmsgpack-dev libtermkey-dev libvterm-dev libjemalloc-dev

**Comment by ovk** [comment]
A few comments based on my (very limited) knowledge of Snap:

1. I don't really think that `snap` folder belongs to this repo. Typically, a snap package would live in a separate repository. For example, it could be published with a help of [snapcrafters](https://github.com/snapcrafters). Please take a look at **Remaining Tasks** section of this sample [snapcrafters projects](https://github.com/snapcrafters/fork-and-rename-me) which describes publishing process.

2. Current snap exposes `neovim` command which is inconsistent with `nvim` that is used in other places (for example, in Debian package). Unfortunately, it is not possible to simply rename command to `nvim` because it won't match snap name (`neovim`) and thus will require additional namespacing. Renaming the whole package to `nvim` will solve namespacing issue, but I think `neovim` is much better for the package than `nvim`. So better solution could be to keep `neovim` as the package name and request a `nvim` command [alias](https://docs.snapcraft.io/commands-and-aliases/3950).

3. If I understand correctly, Neovim snap is currently built from the master's HEAD so there's no way to get stable version. In addition to that, snap takes version info from `git describe` while `:version` command from whatever is in CMake, so `snap info ...` version doesn't match `:version`. Maybe it would be better to start with just `stable` channel and always keep snap for latest stable version? Similarly to how it's done for [Gimp](https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml#L2).

And some small comments related to your current `snapcraft.yaml`:

- Shouldn't it be `confinement: strict` instead of `classic`? It will probably require `home` plug though.
- `build-packages` missing `gettext` dependency.
- `parts.*.snap` is deprecated and should be `parts.*.prime`. Also shouldn't `locale` folder be there?
- It would be nice to have snap icon and desktop file.

> It's failing to build luajit (well this is on the "armf" arch, maybe we need plain Lua there):

As a temporary solution, you can limit supported architectures:
```yaml
architectures:
  - amd64
  - i386
```

> Maybe we should not use "bundled" deps. How to install libraries with the snap yml? We need:

If they linked statically I think it is safe to add them to `build-packages`. But bundler should work as well.

> So we need to add curl to build-packages in the yml?

Yes, if it is required by the "bundler". `gettext` package will bring it as a dependency as well.

**Comment by while0pass** [comment]
Any update?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/11428

**Pull request merged**
