### PR TITLE
[RDY] docs: Describe how to escape keycodes with nvim_feedkeys

### LINKED ISSUE #12297: nvim_feedkeys() not escaping keycodes, nvim_input() does
From [the docs](https://neovim.io/doc/user/api.html#nvim_open_win()), I expect `nvim_feedkeys({keys}, {mode}, {escape_csi}) ` with `{escape_csi}` set to true to interpret key codes. I tried setting it to `true` as well as `false` with no difference in behaviour. I have read the docs but still am not 100% sure if that is its intended purpose.

- `nvim --version`:
```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"
```
- Operating system/version: Windows 10

### Steps to reproduce 
1: `nvim -u NORC`
2. create a new file `temp.vim`
3. Paste in the following:
```
echo "Sourced 5"
let mapleader = " "

lua <<EOF
function feed_test()
    vim.api.nvim_command('startinsert')
    vim.api.nvim_feedkeys("feedkeys feed\\<C-N>", "n", true)
end
function input_test()
    vim.api.nvim_command('startinsert')
    vim.api.nvim_input("input inp\\<C-N>")
end
EOF
imap <F5> <ESC>:lua feed_test()<CR>
imap <F6> <ESC>:lua input_test()<CR>
```
4. Save temp.vim, then `source temp.vim`
5. Enter insert mode, press `F5` and see autocomplete  menu **_does not_** pop up.
6. Enter insert mode, press `F6` and see autocomplete menu _**does**_ pop up.

### Actual behaviour
In step 5 above the <C-N> is sent as literal text instead of being interpretted as a key code.

### Expected behaviour
In step 5 above the <C-N> should be sent as if the user presses CTRL-N

### Side Note
Its hard for me to appreciate the difference between the two commands. If someone explains it here, I will try formalize it and make a PR to improve the docs.

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #12297

cc @erw7

### CODE REVIEW

**Comment by tjdevries** [comment]
Can you add an example while we're here? just use the exact example of `<c-l>` that you mention here so it's obvious how you would od it.

**Comment by tjdevries** [comment]
(add the explicit example in the docs I mean)

**Comment by nhooyr** [comment]
Will do.

**Comment by tjdevries** [comment]
@nhooyr bump

**Comment by nhooyr** [comment]
Thanks for the reminder, fixing this.

**Comment by nhooyr** [comment]
Fixed, please review!

**Pull request merged**
