### PR TITLE
Change pty job to use 'env' job option

### LINKED ISSUE #11751: 'env' job option overrides variables incorrectly, broken for pty jobs
- `nvim --version`: 
```
NVIM v0.5.0-314-g8ba3354d7
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/tpope/Code/vim/neovim/build/config -I/home/tpope/Code/vim/neovim/src -I/home/tpope/Code/vim/neovim/.deps/usr/include -I/usr/include -I/home/tpope/Code/vim/neovim/build/src/nvim/auto -I/home/tpope/Code/vim/neovim/build/include
Compiled by tpope@lancel

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Similar bug on Windows only: https://github.com/vim/vim/issues/5485
- Operating system/version: Ubuntu 19.10
- Terminal name/version: xterm
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
let $TESTVAR = '0'
let g:jobopts = {'stdout_buffered': 1, 'env': {'TESTVAR': '1'}}
call jobwait([jobstart('env', g:jobopts)])
echo join(filter(copy(g:jobopts.stdout), 'v:val =~# "^TESTVAR="'), "\n")
```

### Actual behaviour

```
TESTVAR=0
TESTVAR=1
```

Commands that use one value rather than list all values (e.g., `['sh', '-c', 'echo $TESTVAR']`) use the first value.

### Expected behaviour

```
TESTVAR=1
```

### PR DESCRIPTION
**Pull request by erw7**
fixes #11751.

- [x] Add test.

### CODE REVIEW

**Comment by erw7** [comment]
I have tried implementation on `UNIX` too. However, I do not know if there is no problem in handling `COLUMNS` etc. in the `env` dictionary passed by the user.

**Comment by bfredl** [comment]
> However, I do not know if there is no problem in handling COLUMNS etc. in the env dictionary passed by the user.

The user should set the `width` and `height` keys in `jobstart()` options dict, not COLUMNS directly.

**Comment by teto** [comment]
I had thought of keeping the environment as a vim dict instead https://github.com/neovim/neovim/compare/master...teto:fix_pty_env?expand=1 (to use the existing interface to add/remove keys, call f_environ to retreive the environment and merge it with the job environment) and only at the end convert it to a proper environment C string but now that @erw7 has written these functions I am not sure what is best.

**Comment by erw7** [comment]
As I mentioned in this https://github.com/neovim/neovim/issues/11881#issuecomment-593250517, I think environment variables with duplicate names should be removed. In that case, I think that the implementation by @teto is better because the dictionary is easier to implement. Even in that case,  `build_env_block` on Windows can be used by changing the first loop to `TV_DICT_ITER`, so please use it.

**Comment by jamessan** [comment]
> Even in that case, `build_env_block` on Windows can be used by changing the first loop to `TV_DICT_ITER`, so please use it.

Were you asking @teto to prepare a PR or are you going to use his changes?

**Comment by teto** [comment]
This might be the main blocker for the next release. I might be able to work on this next month (due to the lockdown, It's a bit difficult to work on neovim for me) but feel free to pick it up then.
Still I would love @justinmk agreement as using vim dicts make the whole code more readable but may be more expensive at runtime.
This PR approach may need some tweaks but I suppose would be faster. I suppose we could use dicts first and if it becomes a problem change the implementation.

**Comment by jamessan** [comment]
> Still I would love @justinmk agreement as using vim dicts make the whole code more readable but may be more expensive at runtime.

If the code is easier to reason about/maintain, then I'd say that's the important part for now.  I doubt the performance difference would be noticeable.  Either way, this isn't a high-frequency code path.

**Comment by jamessan** [comment]
Continued in #12937

**Pull request closed without merging**
