### PR TITLE
fix(treesitter): fix TSNode:tree() double free

### LINKED ISSUE #23613: treesitter  api caused neovim crash
### Problem

define a buffer keymap callback for rust filetype . in callback do treesitter highlights query type match . then open a rust file do lhs . crashed.

### Steps to reproduce

min config 

```lua
vim.opt.runtimepath:append("path/to/nvim-treesitter")
require('nvim-treesitter').setup({})

vim.opt.termguicolors = true

local api =vim.api
local buf = api.nvim_get_current_buf()
local function ts_node_match(target,  opt)
  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
  local line = vim.api.nvim_buf_get_lines(opt.buf, row - 1, row, false)[1]
  local word = string.match(line:sub(1, col), '%w+$') or ''
  local ok, lang = pcall(vim.treesitter.language.get_lang, vim.bo[opt.buf].filetype)
  if not ok or not lang then
    return
  end
  local has, parser = pcall(vim.treesitter.get_parser,opt.buf, lang)
  if not parser or not has then
    return false
  end
  local query = vim.treesitter.query.get(lang, 'highlights')
  if not query then
    return
  end
  local curnode = vim.treesitter.get_node({ bufnr = opt.buf })
  if not curnode then
    return
  end
  local root = curnode:tree()
  return true
end

  api.nvim_buf_set_keymap(buf, 'i', ';', '', {
    noremap = true,
    nowait = true,
    expr = true,
    callback = function()
      local opt = {
        buf = buf,
      }
      opt.lnum, opt.col = unpack(api.nvim_win_get_cursor(0))
      if ts_node_match('namespace', opt) then
        return '::'
      end
      return ';'
    end,
  })

```

nvim --clean -u `min.lua` src/main.rs. in this file 

```rust
#[derive(Debug)]
enum PokerSuit {
    Clubs,
}

pub fn enum_in_rust() {
    let clubs = PokerSuit::Clubs;
    if clubs == PokerSuit|->cursor here
}
```
hold `;` until crash..

### ScreenShot

test

### Crash Report

```
VM Region Info: 0 is not in any region.  Bytes before following region: 4478201856
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10aebf000-10b3d3000    [ 5200K] r-x/r-x SM=COW  ...s/USER/*/nvim

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   nvim                          	       0x10aef2a0d ts_subtree_size + 5 [inlined]
1   nvim                          	       0x10aef2a0d ts_node_end_point + 29 (node.c:411)
2   nvim                          	       0x10b171fbf node_range + 175
3   nvim                          	       0x10af1e806 lj_BC_FUNCC + 68
```
Registers 
```
Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000007  rbx: 0x0000000000000010  rcx: 0xffffffff00000000  rdx: 0x0000b25a692988a0
  rdi: 0x000000010b5f7380  rsi: 0x0000000000000002  rbp: 0x00007ff7b503e530  rsp: 0x00007ff7b503e530
   r8: 0x0000000000000065   r9: 0x000000010b61d620  r10: 0x000000010b6f2878  r11: 0x000000010b69a758
  r12: 0x000000010b5f7380  r13: 0x0000001000000007  r14: 0x000000010b5f8360  r15: 0x000000010b171f10
  rip: 0x000000010aef2a0d  rfl: 0x0000000000010246  cr2: 0x00006000035a5000

Thread 0 instruction stream:
  00 00 00 55 48 89 e5 48-8b 45 14 5d c3 66 0f 1f  ...UH..H.E.].f..
  44 00 00 55 48 89 e5 8b-45 10 48 8b 4d 20 48 8b  D..UH...E.H.M H.
  09 f6 c1 01 75 06 48 8b-49 10 eb 04 48 c1 e9 38  ....u.H.I...H..8
  01 c8 5d c3 66 66 66 66-66 66 2e 0f 1f 84 00 00  ..].ffffff......
  00 00 00 55 48 89 e5 48-b9 00 00 00 00 ff ff ff  ...UH..H........
  ff 8b 45 14 48 8b 55 20-48 8b 12 f6 c2 01 75 0c  ..E.H.U H.....u.
 [48]8b 72 10 48 21 ce 8b-52 18 eb 06 48 c1 ea 38  H.r.H!..R...H..8	<==
  31 f6 48 0f a4 f2 20 85-d2 74 0c 89 c6 01 d6 48  1.H... ..t.....H
  21 d1 48 89 c8 eb 10 8b-75 18 48 c1 e6 20 48 01  !.H.....u.H.. H.
  f2 48 21 ca 48 89 d6 48-09 f0 5d c3 0f 1f 80 00  .H!.H..H..].....
  00 00 00 55 48 89 e5 48-8d 45 10 0f b7 4d 1c 66  ...UH..H.E...M.f
  85 c9 74 08 66 83 f9 ff-75 21 eb 16 48 8b 48 10  ..t.f...u!..H.H.

Binary Images:
       0x10aebf000 -        0x10b3d2fff nvim (*) <53b13435-7d13-3663-889c-cab75bd90cff> /Users/USER/*/nvim
       0x10b5cf000 -        0x10b5dafff libintl.8.dylib (*) <146b350b-3118-3f81-aab0-b6792d3d810d> /usr/local/Cellar/gettext/0.21.1/lib/libintl.8.dylib
       0x10b894000 -        0x10b94bfff rust.so (*) <4e9b8691-81f1-3576-85fa-a48109b981db> /Users/USER/*/rust.so

```

VimRegion

```
"vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4478201856\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10aebf000-10b3d3000    [ 5200K] r-x\/r-x SM=COW  ...s\/USER\/*\/nvim",
  "exception" : {"codes":"0x000000000000000d, 0x0000000000000000","rawCodes":[13,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"UNKNOWN_0xD at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":1850},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4478201856\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10aebf000-10b3d3000    [ 5200K] r-x\/r-x SM=COW  ...s\/USER\/*\/nvim",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":1,"thread_set_state":0,"task_for_pid":1},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1680781,"instructionState":{"instructionStream":{"bytes":[0,0,0,85,72,137,229,72,139,69,20,93,195,102,15,31,68,0,0,85,72,137,229,139,69,16,72,139,77,32,72,139,9,246,193,1,117,6,72,139,73,16,235,4,72,193,233,56,1,200,93,195,102,102,102,102,102,102,46,15,31,132,0,0,0,0,0,85,72,137,229,72,185,0,0,0,0,255,255,255,255,139,69,20,72,139,85,32,72,139,18,246,194,1,117,12,72,139,114,16,72,33,206,139,82,24,235,6,72,193,234,56,49,246,72,15,164,242,32,133,210,116,12,137,198,1,214,72,33,209,72,137,200,235,16,139,117,24,72,193,230,32,72,1,242,72,33,202,72,137,214,72,9,240,93,195,15,31,128,0,0,0,0,85,72,137,229,72,141,69,16,15,183,77,28,102,133,201,116,8,102,131,249,255,117,33,235,22,72,139,72,16],"offset":96}},"threadState":{"r13":{"value":68719476743},"rax":{"value":7},"rflags":{"value":66118},"cpu":{"value":6},"r14":{"value":4485776224},"rsi":{"value":2},"r8":{"value":101},"cr2":{"value":105553172516864},"rdx":{"value":196101381130400},"r10":{"value":4486801528},"r9":{"value":4485928480},"r15":{"value":4481031952,"symbolLocation":0,"symbol":"node_range"},"rbx":{"value":16},"trap":{"value":13},"err":{"value":0},"r11":{"value":4486440792},"rip":{"value":4478413325,"matchesCrashFrame":1},"rbp":{"value":140701870581040},"rsp":{"value":140701870581040},"r12":{"value":4485772160},"rcx":{"value":18446744069414584320},"flavor":"x86_THREAD_STATE","rdi":{"value":4485772160}},"queue":"com.apple.main-thread","frames":[{"imageOffset":211469,"sourceFile":"subtree.h","symbol":"ts_subtree_size","imageIndex":0,"symbolLocation":5,"inline":true},{"imageOffset":211469,"sourceLine":411,"sourceFile":"node.c","symbol":"ts_node_end_point","imageIndex":0,"symbolLocation":29},{"imageOffset":2830271,"symbol":"node_range","symbolLocation":175,"imageIndex":0},{"imageOffset":391174,"symbol":"lj_BC_FUNCC","symbolLocation":68,"imageIndex":0}]}],
````

### Expected behavior

not crash

### Neovim version (nvim -v)

NVIM v0.10.0-dev-326+g108601647  

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 13.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build frome source

### LINKED ISSUE #24783: crash(nightly) when using `TSNode:tree()`
### Problem

If you use `tsnode:tree()` and then start editing the file, after a while, neovim will crash, with exit code 134 or 139.

### Steps to reproduce

```
nvim --clean
ifoo<esc>
:lua vim.treesitter.start(0,'lua')
:lua vim.treesitter.get_node():tree()
ofoobarbazfoobarbazfoobarbazfoobarbazfoobarbazfoobarbaz
```

### Expected behavior

neovim not crashing

### Neovim version (nvim -v)

v0.10.0-dev-f0e6e2a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

linux 6.4.10-arch1-1

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

### PR DESCRIPTION
**Pull request by ghost**
Problem: `push_tree`, every time its called for the same TSTree with `do_copy=false` argument, creates a new userdata for it. Each userdata, when garbage collected, frees the same TSTree C object.

Solution: Add flag to userdata, which indicates, should C object, which userdata points to, be freed, when userdata is garbage collected.  

fixes #24783  
fixes #23613

### CODE REVIEW

**Review by lewis6991 — APPROVED** [review]
LGTM

**Comment by lewis6991** [comment]
Asan failure is meaningful. There's some memory being leaked.

**Comment by nwounkn** [comment]
The problem seems to be here: https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/src/nvim/lua/treesitter.c#L475-L481
`parser_parse` creates a new tree, pushes it without copy, it should be garbage collected. How I fixed `push_tree` doesn't allow pushing a tree without making a copy to be owned by userdata. Maybe `push_tree` shouldn't create a copy itself, but require an argument, that indicates, whether a tree should be garbage collected or not.

**Comment by clason** [comment]
CI is happy; @lewis6991 one last look, then I'll squash, merge, and backport?

**Review by lewis6991 — APPROVED** [review]
This looks good. Thanks!

**Comment by bfredl** [comment]
in the latest version `push_tree()` is never used with gc=false, or am I failing to read? So at this point, why did we not just correct the `tree()` method to make a copy? `ts_copy_thread` is comparatively cheap, think "atomic refcount increment" not "deep copy" .

**Comment by lewis6991** [comment]
It's called in `node_tree()`.

**Comment by bfredl** [comment]
ok, it is used in `node:true()` but that is not going to be safe if objects get collected in the wrong order, I'll push a fix.

**Pull request merged**
