### PR TITLE
[RDY] runtime: Update makefile syntax file

### LINKED ISSUE #14024: Syntax highlighting is not applied correctly for ::= in Makefiles
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/via4xnlqpknjfh4afxiv3dvwm28mxva2-neovim-unwrapped-0.4.4/share/nvim
"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
Yes

- Operating system/version : NixOS 21.05pre272380.f6b5bfdb470 (Okapi)
- Terminal name/version: alacritty 0.7.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Open a Makefile, write e.g. `A ::= 1` and notice that syntax highlighting is missing while it is present for e.g. `A = 1`.

### Actual behaviour
Syntax highlighting is missing for that variable.
image

### Expected behaviour
Syntax highlighting.
image

### References

https://www.gnu.org/software/make/manual/html_node/Setting.html#Setting

### PR DESCRIPTION
**Pull request by vdot0x23**
This PR ports runtime changes for Makefiles.

Closes: #14024 
Vim commit info:

    vim/vim@2cfb4a2
    message: Update runtime files
    author: brammool
    committed on May 7, 2020

### CODE REVIEW

**Comment by clason** [comment]
"Presumably" -- did you test it? ;)

**Comment by vdot0x23** [comment]
> "Presumably" -- did you test it? ;)

No, not having success building neovim. I don't think luarocks works well with nixos :/

**Comment by clason** [comment]
There's a flake in the `contrib` folder, I believe -- @teto can give you advice. (You don't have to build, though, since you're just changing runtime files. Just set `$VIMRUNTIME` to the `runtime` folder in your fork where you made the changes.

**Comment by vdot0x23** [comment]
> There's a flake in the `contrib` folder, I believe -- @teto can give you advice. (You don't have to build, though, since you're just changing runtime files. Just set `$VIMRUNTIME` to the `runtime` folder in your fork where you made the changes.)

Oh fancy, it is tested now, works well :)

image

Thanks for being very helpful very fast :D

**Comment by clason** [comment]
No problem, thanks for the PR!

**Comment by janlazo** [comment]
```sh
$ ./scripts/vim-patch.sh -L -- 'runtime/syntax/make.vim'
9834b96820bec95d6858229d6fb256310365efff
ade0d39468014fd55d30f7647a1ac104baff4bc5
b17893aa940dc7d45421f875f5d90855880aad27
2cfb4a2a7248eeb40112bb482ab5b15f01b20433
```

Missing runtime changes are in these vim commits.
Port these commits similar to  https://github.com/neovim/neovim/pull/13835

**Comment by vdot0x23** [comment]
> ```shell
> $ ./scripts/vim-patch.sh -L -- 'runtime/syntax/make.vim'
> 9834b96820bec95d6858229d6fb256310365efff
> ade0d39468014fd55d30f7647a1ac104baff4bc5
> b17893aa940dc7d45421f875f5d90855880aad27
> 2cfb4a2a7248eeb40112bb482ab5b15f01b20433
> ```
> 
> Missing runtime changes are in these vim commits.
> Port these commits similar to #13835

Such that they are separate commits matching vim/vim instead of one big one? Can I do this with cherry-pick?

**Comment by janlazo** [comment]
> > ```shell
> > $ ./scripts/vim-patch.sh -L -- 'runtime/syntax/make.vim'
> > 9834b96820bec95d6858229d6fb256310365efff
> > ade0d39468014fd55d30f7647a1ac104baff4bc5
> > b17893aa940dc7d45421f875f5d90855880aad27
> > 2cfb4a2a7248eeb40112bb482ab5b15f01b20433
> > ```
> > 
> > 
> > Missing runtime changes are in these vim commits.
> > Port these commits similar to #13835
> 
> Such that they are separate commits matching vim/vim instead of one big one? Can I do this with cherry-pick?

Yes, if you can.
I manually copy/paste runtime files or create custom patches to `git apply` on Neovim's runtime/.

**Pull request closed without merging**
