### PR TITLE
vim-patch:7.4.1425

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    There are still references to MS-DOS support.
Solution:   Remove most of the help txt and install instructions. (Ken Takata)

https://github.com/vim/vim/commit/6e722e2f948bc51fcb92d98d6f2a089dac01e2bd

### CODE REVIEW

**Comment by fmoralesc** [comment]
LGTM. Should we merge this before #4301, @Shougo?

**Comment by Shougo** [comment]
Yes, it should be merged.

**Comment by fmoralesc** [comment]
Ok then.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
