### PR TITLE
vim-patch:7.4.1533

### PR DESCRIPTION
**Pull request by davix**
Problem:    Using feedkeys() with an empty string disregards 'x' option.
Solution:   Make 'x' work with an empty string. (Thinca)

When integrating the patch to nvim, used same logic but different code
based on nvim codebase. New test passed.

https://github.com/vim/vim/commit/74c5bbf13435a7ab1e3461078bbcb1200f0451e1

### CODE REVIEW

**Comment by davix** [comment]
Hi, this is my first commit for neovim. Please help to review carefully and tell me if I'm missing anything.

Many thanks,
Wei

**Comment by brcolow** [comment]
You added `source test_feedkeys.vim` to `test_alot.vim` but that file is missing from the commit.

**Comment by Shougo** [comment]
Vim 7.4.1535 should be also included.

**Comment by davix** [comment]
@brcolow Thanks for pointing it out. I've added the missing file and push again. (Here's my steps and please correct me if it's not optimal: 1) add file and commit --amend; 2) push needs pull beforehand, then two pulls; 3) push the updated commit.)

@Shougo Is it necessary to be together with 7.4.1535? I'll check it later.

**Comment by justinmk** [comment]
LGTM. Merged this since I already verified the test and squashed it, but @Shougo's note about 7.4.1535 is a good idea.

**Pull request closed without merging**
