### PR TITLE
ci: remove news workflow

### PR DESCRIPTION
**Pull request by dundargoc**
Contributors find it more annoying than helpful.

Edit: we'll keep it until the 0.9 release as per clason's [comment](https://github.com/neovim/neovim/pull/21967#issuecomment-1403665385)

### CODE REVIEW

**Comment by lewis6991** [comment]
FWIW I found it helpful.

**Comment by clason** [comment]
Maybe keep it until the 0.9 release (at which point the `news.txt` will be "complete"), then evaluate how the whole `news.txt` thing has been working for us and decide on how we'll want to handle it for the 0.10 cycle?

**Comment by dundargoc** [comment]
> Maybe keep it until the 0.9 release

Yes, that was the plan, I just wanted to put this up so 1. I wouldn't forget :) and 2. to give people time to discuss this if they wanted to. I should've mentioned this in the PR description, my bad.

**Comment by justinmk** [comment]
news.txt in general is looking like a success to me. 

We can mitigate the confusion about failed news.txt CI, by automating a one-time PR comment if news.txt fails, which explains something like "you can ignore news.txt CI job if this PR change is too low-level to be of interest to users or other external consumers".

**Comment by dundargoc** [comment]
> which explains something like "you can ignore news.txt CI job if this PR change is too low-level to be of interest to users or other external consumers".

Why can't contributors be expected to click the failing job that shows them the exact message? This will only spam our issues with the same stupid message. Hard no to this, sorry.

**Comment by glacambre** [comment]
I find the news.txt CI check useful and believe it should be kept, but I also think it would be nicer if it was not enabled on draft pull requests.

**Pull request closed without merging**
