### PR TITLE
[RFC] vim-patch:aa3b15d,82af871,7.4.1925,c95a302

### PR DESCRIPTION
**Pull request by jamessan**
#### vim-patch:aa3b15d

Updated runtime files.

https://github.com/vim/vim/commit/aa3b15dbebf333282503d6031e2f9ba6ee4398ed

#### vim-patch:82af871

Updated runtime files.

https://github.com/vim/vim/commit/82af8710bf8d1caeeceafb1370a052cb7d92f076

#### vim-patch:7.4.1925

Problem:    Viminfo does not merge file marks properly.
Solution:   Use a timestamp.  Add the :clearjumps command.

https://github.com/vim/vim/commit/2d35899721da0e9359a9fe1059554f8c4ea7f0c1

#### vim-patch:c95a302

Updated runtime files.

https://github.com/vim/vim/commit/c95a302a4c42ec8230473cd4a5e0064d0a143aa8

### CODE REVIEW

**Comment by jamessan** [comment]
I know 7.4.1925 was marked NA in #4634, but I pulled it back in since it added the `:clearjumps` command.  The shada code already handles the viminfo related changes, but I figured the command was worth adding.

**Comment by justinmk** [comment]
[Test_viminfo_jumplist](https://github.com/vim/vim/commit/2d35899721da0e9359a9fe1059554f8c4ea7f0c1#diff-06ea803abacc360d22b88795c6e82f6dR276) would be worth bringing over, if it passes without any fuss. Maybe even the whole test (again, if it doesn't cause trouble :).

**Comment by jamessan** [comment]
Well, it uses some of the `test_*` functions...  I guess I could replace at least `test_settime` with `sleep`, at the cost of run time.

**Comment by justinmk** [comment]
Oh, I see. Suggestion retracted then.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
