### PR TITLE
revert: "refactor(treesitter): simplify some range functions"

### PR DESCRIPTION
**Pull request by zeertzjq**
Reverts neovim/neovim#22549 because it breaks backward-compatibility.

### CODE REVIEW

**Comment by justinmk** [comment]
`:help treesitter` mentions:

> WARNING: Treesitter support is still experimental and subject to frequent changes. This documentation may also not fully reflect the latest changes.

Though, couldn't we accept a table if needed?

**Comment by lewis6991** [comment]
What compat does it break?

**Comment by clason** [comment]
Don't revert; improve if necessary, or fix upstream use. (Nvim-treesitter still uses its internal functions, IIRC.)

**Comment by clason** [comment]
To be clear: the `node-or-range` polyvalence of these upstreamed functions was a design flaw that needed to be fixed in core anyway. In this sense, Lewis' change was desirable.

**Comment by zeertzjq** [comment]
Closing as this has been fixed in vim-matchup and most other plugins seem to only use a node.

**Pull request closed without merging**
