### PR TITLE
fix(tui): delay initial clear until we know the bg color and termguicolors value

### PR DESCRIPTION
**Pull request by bfredl**
Note: I haven't been able to reproduce the issue myself (pangoterm rendering go brrr), but It might help with the case where `termguicolors` is changed during startup.

### CODE REVIEW

**Comment by IngoMeyer441** [comment]
I can confirm that your patch is working. :+1:  I tested it in Kitty with termguicolors set.

**Comment by gpanders** [comment]
Even without this patch, but with https://github.com/neovim/neovim/pull/26579 now in master, I can no longer reproduce the original issue from https://github.com/neovim/neovim/issues/26372, even when artificially introducing a delay using `nvim --cmd 'sleep 1'`.

**Comment by bfredl** [comment]
yes, https://github.com/neovim/neovim/pull/26579 has the same effect as this w.r.t the visual change. This PR (as a replacement) would only be required if it is necessary to check the detected value of 'termguicolors` early even if it doesn't take effect (I can't think of a good reason, but it is what it would do)

**Comment by bfredl** [comment]
after discussing a bit on matrix, we concluded _always_ setting 'termguicolors' as a OptionSet event is simpler (rather than having it sometimes being pre-set and sometimes being delayed to after startup, depending on the exact timing). So anyone who cares about the detected value should use an OptionSet event anyways.

**Comment by bfredl** [comment]
so, this might still be relevant for cases where the user `set termguicolors` manually. (my problem is that even my craptop is fast enough to never see this kind of flicker, after all rendering a terminal is peanuts compared to _surfing the modern web_, so I wouldn't really know )

**Comment by IngoMeyer441** [comment]
Without this patch, I can still recognize flicker in Kitty 0.31.0. There is a black frame for some milliseconds, followed by the correct background color. With this patch, I never see the black background.

**Comment by towry** [comment]
Yes, I can also see the default black background appears at the startup. I fixed it by set `vim.cmd.colorscheme("vim")` at the beginning of my config file because it has transparent background.

I use latest neovim nightly build.

**Pull request closed without merging**
