### PR TITLE
[RDY] Update LuaJIT

### PR DESCRIPTION
**Pull request by jimman2003**

### CODE REVIEW

**Comment by clason** [comment]
Thank you for this contribution, but the LuaJIT version we bundle is frozen on purpose; we do not follow upstream (blindly) since there is no stability guarantee even between commits -- such a bump can have unforeseeable effects which we don't want to risk for 0.5.

Is there a concrete reason for this bump? Is there an issue that this commit fixes?

**Comment by jimman2003** [comment]
Probably this:https://github.com/LuaJIT/LuaJIT/commit/52449e2a1e664f6fd1db965c2471a5d2a55fb7c5 (minGW build fix)

**Comment by clason** [comment]
Can you confirm that this actually affects (positively) our Windows build? (Manually, since CI doesn' test with Lua plugins like gitsigns that are the most likely to be hit by subtle internal changes.)

**Comment by jimman2003** [comment]
linux user :(

**Comment by clason** [comment]
Then this is too dangerous to merge for now, sorry! Such a change needs to fix an actual issue; we don't bump "just because".

**Pull request closed without merging**
