### PR TITLE
docs: builtin TUI is no longer channel 0

### PR DESCRIPTION
**Pull request by zeertzjq**

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by BlueDrink9** [comment]
Apologies if this isn't the right place for this question, but I can't seem to find the answer anywhere else in the docs. What is now the suggested way to tell if we are running in a TUI? It seems checking for supported `ui_*` features is currently unsatisfactory given many GUIs don't yet set them.

My usecase is to set the window size using `set columns` if not in a TUI. AFAIK none of the UI capabilities talk about having control over your own window size, yet most GUIs do respond appropriately to setting `columns`. Is the intention for users to check for supported features rather than blanket assuming features of TUI vs GUI? If so, can you suggest an alternative workflow?

**Comment by zeertzjq** [comment]
`has('gui_running')`

**Comment by BlueDrink9** [comment]
I tried `:h gui_running` which returned no results, so assumed that was still a wild west on neovim. Does that still require GUI maintainers to set? Or has neovim now got logic to ensure it
works regardless? (For reference:  https://github.com/equalsraf/neovim-qt/issues/102 https://github.com/equalsraf/neovim-qt/issues/219)

**Comment by BlueDrink9** [comment]
I installed nvim-qt, and it seems to now set `gui_running`. It would be helpful to document this solutin, either in a help doc or in a changelog somewhere; I looked at the 0.9 changelog and found this commit but nothing further

**Comment by justinmk** [comment]
:help has()

**Pull request merged**
