### PR TITLE
git: ignore .nvimlog

### PR DESCRIPTION
**Pull request by docwhat**
This was just annoying me.

### CODE REVIEW

**Review by mhinz — APPROVED** [review]

**Comment by justinmk** [comment]
I intentionally didn't do this, but ok.

**Comment by docwhat** [comment]
> I intentionally didn't do this, but ok.

Oh.  May I ask "why"?

**Comment by justinmk** [comment]
To give devs a hint that it's there, in case tests fail it may give useful information. 

If one runs tests often enough to be bothered by it, one can edit `.git/info/excludes`. But I personally am used to living with a noisy `git status`.

**Comment by docwhat** [comment]
I didn't know about `.git/info/excludes`!  TIL :smiley:

**Pull request merged**
