### PR TITLE
build: disable array bounds checking in gcc < 4.8.5

### PR DESCRIPTION
**Pull request by jszakmeister**
Thanks to James McCoy (@jamessan) for finding the source of this issue.

### CODE REVIEW

**Comment by jszakmeister** [comment]
I didn't say this in the commit message, but this gets the QB builds working again on Linux.

**Comment by jamessan** [comment]
LGTM, if you drop the `@` from the commit message. :)

**Comment by bfredl** [comment]
I guess could also delete all the pragma stuff in kbtree.h now

**Comment by jszakmeister** [comment]
> LGTM, if you drop the @ from the commit message. :)

Will do. :-)

**Comment by jszakmeister** [comment]
> I guess could also delete all the pragma stuff in kbtree.h now

Sorry if I caused you any headaches, but it looks like it really wasn't working out as master was still failing as well as all pull requests. :-(  If you want, I could try and remove it as part of this PR.

**Comment by oni-link** [comment]
> I guess could also delete all the pragma stuff in kbtree.h now

Compiling in release mode with gcc-7.1, I still see warnings about array subscripts in `kbtree.h`:
` warning: array subscript is below array bounds [-Warray-bounds]`

**Comment by jszakmeister** [comment]
@oni-link Are you compiling with `-O3` or `-O2`?  Just curious... there seem to be a lot of issue with bounds checking in `-O3`.  Actually, there just seems to be a number of array bounds issues in general. :-(

**Comment by oni-link** [comment]
Should be `-O2`:
`rm -rf build && make CMAKE_EXTRA_FLAGS='-DCMAKE_BUILD_TYPE=Release' -j5`

**Comment by bfredl** [comment]
Ahyes, the pragma actually has an effect on modern GCC, for some reason didn't work on the older gcc, at least not consistently...

**Comment by jamessan** [comment]
Hmm, I'm seeing the same thing @oni-link did with the pragma not being honored in GCC 7.  I wonder if it's related to GCC [bug #66099](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66099).

> This is because the location of the warning is given at 21:19, which is not within the range affected by the #pragmas. Whether the warning should be given at the macro definition point or at the expansion point is a matter of debate (there are at least two PRs open about this, but I don't remember the numbers).

**Pull request merged**
