### PR TITLE
vim-patch: 7.4.1113

### PR DESCRIPTION
**Pull request by gregorias**
Problem:    Using {ns} in variable name does not work. (lilydjwg)
    Solution:   Fix recognizing colon.  Add a test.

### CODE REVIEW

**Comment by gregorias** [comment]
Fixes #4587

**Comment by KillTheMule** [comment]
I'm not of the project team, but I'd vote for keeping the test in test_viml.vim like in the original to not move away from vim upstream if possible.

**Comment by gregorias** [comment]
I would have liked to simply copy paste that test, but it looks like test_viml.vim was previosuly test49.vim and neovim hasn't renamed it. In other words, there's not test_viml.vim in neovim, and test49.vim is its equivalent.

**Comment by KillTheMule** [comment]
Yeah right, I'm not sure how to deal with this properly, I guess I'd have included 1001 and 1030 in your PR myself, but it's not neccesary because they're already in my one.

**Comment by justinmk** [comment]
@gregorias https://github.com/neovim/neovim/pull/4565 is merged, would you mind rebasing this with respect to @KillTheMule comments above?

**Comment by gregorias** [comment]
Ok, the rebase is done

**Pull request merged**
