### PR TITLE
vim-patch:9.0.0434: gitignore files are not recognized

### PR DESCRIPTION
**Pull request by clason**
Problem:    gitignore files are not recognized.
Solution:   Add patterns for the gitignore filetype. (closes vim/vim#11102)
https://github.com/vim/vim/commit/9ba2786f15f0b53a90fd221832a5bedfc6dbfe20

Would it make sense to factor out the `XDG_CONFIG` check?

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
> Would it make sense to factor out the `XDG_CONFIG` check?

Only if it would make sense to factor it out for `gitconfig` & `gitattributes` as well.

**Comment by smjonas** [comment]
> Would it make sense to factor out the XDG_CONFIG check?

Seems like a good idea to me👍🏻

**Review by zeertzjq — APPROVED** [review]

**Review by smjonas — APPROVED** [review]

**Comment by clason** [comment]
> Only if it would make sense to factor it out for gitconfig & gitattributes as well.

Yes, that's what this means.

> Seems like a good idea to me👍🏻(meaning an extra table for all patterns that start with XDG_CONFIG_HOME)

Would you like to make a followup PR for that?

**Comment by smjonas** [comment]
> Would you like to make a followup PR for that?

Sure, I can make one tomorrow

**Comment by clason** [comment]
Maybe make it more general: `pattern_env` or something; that could be used for something like `$HOME` as well?

**Pull request merged**
