### PR TITLE
fix(matchparen): do not highlight inactive windows

### LINKED ISSUE #25099: MatchParen highlight is applied to floating windows
### Problem

`MatchParen` highlights are applied in non-active floating windows, such as the one for LSP hover.

### Steps to reproduce

1. Use the tippy-top of nightly Neovim.
2. In a `lua` file write:
```lua
local foo = {
  bar = 0,
}
```
3. Hover over `bar`.
4. Notice how the parentheses around `field` are underlined (the `MatchParen` highlight is being applied) despite my cursor being in an entirely different window:
image

### Expected behavior

For the `MatchParen` highlight to only be applied in active windows and based on the cursor position.

### Neovim version (nvim -v)

v0.10.0-dev-1074+g4258f4d53

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.5.2

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

From source

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #25099

### CODE REVIEW

**Comment by clason** [comment]
Matchparen is a bundled (fossilized) plugin we just take from Vim. Normally, we'd ask such changes to be made upstream first, but since this is a Neovim-specific issue, I'm not sure that would happen?

In any case, such divergence should be noted down explicitly somewhere.

**Comment by MariaSolOs** [comment]
@clason where should that somewhere be?

**Comment by clason** [comment]
Maybe it would be better to override this (via `nvim_del_autocmd`? or just `:NoMatchParen`?) in the LSP code that opens the float?

**Comment by MariaSolOs** [comment]
@clason sure, that sounds like a better scoped fix.

**Comment by MariaSolOs** [comment]
@clason oh but wait. Both `:NoMatchParen` and `nvim_del_autocmd` will disable the plugin globally since they don't take window-specific parameters.

As for the change in this PR, `WinEnter` will always be invoked even when removing `BufWinEnter`. The issue is that when `BufWinEnter` is invoked, the cursor position doesn't reflect the fact on whether the cursor is actually inside the window.

**Comment by clason** [comment]
Then I would recommend at least trying to get this fix into upstream.

**Comment by zeertzjq** [comment]
I don't think this is the correct solution.

**Pull request closed without merging**
