### PR TITLE
[WIP] tests: wildmode_spec: fix flaky test

### LINKED ISSUE #10253: flaky test: "'wildmenu' is preserved during :terminal activity"
```
  [ RUN      ] 'wildmenu' is preserved during :terminal activity: ERR
  test\functional\helpers.lua:294: attempt to perform arithmetic on local 'written' (a nil value)
  
  stack traceback:
  	test\functional\helpers.lua:294: in function 'nvim_feed'
  	test\functional\helpers.lua:300: in function 'feed'
  	C:/projects/neovim/test/functional\ui\wildmode_spec.lua:116: in function <C:/projects/neovim/test/functional\ui\wildmode_spec.lua:83>
```

Ref: https://ci.appveyor.com/project/neovim/neovim/builds/25334607/job/iykj6tkjmjoid0ed#L6801

### PR DESCRIPTION
**Pull request by blueyed**
Fixes #10253.

### CODE REVIEW

**Comment by justinmk** [comment]
can you wait for https://github.com/neovim/neovim/pull/10733 ?

**Comment by blueyed** [comment]
ok.
It seems to be good after rebase - do you have more plans there?

**Comment by justinmk** [comment]
I need time to stare at it.

**Comment by justinmk** [comment]
#10733 is merged now.

**Comment by blueyed** [comment]
Seems to be good without any changes for now - also for 200 rounds before #10733 even.

**Pull request closed without merging**
