### PR TITLE
vim-patch:8.2.{0208,0215,0942,3824,3939}: fnamemodify() patches

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.2.0208: fnamemodify() does not apply ":~" when followed by ":."

Problem:    Fnamemodify() does not apply ":~" when followed by ":.".
Solution:   Don't let a failing ":." cause the ":~" to be skipped. (Yasuhiro
            Matsumoto, closes vim/vim#5577)
https://github.com/vim/vim/commit/d816cd94d87afb73c505bf1e5cd5e07522482113

#### vim-patch:8.2.0215: wrong file name shortening

Problem:    Wrong file name shortening. (Ingo Karkat)
Solution:   Better check for path separator. (Yasuhiro Matsumoto,
            closes vim/vim#5583, closes vim/vim#5584)
https://github.com/vim/vim/commit/a78e9c61a0ded9c5302bc77e889aa1b3d3467f61

#### vim-patch:8.2.0942: expanding to local dir after homedir keeps "~/"

Problem:    Expanding to local dir after homedir keeps "~/".
Solution:   Adjust modify_fname(). (Christian Brabandt, closes vim/vim#6205)
https://github.com/vim/vim/commit/0e390f40e944036fb558a63b91238cfda128d95f

#### vim-patch:8.2.3824: no ASAN support for MSVC

Problem:    No ASAN support for MSVC.
Solution:   Add ASAN support and fix a coupld of uncovered problems. (Yegappan
            Lakshmanan, closes vim/vim#9357)
https://github.com/vim/vim/commit/6df0f2759d12ec0bc999b2963ecea4387a2bc516

#### vim-patch:8.2.3939: MS-Windows: fnamemodify('', ':p') does not work

Problem:    MS-Windows: fnamemodify('', ':p') does not work.
Solution:   Do not consider an empty string a full path. (Yegappan Lakshmanan,
            closes vim/vim#9428)
https://github.com/vim/vim/commit/5a664fe57fe7ba65a771bc95ef1c205e4db193b7

### CODE REVIEW

**Review by seandewar — COMMENTED** [review]
I think 8.2.3388 can be ported too for path_to_absolute: https://github.com/vim/vim/commit/4eaef9979fc5032606897963f1af37674ee0d422

**Comment by zeertzjq** [comment]
> I think 8.2.3388 can be ported too for path_to_absolute: [vim/vim@4eaef99](https://github.com/vim/vim/commit/4eaef9979fc5032606897963f1af37674ee0d422)

I've previously tried it but failed. Let me try it again.

**Comment by seandewar** [comment]
> I've previously tried it but failed. Let me try it again.

Does this work?

```diff
@@ -2358,6 +2358,10 @@ static int path_to_absolute(const char_u *fname, char_u *buf, size_t len, int fo
     }
 #endif
     if (p != NULL) {
+      if (STRCMP(p, "/..") == 0) {
+        // for "/path/dir/.." include the "/.."
+        p += 3;
+      }
       // relative to root
       if (p == fname) {
         // only one path component
@@ -2368,7 +2372,7 @@ static int path_to_absolute(const char_u *fname, char_u *buf, size_t len, int fo
         memcpy(relative_directory, fname, (size_t)(p - fname));
         relative_directory[p-fname] = NUL;
       }
-      end_of_path = (char *)(p + 1);
+      end_of_path = (char *)(*p == '/' ? p + 1 : p);
     } else {
       relative_directory[0] = NUL;
       end_of_path = (char *)fname;
```

**Comment by zeertzjq** [comment]
Seems to work.

**Review by seandewar — APPROVED** [review]
LGTM!

**Comment by seandewar** [comment]
Annoyingly I think the Windows CI has hung, hopefully it's not related?

**Comment by zeertzjq** [comment]
Looks like it broke clipboard.vim.

**Comment by seandewar** [comment]
Darn. I think it's fine to drop 8.2.3388 for now until we figure out what's up with it, because the other commits look fine. :+1:

**Comment by zeertzjq** [comment]
I also think so.

**Review by seandewar — APPROVED** [review]
Provided this passes CI this LGTM. 😄

**Pull request merged**
