### PR TITLE
[RFC] Fix legacy tests makefile after 4873171f.

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by Pyrohh** [comment]
Thanks @lucc, merged. I don't know if you've already been asked, but have you signed the CLA? I don't see your name on there.

**Comment by lucc** [comment]
@Pyrohh I didn't know this was necessary per se. The README sounds as if it is only for contributions before the license switch. Signed it anyway.

**Comment by Pyrohh** [comment]
> The README sounds as if it is only for contributions before the license switch

I really have no idea, thanks though.

**Comment by justinmk** [comment]
Sorry if the README.md is not clear. Hopefully https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md makes it clear though.

The README.md

**Pull request closed without merging**
