### PR TITLE
feat(lsp): show selected word in quickfix title #30305

### PR DESCRIPTION
**Pull request by Naofal-Helal**
Problem: `vim.lsp.buf.references` creates a quickfix list with a generic title as seen from :chistory :
image

Solution: ~Include the selected word in the title at the time of the request~
add the selected word to a context or vim.lsp.ListOpts

ref #30305

### CODE REVIEW

**Comment by justinmk** [comment]
No tests are failing, that means we don't have a test that exercises this?

**Comment by glepnir** [comment]
`vim.lsp.ListOpts` is designed to be configurable.  If you want to hardcode title there need to add it to all lsp methods that call qflist. Otherwise don't add it to any.  `title: word` or `title for word`? Cannot be defined as good or bad. Maybe we should configure the behavior here in our lsp common interface..

**Comment by Naofal-Helal** [comment]
Is it safe to add stuff to the lsp request context/params or would that cause problems.  e.g. here:
https://github.com/neovim/neovim/blob/b40ec083ae30eb64ddfec2b238c909116e936e99/runtime/lua/vim/lsp/buf.lua#L434-L441
adding
```lua
params.targetSymbol = "..."
or
params.context.targetSymbol = "..."
```

**Comment by mfussenegger** [comment]
> Is it safe to add stuff to the lsp request context/params or would that cause problems. e.g. here:

It should work but I wouldn't go that direction because it makes the typing more troublesome.
In order to handle multiple clients we'd need to move away from the current split into buf.references and handler.references - which would allow to pass along the target symbol with a closure.


The whole thing would probably look something like this:

```diff
diff --git a/runtime/lua/vim/lsp/buf.lua b/runtime/lua/vim/lsp/buf.lua
index a43ad8a69..61199368b 100644
--- a/runtime/lua/vim/lsp/buf.lua
+++ b/runtime/lua/vim/lsp/buf.lua
@@ -431,15 +431,53 @@ end
 ---@param context (table|nil) Context for the request
 ---@see https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references
 ---@param opts? vim.lsp.ListOpts
 function M.references(context, opts)
   validate({ context = { context, 't', true } })
-  local params = util.make_position_params()
-  params.context = context or {
-    includeDeclaration = true,
-  }
-  request_with_opts(ms.textDocument_references, params, opts)
+  local clients = vim.lsp.get_clients({ method = ms.textDocument_references })
+  if not next(clients) then
+    return
+  end
+  local win = api.nvim_get_current_win()
+  local remaining = #clients
+  opts = opts or {}
+
+  local all_items = {}
+  local title = 'References'
+
+  local function on_done()
+    if not next(all_items) then
+      vim.notify('No references found')
+    else
+      local list = { title = title, items = all_items }
+      if opts.loclist then
+        vim.fn.setloclist(0, {}, ' ', list)
+        vim.cmd.lopen()
+      elseif opts.on_list then
+        assert(vim.is_callable(opts.on_list), 'on_list is not a function')
+        opts.on_list(list)
+      else
+        vim.fn.setqflist({}, ' ', list)
+        vim.cmd('botright copen')
+      end
+    end
+  end
+
+  for _, client in ipairs(clients) do
+    local params = util.make_position_params(win, client.offset_encoding)
+    params.context = context or {
+      includeDeclaration = true,
+    }
+    client.request(ms.textDocument_references, params, function(err, result)
+      local items = util.locations_to_items(result or {}, client.offset_encoding)
+      vim.list_extend(all_items, items)
+      remaining = remaining - 1
+      if remaining == 0 then
+        on_done()
+      end
+    end)
+  end
 end
 
 --- Lists all symbols in the current buffer in the quickfix window.
 --- @param opts? vim.lsp.ListOpts
 function M.document_symbol(opts)
 ```

**Comment by Naofal-Helal** [comment]
Sorry for the late response.


> we'd need to move away from the current split into buf.references and handler.references - which would allow to pass along the target symbol with a closure.
> 

 I don't quite understand where the closure would be, and your changes would also need to be done for the other methods (get definition, get declaration, etc.)

After tinkering, the best solution I could figure is to introduce `get_target()` in `vim.lsp.ListOpts` and `target` in `vim.lsp.LocationOpts.OnList`, this would allow users to provide a custom `on_list` with access to the target symbol.

**Comment by justinmk** [comment]
try rebasing and force-pushing.

**Comment by mfussenegger** [comment]
I'm not sure anymore if this is even a good idea to include the `<cword>`.
With language servers like eclipse.jdt.ls you can get references for a function even if the cursor is not above the method name but for example inside the docs or the annotation.

For example:


```java
/**
 * Dummy
 **/
@Nullable
public static String foo() {
    return null;
}
```

Here the cursor could be on a `*` or over `Dummy` or `@Nullable` and you'd get
something like `References: Nullable` shown despite seeing references for
`foo()`.


This would be more confusing than helpful.

**Pull request closed without merging**
