### PR TITLE
[RFC] vim-patch:7.4.590

### PR DESCRIPTION
**Pull request by Yamakaky**
This patch was already present in neovim source.

### CODE REVIEW

**Comment by doppioandante** [comment]
Please follow [this] (https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#pull-requests), otherwise your PR is hard to review.

**Comment by glts** [comment]
Perhaps refer to relevant work in the commit message, #2527 and a71c5e9eb98fbb2ca88510269935cdcda37369fc.

**Comment by Yamakaky** [comment]
Sorry, I read this page but forgot to copy past the pr message.

**Comment by Yamakaky** [comment]
```
Problem:    Using ctrl_x_mode as if it contains flags.
Solution:   Don't use AND with CTRL_X_OMNI. (Hirohito Higashi)
```

https://github.com/vim/vim/commit/v7-4-590

Already included, see https://github.com/neovim/neovim/blob/master/src/nvim/edit.c#L2766

Original patch:

```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -3394,7 +3394,7 @@ ins_compl_bs()
      * allow the word to be deleted, we won't match everything. */
     if ((int)(p - line) - (int)compl_col < 0
 	    || ((int)(p - line) - (int)compl_col == 0
-		&& (ctrl_x_mode & CTRL_X_OMNI) == 0))
+		&& ctrl_x_mode != CTRL_X_OMNI))
 	return K_BS;
 
     /* Deleted more than what was used to find matches or didn't finish
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    590,
+/**/
     589,
 /**/
     588,
```

**Comment by Pyrohh** [comment]
@Yamakaky when you get a chance, please add what @glts said to the commit message.

**Comment by Yamakaky** [comment]
DO you mean add the reference to the other PR ?

**Comment by Pyrohh** [comment]
LGTM, could you take a look @fwalch?

**Comment by Yamakaky** [comment]
I don't really understand the version.c stuff:
- uncommented -> merged
- commented + NA -> no need to merge
Is that it ?

**Comment by Pyrohh** [comment]
> Is that it ? If so, I should have marked 590 as NA

The current situation seems ambiguous. Still, I think makes more sense here because the commit modifying `version.c` doesn't do anything else. That is, 590 was made not applicable because of 653. I don't think this is optimal, but there's not much we can do since we already applied 653 a while ago.

**Comment by Yamakaky** [comment]
Done

**Comment by glts** [comment]
Please follow the style of the surrounding NA lines.

Applying our rule of thumb 'if anyone would want to check whether feature x introduced in patch x.y.z is available would they get a `0` or `1`?', I think they should get a `1` (applicable) in this case. But it doesn't really matter here so I'm fine with NA.

**Comment by Pyrohh** [comment]
> available would they get a 0 or 1?', I think they should get a 1 (applicable) in this case

:+1: that sounds reasonable. Anyways, merged; thanks @Yamakaky.

**Comment by Yamakaky** [comment]
Maybe you forgot to merge ?

**Comment by Pyrohh** [comment]
> Maybe you forgot to merge ?

We merge a lot of PRs manually to avoid the merge commit. You should be able to see your commit referenced above. It was merged in https://github.com/neovim/neovim/commit/dce0b98f808458e48e7e15e90d2d8daaf11d6b8f.

**Comment by Yamakaky** [comment]
Wow, why do you do that ? Is it only for one-commit PR ?

**Comment by justinmk** [comment]
@Yamakaky Yes, only one-commit PRs. And we rebase most PRs, even multi-commit ones. 

Just because *GitHub* represents every snowflake in the universe as a "fork" does not mean every snowflake should be represented in the *permanent project history* as a *branch.* There's nothing sacred or magical about the fact that @user752342 forked the repo on September 13th 1929. In most cases, a patch is a *patch*. Not a *branch*. The permanent project record should reflect semantics, not some invented notion of historical precision.

**Pull request closed without merging**
