### PR TITLE
[RFC] vim-patch 8.0.0681

### PR DESCRIPTION
**Pull request by ckelsel**
vim-patch 8.0.0681: unnamed register only contains the last deleted text

    Problem:    Unnamed register only contains the last deleted text when
                appending deleted text to a register. (Wolfgang Jeltsch)
    Solution:   Only set y_previous when not using y_append. (Christian Brabandt)
    https://github.com/vim/vim/commit/18d90b95c49d9ff1c635dd762864022aab8e71f1

### CODE REVIEW

**Comment by janlazo** [comment]
Are those merge commits needed? Can you make a new branch on top of current master and then apply the patch?

**Comment by janlazo** [comment]
I plan on opening register-related PRs listed in https://gist.github.com/janlazo/cea7acf2711e89a9bc4f7c79612c6e54#register but you can do it instead. I may update the list as I go through the next set of patches after 8.0.0749.

**Comment by ckelsel** [comment]
@janlazo good job! I will do it next time, my job takes too much time

**Comment by janlazo** [comment]
@ckesel Ok. I will wait for you to open PR for those patches. I have other patches to deal with anyway.

**Pull request closed without merging**
