### PR TITLE
[WIP] vim-patch:8.1.{35,36,64,2419}

### PR DESCRIPTION
**Pull request by happy-dude**
Follow-up to https://github.com/neovim/neovim/pull/13025

Skipped patch https://github.com/vim/vim/commit/7964873afe59d0896a921b7c585167674bb784d5 and https://github.com/vim/vim/commit/2debf1c16b93f8693a785f675320d9e949c96a97 since they implement the `previewpopup` feature

I am unsure what to do with the following `testdir` dump files from 8.1.2141 and 8.1.2419:
* https://github.com/vim/vim/commit/e8070987c6ca9b1e14c5305707c6d29c8e58e7c4#diff-29f5730b25209a015079ff73f856b26b
* https://github.com/vim/vim/commit/0efd1bdcf4891f9ef2537e4c3d50a379186dca5f#diff-91e2d8b870f001dd6242ac1f8ff45eac

Ping @janlazo @erw7 for 👀

### CODE REVIEW

**Comment by Happy-Dude** [comment]
If I missed some `v8.0.x`, I don't mind tackling those too in this PR 😅
Sorry for so much trouble reviewing these!

**Comment by janlazo** [comment]
You skipped code for `#ifdef FEAT_JOB_CHANNEL`. That's relevant for patch 8.2.1783 which is why I mentioned that porting could be harder than expected.

**Comment by Happy-Dude** [comment]
I was under the impression that `FEAT_JOB_CHANNEL` was different for neovim; if I'm mistaken, can you provide some more context of where I can look to get a better understanding of what I missed?

From your advice, I elected to tackle `v8.1.x` patches only in this PR.

**Comment by Happy-Dude** [comment]
Ah I see; I was mistaken.

I'll amend this PR 👍

**Comment by Happy-Dude** [comment]
Apologies for the confusion/trouble @janlazo -- giving this another shot 🎯

Appreciate your time a lot!

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/13026 I ported patch 8.1.2141 to work on the tag patches.

**Comment by Happy-Dude** [comment]
Rebased and dropped patch `8.1.2141`.

**Comment by Happy-Dude** [comment]
Will take a look at the linting errors over Friday or the weekend 👍

**Comment by Happy-Dude** [comment]
Sorry for the multiple force-pushes; I rebased onto master realize that was unnecessary for these changes.

Ping @janlazo I updated the test that was failing. Please let me know if there are any items I need to attend to!

**Comment by Happy-Dude** [comment]
Looking closer at the failed tests in `test/functional/ui/screen.lua`; they failed for a similar reason as `popupmenu_spec.lua`: the popup menu closes on callbacks, etc, thus closing completion windows and exiting out of insert mode.

Question: should I get rid of these tests if they no longer apply, or add additional code to test the state that was desired? (i.e. a floating window shown after the popup menu)

I feel as though adding the additional code to the tests would be most appropriate. I am unfamiliar with the nvim-lua API, but I can certainly take a look at it 👍

**Comment by janlazo** [comment]
Your findings suggest that v8.2.x patches are needed to not introduce regressions. These UI tests shouldn't fail because they only target the prompt buffer. I can understand if only the popup tests are failing because there are unmerged popupmnu.c patches.

Ask on Gitter for assistance regarding the UI. It is out of my scope.

**Comment by Happy-Dude** [comment]
Thanks janlazo;

Ping @bfredl -- I was trying my hand at porting some vim-patches, but they cause some failures on some of the lua tests relating to popupmenus and floating windows.

I believe it is related to this block of code from the [8.1.0035](https://github.com/neovim/neovim/pull/13027/commits/2cf54022e5ffb74e91a9412bdae26a0551c13280#diff-ce1f54750dd541783db1cf9a24120ba8R652-R659).

This isn't urgent or anything, and can definitely chat/walk-through this more in Gitter.
Picked a quite an interesting first patch to contribute something to 😅

**Comment by janlazo** [comment]
I am going to cherry-pick patch 8.1.2419 in a separate PR. I can't merge the other patches because of the test failures.

**Comment by Happy-Dude** [comment]
Thanks @janlazo -- that sounds good to me.

Since this PR was beyond my level, I'll close it and leave it to folks who have a better idea of what they are doing 👍😅

**Comment by janlazo** [comment]
@Happy-Dude Thanks for the atempt. Some patches here are difficult to port. New contributors have better luck on patches that include non-screendump tests like  https://github.com/neovim/neovim/pull/13101 or patches that are N/A and should go in version.c PRs like https://github.com/neovim/neovim/pull/12763.

**Pull request closed without merging**
