### PR TITLE
Vim 8.0.1553

### PR DESCRIPTION
**Pull request by lokeshmohanty**
vim-patch: 8.0.1553
vim commit: https://github.com/vim/vim/commit/5f73ef8d20070cd45c9aea4dc33c2e0657f5515c
Problem:    Cannot see what digraph is used to insert a character.
Solution:   Show the digraph with the "ga" command. (Christian Brabandt)

### CODE REVIEW

**Comment by oni-link** [comment]
`*.orig` and `*.rej` are files created by the patching tool and don't belong in the PR. The files to be patched are missing (`various.txt`, `digraph.c`, ...), see the original vim patch for changed files.

**Comment by lokesh1197** [comment]
oh Thanks a lot. I was confused . I thought PR's are accepted in this form over here. I will make the changes and commit them

**Comment by jamessan** [comment]
@lokesh1197 Have you taken a look at our [documentation](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim) for merging patches?  We have tooling to help find patches to merge and setup the commit message for you.

Also, it's better to start with older patches first since newer patches are more likely to rely on the older ones.

**Comment by lokesh1197** [comment]
@jamessan thanks for that. I went through that but I didn't read thoroughly . I will go through it properly.

**Comment by lokesh1197** [comment]
continuing here #8190

**Pull request closed without merging**
