### PR TITLE
[RFC] vim-patches:7.4.530, 531, 535, 539, 542, 546, 561, 565, 566, 568, 572, 580, 585, 588, 595 (re: command ranges)

### PR DESCRIPTION
**Pull request by fmoralesc**
This ports patches related to command counts and ranges, which extend vim's command language.
- [x] 7.4.530
- [x] 7.4.531
- [x] 7.4.535
- [x] 7.4.539
- [x] 7.4.542
- [x] 7.4.546
- [x] 7.4.561
- [x] 7.4.565
- [x] 7.4.566
- [x] 7.4.568
- [x] 7.4.572
- [x] 7.4.580
- [x] T.4.584 _NA_
- [x] 7.4.585
- [x] 7.4.588
- [x] 7.4.595

Also, extended the patches list in version.c up to 595.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for doing this. 

There is discussion on vim_dev about how `addr_type=ADDR_LINES` does not make sense for all `wincmd` sub-commands, and it isn't really clear what the solution will be.

**Comment by fmoralesc** [comment]
@justinmk I thought about it too while porting this; the way it's currently done in this patch is pretty cumbersome.

BTW, I can't figure out why precisely the `clang-asan` build failed; in my local build, it stalls on `test/functional/runtime/autoload/provider/python_spec.lua` (perhaps my setup is messed up). It seems like Travis stalls at some point too (the `SIGPIPE` error), but I'm not sure if it's the same issue.

**Comment by justinmk** [comment]
> It seems like Travis stalls at some point too (the SIGPIPE error), 

I and others are seeing that as well: https://github.com/neovim/neovim/issues/1519#issuecomment-68602266

This is clearly a widespread problem.

**Comment by fmoralesc** [comment]
> This is clearly a widespread problem. 

Not, it seems like the original patch had a minor issue.

Should I add patches [539](https://groups.google.com/forum/#!searchin/vim_dev/cmd_addr_type/vim_dev/couPrse5b6s/Pd3TC6dWv3EJ), [540](https://groups.google.com/forum/#!searchin/vim_dev/cmd_addr_type/vim_dev/7oeh42OjgWU/5dqLRmBi9ZQJ), [561](https://groups.google.com/forum/#!searchin/vim_dev/ADDR_LINES/vim_dev/zp2Hj8v_sGA/qxV3bYF7hqUJ) and [565](https://groups.google.com/forum/#!searchin/vim_dev/ADDR_LINES/vim_dev/_Va04jSbKMs/9qFYvUde1-cJ) to this PR? I'm not sure if any other patch is relevant.

**Comment by justinmk** [comment]
> Should I add patches 539, 540, 561 and 565 to this PR

:+1: There was another bugfix(es) this week I believe.

**Comment by fmoralesc** [comment]
There were several! [566](https://groups.google.com/forum/#!topic/vim_dev/pqDLkEFL-dc), [568](https://groups.google.com/forum/#!topic/vim_dev/4I5X7-LQLMA), [572](https://groups.google.com/forum/#!topic/vim_dev/BeBQZCLkupM) and [580](https://groups.google.com/forum/#!topic/vim_dev/kLEYZHKaFIo) This is going to be another large patchset.

**Comment by fmoralesc** [comment]
Commit 9caac3486c5531b3c02a355d9f1ed702e6fb9bdd also applied vim-patch 531.

I'll have to port patch 535 too, because it is a precondition for 539.

**Comment by fmoralesc** [comment]
Damn! 

I am gladly patching stuff, and then I see "this patch modifies file test_command_count.in". "Ah, ok, that shouldn't be too hard... Hmm, I haven't yet added this file. Where can this come from? Let's go to vim's changelog... Let's see, between 540 and 561..." And then I see [this](https://code.google.com/p/vim/source/detail?r=de877dab1c3163a95ac8e7d3d6c3083a64e3c093). 

This might take longer than anticipated :p

**Comment by aktau** [comment]
> And then I see this.

Ouch! Thanks for the impressive work in letting us not trail vanilla though, I always like seeing these kinds of PRs.

**Comment by fmoralesc** [comment]
Thanks, @aktau. I actually had to add another patch! (7.4.546), because it included a refactoring of code related to these patches.

I'm not sure, but I think once these patches are merged neovim will be on par featurewise with vim 7.4.582 (latest), which is neat ;)

**Comment by Pyrohh** [comment]
Have you looked into `git-clang-format`? It looks like it would be really useful for importing patches while ensuring compliance with nvim's style guide. Just an idea.

```
usage: git clang-format [OPTIONS] [<commit>] [--] [<file>...]

Run clang-format on all lines that differ between the working directory
and <commit>, which defaults to HEAD.  Changes are only applied to the working
directory.

The following git-config settings set the default of the corresponding option:
  clangFormat.binary
  clangFormat.commit
  clangFormat.extension
  clangFormat.style

positional arguments:
  <commit>              revision from which to compute the diff
  <file>...             if specified, only consider differences in these files

optional arguments:
  -h, --help            show this help message and exit
  --binary BINARY       path to clang-format
  --commit COMMIT       default commit to use if none is specified
  --diff                print a diff instead of applying the changes
  --extensions EXTENSIONS
                        comma-separated list of file extensions to format,
                        excluding the period and case-insensitive
  -f, --force           allow changes to unstaged files
  -p, --patch           select hunks interactively
  -q, --quiet           print less information
  --style STYLE         passed to clang-format
  -v, --verbose         print extra information
```

**Comment by fmoralesc** [comment]
Sure, that would have been helpful ;) What would be the appropiate value for `--style?`.

**Comment by Pyrohh** [comment]
IIRC none of the presets match Nvim's style, so you'd have to make a config and load it.

**Comment by fmoralesc** [comment]
I was hoping you'd have that ;) OK, then.

**Comment by fwalch** [comment]
I think https://code.google.com/p/vim/source/detail?r=v7-4-585 is also related to this set of patches.

**Comment by fmoralesc** [comment]
This things grow up overnight! Thanks for the heads up. It also made me realise I haven't updated the Makefile for the old tests...

**Comment by fmoralesc** [comment]
I'll have to review this all (mostly, from 7.4.542 onwards). It seems like buffer ranges are not working properly.

**Comment by fmoralesc** [comment]
:( I'm pretty clueless about this. I've failed at making patch 7.4.542 pass the `test_command_count` test. I'm not sure what the difference between this and vim could be, I must be missing something. A good pair of eyes would be appreciated.

**Comment by fmoralesc** [comment]
@fwalch Thanks a lot for taking a look. Weirdest thing after all of these errors is the tests for the code that commit https://github.com/fmoralesc/neovim/commit/033cc4384b2c23125472de9d71476fb372b84e70 introduces *pass*, even at commit https://github.com/fmoralesc/neovim/commit/80bd9a1311560639bec654818bfc463021014c13, which is why I didn't review the commit. These errors might have been made visible only at https://github.com/fmoralesc/neovim/commit/c317c1a6ff189d5000697dcd6fb440bb31132b01

**Comment by fmoralesc** [comment]
In the end, the errors in the tests were cause by *transcription* errors in commits https://github.com/fmoralesc/neovim/commit/8d2b726532a19282ed80d50721a79394ef7d3b82 (which @fwalch found) and https://github.com/fmoralesc/neovim/commit/a1b73394520534a298172f21e3f8bb4cfe7a8b93. My bad :/

**Comment by elmart** [comment]
Is this finished? Mark it RFC if so, please.

**Comment by fmoralesc** [comment]
I still have to do some cleanup. The final state is fine and ready, but
some of the commits aren't (of course, I could also squash the whole thing,
but I would like to hear from @justinmk about that). patch 7.4.588 is also
relevant to this set, but I would rather clean what is already available
than add even more stuff.

**Comment by elmart** [comment]
Ok, no worries. I just wanted to make sure we weren't in a deadlock (you waiting for review, reviewers waiting for RFC). Regarding the squash, I personally think one separated commit per patch is better.

**Comment by fwalch** [comment]
> one separated commit per patch is better.

:+1: otherwise it will be very hard to review.

**Comment by fmoralesc** [comment]
OK, I cleaned up the commit history and added patches 588 and 595 (which were small). I'm marking as RFC. 

Note some tests might fail in intermediate commits, but this is an upstream issue too (for example, a problem with `test_command_count` introduced in 542 was only fixed in 572). I decided against incorporating these fixes to the affected commits in order to keep the patches history linear and make it match with upstream.

**Comment by elmart** [comment]
What's the status of this after recent big changes?

**Comment by fmoralesc** [comment]
Oh, I had forgotten about this. Will rebase and test.

**Comment by fmoralesc** [comment]
Had a issue with my local repo, I'll have to delete the branch this PR is pulling from and open a new one. In any case, the differences from HEAD were minimal (just in version.c and in ex_cmds.lua).

**Comment by glts** [comment]
Future reader: this epic tale continues in #2041.

**Pull request closed without merging**
