### PR TITLE
[RDY] Reuse inccommand preview window (fix #11529)

### LINKED ISSUE #11529: UI: inccommand should emit win_pos with grid position info
- `nvim --version`:
`NVIM v0.4.3 Build type: Release`

### Steps to reproduce using `nvim -u NORC`
```
$ cat ~/testnote
   "gitlab.com/hoge/fuga"
   "github.com/hoge/fuga"
   "github.com/baa/buzz"

$ goneovim -u NONE --cmd "set inccommand=split"
:e ~/testnote
:%s/github/test
```

### Actual behaviour
neovim ui event not notifies the grid position information corresponding to the `inccommand` window with `win_pos`.

### Expected behaviour
neovim ui event notifies the grid position information corresponding to the `inccommand` window with `win_pos`.

### screenshots
In this screenshot, each grid is translucent to make the problem easier to understand.
スクリーンショット 2019-12-07 17 45 55

### PR DESCRIPTION
**Pull request by vhakulinen**
Currently, show_sub (inside ex_substitute) creates a new split on each
run for its existing buffer, and ex_substitute calls close_windows for
it. This functionality seems to relay in delayed operations on window
structures where the close event on the newest window is "cancelled" by
win_grid_alloc. But for multigrid, there is optimization in place in
win_grid_alloc which causes any (unnecessary?) allocations to be
skipped, and thus inccommand preview window is not preserved but closed
immediately. Alternative fix would be to remove said optimization, but
the whole "lets create a new split each time and trash the earlier
window" seems too wasteful.

Fix #11529

I'm making shots in the dark here with the code, but tests (at least the functional once that I ran) pass.

### CODE REVIEW

**Comment by vhakulinen** [comment]
One failing test case, will look at that later.

**Comment by akiyosi** [comment]
@vhakulinen 
Great works!
It works well on goneovim.

**Comment by vhakulinen** [comment]
All the failed tests reported by the CI are passing on my local machine. How should I proceed with this?

**Comment by vhakulinen** [comment]
@jamessan at gitter related to the tests:
> They appear to be flaky tests. Kicked the test jobs again, but I don't see a reason to block the PR because of that

**Comment by tjdevries** [comment]
Thanks for the fix! This actually cleared up some problems in the terminal for me as well (just checked it out and ran through some tests).

Thanks!

**Pull request merged**
