### PR TITLE
[RFC] Align number of current line to the right

### PR DESCRIPTION
**Pull request by ghost**
This is more to discuss whether new parameter should be added allowing users to specify format of number and/or relativenumber.

At the moment current line's number is aligned to left which makes it ugly in my opinion.

Before patch: 
before

After patch: 
after

### CODE REVIEW

**Comment by wsdjeg** [comment]
oh nice!

**Comment by philix** [comment]
I think a new configuration parameter should be avoided and I don't have a strong opinion on the alignment of the current line number in `relativenumber`.

**Comment by mhinz** [comment]
Results from quick poll on Gitter/IRC: no one is against this change.

If @justinmk isn't against it, we should merge this quickly and get on.

**Comment by justinmk** [comment]
What happens when someone comes along and asks for the reverse? We had a fairly thorough discussion of alternatives on gitter, which should have been mentioned here...

**Comment by mhinz** [comment]
Okay, I quickly read up on that discussion (Gitter's search is nice):

- this change is highly opinionated ("Why is this different from Vim? I want it left-aligned!")
- if an option was introduced that toggles between left and right align, the next user might want it centered or upside-down
- an option that allows custom formatting is hard to get right (and unusual since there's no other option like that)

Putting it in a nutshell, if this "issue" really annoying enough to be changed? My vote is: no.

**Comment by justinmk** [comment]
Another approach: left-align _only_ if there was no highlighting enabled. :>

(Personally, I _like_ the left-alignment, but I don't use num/relnum so I don't count.)

**Comment by wsdjeg** [comment]
please consider
>That indeed looks like a helpful extensions, but I suggest to
highlight the current (absolute) linenumber differently, otherwise
it might be confusing in a file with the cursor at the top:
1 foobar
1 blah
2 fasel
regards,
Christian

**Comment by kwinczek** [comment]
Or unite all line number related options into something like:
set numbering=current-right,relative

One could set current-letf or even current-upsidedown-and-mirrored. :)

**Comment by nhooyr** [comment]
#4424 is a nice improvement

**Comment by justinmk** [comment]
Continued at https://github.com/neovim/neovim/pull/4941

**Pull request closed without merging**
