### PR TITLE
vim-patch:8.1.{1116,1188,1190,1355,1722,2035,2036,2038,2043},8.2.{0886,2309}

### PR DESCRIPTION
**Pull request by seandewar**
This PR adds the `:scriptversion`-related patches, but without the `:scriptversion`-specific stuff.
There are a few extra comments in the commit messages.

### CODE REVIEW

**Comment by justinmk** [comment]
Skeptical that we want `:scriptversion`. It introduces an intermediate form of vimscript before turning into vim9script. This is an "uncanny valley" of a brief moment in vimscript history that might be more confusing than useful.

This kind of stuff:

> When |vimscript-version| is 2 or higher, using "." is not allowed.

Land mines and cognitive overhead in documentation and scripts. 

Maybe it's better if we keep it simple and say "Nvim supports vimscript 1, and that's it".


> :scriptversion 3
>	All |vim-variable|s must be prefixed by "v:".  E.g. "version" doesn't
>	work as |v:version| anymore, it can be used as a normal variable.

We already made this change for some `v:` variables. 

>  :scriptversion 4
>	Numbers with a leading zero are not recognized as octal.  "0o" or "0O"

This again is a weak justification for having to sprinkle caveats all over the documentation.

I don't see a compelling reason for `:scriptversion`.

**Review by justinmk — CHANGES_REQUESTED** [review]
Skeptical that we want `:scriptversion`. It introduces an intermediate form of vimscript before turning into vim9script. This is an "uncanny valley" of a brief moment in vimscript history that might be more confusing than useful.

This kind of stuff:

> When |vimscript-version| is 2 or higher, using "." is not allowed.

Land mines and cognitive overhead in documentation and scripts. 

Maybe it's better if we keep it simple and say "Nvim supports vimscript 1, and that's it".


> :scriptversion 3
>	All |vim-variable|s must be prefixed by "v:".  E.g. "version" doesn't
>	work as |v:version| anymore, it can be used as a normal variable.

We already made this change for some `v:` variables. 

>  :scriptversion 4
>	Numbers with a leading zero are not recognized as octal.  "0o" or "0O"

This again is a weak justification for having to sprinkle caveats all over the documentation.

I don't see a compelling reason for `:scriptversion`. We could mark these as N/A.

**Comment by seandewar** [comment]
I agree; I don't believe many people even know about `:scriptversion` let alone use it anyway. :smile:

If you'd like, I can mark most of these as N/A and only include the revelant changes (namely the doc for `:let {var} ..= {expr1}` and the tests not related to `:scriptversion`).

**Comment by justinmk** [comment]
> If you'd like, I can mark most of these as N/A and only include the revelant changes (namely the doc for `:let {var} ..= {expr1}`, the tests not related to `:scriptversion` and v8.1.1355).

That would be great. I have updated the wiki https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

> NA ("Not Applicable") patches
> ...
> Vim9script features, and anything related to :scriptversion. (Nvim supports Vimscript version 1 only.)

**Review by justinmk — APPROVED** [review]
nice! waiting for non-draft PR

**Comment by seandewar** [comment]
Cheers!
Gonna catch some zzzs rn, but I'll undraft tomorrow once I have time to do a final look over :+1:

**Comment by janlazo** [comment]
Supporting scriptversion-1 compatible changes from `:scriptversion` patches should be fine for compatibility. Vimscript is lenient to to begin with.

It is tricky to mark patches that affect `has()` N/A because Vim updated it to detect **built-in** features. Full port of v8.2.0427 must restore the removed features.

```
has({feature} [, {check}])
		When {check} is omitted or is zero: The result is a Number,
		which is 1 if the feature {feature} is supported, zero
		otherwise.  The {feature} argument is a string, case is
		ignored.  See |feature-list| below.

		When {check} is present and not zero: The result is a Number,
		which is 1 if the feature {feature} could ever be supported,
		zero otherwise.  This is useful to check for a typo in
		{feature} and to detect dead code.  Keep in mind that an older
		Vim version will not know about a feature added later and
		features that have been abandoned will not be known by the
		current Vim version.
```

**Comment by seandewar** [comment]
Ah, I wasn't even aware v8.2.0427 was a thing. Sorry about that! 😅

Hopefully this won't cause too much of an issue when porting it? (Can N/A patches possibly be un-marked?)

**Comment by janlazo** [comment]
I am not aware of a process to filter out un-marked,reverted vim patches.

Make a PR that adds `vimscript-1` to `has()`.
The other `vimscript-` features can be resolved when porting v8.2.0427.

**Comment by justinmk** [comment]
> Keep in mind that an older
> 		Vim version will not know about a feature added later and
> 		features that have been abandoned will not be known by the
> 		current Vim version.

This is quite an escape-hatch. I would tentatively suggest we just don't support the `{check}` param of `has()`, or silently ignore it. Depending on how much code / headaches it would be to support it.

**Pull request merged**
