### PR TITLE
WIP: N/A Vim patches

### LINKED ISSUE #1977: Terminal buffer enters Insert mode if clicked / changed to via <C-o><C-w> from insert mode buffer
Ref neovim/neovim#7164.

Consider the following script:

    vim -u NONE -i NONE -N -s <(echo -n $':terminal sh\n\C-\\\C-n\C-wpi\C-o\C-wp')

After running it Vim enters Insert mode in a terminal:

insert mode in terminal buffer

. In this mode buffer is not updated and trying to type anything results in “E21: Cannot make changes, 'modifiable' is off”.

Same thing if you replace trailing `<C-o><C-w>p` with a click into the terminal buffer, first setting `mouse=a`, of course.

### PR DESCRIPTION
**Pull request by blueyed**
- vim-patch:8.0.0947: entering terminal using C-O C-W C-W goes to Insert mode

  Problem:    When in Insert mode and using CTRL-O CTRL-W CTRL-W to move to a
              termainal window, get in a weird Insert mode.
  Solution:   Don't go to Insert mode in a terminal window. (closes vim/vim#1977)
  https://github.com/vim/vim/commit/6fe15bbc87cb996912fe3c2c4068e356071ac516

### CODE REVIEW

**Comment by justinmk** [comment]
NA patches can just be noted as a comment in https://github.com/neovim/neovim/pull/10115

**Comment by blueyed** [comment]
Ah, I see now.
So vim-patch.sh finds those then based on the commit, when the PR is merged?

Then vim-patch.sh should probably check the WIP PR already?

**Comment by justinmk** [comment]
> So vim-patch.sh finds those then based on the commit, when the PR is merged?

yes

> Then vim-patch.sh should probably check the WIP PR already?

Too complicated. How would it know which comments are "correct"? That must be decided by a human (when I or someone else puts the NA patches in a commit message).

**Comment by blueyed** [comment]
Ok.

As for 8.0.0947: do you agree that it does not apply?

**Comment by justinmk** [comment]
yes, all `FEAT_TERMINAL` patches can be considered N/A by default. If we ever want to consult Vim for terminal features we will do that intentionally.

**Pull request closed without merging**
