### PR TITLE
[RFC] vim-patch: 3 runtime commits

### PR DESCRIPTION
**Pull request by nicdumz**
Oldest 3 runtime/... commits, for #4067

Please note my comment for the first commit:

```
- runtime/syntax/vim.vim that seems to have already been
  applied/autogenerated without the has(...) tests
```

### CODE REVIEW

**Comment by Pyrohh** [comment]
Thanks @nicdumz.

**Comment by nicdumz** [comment]
Thanks!

@Pyrohh a suggestion here: would it make sense to remove the dates and version numbers in those files? AFAICT these only create more potential for merge conflicts, and I can see little value to those.

**Comment by Pyrohh** [comment]
@nicdumz Do you mean the help docs specifically, or all the runtime files? I'm not sure that's a good idea since it gives, at a glance, a general idea of how outdated a file is compared to Vim. Then again, due to the (out of order) way that some runtime patches are merged, the date itself might be misleading.

cc @justinmk, who merges a lot of runtime patches

**Comment by justinmk** [comment]
We could remove the dates if `scripts/vim-patch.sh` is updated to remove those lines from the patch it generates--then we won't get conflicts when the patch is applied.

There's a big list of things we can do to make merging patches easier (especially runtime patches), that could be automated.

**Comment by fwalch** [comment]
> There's a big list of things we can do to make merging patches easier (especially runtime patches), that could be automated.

@justinmk Well, write it up somewhere :wink:

**Comment by justinmk** [comment]
@fwalch Yeah, I've been meaning to just do it :) But people keep sending things to review... :sweat_smile:

**Comment by nicdumz** [comment]
@Pyrohh @justinmk I meant the 'Version' and 'Last change' lines, e.g. https://github.com/neovim/neovim/blob/97ed0e8dd3b26d0d36ae24aacecef4c54ffadc0b/runtime/syntax/tags.vim#L3-L4

I, for one, don't think that a version number is (ever) useful.

I sort of understand the idea of 'how outdated is this file', but in a modern world I think people that care about bleeding edge should know how to use git/github to figure out the last changes to a file: come to the repository, open the file, look at commit history. I think hackers that are advanced enough to go dig into vim runtime files very likely know how to do this, don't you think?

Anyways, if you must keep a last change data, then perhaps a year is enough? The thing is, it doesn't 
make sense to spend time merging these lines, or wondering which year/date should be kept.

Just my 2c. It doesn't take _that much_ to merge those things or take the max() of both versions :-)

**Comment by justinmk** [comment]
I understand what you meant. My comment still applies

**Pull request merged**
