### PR TITLE
[RFC] version.c: mark NA patches

### PR DESCRIPTION
**Pull request by Shougo**
I have updated to version.c to 7.4.2107.
Please review the change.

NA patches

1601: Filelist, Makefile
1602: info files
1609: Filelist
1610: if_ole, directX
1611: FEAT_VERTSPLIT
1612, 1613: small feature
1615: tiny feature
1616-1618, 1621-1628, 1631, 1635: channel fix
1632, 1633: Makefile fix
1636: getln.c
1646: Python eval
1651: MS-DOS
1655: remote_expr() fix
1657, 1659, 1661, 1662, 1665-1669, 1680: channel
1672, 1674: dvorak plugin
1678: if_mzch
1683: dosinst.c
1684: README
1687, 1717, 1722: channel
1688: if_mzch
1689: if_ruby
1690: ifdef
1693: if_perl
1694: Win32 GUI
1698: Makefile
1705: guifont in Windows
1706: __ARGS
1709: ifdef
1713: GTK GUI
1721: vimtbar plugin
1724: tabline with GUI
1725: fix for ANSI C
1726: compiler warning for ex_smile
1729, 1746: if_perl
1733: Makefile
1736, 1743, 1744, 1747: if_python
1737: UNUSED
1745: README
1749: GTK
1756: dll path
1760: compiler warnings
1764: job
1766: INSTALL_pc.txt
1767: configure
1770: true color
1771: ifdef
1772, 1775: Makefile
1773: compiler warnings
1774, 1778: true color
1776: term.c
1777: channel
1784: true color
1786: term.c
1787, 1789-1791: channel
1788: NSIS support
1794: Win32 GUI
1795-1798: term.c
1800: ifdef
1801: Makefile
1803: GTK3
1807, 1810, 1811, 1814, 1817, 1822, 1824-1829: channel
1819: Compiler warning
1830: os_mswin.c
1843: if_python
1845: channel
1846: term.c
1848: if_perl
1849, 1850, 1853, 1855-1859: channel
1852: GUI test
1854: termguicolors
1860: timer
1863: if_xxx
1864: if_python
1865: eval.c leak
1869: if_perl
1870: if_mzch
1872: if_perl
1873: timer in GUI
1874: Win32
1877-1880: channel
1883: ViVim, gui_mac
1885: MinGW
1886, 1887: channel
1890: GUI
1891: channel
1892, 1894: balloon
1899: GUI_GTK
1901: GUI_Win32
1902, 1906: channel
1908: NetBeans
1915: gui_menu
1916: test_channel
1917-1921: viminfo
1922: if_ruby
1924: function(void)
1925, 1926, 1931-1933, 1938, 1939, 1943: viminfo
1927: if_mzch
1929: if_ruby
1930: ifdef
1934: Makefile
1935: GUI
1942: termguicolors
1944: Make_MSVC
1946: Filelist
1947: viminfo
1951: Makefile, if_ruby
1957, 1958: if_perl
1959, 1965: channel
1963: Win32 cygpty
1965, 1969: channel
1974: GUI
1982, 1987, 1988: viminfo
1983: Filelist Makefile ifdef protocol
1985: VMS build filename_upper_camel
1995: GUI
1998: channel
2001: ifdef
2003, 2004: cursor flicker in GUI
2016: Make_cyg
2020: ifdef
2025: GUI_GTK
2026: channel
2027: ifdef
2030, 2032, 2034: Make cygwin MinGW
2035: ACL support
2037, 2038: small build
2039-2041: channel
2042: GUI_GTK
2045: channel
2048: legacy
2052, 2053: Makefile
2054: ifdef
2055, 2057, 2063: eval.c refactoring
2056: prototype
2059, 2060: Makefile
2070: spell.h
2078: term.c
2079: test_netbeans
2089, 2092: GUI
2091: term.c
2102: GUI tiny
2105: configure

Included
1732: auto completion folds

### CODE REVIEW

**Comment by justinmk** [comment]
More NA:

```
1005
1010
```

**Comment by Shougo** [comment]
Thanks.  I have updated it to 7.4.1799.

**Comment by Shougo** [comment]
I have updated it to 7.4.1830.

**Comment by jamessan** [comment]
1039 looks like it should be NA too.  Neovim only has one build type.

**Comment by Shougo** [comment]
> 1039 looks like it should be NA too. Neovim only has one build type.

Thanks.  I have added 1039 and 1073.

**Comment by jamessan** [comment]
We should probably exclude 7.4.1058

    Problem:    It is not possible to test code that is only reached when memory
                allocation fails.
    Solution:   Add the alloc_fail() function.  Try it out with :vimgrep.

and 7.4.1073 too.

    Problem:    Alloc_id depends on numbers, may use the same one twice.  It's not
                clear from the number what it's for.
    Solution:   Use an enum.  Add a function to lookup the enum value from the
                name.

**Comment by Shougo** [comment]
@jamessan Thanks.  I have added.
I have updated it to 7.4.1848.

**Comment by jamessan** [comment]
1079 is also related to `alloc_fail()`.

**Comment by Shougo** [comment]
Thank you.  I have updated it.

**Comment by Shougo** [comment]
I have updated it to 7.4.1944.

**Comment by Shougo** [comment]
I have updated it to 7.4.1952.

**Comment by Shougo** [comment]
I have update it to 7.4.1967.

**Comment by Shougo** [comment]
I have updated it to 7.4.1989.

**Comment by KillTheMule** [comment]
You can makr 1672 and 1674 as NA as well, see https://github.com/neovim/neovim/issues/5040#issuecomment-232152595.

**Comment by Shougo** [comment]
Yes, it should be.  Please wait.

**Comment by Shougo** [comment]
I have updated it to 7.4.2033

**Comment by Shougo** [comment]
I have updated it to 7.4.2092

**Comment by Shougo** [comment]
I have updated it to 7.4.2107.

2055, 2057, 2063: eval.c refactoring  #5081

**Comment by KillTheMule** [comment]
We're running low on vim-patches to port for potential contributors (you know, those that come last are usually the hardest), so I'd be in favor of merging this. If it's too much, it could easily be splitted, to, say 1800 or whatnot.

**Comment by justinmk** [comment]
Working on this now

**Comment by justinmk** [comment]
patch:7.4.1456 should be NA, see #5113

**Comment by KillTheMule** [comment]
7.4.1273 as well, see https://github.com/neovim/neovim/pull/5093, thanks @simonweil

**Comment by Shougo** [comment]
Thanks

**Pull request merged**
