### PR TITLE
[RFC] Find libintl in Windows

### PR DESCRIPTION
**Pull request by sethjackson**
Cherry picked from #810. From equalsraf@a663ad5.

### CODE REVIEW

**Comment by equalsraf** [comment]
FWIW the situation on libintl is not clear. At the moment #810 builds without libintl (but it probably shouldnt - #2837). So this has not been tested in a while.

**Comment by equalsraf** [comment]
@justinmk some of the changes in this this no longer makes sense afterchanges in #810

**Comment by sethjackson** [comment]
@equalsraf should I just close this then?

**Comment by equalsraf** [comment]
yes please

**Pull request closed without merging**
