### PR TITLE
vim-patch:9.1.{0120,0126,0127): add getregion() function

### LINKED ISSUE #16843: lua function to get current visual selection
### Feature already in Vim?

no

### Feature description

wouldn't it be great if there was a lua api function that gives you the current visually selected text?

### PR DESCRIPTION
**Pull request by zeertzjq**
Close #16843
Close #21115

#### vim-patch:9.1.0120: hard to get visual region using Vim script

Problem:  hard to get visual region using Vim script
Solution: Add getregion() Vim script function
          (Shougo Matsushita, Jakub Łuczyński)

closes: vim/vim#13998
closes: vim/vim#11579

https://github.com/vim/vim/commit/3f905ab3c4f66562f4a224bf00f49d98a0b0da91

Cherry-pick changes from patch 9.1.0122, with :echom instead of :echow.

Co-authored-by: Shougo Matsushita <Shougo.Matsu@gmail.com>
Co-authored-by: Jakub Łuczyński <doubleloop@o2.pl>

#### vim-patch:9.1.0126: Internal error when using upper-case mark in getregion()

Problem:  Internal error when passing mark in another buffer to
          getregion().
Solution: Don't allow marks in another buffer (zeertzjq)

closes: vim/vim#14076

Internal error when passing mark in another buffer to getregion()

https://github.com/vim/vim/commit/421b597470c118871c7081de00dd065e0e000b7e

#### vim-patch:9.1.0127: Naming a non-pointer variable "oap" is strange

Problem:  Naming a non-pointer variable "oap" is strange.
Solution: Rename it to "oa". Also prevent using freed memory in case of
          memory allocation failure. (zeertzjq)

closes: vim/vim#14075

https://github.com/vim/vim/commit/5e3674b42da10b7e7c72d1f20f9a15379af1b60a

### CODE REVIEW

**Comment by clason** [comment]
(Pity.)

**Comment by justinmk** [comment]
> Does (can) this replace `vim.region`?

If it can't, why are we adding this? There's no point in adding duplicate APIs.

**Comment by zeertzjq** [comment]
Vimscript functions can have dynamic argument types, and it's easy to extend it to accept lists later.

**Comment by zeertzjq** [comment]
Previous discussion: #21115

**Comment by clason** [comment]
Also, `vim.region` is broken, partly _because_ it is in Lua. Having a C API that works with Vim's internal cell (and especially multibyte) handling will avoid a lot of painful conversion and adjustment across the API boundary due to incompatible (or at least different) representation.

**Comment by zeertzjq** [comment]
`vim.region()` doesn't actually get text. It only gets positions and caller needs to get the text itself.

**Comment by Shougo** [comment]
> For now, it only takes strings for arguments, so no.

I will extend `getregion()` later.
It is basic feature now.  Because it is hard review...

**Comment by Shougo** [comment]
This.

https://github.com/vim/vim/pull/14090

**Comment by justinmk** [comment]
> Also, `vim.region` is broken, partly _because_ it is in Lua. Having a C API that works with Vim's internal cell ...

Ok. Let's plan to completely remove `vim.region` then.

**Pull request merged**
