### PR TITLE
feat(docs): fix misquote

### PR DESCRIPTION
**Pull request by Monster0506**

### CODE REVIEW

**Comment by justinmk** [comment]
@marvim never said that

**Comment by Monster0506** [comment]
> @marvim never said that

This change was originally created in [120797c](https://github.com/neovim/neovim/commit/120797cf87a55da00fd1b9c0b9fda0a0dfcb0cc8). We could revert this to the previous phrase, "A satirical way to say this:", if you prefer.

**Comment by dundargoc** [comment]
It's a joke quote. Don't think too much about it lol.

**Comment by justinmk** [comment]
The change was intentional and the wording is intentionally Nvim-specific. 

Historical note: @marvim at one point was also a chat bot that bridged IRC to/from gitter. Thus, anythiing said in chat was said by @marvim.

**Pull request closed without merging**
