### PR TITLE
build(install): rescan GLOB files on rebuild

### LINKED ISSUE #16054: make install ignores new files
### Neovim version (nvim -v)

v0.6.0-dev+466-gf19dc0608-dirty

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

NA

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

build from repo

### How to reproduce the issue

```sh
$ git clone https://github.com/neovim/neovim.git
$ cd neovim
$ rm runtime/ftplugin/toml.vim
$ make
$ git restore runtime/ftplugin/toml.vim
$ make clean && make # just to illustrate that this is confusing
$ make && sudo make install
```

### Expected behavior

`runtime/ftplugin/toml.vim` should be installed

### Actual behavior

`runtime/ftplugin/toml.vim` is not installed unless cmake is forced to reconfigure (ex any change in cmake files, removing `build` directory etc)

Typical scenario is when user runs:
```
git pull && make clean && make CMAKE_BUILD_TYPE=Release && sudo make install
```
and there is some file added to runtime on master (ex https://github.com/neovim/neovim/commit/0ba77f2f31c9de42f1e7a8435e6322d3f0a04fa5)

### PR DESCRIPTION
**Pull request by doubleloop**
fixes #16054 for cmake 3.12+

### CODE REVIEW

**Review by justinmk — APPROVED** [review]
Unless anyone objects, I'd be in favor of bumping the minimum cmake version to 3.12, it would clean up ~6 other wrapper sections in our cmake definitions. 

@jamessan would this be an issue for packaging?

**Comment by doubleloop** [comment]
> it would clean up ~6 other wrapper sections in our cmake definitions

Found 2: https://github.com/doubleloop/neovim/commit/addc02fe8fb077e4338cad72fa7153b710f43108

Should i update the PR bumping the cmake version and removing the wrappers?

**Comment by doubleloop** [comment]
> There's also a minimum version in ci/before_install.sh

As I understand `.travis.yaml` file should also be updated with propper `CMAKE_URL`, one question, previously i386 build was used but for 3.12 I see only x86_64 builts in https://cmake.org/files/v3.12/ , is it a problem for `gcc-32bit` job?

**Comment by justinmk** [comment]
> EDIT: actually, is travis still in use or is .`travis.yaml` just some legacy file?

Not used. Still kept for reference until we migrate the last 20% to GHA.

**Review by justinmk — APPROVED** [review]

**Comment by doubleloop** [comment]
As for arguments to remove globs completely:

>The CONFIGURE_DEPENDS flag may not work reliably on all generators

 it works for makefiles and for ninja, do we really care for other generators?

> Even if CONFIGURE_DEPENDS works reliably, there is still a cost to perform the check on every rebuild

is this really an issue?


I have no objections to remove globs but this seems bigger task and I do not want to spend time on this. Meanwhile since globs are already being used, `CONFIGURE_DEPENDS` will increase quality of life for current implementation :) Do you want me to do anything more with this PR?

**Comment by jamessan** [comment]
> Meanwhile since globs are already being used, `CONFIGURE_DEPENDS` will increase quality of life for current implementatio

Agreed, thank you.

> Do you want me to do anything more with this PR?

The runtime files aren't the only ones that have this problem, although it probably is affected by new files more often than new C files.

Let's merge this for now, since it's a net improvement, but it would be good to have similar changes made for src/nvim/.

**Pull request merged**
