### PR TITLE
update python syntax

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by splinterofchaos** [comment]
Audi deprecated exceptions not in Python 2, but we still support? If not, this lgtm if version 3.3 is the one in popular circulation.

Before merging, I think the commits should be squashed, but it is easier for reviewing as is.

**Comment by Pyrohh** [comment]
@e-kwsm Have you verified that these aren't already included in Vim runtime patches?

**Comment by e-kwsm** [comment]
@Pyrohh I am sorry not to have verified, but they are not included in vim-patch:7.4.738 nor pull requests.

**Comment by Pyrohh** [comment]
> I am sorry not to have verified

No problem, I don't think it's clearly documented to do that.

> but they are not included in vim-patch:7.4.738 nor pull requests.

:+1:

**Comment by blueyed** [comment]
I think this should be sent to the maintainer of the file, and merged if it gets accepted (and will end up in Vim's runtime).

**Comment by e-kwsm** [comment]
I'm not so familiar with Google code and how to pull request; I suggested a patch.
BTW, is it better to pull request to only vim in such a case?

**Comment by blueyed** [comment]
> I suggested a patch

Found it at https://code.google.com/p/vim/issues/detail?id=382.

> is it better to pull request to only vim in such a case?

The official procedure for runtime files is that you would send your patch / update / link to some public git repo/branch etc. to the maintainer (mentioned at the top of the file).

For the Python files this has recently changed:
https://groups.google.com/d/msg/vim_dev/WWZq1Lw8bvo/x4mMd61XAFwJ

I'll mail/notify Zvezdan about it.

**Comment by zvezdan** [comment]
I just sent a patch to vim-dev with the updates to exceptions as well as some built-ins and doc URLs for the Python syntax file in Vim. Thanks for contacting me Daniel.
If you want you can sync your copy from the Vim repo once my patch is committed.

**Comment by e-kwsm** [comment]
@blueyed and @zvezdan I see. Thank you for your kindness.

**Comment by justinmk** [comment]
Please send a runtime update (use the `./scripts/vim-patch.sh -l` to see which updates are missing).

**Pull request closed without merging**
