### PR TITLE
[RFC] Fix invalid :echo output and add tests for :echo

### PR DESCRIPTION
**Pull request by ZyX-I**
I have not found existing tests which at least check for recent `...@N` addition (searched for `...@` in `test/functional`), so decided to port `string()` tests since they in any case share a great amount of code.

“Copy” commit is there because git does not do rename/copy tracking, used to do this previously for renaming.

### CODE REVIEW

**Comment by ZyX-I** [comment]
The error e.g. in QB is

```
19:54:08,941 INFO  - not ok 892 - :echo used to represent funcrefs dumps references to script functions
19:54:08,941 INFO  - # test/functional/ex_cmds/echo_spec.lua @ 139
19:54:08,941 INFO  - # Failure message: test/functional/ex_cmds/echo_spec.lua:140: Expected objects to be the same.
19:54:08,941 INFO  - # Passed in:
19:54:08,941 INFO  - # (string) '<SNR>2_Test2'
19:54:08,941 INFO  - # Expected:
19:54:08,941 INFO  - # (string) '<SNR>1_Test2'
19:54:08,941 INFO  - # stack traceback:
19:54:08,941 INFO  - #     test/functional/ex_cmds/echo_spec.lua:140: in function <test/functional/ex_cmds/echo_spec.lua:139>
19:54:08,941 INFO  - #
19:54:08,941 INFO  - # test/functional/ex_cmds/echo_spec.lua @ 143: :echo used to represent funcrefs dumps partials with self referencing a partial
```

, same in travis. It is not surprising given that I use `source()` in `before_each`, what *is* surprising is that tests were passing locally and in some travis and QB builds. Looks like linux `tmpname` in test/helpers.lua has a bug.

**Comment by ZyX-I** [comment]
Not `tmpname`, but something strange is going on: with

```Patch
diff --git a/test/functional/ex_cmds/echo_spec.lua b/test/functional/ex_cmds/echo_spec.lua
index 4936c5af8..0998dc68e 100644
--- a/test/functional/ex_cmds/echo_spec.lua
+++ b/test/functional/ex_cmds/echo_spec.lua
@@ -15,6 +15,7 @@ local redir_exec = helpers.redir_exec
 describe(':echo', function()
   before_each(function()
     clear()
+    print('HERE')
     source([[
       function String(s)
         return execute('echo a:s')[1:]
@@ -113,6 +114,7 @@ describe(':echo', function()
 
   describe('used to represent funcrefs', function()
     before_each(function()
+      print('THERE')
       source([[
         function Test1()
         endfunction
@@ -138,6 +140,7 @@ describe(':echo', function()
 
     it('dumps references to script functions', function()
       eq('<SNR>1_Test2', eval('String(Test2_f)'))
+      print(funcs.execute('scriptnames'))
     end)
 
     it('dumps partials with self referencing a partial', function()
diff --git a/test/functional/helpers.lua b/test/functional/helpers.lua
index 4a170d993..b46cb401e 100644
--- a/test/functional/helpers.lua
+++ b/test/functional/helpers.lua
@@ -339,6 +339,7 @@ end
 
 local function source(code)
   local fname = tmpname()
+  print(fname)
   write_file(fname, code)
   nvim_command('source '..fname)
   os.remove(fname)
```

I get

```
HERE
/home/zyx/a.a/Proj/c/neovim/Xtest-tmpdir/nvim-test-lua-1
THERE
/home/zyx/a.a/Proj/c/neovim/Xtest-tmpdir/nvim-test-lua-2
[ RUN      ] :echo used to represent funcrefs dumps references to script functions:
  1: ~/a.a/Proj/c/neovim/Xtest-tmpdir/nvim-test-lua-1
```

Where did `nvim-test-lua-2` disappear?

**Comment by ZyX-I** [comment]
I mean, it is not in `scriptnames` in my test.

**Comment by ZyX-I** [comment]
It appears that `do_source` compares device number and inodes, filesystems I, QB and travis are using are reusing the inodes in our situation (dunno what QB and travis are using, I am using XFS) and as a result this effectively wastes our effort to have separate files for each `source()` call.

**Comment by ZyX-I** [comment]
QB is again only failing to build in one place with what looks like an unrelated error:

```
08:26:17,418 INFO  - cd /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/src/nvim && /usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -Dnvim_test_EXPORTS -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -fPIC -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/config -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src -isystem /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps/usr/include -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/src/nvim/auto -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/build/Release/include -I/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps/usr/include/luajit-2.0 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -Werror ...
08:26:17,725 WARN  - In file included from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:6:0,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/map.h:9,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/buffer_defs.h:40,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/normal.h:6,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/ex_cmds_defs.h:8,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/ex_eval.h:5,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/globals.h:8,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/vim.h:302,
08:26:17,725 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/api/private/handle.h:4,
08:26:17,726 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/buffer.c:26:
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h: In function ‘kb_del_itr_bufhl’:
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:238:28: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,726 WARN  - kp = __KB_KEY(key_t, x)[i]; \
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,726 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,726 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,726 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:239:23: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,726 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 1); \
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,726 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,726 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,726 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:243:28: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,726 WARN  - kp = __KB_KEY(key_t, x)[i]; \
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,726 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,726 WARN  - ^
08:26:17,726 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,726 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,727 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:244:23: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,727 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 2); \
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,727 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,727 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,727 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:238:28: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,727 WARN  - kp = __KB_KEY(key_t, x)[i]; \
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,727 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,727 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,727 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:239:23: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,727 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 1); \
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,727 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,727 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,727 WARN  - ^
08:26:17,727 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,727 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,727 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:243:28: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,728 WARN  - kp = __KB_KEY(key_t, x)[i]; \
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,728 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,728 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,728 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:244:23: error: array subscript is below array bounds [-Werror=array-bounds]
08:26:17,728 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 2); \
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
08:26:17,728 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
08:26:17,728 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
08:26:17,728 WARN  - ^
08:26:17,728 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
08:26:17,728 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10)
08:26:17,728 WARN  - ^
08:26:18,054 WARN  - cc1: all warnings being treated as errors
08:26:18,057 WARN  - make[3]: *** [src/nvim/CMakeFiles/nvim-test.dir/buffer.c.o] Error 1
```

AppVeyor succeeded. Travis looks like it is going to succeed, if it does PR should be considered ready.

**Comment by justinmk** [comment]
The QB kbtree failures are blocked on https://github.com/neovim/neovim/pull/6931, this was a result of merging the kbtree PR.

**Pull request merged**
