### PR TITLE
[WIP] quickfix: add option to ignore lines whose %f isn't an existing file

### PR DESCRIPTION
**Pull request by sugrob9000**
Sometimes errorformats misfire.

For example, when a command fails, make might say something like `make: *** [Makefile:76: run] Error 1`. Most likely I don't want to autojump to my makefile - but not adding an errorformat for this message doesn't help, since it matches file:line:message anyway, the filename being `make: *** [Makefile`.

Also, sometimes the compiler is able to display the filename and sometimes not. Say, OpenGL drivers accept GLSL shader code to compile from in-memory strings, but some support supplying filenames, and in the absence of a filename will just show an internal index in its place. Sure, this can also be solved by two separate errorformats, but the proposed change seems like a neat catch-all solution for these cases - at least for me.

I've updated the docs accordingly, but not the tests so far.

### CODE REVIEW

**Comment by clason** [comment]
@mergify rebase

**Comment by jamessan** [comment]
I don't think you wanted to merge release-0.5 in to your PR, @Crowbarous.  I'd suggest resetting back to the original commit and force pushing that.

**Comment by clason** [comment]
It's usually better to rebase (on master!) rather than merge that into a PR.

**Comment by justinmk** [comment]
For reference since the merge is messed up: https://github.com/neovim/neovim/commit/ab43bd2



```
						*'qfonlyexisting'* *'qfoe'*
'qfonlyexisting' 'qfoe'	boolean (default off)
			global
	When this option is set, quickfix ignores the lines of compiler output
	which have matched some 'errorformat' entry but whose filename (%f) is
	not readable. Useful if you have lines on which errorformats misfire
	and open garbage buffers.
```

```diff
diff --git a/src/nvim/quickfix.c b/src/nvim/quickfix.c
index a625c09f78b4..c6b4efe14a93 100644
--- a/src/nvim/quickfix.c
+++ b/src/nvim/quickfix.c
@@ -1293,13 +1293,15 @@ static int qf_parse_fmt_f(regmatch_T *rmp,
   expand_env(rmp->startp[midx], fields->namebuf, CMDBUFFSIZE);
   *rmp->endp[midx] = c;
 
-  // For separate filename patterns (%O, %P and %Q), the specified file
-  // should exist.
-  if (vim_strchr((char_u *)"OPQ", prefix) != NULL
-      && !os_path_exists(fields->namebuf)) {
+  // Cases in which the file must exist:
+  // - when the appropriate option is set
+  // - for separate filename patterns (%O, %P and %Q)
+  bool must_exist = p_qfonlyexisting
+                 || (vim_strchr((char_u *)"OPQ", prefix) != NULL);
+
+  if (must_exist && !os_path_exists(fields->namebuf)) {
     return QF_FAIL;
   }
-
   return QF_OK;
 }
```

A special-case option is almost never the right interface . However, maybe this condition you've added makes sense to _always_ apply? 

Send your patch to https://github.com/vim/vim , Bram likely can decide quickly whether this is needed.

**Pull request closed without merging**
