### PR TITLE
[RFC] tests: Migrate legacy test 55.

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by lucc** [comment]
ref for a better overview: #1286

**Comment by lucc** [comment]
After a patch was included in master one part of this test is making trouble. Does anyone understand locked variables and the failing test block in this test?

**Comment by lucc** [comment]
I managed to fix it (and include another patch from master). But I don't know the problem and why I had to uncomment the line in question (see last commit = 77af43c, its actually a very small change)

**Comment by lucc** [comment]
The TODO commit moved to 5013e32.

**Comment by KillTheMule** [comment]
LGTM :+1:  I'm going to have nightmares of `eval.c` for weeks coming...

You might want to merge https://github.com/KillTheMule/neovim/commit/c1d608f9a81884523efa8783ba896cf617e13e78 and https://github.com/KillTheMule/neovim/commit/579d7ea56944b48372e579c9a8fe8155092b94ca as well. First one fixes the travis failure btw, yay for testlint!

Check  https://github.com/KillTheMule/neovim/commit/ca795f90f6de9b3b909f68d3554f34a92f9aacac for some breakage, automated by `new_test.sh`. Did the usual manual checks as well.

Speaking of manual: What's https://github.com/lucc/neovim/blob/b4848c5d1474d7226e86acf653fba8b249321c93/test/functional/legacy/055_list_and_dict_types_spec.lua#L926 doing in there? I just checked manually that it's the same as before, seeing that it's a pretty involved specific case.

**Comment by justinmk** [comment]
@KillTheMule Hugely useful, thank you! And thanks @lucc.

**Pull request merged**
