### PR TITLE
docs: clarify that nvim_strwidth counts control characters as one cell

### LINKED ISSUE #18801: `nvim_strwidth` does not work correctly with control characters
### Neovim version (nvim -v)

Latest master

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

From source

### How to reproduce the issue

`:lua = vim.api.nvim_strwidth('^G')`, where `^G` is produced by `<C-v><C-g>`

### Expected behavior

2

### Actual behavior

1

### PR DESCRIPTION
**Pull request by zeertzjq**
Close #18801

### CODE REVIEW

**Comment by andmis** [comment]
I understand that `<Tab>` is special, but why can't we count control characters like `^G` accurately?

**Review by justinmk — APPROVED** [review]

**Comment by bfredl** [comment]
@andmis because it depends on context. It could only ever be done "correctly" with a new api function which let's you supply the context.

**Comment by andmis** [comment]
I didn't realize that the way that `^G` is rendered is context-dependent, do you have an example?

**Comment by bfredl** [comment]
Try typing it into a terminal.

**Comment by jamessan** [comment]
> I didn't realize that the way that `^G` is rendered is context-dependent, do you have an example?

`:set display+=uhex`

**Pull request merged**
