### PR TITLE
fix(column): fill 'statuscolumn' clickdefs with evaluated width

### LINKED ISSUE #26890: Assertion `len <= width` failed with `numberwidth = 1`
### Problem

I get crash with `numberwidth = 1` using statuscol.nvim on 0.10 branch. 

```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007fe3066b015f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007fe306662472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fe30664c4b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fe30664c3d5 in __assert_fail_base (fmt=0x7fe3067c0dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x562ff2ad45e0 "len <= width", 
    file=file@entry=0x562ff2af8398 ".../src/nvim/statusline.c", line=line@entry=260, function=function@entry=0x562ff2aabe00 <__PRETTY_FUNCTION__.12> "stl_fill_click_defs") at ./assert/assert.c:92
#5  0x00007fe30665b3a2 in __assert_fail (assertion=assertion@entry=0x562ff2ad45e0 "len <= width", file=file@entry=0x562ff2af8398 ".../src/nvim/statusline.c", line=line@entry=260, 
    function=function@entry=0x562ff2aabe00 <__PRETTY_FUNCTION__.12> "stl_fill_click_defs") at ./assert/assert.c:101
#6  0x0000562ff291e157 in stl_fill_click_defs (click_defs=0x562ff4a6ff40, click_recs=0x562ff4aac9f0, buf=<optimized out>, buf@entry=0x7ffc0b2b1b30 "1 ", width=1, tabline=tabline@entry=false)
    at .../src/nvim/statusline.c:260
#7  0x0000562ff2925dcd in build_statuscol_str (wp=0x562ff4a20be0, lnum=<optimized out>, relnum=<optimized out>, buf=0x7ffc0b2b1b30 "1 ", stcp=0x7ffc0b2b2d30) at .../src/nvim/statusline.c:889
#8  0x0000562ff277e1e1 in draw_statuscol (wp=0x562ff4a20be0, wlv=0x7ffc0b2b2fe0, lnum=1, virtnum=0, stcp=0x7ffc0b2b2d30) at .../src/nvim/drawline.c:579
#9  0x0000562ff2782c87 in win_line (wp=wp@entry=0x562ff4a20be0, lnum=lnum@entry=1, startrow=startrow@entry=0, endrow=13, number_only=number_only@entry=false, spv=0x7ffc0b2b41f0, foldinfo=...)
    at .../src/nvim/drawline.c:1495
#10 0x0000562ff27879b6 in win_update (wp=wp@entry=0x562ff4a20be0) at .../src/nvim/drawscreen.c:2279
#11 0x0000562ff2788cec in update_screen () at .../src/nvim/drawscreen.c:631
#12 0x0000562ff287b4d3 in normal_redraw (s=s@entry=0x7ffc0b2b4320) at .../src/nvim/normal.c:1347
#13 0x0000562ff287d156 in normal_check (state=0x7ffc0b2b4320) at .../src/nvim/normal.c:1443
#14 0x0000562ff291da6a in state_enter (s=0x7ffc0b2b4320) at .../src/nvim/state.c:37
#15 0x0000562ff287ad32 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at .../src/nvim/normal.c:508
#16 0x0000562ff2841248 in main (argc=4, argv=<optimized out>) at .../src/nvim/main.c:637
```

@luukvbaal 

### Steps to reproduce

init.lua:
```lua
local thisInitFile = debug.getinfo(1).source:match('@?(.*)')
local configDir = vim.fs.dirname(thisInitFile)

vim.env['XDG_CONFIG_HOME'] = configDir
vim.env['XDG_DATA_HOME'] = vim.fs.joinpath(configDir, '.xdg/data')
vim.env['XDG_STATE_HOME'] = vim.fs.joinpath(configDir, '.xdg/state')
vim.env['XDG_CACHE_HOME'] = vim.fs.joinpath(configDir, '.xdg/cache')
local stdPathConfig = vim.fn.stdpath('config')

vim.opt.runtimepath:prepend(stdPathConfig)
vim.opt.packpath:prepend(stdPathConfig)

local function gitClone(url, installPath, branch)
  if vim.fn.isdirectory(installPath) ~= 0 then
    return
  end

  local command = {'git', 'clone', '--depth=1', '--', url, installPath}
  if branch then
    table.insert(command, 3, '--branch')
    table.insert(command, 4, branch)
  end
  local sysObj = vim.system(command, {}):wait()
  if sysObj.code ~= 0 then
    error(sysObj.stderr)
  end
  vim.notify(sysObj.stdout)
  vim.notify(sysObj.stderr, vim.log.levels.WARN)
end

local pluginsPath = 'plugins'
vim.fn.mkdir(pluginsPath, 'p')
pluginsPath = vim.uv.fs_realpath(pluginsPath)

local plugins = {
  ['statuscol.nvim'] = {url = 'https://github.com/luukvbaal/statuscol.nvim', branch = '0.10'},
}

for name, repo in pairs(plugins) do
  local installPath = vim.fs.joinpath(pluginsPath, name)
  gitClone(repo.url, installPath, repo.branch)
  vim.opt.runtimepath:append(installPath)
end

require('statuscol').setup({})
vim.wo.number = true
vim.wo.numberwidth = 1
```
```sh
nvim --clean -u init.lua
```

### Expected behavior

No crash

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2035+g88eb0ad14

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Debian Sid

### Terminal name/version

tmux 3.3a-5, kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

from repo

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix #26890

### CODE REVIEW

**Comment by zeertzjq** [comment]
Do you plan to add a test?

**Comment by luukvbaal** [comment]
Regression from #26845, which no longer truncates the evaluated statuscolum string (since the available width is extended instead). So the width returned by `build_stl_str_hl()` may be larger than the current available width. In which case the 'statuscolumn' will be rebuilt anyways, at which point the clickdefs will be filled.

Can add a test later.

**Comment by przepompownia** [comment]
I get no crash with this change (both on repro and real env). Thank you both for fixing and CR.

**Comment by lewis6991** [comment]
Asan failure looks meaningful.

**Comment by luukvbaal** [comment]
Yes, it's why I converted it to draft. Looking into it later.

**Comment by luukvbaal** [comment]
Passing in a `StlClickRecord` but not filling resulted in leaking. Instead of adding a seperate branch for freeing when we don't fill, just pass the evaluated width to the clickdef functions to avoid the assert error.

**Comment by luukvbaal** [comment]
> I get no crash with this change (both on repro and real env). Thank you both for fixing and CR.

Thanks for confirming @przepompownia. I changed the fix however, care to check again?

**Comment by przepompownia** [comment]
> Thanks for confirming @przepompownia. I changed the fix however, care to check again?

Seems to still work on both envs after the change.

**Pull request merged**
