### PR TITLE
[RFC] refactor/single-include: move.h

### PR DESCRIPTION
**Pull request by carloabelli**
#5321

### CODE REVIEW

**Comment by jamessan** [comment]
Just as an FYI, it would be ok to have multiple commits in a single PR.  They're logically related changes, so you could do a few headers file per PR.

**Comment by mhinz** [comment]
@dedmass Considering that your PRs consist of single commits that only change a few lines at max, this is "overkill" for multiple reasons.

It's much easier to handle for everyone (you and the maintainers), if you use just one PR that consists of multiple commits.

There's also a technical issue. Everytime a new PR gets created (or its commits get changed), [our test suite on Travis CI](https://travis-ci.org/neovim/neovim/builds) will start running. Those tests take a while and since we use what Travis CI offers for free, only a few jobs can run at the same time. Now, if you open multiple PRs, for basically the same thing, the test suite will run multiple times as well and it will take an eternity for them to finish. And thus others have to wait for a long time to get feedback from our CI.

Please, put all those commits into one PR. :-)

**Comment by bfredl** [comment]
The work is definitely wanted https://github.com/neovim/neovim/issues/5321#issuecomment-289440798 but indeed one PR for many small changes would be better. Only bigger changes (like needing to separate out `_defs.h` etc) would warrant a separate PR.

**Comment by justinmk** [comment]
This is a fault of my wording in #5321. Though in general I don't want anyone to hesitate to send PRs just because of travis limitations.

**Comment by dedmass** [comment]
My apologies. I am new to all of this. The remainder of my commits will all
be in one PR. Would you like me to try to merge together my other pull
requests or leave them?

**Comment by jamessan** [comment]
> My apologies. I am new to all of this. The remainder of my commits will all
> be in one PR. Would you like me to try to merge together my other pull
> requests or leave them?

Your existing PRs are fine.  There's no need to put all the remaining changes into a single PR either.  We're just trying to reduce the noise.  As @justinmk clarified in #5321:

> Note: Group several such commits in a single pull request, if you can. But not more than ~5.

**Comment by justinmk** [comment]
Merged

**Pull request closed without merging**
