### PR TITLE
tests: re-enable "tab drag in tabline to the left moves tab left"

### PR DESCRIPTION
**Pull request by blueyed**
Bad timing since tsan is flaky currently (but during `make install`).
I just came across this when investigating the above and wanted to see if it is still necessary.

### CODE REVIEW

**Comment by blueyed** [comment]
So this appears to not be necessary anymore it seems.

**Comment by justinmk** [comment]
it's indeterministic. we can try it, but if it still is a problem, fixing it is a very low priority and it should just be ignored again.

**Comment by blueyed** [comment]
Different flaky failure, will merge it then for now:
```
[----------] Running tests from test/functional/autocmd/termclose_spec.lua
[ RUN      ] TermClose event triggers when fast-exiting terminal job stops: 44.63 ms OK
[ RUN      ] TermClose event triggers when long-running terminal job gets stopped: -- Output to stderr:
Vim: Caught deadly signal 'SIGHUP'
Vim: Finished.
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:66 (message):
  functional tests failed with error: SIGPIPE
```

**Comment by bfredl** [comment]
This test was made more robust in #6930, but for some reason I only removed the flakiness guard for a similar tabline test but not for this one.

**Pull request merged**
