### PR TITLE
vim-patch:8.1.{136, 139, 164, 300, 672, 748}

### PR DESCRIPTION
**Pull request by VVKot**
- vim-patch:8.1.0136: Lua tests don't cover new features
- vim-patch:8.1.0139: Lua tests fail on some platforms
- vim-patch:8.1.0164: luaeval('vim.buffer().name') returns an error
- vim-patch:8.1.0300: the old window title might be freed twice
- vim-patch:8.1.0672: the Lua interface doesn't know about v:null
- vim-patch:8.1.0748: using sprintf() instead of semsg()

First five patches are N/A - they are for `if_lua` and Vim's OS-specific things. Porting last one.

### CODE REVIEW

**Comment by zeertzjq** [comment]
I think empty commits need to be squashed into a non-empty commit.

**Comment by VVKot** [comment]
Ah you're right, I haven't done that for some time, forgot everything. :)

**Comment by janlazo** [comment]
Remind me why these are N/A even though `+lua` wasn't fully ported. Lua patches for `src/if_lua.c` are N/A but no decision for `test_lua.vim`.

**Comment by VVKot** [comment]
@janlazo I assumed that it does not make sense `test_lua.vim` when `if_lua` is not available - correct me if I'm wrong though.

**Comment by bfredl** [comment]
We do share a subset of `if_lua` functionality, but all of these tests here seem to assume `vim.list` `vim.buffer` etc which we do not have, so marking these N/A should be fine I think.

**Comment by VVKot** [comment]
@janlazo how does that sound? ^

**Comment by zeertzjq** [comment]
Patches like 8.1.0132 and 8.1.0134 have already been marked as N/A, so I think it indeed doesn't make sense to port these Lua tests.

**Pull request merged**
