### PR TITLE
refactor(options): use os_win/os_buf for local options

### PR DESCRIPTION
**Pull request by zeertzjq**
Conversely, don't use them for global options.

### CODE REVIEW

**Comment by zeertzjq** [comment]
It's not currently clear whether `curwin` or `os_win` should be used for these three options:
- `'helpheight'`
- `'winheight'`
- `'winwidth'`

As these three are global options.

**Comment by famiu** [comment]
`:help 'winheight'` and `:help 'winwidth'` talk about the current window, so perhaps `curwin` should be used?

**Comment by famiu** [comment]
`'helpheight'` is a complex case, imo it should use `os_win`.

One thing worth nothing, `did_set_option` does set `os_win` to `curwin` (and `os_buf` to `curbuf`), so in most cases they're probably going to be the same value. In fact I can't think of many cases where it'd change.

**Comment by zeertzjq** [comment]
Considering the `ONE_WINDOW` condition, I'm going to use `curwin` for all three, as `ONE_WINDOW` is for current tabpage.

**Pull request merged**
