### PR TITLE
runtime: Fix man.vim's searching function

### PR DESCRIPTION
**Pull request by sophec**
On my Debian and macOS systems, I never had any issue with man.vim (using `:Man` and <kbd>K</kbd> both worked great). However, for the last year or so on Void (which uses mandoc for manual pages), it has been working terribly. I have `b:default_man_sects='2,3'` set for C/C++ buffers, but when I do <kbd>K</kbd> on `write`, I get write(1). Now, I figured I should just do `:Man 2 write` to fix this. Once again, I got write(1). Then, I decided to do `:Man /usr/share/man/man2/write.2`. This *also* got me write(1). Another example: I could not access strlen(3) (or any string functions listed in string(3)), as it would always bring me to strlen(3). After digging into it, I discovered that there are a few issues at play here:

1. When searching, man.vim was using `man -w -S 2,3 write`, which does not work with mandoc
2. When searching for a specific section (i.e. when doing `:Man 2 write`), man.vim was still using `-S 2`, which still doesn't work with mandoc
3. When multiple results were returned by `-w` (as with mandoc), man.vim was simply choosing the first one, which doesn't make sense in a few cases:
    - When doing `man -w strlen`, mandoc will list both `string.3` and `strlen.3` in that order, which means that the first one would always be string.3, which doesn't make sense to choose
    - When searching for `man -w write`, mandoc will list both `write.1` and `write.2` in that order, so man.vim would choose write(1) every single time

With this patch, I am aiming to fix this by searching and then checking for a matching name and/or a matching section. This way, if a matching name is not found (i.e. if you search for `man -w clock_gettime` you will only get `clock_getres.2` which is the correct page), it will check to find the first one in the same section. If a matching name *is* found, such as in the strlen() and write() cases, it will then check to make sure there is one in the correct section (if a section was supplied).

Also, since -S (and -s) on mandoc do not support a comma-separated list of sections, I have changed how `b:man_default_sects` is used. It will be split on commas and then each section will be searched in order. This is a little slow at the time of this writing, but can be made faster by looping through the sections and stopping when a match is found rather than just using `map()` to check all sections. This is a fairly simple fix.

At the moment this patch works on Void, though it has some issues on Debian that I am still in the process of working out. I will update and request review when it is ready.

### CODE REVIEW

**Comment by willeccles** [comment]
It now works on both mandoc and man-db systems, and should work on others as well provided they have a functioning `-w` flag. I have also addressed the inefficiency I mentioned in the original PR message, so now the command is only run as much as necessary to find the right man page. This should be ready to merge now.

**Comment by jamessan** [comment]
Cc @nhooyr

**Comment by nhooyr** [comment]
Will take a look this weekend!

**Comment by willeccles** [comment]
I don't have a clue why the macOS build is failing, but I can test on macOS this evening. I didn't touch anything to cause nvim itself to fail to build, so I am assuming it's an unrelated issue.

**Comment by nhooyr** [comment]
The man.vim tests could have failed on macOS but it looks like it was indeed an unrelated homebrew error.

**Comment by willeccles** [comment]
As far as I am aware, the tests should not have failed on macOS. The only man flag it makes use of now is -w, which is supported on macOS. I have not run any tests (forgot to test on macOS this weekend), so I have no way to be certain.

**Comment by nhooyr** [comment]
> As far as I am aware, the tests should not have failed on macOS.

Exactly, they *did* not!

**Comment by willeccles** [comment]
I'll see if I can trigger the CI to rerun.

**Comment by willeccles** [comment]
macOS seems to have worked this time. No clue what happened to homebrew last time, but it appears to have been a fluke.

**Comment by willeccles** [comment]
Once again it seems the only issue is an unrelated CI failure. In any case, @nhooyr how do you feel about the patch itself? I don't know if you've tried it or looked at the source. I am not particularly familiar with vim script, but I tried to make it decent. Let me know if anything seems poor.

**Comment by nhooyr** [comment]
> Once again it seems the only issue is an unrelated CI failure. In any case, @nhooyr how do you feel about the patch itself? I don't know if you've tried it or looked at the source. I am not particularly familiar with vim script, but I tried to make it decent. Let me know if anything seems poor.

My apologies, I tried to get to it last weekend. Was hoping to play with void linux and understand the differences but I wasn't able to make the time.

My concern is that it's a large change and `man.vim` has been very brittle to such changes in the past. Small changes often cause breakage on a platform here or there. I think we might need to spend some time documenting the precise behaviour of `man` on each platform we support. Although I think there's really only `man-db` and `mandoc`. Maybe I'm just being paranoid but I want to go through each change we've made to the plugin in the past first to make sure we're not breaking anything here.

I checked and it's been nearly 5 years since I wrote the plugin. It's really hard to keep all the random minor changes and incompatibilities since then in my head. It'd also be nice at some point to abstract the common behaviour behind a vimscript API (or lua).

I will say I greatly appreciate your thorough comments & PR description!

**Comment by willeccles** [comment]
From my searching, it looks like the only thing that is different (and slightly consistent) between implementations is the -w flag. Madoc will list all matching pages, while man-db will go through its search and return only the path of the file it would use. The thing man.vim had originally that was inconsistent was the behavior of -S/s, which are not even supported on some implementations, and mandoc's are completely different from man-db.

Rather than trying to use the options which are poorly-supported, my goal with the patch was to make it much more robust by using only the -w flag which is the only one I could find that was the same everywhere (or nearly the same, which is why it searches through the results if there is more than one).

Of course, this is hard to do in general, since the only thing POSIX requires for man is -k, if I remember correctly, so it's pretty difficult to make this plugin work without reinventing the wheel and implementing man page search manually (which I, for one, don't find to be an attractive option, to say the least).

> Was hoping to play with void linux

As far as I know, mandoc is used on both void and OpenBSD (which was the one called out in the comments in man.vim previously), which is why it took me so long to figure out that man.vim was at fault for not finding the man pages properly rather than my system itself. Unrelated: void is quite nice, and I highly recommend it :)

**Comment by willeccles** [comment]
Can anyone force the CI to rerun? It would be nice if this would pass. I have been using this patch for going on 2 weeks now and it has been functional on the systems I've tested it on, and pending @nhooyr's approval I think is ready to merge as long as the CI can be figured out.

**Comment by janlazo** [comment]
Porting https://github.com/vim/vim/commit/39536dd557e847e80572044c2be319db5886abe3 and then extending it to check for more platforms may help here.

**Comment by willeccles** [comment]
> 
> 
> Porting [vim/vim@39536dd](https://github.com/vim/vim/commit/39536dd557e847e80572044c2be319db5886abe3) and then extending it to check for more platforms may help here.

While I agree that it appears to make sense on the surface, I don't think this would help much here. It would require maintaining a map of all known systems and the type of man system they use. At first this would be reasonably maintainable, but it could grow to be disgusting, as there are users on all sorts of niche Linuxes that may use other systems. Additionally, this patch doesn't require knowledge of which system is being used--so long as your man program has a `-w` flag (which excludes strictly POSIX systems, but just about nobody else, as far as I know), you should be able to use this patch. However, that does seem like a patch which should likely be ported to nvim sooner rather than later, all things considered.

**Comment by willeccles** [comment]
While poking around, I realized that tab-completion of man pages does not work with mandoc, but does with man-db. We may want to consider using `man -k` for this, as it allows us to avoid reinventing the wheel for man page searching (which is what is happening now). We should be able to run `man -k` and manually filter the results so that we're only searching for matches to the name. For example, if we want to use `:Man write` and type in `:Man wr`, it would effectively do `man -k wr | grep ^wr | sed -E 's/ - .+//'` (without the external programs), then our results just look like this (on my system):

```
write(1)
write(2)
wresize(3, 3X, 3x)
```

These are easy to parse, and we can order them such that the ones in the user's preferred sections are shown first (if that's desired).

@nhooyr thoughts on this? It seems that the current implementation is relying on `man -w` with no arguments printing out the manual search paths, while this does not happen on mandoc systems.

**Comment by willeccles** [comment]
Oh dear God, this is not what I meant to do

**Comment by willeccles** [comment]
I think this ought to be good to go, just needs some commit squashing and renaming (CI apparently doesn't like "runtime:" anymore). @nhooyr, any thoughts? It appears to work on my mandoc system, would be curious to know if all is well on other systems as well.

**Comment by willeccles** [comment]
Appears to work on my Debian (man-db) system; I should imagine it works everywhere else. At the very least, it accomplishes the goal I set out to achieve.

**Comment by willeccles** [comment]
CI failures appear just to be some strangeness with the Windows runners, so I will assume I don't need to touch anything for the time being.

**Comment by gpanders** [comment]
Seems like a good fix, and @nhooyr doesn't seem to be around for feedback. Let's go ahead and merge and if there are any regressions we can address them before the next release.

**Pull request merged**
