### PR TITLE
doc: Lua.txt formatting

### PR DESCRIPTION
**Pull request by rktjmp**
*This PR isn't 100% complete and requesting review, but before I really get involved in it I figure it's worth checking how much interest there would be in merging. It's quite a heavy change set in terms of line count even if content largely remains as-is. I can understand if it's seen as a bit heavy handed, though commits are kept as atomic as feasible.*

I noticed some of the layout/formatting in `runtime/doc/lua.txt` was inconsistent.

This included:

- Mixed tabs and spaces (even swapping on the same line!):
  - It seems that most newer documentation was written with just spaces, the code style guide specifies spaces over tabs, though that is for *code*, not *documentation*.
  - Tabs have been converted to spaces.
  - I recognize that the modeline specifies 8 spaces for tabs, but again, tabs vs spaces was applied so inconsistently that this didn't really have useful implications.

- Lines overrunning 78 characters:
  - This was sometimes an result of tabs vs spaces, or just inconsistently applied rules.
  - Lines have been re-wrapped to 78 characters where possible (some lines such as URLs or "one liner" vim command examples are left as is (_for now?_)).

- Inconsistent justification of tags:
  - Many tags were not justified to the right edge of 78ch.
  - Tags have been justified.

- Inconsistent blank lines
  - This included after "tags lines", function signatures, some examples, headings, etc.
  - Tags and signatures are followed by a blank line
  - Style guide for some examples isn't so clear, one line examples vs multi line etc.
  - Incomplete.

- Inconsistent indentation for function documentation
  - vim.uri and vim module were indented much deeper than the vim bridge docs. At some point this was _maybe_ to align the documentation paragraphs with the function signatures, but it no longer aligned with anything. This might have also just been a side effect of some docs having been written with tabs, then those spaces were converted at some point.
  - Indentation has been normalized to 4 spaces, which matches the lua-vimscript section, and also I think makes more sense as it allows for less wrap issues and the super deep indentation seemed unnecessary.

As I wrote at the start, this is more of an RFC, welcome to trash it as it is somewhat opinionated. There are still inconsistencies around stuff such as `:lua` and `:luado` separating it's description by a new line or in-line with the command, tags in or out of line with the command , etc. 

I couldn't find an actual documentation style guide, so I tried to infer what I could. Perhaps that would also be a good project (along with a linter or aid of some kind probably)?

### CODE REVIEW

**Comment by rktjmp** [comment]
After poking around a bit, I now see that docs are generated via doxygen, at least partially, which probably explains some of the inconsistencies between generated and written docs.

Which makes much of this PR invalid (or at least *very* ephemeral).

If there is interest in normalizing stuff in the principle of this PR then I can look deeper at how things are generated.

**Comment by tjdevries** [comment]
The docs are generated with `./scripts/gen_vimdoc.py`

I can give you more info if you're interested. Mostly just commenting here to remind myself to look at this when I have some more time :)

**Comment by rktjmp** [comment]
Thanks for the pointer, having a little trouble getting off the ground.

What I can gather:

- Running `make `doesn't run `gen_vimdoc.py`, Grepping the base for `gen_vimdoc` doesn't show much either.
- Running `doxygen src/Doxyfile` doesn't run `gen_vimdoc.py`. Pretty sure this is intentional as the vimdoc script isn't technically part of the doxygen setup, just proxies through doxygen to aid generation, right?
- If I run `python3 scripts/gen_vimdoc.py`, I have to manually install the `msgpack` dependency (this is fine, but unsure if it was supposed to be installed into `.deps`, probably not as that's just neovim deps, not build deps AFAIK). After installing msgpack I get an error:

```
Traceback (most recent call last):
  File "/home/_/projects/neovim/scripts/gen_vimdoc.py", line 1090, in <module>
    main(Doxyfile, args)
  File "/home/_/projects/neovim/scripts/gen_vimdoc.py", line 980, in main
    fail(f'no sections for target: {target}')
  File "/home/_/projects/neovim/scripts/gen_vimdoc.py", line 227, in fail
    raise RuntimeError(s)
RuntimeError: no sections for target: lua
```

Which seems to imply it can't find the appropriate `*section*` header to insert content? This is all being run off the latest master, not my branch. I can see it processing the luafiles (`src/nvim/lua/vim.lua`, etc), so I don't believe it's an indexing issue, just a final output issue.

Feels like I've maybe missed a key step.

**Comment by tjdevries** [comment]
Sorry, I kinda feel off the face of the earth a bit over the past few months. I have a different project working on generating help docs if you're interested in playing around with it.

You can check it out here some time: https://github.com/tjdevries/tree-sitter-lua It uses tree sitter to do the parsing and then lua to do the generation.

Could be fun if this is interesting to you :) 

Sorry again for not responding! Thanks for your hard work.

**Pull request closed without merging**
