### PR TITLE
vim-patch:8.1.1068: cannot get all the information about current comp…

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    Cannot get all the information about current completion.
Solution:   Add complete_info(). (Shougo, Hirohito Higashi, closes vim/vim#4106)
https://github.com/vim/vim/commit/fd133323d4e1cc9c0e61c0ce357df4d36ea148e3

### CODE REVIEW

**Comment by Shougo** [comment]
I have tested it, but it is crashed...

Can you review the changes?

**Comment by justinmk** [comment]
Thanks. Fixed lint errors. 

Crashed fixed by using `EMPTY_IF_NULL `: https://github.com/neovim/neovim/commit/1ae52a3bba88835589c4dbf68d3ad169b1d4d21a

**Comment by prabirshrestha** [comment]
Thanks for the quick turn around. Just release asyncomplete v2 with `complete_info()`.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
