### PR TITLE
[RFC] Fix a couple warnings in the release build.

### PR DESCRIPTION
**Pull request by jszakmeister**
I'd be very interested in people's opinion of what to do for the fix in wstream.c.  I took one approach, but I'm happy to take another if anyone has a better idea (or a preference).

I'd like to get master building with no warnings for the release build, so that we can add another build to the Travis build matrix and check that we are clean in the presence of optimizations.  I had started this in #1071, but I'm going to close that and split the work more.  Plus, the build system has changed considerably (at least from the Travis perspective).

### CODE REVIEW

**Comment by jszakmeister** [comment]
> assert(uv_guess_handle(file) == UV_NAMED_PIPE ||  uv_guess_handle(file) == UV_TTY);

This actually what I had originally done but figured folks would balk at it.  Hopefully others will chime in.  This is my preferred solution though. :-)

**Comment by elmart** [comment]
I'm confused. Last time we talked about it, we said `asserts` should be included in release build. IMO, log statements too, specially at the error level. Difference would just be optimization flags, not included code. I thought that was the case, in fact, but it seems it's not. Couldn't that be fixed instead?

**Comment by jszakmeister** [comment]
> Last time we talked about it, we said asserts should be included in release build.

In RelWithDebInfo they are, but not in a full release build.

**Comment by elmart** [comment]
> In RelWithDebInfo they are, but not in a full release build.

Well, that's my point. We said our "full release" would be "RelWithDefInfo". I mean, we won't release anything not including asserts/logs. Isn't that the case?

**Comment by jszakmeister** [comment]
> Well, that's my point. We said our "full release" would be "RelWithDefInfo".

I read that as our "preferred" release (our binaries may be built that way), not that we were going to work hard to prevent folks from running without asserts and logs.  I'd at least like the option to not have them.  It's handy for debugging right now, but what about down the road?  If we never compile with them disabled, then we will have even more cleaning up to do. :-(

**Comment by elmart** [comment]
> I read that as our "preferred" release (our binaries may be built that way)

Well, that's what I meant, in fact. You're right that our sources being in the open, nothing prevents people to instruct cmake to compile with standard Release mode.

So, I'm ok with these changes. LGTM.

**Comment by jszakmeister** [comment]
Thanks @elmart!

**Pull request merged**
