### PR TITLE
fix(defaults): omit empty line from unimpaired mapping messages

### PR DESCRIPTION
**Pull request by marcuscaisey**

### CODE REVIEW

**Comment by dundargoc** [comment]
Uh, is this done or what? What's happening here?

**Comment by clason** [comment]
PRs must be accompanied by a "Problem: ... Solution: ..." style description. Please add that.

**Comment by marcuscaisey** [comment]
This is not done, which is why i opened in draft status 😄 I need to add a test and a description but got distracted by something else. Will get around to it sometime.

**Comment by clason** [comment]
> Yep, I understand that (i've read https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md). It's in draft so not requesting feedback right now.

We still require that information for triage. Please **always** include this information, even in a draft PR. Otherwise wait until you're done before opening a PR. ("Junk" PRs waste maintainer and CI time, so we need to know that this is not the case here.)

**Comment by marcuscaisey** [comment]
> > Yep, I understand that (i've read https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md). It's in draft so not requesting feedback right now.
> 
> We still require that information for triage. Please **always** include this information, even in a draft PR. Otherwise wait until you're done before opening a PR. ("Junk" PRs waste maintainer and CI time, so we need to know that this is not the case here.)

Alright, fair enough. I'll close this for now then since i'm not sure when i'm going to get around to it 🙏

**Comment by clason** [comment]
Looking forward to the "real" PR then!

**Comment by dundargoc** [comment]
> It's in draft because it's not ready for feedback.

I understand, I was just certain no one would open a two-line change PR unless it was finished. I assumed you had forgotten to undraft it, which happens from time to time.

**Comment by marcuscaisey** [comment]
> > It's in draft because it's not ready for feedback.
> 
> 
> 
> I understand, I was just certain no one would open a two-line change PR unless it was finished. I assumed you had forgotten to undraft it, which happens from time to time.

Ha, yeah fair enough. I can see how we got here 😃

**Pull request closed without merging**
