### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by janlazo** [comment]
vim-patch:8.0.1564: too many #ifdefs 
vim-patch:8.0.1565: can't build Mac version without GUI 
vim-patch:8.0.1566: too many #ifdefs 
vim-patch:8.0.1567: cannot build Win32 GUI without IME 
vim-patch:8.0.1571: can't build without GUI 
vim-patch:8.0.1580: FEAT_CURSORBIND and FEAT_SCROLLBIND are unused 
vim-patch:8.0.1581: cannot build Win32 GUI without +eval 
vim-patch:8.0.1583: using C99 comment 
vim-patch:8.0.1584: using C99 in Mac file gives compiler warning messages 
vim-patch:8.0.1585: enabling beval_term feature in Win32 GUI
vim-patch:8.0.1586: imactivatefunc does not work on non-GUI Mac 
vim-patch:8.0.1603: cannot build with +terminal but without +menu 
vim-patch:8.0.1608: Win32: directx not enabled by default

**Comment by janlazo** [comment]
@blueyed I missed that macro. I thought it didn't apply because `buffer.c` had the changes already and the changes came from @ZyX-I.

**Comment by ZyX-I** [comment]
@janlazo Changes in Vim came *after* I changed Neovim (though AFAIR before changes got *merged*) and @justinmk pointed to my patch in vim/vim#1477, and you could see usual disagreement regarding design decisions in #6112: Vim has this macro and stores pointer to `dictitem_T`, I have `b_changedtick` pseudo-attribute (macros) and store `dictitem_T` by value. Which of the macros is more consistent is questionable: (Neo)Vim codebase has both pseudo-attributes and function-like macros where pseudo-attributes are sufficient, but function-like macros is more future-proof. Also pseudo-attribute was kept primary because at the time of writing the patch *it* would make merging Vim patches easier, now it is not the case.

**Comment by blueyed** [comment]
> So it is probably better to get rid of pseudo-attribute and introduce macros, though adapted to the differences between how Vim and Neovim actually holds the counter.

Makes sense.  Do you agree @justinmk ?
Will you do it then @ZyX-I?

**Comment by justinmk** [comment]
No objection from me... @ZyX-I will you be able to help with this?

**Comment by janlazo** [comment]
Is 8.0.0365 N/A now?

**Comment by janlazo** [comment]
8.0.0649 (without comment changes) is merged already?

**Comment by janlazo** [comment]
@ZyX-I Is https://github.com/vim/vim/commit/f8be461d0284110b321be748fea206d4169b98bb N/A?

**Comment by ZyX-I** [comment]
They should be fine to have, I did not change `ex_function` there AFAIR.

**Comment by janlazo** [comment]
Testing 8.0.0663 on https://github.com/neovim/neovim/pull/8692 to confirm that 8.0.0654 is fully ported.

**Comment by janlazo** [comment]
Why is e9134421ab8f72393d469d9d7793d4a75984cb93 not detected?

**Comment by jamessan** [comment]
> Why is e913442 not detected for 8.0.0649? 8.0.0650 is detected.

The expectation is that there's a distinct `vim-patch: ...` per patch in the commit message.  That wasn't the case here.  That's why we generally do 1 commit per upstream commit.  If there's a reason not to do that, then the commit message should still have one `vim-patch: <description>` per line.

**Comment by janlazo** [comment]
What's the status on reviewing the N/A patches here?

**Comment by janlazo** [comment]
If this won't be merged until every applicable 8.0.x patch has been merged, I'll start adding 8.1.x patches from https://gist.github.com/janlazo/cea7acf2711e89a9bc4f7c79612c6e54#na.

**Comment by janlazo** [comment]
8.0.1269 is merged already (included in 8.0.0703 port, fd58863eb62edddf688a71d73448934efa188241
) so it's N/A.

**Comment by Shougo** [comment]
@justinmk When it is merged?  The version.c changes seems huge.

**Comment by janlazo** [comment]
vim-patch:8.0.0822 is N/A because of https://github.com/neovim/neovim/commit/4a083200078f76f29a84e4788108000009a54020

**Comment by ckelsel** [comment]
vim-patch:8.0.0812: terminal window colors shift when 'number' is set

**Comment by blueyed** [comment]
vim-patch: 8.1.0343 is N/A (https://github.com/neovim/neovim/pull/9041)

**Comment by justinmk** [comment]
Thanks for the notes everyone. I included all the NA patches except:

    vim-patch:8.0.1193: crash when wiping out a buffer after using getbufinfo()

see https://github.com/neovim/neovim/pull/9163

**Pull request closed without merging**
