### PR TITLE
vim-patch:2346a6378483,4d8f476176ea,90df4b9d4234,6aa57295cfbe Update runtime files

### PR DESCRIPTION
**Pull request by jsatk**
https://github.com/vim/vim/commit/2346a6378483c9871016f9fc821ec5cbea638f13
https://github.com/vim/vim/commit/4d8f476176eadfc745bcb8e143460029048f858d
https://github.com/vim/vim/commit/90df4b9d423485f7db16e3a65cab4f14edc815ae
https://github.com/vim/vim/commit/6aa57295cfbe8f21c15f0671e45fd53cf990d404

This PR adds in the four missing runtime updates found by running `./scripts/vim-patch.sh -L --grep "Update runtime files" -- src`. This PR replaces former runtime update PR I opened [here](https://github.com/neovim/neovim/pull/15418) as that PR only pulled in the latest and not all the missing ones in order.

### CODE REVIEW

**Comment by clason** [comment]
Oh, no, don't do that!

Have a little patience, I'll be with you soon.

**Comment by clason** [comment]
Sorry, didn't mean to just close your PR (was on mobile).

Anyway, here's the point: Most vim patches (including runtime files) don't apply cleanly anymore, so they involve a good amount of manual work -- the script is good the lay out the raw material but is only the first step of several. This only gets more difficult by trying to tackle them all at once...

(Also, we're missing _six_ runtime file updates, not four -- the last full sync was the May 16 one.)

**Comment by jsatk** [comment]
> Sorry, didn't mean to just close your PR (was on mobile).

Can we re-open this or...?

> Anyway, here's the point: Most vim patches (including runtime files) don't apply cleanly anymore, so they involve a good amount of manual work -- the script is good the lay out the raw material but is only the first step of several. This only gets more difficult by trying to tackle them all at once...

Would you rather I open all of these as individual PRs? Again, I literally am just trying to get one tiny scala syntax change that I fixed and opened a PR for and Bram merged in
 
> (Also, we're missing _six_ runtime file updates, not four -- the last full sync was the May 16 one.)

When I ran `./scripts/vim-patch.sh -L --grep "Update runtime files" -- src` it only showed me four. I noticed the two extra missing ones. They were the oldest and the newest (this one containing the changes I want). I applied those too but they were empty commits which I found confusing. So I dropped them.

I've followed the instructions in the docs, PRs, and the script to a tee. I'm at a loss for what to do next here.

**Comment by clason** [comment]
Again (for the third time now): porting patches requires manual effort and some know-how (which basically only janlazo possesses fully) since not all upstream changes are applicable to neovim. So the output of the script is not in a mergeable state.

Since you only want to get a small change in, I recommend _just porting that change_, following the steps I've repeatedly told you.

**Pull request closed without merging**
