### PR TITLE
fixup: Statusline doesn't respect winhl.

### LINKED ISSUE #19865: Statusline doesn't respect winhighlight
### Neovim version (nvim -v)

0.8.0 commit ff5cfcdea

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

Built from repo

### How to reproduce the issue

```vim
" file: minimal_init.vim
set stl=%#Normal#
hi NormalCustom ctermbg=grey
hi Normal ctermbg=blue
set winhighlight=Normal:NormalCustom
```

```sh
nvim --clean -u minimal_init.vim
```

### Expected behavior

Statusline highlight should respect winhighlight option. So statusline should blend with background and be invisible as it's highlighted with Normal .

### Actual behavior

Statusline get's highlighted with global Normal instead of with NormalCustom as defined in winhighlight of the windows.

### PR DESCRIPTION
**Pull request by shadmansaleh**
fixes #19865

Let me know if there's a better way to fix this Or if this is missing something. Everything seems to work as expected and all tests pass.

Q: Does screen tests even check highlights in statusline ??

### CODE REVIEW

**Comment by bfredl** [comment]
Hmm, normally `syn_get_final_id` is called at the other end, at the process of translating the oridinal hl_id down to highlight attrs. I'd look into why that is missing. (so that `hi link` and `hi guifg=whatever` definitions take effect at the same time, which will make reasoning with highlight namespace easier).

**Comment by bfredl** [comment]
ok, the problem is rather about running `win_redr_status()` outside the context of `update_screen`, so the logic of setting the namespace must be used there as well. I'll push a fix.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/pull/19897 something like this. I'll need to write some tests tho to verify it helps.

**Comment by shadmansaleh** [comment]
> ok, the problem is rather about running win_redr_status() outside the context of update_screen, so the logic of setting the namespace must be used there as well. I'll push a fix.

**Comment by shadmansaleh** [comment]
> ok, the problem is rather about running win_redr_status() outside the context of update_screen, so the logic of setting the namespace must be used there as well. I'll push a fix.

That would make sence. In that case I can close this pr.

**Pull request closed without merging**
