### PR TITLE
[RFC] Fix UpdateRemotePlugins fails problem

### PR DESCRIPTION
**Pull request by Shougo**
It fixes @critiqjo reported https://github.com/neovim/neovim/issues/3749#issuecomment-161196210 `:UpdateRemotePlugins` problem.

### CODE REVIEW

**Comment by critiqjo** [comment]
@Shougo :+1: Great! This does handle missing providers well. It might be better if the error message is shorter (ignore backtrace?).

**Comment by justinmk** [comment]
@jszakmeister FYI quickbuild is reporting a disk space issue.

**Comment by justinmk** [comment]
Tightening up the python host error messages is a larger issue, so merging this.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
