### PR TITLE
lsp: Revert "lsp: Fix text edits with the same start position (#12434)"

### PR DESCRIPTION
**Pull request by ndreas**
This reverts commit 44fe8828f06a22bc9aa3617a6fd8aae447a838de.

Fixes both the issues I tried to correct in #12434, as well as the issue in #12526. I think something else has fixed the issue I had originally. For more info, see #12533

### CODE REVIEW

**Comment by ndreas** [comment]
@tjdevries Any chance this could be reviewed or should I do something else?

**Comment by tjdevries** [comment]
Sorry, missed this in my inbox. 

So basically the fix that we had actually didn't fix the problem, it was something else?

Are the tests invalid now (as in shouldn't work)? Otherwise we could leave the tests in if they're still passing and the desired behavior.

**Comment by ndreas** [comment]
> Sorry, missed this in my inbox.
> 
> So basically the fix that we had actually didn't fix the problem, it was something else?
> 
> Are the tests invalid now (as in shouldn't work)? Otherwise we could leave the tests in if they're still passing and the desired behavior.

Yeah the tests are invalid. I misinterpreted the (rather hairy) spec so the previous functionality was fine. I have no idea though what fixed my initial error :)

**Comment by tjdevries** [comment]
Ha, ok. It was definitely confusing because I read the same spec you did and agreed :)

TY for fix & revert of fix ;) Thanks for following up.

**Pull request merged**
