### PR TITLE
[RFC] vim-patch:7.4.680

### PR DESCRIPTION
**Pull request by jusga**
```
Problem:    CTRL-W in Insert mode does not work well for multi-byte
            characters.
Solution:   Use mb_get_class(). (Yasuhiro Matsumoto)
```

https://github.com/vim/vim/commit/310f2d59b2b20c642088feb5e6dfe323cc570923

```
Add test files for patch 7.4.680.
```

https://github.com/vim/vim/commit/dbcf19dc498cb1561c9215a3f255e81cde0c0543

### CODE REVIEW

**Comment by fwalch** [comment]
Just a heads up so you don't do unnecessary work: `scripts/legacy2luatest.pl` should work for converting the test.

**Comment by jusga** [comment]
@fwalch Thanks for the hint!

**Comment by fwalch** [comment]
LGTM.

**Comment by justinmk** [comment]
Verified test. Thanks!

**Pull request merged**
