### PR TITLE
fix(paste): ignore mappings in Cmdline mode

### LINKED ISSUE #17724: vim.paste(): mappings are not disabled in Cmdline mode
### Neovim version (nvim -v)

From v0.4.0 to HEAD

### Vim (not Nvim) behaves the same?

no, 8.2.4567

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. `nvim --clean`
2. `:cnoremap a b`
3. paste `a` from system clipboard using bracketed paste

### Expected behavior

`a` is pasted

### Actual behavior

`b` is pasted

### PR DESCRIPTION
**Pull request by VelocityDv**
Problem: mapping not disabled in Cmdline mode. 
Solution:  replace nvim_input with nvim_feedkeys with 'n' flag to ignore mapping.
Fix #17724

### CODE REVIEW

**Comment by zeertzjq** [comment]
I added a test. I'd like to wait for @justinmk's review on this since I don't know why `nvim_input()` was used in the first place.

**Comment by zeertzjq** [comment]
Since this can be rewritten again after #18096, I'll just merge this so that this can be backported.

**Comment by zeertzjq** [comment]
Since this can be rewritten again after #18096, I'll just merge this.

**Comment by justinmk** [comment]
> I added a test. I'd like to wait for @justinmk's review on this since I don't know why `nvim_input()` was used in the first place.

No reason except I thought (assumed/hoped/worried/cargo-culted) that nvim_input would be safer since it's somewhat lower-level than feedkeys().

This looks like a good solution, thanks.

**Pull request merged**
