### PR TITLE
Patch vim-patch:8.1.1310 with v:none reverted only in vimL.

### PR DESCRIPTION
**Pull request by LumaKernel**
vim-patch:8.1.1310: named function arguments are never optional

Problem:    Named function arguments are never optional.
Solution:   Support optional function arguments with a default value. (Andy
            Massimino, closes vim/vim#3952)
https://github.com/vim/vim/commit/42ae78cfff171fbd7412306083fe200245d7a7a6

Note: v:none is needed for supporting skipping args keeping default.
      (Original vim behavior)

v:none never appears in lua and json. And if try to bring v:none to lua
or json, it will be same as null.

---

`v:none` is reverted from https://github.com/neovim/neovim/commit/6167ce6df2753d5474ad49aea19f5957128ab015

This is my first PR to neovim :)

This is not simple patch because `v:none` that was once deleted from neovim is reverted.
It may need discussion.

## What did I do?

- Revert `v:none`.
  - In JSON and msgpack, it behaves as `v:null`.
  - Not providing lua native userdata corresponds to `v:none`
- Patch vim-patch:8.1.1310 to enable `default arugments` of VimL function.

## Vim-patch:8.1.1310 is needed?

- I want. Also in neovim. Default argument is useful.

## What I want to discuss?

- Exporting `v:none` should behaves as...
  + an error ?
  + `v:null` like I PR-ed this time ?
  + ( a native object ? )
    + It seems obviously bad, there is no proper value in JSON.

## Why do I think `v:none` only in VimL is not bad ?

- I thought taking `v:none` only the default value may be not so affecting neovim  
and an easy way to bring default argument.

## Why exporting `v:none` is not error ?

- I have no strong reason.

## Other options I thought

- Use `v:null` to default arguments.
  - Break compatibility with vim.
- Give up using partially default argument.
  - I think it is one good option but wanted it  
because I can easily use this with one special value...
- Use completely new special value instead of `v:none`  
  for setting to use partially default value  
like ... like ...... I have no idea .... sorry.

### CODE REVIEW

**Comment by LumaKernel** [comment]
After sending PR, I was told duplicate https://github.com/neovim/neovim/pull/10905 .
Compared to it, this PR includes `v:none` .

**Comment by justinmk** [comment]
> Note: v:none is needed for supporting skipping args keeping default.

We are not going to support `v:none`.

**Comment by bfredl** [comment]
> Note that this means you cannot pass v:none as an ordinary value when an argument has a default
expression.

So it would impossible to send `v:none` as a value to such a function. I don't think (either) we want to add a value with such a special semantics. Lua's `nil` is at least nothingness-in-nothingness-out, it doesn't cause values to appear out of nowhere.

**Comment by LumaKernel** [comment]
Thanks! I'll try to write in Lua!

**Pull request closed without merging**
