### PR TITLE
[RFC] Replace vim with nvim in macros

### PR DESCRIPTION
**Pull request by djrenren**
Fix for issue #4407 

Simple fix. Also edited the .bat file for windows

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! Please see https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-guidelines.

In particular it's important that commit messages have a short "prefix". This really helps when composing the changelog for a release, as well as just reading the logs. In this case:

    runtime/macros: replace "vim" with "nvim"

**Comment by justinmk** [comment]
@tarruda The new lua test is really flaky.

**Comment by tarruda** [comment]
@justinmk It is only one failure in terminal/cursor_spec.lua. I've seen it happen randomly before, but it seems an indeterminism of the test itself, possibly triggered by lua being significantly slower than luajit.

I will see if I can dig what's the cause, but for now you can ignore it(just run the functionaltest-lua build again and it will probably pass)

**Comment by djrenren** [comment]
Looks like it only failed on the publish step? 

Is this because I force pushed an amend and there was some leftover state somewhere?

**Comment by tarruda** [comment]
> Looks like it only failed on the publish step?

cc @jszakmeister

**Comment by jszakmeister** [comment]
> Looks like it only failed on the publish step?

The publish step is when it determines if there is a test failure.  It's a quickbuild thing, and I can't really change that.  If I had the test suite fail the run step, then you wouldn't get to see the results.

**Pull request merged**
