### PR TITLE
Add `any` type to Go syntax highlighting

### PR DESCRIPTION
**Pull request by speelbarrow**

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but we take these files verbatim from Vim and do not make any changes.

The correct procedure is to contact the maintainer listed at the top of the file, then PR the changes to Vim. We will then pull the changes in as part of the regular runtime updates.

**Comment by dundargoc** [comment]
https://github.com/fatih/vim-go/pull/3351

> Yeah, I'll submit a PR to Vim soon

:thinking:

**Comment by dundargoc** [comment]
aka the maintainer has already fixed this, now he just needs to port it to vim so we can port it.

**Comment by noah-friedman** [comment]
Got it. Thanks!

**Pull request closed without merging**
