### PR TITLE
[RFC] vim-patch:7.4.651

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    Can't match "%>80v" properly for multi-byte characters.
Solution:   Multiply the character number by the maximum number of bytes in a
            character. (Yasuhiro Matsumoto)

https://github.com/vim/vim/commit/4f36dc3bf7118a3fa5ccdae1a37963860dc71e6c

This fix is needed for the problem.
https://github.com/Shougo/vimfiler.vim/issues/260

It is degrade fix of Vim 7.4.577.

### CODE REVIEW

**Comment by mhinz** [comment]
LGTM

**Comment by fwalch** [comment]
LGTM, thanks!

**Comment by Shougo** [comment]
Thank you!

**Comment by Shougo** [comment]
Note: vim-patch.sh is really great.  I use it for the PR.

**Comment by justinmk** [comment]
Yes it is, can't thank @fwalch enough!

**Pull request closed without merging**
