### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by equal-l2**

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM. If anyone thinks this should wait until 0.2.2 please speak up, but I'm inclined to sort this out in 0.2.1 since that was planned after releasing 0.2.0.

**Comment by justinmk** [comment]
In https://github.com/neovim/neovim/pull/6837#issuecomment-305870343 appveyor didn't like the LuaJit upgrade. We could postpone that if it's too much trouble.

**Comment by justinmk** [comment]
Looks like msgpack requires cmake 2.8.12 now, so we may need to follow suit.

```
02:05:46,545 INFO  - [ 87%] Performing configure step for 'msgpack'
02:05:46,561 WARN  - CMake Error at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
02:05:46,561 WARN  - CMake 2.8.12 or higher is required. You are running version 2.8.7
```

**Comment by concatime** [comment]
Please change the link of gperf and luajit to https. Thank you.

**Comment by equal-l2** [comment]
@concatime Fixed. Thanks!

The problem with LuaJIT is that LuaJIT uses `ar rcus 2>/dev/null` as `AR`.
Since `/dev/null` doesn't exist on Windows, this cause the error.
`AR` have been correct before https://github.com/LuaJIT/LuaJIT/commit/eef77a6d775147a1b581b06c296e9f2b3ebc9d2b.

**Comment by justinmk** [comment]
I would think /dev/null works on appveyor since we're using msys2.

**Comment by equal-l2** [comment]
@justinmk 
msys2's `/dev/null` is only accessible via msys2's own shell (e.g.`C:\msys64\usr\bin\bash.exe`)
Appveyor apparently uses `cmd.exe`, it can't use `/dev/null`.

**Comment by concatime** [comment]
Why do you build with msys2 and not with MSVC?
I just tried to build LuaJIT with [MSVC_17](https://www.visualstudio.com/downloads) (
Other Tools and Frameworks > Build Tools for Visual Studio 2017) and worked perfectly.

**Comment by justinmk** [comment]
@concatime luajit is not the limiting factor, Nvim is. Building Nvim with MSVC was possible at one point, but it regressed before we had established appveyor. So now that's a pending task waiting for someone to take care of...

In the meantime Nvim currently only builds with mingw/msys2.

**Comment by concatime** [comment]
Ok, I understand. So, why not forking LuaJIT into `neovim/deps`, and remove the pipe to `/dev/null`? A temporary fix until the LuaJIT team fix the [issue](https://github.com/LuaJIT/LuaJIT/issues/336).

**Comment by jszakmeister** [comment]
> Looks like msgpack requires cmake 2.8.12 now, so we may need to follow suit (see the top of our CMakeLists.txt).
> 
> 02:05:46,545 INFO  - [ 87%] Performing configure step for 'msgpack'
> 02:05:46,561 WARN  - CMake Error at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
> 02:05:46,561 WARN  - CMake 2.8.12 or higher is required. You are running version 2.8.7
> And we will need to upgrade quickbuild. cc @jszakmeister

What are we upgrading to?  Just CMake to version 2.8.12?  To some other minimum set of operating systems?

**Comment by jamessan** [comment]
Not sure what the CMake versions are for the non-Linux environments, but upgrading Ubuntu to Trusty (14.04) would resolve the issue there.

**Comment by jszakmeister** [comment]
> Not sure what the CMake versions are for the non-Linux environments, but upgrading Ubuntu to Trusty (14.04) would resolve the issue there.

Sure, we can do that.  I guess I'd just like to be more formal about it and say that "we support, at a minimum, the oldest LTS series that still actively maintained, the last two macOS releases, FreeBSD 10.2 or better, and Windows 7 or better."  Or something to that effect.  I think it would guide things in the future about knowing when to upgrade and when to workaround the presence of new things that may not be present in systems still being supported.

**Comment by jamessan** [comment]
Agreed that a better defined support matrix would be good, but in this case it's a third party dependency that's bumping the requirement.  Either we supply a patch to them to avoid that, or we deal with it.

**Comment by jszakmeister** [comment]
> Agreed that a better defined support matrix would be good, but in this case it's a third party dependency that's bumping the requirement. Either we supply a patch to them to avoid that, or we deal with it.

I disagree.  We've been dancing around it for a while and I think we should just make a decision. :-)  I'll look to upgrade the Linux VM to Trusty.  I'm not sure when I'll get time for it though... it may be tomorrow night or Wednesday night before I can get cycles for it (sorry, but family life is just plain busy this time of year!).

**Comment by jszakmeister** [comment]
@jamessan The Linux QB node has been upgraded to Trusty.  It might take it a little while to catch up on any builds.

**Comment by jamessan** [comment]
> The Linux QB node has been upgraded to Trusty.

Thanks @jszakmeister!

> Looks like msgpack requires cmake 2.8.12 now, so we may need to follow suit

@justinmk I don't see why we would need to bump the minimum version for _our_ CMake files because of that.

**Comment by justinmk** [comment]
Re the lack of a support matrix: I view the bundled deps as "bleeding edge". I don't think they are our minimum requirements, more like the maximum. I guess we should also have CI envs testing against the minimums.

**Comment by jamessan** [comment]
@equal-l2 Can you bump msgpack-c to 2.1.3 so we have the gcc-7 fixes?

**Comment by jamessan** [comment]
LGTM.

The only outstanding question is whether to keep ecaae451 or not.  Since none of _our_ CMake files require the newer version, I'd lean towards dropping that commit.

**Comment by equal-l2** [comment]
@jamessan 
Which file do you mean by "our CMake files"?
`CMakeLists.txt` in root directory, in `third-party`, or both?

**Comment by jamessan** [comment]
> Which file do you mean by "our CMake files"?

I mean everything that's part of this git repository.  ecaae45 can be completely dropped since none of the CMakeLists.txt files in our repository are using anything that requires 2.8.12.

msgpack-c bumped _their_ minimum CMake version, but that's irrelevant to us other than the fact that people building the bundled msgpack-c will need to abide by their requirements.

I'm not opposed to raising our minimum CMake version, but I also don't see a reason to do it needlessly.

**Comment by equal-l2** [comment]
@jamessan 
That makes sense. I'll revert the commit.

**Pull request merged**
