### PR TITLE
build: BuildLibuv.cmake: use libuv upstream CMakeLists.txt

### PR DESCRIPTION
**Pull request by erw7**
This PR is for #9182.
A patch to CMakeLists.txt has already created a PR(libuv/libuv#2085) to upstream.

### CODE REVIEW

**Comment by justinmk** [comment]
Thank you @erw7 ! I think we should wait on libuv/libuv#2085 , managing all of these patches is very difficult.

**Comment by justinmk** [comment]
With https://github.com/libuv/libuv/pull/2085 , now the patch here is not needed?

**Comment by erw7** [comment]
> Would make sense to do a CI run here with libuv/libuv#2085 before libuv/libuv#2085 is merged.

I tried, but Windows build fails because the installation path contains `$<CONFIG>`. Also, it seems that the test fails because `luv.so` is not found on OpenBSD.

For Windows, I'll fix it and create a pull request upstream.

**Comment by erw7** [comment]
Is there a good way to force a static link when installing `luv` with `luarocks`? Should we delete shared libraries like `clean-shared-libraries`?

**Comment by justinmk** [comment]
Looks like this is working? Anything left to do?

**Comment by erw7** [comment]
> Looks like this is working? Anything left to do?

Yes, I think this is working. If we incorporate the libuv/libuv#2085 and libuv/libuv#2697 changes into the forked libuv, we can merge them.

However, `cmake_minimum_required` is 3.4, is that OK?

In addition, the following ugly countermeasures are needed. Therefore, I think it would be good if there was a function to select shared libraries and static libraries deleted from libuv/libuv#2085.

https://github.com/neovim/neovim/pull/9265/commits/538721c46f902e75d3c9ce2461e56d1282ae5321#diff-775b05e8e4c8012c87bf551979ad35f9R65-R72

**Comment by erw7** [comment]
For `i386`, we have installed `i386` `cmake`, is this necessary? If `CMAKE_TOOLCHAIN_FILE` is set properly, I think it is possible to create `i386` binaries with `x86_64` `cmake`, am I wrong?

**Comment by clason** [comment]
@erw7 I think this is now obsolete with the switch to upstream LibUV on Windows?

**Comment by erw7** [comment]
> I think this is now obsolete with the switch to upstream LibUV on Windows?

The change to use the upstream `CMakeLists.txt` is still needed. But surely this is getting old. So I will reconsider and either open a new PR or update this one.

**Pull request closed without merging**
