### PR TITLE
build: remove nix flakes

### PR DESCRIPTION
**Pull request by dundargoc**
It does not work and we don't plan on maintaining these anymore.

The flake files are being moved to
https://github.com/nix-community/neovim-nightly-overlay/pull/483
instead.

### CODE REVIEW

**Review by bfredl — APPROVED** [review]

**Review by teto — APPROVED** [review]
There seems to be a nice update possible https://github.com/nix-community/neovim-nightly-overlay/pull/483#issuecomment-2121161994 .
I will try to do the whole update/annoucements today and will merge this afterwards if that's ok with you. Having the flake disappear without proper announcements will annoy several people.

**Comment by teto** [comment]
flake moved to nix-community in https://github.com/nix-community/neovim-nightly-overlay/pull/516 . 
Announced on reddit via crosspost on r/neovim and r/nixos at https://www.reddit.com/r/NixOS/comments/1cz67bm/flakenix_moved_from_githubneovimneovim_to/ . 
And on nixos discourse at https://discourse.nixos.org/t/neovims-flake-nix-moved-to-nix-community/45887 . 

Thanks to the core maintainers for accepting the flake to be committed in the first place, then merging nix PRs, and finally let nix users handle a graceful migration. 
As development sped up, it became a hindrance to maintain so let's have neovim maintainers focus on neovim instead and the nix community build a richer neovim flake.

**Comment by farnoy** [comment]
There are some orphaned references left in BUILD.md referring to this flake that's been removed.

**Comment by dundargoc** [comment]
@farnoy wanna make a PR?

**Pull request merged**
