### PR TITLE
docs: remove Vi defaults from documentation

### PR DESCRIPTION
**Pull request by dundargoc**
It's not relevant and clutters the documentation.

### CODE REVIEW

**Comment by clason** [comment]
If we start diverging from upstream on those docs, maybe we should go whole hog and make these `Neovim default` -- at least for those where the defaults are different (like `'shortmess'`, where the "Vim default" is misleading)?

**Comment by dundargoc** [comment]
Hmm, I thought I got all of them. Yes, I think the "Vim" part of "Vim default" is redundant. Thanks.

**Comment by dundargoc** [comment]
Oh, you mean that instead of removing the Vim defaults, we should do it like how Vim does with the "Vim/Vi defaults" but instead with "Nvim/Vim defaults"?

**Comment by clason** [comment]
Well, my point was that it's probably useful to point out where Nvim diverges? (So "Vim defaults" if we share it with Vim; "Nvim defaults" where we have diverged.) This would also minimize the divergence in the docs.

**Comment by clason** [comment]
But the current state is also appealing.

**Comment by dundargoc** [comment]
I just remembered that `defaults.vim` is a thing. I guess I should just use the default value of vanilla Vim without `defaults.vim`? It'll look like a mess if I try to include Vim default with and without `defaults.vim`.

**Comment by clason** [comment]
> I just remembered that defaults.vim is a thing.

Not in Neovim, it isn't. (Thankfully.)

**Comment by justinmk** [comment]
> just writing "default" and being done with it.

+1

This also is a reminder that removing the `{not available without...}` stuff (e.g. https://github.com/neovim/neovim/pull/18684/files ) would be nice. Doesn't need to block this PR though.

**Comment by dundargoc** [comment]
> This also is a reminder that removing the {not available without...} stuff (e.g. [#18684 (files)](https://github.com/neovim/neovim/pull/18684/files) ) would be nice.

Pretty sure those have already been removed.

**Pull request merged**
