### PR TITLE
ci: fix Travis

### PR DESCRIPTION
**Pull request by blueyed**
It is disabled by default, and the docs mention that it slows builds
down [1].  It took 165s in https://travis-ci.org/neovim/neovim/jobs/572000615.

1: https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos

### CODE REVIEW

**Comment by blueyed** [comment]
/cc @janlazo 
You've used "update: true" since the beginning (c926ba1dc).  Is it ok to remove it?

**Review by justinmk — APPROVED** [review]

**Comment by blueyed** [comment]
@justinmk 
I was about to look having an override instead.. it is expected, isn't it?

**Comment by justinmk** [comment]
> I was about to look having an override instead.. it is expected, isn't it?

Yes, I think it's fine to ignore it.

**Comment by blueyed** [comment]
Should be good now.

**Comment by janlazo** [comment]
@blueyed It depends on the mac `osx_image`. Older images need it. Latest `osx_image` does not need it for most cases.

**Pull request merged**
