### PR TITLE
[RFC] Fix OS X builds.

### PR DESCRIPTION
**Pull request by fwalch**
Trying what happens with a more recent version of CMake first (from @aktau's observation in https://github.com/neovim/neovim/pull/1538#issuecomment-64965660).

### CODE REVIEW

**Comment by fwalch** [comment]
@aktau Do you already know more? :-)

**Comment by aktau** [comment]
> @aktau Do you already know more? :-)

I've been anxiously waiting for a reply. Must be the Christmas period slowness. Luckily if the answer is positive my future contributions will go a lot easier. So here's to hoping!

**Comment by aktau** [comment]
@fwalch check out the patches I posted on #1833. It should hopefully help :).

**Comment by fwalch** [comment]
:tada: 

Rebased this onto master (since #1833 was already merged), and it works! I'll clean up this PR, and hopefully this can finally be merged then. Thank you very much, @aktau!

**Comment by tarruda** [comment]
Great work @aktau, it will be nice to detect OSX bugs in PRs

**Comment by justinmk** [comment]
Thank you both, this is great!

**Comment by aktau** [comment]
> Great work @aktau, it will be nice to detect OSX bugs in PRs

It was actually all @fwalch's work, I just deblocked him because of an oversight in my Lua C formatter :). Props go to him.

> Rebased this onto master (since #1833 was already merged), and it works!

Totally awesome!

**Comment by aktau** [comment]
Perhaps the unit tests are working now, but the functional tests on OSX still seem to have some flakes:

```
Scanning dependencies of target functionaltest
++++++++++++++++++++++++++++++++++++++++++++++++++++++-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
190 successes / 1 failure / 0 errors / 0 pending : 0.0 seconds
Failure → ...vis/build/neovim/neovim/test/functional/job/job_spec.lua @ 100
jobs will only emit the "exit" event after "stdout" and "stderr"
...vis/build/neovim/neovim/test/functional/job/job_spec.lua:106: Expected objects to be the same.
Passed in:
(table): {
  [1] = 'notification'
  [2] = 'j'
  [3] = {
    [1] = {
      [1] = 1
      [2] = 'exit' } } }
Expected:
(table): {
  [1] = 'notification'
  [2] = 'j'
  [3] = {
    [1] = {
      [1] = 1
      [2] = 'stdout'
      [3] = { ... more } } } }
stack traceback:
	...vis/build/neovim/neovim/test/functional/job/job_spec.lua:106: in function <...vis/build/neovim/neovim/test/functional/job/job_spec.lua:100>
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:23 (message):
  Running functional tests failed with error: 1.
```

**Comment by fwalch** [comment]
Yes, just noticed it as well :-( What you posted was for the GCC 4.9 (from homebrew) build; with AppleClang, the output is

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build functionaltest
[100%] Built target nvim
Scanning dependencies of target functionaltest
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:23 (message):
Running functional tests failed with error: SIGPIPE.
```

**Comment by tarruda** [comment]
> It was actually all @fwalch's work, I just deblocked him because of an oversight in my Lua C formatter :). Props go to him.

yes, @fwalch has done an amazing work on our CI infrastructure!

**Comment by fwalch** [comment]
Thanks guys, but I don't even have access to a Mac.. in this PR, besides rebasing and hoping that it just works, I'm basically just doing what you are telling me to :wink:

Speaking of rebasing, the clang build seems to work now, but the GCC target still has the `SIGPIPE` error. If someone with a Mac has some time to spare: can you try building and running tests with Homebrew GCC?

Btw, as a general note, should unit tests be run with Clang as well (currently not the case)? Since the functional tests seem to behave differently for GCC/Clang..

**Comment by fwalch** [comment]
I tried to disable Valgrind for the GCC build to see if that would change anything, and it did:

```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++PANIC: unprotected error in call to Lua API (29)
```

**Comment by tarruda** [comment]
> ++++++++PANIC: unprotected error in call to Lua API (29

Strange error, I doner why this is only happening on GCC. What happens if you disable the JIT?

**Comment by fwalch** [comment]
> What happens if you disable the JIT?

Can you tell me how to do that?

**Comment by tarruda** [comment]
> Can you tell me how to do that?

You can call `jit.off()` before executing the relevant code, one way might be to add the statement at the top of helpers.lua

**Comment by tarruda** [comment]
It might be better to use `jit.off(true, true)` according to [this](http://luajit.org/ext_jit.html#jit_onoff_func)

**Comment by fwalch** [comment]
Huh, now the Clang build fails again (see https://github.com/neovim/neovim/pull/1572#issuecomment-70363630). Could it be a race condition?

For the GCC build:

```
DEBUG: turn off JIT

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*

196 successes / 0 failures / 3 errors / 0 pending : 0.0 seconds

Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 9

Screen before_each
./test/functional/helpers.lua:165: resource temporarily unavailable

stack traceback:
./test/functional/helpers.lua:165: in function 'clear'
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:10: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:9>
Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 15
Screen after_each
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: bad file descriptor

stack traceback:
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: in function 'send'
...im-deps/osx-x64/usr/share/lua/5.1/nvim/async_session.lua:34: in function 'request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:150: in function '_blocking_request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:79: in function 'request'
./test/functional/helpers.lua:44: in function 'request'
./test/functional/ui/screen.lua:135: in function 'detach'
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:16: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:15>
Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 465
Screen resize has minimum width/height values
Error in before_each
Error in after_each
stack traceback:
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:465: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:449>
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:23 (message):
Running functional tests failed with error: 2.
```

**Comment by fwalch** [comment]
Now, there was a [passing build](https://travis-ci.org/neovim/neovim/builds/48024801), but once I removed the two test commits (disable Valgrind/JIT), it [failed](https://travis-ci.org/neovim/neovim/builds/48030615) again :-(

Now trying with only JIT disabled.

**Comment by tarruda** [comment]
> Now, there was a passing build, but once I removed the two test commits (disable Valgrind/JIT), it failed again :-(

> Now trying with only JIT disabled.

I think its ok to permanently turn the JIT off, there's little gain in having it enabled for the functional tests.

**Comment by jszakmeister** [comment]
> I think its ok to permanently turn the JIT off, there's little gain in having it enabled for the functional tests.

Is the thought that Valgrind and the JIT are not cooperating?  Should we somehow add `-DLUAJIT_USE_VALGRIND` to `CFLAGS` for the LuaJIT build on Travis CI?

**Comment by tarruda** [comment]
> Is the thought that Valgrind and the JIT are not cooperating? Should we somehow add -DLUAJIT_USE_VALGRIND to CFLAGS for the LuaJIT build on Travis CI?

When valgrind is enabled for the functional tests, its enabled for the nvim process and not the luajit process, so I dont think that is the case.

**Comment by tarruda** [comment]
Its more likely that these failures are caused by race conditions, so we need to remove the non deterministic factors

@fwalch, try rebasing on master to get commits from #1863

**Comment by fwalch** [comment]
> Is the thought that Valgrind and the JIT are not cooperating?

I don't think so; I only disabled Valgrind because it was one difference between the Clang (which passed) and GCC builds.

**Comment by fwalch** [comment]
Disabling Valgrind doesn't seem to help with the error itself, but if it runs, the error is hidden (only `SIGPIPE` is shown). Seems to have been a "random working test", the error is still (despite rebasing):

```
Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 9
Screen before_each
./test/functional/helpers.lua:166: resource temporarily unavailable

stack traceback:
./test/functional/helpers.lua:166: in function 'clear'
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:10: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:9>

Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 16
Screen after_each
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: bad file descriptor

stack traceback:
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: in function 'send'
...im-deps/osx-x64/usr/share/lua/5.1/nvim/async_session.lua:34: in function 'request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:150: in function '_blocking_request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:79: in function 'request'
./test/functional/helpers.lua:45: in function 'request'
./test/functional/ui/screen.lua:140: in function 'detach'
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:17: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:16>

Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 9
Screen before_each
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: bad file descriptor

stack traceback:
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: in function 'send'
...im-deps/osx-x64/usr/share/lua/5.1/nvim/async_session.lua:34: in function 'request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:150: in function '_blocking_request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:79: in function 'request'
./test/functional/helpers.lua:159: in function 'clear'
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:10: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:9>

Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 16
Screen after_each
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: bad file descriptor

stack traceback:
...m-deps/osx-x64/usr/share/lua/5.1/nvim/msgpack_stream.lua:46: in function 'send'
...im-deps/osx-x64/usr/share/lua/5.1/nvim/async_session.lua:34: in function 'request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:150: in function '_blocking_request'
/opt/neovim-deps/osx-x64/usr/share/lua/5.1/nvim/session.lua:79: in function 'request'
./test/functional/helpers.lua:45: in function 'request'
./test/functional/ui/screen.lua:140: in function 'detach'
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:17: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:16>

Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 456
Screen resize rebuilds the whole screen
Error in before_each
Error in after_each

stack traceback:
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:456: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:450>

Error → ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 466
Screen resize has minimum width/height values
Error in before_each
Error in after_each

stack traceback:
...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:466: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:450>

CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:23 (message):

Running functional tests failed with error: 4.
```

**Comment by fwalch** [comment]
I disabled Valgrind, and while the latest build passed, it seems to be random. For example, [this failing build](https://travis-ci.org/neovim/neovim/builds/48156310) should be identical to the latest build (forgot to squash commits). Maybe Valgrind simply triggers this error more often because of the slowdown it causes.

**Comment by tarruda** [comment]
Ok now that #1519 is fixed, time to focus on this, I seriously need travis to test my changes on OSX :)

**Comment by tarruda** [comment]
@fwalch can you run some tests with this patch?

```diff
diff --git a/test/functional/job/job_spec.lua b/test/functional/job/job_spec.lua
index 07ca0c0..217f764 100644
--- a/test/functional/job/job_spec.lua
+++ b/test/functional/job/job_spec.lua
@@ -102,8 +102,8 @@ describe('jobs', function()
     nvim('command', "let j = jobstart('xxx', 'cat', ['-'])")
     local jobid = nvim('eval', 'j')
     nvim('eval', 'jobsend(j, "abcdef")')
-    nvim('eval', 'jobstop(j)')
     eq({'notification', 'j', {{jobid, 'stdout', {'abcdef'}}}}, next_message())
+    nvim('eval', 'jobstop(j)')
     eq({'notification', 'j', {{jobid, 'exit'}}}, next_message())
   end)
 end)
```

**Comment by tarruda** [comment]
The problem seems to be that `jobsend` is not a blocking function, and there's currently no way of being notified about its success or failure, so the failure could very well be caused by the fact that jobstop can kill the job before libuv has a chance to write the data to the job's stdin(so `cat` will never send anything else before exiting)

**Comment by fwalch** [comment]
@tarruda Does that work for you? I tried that locally, but then the test got stuck. I figured that `next_message()` would only work for a stopped job (output buffering?), but didn't investigate much further.

**Comment by tarruda** [comment]
> @tarruda Does that work for you? I tried that locally, but then the test got stuck. I figured that next_message() would only work for a stopped job (output buffering?), but didn't investigate much further.

I didn't test, but your'e right. It is output buffering, sending "abcdef\n" seems to fix the problem

**Comment by fwalch** [comment]
:+1:

**Comment by tarruda** [comment]
> Re-enabled Valgrind for the GCC build, let's see how it goes. Edit: not too good, apparently... SIGPIPE again

Is random or it always happens with valgrind/gcc?

**Comment by tarruda** [comment]
If the SIGPIPE caused by valgrind is the only remaining error, I suggest we simply disable valgrind on OSX and merge this PR. We can already detect memory problems with the clang/asan build.

**Comment by tarruda** [comment]
Very strange. All tests passed for @ec66ae4 but it still seems like valgrind was used for the gcc build due to how much time it took for the tests to run

**Comment by tarruda** [comment]
I noticed something disturbing: There are 207 functional tests, but travis only seems to be running 200(198 for OSX because of the missing xclip). I wonder what is happening to those 7 extra tests

**Comment by tarruda** [comment]
Found the problem: @276ac99350961631d89d0c4ec2bc03050f7d6c5d

When I pushed that commit, I forgot that the neovim module is also needed for testing `autoload/provider/python.vim`, my bad!

Will create a PR for fixing this

**Comment by justinmk** [comment]
If busted has an 'ignore test' function we shoulde that instead of just skipping the test, so we can see which tests are ignored.

**Comment by tarruda** [comment]
> If busted has an 'ignore test' function we shoulde that instead of just skipping the test, so we can see which tests are ignored.

It might be possible to achieve this with --exclude-tags, but I'm not sure it will display which tests were skipped

**Comment by tarruda** [comment]
@fwalch you can remove the last commit now, the problematic job spec has been marked as pending for now(need to rebase).

**Comment by fwalch** [comment]
Alright; rebased.

**Comment by aktau** [comment]
> Alright, rebased.

It *says* it's still failing in the OSX/clang builds, but I can't even see where. As far as I can see, the unit tests and functional tests are now passing:

```
Scanning dependencies of target unittest
++++++++E94: No matching buffer for _test_
E94: No matching buffer for _test_
E94: No matching buffer for _test_
E94: No matching buffer for test++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
200 successes / 0 failures / 0 errors / 0 pending : 0.0 seconds
[100%] Built target unittest
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -C build
[  0%] Built target sjiscorr
[ 42%] Built target translations
[100%] Built target nvim
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -C build functionaltest
[100%] Built target nvim
Scanning dependencies of target functionaltest
++++++++++++++++++++++++++++++++++++++++++++++++++++++.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
197 successes / 0 failures / 0 errors / 1 pending : 0.0 seconds
Pending → ...vis/build/neovim/neovim/test/functional/job/job_spec.lua @ 101
jobs will only emit the "exit" event after "stdout" and "stderr"
[100%] Built target functionaltest
```

Then it starts executing oldtest and I can't even see where it goes wrong.

Something I noticed though: these tests are taking an enormous amount of time:

```
 6639.1	9 min 14 sec	about 6 hours ago	linux	CI_TARGET=clang	
 6639.2	29 min 35 sec	about 6 hours ago	linux	CI_TARGET=gcc	
 6639.3	4 min 1 sec	about 6 hours ago	linux	CI_TARGET=gcc-32	
 6639.4	23 sec	about 6 hours ago	linux	CI_TARGET=clint	
 6639.5	50 min 4 sec	about 5 hours ago	osx	CI_TARGET=clang	clang
 6639.6	38 min 26 sec	about 6 hours ago	osx	CI_TARGET=gcc	gcc-4.9
```

That's half an hour for the largest linux build, and 50 mins for the largest OSX build (which was aborted in the end, possibly maybe because of some timeout (who knows?). Do we get less resources now or are we doing crazier and crazier things since I last looked at the test infrastructure?

**Comment by aktau** [comment]
Whoops, so after downloading the raw log files, I saw this at the end of the clang run:

```
I'm sorry but your test run exceeded 50.0 minutes. 
```

So, should we perhaps already disable oldtest on OSX?

**Comment by doppioandante** [comment]
I don't remember the pull request, but I think that at some point travis settings were modified to print the code of the test being run. If I remember correctly, before that all tests could complete in time, but I may be wrong.
Anyway, I think it would be better to dump just the failing tests.

**Comment by fwalch** [comment]
I re-pushed (didn't change the contents of the commits), and the build time is now more or less the same as on `master`. Travis seems a bit inconsistent lately..
FWIW, I plan to send PRs at some point to change the Travis setup to use the new containerized build infrastructure, use caching instead of `neovim/deps`, maybe enable "fast_finish", and split the build matrix into more, but smaller jobs (e.g. one that only runs unit tests, ...). Overall build time should hopefully go down.

**Comment by tarruda** [comment]
> Whoops, so after downloading the raw log files, I saw this at the end of the clang run:

Can you link to the raw log? Travis reports that all tests passed and I just searched the gcc/clang logs and couldn't find the timeout message.

**Comment by tarruda** [comment]
@aktau nvm, it must have been a random travis failure

**Comment by tarruda** [comment]
@fwalch thank you for this great work, LGTM. 

IMO we should merge this as soon as possible to have some OSX coverage, will wait for @justinmk though.

**Comment by tarruda** [comment]
>  Travis seems a bit inconsistent lately..

@justinmk Maybe we should use some of the project funds to hire a paid CI service? I've been looking at travis plans but the simplest one is $129 which seems a bit expensive.

Anyone interested in looking into alternatives?

**Comment by aktau** [comment]
Ok, seems great now. LGTM!

**Comment by justinmk** [comment]
> @justinmk Maybe we should use some of the project funds to hire a paid CI service? 

I think it's only a matter of time, but I don't think it is urgent right now. CI is messy in general, and we have an extremely sophisticated CI setup compared to most projects (open source *or* commercial).

> I've been looking at travis plans but the simplest one is $129 which seems a bit expensive.

I reached the same conclusion :)

**Comment by justinmk** [comment]
Thank you @fwalch

**Comment by jszakmeister** [comment]
> @justinmk Maybe we should use some of the project funds to hire a paid CI service? I've been looking at travis plans but the simplest one is $129 which seems a bit expensive.

I agree too, and Travis is actually not flexible enough for us.  Ideally, I'd like to build not only for Linux, but OSX, FreeBSD, and Windows as well.  I've been trying to get some equipment that we no longer need at my company (as in I co-founded it) together so that I can put together a CI system using QuickBuild (www.pmease.com).  I've used QuickBuild for over 10 years, and it's an excellent system.  We should be able to get an Open Source license from them too.  I believe I can at least cobble enough together to get build agents for Linux, OSX, and FreeBSD.  There are lots of little issues that I need to solve to help make it happen though.

One nice part of doing this is that QuickBuild can test pull requests too, so we could make sure things pass on all platforms before merging.

**Pull request merged**
