### PR TITLE
build(clint): refactor reports fetching

### PR DESCRIPTION
**Pull request by kylo252**
- replace Download.cmake with a more robust FetchErrorSuppressions module based on ExternalProjects, for better readability and error handling
- rename clint specific variables to `CLINT_`

### CODE REVIEW

**Comment by dundargoc** [comment]
I'd have to protest on this PR. I think we should work on remove clint error suppression altogether rather than improve it.

**Comment by lewis6991** [comment]
Yes. I was about to say the same thing. We need to remove the downloading entirely and keep the errors in the repo.

**Comment by lewis6991** [comment]
There's still a lot that uncrustify doesn't do which we rely on Clint for. E.g. pre-incr/decrements, true/false. I don't think we should be treating uncrustify as a replacement.

**Comment by kylo252** [comment]
> There's still a lot that uncrustify doesn't do which we rely on Clint for. E.g. pre-incr/decrements, true/false. I don't think we should be treating uncrustify as a replacement.

time to resurrect https://github.com/neovim/neovim/pull/15601 ?

**Comment by dundargoc** [comment]
@kylo252 which clint error does `clang-tidy` fix that `uncrustify` doesn't?

**Comment by kylo252** [comment]
> @kylo252 which clint error does `clang-tidy` fix that `uncrustify` doesn't?

@dundargoc, I'm not sure if that's the right question, rather it should be, just as mentioned earlier, about what uncrustify is unable to cover generally.

We do have PVS running, but it's probably a good idea to:
- have more than one linter (different feature-set)
- have a local linter in the dev environment (faster feedback loop)

**Comment by dundargoc** [comment]
But the discussion was about how we could remove clint errors, not the general benefits of introducing another linter?

Anyway, that PR needs a rebase.

**Pull request closed without merging**
