### PR TITLE
fix(query): fix unnatural order for inherits in treesitter queries

### LINKED ISSUE #20297: Unnatural order for inherits in treesitter queries
### Neovim version (nvim -v)

v0.8.0-dev-1121-g10196f1b4-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.5.1

### Terminal name/version

kitty 12.5.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

Create some queries hierarchy:
  - `queries/mylangbase/hightlights.scm`
  - `queries/mylangext/hightlights.scm` — add here on first line `; inherits: mylangbase`

### Expected behavior

Looks like it's more natural to have ability to redefine queries from `queries/mylangbase/hightlights.scm`, so queries from `queries/mylangext/hightlights.scm` should have higher priority.

### Actual behavior

Queries from `queries/mylangbase/hightlights.scm` will be executed **after** `queries/mylangext/hightlights.scm`.

That's because of order in https://github.com/neovim/neovim/blob/0760379b413ca95b80ed2970b49f14ba3b1acbf9/runtime/lua/vim/treesitter/query.lua#L128-L133

Here is the fix:
```lua
  local query_files = {}
  for _, base_lang in ipairs(base_langs) do
    local base_files = M.get_query_files(base_lang, query_name, true)
    vim.list_extend(query_files, base_files)
  end
  vim.list_extend(query_files, { base_query })
  vim.list_extend(query_files, extensions)
```

### PR DESCRIPTION
**Pull request by veged**
close #20297

### CODE REVIEW

**Comment by vigoux** [comment]
Hey thanks for the contribution! 

It seems indeed more natural this way than the other.

Could you add this to the documentation too?

**Comment by clason** [comment]
This should also apply to `extends`, right? So you can override queries for the _same_ language later, too?

**Comment by veged** [comment]
> This should also apply to `extends`, right? So you can override queries for the _same_ language later, too?

@clason I thought about that, but since `extents` is undocumented, I supposed that it's about ability to redefine order (make it reverse) — because actually it's looks like "redefinition of same lang" works just fine without any other keywords

**Comment by veged** [comment]
> Could you add this to the documentation too?

sure!

**Comment by clason** [comment]
> @clason I thought about that, but since extents is undocumented,

No, it's documented (`:h treesitter-query-modeline-extends`) and the (now) standard way of adding to queries for the same language from plugins or your own config -- without it, later queries _replace_ earlier ones (and this order is correct and should not change)!

But the order of extension is (like that of inheritance) such that later queries come earlier, so you can't replace _single_ queries.

But that can be a separate PR if it's complicated. (@vigoux ?)

**Comment by veged** [comment]
> > @clason I thought about that, but since extents is undocumented,
> 
> 
> 
> No, it's documented (`:h treesitter-query-modeline-extends`) and the (now) standard way of adding to queries for the same language from plugins or your own config -- without it, later queries _replace_ earlier ones (and this order is correct and should not change)!

hm... I'll double check this... (cause currently looks like my custom queries stacks well with defaults)

> But the order of extension is (like that of inheritance) such that later queries come earlier, so you can't replace _single_ queries.
> 
> 
> 
> But that can be a separate PR if it's complicated. (@vigoux ?)

BTW, I'm ready to fix it in one PR, if we consider that

**Comment by clason** [comment]
> hm... I'll double check this... (cause currently looks like my custom queries stacks well with defaults, without extends)

Then you are not on the latest master, because there without `extends`, queries do _not_ combine!

**Comment by vigoux** [comment]
It indeed is weird. Make sure you are on latest master. And in that case, this PR should not be needed.

**Comment by veged** [comment]
> > hm... I'll double check this... (cause currently looks like my custom queries stacks well with defaults, without extends)
> 
> Then you are not on the latest master, because there without `extends`, queries do _not_ combine!

@clason

here is my example on NVIM v0.8.0-dev-1121-g10196f1b4-dirty:
- there are some queries in `nvim-treesitter/queries/ecma/highlights.scm`
- and there are some queries in `~/.config/nvim/queries/javascript/highlights.scm` (_without_ `extends` keyword)

all queries are combines and affects editing `javascript` files — and this is correlates with my understanding of [the current master code](https://github.com/neovim/neovim/blob/7a70e9587c866c506182a32839f4c3b27b9a3b40/runtime/lua/vim/treesitter/query.lua#L120-L133), where `filename` appears in `query_files` in both cases (with/without `extends`, through `base_query` or `extensions`)

probably I misunderstand something and there is nuance in redefinition _exactly_ same query...

> (Which would explain why you didn't find it in the documentation.)

sorry, I wrote not about documentation `:h treesitter-query-modeline-extends` (which I just didn't notice 🤦‍♂️), but about [comments in code](https://github.com/neovim/neovim/blob/7a70e9587c866c506182a32839f4c3b27b9a3b40/runtime/lua/vim/treesitter/query.lua#L73-L79) (there is something about `inherits`, but nothing about `extends`)

**Comment by clason** [comment]
* `extends` is for the _same_ language, so you'd need a `ecma/highlights.scm` in your config for this to matter
* `inherits` is for a _different_ language, and should be set in the bundled `ecma/highlights.scm`

And queries for the same language are _not_ combined without `extends`.

**Comment by veged** [comment]
> * `extends` is for the _same_ language, so you'd need a `ecma/highlights.scm` in your config for this to matter
> * `inherits` is for a _different_ language, and should be set in the bundled `ecma/highlights.scm`
> 
> And queries for the same language are _not_ combined without `extends`.

I see... thank you for clarification

but initial issue with `inherits` seems to be valid — without that patch order of queries:
- `~/.config/nvim/queries/javascript/highlights.scm`
- `nvim-treesitter/queries/ecma/highlights.scm`
- `nvim-treesitter/queries/javascript/highlights.scm`

and with it it's:
- `nvim-treesitter/queries/ecma/highlights.scm`
- `nvim-treesitter/queries/javascript/highlights.scm`
- `~/.config/nvim/queries/javascript/highlights.scm`

**Comment by clason** [comment]
Yes, I agree about the issue with inherit; all I'm saying is that there is _also_ an issue with extends (possibly) ;)

**Comment by veged** [comment]
@vigoux 
> Could you add this to the documentation too?

I realised that I couldn't add anything to existing documentation in [`runtime/doc/treesitter.txt`](https://github.com/neovim/neovim/blob/7a70e9587c866c506182a32839f4c3b27b9a3b40/runtime/doc/treesitter.txt#L305-L334) — it's already sounds right and clear about inheritance

**Comment by veged** [comment]
> Yes, I agree about the issue with inherit; all I'm saying is that there is _also_ an issue with extends (possibly) ;)

I'm afraid to be wrong again 😅 but now for me order of `extends` looks fine

**Comment by clason** [comment]
That's good; if it's been tested (before and after this patch) and works as expected (which it doesn't for me; highlights in `.config/nvim` don't take precedence over highlights in `runtime`) that is all I asked for.

**Comment by clason** [comment]
@vigoux I'm fine with leaving the `extends` issue (which I believe to be specific to highlights, so probably should be handled at a different level) to a followup PR. Is _this_ fix good to merge?

**Comment by clason** [comment]
Maybe we could add a test for this, though?

**Comment by veged** [comment]
> Maybe we could add a test for this, though?

I could try, if you point me to any existing example of similar test (I'm not that familiar with codebase and approaches...)

**Comment by clason** [comment]
This is the closest one:
https://github.com/neovim/neovim/blob/8317b9199edc6936fec829f4908f9c74dc874ce4/test/functional/treesitter/highlight_spec.lua#L473-L510

**Comment by veged** [comment]
> This is the closest one:
> 
> https://github.com/neovim/neovim/blob/8317b9199edc6936fec829f4908f9c74dc874ce4/test/functional/treesitter/highlight_spec.lua#L473-L510

@clason as far as I understood those tests don't use `get_query` and `get_query_files`, so I can't "naturally" test the precedence of queries from different files...

**Comment by clason** [comment]
OK, then let's merge this now (as it is better than the status quo) and keep the test for a follow-up. Treesitter is still experimental, after all.

**Comment by clason** [comment]
And thank you!

**Pull request merged**
