### PR TITLE
[RDY] tests: Add write_file helper function.

### PR DESCRIPTION
**Pull request by lucc**
See #2722 for initial discussion.

### CODE REVIEW

**Comment by fwalch** [comment]
Looks good, but sometimes you used `write_file` and sometimes `helpers.write_file`.. I think the first should be used throughout.

**Comment by lucc** [comment]
@fwalch fixed and rebased.

**Comment by Pyrohh** [comment]
LGTM, @fwalch?

**Comment by fwalch** [comment]
LGTM.

**Comment by Pyrohh** [comment]
Thanks both.

**Pull request merged**
