### PR TITLE
[WIP/blocked] build: libuv: use CMake

### PR DESCRIPTION
**Pull request by blueyed**
Libuv has a CMake build file since v1.21.0 [1].

This removes our own `LibuvCMakeLists.txt`, which was used on Windows
only.

1: https://github.com/libuv/libuv/commit/7e6681f7

### CODE REVIEW

**Comment by blueyed** [comment]
On AppVeyor it fails:
```
[70/70] Linking C static library libuv_a.a
[68/122] cmd.exe /C "cd /D C:\projects\nvim-deps\build\src\libuv-build && C:\msys64\mingw64\bin\cmake.exe --build . --target install && C:\msys64\mingw64\bin\cmake.exe -E touch C:/projects/nvim-deps/build/src/libuv-stamp/libuv-install"
FAILED: build/src/libuv-stamp/libuv-install 
cmd.exe /C "cd /D C:\projects\nvim-deps\build\src\libuv-build && C:\msys64\mingw64\bin\cmake.exe --build . --target install && C:\msys64\mingw64\bin\cmake.exe -E touch C:/projects/nvim-deps/build/src/libuv-stamp/libuv-install"
ninja: error: unknown target 'install'
```
https://ci.appveyor.com/project/neovim/neovim/builds/25874876/job/jf31rtil1d8kc84q#L1221

**Comment by erw7** [comment]
> On AppVeyor it fails:

@blueyed The current libuv CMakeLists.txt does not contain installation rules on Windows. A pull request for that has been created in libuv/libuv#1886 and libuv/libuv#2113.

**Comment by justinmk** [comment]
This might be unblocked since https://github.com/tree-sitter/tree-sitter/releases was merged.

Else https://github.com/libuv/libuv/pull/1886#issuecomment-539712174 suggests that https://github.com/libuv/libuv/pull/2504 will help.

**Comment by blueyed** [comment]
@justinmk 
> This might be unblocked since https://github.com/tree-sitter/tree-sitter/releases was merged.

How is tree-sitter related here?

**Comment by justinmk** [comment]
@blueyed that must have been a copy-paste mistake. I think I was referring to a libuv PR.

**Comment by clason** [comment]
Superseded by #19632

**Pull request closed without merging**
