### PR TITLE
[WIP] tui: use env to config cursor shape

### PR DESCRIPTION
**Pull request by splinterofchaos**
Some terminals which set `$TERM` to `xterm` do so claiming to be xterm emulators, but don't actually support all xterm codes. For example, gnome-terminal doesn't support the codes to change the cursor shape and instead prints garbage on the screen.

I'm posting this a bit early partially for my TODO list. Also, maybe there's a better way. 

Needs documentation.

### CODE REVIEW

**Comment by jck** [comment]
Gnome terminal(and all vte3 based terms) support cursor shape escape codes starting from VTE3 v0.39.

**Comment by jck** [comment]
iTerm2 also supports xterm style esc codes(DECSCUSR) for cursor shape. AFAIK, Konsole is the only widely used emulator that needs proprietary esc codes for cursor shape.

**Comment by justinmk** [comment]
I think https://github.com/neovim/neovim/pull/2660 addressed this? Can we close this for now?

**Comment by splinterofchaos** [comment]
Unfortunately, I can't test it right now, but I don't think #2660 fixes this. The problem is that gnome-terming 2.x and below doesn't accept xterm codes for changing the cursor shape. You have to run a program:
```
$ gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape <VALUE>
```
so, right now I'm thinking we'd need a cursor shape provider for use with TUI's, I don't think I actually created an issue for this, so I'll do that now.

**Comment by justinmk** [comment]
I think this is mostly addressed. Closing this to focus on your other PRs, eventually.

**Pull request closed without merging**
