### PR TITLE
[WIP] test: win: enable unit tests

### PR DESCRIPTION
**Pull request by janlazo**
Unit tests rely on posix api and lua ffi so they don't run on Appveyor. msvc is not setup properly such that even if it is installed properly, gcc options are passed to cl.exe (msvc) so the compilation fails.

Goal is to create (or reuse) a posix api and make unit tests work with gcc (or clang). 

If time permits, support msvc (setup in ci/build.bat and update test/unit/preprocess.lua to pass the right arguments).

The following are tests that I expect to fail on Windows:
- https://github.com/neovim/neovim/pull/7846#issuecomment-357504968
  - filepaths with spaces

### CODE REVIEW

**Comment by justinmk** [comment]
msvc support would be a huge gain!

**Comment by janlazo** [comment]
I'd like some assistance for gcc/clang because `cimport` isn't working. Not sure about the table format for the compiler paths in preprocess.lua are for but `/usr/bin/env` isn't available on Windows.

For now, I'll setup msvc and try Visual C++ 2015 or 2017.

**Comment by janlazo** [comment]
Need `Msvc:init_defines()`

```
[00:10:35] -- Output to stderr:
[00:10:35] Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
[00:10:35] Copyright (C) Microsoft Corporation.  All rights reserved.
[00:10:35] 
[00:10:35] cl : Command line warning D9002 : ignoring unknown option '-dM'
[00:10:35] '-Daligned(ARGS)='
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] '-Daligned(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] '-Daligned(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] config'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] src'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/build/config'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/src'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] '-std=c99'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/build/include'': No such file or directory
[00:10:35] tmp_pseudoheader.h
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-std=c99'': No such file or directory
[00:10:35] Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
[00:10:35] Copyright (C) Microsoft Corporation.  All rights reserved.
[00:10:35] 
[00:10:35] cl : Command line warning D9002 : ignoring unknown option '-dM'
[00:10:35] '-Daligned(ARGS)='
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] '-Daligned(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] '-Daligned(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] config'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] src'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/build/config'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/src'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] '-std=c99'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/build/include'': No such file or directory
[00:10:35] tmp_empty_pseudoheader.h
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-std=c99'': No such file or directory
[00:10:35] Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
[00:10:35] Copyright (C) Microsoft Corporation.  All rights reserved.
[00:10:35] 
[00:10:35] '-Daligned(ARGS)='
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] '-Daligned(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] '-Daligned(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] '-D__attribute__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-Daligned(ARGS)='': No such file or directory
[00:10:35] '-D__asm(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__attribute__(ARGS)='': No such file or directory
[00:10:35] '-D__asm__(ARGS)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm(ARGS)='': No such file or directory
[00:10:35] '-D__inline__='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__asm__(ARGS)='': No such file or directory
[00:10:35] '-DEXTERN=extern'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D__inline__='': No such file or directory
[00:10:35] '-DINIT(...)='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DEXTERN=extern'': No such file or directory
[00:10:35] '-D_Thread_local='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-DINIT(...)='': No such file or directory
[00:10:35] '-D_Nullable='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Thread_local='': No such file or directory
[00:10:35] '-D_Nonnull='
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nullable='': No such file or directory
[00:10:35] config'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-D_Nonnull='': No such file or directory
[00:10:35] src'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/build/config'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/src'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/.deps/usr/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] include'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/msys64/mingw64/include'': No such file or directory
[00:10:35] '-std=c99'
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-IC:/projects/neovim/build/include'': No such file or directory
[00:10:35] tmp_pseudoheader.h
[00:10:35] c1: fatal error C1083: Cannot open source file: ''-std=c99'': No such file or directory
[00:10:35] busted: error: Cannot load helper script: C:/projects/neovim/test/unit/preload.lua
```

**Comment by janlazo** [comment]
Did I break something?

```
[00:08:32] -- Output to stderr:
[00:08:32] .\test\unit\formatc.lua:158: bad argument #2 to 'TokeniseC' (string expected, got nil)
[00:08:32] C:/projects/neovim/.deps/usr/bin/luajit.exe: C:\projects\neovim\.deps\usr\bin\lua\busted\runner.lua:99: attempt to concatenate local 'message' (a table value)
[00:08:32] stack traceback:
[00:08:32] 	C:\projects\neovim\.deps\usr\bin\lua\busted\runner.lua:99: in function 'fn'
[00:08:32] 	C:\projects\neovim\.deps\usr\bin\lua\mediator.lua:103: in function 'publish'
[00:08:32] 	...eovim\.deps\usr\bin\lua\busted\modules\helper_loader.lua:21: in function 'helperLoader'
[00:08:32] 	C:\projects\neovim\.deps\usr\bin\lua\busted\runner.lua:147: in function <C:\projects\neovim\.deps\usr\bin\lua\busted\runner.lua:11>
[00:08:32] 	...deps\usr\lib\luarocks\rocks\busted\2.0.rc12-1\bin\busted:3: in main chunk
[00:08:32] 	[C]: at 0x00401f80
```

**Comment by janlazo** [comment]
In preprocess.lua, is `cc:dependencies` for debugging only?

**Comment by janlazo** [comment]
@ZyX-I `io.popen` succeeds for non-existent program on Windows.

**Comment by ZyX-I** [comment]
@janlazo Lua standard library is crap. `io.popen` uses shell, so it should *always* succeed as long as it can invoke shell, not sure what it would do if it couldn’t though. But I do not quite understand what your comment is about exactly.

**Comment by janlazo** [comment]
@ZyX-I It's the behavior with `version:close()` in `find_best_cc`. The `version` file handle does not become `nil` so the first compiler is always used.

**Comment by ZyX-I** [comment]
@janlazo Code AFAIK was not written by me, and `find_best_cc` is nonsense: if `version` *is* `nil` then `if` would not execute because `(nil):close()` throws an error (and lua has yet another strange behaviour here: `nil:close()` yields parser error, not the same runtime error as `(nil):close()`). Better drop any lua standard functions to invoke commands and use luv everywhere, AFAIK it is already in a list of dependencies so it has to be installed.

**Comment by ZyX-I** [comment]
@janlazo And `version` by no means can *become* `nil`, it is either `nil` from the beginning or not `nil`, `foo:meth()` can only alter what is stored in `foo` variable by adding a bunch of low-level hacks, and AFAIK lua does not have anything like Python’s `__bool__()` method: only `nil` and `false` are false and nothing else ever.

**Comment by janlazo** [comment]
@ZyX-I Is there a refactor to use `luv` instead of standard library, at least for unit tests? I prefer not do it here but I can help out in another PR.

As for `version` becoming nil, I assumed it to be the desired behaviour because of http://lua-users.org/lists/lua-l/2013-12/msg00526.html except this doesn't work on Windows.

**Comment by ZyX-I** [comment]
@janlazo Code you mentioned will neither make find_best_cc work. And it does not exactly return `nil`, it throws an error. You can actually create similar code for Windows, but I do not like the idea, and it is not exactly correct on linux as well: file *may* be executable, but not readable, though it limits kinds of executables: specifically I am able to run ELF this way as it is mostly executed by kernel, but not able to run `#!/bin/sh` script as `sh` needs to read it. Just as well it could be readable, but not executable, none of standard library functions are really helpful for implementing `exists()`.

You don’t need to do global refactoring, just get rid of `io.popen` in one place where it is not sufficient and check for UV_ENOENT or whatever libuv returns if you attempt to run a command which could not be found.

**Pull request closed without merging**
