### PR TITLE
fix strict-overflow cases

### PR DESCRIPTION
**Pull request by justinmk**
Moving forward with #683  now that we have decent test coverage and a mature build.

### CODE REVIEW

**Comment by justinmk** [comment]
Merged. Thanks @ony

**Comment by Pyrohh** [comment]
Apologies if this was discussed previously and I missed something, but should we also be building with `-Wstrict-overflow[=n]` now that this has been done?

**Comment by justinmk** [comment]
@Pyrohh could be worth a try. Not sure if there were other cases.

**Comment by ony** [comment]
@justinmk thank you

**Pull request closed without merging**
