### PR TITLE
vim-patch:8.1.2228,8.2.{36,37,766,810}

### PR DESCRIPTION
**Pull request by janlazo**

### CODE REVIEW

**Comment by tjdevries** [comment]
Hey @janlazo what's the best way to review these? I'd be happy to help get them merged since it's super helpful that you're doing them, but I'm not an expert in this area.

**Comment by janlazo** [comment]
For each vim-patch commit, compare it with the referenced vim patch in the commit message and verify that the vim patch is ported correctly. There is `./scripts/vim-patch -r ${PR_NUMBER}`, where `${PR_NUMBER}` is the github pull request number, to automate this process.

Some vim patches are trivial enough to port with minimal changes (ie. indent, move C,Vimscript code to a different line or file). Some vim patches are [N/A](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#na-not-applicable-patches) (ie. `#ifdef FEAT_`, Vim CI config, GUI, README, test dump files, encryption, python/ruby/perl C code, channels, jobs, terminal) but it depends on Neovim's API and features. Some vim patches may depend on earlier vim patches so you may have to use `./scripts/vim-patch -l -- ${VIM_REPO_PATH}` to get a list of missing patches for some filepath in Vim repo or `./scripts/vim-patch.sh -m ${VIM_PATCH_TAG}` to get a list of missing patches for files modified by the vim patch.

A vim patch could be merged but `./scripts/vim-patch.sh` lists it because the merged vim patch was not documented in the commit message such as code for [:Termdebug](https://github.com/neovim/neovim/pull/8364). Those merged vim patches become N/A. To resolve them, I went through some `:Termdebug` patches in https://github.com/neovim/neovim/pull/12329 to create another `version.c` PR, like https://github.com/neovim/neovim/pull/12196, when it is merged. `version.c` PRs are where N/A patches are included them but it depends on vim patches for the current `v:version` which is why merged v8.1.x and v8.2.x patches cannot be detected via `has()` at the moment.

This PR should be easy to review because there is little difference between my commits and the referenced vim patches. `:Termdebug` can be an issue because there are many undocumented v8.1.x patches merged but the differences are on Neovim job/terminal api and the Toolbar feature, https://github.com/neovim/neovim/issues/11513.

**Comment by tjdevries** [comment]
Awesome, thanks for the detailed message. I can try and do that sometime this week. Please ping me if I forget. Sometimes my TODO's on github get lost. Thanks again for all the PRs!

**Comment by tjdevries** [comment]
@teto or @h-michael can one of you check this as well? I tried the steps above and it seems to make sense to me, but would be good for someone else to confirm if possible.

Thanks again @janlazo . If no one has time to look at it, this seems all good to me from what I can tell.

**Comment by teto** [comment]
reviewed as well and it's good. Thanks again !

**Pull request merged**
