### PR TITLE
'mousescroll' option: number of lines to scroll with wheel

### PR DESCRIPTION
**Pull request by qstrahl**
Based on #1288 from @cepko33

TODO:

- [x] Add the option
- [x] Document the option
- [ ] Test the option manually
- [ ] Create a new automated test
- [ ] Update `:help scroll-mouse-wheel`
- [ ] Update `:help vim-differences`

Low-effort, good first issue for anyone interested.

### CODE REVIEW

**Comment by blueyed** [comment]
I think this should be suggested as a new feature for Vim.

I've not really followed the discussion, but think https://github.com/neovim/neovim/pull/1288#issuecomment-59099421 still applies: i.e. it would be possible to control this already.

**Comment by qstrahl** [comment]
@blueyed See the discussion in #2262

**Comment by justinmk** [comment]
Why 'mouselines' instead of 'mousescroll'? The latter has parallel with existing 'scroll' option, whereas the former has a misleading parallel with the exisiting 'lines' option.

**Comment by qstrahl** [comment]
Honestly, just because the short version `mouses` is already taken by `mouseshape`. That's a good point about the inconsistency, though; I agree. What's the convention in cases where the obvious short name is taken? Next character, `mousec`?

**Comment by justinmk** [comment]
I'm not aware of any convention for option short names. In fact 'mouse' has no short name. 

This is not something users would be typing in manually very often, so it doesn't need a short name.

**Comment by qstrahl** [comment]
Sounds good to me!

**Comment by justinmk** [comment]
continued at https://github.com/neovim/neovim/pull/12355

**Pull request closed without merging**
