### PR TITLE
Add method call support for more built-ins: vim-patch:8.1.{1336,1952,1961,1984}

### PR DESCRIPTION
**Pull request by seandewar**
Still more patches to comb through after this one, but we're getting there :+1:

Adds support for all (applicable) functions in the patches.
Only exception is v8.1.1987, which requires `+clientserver` for `remote_*()`, which we don't have yet.

Though we support every function in these patches, we can't fully port every patch due to missing tests for:

- `filereadable()`
- `confirm()`
- `getcwd()`
- `index()`
- `iconv()`

### CODE REVIEW

**Comment by janlazo** [comment]
Does this obsolete https://github.com/neovim/neovim/pull/15194?

**Comment by seandewar** [comment]
Yes, I think it's ported correctly and [the tests succeed](https://github.com/seandewar/neovim/actions/runs/1175808951).

(That being said, I didn't know that PR already existed -- sorry 😅)

**Comment by seandewar** [comment]
Interestingly, `eval.txt` seems to have the docs for the `remote_*()` functions, but `+clientserver` was removed (though there seems to be plans to bring it back). 🤔

Shouldn't these be removed? Seems they may have been included on purpose in #8725, for example.

**Comment by bfredl** [comment]
Let's consider it when we get to actually implement our version of clientserver  :)

**Comment by janlazo** [comment]
Needs a rebase.
I'm prioritizing https://github.com/neovim/neovim/pull/15364.

**Comment by seandewar** [comment]
> vim-patch:8.1.1954: more functions can be used as a method
> ...
> listener_*() and js_*() functions are N/A.

Is `test_listener.vim` actually N/A?
Or are there plans to maybe support a shim at some point?

**Comment by justinmk** [comment]
> Is `test_listener.vim` actually N/A?

Yes.

> Or are there plans to maybe support a shim at some point?

No.

**Comment by janlazo** [comment]
listener api is not N/A so i stopped reviewing halfway in the commits.

**Comment by justinmk** [comment]
> listener api is not N/A

what do you mean exactly? Why do we need it?

**Comment by janlazo** [comment]
If `:h api-buffer-updates` or some Lua API covers all usecases from Vimscript listener API and Vimscript listener API cannot be polyfilled by Neovim's API, then the listener API is N/A.
Vim's internal implementation of listener API is probably N/A.

I suspect that it can be polyfilled for simple cases but matching Vim's behavior on autocmd,completion events is non-trivial because of Neovim's event loop and the state of Vim's codebase since the listener API was implemented.

High effort and low benefit (ie. API compatiblity) makes it low priority. Work on it only if other major features have been ported or marked N/A.

**Comment by justinmk** [comment]
> I suspect that it can be polyfilled ... High effort and low benefit (ie. API compatiblity) makes it low priority.

I would even say it is anti-priority. Spending our time supporting polyfiles is not great for users even, harder to understand 1.7 interfaces for Nvim instead of 1.

**Comment by seandewar** [comment]
Rebased to resolve conflicts. Should I also mark v8.1.1954 as a partial port instead for now?

**Comment by janlazo** [comment]
yes

**Comment by janlazo** [comment]
When were `has('lua')` and `test_lua.vim` marked N/A? Vim's lua interface wasn't fully ported but that doesn't imply N/A.

**Comment by seandewar** [comment]
Corrected the message. :+1:

**Comment by justinmk** [comment]
> `if_mzscheme` is N/A though, right?

yes

**Review by janlazo — APPROVED** [review]
LGTM

**Comment by seandewar** [comment]
Note to self: 8.1.1925 can be fully ported after #15952.

**Pull request merged**
