### PR TITLE
[WIP] coverage: use fastcov

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by justinmk** [comment]
What is the maximum benefit from using this third-party thing? AFAICT, maybe 30 seconds saved in 1 CI job.

The cost is that we are using third-party / non-standard tool, which apparently needs fixes already.

**Comment by blueyed** [comment]
Yeah, I've hoped it would have been a drop-in replacement..
It's not only for CI: I've started adding Makefile targets to generate html coverage reports etc locally, and noticed that gcovr is rather slow.
But I'd rather stick with it for now - given the issues with fastcov.

(gcovr also is a 3rd party tool in this regard, but more stable apparently)

**Comment by justinmk** [comment]
> I've started adding Makefile targets to generate html coverage reports etc locally,

But why? How many people will use that? Open issues/enhancements are things that people actually have asked for. Particularly things in the 0.4 milestone are very high-priority.

Code coverage is working as well as needed. We don't need to spend more time on it.

**Comment by blueyed** [comment]
Closing for now.

**Pull request closed without merging**
