### PR TITLE
fix doc codeblock

### PR DESCRIPTION
**Pull request by kaddkaka**
- doc: mark example in remote_plugin with >plugin

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but we don't make such changes to doc files owned by Vim.

**Comment by kaddkaka** [comment]
@clason oh, i looked in vim but couldn't find a file with similar name. How can I tell that this is from vim?

**Comment by clason** [comment]
Sorry, that was my bad; I misread the file name.

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/25171

**Pull request closed without merging**
