### PR TITLE
fix(terminal): use coladvance() to calculate buffer cursor position

### LINKED ISSUE #14671: Cursor jumps back too far in terminal on <C-\\><C-n> after entering unicode chars
- `nvim --version`:
```
NVIM v0.5.0-dev+43956dea5
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210529-91425-1jzy01u/build/config -I/tmp/neovim-20210529-91425-1jzy01u/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210529-91425-1jzy01u/build/src/nvim/auto -I/tmp/neovim-20210529-91425-1jzy01u/build/include
Compiled by [redacted]

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-43956de_2/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: macOS Big Sur 11.2.3
- Terminal name/version: iTerm build 3.4.6
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

```viml
:term
:set number " Not 100% sure if this is necessary but it seems to be to repro this for me with NORC
```

Then press `A`, enter `ééüü`, and then do `<C-\\><C-n>` to get out of insert mode.

### Actual behaviour

The cursor jumps back to the first `é` character.

Note that this also seems to occur with any non-ASCII char, like `∫`, `µ`, etc.

Additionally, the offset seems to increase the more of these chars are entered. For example, after entering `µµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµ` and getting out of insert mode with `<C-\\><C-n>`, the cursor jumps to about the middle of that set of chars.

### Expected behaviour

The cursor should only go back to the first `ü` character, like it does with the non-unicode `eeuu`.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #14671

### CODE REVIEW

**Comment by zeertzjq** [comment]
IME preedit position is occasionally off by one...

**Comment by zeertzjq** [comment]
I wrote 18 tests. 3 of them still pass if the changes are reverted because they are handled correctly before. Other 15 fail.
```
[ RUN      ] buffer cursor position is correct in terminal without number column at the end of a line with no multibyte characters or trailing spaces: 43.12 ms OK
[ RUN      ] buffer cursor position is correct in terminal without number column near the end of a line with no multibyte characters or trailing spaces: 44.33 ms OK
[ RUN      ] buffer cursor position is correct in terminal without number column near the beginning of a line with no multibyte characters or trailing spaces: 40.84 ms OK

[  FAILED  ] 1 test, listed below:
[  FAILED  ] test/functional/terminal/cursor_spec.lua @ 809: buffer cursor position is correct in terminal with number column near the beginning of a line with double-cell multibyte characters and no trailing spaces
test/functional/terminal/cursor_spec.lua:822: Row 6 did not match.
Expected:
  |{7:  1 }                                                                  |
  |{7:  2 }                                                                  |
  |{7:  3 }                                                                  |
  |{7:  4 }                                                                  |
  |{7:  5 }Entering Ex mode.  Type "visual" to go to Normal mode.            |
  |*{7:  6 }:哦^哦{2:哦}哦哦哦哦哦                                                 |
  |                                                                      |
Actual:
  |{7:  1 }                                                                  |
  |{7:  2 }                                                                  |
  |{7:  3 }                                                                  |
  |{7:  4 }                                                                  |
  |{7:  5 }Entering Ex mode.  Type "visual" to go to Normal mode.            |
  |*{7:  6 }:哦哦{2:^哦}哦哦哦哦哦                                                 |
  |                                                                      |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:595: in function '_wait'
	test/functional/ui/screen.lua:362: in function 'expect'
	test/functional/terminal/cursor_spec.lua:822: in function <test/functional/terminal/cursor_spec.lua:809>

[  ERROR   ] 14 errors, listed below:
[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 294: buffer cursor position is correct in terminal without number column at the end of a line with single-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e61e3a8) {
  [1] = 6
 *[2] = 9 }
Expected:
(table: 0x7fb40e61de90) {
  [1] = 6
 *[2] = 17 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:305: in function <test/functional/terminal/cursor_spec.lua:294>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 330: buffer cursor position is correct in terminal without number column near the end of a line with single-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e26a9e8) {
  [1] = 6
 *[2] = 7 }
Expected:
(table: 0x7fb40e26a410) {
  [1] = 6
 *[2] = 13 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:341: in function <test/functional/terminal/cursor_spec.lua:330>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 366: buffer cursor position is correct in terminal without number column near the beginning of a line with single-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e3bc000) {
  [1] = 6
 *[2] = 3 }
Expected:
(table: 0x7fb40e3bba98) {
  [1] = 6
 *[2] = 5 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:377: in function <test/functional/terminal/cursor_spec.lua:366>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 402: buffer cursor position is correct in terminal without number column at the end of a line with double-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e1c01b8) {
  [1] = 6
 *[2] = 16 }
Expected:
(table: 0x7fb40e1bfc88) {
  [1] = 6
 *[2] = 25 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:413: in function <test/functional/terminal/cursor_spec.lua:402>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 438: buffer cursor position is correct in terminal without number column near the end of a line with double-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e504760) {
  [1] = 6
 *[2] = 13 }
Expected:
(table: 0x7fb40e5041f8) {
  [1] = 6
 *[2] = 19 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:449: in function <test/functional/terminal/cursor_spec.lua:438>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 474: buffer cursor position is correct in terminal without number column near the beginning of a line with double-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e78bf90) {
  [1] = 6
 *[2] = 4 }
Expected:
(table: 0x7fb40e8882d8) {
  [1] = 6
 *[2] = 7 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:485: in function <test/functional/terminal/cursor_spec.lua:474>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 521: buffer cursor position is correct in terminal with number column at the end of a line with no multibyte characters or trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e3e50e8) {
  [1] = 6
 *[2] = 8 }
Expected:
(table: 0x7fb40e3eb3e0) {
  [1] = 6
 *[2] = 9 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:532: in function <test/functional/terminal/cursor_spec.lua:521>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 557: buffer cursor position is correct in terminal with number column near the end of a line with no multibyte characters or trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e2d03a0) {
  [1] = 6
 *[2] = 8 }
Expected:
(table: 0x7fb40e404210) {
  [1] = 6
 *[2] = 7 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:568: in function <test/functional/terminal/cursor_spec.lua:557>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 593: buffer cursor position is correct in terminal with number column near the beginning of a line with no multibyte characters or trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40df9e220) {
  [1] = 6
 *[2] = 7 }
Expected:
(table: 0x7fb40df9dc80) {
  [1] = 6
 *[2] = 3 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:604: in function <test/functional/terminal/cursor_spec.lua:593>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 629: buffer cursor position is correct in terminal with number column at the end of a line with single-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e729b88) {
  [1] = 6
 *[2] = 13 }
Expected:
(table: 0x7fb40e8089b8) {
  [1] = 6
 *[2] = 17 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:640: in function <test/functional/terminal/cursor_spec.lua:629>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 665: buffer cursor position is correct in terminal with number column near the end of a line with single-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e1abaa8) {
  [1] = 6
 *[2] = 11 }
Expected:
(table: 0x7fb40e1ab4a8) {
  [1] = 6
 *[2] = 13 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:676: in function <test/functional/terminal/cursor_spec.lua:665>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 701: buffer cursor position is correct in terminal with number column near the beginning of a line with single-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e22b4e0) {
  [1] = 6
 *[2] = 7 }
Expected:
(table: 0x7fb40e22afc8) {
  [1] = 6
 *[2] = 5 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:712: in function <test/functional/terminal/cursor_spec.lua:701>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 737: buffer cursor position is correct in terminal with number column at the end of a line with double-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e27c530) {
  [1] = 6
 *[2] = 19 }
Expected:
(table: 0x7fb40e27c018) {
  [1] = 6
 *[2] = 25 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:748: in function <test/functional/terminal/cursor_spec.lua:737>

[  ERROR   ] test/functional/terminal/cursor_spec.lua @ 773: buffer cursor position is correct in terminal with number column near the end of a line with double-cell multibyte characters and no trailing spaces
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7fb40e39a5a0) {
  [1] = 6
 *[2] = 16 }
Expected:
(table: 0x7fb40df1db30) {
  [1] = 6
 *[2] = 19 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/cursor_spec.lua:784: in function <test/functional/terminal/cursor_spec.lua:773>


 1 FAILED TEST
 14 ERRORS
```

**Comment by zeertzjq** [comment]
The cursor in on the column in Windows tests... Nvim's Ex mode shouldn't allow that...

**Comment by zeertzjq** [comment]
> The cursor is on the colon in some tests in Windows CI... Nvim's Ex mode shouldn't allow that...

May be a problem with `<Left>` and `<RIght>` keys.

**Comment by zeertzjq** [comment]
> The cursor is on the colon in some tests in Windows CI... Nvim's Ex mode shouldn't allow that...

Maybe it is an encoding problem. I'll disable the failing tests on Windows.

**Comment by zeertzjq** [comment]
I also added mappings to `<Left>` and `<Right>` as they may have problems on Windows.

**Comment by zeertzjq** [comment]
Note: This also makes IME preedit position correct on terminal lines with multibyte characters.

Before:
Screenshot_20211208_065943

After:
Screenshot_20211208_070030

I guess this is because after #9883, window cursor position is recalculated from buffer cursor position later.

Buffer cursor and IME preedit position is still wrong on lines with trailing whitespace (#16234), and I'll fix that in a separate PR (#16423). That fix is currently not working on Windows.

**Comment by jamessan** [comment]
Awesome tests.  Thanks!

**Pull request merged**
