### PR TITLE
docs: fix small typo in lsp docs.

### PR DESCRIPTION
**Pull request by adrian5**
I saw the [comment](https://github.com/neovim/neovim/pull/19589#issuecomment-1200398561) regarding typo collection. Not sure if that implies these small PRs shouldn't be made, or just that they get absorbed into another big PR.

### CODE REVIEW

**Comment by clason** [comment]
the latter, but you should make it from the latest master.

**Comment by adrian5** [comment]
I knew this might come up (GitHub's fetch/sync being unsuitable), but couldn't remember how to do it right.

Do I need to clone the neovim/neovim repo to do a proper rebase? And if so, how can I keep my fork up-to-date when I do PRs like this?

**Comment by clason** [comment]
You can go to your fork's Github page and click on the `Sync fork` button:
Screenshot 2022-08-15 at 17 05 55
 
then `git pull -a` (or just `git pull` from `master`), then `git rebase master` from your branch, then `git push -f`.

**Comment by dundargoc** [comment]
Thank you for your contribution! We collect all typo fixes and similar small fixes into a single pull request and merge it once it gets big enough: https://github.com/neovim/neovim/pull/19798

**Pull request closed without merging**
