### PR TITLE
[RFC] Migrate legacy tests 92 and 93

### PR DESCRIPTION
**Pull request by glts**
Migrates legacy tests 92 and 93, which are the same test with different file encoding. Two down, more to go.

### CODE REVIEW

**Comment by Pyrohh** [comment]
@glts I'd like to get acquainted with reviewing these tests, as you have a few of them in open PRs. Besides what's mentioned on the wiki (https://github.com/neovim/neovim/wiki/Unit-tests), is there anything you read before doing these conversions?

**Comment by glts** [comment]
@Pyrohh I'd *love* to get rid of the legacy tests, so your offer to help is much appreciated.

I don't have any reading materials handy, though I did read through the busted docs, and I had to quickstart my Lua.

I can tell you how I do these conversions: First I run the conversion script to get started. The Lua spec you then get often (always?) doesn't run because there are things like `:q!` in the original test. This kills the test runner. The actual conversion work is a mixture of trying to get it to run at all, and actually manually stepping through the test steps (keystrokes) in a Vim/Neovim instance to understand what it's doing, to see the state progression. The old test format is so outrageously opaque that I add comments for all logical steps along the way. Sometimes the generated Lua is a little off (using `feed` instead of `execute` etc.) and needs fix+prettify.

Let me know if you'd like something explained, and keep in mind that I'm a new contributor so there's always the chance I'm doing something wrong (the usual 'it's you not me' :smile: ).

**Comment by Pyrohh** [comment]
Thanks @glts, I'll get around to reading those docs.

**Comment by justinmk** [comment]
Merged. The comments in the new tests are valuable, thanks.

**Pull request closed without merging**
