### PR TITLE
[RFC] vim-patch:7.4.562

### PR DESCRIPTION
**Pull request by glts**
```
Problem:    Segfault with wide screen and error in 'rulerformat'. (Ingo Karkat)
Solution:   Check there is enough space. (Christian Brabandt)
```

Reproduce with https://groups.google.com/d/msg/vim_dev/bGrnJq7sFH4/cAJPyZmvNXkJ
Best try in a new terminal (messed up my prompt and colours).

This fixes the segfault, but the display is still messed up, unlike in Vim. The patch applied relatively cleanly, so that might be a different problem.

https://github.com/vim/vim/commit/v7-4-562

Original patch:

``` diff
diff --git a/src/nvim/buffer.c b/src/nvim/buffer.c
--- a/src/nvim/buffer.c
+++ b/src/nvim/buffer.c
@@ -4409,6 +4409,8 @@ get_rel_pos(wp, buf, buflen)
     long   above; /* number of lines above window */
     long   below; /* number of lines below window */

+    if (buflen < 3) /* need at least 3 chars for writing */
+   return;
     above = wp->w_topline - 1;
 #ifdef FEAT_DIFF
     above += diff_check_fill(wp, wp->w_topline) - wp->w_topfill;
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -10588,7 +10588,8 @@ win_redr_ruler(wp, always)
        this_ru_col = (WITH_WIDTH(width) + 1) / 2;
    if (this_ru_col + o < WITH_WIDTH(width))
    {
-       while (this_ru_col + o < WITH_WIDTH(width))
+       /* need at least 3 chars left for get_rel_pos() + NUL */
+       while (this_ru_col + o < WITH_WIDTH(width) && RULER_BUF_LEN > i + 4)
        {
 #ifdef FEAT_MBYTE
        if (has_mbyte)
diff --git a/src/nvim/version.c b/src/nvim/version.c
--- a/src/nvim/version.c
+++ b/src/nvim/version.c
@@ -742,6 +742,8 @@ static char *(features[]) =
 static int included_patches[] =
 {   /* Add new patch number below this line */
 /**/
+    562,
+/**/
     561,
 /**/
     560,
```

### CODE REVIEW

**Comment by Pyrohh** [comment]
I can only reproduce this using `-fstack-protector-strong` (we should probably be building with that if available): https://gist.github.com/Pyrohh/88a918e525b7a45554db

> This fixes the segfault, but the display is still messed up, unlike in Vim. The patch applied relatively cleanly, so that might be a different problem.

Yes indeed... not quite sure what to do. If we're just concerned about the issue addressed by 562, then LGTM.

**Comment by justinmk** [comment]
@Pyrohh In your gist, I see `__fortify_fail`. Does it detect it if you disable FORTIFY_SOURCE?

    rm -r build && make cmake CFLAGS='-U_FORTIFY_SOURCE' && make

**Comment by Pyrohh** [comment]
@justinmk It does not (just to be sure, `nm` and `strings` don't show any instance of `fortify`).

**Comment by justinmk** [comment]
@jszakmeister The QB build appears to be failing on a post-build step: http://neovim-qb.szakmeister.net/build/869/log

I assume this isn't related to this PR, and it appears the tests passed.

**Comment by Pyrohh** [comment]
@justinmk @glts Perhaps this should be merged? Despite the screen corruption, most anything is better than a segfault.

**Comment by justinmk** [comment]
Merged. Thanks both :)

**Pull request closed without merging**
