### PR TITLE
[RFC] Jumplist placement (jumporder)

### PR DESCRIPTION
**Pull request by Ainoss**
ref #6284 

Option `jumporder` added to drop jumplist tail (current and followed jumps). 
Therefore, new jump will be placed right at current jumplist position, not at the tail of jumplist.

Simple test also added.

### CODE REVIEW

**Comment by justinmk** [comment]
- I would suggest "jump" is the option name prefix, not suffix. E.g. 'jumporder'.
    - Is there any other behavior that might be requested in the future, which would suggest the option should be integer instead of boolean?
- Need also a test in `shada/merging_spec.lua` testing shada with the option enabled, covering the concerns mentioned in https://github.com/neovim/neovim/issues/6284#issuecomment-286892209.
- Need a test that verifies behavior of `:keepjumps` with this option.

**Comment by Ainoss** [comment]
About integer option: I can't mind any other behavior. There are little question about keeping or dropping current jump (one pointed by jump index). In this pr I suggest to drop it. Anyway, I think it is not a case to support option for it. 
May be anybody have some thoughts about other behavior of jumplist?

Ok,  I will rename option and add mentioned tests in new commits.

**Comment by Ainoss** [comment]
I think the test for `:keepjumps` is unnecessary, because `setpcmark()` function is skipped in this case. So behavior of this command is not affected by suggested commits.
Added test for shada merging is a bit synthetic, like other tests in merging_spec.

Option renamed to `jumporder`

**Comment by justinmk** [comment]
> because setpcmark() function is skipped in this case.

Well, the test will verify that :) And it serves to test that the logic added here doesn't have some weird mistake if keepjumps is used.

**Comment by justinmk** [comment]
Anyone have a better idea for the option name or a different approach for enabling this?

**Comment by Ainoss** [comment]
Keepjumps test already added. Hope it cover enough cases.
Also I fixed strange fails in legacy tests, caused by not alphabetical order of options.

Waiting for your comments

**Comment by justinmk** [comment]
- Needs a doc update. 
- Option name still isn't good. I don't have a better idea but someone needs to think of one.

Please re-open a new PR if you want to continue this.

**Comment by epheien** [comment]
> * Needs a doc update.
> * Option name still isn't good. I don't have a better idea but someone needs to think of one.
> 
> Please re-open a new PR if you want to continue this.

`jumplistopt=trim`
what about this option name?
If you accept, I will continue this pr, and update a doc.

long time ago, I have the same problem of @Ainoss, and make a patch for vim, but had been rejected.
Currently, I use getjumplist() api to emulator jumplist trim behave.
Sadly story.

**Pull request closed without merging**
