### PR TITLE
[WIP] Update the cursor shape inmediately on mode change

### PR DESCRIPTION
**Pull request by fmoralesc**
I only tried this locally as a test, so no wonder it makes the tests crash and burn. I'll investigate later when I get home.

### CODE REVIEW

**Comment by Pyrohh** [comment]
@fmoralesc could you move your branch to a different remote? You accidentally pushed to `neovim/neovim` :)

**Comment by fmoralesc** [comment]
Yeah, I did this change using github's editor and blundered out. Could you delete this branch for me (I can't atm)? I'll reopen later today.

**Comment by Pyrohh** [comment]
It won't let me delete it until I close this PR, so I'll do that. I made a copy of the change below.

```diff
From 751d1cc92a5d789fa981bbb142fbefd4e6428eb6 Mon Sep 17 00:00:00 2001
From: Felipe Morales <hel.sheep@gmail.com>
Date: Mon, 27 Jul 2015 09:53:28 -0300
Subject: [PATCH] Update the cursor shape inmediately on mode change

---
 src/nvim/tui/tui.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 2659125..684b9ef 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -425,6 +425,7 @@ static void tui_mode_change(UI *ui, int mode)
     }
   }
   data->showing_mode = mode;
+  ui_refresh();
 }
 
 static void tui_set_scroll_region(UI *ui, int top, int bot, int left,
```

**Comment by fmoralesc** [comment]
Thanks, bro.

**Comment by Pyrohh** [comment]
Sure thing, bruh :sunglasses:.

**Pull request closed without merging**
