### PR TITLE
Add g:ruby_host_prog

### PR DESCRIPTION
**Pull request by wsdjeg**
I do not have `neovim-ruby-host` in my PATH, maybe provide a glob var `g:ruby_host_prog` will be better.

### CODE REVIEW

**Comment by stephenprater** [comment]
So unfortunately, I'm not sure this is a good solution.   The way the host works, it's going to run it in the context of the shell you're running Neovim in - so if that shell is running ruby 2.3.1, that's the ruby host it will attempt to use.  Providing a global variable (I presume you'd be setting this in your .vimrc?) breaks a Ruby-land assumption about how Gems should work.

If you do a `gem install neovim-ruby` it should add that gem's bin direction to your PATH.

**Comment by wsdjeg** [comment]
I can not use `gem install neovim-ruby`, but `gem install neovim`. and I have add below into bashrc.
```sh
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
```

**Comment by wsdjeg** [comment]
@stephenprater how about the latest commit?

**Comment by stephenprater** [comment]
Sorry for the delay - I think maybe we're treating the symptom rather than the underlying problem here.  If you install the neovim gem with `gem install` what does `which neovim-ruby-host` return?

**Comment by mbainter** [comment]
@stephenprater I hate to reopen something old like this, but I'm wondering if you could expand on this a bit?  I have some pretty heavy use of rbenv across multiple versions for various projects. I would rather not have to install the neovim gem in every one just to use ruby plugins while editing those files.

Is there something inherent to the differences between how the ruby and python interpreters function that prevent using a similar methodology to g:python_host_prog and g:python3_host_prog? It seems like maybe that's what you might've been getting at above, but it wasn't clear (at least to me).

**Pull request closed without merging**
