### PR TITLE
syntax/markdown: Fix code block detection and categorization

### PR DESCRIPTION
**Pull request by zhimsel**
Please see individual commit messages for more detailed notes.

Happy to address any feedback and RFCs.

### CODE REVIEW

**Comment by jamessan** [comment]
Thanks for the help!

We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason.

Please send this change to the upstream repo -- https://github.com/tpope/vim-markdown.  If it gets accepted there, we'll get it the changes from our routine runtime file updates.

**Comment by zhimsel** [comment]
Understood, I'll create a PR there. Thanks!

**Comment by Shatur95** [comment]
@jamessan, I see that current markdown syntax in this repo is very old. Will it be updated just before the 0.5 release or is it worth submitting a PR now?

**Comment by zhimsel** [comment]
FYI the PR at Tim Pope's repo was just merged. What's the timeline/process for that change getting included in nvim?

**Pull request closed without merging**
