### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mhanberg**
overriden -> overridden

### CODE REVIEW

**Comment by kuator** [comment]
Engllsh is confusing

**Comment by mhanberg** [comment]
Bump

**Comment by vigoux** [comment]
I think that for most part, this could/should be done upstream, could you confirm the types are there too?

**Comment by rktjmp** [comment]
AFAICT

| file                                        | upstream                       |
| --                                          | --                             |
| runtime/autoload/vimexpect.vim              | file does not exist upstream   |
| runtime/doc/api.txt                         | file does not exist upstream   |
| runtime/doc/eval.txt                        | section dos not exist upstream |
| runtime/syntax/8th.vim                      | **can be patched upstream**        |
| runtime/syntax/reva.vim                     | already patched upstream       |
| src/nvim/api/vim.c                          | file does not exist upstream   |
| src/nvim/api/window.c                       | file does not exist upstream   |
| src/nvim/viml/parser/expressions.c          | file does not exist upstream   |
| test/functional/api/vim_spec.lua            | file does not exist upstream   |
| test/functional/lua/vim_spec.lua            | file does not exist upstream   |
| test/functional/terminal/highlight_spec.lua | file does not exist upstream   |

Search seems to confirm: https://github.com/vim/vim/search?q=%22overriden%22

**Comment by vigoux** [comment]
Then it'll have to be sent upstream first.

**Comment by mhanberg** [comment]
Thanks for following up on this when I did not. I'll try and get that patch into vim.

**Comment by rktjmp** [comment]
Good luck https://github.com/vim/vim/pull/2383 (2017)

**Comment by mhanberg** [comment]
Submitted a patch for the file that is upstream: https://github.com/vim/vim/pull/8398

**Comment by rktjmp** [comment]
Seems this was accepted upstream and the issue can be closed?

**Comment by vigoux** [comment]
From what I remember, we already had a PR fixing a whole bunch of typos.
Could you confirm that this specific typo has been fixed in master?

**Comment by rktjmp** [comment]
Actually this PR includes a patch to https://github.com/neovim/neovim/blob/2475161defb775b0104dbe8b504a5299044584a2/runtime/doc/eval.txt#L11884 which is nvim specific so will need to merge (with alteration?) or a new PR.

**Comment by janlazo** [comment]
Redo as a vim-patch PR with a separate commit for the neovim-specific typos.

**Pull request closed without merging**
