### PR TITLE
vim-patch:ce001a337e28

### PR DESCRIPTION
**Pull request by clason**
Update runtime files
https://github.com/vim/vim/commit/ce001a337e28fa368f40ac6422835d730fb8ebb1

### CODE REVIEW

**Review by gpanders — APPROVED** [review]
🚀

**Review by zeertzjq — APPROVED** [review]

**Review by seandewar — APPROVED** [review]
The `vimStdPlugin` change in `syntax/vim.vim` is technically relevant (termdebug); looks like we're a bit behind with changes to that line?

Otherwise LGTM

**Comment by clason** [comment]
Isn't that line autogenerated? That's why I didn't touch it...

**Comment by seandewar** [comment]
Pretty sure it's not

**Comment by seandewar** [comment]
Yeah, I'd cherry-pick the whole thing (even with `:Winbar`)

**Comment by clason** [comment]
Done!

**Review by seandewar — APPROVED** [review]

**Pull request merged**
