### PR TITLE
travis: Enable ccache

### PR DESCRIPTION
**Pull request by jamessan**

### CODE REVIEW

**Comment by justinmk** [comment]
do we need any of these tweaks: https://github.com/urho3d/Urho3D/blob/da6fd0e3a4d79b639660d197c94b0c8cb792c587/.travis.yml#L379

Do we need `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache` (https://stackoverflow.com/a/37828605/152142) or [this](https://stackoverflow.com/a/36515503/152142) ?

**Comment by jamessan** [comment]
`CMAKE_CXX_COMPILER_LAUNCHER` could be enabled if we're using a new enough CMake.  Although setting `$CCACHE_CC` may be simpler.

Neovim's code doesn't require any of the `$CCACHE_SLOPPINESS` stuff, but it may help for third-party.

Enabling compression would probably be useful, too.

**Comment by justinmk** [comment]
Looks like it's working! Build failures are unrelated, caused by the new python release (my fault).

```
before_cache.sh: ccache stats
cache directory                     /home/travis/.ccache
cache hit (direct)                    13
cache hit (preprocessed)               0
cache miss                           328
called for link                       80
called for preprocessing             146
preprocessor error                     5
bad compiler arguments                 6
autoconf compile/link                 18
no input file                         20
files in cache                       898
cache size                          14.2 Mbytes
max cache size                     512.0 Mbytes
```

I see this also (macOS build): 

```
[0Ktravis_fold:end:before_cache
[0Ktravis_fold:start:cache.2
[0Kstore build cache
travis_time:start:022589f0
[0K
travis_time:end:022589f0:start=1525136887082723000,finish=1525136887097674000,duration=14951000
[0Ktravis_time:start:00d39adc
[0K[32;1mchange detected (content changed, file is created, or file is deleted):

/Users/travis/.ccache/3/4/eb1521922a6dbf6e4f7758a0432717-651334.o
/Users/travis/.ccache/3/4/eb1521922a6dbf6e4f7758a0432717-651334.stderr
/Users/travis/.ccache/3/5/99f751ea511db384c7595360e4cd7d-48924.manifest
/Users/travis/.ccache/3/CACHEDIR.TAG
/Users/travis/.ccache/3/a/8373c478104a2dd2622a4912221890-381280.manifest
...
```

IIUC it looks like travis's cache is affected by ccache. I guess that's intentional, it's from the `ccache: true` directive?

**Comment by jamessan** [comment]
> IIUC it looks like travis's cache is affected by ccache. I guess that's intentional

Yeah, otherwise we couldn't leverage the ccache artifacts across builds. :)

I opted not to add the XCode complications to our CMake files for now.  I wanted to keep the changes fairly simple and isolated.

One last thing that I thought of is to guard the `ccache -s` calls against failing the build, to be on the safe side.  I'll push an update for that and then I'm done unless there's more feedback.

**Pull request merged**
