### PR TITLE
vim-patch:8.2.3295: 'cursorline' should not apply to 'breakindent'

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:    'cursorline' should not apply to 'breakindent'.
Solution:   Make 'cursorline' apply to 'breakindent' and 'showbreak'
            consistently. (closes vim/vim#8684)
https://github.com/vim/vim/commit/4f33bc20d7d5444e44d13f954e8219ad1abd26ef

### CODE REVIEW

**Comment by zeertzjq** [comment]
I added some tests for `'cursorlineopt'` `screenline` in `highlight_spec.lua`. Not sure whether these test are enough.

**Comment by zeertzjq** [comment]
There seems to some problem with quickfix.

**Comment by zeertzjq** [comment]
> There seems to be some existing problem with `QuickFixLine`: in a Quickfix window, if `cursorline` is set, `cursorlineopt` contains `line`, `CursorLine` contains `gui=underline`, `QuickFixLine` doesn't contain `gui` and cursor is on current Quickfix line, current Quickfix line has an underline when `CursorLine` is low priority, but has no underline when `CursorLine` is high priority (high-priority `CursorLine` isn't applied to current Quickfix line at all). I guess this is caused by [1248178](https://github.com/neovim/neovim/commit/12481781a0215c2ba0ab250d9cfdb9a082ab495a).
> 
> Vim always overrides `QuickFixLine` with `CursorLine`, so this is not applicable to Vim.

A question arises here: should `QuickFixLine` also override `CursorLine` when `cursorlineopt` contains `screenline`?

**Comment by justinmk** [comment]
> should `QuickFixLine` also override `CursorLine` when `'cursorlineopt'` contains `screenline`

IMO no. Often quickfix opens with the first line highlighted as QuickFixLine, and having it get clobbered by CursorLine is very annoying: can't tell which line is selected in the quickfix (the entire point of QuickFixLIne).

**Comment by justinmk** [comment]
tested locally, LGTM. Thanks so much for this followup @zeertzjq

**Pull request merged**
