### PR TITLE
[RFC] clint.py stuff

### PR DESCRIPTION
**Pull request by ghost**
commit messages:

```
  clint.py: don't print `--help` output to stderr

a) It's not an error
b) It requires manual redirection of stderr into stdout ('2>&1') in
   order to be viewed with a pager, which it warrants given how long the
   help message is.
```

```
 cmake: Make `make lint` less verbose

It unnecessarily complicates spotting linter errors, as they're usually
surrounded by a bunch of lines saying "Done processing ... ".
```

To put it another way, I don't like my terminal being filled three times over when running `make lint`, which happens regardless of there being linter errors or not. I figure that `RunLint.cmake` is very simple, so I don't see much point in having the contents of `clint-ignored-files.txt` printed on every `lint` invocation for manual verification.

ping @fwalch

### CODE REVIEW

**Comment by fwalch** [comment]
Hmm.. what about the following (on top of your PR):

```diff
diff --git a/clint.py b/clint.py
index d913fa8..097b54f 100755
--- a/clint.py
+++ b/clint.py
@@ -3077,11 +3077,12 @@ def PrintUsage(message):
     Args:
       message: The optional error message.
     """
-    sys.stderr.write(_USAGE)
     if message:
+        sys.stderr.write(_USAGE)
         sys.exit('\nFATAL ERROR: ' + message)
     else:
-        sys.exit(1)
+        sys.stdout.write(_USAGE)
+        sys.exit(0)
 
 
 def PrintCategories():
@@ -3089,7 +3090,7 @@ def PrintCategories():
 
     These are the categories used to filter messages via --filter.
     """
-    sys.stderr.write(''.join('  %s\n' % cat for cat in _ERROR_CATEGORIES))
+    sys.stdout.write(''.join('  %s\n' % cat for cat in _ERROR_CATEGORIES))
     sys.exit(0)
 
 
@@ -3123,8 +3124,7 @@ def ParseArguments(args):
 
     for (opt, val) in opts:
         if opt == '--help':
-            sys.stdout.write(_USAGE)
-            sys.exit(0)
+            PrintUsage(None)
         elif opt == '--output':
             if val not in ('emacs', 'vs7', 'eclipse'):
                 PrintUsage('The only allowed output formats are emacs,'
```

The `PrintCategories` output can be invoked with `./clint.py --filter=`, which is a bit strange, but I guess not an error (hence the change to stdout). If it were an error, the return code should not be 0.

**Comment by Pyrohh** [comment]
> Hmm.. what about the following (on top of your PR):

Sure, repushed with those changed.

**Comment by Pyrohh** [comment]
cc @fwalch, I'll merge this if you give the OK.

**Comment by fwalch** [comment]
LGTM :+1:

**Comment by Pyrohh** [comment]
Thanks.

**Pull request merged**
