### PR TITLE
(Draft): Adding new highlight group in 'highlight_defs.h' makes (only) Windows CI halt

### PR DESCRIPTION
**Pull request by echasnovski**

### CODE REVIEW

**Comment by echasnovski** [comment]
Previous bisecting showed that this halts specifically after executing [this line](https://github.com/neovim/neovim/blob/afd0c648a89ff88c9bff1b24c37e139813ec13c9/test/functional/ui/embed_spec.lua#L101).

**Comment by echasnovski** [comment]
Note for the future: if/when this issue is resolved, add new core highlight group for `FloatFooter` (introduced in #24739) by committing similar code from this PR (but with correct highlight group name).

**Comment by zeertzjq** [comment]
The hang happens inside `read()` in `read_eintr()` when one more RPC notification is sent before reading stdin.

**Comment by zeertzjq** [comment]
It seems that `Session:_blocking_request()` hangs on Windows if it receive a notification.

**Comment by zeertzjq** [comment]
I think this hang happens because of the following deadlock:
1. After receiving `nvim_ui_attach`, server calls `uv_write()` multiple times, the last of which is the response.
2. Server doesn't call `uv_run()` enough number of times for the response to be actually written to stdout.
3. Server is waiting to read from file descriptor 3, but client needs to wait for the response to arrive before writing to the pipe.

**Comment by zeertzjq** [comment]
The following change can fix this deadlock, but I'm not sure if it will cause performance problems:
```diff
diff --git a/src/nvim/event/wstream.c b/src/nvim/event/wstream.c
index 3f8bccb56..3666ca437 100644
--- a/src/nvim/event/wstream.c
+++ b/src/nvim/event/wstream.c
@@ -10,6 +10,7 @@
 #include "nvim/event/wstream.h"
 #include "nvim/log.h"
 #include "nvim/macros.h"
+#include "nvim/main.h"
 #include "nvim/memory.h"
 
 #define DEFAULT_MAXMEM 1024 * 1024 * 2000
@@ -97,6 +98,7 @@ bool wstream_write(Stream *stream, WBuffer *buffer)
   }
 
   stream->pending_reqs++;
+  uv_run(&main_loop.uv, UV_RUN_DEFAULT);
   return true;
 
 err:
@@ -148,6 +150,7 @@ static void write_cb(uv_write_t *req, int status)
   }
 
   xfree(data);
+  uv_stop(&main_loop.uv);
 }
 
 void wstream_release_wbuffer(WBuffer *buffer)
```

**Pull request closed without merging**
