### PR TITLE
fix #14722

### LINKED ISSUE #14722: Neovim displays Arabic or Persian characters incorrectly
- `nvim --version`:
NVIM v0.5.0-dev+1052-g271cec291
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/khanj/Documents/git/neovim/build/config -I/home/khanj/Documents/git/neovim/src -I/home/khanj/Documents/git/neovim/.deps/usr/include -I/usr/include -I/home/khanj/Documents/git/neovim/build/src/nvim/auto -I/home/khanj/Documents/git/neovim/build/include
Compiled by root@PooyanPC

- Operating system/version:
`Linux PooyanPC 5.10.32-1-MANJARO #1 SMP Wed Apr 21 14:54:10 UTC 2021 x86_64 GNU/Linux`
- Terminal name/version:
Suckless st terminal
- `$TERM`: `st-256color`

[ ] `vim -u NORC` (version: 8.2 ) behaves differently

### Steps to reproduce using `nvim -u NORC`
`nvim -u NORC arabicOrPersianFile.txt`
Set righttoleft in neovim:
`:set rl`

### Actual behaviour
When opening Arabic or Persian files in Neovim and setting `righttoleft` variable to true, there is some problems in showing characters.
As you may know in both of these languages when 2 characters come together, in some cases the displaying for the first character sould change.
For example when appending character `ی` to `ت` it should be displayed like `تی`, but in Neovim it would appear something like this `ت ی` as two separate characters(I inserted space here to demonstrate the issue, Neovim inserts no space, It only does not join characters either). This behavior does not happen in vim and characters are displayed correctly.
For which I have found out any character which comes after `ک` and `پ` and `گ` are affected and would not join with these characters. And also any character which comes before `ی` and should be joined, would not join.

For example:
`گ` + `ا` Should be displayed like ‍‍`گا`
But is being displayed like `گ ا`

`گ` + `ظ` Should be displayed like ‍‍`گط`
But is being displayed like `گ ط`

`ک` + `ا` Should be displayed like ‍‍`کا`
But is being displayed like `ک ا`

`م` + `ی` Should be displayed like ‍‍`می`
But is being displayed like `م ی`

`ت` + `ی` Should be displayed like ‍‍`تی`
But is being displayed like `ت ی`

Left side is vim which has correct behavior, right side is neovim which has wrong behavior in lines which marked with XXX.
Image

You can paste this text in vim and nvim to see the difference(don't forget to `set rl` to switch to righttoleft mode):
ت + ا = تا
ب + ا = با
**پ + ا = پا XXX**
**گ + ا = گا XXX**
**ک + ا = گا XXX**

**ت + ی = تی XXX**
**ب + ی = بی XXX**
**پ + ی = پی XXX**
**گ + ی = گی XXX**
**ک + ی = کی XXX**

### PR DESCRIPTION
**Pull request by TheKhanj**
Fixes bug for persian characters which me myself reported earlier.

### CODE REVIEW

**Comment by jamessan** [comment]
Would you mind sending this fix to Vim?  This should also be a problem there, so it would be good to get it fixed in both projects and then we can port the vim patch.

**Comment by jamessan** [comment]
Oh, I just saw your report says Vim works correctly. Are we missing relevant fixes from Vim, then?

**Comment by janlazo** [comment]
Patch v8.1.1038.

**Comment by TheKhanj** [comment]
> Oh, I just saw your report says Vim works correctly. Are we missing relevant fixes from Vim, then?

As @janlazo mentoined Vim has the patch for it.
Patch v8.1.1038.

**Comment by janlazo** [comment]
Therefore, this PR should be replaced with a vim-patch PR that includes patch v8.1.1038.

**Comment by zeertzjq** [comment]
#19285

**Pull request closed without merging**
