### PR TITLE
[RFC] Speed up garbage collection (Issue 1687).

### PR DESCRIPTION
**Pull request by oni-link**
Speed up garbage collection. (Issue https://github.com/neovim/neovim/issues/1687)

For garbage collection all lists are kept in first_list, a list of all
lists.

free_unref_items() searches through first_list and removes unreferenced
lists from it (by calling list_free(..., FALSE)). But after a list was
removed, the search continues from the beginning of first_list (not sure
how many lists were really removed and where to continue in first_list).

This is not necessary anymore since vim-patch [7.0.135](https://code.google.com/p/vim/source/detail?r=v7-0-135) , because a call to
list_free(...,FALSE) makes sure, that no other lists (and dictionaries)
are freed. So we always know, that the next list in first_list is
still valid (allocated or NULL) and can be used to continue the search.

Likewise for dictionaries.

Original patch by Ariya Mizutani
https://groups.google.com/forum/#!searchin/vim_dev/GC/vim_dev/DBYOdHQWvqY/1WH04_dwETIJ

### CODE REVIEW

**Comment by Shougo** [comment]
:+1:

**Comment by justinmk** [comment]
Very nice. What are the before/after results for the test case in the vim_dev link?

**Comment by demonking** [comment]
@justinmk what do you mean by vim_dev?

In the Link the Result was the following:

Without this patch, it take 100 seconds to finish GC. And if set 100000 instead of 50000, vim often hangs. With this patch, it take just 0.133967 seconds.

**Comment by oni-link** [comment]
When I run the following script in nvim/vim the times shown are similar (0.074/0.070). But vim (or unpatched nvim) blocks for me >28s after showing the output time.

```viml
let s:hoge = {}
let s:fuga = {}
let s:arr = []

function! Prepare() abort " {{{
  let s:hoge.a1 = map(range(1, 50000), '{}')
  let s:hoge.a2 = map(range(1, 50000), '{}')
  let s:hoge.a3 = map(range(1, 50000), '{}')
  let s:hoge.fuga = s:fuga
  let s:fuga.hoge = s:hoge
endfunction " }}}

function! Release() abort " {{{
  let s:arr = s:hoge.a2
  unlet s:hoge
  unlet s:fuga
endfunction " }}}

let start = reltime()
call Prepare()
call Release()
call garbagecollect()
echomsg string(reltimestr(reltime(start)))

**Comment by fmoralesc** [comment]
Perhaps this would help in the locking scenario in issue #1776 (when there is no corruption).

**Comment by justinmk** [comment]
Tried this patch, but it didn't appear to change the behavior of #1176.

**Comment by fmoralesc** [comment]
Just tried it, and no, it doesn't seem to help with locking in #1776. 

I tried @oni-link script, and I can confirm his report.

**Comment by justinmk** [comment]
> This is not necessary anymore since vim-patch 7.0.135, because a call to list_free(...,FALSE) makes sure, that no other lists (and dictionaries) are freed. So we always know, that the next list in first_list is still valid (allocated or NULL) and can be used to continue the search.

It appears that 7.0.135 was focused on eliminating the DEL_REFCOUNT magic global and simply missed the optimization opportunity hiding in plain sight. Nice find @oni-link

**Comment by Shougo** [comment]
:+1:

**Comment by Shougo** [comment]
It is included in Vim 7.4.615.

http://ftp.vim.org/vim/patches/7.4/7.4.615

**Pull request merged**
