### PR TITLE
[RFC] vi_diff.txt pruning

### PR DESCRIPTION
**Pull request by ghost**
See the individual commit messages for rationales.

I kept some sections as it wasn't clear whether they should be removed. I think the limits stuff could be generalized in the form of `limits.txt`, given it doesn't have much relation to Vi. The `Most interesting additions` section is a bit outdated, but useful for new Vim users IMO, so I could clean that up in a later PR.

refs #2548

### CODE REVIEW

**Comment by justinmk** [comment]
:+1:

**Comment by Pyrohh** [comment]
Rebased, although it probably doesn't make a difference.

@mhinz @fmoralesc if either of you have the time, would you mind taking a look at this? I can do further work on `vi_diff.txt` after this is merged, given that some parts could be split out into other files and other parts are outdated.

**Comment by fmoralesc** [comment]
LGTM. I was wondering if there was anything of note in that long section you removed, but it's all better described elsewhere - and nobody will look here for a description of these things nowadays.

**Comment by mhinz** [comment]
> and nobody will look here for a description of these things nowadays

:+1:

**Comment by Pyrohh** [comment]
Thanks all.

**Pull request merged**
