### PR TITLE
ci/appveyor: debug failed 7z.exe in MINGW_32 build

### PR DESCRIPTION
**Pull request by justinmk**
**Update:** see support ticket: http://help.appveyor.com/discussions/problems/8193-build-cache-failure-7zexe-uncompress-error

 appveyor error:

```
Cache '.deps' - Unzipping...
Error uncompressing cache item: 7z.exe process has exited with code 2. 
Check C:\Users\appveyor\AppData\Local\Temp\1\build-cache-logs\69731fe8b0155899a53c5aabbdf609f8f85ff800.zip.001.log for details.
```

### CODE REVIEW

**Comment by bfredl** [comment]
How does helptags affect .deps caching?

**Comment by justinmk** [comment]
No idea, and looking through the appveyor history I think there are earlier cases. Still looking.

**Comment by justinmk** [comment]
Earliest case appears to be: https://ci.appveyor.com/project/neovim/neovim/build/15225

But that could have happened after the real cause was on master (but whose CI happened to succeed).

**Comment by justinmk** [comment]
I'm out of ideas. Guess I'll need to remote into the build to see the contents of `build-cache-logs`.

https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by justinmk** [comment]
seems to be fixed after appveyor cleared the backend.
 http://help.appveyor.com/discussions/problems/8193-build-cache-failure-7zexe-uncompress-error

**Pull request closed without merging**
