### PR TITLE
Fix LSP multibyte indexing

### PR DESCRIPTION
**Pull request by ndreas**
This is a follow-up to #12314. I have converted `vim.lsp.util.jump_to_location` to use the function I added in #12314, and I also refactored the function to take an LSP position instead. Finally I've added tests for `vim.lsp.util.jump_to_location`.

### CODE REVIEW

**Comment by clason** [comment]
Could you add a test for actual multibyte characters as well? Something like
```
นายสังฆภัณฑ์ เฮงพิทักษ์ฝั่ง ผู้เฒ่าซึ่งมีอาชีพเป็นฅนขายฃวด ถูกตำรวจปฏิบัติการจับฟ้องศาล ฐานลักนาฬิกาคุณหญิงฉัตรชฎา ฌานสมาธิ (Thai)

いろはにほへと ちりぬるを わかよたれそ つねならむ うゐのおくやま けふこえて あさきゆめみし ゑひもせす
안녕, 테스트
😄🍻😃
```
(pick your poison).

**Comment by ndreas** [comment]
> Could you add a test for actual multibyte characters as well? Something from
> 
> ```
> นายสังฆภัณฑ์ เฮงพิทักษ์ฝั่ง ผู้เฒ่าซึ่งมีอาชีพเป็นฅนขายฃวด ถูกตำรวจปฏิบัติการจับฟ้องศาล ฐานลักนาฬิกาคุณหญิงฉัตรชฎา ฌานสมาธิ (Thai)
> 
> いろはにほへと ちりぬるを わかよたれそ つねならむ うゐのおくやま けふこえて あさきゆめみし ゑひもせす
> 안녕, 테스트
> 😄🍻😃
> ```
> 
> (pick your poison -- the first line uses composited characters, which adds another level of difficulty; the others should all be double-width).

Sure, but I thought I did that with `local lines = {"1st line of text", "å å ɧ 汉语 ↥ 🤦 🦄"}` and checking in the last test.

**Comment by clason** [comment]
> Sure, but I thought I did that with local lines = {"1st line of text", "å å ɧ 汉语 ↥ 🤦 🦄"} and checking in the last test.

Yes, sorry, I noticed after writing this that you actually jumped past the hanzi in your test (which is why I just deleted the comment).

**Review by mfussenegger — APPROVED** [review]

**Comment by tjdevries** [comment]
LGTM. How bout you @h-michael ?

**Review by tjdevries — APPROVED** [review]

**Review by h-michael — APPROVED** [review]

**Comment by h-michael** [comment]
@ndreas Thanks :)

**Pull request merged**
