### PR TITLE
[RFC] version.c: add completed patches

### PR DESCRIPTION
**Pull request by munyari**
Patch 1603 does not appear in `version.c` or the [vim patch report](https://neovim.io/doc/reports/vimpatch/), and is in the output of the vim-patch script.
However, it seems to have already been addressed by @bfredl in #4624.

If I find any more such cases, they will be added to the PR.

### CODE REVIEW

**Comment by bfredl** [comment]
Thanks, It is correct. But please make commit/issue titles more specific like "mark timer patch 1603 as completed", it makes the issue/PR more discoverable.

**Comment by justinmk** [comment]
@bfredl I assume @munyari was following the guidance I added here: https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#na-not-applicable-patches

We don't want individual PRs for every NA patch...

**Comment by bfredl** [comment]
@justinmk it was not a NA patch, it was a mistake in my PR. We don't require people to collect mistakes from several PRs before they can point out and correct a mistake in a single PR.

**Comment by justinmk** [comment]
Ok.

**Comment by munyari** [comment]
@justinmk indeed, I figured if I found more merged patches that had not been noted I'd add them to this PR.

**Comment by munyari** [comment]
Apologies, I'll be more specific in future commit/PR titles

**Pull request merged**
