### PR TITLE
[RFC] documentation: mark balloon options as removed

### LINKED ISSUE #3523: Outdated doc regarding balloons
Setting any of `balloondelay`, `ballooneval` or `ballonexpr` is an error, but the docs do not reflect that. They should read with `Removed. |vim-differences| {Nvim}`, like other removed options.

### PR DESCRIPTION
**Pull request by Grimy**
Fixes #3523.

### CODE REVIEW

**Comment by Grimy** [comment]
It seems this PR fails some functional tests, even though it makes no code change. Is master broken?

**Comment by jszakmeister** [comment]
It's more like busted is broken.  There was a breaking change to lua_cliargs, and it's causing busted to fail because they didn't restrict the requirements.  They tried to fix it with an update to the rock spec, but that didn't do it either.  See #3525 for my proposed fix.

**Comment by Pyrohh** [comment]
Since #3525 was merged I restarted the tests.

Anyways, this should be mentioned in `vim_diff.txt`, and it looks like there's some more balloon cruft that could be removed (not sure if you didn't touch this on purpose):

```diff
diff --git a/runtime/doc/debugger.txt b/runtime/doc/debugger.txt
index f1eb563..f2b0ed0 100644
--- a/runtime/doc/debugger.txt
+++ b/runtime/doc/debugger.txt
@@ -19,7 +19,6 @@ Environment (IDE):
 	Debug Signs					|debug-signs|
 	Debug Source Highlight				|debug-highlight|
 	Message Footer					|gui-footer|
-	Balloon Evaluation				|balloon-eval|
 
 These features were added specifically for use in the Motif version of gvim.
 However, the |alt-input| and |debug-highlight| were written to be usable in
@@ -77,31 +76,5 @@ bottom of the GUI window, below the line used to display colon commands.
 
 The display of the footer is controlled by the 'guioptions' letter 'F'.
 
-
-1.5 Balloon Evaluation					*balloon-eval*
-
-This feature allows a debugger, or other external tool, to display dynamic
-information based on where the mouse is pointing.  The purpose of this feature
-was to allow Sun's Visual WorkShop debugger to display expression evaluations.
-However, the feature was implemented in as general a manner as possible and
-could be used for displaying other information as well.
-
-The Balloon Evaluation has some settable parameters too.  For Motif the font
-list and colors can be set via X resources (XmNballoonEvalFontList,
-XmNballoonEvalBackground, and XmNballoonEvalForeground).
-The 'balloondelay' option sets the delay before an attempt is made to show a
-balloon.
-The 'ballooneval' option needs to be set to switch it on.
-
-Balloon evaluation is only available when compiled with the |+balloon_eval|
-feature.
-
-The Balloon evaluation functions are also used to show a tooltip for the
-toolbar.  The 'ballooneval' option does not need to be set for this.  But the
-other settings apply.
-
-Another way to use the balloon is with the 'balloonexpr' option.  This is
-completely user definable.
-
 ==============================================================================
  vim:tw=78:sw=4:ts=8:ft=help:norl:
diff --git a/runtime/doc/various.txt b/runtime/doc/various.txt
index d34c051..47fe2a2 100644
--- a/runtime/doc/various.txt
+++ b/runtime/doc/various.txt
@@ -299,9 +299,6 @@ g8			Print the hex values of the bytes used in the
    *+acl*		|ACL| support included
 B  *+arabic*		|Arabic| language support
 N  *+autocmd*		|:autocmd|, automatic commands
-m  *+balloon_eval*	|balloon-eval| support. Included when compiling with
-			supported GUI (Motif, GTK, GUI) and either
-			Netbeans/Sun Workshop integration or |+eval| feature.
 N  *+browse*		|:browse| command
 N  *+byte_offset*	support for 'o' flag in 'statusline' option, "go"
 			and ":goto" commands.

```

There's also `v:beval_(bufnr|col|lnum|text|winnr)`, all of which seem to do nothing, although maybe they should be left for a separate PR:
```
/home/michael/src/neovim/src/nvim % grep beval_ *
eval.c:  {VV_NAME("beval_bufnr",      VAR_NUMBER), VV_RO},
eval.c:  {VV_NAME("beval_winnr",      VAR_NUMBER), VV_RO},
eval.c:  {VV_NAME("beval_lnum",       VAR_NUMBER), VV_RO},
eval.c:  {VV_NAME("beval_col",        VAR_NUMBER), VV_RO},
eval.c:  {VV_NAME("beval_text",       VAR_STRING), VV_RO},
```

**Comment by Pyrohh** [comment]
There's #2544 by the way, although no one has bothered implementing what @justinmk mentioned there yet, so I'm fine with this PR. Documentation for non-existent features is misleading.

**Comment by justinmk** [comment]
That's why I don't want to do this. It will just be reversed later.

BTW this is not really a difference from Vim, its terminal version does not support balloon. I do not think we should start listing every GUI feature in our differences doc...

**Comment by Pyrohh** [comment]
> That's why I don't want to do this. It will just be reversed later.

#2544 has been sitting around for months and there are barely any references to balloon-anything in the issue tracker, so IMO it remains to be seen if a PR like this--if merged--would be reversed anytime soon.

I figure that no documentation is better than misleading documentation, especially given the apparent lack of interest. I doubt re-adding ~80 lines of docs would take more than a few minutes if the time ever comes for it...

(I hope I'm not coming across as curt)

**Comment by justinmk** [comment]
Understood, but there are many "land mines" in the docs waiting to confuse users while we work things out, particularly GUI-related things. removing these things adds non-zero work for the future. It must not be too confusing because I have not heard any terminal-Vim users complain about the inconsistencies of Vim docs. We improved the docs and will continue to do so.

My proposal: I am 100% in favor of performing tasks that may potentially be reversed in the future as soon as we run out of other tasks.

**Comment by justinmk** [comment]
Even if you don't agree, at least this does not belong in vim-differences documentation. Just remove it totally--we have not been adding GUI differences and do not need to start.

**Comment by Pyrohh** [comment]
> Understood, but there are many "land mines" in the docs waiting to confuse users while we work things out, particularly GUI-related things. Removing these things adds non-zero work for the future. It must not be too confusing because I have not heard any terminal-Vim users complain about the inconsistencies of Vim docs. We improved the docs and will continue to do so, but there's other higher priorities for improving the documentation (better documentation of features we added such as job control, rplugin).

Indeed, there are many land mines, although those land mines haven't been dealt with yet so I'm not sure how that's related here. In other words, I don't think that it makes sense to prioritize possible (non-existent) doc improvements over a completed doc cleanup, i.e., this PR (well, not completed, but the work is mostly done).

> My proposal: I am 100% in favor of performing tasks that may potentially be reversed in the future as soon as we run out of other tasks.

I understand what you're getting at--we do indeed have a lot of possible documentation improvements which probably wouldn't be reversed ever (lots of things in the os_*.txt files to start).

> Even if you don't agree, at least this does not belong in vim-differences documentation. Just remove it totally--we have not been documenting GUI differences and do not need to start.

I think I'm fine with that.

**Comment by Grimy** [comment]
> It must not be too confusing because I have not heard any terminal-Vim users complain about the inconsistencies of Vim docs.

Well *I* was confused, and I complained in #3523.

> It will just be reversed later.

Are there really plans to reintroduce balloon support in core nvim? It seems to me that the best course of action would be to add them as a feature of an external GUI talking to nvim via msgpack. As such, their documentation does not belong in nvim. I may be mistaken, though.

**Comment by fmoralesc** [comment]
For the balloon* feature to be a viable feature *across* UIs, it should be supported by the core. Imho, this is not a feature that might be best served by the UIs themselves. Obviously, this puts a requirement on the TUI to support something like this. The underlying issue is the need to support floating "windows" across UIs. This would enable nvim to support menus in the TUI aswell, I imagine. However, I suspect this would require large changes in the display code, and that might be related to the issue of detaching buffer views from the grid (as in @tarruda's proposal of the smart ui protocol).

**Comment by justinmk** [comment]
Merged

**Pull request closed without merging**
