### PR TITLE
[release-0.4] backports

### PR DESCRIPTION
**Pull request by blueyed**
The two remaining ones: https://github.com/neovim/neovim/pulls?q=is%3Apr+milestone%3A0.4.3+is%3Aclosed+-label%3Amaintenance%3Abackported

Should we maybe push those to the release-0.4 branch directly?

### CODE REVIEW

**Comment by justinmk** [comment]
> Should we maybe push those to the release-0.4 branch directly?

Sure (why not?)

**Comment by blueyed** [comment]
> why not?

Through PRs we get extra CI confirmation (before merging) - but it should not really be required.

(and we could even force-push to the release-0.4 branch I suppose if needed?)

**Comment by blueyed** [comment]
Pushed those two directly.

**Comment by justinmk** [comment]
> (and we could even force-push to the release-0.4 branch I suppose if needed?)

Haven't considered that before. Hmm..

**Comment by blueyed** [comment]
> Haven't considered that before. Hmm..

We should try to avoid it.. and likely it is still better to fix things there then through a proper PR / CI testing then.

**Comment by blueyed** [comment]
btw: force-pushing does not work (the branch is protected).

```
remote: error: GH006: Protected branch update failed for refs/heads/release-0.4.
remote: error: Cannot force-push to a protected branch
To ssh://github.com/neovim/neovim.git
 ! [remote rejected]     release-0.4 -> release-0.4 (protected branch hook declined)
error: failed to push some refs to 'ssh://git@github.com/neovim/neovim.git'
```

(wanted to add the "[release-0.4]" tag to 4f452a6's subject)

**Comment by bfredl** [comment]
We should not force push to release branches. People should be able to fast forward pull a release branch always, just like master.

**Comment by blueyed** [comment]
Yeah.  It was just that we discussed this here before, and I've noticed it 2s after pushing, and mainly wanted to try it then.  Still OK to not do it altogether (even only after 2s).

**Pull request merged**
