### PR TITLE
tsan: Compile with -fPIE and updated clang

### PR DESCRIPTION
**Pull request by jamessan**
This fixes failures with TSAN builds like

    FATAL: ThreadSanitizer can not mmap the shadow memory (something is mapped at 0x55deea465000 < 0x7cf000000000)
    FATAL: Make sure to compile with -fPIE and to link with -pie.

### CODE REVIEW

**Comment by jamessan** [comment]
Hmm, not sure what's going on here.  The TSAN builds are failing, so I do what they say and it doesn't fix it.

**Comment by justinmk** [comment]
Yes, my only guess is that Travis has been changing stuff lately. Weird failures are appearing and disappearing.

**Comment by justinmk** [comment]
Travis [recently announced](https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/) ubuntu 14/trusty "beta" option. That's likely related to the TSan failure.

 For reference: 

- upstream report: https://github.com/google/sanitizers/issues/503
- something like [this](https://github.com/znc/znc/commit/9974b6692b3e525311bc1e235731470b1f6dda2e#diff-354f30a63fb0907d4ad57269548329e3) may fix the issue for us

**Comment by jamessan** [comment]
TSAN's working now but ASAN_UBSAN isn't ...

```
[100%] Built target nvim-test
NVIM v0.2.0-63-ga4d6192
Build type: Debug
Compilation: /usr/bin/clang-3.8 -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Werror -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -DMIN_LOG_LEVEL=0 -I/home/travis/build/neovim/neovim/build/config -I/home/travis/build/neovim/neovim/src -I/home/travis/nvim-deps/usr/include -I/usr/include -I/home/travis/build/neovim/neovim/build/src/nvim/auto -I/home/travis/build/neovim/neovim/build/include
Compiled by travis@testing-docker-918f0727-a95c-4a9b-87a2-2684b45c6ac6

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/nvim-install/share/nvim"

/home/travis/nvim-deps/usr/include/msgpack/sbuffer.h:92:37: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:46:14: note: nonnull attribute specified here
SUMMARY: AddressSanitizer: undefined-behavior /home/travis/nvim-deps/usr/include/msgpack/sbuffer.h:92:37 in 
Runtime errors detected.
```

And then there's this, which apparently isn't new but is quite odd...

```
Linking C executable ../../bin/nvim
/usr/bin/ld: Warning: size of symbol `utf8len_tab' changed from 256 in CMakeFiles/nvim.dir/main.c.o to 320 in CMakeFiles/nvim.dir/mbyte.c.o
```

**Comment by justinmk** [comment]
I don't see why the size of `utf8len_tab` would change, but we _are_ defining it twice. Maybe the warning will go away if the definition in mbyte.c is moving to globals.h.

```diff
diff --git a/src/nvim/globals.h b/src/nvim/globals.h
index 301a2c1663fe..f1e000f44a69 100644
--- a/src/nvim/globals.h
+++ b/src/nvim/globals.h
@@ -788,8 +788,20 @@ EXTERN int vr_lines_changed INIT(= 0);      /* #Lines changed by "gR" so far */
 /// Encoding used when 'fencs' is set to "default"
 EXTERN char_u *fenc_default INIT(= NULL);
 
-// To speed up BYTELEN() we keep a table with the byte lengths for utf-8
-EXTERN char utf8len_tab[256];
+// To speed up BYTELEN(): Keep a lookup table to quickly get the length in bytes
+// of a UTF-8 character from the first byte of a UTF-8 string.
+// Bytes which are illegal when used as the first byte have a 1.
+// The NUL byte has length 1.
+EXTERN char utf8len_tab[256] INIT(= {
+  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
+  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
+  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
+  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
+  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
+  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
+  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
+  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,6,6,1,1,
+});
 
 # if defined(USE_ICONV) && defined(DYNAMIC_ICONV)
 /* Pointers to functions and variables to be loaded at runtime */
diff --git a/src/nvim/mbyte.c b/src/nvim/mbyte.c
index 7be0be71067c..2ecd86974ea6 100644
--- a/src/nvim/mbyte.c
+++ b/src/nvim/mbyte.c
@@ -69,24 +69,6 @@ struct interval {
 #endif
 
 /*
- * Lookup table to quickly get the length in bytes of a UTF-8 character from
- * the first byte of a UTF-8 string.
- * Bytes which are illegal when used as the first byte have a 1.
- * The NUL byte has length 1.
- */
-char utf8len_tab[256] =
-{
-  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
-  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
-  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
-  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
-  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
-  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
-  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
-  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,6,6,1,1,
-};
-
-/*
  * Like utf8len_tab above, but using a zero for illegal lead bytes.
  */
 static uint8_t utf8len_tab_zero[256] =
```

**Comment by jamessan** [comment]
As for the UB, it's easily reproducible -- `env VIMRUNTIME=runtime ./build/bin/nvim -i newfile --cmd q`.  It happens when we try to store the (NULL) search replacement in the shada file.

**Comment by justinmk** [comment]
I wonder if that NULL write is related to https://github.com/neovim/neovim/issues/5548#issuecomment-257142878

**Comment by jamessan** [comment]
@ZyX-I Can you take a look at the shada write issue?  Passing the NULL SubString down to msgpack results in `msgpack_sbuffer_write` calling `memcpy` with a NULL second argument.  Is there a better way we should be representing that there isn't a value set for a string?

**Comment by oni-link** [comment]
@jamessan, should that not be fixed in function `msgpack_sbuffer_write(...,buf,len)`?
Calling this function with `buf=NULL` and `len=0` results (almost) always in UB.

**Comment by jamessan** [comment]
That depends on whether it makes sense to serialize NULL through msgpack.

We're asking msgpack to write our data=NULL/len=0 string, so it needs to write something otherwise it's not doing what we asked.  It can't just elide the data, because then reading back from the packed data would be missing that "piece".

**Comment by jamessan** [comment]
Ok, I've addressed the `msgpack_sbuffer_write` issue, but I would appreciate some extra eyes on it (especially if @ZyX-I can take a look).

**Comment by jamessan** [comment]
Ping?

**Comment by justinmk** [comment]
> That depends on whether it makes sense to serialize NULL through msgpack.

Isn't there a way to serialize it as msgpack "nil"? That's how `pack()` at http://msgpack.org/ddoc/ is documented to behave.

**Comment by bfredl** [comment]
The question is more if we actually consider  `(String){data=NULL, size=0}` to _semantically_ be a different value (than the empty string), and not only the efficient representation of the empty string, the later which is my understanding. At least, as a typval_T the NULL string is a representation of the empty string, ref #1981. 

If we allow `String` type to be serialized as msgpack NIL, then all clients must be updated to allow (and do something meaninful) both when `STR` and `NIL` is received, rather than being able to simply expect that a `String` is a `STR`.

**Comment by justinmk** [comment]
@bfredl Thanks, after your comment I see now that @jamessan's change is storing an entry with no body, which I guess will manifest as "empty string". 

> That depends on whether it makes sense to serialize NULL through msgpack.
> 
> We're asking msgpack to write our data=NULL/len=0 string, so it needs to write something otherwise it's not doing what we asked. It can't just elide the data, because then reading back from the packed data would be missing that "piece".

For reference: there was discussion about the need for "empty" shada entry [here](https://github.com/neovim/neovim/issues/4295#issuecomment-199512733). After reviewing, I see it is not a question of "nil" vs "empty string".

So I think there's no problem with this PR.

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
Just noticed that the changes in ca292c97688e1a43f2b29594007effb8dd141636 are included in #5119.

**Comment by jamessan** [comment]
Good, I wasn't completely off base. :-)

**Pull request merged**
