### PR TITLE
[RFC] Remove "H" flag from 'cpoptions'

### PR DESCRIPTION
**Pull request by glts**
```
                                                            *cpo-H*
            H       When using "I" on a line with only blanks, insert
                    before the last blank.  Without this flag insert after
                    the last blank.
```

Ah, this one takes the cake. Completely useless.

### CODE REVIEW

**Comment by Pyrohh** [comment]
LGTM

**Comment by Pyrohh** [comment]
@splinterofchaos can you take a look? I think this should be fine after that.

**Comment by splinterofchaos** [comment]
LGTM :+1: -- this is rather silly behaviour that could lead to unintentional trailing whitespace.

**Comment by Pyrohh** [comment]
merged, thanks @glts and @splinterofchaos.

**Comment by glts** [comment]
Thanks everybody!

**Comment by Pyrohh** [comment]
Thanks for all of the patches, it's much appreciated... although it's hard to keep up with you :D

**Comment by glts** [comment]
... and for me it's hard to keep up with the old Vim patch stream atm :sweat: :sweat_drops: the guy is on fire. But yeah, :D to you too!

**Pull request closed without merging**
