### PR TITLE
tutor: change vimtutor's arrows (--->) to symbols ✗ and ✓

### PR DESCRIPTION
**Pull request by killthekitten**
* Display ✓ or ✗ based on the line user sees
* Add vim-tutor-mode expectations to the lines marked with an arrow.
* Fix some existing expectations to behave predictably.

image

### CODE REVIEW

**Comment by killthekitten** [comment]
I'm struggling to complete the build locally and confirm all the changes, could use some help there.

**Comment by killthekitten** [comment]
Solved the build issues, tested manually against v0.3.8 (to avoid #11401) - looks good.

**Comment by justinmk** [comment]
makes sense to me. @fmoralesc ?

**Comment by fmoralesc** [comment]
LGTM, it makes all the sense.

**Pull request merged**
