### PR TITLE
[RDY] Fix "unsupported_method" error when the buffer does not have an LSP Server

### PR DESCRIPTION
**Pull request by eightpigs**
BUG from: PR #12764

### Problem

When I add the following configuration, opening a file without LSP Server (eg: abc.txt) will report an error.

```vimscript
autocmd CursorHold  <buffer> lua vim.lsp.buf.document_highlight()
autocmd CursorHoldI <buffer> lua vim.lsp.buf.document_highlight()
autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
```

error: 
```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/callbacks.lua:338: RPC[Error] code_name = MethodNotFound, message = "method textD
ocument/documentHighlight is not supported by any of the servers registered for the current buffer"
```

### Solution
`unsupported_method` should not be executed when the current buffer does not have an LSP Server.

### CODE REVIEW

**Comment by fsouza** [comment]
Oh no, sorry about that 🙈 If you want, I can dig into how to make the tests pass and add a new test for this.

**Comment by tjdevries** [comment]
Instead, can we just check if the active clients table is empty for the buffer and short circuit out?

**Comment by tjdevries** [comment]
(the only thing to consider is, it is a bit difficult to determine whether a request failed for some reason or because no servers were attached... but it's probably fine)

**Comment by eightpigs** [comment]
> Instead, can we just check if the active clients table is empty for the buffer and short circuit out?

Yes,Indeed. I pushed.

**Pull request merged**
