### PR TITLE
ci: add MSan job

### PR DESCRIPTION
**Pull request by zeertzjq**
Currently doesn't work with either PUC Lua or LuaJIT:
- With LuaJIT build fails at installing LuaRocks.
- With PUC Lua build fails at generating headers.

### CODE REVIEW

**Comment by zeertzjq** [comment]
MSan log with LuaJIT:
```
==325184==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x56154c4d71ac in lj_prng_condition **/.deps/build/src/luajit/src/lj_prng.c:66:7
    #1 0x56154c4d71ac in lj_prng_seed_secure **/.deps/build/src/luajit/src/lj_prng.c:253:3
    #2 0x56154c4d7c35 in lua_newstate **/.deps/build/src/luajit/src/lj_state.c:206:8
    #3 0x56154c5336de in luaL_newstate **/.deps/build/src/luajit/src/lib_aux.c:354:7
    #4 0x56154c4c3d95 in main **/.deps/build/src/luajit/src/luajit.c:574:7
    #5 0x7f408816328f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #6 0x7f4088163349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #7 0x56154c432434 in _start (**/.deps/usr/bin/luajit-2.1.0-beta3+0x29434) (BuildId: a342532b01e140549a222e2ea5b99f6289d234a4)

SUMMARY: MemorySanitizer: use-of-uninitialized-value **/.deps/build/src/luajit/src/lj_prng.c:66:7 in lj_prng_condition
```

MSan log with PUC Lua:
```
==332223==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55e3da329c0e in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:82:12
    #1 0x55e3da2c2a20 in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55e3da360a46 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55e3da3606e0 in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7f8b3c7e1b5c in lmpack_pack lmpack.c
    #5 0x55e3da2e54f5 in luaD_precall **/.deps/build/src/lua/src/ldo.c:320:9
    #6 0x55e3da350d31 in luaV_execute **/.deps/build/src/lua/src/lvm.c:591:17
    #7 0x55e3da2e8e5a in luaD_call **/.deps/build/src/lua/src/ldo.c:378:5
    #8 0x55e3da2cab2f in f_call **/.deps/build/src/lua/src/lapi.c:800:3
    #9 0x55e3da2e072e in luaD_rawrunprotected **/.deps/build/src/lua/src/ldo.c:116:3
    #10 0x55e3da2eb3dd in luaD_pcall **/.deps/build/src/lua/src/ldo.c:464:12
    #11 0x55e3da2ca61c in lua_pcall **/.deps/build/src/lua/src/lapi.c:821:12
    #12 0x55e3da2b7937 in docall **/.deps/build/src/lua/src/lua.c:102:12
    #13 0x55e3da2b6a98 in handle_script **/.deps/build/src/lua/src/lua.c:250:14
    #14 0x55e3da2b3f79 in pmain **/.deps/build/src/lua/src/lua.c:362:17
    #15 0x55e3da2e54f5 in luaD_precall **/.deps/build/src/lua/src/ldo.c:320:9
    #16 0x55e3da2e8dcf in luaD_call **/.deps/build/src/lua/src/ldo.c:377:7
    #17 0x55e3da2cb5ad in f_Ccall **/.deps/build/src/lua/src/lapi.c:846:3
    #18 0x55e3da2e072e in luaD_rawrunprotected **/.deps/build/src/lua/src/ldo.c:116:3
    #19 0x55e3da2eb3dd in luaD_pcall **/.deps/build/src/lua/src/ldo.c:464:12
    #20 0x55e3da2cae54 in lua_cpcall **/.deps/build/src/lua/src/lapi.c:856:12
    #21 0x55e3da2b2f47 in main **/.deps/build/src/lua/src/lua.c:387:12
    #22 0x7f8b3c4f028f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #23 0x7f8b3c4f0349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #24 0x55e3da221414 in _start (**/.deps/usr/bin/lua+0x28414) (BuildId: bc2d20e977c910ec9e1593f1fce8260198ce91a1)

SUMMARY: MemorySanitizer: use-of-uninitialized-value **/.deps/build/src/lua/src/lstring.c:82:12 in luaS_newlstr
```

**Comment by zeertzjq** [comment]
MSan log with LuaJIT:
```
==337211==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x56206da2c593 in lj_prng_condition **/.deps/build/src/luajit/src/lj_prng.c:66:7
    #1 0x56206da2c593 in lj_prng_seed_secure **/.deps/build/src/luajit/src/lj_prng.c:253:3
    #2 0x56206da2d96e in lua_newstate **/.deps/build/src/luajit/src/lj_state.c:206:8
    #3 0x56206dac680f in luaL_newstate **/.deps/build/src/luajit/src/lib_aux.c:354:7
    #4 0x56206da0fdc6 in main **/.deps/build/src/luajit/src/luajit.c:574:7
    #5 0x7f8872f6028f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #6 0x7f8872f60349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #7 0x56206d97e434 in _start (**/.deps/usr/bin/luajit-2.1.0-beta3+0x29434) (BuildId: 25617a27e0e75bb0ecc3d5d5a6113b5c6b6db8cf)

  Uninitialized value was created by an allocation of 'prng' in the stack frame of function 'lua_newstate'
    #0 0x56206da2d8d0 in lua_newstate **/.deps/build/src/luajit/src/lj_state.c:200

SUMMARY: MemorySanitizer: use-of-uninitialized-value **/.deps/build/src/luajit/src/lj_prng.c:66:7 in lj_prng_condition
```

MSan log with PUC Lua:
```
==344267==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55d26c5ab68f in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:82:12
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c
    #5 0x55d26c536703 in luaD_precall **/.deps/build/src/lua/src/ldo.c:320:9
    #6 0x55d26c5f0188 in luaV_execute **/.deps/build/src/lua/src/lvm.c:591:17
    #7 0x55d26c53ce08 in luaD_call **/.deps/build/src/lua/src/ldo.c:378:5
    #8 0x55d26c50929f in f_call **/.deps/build/src/lua/src/lapi.c:800:3
    #9 0x55d26c52e10b in luaD_rawrunprotected **/.deps/build/src/lua/src/ldo.c:116:3
    #10 0x55d26c540e05 in luaD_pcall **/.deps/build/src/lua/src/ldo.c:464:12
    #11 0x55d26c5089c6 in lua_pcall **/.deps/build/src/lua/src/lapi.c:821:12
    #12 0x55d26c4e51e2 in docall **/.deps/build/src/lua/src/lua.c:102:12
    #13 0x55d26c4e34fd in handle_script **/.deps/build/src/lua/src/lua.c:250:14
    #14 0x55d26c4dee0e in pmain **/.deps/build/src/lua/src/lua.c:362:17
    #15 0x55d26c536703 in luaD_precall **/.deps/build/src/lua/src/ldo.c:320:9
    #16 0x55d26c53cd4c in luaD_call **/.deps/build/src/lua/src/ldo.c:377:7
    #17 0x55d26c50a80d in f_Ccall **/.deps/build/src/lua/src/lapi.c:846:3
    #18 0x55d26c52e10b in luaD_rawrunprotected **/.deps/build/src/lua/src/ldo.c:116:3
    #19 0x55d26c540e05 in luaD_pcall **/.deps/build/src/lua/src/ldo.c:464:12
    #20 0x55d26c5098c1 in lua_cpcall **/.deps/build/src/lua/src/lapi.c:856:12
    #21 0x55d26c4dd313 in main **/.deps/build/src/lua/src/lua.c:387:12
    #22 0x7ffaab4cf28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #23 0x7ffaab4cf349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 768945cdf5e5796c2ab39f38ed160748fd94d12e)
    #24 0x55d26c44b414 in _start (**/.deps/usr/bin/lua+0x28414) (BuildId: 9786e47d0e8b40086d5e730f1b96f6fdb8984719)

  Uninitialized value was stored to memory at
    #0 0x55d26c5ab307 in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:81:7
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c

  Uninitialized value was stored to memory at
    #0 0x55d26c5ab307 in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:81:7
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c

  Uninitialized value was stored to memory at
    #0 0x55d26c5ab307 in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:81:7
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c

  Uninitialized value was stored to memory at
    #0 0x55d26c5ab307 in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:81:7
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c

  Uninitialized value was stored to memory at
    #0 0x55d26c5ab307 in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:81:7
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c

  Uninitialized value was stored to memory at
    #0 0x55d26c5ab307 in luaS_newlstr **/.deps/build/src/lua/src/lstring.c:81:7
    #1 0x55d26c4fa20f in lua_pushlstring **/.deps/build/src/lua/src/lapi.c:448:3
    #2 0x55d26c60d257 in emptybuffer **/.deps/build/src/lua/src/lauxlib.c:402:5
    #3 0x55d26c60cd0c in luaL_prepbuffer **/.deps/build/src/lua/src/lauxlib.c:430:7
    #4 0x7ffaab7c0b5c in lmpack_pack lmpack.c

  Uninitialized value was created by an allocation of 'lf' in the stack frame of function 'luaL_loadfile'
    #0 0x55d26c60fd00 in luaL_loadfile **/.deps/build/src/lua/src/lauxlib.c:552

SUMMARY: MemorySanitizer: use-of-uninitialized-value **/.deps/build/src/lua/src/lstring.c:82:12 in luaS_newlstr
```

**Comment by zeertzjq** [comment]
It seems that MSan doesn't like uninitialized `luaL_Buffer`.

**Comment by zeertzjq** [comment]
This is probably not worth the effort considering the false positives. Clang analyzer can already catch using uninitialized memory, although not immediately in CI.

**Comment by justinmk** [comment]
> probably not worth the effort considering the false positives.

related:

- https://github.com/neovim/neovim/issues/4956
- https://github.com/neovim/neovim/issues/2957

**Pull request closed without merging**
