### PR TITLE
feat(lua): typing for vim.fn.*

### PR DESCRIPTION
**Pull request by lewis6991**
### Problem

No LSP information for `vim.fn.*`

### Solution

Add meta file for `vim.fn.*`.

---

- Optional arguments are properly annotated.
- Argument names are fully parsed.
- Argument types are approximated using the argument names and fallback to `any`.
  - Need to annotate these types in `eval.lua`.
- Currently does not handle `searchpair` and `searchpairpos` because the signature spans multiple lines.

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by lewis6991** [comment]
Ah, I was unaware of #18311, I just assumed we wanted vim to own `builtin.txt`.

I would definitely like to have `src/nvim/eval.lua` as the source of truth, and likewise for `src/nvim/ex_cmds.lua` and `src/nvim/options.lua` which I assume also applies? 

Since we're aligned on this, I can rampage on since this is all fairly straight forward. It is `vim.api.*` that will be less obvious to generate type information for.

**Comment by justinmk** [comment]
> I would definitely like to have `src/nvim/eval.lua` as the source of truth, and likewise for `src/nvim/ex_cmds.lua` and `src/nvim/options.lua` which I assume also applies?

Yes, all vimscript-related things should be programmatically exposed. In practice that really just means moving our Lua definitions files into `runtime/`. The only remaining hesitation was that this makes the files a public API, but I don't think that should block us at this point. But ideally, we should (or did) structure the data in a way that avoids the need for major revisions in the future.

**Comment by zeertzjq** [comment]
This sounds like reinventing Vim9script type checks for builtin functions

**Comment by lewis6991** [comment]
I guess that would be in scope since all the type information would be available in a machine-readable format. The main motivation atm is just to provide type information to LSP's.

**Comment by zeertzjq** [comment]
This also doesn't work well for function with multiple signatures, like `get()` and `input()`. When there are multiple signatures only the last one is generated.

**Comment by lewis6991** [comment]
Already working on it 😉 

Currently got:
```lua
  get__1 = {
  args = { 2, 3 },
  base = 1,
  desc = { "Get byte {idx} from |Blob| {blob}.  When this byte is not", "available return {default}.  Return -1 when {default} is", "omitted." },
  name = "get",
  params = { { "blob", "any" }, { "idx", "integer" }, { "default", "any" } },
  signature = "get({blob}, {idx} [, {default}])"
},
  get__2 = {
  args = { 2, 3 },
  base = 1,
  desc = { "Get item with key {key} from |Dictionary| {dict}.  When this", "item is not available return {default}.  Return zero when", "{default} is omitted.  Useful example: >", "\tlet val = get(g:, 'var_name', 'default')", "<This gets the value of g:var_name if it exists, and uses", '"default" when it does not exist.' },
  name = "get",
  params = { { "dict", "any" }, { "key", "any" }, { "default", "any" } },
  signature = "get({dict}, {key} [, {default}])"
},
  get__3 = {
  args = { 2, 3 },
  base = 1,
  desc = { "Get item {what} from Funcref {func}.  Possible values for", "{what} are:", '\t"name"\tThe function name', '\t"func"\tThe function', '\t"dict"\tThe dictionary', '\t"args"\tThe list with arguments', "Returns zero on error.", "", "\t\t\t\t\t*getbufinfo()*" },
  name = "get",
  params = { { "func", "any" }, { "what", "any" } },
  signature = "get({func}, {what})"
},
```

**Comment by justinmk** [comment]
> This also doesn't work well for functions with multiple signatures, like `get()` and `input()`. When there are multiple signatures only the last one is generated

These problems go away if we use eval.lua as the source of truth, i.e. gen_vimfn_types.lua is only the bridge that bootstraps us to that phase.

**Comment by T-727** [comment]
Perhaps this would be a perfect use case for the [`@overload` annotation](https://github.com/LuaLS/lua-language-server/wiki/Annotations#overload)?

**Pull request merged**
