### PR TITLE
fix(lsp): fix rename capability checks and multi client support

### PR DESCRIPTION
**Pull request by mfussenegger**
Adds filter and id options to filter the client to use for rename.
Similar to the recently added `format` function.

rename will use all matching clients one after another and can handle a
mix of prepareRename/rename support. Also ensures the right
`offset_encoding` is used for the `make_position_params` calls

### CODE REVIEW

**Comment by przepompownia** [comment]
@mfussenegger now (with no filter) I cannot rename class using phpactor because null-ls has no rename capability and `try_use_client` is not performed on the next client (phpactor). After adding 
```lua
      if next(clients, idx) then
        try_use_client(next(clients, idx))
      end
```
below the notification phpactor is used to rename.

**Comment by mfussenegger** [comment]
You can pass a name or filter to avoid that.  I wasn't sure if it should automatically continue if a client doesn't have the capability as it seemed more like a "user does something wrong" condition. 

But I'm open to change it to continue and only notify if no client had rename capabilities

**Comment by przepompownia** [comment]
With no filter it would be good to try the only rename capable client as I proposed. 

There is another case when two or more client supports `textDocument/rename`. Do we want to allow the next such client to handle the same request?

**Comment by mfussenegger** [comment]
> I understand this idea for formatting but in this case it would be nice to have a convincing example.

One client may be unable to rename something and another might. It's a long stretch and I don't think anybody will ever have that use-case, but the same can be said for formatting. Doing those operations with mulitple clients hardly makes sense, but that's why we added the filter arguments. The intention is that users select the right client.

**Comment by quantum-booty** [comment]
for those who wants to see how the filter works, here is a snippet:
```lua
    local function not_nullls(servers)
        for k, v in ipairs(servers) do
            if v.name == 'null-ls' then
                table.remove(servers, k)
            end
        end
        return servers
    end

    vim.keymap.set('n', '<leader>rn', function() vim.lsp.buf.rename(nil, {filter=not_nullls}) end, { noremap=true, silent = true, buffer = bufnr })
```

**Comment by neovim-discourse** [comment]
This pull request has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/getting-method-textdocument-preparerename-is-not-supported-by-any-of-the-servers-registered-for-the-current-buffer/2535/3

**Pull request merged**
