### PR TITLE
Fixed tiny typo in :bufdo section

### PR DESCRIPTION
**Pull request by munyari**

### CODE REVIEW

**Comment by justinmk** [comment]
Please read CONTIBUTING.MD section about commit messages.

**Comment by munyari** [comment]
@justinmk I have now amended commit message to use the imperative voice as per https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-guidelines

Please let me know if there is anything else that I need to do.

**Comment by fmoralesc** [comment]
@munyari Please append the commit with `doc:` (we usually add this tag to quickly see where the changes are being made).

Also, squash the commits ;)

**Comment by munyari** [comment]
Apologies @fmoralesc, I'm pretty new at this and this is one of my first contributions. I attempted to rebase to edit my previous commit.

**Comment by fmoralesc** [comment]
@munyari No need to apologize, It's OK ;) Generally, you need to rebase within the working branch only, not rebase on master, unless there are conflicts.

@justinmk Have you thought about enabling Github's new functionality of squashing-on-merge?

**Comment by justinmk** [comment]
> Have you thought about enabling Github's new functionality of squashing-on-merge?

Does it require some special switch? I have seen the option on some commits, though not this one. But I don't see what good it does us, anyways. Merge-commits are useful because:

- they don't modify commits, which makes it easy to verify that a mistake wasn't introduced in a rebase, (also allows commit-signing to work, once that becomes more popular)
- they allow `git fetch --prune` to work
- they allow cross-referencing to work
- in the case of correctly-structured PRs, they preserve useful history

**Comment by justinmk** [comment]
Merged.

P.S. I don't think a squash would help here. Only `git cherry-pick 6426bfba132c5b131a342f7b0e1709972a326bbf` was needed.

**Comment by fmoralesc** [comment]
@justinmk Sure, I was just thinking that in cases like this, where the commits could be squashed without losing meaningful history, it might be simpler than waiting for the PR author to do so. Obviously, it would depend on the nature of the PR.

**Pull request closed without merging**
