### PR TITLE
[RFC] implement timers (vim-patch:7.4.1578) and process events during sleep

### PR DESCRIPTION
**Pull request by bfredl**
Ref #1404

### CODE REVIEW

**Comment by bfredl** [comment]
vim is handling timers during a `:sleep` call. It also appears to handle channel request during `:sleep` (but only once per second, interesting enough). I wonder if nvim should do the same (two questions)?

**Comment by justinmk** [comment]
> vim is handling timers during a :sleep call

I assumed we would do that naturally since the libuv timers presumably run in a separate thread. 

When I looked at the Vim timer code, it looked like it was just checking at os_breakcheck intervals (or something analogous). Is is using a separate thread now?

> It also appears to handle channel request during :sleep (but only once per second, interesting enough).

I had also assumed we process API calls during sleep. I guess this is treated as "operator pending" / "Press Enter" mode, where we do nothing at all? Those are the fundamental problems we have had. If Vim handles them then we should be able to re-use the solution from Vim.

**Comment by bfredl** [comment]
libuv runs in a separate thread but ex_sleep is blocking the thread which runs viml code. It shouldn't be too hard to change it to "wait for events for X msec" (we already have similar conditions like "process events until event X happens", i e a request response).

vim actually precalulates if the `:sleep` can be interrupted by a timer, and adjusts the sleep time, but we could represent end-of-sleep as a uv_timer_t and let uv do this logic for us.

"press ENTER" apparently processes timers in vim, but not channel events. I would suggest that we do both (but it could require some work to do this robustly, i e most request should not abort the press ENTER prompt, except for vim_input of course)

**Comment by justinmk** [comment]
> vim actually precalulates if the :sleep can be interrupted by a timer, and adjusts the sleep time, but we could represent end-of-sleep as a uv_timer_t and let uv do this logic for us.

Got it. Agreed.

> "press ENTER" apparently processes timers in vim, but not channel events.

That makes sense. I agree we should do both (and during operator-pending), eventually...

**Comment by bfredl** [comment]
so I suppose the "proper" handling of test would be: keep the existing "new-style" timers+sleep test unmodified and also add lua/function test for input/events+timers situation.

**Comment by justinmk** [comment]
Since we are keeping the vim interdace, yes, that sounds good.

**Comment by bfredl** [comment]
so, it seems to me that vim considers any point where `vgetc()` or `safe_vgetc()` is called "safe to execute channel messages or timers" (i e arbitrary vimscript).

We should probably do the same, or a large part of those cases (we can add a flag to control this), but I will open a separate PR for that after this, as it has larger consequences.  For the moment timers will pause on a "press RETURN" prompt for instance (but ticks will not be queued up, so there will be no burst of callback invocations).

**Comment by bfredl** [comment]
marking RFC. As I cherry-picked part of 1624 I marked it NA. (Most of the rest is channels stuff)

**Comment by justinmk** [comment]
I'm running this locally for a few days, hope others can try it out too.

**Comment by bfredl** [comment]
I added the missing free.

> timer_stop() never reports an error, regardless of input

This is consistent with vim, but I agree it is weird that it is silent on a type error (a number that is not a timer I think it is intentional, so you could always `timer_stop(id)` without needing to guard against the timer already been stopped). Maybe ask on vim-dev?

**Comment by bfredl** [comment]
hmm, vim allows you redefine the callback while the timer is in use as well

**Comment by bfredl** [comment]
Was it a conscious decision that callbacks (for jobs) etc can't be redefined, or was it an accident of neovim implementation? It seems the intention of the error message was that a function can't be redefined while it is executing. Storing a funcref (or partial in vim) doesn't stop it from being redefined, and passing a callback to a builtin function should work the same as passing it to a user function (that stores it) IMO.

**Comment by bfredl** [comment]
updated with vim patch 1831.

**Comment by Shougo** [comment]
The rest of timer patches:
7.4.1603, 7.4.1656

**Comment by bfredl** [comment]
I added 7.4.1603 (+ visual test that fails without it) but 7.4.1656 should be part of a future partial PR as we don't have partials yet.

I hope don't mind sneaking in `inspect` lua dependency, as I noticed debugging screen tests per suggestions in `screen.lua` is broken (as in silent misbehavior broken) without it.

**Comment by bfredl** [comment]
I think we should merge this soon. There might be more bugs, but the only way to find them is more people actually using timers (to do interesting stuff).

The callback inconsistency with vim is a bit unfortunate, but I might do a later PR with the suggested behavior: redefining callback registered functions is ok, but deleting them are is. Possibly using a dedicated callback handle type that transparently can be changed to partials when we get those.

**Comment by Shougo** [comment]
OK.  I will try the feature

**Comment by wsdjeg** [comment]
:+1:

**Comment by Shougo** [comment]
I have found the bug in the feature.
If users use `timers` feature, they must call `timer_stop()` before exiting.
If not, neovim does not exit.

**Comment by Shougo** [comment]
timers feature seems not work with neovim job feature in insert mode like CursorHoldI.
https://github.com/neovim/neovim/issues/3757

**Comment by bfredl** [comment]
Yes, timers are handled the same way as all other async events (remote rpc / `:term` output) and thus will have the same set of bugs.

> If not, neovim does not exit.

I will fix it, but I don't remember why we do this "wait for the the event loop to close" ritual on exit. Why not save all persistent state and then just `exit(0)` ?

**Pull request merged**
