### PR TITLE
feat(api): add nvim_{get,set}_option_value

### PR DESCRIPTION
**Pull request by gpanders**
The current option APIs `nvim_get_option` and `nvim_{buf,win}_get_option` are insufficient to fully replicate the behavior of `:set` and friends in Vimscript.

Status quo:

* `nvim_get_option` only returns global values of options
* `nvim_{buf,win}_get_option` return the local value of an option if set. If the local value is unset then they throw an error for string-type options and return an uninitialized garbage value for number options (see #15587)
* `vim.opt` and `vim.o` depend on the error-throwing behavior of `nvim_{buf,win}_get_option` in order to emulate `:set`: if the local getter API returns an error then `vim.o` falls back to the global value. Because number-valued options do not throw an error, `vim.o` and `vim.opt` also return garbage values for number options (`:lua print(vim.opt_local.scrolloff:get())`).

Potential solutions and their trade-offs:

1. Make `nvim_{buf,win}_get_option` also return an error for unset local number-options. This makes the behavior consistent for all option types and makes `vim.o` and `vim.opt` work as expected
    * The tradeoff is that it then becomes impossible to truly get the local value of an option. For example, `:setlocal undolevels?` correctly shows `-123456`, but `:echo nvim_buf_get_option(0, 'undolevels')` throws an error.
2. Make `nvim_{buf,win}_get_option` never return an error and instead simply return the local value, even if unset. This means that unset string-valued global-local options return an empty string, and number-valued options return their "unset" number variant (e.g. `-123456` for `'undolevels'` and `-1` for `'scrolloff'`)
    * The tradeoff is that `vim.opt` and `vim.o` cannot tell if a given option has its local value set or not. How can it know that `-123456` means "unset" for `'undolevels'` unless that information is hard coded in? But that is ugly and repetitive.
3. Implement new options APIs `nvim_get_option_value` and `nvim_set_option_value` that intentionally behave like `:set` in that they are "context aware". Both of these new APIs also include future-proof `opts` parameters. When the `opts` parameter is empty, both APIs behave like `:set` (see `:h global-local`, `:h :setglobal`, and `:h :setlocal` for details). The `opts` parameter accepts a `"scope"` key that accepts either `"local"` or `"global"` as its value, which makes the function behave like `:setlocal` or `:setglobal`, respectively.

This PR implements option 3.

An added benefit of this approach is that it greatly simplifies the `vim.o` and `vim.opt` accessors: they are now simply wrappers around `nvim_{get,set}_option_value`.

TODO:

- [x] Implement `nvim_set_option_value`
- [x] Refactor `vim.opt` and `vim.o` to use `nvim_{get,set}_option_value`
  * This may also be the time to standardize on a single API rather than having both `vim.opt` and `vim.o`
- [x] Write/update tests
- [x] Write/update documentation

### CODE REVIEW

**Comment by gpanders** [comment]
Lint failure is due to recent uncrustify changes. Will squash commits after review and update commit message.

Windows CI failure is unrelated:

```
2021-10-12T19:20:54.2797189Z [  ERROR   ] 1 error, listed below:
2021-10-12T19:20:54.2797860Z [  ERROR   ] test/functional\core\channels_spec.lua @ 61: channels can use stdio channel
2021-10-12T19:20:54.2798569Z test\helpers.lua:73: Expected objects to be the same.
2021-10-12T19:20:54.2799030Z Passed in:
2021-10-12T19:20:54.2799382Z (table: 0x101e08c8) {
2021-10-12T19:20:54.2799772Z   [1] = 'notification'
2021-10-12T19:20:54.2800121Z  *[2] = 'stdout'
2021-10-12T19:20:54.2800450Z   [3] = {
2021-10-12T19:20:54.2800739Z     [1] = 3
2021-10-12T19:20:54.2801005Z     [2] = {
2021-10-12T19:20:54.2801309Z       [1] = '' } } }
2021-10-12T19:20:54.2801642Z Expected:
2021-10-12T19:20:54.2802001Z (table: 0x101dbaa0) {
2021-10-12T19:20:54.2802372Z   [1] = 'notification'
2021-10-12T19:20:54.2802742Z  *[2] = 'stderr'
2021-10-12T19:20:54.2803056Z   [3] = {
2021-10-12T19:20:54.2803332Z     [1] = 3
2021-10-12T19:20:54.2803624Z     [2] = {
2021-10-12T19:20:54.2803922Z       [1] = '' } } }
```

**Comment by tjdevries** [comment]
> This may also be the time to standardize on a single API rather than having both vim.opt and vim.o

I am happy to hear suggestions regarding this for 0.6. I don't like how many methods we have for this (but I didn't want to remove anything while we were still in 0.5 before).

I think `vim.bo`, `vim.wo`, `vim.to` still seem fine (they are useful and allow you to set things for _other_ buffers with `vim.bo[12].option = value`), but I'm not sure `vim.o` has any useful value now that we have `vim.opt` and others (especially if they work the right way now!)

Open to suggestions (maybe @bfredl you have some thoughts)

**Comment by gpanders** [comment]
>I think vim.bo, vim.wo, vim.to still seem fine (they are useful and allow you to set things for other buffers with vim.bo[12].option = value), but I'm not sure vim.o has any useful value now that we have vim.opt and others (especially if they work the right way now!)

IMO `vim.o`'s primary value proposition is that it is a much more terse form of *reading* option values:

```lua
print(vim.o.makeprg)
-- vs
print(vim.opt.makeprg:get())
```

I'm not sure if this is valuable enough to merit having two ways to do the same thing though (I lean toward "no").

**Comment by zeertzjq** [comment]
`vim.o` is also more stable, as it doesn't perform type conversion, which may change in future (<https://github.com/neovim/neovim/blob/fa97d34858fbb755e8bb6f161c49c18c7187eb4e/runtime/lua/vim/_meta.lua#L262-L263>).

**Comment by tjdevries** [comment]
> IMO `vim.o`'s primary value proposition is that it is a much more terse form of _reading_ option values:
> 
> ```lua
> print(vim.o.makeprg)
> -- vs
> print(vim.opt.makeprg:get())
> ```
> 
> I'm not sure if this is valuable enough to merit having two ways to do the same thing though (I lean toward "no").

Ah, that's an interesting point. Perhaps we should do something like:

```
vim.opt.makeprg:eq(val)
```

This could be nice because we could try and do extra coercing of values to what people might be expecting in lua (in the cases where viml might return 0/1 when it should be false/true or something. Not sure off the top of my head if that's happening for options). Just a thought I had while reading your message

**Comment by tjdevries** [comment]
> `vim.o` is also more stable, as it doesn't perform type conversion.
> 
> In contrast, `vim.opt` performs type conversion, whose result may be changed in future (
> 
> https://github.com/neovim/neovim/blob/fa97d34858fbb755e8bb6f161c49c18c7187eb4e/runtime/lua/vim/_meta.lua#L262-L263
> 
> ).

This is a fair argument. Perhaps it could be mitigated by adding `:raw()` as a method that returns directly the item from vim. For the cases someone wants to have that happen, that could work.

In regards to the part you mentioned above, that's actually just that we don't have the necessary information to know that `listchars` for example is actually more of a map type structure, not just a list. So I left a TODO so that at some point in the future we could inspect the metadata of the option to determine if it was a map or not. It should not change structure in the future.

**Comment by zeertzjq** [comment]
Well, it is parsed character by character in C.

**Pull request merged**
