### PR TITLE
LSP: Track active requests to the language server on the client object

### PR DESCRIPTION
**Pull request by jdrouhard**
This PR addresses the last remaining items keeping me from switching to the native LSP client over coc.nvim. That is:

1. A way to see the currently pending (active) requests to the language server (like in a status line)
2. A way to see requests for which cancellations have been requested
3. A way to cancel pending requests on CursorMoved events that does not require wrapping all of the requests (and handlers!) in a special function.

I know that `lsp.buf_request()` already returns a list of request IDs and a function to cancel them all. This PR doesn't break any existing code that uses this. However, this particular method only works if each request is wrapped appropriately. The built-in request convenience functions don't return the result of `buf_request()` so they have to be re-written with the proper method name and location params.

Even if the request functions were rewritten to return the IDs and cancellation function, there is still no way to watch pending requests if they are cancelled by the language server (either due to a user request, or due to a ContentModified error). The RPC layer swallows these responses up and never even gives the opportunity for an observer to see that a request is no longer pending to be able to clear out any external mechanism for tracking them.

I've been using this patch to great effect with the following status line and CursorMoved function:

https://gist.github.com/jdrouhard/50aa56c8f54ba9a1e94112422262e56c
https://gist.github.com/jdrouhard/d5524ed2153bfb36ffa2cc492e4d5267

### CODE REVIEW

**Comment by mjlbach** [comment]
```
    A way to see the currently pending (active) requests to the language server (like in a status line)
    A way to see requests for which cancellations have been requested
    A way to cancel pending requests on CursorMoved events that does not require wrapping all of the requests (and handlers!) in a special function.
```

Can you elaborate more on the usecase for these? With the recent clientside performance improvements, anything that isn't a slow server side operation should take less than 50 ms or so, so not enough to motivate showing anything interactively to the user. Is there a particular slow server side operation you are thinking of? The only thing that springs to mind is maybe resolving references on extremely large codebases (I assume the origin from your third point)

**Comment by mjlbach** [comment]
Thanks, I'm happy with this apart from maybe some bikeshedding around the name of `cancel_requests` and `notify_reply_callbacks`. Tagged mfussenegger for review.

**Review by mjlbach — APPROVED** [review]

**Review by justinmk — CHANGES_REQUESTED** [review]

**Review by mjlbach — APPROVED** [review]
I was mostly happy with the last version of the PR, it looks even better after Justin's suggestions. I'll leave it to him to give final approval and merge. Thanks for the tests.

Can you fix the linux lint issue?

Ping @rish987, does this solve your usecase from #15029?

**Review by mjlbach — APPROVED** [review]

**Review by justinmk — APPROVED** [review]
Looks much better, thanks!

**Pull request merged**
