### PR TITLE
[WIP] [Advice Needed] Converting legacy test 024, however it is seriously broken!

### PR DESCRIPTION
**Pull request by alcarney**
First let me start off by saying this is my attempt at contributing to open source so please excuse if me if I'm going about this wrong or posting in the wrong place...

I thought that a test like this would be easy to convert to the format requested in #1286 and for the most part it was however once I tried to run the test it simply fails to pass. Upon closer inspection I discovered that the text being inserted with the `insert` function doesn't match the exact same text in the `expect` function call I added immediately afterwards. 

I've attached a screenshot of the relevent output from `make test` so you can see for yourselves what I'm talking about. It seems to work fine up until the special characters that I've highlighted when it all goes haywire skipping lines etc.

2015-01-20-205155_1920x1080_scrot

Not sure where to go from here, is it a problem with the `insert` function? Am I passing in the text incorrectly? Or should they even be there? Any help or advice would be greatly appreciated

### CODE REVIEW

**Comment by fmoralesc** [comment]
I think you need to escape the special characters correctly in the format lua expects: "\0" for "\x00", etc.

See http://www.lua.org/manual/5.2/manual.html#3.1

**Comment by tarruda** [comment]
> Not sure where to go from here, is it a problem with the insert function? Am I passing in the text incorrectly? Or should they even be there? Any help or advice would be greatly appreciated

First of all, did you try to use `./scripts/legacy2luatest.pl ./src/nvim/testdir/test24.in test/functional/legacy` as a starting point?

If yes, there's some difference in the key encoding used by the new tests and the old tests, so a direct will not work correctly all the times. If the test contain non-printable bytes such as 0x80, you need to insert using digraphs. For example:

```lua
insert([[
  some text<c-v>x80
]])
```

will result in a buffer containing

```
some text<80>
```

**Comment by tarruda** [comment]
> I think you need to escape the special characters correctly in the format lua expects: "\0" for "\x00", etc.

> See http://www.lua.org/manual/5.2/manual.html#3.1

:+1:  In most cases it is possible to insert using lua escape sequences too, though lua does not have a hexadecimal notation, only octal escape sequences are supported.

**Comment by fwalch** [comment]
If you don't want to change these escape sequences by hand, you could probably extend the `./scripts/legacy2luatest.pl` script to do that for you :-)

**Comment by justinmk** [comment]
closing per inactivity and lack of an actual PR.

**Comment by nelsyeung** [comment]
> insert([[   some text\<c-v>x80 ]])

I would like to say that this doesn't actually work because the insert function escapes `<`. Look into `test/functional/helpers.lua`:
```lua
local function insert(...)
  nvim_feed('i')
  for _, v in ipairs({...}) do
    local escaped = v:gsub('<', '<lt>')
    rawfeed(escaped)
  end
  nvim_feed('<ESC>')
end
```
`feed` will be needed instead (i.e., `feed([[i<c-v>x80<esc>]])`).

I'm not sure whether this is still being worked on, so I've created a new pull request #2845 for this test.

**Comment by justinmk** [comment]
@nelsyeung Thanks very much.

**Pull request closed without merging**
