### PR TITLE
[RFC] vim-patch:7.4.2251

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    In rare cases diffing 4 buffers is not enough.
Solution:   Raise the limit to 8. (closes vim/vim#1000)

https://github.com/vim/vim/commit/015efc32c1add6269099364835ddf85ff257b3c6

### CODE REVIEW

**Comment by jamessan** [comment]
Looks good other than the lint failure.

```
src/nvim/buffer_defs.h:774:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]
Total errors found: 1
```

**Comment by jamessan** [comment]
> Looks good other than the lint failure.

Fixed in the merge commit.  Thanks!

**Comment by Shougo** [comment]
Thank you!

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
