### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by blueyed** [comment]
>  missing colon in last update (https://github.com/neovim/neovim/commit/098fd362355c3895d8c23894f901834eb4c5f9e4)

vim-patch:8.0.1671: crash when passing non-dict argument as env to job_start()

**Comment by janlazo** [comment]
vim-patch:8.1.0525: terminal test skips part on Windows
vim-patch:8.1.0778: terminal test fails on MS-Windows

**Comment by janlazo** [comment]
Is there any enough N/A patches to merge?

**Comment by blueyed** [comment]
@janlazo 
Removed "vim-patch:8.1.0572: stopping a job does not work properly on OpenBSD", will port that (via https://github.com/neovim/neovim/issues/9704#issuecomment-471329427).

**Pull request merged**
