### PR TITLE
[RFC] vim-patch:7.4.2148,7.4.2159,7.4.2175,7.4.2295

### PR DESCRIPTION
**Pull request by lonerover**
#### vim-patch:7.4.2148

Problem:    Not much testing for cscope.
Solution:   Add a test that uses the cscope program. (Christian Brabandt)

https://github.com/vim/vim/commit/edf634e0f1985c5ea1afb5b480b47a44cabbce34

#### vim-patch:7.4.2159

Problem:    Insufficient testing for cscope.
Solution:   Add more tests. (Dominique Pelle)

https://github.com/vim/vim/commit/5971dab1126d6279c6e523f4fedc2f1e6fb9b4c9

#### vim-patch:7.4.2175

Problem:    Insufficient testing of cscope.
Solution:   Add more tests. (Dominique Pelle)

https://github.com/vim/vim/commit/812ad4f3a2cb33002a24f6b5862c7b375cd68fe4

#### vim-patch:7.4.2295

Problem:    Cscope test fails.
Solution:   Avoid checking for specific line and column numbers.

https://github.com/vim/vim/commit/4792255eff03760dca0fd014616532e6d47db364

### CODE REVIEW

**Comment by lonerover** [comment]
Two more  fix for cscope test.
1. memfile_test.c is removed from src, but it is needed for cscope test, add it to testdir/samples.
2. execute "cs kill -1" when there's no cscope connections, neovim will get error "E261: cscope connection -1 not found", but vim get no error.

**Comment by Shougo** [comment]
Vim 7.4.2284 is missing.

**Comment by lonerover** [comment]
vim-patch 7.4.2284 is already patched.
see #5254

**Comment by Shougo** [comment]
OK.

**Pull request merged**
