### PR TITLE
WIP: debug AppVeyor cache

### PR DESCRIPTION
**Pull request by blueyed**
Caching appears to not happen on AppVeyor in general.  This is an
attempt to figure out why, and fix it.

It always says:

> cache dir not found: C:/projects/nvim-deps

There is no log for restoring / saving the cache.

It was available with the latest master build however: https://ci.appveyor.com/project/neovim/neovim/builds/25650147/job/2ufi04s3nxdnkcoq?fullLog=true#L45

The docs state:

> Note: By default, saving cache is disabled in Pull Request builds. Use Save build cache in Pull Requests checkbox on the General tab of project settings if you need to save cache during PR builds. This setting is not exposed in YAML to prevent unauthorized cache modifications.

But I would still expect the cache to be used (read) for PRs then, no? [Yes.](https://help.appveyor.com/discussions/problems/4048-build-cache-not-restored)

According to https://www.appveyor.com/docs/build-configuration/ it should happen after cloning, but is clearly missing in https://ci.appveyor.com/project/neovim/neovim/builds/25667932/job/f3on2ahcr8tkfdwo?fullLog=true.

Cache was used in #10392 (MINGW_64-gcov (https://ci.appveyor.com/project/neovim/neovim/builds/25674238/job/2aky23wj41if5ndi?fullLog=true#L12), but not MSVC_32):
```
Build started
# Pull requests: skip some build configurations to save time.
if ($env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT -and $env:CONFIGURATION -match '^(MSVC_64|MINGW_32)$') {
  $env:APPVEYOR_CACHE_SKIP_SAVE = "true"
  Exit-AppVeyorBuild
}
git clone -q https://github.com/neovim/neovim.git C:\projects\neovim
git fetch -q origin +refs/pull/10392/merge:
git checkout -qf FETCH_HEAD
Restoring build cache
Cache 'C:\projects\nvim-deps' - Restored
Install-Product node 8
Uninstalling node 8.15.1 (x86)...
Installing node 8.16.0 (x86)...
```

### CODE REVIEW

**Comment by justinmk** [comment]
> It always says:
> 
> > cache dir not found: C:/projects/nvim-deps

After https://github.com/neovim/neovim/pull/9858 the cache was working. So if it _never_ works now, that must be related to recent changes.

**Comment by blueyed** [comment]
> After #9858 the cache was working

Also for PRs (restoring/using it there)?

**Comment by justinmk** [comment]
> Also for PRs (restoring/using it there)?

yes. are you looking are mingw or msvc or both?

**Comment by blueyed** [comment]
> are you looking are mingw or msvc or both?

both / in general.

**Comment by blueyed** [comment]
@justinmk 
As per https://github.com/appveyor/ci/issues/3015#issuecomment-509379643 we should enable the cache for PRs also.

**Comment by justinmk** [comment]
done

**Comment by blueyed** [comment]
Closing for now.  Might have fixed or worked around it.  Only checked a single PR job now though.

**Comment by justinmk** [comment]
It definitely seems better , thanks for investigating!

**Pull request closed without merging**
