### PR TITLE
[RFC] Add missing header guards in job.c and log.c

### PR DESCRIPTION
**Pull request by equalsraf**

### CODE REVIEW

**Comment by fwalch** [comment]
Shouldn't there be `#ifdef`s around code that uses these headers as well? A quick grep only showed a few results in `os_unix_defs.h`.

**Comment by equalsraf** [comment]
> Shouldn't there be #ifdefs around code that uses these headers as well?

Depends on the case. e.g. time.h is enough in some systems, others require sys/time.h - in any case this should not break anything since those guards were already true, otherwise the `#include` would be failing.

os_unix_defs.h already has `HAVE_UNISTD_H` so it should work either way with or without it.

**Comment by fwalch** [comment]
> in any case this should not break anything

I was just wondering whether something would break even after this PR, if `HAVE_XX` were false. I removed the includes entirely and re-built without errors, but one warning:

```
/home/florian/Projects/neovim/src/nvim/os/job.c: In function ‘chld_handler’:
/home/florian/Projects/neovim/src/nvim/os/job.c:437:5: warning: implicit declaration of function ‘waitpid’ [-Wimplicit-function-declaration]
     pid = waitpid(-1, &stat, WNOHANG);
     ^
```

**Comment by equalsraf** [comment]
If we were to find a system where waitpid is not in sys/wait.h the result would be an include error for sys/wait.h - in this particular case we really need waitpid(), so there would always be an error.

**Comment by fwalch** [comment]
I'm a bit confused now. The scenario I imagine is the following:

`HAVE_SYS_WAIT_H` is false. The header is thus not included, because after this PR, we have the header guards. The compilation would fail because we don't include a header that defines `waitpid()`.

**Comment by equalsraf** [comment]
If HAVE_SYS_WAIT_H is false then the include would fail anyway. But actually if HAVE_SYS_WAIT is false the build [never starts (for UNIX)](https://github.com/neovim/neovim/blob/b427dcdda286603a06ed29b45f1090894e92074a/config/CMakeLists.txt#L29).

**Comment by Pyrohh** [comment]
LGTM

**Comment by equalsraf** [comment]
Failing in Travis, job.c is not getting the definitions from config.h, need to move that include.

**Comment by fwalch** [comment]
> Failing in Travis, job.c is not getting the definitions from config.h, need to move that include.

`config.h` is included in `vim.h`, so I think you need to move the includes in `log.c` as well (the build still works if they're not included). Or add the following, like in `iconv.h`:

```
#ifdef HAVE_CONFIG_H
# include "auto/config.h"
#endif
```

**Comment by equalsraf** [comment]
> config.h is included in vim.h, so I think you need to move the includes in log.c as well (the build still works if they're not included, so Travis didn't fail)

Not even an implicit declaration warning. Both includes are also in os_unix_defs.h, the os/os.h include should have have included them too.which was why there were no errors. Moved them to the bottom.

**Comment by equalsraf** [comment]
Ok I think that is all on this end.

**Comment by Pyrohh** [comment]
What do you think @fwalch, this LGTM.

**Comment by fwalch** [comment]
LGTM as well.

**Comment by Pyrohh** [comment]
Thanks both, merged.

**Pull request closed without merging**
