### PR TITLE
ci: Travis: move gcov job to baseline (no allowed failures)

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by jamessan** [comment]
Why move ASAN out of baseline?

**Comment by blueyed** [comment]
> Why move ASAN out of baseline?

It is one of the slower ones, and is more of a next-step check, isn't it?

Also it appears to be "flaky" / showing issues (https://github.com/neovim/neovim/issues/8813#issuecomment-502445859)), and should not prevent the next stage to run due to this.

The main point of this PR is moving coverage to the first stage, and I think that while ASAN could be left there also, it is better to split this into 4/4.

**Comment by blueyed** [comment]
@jamessan 
Is it OK?

**Comment by justinmk** [comment]
> Also it appears to be "flaky" / showing issues ([#8813 (comment)](https://github.com/neovim/neovim/issues/8813#issuecomment-502445859))), and should not prevent the next stage to run due to this.

No, ASAN job is one of the most reliable ones. Some tests are flaky but that isn't related. That change should be reverted

> The main point of this PR is moving coverage to the first stage, 

Why ? I said in another ticket that test coverage is not a high priority CI job. It is a sanity check. There has never been a case where we accidentally merged something that broke project test coverage, and even if we did, it's easy to revert and it makes zero sense to make it a high-priority job in all of our PRs. 

This should be reverted.

**Comment by blueyed** [comment]
> No, ASAN job is one of the most reliable ones. Some tests are flaky but that isn't related.

Well, it is certainly slower after all.

I think we should aim for making all jobs pass in general, but if they fail due to flakiness it is better to a) not being the gcov job, and b) not being a slower job.

**Comment by justinmk** [comment]
ASAN job is slower but it is also the most useful and comprehensive job. gcov job is also slow, and much less useful than the ASAN job.

**Comment by bfredl** [comment]
The only reason reason ASAN is "slower" is because it _tests more things_ and produces _a lot_ more information in case of failures. Even measured per time unit it is by far the most powerful CI build. De-prioritizing a build because it takes time to actually test stuff makes no sense. It should be the first build that get started by travis, like it always have been.

**Comment by blueyed** [comment]
Ok, I see.  https://github.com/neovim/neovim/pull/10274

**Pull request merged**
