### PR TITLE
[RFC] Changed comment style on edit.c

### PR DESCRIPTION
**Pull request by swpark706**
Looking around codes, in edit.c I found code that is incompatible with the current comment style. 

Due to length of the codes, only partial updates are made. We are going to update continuously.

Thanks.

### CODE REVIEW

**Comment by KillTheMule** [comment]
> We are going to update continuously.

Let me stop you right there.

First though: Thanks for your interest in contributing, it is appreciated.

But: We don't do style-only changes, we "just" change the style of those sections of the code we change anyways. A large motivation for that is that we continously merge patches from upstream vim, and the diffs of those will just get large by these style changes. It's a lot of churn for not much win.

I'd like to update the wiki/documentation to make that clearer. Would you have any suggestion where to put that?

**Comment by swpark706** [comment]
Thank you. It would be nice if it were on a code style or Refactoring guidelines.. I appreciate it.

**Comment by mang1375** [comment]
I think warning messages are needed in the Code style & Development tips

**Comment by KillTheMule** [comment]
> It would be nice if it were on a code style or Refactoring guidelines

I will put a message there.



> I think warning messages are needed in the Code style & Development tips

I'll have a look there, too.

Thanks!

**Comment by KillTheMule** [comment]
I've put a section here: https://github.com/neovim/neovim/wiki/Refactoring. @justinmk Would you put a small note on the style guide?

**Pull request closed without merging**
