### PR TITLE
vim-patch:8.1.{1354, 1356,1362,1588}

### PR DESCRIPTION
**Pull request by jbradaric**
```
vim-patch:8.1.1354: getting a list of text lines is clumsy
Problem:    Getting a list of text lines is clumsy.
Solution:   Add the =<< assignment. (Yegappan Lakshmanan, closes vim/vim#4386)
```
https://github.com/vim/vim/commit/f5842c5a533346c4ff41ff666e465c85f1de35d5

```
vim-patch:8.1.1356: some text in heredoc assignment ends the text          
                                                                           
Problem:    Some text in heredoc assignment ends the text. (Ozaki Kiichi)  
Solution:   Recognize "let v =<<" and skip until the end.                  
```
https://github.com/vim/vim/commit/8471e57026714c5a0faf89288ceef5231fb88d4f 

```
vim-patch:8.1.1362: code and data in tests can be hard to read

Problem:    Code and data in tests can be hard to read.
Solution:   Use the new heredoc style. (Yegappan Lakshmanan, closes vim/vim#4400)
```
https://github.com/vim/vim/commit/c79745a82faeb5a6058e915ca49a4c69fa60ea01

```
vim-patch:8.1.1588: in :let-heredoc line continuation is recognized

Problem:    In :let-heredoc line continuation is recognized.
Solution:   Do not consume line continuation. (Ozaki Kiichi, closes vim/vim#4580)
```
https://github.com/vim/vim/commit/e96a2498f9a2d3e93ac07431f6d4afd77f30afdf

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks @jbradaric ! Were there any followup patches to this feature?

**Comment by jbradaric** [comment]
@justinmk, yes, patch 8.1.1356. I forgot to check yesterday, I will add it to the pull request as soon as I get off work.

**Comment by jbradaric** [comment]
Seems 8.1.1362 and 8.1.1588 are also related, I will add those as well.

**Comment by justinmk** [comment]
the most gentle ping

**Comment by jbradaric** [comment]
@justinmk, I think I've added all other related patches. Sorry for the delay.

**Comment by justinmk** [comment]
Thanks! Looks like an oldtest is failing:

```
Failures: 
	From test_quickfix.vim:
	Found errors in Test_efm_dirstack():
	function RunTheTest[37]..Test_efm_dirstack[28]..<SNR>3_dir_stack_tests line 29: Expected 'dir1/a/habits2.txt' but got 'habits2.txt'
	function RunTheTest[37]..Test_efm_dirstack[28]..<SNR>3_dir_stack_tests line 31: Expected 'dir1/a/b/habits3.txt' but got 'habits3.txt'
	function RunTheTest[37]..Test_efm_dirstack[28]..<SNR>3_dir_stack_tests line 33: Expected 'dir1/a/habits2.txt' but got 'habits2.txt'
	function RunTheTest[37]..Test_efm_dirstack[28]..<SNR>3_dir_stack_tests line 35: Expected 'dir1/c/habits4.txt' but got 'habits4.txt'
	function RunTheTest[37]..Test_efm_dirstack[28]..<SNR>3_dir_stack_tests line 39: Expected 'dir2/habits5.txt' but got 'habits5.txt'
	function RunTheTest[37]..Test_efm_dirstack[29]..<SNR>3_dir_stack_tests line 29: Expected 'dir1/a/habits2.txt' but got 'habits2.txt'
	function RunTheTest[37]..Test_efm_dirstack[29]..<SNR>3_dir_stack_tests line 31: Expected 'dir1/a/b/habits3.txt' but got 'habits3.txt'
	function RunTheTest[37]..Test_efm_dirstack[29]..<SNR>3_dir_stack_tests line 33: Expected 'dir1/a/habits2.txt' but got 'habits2.txt'
	function RunTheTest[37]..Test_efm_dirstack[29]..<SNR>3_dir_stack_tests line 35: Expected 'dir1/c/habits4.txt' but got 'habits4.txt'
	function RunTheTest[37]..Test_efm_dirstack[29]..<SNR>3_dir_stack_tests line 39: Expected 'dir2/habits5.txt' but got 'habits5.txt'
```

also this Lua test:

```
stack traceback:
	test/functional/eval/system_spec.lua:325: in function <test/functional/eval/system_spec.lua:315>
```

**Comment by jbradaric** [comment]
@justinmk, fixed the oldtest. The lua test seems unrelated to this change and passes on my machine. I will investigate further if it fails again.

**Comment by blueyed** [comment]
lint job failed:

> src/nvim/eval.c:21892:  Small and focused functions are preferred: ex_function() has 503 non-comment lines (error triggered by exceeding 500 lines).  [readability/fn_size] [1]

I guess we should whitelist it?  `// NOLINT(readability/fn_size` at the end of the function it seems, check other uses.

**Pull request merged**
