### PR TITLE
refactor(comment): replace nvim_buf_set_lines with nvim_buf_set_text

### PR DESCRIPTION
**Pull request by altermo**
`nvim_buf_set_lines` is less precise, which causes an incorrect change in the extmarks position, so use `nvim_buf_set_text` instead.
Other benefits of this refactor:
+ `lockmarks = true` can be removed as regular marks should mostly work as intended.
+ `nvim_buf_attach` (and similar functions) reports only the regions that have changed, not the whole line.

### CODE REVIEW

**Comment by echasnovski** [comment]
Thanks for the PR.

Unfortunately, preserving extmarks is not a universally good side effect. I explored the idea in 'mini.comment' prior to making built-in commenting PR and decided that using `nvim_buf_set_lines()` is a better approach right now. [Here is full motivation](https://github.com/echasnovski/mini.nvim/blob/1d4772e9f4f3ddc125a5ec1386fd4f85c7e3bb18/lua/mini/comment.lua#L260-L287). TL;DR: preserving extmarks result into flickering (as some extmarks highlight text ranges) while calling `nvim_buf_set_text()` twice per line instead of a single `nvim_buf_set_lines()` can be costly.

**Comment by clason** [comment]
> nvim_buf_attach (and similar functions) reports only the regions that have changed, not the whole line.

That part seems like a worthwhile change, though -- if it can be isolated.

**Comment by echasnovski** [comment]
> > nvim_buf_attach (and similar functions) reports only the regions that have changed, not the whole line.
> 
> That part seems like a worthwhile change, though -- if it can be isolated.

I'd say "maybe". This boils down to whether "add/remove comment" should be perceived as simple text edit ("add/remove comment markers at these positions") or a more general semantic one ("replace these lines with their commented/uncommented version"). Using the second one seems like more useful on practice.

**Comment by clason** [comment]
Oh, sorry, my bad -- I somehow read "buffer" for "line". Then the current behavior is consistent, of course (commenting replaces a code line with a comment line, and vice versa).

**Comment by dundargoc** [comment]
@echasnovski mind adding a comment and/or link to your reasoning? Just as a precaution so people know why the code is written like this.

**Pull request closed without merging**
