### PR TITLE
fix(lua): avoid recursive vim.on_key() callback

### LINKED ISSUE #30752: Using `vim.on_key()` stuck at `Press ENTER or...`.
### Problem

The only way out is to `kill -INT <pid>`. Other kills work as well.

### Steps to reproduce

Using `nvim --clean`, edit and source the following, get the following for any keystroke.
```
Press ENTER or type command to continue                                                             
Press ENTER or type command to continue                                                             
...
```

```
local ns_id
local function key_cb(key, typed)
    vim.print("key_cb")
    vim.print(string.format("KEYCB: key '%s', typed '%s'", key, typed))
end

ns_id = vim.on_key(key_cb)


key_cb("foo", "bar")

-- The defered function doesn't work. Guess it's never executed.
--vim.defer_fn(function() vim.on_key(nil, ns_id) end, 9000)
```

### Expected behavior

Expect `Ctrl-C` to get out of loop.

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/61f1b091ea97793f9b644cebf6c84cf6bbb4f0bc

### Vim (not Nvim) behaves the same?

Can't reproduce in vim

### Operating system/version

ubuntu

### Terminal name/version

gnone

### $TERM environment variable

xterm-256color

### Installation

make install

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #30752

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by errael** [comment]
Tried this. :+1:

After first reading `avoid recursive vim.on_key()`, I thought some calls would be lost. Oh wait, some are lost; curiously doing `j` with map `j -> gj` nothing's lost is a simple test but `type` not as expected (as mentioned elsewhere) . 

Should be using a scheduled function, or other alternative, anyway. If deferred, need  to make sure all debug output is deferred so that order is preserved.

**Comment by errael** [comment]
Opened #30770 which is loosely related.

**Comment by zeertzjq** [comment]
"recursive callback" only happens when the callback itself consumes input, which isn't common. Maybe I should make it clearer in the docs.

**Comment by errael** [comment]
> "recursive callback" only happens when the callback itself consumes input, which isn't common. Maybe I should make it clearer in the docs.

Don't know, seems difficult to make perfectly clear. In this case, I guess the recursion is because the `Press enter` is indirectly called through `on_key` and the `<CR>` key is queued...

**Pull request merged**
