### PR TITLE
[RFC] Change 'backspace' default to "indent,eol,start"

### PR DESCRIPTION
**Pull request by ghost**
refs #1664

I kept this small given what was said in https://github.com/neovim/neovim/pull/1667#issuecomment-95935987.

### CODE REVIEW

**Comment by Pyrohh** [comment]
Also, if anyone is wondering why I removed the `P_VI_DEF` field, it's because:
- There's no mention of a Vi default for `backspace` in the docs, at least explicitly in `options.txt`
- I couldn't get it to work without removing it :disappointed:

**Comment by justinmk** [comment]
:+1:

**Comment by yagebu** [comment]
You could also document the change in `vim_diff.txt`, but apart from that it LGTM!

Regarding the `P_VI_DEF`: If that flag is set for an option, it means that (N)Vim uses the same default as Vi, and hence for those options, the default value for Nvim is not even set (or if it's set it's ignored). So removing the flag was exactly the right thing to do, as you've changed the default for Nvim, but the Vi default (`""`) stays the same.

**Comment by Pyrohh** [comment]
> You could also document the change in vim_diff.txt, but apart from that it LGTM!

Doh, I'll add that.

> Regarding the P_VI_DEF: If that flag is set for an option, it means that (N)Vim uses the same default as Vi, and hence for those options, the default value for Nvim is not even set (or if it's set it's ignored). So removing the flag was exactly the right thing to do, as you've changed the default for Nvim, but the Vi default ("") stays the same.

Thanks for explaining, that makes sense.

**Comment by Pyrohh** [comment]
Repushed.

**Comment by justinmk** [comment]
LGTM if the tests pass.

**Comment by Pyrohh** [comment]
> LGTM ***if the tests pass***.

Give it a week, Travis is very thorough :)

**Comment by Pyrohh** [comment]
The tests passed so I merged this. Thanks for the reviews everyone (and @fmoralesc for fixing my attempt at fixing the tests :grin:).

**Pull request closed without merging**
