### PR TITLE
fix: typo in lua guide config

### PR DESCRIPTION
**Pull request by Alkindi42**

### CODE REVIEW

**Comment by clason** [comment]
No, that's not a typo. Thanks, though!

**Comment by Alkindi42** [comment]
Ok thanks, that's confusing.

**Comment by clason** [comment]
You can use Vimscript in a Lua file (using, e.g., `vim.cmd`) and Lua in a Vimscript file (using `lua << EOF ... EOF` heredoc), so the extension doesn't limit you to either one or the other language.

**Comment by Alkindi42** [comment]
Just for fun, before my Pull Request, I asked chatGPT what he thinks of the phrase and he himself was confused 😂 

But I got it, thanks for the clarification.

**Pull request closed without merging**
