### PR TITLE
ci: enable automerge by default when backporting

### PR DESCRIPTION
**Pull request by dundargoc**
This will automatically merge backported PRs without human intervention
if the tests pass.

### CODE REVIEW

**Comment by dundargoc** [comment]
todo: test the damn thing

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Followup (brought up in chat): add `needs:backport` label if backport failed (`outputs.was_successful=false`).

(Also check if we can make it fail less, e.g., with https://github.com/korthout/backport-action#merge_commits set to `skip`.)

**Comment by dundargoc** [comment]
> (Also check if we can make it fail less, e.g., with [korthout/backport-action#merge_commits](https://github.com/korthout/backport-action#merge_commits) set to skip.)

I tried it out with and without and I'm pretty sure it doesn't make a difference. I think the merge commit is already skipped since we use `cherry_picking = auto`. I don't mind adding `merge_commits = skip` just to be safe though.

**Comment by clason** [comment]
I think this is specifically about when the action fails, which happens more often than I would like (and understand). I'm not sure if (in combination with our other flags) this will make a difference, but anything else than `fail` simply sounds... less likely to fail ;)

**Pull request merged**
