### PR TITLE
lsp: add show_buffer_diagnostics, rework diagnostics handler

### LINKED ISSUE #13324: [LSP Diagnostics Feature Enhancement] delay_until_save option for on_publish_diagnostics (if possible)
Hello Neovim LSP folks,

Spawning a new issue from [this Reddit post](https://www.reddit.com/r/neovim/comments/jw9i8b/lsp_diagnostics_is_it_possible_to_only_display).

As an ALE user one can specify to emit diagnostics after certain events such as: on buffer enter, on insert leave, on file save etc.

I use *on file save* since I don't like to see diagnostics until I actually change a file. This makes browsing files, often not my own, far more pleasant since linting/diagnostics display can be distracting. I prefer to see diagnostics only when I am actually editing files.

With linting it is often the case that a separate command line utility is run which makes setting up *on file save* processing much easier (I assume). LSP diagnostics however are produced by the language server even when not asked for, usually after the *documentOpen* request been processed (if I recall correctly).

So I can understand why Neovim LSP diagnostics appear out of thin air soon after opening a buffer.

I do wonder whether it is possible to delay the display of diagnostics until after the first file save? I would find that ideal.

I wonder, and hope, that something like this is possible:

```viml
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    signs = true,
    underline = false,
    update_in_insert = false,
    virtual_text = true,
    delay_until_save = true <<< NEW OPTION, MAYBE
  }
)
```

This theoretical example states to only display diagnostics after a file save operation has occurred, and then proceed as usual.

Best regards.

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #13324

Alternative to  #13742

@fsouza @lithammer @Jesse-Bakker @tjdevries  @bluz71 

We don't have to deal with scheduling/setting our own autocommands, users can just define their own autocommands to trigger show_buffer_diagnostics.

Your options are: 
* Always show every time we receive a 'textDocument/publishDiagnostics' if `show_diagnostics = true`
* Never show when receive a 'textDocument/publishDiagnostics' if `show_diagnostics = false`
* Never show when receive a 'textDocument/publishDiagnostics' if `show_diagnostics = false`, but then set an autocommand to trigger `show_buffer_diagnostics`

Set via the usual method

```lua
  vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
      -- disable virtual text
      -- virtual_text = false;

      -- disable underline
      -- underline = false,

      -- disable signs
      -- signs = false,
 
      display_diagnostics = false,
    }
  )
-- shows on BufWrite for all clients attached to current buffer, where virtual_text is false, but underline and signs default true
vim.cmd[[autocmd BufWrite * lua vim.lsp.diagnostic.show_buffer_diagnostics(nil, nil, {virtual_text = false})]]
```

Independently, you can assign an autocommand to call `vim.lsp.diagnostic.show_buffer_diagnostics()` which optionally takes a bufnr, and list of client ids, and a config table which defines what to draw. This will show all of the currently available diagnostics from the last invocation of `textDocument/publishDiagnostics`

### CODE REVIEW

**Comment by bluz71** [comment]
In this scheme is there scope to delay the showing of diagnostics a certain amount after the autocmd is triggered (as discussed in #13742)?

I do like this API more than the other one, I think most folks would choose display diagnostics true and be done with it.

But in my case where I only want to display diagnostics after InsertLeave and TextChanged, hence a delay really would helpful.

**Comment by mjlbach** [comment]
Sure `vim.cmd[[autocmd BufWrite * :call timer_start(1000, { -> v:lua.vim.lsp.diagnostic.show_buffer_diagnostics()})]]`

**Comment by bluz71** [comment]
Excellent. I will give that a test in a little while.

I believe this is the better API.

**Comment by Jesse-Bakker** [comment]
This looks like something I will enjoy using. Thanks @mjlbach !

**Comment by mjlbach** [comment]
I'm tempted to just remove the failing tests. 

```
[  ERROR   ] test/functional/plugin/lsp/diagnostic_spec.lua @ 407: vim.lsp.diagnostic vim.lsp.diagnostic.on_publish_diagnostics can perform updates after insert_leave
[  ERROR   ] test/functional/plugin/lsp/diagnostic_spec.lua @ 437: vim.lsp.diagnostic vim.lsp.diagnostic.on_publish_diagnostics does not perform updates when not needed
[  ERROR   ] test/functional/plugin/lsp/diagnostic_spec.lua @ 491: vim.lsp.diagnostic vim.lsp.diagnostic.on_publish_diagnostics never sets virtual text, in combination with insert leave
```

These will never work, as show_buffer_diagnostics checks if the buffer is attached to the client passed in (or checks which of active clients the buffer is attached to, and pases the client_id to M.get. We're not faking a client in these tests, so the autocommand callbacks to show_buffer_diagnostics won't work.

**Comment by bluz71** [comment]
Ok, I just tested this PR with the following configuration:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    signs = {
      severity_limit = 'Warning',
    },
    underline = false,
    -- update_in_insert = false,
    -- show_diagnostic_autocmds = { 'InsertLeave', 'TextChanged' },
    display_diagnostics = false,
    virtual_text = {
      spacing = 2,
      severity_limit = 'Warning',
    },
  }
)

vim.cmd[[autocmd InsertLeave,TextChanged * :call timer_start(500, { -> v:lua.vim.lsp.diagnostic.show_buffer_diagnostics()})]]
```

500ms is enough time for the server to get the responses to the client.
I don't appear to need debouncing.
Interactivity appears good. 
It basically solves my issue #13324
Many thanks.

Now for the minor nitpicks:

- The `show_buffer_diagnostics` call is not inheriting my diagnostic handler settings (which is understandable). Can you suggest how I struct my Lua code such that my `signs`, `underline` and `virtual_text` settings listed in my `on_publish_diagnostic` handler can also be shared with the `show_buffer_diagnostics` function for the autocmd. Ideally DRY (don't repeat yourself) style.

- Secondly is the `vim.cmd[[autocmd...]]` creating a global event listener for all buffer types via the * notation? If it is, I would feel more comfortable if the `autocmd` event listener was only active for LSP attached buffers. Maybe it isn't, I don't know.

- Lua notation for `autocmd` would likely improve the look of the code a great deal.

**Comment by mjlbach** [comment]
> The show_buffer_diagnostics call is not inheriting my diagnostic handler settings (which is understandable)

> Secondly is the vim.cmd[[autocmd...]] creating a global event listener for all buffer types via the * notation? 


I would solve both of the issues like this:

```
local diagnostic_config = {
    virtual_text = false;
    signs = true,
    underline = true,
  }
local handler_config = vim.deepcopy(diagnostic_config)
handler_config.display_diagnostics = false

function DiagnosticTimer(bufnr)
  vim.defer_fn(function()
    vim.lsp.diagnostic.show_buffer_diagnostics(bufnr, nil, diagnostic_config) 
  end, 1000)
end

local nvim_lsp = require('lspconfig')

local on_attach = function(_, bufnr)
  vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics,  handler_config
    )
  vim.cmd(string.format([[autocmd BufWrite %s lua DiagnosticTimer(%s)]],
      vim.fn.expand("%"), bufnr))
end

local servers = {'gopls'}

for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
  }
end
```

There's not much you can't do, right now the only reason I copied the table is because the validation params for handler take an additional key, display_diagnostics (virtual_text, highlights, underline).

You'll also notice in this example I used a global lua function instead of doing it in vimscript, and a uv loop instead of the timer_start vimscript function. You can use either, the advantage with this way is you can write a super complex lua function. Disadvantage being you have a global lua function (nbd). 

You could have written this all in vimscript, and converted the lua table into a vimdict into a string, or written some wrapper around a lua command. There are tons of different options, but once lua autocommands become a thing probably the way I showed you will be preferred. I'm pretty sure there's no disadvantage vs vim's timer_start.

**Comment by bluz71** [comment]
This appears to work for me, but I don't know if it as optimised as it can be:

```lua
local diagnostic_flags = {
  signs = {
    severity_limit = 'Warning',
  },
  underline = false,
  virtual_text = {
    spacing = 2,
    severity_limit = 'Warning',
  },
}

local diagnostic_config = vim.deepcopy(diagnostic_flags)
diagnostic_config.display_diagnostics = false

local diagnostic_handler = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, diagnostic_config
)

function DiagnosticTimer()
  vim.defer_fn(function()
    vim.lsp.diagnostic.show_buffer_diagnostics(nil, nil, diagnostic_flags)
  end, 500)
end

local lsp_on_attach = function(client)
  completion.on_attach(client)

  vim.cmd('autocmd InsertLeave,TextChanged <buffer> lua DiagnosticTimer()')
end

nvim_lsp.dartls.setup {
  on_attach = lsp_on_attach,
  handlers = {
    ['textDocument/publishDiagnostics'] = diagnostic_handler
  }
}

nvim_lsp.tsserver.setup {
  on_attach = lsp_on_attach,
  handlers = {
    ['textDocument/publishDiagnostics'] = diagnostic_handler
  }
}
```

Notice the use of `vim.cmd('autocmd InsertLeave,TextChanged <buffer> lua DiagnosticTimer()')`, I think that should make it buffer local.

I am hijacking this PR and I should not do that.

I am happy where we have ended up. My issue in #13324 is solved by this PR.

**Comment by tjdevries** [comment]
Hmmm, I'm not sure I like this as much as the autocommands approach. I will read them again and consider the situation. Some of the difficulties of the initial implementation will be solved when you can pass a lua callback to an autocommand

**Comment by tjdevries** [comment]
Some thoughts (will probably edit some more):

1. This approach does not automatically share the configuration of the display with the handler
2. This approach may lead to calling showing displays much more often than necessary (if you're calling it in a timer for example, which will be set even when there are no new diagnostics to display).

It is possible to debounce in the old method as well, but perhaps slightly complicated atm. I think we can make it possible to debounce more easily when we ship more debounce utilties / wrappers.

**Comment by mjlbach** [comment]
> This approach does not automatically share the configuration of the display with the handler

I anticipate that most of the time, people would not be using the display option in the handler when using the autocommand. We could also move this to being a buffer option instead of wrapping the handler to accept the config options.

>  This approach may lead to calling showing displays much more often than necessary (if you're calling it in a timer for example, which will be set even when there are no new diagnostics to display).

One thing I could do would be to make show_buffer_diagnostics aware if the diagnostics were updated since the last draw. That would avoid unnecessary redraws. 

I like this method because the complexity of implementation is lower, and it lets people do arbitrary autocommands more easily, but I'm also happy to improve the other version/PR.

**Comment by bluz71** [comment]
I am not fussed if the API changes. Refinement is fine. Go ahead.

But I do want an ability to trigger diagnostic display a user configurable amount of milliseconds after a user chosen autocmd. That is a must to be an ALE replacement.

When required I am here to test, just buzz me.

Best regards.

**Comment by mjlbach** [comment]
@bluz71 You might want to unsubscribe to the issue for now 😆  I'll ping you if necessary

@tjdevries I just pushed a fix for the unecessary redraws, I tested and it now only redraws when the handler has updates.

**Comment by bluz71** [comment]
I like to follow this, so I will remain subscribed. But I will go quiet leaving Neovim devs space to discuss without my clutter :)

**Comment by mfussenegger** [comment]
@mjlbach can we close this, or is this still worth following up, despite the vim.diagnostic refactor?

**Comment by mjlbach** [comment]
Close, but I still think the idea of driving diagnostics with an auto command instead of string options is useful (cc @gpanders)

**Pull request closed without merging**
