### PR TITLE
[RFC] CMake: Hide stderr output for successful test runs.

### PR DESCRIPTION
**Pull request by fwalch**
A possible fix for #1301, based on @Islah's last comment there.

### CODE REVIEW

**Comment by fwalch** [comment]
Rebased.

**Comment by fwalch** [comment]
Any comments on this? :-)
To recap, this PR suppresses stderr output from the unit tests (fixing #1301), but assures that this output doesn't change unnoticed at some point.

**Comment by jszakmeister** [comment]
@fwalch I'm on the fence about asserting the error output.  It's not necessarily an error for us to emit something, IMHO, but I think it's nice to see the error output if something fails--just in case some useful information is buried in there.

**Comment by elmart** [comment]
Not sure about assertion mechanism. Current approach makes so we'd have to change CMakeLists.txt (to edit EXPECTED_ERROR_OUTPUT) each time a new test produces some output. Maybe externalizing expected error output to its own file would be better, though it would still create a non-obvious dependency for test creators. Or maybe I'd be more in favor of another approach that doesn't require changes when tests are added (like hiding output except if something fails, in which case all output gets dumped).

**Comment by fwalch** [comment]
> hiding output except if something fails, in which case all output gets dumped

That sounds like a good solution to me, updated the PR. Full output if a unit test fails (in this case, I manually changed an assertion):

```
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
199 successes / 1 failure / 0 errors / 0 pending : 0.0 seconds

Failure → /home/florian/Projects/neovim/test/unit/os/fs_spec.lua @ 76
fs function os_dirname returns OK and writes current directory into the buffer if it is large
    enough
/home/florian/Projects/neovim/test/unit/os/fs_spec.lua:77: Expected objects to be the same.
Passed in:
(number) 1
Expected:
(number) 0

stack traceback:
	/home/florian/Projects/neovim/test/unit/os/fs_spec.lua:77: in function </home/florian/Projects/neovim/test/unit/os/fs_spec.lua:76>

-- Output to stderr:
E94: No matching buffer for _test_
E94: No matching buffer for _test_
E94: No matching buffer for _test_
E94: No matching buffer for test
CMake Error at /home/florian/Projects/neovim/cmake/RunTests.cmake:25 (message):
  Running unit tests failed with error: 1.
```

**Comment by elmart** [comment]
LGTM.

**Comment by justinmk** [comment]
nice compromise!

**Pull request merged**
