### PR TITLE
api: Allow nvim_buf_set_text to append after last line

### PR DESCRIPTION
**Pull request by mfussenegger**
If you've a buffer with:

    first_line
    second_line

This now allows to use nvim_buf_set_text to insert text after the second
line:

    nvim_buf_set_text(0, 2, 0, 2, 0, {'third line'})

Before this was an error (start_row out of bounds) and it was necessary
to append the text on the last column of the last line:

    nvim_buf_set_text(0, 1, 10, 1, 10, {'', 'third line'})

### CODE REVIEW

**Review by mjlbach — APPROVED** [review]
This LGTM, maybe should get signoff from @bfredl

**Comment by bfredl** [comment]
Hmm, this should actually require a _final_ empty new line in the replacement text. Compare if you do:

    nvim_buf_set_text(0, 1, 0, 1, 0, {'third line', ''})

or 

     nvim_buf_set_text(0, 1, 0, 1, 0, {'third line', ''})

both create a new line at index `start_line`, so the corresponding operation should be

     nvim_buf_set_text(0, 2, 0, 2, 0, {'third line', ''})

**Comment by mfussenegger** [comment]
> this should actually require a final empty new line in the replacement text. Compare if you do: 

If I understand it right, `nvim_buf_set_text(0, 1, 0, 1, 0, {'third line', ''})` inserts `third line` at the start of line 1, and then inserts a `''`, which causes the text that was previously in line 1 to move to the next line.

In `nvim_buf_set_text(0, 2, 0, 2, 0, {'third line', ''})` line 2 is already empty, so there is nothing to shift. Wouldn't the `''` just start a new line?

**Comment by bfredl** [comment]
Well, If you take the interpretation that there is a empty line after the final EOL that you can put stuff at, then a new line ending needs to be _added_ so the operation could be repeated according to the same interpretation, which is represented by the final `, ''`. . Another interpretation is that if you count the total number of line separators of the replaced and the new texts, this should uniquely determine the change of `line_count`, regardless of position.

**Comment by mfussenegger** [comment]
How should `nvim_buf_set_text(0, 2, 0, 2, 0, {'third line'})` behave then? Result in an error?

For comparison, in an empty buffer:

```
```

```
:lua vim.api.nvim_buf_set_text(0, 0, 0, 0, 0, {'one'})
```

Changes the buffer to:

```
1| one
```

Compared to:

```
```

```
:lua vim.api.nvim_buf_set_text(0, 0, 0, 0, 0, {'one', ''})
```

```
1| one
2|
```

**Comment by bfredl** [comment]
> How should nvim_buf_set_text(0, 2, 0, 2, 0, {'third line'}) behave then? Result in an error?

Probably. an option could to make it work automagically, but in case one deliberately supplies the final line ending it _must_ be properly handled (not cause one extra line) because otherwise it is actively inconsistent with already legal arguments. Not sure that is helpful in the end as it easy to make misinterpretations of the semantics if you just use it without reading docs (like who would ever do that?).

> For comparison, in an empty buffer:

an empty buffer is always considered to have one empty line (zero lines is not possible, and already triggers a warning when it _should have been_ the result of any edit operation).

**Comment by mfussenegger** [comment]
I'm still not convinced :)

How do you explain that in the following case the trailing `''` is not necessary?

```
One
```


```
lua vim.api.nvim_buf_set_text(0, 0, 3, 0, 3, {'', 'Two'})
```

This currently results in

```
One
Two
```

Based on that, I'd infer that if neovim allowed the starting position to be past the last line, `lua vim.api.nvim_buf_set_text(0, 0, 3, 0, 3, {'', 'Two'})` and `lua vim.api.nvim_buf_set_text(0, 1, 0, 1, 0, {'Two'})` should behave the same.

**Comment by bfredl** [comment]
@mfussenegger what is there to explain? That already behaves consistent with everything what I said before. Not sure how it follows from a case where the line separator _is_ explicit to that it should be implicit in another case.

**Comment by mfussenegger** [comment]
> Not sure how it follows from a case where the line separator is explicit to that it should be implicit in another case.


You argued that in `lua vim.api.nvim_buf_set_text(0, 1, 0, 1, 0, {'Two'})` there would have to be an explicit *trailing* `''`. What I don't get is why this would be necessary, if it currently is not necessary with `vim.api.nvim_buf_set_text(0, 0, 3, 0, 3, {'', 'Two'})` ? I understand the need for the starting `''` to create a new line.
I also understand the need for a trailing `''` to insert something in the middle of the document. I need to shift the line that's already at the range to the next line.


Based on the docs:

> Sets (replaces) a range in the buffer
> [...]
> To insert text at a given index, set `start` and `end` ranges to the same index.


I'd assume that if I set `start` and `end` to the same index it would be similar to moving to that position, and then inserting the parts in the `replacement` array. That doesn't explain the need for a trailing `''` at the last line.


You probably have some model of the internals in your head where this makes sense, but from my perspective as a user of the API it doesn't.


In any case, if you've a strong opinion on this I'd close the PR without merging the change, because if we require an extra trailing `''` it wouldn't accomplish my goal to avoid extra processing steps that are required to apply LSP `TextEdit` payloads.

**Comment by bfredl** [comment]
> You argued that in lua vim.api.nvim_buf_set_text(0, 1, 0, 1, 0, {'Two'}) there would have to be an explicit trailing ''. What I don't get is why this would be necessary, if it currently is not necessary with vim.api.nvim_buf_set_text(0, 0, 3, 0, 3, {'', 'Two'}) ? I understand the need for the starting '' to create a new line.

Well, as I said before, it is help consider an analogous case for adding a line in the middle of the file. In that case, clearly, [1, 0] adresses the position just _after_ a `\n` while [0, 3] addresses the position just _before_. So, does it not make sense that in the first case you end with a final `\n` in the inserted text, while in the latter you need a `\n` in the start of the text? Quite usefully (IMHO), the total change of number of lines is determined _solely_ by the difference of end_line-start_line and the length of the replacement vector, regardless of the current contents of a buffer (or an error is raised).

**Comment by bfredl** [comment]
> '' it wouldn't accomplish my goal to avoid extra processing steps that are required to apply LSP TextEdit payloads.

I understand the concern, but I don't think the internal API:s should be determined solely by the LSP spec, which uses different conventions than us for a lot of stuff (and sometimes between servers). We should add API functionality to make conversion steps _efficient_ (like the utf16 helper functions), but we cannot expect generally to pass LSP data unconverted to general-purpose API functions always.

**Comment by mfussenegger** [comment]
> Well, as I said before, it is helpful consider an analogous case for adding a line in the middle of the file. In that case, clearly, [1, 0] adresses the position just after a \n while [0, 3] addresses the position just before.

Ah, I think this is where our mental model differs. In my mind the `\n` weren't explicitly there, but were kinda implicit in a grid structure. So if I understand you right, it looks like this?



`nvim_set_text(0, 0, 3, 0, 3, {'', 'Two'})`

```
One|\n
   ↑
   [0, 3]
```

First inserts `''`

```
One\n
|\n
```

Then inserts `'Two'`

```
One\n
Two|\n
```


But with `nvim_set_text(0, 1, 0, 1, 0, {'Two'})`, it would look like this:


```
One\n
|
↑
Cursor past last line
```


```
One\n
Two|
   ↑
   missing \n
```


I think now I get it and it makes sense to me too. Thank you for the elaboration and patience.
So we drop the PR?

**Comment by bfredl** [comment]
Regardless, maybe we should allow col=-1 as an alias for the length of the line?

**Comment by mfussenegger** [comment]
> Regardless, maybe we should allow col=-1 as an alias for the length of the line?

Sounds good to me :+1:

**Pull request closed without merging**
