### PR TITLE
[RFC] vim-patch:8.0.0435

### PR DESCRIPTION
**Pull request by ckelsel**
#### vim-patch:8.0.0435: some functions are not tested

Problem:    Some functions are not tested.
Solution:   Add more tests for functions. (Dominique Pelle, closes vim/vim#1541)
https://github.com/vim/vim/commit/41042f3cfdb91f946e553456278a995e61dd8578

### CODE REVIEW

**Comment by ckelsel** [comment]
Test results:


From test_alot.vim:
Found errors in Test_hlexists():
function RunTheTest[35]..Test_hlexists line 2: Expected 0 but got 1
function RunTheTest[35]..Test_hlexists line 4: Expected 0 but got 1
TEST FAILURE
```
+func Test_hlexists()
 +  call assert_equal(0, hlexists('does_not_exist'))
 +  call assert_equal(0, hlexists('Number'))   // Expected 0 but got 1
 +  call assert_equal(0, highlight_exists('does_not_exist'))
 +  call assert_equal(0, highlight_exists('Number')) //Expected 0 but got 1
```

**Comment by jamessan** [comment]
Neovim defaults to having syntax enabled, so that highlight group is already defined.

This should fix it, assuming it doesn't cause other problems. :)

```diff
diff --git i/src/nvim/testdir/runnvim.sh w/src/nvim/testdir/runnvim.sh
index 43556f3ad..dbdc524b6 100755
--- i/src/nvim/testdir/runnvim.sh
+++ w/src/nvim/testdir/runnvim.sh
@@ -32,6 +32,7 @@ main() {(
   if ! "$nvim_prg" \
     -u NONE -i NONE \
     --headless \
+    --cmd 'syntax off' \
     --cmd 'set shortmess+=I noswapfile noundofile nomore' \
     -S runnvim.vim \
     "$tlog" > "out-$tlog" 2> "err-$tlog"
```

**Comment by ckelsel** [comment]
I think we can add `syntax off` in the front of test
```
+func Test_hlexists()
 +  syntax off 
 +  call assert_equal(0, hlexists('does_not_exist'))
 +  call assert_equal(0, hlexists('Number'))   
 +  call assert_equal(0, highlight_exists('does_not_exist'))
 +  call assert_equal(0, highlight_exists('Number')) 
```

**Comment by jamessan** [comment]
No, by then the highlight group is already defined.  Also, it's possible there may be other tests that rely on Vim's default, so it's better to set more generally.

**Comment by ckelsel** [comment]
@jamessan `--cmd 'syntax off'` failed .
```
Test results:


From test_alot.vim:
Found errors in Test_hlexists():
function RunTheTest[35]..Test_hlexists line 2: Expected 0 but got 1
function RunTheTest[35]..Test_hlexists line 4: Expected 0 but got 1
TEST FAILURE
```

**Pull request closed without merging**
