### PR TITLE
[RFC] Fix line length lint errors in main.c

### PR DESCRIPTION
**Pull request by war1025**
Lint has been broken for a week and no one seemed in a hurry to fix it.

Here is a fix. Or someone else can decide to fix it another way

### CODE REVIEW

**Comment by Pyrohh** [comment]
I wonder if the warnings are due to [neovim/doc](https://github.com/neovim/doc) being 8 days out of date.  Checking out at 94015cd (the date of @marvim's last commit) and running `make lint` results in no errors.

cc @ZyX-I, as you probably understand the lint suppression system better than me

**Comment by ZyX-I** [comment]
No, I do not. Problem is not lint suppression system, problem is when and how this thing is updated. I do not know enough about used bot.

**Comment by war1025** [comment]
Regardless, it seems like bad practice to have code that purposefully violates lint. Especially when it is left broken for so long, and when it functioning is dependent on a script or bot that is not readily understood.

**Comment by mhinz** [comment]
We know the issue and it will be fixed soon. Sorry for the inconvenience.

**Comment by war1025** [comment]
When can we expect the lint to be fixed? It appears that people aren't interested in this fix. 

IMHO it makes the project look bad to have builds broken this long.

**Comment by Pyrohh** [comment]
> IMHO it makes the project look bad to have builds broken this long.

I think so too, but I don't think there are many people who have the required access to fix this.
@justinmk said on Gitter that he's sick, so it's understandable.

**Comment by Shougo** [comment]
> @justinmk said on Gitter that he's sick, so it's understandable.

Oh, I don't know that...

**Comment by Pyrohh** [comment]
Since this doesn't seem likely to be merged I'll close this.  I hope @justinmk is okay, he's been out a while.

**Comment by justinmk** [comment]
clint build is fixed now, so this PR should not be needed. I was out last 1-2 weeks with pneumonia.

**Comment by Shougo** [comment]
@justinmk Nice work!  Take care of yourself...

**Pull request closed without merging**
