### PR TITLE
[RFC] Change detection for python interpreter

### PR DESCRIPTION
**Pull request by jonthn**
Rework the code a bit to use a function
Add well-known python 2.x naming interpreter
Use absolute path to python so system() honors $PATH

### CODE REVIEW

**Comment by jonthn** [comment]
Basically I just updated the detection of python interpreters I made in an older version, I hope it will be okay for you as it saves me of specifying in nvimrc my python path for each host so I suppose it could help others.

Sorry for the strange commit history I thought it would be better to include the new changes in the same pull request but I didn't know how to cleanly do it in github.

**Comment by justinmk** [comment]
Thanks @jonthn, can you squash the commits and force push (`git push -f ...`).

> Unfortunately (even though this path is added in my $PATH) the system() call in VimL isn't taking into account this path,

- What does `:echo $PATH` say in neovim? 

> The first 'path' in my $PATH value is of course $HOME/pkg/bin
> `system("python2.7 ......")` 

What does `:echo system("echo $PATH")` report? And can you post the output of `exepath("python2.7")`.

**Comment by jonthn** [comment]
@justinmk I was trying to avoid push force to keep the previous commit in the pull request (for a better history) and also I was trying to use the GitHub for Mac application. Thanks for giving me the right direction I've made the changes to the repository

Also I didn't check again if exepath() was still necessary, but I just tried and it works now without it. So I've removed those calls. Thanks again.

And to answer your questions both `:echo $PATH` and `:echo system('echo $PATH')` report the same content.

**Comment by jonthn** [comment]
Just thought I would document this here.
I experienced an issue when using plugins with my other Python installation (the one in my home directory). It was due to a native library for python compiled for the system Python installation once I recompiled this library (in that case YouCompleteMe) it worked perfectly.
I didn't search if the current python executable (or full path) used by neovim is available to plugin or others but that would help in that case I think. 

I got messages like those : 
```
Error detected while processing function youcompleteme#Enable..<SNR>103_SetUpPython..provider#python#Call:            
line    1:                                                                                                            
Channel was closed by the client                                                                                      
Press ENTER or type command to continue                                                                               
....
```
and in the $HOME/.nvimlog
```
2015/01/04 21:14:38 [error @ job_err:357] 46882 - Channel 1 stderr: Fatal Python error: PyThreadState_Get: no current thread

2015/01/04 21:14:38 [error @ call_set_error:730] 46882 - Msgpack-RPC error: Channel was closed by the client
```
But in nvim I was able to do `:py print 'hello'` and I also tested snake.py (found in another issue) and it worked without problems.

**Comment by blueyed** [comment]
This appears to conflict / get obsoleted by #2208.

This PR here should probably get reviewed to see if it has things that should be taken over.

**Comment by jonthn** [comment]
@blueyed there has been some changes since I made this PR ;) I agree with you it's outdated.

I quickly read the PR #2208 the only missing point which is rather important in my setup(s) is the ability to test not only the executable "python" / "python2" but also "python2.6" "python2.7" ... as some package manager doesn't set a default to the fully identified version. And as I often change system (different host/hardware/OS) I don't want to set a default python that override the one provided by the system and don't want to pollute this python installation. Finally I also don't want to maintain a full path to a python installation in my vimrc

**Comment by Shougo** [comment]
@jonthn OK.  But I don't want to add the hardcoded version number in #2208.

**Comment by Shougo** [comment]
> I quickly read the PR #2208 the only missing point which is rather important in my setup(s) is the ability to test not only the executable "python" / "python2" but also "python2.6" "python2.7" ... as some package manager doesn't set a default to the fully identified version. And as I often change system (different host/hardware/OS) I don't want to set a default python that override the one provided by the system and don't want to pollute this python installation. Finally I also don't want to maintain a full path to a python installation in my vimrc 

Implemented in #2208.  Please check it.

**Comment by jonthn** [comment]
@Shougo  Sorry for the late reply. Just wanted to say it works for me. Thanks a lot :)

**Comment by fwalch** [comment]
> I quickly read the PR #2208 the only missing point which is rather important in my setup(s) is the ability to test not only the executable "python" / "python2" but also "python2.6" "python2.7"

That's bound to cause confusion, IMO.. for example, installing a new Python (not set as default) would suddenly switch Neovim to use that version and break the Python plugins for no apparent reason. Users would need to be familiar with the order in which Neovim resolves Python interpreters to figure that out.
Also, why do you consider installing a Python module "polluting" this Python?

**Comment by jonthn** [comment]
> Le 25 mai 2015 à 08:34, Florian Walch <notifications@github.com> a écrit :
> 
> I quickly read the PR #2208 the only missing point which is rather important in my setup(s) is the ability to test not only the executable "python" / "python2" but also "python2.6" "python2.7"
> 
> That's bound to cause confusion, IMO.. for example, installing a new Python (not set as default) would suddenly switch Neovim to use that version and break the Python plugins for no apparent reason. Users would need to be familiar with the order in which Neovim resolves Python interpreters to figure that out.
> Also, why do you consider installing a Python module "polluting" this Python?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

I can't touch/modify the base Python installation, so I install a new python but I don't want to change the interpreter pointed by 'python' so using python2.6 / python2.7 I'm always sure I will use the correct python interpreter. This behavior allows me to avoid maintaining a specific 'vimrc' for each system I run neovim on.
In an usual setup IIRC if you have one of the python interpreter from the ones tested that provide the neovim module it will use this one and forget about the other so I don't understand how it would break the Python plugins, the only possibility is if you install the same python version elsewhere, but in that case you'll be forced to use the variable in your vimrc to identify which python interpreter to use.

**Comment by fwalch** [comment]
Sorry, I had come to a wrong conclusion (which is why I deleted my comment... damn those mail notifications :-D). Anyway, I'm still not sure whether this won't cause confusion with Neovim modules (accidentally) installed into multiple Pythons, but I understand you use case now, thanks for explaining.

**Comment by jonthn** [comment]
No problem that's why I couldn't find the message and replied by mail (my bad :( I will know next time).
With multiple python I admit it could be a problem but as long as it rather easy to troubleshoot with messages in ```:messages``` a user should be able to solve this.

**Comment by blueyed** [comment]
I agree with @fwalch that it would be simpler to only check for `python` and `python2`/`python3`.

For @jonthn's use case a wrapper around Vim could be used that sets up the `PATH` accordingly, and/or provides a `python` wrapper script to be used with Neovim.

But then I can also see that it might be more comfortable to use the first Python that is setup to provide the `neovim` module - with the drawback of a performance decrease, when multiple interpreters get checked automatically.

@jonthn 
Couldn't you use `g:python_host_prog` / `g:python3_host_prog` to point it at e.g. `python2.7`?

**Comment by jonthn** [comment]
@blueyed My whole point is to avoid setting g:*_host_prog as it differs from different machine it's not always 2.7. If that would be better for you would it be acceptable to add the possibility to define a dictionary with additional executable to check ? Which in my case would contain 'python2.7', 'python2.6' ?

**Comment by blueyed** [comment]
> would it be acceptable to add the possibility to define a dictionary with additional executable to check ?

Makes sense to me.

@Shougo @jonthn 
What do you think?

**Comment by blueyed** [comment]
> Makes sense to me.

OTOH it defeats the whole purpose, because additional checks would be required then still.

A solution would be for you to check and set this manually in your vimrc, but that's not very comfortable.

**Comment by jonthn** [comment]
> OTOH it defeats the whole purpose, because additional checks would be required then still.
I know but it seems to cause too much trouble for everyone so I'll handle this in my vimrc and that's less painful to have a  static dict of python possibilities than maintaining on each host the right version.

**Comment by blueyed** [comment]
@jonthn 
Ok.  Please let us know what you come up with, and how good it works out for you.

Please also note that this has not really been decided upon yet, but was most recently mentioned by @Shougo in https://github.com/neovim/neovim/pull/2735#discussion_r30958798.

**Comment by Shougo** [comment]
> @blueyed My whole point is to avoid setting g:*_host_prog as it differs from different machine it's not always 2.7. If that would be better for you would it be acceptable to add the possibility to define a dictionary with additional executable to check ? Which in my case would contain 'python2.7', 'python2.6' ?

I think you can check the python interpreters in your .vimrc.

```vim
let g:python_host_prog = get(filter(['python2.7', 'python2.6', 'python2.5'], 'executable(v:val)'), 0, 'python2')
 ```

I think it is better than the check in pythonx.vim.

**Comment by jonthn** [comment]
@Shougo Thanks this works.

But I was wondering if it would be possible to include this 2 lines (the other line for python3) inside the runtime directory under a new name something like ```versioned_python_detection.vim```?
So it would be possible to add in a ```.vimrc```
```
runtime!  ..path.../versioned_python_detection.vim
```
So it would benefit to other people without having to search too much on the Web.

**Pull request closed without merging**
