### PR TITLE
filetype.lua: More extensible / reusable filetype detection subsystem

### PR DESCRIPTION
**Pull request by naruaway**
I have been thinking about file type detection in Neovim and researched briefly [how other editors are doing filetype detection](https://gist.github.com/naruaway/2445a97de36fdfd408631f89f29f72a9).
**My hope is that this PR sparks a meaningful discussion around file type detection in Neovim.**

Note that nothing here is definitive and any feedback is appreciated. I am not a Neovim dev but I love Neovim as a user (and love lua filetype detection initiative in general!) and I just want to help it to improve where possible.

## My vision about Neovim filetype detection system
Since filetype.lua will make it harder to port Vim filetype detection patches, it would be nice if we can take this opportunity to make it better in several ways aside from performance boost.
Here I list what I would expect from Neovim filetype detection system

- It should optimize for common case for adding new filetypes (e.g. shebang / firstLine) like [other modern editors like VS Code](https://gist.github.com/naruaway/2445a97de36fdfd408631f89f29f72a9)
- Every aspect / behavior of filetype detection system should be able to be overridden by users. Workaround or adhoc fix should be always possible (maximum configurability, Vim / Neovim way?)
- It should be open for future extension (e.g. use filetype [detection definition from tree-sitter in the future?](https://gist.github.com/naruaway/2445a97de36fdfd408631f89f29f72a9))
- It should keep the existing behavior where possible
  - `:filetype off` and `:filetype on`?
- It should work well with existing way of defining file types ([several plugins are using `ftdetect` to set autocommands](https://github.com/nvim-treesitter/nvim-treesitter/blob/0f01bbb1c28055de6b81da1ba7385e01e0b67215/ftdetect/zig.vim#L1))
- Filetype detection subsystem should be more reusable (e.g. even without buffer)
  - I would like to know exact use case though

## Proposal implemented in this PR
- Separated "strategy" (functions) and "definition" (tables) to make it simpler and configurable
  - Users can override both vim.filetype.strategy and vim.filetype.definition
    - vim.filetype.strategy can be overridden like [vim.paste](https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/doc/lua.txt#L1293-L1301)
- `vim.filetype.detect()` can be used without underlying buffer (buffer-less mode) like `vim.filetype.detect {path = 'main.py'}` returns `"python"`
  - This is possible by using `clue` parameter, which includes all the clue filetype detector could use and it even includes abstracted `clue.getline()` interface (this API might need to be updated to deal with [other cases like `nextnonblank()` usage](https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/autoload/dist/ft.vim#L228))
- Stopped using numbers for priority
  - Note: Vim has built-in "priority" system about filetype assignment
    - `:setfiletype FALLBACK ft` &lt; `:setfiletype ft` &lt; `set filetype=ft`
    - However this is not used a lot since overriding filetype in this way will trigger multiple `FileType` autocmd, which has undesired side effects
    - So if we can avoid relying on this, it would be nice
  - I saw [a PR introduced](https://github.com/neovim/neovim/pull/16952/commits/d18d25f99fd58fa99ee2547e3fe7888861132309) `priority = -1` just to retain orders inside internal definitions
      - I think it's simpler and more obvious to rely on definition ordering
        - Later definition will have higher priority and I think this would work for more than 90% of the case
          - Edge case can be always worked around by overriding "vim.filetype.strategy"
- filetype.lua will delegate detection to `scripts.vim` as a fallback
- vim.filetype.detect (vim.filetype.detect_main) internally uses vim.filetype.strategy, which is using vim.filetype.definition
- both "strategy" and "definition" can be overridden
  - By overriding vim.filetype.detect_main, users can even change "how to combine strategies" or interleave new strategy (e.g. something like using tree-sitter filetype definitions)

## Guide for reviewers
- To focus on the logic rather than each definition, temporarily I stripped most of existing definitions. So probably it's easier to view the whole filetype.lua rather than checking the diff.
  - If Neovim devs agree with the overall direction, I can put the actual definition somewhere (probably in a separate file like `filetype/definition.lua`) (also incorpolating recent changes around filetype.lua definitions)

### Users can add a new file name pattern
```lua
table.insert(vim.filetype.definition.filename_pattern_low_priority, {'.*awesome.*', 'myawesomescript'})
table.insert(vim.filetype.definition.filename_pattern, {'.*-awesome', 'myawesomescript'})
```
### Users can add a new logic for extension handler to "break a tie" for the same extension
```lua
vim.filetype.definition.extension.ts = (function(overridden)
   return function(clue)
     if clue.path and clue.path:find('super') then
       return 'supertypescript'
     end
     return overridden(clue)
   end
end)(vim.filetype.definition.extension.ts)
```
### Users can modify the filetype detection logic itself
```lua
vim.filetype.detect_main = (function(overridden)
   return function(clue)
     local ft =  overridden(clue)
     if ft == 'python' and vim.g.python_should_be_python3 then
       return 'python3'
     end
     if ft then return ft end
     return my_own_strategy(clue)
   end
end)(vim.filetype.detect_main)
```
### Users can use the detection logic in isolation without any buffers
```lua
local ft1 = vim.filetype.detect {path = 'main.py'} -- this returns "python"

local ft2 = vim.filetype.detect {
  path = 'main',
  getline = function(lnum)
    if lnum == 1 then
      return '#!/usr/bin/env node'
    end
    return ''
  end
} -- this returns "javascript"
```
Since `is_current_buffer` is not passed as `clue`, it will skip all the routines which could use current buffer information. (see `wrap_legacy_side_effectful_filetype_detector` for details)

Note that I am not sure whether this ability is **really** needed or not.
We could just create a buffer and possibly use `nvim_buf_call` API. But maybe the ability to know filetype without neither causing any side effect nor requiring special setup could be nice to have.
Note: [related comment by @tjdevries](https://github.com/neovim/neovim/pull/16600#issuecomment-1005889399)

## Known issues for this PR aside from "being not ready" (e.g. tests / code quality / variable names)
- Configuration reloadability issue
  - To be honest, I am not sure how we should deal with reloadable configuration in general. For example, something like reloading `vim.paste` override will cause meaninglessly deeply nested function calls.
  - `:filetype off` and `:filetype on` when having strategy/definition overrides in `ftdetect`...
  - In some situations, the same configuration files will be reloaded
    - e.g. `:filetype off` [will remove all filetypedetect autocmds](https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/ftoff.vim#L10-L11)
      - But filetype.lua definitions will not be cleaned up and `:filetype on` will [reload `ftdetect` files](https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/filetype.vim#L2411-L2414)
      - If we really want to keep the current semantics, we should reset the file type detection definitions to the original state
    - question: How much should we care? When doing `:filetype off` can be useful?

## Other considerations (not implemented in this PR)
- Refine APIs
  - Probably we should adopt "shebang" (it is "common enough" and probably timeless concept) as the primary strategy and port [this scripts.vim logic](https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/scripts.vim#L125-L138)
  - Do we want to adopt something like [Atom's language recognition mechanism](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#language-recognition)?
- Namespace based management [proposed by @tjdevries](https://github.com/neovim/neovim/pull/16600#issuecomment-1005889399)
  - I am afraid this could make it unnecessarily complicated though. I guess we should collect real use cases
  - But if we use namespace, configuration reloadability issue will be automatically solved (it works like `:au!`)
- Debuggability
  - It would be nice if we can establish an easy way to know "why / how this specific filetype was chosen"
    - However, I think it's better to focus improving / establishing better ways to debug lua script inside Neovim itself rather than implementing specific debugging way **only for** filetype detection subsystem
    - For now, we can just override every strategy in `vim.filetype.strategy` to log some information
    - If users want to know "who modified the definition table", they can associate metatable to hook into table modification for debugging
- introspection and hackability
  - Are vim.filetype.strategy and vim.filetype.definition enough or too much? Are there better way to structure the whole file detection subsystem in simpler and extensible way?
- Further ecosystem split concern against Vim?
  - e.g. Do we want to have Neovim plugins for new file types to use filetype.lua mechanism?
    - If so, we need to make the API good enough to make it worth the effort

### CODE REVIEW

**Comment by naruaway** [comment]
My main motivation comes originally from [this issue](https://github.com/neovim/neovim/issues/16940)
I think we can use this PR to discuss the whole filetype.lua subsystem (cc @tjdevries and @gpanders)

**Comment by gpanders** [comment]
I appreciate that you've put a lot of thought and effort into this.

We had a long period of open review and discussion among team members around the design of filetype.lua. We will be sticking with the overall design as it exists now, unless and until it is found to be fundamentally incapable of fulfilling the necessary requirements. However, there are still some shortcomings in the implementation as you pointed out in https://github.com/neovim/neovim/issues/16940. Please feel free to create a PR that addresses those things within our existing design.

If you'd rather use the design you've outlined here, then of course you are free to create a plugin and share it with the broader community.

**Comment by clason** [comment]
And allow me to add a general comment, since similar enthusiasm for "let's rewrite <component of the day>, with blackjack, and kittens!" is a regular recurrence:

Despite all changes, the central mission statement of Neovim is still a _refactor_ of Vim, not a clean-slate reboot (unlike, say, Helix). While additions are fair game, changes to core functionality _must_ be incremental until it becomes clear that an agreed-upon goal cannot be achieved that way. For example, this means (in this specific case) that passing the legacy filetype tests is of paramount importance, constraining the design (as opposed to https://github.com/nathom/filetype.nvim, which as a plugin is not restrained in this way).

And on a personal note, I find @gpanders' API admirably extensible while remaining simple. Opening a PR that immediately rips out a well-thought out contribution completely is not the best way of starting to contribute to a long-running and successful project...

**Comment by naruaway** [comment]
Sure, totally understandable and thank you so much for checking this PR!

Do you think some of them could be still considered? For example, do we want to have "buffer-less" file detection function to avoid logic duplication with [Plenary filetypes module](https://github.com/nvim-lua/plenary.nvim/blob/master/data/plenary/filetypes/builtin.lua) in the future? Or is it too early to consider...?

**Pull request closed without merging**
