### PR TITLE
docs: remove trailing spaces

### PR DESCRIPTION
**Pull request by ii14**
Left out pi_msgpack.txt and spaces that are also present in upstream vim

### CODE REVIEW

**Comment by clason** [comment]
We prefer not to make any (including whitespace) changes to upstream docs as that will make the vim-patch script fail more often.

**Comment by ii14** [comment]
I didn't touch those :)

**Comment by ii14** [comment]
this PR:
```
$ grep '\s$' *.txt
change.txt:	    bla bla foobar bla
change.txt:	    bla bla foobar bla
intro.txt:3. ccc ccc ccc	3. ccc ccc ccc	3. ccc ccc c	11. ~
intro.txt:				6. ~
map.txt:	unmap @@
options.txt:		:set list lcs=tab:\ \
options.txt:		:set showbreak=>\
pi_msgpack.txt: [...] a lot of trailing whitespace here
usr_12.txt:	/ 	
usr_41.txt:	:map <F4> o#include
```

vim:
```
$ grep '\s$' *.txt
change.txt:8. The selection and drop registers "*, "+ and "~
change.txt:8. Selection and drop registers "*, "+ and "~
change.txt:	    bla bla foobar bla
change.txt:	    bla bla foobar bla
intro.txt:3. ccc ccc ccc	3. ccc ccc ccc	3. ccc ccc c	11. ~
intro.txt:				6. ~
map.txt:	unmap @@
options.txt:		:set list lcs=tab:\ \
options.txt:		:set showbreak=>\
usr_12.txt:	/ 	
usr_41.txt:	map <F4> o#include
```

I didn't touch change.txt, it was like that before

**Comment by clason** [comment]
(just wanted to make sure; on mobile right now so couldn't check myself)

**Review by justinmk — APPROVED** [review]
Could probably check this in a lint task. Maybe in `gen_help_html.lua`

**Comment by zeertzjq** [comment]
Vim has a test case for this

**Pull request merged**
