### PR TITLE
Revert "Downgrade to clang-4.0 to avoid false-positive warnings from clang"  [skip appveyor]

### PR DESCRIPTION
**Pull request by blueyed**
This reverts commit 2cbac719c3eba8ea5826e16912126d70222911ed.

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM. We already work around the `__fpclassify` problem. We can work around the tautalogical compare if needed.

**Comment by blueyed** [comment]
The `-Wtautological-compare` mentioned in https://github.com/neovim/neovim/commit/2cbac719c3eba8ea5826e16912126d70222911ed is apparently what I am seeing with #10480.

**Comment by blueyed** [comment]
```
AILED: /usr/lib/ccache/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Iconfig -I../src -Isrc/nvim/auto -Iinclude -isystem /home/travis/nvim-deps/usr/include -g   -DEXITFREE -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -fsanitize=undefined -fsanitize-blacklist=/home/travis/build/neovim/neovim/src/.asan-blacklist -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -Werror  -Wno-conversion -MD -MT src/nvim/CMakeFiles/nvim.dir/diff.c.o -MF src/nvim/CMakeFiles/nvim.dir/diff.c.o.d -o src/nvim/CMakeFiles/nvim.dir/diff.c.o   -c ../src/nvim/diff.c
../src/nvim/diff.c:124:32: error: self-comparison always evaluates to true [-Werror,-Wtautological-compare]
    for (win_T *wp = ((curtab) == curtab) ? firstwin : (curtab)->tp_firstwin; wp != ((void*)0); wp = wp->w_next) {
                               ^
../src/nvim/diff.c:638:30: error: self-comparison always evaluates to true [-Werror,-Wtautological-compare]
  for (win_T *wp = ((curtab) == curtab) ? firstwin : (curtab)->tp_firstwin; wp != ((void*)0); wp = wp->w_next) {
                             ^
../src/nvim/diff.c:1418:30: error: self-comparison always evaluates to true [-Werror,-Wtautological-compare]
  for (win_T *wp = ((curtab) == curtab) ? firstwin : (curtab)->tp_firstwin; wp != ((void*)0); wp = wp->w_next) {
                             ^
../src/nvim/diff.c:2769:30: error: self-comparison always evaluates to true [-Werror,-Wtautological-compare]
  for (win_T *wp = ((curtab) == curtab) ? firstwin : (curtab)->tp_firstwin; wp != ((void*)0); wp = wp->w_next) {
                             ^
4 errors generated.
[143/262] Building C object src/nvim/CMakeFiles/nvim.dir/cursor_shape.c.o
ninja: build stopped: subcommand failed.
+exit 1
```

Similar to #10480 I cannot reproduce this locally (clang version 8.0.0 (tags/RELEASE_800/final)).

In both cases it seems like locally this is ignored with macros.

**Comment by blueyed** [comment]
Should be good/better after https://github.com/neovim/neovim/pull/10533.

**Comment by blueyed** [comment]
Ok, `-Wtautological-compare` errors here are not due to cclang, but rather the clang version used then.

Not sure if we should work around that given that it appears to be handled correctly (with more recent clang).

**Comment by blueyed** [comment]
Should be fixed now with the (fixed) ccache workaround in master.

**Review by justinmk — APPROVED** [review]

**Pull request merged**
