### PR TITLE
ui: Fix click on foldcolumn when ext_multigrid is enabled

### PR DESCRIPTION
**Pull request by tksrsk**
If ext_multigrid feature was enabled, couldn't close or open fold when click charactor of foldopen or foldclose on foldcolumn.

Because foldcolumn asumed rendered by default grid, but it rendering on each grids if multigrid enabled.
So changed from default to judged by each grids.

### CODE REVIEW

**Comment by bfredl** [comment]
@tk-shirasaka whe close? was this a non-issue or was the solution wrong?

**Comment by tk-shirasaka** [comment]
@bfredl
Thank you for your concern.
This PR did not pass the test, so I closed it once.
After modifying it to pass the test, reopen this PR

**Comment by tk-shirasaka** [comment]
Fix code and passed test for test /functional/ui/fold_spec.lua, so reopen PR

**Comment by bfredl** [comment]
@tk-shirasaka very nice, do you think you could write a test for you fix (which fails on master but passes with this PR)?

**Comment by tk-shirasaka** [comment]
@bfredl 
Added a multigrid folding test case.

I've added multigrid cases to all fold_spec tests, but if it's better to limit it to this fix, why not remove the irrelevant test cases?

**Comment by teto** [comment]
very nice. You can run `make clint` locally to address the linting issues.

**Comment by tk-shirasaka** [comment]
@teto 
Thank you for advice!
Fixed issue.

**Pull request merged**
