### PR TITLE
let remote hosts update their specs

### PR DESCRIPTION
**Pull request by bfredl**
Currently works only in the following scenario: when the user starts the host by calling some already registered plugin, or starts a not started plugin in a running host, the host is allowed to send back updated specs, for all or some subset of already registered plugins, which updates the registration file and takes effect in _real_ time.

goals, not necessarily in this PR, but should be made possible to implement in a _forward_ compatible fashion with out breaking compatibility either way:

- [ ] nvim at startup detecting specs are out of date and start the host and asks for updated specs
- [ ] even if the host is already running, if a new plugin is installed, ask the host to load it and return specs for the new plugin
- [ ] the host can take initiative to reload an already running plugin, and update its specs
- [ ] use timestamps in the registration file so old specs don't overwrite new (reuse shada logic?)
- [ ] Figure out the right time points load errors should be shown to the user.
- [ ] nvim should do what the user asks it, never reply with confusing error messages like "host x is already running", "plugin x is already registered"

There is probably some relevant discussion from 2015 to reread...

[python-client branch](https://github.com/neovim/python-client/compare/master...bfredl:specs?expand=1)

### CODE REVIEW

**Comment by bfredl** [comment]
I wonder if there should be some versioning of the nvim `<->` host interface. Or perhaps nvim can ask the host for a list of capabilities (same as request names in most cases) `rpcrequest(host, "capabilities") -> ["plugin_change_notify", "add_plugin", "try_reload_plugin", ...]`

**Comment by bfredl** [comment]
refs #5532 #4439 #4438

**Comment by justinmk** [comment]
> Or perhaps nvim can ask the host for a list of capabilities (same as request names in most cases) 

More generally, some convention which identifies each channel (host, UI, or any other client) with at least a client name (like a user agent string) would be valuable. At least for error reporting, maybe also for UI configuration.

**Comment by bfredl** [comment]
Yes, something like nvim_get_api_info, but in reverse.

**Comment by justinmk** [comment]
The simplest thing might be to add a voluntary API function, e.g. `nvim_set_channel_info`. Then, even clients that aren't prepared to receive requests can still provide info.

We could also have a field in the `nvim_ui_attach` options that invites this info for UI clients.

**Comment by bfredl** [comment]
That could work to implement this and be compatible with existing hosts. To still be able to get rid off "poll" #5856 and do it all async, we would need some kind of callback or autocommand, i e replace the poll command with

`exe "autocmd OnChannelInfo "..host.channel.." call RegisterHost("..host.name..")"`

**Comment by Shougo** [comment]
The feature also works for delayed loading plugins?

**Comment by bfredl** [comment]
You mean not load all plugins in the host at once? The PR doesn't do it, but it is _forward_ compatible with either nvim or the host doing it later.

**Comment by Shougo** [comment]
> You mean not load all plugins in the host at once?

Yes.

**Comment by bfredl** [comment]
updated on top of #6743

**Comment by justinmk** [comment]
> Yes, something like nvim_get_api_info, but in reverse.

We can avoid that by simply requiring remote plugins to ship a `lua/foo.lua` file which defines commands/functions that call to the plugin's remote plugins. If that's too cumbersome, let's make it _not cumbersome_. By doing so, we avoid tons of redundant code in _every_ "remote plugin host". Then API clients can be much, much simpler. 

- https://github.com/neovim/neovim/issues/27949

**Pull request closed without merging**
