### PR TITLE
[WIP]vim-patch: 8.2.{0869,0933,0959}

### PR DESCRIPTION
**Pull request by kevinhwang91**
Xexpr can't throw an error before patch 8.1.0877 in some test cases, so I use Xexpr without `assert_fails`.

### CODE REVIEW

**Comment by janlazo** [comment]
These patches should be ported using https://github.com/neovim/neovim/blob/master/scripts/vim-patch.sh. The PR title is ok for convenience but not the commit message. Each vim-patch should be in a separate commit and any diverges from Vim should be noted in that commit.

**Comment by kevinhwang91** [comment]
I have force-pushed the patch v8.2.0869, please review. If everything is ok, I will go-ahead with patching v8.2.0933 and v8.2.0959.

**Comment by janlazo** [comment]
Merge commits shouldn't have code changes if there are no conflicts. I do not see a separate commit just for 1 vim patch.

If you followed the instructions in https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#quickstart and created the commit message via `vim-patch.sh`, then there should be a separate commit.

**Comment by kevinhwang91** [comment]
So sorry for my rebase mistake, I have force-pushed again. There're many conflicts in quickfix.c.

**Comment by kevinhwang91** [comment]
Could I make a new PR for 8.2.0869?  I want to patch 0869, 0933, and 0959 one by one.

**Comment by janlazo** [comment]
Yes.

**Pull request closed without merging**
