### PR TITLE
Fix expression highlighting

### PR DESCRIPTION
**Pull request by ZyX-I**
Some errors found by KLEE plus #7889. It also appears that unit tests now may ignore crashes.

### CODE REVIEW

**Comment by ZyX-I** [comment]
KLEE has actually found error which triggered the same assert, but has a fix elsewhere (`*]08`).

**Comment by ZyX-I** [comment]
It appears that only reliable way to get crash for out-of-bounds access is allocating continuous region of memory via `mmap(…, MAP_ANONYMOUS…)`, two or more pages, and then protecting last page via `mprotect(…PROT_NONE)`. Or using ASAN, but setting it up for unit tests would be increadibly tricky.

**Comment by justinmk** [comment]
@ZyX-I somewhat unrelated, what are you thoughts are using something like [sds](https://github.com/neovim/neovim/issues/859) instead of doing these `*_len` variants of string-related functions?

**Comment by ZyX-I** [comment]
Something like sds does not allow operating on string slices or if the input does not have NUL, and I did see at least slices in the codebase (a bunch of places which have a code to save character at position, set it to NUL, do something, restore character). Specifically sds is always a pointer, so no fixed-sized strings embedded into a structure like we have in a number of places (e.g. in Error). And no creating it from a C string without allocations. And it is supposed to be dynamically populated (or `alloc` field would not be needed) while in Neovim strings rarely stretch (though in some cases they actually better stretch, but in reality are cut into a static buffer).

**Comment by ZyX-I** [comment]
If CI succeeds then PR is ready, I have fixed all errors KLEE has found in the last run.

**Comment by ZyX-I** [comment]
Full run results, if anybody is interested: [klee.tar.xz.not.zip](https://github.com/neovim/neovim/files/2043060/klee.tar.xz.not.zip).

**Comment by justinmk** [comment]
In other PRs this failure randomly happens:

```
  [  ERROR   ] test\unit\viml\expressions\parser_tests.lua @ 6329: api nvim_parse_expression works with &opt
  C:/projects/neovim/test/functional\api\vim_spec.lua:1186: Error while processing test ('(1+&)', E):
CUSTOMBUILD : table error :  [C:\projects\neovim\build\functionaltest.vcxproj]
  C:/projects/neovim/test/functional\api\vim_spec.lua:1170: Expected objects to be the same.
  Passed in:
  (table) {
    [1] = 'NvimNestingParenthesis:0:0:('
    [2] = 'NvimNumber:0:1:1'
    [3] = 'NvimBinaryPlus:0:2:+'
    [4] = 'NvimInvalidOptionSigil:0:3:&'
   *[5] = 'NvimInvalidOptionScope:0:4:)'
    [6] = 'NvimInvalidOptionScopeDelimiter:0:5:'
    [7] = 'NvimInvalidOptionName:0:6:'
    [8] = 'NvimNestingParenthesis:0:4:)' }
  Expected:
  (table) {
    [1] = 'NvimNestingParenthesis:0:0:('
    [2] = 'NvimNumber:0:1:1'
    [3] = 'NvimBinaryPlus:0:2:+'
    [4] = 'NvimInvalidOptionSigil:0:3:&'
   *[5] = 'NvimNestingParenthesis:0:4:)' }
  
  ({message = 'C:/projects/neovim/test/functional\\api\\vim_spec.lua:1170: Expected objects to be the same.\nPassed in:\n(table) {\n  [1] = \'NvimNestingParenthesis:0:0:(\'\n  [2] = \'NvimNumber:0:1:1\'\n  [3] = \'NvimBinaryPlus:0:2:+\'\n  [4] = \'NvimInvalidOptionSigil:0:3:&\'\n *[5] = \'NvimInvalidOptionScope:0:4:)\'\n  [6] = \'NvimInvalidOptionScopeDelimiter:0:5:\'\n  [7] = \'NvimInvalidOptionName:0:6:\'\n  [8] = \'NvimNestingParenthesis:0:4:)\' }\nExpected:\n(table) {\n  [1] = \'NvimNestingParenthesis:0:0:(\'\n  [2] = \'NvimNumber:0:1:1\'\n  [3] = \'NvimBinaryPlus:0:2:+\'\n  [4] = \'NvimInvalidOptionSigil:0:3:&\'\n *[5] = \'NvimNestingParenthesis:0:4:)\' }'})
  
  stack traceback:
  	C:/projects/neovim/test/functional\api\vim_spec.lua:1186: in function 'check_parsing'
  	test\unit\viml\expressions\parser_tests.lua:6475: in function <test\unit\viml\expressions\parser_tests.lua:6329>
```

@ZyX-I any idea why that test would be non-deterministic? Does this PR help with that?

**Comment by ZyX-I** [comment]
In my opinion as long as msgpack stream is transferred fully and correctly it can’t be non-determenistic. PR should not help with that. But what actually happens looks more like some kind of array overrun then RPC/stream related, but not like any one I fixed here (though changing that test to use `check_pagealloc_parsing` did not show any problems) and I have no idea why this could be non-determenistic (especially given that API Strings are NUL-terminated despite being binary AFAIR). Can you point to travis page with error so that exact results (including possible non-printable symbols) could be seen?

**Comment by justinmk** [comment]
> Can you point to travis page with error so that exact results (including possible non-printable symbols) could be seen?

In this case it was appveyor: https://ci.appveyor.com/project/neovim/neovim/build/20669/job/5ikciapmdoctumws

When it happened in another (@bfredl) PR it may have been on travis (can't remember).

**Comment by justinmk** [comment]
travis and quickbuild failures:

```
19:14:01,577 INFO  - not ok 267 - mbyte utf_char2bytes
19:14:01,578 INFO  - # ./test/unit/helpers.lua @ 780
19:14:01,578 INFO  - # Failure message: ./test/unit/helpers.lua:748: (string) '
19:14:01,578 INFO  - # Test crashed without proper end marker.
19:14:01,578 INFO  - # 
19:14:01,578 INFO  - # Test crashed, trace:
19:14:01,578 INFO  - # Trace: either in the format described below or custom debug output starting
19:14:01,578 INFO  - # with `>`. Latter lines still have the same width in bytes.
19:14:01,578 INFO  - # 
19:14:01,578 INFO  - # ┌ Trace type: _r_eturn from function , function _c_all, _l_ine executed,
19:14:01,578 INFO  - # │             _t_ail return, _C_ount (should not actually appear),
19:14:01,578 INFO  - # │             _s_aved from previous run for reference, _>_ for custom debug
19:14:01,578 INFO  - # │             output.
19:14:01,578 INFO  - # │┏ Function type: _L_ua function, _C_ function, _m_ain part of chunk,
19:14:01,578 INFO  - # │┃                function that did _t_ail call.
19:14:01,578 INFO  - # │┃┌ Function name type: _g_lobal, _l_ocal, _m_ethod, _f_ield, _u_pvalue,
19:14:01,578 INFO  - # │┃│                     space for unknown.
19:14:01,578 INFO  - # │┃│ ┏ Source file name             ┌ Function name                ┏ Line
19:14:01,578 INFO  - # │┃│ ┃ (trunc to 30 bytes, no .lua) │ (truncated to last 30 bytes) ┃ number
19:14:01,578 INFO  - # CWN SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:LLLLL\n
19:14:01,578 INFO  - # cCl =[C]                          :(for generator)               :nknwn
19:14:01,578 INFO  - # cCf =[C]                          :insert                        :nknwn
19:14:01,578 INFO  - # cCl =[C]                          :(for generator)               :nknwn
19:14:01,578 INFO  - # cCm =[C]                          :lower                         :nknwn
19:14:01,578 INFO  - # cCm =[C]                          :gmatch                        :nknwn
19:14:01,578 INFO  - # cCl =[C]                          :(for generator)               :nknwn
19:14:01,578 INFO  - # cCf =[C]                          :insert                        :nknwn
19:14:01,578 INFO  - # cCl =[C]                          :(for generator)               :nknwn
19:14:01,578 INFO  - # cCg =[C]                          :require                       :nknwn
19:14:01,578 INFO  - # cCf =[C]                          :insert                        :nknwn
19:14:01,578 INFO  - # cCf =[C]                          :insert                        :nknwn
```

**Comment by justinmk** [comment]
@ZyX-I Anything we can do to help with this?

**Comment by jamessan** [comment]
> travis and quickbuild failures:

That looks like what's getting logged in https://github.com/neovim/neovim/issues/9212 too.

**Comment by bfredl** [comment]
@jamessan what compiler do you use? I can't reproduce with gcc 8.2, with any of the standard build types.

**Comment by jamessan** [comment]
> what compiler do you use?

```
% gcc --version; clang --version
gcc (Debian 8.2.0-13) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

clang version 7.0.1-3 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Both failed with the same problem.  I've pushed my rebased branch to my own repo and Travis is [currently running](https://travis-ci.org/jamessan/neovim/builds/473574817).

**Comment by jamessan** [comment]
> I've pushed my rebased branch to my own repo and Travis is [currently running](https://travis-ci.org/jamessan/neovim/builds/473574817).

Which ran into some of the same failures @justinmk hit last time he tried.

**Comment by justinmk** [comment]
Expression highlighting will be driven by treesitter.

**Pull request closed without merging**
