### PR TITLE
feat(highlight): add strikethrough, nocombine to `nvim_set_hl`

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Comment by bfredl** [comment]
And to answer your other question, I think "nocombine" should be added here as well :]

**Review by lewis6991 — APPROVED** [review]

**Comment by clason** [comment]
> And to answer your other question, I think "nocombine" should be added here as well :]

Done (but not tested). What about `inverse`? That seems to break the generator script...

**Comment by lewis6991** [comment]
We already have `reverse` so not essential.

**Comment by clason** [comment]
My thought as well, but I'd still like to understand why it's not working ;)

**Comment by bfredl** [comment]
yes, hash collisions are not implemented as those have not happened yet (until now, that is). But I don't think we should include the "inverse" alias here anyway.

**Comment by clason** [comment]
Makes sense. I'll wait for CI to finish (FreeBSD failure seems unrelated), then squash.

**Comment by bfredl** [comment]
looks alright:)

**Pull request merged**
