### PR TITLE
lsp: fix highlighting for lsp markdown code blocks

### PR DESCRIPTION
**Pull request by mjlbach**
Closes #14098

@tjdevries Maybe we do this for now? should fix the codeblock highlighting issue

### CODE REVIEW

**Comment by mjlbach** [comment]
@bluz71 Do you want to sanity check me that this fixes your issue and I'll merge? You'll need to `make clean && make distclean` and probably remove the lua/nvim files from /usr/local/whatev for a proper test.

**Comment by bluz71** [comment]
@mjlbach,

I built your branch and tested with JavaScript and Dart.

JavaScript hover docs generally are sent with filetype hints, not as Mardown, and your branch restores syntax highlighting. Excellent. JavaScript is back and working for me.

Dart always send Markdown format and there is a difference between between old Neovim and your latest branch as seen in these screenshots:

Old commit d49177af, Dart Flutter hovering:

flutter_good

And your new branch:

Dart_New

The old one likely was highlighted by Tim Pope's Markdown highlighter (my preferred Markdown highlighter). The `fix_highlighting` branch appears to be something different? Lots of missing color.

To be honest, more color is needed, or maybe I need to update my own moonfly and nightfly color schemes?

**Comment by mjlbach** [comment]
If you look at what I'm doing in the original PR: https://github.com/neovim/neovim/pull/14073/files

You'll see I'm sourcing tpope's markdown branch, and then extending it with some rules to ignore special characters. Non of the syntax highlighting should have changed (what broke it was setting the filetype to lsp_markdown, which is what this PR reverts). I can try reproducing your example, one of the advantages of this PR is that you should be able to drop an lsp_markdown.vim in your ftplugin folder and override these custom rules.

**Comment by mjlbach** [comment]
Oh wait, this old commit is from after my PR? Yes, that's because it *was* using the markdown highlighting, but unfortunately that breaks the little code block highlighting at the top.

**Comment by bluz71** [comment]
Sorry, I am confused. Is there still work happening with the new `lsp_markdown` filetype to bring up to the same point as the old `markdown` filetype style? So I wait?

My sample is Flutter + Dart code if you are interested. The docs are huge and very Markdown heavy. Being colorful helps readability. Currently, the missing color is a slight regression.

Let me know what you want me to do, I am always willing to test and help.

Cheers.

**Comment by mjlbach** [comment]
The new markdown and old markdown are the same :) 

I think the issue is the filetype, if you call `:set filetype=lsp_markdown` on that floating window (ctrl-w into it, then try the cmd), do you see the color change?

The issue is, if I enable the filetype for the file, the custom syntax highlighting we do on the code block at the top of the window gets overwritten.

**Comment by bluz71** [comment]
> I think the issue is the filetype, if you call :set filetype=lsp_markdown on that floating window (ctrl-w into it, then try the cmd), do you see the color change?

All color gets stripped away if I do that.

If I do `:set filetype=markdown` I get see this:

Dart2

Notice the `Icon` section is not highlighted like it was before:

flutter_good

I think that may be fenced `dart` code with the fence markers stripped out by the fancy hover window code. But don't quote me.

**Comment by mjlbach** [comment]
@bluz71 I think I'm going to merge this because it's not a regression relative to what it was before my original floating win syntax PR (right?), and then someone can go about making highlights prettier after 0.5.

**Pull request merged**
