### PR TITLE
[RFC] Remove :open command

### PR DESCRIPTION
**Pull request by ghost**
From the documentation itself:

```
  :[range]o[pen]                 Works like |:visual|: end Ex mode.
                                 {Vi: start editing in open mode}
  ...

  Vim does not support open mode, since it's not really useful.  For
  those situations where ":open" would start open mode Vim will leave Ex
  mode, which allows executing the same commands, but updates the whole
  screen instead of only one line.
```

This is being done to fulfill #2548 (I think at least the `limits` section of `vi_diff.txt` could be kept, not sure where it could be moved though), as well as because `:open` isn't too useful in itself. If wanted, I could avoid removing the command and just move the documentation to somewhere else, but, again, it seems unlikely this is used much at all.

### CODE REVIEW

**Comment by justinmk** [comment]
:+1:

**Comment by dsummersl** [comment]
I'll take a look at this, or does that :thumbsup: mean you got it @justonmk?

**Comment by dsummersl** [comment]
The CI tests are failing, I downloaded and reran `make test` manually. I see the following failure:

```
Failure → ...rs/Downloads/neovim/test/functional/shada/marks_spec.lua @ 103
ShaDa support code is able to populate v:oldfiles
...rs/Downloads/neovim/test/functional/shada/marks_spec.lua:112: Expected objects to be the same.
Passed in:
(string) 'estfile-functional-shada-marks-2'
Expected:
(string) 'Xtestfile-functional-shada-marks'

stack traceback:
        ...rs/Downloads/neovim/test/functional/shada/marks_spec.lua:112: in function <...rs/Downloads/neovim/test/functional/shada/marks_spec.lua:103>

-- Output to stderr:

CMake Error at /Users/danesummers/Downloads/neovim/cmake/RunTests.cmake:39 (message):
  Running functional tests failed with error: 1.
```

On the plus side `make unittest` passes!

**Comment by mhinz** [comment]
@dsummersl That's probably related to an issue that was fixed today: https://github.com/neovim/neovim/commit/a6c45d15fd34892ad93a7cfcf678f05b8ed56ed3

So, update master. :)

**Comment by dsummersl** [comment]
Nice rebasing this branch does indeed fix `make test` - does the original author make that change or should/can I? (and if so...do I rebase and push -f, or merge from master to this PR or...)

**Comment by mhinz** [comment]
What change do you mean?

In general it works like this:

```
git checkout -b my-fix
<make changes>
git add -u
git push (to _your_ repo, so probably `dsummersl/neovim)
```

If you then visit Github online interface, it will show that your branch is ahead of `neovim/neovim`, then you can easily create a pull request for it.

And.. well, always `git rebase master` before pushing. And you can update pull requests by `git push -f`.

**Comment by dsummersl** [comment]
oh I'm sorry I just mean this PR isn't mine - I'm doing CR...master worked, rebasing this PR worked...

**Comment by mhinz** [comment]
@dsummersl Oh, sorry, I totally missed the this is a PR not an issue. Well, in that case @Pyrohh will care about it sooner or later.

You can have a look at his patch (online or check it out locally: https://gist.github.com/piscisaureus/3342247).

If you found issues in the patch, click the line numbers in https://github.com/Pyrohh/neovim/commit/1f0385519d250a7a189b8d78bd3a433629102630 and leave a comment.

Otherwise just say LGTM ("looks good to me") here.

**Comment by Pyrohh** [comment]
@dsummersl @mhinz thanks for the reminder, I just rebased.

> You can have a look at his patch (online or check it out locally: https://gist.github.com/piscisaureus/3342247).

I've been using [`hub`](https://hub.github.com/) for a while, which offers similar functionality.

**Comment by Pyrohh** [comment]
Hmm, I don't think I've ever encountered a test failure like this:

```
[----------] Global test environment teardown.
[==========] 869 tests from 139 test files ran. (84790.46 ms total)
[  PASSED  ] 864 tests.
[ SKIPPED  ] 4 tests, listed below:
[ SKIPPED  ] ...vis/build/neovim/neovim/test/functional/job/job_spec.lua @ 362: jobs will only emit the "exit" event after "stdout" and "stderr"
[ SKIPPED  ] ...neovim/neovim/test/functional/shell/viml_system_spec.lua @ 189: system() with a program that doesn't close stdout skipped (missing xclip)
[ SKIPPED  ] ...neovim/neovim/test/functional/shell/viml_system_spec.lua @ 368: systemlist() with a program that doesn't close stdout skipped (missing xclip)
[ SKIPPED  ] ...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua @ 555: Screen resize has minimum width/height values
[  ERROR   ] 11 errors, listed below:
[  ERROR   ] ...uild/neovim/neovim/test/functional/terminal/tui_spec.lua @ 160: tui with non-tty file descriptors can handle pipes as stdout and stderr
[  ERROR   ] ...d/neovim/neovim/test/functional/terminal/window_spec.lua @ 10: terminal window before_each
[  ERROR   ] ...d/neovim/neovim/test/functional/terminal/window_spec.lua @ 10: terminal window before_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 10: terminal before_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 21: terminal after_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 10: terminal before_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 21: terminal after_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 10: terminal before_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 21: terminal after_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 10: terminal before_each
[  ERROR   ] ...eovim/test/functional/terminal/window_split_tab_spec.lua @ 21: terminal after_each
 4 SKIPPED TESTS
 11 ERRORS
-- Output to stderr:
```

**Comment by mhinz** [comment]
No idea about the test output, but the removal of a command should be noted in `vim_diff.txt`. :)

**Comment by dsummersl** [comment]
huh, tests all worked for me.

Tested with ```VIMRUNTIME=`pwd` build/bin/nvim``` and `:o` does indeed now complete to `:oldfiles` so @mhinz suggetion makes sense. Otherwise LGTM; didn't see anything else git grepping for 'open' :)

**Comment by justinmk** [comment]
@Pyrohh  can you test `:o` and update oldfiles doc if needed? Then please merge.

**Comment by Pyrohh** [comment]
> @Pyrohh can you test :o and update oldfiles doc if needed?

Sure, I'm merging after tests. Thanks everyone.

**Pull request merged**
