### PR TITLE
doc: add description for cancelreturn option in input()

### LINKED ISSUE #13683: cancelreturn option in input() lacking documentation
In `NVIM v0.5.0-dev+1005-ga1ed941a7`, the documentation for `:h input()` provides a second form which accepts a parameter `cancelreturn`

```
		Key           Default  Description ~
		prompt        ""       Same as {prompt} in the first form.
		default       ""       Same as {text} in the first form.
		completion    nothing  Same as {completion} in the first form.
		cancelreturn  ""       Same as {cancelreturn} from
		                       |inputdialog()|. Also works with
		                       input().
		highlight     nothing  Highlight handler: |Funcref|.
```

The documentation for `inputdialog()` however redirects us back to `input()` and does not offer any description for the cancelreturn parameter. On investigation this documentation was removed in 30940f809b1e6dbd4de4f3e76fdb5336d06cd20a. Ideally I think the documentation for `cancelreturn` that was in `inputdialog` should be transferred over

### PR DESCRIPTION
**Pull request by pohzipohzi**
fixes https://github.com/neovim/neovim/issues/13683

### CODE REVIEW

**Review by vigoux — APPROVED** [review]

**Comment by pohzipohzi** [comment]
bump

**Comment by pohzipohzi** [comment]
@vigoux thank you for the approval. This PR has been open for some time and I'll like to merge it. Are you able to help facilitate this?

**Comment by bfredl** [comment]
sorry for the wait :)

**Comment by pohzipohzi** [comment]
thank you @bfredl !

**Pull request merged**
