### PR TITLE
[RFC] Testlinting.

### PR DESCRIPTION
**Pull request by KillTheMule**
Missed in https://github.com/neovim/neovim/pull/4644/commits/fd3088b425b8c1f4f41eb715201e429ddd37af32

### CODE REVIEW

**Comment by bfredl** [comment]
which reminds me we should add it to travis. I suppose we could change `.ci/script.sh` to run `make lint testlint` when `CI_TARGET=lint`

**Comment by jamessan** [comment]
`testlint` would need to be clean first, wouldn't it.  Last I looked, it was far from that.

**Comment by KillTheMule** [comment]
I fixed it in https://github.com/neovim/neovim/commit/360d0513d1ba2d6e2b8948daad5bb56f11db7070, broke it in https://github.com/neovim/neovim/pull/4644/commits/fd3088b425b8c1f4f41eb715201e429ddd37af32 and refixed in this PR :)

**Comment by bfredl** [comment]
it seems that `make testlint` compiles the c code which is pretty unneccesary. I suppose we could change `testlint` to depend on `deps` only and not `nvim`.

**Comment by KillTheMule** [comment]
Quickbuild keeps on timing out on the same tests, I'll use this PR to try to figure out what's going on.

**Comment by KillTheMule** [comment]
QB failures should be fixed by https://github.com/neovim/neovim/pull/4718.

**Comment by KillTheMule** [comment]
Ok, done. The QB failure is the good ol' "Fixed by jszagmeister".

**Comment by KillTheMule** [comment]
There seems to be a problem with 

> input_spec.lua @ 61: feeding large chunks of input with <Paste> ok

on osx for travis, this time it's the clang build.

**Pull request merged**
