### PR TITLE
[RFC] option: Do not expand options, obtained from XDG vars

### LINKED ISSUE #4961: No syntax highlighting if XDG_DATA_DIRS is too long
- `nvim --version`:
NVIM 0.1.4
Build type: Release
Compilation: /nix/store/6rfvkcxwglqxq08kh7w8a08p533m39gj-gcc-wrapper-5.3.0/bin/gcc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/build/config -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/src -I/nix/store/g45z22w8gy423l28a16qqbpyjc6h8mc1-libuv-1.9.1/include -I/nix/store/r9f075g92jf3i69z7zngk4fn6kxsmdyc-libmsgpack-1.1.0/include -I/nix/store/wq0pql3gpiqj5y6j7gdigbsmkajp8gra-luajit-2.1.0-beta1/include -I/nix/store/qbhlz2b5m9z6xv2nmqz903qxiw82srcb-unibilium-1.2.0/include -I/nix/store/v6wlaxwik8j64xsx8pqw5c259kzk1g6l-libtermkey-0.18/include -I/nix/store/qibb1yiwqydp7w04mwgzb6w7qm1zadvj-neovim-libvterm-2015-11-06/include -I/nix/store/m9hvah4ccnih51ikgy9chprnq3ljsvna-jemalloc-4.1.1/include -I/nix/store/zj5k6nandjij75093g2q3f2191hvf1xi-glibc-2.23-dev/include -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/build/src/nvim/auto -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/build/include
Compiled by nixbld

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/b8sqcgs4im2ya3hkmjd1vbyg01chivbh-neovim-0.1.4/share/nvim"

- Vim (version: ) behaves differently?
Yes

- Operating system/version:
NixOS 16.03

- Terminal name/version:
konsole

- `$TERM`:
xterm

### Actual behaviour
No syntax highlighting if the XDG_DATA_DIRS env variable is too long (on my system it seems to be 2955).

Using `:syntax on` triggers an error:

Error detected while processing /nix/store/b8sqcgs4im2ya3hkmjd1vbyg01chivbh-neovim-0.1.4/share/nvim/runtime/syntax/syntax.vim:
line   42:
E216: No such group or event: filetypedetect BufRead

This was reported as a NixOS bug: https://github.com/NixOS/nixpkgs/issues/15805

### Expected behaviour

Syntax highlighting

### Steps to reproduce using `nvim -u NORC`

```
export XDG_DATA_DIRS=<VERY LONG STRING>
nvim -u NORC
:syntax on
```

### PR DESCRIPTION
**Pull request by ZyX-I**
It is a wrong thing to do, this makes valid variable values be treated 
incorrectly: in

```
XDG_DATA_HOME='/home/$foo/.local/share'
```

`$foo` should be treated literally and not expanded to `foo` environment 
variable value.

Also makes option_expand not try to expand too long strings even if these too 
long strings are default values. Previously it thought that default values 
should always be expanded. Also does not try to expand NULL should it be the 
default value just in case.

Fixes #4961

### CODE REVIEW

**Comment by ZyX-I** [comment]
There is a question now: I want to test my changes (this is the only reason I used `WIP` tag), but lua (5.1 at least) has `os.getenv` and no `os.setenv`. Using `--cmd` to set environment is too late. Can I use `env` command or it should be banned because of Windows? Or we have a lua package in dependencies that provides `setenv` (e.g. `luv` probably has bindings for `uv_spawn` which may be configured via [handle->env](http://docs.libuv.org/en/v1.x/process.html?highlight=environment#c.uv_process_options_t.env))?

**Comment by ZyX-I** [comment]
`luv` indeed provide such bindings, including `env` support. I will check whether used neovim client provides any interface to alter environment.

**Comment by ZyX-I** [comment]
No, it does not provide such interface. Though this will be rather easy to fix, this still needs changes to lua client or duplicating its code here.

**Comment by ZyX-I** [comment]
While writing tests found few other bugs. https://github.com/neovim/neovim/pull/4964/commits/74d7854b49adc0231f877b59a0619754ad118e14 is there because I had a wrong idea about how to not expand defaults with `:set&` (though I will need a new flag).

**Comment by ZyX-I** [comment]
One of the build hangs (#5002). The other fails like if I did not drop caches (i.e. did not get an update to lua client). Any ideas regarding the second problem?

**Comment by justinmk** [comment]
Perhaps @fwalch can comment

**Comment by fwalch** [comment]
Last time I worked on this, caches were not supported on Travis OSX at all. Looking at the build log, this seems to have changed (although https://docs.travis-ci.com/user/ci-environment/ still says that caches are only available for private builds). I opened #5007, although I'm not certain how that will help -- if I remember this setup correctly, OSX should have just had empty caches until now.

**Comment by justinmk** [comment]
Looks like the first macOS build is failing actual tests (unlike the other, which is a timeout unrelated to this PR): https://s3.amazonaws.com/archive.travis-ci.org/jobs/143627144/log.txt

**Comment by justinmk** [comment]
Cleared the travis cache for this PR and restarted the non-timeout macOS build.

**Comment by justinmk** [comment]
@ZyX-I Is this ready for merge? The build issues here seem to be solved after merge/rebase to master (https://github.com/neovim/neovim/pull/5157).

**Comment by ZyX-I** [comment]
It was ready, except for the problems you refered to.

**Pull request merged**
