### PR TITLE
[RDY] Clean up dependency patches

### PR DESCRIPTION
**Pull request by b-r-o-c-k**

### CODE REVIEW

**Comment by justinmk** [comment]
Great, thanks!

Some unit test failures on quickbuild I haven't seen before:

```
23:30:20,118 INFO  - not ok 254 - garray ga_append can append integers
23:30:20,118 INFO  - # ./test/unit/helpers.lua @ 764
23:30:20,118 INFO  - # Failure message: ./test/unit/helpers.lua:463: write() error: 32: Broken pipe
23:30:20,118 INFO  - # stack traceback:
23:30:20,118 INFO  - # 	./test/unit/helpers.lua:463: in function 'write'
23:30:20,118 INFO  - # 	./test/unit/helpers.lua:669: in function 'itp_child'
23:30:20,118 INFO  - # 	./test/unit/helpers.lua:769: in function <./test/unit/helpers.lua:764>
23:30:20,118 INFO  - # 
...
23:30:22,082 INFO  - # ./test/unit/helpers.lua @ 764: mbyte utfc_ptr2char_len 2-byte sequences
23:30:22,119 INFO  - not ok 268 - mbyte utfc_ptr2char_len 2-byte sequences
23:30:22,119 INFO  - # ./test/unit/helpers.lua @ 764
23:30:22,119 INFO  - # Failure message: ./test/unit/helpers.lua:463: write() error: 32: Broken pipe
23:30:22,119 INFO  - # stack traceback:
23:30:22,119 INFO  - # 	./test/unit/helpers.lua:463: in function 'write'
23:30:22,119 INFO  - # 	./test/unit/helpers.lua:669: in function 'itp_child'
23:30:22,119 INFO  - # 	./test/unit/helpers.lua:769: in function <./test/unit/helpers.lua:764>
23:30:22,119 INFO  - # 

```

**Comment by b-r-o-c-k** [comment]
QuickBuild succeed after re-running it.

**Comment by justinmk** [comment]
Ah, quickbuild vps had a hardware issue, maybe this was related.

**Comment by justinmk** [comment]
@leonerd We are now maintaining patches for libtermkey and libvterm.

Reminder about https://github.com/neovim/neovim/issues/6659 , I'm closing that but it would be nice to reduce the divergence between your upstream projects and the patches we maintain.

**Comment by leonerd** [comment]
@justinmk Righty. If someone can make me a patch that I can look at that would definitely help.

For Windows-related divergences there's not a lot I can do about that, as I don't know what to do or how to test it. So I'd be running somewhat blind on that one.

**Comment by justinmk** [comment]
@leonerd The `*.patch` files are in this PR. As for running blind, we are using this in Neovim, so the patches are somewhat tested...

**Pull request merged**
