### PR TITLE
[RFC] Update patches list up to 7.4.738, marks patches as NA and vim-patch:7.4.713

### PR DESCRIPTION
**Pull request by fmoralesc**
These patches don't apply to the codebase:
- [.611](https://code.google.com/p/vim/source/detail?r=v7-4-611) (if_python3.c)
- [.627](https://code.google.com/p/vim/source/detail?r=v7-4-627) (term.c)
- [.666](https://code.google.com/p/vim/source/detail?r=v7-4-666) (X on *nix)
- [.678](https://code.google.com/p/vim/source/detail?r=v7-4-678) (--remote)
- [.683](https://code.google.com/p/vim/source/detail?r=v7-4-683) (vimtutor)
- [.687](https://code.google.com/p/vim/source/detail?r=v7-4-687) (terminal)
- [.691](https://code.google.com/p/vim/source/detail?r=v7-4-691) (mzscheme)
- [.692](https://code.google.com/p/vim/source/detail?r=v7-4-692) (Solaris)
- [.730](https://code.google.com/p/vim/source/detail?r=v7-4-730) (crypto)
- [.731](https://code.google.com/p/vim/source/detail?r=v7-4-731) (GUI)
- [.738](https://code.google.com/p/vim/source/detail?r=v7-4-738) (compiling w/o syntax highlighting)

[.644](https://code.google.com/p/vim/source/detail?r=v7-4-644) applied in an unsupported platform (Stratus VOS)

Originally I thought [.713](https://code.google.com/p/vim/source/detail?r=v7-4-713) was already applied to the codebase so I was going to include it as a NA, but on checking I realized it wasn't.

### CODE REVIEW

**Comment by splinterofchaos** [comment]
LGTM :+1:

**Comment by Pyrohh** [comment]
Could you please provide URLS to the patches? I think it's only been happening recently (i.e., #2672).

**Comment by fmoralesc** [comment]
@Pyrohh Done. 

Btw, I found patches [.664](https://code.google.com/p/vim/source/detail?r=v7-4-664) and [.703](https://code.google.com/p/vim/source/detail?r=v7-4-703) could be considered as NA too, but I'm wasn't sure, so I didn't include them in this. The first deals with the behavior of 'numberwidth' when 'compatible' is reset, but that is a no-op in nvim, right? The second deals with a part of the code that was removed from `main.c`, but I'm not sure if that was intentional or an oversight.

**Comment by fmoralesc** [comment]
Also: are patches .238 and .244 are really wanted? They add support for [SMACK](https://en.wikipedia.org/wiki/Smack_%28software%29), but I imagine porting them wouldn't do much over the current codebase.  Not sure, though, I didn't see much of how that worked.

**Comment by fwalch** [comment]
> Also: are patches .238 and .244 are really wanted?

Also see #1253.

**Comment by justinmk** [comment]
> Btw, I found patches .664 and .703 could be considered as NA too, 

:+1:  those are NA. .703 is dependent on https://github.com/vim/vim/commit/v7-4-691which is NA, though it is dependent on https://github.com/vim/vim/commit/v7-4-689 which we may need. We can integrate  https://github.com/vim/vim/commit/v7-4-689 without including the others, so I'll include those NAs when I merge this.

**Comment by justinmk** [comment]
Merged thanks!

**Pull request closed without merging**
