### PR TITLE
Improve error handling and reduce duplication of providers' #Require()

### PR DESCRIPTION
**Pull request by jamessan**

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by justinmk** [comment]
Anything blocking this?

**Comment by justinmk** [comment]
@jamessan Does this help with https://github.com/neovim/neovim/pull/5856 (or replace it)?

**Comment by jamessan** [comment]
> Does this help with #5856 (or replace it)?

@Shougo or @chemzqm would have to answer that.  There are similarities in the PRs, but I'm not quite sure what theirs was trying to address.

My intention was solely to avoid causing an exception in `#Require` be accessing a non-existent `job.stderr`.  In the process, I noticed that there was common functionality that could be factored out.

**Comment by Shougo** [comment]
It is better than before implementation, but it is not same with #5856.

My PR is:
https://github.com/neovim/neovim/pull/7036

It improves async RPC initialization.

**Pull request merged**
