### PR TITLE
[WIP] treesitter: simplify query reading logic

### PR DESCRIPTION
**Pull request by bfredl**
Only the plugin/package manager should "manage" `after/`. Consumers of `nvim_get_runtime_file()` should not need to special case it (if your plugin manager is broken then fix it instead).

Don't use `vim.fn.readfile()`. Lua can already read files. It is even better at it than vim script.

expose `M.get_query_files()`. Listing the queries is essential for user config debug, and let plugins do fun things with it.
Abstraction-by-obscurity is not useful (plugins can just cargo cult copy the code anyway, better with public entry points).

missing: test for "modeline" langlists.

### CODE REVIEW

**Comment by bfredl** [comment]
@vigoux did you reach any conclusion if override/extend distinction is still needed?

**Review by vigoux — APPROVED** [review]
I think I agree with this, only thing would be to test this now to fix the behavior.

**Comment by bfredl** [comment]
@vigoux Is there some exiting tests for "inherits" modeline etc in nvim-treesitter that we can port over? :]

**Comment by vigoux** [comment]
Hehe, we don't have tests in nvim-treesitter, users bring us the tests 😉

**Pull request merged**
