### PR TITLE
[RFC] Update version.c to 7.4.1000

### PR DESCRIPTION
**Pull request by Shougo**
NA patches list:
607 Compiler warning
620 Compiler warning
624 result check for realloc
628 volatile add, but no code in neovim
641 tabnew fix, but no code in neovim
661 no K_CURSORHOLD in neovim
841 add ifdef
842 Windows GUI
854 CONTRIBUTION.md
863 FEAT_DIFF
864 Tiny build
923 add ifdef
924 configure changes
927 if_ruby
928 client server
930 Windows GUI
934 Appveyor
938 X11 and GTK GUI fix
940 term
948 ifdef
954 if_lua
959 term
960 Windows build
962 Makefile fix
965 ifdef fix
966 configure fix
967 Makefile fix
976 configure fix
979 crypt feature
985 if_ruby
986 test fix in Windows
987 if_ruby
988 build rule
990 Appveyor

Edit:
Add to 7.4.1000

992 build fix in Windows
994 tests for Windows
995 GTK GUI
996 GTK GUI
997 Travis CI
999 Makefile change

### CODE REVIEW

**Comment by sethjackson** [comment]
LGTM :+1: 

Although I think `988` might be relevant still.

**Comment by Shougo** [comment]
Thanks.  I may update it to 7.4.1000.
Because, Vim HEAD is 7.4.998 now.

**Comment by justinmk** [comment]
Our builds are failing on failed connection to http://luajit.org/download/LuaJIT-2.0.4.tar.gz. I wonder if luajit.org is actually blocking travis, because it downloads fine on my desktop.

**Comment by justinmk** [comment]
LGTM

**Comment by Shougo** [comment]
Thanks.

I will update it to 7.4.998.
992, 994, 995, 996, 997 are new NA patches.

**Comment by justinmk** [comment]
> 992, 994, 995, 996, 997 are new NA patches.

:+1: Also 998, 999.

**Comment by Shougo** [comment]
Updated version.c to 7.4.1000.

> :+1: Also 998, 999.

I think 7.4.999 is NA, but 7.4.998 is not NA.
7.4.998 include test change.  It is needed for neovim.

https://github.com/vim/vim/commit/f9c8bd2137b045f9a64d63eefcf022b4726b1419

Note: Many patches after 7.4.951 includes New style tests.
So, new style tests support is important for neovim.
https://github.com/neovim/neovim/pull/3857

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
