### PR TITLE
feat(lsp): add didChangeWatchedFiles capability

### PR DESCRIPTION
**Pull request by mfussenegger**
This is very early WIP.
Just opening the PR to indicate that I'm working on this.

### CODE REVIEW

**Comment by fsouza** [comment]
@mfussenegger I got tired of random errors from servers complaining about new files being unknown and decided to implement this in my dotfiles, let me know if you'd like to collaborate on getting this merged in core. The strategy in this PR can't really work (eagerly evaluating the glob may cause you to miss new files being added to a file and on large projects you'll run out of file descriptors), instead what I did is:

- start fs_event in the root_dir in recursive mode (don't do anything if the langserver doesn't have a root_dir)
- when the events come, filter them based on the provided blobs (I rolled-up a custom glob-to-regexp compiler for fun, but in core we could just use vim.fn.glob2regpat + vim.regex, I did run into [issues while testing that](https://github.com/neovim/neovim/issues/18111), but there's an easy workaround)
- group the events of interest and send them using client.notify. This uses a timer, and dedupe on the uri - only the most recent event for a uri gets sent. Arguably that may be a bad idea: if the file gets created and deleted within the timer interval, we'll send a delete event for a file that never existed in the server, but hopefully the server can handle that.
- if multiple clients want to watch the same root_dir (or multiple registrations for different globPatterns), we just add them to a list of filters. There's only one fs_event per root_dir. If the number of filters attached to a root_dir gets to 0, stop the fs_event watcher

As far as I understand it, this is how coc.nvim does it, but they offload the heavy work to watchman.

Some of the tricky things:

- like you noted, no bitwise operations. In my case I'm just using bitops from luajit, but I understand that that's a no-no in core for compatibility with PUC Lua
- detecting Changed vs Created: for atomic writes, neovim uses rename, which means fs_event will notify the deletion of the backup file and then the creation of the new file (at least on my filesystem, with `backupcopy=auto`) would need to test the behavior in other system. My "creative" solution here is to keep track of all buffers registered in neovim and whenever I get an event I check whether I have a buffer for that file. If the event is "Created" and I have a buffer for it, I send Changed instead of Created.
- 

I can see a world where this is implemented using autocmds too. The downside is that neovim wouldn't be able to report files created/modified outside of the editor until they're read, but maybe that's ok?

**Comment by mjlbach** [comment]
> start fs_event in the root_dir in recursive mode (don't do anything if the langserver doesn't have a root_dir)

You probably already know this/are doing this but it should watch all workspaceFolders, not just what is marked rootUri (which is deprecated in the spec.

> As far as I understand it, this is how coc.nvim does it, but they offload the heavy work to watchman.

I think we should be able to support watchman as an alternative backend if the user installs it

> like you noted, no bitwise operations

The PR for semantic tokens requires a bit wrapper, I think you can yank it from that PR and file it as a separate function unless @theHamsta wants to do it

> detecting Changed vs Created

This one is tricky, is this a libuv limitation or filesystem?

**Comment by fsouza** [comment]
> This one is tricky, is this a libuv limitation or filesystem?

I assume that it's just a side effect of what neovim does. neovim is effectively always recreating the file, so the filesystem event is the creation of a new file, but we could test it in a Linux box too to see if we get different events.

**Comment by mjlbach** [comment]
I think you're right, that from vim's perspective there is no renaming a file (maybe this should change), but inotify should support rename events: https://man7.org/linux/man-pages/man7/inotify.7.html.

That being said there isn't a convenient way to rename a file anyways (or delete for that matter, except via netrw), so maybe addition only would suffice for now?

**Comment by fsouza** [comment]
Oh yeah I forgot to mention this, but I'm also ignoring events for files that end with `vim.o.backupext`. Here's an example of what I observe on macOS:

```
% cd $(mktemp -d)
% cat >file.lua
local event = vim.loop.new_fs_event()
event:start(vim.loop.cwd(), {recursive=true}, function(err, filename, events)
  print(filename, vim.inspect(events))
end)
^-D
% nvim --clean file.lua
```

Inside neovim run `source %` then save the file. It prints:

```
4913 {
  rename = true
}
file.lua {
  rename = true
}
file.lua {
  rename = true
}
file.lua~ {
  rename = true
}
```

I don't know what 4913 is, I do see it elsewhere and it's always that same number, so I assume that's the name neovim is using for the file temporarily? idk

If I set backupcopy to `yes`, this is what I see:

```
file.lua {
  change = true
}
file.lua~ {
  rename = true
}
```

No 4913 this time. I feel like the events are getting debounced. Otherwise I'd be getting two events for `file.lua~`: one for creation and another one for deletion?

**Comment by mfussenegger** [comment]
> The strategy in this PR can't really work (eagerly evaluating the glob may cause you to miss new files being added to a file and on large projects you'll run out of file descriptors), instead what I did is:


Yes I noticed this, that's the part where I wanted to have a closer look at the vscode implementation to see how they're handling it.

> start fs_event in the root_dir in recursive mode (don't do anything if the langserver doesn't have a root_dir)

Not sure if this is entirely safe. I saw that some servers to send a combination of sub-folders and regexes.
If neovim would always listen to all workspaceFolders it could end up sending notifications for which the server is not interested in. Maybe not an issue, but if the servers are _not_ lenient about that, it could cause troubles.

> group the events of interest and send them using client.notify. This uses a timer, and dedupe on the uri - only the most recent event for a uri gets sent. Arguably that may be a bad idea: if the file gets created and deleted within the timer interval, we'll send a delete event for a file that never existed in the server, but hopefully the server can handle that.

> if multiple clients want to watch the same root_dir (or multiple registrations for different globPatterns), we just add them to a list of filters. There's only one fs_event per root_dir. If the number of filters attached to a root_dir gets to 0, stop the fs_event watcher


Yes I had something like this in mind.

I wanted to get back to this for the 0.8 cycle. I'll have a look at your implementation and take the bits I find useful if that's okay with you.


---

> I think we should be able to support watchman as an alternative backend if the user installs it

I don't think we should attempt to do this for a first implementation. Maybe have a way to make it pluggable so that users could plug in alternative implementations but that's as far as I would go. Things can always get extended later on.
(And they could always override the capability handlers, so even if there is no first-class pluggable support, the handler overrides would always allow it)

**Comment by fsouza** [comment]
> Not sure if this is entirely safe. I saw that some servers to send a combination of sub-folders and regexes.
> If neovim would always listen to all workspaceFolders it could end up sending notifications for which the server is not interested in. Maybe not an issue, but if the servers are not lenient about that, it could cause troubles.

So, while I receive events for all files in the folder, I filter them out based on the provided globPattern. This is what the data structure looks like (in typescript-ish because that's what LSP uses anyways, so I figured everyone would understand it):

```typescript
type Watcher = {
  registrationId: string;
  client: NeovimLSPClient;
  pattern: VimRegex;
  kind: number;
}

type WatchedFolder = {
  event: LuvFSEvent;
  watchers: Watcher[];
}

type State = {
  [folderName: string]: WatchedFolder;
}
```

So whenever there's an event in a folder, I run through all the watchers in that folder, and whenever the pattern matches, I enqueue a notification.

I did just run into one issue with pyright where it wants to get notified about changes in the virtualenv while working on a project for which the virtualenv is not inside the workspace_folder (didn't experience this before because all projects at work store the virtualenv in a subfolder of the workspace).

Here's the notification I got from pyright while working on a project that has a virtualenv outside of the workspace_folder:

```
[TRACE][2022-04-15 10:30:24] .../lua/vim/lsp.lua:806    "server_request"        "client/registerCapability"     {
  registrations = { {
      id = "c9564624-6a7f-49ee-93fb-a668d5516554",
      method = "workspace/didChangeWatchedFiles",
      registerOptions = {
        watchers = { {
            globPattern = "**/pyrightconfig.json",
            kind = 7
          }, {
            globPattern = "**",
            kind = 7
          }, {
            globPattern = "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/**",
            kind = 7
          }, {
            globPattern = "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload/**",
            kind = 7
          }, {
            globPattern = "/Users/fsouza/.cache/nvim/venv/lib/python3.10/site-packages/**",
            kind = 7
          } }
      }
    } }
}
```

My current implementation can't handle that, but I'll try to think of something 🤔 

<details>
<summary>for anyone curious, this is what the notification from pyright looks like when the virtualenv is under the workspace folder</summary>
<pre>
[DEBUG][2022-04-15 10:47:01] .../vim/lsp/rpc.lua:454    "rpc.receive"   {
  id = 5,
  jsonrpc = "2.0",
  method = "client/registerCapability",
  params = {
    registrations = { {
        id = "760681b1-4d66-44e0-92c7-e6871a97bf50",
        method = "workspace/didChangeWatchedFiles",
        registerOptions = {
          watchers = { {
              globPattern = "**/pyrightconfig.json",
              kind = 7
            }, {
              globPattern = "**",
              kind = 7
            } }
        }
      } }
  }
}
</pre>
</details>

> I wanted to get back to this for the 0.8 cycle. I'll have a look at your implementation and take the bits I find useful if that's okay with you.

Yeah absolutely. If you want to test things out I can extract it in a standalone plugin later today or tomorrow.

**Comment by justinmk** [comment]
looks like https://github.com/neovim/neovim/pull/21293 is further along, can we close this?

**Comment by mfussenegger** [comment]
> looks like #21293 is further along, can we close this?

Yes

**Pull request closed without merging**
