### PR TITLE
API: emit nvim_error_event on failed async request

### PR DESCRIPTION
**Pull request by justinmk**
We already do this for _invalid_ async requests #9300.
Now we also do it for failed invocation of valid requests.

### CODE REVIEW

**Comment by justinmk** [comment]
interesting failure:

```
[ RUN      ] swapfile detection always show swapfile dialog #8840 #9027: 589.62 ms OK
test/functional/helpers.lua:814: Keyboard interrupt
stack traceback:
  test/functional/helpers.lua:814: in function <test/functional/helpers.lua:804>
[----------] 3 tests from test/functional/ex_cmds/swapfile_preserve_recover_spec.lua (767.83 ms total)
```

**Comment by bfredl** [comment]
because `nvim_async('command', 'edit %')` will now send back an async error. We could add a flag to `screen:expect` to ignore `nvim_error_event` notifications.

**Comment by justinmk** [comment]
Working on it. It's caught by after_each though, so I was thinking to check the events explicitly using `expect_msg_seq` or something like that. So I am adding an option to `expect_msg_seq` to ignore "redraw" events.

**Comment by bfredl** [comment]
Hmm, what is the `feed('<c-c>')` needed for? if it is to dismiss a message after `feed('e')`, maybe it could just be changed to `<cr>`

**Comment by justinmk** [comment]
Updated, will wait a bit for comments.

**Pull request merged**
