### PR TITLE
ci(publish-winget): use versioned tags for action

### PR DESCRIPTION
**Pull request by vedantmgoyal9**

### CODE REVIEW

**Comment by justinmk** [comment]
I assume this is why the job failed in the release CI? In the future, please include a brief explanation in the commit message, with references or snippets of relevant logs/errors.

**Comment by vedantmgoyal2009** [comment]
@justinmk can you please give the token `workflow` permission OR install https://github.com/wei/pull on neovim/winget-pkgs repo.

**Comment by justinmk** [comment]
> please give the token `workflow` permission

Added workflow permission to the WINGET_TOKEN token of user https://github.com/nvim-winget .

**Comment by dundargoc** [comment]
@vedantmgoyal2009 the winget job is failing again.

**Comment by vedantmgoyal2009** [comment]
I think it is due to the migration from set-ouput to environment variable. GitHub Actions don't pass `version` to the action, which is why, it's failing.

**Comment by dundargoc** [comment]
Ah, I see. I think the syntax for windows is sligthly different, my bad. I'll fix it. Thanks for the response.

**Comment by vedantmgoyal2009** [comment]
PR: https://github.com/neovim/neovim/pull/21077
Test: https://github.com/vedantmgoyal2009/neovim/actions/runs/3481320131

**Pull request merged**
