### PR TITLE
refactor(ui): ui_log() can now just be a function

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by lewis6991** [comment]
This change is causing this error for me:

```

**Comment by lewis6991** [comment]
Caused with src/nvim/memory.c:
```
#ifdef EXITFREE
bool entered_free_all_mem = false;
#endif
```

**Comment by bfredl** [comment]
right, should be the reverse. curious it still worked with Release CI build.

**Comment by dundargoc** [comment]
Uhh, I moved the release build from test.yml to build.yml as I thought it'd only be relevant for build system changes. I guess we should move it back, if not to test then just build.

**Comment by lewis6991** [comment]
We need CI to build at least once without `EXITFREE`.

**Comment by bfredl** [comment]
right, it is the combination of DEBUG but not EXITFREE (plain RelWithDebInfo has neither and thus is fine)

**Comment by dundargoc** [comment]
> We need CI to build at least once without `EXITFREE`.

We should be though. The "unsigned char", "macos", "windows" and "functionaltest-lua" should all not have `EXITFREE` defined.

**Pull request merged**
