### PR TITLE
feat(treesitter): add start/stop autocommands

### LINKED ISSUE #25237: `TreesitterAttach` and `TreesitterDetach` autocmds
### Problem

There is no clean way to add logic right after treesitter is attached to a buffer, instead we have to hook our logic into another autocmd and `vim.treesitter.start()`.

Example: https://github.com/lewis6991/dotfiles/blob/13faceced69a2811773071587d9d1af1c4a7526f/config/nvim/lua/lewis6991/treesitter.lua#L65

### Expected behavior

**TreesitterAttach** and **TreesitterDetach** autocmds.

### PR DESCRIPTION
**Pull request by MariaSolOs**
Closes #25237

I know that I'm missing the documentation but I wanted to get a review first.

### CODE REVIEW

**Comment by lucario387** [comment]
This doesn't make much sense since treesitter doesn't just mean highlighting, it can also be folds, (and for nvim-treesitter, indents and textobjs). A person can enable the other treesitter-related functionalities without highlighting

**Comment by MariaSolOs** [comment]
@lucario387 I was also thinking about the additional modules, but I couldn't find any code aware of those in this codebase (I might have not searched carefully).

**Comment by lucario387** [comment]
For folds, it's `_fold.lua`. It was previously refactored to not rely on highlighting.
For nvim-treesitter indents, it's in `lua/nvim-treesitter/indent.lua`
For nvim-treesitter-textobjects and nvim-treesitter-context, it's in the respective repos

**Comment by lucario387** [comment]
It's okay for it to be only for highlights though. attach/detach logic may become a burden to maintain from nvim, example being nvim-treesitter/nvim-treesitter#4767

**Comment by MariaSolOs** [comment]
@lucario387 yeah... I'm afraid it might become more confusing for the event only to be fired for modules bundled in core, and not for external modules.

**Comment by clason** [comment]
Yes, I believe the original request to be fundamentally misguided (based on nvim-treesitter's ill-conceived "modules" system, which had `attach` and `detach` methods inspired by LSP).

Let's park this and wait for a stronger argument from the OP before implementing something based on a hunch ;)

**Comment by lewis6991** [comment]
Adding autocmds for this is jumping the gun IMO.

I think in general we need to be applying effort to our internal implementation of treesitter and hold off on extending the API until that is in much better shape.

**Pull request closed without merging**
