### PR TITLE
[RFC] vim-patch:7.4.888

### PR DESCRIPTION
**Pull request by jbradaric**
Problem:    The OptionSet autocommands are not triggered from setwinvar().
Solution:   Do not use switch_win() when not needed. (Hirohito Higashi)

https://github.com/vim/vim/commit/ba117c23dfd1146aca3235bea172df17a48bccee

### CODE REVIEW

**Comment by watiko** [comment]
LGTM.

I wrote additional test cases (https://github.com/watiko/neovim/commit/2f589501870efded874de90bcd0f6127ebdad2af). Can you cherry-pick it? This commit also fixes the test issue.

**Comment by jbradaric** [comment]
@watiko Ok, I've cherry-picked your commit.

**Comment by watiko** [comment]
@jbradaric Thanks. Ah, but sorry `make testlint` cause errors. I pushed a fix to the same branch.

**Comment by jbradaric** [comment]
@watiko No problem, I've cherry-picked the fix as well.

**Comment by watiko** [comment]
:+1:

**Pull request merged**
