### PR TITLE
[RFC] vim-patch:7.4.1740

### PR DESCRIPTION
**Pull request by novadev94**
#### vim-patch:7.4.1740

Problem:    syn-cchar defined with matchadd() does not appear if there are no
            other syntax definitions which matches buffer text.
Solution:   Check for startcol. (Ozaki Kiichi, haya14busa, closes vim/vim#757)

https://github.com/vim/vim/commit/4d585022023b96f6507e8cae5ed8fc8d926f5140

### CODE REVIEW

**Comment by KillTheMule** [comment]
The build fail because of [this change](https://github.com/neovim/neovim/pull/5366/commits/ff070d86f8baaece012781226b8976e72f3c8224#diff-652ba8f711669fd3aa981ba690a56f43R3640). The vim patch has [proper parenthesis](https://github.com/vim/vim/commit/4d585022023b96f6507e8cae5ed8fc8d926f5140#diff-ceb2e2231c5d45523135ca0cfc492792R4914) here.

**Comment by NovaDev94** [comment]
Thanks a lot @KillTheMule 👍. My bad.

**Comment by KillTheMule** [comment]
[This](https://github.com/neovim/neovim/pull/5366/commits/bd25b023e9230477f8dfce89156f487aef1c0b11#diff-01364eebe7d8538946ada38135fbaeaaR5) does not work in neovim, encoding can't be changed after startup, dunno about scriptencoding... are we fixed on utf-8 now? See https://github.com/neovim/neovim/pull/2929. Ping @bfredl, what is supposed to happen here wrt scriptencoding?

**Comment by bfredl** [comment]
I think it should be ok to just remove both lines. If it is valid utf8 the script will automatically be detected as utf8

**Comment by jamessan** [comment]
`scriptencoding` is still a useful command, more so when the encoding isn't utf8.  I don't see a reason to remove it from here, even if it is essentially a no-op in this case.

**Comment by jamessan** [comment]
Why was match_conceal_spec.lua removed?

**Comment by bfredl** [comment]
But I think the reason for scriptencoding here is, if vim starts with `encoding=latin1` the script will be detected as latin1 (unless it would have a BOM), and after changing to `enc=utf8` the scriptencoding needs be changed to utf-8 as well. Leaving this completely unmodified might be better (#2905 will allow this again), but after removing `set encoding=utf-8`(because it is assumed) the following `scriptencoding utf-8` does not fill any purpose on its own.

**Comment by NovaDev94** [comment]
@jamessan Thank you for giving this a review. `match_conceal_spec.lua` is removed since the `src/testdir/test_match_conceal.in` is also removed in the original patch. I've checked and those files' content are identical. Please let me know if removing it isn't needed / prohibited.  

@bfredl I will try removing both the encoding lines 👍 .

**Comment by KillTheMule** [comment]
Can't really figure out the QB failures. Looks like some cloning failed? Maybe someone could restart the build.

**Comment by NovaDev94** [comment]
There's no failed tests on QB. However the success rate is still below 100%. Maybe this is because of the removed test?

image

**Comment by KillTheMule** [comment]
What fails is the osx and bsd builds, klick on "Step status" for an overview. The non-100% success rate stems from the 10 skipped tests, I assume.

**Comment by NovaDev94** [comment]
Ah ok I got it. Seems like a checkout/clone problem.

**Comment by jamessan** [comment]
Thanks! Merged.

**Pull request merged**
