### PR TITLE
[RDY] vim-patch: 7.4.735 is NA

### PR DESCRIPTION
**Pull request by fmoralesc**
Problem:    Wrong argument for sizeof().
Solution:   Use a pointer argument. (Chris Hall)

https://github.com/vim/vim/releases/tag/v7.4.735

This was already handled in nvim.

### CODE REVIEW

**Comment by oni-link** [comment]
The link in the commit message should point directly to the vim commit, otherwise LGTM.

**Comment by fmoralesc** [comment]
Done. Will merge once the tests pass.

**Comment by justinmk** [comment]
Note for future reference: technically, NA patches should not be mentioned with the `vim-patch:<version>` format, for license purposes. Though in this case it doesn't matter since the edit is just a version.c change.

**Comment by fmoralesc** [comment]
Ah! I had never seen this before, sorry if I messed up a bit.

**Pull request merged**
