### PR TITLE
eval.c: factor out eval/funcs.c (vim-patch 7.4.2063)

### PR DESCRIPTION
**Pull request by doubleloop**
ref #5081

notes:
- the changes are split into commits to avoid sneaky changes (no "move and change" commits for sake of easier review)

questions:
- do I have to fix lint errors in eval/funcs.c (~11k lines of code moved from eval.c) in this pr? Alternatively the list of lint exceptions could be updated for now.
- any idea why ASAN build fails on travis? (it does not on my machine)

### CODE REVIEW

**Comment by justinmk** [comment]
This is quite some work, thanks. Looks like you referenced the ideas from #5081, great!

> do I have to fix lint errors in eval/funcs.c (~11k lines of code moved from eval.c) in this pr?

No, this is big enough. Let's be conservative.

>  any idea why ASAN build fails on travis? (it does not on my machine)

search the build logs to find out. In this case, first error is:

```
In file included from ../src/nvim/eval/funcs.c:88:
[1m/home/travis/build/neovim/neovim/build/src/nvim/auto/funcs.generated.h.gperf:519:26: [0m[0;1;31merror: [0m[1mstatic function 'hash_internal_func_gperf' is used in an inline function with external linkage [-Werror,-Wstatic-in-inline][0m
      register int key = hash_internal_func_gperf (str, len);
[0;1;32m                         ^
[0m[1m/home/travis/build/neovim/neovim/build/src/nvim/auto/funcs.generated.h.gperf:509:1: [0m[0;1;30mnote: [0muse 'static' to give inline function 'find_internal_func_gperf' internal linkage[0m
```

**Review by justinmk — APPROVED** [review]
LGTM at a glance. Will do a final pass after ASAN job is fixed

Note: the `check_parser` error on appveyor is unrelated, ignore it.

**Comment by doubleloop** [comment]
ASAN job is fixed now

> >do I have to fix lint errors in eval/funcs.c (~11k lines of code moved from eval.c) in this pr?
>
>No, this is big enough. Let's be conservative.

so what should I do now to prevent lint job failures?

Questions:
* I locally started porting v7.4.2058, I think it should go to separate PR, is it ok or do you prefer to add it to this one?
* do you prefer me to squash the commits our should I just for example prefix all commit msgs with patch number, or simply leave it as is?

**Comment by justinmk** [comment]
> so what should I do now to prevent lint job failures?

Our CI bot will update the allowed violations. I might try to fix up some of them before merging--so please wait on that to avoid merge conflicts.

> I locally started porting v7.4.2058, I think it should go to separate PR, is it ok or do you prefer me to push commits to this one?

new PR 👍  Let's get through this one first. 

What's your plan for it at a high level? (e.g. moving which family of functions , to which files?)

> do you prefer me to squash the commits our should I just for example prefix all commit msgs with patch number, or simply leave it as is?


For these delicate PRs it's better to let the merger do the squashing, so that it is clear via GitHub which parts were already reviewed.

**Comment by doubleloop** [comment]
> What's your plan for it at a high level? (e.g. moving which family of functions , to which files?)

For now:
* eval/funcs.c (this PR, simmilar as evalfuncs.c in [7.4.2063](https://github.com/vim/vim/commit/73dad1e64cb42842d8259cb1a255a6fa59822f76) )
* eval/user_funcs.c (simmilar as userfunc.c in [v7.4.2058](https://github.com/vim/vim/commit/a9b579f3d7463720a316e11e77a7a9fbb9267986) )

Here are my notes with the list of moved functions:
<details><summary>functions moved to eval/funcs.c</summary>

```
both (vim an neovim):
    buf_win_common
    byteidx
    do_searchpair
    do_sort_uniq
    find_buffer
    find_internal_func
    find_some_match
    findfilendir
    foldclosed_both
    get_buffer_lines
    get_expr_name
    get_function_name
    get_list_line
    get_maparg
    get_search_arg
    get_winnr
    getpos_both
    item_compare
    item_compare2
    libcall_common
    list2proftime
    max_min
    non_zero_arg
    search_cmn
    searchpair_cmn
    set_qf_ll_list
    all f_*

nvim only (absent in vim codebase)
    item_compare2_keeping_zero
    item_compare2_not_keeping_zero
    item_compare_keeping_zero
    item_compare_not_keeping_zero

vim only (absent in nvim codebase)
    buflist_find_by_name
    call_internal_func
    check_connection
    compare_func_name
    execute_redir_str
    free_callback
    get_buf_tv
    get_callback
    get_cmd_output_as_rettv
    get_float_arg
    get_job_arg
    get_tv_lnum
    get_tv_lnum_buf
    make_connection
    mkdir_recurse (os/fs.c:os_mkdir_recurse)
    mzscheme_call_vim
    remote_common
    sortFunctions
    tv_islocked (typval.c)
    vim_round
```

</details>

<details><summary>functions moved to eval/user_funcs.c (wip)</summary>

```
vim and neovim:
    add_nr_var
    builtin_function
    call_func
    call_user_func
    can_free_funccal
    cat_func_name
    current_func_returned
    deref_func_name
    do_return
    emsg_funcname
    eval_fname_script
    eval_fname_sid
    ex_call
    ex_delfunction
    ex_function
    ex_return
    find_func
    fname_trans_sid
    free_all_functions
    free_funccal
    func_breakpoint
    func_call
    func_dbg_tick
    func_do_profile
    func_dump_profile
    func_free
    func_has_abort
    func_has_ended
    func_level
    func_line_end
    func_line_exec
    func_line_start
    func_name
    func_ref
    func_unref
    function_exists
    get_func_line
    get_func_tv
    get_funccal
    get_funccal_args_ht
    get_funccal_local_ht
    get_function_args
    get_lambda_tv
    get_return_cmd
    get_user_func_name
    list_func_head
    list_func_vars
    prof_child_enter
    prof_child_exit
    prof_func_line
    prof_self_cmp
    prof_sort_list
    prof_total_cmp
    restore_funccal
    save_funccal
    trans_function_name
    translated_function_exists

vim only (absent in nvim codebase):
    clear_current_funccal
    discard_pending_return
    free_unref_funccal
    func_init
    get_current_funccal_dict
    get_expanded_name
    get_funccal_args_var
    get_funccal_local_var
    make_partial
    restore_current_funccal
    set_ref_in_call_stack
    set_ref_in_func_args
    set_ref_in_previous_funccal
```

</details>

For this particular changes I kind of blindly followed what vim did at that point (the strategy was: moved all functions which were moved in vim patches then make nesesery changes to compile the code). In result there might be some leftovers in eval.c. If so they can be fixed in separate commits (it is a lot code to familiarize with so iterative approach looks to be the right one here).

This 2 changes alone would reduce eval.c from ~25k  to ~11k which I think it is not bad starting point. I do not  yet have clear view where to go next after this (opened for suggestions).

**Comment by justinmk** [comment]
> Here are my notes with the list of moved functions:

Really nice--thanks!

> I kind of blindly followed what vim did at that point

Don't worry about that. For merging upstream patches, the function name matters more than where it lives. 

> This 2 changes alone would reduce eval.c from ~25k to ~11k which I think it is not bad starting point. I do not yet have clear view where to go next after this

Let's stop there, unless we actually have a _reason_ to go further. "Make files smaller" is not a reason. But "builtin functions live in X, userfunc engine lives in Y", is a reasonable separation.  File size itself is meaningless (though websites have trouble with it, but that's there problem...)

**Comment by justinmk** [comment]
> I might try to fix up some of them before merging--so please wait on that to avoid merge conflicts.

Looks like 95% of the lint complaints are about `/*` comments. So I didn't touch it, that's easy to fix later in a low-risk lint commit.

**Pull request closed without merging**
