### PR TITLE
nvim__screenshot

### PR DESCRIPTION
**Pull request by bfredl**
why?
===

Because screenshot.

but seriously why?
===

I need it for my vimconf talk.

### CODE REVIEW

**Comment by bfredl** [comment]
This is going to allow us to resolve #5116. Just include a screenshot of `vim8` displaying `:smile` into the runtime, and hot wire it to `:smile` using some lua magic.

**Comment by bfredl** [comment]
drawback: this does not handle external UI. 0.6 will ship with an additional fileformat for dumping ext_multigrid/ext_hlstate state.

**Comment by glacambre** [comment]
@bfredl I saw your screenshot in #5116 - am I understanding your PR correctly if I see it as an equivalent to `:TOhtml` but for neovim grids?

**Comment by bfredl** [comment]
lol I have no idea what Tohtml really does. Currently this just dumps the final rendered grid inside the TUI module (multigrid support will be later) as the equivalent ANSI sequences to render on a big enough truecolor term with `cat` only.

**Comment by glacambre** [comment]
Ah, yes, that's almost what `:TOhtml` does. Thanks for indulging my curiosity :)

**Comment by bfredl** [comment]
merged. considered a quasi-official util function now, function will be versioned once the format is stabilized (which needs ext_ support).

**Comment by justinmk** [comment]
We do document the private API methods though. Also worth a smoke test...

**Comment by bfredl** [comment]
@justinmk I trust you with docs :> Bring on the smoke!

**Comment by vhakulinen** [comment]
`nvim --api-info` seems to expose this.

**Pull request merged**
