### PR TITLE
[RDY] Fix bug, hostname on windows ignore character-case

### LINKED ISSUE #7909: BUG: hostname on windows don't care character case
Version: HEAD

https://github.com/neovim/neovim/blob/15119f943ab8c2d089f45969da06b6b58b4d0036/test/functional/eval/hostname_spec.lua#L14

`helpers.eq(expected, actual)` => `helpers.eq(expected:upper(), actual:upper())`

image

### LINKED ISSUE #7910: BUG: test
The test program is assumed in the C drive operation, I actually in the E disk, the comparison fails

https://github.com/neovim/neovim/blob/15119f943ab8c2d089f45969da06b6b58b4d0036/test/functional/core/job_spec.lua#L65-L66

image

### PR DESCRIPTION
**Pull request by zhaozg**
try to fix https://github.com/neovim/neovim/issues/7909
try to fix #7910

### CODE REVIEW

**Comment by zhaozg** [comment]
@justinmk please do Code Review, and thanks

**Comment by zhaozg** [comment]
push wrong, Let me fix later.

**Comment by zhaozg** [comment]
ping @marvim

**Comment by justinmk** [comment]
merged, thanks!

**Pull request closed without merging**
