### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by ckelsel** [comment]
vim-patch:8.0.0207: leaking file descriptor when system() fails

**Comment by DrizzlingCattus** [comment]
vim-patch:8.0.0236: gcc complains about uninitialized variable

**Comment by ckelsel** [comment]
vim-patch:8.0.0233: paste test fails in the GUI                                 
vim-patch:8.0.0231: bracketed paste mode is not tested
vim-patch:8.0.0230: bracketed paste does not support line breaks
vim-patch:8.0.0210: no support for bracketed paste

**Comment by KillTheMule** [comment]
>  vim-patch:8.0.0231: bracketed paste mode is not tested

Sure about that? Neovim has bracketed paste, so maybe we should merge those tests. Or do we have enough already?

**Comment by ckelsel** [comment]
@KillTheMule [Bracketed paste only works with "xterm".](https://github.com/vim/vim/blob/v8.0.0231/src/testdir/test_paste.vim)

**Comment by KillTheMule** [comment]
Maybe I'm not fully understanding something, but it still looks like a worthwhile patch to merge to me.

**Comment by justinmk** [comment]
> vim-patch:8.0.0233: paste test fails in the GUI
> vim-patch:8.0.0231: bracketed paste mode is not tested

@ckelsel we should almost always merge changes to the tests, so that future merges are easier. And 0231 has a change that we should mimic in `src/nvim/testdir/Makefile`. Some of the tests in `test_paste.vim` should be skipped in Nvim, but some are relevant, such as `Test_paste_normal_mode()`.

**Pull request merged**
