### PR TITLE
docs(maintain): add note on updating `luvref.txt`

### PR DESCRIPTION
**Pull request by clason**
Reminder to self that when we bump luv, we should (manually) update our bundled documentation from upstream. (Easiest way is to check the commit log for https://github.com/luvit/luv/blob/master/docs.md and port each commit by hand.)

### CODE REVIEW

**Comment by lewis6991** [comment]
I dislike how `luv`'s docs are manually written in markdown. I might push for their docs to be maintained in a more machine-readable format (Lua or Json), so we can then use that to render out our vim-docs AND Lua type annotations.

**Comment by clason** [comment]
I think the markdown itself is generated from somewhere? That'd be the first thing to check.

**Comment by lewis6991** [comment]
I thought it would be too, but couldn't quickly find out where. The git blame indicated to me it wasn't.

I'll double check.

**Comment by lewis6991** [comment]
Based on this [commit](https://github.com/luvit/luv/commit/cdd34897cbf0d218b29c42800ba10ca42b873ed3) which adds a new function, I don't think it is.

**Comment by clason** [comment]
Must have confused it with another project (probably LibUV). In any case, except the top sections, the document seems to be a pure API reference, which should indeed be generated from code annotations.

Maybe we could interest the project in our own workflow for that 😬

**Comment by lewis6991** [comment]
https://github.com/luvit/luv/issues/632

**Comment by lewis6991** [comment]
>  which should indeed be generated from code annotations.

There isn't really any good workflows to extract these annotations. [ldoc](https://stevedonovan.github.io/ldoc/) is the best thing I've found which I'm using for https://github.com/lewis6991/async.nvim but it isn't great.

A good stop gap solution would to just maintain a more machine readable format as opposed to markdown.

**Comment by clason** [comment]
There's some (very welcome) discussion around a streamlined workflow at https://github.com/neovim/neovim/issues/21273

**Review by justinmk — APPROVED** [review]

**Pull request merged**
