### PR TITLE
Use Dockerfile syntax file from the upstream Vim 

### PR DESCRIPTION
**Pull request by jubnzv**
Before:

image

After:

image

### CODE REVIEW

**Comment by jarimayenburg** [comment]
Thanks, I was looking for this. What if we just use the syntax file that's used in Vim? It fixes this `AS` issue and improves support overall. For example, it's based on regular shell syntax, so your `RUN` commands get highlighting too!

https://github.com/vim/vim/blob/master/runtime/syntax/dockerfile.vim

**Comment by jubnzv** [comment]
Interesting. They recently updated this file, and it includes a bit more fixes. I think it's right to take it as it is.

**Comment by jarimayenburg** [comment]
Great! I think we're ready to tag this as [RDY]

**Comment by janlazo** [comment]
Redo this PR like the other merged runtime PRs in https://github.com/neovim/neovim/pulls?q=is%3Apr+is%3Aclosed+label%3Aruntime.

**Comment by jarimayenburg** [comment]
@janlazo I created a new PR according to contribution guidelines: #13404

**Pull request closed without merging**
