### PR TITLE
docs: ":che" is ":checkhealth"

### PR DESCRIPTION
**Pull request by ii14**

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by zeertzjq** [comment]
How about making the behavior compatible with Vim instead?
```diff
diff --git a/src/nvim/ex_cmds.lua b/src/nvim/ex_cmds.lua
index 04b883242..dee719d9e 100644
--- a/src/nvim/ex_cmds.lua
+++ b/src/nvim/ex_cmds.lua
@@ -486,18 +486,18 @@ module.cmds = {
     addr_type='ADDR_NONE',
     func='ex_changes',
   },
-  {
-    command='checkhealth',
-    flags=bit.bor(EXTRA, TRLBAR),
-    addr_type='ADDR_NONE',
-    func='ex_checkhealth',
-  },
   {
     command='checkpath',
     flags=bit.bor(TRLBAR, BANG, CMDWIN, LOCK_OK),
     addr_type='ADDR_NONE',
     func='ex_checkpath',
   },
+  {
+    command='checkhealth',
+    flags=bit.bor(EXTRA, TRLBAR),
+    addr_type='ADDR_NONE',
+    func='ex_checkhealth',
+  },
   {
     command='checktime',
     flags=bit.bor(RANGE, BUFNAME, COUNT, EXTRA, TRLBAR),
```

Completion is still ordered alphabetically, so `:che<Tab>` still gives `:checkhealth` first.

**Comment by justinmk** [comment]
> Completion is still ordered alphabetically, so `:che<Tab>` still gives `:checkhealth` first.

Good idea. Thanks for this also @ii14 . I've long been tempted to claim `:ch` for this (does anyone actually use `:change` ?), but `:che` is probably good enough.

**Comment by ii14** [comment]
`:change` is also `:c`, so if you're using that command then I assume you most likely prefer the shorter `:c` rather than `:ch`. I personally can't see myself using that command ever. At the same time I'm not sure if `:checkhealth` is necessarily the best candidate to replace such a short mapping. I think that for example `:chistory` would be more convenient to have as `:ch`, if we decide to change it.

**Comment by justinmk** [comment]
> `:change` is also `:c`, so if you're using that command then I assume you most likely prefer the shorter `:c` rather than `:ch`. 

Indeed...

> At the same time I'm not sure if `:checkhealth` is necessarily the best candidate to replace such a short mapping. I think that for example `:chistory`

"ch" has the nice property of being an acronym for "check health" :) 

Probably not worth the risk though.

**Comment by dundargoc** [comment]
Rebase

**Pull request merged**
