### PR TITLE
feat(tui): use terminfo for set_cursor_color/reset_cursor_color OSC

### PR DESCRIPTION
**Pull request by kraftwerk28**
Use terminfo capability instead of pattern-matching through the `$TERM`.
Related: https://codeberg.org/dnkl/foot/issues/463

### CODE REVIEW

**Comment by gpanders** [comment]
How common are the `Cs` and `Cr` terminfo entries? Perhaps the heuristics on `$TERM` should be kept as a fallback if these attributes are missing from terminfo.

**Comment by justinmk** [comment]
terminfo is often wrong so we tend to avoid it, it just confuses users. But $TERM is not much better, so checking terminfo makes sense here.

**Comment by kraftwerk28** [comment]
Would it be ok to check for terminfo first, then fallback to `$TERM`, if no such cap is found?

**Comment by justinmk** [comment]
> Would it be ok to check for terminfo first, then fallback to `$TERM`, if no such cap is found?

isn't that what this PR does? 

the problem in general is that terminfo entries are often wrong.

**Pull request merged**
