### PR TITLE
[WIP/TEST] ci: test using Windows on Travis

### PR DESCRIPTION
**Pull request by blueyed**
Might be a good alternative to AppVeyor.
Using Azure Pipelines was mentioned in https://github.com/neovim/neovim/issues/10199#issuecomment-501746066 (as a low prio).

### CODE REVIEW

**Comment by justinmk** [comment]
we should not increase our dependency on travis.

**Comment by blueyed** [comment]
> we should not increase our dependency on travis.

ok.  Is the plan then to move away from it in the long run, e.g. when Azure is used for Windows?

**Comment by justinmk** [comment]
in the near-term, Azure would be useful as a macOS alternative. Then we would disable macOS on travis. 

If it works well we could in the long term eliminate AppVeyor. But that is a really low priority. We should not spend time on it.

**Comment by blueyed** [comment]
It will never happen when not spending time on it though.. ;)

I wanted to give it a try.
I think it is good to share config between builds (unlike AppVeyor which is different altogether already).

**Comment by justinmk** [comment]
> It will never happen when not spending time on it though.. ;)

That's a good thing, if higher-priority things got done instead.

**Pull request closed without merging**
