### PR TITLE
server: introduce --listen, deprecate $NVIM_LISTEN_ADDRESS

### PR DESCRIPTION
**Pull request by justinmk**
`$NVIM_LISTEN_ADDRESS` is awkward/ambiguous because it does multiple things: it sets the listen address, but also is used to detect a parent `nvim`.

This PR introduces the `--listen` option and deprecates `$NVIM_LISTEN_ADDRESS`.

A followup PR will introduce `$NVIM` env var which is like `$TMUX`, it will be an opaque map for used by nested `nvim` instances.

todo

- [x] tests
- [x] initialize `v:servername` with a new address if `$NVIM_LISTEN_ADDRESS` is invalid.
- [x] implement `helper.matches()`

future

- do not pass `$NVIM_LISTEN_ADDRESS` to `:terminal` environment
- ~~should `$NVIM_LISTEN_ADDRESS` actually be deprecated? It's still useful for the example give at `:help rpc-connecting`~~

### CODE REVIEW

**Comment by mrbiggfoot** [comment]
@justinmk with this PR, how a script inside a neovim terminal is supposed to communicate with the parent neovim instance?

**Comment by justinmk** [comment]
@mrbiggfoot I will introduce a new env var `$NVIM` which will be set only in `:terminal` and will not be passed down to grandchildren. I'm thinking it should be a JSON map, something like:

    $NVIM={"server":"/tmp/nvimfoo","buf":42}

**Comment by bfredl** [comment]
Sounds good. Not sure I understand the " will not be passed down to grandchildren" part, but I suppose it will make sense when we see the next PR :)

**Comment by mhinz** [comment]
> I'm thinking it should be a JSON map, something like:

```
$NVIM={"server":"/tmp/nvimfoo","buf":42}
```

Is this better than simply adding multiple env variables? This means that all programs relying on `$NVIM` need to be able to parse JSON. E.g. for nvr I'd need to import yet another package for this.

IMHO, using JSON in an env variable is rather uncommon and makes it harder to use. :)

**Comment by justinmk** [comment]
> Is this better than simply adding multiple env variables? This means that all programs relying on $NVIM need to be able to parse JSON. 

It's meant to be opaque. If there is some program that can't parson the (extremely simple) JSON we can revisit, but it doesn't require a JSON library. 

Not to mention, `nvim` is capable of parsing JSON, so one can always shell out ...

Also `$NVIM_LISTEN_ADDRESS` still exists for back-compat.

**Pull request merged**
