### PR TITLE
fix(api): fix issues with nvim_buf_set_lines refactor

### PR DESCRIPTION
**Pull request by bfredl**
the change to topline was different for non-current and current (including "current") window, for some undocumented reason.

### CODE REVIEW

**Comment by bfredl** [comment]
After writing tests, I concluded the proper fix is to change it the other way around. i e the old behavior for current window was the incorrect one. The tests should hopefully illustrate this reasoning. This behavior is consistent with if you manually edited the buffer in a split window, i e the logical topline "www" would be preserved, not the numeric value of topline.

Unfortunately this means that telescope need to be changed somehow, as to not rely on the previous, self-inconsistent behavior.

**Comment by bfredl** [comment]
Added fix for the undolevel issue as well.

**Comment by lewis6991** [comment]
I'm still having issues with telescope. Whenever the amount of matches is less than the height of the window, then they are not rendered.

This is with `git_files`.

**Comment by lalitmee** [comment]
I am also facing some issues while searching in `Telescope` and opening any buffer, the first line is automatically removed, and whenever I save the buffer too.

**Comment by TymekDev** [comment]
Hey, I have just noticed that commit https://github.com/neovim/neovim/commit/9b9030ff2ca820d4c4f4b559f86b0f9a3496645b introduces an unexpected window scrolling. Whenever I call `vim.lsp.buf.format()` I end up with window scrolled as if I used `zb`.

https://github.com/neovim/neovim/assets/38053499/c9b4b9e6-c4ca-4f0f-b258-23849fe4c278

This appears to be affected by both `scrolloff` and window size. If the window contains fewer lines, then it does not necessarily happen.

Config for reproduction:

```lua
-- lazy.nvim bootstrap start
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
-- lazy.nvim bootstrap end

require("lazy").setup({
  {
    "neovim/nvim-lspconfig",
    config = function()
      require("lspconfig").r_language_server.setup({
        cmd = { "R", "--vanilla", "--slave", "-e", "languageserver::run()" },
      })
    end,
  },
})
```

**Comment by zeertzjq** [comment]
Please create an issue.

**Pull request merged**
