### PR TITLE
coverity/155509: negative close() arg

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Review by jamessan — COMMENTED** [review]
Why not return from `os_nodetype()` immediately if `open()` returns -1?

**Comment by justinmk** [comment]
That manifests as the UV_UNKNOWN_HANDLE case, which is handled differently on win/unix. Probably doesn't matter, but I thought this keep the logic together.

**Comment by jamessan** [comment]
Ok, but why is it inside an `if (fd > 2)` check?  If we opened it, we should close it, no?

**Comment by justinmk** [comment]
It's part defensive, part cargo-cult. We probably don't ever want to close 0/1/2 accidentally, but it probably will never be passed to os_nodetype(). Corrections appreciated.

**Comment by jamessan** [comment]
We're calling `open()` _in_ this function, so it doesn't matter if we close it.  It would be different if `fd` were being passed into this function.

**Comment by jdebp** [comment]
Checking `fd > 2` turns a call to `close()` that benignly may signal `EBADF`, into a potential open file leak into child processes.

**Comment by justinmk** [comment]
Thanks @jamessan and @jdebp .

> That manifests as the UV_UNKNOWN_HANDLE case, which is handled differently on win/unix. Probably doesn't matter, but I thought this keep the logic together.

On second thought, returning anything other than NODE_OTHER if open() failed, seems wrong. 

Updated to return NODE_OTHER.

**Comment by justinmk** [comment]
macOS unittests are failing. On macOS, `/dev/stderr` has permissions `lr-xr-xr-x`. But we specify `O_RDONLY`; is it still expected that open() returns -1?

```
[1m[35m[  FAILED  ][0m[0m [1m1[0m test, listed below:
[1m[35m[  FAILED  ][0m[0m [36m./test/unit/helpers.lua[0m @ [36m733[0m: [1mfs.c file operations os_nodetype returns NODE_WRITABLE for /dev/stderr[0m
./test/unit/helpers.lua:702: (string) '
/Users/travis/build/neovim/neovim/test/unit/os/fs_spec.lua:718: Expected objects to be the same.
Passed in:
(number) 2
Expected:
(number) 1'
```

**Comment by jamessan** [comment]
> That's a link to a non-readable file:

It's readable by the owner...

**Comment by jamessan** [comment]
The `NODE_OTHER` return was due to incorrectly checking the returned value from `open()`.  The only thing that's guaranteed is that -1 indicates an error, where as the code was treating all negative values as an error.

The check is fixed in the current commit but there are issues with clang in Travis which should be addressed by #6896.

**Review by jamessan — APPROVED** [review]

**Pull request merged**
