### PR TITLE
vim-patch:8.2.{1949,2781}

### PR DESCRIPTION
**Pull request by zeertzjq**
#### vim-patch:8.2.2781: add() silently skips when adding to null list or blob

Problem:    Add() silently skips when adding to null list or blob.
Solution:   Give an error in Vim9 script.  Allocate blob when it is NULL like
            with list and dict.

https://github.com/vim/vim/commit/b7c21afef14bba0208f2c40d47c050a004eb2f34

Do not implicitly change a NULL blob/dict/list to an empty one.

N/A patches for version.c:

vim-patch:8.2.1949: Vim9: using extend() on null dict is silently ignored

Problem:    Vim9: using extend() on null dict is silently ignored.
Solution:   Give an error message.  Initialize a dict variable with an empty
            dictionary.

https://github.com/vim/vim/commit/348be7ed07d164970ec0004bc278e254eb0cf5bf

N/A because Nvim's current behavior is an error message as a locked
list/dict, which is more consistent. Ref #4615.

Co-authored-by: Bram Moolenaar <Bram@vim.org>

### CODE REVIEW

**Comment by zeertzjq** [comment]
This change is probably unwanted.

**Comment by justinmk** [comment]
Not sure. What's the benefit of silent failure for these cases? Is it useful for Lua/RPC bridge?

**Comment by zeertzjq** [comment]
These patches make the behavior of NULL List/Dict/Blob inconsistent. With these patches `v:_null_list`, `v:_null_dict`, `v:_null_blob` are implicitly changed to empty List/Dict/Blob when passed to a function, while NULL List/Dict/Blob returned by functions are not, so `v:_null_list`, `v:_null_dict`, `v:_null_blob` can no longer be used with these patches.

**Comment by bfredl** [comment]
> Not sure. What's the benefit of silent failure for these cases? 

Currently you get the same error message as a locked (read-only) list which I think is reasonable.

**Comment by justinmk** [comment]
Ok, then let's mark these patches as N/A in a commit with this note:

> Current behavior is an error message as a locked (read-only) list.

**Comment by justinmk** [comment]
Ok, in https://github.com/neovim/neovim/pull/22363 I marked these patches as N/A in a commit with this note:

> Current behavior is an error message as a locked (read-only) list.

**Comment by zeertzjq** [comment]
I don't think the error message is important. I'll merge these without the change to variable passing.

**Comment by zeertzjq** [comment]
Oh, keeping the current error message indeed makes more sense.

**Pull request merged**
