### PR TITLE
test: :!  cat binary data, handle control chars

### LINKED ISSUE #4142: cat'ing binary file causes abort
Very simple and easy to reproduce. 
1. `nvim -u NONE`
2. `:term<CR>`
3. `cat /bin/bash`
4. Crash

I know you aren't supposed to literally read a binary, but I don't think there should be room for neovim to crash.

### LINKED ISSUE #5442: cat'ing binary file causes abort
This will crash nvim 0.1.6 (and probably much older):

    :!cat build/bin/nvim
    src/nvim/ui.c:507: ui_cursor_left: Assertion `new_col >= 0` failed

This isn't a super important problem given that the "normal" behavior is to trash the terminal, but fixing it may lead to insight. Actually https://github.com/neovim/neovim/pull/4376 should fix it.

### PR DESCRIPTION
**Pull request by justinmk**
Closes #5442
Closes #4142
References #6618
References #4376

### CODE REVIEW

**Comment by justinmk** [comment]
@ZyX-I It looks like a crashed `nvim` now stops the tests. Is that intentional? or maybe it always worked like that?

**Comment by ZyX-I** [comment]
@justinmk Functional tests? In my experience it always worked like this, rather unexpected. I did not alter the behaviour nor tried to so far. Should have something to do with luv I think.

**Comment by ZyX-I** [comment]
I only changed how unit tests behave on crash.

**Comment by justinmk** [comment]
Still looks like `gcc-5 m32` build crashed, though this was rebased onto  #6618.

```
RUN      ][0m[0m shell command :! cat a binary file #4142: -- Output to stderr:
2017/05/10 22:31:45 ERROR 11073/open_log_file:127: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
2017/05/10 22:31:45 ERROR 11073/call_set_error:733: RPC: ch 1 was closed by the client
2017/05/10 22:32:03 ERROR 11552/open_log_file:127: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
2017/05/10 22:32:03 ERROR 11552/call_set_error:733: RPC: ch 1 was closed by the client
```

**Pull request merged**
