### PR TITLE
fix: build neovim 0.8 under Windows

### PR DESCRIPTION
**Pull request by Fuzzier**
There are several issues to build neovim 0.8 under Windows.

Version: NVIM v0.8.0-7
Build type: Release
Compilers: MSVC/cl 19.33.31630 x64, LLVM/clang-cl 15.0.2 x64
Windows: 10 21H2 19044.2006

Dependencies build command:
~~~{batch shell}
pushd neovim\cmake.deps
md Release
cmake -S. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
cmake --build Release
popd
~~~

Neovim build command:
~~~{batch shell}
pushd neovim
md Release
cmake -S. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DDEPS_PREFIX="cmake.deps/Release/usr"
cmake --build Release
popd
~~~

Note: cl can be used in replacement of clang-cl.

# Problem 1:
  Cannot build both static and share libraries for libvterm under Windows.
  The static and shared library would have the same name, thus there would be multiple rules to build the same target.

## Solution 1:
  Disable shared library for libvterm.

# Problem 2:
  msgpack requires a CXX compiler.
  When magpack is built with clang-cl under Windows, the CXX compiler defaults to clang (GNU-frontend), which conflicts with the C compiler clang-cl (MSVC-frontend). (edited)

## Solution 2:
  Add CXX compiler settings for msgpack.

# Problem 3:
  The build type is missing for libuv, thus libuv is always build for Debug type.

## Solution 3:
  Add build type for libuv.

# Problem 4:
  clang-cl complains about invalid type conversion from `HANDLE` to `intptr_t`.

## Solution 4:
  Add explicit type conversion.

### CODE REVIEW

**Comment by clason** [comment]
> Problem 2: msgpack requires a CXX compiler

I don't think that's true; we depend on `msgpack-c`, which is a pure C implementation.

**Comment by kylo252** [comment]
are you using Ninja or MSBuild as the build backend? because this will determine if `CMAKE_BUILD_TYPE` will get ignored or not

> Dependencies build command:
> 
> ```
> cmake -S. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
> ```

you could also control all of this from `CMakeUserPresets.json`, see https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#select-your-compilers

**Comment by Fuzzier** [comment]
> > Problem 2: msgpack requires a CXX compiler
> 
> I don't think that's true; we depend on `msgpack-c`, which is a pure C implementation.

msgpack actually contains a "test" directory, the source files are written in C++.
If CMAKE_CXX_COMPILER is not set, CMake will complain and fail.
Well, the problem is that CXX compiler defaults to clang (GNU-frontend), which is incompatible with clang-cl (MSVC-frontend).

msgpack build error

**Comment by clason** [comment]
> msgpack actually contains a "test" directory, the source files are written in C++.

I'm sorry; that's just not true. We are using https://github.com/msgpack/msgpack-c/tree/c_master

(Unless you meant the other way around: the _tests_ are in C++ and  the source files are written in C? But then you don't have to build the tests as part of building Neovim.)

**Comment by Fuzzier** [comment]
> are you using Ninja or MSBuild as the build backend? because this will determine if `CMAKE_BUILD_TYPE` will get ignored or not
> 
> > Dependencies build command:
> > ```
> > cmake -S. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
> > ```
> 
> you could also control all of this from `CMakeUserPresets.json`, see https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#select-your-compilers

I build neovim in a Windows batch shell:
1. Start "x64 Native Tools Command Prompt for VS 2022", which sets up necessary environment variables.
2. Run cmake.

Ninja is used as the build system by passing "-G Ninja" to cmake.

**Comment by Fuzzier** [comment]
> > msgpack actually contains a "test" directory, the source files are written in C++.
> 
> I'm sorry; that's just not true. We are using https://github.com/msgpack/msgpack-c/tree/c_master
> 
> (Unless you meant the other way around: the _tests_ are in C++ and the source files are written in C? But then you don't have to build the tests as part of building Neovim.)

Well, I believe the problem is that msgpack/CMakeLists.txt does not state the project is C-only.
You can see that in the following figure.

msgpack CMakeLists

However, msgpack cannot state that the it is C-only.

msgpack C and CXX

**Comment by Fuzzier** [comment]
> In any case, your change broke all _other_ builds.

Why specifying CMAKE_CXX_COMPILER for msgpack will break all other builds?

**Comment by dundargoc** [comment]
I tested only your first commit locally on Windows. The debug works as expected but on Release I get the following error:

```
failed (exit code 1120) with the following output:
   Creating library lib\nvim.lib and object lib\nvim.exp
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
```

The other errors are due to cmake expecting a C++ compiler but the value of `CMAKE_CXX_COMPILER` is empty. I'm not sure if the problem here is that we msgpack requires a C++ compiler.

**Comment by dundargoc** [comment]
I suggest you tackle one problem at a time, otherwise this could get messy very fast.

**Comment by Fuzzier** [comment]
> I tested only your first commit locally on Windows. The debug works as expected but on Release I get the following error:
> 
> ```
> failed (exit code 1120) with the following output:
>    Creating library lib\nvim.lib and object lib\nvim.exp
> LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
> LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
> ```
> 
> The other errors are due to cmake expecting a C++ compiler but the value of `CMAKE_CXX_COMPILER` is empty. I'm not entirely convinced if msgpack requires a C++ compiler.

It is problem 3: the build type is missing for libuv, thus libuv is always built for Debug type.
While all other libs are built for Release, libuv (uv_a.lib) is built for Debug.
However, Release uses msvcrt.lib, while Debug use msvcrtd.lib, which are inconsistent, and cannot be linked together.

**Comment by Fuzzier** [comment]
> I tested only your first commit locally on Windows. The debug works as expected but on Release I get the following error:
> 
> ```
> failed (exit code 1120) with the following output:
>    Creating library lib\nvim.lib and object lib\nvim.exp
> LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
> LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
> ```
> 
> The other errors are due to cmake expecting a C++ compiler but the value of `CMAKE_CXX_COMPILER` is empty. I'm not entirely convinced if msgpack requires a C++ compiler.

msgpack/CMakeLists.txt states "PROJECT (msgpack)", not "PROJECT (msgpack C)" (use only C language).
The reason is that, msgpack/CMakeListst.txt may include msgpack/test/CMakeListst.txt.
The latter requires CXX compiler to build.

Although in reality only C compiler is required to build msgpack itself, but the msgpack/CMakeLists.txt does not state that the project is C-only, thus CMake indeed examines both C and CXX compiler to configure msgpack.
If a CXX compiler is not specified explicitly, CMake will guess and stuff one.

**Comment by Fuzzier** [comment]
> You don't have to convince me, you have to convince the CI :)

Thanks, your suggestion is very kind.
I shall tackle one problem at a time, otherwise this could get messy very fast.

**Pull request closed without merging**
