### PR TITLE
doc: drop obsolete section from 'langnoremap' help

### PR DESCRIPTION
**Pull request by ghost**
see #3446, I guess I need to pass status checks

### CODE REVIEW

**Comment by justinmk** [comment]
:+1:

**Comment by Pyrohh** [comment]
I wonder what's going on with Travis, especially since I have `[ci skip]` in the commit msg.

**Comment by justinmk** [comment]
@Pyrohh We enabled the new GH feature that requires travis to pass before merge is allowed. What kind of problems are you having?

**Comment by Pyrohh** [comment]
> We enabled the new GH feature that requires travis to pass before merge is allowed

Oh yeah, I understand that. It's just that Travis has been saying `Waiting for status to be reported' ever since the PR was opened. Not sure if the issue is with Github or Travis; if this PR is being successfully parsed/run/whatever by Travis then it should have finished instantly (`[ci skip]` is used).

**Comment by justinmk** [comment]
@Pyrohh I wonder if `[ci skip]` is incompatible with the GH "require travis to pass" feature. I will commit it directly.

**Comment by Pyrohh** [comment]
> I wonder if [ci skip] is incompatible with the GH "require travis to pass" feature

Perhaps; next time I'll try without it.

> I will commit it directly.

thanks

**Pull request closed without merging**
