### PR TITLE
feat(lua): move compat module from runtime to test

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Review by clason — APPROVED** [review]

**Comment by justinmk** [comment]
What's the reason for this? In https://github.com/neovim/neovim/pull/22598 I was thinking we should probably add `table.pack` (Lua 5.2) since that seems preferable to adding a custom function?

**Comment by bfredl** [comment]
yes. also for tests. The lua interpreter used for running `busted` in functionaltests and unittests is now guaranteed to be the same as the one in nvim (since #22077 )

**Comment by justinmk** [comment]
> I thought we strictly only support Lua 5.1? Supporting other versions shouldn't be a goal as they contain too many breaking changes.

Supporting 5.2+ isn't a goal, but does it make sense to shim a few select 5.2+ APIs such as `table.pack` , instead of adding e.g. `vim.pack` ? This would reduce churn in the future if we ever decide to support 5.2 (e.g. if LuaJit supports a newer Lua version or adds things like `table.pack`).

**Comment by lewis6991** [comment]
>  if LuaJit supports a newer Lua version or adds things like table.pack

It does already infact with a build flag.

> but does it make sense to shim a few select 5.2+ APIs such as table.pack

Sure, we can add them back. They were only removed since they were undocumented, and used internally, and required `require`ing.

**Pull request merged**
