### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by janlazo** [comment]
vim-patch:8.1.0113: compiler warning for unused variable

**Comment by janlazo** [comment]
@teto Can you review?

**Comment by janlazo** [comment]
Ran out of easy v8.0.x patches to port (except the menu patches maybe?). Someone (besides me) has to step up and port the rest. Would be nice if v8.0.1300 and related patches are resolved.

**Comment by Joakker** [comment]
v8.0.1119: quitting a split terminal window kills the job
v8.0.1300: file permissions may end up wrong when writing
v8.0.1307: compiler warning for ignoring return value
v8.0.1459: cannot handle change of directory
v8.0.1460: missing file in patch
v8.0.1461: missing another file in patch

**Comment by janlazo** [comment]
@Joakker None of those patches are N/A. Posting N/A patches should be done on an automated, unmerged PR for version.c. There's isn't 1 atm because https://github.com/neovim/neovim/issues/13312 is not completed.

**Pull request merged**
