### PR TITLE
viml: Literal Dicts

### PR DESCRIPTION
**Pull request by tjdevries**
Adds literal dict support f or vim.

### CODE REVIEW

**Comment by tjdevries** [comment]
Relevant patches:

8.1.1692 https://github.com/vim/vim/commit/b8be54dcc517c9d57b62409945b7d4b90b6c3071

**Comment by tjdevries** [comment]
@janlazo or @erw7 thoughts on this? I probably should have done this via vim-path method, huh.... Wasn't really intending on making it resemble patches so closely, but it ended up being pretty simple.

I can just put the patches that are N/A in the final commit message, right?

**Comment by janlazo** [comment]
If patch 8.1.1722, https://github.com/vim/vim/commit/61343f0c44c8e71df04918d033e0a744c0b7f8aa, and similar patches are relevant, then patches for `vimscript-2` feature such as https://github.com/vim/vim/commit/558ca4ae55096f8763ab8515a304cda9c57f18a7 should be included so that Vimscript code that opt-in to Vim 8.1+ syntax don't break when used with neovim.

If `+popupwin` feature is N/A, then we should document that first and come up with a list of files to ignore so that contributors know which files to port going forward.

Changes for `src/testdir/test_listdict.vim` and most new-style tests that don't use screendumps should be included. `./scripts/vim-patch.sh` should be used even if only to setup the commit message.

It's fine to put N/A patches in the commit message as long as `./scripts/vim-patch.sh` can find them for the version.c PR.

**Comment by eyalk5** [comment]
Will it be merged soon? waiting for it.

**Comment by tjdevries** [comment]
I'm not sure what we're going to do. @janlazo brings up several good points that I had not seen yet, so I need to do some investigating perhaps? I don't have a ton of time for this at the moment, and I'm not sure exactly what our long term goals are for these kinds of vim syntax improvements will be.

**Comment by bfredl** [comment]
The vim _implemtation_ of +popupwin is definitely N/A, but we might want to polyfill the API eventually (based on tj code, of c).

**Comment by tjdevries** [comment]
Hey @janlazo so I don't think the scriptverison stuff applies yet to this -- so do you think this is OK to merge?

We will probably want to do some stuff later with `scriptversion` but I don't think it's this PR.

Perhaps the best method would be I delete this PR and re-make as a "vim-patch" PR?

**Comment by janlazo** [comment]
> Hey @janlazo so I don't think the scriptverison stuff applies yet to this -- so do you think this is OK to merge?
> 
> We will probably want to do some stuff later with `scriptversion` but I don't think it's this PR.
> 
> Perhaps the best method would be I delete this PR and re-make as a "vim-patch" PR?

Redoing this PR as a regular vim-patch PR would be best.

**Comment by tjdevries** [comment]
@janlazo OK, so I tried doing this today and I'm not sure what's happening but it is not working for me well -- I can look into it more later. Too frustrated to go again at the moment :laughing: 

The popup test stuff is all just formatting to change to using literal dicts, so it's all N/A for us (just formatting changes).

**Comment by janlazo** [comment]
It's ok. I'll see what I can do. I need these patches for tests in v8.2.x patches.

**Comment by janlazo** [comment]
`test_popupwin.vim` depends on the `+textprop` feature and screendump tests. No point in porting it without full `+textprop` support.

**Comment by janlazo** [comment]
Ported the same vim patches in https://github.com/neovim/neovim/pull/13064. I didn't add the lua tests.

**Comment by tjdevries** [comment]
Closed by #13064

**Pull request closed without merging**
