### PR TITLE
[WIP] Check/remove superfluous vpeekc_any: Issue #6503

### PR DESCRIPTION
**Pull request by acferreir4**
#6503

### CODE REVIEW

**Comment by acferreir4** [comment]
I'll clean this up and resubmit.

**Comment by KillTheMule** [comment]
Just for adde safety, you know you can just force-push to your branch after the cleanup? That's actually the preferred way :)

**Comment by acferreir4** [comment]
Thanks for the tip :) I'll mess with that tonight and get it all sorted out.

**Comment by dundargoc** [comment]
Closing as this PR is essentially empty and has had no activity in the last 5 years.

**Pull request closed without merging**
