### PR TITLE
Updated Raku runtime files

### LINKED ISSUE #14376: Perl6/Raku syntax file is very outdated
`neovim/runtime/syntax/perl6.vim` is very outdated, its last change was in 2013.
Since then, the upstream has moved from `vim-perl/vim-perl` to `Raku/vim-raku`.
The latest versions include support for new .raku{mod,doc,test} file extensions
and various bug fixes.
It would be a good idea to keep neovim/vim in sync with it.

### PR DESCRIPTION
**Pull request by demostanis**
Fixes #14376.

### CODE REVIEW

**Comment by demostanis** [comment]
ffs

**Comment by demostanis** [comment]
The reason the FreeBSD test failed seems unrelated to my changes.

**Comment by demostanis** [comment]
The OpenBSD test succeeds. Can anyone check if everything's fine?

**Comment by demostanis** [comment]
`aaa` commits were to trigger a rebuild

**Comment by demostanis** [comment]
All checks have passed :sunglasses:

**Comment by janlazo** [comment]
Runtime files must be ported via `vim-patch.sh` or via cherry-picked runtime commits from Vim, like https://github.com/neovim/neovim/pull/13835.

**Comment by mhinz** [comment]
Yup, we merge the runtime files from Vim. For getting a list of runtime patches that affect a certain file, use this:

```
./scripts/vim-patch.sh -l runtime/syntax/perl6.vim
```

This only lists one runtime patch, https://github.com/vim/vim/commit/2c7f8c574f1f8723d59adca3fec8fb89c41cf8c9, which confusingly does nothing else than bumping the headers. The actual perl6 syntax is not changed at all. So, you wouldn't gain much from it anyway.

Your best bet is to get newer runtime files in Vim first and then port that patch via `vim-patch.sh` to Nvim.

**Pull request closed without merging**
