### PR TITLE
vim-patch: runtime file updates

### PR DESCRIPTION
**Pull request by clason**
- vim-patch:c6d533b0ad56
- vim-patch:e34b51e95fd0
- vim-patch:b0d584d97ab6
- vim-patch:cdd934439d08
- vim-patch:118f8e9da39e
- vim-patch:6e93689bde73
- vim-patch:544b209a2d4b (empty commit; patch already applied earlier)
- vim-patch:e059fae10044
- vim-patch:3fc7a7e44abd
- vim-patch:2f25e40b1f54

### CODE REVIEW

**Comment by zeertzjq** [comment]
The content of the last two commits are reversed

**Comment by clason** [comment]
I just used vim-patch.sh; any idea what went wrong?

**Comment by zeertzjq** [comment]
You forgot to `git add` and `git commit --amend --no-edit`?

**Comment by clason** [comment]
Hmm, I thought I did these strictly in sequence, but can't be sure now.

**Review by seandewar — APPROVED** [review]
LGTM. I guess the empty commit can just be squashed (similar to an N/A patch).

**Review by zeertzjq — APPROVED** [review]

**Comment by seandewar** [comment]
Co-authored-by lines have to be the last lines in the squashed commit for it to work properly

**Comment by clason** [comment]
There's more coming, anyway!

**Pull request merged**
