### PR TITLE
[RFC] Update to libuv 1.3.0

### PR DESCRIPTION
**Pull request by ghost**
All tests pass for me, although I'm not sure if that means much in this context.

### CODE REVIEW

**Comment by fwalch** [comment]
You can set [`BUILD_NVIM_DEPS`](https://github.com/neovim/neovim/blob/c53852a244fd78bcf11e37ddc94e8a847e80062a/.travis.yml#L8) temporarily to force the build to use the updated libuv instead of the one from `neovim/deps`. If it passes, you can remove the commit from the PR so it doesn't get merged.

**Comment by Pyrohh** [comment]
I wasn't aware of that, will do.

**Comment by Pyrohh** [comment]
All tests passed except for CI_TARGET={clang-asan,gcc} for osx, although they're under 'Allowed Failures' so I'm not sure if it's an issue.

**Comment by Pyrohh** [comment]
Updated to 1.2.1 and rebased.

**Comment by Pyrohh** [comment]
Updated to 1.3.0 and rebased.

**Comment by aktau** [comment]
LGTM.

**Comment by justinmk** [comment]
I'll leave it up to @tarruda to merge this.

**Comment by fwalch** [comment]
Before merging, the second commit (`BUILD_NVIM_DEPS=true`) should be removed.

**Comment by tarruda** [comment]
> I'll leave it up to @tarruda to merge this.

:+1: will merge after the test

Though libuv should be safe to update since no more breaking API changes will happen.

**Comment by Pyrohh** [comment]
The tests look to be passing now, assuming you were referring to Travis.

**Comment by tarruda** [comment]
:+1: merged, thanks

**Comment by tarruda** [comment]
@Pyrohh could you also send a PR to homebrew/neovim updating the libuv sha1?

**Comment by Pyrohh** [comment]
Sure

**Comment by jszakmeister** [comment]
@Pyrohh You don't happen to have access to an OSX system, do you?  It looks like libuv 1.3.0 has broken Neovim on OSX. :-(

**Comment by jszakmeister** [comment]
FWIW, 1.2.0 appears to work fine, so perhaps we should pin it back to that for now?

**Comment by Pyrohh** [comment]
@jszakmeister I do not, just Linux. When you say broken build, are you referring to Travis? Or do you mean it compiles and there's some other issue. It's not my decision, but IMO we should ideally keep up with the libraries being used.

**Comment by jszakmeister** [comment]
> @jszakmeister I do not, just Linux. When you say broken build, are you referring to Travis?

I meant that introducing libuv 1.3.0 yielded bad behavior on OSX.

> It's not my decision, but IMO we should ideally keep up with the libraries being used.

I agree that we should keep up, but I see no reason to be bleeding edge. :-)

At the moment, anyone installing via Homebrew or building from master on OSX will get a busted Neovim that has all kinds of drawing issues. :-(

**Comment by tarruda** [comment]
@jszakmeister I dont have access to a computer right now, but if its confirmed that the bug is caused by 1.3.0 then we should revert it.

It would be a good idea to try and find which libuv commit caused the bug. Do you think you could do this?

**Comment by jszakmeister** [comment]
> @jszakmeister I dont have access to a computer right now, but if its confirmed that the bug is caused by 1.3.0 then we should revert it.

Okay, I'll do that shortly.

> It would be a good idea to try and find which libuv commit caused the bug. Do you think you could do this?

Already done in [#1914](https://github.com/neovim/neovim/issues/1914#issuecomment-72354519).  It's libuv/libuv@393c1c59a27591d705648919b2d7fb921cba37bc.  But as I said there, I'm not sure who is to blame: us for wrong expectations, or them for some sort of broken implementation.

**Comment by tarruda** [comment]
From a quick look at the commit, it doesn't seem like they could have broken anything, so its probably some wrong assumption we are making.

In any case we should revert this until the real problem is fixed

**Comment by jszakmeister** [comment]
> In any case we should revert this until the real problem is fixed

It's done.  Thanks for chiming in.

**Pull request closed without merging**
