### PR TITLE
Add loclist config option to lsp location_handler

### PR DESCRIPTION
**Pull request by RRethy**
Allows configuration like:

```lua
vim.lsp.handlers['textDocument/typeDefinition'] = vim.lsp.with(
    vim.lsp.handlers['textDocument/typeDefinition'], {
        loclist = true,
    }
)
vim.lsp.handlers['textDocument/declaration'] = vim.lsp.with(
    vim.lsp.handlers['textDocument/declaration'], {
        loclist = true,
    }
)
vim.lsp.handlers['textDocument/definition'] = vim.lsp.with(
    vim.lsp.handlers['textDocument/definition'], {
        loclist = true,
    }
)
vim.lsp.handlers['textDocument/implementation'] = vim.lsp.with(
    vim.lsp.handlers['textDocument/implementation'], {
        loclist = true,
    }
)
```

Then when there are multiple results, it'll go into the location list instead of the quickfix list.

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]

**Comment by RRethy** [comment]
Rebase and bumping so it doesn't get forgotten, @mjlbach. I saw [the discussion](https://github.com/neovim/neovim/pull/17475#discussion_r810688274) around a more unified interface, but I'm hoping this would be able to get merged before then and can be removed when that new interface comes to fruition.

**Comment by mjlbach** [comment]
I'm not sure how I feel about this PR, I generally think we should be opinionated about location list/quickfix list usage in handlers (and if user's disagree, override the handler instead of adding additional options), and that the current status quo is the correct decision (using the quickfix list). What is the motivation for using the location list?

**Comment by RRethy** [comment]
> I'm not sure how I feel about this PR, I generally think we should be opinionated about location list/quickfix list usage in handlers (and if user's disagree, override the handler instead of adding additional options), and that the current status quo is the correct decision (using the quickfix list). What is the motivation for using the location list?

I personally never use the quickfix list (my whole workflow is centered around the loclist), the location list being tied to the window and inherited during window splits provides a lot more flexibility in my workflow. I can can filter (via `:Lfilter ...`), search (`:lgrep`), or populate it with something else (e.g. `vim.lsp.implementations`), and I don't have to `:lolder` to recover the original list since I usually start the side-adventure with a `<c-w>v` or `<c-w>T`. Essentially, I use the location list like a tree and I move horizontally and vertically in the tree by jumping windows, whereas `:lolder` only lets me traverse up the tree one node at a time.

On top of this, the quickfix is global across tabs, which is pretty rarely the behaviour a person wants (assuming they using tabs as a collection of windows instead of tabs as buffers). I generally don't like having my list clobbered by a different tab.

> I generally think we should be opinionated about location list/quickfix list usage in handlers

The references handler already lets the user specify loclist which is the code I copy pasted in this PR. On top of this, it goes against every other command that's built-into Vim which loads things into the quickfix list, e.g. `:make`/`:helpgrep`/`:grep`/`:vimgrep`, they all provide an alternative `:lmake`/`:lhelpgrep`/`:lgrep`/`:lvimgrep` out of the box which make the location list a first class citizen.

> and if user's disagree, override the handler instead of adding additional options

Functionally I don't really see the difference here, forcing a user to copy-paste the handler code into their config feels like overkill for a small change.

**Comment by mjlbach** [comment]
> I can can filter (via :Lfilter ...), search (:lgrep), or populate it with something else (e.g. vim.lsp.implementations), and I don't have to :lolder to recover the original list since I usually start the side-adventure with a <c-w>v or <c-w>T.

I think all of these have quickfix equivalents? I don't think anything under the cfilter plugin is location list specific.

>  On top of this, the quickfix is global across tabs, which is pretty rarely the behaviour a person wants (assuming they using tabs as a collection of windows instead of tabs as buffers). I generally don't like having my list clobbered by a different tab.

Hmm, I would think this would be exactly what users would want. I would assume tabs are tied together based on project (at least, that is my workflow) and since most location handlers provide project level navigation (go-to references for example is rarely buffer specific, but provides a generic list of referred symbols at the project level) I would think tying this to the buffer would be extremely unintuitive.

> Functionally I don't really see the difference here, forcing a user to copy-paste the handler code into their config feels like overkill for a small change.

The main issue is that every option we add to any of the handlers essentially becomes an unbreakable contract, so I've always been resistant to expanding anything beyond the most basic default options in favor of allowing people to override the handler entirely.

Anyways @mfussenegger I am mostly neutral on this now, so you can feel free to merge if you think this is the right thing to do.

**Comment by RRethy** [comment]
One note of clarification.

> I can can filter (via :Lfilter ...), search (:lgrep), or populate it with something else (e.g. vim.lsp.implementations), and I don't have to :lolder to recover the original list since I usually start the side-adventure with a <c-w>v or <c-w>T.
> > I think all of these have quickfix equivalents? I don't think anything under the cfilter plugin is location list specific.

They aren't equivalent if they are preceded by a `<c-w>v` or `<c-w>T`, or anything that splits windows, since the loclist is copied and the old list is mangled by called to `:Lfilter`, `:lgrep`, etc. which was the point I was making.

**Comment by justinmk** [comment]
> I generally think we should be opinionated about location list/quickfix list usage in handlers (and if user's disagree, override the handler instead of adding additional options)

Agreed. If overriding the handler is burdensome we can improve that.

**Pull request closed without merging**
