### PR TITLE
ci(ubuntu): remove azure mirror

### PR DESCRIPTION
**Pull request by zeertzjq**
This mirror intermittently becomes slow, making CI hang.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Hmm, the same mirror now doesn't hang for two pushes on `master` branch, but still hangs for PRs. Is this just a coincidence or is there something else wrong?

**Comment by dundargoc** [comment]
How often does this happen/how big of a problem is this?

Could we maybe raise this issue upstream to https://github.com/actions/virtual-environments instead and let them handle it? I feel like they should be the ones to take care of this. And if they fix it everyone will benefit. If they don't want to fix it for some reason then I feel we can go ahead and merge this.

**Comment by zeertzjq** [comment]
There is already one: <https://github.com/actions/virtual-environments/issues/675>.

**Comment by dundargoc** [comment]
> We're going to close the issue, but feel free to open a new one if there are any similar issues in the future.

**Comment by zeertzjq** [comment]
> How often does this happen?

Look at how long the "Install apt packages" took in every retry attempt in <https://github.com/neovim/neovim/runs/5475639190?check_suite_focus=true> and <https://github.com/neovim/neovim/actions/runs/1955536240>.

**Comment by zeertzjq** [comment]
The mirror isn't slow now, so I'll convert this to draft.

**Pull request closed without merging**
