### PR TITLE
[RFC] :CheckHealth system call timeout

### PR DESCRIPTION
**Pull request by tweekmonster**
@wsdjeg Mentioned in Gitter that `:CheckHealth` was hanging and discovered it was due to the following system call in the Ruby check:

```
gem list -ra '^neovim$' 2>/dev/null
```

It turns out that `api.rubygems.org` is blocked in his country and `gem` wasn't timing out the request (he said it was taking up to 20 minutes).  He was able to resolve this by setting his gem source to http://gems.ruby-china.org/.

I figured it would be sane to have a 30 second timeout for system calls so the user isn't stuck without answers when they're trying to troubleshoot something.

### CODE REVIEW

**Comment by justinmk** [comment]
Good idea. Ideally we could use curl's `--connect-timeout` but it doesn't look like `gem list` has that ability.

**Comment by justinmk** [comment]
We probably don't want to muck around with trying to figure out the user's `gem` source, though.

**Comment by mhinz** [comment]
@tweekmonster I think the problem is the Great Firewall of China blocking all Amazon S3, indeed. Or, the way it is blocking it. No timeout happens, otherwise we could simply use `gem list -s https://gems.ruby-china.org`.

The official source suggests removing the default source for that reason: https://ruby.taobao.org

**Comment by tweekmonster** [comment]
> We probably don't want to muck around with trying to figure out the user's gem source, though.

Oh, I wasn't suggesting that we should.  I was pointing out that `gem` doesn't hang under normal conditions.  I'm concluding that if we set a connection timeout for `curl` or `python -c` in general, the same issue might occur if say `pypi.python.org` is blocked.

**Comment by tweekmonster** [comment]
> No timeout happens

Yeah this is the part that's confusing to me.  I'm not a networking guy, but I guess that means the GFW is keeping connections open indefinitely and not responding?

**Comment by wsdjeg** [comment]
hi @justinmk , I think the latest version number of host provider should build in neovim itselt, instead of get it info from webside. it will make checkhealth faster, and for each version of nvim, it has it own latest version of provider package.

for example, if I use neovim 0.1.4, it only support neovim-python 0.1.6, it does not support the latest version 0.1.10 in pip website. if I use neovim 0.1.4, I run CheckHealth, it should not suggest me to update neovim-python to 0.1.10.

**Comment by justinmk** [comment]
> if I use neovim 0.1.4, it only support neovim-python 0.1.6, it does not support the latest version 0.1.10 in pip website. if I use neovim 0.1.4, I run CheckHealth, it should not suggest me to update neovim-python to 0.1.10.

For that example, sure. But generally the clients (hosts) are backwards-compatible. And it is more important that 0.1.5 users, for example, are up-to-date. Otherwise we can't fix bugs without asking users to upgrade `nvim`.

**Comment by wsdjeg** [comment]
> But generally the clients (hosts) are backwards-compatible. 

nice, And I understand now. and sure it is better to  use latest version `nvim`.

**Comment by justinmk** [comment]
LGTM. In the future we can enhance `jobwait()` to avoid much of this code.

**Comment by tweekmonster** [comment]
> LGTM. In the future we can enhance jobwait() to avoid much of this code.

Thanks!  How about instead of tweaking `jobwait()`, tweak `system()` and `systemlist()` to accept an optional timeout?  My initial solution was to go with coreutils `timeout`, but it's not a portable option.

**Comment by justinmk** [comment]
We could go much further with jobwait(): 

- optional parameter which tells jobstart() to sink to "standard handlers" which will be returned by jobwait()
    - avoids needing to specify `on_stdout`, `on_stderr` just to get job results
- get results from many jobs (this is a powerful feature of jobwait(), it "converges" multiple jobs)

**Comment by tweekmonster** [comment]
> optional parameter which tells jobstart() to sink to "standard handlers" which will be returned by jobwait()

Return the standard handler, or returned as a dict with status, stdout, and stderr?

> get results from many jobs (this is a powerful feature of jobwait(), it "converges" multiple jobs)

Good point.  I didn't think about timing out multiple jobs.

In any case this conversation can be continued in a PR.  Thanks again!

**Pull request merged**
