### PR TITLE
refactor(api/marks)!: add opts param for feature extensibility

### PR DESCRIPTION
**Pull request by muniter**
In the future we might want to extend the concept of named marks and adding opts reduces the need of changing the function signature in the furute. The `:help api-contract` *"Functions introduced in the development (unreleased) version MAY CHANGE"*

This is a breaking change. From a sourcegraph public search nobody seems to be using them so far. [Link to the search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com.*+%28nvim_buf_set_mark%7Cnvim_get_mark%29&patternType=regexp)

### CODE REVIEW

**Review by gpanders — APPROVED** [review]

**Comment by muniter** [comment]
@gpanders mind re running CI to see if sourcehut passes, don't see why not. Don't want this to skip the next release.

**Comment by zeertzjq** [comment]
I think you can re-run by closing and reopening.

**Comment by gpanders** [comment]
Windows failures are caused by redefinition of macros, e.g. `TCP_INITIAL_RTO_PARAMETERS`. https://github.com/neovim/neovim/pull/16187 looks related? In any case, not a result of this PR.

**Comment by clason** [comment]
Yes, that's #16187

**Comment by gpanders** [comment]
Are lint failures just a result of recent uncrustification?

**Comment by muniter** [comment]
Yes, should be relate to uncrustify since lint was passing previous to the re run of CI.

**Pull request merged**
