### PR TITLE
doc

### PR DESCRIPTION
**Pull request by justinmk**
- document new Lua feature, `vim.loop` https://github.com/neovim/neovim/pull/10123

### CODE REVIEW

**Comment by bfredl** [comment]
Maybe we should document that the API in general is not safe to invoke in luv callbacks.

The following is a code golf crash, but every API that might invoke event processing (which easily can occur unexpectedly due to breakcheck and friends), should be avoided.
```
timer = vim.loop.new_timer()
timer:start(1000,0, function ()
  vim.api.nvim_command("sleep 100m")
end
)
```
I have some ideas how to fix this in the long term:

- only allow un-deferred API functions in raw luv callbacks. Also make most read-only API function calls undeferred plus some more ( a future `nvim_message` should be made async-safe, for instance)
- add a `vim.timer_start()` wrapper that wraps callbacks in `vim.schedule`, which is equivalent to vimL `timer_start()` (the sensible choice for most lua timer usecases)

**Comment by justinmk** [comment]
@bfredl so general advice for now is to wrap API calls in `vim.schedule()` ?

```
timer = vim.loop.new_timer()
timer:start(1000,0, function()
    vim.schedule(function() vim.api.nvim_command("sleep 100m")
  end
end
)
```

**Comment by justinmk** [comment]
> * add a `vim.timer_start()` wrapper that wraps callbacks in `vim.schedule`, which is equivalent to vimL `timer_start()` (the sensible choice for most lua timer usecases)

Would prefer to avoid more wrappers if possible. Guiding users to `vim.schedule()` seems fine.

**Comment by bfredl** [comment]
We should at least add a `vim.schedule_wrap` combinator or similar. So you can write

```
timer:start(1000, 0, vim.schedule_wrap(function()
   vim.api.nvim_command("...")
end)
```

This will avoid two levels of function nesting for 90% of timer usecases (and probably for a lot of the others). We should make it easy to do the correct thing.

**Pull request merged**
