### PR TITLE
Fix crash in msgpackparse function

### PR DESCRIPTION
**Pull request by ZyX-I**
Found by @justinmk and reported in https://github.com/neovim/neovim/pull/2506#issuecomment-141581440. Has nothing to do with #2506.

### CODE REVIEW

**Comment by ZyX-I** [comment]
@HiPhish I have added `exc_exec` function in this PR. You may cherry-pick the relevant commit, it will be remove on rebase after this PR is merged in any case. Also contains examples of tests with invalid arguments.

**Comment by ZyX-I** [comment]
Default failed due to indetermenism in the test:

```
18:53:55,988 INFO  - # test/functional/ui/screen_basic_spec.lua @ 554: Screen resize has minimum width/height values
18:53:55,988 INFO  - Warning: Screen changes have been received after the expected state was seen.
18:53:55,988 INFO  - This is probably due to an indeterminism in the test. Try adding
18:53:55,988 INFO  - `wait()` (or even a separate `screen:expect(...)`) at a point of possible
18:53:55,988 INFO  - indeterminism, typically in between a `feed()` or `execute()` which is non-
18:53:55,988 INFO  - synchronous, and a synchronous api call.
18:53:55,988 INFO  -
18:53:55,988 INFO  - Note that sometimes a `wait` can trigger redraws and consequently generate more
18:53:55,988 INFO  - indeterminism. If adding `wait` calls seems to increase the frequency of these
18:53:55,988 INFO  - messages, try removing every `wait` call in the test.
18:53:55,989 INFO  -
18:53:55,989 INFO  - If everything else fails, use Screen:redraw_debug to help investigate what is
18:53:55,989 INFO  - causing the problem.
18:53:55,989 INFO  -
18:53:55,989 INFO  - stack traceback:
18:53:55,989 INFO  -     ./test/functional/ui/screen.lua:271: in function 'wait'
18:53:55,989 INFO  -     ./test/functional/ui/screen.lua:220: in function 'expect'
18:53:55,989 INFO  -     test/functional/ui/screen_basic_spec.lua:556: in function <test/functional/ui/screen_basic_spec.lua:554>
18:53:55,989 INFO  -
18:53:55,989 INFO  - not ok 557 - Screen resize has minimum width/height values
18:53:55,989 INFO  - # test/functional/ui/screen_basic_spec.lua @ 554
18:53:55,989 INFO  - # Failure message: ./test/functional/ui/screen.lua:277: Row 1 didn't match.
18:53:55,989 INFO  - # Expected: "-- INS^ERT --"
18:53:55,989 INFO  - # Actual: "resize^ "
18:53:55,989 INFO  - # stack traceback:
18:53:55,989 INFO  - #     ./test/functional/ui/screen.lua:277: in function 'wait'
18:53:55,989 INFO  - #     ./test/functional/ui/screen.lua:220: in function 'expect'
18:53:55,989 INFO  - #     test/functional/ui/screen_basic_spec.lua:556: in function <test/functional/ui/screen_basic_spec.lua:554>
18:53:55,989 INFO  - # 
```

**Comment by tarruda** [comment]
> Default failed due to indetermenism in the test:

Yes, currently this is the reason "default" fails a lot(it fails when extra output is mixed with TAP). Until I manage to fix this indeterminism feel free to ignore any test errors caused by it. FWIW this is not critical bug, it is just some intermediate screen states nvim sends to the busted process under certain conditions(but in the end the screen should be as expected). This message is a trap @bfredl added to help catch wrong test assumptions.

**Comment by justinmk** [comment]
@tarruda we could skip that for non Travis builds.

**Comment by HiPhish** [comment]
@ZyX-I How do I cherry-pick that commit without fetching your entire fork?

**Comment by fwalch** [comment]
@HiPhish You could [fetch the pull request](https://help.github.com/articles/checking-out-pull-requests-locally):

```
$ git fetch upstream pull/3359/head
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9 (delta 5), reused 9 (delta 5), pack-reused 0
Unpacking objects: 100% (9/9), done.
From git://github.com/neovim/neovim
 * branch            refs/pull/3359/head -> FETCH_HEAD
 * [new ref]         refs/pull/3359/head -> refs/pull/upstream/3360
$ git cherry-pick FETCH_HEAD
```

**Comment by HiPhish** [comment]
@fwalch Thanks :)

**Comment by ZyX-I** [comment]
@fwalch @HiPhish *Not* FETCH_HEAD. This commit is the very first one *in DAG*, but the last one *when sorted by date*. So GH displays it last, but FETCH_HEAD will be commit fixing crash.

**Comment by HiPhish** [comment]
@ZyX-I OK, got it now.

**Pull request merged**
