### PR TITLE
[RFC] Rename UvProcess and uv_process_*

### PR DESCRIPTION
**Pull request by sethjackson**
In windows - libuv already defines a uv_process_close function causing
the build to fail due to duplicate definitions.

See: https://github.com/libuv/libuv/blob/v1.x/src/win/internal.h#L292

Cherry picked from #810.

### CODE REVIEW

**Comment by justinmk** [comment]
We should not have any functions (or files!) prefixed with `uv_`. This is a good reason why. @tarruda can we rename `uv_process.c`?

**Comment by sethjackson** [comment]
@justinmk yes I totally agree but wasn't sure if changing that was ok or not.

**Comment by justinmk** [comment]
We also have `UvProcess`. Why?

**Comment by tarruda** [comment]
> We should not have any functions (or files) prefixed with uv_. This is a good reason why. @tarruda can we rename uv_process.c?

I did this to classify process started and managed by libuv, but it was a bad choice due to name conflict. @sethjackson would you mind amending this PR to  rename the entire module/functions/type as suggested by @justinmk ?

@justinmk clearly need a new name, so how about we simply change everything to have a `libuv` prefix? It should be enough to avoid name conflicts in the future.

**Comment by justinmk** [comment]
:+1:

**Comment by justinmk** [comment]
Merged. Thanks @sethjackson and @equalsraf !

**Pull request closed without merging**
