### PR TITLE
treesitter: separate tree and parser

### PR DESCRIPTION
**Pull request by vigoux**
Together with @steelsojka we'll be doing a set of PRs preparing for the LanguageTree to be upstreamed.
This is the first one in the list, splitting the current implementation of the treesitter parsers in lua, to better match the API.

While this might sound silly, but it is needed for further improvements.

### CODE REVIEW

**Comment by vigoux** [comment]
Okay so, with these changes, we lose an property on the trees, that is they are not immutable anymore.
Furthermore, each call to `parser:parse()` is expected to change to old tree, which may not be what you want.
@bfredl what do you think of this mutability change ?

**Comment by bfredl** [comment]
@vigoux hmm, it is by design that `ts_tree_copy(tree)` is essentially cost-free (on top of a reparse that is), what is it what we gain by discarding immutability of trees (and by extension, all the nodes a tree contains)?

**Comment by vigoux** [comment]
I'd say it saves us some unnecessary memory, but I am not even that sure.

**Comment by bfredl** [comment]
but if another plugin explicitly references the old tree, it is because it _wants_ to use the old tree. memory pressure is the GC:s responsibility.

**Comment by vigoux** [comment]
Okay, the updated version guarantees imuttability for the tree returned by `parser:parse()` but not the internal tree.

**Comment by vigoux** [comment]
Weird failure on WIN32, @bfredl do you think it is related to treesitter ?

**Comment by bfredl** [comment]
@vigoux just curious, what is the followup PR that motivates this?

**Comment by vigoux** [comment]
It will be akin to https://github.com/neovim/neovim/pull/13207 but with some changes.

**Pull request merged**
