### PR TITLE
terminal: Fix potential invalid local 'scrollback'

### LINKED ISSUE #9588: 'scrollback' crash
If I open a terminal, nvim immediately crashes. I'm not sure how to get debug info that would be useful for figuring out what's going on.

This is a combination of a bug report and a note to self since I'm not really sure what's causing it. I know it has some relation to my config, since `nvim NORC` makes it disappear, and some relation to #9563, since previous commits did not have this issue. Weirdly, if I set the scrollback to 100,000 explicitly, nothing happens.

### PR DESCRIPTION
**Pull request by justinmk**
TermOpen autocmd may set local 'scrollback' to -1, this needs to be
adjusted as in on_scrollback_option_changed().

fixes #9588 (OOM, out of memory)

- [x] add tests

### CODE REVIEW

**Comment by alok** [comment]
Just checked this out and ran it, no luck.

**Comment by justinmk** [comment]
Do you have TermOpen autocmds?

    :au TermOpen

Can you use ELOG("%ld", ...) to print the value

**Comment by justinmk** [comment]
@alok 	 on Linux, can you please try this, it will tell us exactly where the OOM is happening (post the callstack found in `$NVIM_LOG_FILE`):

```diff
diff --git a/src/nvim/memory.c b/src/nvim/memory.c
index b49b521bc965..4a93fbb08a52 100644
--- a/src/nvim/memory.c
+++ b/src/nvim/memory.c
@@ -102,6 +102,7 @@ void *xmalloc(size_t size)
 {
   void *ret = try_malloc(size);
   if (!ret) {
+    LOG_CALLSTACK();
     mch_errmsg(e_outofmem);
     mch_errmsg("\n");
     preserve_exit();
```

**Comment by alok** [comment]
I messed up and forgot to rebuild the project before running the binary. Turns out that this PR does in fact appear to fix the problem. Sorry for the headache.

**Pull request merged**
