### PR TITLE
[RDY]vim-patch:7.4.1557

### PR DESCRIPTION
**Pull request by prollings**
Problem:    Windows cannot be identified.
Solution:   Add a unique window number to each window and functions to use it.

https://github.com/vim/vim/commit/86edef664efccbfe685906c854b9cdd04e56f2d5

### CODE REVIEW

**Comment by KillTheMule** [comment]
Please squash the commits :)

**Comment by prollings** [comment]
Haha... Uhh.. The opposite of squash has been achieved.

**Comment by KillTheMule** [comment]
Now it's missing `src/testdir/test_window_id.vim` and instead has an empty file `test_window_id.res`.

**Comment by ZyX-I** [comment]
Note for reviewers: rettv_list_alloc from eval.c does *not* return `int` OK or FAIL, it returns `list_T *`. Function signature has changed, this has not failed CI only because -Wconversion is not used for eval.c.

**Pull request merged**
