### PR TITLE
lsp: Add severity_limit for other diagnostics

### PR DESCRIPTION
**Pull request by tjdevries**
TODO:
- Add test
- Add docs
- Consider adding same param to each of the diagnostics stuff.

### CODE REVIEW

**Comment by tjdevries** [comment]
When I'm done, you can do this:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    virtual_text = {
      severity_limit = "Warning",
    },
  }
)
```

**Comment by mattsacks** [comment]
Closes https://github.com/neovim/neovim/pull/13528

**Comment by tjdevries** [comment]
Closes #13314

**Comment by tjdevries** [comment]
Ready for review

**Comment by mjlbach** [comment]
LGTM! Here's what it looks like in practice:

Screen Shot 2021-01-10 at 9 54 35 PM

My only comment would be, that we should probably do this for signs (as some people really don't like the info level warning).

**Review by mjlbach — APPROVED** [review]

**Comment by tjdevries** [comment]
Specific diagnostic combinations doesn't make sense, and people can override the handlers IMO.

I added the feature for signs and underline now, so each of them respects `severity_limit`.

**Pull request merged**
