### PR TITLE
[RFC] legacy test: migrate test 72

### PR DESCRIPTION
**Pull request by fbrosda**
As a contribution to #1286, here a port of the test 72.

### CODE REVIEW

**Comment by justinmk** [comment]
Awesome!

**Comment by tarruda** [comment]
LGTM

**Comment by tarruda** [comment]
:+1: merged, thanks

**Comment by justinmk** [comment]
@tarruda Since your merge script does a rebase anyways (thus changing the hash), can you modify it to avoid merge commits for single-commit PRs? [Here's](https://github.com/justinmk/config/blob/master/.bashrc#L234-L243) what I do:

```sh
ghrebase1() {
  GITHUB_PR=$1
  git fetch --all &&
    git checkout refs/pull/upstream/$GITHUB_PR &&
    git rebase upstream/master &&
    git commit --amend -m "$(git log -1 --pretty=format:"%B" \
      | sed -E "1 s/^(.*)\$/\\1 #$GITHUB_PR/g")" &&
    git l -n 5
}
```

**Comment by tarruda** [comment]
> @tarruda Since your merge script does a rebase anyways (thus changing the hash), can you modify it to avoid merge commits for single-commit PRs? Here's what I do (the PR number is appened to the first line):

:+1:

**Comment by Pyrohh** [comment]
It looks like this dumps `Xtestfile` into the root of the repository. I'm not familiar with where test files should go, so just putting it out there.

**Comment by tarruda** [comment]
> It looks like this dumps Xtestfile into the root of the repository. I'm not familiar with where test files should go, so just putting it out there.

Yes, there should be `os.remove` calls for all created files. I will push a fix

**Pull request closed without merging**
