### PR TITLE
treesitter: update build items

### PR DESCRIPTION
**Pull request by tjdevries**

### CODE REVIEW

**Comment by tjdevries** [comment]
(we will also have to update tree-sitter-c grammar)

**Comment by theHamsta** [comment]
we should also remove `queries/c/highlight.scm`. We do not bundle a parser and any mismatch in parser version will result in an error for the users (right now they would require this change: https://github.com/nvim-treesitter/nvim-treesitter/commit/866f39bb712985eb33b23159aabf33a3af5873ec).

**Comment by tjdevries** [comment]
Yeah, makes sense to me. Until we actually ship a grammar, I don't think we need to have it here.

**Comment by vigoux** [comment]
I don't agree with removing the c parser, as we use it for tests to test the new features we add to treesitter integration.

**Comment by stsewd** [comment]
> I don't agree with removing the c parser, as we use it for tests to test the new features we add to treesitter integration.

Then maybe just include it when testing? So isn't include in the runtime files by default.

**Comment by theHamsta** [comment]
Maybe give a warning before merging this. We need to merge be either a generate-from source marker or fork all parsers with the old ABI to avoid sad users.

**Comment by stsewd** [comment]
3 versions of ts have been released this week, I think we can wait a couple of days more before merging this and forking, just so things settle down :)

Screenshot_2021-03-05 tree-sitter-cli

**Comment by bfredl** [comment]
> we should also remove queries/c/highlight.scm.

>  don't agree with removing the c parser, as we use it for tests to test the new features we add to treesitter integration.

> Then maybe just include it when testing? So isn't include in the runtime files by default.

There are two different things. `queries/c/highlight.scm` can be removed. the tests have their own bundled queries (if `.scm` file loading should be tested, use `test/fixtures` as extra `&rtp` ) and end user is expected to use nvim-treesitter for now.  the parser (binary `.so`) shouldn't be removed.

**Comment by bfredl** [comment]
> 3 versions of ts have been released this week, I think we can wait a couple of days more before merging this and forking, just so things settle down :)

Tree-sitter releases new releases all of the time, there is nothing here to "settle down". the only reason 0.19.0+ vs -0.18 is controversial because it is an ABI breaking change which is much more rare. further bug fixes / optimizations can be merged after this without any controversy or discussion (as done countless times in the past) as long as they are not ABI-breaking in turn.

**Comment by maxbrunsfeld** [comment]
Just echoing what @bfredl said - subsequent changes to Tree-sitter (after 0.19) are planned to be backwards-compatible, similarly to how they usually were before 0.19. There were just a couple of longstanding problems that required a breaking change to fix.

**Comment by tjdevries** [comment]
Closing in favor of: #14076

**Pull request closed without merging**
