### PR TITLE
[RFC] tests: remove already converted legacy tests from makefile

### PR DESCRIPTION
**Pull request by lucc**
I can also squash the commits if that looks better.

(how can I put commit ids in commit messages so that github will turn them into links here?)

### CODE REVIEW

**Comment by justinmk** [comment]
Use the full SHA and github will link it.

**Comment by lucc** [comment]
But then the commit message will be unnecessary long if viewed on the command line. I could also use the PR numbers.

**Comment by lucc** [comment]
The PRs are #699,  #1328, #1420.

**Comment by Pyrohh** [comment]
One commit per test seems excessive. Maybe everything could be squashed and then, in the commit message, listed off like so:
```
- [test1] - [test1- shasum]
- [test2] - [test2-shasum]
...
```

**Comment by Pyrohh** [comment]
Thanks @lucc, merged. The only thing I changed was the `#1428` to `#1328` in the commit message (the former was something about homebrew).

**Comment by lucc** [comment]
thanks @Pyrohh that was a mix up of 1420 and 1228 :(

**Comment by Pyrohh** [comment]
Heh, it's fine. You have a ton of PRs, something like that was bound to happen eventually :D

**Pull request closed without merging**
