### PR TITLE
revert: "ci: run functionaltest-lua on drafts as well"

### PR DESCRIPTION
**Pull request by dundargoc**
This reverts commit a91a5c1880dcb7718aed4e19ff2757be0948e7d5.

### CODE REVIEW

**Comment by dundargoc** [comment]
Reasoning: I don't think this is the correct approach to save CI times.

**Comment by jamessan** [comment]
> Reasoning: I don't think this is the correct approach to save CI times.

The reasoning was to get _some_ feedback on draft PRs without running the whole suite.

If this is reverted, is the intention to run the whole suite on draft PRs?

**Comment by dundargoc** [comment]
> If this is reverted, is the intention to run the whole suite on draft PRs?

That wasn't my initial thought, but we could do that as well. I didn't really have long term goal in mind, it was mostly that I felt that the "end didn't justify the means" aka that the amount of code duplication was just too much for a small gain. Maybe I should've come with a counterproposal instead of a straight up revert?

I'm fine with closing this if this isn't the approach we want to take.

**Comment by dundargoc** [comment]
I just remembered, we're already running the full test suite twice on sourcehut (thanks Drew), even on drafts. I kinda feel that should be enough on drafts.

**Review by jamessan — APPROVED** [review]

**Pull request merged**
