### PR TITLE
[RFC] msg: don't output unprintable chars to screen

### LINKED ISSUE #7586: abort on file changed warning
- `nvim --version`:
```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
```

- Vim (version: ) behaves differently?
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642
```

- Operating system/version:
macOS 10.13.1

- Terminal name/version:
`$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
```
Open any file:
nvim -u NORC file

Write into the file from outside neovim:
echo anything >> file

Try to save file in neovim:
:w

It will warn you about file changes.
Do not press 'y' or 'n'.
Press CTRL+Z instead.
```

### Actual behaviour
It crashes with Abort Trap 6

### Expected behaviour
Not to crash.

### PR DESCRIPTION
**Pull request by bfredl**
fixes #7586 #8070

I will add a test also.

### CODE REVIEW

**Comment by justinmk** [comment]
@bfredl I was working on a test, maybe it saves you time: https://github.com/justinmk/neovim/commit/de38a2fee8fc21e54eb3874786dfb48536094c92

Note that I couldn't figure out how to dismiss the yes-no dialog at the end ...

**Comment by bfredl** [comment]
well, the dialog is dismissed by typing `y` or `n` :). Anyway, I added a screen test, to check that we infact echo printable chars to contrast.

**Comment by justinmk** [comment]
@jszakmeister Here's a case where the quickbuild bsd env completely failed to start.

```
04:50:11,821 INFO  - Checking step execute condition...
04:50:11,822 INFO  - Step execute condition satisfied, executing...
04:50:14,483 INFO  - Executing pre-execute action...
04:50:15,476 ERROR - Step 'master>buildall>build-node?testNode=freebsd-64' is failed: Failed to delete file '/usr/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps/build/src/luv-static-build'.
```

Any idea what's going on?

**Comment by jszakmeister** [comment]
@justinmk Yeah, that's my fault.  I had an update go awry on the host machine recently, so it unexpectedly rebooted without me shutting down the VMs cleanly.  Interestingly, despite the file system being journaled, the file system was in a goofy state and couldn't remove cruft leftover from the previous build, so the build failed.  Sorry for the trouble, but the file system should be clean now.  I kicked off another build for this PR.

**Pull request merged**
