### PR TITLE
docs: Use nvim-lspconfig plugin in lsp docs

### PR DESCRIPTION
**Pull request by rockerBOO**
Update documentation to use the renamed nvim-lspconfig. 

Noted on #12823

### CODE REVIEW

**Comment by teto** [comment]
you missed one occurence line 33 https://github.com/neovim/neovim/pull/12885/files#diff-c192318c8fe0210cd48038dad294c17cR33

**Comment by rockerBOO** [comment]
On 33, 
> Add nvim_lsp.xx.setup{…} to your vimrc,
is referencing the lua module name here, which remains as `nvim_lsp`.

https://github.com/neovim/nvim-lspconfig/tree/master/lua

**Comment by teto** [comment]
but the `See the nvim-lsp README for details.` should be `See the nvim-lspconfig` README for details.

**Comment by rockerBOO** [comment]
OHH! Sorry about that! Should be good now.

Thanks @teto !

**Comment by teto** [comment]
thanks for the PRs, these small errors adds up so it's important to correct them and polish the experience.

**Pull request merged**
