### PR TITLE
[RFC] Wildmenu support C-E and C-Y as popupmenu

### PR DESCRIPTION
**Pull request by Billy4195**
From #10693, add `cancel` and `apply` operations for the wildmenu in ex mode.

- [x] Implement operations
- [x] Add functional tests

### CODE REVIEW

**Comment by teto** [comment]
sorry I posted https://github.com/neovim/neovim/issues/10693#issuecomment-579816047 in the wrong window. If you look at the CI checks, you can see a red cross, i.e., some tests fail. If you click on details, you can have a better idea of the cause. I can't restart the job on appveyor so your best chance is to rebase and force push to trigger the CI again.

**Comment by justinmk** [comment]
this is much smaller than https://github.com/neovim/neovim/pull/11001 , which is good. I wonder if we need anything from there.

The appveyor/windows failure is unusual:

```
  [  FAILED  ] test/functional\lua\vim_spec.lua @ 449: lua stdlib vim.rpcrequest and vim.rpcnotify
  test/functional\lua\vim_spec.lua:521: Expected objects to be the same.
  Passed in:
  (table: 0x10b33948) { }
  Expected:
  (table: 0x1342a3b8) {
   *[1] = 3
    [2] = mpack.NIL }
  stack traceback:
  	test/functional\lua\vim_spec.lua:521: in function <test/functional\lua\vim_spec.lua:449>
```

I restarted it, since that test in `lua/vim_spec.lua` is fairly new and doesn't look related to this change.

**Comment by wsdjeg** [comment]
Doc about this two key bindings is missing.
--------------
wsdjeg

**Comment by teto** [comment]
Appveyor now passes.

As for the documentation the new shortcuts could be mentioned in the 'wildmenu' section of options.txt .
In general shouldn't we aim to have pum and wildmenu converge ? I would like to have lua completion in command line mode.

**Comment by Billy4195** [comment]
@justinmk Do you mean Adding Page Up/Down binding from the previous PR to this PR?

**Comment by teto** [comment]
@Billy4195 just mention this new feature in docs and I will merge.

**Comment by Billy4195** [comment]
@teto Sorry, I'm busy these days, I will update this PR next week.

**Comment by Billy4195** [comment]
@teto I add some description of this PR in the docs. Sorry for the late update.
Cause I'm kind of busy these days, I have no time to continue with the follow up to add Page Up/Down key bind. If someone is interested in feel free to take it.

**Comment by teto** [comment]
thanks

**Pull request merged**
