### PR TITLE
fix(terminal): do not trim whitespace that is actually in the terminal

### LINKED ISSUE #16234: Allow getting full current line and cursor position in terminal-mode.
### Feature already in Vim?

Yes.

### Description

The `nvim_get_current_line` and `nvim_win_get_cursor` does not contains suffix spaces of current line.
So in the below situation, the `nvim_win_get_cursor` will return 10. (I don't know the reason but it always returns -1 col value)

```
hrsh7th$ ls     |
```

_| is cursor_

### Vim API

vim has an APIs that is `term_getcursor` and `term_getline`.

### Use-case

I'm implementing completion plugin. I hope to implement terminal completion but it requires `current line` and `current cursor position` to realize.

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #16234

### CODE REVIEW

**Comment by zeertzjq** [comment]
All three tests fail if the changes are reverted:
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] test/functional/terminal/buffer_spec.lua @ 318: :terminal buffer where output has trailing space cursor can be placed on trailing space in Normal mode
test/functional/terminal/buffer_spec.lua:320: Row 2 did not match.
Expected:
  |tty ready                                         |
  |*aaa  ^ {2: }                                           |
  |                                                  |
  |                                                  |
  |                                                  |
  |                                                  |
  |                                                  |
Actual:
  |tty ready                                         |
  |*aa^a   {2: }                                           |
  |                                                  |
  |                                                  |
  |                                                  |
  |                                                  |
  |                                                  |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:595: in function '_wait'
	test/functional/ui/screen.lua:362: in function 'expect'
	test/functional/terminal/buffer_spec.lua:320: in function <test/functional/terminal/buffer_spec.lua:318>

[  ERROR   ] 2 errors, listed below:
[  ERROR   ] test/functional/terminal/buffer_spec.lua @ 314: :terminal buffer where output has trailing space nvim_get_current_line() includes trailing space
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(string) 'aaa'
Expected:
(string) 'aaa   '

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/buffer_spec.lua:315: in function <test/functional/terminal/buffer_spec.lua:314>

[  ERROR   ] test/functional/terminal/buffer_spec.lua @ 331: :terminal buffer where output has trailing space nvim_win_get_cursor() includes trailing space in Terminal and Normal mode
test/helpers.lua:73: Expected objects to be the same.
Passed in:
(table: 0x7f8d58180fe0) {
  [1] = 2
 *[2] = 2 }
Expected:
(table: 0x7f8d58096d50) {
  [1] = 2
 *[2] = 6 }

stack traceback:
	test/helpers.lua:73: in function 'eq'
	test/functional/terminal/buffer_spec.lua:332: in function <test/functional/terminal/buffer_spec.lua:331>


 1 FAILED TEST
 2 ERRORS
```

**Comment by hrsh7th** [comment]
Thank you! I will try it in my environment.

**Comment by zeertzjq** [comment]
Seems not working on Windows...

**Comment by hrsh7th** [comment]
I'm sorry I can't contribute because I don't understand C language.
I checked the operation, but it seems to behave strangely.

_google translated_

https://user-images.githubusercontent.com/629908/143252536-7d5301fd-3500-4cf6-8843-090cb8509a60.mp4

**Comment by zeertzjq** [comment]
Are you sure there isn't something else interfering?

**Comment by zeertzjq** [comment]
Changing `tty-test` to `shell-test` still fails, so this is not `tty-test`'s problem. It is indeed not working on Windows...

**Comment by hrsh7th** [comment]
Yes. I don't meet other problems. (it seems to have the `<BS>` and `<Left>` both have the same problem.

**Comment by zeertzjq** [comment]
@hrsh7th Does it work properly if you disable `'signcolumn'`?

**Comment by zeertzjq** [comment]
`nvim_win_get_cursor()` indeed has problem when `'signcolumn'` or `'number'` is present, even in non-whitespace characters. I'll fix that for non-whitespace characters in #16418.

**Comment by hrsh7th** [comment]
Oh. You are right. If I disabled the `signcolumn` and `number`, this problem does not occur.

**Comment by zeertzjq** [comment]
Hmm, I just tested this on Windows, and found out that this work in when running `cmd.exe` in Nvim's terminal, but doesn't work when running Nvim in Nvim's terminal.

**Comment by zeertzjq** [comment]
Looks like the tests still fail on Windows CI even if I use `cmd /c type con`.

**Comment by zeertzjq** [comment]
The Windows test failures seem to have disappeared after some dependency updates?

**Comment by zeertzjq** [comment]
Oh, probably because of the removal of winpty support.

**Review by justinmk — APPROVED** [review]

**Comment by zeertzjq** [comment]
I don't think there is anything that can be done here.

**Pull request merged**
