### PR TITLE
deps: update libuv

### PR DESCRIPTION
**Pull request by justinmk**
Notable changes in libuv since v1.12:

- 1.16.0
  - uv_os_getppid(): get parent PID
  - "win,tty: improve SIGWINCH support" (v1.15.0)
- 1.18.0
  - uv_os_getpid()
- 1.19.0
  - `uv_kill` pid 0 now means "current process group", like unix. https://github.com/libuv/libuv/commit/890eedaf59cea75faaa6a14b4248a472dcadb831 
- 1.20.0
  - unix,spawn: respect user stdio flags for new pipe https://github.com/libuv/libuv/commit/c409b3fcff51ea270724e4f43866764e65666095

## todo

- [x]  latest libuv [has `UV_OVERLAPPED_PIPE`](https://github.com/libuv/libuv/commit/62a0f763a7d1a5bbaa2670b9d2687ba183d2c528)  (see also #8462) so we can remove `libuv-overlapped.patch`
- [x] review https://github.com/libuv/libuv/issues/736
  - `fopen_noinh_readbin` looks OK. 
  - `fdopen` calls in `if_cscope.c` and `u_write_undo` may need to be revisited. 
- [x] review https://github.com/joyent/libuv/issues/1493
- [x] Upstream libuv now has a CMakeLists.txt so we can use that. #9182

## Future note

- luv added a [new dependency](https://github.com/luvit/luv/pull/279) on [lua-compat-5.3](https://github.com/keplerproject/lua-compat-5.3) which is annoying because now we need to write a `third-party/cmake/BuildLuaCompat53.cmake` script.

### CODE REVIEW

**Comment by justinmk** [comment]
```
[----------] Running tests from /home/travis/build/neovim/neovim/test/functional/provider/ruby_spec.lua
[ RUN      ] ruby feature test works: 5.77 ms OK
[ RUN      ] :ruby command evaluates ruby: ERR
./test/functional/helpers.lua:93: Key 'set_by_ruby' not found
stack traceback:
	./test/functional/helpers.lua:93: in function 'get_var'
	...ild/neovim/neovim/test/functional/provider/ruby_spec.lua:38: in function <...ild/neovim/neovim/test/functional/provider/ruby_spec.lua:36>
[ RUN      ] :ruby command supports nesting: 136.87 ms OK
[ RUN      ] :rubyfile command evaluates a ruby file: 136.21 ms OK
[ RUN      ] :rubydo command exposes the $_ variable for modifying lines: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by justinmk** [comment]
travis hang:

```
[ RUN      ] ShaDa support code is able to dump and restore jump list with different times (slow!): 
```

travis hang 2:

```
[ RUN      ] :sort alphabetical, skip past first 2 digits: 6.25 ms OK
```

**Comment by justinmk** [comment]
failed to link in macOS travis builds:

```
src/nvim/CMakeFiles/nvim.dir/viml/parser/parser.c.o src/nvim/CMakeFiles/nvim.dir/window.c.o  -o bin/nvim  /usr/local/opt/gettext/lib/libintl.dylib /usr/lib/libiconv.dylib /Users/travis/nvim-deps/usr/lib/libuv.a -lpthread -ldl -ldl /Users/travis/nvim-deps/usr/lib/libmsgpackc.a /Users/travis/nvim-deps/usr/lib/libvterm.a /Users/travis/nvim-deps/usr/lib/libtermkey.a /Users/travis/nvim-deps/usr/lib/libunibilium.a -lm -lutil /Users/travis/nvim-deps/usr/lib/libluajit-5.1.a /Users/travis/nvim-deps/usr/lib/libjemalloc.a && :

Undefined symbols for architecture x86_64:
  "_pthread_barrier_destroy", referenced from:
      _uv_barrier_destroy in libuv.a(libuv_la-thread.o)
  "_pthread_barrier_init", referenced from:
      _uv_barrier_init in libuv.a(libuv_la-thread.o)
  "_pthread_barrier_wait", referenced from:
      _uv_barrier_wait in libuv.a(libuv_la-thread.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

+ exit 1
```

wonder if this is because of https://github.com/neovim/neovim/pull/8365#issuecomment-386818401

cleared travis cache, restarted macOS builds.

**Comment by jamessan** [comment]
Since you're updating deps, it would be good to bump msgpack-c to 3.0.0.  Whenever we pick up gcc8, the current msgpack-c version will fail to build.

I've done a test build of Neovim against 3.0.0 in Debian (since I just uploaded 3.0.0) and everything worked fine.

**Comment by justinmk** [comment]
@jamessan Thanks for noting that, I was avoiding it because [this](https://github.com/msgpack/msgpack-c/releases) mentioned breaking changes.

**Comment by jamessan** [comment]
The only place we actually use the offset from `msgpack_unpack_next()` is in the ShaDa code, and it will have the intended effect of improving the accuracy of our error reporting.

https://github.com/neovim/neovim/blob/273d2cd5d5cfc7616c76d3531e9938750abcc05e/src/nvim/shada.c#L1968-L1969

**Comment by justinmk** [comment]
@jamessan appveyor build is timing out after updating msgpack, going to table that for now.

**Comment by jamessan** [comment]
> AppVeyor hang is correlated with libuv upgrade.

Maybe related to https://github.com/libuv/libuv/issues/1729?  @bfredl made some changes so nvim uses pipes on Windows, right?

**Comment by justinmk** [comment]
@jamessan Thanks for taking a look! I think that shouldn't be an issue since we have a PATCH_COMMAND which seems to be working if I'm reading the CMake logs on AppVeyor correctly.

**Comment by justinmk** [comment]
Targeting 0.3.1, this is too risky for 0.3.0.

**Comment by jamessan** [comment]
N.B., skip libuv 1.21.0 because they accidentally made an ABI incompatible change (fixed in 1.22.0).

**Comment by justinmk** [comment]
@neovim/core Note that `make distclean` is needed after merging this.

**Pull request merged**
