### PR TITLE
[WIP]vim-patch:8.1.1790

### PR DESCRIPTION
**Pull request by janlazo**
Build failed so I assume we're missing `mksession` patches. This will take a while.

### CODE REVIEW

**Comment by justinmk** [comment]
ASAN job:

```
[OLDTEST] Running test_mksession
Failed: F /tests/oldtests|test_mksession :: Nvim exited with non-zero code
-en travis_fold:start:-tests-oldtests-test-mksession
[0K
=================================================================
==25553==ERROR: AddressSanitizer: attempting double-free on 0x6020000458b0 in thread T0:
    #0 0x4fb892 in __interceptor_free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:124:3
    #1 0x10669a4 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:119:3
    #2 0x12c54e8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2306:5
    #3 0x12c4a0d in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
    #4 0x1069639 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:650:3
    #5 0x1378fc5 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
    #6 0xf4e141 in getout /home/travis/build/neovim/neovim/build/../src/nvim/main.c:675:3
    #7 0xc6ec67 in ex_quit_all /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:6148:5
    #8 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #9 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #10 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
    #11 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
    #12 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
    #13 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
    #14 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #15 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #16 0xbc5938 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
    #17 0xbc18a0 in cmd_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2970:14
    #18 0xbc1ff7 in ex_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2951:3
    #19 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #20 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #21 0xbe5713 in do_cmdline_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:270:10
    #22 0xf4b8d5 in exe_commands /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1680:5
    #23 0xf3964c in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:521:5
    #24 0x7f072076d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #25 0x453db8 in _start (/home/travis/build/neovim/neovim/build/bin/nvim+0x453db8)

0x6020000458b0 is located 0 bytes inside of 8-byte region [0x6020000458b0,0x6020000458b8)
freed by thread T0 here:
    #0 0x4fb892 in __interceptor_free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:124:3
    #1 0x10669a4 in xfree /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:119:3
    #2 0x12c54e8 in free_string_option /home/travis/build/neovim/neovim/build/../src/nvim/option.c:2306:5
    #3 0x12c4a0d in free_all_options /home/travis/build/neovim/neovim/build/../src/nvim/option.c:969:9
    #4 0x1069639 in free_all_mem /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:650:3
    #5 0x1378fc5 in mch_exit /home/travis/build/neovim/neovim/build/../src/nvim/os_unix.c:102:3
    #6 0xf4e141 in getout /home/travis/build/neovim/neovim/build/../src/nvim/main.c:675:3
    #7 0xc6ec67 in ex_quit_all /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:6148:5
    #8 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #9 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #10 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
    #11 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
    #12 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
    #13 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
    #14 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #15 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #16 0xbc5938 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
    #17 0xbc18a0 in cmd_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2970:14
    #18 0xbc1ff7 in ex_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2951:3
    #19 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #20 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #21 0xbe5713 in do_cmdline_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:270:10
    #22 0xf4b8d5 in exe_commands /home/travis/build/neovim/neovim/build/../src/nvim/main.c:1680:5
    #23 0xf3964c in main /home/travis/build/neovim/neovim/build/../src/nvim/main.c:521:5
    #24 0x7f072076d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

previously allocated by thread T0 here:
    #0 0x4fbc13 in malloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
    #1 0x1066684 in try_malloc /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:71:15
    #2 0x106684c in xmalloc /home/travis/build/neovim/neovim/build/../src/nvim/memory.c:105:15
    #3 0x12d76a4 in do_set /home/travis/build/neovim/neovim/build/../src/nvim/option.c:1670:24
    #4 0xc74559 in ex_set /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:9987:9
    #5 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #6 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #7 0xbc5938 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
    #8 0xbc18a0 in cmd_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2970:14
    #9 0xbc1ff7 in ex_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2951:3
    #10 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #11 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #12 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
    #13 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
    #14 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
    #15 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
    #16 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #17 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #18 0x8f7bcd in ex_execute /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:20876:7
    #19 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #20 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #21 0x8d8056 in call_user_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:22775:3
    #22 0x8a4a6d in call_func /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6521:11
    #23 0x8b7d67 in get_func_tv /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:6277:11
    #24 0x8b0c5e in ex_call /home/travis/build/neovim/neovim/build/../src/nvim/eval.c:2887:9
    #25 0xbfd309 in do_one_cmd /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:2247:5
    #26 0xbdf418 in do_cmdline /home/travis/build/neovim/neovim/build/../src/nvim/ex_docmd.c:593:20
    #27 0xbc5938 in do_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:3230:3
    #28 0xbc18a0 in cmd_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2970:14
    #29 0xbc1ff7 in ex_source /home/travis/build/neovim/neovim/build/../src/nvim/ex_cmds2.c:2951:3

SUMMARY: AddressSanitizer: double-free /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:124:3 in __interceptor_free
==25553==ABORTING
Failed: E /tests/oldtests|logs :: Runtime errors detected.
Job exited with code 1
```

**Comment by justinmk** [comment]
asan failure looks like what is fixed by https://github.com/neovim/neovim/pull/9163 ? Perhaps we should merge https://github.com/neovim/neovim/pull/9163 ( I was blocking it with the plan to look for other b:changedtick patches as you suggested)?

**Comment by blueyed** [comment]
Rebased it.

**Comment by justinmk** [comment]
still happening. On closer inspection, there is a difference: the trace in https://github.com/neovim/neovim/pull/9163 originates from allocation by `ex_bunload` (freed later in that same function), whereas this one allocates from `ex_source .. ex_set`  then frees in `free_all_options` ... and somehow frees _again_ in `free_all_options`.

**Comment by blueyed** [comment]
JFI: just `mkvimrc Xtestvimrc` and `source Xtestvimrc` triggers it.

It can be triggered by `source'ing a file with just `set viminfofile=NONE`.

**Comment by justinmk** [comment]
2e621553c089ca6b7de5123a9c63a7a54ee06c20 fixed a similar-looking bug, might as well rebase this to see if that helped.

**Comment by blueyed** [comment]
It's related to the test runner's `-i NONE` / `-i viminfo`.
Without those it passes (not all might be needed):

```diff
 src/nvim/testdir/Makefile    | 4 ++--
 src/nvim/testdir/runnvim.sh  | 2 +-
 src/nvim/testdir/runtest.vim | 5 +++--
 3 files changed, 6 insertions(+), 5 deletions(-)

diff --git i/src/nvim/testdir/Makefile w/src/nvim/testdir/Makefile
index 03b1bae28..c1fc9b030 100644
--- i/src/nvim/testdir/Makefile
+++ w/src/nvim/testdir/Makefile
@@ -103,7 +103,7 @@ NO_PLUGINS = --noplugin --headless
 # In vim, if the -u command line option is specified, compatible is turned on
 # and viminfo is not read. Unlike vim, neovim reads viminfo and requires the
 # -i command line option.
-NO_INITS = -U NONE -i NONE $(NO_PLUGINS)
+NO_INITS = -U NONE $(NO_PLUGINS)
 
 # TODO: find a way to avoid changing the distributed files.
 fixff:
@@ -114,7 +114,7 @@ fixff:
 
 RM_ON_RUN   := test.out X* viminfo
 RM_ON_START := test.ok
-RUN_VIM     := $(TOOL) $(NVIM_PRG) -u unix.vim -U NONE -i viminfo --headless --noplugin -s dotest.in
+RUN_VIM     := $(TOOL) $(NVIM_PRG) -u unix.vim -U NONE --headless --noplugin -s dotest.in
 
 CLEAN_FILES := *.out \
   *.failed          \
diff --git i/src/nvim/testdir/runnvim.sh w/src/nvim/testdir/runnvim.sh
index 249b89d04..522b940ac 100755
--- i/src/nvim/testdir/runnvim.sh
+++ w/src/nvim/testdir/runnvim.sh
@@ -30,7 +30,7 @@ main() {(
 
   export VIMRUNTIME="$root/runtime"
   if ! "$nvim_prg" \
-    -u NONE -i NONE \
+    -u NONE \
     --headless \
     --cmd 'set shortmess+=I noswapfile noundofile nomore' \
     -S runnvim.vim \
diff --git i/src/nvim/testdir/runtest.vim w/src/nvim/testdir/runtest.vim
index fa2574099..cef5671e1 100644
--- i/src/nvim/testdir/runtest.vim
+++ w/src/nvim/testdir/runtest.vim
@@ -49,7 +49,8 @@ source setup.vim
 
 " For consistency run all tests with 'nocompatible' set.
 " This also enables use of line continuation.
-set nocp viminfo+=nviminfo
+set nocp
+" viminfo+=nviminfo
 
 " Use utf-8 by default, instead of whatever the system default happens to be.
 " Individual tests can overrule this at the top of the file.
@@ -207,7 +208,7 @@ func FinishTesting()
   call AfterTheTest()
 
   " Don't write viminfo on exit.
-  set viminfo=
+  " set viminfo=
 
   " Clean up files created by setup.vim
   call delete('XfakeHOME', 'rf')
```

(I've seen the known ASAN on-exit issue then once)

**Comment by blueyed** [comment]
Rebased.

**Comment by blueyed** [comment]
Looks like viminfo/shada related settings being freed twice when `viminfo` get (re)set then maybe?

**Comment by blueyed** [comment]
The problem is that "viminfofile" is an alias for "shadafile": they both use the same memory (`.var=(char_u *)&p_shadafile`).
This should also affect (at least) "shada"/"viminfo" then.
This appears to be only a problem with `EXITFREE`, isn't it?
Should we skip those there explicitly, or have something like an "alias" flag?
Simply using `XFREE_CLEAR` within `free_string_option` did not fix it.

Another issue is that not both names should be written to the session file in the first place likely.
For compatibility it should be viminfo/viminfofile probably, but Vim would not be able to read a shada file then anyway - so should it use shada/shadafile then?

**Comment by blueyed** [comment]
Cherry-picked into https://github.com/neovim/neovim/pull/10850.

**Pull request closed without merging**
