### PR TITLE
feat: add link in issue template to minimal config template

### PR DESCRIPTION
**Pull request by lewis6991**
Link to https://github.com/neovim/neovim/wiki/Minimal-reproduction-template

### CODE REVIEW

**Comment by dundargoc** [comment]
Why is it yelling?

**Comment by lewis6991** [comment]
idk, to make it clear where the reported needs to add stuff.

**Comment by dundargoc** [comment]
It's not any more clear than a normal comment.

**Comment by clason** [comment]
Well, it does distinguish the instruction from the sample code in the next line...

**Comment by dundargoc** [comment]
Only because they were needlessly put next to each other.

Also the code doesn't seem to work.

**Review by dundargoc — APPROVED** [review]
I just dislike all caps. It doesn't natter how loud you are; some people just won't listen.

Other than that I wholeheartedly agree with this. We need more programmatically reproducible bugs.

**Pull request merged**
