### PR TITLE
[WIP] vim-patch:7.4.2201

### PR DESCRIPTION
**Pull request by cjlucas**
patch 7.4.2201
Problem:    The sign column disappears when the last sign is deleted.
Solution:   Add the 'signcolumn' option. (Christian Brabandt)

https://github.com/vim/vim/commit/95ec9d6a6ab3117d60ff638670a803d43974ba51

patch 7.4.2225
Problem:    Crash when placing a sign in a deleted buffer.
Solution:   Check for missing buffer name. (Dominique Pelle). Add a test.

https://github.com/vim/vim/commit/bfd096d02087a10e8e2f4bdfb74e0435506fa8bb

patch 7.4.2294
Problem:    Sign test fails on MS-Windows when using the distributed zip archives.
Solution:   Create dummy files instead of relying on files in the pixmaps directory.

https://github.com/vim/vim/commit/64cefedfc834aa4dac54ae5f91ccbc04e2d56bc5

### CODE REVIEW

**Comment by brcolow** [comment]
Thanks very much for porting a patch from vim upstream! I took a quick glance and mostly looks good, but you will want to fix the [lint issues](https://travis-ci.org/neovim/neovim/jobs/171705324).

**Comment by cjlucas** [comment]
Ah thanks, I figured there would be linting issues. Could you explain to me why I'm getting lint errors for `/*` style comments for my additions, but other `/*` comments pass lint?

**Comment by brcolow** [comment]
Ideally there should be no linting errors after porting the patch (i.e. make the necessary changes such as changing `TRUE` to `true`, `FALSE` to `false`, `/* */` to `//` etc.)

**Comment by Shougo** [comment]
I think below patches are also should be merged.

2225: sign delete buffer
2277: sign
2294: test_signs

**Comment by jamessan** [comment]
> Could you explain to me why I'm getting lint errors for /* style comments for my additions, but other /* comments pass lint?

Neovim uses a different coding style than Vim, but wholesale converting the code base would be too disruptive.  Instead, as changes are made to an area of the code, those changes should use the appropriate coding style.  Also, nearby lines are linted as well, so sometimes a change in one area cascades lint changes.

I wouldn't worry about the lint fixes until all of the functional changes are done.  Then you can simply do one commit fixing up the lint issues with a simple "lint" commit message.

**Comment by jamessan** [comment]
> I think below patches are also should be merged.

Without having looked at these patches, it is a good idea to group related upstream patches in a single PR.  If you run scripts/vim-patch.sh again in the same branch, it will setup the commit in same branch instead of creating a new one, to ease that process.

**Comment by cjlucas** [comment]
Sounds good. I'll work on adding the three additional patches.

**Comment by cjlucas** [comment]
Alright I think it's good to go. 7.4.2225 was significant as it fixes a segfault. I ported the vimscript test to lua. 7.4.2277 and 7.4.2294 don't apply, as both are fixing code that doesn't exist in neovim.

The linting required for 7.4.2225 was fairly significant. There was quite a bit of if/elseif/else statements without braces, so I'd appreciate a 2nd set of eyes to make sure I didn't miss anything.

I'm assuming the patch tracking system uses the commits created by `scripts/vim-patch` to track which patches have been migrated, so I kept the empty commits for patches that didn't apply.

**Comment by KillTheMule** [comment]
> Alright I think it's good to go. 7.4.2225 was significant as it fixes a segfault. I ported the vimscript test to lua. 7.4.2277 and 7.4.2294 don't apply, as both are fixing code that doesn't exist in neovim.

In that case you should modify `version.c` and put a comment `NA` there (just look at the file, you will easily see examples), that's how the script picks up that patches have been processed, but not applied.

**Comment by bfredl** [comment]
> I assume getbufinfo from 2277 has been absorbed into the remote API, but I could not find it. Ping @bfredl for confirmation, so we're sure that patch isn't needed in any form.

Well, a vim plugin relying on it will not work in nvim without it, so it won't be "absorbed" into the remote API even if it provides the same information.

**Comment by KillTheMule** [comment]
Ohhh I get it, we don't have that function because we did not yet port [7.4.2204](https://github.com/vim/vim/commit/b5ae48e9ffd3b8eb6ca4057de11f1bddcde8ce6f). So the same thing applies, don't mark 2277 as NA, just leave it out of your patchset, or add 2204 and apply 2277 appropriately.

**Comment by KillTheMule** [comment]
There are no `FEAT_*` definitions in  nvim (it's always compiled with all features), so you should remove [this](https://github.com/neovim/neovim/pull/5547/commits/2e8fd0527a4a8b523a08fcecd61d11310392c1c7#diff-bfacc6d8f849b9559c1c6cd5b79a5431R4760).

**Comment by cjlucas** [comment]
I'll leave out 2204/2277 out of this patchset, as it's not entirely related to 2201.

As for the test in 2294, is there a way to replicate this assert (https://github.com/vim/vim/commit/64cefedfc834aa4dac54ae5f91ccbc04e2d56bc5#diff-0337665a5c87f92b570e6894982f792cR151) in lua? I couldn't find any examples using "@:"

**Comment by KillTheMule** [comment]
Looking at it again I realized the following: Our `sign_spec.lua` is not a port of the oldstyle test `test_signs.in`. It was converted in vim to a newer style [here](https://github.com/vim/vim/commit/09de17536dd84e43aed7a575183e320e8d980b68), and we usually don't make an effort to convert newer style tests to lua.

So I'd suggest not making the effort of integrating the tests into `sign_spec.lua`, but port the patches for `test_signs.vim` to nvim (they'll be pretty trivial to do), and maybe add a comment in `sign_spec.lua` to clarify that it's a different test.

If that's getting too much out of hand for you, I'd say only porting 7.4.2201 also has a solid chance of being merged :)

Just one more thing: 7.4.2201 contains a test, added to `test_options.vim`. You should definitely include that when porting 7.4.2201.

**Comment by cjlucas** [comment]
It's not an issue of things getting out of hand. It's just not clear how mainline vim tests are migrated over to nvim. It seems that vimscript tests are not part of the nvim test suite, so I attempted to make a lua version of the test.

**Comment by KillTheMule** [comment]
> It's just not clear how mainline vim tests are migrated over to nvim

There are 2 types of tests in vim: Oldstyle, or legacy, tests (ending on `.in`), and newstyle tests (`.vim`). We do port the oldstyle tests to lua, which is mostly dones, the last remains can be seen [here](https://github.com/neovim/neovim/pulls/lucc). We don't port the newstyle tests, but just import them the way they are. Also, most neovim contributors seem to prefer to write new tests in lua (I certainly do).

Of course, as this example here shows, things can get weird if someone makes a test in neovim that is called like the conversion of an oldstyle test would be called, and then that oldstyle test gets converted to newstyle in vim itself, but the contents are changed... there's no bound on the confusion caused by the most simple operations. But we're here to help, let us know if something is still unclear :)

**Comment by KillTheMule** [comment]
> The linting required for 7.4.2225 was fairly significant.

I just remebered that line. In case you did not know, see [the wiki](https://github.com/neovim/neovim/wiki/Development-tips#code-linting) to cut down on the linting run time.

**Comment by jamessan** [comment]
I started working on the getbufinfo/gettabinfo/getwininfo patches.  Those are a bit intertwined with this PR, so I'll cherry-pick the commits that @cjlucas already did into that set of patches.

**Pull request closed without merging**
