### PR TITLE
[RFC] Make clint.py pep8-compliant.

### PR DESCRIPTION
**Pull request by elmart**
Make clint.py respect pep8 recommendations:
- Avoids lots of warnings if you use [pymode](https://github.com/klen/python-mode).
- It's good practice anyway.

Done mainly automatically using [autopep8](https://pypi.python.org/pypi/autopep8/).

### CODE REVIEW

**Comment by justinmk** [comment]
@elmart Feel free to merge it :)

**Comment by elmart** [comment]
Done, thanks.

**Comment by elmart** [comment]
@justinmk It seems my merge broke the build. Test 61 has failed. But Travis build passed on the PR... How come?? What should I do now?

**Comment by elmart** [comment]
I'm pretty sure that's nothing to do with my PR.
I think it's some of the tests on Travis builds for OSX are still brittle.
So, may I just restart the build on Travis?

**Comment by justinmk** [comment]
@elmart sure. Note you can restart the os x builds individually

**Comment by elmart** [comment]
Yes. I restarted the OSX-gcc job and that did it.
I suppose this was just the kind of thing that had to happen the first time... ;-)
Thanks.

**Pull request merged**
