### PR TITLE
[RFC] tui: Add support for true color terminals

### LINKED ISSUE #59: True Color support in both GUI and console application
See the support/patches for original VIm https://bitbucket.org/ZyX_I/vim/commits/branch/24-bit-xterm
Also, ncurses is not going to have support for that (thanks its author!).
And now it is supported by major part of terminal applications.
Here is the addition info about true colors:
Colors in terminal
==================
It's a common confusion about terminal colors... Actually we have this:
* plain ascii
* ansi escape codes (16 color codes with bold/italic and background)
* 256 color palette (216 colors+16gray + ansi) (colors are 24bit)
* 24bit true color (888 colors (aka 16 milion))

The 256 color palete is configured at start, and it's a 666 cube of
colors, each of them defined as a 24bit (888 rgb) color.

This means that current support can only display 256 different colors
in the terminal, while truecolor means that you can display 16 milion
different colors at the same time.

Truecolor escape codes doesnt uses a color palete. It just specifies the
color itself.

Here's a test case:
```
printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"
```
* or http://github.com/robertknight/konsole/tree/master/tests/color-spaces.pl
* or https://git.gnome.org/browse/vte/tree/perf/img.sh?h=vte-0-36

Keep in mind that it is possible to use both ';' and ':' as parameters delimiter.

According to Wikipedia[1], this is only supported by xterm and konsole.

[1] https://en.wikipedia.org/wiki/ANSI_color

Here are terminals discussions:
==============================

Now **supporting** truecolor
----------------------------

* [st](http://st.suckless.org/) (from suckless) [delimeter: semicolon] -  http://lists.suckless.org/dev/1307/16688.html
* [konsole](http://kde.org/applications/system/konsole/) [delimeter: colon, semicolon] - https://bugs.kde.org/show_bug.cgi?id=107487
* [iterm2](http://www.iterm2.com/) [delimeter: colon, semicolon] - only in the nighties https://code.google.com/p/iterm2/issues/detail?id=218
* [qterminal](https://github.com/qterminal/qterminal) [delimeter: semicolon] - https://github.com/qterminal/qterminal/issues/78
* [Tera Term](http://en.sourceforge.jp/projects/ttssh2/) [delimeter: colon, semicolon] - **Windows platform**
* [FinalTerm](http://finalterm.org/) [delimeter: semicolon]
* all [libvte](http://ftp.gnome.org/pub/GNOME/sources/vte/) based terminals (since 0.36 version) [delimeter: colon, semilocon] -  https://bugzilla.gnome.org/show_bug.cgi?id=704449
    * **libvte**-based [Gnome Terminal](https://help.gnome.org/users/gnome-terminal/stable/)
    * **libvte**-based [sakura](http://www.pleyades.net/david/projects/sakura)
    * **libvte**-based [Terminator](http://gnometerminator.blogspot.com/p/introduction.html)
    * **libvte**-based [Lilyterm](http://lilyterm.luna.com.tw/) - since commit https://github.com/Tetralet/LilyTerm/commit/72536e7ba448ad9ef1126ce45fbde3a3407a271b
    * **libvte**-based [ROXTerm](http://roxterm.sourceforge.net/)
    * **libvte**-based [evilvte](http://www.calno.com/evilvte/) - no release yet, version from git https://github.com/caleb-/evilvte
    * **libvte**-based [Termit](https://github.com/nonstop/termit)
    * **libvte**-based [Termite](https://github.com/thestinger/termite)
    * **libvte**-based [Tilda](https://github.com/lanoxx/tilda)
    * **libvte**-based [tinyterm](https://code.google.com/p/tinyterm)
    * **libvte**-based [lxterminal](http://sourceforge.net/projects/lxde) - with **--enable-gtk3** configure flag.

But there are bunch of libvte-based terminals for GTK2 so they are listed in the another section.

Parsing ANSI color sequences, but approximating them to 256 palette
-------------------------------------------------------------------

* xterm (though doing it wrong: "it uses nearest colour in RGB colour space, with a usualfalse assumption about orthogonal axes")
* [mlterm](https://sourceforge.net/projects/mlterm/) - http://sourceforge.net/mailarchive/message.php?msg_id=31828705

Note about colour differences: a) RGB axes are not orthogonal, so you cannot use sqrt(R^2+G^2+B^2) formula, b) for colour differences there is more correct (but much more complex) [CIEDE2000](http://en.wikipedia.org/wiki/Color_difference#CIEDE2000) formula (which may easily blow up performance if used blindly) [2].

[2] https://github.com/neovim/neovim/issues/793#issuecomment-48106948

**NOT supporting** truecolor
----------------------------

* [urxvt](http://software.schmorp.de/pkg/rxvt-unicode.html) -  http://lists.schmorp.de/pipermail/rxvt-unicode/2013q3/001826.html 
* [Terminlogy](https://www.enlightenment.org/p.php?p=about/terminology) (E17) - https://phab.enlightenment.org/T746
* [mrxvt](https://sourceforge.net/projects/materm) - https://sourceforge.net/p/materm/feature-requests/41/
* [aterm](http://www.afterstep.org/aterm.php) - https://sourceforge.net/p/aterm/feature-requests/23/
* [mintty](https://code.google.com/p/mintty/) (Cygwin and MSYS) - https://code.google.com/p/mintty/issues/detail?id=431
* [fbcon](https://www.kernel.org/doc/Documentation/fb/fbcon.txt) (from linux kernel) - https://bugzilla.kernel.org/show_bug.cgi?id=79551
* FreeBSD console - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=191652
* libvte and GTK2 - based:
     * **libvte**-based [GTKTerm2](http://gtkterm.feige.net/)
     * **libvte**-based [stjerm](https://github.com/stjerm/stjerm) - https://github.com/stjerm/stjerm/issues/39

Terminal multiplexers
---------------------

* [tmux](http://tmux.sourceforge.net/) (have workaround[3]) - https://sourceforge.net/p/tmux/tickets/140/ and https://www.mail-archive.com/tmux-users@lists.sourceforge.net/msg04720.html
* screen

[3] Currently you can use tmux_escape option as a workaround if you want true color in shell run under tmux. No true color in tmux statusline though.

Here are another console programs discussions:
============================================

Supporting True Color:

* irssi - https://github.com/irssi/irssi/pull/48

Not supporting True Color:

* mutt - http://dev.mutt.org/trac/ticket/3674
* mc - http://www.midnight-commander.org/ticket/3145#comment:1 - demo patches attached
* s-lang library - http://lists.jedsoft.org/lists/slang-users/2014/0000002.html
* ncurses library - https://lists.gnu.org/archive/html/bug-ncurses/2013-10/msg00007.html
* termbox library - https://github.com/nsf/termbox/issues/37
* mcabber - https://bitbucket.org/McKael/mcabber-crew/issue/126/support-for-true-color-16-millions-colors
* emacs - http://emacs.1067599.n5.nabble.com/RFC-Add-tty-True-Color-support-td299962.html
* vim - https://bitbucket.org/ZyX_I/vim/commits/branch/24-bit-xterm
* tig - https://github.com/jonas/tig/issues/227

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/1483710-true-color-support-in-both-gui-and-console-application?utm_campaign=plugin&utm_content=tracker%2F461131&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F461131&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tarruda**
This is enabled by setting the `$NVIM_TUI_ENABLE_TRUE_COLOR` environment variable, eg:

```
$ NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim
```

Close #59

### CODE REVIEW

**Comment by justinmk** [comment]
For anyone wondering, mintty does not support true color: https://code.google.com/p/mintty/issues/detail?id=431 

And here's a comprehensive list of true color support across terminals:

https://gist.github.com/XVilka/8346728

**Comment by rainerborene** [comment]
This means the current TUI supports `guifg` and `guibg` colors If I enable that environment variable?

**Comment by Pyrohh** [comment]
Is there any particular reason this is being done with an environment variable? I'm not a huge fan of adding *yet another* option, but it makes sense over an environment variable in this case IMO. The few env vars `nvim` does obey are for its initialization (e.g., `VIMINIT`), although I might be wrong on that.

**Comment by justinmk** [comment]
@Pyrohh Neither am I but we need some way to set the option per UI. E.g., ,one TUI may be running in a 16-color terminal, the other in 16-million, both connected to the same `nvim`.

Once we figure out a better approach, we can avoid many env vars currently floating around.

**Comment by Pyrohh** [comment]
@justinmk that's a good point, but I wonder if something like that could be auto detected instead.

**Comment by XVilka** [comment]
@justinmk In fact I've started to adding true color support in the mintty, but not finished yet (lacking free time hardly) https://github.com/XVilka/mintty/commits/master (see last 3 commits).

**Comment by tarruda** [comment]
@Pyrohh I don't like using environment variables either, but it is better than introduce coupling between the core and the UI. Later I will add support for UI-specific configuration through vimscript variables.

**Comment by justinmk** [comment]
@XVilka very cool. Thanks for maintaining that gist also!

**Comment by Pyrohh** [comment]
@tarruda I see, that certainly makes sense.

**Comment by ZyX-I** [comment]
@tarruda My 24-bit-xterm branch allows setting and removing true color support in the running Vim instance which is good should you add this to the vimrc and forget to add checks for terminal not supporting this. About VimL variables: how should this work given that there are no notifications for variable changes? Specifically for this case I would simply check variable on full redraw, but this is slightly worse then 24-bit-xterm variant where `set guicolors` *causes* full redraw.

**Comment by ZyX-I** [comment]
Also @tarruda has a valid concern which is not solved neither by VimL variables nor by options.

Except that if you have some identifier unique to each connected UI (e.g. position of UI in uis or `UI*` pointer address) you may make VimL variable a dictionary. You can’t do the same thing with options.

Thus I would suggest using

    let g:ui_truecolor={
        'default': 1,
    }
    if !empty($STY.$TMUX)
        let g:ui_truecolor[1]=0
    endif
    " Do the same thing on attaching new UI. But I don’t know how: `UI` struct has no “get_ui_env_var” and there seems to be no UIAttached event.

**Comment by tarruda** [comment]
@ZyX-I one way to enable a running instance is by setting `$NVIM_TUI_ENABLE_TRUECOLOR` and suspending/restoring nvim. In any case I think we do need a way to expose notifications about variable changes, which is not only useful for UI configuration but also for plugins in general

**Comment by Pyrohh** [comment]
@tarruda do you plan on documenting that variable? I'll send a PR for it if not.

**Comment by tarruda** [comment]
> @tarruda do you plan on documenting that variable? I'll send a PR for it if not.

I'd appreciate if you did. While your'e at it, could you also document `$NVIM_TUI_ENABLE_CURSOR_SHAPE`?

**Comment by Pyrohh** [comment]
Already on my to-do list :)

**Comment by woegjiub** [comment]
http://lists.schmorp.de/pipermail/rxvt-unicode/2013q3/001834.html

Rxvt-unicode refuses to support 'true colour', with the above explanation.
It has full support for 30-bit colour, just like xterm, and insists that there is a right way to do this, and that the 'true colour' standard is not it.

Is it worth attempting to use colour in that way, as opposed to this way?
For an example of use, w3m-img outputs full colour in terminals that support rxvt-unicode/xterm's way, which is apparently the earlier method.

**Comment by tarruda** [comment]
@woegjiub more than 24 bit colors is useless for Neovim since you cant specify the alpha component in color schemes.

I've seen that post and their argument is weak. It can be simplified as "Since terminfo exposes codes of changing the color palette, programs should use that(because its "portable") even though its much hackier and messier than simply specifying the RGB colors directly."

Terminfo is not reliable and does not support some new terminal features such as bracketed paste, thats why many terminals follow "xterm compliance" instead of being limited to what is available on terminfo.

**Comment by pacuna** [comment]
I'm trying this feature with the solarized scheme and works great, but when I open nvim, the colorscheme isn't being loaded. I have to set the colorscheme again, even if it's declared in my .nvimrc.
Is this an issue related to the colorscheme?

thanks!

**Comment by tarruda** [comment]
@pacuna I think this is related to how colorschemes are initialized using `has('gui_running')`(which is only set after the UI loads). What happens if you load the colorscheme using the `VimEnter` autocmd?

**Comment by pacuna** [comment]
@tarruda yeah that did the trick :D, thanks!!

**Pull request merged**
