### PR TITLE
Make sure window is still valid in the middle of calling :lopen

### LINKED ISSUE #13721: Crash on 'lopen' if curtain is a float and float is closed
- `nvim --version`:

```
ben@BenMBP neovim % ./build/bin/nvim --version
NVIM v0.5.0-dev+1013-g1ad867713
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/ben/Development/neovim/build/config -I/Users/ben/Development/neovim/src -I/Users/ben/Development/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/ben/Development/neovim/build/src/nvim/auto -I/Users/ben/Development/neovim/build/include
Compiled by ben@BenMBP.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
ben@BenMBP neovim %
```

- `vim -u DEFAULTS` (version: ) behaves differently? N/A, you can't focus a popup in Vim.
- Operating system/version: macOS Big Sur
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

`ben@BenMBP neovim % ./build/bin/nvim -u NORC -c 'source test_popup_lopen.vim'

```
let buf = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(
      \ buf,
      \ 0,
      \ -1,
      \ v:true,
      \ [ 'test' ] )

let opts = {
      \ 'relative': 'cursor',
      \ 'width': 18,
      \ 'height': 18,
      \ 'col': 0,
      \ 'row': 1,
      \ 'anchor': 'NW',
      \ 'style': 'minimal'
      \ }
let win = nvim_open_win(buf, 0, opts)

call win_gotoid( win )

augroup TEST
  autocmd!
  autocmd WinLeave * :call nvim_win_close(win, v:true) | autocmd! TEST
augroup END

call setloclist( 0, [] )
lopen

```

### Actual behaviour

```
zsh: segmentation fault  ./build/bin/nvim -u NORC -c 'source test_popup_lopen.vim'
                                                                                  %
ben@BenMBP neovim %
```

w_llist is NULL

Screenshot-2021-01-08-at-23 03 51

Screenshot-2021-01-08-at-23 04 44

### Expected behaviour

Not sure. It seems odd that you can even call `lopen` in a popup, but without the `autocmd`, it opens the location list for the previous window, so I guess that.

### PR DESCRIPTION
**Pull request by chentoast**
Fixes #13721.

Not sure what the expected behavior is when the window is closed while the location list is being opened. For me, there are probably two options that I would expect when running the repro script:

1. Leave the window that was supposed to be for the location list open, so we end up two windows.
2. Close the window meant for the location list, meaning that from the user's perspective, nothing happens.

I went with option 2 in this PR

### CODE REVIEW

**Comment by chentau** [comment]
Hi @teto , can I ask if you are available to review this PR? I'm trying to get the 0.5 issues closed as soon as I can.

**Comment by janlazo** [comment]
Vim doesn't do this so I suspect a missing (quickfix or window) vim patch or reverted vim patch like https://github.com/neovim/neovim/commit/dff3a0d , https://github.com/neovim/neovim/commit/7b2fd21.

**Comment by chentau** [comment]
Looks like the relevant patch is 8.1.0892

**Comment by janlazo** [comment]
I tried porting patch 8.1.0892 but ASAN build had test failures. I'm ok with this hotfix going into release 0.5 and then reverting it when porting 8.1.0892 in release 0.5.1

**Pull request closed without merging**
