### PR TITLE
fix: compiler warnings from clang 15

### PR DESCRIPTION
**Pull request by dundargoc**
Add -Wno-strict-prototypes flag to external dependencies to suppress
cjson warnings. These needs to be fixed upstream first.

### CODE REVIEW

**Comment by zeertzjq** [comment]
The digraph.c changes can be upstreamed to Vim.

**Comment by zeertzjq** [comment]
Can cjson be changed?

**Comment by dundargoc** [comment]
@justinmk @bfredl can we change the cjson files? If not should we disable all warnings from these files since there's no point in having unfixable warnings?

**Comment by justinmk** [comment]
cjson is an active upstream, we should send fixes upstream. https://github.com/neovim/neovim/blob/master/MAINTAIN.md

(Side note: I wonder if we could send enhancements upstream that would allow us to avoid the need to micro-fork it.)

**Comment by dundargoc** [comment]
https://github.com/openresty/lua-cjson/pull/85

**Comment by clason** [comment]
Did we upstream https://github.com/neovim/neovim/commit/4d2744ffe30c785ff19624831e36d01e3f6a6089?

**Comment by dundargoc** [comment]
No. Although a lot of that is just `char_u` Vimism that can't be upstreamed anyway.

**Comment by clason** [comment]
> (Side note: I wonder if we could send enhancements upstream that would allow us to avoid the need to micro-fork it.)

I don't think so; there were some necessary changes to make it work for our purposes:
https://github.com/neovim/neovim/pull/14871

(Upstream doesn't move a lot; but it may be worth a look at the handful of commits since we vendored it to see if any should be pulled.)

**Review by zeertzjq — APPROVED** [review]

**Comment by dundargoc** [comment]
> (Side note: I wonder if we could send enhancements upstream that would allow us to avoid the need to micro-fork it.)

Couldn't we use the dependencies as is and them patch them instead?

**Review by zeertzjq — APPROVED** [review]

**Pull request merged**
