### PR TITLE
#6611 - fixed 'compiler not supported: sbt' error

### PR DESCRIPTION
**Pull request by ghost**
Fix for https://github.com/neovim/neovim/issues/6611

### CODE REVIEW

**Comment by jamessan** [comment]
The proper fix would be to merge https://github.com/vim/vim/commit/64d8e25bf6e, but there are earlier runtime and source patches that should really be done first.

If we can't/don't want to do those before 0.2, then we should merge this for a quick fix.

**Comment by justinmk** [comment]
I'm in the process of runtime merges, starting with #6613

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6613 has the relevant patch.

@stevendobay thanks for the reminder to update runtime files before release :)

**Comment by stevendobay** [comment]
@justinmk you're welcome, thanks for the fix!

**Pull request closed without merging**
