### PR TITLE
ci: allow for skipping jobs via commit message

### PR DESCRIPTION
**Pull request by blueyed**
This allows for quick builds using `[only coverage]`.

### CODE REVIEW

**Comment by justinmk** [comment]
this is a lot of code and new concepts (JOB_GROUP...) to support a use-case that really shouldn't be very common. And the benefit AFAICT is only that it avoids having to comment-out parts of travis.yml--something that would be easier if we keep travis.yml simple.

**Comment by blueyed** [comment]
> And the benefit AFAICT is only that it avoids having to comment-out parts of travis.yml--something that would be easier if we keep travis.yml simple.

That would not be harder because of this - it's even more that having common properties factored out reduces the jobs list itself.
Also, I've once even accidentally merged a PR with commented out jobs - so there is always a risk there.
It also makes PRs more difficult to review, because of the temporary diff.

My goal here is for something like "[only coverage]" to be faster on CI for WIP pull requests.

But I get your arguments in general of course.

> Any minutes saved by this new feature will be lost if this new code causes someone to spend minutes/hours debugging a problem with it.

Agreed.  But when being used this saves a lot of time in general - it is much faster to iterate on PRs if there is just a single job on Travis and AppVeyor.

> CI in general should not be micro-managed. `[ci skip]` itself is questionable...

I agree in general, but it is also very bad having to wait on CI - and given the AppVeyor backlog that can be there this can be hours.  I see "[coverage only]" kind of as a compromise / fix for this here.
I've taken "coverage" since it also reports a status, but this could be something else.

With regard to a new concept of job groups: we could also have just something more simple (like on AppVeyor, probably with a different name, i.e. "[ci quick]").

**Comment by justinmk** [comment]
> My goal here is for something like "[only coverage]" to be faster on CI for WIP pull requests.

I don't see why coverage is so important. Especially for WIP,  knowing exact coverage every 10 minutes is not worth all the time being spent enhancing, and discussing, coverage tools.

**Comment by blueyed** [comment]
> I don't see why coverage is so important. Especially for WIP, knowing exact coverage every 10 minutes is not worth all the time being spent enhancing, and discussing, coverage tools.

This is not about coverage itself, rather that it is the best job to pick when only running a single one IMHO.

**Comment by justinmk** [comment]
Also editing travis.yml is not necessary, you can use the travis UI.

**Comment by blueyed** [comment]
> Also editing travis.yml is not necessary, you can use the travis UI.

By cancelling other jobs?

> And most other PRs won't micro manage CI, so this doesn't help the case of a queue.

Yeah.  I've hoped for it to make it easier for others also - I can understand that you do not want to add TEMP commits usually.

**Pull request closed without merging**
