### PR TITLE
[RFC] vim-patch:8.0.0449

### PR DESCRIPTION
**Pull request by ckelsel**
#### vim-patch:8.0.0449: part of fold patch accidentally included

Problem:    Part of fold patch accidentally included.
Solution:   Revert that part of the patch.
https://github.com/vim/vim/commit/abb4d5f73fd97d8f3c3e32311959929820e74b54

### CODE REVIEW

**Comment by justinmk** [comment]
No idea what to do with this. Does this mean we've included a patch already that should have been immediately reversed?

**Comment by chrisbra** [comment]
I think this was later fixed with https://github.com/vim/vim/releases/tag/v8.0.0457 (which mentions #6221, which I believe you have already merged and included). So I guess it is `N/A` for you.

**Comment by justinmk** [comment]
@ckelsel `make oldtest` is failing.

**Comment by ckelsel** [comment]
test_fold.vim

**Comment by justinmk** [comment]
@ckelsel Do you need help with this or just making notes?

**Comment by ckelsel** [comment]
@justinmk If I don't apply this patch, `TEST_FILE=test_fold.res make oldtest` will success. And I think this patch should be NA.

**Comment by justinmk** [comment]
yes, 8.0.0457 was already marked in b2b88423aa0087e5d4aaa122e63dffb97f85222f . Thanks.

**Pull request closed without merging**
