### PR TITLE
vim-patch:0378f07fbaee

### PR DESCRIPTION
**Pull request by clason**
runtime(colorschemes): Update colorschemes (vim/vim#13691)

Minor changes:

- Regenerated using colortemplate 2.2.3
- Removed reversed gui-cursor for some of the colorschemes (retrobox, wildcharm, lunaperche)
- Change MatchParen for some of colorschemes.

https://github.com/vim/vim/commit/0378f07fbaee9fd8773f3cf8cef146606dd7bf72

Co-authored-by: Maxim Kim <habamax@gmail.com>

### CODE REVIEW

**Review by zeertzjq — COMMENTED** [review]
Missing date and Colortemplate version updates

**Review by zeertzjq — APPROVED** [review]

**Review by zeertzjq — COMMENTED** [review]
Need to update `options.lua`

**Comment by clason** [comment]
Dangit, foiled again.

**Comment by clason** [comment]
Ah, sorry, pushed to the wrong PR.

**Review by zeertzjq — APPROVED** [review]

**Review by zeertzjq — APPROVED** [review]

**Pull request merged**
