### PR TITLE
defaults: set 'mouse' to 'a' by default.

### PR DESCRIPTION
**Pull request by fmoralesc**
Re: https://github.com/neovim/neovim/issues/2676

Also, some documentation changes.

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM. Merged

**Comment by fwalch** [comment]
This broke pasting with middle mouse button for me. Running `:set mouse=` fixes it again.

**Comment by fmoralesc** [comment]
The issue is it tries to use the `*` register for the paste, instead of `+`.

**Comment by fwalch** [comment]
Is the `*` register not what it *should* use? `CTRL-R *` pastes what I would expect from pressing the middle mouse button.

It does not seem to use any register, it just pastes a single `o` for each press. Both `*` and `+` have some text in them.

**Comment by fmoralesc** [comment]
Yes, absolutely. I don't know where that `o` is coming from... (I see that too)

**Comment by fmoralesc** [comment]
It's pasting from the unnamed register (`""`), in my tests.

**Comment by fmoralesc** [comment]
Using `clipboard=unnamed` seems to make it work as expected using `mouse=a`.

**Comment by fwalch** [comment]
In any case, it's a different behaviour than Vim (which pastes `*` even without `clipboard=unnamed`). I'll open an issue.

**Comment by rbjorklin** [comment]
This change is giving me some serious grief in having to `set mouse=` for every new vim installation because highlighting text no longer puts it in the paste-buffer. What's the recommended way of handling this? Pushing a `init.vim` file to all the servers I frequent?

**Comment by fmoralesc** [comment]
This change was recently reverted, you should be able to simply update your installs.

**Pull request closed without merging**
