### PR TITLE
clang/'Dead initialization': don't assign unused value to variable "string".

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by justinmk** [comment]
LGTM, why is it in draft?

**Comment by dundargoc** [comment]
It didn't pass all the tests the first time around, thought maybe I should rerun and pass all test before requesting a review. I've marked it as ready.

**Comment by clason** [comment]
Tests aren't run on draft PRs. You can re-trigger a test by force-pushing (or asking a maintainer).

**Comment by clason** [comment]
YOLO :)

(We normally use [conventional commits](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-messages) now, by the way -- this would qualify as `chore`, I guess.)

**Comment by dundargoc** [comment]
@clason ah OK, good to know. So instead of "clang/...", the commit message should be "chore(<file-name-with-change): ..."?

**Comment by clason** [comment]
maybe `chore(lint): clang/...` or `chore(clang): 'Dead...'`? If in doubt, ask in https://app.element.io/#/room/#nvim-dev:matrix.org :)

**Pull request merged**
