### PR TITLE
feat(lsp): conditionally send a work done progress token on initialize

### PR DESCRIPTION
**Pull request by rudiejd**
Problem:
https://github.com/neovim/neovim/issues/27938 we don't send a progress token on initialize

Solution:
Conditionally send a progress token if a flag is set. 

Apparently there's no harm in sending one, but since the LSP doesn't require one to be sent, I'm guessing disabling this feature might come in handy in case some servers aren't expecting it on initialize.

### CODE REVIEW

**Comment by clason** [comment]
In particular, the spec says:

> To keep the protocol backwards compatible servers are only allowed to use `window/workDoneProgress/create` request if the client signals corresponding support using the client capability `window.workDoneProgress` which is defined as follows: [...]

So we should make sure that we set this capability correctly, but otherwise expect servers to respect this correctly. We do _not_ add _any_ workarounds for misbehaving servers!

**Comment by mfussenegger** [comment]
Wouldn't it make more sense to have this changed in the server? If the client doesn't report a token, they can generate one.

I'd also rather not have a new flag/setting for this, but if we set the token on the client side it could limit servers in regards how they can group notifications. Without this, they could use many different tokens, with this, they'd have to assign the same token for all progress relevant for initialize.

For current neovim core that shouldn't be an issue because there is no display that groups the notifications, but it could affect plugins in some negative way.


---

> So we should make sure that we set this capability correctly

We do:

https://github.com/neovim/neovim/blob/dde2cc65fd2ac89ad88b19df08dc03cf1da50316/runtime/lua/vim/lsp/protocol.lua#L847

**Comment by rudiejd** [comment]
@mfussenegger I think the issue here is that, while the server can generate one, they're not required by the protocol to generate one. My interpretation is that the progress token can be generated on either side.

> I'd also rather not have a new flag/setting for this, but if we set the token on the client side it could limit servers in regards how they can group notifications. Without this, they could use many different tokens, with this, they'd have to assign the same token for all progress relevant for initialize.

yeah, that does seem like an argument in favor of a setting, albeit one that we default to true. I don't think you could avoid this by using a UUID either.

**Comment by mfussenegger** [comment]
> while the server can generate one, they're not required by the protocol to generate one. My interpretation is that the progress token can be generated on either side.

Yes, either side can. But a client _not_ sending the token isn't a opt-out of progress reports if the `workDoneProgress` capability is set to `true`, it just means the server can decide on the tokens.
And having a fallback on the server side to generate a token (or many) if the client request doesn't provide one, and if the capability is set shouldn't have any negative impact for other clients or servers.
This is afaik also what most other servers do.

**Comment by rudiejd** [comment]
>And having a fallback on the server side to generate a token (or many) if the client request doesn't provide one, and if the capability is set shouldn't have any negative impact for other clients or servers.
This is afaik also what most other servers do.

Maybe this is something that needs to be clarified with the spec. To me, it seems that it's unclear where the responsibility of creating the token lies

**Comment by mfussenegger** [comment]
ok re-reading the spec again, specifically these two parts:

Under client initiated:
> There is no specific client capability signaling whether a client will send a progress token per request. The reason for this is that this is in many clients not a static aspect and might even change for every request instance for the same request type. So the capability is signal on every request instance by the presence of a workDoneToken property.

Server initiated:
> Servers can also initiate progress reporting using the window/workDoneProgress/create request. This is useful if the server needs to report progress outside of a request (for example the server needs to re-index a database).


So I think it would be fine to just always set a token on initialize, without any configuration or flags. Servers can still initiate new progress reports that are independent of the request.

**Comment by mfussenegger** [comment]
Opened https://github.com/neovim/neovim/pull/28182

**Comment by rudiejd** [comment]
thank you! I'm on vacation this week

**Pull request closed without merging**
