### PR TITLE
feat: able to change popupmenu ordering(ie. word, kind, extra)

### PR DESCRIPTION
**Pull request by kiddos**
Hi,
I was wondering if we can do this.

https://github.com/neovim/neovim/assets/9444583/c524bba2-4545-48c3-bf16-6ed9db5a35af

Notice that the `kind` is now the first in the popup menu.

I want to be able to change the ordering of popup menu (`word`, `kind`, `extra`) in my way.

I added an option `pumordering` (default value `012`) to specify the ordering, but I'm not sure adding an option is the best choice here.

btw, this is the first PR to neovim (I'm ready to be roasted).

### CODE REVIEW

**Comment by clason** [comment]
Welcome! That's probably not the feedback you had hoped for, but in general such features are best PR'd to vim/vim first; if they accept it, we'll port the patch. This way, both projects profit, and we avoid divergence on such basic features that are shared by both editors (this is important for plugins that support both).

**Comment by kiddos** [comment]
agree. I'll do that first. Thanks.

**Comment by kiddos** [comment]
WIP: vim-[14006](https://github.com/vim/vim/pull/14006)

**Comment by glepnir** [comment]
emmm i have a plan to do it on our new api `nvim_complete` .  addding an option makes no sense to me。

**Comment by kiddos** [comment]
is there a link to that PR? feels like I need to make it work with that new `nvim_complete`.
yeah, adding an options seems weird to me too, but I'm not sure is there any better way to do it.

**Comment by glepnir** [comment]
There is no relevant PR yet. but has related issuse and my thought  is to use the VirtText structure to freely combine arrangement item and highlight.  I plan to do it  after completepopupop merged.

**Comment by kiddos** [comment]
completepopupop you are refering to this right? [25541](https://github.com/neovim/neovim/pull/25541). I kinda want that too. Seems like you want to extend that PR's implementation to make this work? (it would be very different from this PR)

**Comment by glepnir** [comment]
emm I mean i will implement the `nvim_complete` after that pr not in that pr :)

**Comment by kiddos** [comment]
We could keep this PR open for now, And when you start working on `nvim_complete`, what you want to do with this one. I think I will still try to push [14006](https://github.com/vim/vim/pull/14006) into vim. Is that cool for you?

**Comment by glepnir** [comment]
It's been cool always.  just that it overlaps with part of our plan :p

**Pull request closed without merging**
