### PR TITLE
[RFC] Fix some dead store clang-scan issues

### PR DESCRIPTION
**Pull request by sander2**
Hi there. We are students from Delft University of Technology, and we are doing a course project on Software Architecture, for which we need to analyse and contribute to an open source project in groups of four. Our group chose Neovim, and to start we fixed some low-hanging fruit: a few dead stores reported by clang-scan. Each commit contains a short explanation of the change made.

We have a couple of questions:
1. How much of the surrounding code are we supposed to update to the new style? We fixed every warning produced by clint around the code we touched.
2. Are there any tests for code we have changed, or do we have to add tests for changes we made? If so, can you point us to where these tests should go?
3. The fix made in the first commit is also found in upstream vim (https://github.com/vim/vim/blob/master/src/screen.c#L6732); what do we do with this?

### CODE REVIEW

**Comment by chrisbra** [comment]
how much of that does still apply to Vim?

**Comment by Hjdskes** [comment]
As noted, at least the first commit also applies vim. We'll have a look to see if the others do, too.

**Comment by chrisbra** [comment]
please check with the other commits and then please go ahead and file a separate issue on vim/vim then. Thanks.

**Comment by Hjdskes** [comment]
Sure, will do!

**Comment by Hjdskes** [comment]
The only other commit we are unsure about is 1a81ec6: it seems to imply that vim treats `%lp`, `%hp` and `%Lp` as `%p`. If this is indeed the correct behavior, then this commit does not apply to vim.

**Comment by Hjdskes** [comment]
04fb65f has now been [merged](https://github.com/vim/vim/commit/3457d295f4035293a78f9a9851ea416f923dd59e) by vim.

**Comment by justinmk** [comment]
@ZyX-I ok with https://github.com/neovim/neovim/commit/1a81ec6d8841e96ce01f25fd030f76851b00d895 ?

**Comment by justinmk** [comment]
@sander2 @Hjdskes Thanks for contributing.

> How much of the surrounding code are we supposed to update to the new style? We fixed every warning produced by clint around the code we touched.

The linter "cascades" to the next +/- 1 line, to encourage incremental update of the legacy style. If it turns into a lot of changes, just make a separate commit with the subject line: `lint`.

> Are there any tests for code we have changed, or do we have to add tests for changes we made? If so, can you point us to where these tests should go?

For testing see https://github.com/neovim/neovim/wiki/Unit-tests . In general the wiki and the built-in documentation are the authorities for most questions. Or try gitter.im/neovim/neovim .

> The fix made in the first commit is also found in upstream vim (https://github.com/vim/vim/blob/master/src/screen.c#L6732); what do we do with this?

You could mark the commit message body with `vim-patch:<sha>`, or just mention it in your pull request.

**Comment by justinmk** [comment]
Thanks! If you are looking for other work, try [complexity:low](https://github.com/neovim/neovim/issues?q=is%3Aopen+is%3Aissue+label%3Acomplexity%3Alow) or [complexity:medium](https://github.com/neovim/neovim/issues?q=is%3Aopen+is%3Aissue+label%3Acomplexity%3Amedium).

We've worked with students in the past and will try to find something that fits in your timeframe.

**Comment by Hjdskes** [comment]
Thanks for your tips, Justin! Regarding the time frame, the only requirement in our course is making a contribution before March 6. We've already done that, so the pressure is off :smile: It's great fun though, so we will certainly look at those issues and Coverity!

**Pull request merged**
