### PR TITLE
feat!(treesitter): do not return changes from LanguageTree:parse()

### PR DESCRIPTION
**Pull request by lewis6991**
Closes #19915

### CODE REVIEW

**Review by clason — APPROVED** [review]
Maybe enough to mention this in the Following HEAD issue?

(Unless we have already stopped using that completely?)

(and bang goes after scope in conventional commits...)

**Comment by lewis6991** [comment]
We need a bot to automatically comment on that issue when changes to news.txt happen.

**Comment by clason** [comment]
Or put it out of its misery, if we don't use it.

**Comment by justinmk** [comment]
Let's at least paste the explanation from https://github.com/neovim/neovim/pull/19915#issuecomment-1225246460 in the commit message

**Review by justinmk — APPROVED** [review]

**Comment by lewis6991** [comment]
Updated commit message, skipping CI.

**Pull request merged**
