### PR TITLE
OpenDyslexia.vim

### PR DESCRIPTION
**Pull request by jbennett-1**
We created a colorscheme that provides more readability for those with dyslexia since Neovim/vim do not contain such options. This colorscheme contains high-contrast colors and a darker background. The GUI interface of the colorscheme has font options such as OpenDyslexic and Verdana ; both fonts have character spacing and/or are commonly used by those with reading difficulties. We have tested this theme and had it reviewed in order to maintain its efficacy with both dyslexia and neovim/vim. Includes text files (runtime/colors/CONFIG.txt and config/init.vim) that gives instructions for use.

### CODE REVIEW

**Comment by clason** [comment]
Thank you for this making this effort to improve accessibility, which is appreciated. However:

1. We do not maintain (most) runtime files but take them verbatim from upstream -- so you should make the PR to https://github.com/vim/vim; if it gets accepted there, we will port it as part of the regular runtime file updates, and both projects profit!

2. You are making changes in unrelated files -- especially the `config/init.vim`! -- which is not acceptable.

**Comment by dundargoc** [comment]
@jbennett-1 for what it's worth I'm a fan of the colorscheme. You should definitely send it to vim :+1:

**Comment by jbennett-1** [comment]
ok, thank you!

**Comment by clason** [comment]
Yes, I believe gui font options have no place in a colorscheme.

And I'm serious: Please submit this (with these changes) to Vim; we'd be happy to include it this way.

**Comment by chrisbra** [comment]
You may want to contribute this to https://github.com/vim/colorschemes

**Comment by jbennett-1** [comment]
@chrisbra I'll submit a PR there as well, thanks for linking it!

**Pull request closed without merging**
