### PR TITLE
Replace hack used to run TermOpen with nested modifier

### PR DESCRIPTION
**Pull request by ZyX-I**
Also adds a test.

Ref #4306.
Ref #4362.

### CODE REVIEW

**Comment by justinmk** [comment]
Why is this better?

**Comment by ZyX-I** [comment]
@justinmk Try configuring color palette or scrollback buffer size from your autocmd. Also which side effects you were talking about exactly?

**Comment by ZyX-I** [comment]
@justinmk I have added a test which fails with your solution, but not with mine.

Generally `:doautocmd` should be avoided always because it runs in different context. Most likely you do not know what the difference is exactly because it requires good knowledge of the source code.

So *if there exists solution that avoids `:doautocmd` it <b>must</b> be preferred over `:doautocmd`*. Better to follow this rule then to dig C code seeking what you have lost.

**Comment by tarruda** [comment]
@justinmk regarding your previous [concern](https://github.com/neovim/neovim/pull/4306#issuecomment-189309941):

> main.c needs to be fixed, we shouldn't use BufReadCmd to implement internal functionality (unless we want users to have the option to delete that autocmd... hmm...)

The solution is to simply enhance our infrastructure to better support the concept of "internal vimscript": https://github.com/neovim/neovim/issues/4091#issuecomment-174346883. Here's a more detailed idea:

- Our build system collects all vimscript code in a certain directory in our source tree and generates a C file with a huge static string that contains all code.
- During `main()` this code is executed, and all vimscript constructs created during this phase(autocmds, commands, functions) get a special "undeletable" flag that wont allow users to delete them.
- As a bonus we can even enhance the definition of commands/functions  during this phase to allow creation of lowercase functions/commands(a sort of "privileged vimscript" mode)

**Comment by justinmk** [comment]
> get a special "undeletable" flag that wont allow users to delete them.

To be clear, I was suggesting that the ability to delete the autocmd may be considered a feature.

**Pull request merged**
