### PR TITLE
ci(api-docs): add comment explaining why full clone is needed

### PR DESCRIPTION
**Pull request by dundargoc**
This will save 15 seconds of CI time per commit. Such time saving!!!

### CODE REVIEW

**Comment by dundargoc** [comment]
This will save 15 seconds of CI time per commit. Such time saving!!!

**Review by justinmk — APPROVED** [review]

**Comment by jamessan** [comment]
Hmm, there was some reason I didn't do this in the first place, but not sure why now...

**Comment by dundargoc** [comment]
@jamessan good catch, I think I understand now. The `fetch-depth: 0` is needed to find when `check_only: false` since it needs to find the other brances (the regenerate docs auto-PR). In a normal pull request it's not needed. It is possible to work around this and save us a few seconds of CI time but it'll be at the cost of CI complexity, so probably not worth it.

Thanks for the input. I think I'll close this as I don't think it's worth it.

**Comment by dundargoc** [comment]
I realized I should leave a comment instead so that someone else doesn't get the same idea as me. I'll use this PR to do that.

**Pull request merged**
