### PR TITLE
build(windows): work around luarocks not finding its own md5sum

### PR DESCRIPTION
**Pull request by dundargoc**
Luarocks is unable to find its own md5sum due to these reasons listed in
the comment https://github.com/luarocks/luarocks/issues/1443.

The pull request https://github.com/luarocks/luarocks/pull/1498 resolves
this issue, but in the meantime we can work around it by resetting the
value of MD5sum to "md5sum".

### CODE REVIEW

**Comment by erw7** [comment]
Unfortunately, this change does not solve the problem. You must add `${DEPS_INSTALLDIR}/luarocks/tools` to your `PATH` when installing `mpack`.

**Comment by dundargoc** [comment]
Hmm, weird. It worked for me. Would you mind sending a PR with a workaround that works for you?

**Comment by erw7** [comment]
> Hmm, weird. It worked for me.

Probably because `md5sum.exe` is in your `PATH`. I have not heard of `md5sum.exe` being included in Windows as standard, is it included in Windows 11? I have confirmed the following procedure with `Version 10.0.19045.2728` at hand, but this change alone does not solve the problem.

```
set PATH=%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SystemRoot%\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
git clone https://github.com/neovim/neovim
cd /d neovim
cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build .deps --target mpack
```

> Would you mind sending a PR with a workaround that works for you?

The following patch solves the problem in the environment at hand, but I am not troubled by this problem, so I will not create a PR.

```diff
diff --git a/cmake.deps/cmake/BuildLuarocks.cmake b/cmake.deps/cmake/BuildLuarocks.cmake
index 9998f55fc..80ec5881e 100644
--- a/cmake.deps/cmake/BuildLuarocks.cmake
+++ b/cmake.deps/cmake/BuildLuarocks.cmake
@@ -102,8 +102,12 @@ endif()
 set(ROCKS_DIR ${DEPS_LIB_DIR}/luarocks/rocks-${LUA_VERSION})

 # mpack
+if (MSVC)
+  set(ENV{PATH} "${DEPS_INSTALL_DIR}/luarocks/tools;$ENV{PATH}")
+endif()
 add_custom_command(OUTPUT ${ROCKS_DIR}/mpack
-  COMMAND ${LUAROCKS_BINARY} build mpack 1.0.10-0 ${LUAROCKS_BUILDARGS}
+  COMMAND ${CMAKE_COMMAND} -E env "PATH=$ENV{PATH}"
+  ${LUAROCKS_BINARY} build mpack 1.0.10-0 ${LUAROCKS_BUILDARGS}
   DEPENDS luarocks)
 add_custom_target(mpack ALL DEPENDS ${ROCKS_DIR}/mpack)
```

**Comment by dundargoc** [comment]
> Probably because `md5sum.exe` is in your `PATH`.

Welp, this is embarrassing. It was in my `PATH` like you said.

> This change and the following patch solves the problem in the environment at hand, but I am not troubled by this problem, so I will not create a PR.

No worries. I'll test your suggestion later and create the PR. Thank you for the help!

**Pull request merged**
