### PR TITLE
robustness: avoid adding offset to NULL pointer

### LINKED ISSUE #12705: UBSAN with clang 10.0 fails (zero offset to null pointer, etc)
- `nvim --version`:

```
NVIM v0.5.0-82bfdbf
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -fsanitize=undefined -fsanitize-blacklist=/home/comicfans/neovim/src/.asan-blacklist -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -DEXITFREE -I/home/comicfans/neovim/build/config -I/home/comicfans/neovim/src -I/home/comicfans/neovim/.deps/usr/include -I/usr/include -I/home/comicfans/neovim/build/src/nvim/auto -I/home/comicfans/neovim/build/include
Compiled by comicfans@DESKTOP-35AEQ6R

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/comicfans/.local/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?  havn't tried
- Operating system/version: ubuntu 20.04.1 LTS
- Terminal name/version:
- `$TERM`: tmux

### Steps to reproduce using `nvim -u NORC`

just open nvim
```   
~/.local/bin/nvim -u NORC 
```

### Actual behaviour
```
../src/nvim/fold.c:1088:13: runtime error: applying zero offset to null pointer
                                                                               SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/nvim/fold.c:1088:13 in
```

backtrace shows:

```
0x00000000005039f0 in __ubsan::UndefinedBehaviorReport::UndefinedBehaviorReport(char const*, __ubsan::Location&, __sanitizer::InternalScopedString&) ()
#1  0x00000000004fe2e5 in __ubsan::Diag::~Diag() ()
#2  0x00000000005033be in handlePointerOverflowImpl(__ubsan::PointerOverflowData*, unsigned long, unsigned long, __ubsan::ReportOptions) ()
#3  0x000000000050341a in __ubsan_handle_pointer_overflow_abort ()
#4  0x0000000000e147a7 in foldFind (gap=0x626000000448, lnum=1, fpp=0x7fffffff3520) at ../src/nvim/fold.c:1088
#5  0x0000000000e209f9 in foldUpdate (wp=0x626000000100, top=1, bot=2147483647) at ../src/nvim/fold.c:793
#6  0x0000000000e13584 in checkupdate (wp=0x626000000100) at ../src/nvim/fold.c:1124
#7  0x0000000000e116c5 in hasFoldingWin (win=0x626000000100, lnum=1, firstp=0x0, lastp=0x0, cache=true, infop=0x0) at ../src/nvim/fold.c:176
#8  0x0000000001180cc1 in plines_win_full (wp=0x626000000100, lnum=1, nextp=0x0, foldedp=0x626000000414, cache=true) at ../src/nvim/misc1.c:500
#9  0x00000000011bccc1 in curs_rows (wp=0x626000000100) at ../src/nvim/move.c:600
#10 0x00000000011ae9d2 in curs_columns (may_scroll=1) at ../src/nvim/move.c:742
#11 0x00000000011ab9b3 in validate_cursor () at ../src/nvim/move.c:541
#12 0x0000000000bf404d in ex_listdo (eap=0x7fffffff5840) at ../src/nvim/ex_cmds2.c:2216
#13 0x0000000000c2e493 in do_one_cmd (cmdlinep=0x7fffffff7460, flags=7, cstack=0x7fffffff7480, fgetline=0xafd410 <get_func_line>, cookie=0x61d00000c880)
    at ../src/nvim/ex_docmd.c:2251
#14 0x0000000000c175e0 in do_cmdline (cmdline=0x0, fgetline=0xafd410 <get_func_line>, cookie=0x61d00000c880, flags=7) at ../src/nvim/ex_docmd.c:615
#15 0x0000000000af9cdd in call_user_func (fp=0x611000125100, argcount=1, argvars=0x7fffffffa3c0, rettv=0x7fffffffa8f0, firstline=1, lastline=1,
    selfdict=0x0) at ../src/nvim/eval/userfunc.c:1038
#16 0x0000000000af2dd2 in call_func (funcname=0x6020000599b0 "\200\375R13_VimEnter", len=14, rettv=0x7fffffffa8f0, argcount_in=1,
    argvars_in=0x7fffffffa3c0, argv_func=0x0, firstline=1, lastline=1, doesrange=0x7fffffffa910, evaluate=true, partial=0x0, selfdict_in=0x0)
    at ../src/nvim/eval/userfunc.c:1445
#17 0x0000000000aefdd7 in get_func_tv (name=0x6020000599b0 "\200\375R13_VimEnter", len=14, rettv=0x7fffffffa8f0, arg=0x7fffffffa8c0, firstline=1,
    lastline=1, doesrange=0x7fffffffa910, evaluate=1, partial=0x0, selfdict=0x0) at ../src/nvim/eval/userfunc.c:422
#18 0x0000000000b255b8 in ex_call (eap=0x7fffffffad40) at ../src/nvim/eval/userfunc.c:2857
#19 0x0000000000c2e493 in do_one_cmd (cmdlinep=0x7fffffffc960, flags=7, cstack=0x7fffffffc980, fgetline=0xe018a0 <getnextac>, cookie=0x7fffffffdbc0)
    at ../src/nvim/ex_docmd.c:2251
#20 0x0000000000c175e0 in do_cmdline (cmdline=0x0, fgetline=0xe018a0 <getnextac>, cookie=0x7fffffffdbc0, flags=7) at ../src/nvim/ex_docmd.c:615
#21 0x0000000000dff751 in apply_autocmds_group (event=EVENT_VIMENTER, fname=0x602000059970 "", fname_io=0x0, force=false, group=-3, buf=0x627000000100,
    eap=0x0) at ../src/nvim/fileio.c:6999
#22 0x0000000000dcaed4 in apply_autocmds (event=EVENT_VIMENTER, fname=0x0, fname_io=0x0, force=false, buf=0x627000000100) at ../src/nvim/fileio.c:6629
#23 0x0000000000f9bd77 in main (argc=3, argv=0x7fffffffe9f8) at ../src/nvim/main.c:517

```

fold.c:1088:  
```C
*fpp = fp + low;
```

fp :(fold_T *) 0x0
low: 0

### PR DESCRIPTION
**Pull request by bfredl**
UBSAN in clang 10.0 is checking for adding offsets to a `NULL` pointer which is not allowed. This is not yet checked in the version of clang used in CI (7.0.0). I will work on cases of this so that tests passes locally for me.

This could be tested in CI by either upgrading the clang of the ASAN/UBSAN to 10.0, or add yet another CI target which builds with
clang 10.0.

work towards fixing #12705

### CODE REVIEW

**Comment by bfredl** [comment]
Now all existing tests runs without UBSAN errors (some other failures though, but nothing that triggers UBSAN directly).

Some tree-sitter changes that should be upstreamed.

**Comment by teto** [comment]
I've been planning to add a nixos target on sr.ht. I may as well use clang 10 there.

**Comment by bfredl** [comment]
Sent tree-sitter changes to upstream https://github.com/tree-sitter/tree-sitter/pull/715

**Review by justinmk — APPROVED** [review]

**Comment by tjdevries** [comment]
I believe @vigoux added the script: `./scripts/update-ts-runtime.sh` to help with TS updates so that we can pull all the updates from their repo to us. Not sure if you want to do that rather than fixing them directly in this PR.

**Comment by bfredl** [comment]
that's cool, I will try it.

**Comment by justinmk** [comment]
the gcc-32bit failure on travis i think is unrelated, it bailed here, which IIRC is a known flaky failure:

> [ RUN      ] TextYankPost is executed after yank and-- Configuring done

**Comment by jamessan** [comment]
FWIW, I've submitted a [Vim PR](https://github.com/vim/vim/pull/6811) to have their CI run with both ASAN and UBSAN using Clang 11 (before it was just ASAN and using gcc).  Hopefully that will help get some of the common issues addressed.

I'll also wait to merge https://github.com/neovim/neovim/pull/12802 until we've cleaned up the sanitizer issues.

**Pull request merged**
