### PR TITLE
feat(cindent) Add new option cinscopedecls to customize cino-g

### PR DESCRIPTION
**Pull request by tom-anders**
When working with Qt, it always annoyed me a bit that `signals:` and `public slots:` messed up indentation.

I had a commit that fixed this for quite a while now (by just hard coding it into `cin_isscopedecl`), but I've now finally gotten around to making it fully configurable.

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but it would be better to open your PR at https://github.com/vim/vim -- Neovim is a fork, and if you contribute the change to Vim, both projects profit (as we would then port the patch in turn).

**Comment by tom-anders** [comment]
Will do, thanks!

**Comment by tom-anders** [comment]
For reference, vim PR is here: https://github.com/vim/vim/pull/10109

**Comment by tom-anders** [comment]
Feature already got merged in vim (wow that was quick), here's the port back to neovim: https://github.com/neovim/neovim/pull/18023

**Pull request closed without merging**
