### PR TITLE
fix(lsp): handle offset_encoding

### PR DESCRIPTION
**Pull request by black-desk**
@mjlbach

### CODE REVIEW

**Review by mfussenegger — CHANGES_REQUESTED** [review]
`get_line_byte_from_position` should already be called with the `offset_encoding` and not do an implicit lookup.

Can you explain in the commit message what this is fixing? 

This should probably also have a test

**Comment by black-desk** [comment]
https://github.com/black-desk/neovim/blob/4e4cb765131640c3c3721a46f85c1dfbf5ee0d57/runtime/lua/vim/lsp/util.lua#L1004

**Comment by mjlbach** [comment]
I agree with Mathias that it should not have a default offset encoding. Default offset encodings should only be supplied via buf utility functions, or param generating functions. an error can be thrown instead.

the apply_text_edit bug is being fixed in an overhaul of that function.

**Comment by black-desk** [comment]
> I agree with Mathias that it should not have a default offset encoding.

So what you mean is this line
https://github.com/neovim/neovim/blob/70fe3ce004f1c17328257349da5528757fdcd354/runtime/lua/vim/lsp/util.lua#L1003
should be changed to:
```lua
  local col = get_line_byte_from_position(bufnr, range.start, M._get_offset_encoding(bufnr))
```
correct?

> the apply_text_edit bug is being fixed in an overhaul of that function.

which pr?

**Comment by mjlbach** [comment]
This PR https://github.com/neovim/neovim/pull/17037 which was just merged, also see https://github.com/neovim/neovim/pull/17049 where I cleaned the rest up

**Comment by black-desk** [comment]
Thanks

**Pull request closed without merging**
