### PR TITLE
feat(lsp): implement workspace/didChangeWatchedFiles

### LINKED ISSUE #16078: LSP: Support workspace/didChangeWatchedFiles
### Feature already in Vim?

No

### Feature description

> The watched files notification is sent from the client to the server when the client detects changes to files and folders watched by the language client (note although the name suggest that only file events are sent it is about file system events which include folders as well). It is recommended that servers register for these file system events using the registration mechanism. In former implementations clients pushed file events without the server actively asking for it.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willRenameFiles

Used by omnisharp iirc, and maybe rust-analyzer.

Needs a filesystem watcher like libuv, watchman, chokidar...

### PR DESCRIPTION
**Pull request by nojnhuh**
Follow-up from #21293 to implement LSP `workspace/didChangeWatchedFiles`, hopefully without making neovim freeze this time.

Currently there are no changes beyond the original PR so that context will still be available here. I'll mark this PR ready for review once I've pushed some changes I feel reasonably confident about.

Resolves #16078

fyi @mfussenegger

### CODE REVIEW

**Comment by nojnhuh** [comment]
From https://github.com/neovim/neovim/pull/21293#issuecomment-1445160916:

> > For some language server you get one watcher registration per sub-folder.
> 
> @mfussenegger To clarify, in that case are the sub-folders defined in the watchers' `globPattern`s so they all share the same `baseUri`? If that's the case then I can see if we can consolidate to one `vim._watch.watch/poll` per root directory that's shared between the `watchers` in the registration.

Just pushed this change.

**Comment by mfussenegger** [comment]
It's a lot better but there are still periodic cpu spikes which are kinda noticeable. I suspect due to the polling on Linux instead of using inotify.  What were the reasons again you didn't use the M.watch path on Linux too?

**Comment by nojnhuh** [comment]
Not sure I remember all the details, but I think the main issue I was running into with making uv_fs_event_t recursive on Linux was getting a watch to end itself when the watched path gets deleted. Since [libuv sets both the `IN_DELETE` and  `IN_DELETE_SELF` flags](https://github.com/libuv/libuv/blob/e613fdd83cb1fb448ac0ebace7ade055d0068829/src/unix/linux.c#L1530-L1531), then when a subdirectory gets deleted, that event comes through to both the subdirectory's watcher and its direct parent's. And on the subdirectory's watcher (where we'd likely have easier access to its watch handle), the callback was invoked with a `filename` matching the subdirectory name, so the usual `{watch path}/{filename}` way to construct the full path was incorrect since it would have the subdirectory name at the end twice (I think because of the libuv code [here](https://github.com/libuv/libuv/blob/e613fdd83cb1fb448ac0ebace7ade055d0068829/src/unix/linux.c#L1468-L1472)). I don't think there's an obvious workaround for that issue though since it would be perfectly valid to have a directory at e.g. `/dir/subdir/subdir`.

I maybe could have done some more digging to try to compensate for that, but it must've been shortly after that I saw Node.js implement recursive watching on Linux with uv_fs_poll_t, so I took that as a sign there might be other issues with uv_fs_event_t I hadn't seen yet.

**Comment by gpanders** [comment]
Forgive the drive by comment, but any reason not to use `vim.watch` and `vim.poll` instead of `vim._watch.watch` and `vim._watch.poll`? Are these not intended to be used more generally by plugins?

**Comment by mfussenegger** [comment]
> Are these not intended to be used more generally by plugins?

Currently not. They're marked private to avoid discussion around their API as part of this PR. We can promote them to top level and expose them later once/if we're happy with their interface and how they work.


> I think the main issue I was running into with making uv_fs_event_t recursive on Linux was getting a watch to end itself when the watched path gets deleted. 

I see. I'll have another closer look to get a better picture of where the CPU spikes I'm seeing are coming from and see if there's some low hanging fruit to mitigate them.

**Comment by teto** [comment]
considering the criticality of the feature, shouldn't we make it (temporarily ?) opt-in as we work out the different issues ? this way we can merge and let powerusers test it without  impacting others. LSP servers can behave pretty differently when filewatching is enabled (thinking about you haskell-language-server) so documenting how to enable/disable it should prove useful.

**Comment by mfussenegger** [comment]
> considering the criticality of the feature, shouldn't we make it (temporarily ?) opt-in as we work out the different issues ? this way we can merge and let powerusers test it without impacting others. LSP servers can behave pretty differently when filewatching is enabled (thinking about you haskell-language-server) so documenting how to enable/disable it should prove useful.

Good point. Maybe we can set `didChangeWatchedFiles = { dynamicRegistration = false }` for now. Then to opt-in one must override the capability. Once we think it's working good enough we can then swap the default.

**Comment by nojnhuh** [comment]
> Good point. Maybe we can set `didChangeWatchedFiles = { dynamicRegistration = false }` for now. Then to opt-in one must override the capability. Once we think it's working good enough we can then swap the default.

Just pushed this change. I added a note about this being disabled by default to the news.txt entry, but please let me know if there's a better place for that.

**Comment by teto** [comment]
yeah it's good advertising it in news.txt. We can adjust the news.txt later when/if we turn the feature on by default. 
So to test it one would do :
```
lspconfig.hls.setup({
    capabilities = {
    		workspace.didChangeWatchedFiles.dynamicRegistration=true
     }
}
```
?

**Comment by nojnhuh** [comment]
@teto I don't think that exact syntax works, but this is the snippet I have from my config that I checked does work:
```lua
local default_caps = {
  workspace = {
    didChangeWatchedFiles = {
      dynamicRegistration = true,
    },
  },
}
```
And this is used to construct the `config.capabilities` just like you have.

**Comment by justinmk** [comment]
@nojnhuh some of the tests from this PR are flaky, would you be able to take a look?

```
ERROR    test/functional/lua/watch_spec.lua @ 102: vim._watch poll detects file changes
test/functional/helpers.lua:103: Error executing lua: [string "<nvim>"]:10: Timed out waiting for expected number of events. Current events seen so far: { {
    change_type = 1,
    path = "/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/T3131.65"
  } }
```

**Comment by nojnhuh** [comment]
@justinmk Yep, I just took a look. Overall I'm having trouble reproducing any of these locally and I don't see any obvious causes for flakiness but I'll keep digging. It seems like each kind of failure I noticed was platform-specific, so if we can `skip()` a specific test on a specific platform that might be a worthwhile bandaid until we have a real fix.

You must've seen the error you posted above on this build? https://github.com/neovim/neovim/actions/runs/4348962234/jobs/7598083483 (similarly on https://github.com/neovim/neovim/actions/runs/4348177340/jobs/7596380932, both MacOS)

Looking through the last few failing runs against `master`, I saw these failures too:

https://github.com/neovim/neovim/actions/runs/4366849199/jobs/7637394861 (MacOS):
```
-------- Running tests from test/functional/lua/watch_spec.lua
RUN      T3130 vim._watch watch detects file changes: 185.37 ms FAIL
test/functional/lua/watch_spec.lua:97: Expected objects to be the same.
Passed in:
(table: 0x0121816878) {
 *[1] = {
    [change_type] = 2
   *[path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/T3130.64/T3130.64' }
  [2] = {
    [change_type] = 3
    [path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/T3130.64/file' } }
Expected:
(table: 0x011825a788) {
 *[1] = {
    [change_type] = 1
   *[path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/T3130.64/file' }
  [2] = {
    [change_type] = 3
    [path] = '/Users/runner/work/neovim/neovim/build/Xtest_tmpdir/T3130.64/file' } }

stack traceback:
	test/functional/lua/watch_spec.lua:97: in function <test/functional/lua/watch_spec.lua:14>
```
Seems odd that the file name is something I don't think should ever exist since the test only ever creates `<root dir>/file`.

https://github.com/neovim/neovim/actions/runs/4367134146/jobs/7638057990,
https://github.com/neovim/neovim/actions/runs/4351265051/jobs/7602754099,
https://github.com/neovim/neovim/actions/runs/4348962234/jobs/7598083371 (all Linux):
```
RUN      T3481 LSP vim.lsp._watchfiles sends notifications when files change: 2566.11 ms ERR
test/functional/helpers.lua:103: Error executing lua: [string "<nvim>"]:14: Timed out waiting for expected number of messages. Current messages seen so far: { {
    method = "initialize",
    params = { ... }
  }, {
    method = "initialized",
    params = vim.empty_dict()
  } }
stack traceback:
	[C]: in function 'assert'
	[string "<nvim>"]:14: in function 'wait_for_messages'
	[string "<nvim>"]:41: in main chunk

stack traceback:
	test/functional/helpers.lua:103: in function 'exec_lua'
	test/functional/plugin/lsp_spec.lua:3601: in function <test/functional/plugin/lsp_spec.lua:3595>
```

**Comment by nojnhuh** [comment]
Actually made a bit of progress. I spun up a VM with 2 CPUs (which I believe is what the GH Actions runners have) and immediately repro'd the "vim.lsp._watchfiles sends notifications when files change" failure and see that fail somewhat frequently. Also repro'd the "vim._watch poll detects file changes" failure on Linux (though it's been failing in CI on MacOS).

I should have some time over the weekend to dig into this more and hopefully get a fix together.

**Comment by justinmk** [comment]
fwiw, `helpers.retry()` may be useful to wait for filesystem changes. I don't see it in `watch_spec.lua`.

**Comment by nojnhuh** [comment]
I looked into this a bit more and still don't have a super clear idea exactly what's wrong in the tests, but I opened #22637 with what I've found out so far and a `vim.wait()` hack that definitely improves things. If anyone has ideas on what a more permanent fix might look like then that would be much appreciated feedback on that PR.

**Comment by pencilcheck** [comment]
Thanks! just discovered this. Upgraded to 0.9.0, finger crossed

**Comment by lewis6991** [comment]
> Not sure I remember all the details, but I think the main issue I was running into with making uv_fs_event_t recursive on Linux was getting a watch to end itself when the watched path gets deleted. Since [libuv sets both the IN_DELETE and IN_DELETE_SELF flags](https://github.com/libuv/libuv/blob/e613fdd83cb1fb448ac0ebace7ade055d0068829/src/unix/linux.c#L1530-L1531), then when a subdirectory gets deleted, that event comes through to both the subdirectory's watcher and its direct parent's. And on the subdirectory's watcher (where we'd likely have easier access to its watch handle), the callback was invoked with a filename matching the subdirectory name, so the usual {watch path}/{filename} way to construct the full path was incorrect since it would have the subdirectory name at the end twice (I think because of the libuv code [here](https://github.com/libuv/libuv/blob/e613fdd83cb1fb448ac0ebace7ade055d0068829/src/unix/linux.c#L1468-L1472)). I don't think there's an obvious workaround for that issue though since it would be perfectly valid to have a directory at e.g. /dir/subdir/subdir.
>
> I maybe could have done some more digging to try to compensate for that, but it must've been shortly after that I saw Node.js implement recursive watching on Linux with uv_fs_poll_t, so I took that as a sign there might be other issues with uv_fs_event_t I hadn't seen yet.

How much of an issue if this *really*? Does this completely break things, or does it just lead to watchers firing callbacks incorrectly sometimes?

In light of the huge perf degradation due to all the polling objects, can we reconsider this?

**Comment by nojnhuh** [comment]
> How much of an issue is this _really_? Does this completely break things, or does it just lead to watchers firing callbacks incorrectly sometimes?

I didn't play around with it enough to see if this still works most of the time, but my sense is that it would involve a non-trivial amount of hacking around to become reasonably usable.

> I also couldn't see any related issues on Libuv's issue tracker.

Here's a (decade-old) thread on their mailing list which seems to be the only discussion I can find. The maintainers at the time were pretty firmly against building in this kind of functionality to libuv: https://groups.google.com/g/libuv/c/jYaSDlNzWzU/m/-3FtSLaIi1IJ

> In light of the huge perf degradation due to all the polling objects, can we reconsider this?

Overall I think it's fair to give this another look. I probably won't get around to it anytime soon so if anyone else wants to give this a shot that would be great!

**Pull request merged**
