### PR TITLE
feat(runtime): default treesitter highlighting for Lua

### PR DESCRIPTION
**Pull request by clason**
2024 is the year of treesitter on the desktop.

### CODE REVIEW

**Comment by lucario387** [comment]
2025 is the year for C highlighting using treesitter? :tm:

**Comment by clason** [comment]
Once the performance issues are fixed, yes.

**Comment by xvzc** [comment]
Why does your checks all pass mine don't

**Review by dundargoc — APPROVED** [review]

**Comment by jirutka** [comment]
This makes neovim [crash](https://gitlab.alpinelinux.org/alpine/aports/-/issues/16132) when treesitter for Lua is not available.

Unlike classic syntax highlighting definitions, tree-sitter parsers are very big binaries (for example, tree-sitter-julia is ~5 MiB). Neovim currently provides classic syntax highlighting support for [~710 languages](https://github.com/neovim/neovim/tree/master/runtime/syntax), and it costs 8 MiB in total (11 kiB each on average). tree-sitter parsers are 900 kiB on average (between 100–5000 kiB) **each**, so it would cost **639 MiB** if you were to replace them all with tree-sitter. This is insane and unsustainable.

Therefore tree-sitter should be optional with a graceful fallback to classic syntax highlighting if the tree-sitter for a particular language is not installed. Users can then install tree-sitter parsers only for languages they actively use and for which they want advanced features. Linux distros distribute tree-sitter parsers for various languages as separate packages.

(I’m a maintainer of the neovim package and many tree-sitter parsers in Alpine Linux.)

**Comment by clason** [comment]
> This makes neovim [crash](https://gitlab.alpinelinux.org/alpine/aports/-/issues/16132) when treesitter for Lua is not available.

This means your Neovim installation is broken. The parsers are **required**. And the Lua parser is 81 kiB, which is 1% of the syntax directory, so your concern about size is beside the point. (Obviously we're not planning to bundle all 300 parsers in this way. Instead, we'll ship with a wasmtime runtime so users can download them at runtime.)

**Comment by jirutka** [comment]
> And the Lua parser is 81 kiB, which is 1% of the syntax directory, so your concern about size is beside the point. 

It’s not beside the point. Yes, the tree-sitter parser for Lua is small, but we found out that you already unconditionally require more parsers, tree-sitter-query and tree-sitter-vimdoc. How many more will you add next release?

Why are they required? The classic syntax highlighting definitions are still there, so why take away the user’s choice?

> (Obviously we're not planning to bundle all 300 parsers in this way.)

So how many are you planning to bundle this way?

> That is fine and their prerogative

prerogative? What do you mean by that?

> as long as they make sure these are the exact versions we ship queries for. (Good luck finding a version that Neovim and Helix and Zed and Emacs are compatible with.)

That’s why we package parsers together with the queries they come with. I’m aware of issues with compatibility, but that’s something the tree-sitter community should solve. It is not sustainable for every text editor to bundle dozens of tree-sitter parsers of arbitrary versions.

**Comment by clason** [comment]
> It’s not beside the point. Yes, the tree-sitter parser for Lua is small, but we found out that you already unconditionally require more parsers, tree-sitter-query and tree-sitter-vimdoc. How many more will you add next release?

As many as we need. I don't see why we should justify our project development to you.

> but that’s something the tree-sitter community should solve.

And we are. By treating parsers and queries as "runtime files", just like the syntax files and plugins. You either accept that or stop packaging Neovim; the choice is up to you. Other distros manage just fine.

(Just to be clear: I take umbrage at your tone. Had you asked instead of starting with recriminations right from the bat, you would have gotten a different reply.)

**Comment by KAAtheWiseGit** [comment]
@clason, good day!

I want try and weigh in on this issue, since it affect me too, both as an avid Neovim user and as a package maintainer.

This breakage happened in the context of packaging Neovim into the [Alpine Linux'](https://alpinelinux.org/) aports tree, which is the collection of all packages provided by Alpine.  Alpine, as a distro, is focused on small size and security, so that dictates a lot of choices made by packagers.  For example, all documentation is provided in separate `<pkgname>-doc` packages, in order to reduce typical installation and container size.  And when a new Python app is added, all of it's dependencies have to be painstakingly put into their own packages.

So, with that philosophy in mind, we generally try to reduce the general amount of things a package requires or pulls over the internet, be it runtime packages or documentation.  So, as long as the original manual filetype configuration files aren't removed from Neovim, using them would be more preferable.

Packaging tree sitter can indeed cause issues, but such is the toil of the maintainers.  Current Lua TS package, for example, works fine on both Neovim and Helix (with the latter gracefully falling back on no-highlighting if TS isn't present).  So, as long as sticking to a minimal install is possible, we try to do that.

Finally, with all of that in mind, I (and probably many Neovim users on Alpine) would appreciate it if Neovim would allow bypassing tree sitter as an option, if it's not present at startup.  From my limited understanding, it can be done with a `pcall`, but I haven't yet figured out how to print a diagnostic message[^msg].

[^msg]: for some reason, `vim.print` doesn't print anything for me if it's located inside an `if`.

**Comment by bfredl** [comment]
> So, as long as the original manual filetype configuration files aren't removed from Neovim, using them would be more preferable.

By the same argument, the recently added tree-sitter parsers shouldn't be removed from the neovim runtime either. They are not somehow less part of the (mandatory) runtime distribution just because they happen to be more recently added.

**Comment by clason** [comment]
> Finally, with all of that in mind, I (and probably many Neovim users on Alpine) would appreciate it if Neovim would allow bypassing tree sitter as an option, if it's not present at startup. 

Sorry, but we won't do that. Neovim does not have "optional dependencies" or "optional features" (this is one of the differentiators from Vim). And we use the parsers for more than just syntax highlighting. (I also want to mention that the legacy syntax for Lua specifically has been broken for a long time; as upstream does not see fixing that as a priority -- understandably, since it's a thorny issue and not just a bugged syntax file -- switching to treesitter highlighting was the best option to fix the issue.)

So, sorry, the parsers are here to stay and are required for a good reason, so if you package Neovim, you must include them (somehow -- the choice is up to you, but make sure that they are at the exact version specified in our `cmake.deps/deps.txt`, any other version **will** be incompatible). We don't intend to add more in the near future, though.

**Comment by clason** [comment]
Obviously we're happy if Neovim gets packaged -- but that means packaging Neovim _as intended by the developers_. I completely understand if Alpine's priorities make Neovim a poor fit for an official package, and no hard feelings. But telling us that we should be developing our software differently because of that (implying your priorities should be _everyone's_ priorities) tends not to be well received ;)

**Pull request merged**
