### PR TITLE
[RFC] Add "margin" option

### PR DESCRIPTION
**Pull request by egormalyutin**
"margin" option changes space between line numbers and text.

`set margin=0`:
deepinscreenshot_ - _20190101235408

`set margin=4`:
deepinscreenshot_ - _20190101235347

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks. Did you see the disucussion in https://github.com/neovim/neovim/pull/6373 ? Also needs tests.

**Comment by malyutinegor** [comment]
@justinmk

I don't really know C, and trying to change "margin" to something like "numbersmargin" caused the variable couldn't be set. 

> tests
How can I test it?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/blob/master/test/README.md

**Comment by malyutinegor** [comment]
No, I mean how can I test UI option?

**Comment by bfredl** [comment]
@malyutinegor look at an existing screentests like `test/functional/ui/searchhl_spec.lua`. Use `screen:snapshot_util()` to generate new asserts.

**Comment by malyutinegor** [comment]
@justinmk Ok, I added test.

**Comment by justinmk** [comment]
This looks like mostly a copy of #6373, so closing in favor of that. In that PR I mentioned the test you added here, so it can be re-used.

**Pull request closed without merging**
