### PR TITLE
[RFC] CMake: Explicitly add curses include directory

### PR DESCRIPTION
**Pull request by Hinidu**
Hi guys!
Today I've tried to build neovim on NixOS and I found the small problem: because NixOS installs each package in its own tree with `bin`, `lib`, `usr`, etc. CMake couldn't find `termcap.h`. I spent some time trying to find the good solution myself, though I'm not expert in CMake and maybe someone could suggest some improvements.
Also I found `ncurses`-related stuff in `src/nvim/CMakeLists.txt` but I don't know why we need looking for `tinfo` library. Perhaps code in that file can be replaced by variables provided by `FindCurses` module.
PS. Good to see such active development! I hope I'll join you again now :-)

### CODE REVIEW

**Comment by justinmk** [comment]
Some related past issues: https://github.com/neovim/neovim/issues/1402 https://github.com/neovim/neovim/issues/960

If I'm not mistaken, with libtickit (https://github.com/neovim/neovim/pull/1657) and [unibilium](https://github.com/mauke/unibilium) we should not even need curses anymore. @tarruda, is it feasible to remove the curses dependency?

> I hope I'll join you again now :-)

You're always welcome!

**Comment by Hinidu** [comment]
> If I'm not mistaken, with libtickit (#1657) and unibilium we should not even need curses anymore.

Yes, I understand that it will be removed entirely in the future. I submitted that patch only to be able to work on the other tasks.
Though if it is possible to make some not too big changes and remove curses dependency entirely I would be glad to do that instead.

**Comment by justinmk** [comment]
Understood. I don't have a clear idea of the curses dependency, so I hope @jszakmeister can look at this.

**Comment by tarruda** [comment]
> If I'm not mistaken, with libtickit (#1657) and unibilium we should not even need curses anymore. @tarruda, is it feasible to remove the curses dependency?

We can't remote it yet because nvim still needs it to use the terminfo/termcap database. Even though it has its own hardcoded termcap database, those aren't helpful when using nvim with custom terminfos.

But as soon as I finish #1657, I will translate the tickit UI to C and move it to neovim repository which will remove all dependencies on the system curses/terminfo.

**Comment by Hinidu** [comment]
@tarruda thanks for clarification! So if ncurses will be dropped relatively soon then I think I can leave these changes locally and just don't commit them when working with some other stuff.

**Pull request closed without merging**
