### PR TITLE
version.c: update [ci skip]

### PR DESCRIPTION
**Pull request by marvim**
This pull request is [automated](https://github.com/neovim/bot-ci).

### CODE REVIEW

**Comment by justinmk** [comment]
vim-patch:8.0.0725

**Comment by janlazo** [comment]
vim-patch:8.1.1145: compiler warning for unused function
vim-patch:8.1.1146: in MS-Windows console colors in a terminal window are wrong
vim-patch:8.1.1147: desktop file translations are requiring manual updates
vim-patch:8.1.1149: building desktop files fails with older msgfmt
vim-patch:8.1.1150: generating desktop files not tested on Travis
vim-patch:8.1.1151: build fails when using shadow directory
vim-patch:8.1.1152: compiler warning with VS2019
vim-patch:8.1.1154: getting a newer msgfmt on Travis is too complicated

vim-patch:8.1.1153 does not exist or was suppose to be https://github.com/vim/vim/commit/9a419ffb934bd04bf8d44ceaf4694e50cce55eab which is N/A.

**Comment by LTKills** [comment]
vim-patch:8.0.0732: there is no dedicated redraw for callbacks in neovim

**Comment by janlazo** [comment]
@LTKills I added the typo changes from vim-patch:8.0.0768 in https://github.com/neovim/neovim/pull/9906

**Comment by LTKills** [comment]
> @LTKills I added the typo changes from vim-patch:8.0.0768 in #9906

@janlazo Does this mean I should edit the comment? If so, ~strikethrough~ or just remove the patch line?

**Comment by janlazo** [comment]
@LTKills Your choice. I personally remove it when the patch is included in a vim-patch PR. Keep all the vim-patch in 1 comment if possible. I use separate posts for discussion if I'm not sure such as the multi_byte patches.

**Pull request merged**
