### PR TITLE
[WIP] fix qb kbtree errors

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by bfredl** [comment]
Strange, even with `#if 1` the pragmas only silences the errors in one case, but not the other.

**Comment by blueyed** [comment]
Does rebasing this on master help?  (via #6851)

**Comment by ZyX-I** [comment]
By the way, PVS reports

    ./src/nvim/bufhl_defs.h:32:1: error: V512 A call of the 'memcpy' function will lead to underflow of the buffer 'z->key'.

error for the new code. Could you check this? I have only gone so far that you probably need to replace `T - 1` with `2 * T - 1` in

```C
		memcpy(__KB_KEY(key_t, z), &__KB_KEY(key_t, y)[T], sizeof(key_t) * (T - 1)); \
```

, but not sure whether this is right.

**Comment by bfredl** [comment]
It is not "buffer underflow" as it explicitly sets the size of the buffer to T-1 on the row before. (Reasonably after a "split" the two nodes will only be half-full)

I already removed some type params in kbtree, but I'm sure it can be removed in more places.

**Comment by jszakmeister** [comment]
I don't know if this helps, but going through the logs I see that there is a small difference in compilation flags between compiling buffer.c for nvim and buffer.c being compiled for use in the unit tests.  Specifically, buffer.c being compiled for unit tests has the following additional flags: `-Dnvim_test_EXPORTS -fPIC -DUNIT_TESTING`.  Playing around, changing the good build line to include `-fPIC` causes the kbtree errors.  So there's something about enabling `-fPIC` that seems to be causing the problem.

**Comment by jamessan** [comment]
This is a [false-positive](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56273) that's been fixed in GCC 5 and later versions of GCC 4.8.

It is odd that the pragma isn't disabling the diagnostic, though.

**Comment by justinmk** [comment]
Maybe try the _Pragma explicitly at the call sites instead of in the macro definition?

**Comment by bfredl** [comment]
You mean every call to the kbtree function that happens to inlined (and possibly inlined in turn and so forth)? That seems incredibly fragile... (But then again optimization dependent warnings turned into errors is per definition fragile...). Better maybe to disable this warning globally for gcc 4 and less, if it is broken anyway?

**Comment by justinmk** [comment]
Maybe not permanently, but just as an experiment.

> Better maybe to disable this warning globally for gcc 4 and less, if it is broken anyway?

If that works then yes, let's do it (perhaps `<= 4.8.4`).

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/7083

**Pull request closed without merging**
