### PR TITLE
support threads in lua

### PR DESCRIPTION
**Pull request by bfredl**
continuation of #15658

### CODE REVIEW

**Comment by clason** [comment]
Probably want to rebase on https://github.com/neovim/neovim/pull/17219 instead of the dependency bump?

**Comment by bfredl** [comment]
or just merge that if there is no outstanding issue?

**Comment by clason** [comment]
> or just merge that if there is no outstanding issue?

Well, the current state of the PR pulls in a pre-release commit of LibUV since the 1.43.0 release had a regression that breaks our openBSD build -- I had planned to wait for a followup 1.44.0 release. But we can also merge as-is, and I'll make a followup PR to bump to an actual release whenever that happens (which may or may not be in the near future).

Your call!

**Comment by bfredl** [comment]
sure, I just didn't see any need to change the PR in a hurry, these were just commits I didn't squash so it would be easy to drop them when they are not needed anymore :]

**Comment by clason** [comment]
Sure, and I felt a bit bad for the insta-comment; just wanted to make a note of it since this PR is the main motivation for the libuv bump. Just let me know if and when I should squash and merge that PR.

**Comment by bfredl** [comment]
I plan to merge this quite soon (but after #17219 ). Though note this is just the beginning, and more work will be done to expose more builtin functionality to threads, and perhaps abstractions to facilitate communications across threads (like use msgpack rpc from thread to access the API from thread asynchronously).

**Comment by bfredl** [comment]
Lint build alone seems to use an outdated luv.h header which gives a warning, though the build still continues with the actual lint checks. I assume it is a stale CI cache issue fixed when this hits nightly.

**Comment by jamessan** [comment]
> Lint build alone seems to use an outdated luv.h header which gives a warning

It uses system dependencies instead of bundled.

**Pull request merged**
