### PR TITLE
refactor: Minimize variable scope as per the neovim style guide.

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by bfredl** [comment]
could be worth keeping #14661 in mind for not too many conflicting changes

**Comment by dundargoc** [comment]
> could be worth keeping #14661 in mind for not too many conflicting changes

Do you mean specifically for autocmd or for all files?

**Comment by bfredl** [comment]
I mean for files with larger ongoing refactors, of which autocmds is closest in time. Probably it is not a big deal, but it is good to be aware.

**Comment by dundargoc** [comment]
Closing as to not mess with ongoing refactoring.

**Pull request closed without merging**
