### PR TITLE
lsp: Allow user to configure focusability of lsp float

### PR DESCRIPTION
**Pull request by shadmansaleh**
Currently lsp floats created with `lsp.utils.open_floating_preview`
Are all focusable . This pr allows user to specify whether to make
it focusable or not . If user don't specify anything by default
float will be focusable.

After #14649 diagnostics floats are focusable . Previously they were not . I think focusability of diagnostics floats are personal opinion . So making it configurable makes sence . Personaly it annoys me too much .

@mjlbach waiting for your opinion at this 🙂

### CODE REVIEW

**Comment by mjlbach** [comment]
sgtm, but you should clean up you commit message. We're doing [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) now (so like feat(lsp): whatever)

**Comment by folke** [comment]
Maybe add it do the docs for `open_floating_preview` instead?

**Comment by shadmansaleh** [comment]
> sgtm, but you should clean up you commit message. We're doing conventional commits now (so like feat(lsp): whatever).

Didn't know that . I've changed the commit message is it ok now ?

> Also not sure we need to explicitly list the opt in the docs for show line diagnostics given you can throw any arbitrary opt in there and it should work no?

I agree with @folke I think it makes sense to be in open_floating_preview. If it's not mentioned anywhere no one will know it exists.

**Comment by shadmansaleh** [comment]
> Maybe add it do the docs for open_floating_preview instead?

Yeah done :)

**Comment by shadmansaleh** [comment]
One more thing I think docs for `open_floating_preview` was wrong . Doesn't documentation comments need to start with `---` (3 '-') to be captured by docgen ? They had only 2 ('--') . I've changed them to have 3

**Comment by mjlbach** [comment]
You should fix your commit message on the docgen commit, there are typos. You can also run docgen and add it in this commit.

```
`vim.lsp.util.open_floating_preview` opts tables keys
were prefixed with `--` instead of `---`, preventing
capture by docgen.
```

**Comment by mjlbach** [comment]
Same with your first commit 

```
 This pr allows user to specify whether `lsp.utils.open_floating_preview`
it focusable via the `opts` parameter. Defaults to true.
```

**Comment by shadmansaleh** [comment]
@mjlbach Done :)

**Comment by mjlbach** [comment]
Still a typo :) (also get rid of the like while you are at it). Then I'll merge.

`by setting the focusable key inside opts parameter:`

**Comment by shadmansaleh** [comment]
> Still a typo :)

I think I've forgotten all the grammar .

> Also there's a space in the second commit message on the second line, first char.

I copy pasted :P

**Comment by mjlbach** [comment]
> I copy pasted :P

You should know better than to trust someone reviewing your PR at 4 AM 💤

**Comment by shadmansaleh** [comment]
> You should know better than to trust someone reviewing your PR at 4 AM 💤

Why aren't you sleeping man !!

**Comment by mjlbach** [comment]
There are still typos:

First commit:

This pr allows the user to specify whether `lsp.utils.open_floating_preview`
**is** focusable via the `opts` parameter. Defaults to true.

Second commit (missing space after for)

In the documentation for `vim.lsp.util.open_floating_preview`
the opts table keys **was** prefixed with `--` instead of `---`,
preventing capture by docgen.

**Comment by mjlbach** [comment]
I'm just so excited about focusable windows, I can't sleep.

**Comment by shadmansaleh** [comment]
> There are still typos (my bad, didn't catch these the first time)

Why are you so stubborn about commit messages 😂
I need see if someone has written a plugin to check grammar .

> the opts table keys was prefixed with -- instead of

Isn't keys plural ?

**Comment by mjlbach** [comment]
whoops you right. other points remain.

**Comment by mjlbach** [comment]
Vig has https://github.com/vigoux/LanguageTool.nvim, not sure what the state of the art is in grammar check for neovim.

**Comment by shadmansaleh** [comment]
Updated.
> Vig has https://github.com/vigoux/LanguageTool.nvim, not sure what the state of the art is in grammar check for neovim.

Thanks will check it out

**Pull request merged**
