### PR TITLE
[RDY] Fix coverity issues. (3)

### PR DESCRIPTION
**Pull request by elmart**
Fix 5 coverity issues, 4 of them in "High impact outstanding" category.

### CODE REVIEW

**Comment by elmart** [comment]
Added review commits addressing all suggested changes.

**Comment by oni-link** [comment]
LGTM.

**Comment by elmart** [comment]
Integrated review commits and repushed.

@aktau Have you got some other comment, or can I mark this RDY?

**Comment by elmart** [comment]
Thanks, @oni-link and @aktau.

**Comment by aktau** [comment]
Since my comments were only stylistic, this LGTM.

**Comment by elmart** [comment]
Addressed last remarks by @aktau (extra parens in ternary expression) and repushed. Seems that Travis is veeeery slow startins osx builds.

**Comment by justinmk** [comment]
merged. thank you @elmart !

**Pull request closed without merging**
