### PR TITLE
lint

### PR DESCRIPTION
**Pull request by fowles**
Suppress uninitialized variable warning

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for contributing. We build with [`-Werror`](https://github.com/neovim/neovim/blob/852ebc6f0bab4e08f99f08d279776194172a4fac/CMakeLists.txt#L255) on CI. It is also a goal to fix coverity warnings and [clang-scan warnings](https://neovim.io/doc/reports/clang/).

But it's not a goal to fix every warning from every compiler at every optimization level. E.g. `-O2` optimization level tends to show spurious warnings.

Inspecting the codepath shows that this is a false positive, so closing.

**Comment by fowles** [comment]
I agree that it is a false positive, but given the simplicity of preventing it altogether, I think you should reconsider.  It is far easier to keep a project warning free than it is to claw it back to that state after it has started having them.

**Comment by justinmk** [comment]
There is a reason for not initializing variables: it helps analyzers catch logic that uses the value without having set a useful value.

**Comment by justinmk** [comment]
I see this shows up very often in the RelWithDebInfo build, along with 1 other case. Since it is a common case, it is worth silencing.

**Pull request merged**
