### PR TITLE
snap: Adjust snapcraft yaml to support multiarch and support luajit on supported platforms

### PR DESCRIPTION
**Pull request by hurricanehrndz**
On platforms luajit is supported, nvim should be built with luajit support and vice versa.

### CODE REVIEW

**Review by jamessan — APPROVED** [review]

**Comment by hurricanehrndz** [comment]
I have shared with @justinmk the new SECRET_SNAP_SIG value that needs to be added to the travis-ci config before new releases get triggered.

**Comment by justinmk** [comment]
wow this is a lot. 

- We send  a sample webhook payload to https://snapcraft.io/nvim/webhook/notify , where the payload  points to https://github.com/hurricanehrndz/neovim-snap 
  - I assume the plan is to later point to https://github.com/neovim/neovim-snap . Ok.

**Comment by hurricanehrndz** [comment]
@justinmk 

Yes I agree it is a lot, bu itt was the only way to fully support all the architectures. The neovim-snap repo is relatively small and will stay that way. If Neovim wants ownership of the repo that seems perfectly sensible to me. If the repo was owned by Neovim, we could trigger the builds via a commit (appending date to a dummy text) other than the simulated webhook.

snapcrafters discuss this method in this [post](https://forum.snapcraft.io/t/the-automatic-build-and-pubish-process-of-snaps-owned-by-the-snapcrafters/7954/2).

**Comment by justinmk** [comment]
Hmm master `snap` job is failing: https://travis-ci.org/github/neovim/neovim/builds/725135938

```
napcraft.project.errors.YamlValidationError: Issues while validating properties: The 'version' property does not match the required schema: 'v0.5.0-nightly-' is not a valid snap version string. Snap versions consist of upper- and lower-case alphanumeric characters, as well as ...
```

**Comment by hurricanehrndz** [comment]
@justinmk ,

I will take a look at it, and try and address it. The real builds are fine, but are not being trigger because of the travis.ci build is failing. I will need to go through the logs. 

PS snaps become very troublesome when trying to automate their deployment, otherwise they are quite easy to work with.

**Comment by hurricanehrndz** [comment]
image
image

**Pull request merged**
