### PR TITLE
build/gcc: disable -Warray-bounds entirely (WAS: kbtree: adjust __KB_PRAGMA_START)

### LINKED ISSUE #7921: ci: quickbuild failure
Quickbuild failure below, I would guess this stems from the recent upgrade of Ubuntu on the quickbuild environment. cc @jszakmeister 

@bfredl IIRC you put a workaround in place for this, but maybe it doesn't apply to Release mode?

```
7:22:41,607 WARN  - In file included from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:6:0,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/map.h:9,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/buffer_defs.h:40,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/normal.h:6,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/ex_cmds_defs.h:8,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/ex_eval.h:5,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/globals.h:8,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/vim.h:291,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/api/private/handle.h:4,
07:22:41,607 WARN  - from /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/buffer.c:26:
07:22:41,607 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/buffer.c: In function ‘bufhl_mark_adjust’:
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:238:28: error: array subscript is below array bounds [-Werror=array-bounds]
07:22:41,608 WARN  - kp = __KB_KEY(key_t, x)[i]; \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
07:22:41,608 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
07:22:41,608 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
07:22:41,608 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10) // -V512
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:239:23: error: array subscript is below array bounds [-Werror=array-bounds]
07:22:41,608 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 1); \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
07:22:41,608 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
07:22:41,608 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
07:22:41,608 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10) // -V512
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:243:28: error: array subscript is below array bounds [-Werror=array-bounds]
07:22:41,608 WARN  - kp = __KB_KEY(key_t, x)[i]; \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
07:22:41,608 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
07:22:41,608 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
07:22:41,608 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10) // -V512
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:244:23: error: array subscript is below array bounds [-Werror=array-bounds]
07:22:41,608 WARN  - __KB_KEY(key_t, x)[i] = __kb_delp_aux_##name(b, xp, 0, 2); \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:418:2: note: in expansion of macro ‘__KB_DEL’
07:22:41,608 WARN  - __KB_DEL(name, key_t, kbnode_t, T) \
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:391:3: note: in expansion of macro ‘KBTREE_INIT_IMPL’
07:22:41,608 WARN  - KBTREE_INIT_IMPL(name, key_t, kbnode_##name##_t, __cmp, T, (sizeof(kbnode_##name##_t)+(2*T)*sizeof(void *)))
07:22:41,608 WARN  - ^
07:22:41,608 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/bufhl_defs.h:32:1: note: in expansion of macro ‘KBTREE_INIT’
07:22:41,608 WARN  - KBTREE_INIT(bufhl, BufhlLine *, BUFHL_CMP, 10) // -V512
07:22:41,608 WARN  - ^
07:22:41,900 WARN  - cc1: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by justinmk**
closes #7921

### CODE REVIEW

**Comment by justinmk** [comment]
Test commit confirms that the define is set on quickbuild ubuntu env:

```
12:27:40,828 WARN  - /home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/src/nvim/lib/kbtree.h:394:3: error: #error "test"
12:27:40,828 WARN  - # error "test"
```

**Comment by justinmk** [comment]
@jamessan @jszakmeister @bfredl latest change https://github.com/neovim/neovim/pull/7923/commits/c681ffe19ca40b33367b488a7e8705e1354f6d80 disables `-Warray-bounds` entirely for GCC, I can't find a better way.

IIUC https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66099 explains why `_Pragma("GCC diagnostic push")` wasn't working.

**Review by jamessan — APPROVED** [review]

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7923/commits/404ac16c5f3c4c114284fefe184fa2a9973c79fe didn't help with `lldb` problem:

```
[32m[2m[ RUN      ][0m[0m tui accepts basic utf-8 input: [2m77.16 ms[0m [1m[32mOK[0m[0m
========================= Core file /cores/core.22675 =========================
(lldb) target create "build/bin/nvim" --core "/cores/core.22675"
error: Unable to find process plug-in for core file '/cores/core.22675'
```

Something is crashing on travis macOS, and we can't get a backtrace.

https://github.com/springmeyer/travis-coredump#os-x suggests we need a recent version of lldb.

**Comment by justinmk** [comment]
@jszakmeister The linux build is failing to build busted, would you be able to investigate this?

```
22:40:48,082 INFO  - [ 78%] Generating usr/bin/busted
22:40:48,296 INFO  - CMakeFiles/busted.dir/build.make:60: recipe for target 'usr/bin/busted' failed
22:40:48,296 INFO  - make[3]: Leaving directory '/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps'
22:40:48,296 WARN  - make[3]: *** [usr/bin/busted] Terminated
22:40:48,298 WARN  - make[2]: *** [CMakeFiles/busted.dir/all] Error 2
22:40:48,298 WARN  - make[1]: *** [all] Error 2
22:40:48,298 WARN  - make: *** [deps] Error 2
22:40:48,298 INFO  - CMakeFiles/Makefile2:258: recipe for target 'CMakeFiles/busted.dir/all' failed
22:40:48,298 INFO  - make[2]: Leaving directory '/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps'
22:40:48,298 INFO  - Makefile:83: recipe for target 'all' failed
22:40:48,298 INFO  - make[1]: Leaving directory '/home/quickbuild/buildagent/workspace/root/neovim/pull-requests-automated/.deps'
22:40:48,298 INFO  - Makefile:76: recipe for target 'deps' failed
22:40:48,700 INFO  - Executing post-execute action...
22:40:48,700 ERROR - Step 'master>buildall>build-node?testNode=linux-64>build-deps' is failed: Failed to run command: make deps
Command return code: 2
Command error output: ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
+ libtoolize --copy
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
configure.ac:38: installing './ar-lib'
configure.ac:25: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:21: installing './missing'
Makefile.am: installing './depcomp'
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
Warning: variable CFLAGS was not passed in build_variables
No existing manifest. Attempting to rebuild...
make[3]: *** [usr/bin/busted] Terminated
make[2]: *** [CMakeFiles/busted.dir/all] Error 2
make[1]:...
```

**Comment by jszakmeister** [comment]
@justinmk Sure, but not until this evening or tomorrow morning.  That's a pretty weird error though.  Did we change more things in the build?  It may be that I no longer have the step setup correctly to match what happens by default (I split some of the steps so that we could get better logging and data out).

**Comment by jszakmeister** [comment]
Hey @justinmk, it looks you may have the issue resolved.  I tried recreating the problem and saw that some things changed on us (third-party dependency-wise), but it looks like the fix landed in master and this was rebased on top of it.  The actual build seems to be working fine though.  Let me know if there's something else I should be looking into.

**Comment by justinmk** [comment]
@jszakmeister The failure is random from what I can tell, that's why I'm kind of desperate for help here.

>  It may be that I no longer have the step setup correctly to match what happens by default (I split some of the steps so that we could get better logging and data out).

Would you be able commit your script(s) to the repo? Or add them as new cmake targets? Then we might be able to reproduce problems easier, in some cases.

**Comment by justinmk** [comment]
@jszakmeister Thanks! What if we don't bother with the TAP report? I personally only look at the build log, not the graphical UI.  

Or, can QB look for e.g. an XML file that contains TAP or junit data, instead of reading the build log? Maybe we can generate the TAP/junit data while keeping the build log (and build invocation) the same as for the other builds.

Note that we already have a custom busted handler, we could modify it to generate an extra file.

**Comment by jszakmeister** [comment]
> @jszakmeister Thanks! What if we don't bother with the TAP report? I personally only look at the build log, not the graphical UI.

We could do that.  I think the charts are nice and it's a little easier to navigate to the test that broke, IMHO.  And to be honest, that really isn't the issue here: building the dependencies is happening in it's own step and is doing a "make deps":

```text
${node.getAttribute("make", "make")} deps
```

There's really nothing special happening in that step, which is what makes me think we have a dependency issue.  BTW, the step is written this way so that we call gmake instead of BSD make on the FreeBSD node.

> Or, can QB look for e.g. an XML file that contains TAP or junit data, instead of reading the build log? Maybe we can generate the TAP/junit data while keeping the build log (and build invocation) the same as for the other builds.

That doesn't really help us--I had that before and there are several issues.  QB expects a real junit file, and busted doesn't conform.  We could capture the TAP report separately (in the same way we did the junit file), but that goes back to the original problem of not being able to watch the build and see where things failed from the log.  :-(

> Note that we already have a custom busted handler, we could modify it to generate an extra file.

We could do that, but QB cannot parse it and produce the charts from it.  Maybe that's not a concern, but I think being able to find the wrong test quickly is rather nice.  I may be the only one who knows how to do that though. :-)

**Comment by justinmk** [comment]
@jszakmeister Thanks for the clarifications. Maybe that issue was only occurring when I last worked on this. I haven't seen it since then. Ironically I may end up using the QB TAP features more often now that they have my attention (I've been wanting something similar for travis for a long time).

The Linux QB build now seems to complete, but also consistently provokes the hang detection (I think). I'm hoping #6530 will help with that.

**Comment by jamessan** [comment]
> I may be the only one who knows how to do that though. :-)

This comment made me revisit that aspect of QB ... :100: :+1:

**Pull request merged**
