### PR TITLE
[RFC] job.c: Prevent early return from job_wait().

### PR DESCRIPTION
**Pull request by oni-link**
job.c: Prevent early return from job_wait().

A blocking call job_wait(job, -1) can only return after job is finished
and all handles of job are closed. But hitting CTRL-C makes job_wait()
return early while handles can still be open. This can lead to problems
with the job/handle callbacks if the caller (of job_wait()) already
freed the memory that is used in the job callbacks.

To fix this, only return after all handles of the job are closed.

Can reproduce an assert on my system trying to abort the following command:

``` viml
:call system('sleep 100')
```

https://github.com/neovim/neovim/pull/1365#discussion_r22559122
ping @tarruda

### CODE REVIEW

**Comment by justinmk** [comment]
If CTRL-C works in the functional tests, it should be fairly easy to add a test for this.

**Comment by tarruda** [comment]
LGTM. @oni-link could you try adding a test to https://github.com/neovim/neovim/blob/master/test/functional/shell/viml_system_spec.lua ?

You can simulate sending ctrl+c with `feed('<c-c>')` and verify screen state with: [screen:expect()](https://github.com/neovim/neovim/blob/master/test/functional/ui/screen_basic_spec.lua#L22-L38)

**Comment by oni-link** [comment]
I can add a test to check whether CTRL-C terminates a system() call or not. But this PR tries to prevent a stack/memory corruption. Not sure if one can test for that.

**Comment by tarruda** [comment]
> I can add a test to check whether CTRL-C terminates a system() call or not. But this PR tries to prevent a stack/memory corruption. Not sure if one can test for that.

I assumed that this would fix https://github.com/neovim/neovim/issues/1234, thats why I suggested adding the test. In any case, it would be a good idea to add a test that would reproduce the bug fixed by this PR because valgrind detects memory errors.

**Comment by oni-link** [comment]
Found a way that always segfaults for me: Aborting `:call system('yes')`. Here `valgrind nvim` can detect (more) errors. The patch fixes both problems.

When I use `feed(':call system("yes")<cr>'); feed('<c-c>')` the test programm terminates, but
with `feed(':call system("yes")<cr><c-c>')` the tests complete. Is the first one the right way to 
detect the bug?

**Comment by aktau** [comment]
A bit messy but by necessity. LGTM!

**Comment by justinmk** [comment]
> Is the first one the right way to 
detect the bug?

May as well test both.

**Comment by oni-link** [comment]
Added some tests for `system()` and `systemlist()` to see what happens when interrupted with CTRL-C.

Running `TEST_FILE=test/functional/shell/viml_system_spec.lua make functionaltest` without the fix gives the error message `Running functional tests failed with error: SIGPIPE.`.

**Comment by justinmk** [comment]
Should we keep screen tests under `test/functional/ui`, or move `screen.lua` to `test/functional/screen.lua`?

**Comment by tarruda** [comment]
> Should we keep screen tests under test/functional/ui, or move screen.lua to test/functional/screen.lua?

Yes it should be moved.

**Comment by justinmk** [comment]
Thanks @oni-link !

**Pull request merged**
