### PR TITLE
Fix test bashisms

### PR DESCRIPTION
**Pull request by jdebp**
This is another reason that 0.2 does not work on FreeBSD.

### CODE REVIEW

**Comment by ZyX-I** [comment]
There are way too much commits for such a small amount of changes. Can you squash everything?

**Comment by jdebp** [comment]
I already did.  I rebased against master as of today, because I branched from an earlier master.  This is what resulted.  The only _real_ commit is the one after the final merge from master.  The rest seem to have come from a branch that was already merged in #6673.

**Comment by justinmk** [comment]
travis macOS builds are failing. Maybe if we use `printf` (which is POSIX specified) instead of `echo -n`  it will work.

```
[1m[35m[  FAILED  ][0m[0m [36m./test/unit/helpers.lua[0m @ [36m733[0m: [1mshell functions os_system can echo some output (shell builtin)[0m

./test/unit/helpers.lua:702: (string) '

...s/travis/build/neovim/neovim/test/unit/os/shell_spec.lua:58: Expected objects to be the same.

Passed in:

(string) '-n some text

'

Expected:

(string) 'some text''



stack traceback:

	./test/unit/helpers.lua:716: in function 'itp_parent'

	./test/unit/helpers.lua:743: in function <./test/unit/helpers.lua:733>



[1m[35m[  FAILED  ][0m[0m [36m./test/unit/helpers.lua[0m @ [36m733[0m: [1mshell functions os_system can deal with empty output[0m

./test/unit/helpers.lua:702: (string) '

...s/travis/build/neovim/neovim/test/unit/os/shell_spec.lua:65: Expected objects to be the same.

Passed in:

(string) '-n

'

Expected:

(string) '''



stack traceback:

	./test/unit/helpers.lua:716: in function 'itp_parent'

	./test/unit/helpers.lua:743: in function <./test/unit/helpers.lua:733>
```

**Comment by jdebp** [comment]
Aha.  MacOS.  I thought of using `printf`, then a quick check of FreeBSD, Debian, and OpenBSD indicated that `echo -n` would be alright.  Let me return to my first instinct.

**Comment by justinmk** [comment]
Side note: we have FreeBSD in our quickbuild CI: http://neovim-qb.szakmeister.net/build/12740/step_status

I assume @jszakmeister installed bash. Maybe it would be a good idea to uninstall it, assuming we get things working?

**Comment by jszakmeister** [comment]
Yeah, that's my fault.  Bash is installed, but I have a link to `/bin/bash` to support my environment (yes, I could use `/usr/bin/env bash` as the shebang, but that has other problems in environments I work in).  I can remove the link if that helps things though (then it'd only be available as `/usr/local/bin/bash`, which is where it lives on FreeBSD).

**Pull request closed without merging**
