### PR TITLE
oldtest: align test file contents

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by janlazo** [comment]
I did this patch in https://github.com/neovim/neovim/pull/11096

**Comment by blueyed** [comment]
Oh, you mean https://github.com/neovim/neovim/pull/11087.
Missed that - I've search for the patch ("8.1.0514") though before.  We should make sure that this gets found then.

I guess I'll rebase the re-ordering / alignment of existing tests then on top - or feel free to cherry-pick it.  I'll try to review #11087 later then.

**Comment by justinmk** [comment]
seems like this is redundant with https://github.com/neovim/neovim/pull/11087 ?

**Comment by blueyed** [comment]
@justinmk 
Yes, but it has something on top that should be done after #11087.

**Comment by blueyed** [comment]
Rebased.

**Pull request merged**
