### PR TITLE
version.c: mark NA patches

### PR DESCRIPTION
**Pull request by Shougo**
1710: external command
2311: Appveyor

### CODE REVIEW

**Comment by Shougo** [comment]
Added 1710

**Comment by justinmk** [comment]
Why is 2086 NA? Cannot just assume anything related to encoding is not applicable. In the case of 2086, it's making changes that are relevant to Vim tests we brought over. And it's reducing code. Without 2086 we have more code, and will have merge conflicts too.

**Comment by justinmk** [comment]
Merged 2086 0de6f450e47d

**Comment by Shougo** [comment]
Thank you.  I have fixed it.

**Comment by justinmk** [comment]
No more to add?

**Comment by Shougo** [comment]
Nothing.

**Comment by Shougo** [comment]
Thank you.

**Pull request merged**
