### PR TITLE
do_highlight(): leave 'background' alone

### LINKED ISSUE #8595: colorscheme resets background to light; setting background=dark will reset the colorscheme
- `nvim --version`: NVIM v0.3.0
- Vim (version: 8.0 Included patches: 1-1766) behaves differently? yes
- Operating system/version: debian sid
- Terminal name/version: xfce4-terminal 0.8.7.4
- `$TERM`: xterm-256colors

### Steps to reproduce using `nvim -u NORC`

Requires a vimrc loading the packages vim-airline/vim-airline and crusoexia/vim-monokai

### Actual behaviour

When I do `:color monokai`, the background variable is set to `light` (nothing in monokai.vim sets this). If I do `:set background=dark` however, the color scheme is reset to `default`. When `color monokai` is set, airline turns white because the background variable changes. I am reporting here because this seems to be an error related to the `termguicolors` command or something like that, since the following makes it work:

```vimscript
color monokai
set termguicolors background=dark
set notermguicolors
let g:airline_theme = 'minimalist'
```
This makes the background color stay at dark while the monokai colorscheme is still selected, allowing normal operation. I did not observe this issue with nvim 0.2.3. 

### Expected behaviour

background variable to stay at dark while changing colorschemes.

### PR DESCRIPTION
**Pull request by justinmk**
closes #8595 

cc @bfredl @zhou13 @teto

### CODE REVIEW

**Comment by janlazo** [comment]
Check https://github.com/vim/vim/commit/1615b36b91b094263240d7b555283ddf33208f62 before commiting this.

**Comment by bfredl** [comment]
What @janlazo said, and also, could we explicitly check if the option was set by the user before and avoid it then?

**Comment by justinmk** [comment]
Just to be clear, everyone here prefers that the auto-detection remains, but it is skipped if 'bg' was explicitly set? That is, you think the auto-detection is worth keeping?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/8595#issuecomment-399033933

**Pull request closed without merging**
