### PR TITLE
doc(CONTRIBUTING): update

### PR DESCRIPTION
**Pull request by lewis6991**
- add section for managaing includes via IWYU
- recommend clangd over ctags
- tidy up links
- remove ./scripts/check-includes.py

### CODE REVIEW

**Comment by dundargoc** [comment]
Wait, what? The output from IWYU is incorrect, it recommends including the generated headers and not the real headers. The documentation is misleading. If we want to use IWYU we can generate the suggested changes from it, remove the `.generated.h` from the include suggestions and *then* apply it.

**Comment by justinmk** [comment]
> IWYU is incorrect, it recommends including the generated headers and not the real headers

Thanks. Noted in https://github.com/neovim/neovim/issues/549#issuecomment-1224113319

**Comment by lewis6991** [comment]
Could mapping files help here? https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md

**Comment by dundargoc** [comment]
@lewis6991 huh, I should've done more research. That looks very promising. Let's experiment with it and see if we can get it to work.

**Pull request merged**
