### PR TITLE
test: comment out test that freezes sourcehut CI

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by Jun-T** [comment]
Could you please try my PR #15251 ?

**Comment by dundargoc** [comment]
Yeah, let's try out the [PR](https://github.com/neovim/neovim/pull/15251) @Jun-T wrote first.

**Comment by dundargoc** [comment]
Closing this in favor of https://github.com/neovim/neovim/pull/15251.

**Comment by clason** [comment]
Let's see if that PR can actually fix the hang, but for the record: rather than commenting out the test, it should be skipped just on CI similarly to https://github.com/neovim/neovim/blob/3d183596720aeab874ceb475af23e390bbe9b8a3/test/functional/plugin/lsp_spec.lua#L266

**Pull request closed without merging**
