### PR TITLE
[RFC] vim-patch:7.4.569, 7.4.573

### PR DESCRIPTION
**Pull request by Shougo**
Problem:    Having CTRL-C interrupt or not does not check the mode of the
            mapping. (Ingo Karkat)
Solution:   Use a bitmask with the map mode. (Christian Brabandt)

https://github.com/vim/vim/commit/651863c94a882a97aec7968fc87a638ff78e56ff

Problem:    Mapping CTRL-C in Visual mode doesn't work. (Ingo Karkat)
Solution:   Call get_real_state() instead of using State directly.

https://github.com/vim/vim/commit/5000869712f799d9ca25c0e45dc21d332edae5f4

It is based on @glts fix in https://github.com/neovim/neovim/pull/2621

~~This fix fails the mapping_spec.lua.~~
~~I don't know why...~~
~~Can you check it?~~

### CODE REVIEW

**Comment by Shougo** [comment]
Dup of https://github.com/neovim/neovim/pull/2621

**Comment by Shougo** [comment]
Rebased.

**Comment by justinmk** [comment]
This looks good, I verified the tests locally, but made some changes in https://github.com/neovim/neovim/pull/3996

**Comment by Shougo** [comment]
OK, thanks.

**Pull request closed without merging**
