### PR TITLE
vim-patch:9.0.1443: ending Insert mode when accessing a hidden prompt buffer

### LINKED ISSUE #22924: Accessing hidden prompt buffer stops insert mode unexpectedly
### Problem

First of all, I wanted to debug more before creating the issue, but noticed the 0.9 release so I'm creating it now.

Whenever I start nvim-dap debug session Neovim stops entering insert mode. Whenever I try to enter insert mode, e.g. by pressing `a`, it immediately exists. If I try to hold the `a` key once in a while a character will be inserted, but generally the insert-exit happens pretty fast.

I tried to pinpoint the issue by checking different plugins, but couldn't find a related change. Then I did `git bisect` on Neovim repo and found that the **commit that introduced the issue** was https://github.com/neovim/neovim/commit/10baf89712724b4b95f7c641f2012f051737003c. Judging from the description it is related to insert mode so it makes sense.  

I didn't yet have time to debug it more and may not have enough time soon so wanted to report it here.

### Steps to reproduce

Will try to provide detailed repro when I have more time to debug this. For reference, I'm starting nvim-dap debug session with cppdebug, I have disabled nvim-dap-ui. I am using noice.nvim if that may be related (juding from the vim patch that introduced the error it might be related to some noice prompt buffers?).

### Expected behavior

Can enter insert mode.

### Neovim version (nvim -v)

nightly 10baf89712724b4b95f7c641f2012f051737003c

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.12.0 (5a728195)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #22924

#### vim-patch:9.0.1443: ending Insert mode when accessing a hidden prompt buffer

Problem:    Ending Insert mode when accessing a hidden prompt buffer.
Solution:   Don't stop Insert mode when it was active before.

https://github.com/vim/vim/commit/05a627c3d4e42a18f76c14828d68ee4747118211

Co-authored-by: Bram Moolenaar <Bram@vim.org>

### CODE REVIEW

**Comment by Shougo** [comment]
Hi.  The PR seems has the problem.

https://github.com/nvim-telescope/telescope.nvim/issues/2501

https://github.com/nvim-telescope/telescope.nvim/issues/2027#issuecomment-1538718111

I think it has the breaking change.

**Comment by Shougo** [comment]
I think this is the reason.

https://github.com/nvim-telescope/telescope.nvim/issues/2501#issuecomment-1541009573

**Comment by Shougo** [comment]
I don't know this is plugin problem or neovim/Vim problem.
But `mode change is restored after autocmd` is reasonable.

**Comment by zeertzjq** [comment]
I think it was fixed in #23785.

**Pull request merged**
