### PR TITLE
found a typo in docs/api.txt

### PR DESCRIPTION
**Pull request by akurdunkar**
I think it is supposed to 'can' instead of 'cal'.

### CODE REVIEW

**Comment by gpanders** [comment]
API documentation is taken from the function docstrings. Can you fix the typo in the docstring of `nvim_open_term` in `src/nvim/api/vim.c`?

**Comment by aditya-K2** [comment]
> API documentation is taken from the function docstrings. Can you fix the typo in the docstring of `nvim_open_term` in `src/nvim/api/vim.c`?

so should I abandon the changes that are made in the docs/api.txt?

**Comment by gpanders** [comment]
No need, you can leave it :)

**Comment by aditya-K2** [comment]
> No need, you can leave it :)

Ok. Thanks for the help. I have made the necessary changes.

**Pull request merged**
