### PR TITLE
[RFC] Exclude build directory from Coveralls

### PR DESCRIPTION
**Pull request by steveno**
I know this patch is split among two different commits. Before I waste time squashing them I'd like to know if this is a desired change.

### CODE REVIEW

**Comment by Pyrohh** [comment]
This certainly makes sense to me. I think we could also exclude third-party, cmake, config, runtime/doc, and a few others. What do you think @justinmk?

**Comment by justinmk** [comment]
Where does coveralls get its data, if not from the `build/` directory? That would be a good thing to note in the commit message.

**Comment by jszakmeister** [comment]
I think this is trying to leave generated files out of the coverage report.

**Comment by steveno** [comment]
@justinmk by default coveralls scans every sub-directory of the root you pass to it. So it is checking `/build`, `/test`, and others that more than likely shouldn't included in metrics detailing how much of your code is covered by a test.

You can see this here: https://coveralls.io/builds/2258015

The list of 122 changed files includes files from the build directory.

**Comment by steveno** [comment]
My initial description of this change my have too vague. I apologize for that.

**Comment by fwalch** [comment]
Is there an "include" flag we can use instead/can we run coveralls only on the src directory?

**Comment by justinmk** [comment]
per https://github.com/eddyxu/cpp-coveralls , there appears to be a `--include` option. Shall we go with that instead?

**Comment by Pyrohh** [comment]
> per https://github.com/eddyxu/cpp-coveralls , there appears to be a --include option. Shall we go with that instead? We probably want to exclude tests/, for example...

:+1:

**Comment by steveno** [comment]
It appears the consensus is to whitelist instead of blacklist. I'll open a new PR to do that instead. Feel free to leave suggestions as to which folders you feel should or should not be on the whitelist.

**Comment by fwalch** [comment]
No need to create a new PR, you can just perform the changes, amend your commit (`git commit --amend`) and overwrite the branch of this PR (force-push; `git push --force`). If you have problems/questions, just ask :-)

**Comment by steveno** [comment]
@fwalch that works for me.

**Comment by justinmk** [comment]
The original change in this PR brought the coverage down to zero: https://coveralls.io/builds/2276231

So now I'm back to wondering what motivated the idea of excluding `build/`?

**Comment by fwalch** [comment]
> So now I'm back to wondering what motivated the idea of excluding build/?

Not having the autogenerated files (`build/include/*.generated.h`) in the coverage report, I suppose.

**Pull request closed without merging**
