### PR TITLE
lsp: Add vim.lsp.buf.range_code_action()

### LINKED ISSUE #12927: LSP: is it possible to vim.lsp.buf.code_action() given a multi-line range?
- `nvim --version`: v0.5.0-672-gd8e6a0396

### Steps to reproduce using `nvim -u NORC`

- select a multiline range of text, do `:lua vim.lsp.buf.code_action()` (perhaps a `'<,'>` prefix for the current visual selection)

### Actual behaviour
the code action request seems to only consider the current line of cursor

### Expected behaviour
the code action request uses the current range selection

### Some context
with [gopls v0.5.0](https://github.com/golang/tools/releases/tag/gopls%2Fv0.5.0) there is an "extract range to function" code action. and [seems to work in vs code](https://streamable.com/d6wym3)

so I'm wondering is this possible in nvim builtin lsp?

thanks for your help!

### PR DESCRIPTION
**Pull request by notomo**
This pull-request will enable to execute code_action for a given range.
```
:'<,'>lua vim.lsp.buf.range_code_action()
```

fix: https://github.com/neovim/neovim/issues/12927

### CODE REVIEW

**Comment by sentriz** [comment]
works great, thank you!

**Comment by teto** [comment]
haven't tested yet but looks ok. thanks.

**Comment by mightyiam** [comment]
Hey, is there an example somewhere of how one would set a keybinding to use this, please?

**Comment by sentriz** [comment]
@mightyiam 

```
vnoremap <silent> ga  :<c-u>lua vim.lsp.buf.range_code_action()<cr>
```

should do it

**Pull request merged**
