### PR TITLE
Fix #8696

### LINKED ISSUE #8696: Running Neovim in Vim's terminal triggers E5009 (uses Vim's VIM/VIMRUNTIME)
Vim appears to set `$VIM` and `$VIMRUNTIME` in its terminal environment, which then gets picked up by Neovim.

Running `:checkhealth` will trigger:

> E5009: Invalid $VIMRUNTIME: /usr/share/vim/vim81

The workaround is to unset VIM/VIMRUNTIME before running nvim.

Vim 8.1.22
NVIM v0.3.1-139-g2bfabd5b

### PR DESCRIPTION
**Pull request by shinymimiq**
It set VIM/VIMRUNTIME correctly for neovim running inside of a vim's terminal
This could resolve https://github.com/neovim/neovim/issues/8696

### CODE REVIEW

**Comment by janlazo** [comment]
Can this be tested in neovim's test suite? CI workflow runs ubuntu 20.04.

**Comment by shinymimiq** [comment]
One possible way of testing is to run nvim with VIM_TERMINAL set to some value, and check if we set VIM/VIMRUNTIME correctly. 

I may need to spend some time to get started with writing test 😄

**Comment by jamessan** [comment]
As I described in https://github.com/neovim/neovim/issues/8696#issuecomment-864343230, I don't think this is the right approach.  It's just working around the problem and actually breaks legitimate use cases.

**Comment by shinymimiq** [comment]
Agree with @jamessan . I think this PR didn't solve the root cause and will introduce other problems.

**Pull request closed without merging**
