### PR TITLE
refactor(snippet): rename exit() => stop()

### PR DESCRIPTION
**Pull request by justinmk**
Reduce "vocabulary creep".

### CODE REVIEW

**Comment by clason** [comment]
I'm not sure that has the right connotation here; "cancel" implies "do _not_ do this, revert", but `exit` _will_ have expanded the snippet.

**Comment by justinmk** [comment]
> I'm not sure that has the right connotation here; "cancel" implies "do _not_ do this, revert",

It cancels the current operation, which indeed this function does, i.e. it doesn't proceed with the remaining snippet activities. That is pretty analogous to canceling a mapping, insert mode, etc: none of them *revert* any changes or edits.

**Comment by clason** [comment]
I don't think we talk anywhere about "canceling insert mode" -- we "leave" a mode (which is also a valid semantic cousin). And "cancelling a mapping" _does_ prevent it from being executed. If it must be `stop` instead of `exit`, so be it. (As to "why", remember that this feature was provided by a new contributor that had not yet internalized such guidance.)

**Comment by justinmk** [comment]
> This wasn't me making arbitrary naming decisions.

I know.

**Pull request merged**
