### PR TITLE
lsp: Limit signs for the same line number

### PR DESCRIPTION
**Pull request by lewis6991**
For cases when LSP reports multiple diagnostics for the same line, don't
ever place more than one sign for the same severity.

This is particularly useful for LSP's like diagnosticls which allow you
to hook up multiple linters through the same client.

### CODE REVIEW

**Comment by teto** [comment]
the current behavior is less surprising: one mark per error so you can see at a glance how many errors you have. It could go as an option but I fear this is will go out of hand. Ideally this level of configurability should go into a plugin. Not sure what's best: should we provide an augmented Diagnostic type with sign_id and all and have a `filter(diagnostic) -> diagnostics` that users could override @tjdevries

**Comment by lewis6991** [comment]
I've added a config field `minimal` for the signs. Hopefully this is a nice compromise.

If we don't want to commit this to the API we can prefix the field with `_` to mark it as unstable. Otherwise we can implement something else if someone has a better idea.

**Comment by tjdevries** [comment]
Can you explain to me _why_ you don't want more than one sign per line? I'm not sure I understand the reasoning (nothing seems weird on my end when I have this, so trying to understand the underlying problem).

One thing to note is that `set_signs` is specifically set as an exposed function so that anyone can override, so even if we don't merge the changes, you can simply put this into your `init.lua` (or make a plugin :wink:) that would do this for you and other users. Just as a general note about extending the builtin LSP.

Thanks!

**Comment by lewis6991** [comment]
> Can you explain to me why you don't want more than one sign per line? I'm not sure I understand the reasoning (nothing seems weird on my end when I have this, so trying to understand the underlying problem).

Currently for python files I have 3 effective clients:

- `jedi-language-server`
- `diagnostic-language-server`
    - `mypy`: type checking
    - `pylint`: style checking

For any basic python error, all three clients often report the same error:
Screenshot 2021-01-18 at 09 54 56

When I first saw this, I just assumed the signs handler was being naive and blowing up the sign column because not many people use multiple clients like this. I can see this getting worse for other languages where a single error can propagate into many other errors (like above) and for those cases I certainly don't want the signcolumn jumping around constantly. I know I can `set signcolumn=auto:N`, but that is really just a workaround.

Given how `nvim-lsp` is going, I definitely see people adding more clients as they become available in the future. As this happens we should ensure the signcolumn is being (or can be) used more efficiently.

> One thing to note is that set_signs is specifically set as an exposed function so that anyone can override, so even if we don't merge the changes, you can simply put this into your init.lua (or make a plugin 😉) that would do this for you and other users. Just as a general note about extending the builtin LSP.

Tbh, I'd like to make a plugin so I can be more opinionated about this however for that we would kind of need the following to be exposed from `diagnostic.lua`:
- `diagnostic_severities`
- `sign_highlight_map`
- `get_bufnr` (This one is trivial to reimplement)

None of these are essentially, but the omission of each one makes it a little more awkward to implement something that gels well with he built-in defaults of nvim-lsp.

**Comment by tjdevries** [comment]
>  I know I can set signcolumn=auto:N, but that is really just a workaround.

I guess I don't see who that's a "workaround" -- that's the desired behavior of signcolumn as far as I understand it. What is the advantage of your method over configuring it that way?

**Comment by lewis6991** [comment]
> I guess I don't see who that's a "workaround" -- that's the desired behavior of signcolumn as far as I understand it. What is the advantage of your method over configuring it that way?

I currently have it set to `auto:3` which allows one sign for gitsigns/gitgutter/signify, one for lsp and one for something else (maybe folds or something). However a majority of the time the signcolumn is often jumping around from 1-3 (gitsigns is mostly constant) as the LSP is moving it around. So with `signcolumn=auto:N` you still have the problem of it moving around too much, which means to 'workaround' this problem I would need to set it to `yes:N` and have it fixed width which is a shame. I don't mind the sign column moving around a bit, just not to the degree my LSP setup makes it.

Also it just leads to ugly situations where the signs are being truncated or overlapping:
Screenshot 2021-01-18 at 15 31 13

It would be nice if the mental model is that "a single sign from LSP indicates errors on that line" as opposed to "N signs from LSP means there is **at least** N errors on that line).

I admit this is all very minor, but it's being able to correct these annoyances that keep me using neovim.

**Comment by lewis6991** [comment]
Another thing to consider is that each client updates the signcolumn at different times (some after a long delay) which makes the sign column jumping much worse.

**Comment by teto** [comment]
The jumping around can be annoying, there is this suggestion on a behavior I feel could help here https://github.com/neovim/neovim/issues/13783 . As:
1/ the current behavior is the least surprising (a sign per error)
2/ concurrent LSP the exception  rather than the norm,
3/ and we seem to  agree that it would be best left to a plugin
I propose to close this and reopen an issue with propositions on how to best expose what you described in https://github.com/neovim/neovim/pull/13763#issuecomment-762147804

**Comment by tjdevries** [comment]
```
Tbh, I'd like to make a plugin so I can be more opinionated about this however for that we would kind of need the following to be exposed from diagnostic.lua:

    diagnostic_severities
    sign_highlight_map
    get_bufnr (This one is trivial to reimplement)
```

I'd be fine with exposing most/all of those as one option.

Another option could be we could create a new function `vim.lsp.diagnostic.get_sign_priority(...)` with the `...` being whatever we need to create unique IDs. by default, it could return 0 or whatever we're currently doing. This would allow consumers to create IDs as they see fit, as well as potentially even skipping certain signs (`nil` could represent "please do not show this sign"). 

I prefer to try and find ways that we can extend the LSP with functions, as those tend to compose much better than options (particularly when the options are not exactly 1-to-1 with some idea, like relating to diagnostic severity or similar).

What do you think of the second option? Then plugins/users can implement the feature you have in this PR with a very simple addition.

> I admit this is all very minor, but it's being able to correct these annoyances that keep me using neovim.

Agreed :smile: It is one of my favorite things about Neovim as well :)

**Comment by lewis6991** [comment]
> The jumping around can be annoying, there is this suggestion on a behavior I feel could help here #13783 . As:
1/ the current behavior is the least surprising (a sign per error)
2/ concurrent LSP the exception rather than the norm,
3/ and we seem to agree that it would be best left to a plugin
I propose to close this and reopen an issue with propositions on how to best expose what you described in #13763 (comment)

Ok, I can open:
-  an issue for the sign changes
- Another PR for the fix to the testcase that this PR has (in `diagnostic_spec.lua`).

> I'd be fine with exposing most/all of those as one option.

I made some mistakes in that initial list what we really need it:
- `sign_highlight_map`
- `diagnostic_cache` - could we refactor the code so this wouldn't be needed?
- `get_bufnr` - again not a big deal but maybe we can hoist this out too?

> Another option could be we could create a new function vim.lsp.diagnostic.get_sign_priority(...) with the ... being whatever we need to create unique IDs. by default, it could return 0 or whatever we're currently doing. This would allow consumers to create IDs as they see fit, as well as potentially even skipping certain signs (nil could represent "please do not show this sign").

I think that would get confused with the actual sign priority which is already a configuration point in `set_signs`. Additionally I like the idea of using `set_signs` as a hook point as it gives you lots of freedom and the default implementation is already pretty simple (even more simple if we can hoist `diagnostic_cache` out of it). 

One idea I've already got is to use the second sign char to display the count (e.g. `E E E E ` becomes `E4`). I  didn't implement that in this PR as that would require a much more intrusive change but it can all be done within `set_signs`... I think.

**Pull request closed without merging**
