### PR TITLE
fix(treesitter): revert to using iter_captures in highlighter

### LINKED ISSUE #27895: Tree-sitter highlighting no longer takes query range/specificity into account
### Problem

Before https://github.com/neovim/neovim/pull/27132, queries where a more specific capture appeared earlier than a less specific capture later on used to have a higher precedence, but now that is no longer the case, which is a pretty breaking change really, since I've taken into account specificity of a capture plenty of times when writing queries (especially highlights) for nvim-treesitter. Highlights in certain circumstances will appear off now as a result. I understand this wasn't really documented/obvious, but it was a convenient feature to use.

### Steps to reproduce

config:

```lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "c" },
	callback = function(args)
		vim.treesitter.start()
	end,
})

vim.cmd("highlight! @variable.parameter gui=bold guifg=#ff0000 guibg=NONE")
vim.cmd("highlight! @operator gui=bold guifg=#00ff00 guibg=NONE")
```

```sh
nvim --clean -u minimal.lua test.c
```

write `void foo(int *bar)`

Notice that `*` is highlighted the same as `a` because the `@variable.parameter` capture captures the whole `pointer_declarator` node, but the earlier `@operator` capture for `*` ideally would have a higher priority than this

### Expected behavior

I'd expect `*` to be highlighted with `@operator`, not `@variable.parameter`, a possible solution could be to account for the size of the node when applying captures.

It'd also be fine to just not consider specificity anymore, that's totally fine but some queries need to be reworked then (e.g. some of C's highlights) and this should be documented to avoid further confusion

### Neovim version (nvim -v)

v0.10.0-dev-2619+gc52dfb6e8

### Vim (not Nvim) behaves the same?

no (no treesitter)

### Operating system/version

Arch Linux 6.7.9-zen1-1

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

built from source

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes #27895

### CODE REVIEW

**Review by gpanders — APPROVED** [review]
I did [consider doing this originally](https://github.com/neovim/neovim/pull/27132#issuecomment-1918238282), but there was a concern that exposing the match table in `iter_captures` might surface other bugs. See https://github.com/neovim/neovim/pull/27274 (cc @wookayin). At this point it seems like we might just have to pick our poison though.

I had a branch where I was working on an independent fix for the issues that #27274 resolved, so perhaps I can revive that if @wookayin doesn't want to pick it back up.

**Comment by lewis6991** [comment]
> I did [consider doing this originally](https://github.com/neovim/neovim/pull/27132#issuecomment-1918238282), but there was a concern that exposing the match table in `iter_captures` might surface other bugs. See https://github.com/neovim/neovim/pull/27274 (cc @wookayin). At this point it seems like we might just have to pick our poison though.
> 
> I had a branch where I was working on an independent fix for the issues that #27274 resolved, so perhaps I can revive that if @wookayin doesn't want to pick it back up.

My god this is such a minefield!

It seems the most glaring problem in that PR is with the metadata table. The metadata table is match level, so regardless of where we go, I would say that it should always be provided with the match table.

**Comment by clason** [comment]
Yeah, this is design debt inherited from the earliest implementation (and possibly even upstream). The `prepare_iter_matches` spaghetti in nvim-treesitter should have tipped us off...

**Comment by clason** [comment]
That was quick. (Lint was failing, btw.)

**Comment by lewis6991** [comment]
Dam, pulled the trigger a bit quick. Will fixup at some point.

**Comment by wookayin** [comment]
I just checked this one and #27895; so this PR does revert the use of `iter_matches` in TS highlighter (#27132). While this is LGTM to me, but can anyone explain why `iter_matches` would suffer from the bug #27895 whereas `iter_captures` aren't?

**Comment by lewis6991** [comment]
Yes, as far as I understand it `iter_captures` priorities node order first, and then match order, I think, I'm not 100% sure tbh, but something like that.

**Pull request merged**
