### PR TITLE
[RFC] vim-patch: 7.4.2255,7.42256

### PR DESCRIPTION
**Pull request by lonerover**
#### vim-patch:7.4.2255
Problem:    The script that checks translations can't handle plurals.
Solution:   Check for plural msgid and msgstr entries.  Leave the cursor on
                the first error.
https://github.com/vim/vim/commit/ec42059b78c1932a44f2bf36ac982109884dc7c7

#### vim-patch:7.4.2256
Problem:    Coverity complains about null pointer check.
Solution:   Remove wrong and superfluous error check.
    
https://github.com/vim/vim/commit/db249f26edf7a5f88d1f4468d08ec5b84f5ab7ad

This's a converity issue, so just update the version.c and mark it as applied.

### CODE REVIEW

**Comment by justinmk** [comment]
Is this still WIP?

**Comment by justinmk** [comment]
> This's a converity issue, so just update the version.c and mark it as applied.

Coverity issues usually are worth applying to our codebase.

**Comment by lonerover** [comment]
Fixed

**Comment by justinmk** [comment]
Thanks @lonerover

**Pull request merged**
