### PR TITLE
[RFC] input.c: Restore double click

### PR DESCRIPTION
**Pull request by sach1t**
Let there be double click (again :)
Fixes issue #4887 
(the implementation is very similar to vim... don't process the release events)

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! Is it possible to simulate in a test? That will prevent https://github.com/neovim/neovim/issues/4887 from happening again.

**Comment by sach1t** [comment]
I think it can be simulated by just feeding <LeftMouse><LeftRelease> repeatedly and seeing if it cycles through the modes (visual, visual line, visual block). I will add some tests, if it works. I think the reason why #4887 wasn't detected was because usually in the test cases we just feed <LeftMouse> repeatedly opposed to what actually occurs which is <LeftMouse><LeftRelease>.

**Comment by sach1t** [comment]
I think it can be simulated by just feeding `<LeftMouse><LeftRelease>` repeatedly and seeing if it cycles through the modes (visual, visual line, visual block). I will add some tests, if it works. I think the reason why #4887 wasn't detected was because usually in the test cases we just feed `<LeftMouse>` repeatedly opposed to what actually occurs which is `<LeftMouse><LeftRelease>`.

**Comment by sach1t** [comment]
The tests I added are passing on Travis CI, other tests seem to be failing... specifically:
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] .../neovim/neovim/test/functional/options/defaults_spec.lua @ 102: XDG-based defaults with too long XDG variables are correctly set
[  FAILED  ] .../neovim/neovim/test/functional/options/defaults_spec.lua @ 162: XDG-based defaults with XDG variables that can be expanded are not expanded
[  FAILED  ] .../neovim/neovim/test/functional/options/defaults_spec.lua @ 220: XDG-based defaults with commas are escaped properly

**Comment by justinmk** [comment]
Might be the Travis cache for this PR. I'll clear it and restart

**Comment by justinmk** [comment]
Restarted build.

**Comment by sach1t** [comment]
Thanks for restarting it. I also fixed the linting and rebased.
It looks like everything was fine when you restarted it (https://travis-ci.org/neovim/neovim/builds/150349014).

**Comment by sach1t** [comment]
Looks good (except for the stalled stuff).

**Comment by justinmk** [comment]
Thanks @sach1t !

**Pull request merged**
