### PR TITLE
vim-patch:8.0.1089: cannot get range count in user command

### PR DESCRIPTION
**Pull request by kwon-young**
Problem:    Cannot get range count in user command.
Solution:   Add <range> argument.
https://github.com/vim/vim/commit/c168bd4bd3a9b856fc410fc4515dcca1d10d7461

### CODE REVIEW

**Comment by justinmk** [comment]
There are no changes here. Maybe try `git cherry-pick ...`

**Comment by kwon-young** [comment]
Sorry, I still doesn't fully understand how the vim-patch.sh script works.
I fixed it manually.
Is it okay now?

**Comment by janlazo** [comment]
Lint build failure

```
src/nvim/ex_docmd.c:5191:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5191:  if should always use braces  [readability/braces] [5]
src/nvim/ex_docmd.c:5192:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 5191  [whitespace/alignment] [2]
src/nvim/ex_docmd.c:5193:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 5191  [whitespace/alignment] [2]
src/nvim/ex_docmd.c:5192:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5227:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {). Relevant opening is on line 5226  [whitespace/alignment] [2]
src/nvim/ex_docmd.c:5227:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5402:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5403:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5404:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5405:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5406:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5407:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5408:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5409:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5410:  Tab found; better to use spaces  [whitespace/tab] [1]
src/nvim/ex_docmd.c:5411:  Tab found; better to use spaces  [whitespace/tab] [1]
```

**Comment by kwon-young** [comment]
Ah okay, thank for your help!
I'll refactor as soon as I can.

**Pull request closed without merging**
