### PR TITLE
refactor(lua): rewrite vim.highlight.range()

### PR DESCRIPTION
**Pull request by zeertzjq**
- Use getregionpos().
- Use a single extmark for non-blockwise selection.

### CODE REVIEW

**Review by justinmk — APPROVED** [review]

**Comment by clason** [comment]
This introduced a regression with diagnostics: if diagnostics are at the end of the line, the underline for it now extends to the beginning of the next line. I haven't cooked up a minimal example yet, but you can observe this in the `lazy.nvim` update output:
Screenshot 2024-05-26 at 13 04 46

I think there still needs to be some distinction between single- and multiline extmarks (regarding the `hl_eol` option).

**Comment by zeertzjq** [comment]
Oh, I forgot about the existence of `hl_eol`.

**Comment by zeertzjq** [comment]
I don't end of line or `hl_eol` are relevant. I think #29022 should fix this.

**Comment by clason** [comment]
Indeed it does, thank you!

**Pull request merged**
