### PR TITLE
shada: Continue dumping when variables failed to dump

### LINKED ISSUE #3721: Storing a funcref in a variable can break shada dump
I was seeing this issue because of [a plugin](https://github.com/jdonaldson/vaxe/blob/79d59c8040fff21bdcf86b2d29e79411ad720115/plugin/haxe.vim#L63), but I can repro it manually with `-u NONE`. Here's a passing spec illustrating the behavior:

``` diff
diff --git a/test/functional/shada/variables_spec.lua b/test/functional/shada/variables_spec.lua
index 6225971..439f099 100644
--- a/test/functional/shada/variables_spec.lua
+++ b/test/functional/shada/variables_spec.lua
@@ -82,6 +82,13 @@ describe('ShaDa support code', function()
     eq(0, funcs.exists('g:str_var'))
   end)

+  it('breaks when a funcref is stored in a variable', function()
+    nvim_command('let C = function("escape")')
+    nvim_command('set shada+=!')
+    eq('Vim(wshada):E475: Invalid argument: attempt to dump function reference',
+      helpers.exc_exec('wshada'))
+  end)
+
   it('dumps and loads variables correctly when &encoding is not UTF-8',
   function()
     set_additional_cmd('set encoding=latin1')
```

I don't really understand this part of Vim well enough to know what the correct behavior is, but this was silently breaking shada saves for me. I guess it should probably just omit funcrefs when persisting variables?

### PR DESCRIPTION
**Pull request by ZyX-I**
Closes #3721

### CODE REVIEW

**Comment by justinmk** [comment]
@ZyX-I sorry I missed this, can you rebase?

**Comment by ZyX-I** [comment]
Rebased. Linter will fail, but I verified that there are no errors in shada.c.

**Comment by justinmk** [comment]
Travis and QB are failing on `:wshada`:

```
test/functional/shada/compatibility_spec.lua @ 161
Failure message: ./test/functional/helpers.lua:72: Vim(wshada):E136: Did not rename Xtest-functional-shada-compatibility.shada.tmp.a to Xtest-functional-shada-compatibility.shada because there were errors during writing it
stack traceback:
./test/functional/helpers.lua:72: in function 'request'
./test/functional/helpers.lua:128: in function 'nvim_command'
test/functional/shada/compatibility_spec.lua:169: in function <test/functional/shada/compatibility_spec.lua:161>

test/functional/shada/compatibility_spec.lua @ 122: ShaDa forward compatibility support code works with jump item with BOOL unknown (mX) key value
```

**Comment by ZyX-I** [comment]
@justinmk Should be fixed now.

**Pull request merged**
