### PR TITLE
build(deps): bump libuv to 1.44.0

### PR DESCRIPTION
**Pull request by clason**
Now that the fix for the OpenBSD hangs is merged upstream, prepare for bumping libuv again.

The intention here is to get a head start on tests and possible remaining breakages _before_ the upcoming 1.44.0 release (which is the one that should be merged; I'll update the PR accordingly).

### CODE REVIEW

**Comment by clason** [comment]
Well, that looks encouraging :]

**Comment by clason** [comment]
I know, on it :)

**Comment by jamessan** [comment]
freebsd failed with:

```
============================ Core file ./nvim.core ============================
sh: gdb: not found


Tests covered by this check: 13
nan ms test/helpers.lua:408: crash detected (see above)

stack traceback:
	test/helpers.lua:408: in function 'check_cores'
	test/functional/helpers.lua:894: in function <test/functional/helpers.lua:889>
```

Can you rebase on latest master?  I think this is what https://github.com/neovim/neovim/pull/17636 fixed.

**Comment by clason** [comment]
Guess you can't win all of them...

**Review by jamessan — APPROVED** [review]

**Comment by clason** [comment]
Let's see if this one sticks :)

**Comment by Dotrar** [comment]
Good timing, I just decided to update neovim on my local too.
following build instructions, make clean, etc. I get 
```
/usr/bin/ld: /tmp/nvim.jYFYsC.ltrans29.ltrans.o: in function `nlua_common_vim_init':
/home/dre/tmp/neovim/build/../src/nvim/lua/executor.c:509: undefined reference to `luv_set_thread'
/usr/bin/ld: /home/dre/tmp/neovim/build/../src/nvim/lua/executor.c:510: undefined reference to `luv_set_cthread'
collect2: error: ld returned 1 exit status
```

Ubuntu 20.04 is stuck on 1.34 ? 
```
09:45 $ apt list libuv1
Listing... Done
libuv1/focal-updates,focal-security,now 1.34.2-1ubuntu1.3 amd64 [installed,automatic]
libuv1/focal-updates,focal-security 1.34.2-1ubuntu1.3 i386
```

**Pull request merged**
