### PR TITLE
WIP: f_getcwd: assert that return value is same as ex_pwd

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neovim/neovim/issues/7662#issuecomment-423822146

`make test` passed locally.

### CODE REVIEW

**Comment by lervag** [comment]
I'm sorry for intruding and possibly for commenting in the wrong thread. I'm using neovim version 0.3.4 (in Community repos of Arch Linux). I find in some weird cases with vim-fugitive and vimtex that I end up with an inconsistent state where `:pwd` and `:echo getcwd()` do not return the same value.

I would be happy to help work on this issue if it is of interest to pursue it as a bug. I.e., I can try to create a minimal example and to open a new issue. But I thought I'd first reach out and check if this is already a known issue (I only found #7662, which seems to be similar but also claims to be resolved).

**Comment by justinmk** [comment]
@lervag minimal repro example be very useful.

**Comment by lervag** [comment]
Great, thanks. I've opened an issue with a minimal example, see #9892.

**Comment by blueyed** [comment]
Closing for now (https://github.com/neovim/neovim/issues/9892#issuecomment-482812619).

**Pull request closed without merging**
