### PR TITLE
[RFC] Add ui test for default title (with/without filename)

### PR DESCRIPTION
**Pull request by bfredl**
I thought we already had this and got a bit worried #3090 build passed (well, the functional parts) without corresponing change in the tests :)

### CODE REVIEW

**Comment by justinmk** [comment]
:+1:  Can the new `it()` tests go in the `describe(':set title'...` block on line 79?

**Comment by bfredl** [comment]
@justinmk Done!

**Comment by justinmk** [comment]
LGTM

**Comment by fmoralesc** [comment]
Sorry for not taking a shot at this in #3090, I really jumped the gun on that. :/

**Comment by bfredl** [comment]
@fmoralesc No worries, the issue here was that there weren't any tests about this in the first place

**Comment by fmoralesc** [comment]
Sure, but I had to leave home, and then I got a notification that the build had failed, so I kinda panicked a bit. :/ At least the failure was unrelated...

**Pull request merged**
