### PR TITLE
[WIP]ci/appveyor: run pacman -Syu to update package list

### PR DESCRIPTION
**Pull request by janlazo**

### CODE REVIEW

**Comment by erw7** [comment]
Perhaps the terminal has switched from using a `winpty` to a `conpty`, and the test is failing to run. We may want to put terminal testing in Windows on pending.

Ref https://www.appveyor.com/docs/windows-images-software/
Ref https://docs.microsoft.com/en-us/windows/console/createpseudoconsole#requirements

**Comment by janlazo** [comment]
Vim has `termwintype`. Maybe we can port that to force winpty or conpty in the terminal tests.

**Comment by erw7** [comment]
I created the `termwintype` equivalent option at implementation time. But due to justinmk's objections it was removed.

Ref https://github.com/neovim/neovim/pull/11390#discussion_r346152824

**Comment by janlazo** [comment]
@erw7 I think it's time to revisit that decision, even if `termwintype` is undocumented. I suggest that we treat `termwintype` like the `term` option for now so that we can debug whether `winpty` or `conpty` is used and adjust/skip the tests for `conpty`.

**Comment by erw7** [comment]
> I suggest that we treat `termwintype` like the term option for now so that we can debug whether `winpty` or `conpty` is used and adjust/skip the tests for conpty.

I added `has('compty')` in #13177. Vim also has this, so I think this is a good idea.

Ref https://github.com/vim/vim/blob/cf4d454df0619ee41ef40e7e91fce3fb061d7d5b/runtime/doc/eval.txt#L11518

I was able to adjust the test to pass locally, but it doesn't work in CI. I'll probably give up.

**Pull request closed without merging**
