### PR TITLE
[RFC] Remove duplicates and garbage from installation

### PR DESCRIPTION
**Pull request by ZyX-I**
Fixup for #2288 for the issues found by @Pyrohh.

### CODE REVIEW

**Comment by ZyX-I** [comment]
By the way, I noticed the following artifacts in runtime/doc: Makefile and doctags.c. Specifically there are 2 ways to generate help tags in the makefile:

1. Compile and use doctags.c.
2. Use *vim* (not nvim). Vim should be installed in this case.

Additionally this makefile generates html using awk script (BTW, was not that retired?). After this PR these files are not installed.

**Comment by Pyrohh** [comment]
> 1. Compile and use doctags.c.
> 2. Use vim (not nvim). Vim should be installed in this case.

AFAICT, only the first one (used through `gmake html`) can detect missing tags.

For example, if I make this change:
```diff
diff --git a/runtime/doc/nvim_intro.txt b/runtime/doc/nvim_intro.txt
index 40f6562..902823b 100644
--- a/runtime/doc/nvim_intro.txt
+++ b/runtime/doc/nvim_intro.txt
@@ -13,7 +13,7 @@ see |help.txt|.
 For now, it is just an index with the most relevant topics/features that
 differentiate Nvim from Vim:
 
-1. Differences from Vim		 |vim-differences|
+1. Differences from Vim		 |vim-differencess|
 2. Msgpack-RPC			 |msgpack-rpc|
 3. Job control			 |job-control|
 4. Python plugins		 |nvim-python|

```
then run `gmake html`, I get this warning:
```
============================================
nvim_intro.txt, line 16, pointer: >>vim-differencess<<
1. Differences from Vim          YXXYvim-differencessYXXY
```
If instead I used `:helptags .` inside nvim, no warnings are printed.

> Additionally this makefile generates html using awk script (BTW, was not that retired?)

I think it's used for the [generated online documentation](https://github.com/neovim/bot-ci/blob/master/ci/user-docu.sh#L14).

**Comment by ZyX-I** [comment]
@Pyrohh This is strange because it looks like in neovim.github.io#55 it was decided to use @c4rlo’s script.

**Comment by justinmk** [comment]
> I thought neovim/neovim.github.io#55 it was decided to use @c4rlo’s script.

@ZyX-I We never implemented that. Added a todo https://github.com/neovim/bot-ci/issues/12

**Comment by justinmk** [comment]
@ZyX-I  vimscript syntax is currently broken. Any chance you could look at it?

**Comment by justinmk** [comment]
E.g., `endif` is tagged as `vimIsCommand` and mis-highlighted.

**Comment by fmoralesc** [comment]
@justinmk @ZyX-I It seems the generated syntax file is not being installed. I also found this, I worked around it by installing a copy I had around.

**Pull request merged**
