### PR TITLE
[RFC] allow specify api since field and more compatibility checks

### PR DESCRIPTION
**Pull request by bfredl**
- [x] check methods can't be added to new level without bumping api_level
- [x]  check methods can't be added to existing levels (compare with the relevant api level fixture)
- [x]  check that methods in compatible levels actually still exist (not only that they are equal if they exist)
- [x] check that level is not bumped without setting api_prerelease
- [x]  checks should have sensible error messages so the PR contributor (in most cases) know what to do without asking further.

An alternative is: we could actually _compute_ `since` using the metadata fixtures, but I prefer the solution currently in this PR because (1) explicit (and in the correct place) is better than implicit  (2) the binary metadata would then be part of the authoritative source and not just test fixtures.

### CODE REVIEW

**Comment by justinmk** [comment]
> An alternative is: we could actually compute since using the metadata fixtures, but I prefer the solution currently in this PR because (1) explicit (and in the correct place) is better than implicit (2) the binary metadata would then be part of the authoritative source and not just test fixtures.

Agreed.

**Comment by bfredl** [comment]
Updated. As it stands, one more step should be added to `release.sh`: the same time as `api_prerelease` is set to false, the metadata for the newly stable-marked level must be added to the test fixtures.

**Comment by bfredl** [comment]
Updated. This now tests what I want it to test, but suggestions welcome.

**Comment by jamessan** [comment]
> As it stands, one more step should be added to release.sh: the same time as api_prerelease is set to false, the metadata for the newly stable-marked level must be added to the test fixtures.

Is this something intended to be included in this PR, or will that be handled separately?

**Comment by bfredl** [comment]
I added the change to `release.sh`.

**Comment by bfredl** [comment]
Any more comments or should we merge this? The only change to current PRs would be to add `FUNC_API_SINCE(2)` is done with `nvim_buf_get_changedtick` (otherwise there will be a warning)

**Pull request merged**
