### PR TITLE
[WIP] luahl

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by bfredl** [comment]
TODO: document how to use highlight id:s instead of highlight names.

**Comment by bfredl** [comment]
It seems at least less broken than current master :]

**Comment by bfredl** [comment]
TODO: "luahl" is internal jargon, like "bufhl". Stable API needs sensible names. `nvim_buf_set_decoration_provider` ? or something like that. We could also allow more than one provider per buffer, one per ns_id would seem sensible (especially if we want to harmonize this even more with "extmark" api).

**Comment by vigoux** [comment]
Sounds good to me, let's wait for this to be documented and stabilized first? 
What would be the priority order if there is multiple providers? Order of declaration?

**Comment by bfredl** [comment]
I think we should do "one" provider first. TS will be the only provider to start with. we can figure priority when non-TS plugins need it.

**Comment by bfredl** [comment]
Unrelated failure:

```
[ RUN      ] API nvim_parse_expression works with ternary operator: 18.87 ms OK

=============================== Core file ./core ===============================

warning: core file may not match specified executable file.

[New LWP 19185]

warning: Selected architecture i386 is not compatible with reported target architecture i386:x86-64

warning: Architecture rejected target-supplied description

warning: Unexpected size of section `.reg/19185' in core file.

Core was generated by `ps -p 19176 -o ucomm='.

Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg/19185' in core file.

#0  0x5aae0010 in ?? ()

Thread 1 (LWP 19185):

#0  0x5aae0010 in ?? ()

No symbol table info available.

#1  0x11b81e78 in ?? ()
```

Maaybe "one day" we can replace the hand-written vimL parser with something something tree-sitter?

**Comment by bfredl** [comment]
Merged. Still WIP but makes master a little bit less broken, and re-enables some disabled tests :]

**Pull request merged**
