### PR TITLE
refactor(lsp): avoid redundant function wrapping

### PR DESCRIPTION
**Pull request by aktau**
Removes a `function() end` wrap that doesn't appear necessary, given that `vim.schedule` doesn't pass in any arguments. Leftover from #21026.

cc @lewis6991.

### CODE REVIEW

**Comment by lewis6991** [comment]
LGTM. CI failures need addressing.

**Comment by aktau** [comment]
> LGTM. CI failures need addressing.

Done.

**Comment by zeertzjq** [comment]
Still failing

**Comment by dundargoc** [comment]
Install stylua, run `make format`

**Comment by aktau** [comment]
> Install stylua, run `make format`

Done now.

**Pull request merged**
