### PR TITLE
[WIP] Detect mintty as a terminal

### PR DESCRIPTION
**Pull request by Marwes**
Part 1 and 2 of https://github.com/neovim/neovim/issues/6751#issuecomment-301932788

Not sure how to implement step 3 completely. I tried, replacing the `rstream_init_stream` call with `rstream_init_fd` but it does not seem to do the trick. No editor window opens, though it does seem to get further along. With `rstream_init_stream` it aborts at https://github.com/neovim/neovim/blob/e0466dc5925dbe9c47c9b7aebbe8fe55767dd008/src/nvim/tui/tui.c#L285 . With `rstream_init_fd` it does not abort but the editor does not show up either but if i type `:q<Enter>` it aborts in the same location as with `rstream_init_stream`.

```
Breakpoint 1, 0x00000000006f4968 in abort ()
(gdb) backtrace
#0  0x00000000006f4968 in abort ()
#1  0x000000000066e41e in uv_close ()
#2  0x000000000064340e in terminfo_stop (ui=0x59fac50) at ../src/nvim/tui/tui.c:282
#3  0x0000000000643574 in tui_terminal_stop (ui=0x59fac50) at ../src/nvim/tui/tui.c:306
#4  0x00000000006435a2 in tui_stop (ui=0x59fac50) at ../src/nvim/tui/tui.c:312
#5  0x000000000064cd50 in ui_bridge_stop_event (argv=0x65ff858) at ../src/nvim/ui_bridge.c:130
#6  0x000000000049ae20 in multiqueue_process_events (this=0x59f7a60) at ../src/nvim/event/multiqueue.c:150
#7  0x000000000049a4de in loop_poll_events (loop=0x65ff900, ms=-1) at ../src/nvim/event/loop.c:59
#8  0x000000000064376c in tui_main (bridge=0x591d830, ui=0x59fac50) at ../src/nvim/tui/tui.c:345
#9  0x000000000064cbc5 in ui_thread_run (data=0x591d830) at ../src/nvim/ui_bridge.c:104
#10 0x000000000067ffce in uv.thread_start ()
#11 0x00007ffc9ea5a8e6 in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#12 0x00007ffc9ea5a9bc in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#13 0x00007ffc9c1c1fe4 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#14 0x00007ffc9ed1ef91 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#15 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

See #6751

Explanations

https://fossies.org/linux/vim/src/iscygpty.c
https://github.com/BurntSushi/ripgrep/issues/94#issuecomment-261745480

### CODE REVIEW

**Comment by Marwes** [comment]
Tried to read what failed on travis but it is still unclear to me. Nothing should have changed outside of windows so it might have been a flaky test?

**Comment by justinmk** [comment]
Yes `termclose_spec.lua:44` is flaky. Restarted.

**Comment by Marwes** [comment]
No idea how to proceed from here so feel free to merge what is there (it gets things a bit further along with mintty but still crashes) or close it. Anyone that thinks they can fix the last part of this may feel free to base that work on this since the port from vim has a bit of work put into to make things compile.

**Comment by justinmk** [comment]
can you rebase?

**Comment by Marwes** [comment]
Done!

**Comment by justinmk** [comment]
@Marwes perhaps the next step is to update `check_and_set_isatty()`, could you try that?

**Comment by eshepelyuk** [comment]
Any update on this ?

**Comment by janlazo** [comment]
Does `nvim -es -u NONE` work now with `SHELL=cygwin`?

**Comment by justinmk** [comment]
continued at https://github.com/neovim/neovim/pull/8271

**Pull request closed without merging**
