### PR TITLE
docs: a small fix

### PR DESCRIPTION
**Pull request by zdm2202**
change '[text(, hl_id, repeat)]' into '[(text, hl_id, repeat)]'

### CODE REVIEW

**Comment by zdm2202** [comment]
Oh sorry, I just noticed that: #26781

**Comment by zdm2202** [comment]
Should I close this pull request?

**Comment by zeertzjq** [comment]
There is nothing wrong with the text.

**Comment by zdm2202** [comment]
Thank you. But I wander how to understand the ',' after '(' ? Is that a valid grammar?

**Pull request closed without merging**
