### PR TITLE
fix: do not cast offset to char_u

### PR DESCRIPTION
**Pull request by mjlbach**
* str_utf_start/end both cast the offset into the utf string
to a char_u, a pointer + long is well-defined and the cast is
unnecessary. This previously resulted in issues for offsets greater than
256.

### CODE REVIEW

**Comment by rish987** [comment]
Thanks. This doesn't quite close #16624 since parts of #16358 need to be fixed. I've been working on a general refactor/simplification/fix of `sync.lua` with many new test cases that should be ready within the next hour or so.

**Comment by rish987** [comment]
See #16669

**Comment by mjlbach** [comment]
Test error is unrelated

**Comment by mjlbach** [comment]
I think it's unlikely that we will merge #16669 anytime soon, so this should still be merged.

**Comment by gebner** [comment]
This PR doesn't fix #16624 for me.

**Comment by mjlbach** [comment]
Sure, removed that from the issue description. It's still a necessary bugfix.

**Review by bfredl — APPROVED** [review]

**Pull request merged**
