### PR TITLE
fix(runtime): fully port emoji_list to Lua

### PR DESCRIPTION
**Pull request by clason**
Problem: `runtime/tools/emoji_list.vim` is a Lua script masquerading as Vimscript, which is unnecessary now that `:source` works for Lua files.

Solution: Remove Vimscript wrapper.

Question: Is there a better place for this script? E.g., `runtime/lua/emoji_list.lua`? Or is this too niche to pollute the `require` namespace with?

### CODE REVIEW

**Comment by justinmk** [comment]
> Is there a better place for this script? E.g., `runtime/lua/emoji_list.lua`? Or is this too niche to pollute the `require` namespace with?

It could live in `runtime/pack/dist/opt/` . The "tools" subdir should be eliminated, either those should live in scripts/ or if they are wanted by users then `runtime/pack/dist/opt/` is the place for them.

**Comment by clason** [comment]
> It could live in runtime/pack/dist/opt/ .

Hmmm... This feels a bit wrong; those are for "proper" plugins (i.e., plugins that set stuff up and then react to commands or mappings), while this is a single-shot script. It's most similar to stuff directly under `runtime/` like `macmap.vim` (although those are hateful, too).

Maybe a separate `runtime/scripts` folder, which can collect all those "one-off" scripts (that we want to keep!) from `runtime/`, `tools/`, and `pack/dist/opt` (like `swapmouse` and `shellmenu` -- which I'd put on the chopping block, personally)?

**Comment by justinmk** [comment]
> Maybe a separate `runtime/scripts` folder

sure. the stuff in runtime/macros/ could also go in there.

**Comment by clason** [comment]
> sure. the stuff in runtime/macros/ could also go in there.

If we want to keep it... How do we decide? Do you want to make an executive decision?

**Comment by clason** [comment]
I any case, this need not block this PR and is better tackled in the context of #22980. I'll start chipping away on that in a follow-up PR.

**Comment by justinmk** [comment]
> Do you want to make an executive decision?

no 😂 

I think moving these various scripts to one place is a good improvement to start with. There might be one or two scripts that obviously should be dropped entirely, but anything marginally useful can stay.

**Comment by clason** [comment]
Even `swapmouse.vim`?

**Pull request merged**
