### PR TITLE
[RDY] vim-patch:8.0.0672

### LINKED ISSUE #7589: Calling synID() breaks third return value from synconcealed()
- `nvim --version`: v0.2.1 (from the Arch Repos) and d6f9d1df0
- Vim (version: 8.0, patches 1-1297, also from Arch Repos) behaves differently? YES
- Operating system/version: Arch Linux (uname -a: `Linux tp 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`
- Terminal name/version: [termite](https://github.com/thestinger/termite/) v12 (from Arch Repos)
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

We need a minimal config folder with a simple syntax file, so:

```
mkdir -p testfolder/syntax
cp example.vim testfolder/syntax
cp test.vim test.txt testfolder/
cd testfolder
```
with these files:

*example.vim* syntax file:
```vim
syn match tutorSampleTextMark /^--->/ conceal cchar=→
```
the *test.vim* script to demonstrate the problem
```vim
if !has('nvim')
  se nocp
endif
set cole=2
syntax on
filetype on

let lnum = 1

for cnum in range(1, len(getline(lnum)))
  echo synconcealed(lnum, cnum)
  " TODO Comment the following line in or out to see the bug:
  echo synID(lnum, cnum, 1)
endfor

quitall!
```
and the *test.txt* data file:
```
--->
vim: ft=example
```

### Actual behaviour

The output from `nvim --headless -u NONE --cmd 'se rtp+=.' -S test.vim test.txt` is:
```
"test.txt" "test.txt" 2L, 21C
[1, '→', 1]
88
[1, '→', 2]
88
[1, '→', 3]
88
[1, '→', 4]
88
```

### Expected behaviour

The output from `vim -T dumb -u NONE --cmd 'se rtp+=.' -S test.vim test.txt` is:
```

"test.txt" 2 lines, 21 characters
[1, '→', 1]
87
[1, '→', 1]
87
[1, '→', 1]
87
[1, '→', 1]
87
```

If the synID() call in test.vim is commented out both nvim and vim produce this output:

```
"test.txt" "test.txt" 2L, 21C
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
```

In my opinion this demonstrates that a call to `synID()` will somehow mess up the third return value from `synconcealed()` which per the docs should be
```
[...] a unique number representing the
specific syntax region matched. This allows detection of the
beginning of a new concealable region if there are two
consecutive regions with the same replacement character.
```

### PR DESCRIPTION
**Pull request by nateozem**
Problem:    Third item of synconcealed() changes too often. (Dominique Pelle)
Solution:   Reset the sequence number at the start of each line.

https://github.com/vim/vim/commit/cc0750dc6e878394ab0fd922b7ea4280918ae406

closes #7589

### CODE REVIEW

**Comment by justinmk** [comment]
This closes #7589, right? It's always a good idea to mention that in the commit message.

**Comment by nateozem** [comment]
@justinmk you're right. thanks for the advise.

**Comment by justinmk** [comment]
8.0.0659 should also be included. Maybe check the ones in between 8.0.0659-8.0.0672.

**Comment by nateozem** [comment]
sure, I'll look into it.

**Comment by nateozem** [comment]
@justinmk what should I be checking for between 8.0.0659-8.0.0672?  Should I check if the other patches would contain changes from the same files as 8.0.0672 patch?

**Comment by justinmk** [comment]
It's only 13 patches, I would suggest checking each one to see if it's releated to "conceal".

**Comment by nateozem** [comment]
no problem.

**Comment by justinmk** [comment]
merged in https://github.com/neovim/neovim/pull/7887

**Pull request closed without merging**
