### PR TITLE
test: do not write into user's ~/.bash_history

### PR DESCRIPTION
**Pull request by Jun-T**
If I run 'make test' on Linux (Fedora), a few lines like
/_path_/_to_/neovim/build/bin/shell-test REP 31 line
/_path_/_to_/neovim/build/bin/shell-test REP 41 line
are written to my ~/.bash_history.  This is not a serious problem but may be a little bit annoying for users who are using bash as an interactive shell.
These lines are from test/functional/terminal/scrollback_spec.lua.

This PR sets HISTFILE=/dev/null while running the test so that the shell do not write into ~/.bash_history.

I tried
`set(ENV{HISTFILE} "")`
but it didn't work. I don't know why, because running the test from my shell by
`HISTFILE= make test`
does work. I hope /dev/null is available everywhere.

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks! Nice catch.

> I tried `set(ENV{HISTFILE} "")` but it didn't work.

https://cmake.org/cmake/help/latest/command/unset.html

> To force a variable reference of the form `${VAR}` to return an empty string, use `set(<variable> "")`, which clears the normal variable but leaves it defined.

can you try `set(HISTFILE "")`

**Comment by Jun-T** [comment]
> can you try set(HISTFILE "")

It doesn't work. 
HISTFILE must be in environment so that it is passed down to child processes. What we want to do is not to unset HISTFILE but set it to "" and pass it to /bin/sh (= /bin/bash).

BTW, what does the error in Commit Linter mean? What's wrong with my commit?

**Comment by justinmk** [comment]
> HISTFILE must be in environment so that it is passed down to child processes. What we want to do is not to unset HISTFILE but set it to "" and pass it to /bin/sh (= /bin/bash).

just to be clear:

- did you see the quote from https://cmake.org/cmake/help/latest/command/unset.html 
- did you try `set(HISTFILE "")`, _not_ `set(ENV{HISTFILE} "")` ?



> BTW, what does the error in Commit Linter mean? What's wrong with my commit?

we tweaked our commit message conventions: https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#commit-messages

but, I can fix it for you when merging this.

**Comment by Jun-T** [comment]
> did you try set(HISTFILE ""), not set(ENV{HISTFILE} "") ?

Yes. I tried set(ENV{HISTFILE} "") before sending PR, and tried set(HISTFILE "") after your comment. HISTFILE is not used by cmake but should be passed to /bin/bash via environment, so I think it is not surprising that  set(HISTFILE "") does not work.

I tried putting
`print(os.getenv("HISTFILE"))`
in test/functional/terminal/scrollback_spec.lua to see what is passed to lua (and then to /bin/bash).
If I use set(ENV{HISTFILE} "/dev/null") then it prints "/dev/null", but
if I use set(ENV{HISTFILE} "") it prints nil. This means cmake does not create an environment variable HISTFILE. I don't know how to force cmake to create HISTFILE in environment with value "".

**Comment by justinmk** [comment]
ah sorry i just noticed https://cmake.org/cmake/help/latest/command/unset.html#unset-environment-variable : 

> `unset(ENV{<variable>})`
> Removes `<variable>` from the currently available Environment Variables. Subsequent calls of `$ENV{<variable>}` **will return the empty string.**

**Comment by Jun-T** [comment]
> try unset(ENV{HISTFILE})

It does not work, of course.
As I wrote before, HISTFILE must exist (should not be unset), but set to "" (zero-length string).
Unset-variable (non-existent variable), and
variable set to ""
are different.
Since we need to propagate HISTFILE from build system (cmake? ninja?) to the shell, it must exist as an environment variable.

`set` builtin command of a shell shows all the existing variables. For example:
```
$ set | grep FOO

$ FOO=
$ set | grep FOO
FOO=
$ unset FOO
$ set | grep FOO

```
(the last command may show `_=FOO` but it means the variable `_` has a value `FOO`)

I think /dev/null is sufficiently portable, but if you want to avoid it, another possibility would be:
`set(ENV{HISTFILE} "${BUILD_DIR}/sh_history")`
(or a file in TMPDIR?).

**Comment by Jun-T** [comment]
If HISTFILE has non-empty value, the shell use it as a history file name.
If HISTFILE exists but  empty (zero-length), then the shell does not output history to a file.
if HISTFILE does not exist (unset), the shell uses the default history file.

This behavior is common to many (but not all) shells.

**Comment by Jun-T** [comment]
Bash set HISTFLE to ~/.bash_history if it is not set in environment.
If cmake does not allow us to set environment variable HISTFILE to "" (empty string),
another possibility is to unset it (or set it to empty) after starting the shell.
This can be done if we add
    `feed_data('unset HISTFILE\n'))`
just after the following line (and line 414)
https://github.com/neovim/neovim/blob/7525052270c4c5e62b9b5bc7dbc20b851f986900/test/functional/terminal/scrollback_spec.lua#L398

So the possibilities are:
set HISTFILE to /dev/null or to a file in builddir or tmpdit
(in RunTest.cmake, before starting the shell, via environment),
or unset HISTFILE after starting the shell (in scrollback_spec.lua),

**Comment by justinmk** [comment]
> Unset-variable (non-existent variable), and
> variable set to ""
> are different.

I know. But that doesn't mean cmake works exactly the same. The cmake doc https://github.com/neovim/neovim/pull/15621#issuecomment-916932549 gave the impression that the env var would be empty string. I guess that is a wrong interpretation though.

**Comment by Jun-T** [comment]
But if we modify scrollback_spec.lua, similar modification will be necessary (in the same or other files) if we use shell interactively in tests.
So I think modifying RunTest.cmake is better.

**Comment by Jun-T** [comment]
Already merged, but:
I was curious why set(ENV{HISTFILE} "") does not work. So I've looked into the cmake source code just briefly (cmSetCommand.cxx). It seems `set(ENV{HISTFILE} "")` works only if the environment variable HISTFILE already exists. So replacing `set(ENV{HISTFILE} ")` by
```
set(ENV{HISTFILE} "fake value")    # create HISTFILE
set(ENV{HISTFILE} "")
```
works. I think this is a quite odd behavior of cmake.
I will create an Issue at the cmake webpage in gitlab to  see this is intensional or not.

**Pull request merged**
