### PR TITLE
[RFC] Update to libuv 1.4.2

### PR DESCRIPTION
**Pull request by ghost**
This should apparently allow libuv to work on SmartOS (#2049). If anyone running OS X could try this out, it'd be appreciated (see #1914 and https://github.com/neovim/neovim/issues/1914#issuecomment-75378246).

It might be worth mentioning that this is in the `1.3.0` changelog: `fs, pipe: no trailing terminator in exact sized buffers (Andrius Bentkus)`. I don't know if we rely on such semantics.

### CODE REVIEW

**Comment by Pyrohh** [comment]
```
Test results:
ALL DONE
make[1]: Leaving directory `/home/travis/build/neovim/neovim/src/nvim/testdir'
make  -C .deps
make[1]: Entering directory `/home/travis/build/neovim/neovim/.deps'
make[2]: Entering directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Entering directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Entering directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
[ 13%] Built target libuv
[ 26%] make[3]: Entering directory `/home/travis/build/neovim/neovim/.deps'
Built target unibilium
make[3]: Entering directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
[ 39%] Built target libvterm
make[3]: Entering directory `/home/travis/build/neovim/neovim/.deps'
[ 52%] Built target luajit
make[3]: Entering directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
[ 65%] Built target msgpack
[ 78%] Built target libtermkey
make[3]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
make[3]: write error
make[2]: *** [CMakeFiles/luarocks.dir/all] Error 1
make[2]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/travis/build/neovim/neovim/.deps'
make: *** [deps] Error 2
```

Write error, huh... wonder what that's about.

**Comment by wbinnssmith** [comment]
On OS X: pointed homebrew at this branch and pulled in the referenced libuv, and it built and ran like a charm. Been going strong for a while now :smile:

**Comment by fwalch** [comment]
Restarted the failing Travis job, seems to have worked now. Also just found out that libuv on Arch Linux is already on 1.4.2 since the end of February, looks like it didn't cause problems.

**Comment by tarruda** [comment]
:+1: merged, thanks

**Pull request closed without merging**
