### PR TITLE
[WIP] tests: Migrate legacy test 10

### PR DESCRIPTION
**Pull request by AitorATuin**

### CODE REVIEW

**Comment by AitorATuin** [comment]
Random failures in the CI system?

**Comment by AitorATuin** [comment]
Any clue why is this build failing?

**Comment by AitorATuin** [comment]
Now it worked, so i guess it's failing randomly ...

**Comment by bfredl** [comment]
Dup of #2844, please see #1286 for an overview of existing PRs. While porting untouched tests are welcome, to speed up the legacy test porting, the most efficient way to contribute right now is likely to review existing open PRs. (It will also help to learn the preferred style, like using `write_file` for handling input files, like #2844 does)

**Comment by AitorATuin** [comment]
ok, sorry for the dup, my bad. I will look into the list before porting a new test and i will help with the review process to get used to the preferred style. :+1: 

btw, why do we have random failures in the CI?

Thanks for the advise.

**Comment by justinmk** [comment]
> btw, why do we have random failures in the CI?

Because the new functionaltest-lua build is flakey. We need to ignore a specific test in that build, to avoid spurious failures.

**Pull request closed without merging**
