### PR TITLE
build: remove old workarounds

### PR DESCRIPTION
**Pull request by dundargoc**
- build: remove workaround for old luajit versions

Luajit version 2.1.0-beta3 was released 2017, there's no reason to use
such an old version on macOS. Also, the version check doesn't work
anymore as LUAJIT_VERSION seems to not be defined anywhere.

- build: remove workaround for ancient clang versions

We don't need to support this as it's only required when using
AddressSanitizer, meaning it only affects developers.

### CODE REVIEW

**Comment by clason** [comment]
Can we set the minimum version of LuaJIT somewhere else? 

Alternatively, just simplify the check to unconditionally error if LuaJIT version is less than 2.1.0-beta3.

**Comment by dundargoc** [comment]
`LUAJIT_VERSION` isn't defined for me even when using luajit. I suspect it's never defined anywhere, so the conditional that was removed probably hasn't been used for a long time. I'm fairly confident we can remove this without any consequences.

Pkgconfig seems to think that the luajit version is `2.1.0-beta3` since `PC_LUAJIT_VERSION=2.1.0-beta3`, but as I understand it this is a really old version and not the actual version we're currently using, so I'm assuming it's simply unable to correctly determine the real version. Furthermore, pkgconfig isn't a required program since it's unusual to have on Windows, so this variable isn't even defined half the time, so it's a dead end as well.

I'm guessing that leaves us with having to manually determine which luajit commit is later than another commit if we decide to pursue this? As I understand it Luajit doesn't do any versioning, only commits, so that's the only option I can think of.

**Comment by clason** [comment]
The version is correct; it just is meaningless since Mike Pall stopped caring about releases.

I don't think we can and should require a specific commit; the point was just to handle a version that is _definitely_ too old (since an actual release), even though it might not cover later but still too old versions. (Best efforts and whatnot.)

**Comment by dundargoc** [comment]
Proposal: let's move forward with this PR in its current state since the version checking isn't working to begin with. I'll write a tracking issue about implementing a real luajit version check that I or someone else can implement later on. This PR is only meant to unblock/remove as much code as possible before https://github.com/neovim/neovim/pull/21589.

**Comment by dundargoc** [comment]
https://github.com/neovim/neovim/issues/21688

**Pull request merged**
