### PR TITLE
feat(nvim_buf_set_extmark): add sign_name

### PR DESCRIPTION
**Pull request by glepnir**
add `sign_name` in `nvim_buf_set_extmakrk`, it's useful when use this api to set sign

### CODE REVIEW

**Comment by lewis6991** [comment]
I don't think we should do this. Sign names were a design aspect of legacy vim signs. They are unnecessary for extmarks and we need to migrate away from them.

If you need to set a sign name then use `vim.fn.*`.

**Comment by clason** [comment]
You can also use namespaces to group signs.

**Comment by glepnir** [comment]
idk. feel free close.

**Comment by luukvbaal** [comment]
> I don't think we should do this. Sign names were a design aspect of legacy vim signs. They are unnecessary for extmarks and we need to migrate away from them. 

I think it would have been nice if `sign_name` were required when setting a sign through the extmark API. For statuscolumn consumers it is an unfortunate design decesion that marks do not have a name attached to them (brought this up with Lewis a few months ago).

> You can also use namespaces to group signs.

How descriptive namespaces are is not up to the interested party (statuscolumn consumer). The namespaces used by gitsigns and diagnostics currently are not descriptive enough to distinguish signs from one another. They are all grouped into a single namespace.

Having said that, I don't think there is any point to add this field, at least if we don't require it. It is possible to distinguish by sign text or highlight group instead, up to a point.

**Comment by clason** [comment]
> How descriptive namespaces are is not up to the interested party (statuscolumn consumer). The namespaces used by gitsigns and diagnostics currently are not descriptive enough to distinguish signs from one another.

Doesn't mean that can't be changed, if people give a compelling enough reason? We could also consider hierarchical namespaces (or at least document some official convention) if that would be of wide enough use. The point is to prefer generic composable solutions over the smörgåsbord of legacy one-offs.

**Pull request closed without merging**
