### PR TITLE
[RFC] vim-patch:8.1.0449,8.1.0450

### LINKED ISSUE #3484: Erratically flashing `hl-Folded` highlighting when `'rnu'` is set
In recent versions of Vim (starting with 8.1.0373?), when `'relativenumber'` is set and actions are performed in a window containing folded lines, the highlighting at the intersection of folded lines and the relative-number columns flashes erratically.

In older versions of Vim, the highlighting consistently stays where it should.

Reproduction: `echo -e "{{{1\nline 1\n{{{1\nline 2\n" | vim --clean --not-a-term -c 'se fdm=marker rnu | au VimEnter * cal timer_start(100, {id -> feedkeys("gsjgskgsO\<Esc>gsjV\<Esc>gsj")})' -`

### PR DESCRIPTION
**Pull request by mvilim**
#### vim-patch:8.1.0449: when 'rnu' is set folded lines are not displayed correctly

Problem:    When 'rnu' is set folded lines are not displayed correctly.
            (Vitaly Yashin)
Solution:   When only redrawing line numbers do draw folded lines.
            (closes vim/vim#3484)
https://github.com/vim/vim/commit/7701f308565fdc7b5096a6597d9c3b63de0bbcec

#### vim-patch:8.1.0450: build failure without the +fold feature

Problem:    Build failure without the +fold feature.
Solution:   Add #ifdef.
https://github.com/vim/vim/commit/0e9deefb4fb4f99d0ab90b21ca38260be26bf5de

This upstream patch fixes a conflict between relative line numbers and fold highlighting. Previously, relative line numbers would update on a cursor movement and overwrite fold highlighting in the line number columns. Other operations can cause the fold highlighting to overwrite the line number styles. Together, this causes the highlighting in the line number columns to flicker back and forth while editing.

The second commit (8.1.0450) has no effect (as it adds a feature ifdef that no longer exists in neovim and modifies a variable that is not used again), but it has been included for completeness.

To observe the effect of these commits, create a file `Xtest_folds_with_rnu` with the following contents:

```
set fdm=marker rnu foldcolumn=2
call setline(1, ["{{{1", "nline 1", "{{{1", "line 2"])
```

and then call `nvim -S Xtest_folds_with_rnu` and press `j` (i.e. the cursor down key); observe that the fold highlighting disappears.

### CODE REVIEW

**Comment by mvilim** [comment]
The first build failed due to a file sourced in the ported test that no longer exists. I have force pushed a fix.

Is the code coverage required to be fixed? The changed is covered by the ported "old test", but I presume that is not counted in the code coverage.

**Comment by bfredl** [comment]
Unfortunately the old test doesn't run, it uses vim specific functionality. A nvim screen test would be needed for testing.

**Comment by mvilim** [comment]
You are correct -- the old test was not doing anything. I did not read it carefully enough or run it without the patch.

I have replaced it with an equivalent nvim screen test (and verified that it fails without this patch).

The MSVC_32 build failure appears to be unrelated -- it looks like a test timed out.

**Comment by justinmk** [comment]
@mvilim Thank you for the clear explanation and test case (which are always worth including in the commit message, so I did).

The `test_fold.vim` changes will be skipped silently because (without the `*.dump` files)
`CanRunVimInTerminal()` returns false for Nvim `oldtests` target. So we generally include those tests because it makes merges more convenient.

oldtests can be run individually like this:

    NVIM_LISTEN_ADDRESS= VIMRUNTIME= TEST_FILE=test_fold.res make oldtest

**Comment by mvilim** [comment]
Great; thank you for the comments (noted) and for fixing up + merging.

**Pull request closed without merging**
