### PR TITLE
docs(lsp): use protocol.Methods instead of raw strings

### PR DESCRIPTION
**Pull request by MariaSolOs**
IMO examples should encourage the use of `vim.lsp.protocol.Methods` instead of string literals.

### CODE REVIEW

**Review by glepnir — APPROVED** [review]

**Comment by MariaSolOs** [comment]
@clason @mfussenegger I would appreciate a quick review of this 😸

**Comment by justinmk** [comment]
> examples should encourage the use of

generally agree, but I'm on the fence in this case. I would guess that `"textDocument/publishDiagnostics"` is more recognizable for those familiar with LSP, vs the very verbose symbol name.

No objection if others approve though.

**Comment by MariaSolOs** [comment]
@justinmk I agree that this change makes the examples a bit more verbose, but given that these end up being the main point of reference for neovim extenders, I feel like they should encourage the use of the string constants versus hard-coding the literals.

WDYT of adding a small clarification at the beginning saying that "`methods` below will refer to `vim.lsp.protocol.Methods`" and then use that in the examples? I'll add a commit that reflects what I mean.

**Comment by mfussenegger** [comment]
> generally agree, but I'm on the fence in this case. I would guess that "textDocument/publishDiagnostics" is more recognizable for those familiar with LSP, vs the very verbose symbol name.

> No objection if others approve though.

I had similar thoughts. It also makes it less clear that you can use any method, including off-spec functions or future addition, in case we lag behind with updating protocol.Methods - the request functions are forward compatible. That's an important aspect.

> WDYT of adding a small clarification at the beginning saying that "methods below will refer to vim.lsp.protocol.Methods" and then use that in the examples? I'll add a commit that reflects what I mean.

It's common to jump to a sub-section in the docs, in which case users would miss this.

I think a compromise could be to introduce `vim.lsp.protocol.Methods`  somewhere in the beginning, with an example that shows the text version and then the Methods version. It would be okay for me if the remainder then uses the constants.

**Comment by MariaSolOs** [comment]
Hmmm @justinmk do you know why the generator says that the [methods should be kept at the end of the file](https://github.com/neovim/neovim/blob/4258f4d53cb3d8d0adbaccf410e1bb422db9badb/scripts/gen_lsp.lua#L44)? IIRC you reviewed that PR so you might have some context.

**Comment by glepnir** [comment]
only the methods part of `lsp/protocol.lua` is generated by the script.  it needs to be inserted at the end of the file.

**Comment by MariaSolOs** [comment]
@glepnir but correct me if I'm wrong, but doesn't the layout of `lsp/protocol.lua` affect the section order of `lsp.txt`? Not entirely familiar with how the docs are generated.

**Comment by glepnir** [comment]
you mean `Methods` not the latest element of `lsp-protocol` ? doc generate by `scripts/gen_vimdoc.py` . keep to latest because when lsp new version release there need regenerate `Methods` part.

**Comment by MariaSolOs** [comment]
@glepnir Sorry my question isn't clear. What I'm wondering is if it's okay for me to move the `Methods` section higher up in the `lsp.txt` docs despite the generator needing for the methods to be defined at the bottom of the file.

**Comment by MariaSolOs** [comment]
@justinmk hmm if I move the `lsp.protocol` section at the top then `scripts/gen_vimdoc.py` will still create the section at the end.

**Comment by MariaSolOs** [comment]
Ahhh I'll just close this PR. The type generator will always write the `lsp.protocol` section at the end, which conflicts the idea of having the clarification about string literal versus the variables before the examples. You've also convinced me that using the fully qualified variables makes the examples more verbose and a bit harder to digest.

**Pull request closed without merging**
