### PR TITLE
[RDY] event.c: Simplify timer use in event_poll()

### PR DESCRIPTION
**Pull request by oni-link**
event.c: Simplify timer use in event_poll()

event_poll() always leaves the libuv I/O loop after one iteration. The
duration for how long the loop polls for I/O is given by the shortest
timeout of all active timers. Is no timer active, I/O is/could be polled
indefinitely.

To make sure our timer is still active when I/O polling begins,
a prepare handle is used to start the timer right before the polling.

But by only using a timer that restarts after its timeout was reached,
we also can assure that polling is done with (nearly) the same finite
timeout.

For a short explanation how the I/O loop is working, see
http://docs.libuv.org/en/latest/design.html#the-i-o-loop.

### CODE REVIEW

**Comment by UnrealQuester** [comment]
The TimerData at the top of event.c is now unused and can be removed as well. Otherwise, LGTM.

**Comment by oni-link** [comment]
@UnrealQuester, removed `TimerData` type and repushed.

**Comment by aktau** [comment]
I also don't believe there can be a large interval between starting the timer and starting to poll, so I believe this is a worthwhile simplification. LGTM.

**Comment by tarruda** [comment]
:+1: LGTM

**Comment by philix** [comment]
Merged manually (single commit -> fast forward). It's my first merge and I hope I didn't mess anything up.

Thanks @oni-link!

**Pull request closed without merging**
