### PR TITLE
build(deps): bump libuv and luv

### PR DESCRIPTION
**Pull request by clason**
LibUV 1.43.0 contains our MinGW patch, so remove that.

Luv 1.43.0-0 contains https://github.com/luvit/luv/pull/571 by @erw7, which is useful for https://github.com/neovim/neovim/pull/15658.

### CODE REVIEW

**Comment by zhaozg** [comment]
luv has release  [1.43.0-0](https://github.com/luvit/luv/releases/tag/1.43.0-0)

**Comment by clason** [comment]
> luv has release [1.43.0-0](https://github.com/luvit/luv/releases/tag/1.43.0-0)

That's what I'm including here, yes (thanks!)

**Review by bfredl — APPROVED** [review]

**Comment by clason** [comment]
macOS 11.0 failure is worrying: 

```
2022-01-28T14:10:38.3386060Z -- Tests exited non-zero: Subprocess aborted
2022-01-28T14:10:38.3386470Z -- Output to stderr:
2022-01-28T14:10:38.3386740Z LuaJIT ASSERT lj_api.c:836: lua_rawgeti: stack slot 2 is not a table
```

**Comment by clason** [comment]
@jamessan could you take a look at the Windows CI failure? I'm not sure it's something to do with this PR or just the general problems we've been having.

**Comment by jamessan** [comment]
OpenBSD build is also [crashing](https://builds.sr.ht/~jmk/job/687145#task-build-529), which gives me pause.

**Comment by clason** [comment]
Oof. That's not good. I've looked through the changelogs but didn't find anything clearly related.

**Comment by clason** [comment]
I guess I'll start by separating these bumps into two commits and see if we can narrow it down to one.

**Comment by clason** [comment]
Hmm. Curiouser and curiouser.

Still, flake is not good.

**Comment by zeertzjq** [comment]
On Arch Linux with libuv 1.43.0 and libluv 1.42.0 I occasionally get some assertion failure on exit with a message containing `uv__is_closing()`. I can recall this happening more than once several hours ago, but now opening and closing Nvim a hundred times doesn't trigger the failure any more.

**Comment by clason** [comment]
Yeah, I'm tentatively blaming luv specifically at the moment (hence I'm currently running CI against that bump in isolation).

**Comment by clason** [comment]
Hmm, openBSD passes now, but the same failures on macOS 10.15 and Windows (failing to start servers).

**Comment by clason** [comment]
Trying again with libuv _and_ the latest LuaJIT; let's see if that makes a difference.

**Comment by zeertzjq** [comment]
> failing to start servers

Doesn't that always appear?

**Comment by clason** [comment]
> > failing to start servers
> 
> Doesn't that always appear?

I do see it frequently, but not as consistently as with this PR. (Which is the frustrating thing here: I cannot tell what is going wrong with the failing tests.)

**Comment by clason** [comment]
....aaand BSD is failing again. So I guess we have the culprit 😆  (See also https://github.com/libuv/libuv/issues/3452.)

**Comment by zeertzjq** [comment]
This failure on macOS never happens before:
```
2022-02-03T14:00:31.1987850Z [  ERROR   ] 1 error, listed below:
2022-02-03T14:00:31.1988220Z [  ERROR   ] test/functional/plugin/lsp_spec.lua @ 385: LSP basic_init test workspace/configuration returns NIL per section if client was started without config.settings
2022-02-03T14:00:31.1988600Z test/helpers.lua:73: Expected objects to be the same.
2022-02-03T14:00:31.1988800Z Passed in:
2022-02-03T14:00:31.1989070Z (userdata) 'mpack.NIL'
2022-02-03T14:00:31.1989240Z Expected:
2022-02-03T14:00:31.1989410Z (table: 0x0116925dd8) {
2022-02-03T14:00:31.1989590Z   [1] = mpack.NIL
2022-02-03T14:00:31.1989750Z   [2] = mpack.NIL }
```

**Comment by clason** [comment]
Yes. But I don't see what the reason is (server start failed). LSP works fine locally (macOS 12) with these changes.

**Comment by clason** [comment]
And now macOS passes... Guess we have to chose ;)

**Comment by bnoordhuis** [comment]
@clason Libuv maintainer here. The openbsd failure only says "Abort trap". Is there a way to get more info, preferably a backtrace?

My hunch is either libuv/libuv@6cce781b or libuv/libuv@e43eb667 - those are the only bsd-specific changes in v1.43.0.

**Comment by clason** [comment]
> @clason Libuv maintainer here. The openbsd failure only says "Abort trap". Is there a way to get more info, preferably a backtrace?

Thanks for looking into this! I don't have access to these hosts, but @jamessan might.

> My hunch is either [libuv/libuv@6cce781](https://github.com/libuv/libuv/commit/6cce781b) or [libuv/libuv@e43eb66](https://github.com/libuv/libuv/commit/e43eb667) - those are the only bsd-specific changes in v1.43.0.

Only the first is in 1.43.0, right? The second one is the fix slated for 1.44.0

I can test a build with LibUV checkout out at that commit and see if it fixes things.

**Comment by clason** [comment]
Yep, that seems to have fixed it indeed!

**Comment by clason** [comment]
Test failures look like standard GHA timeout flakery.

**Pull request merged**
