### PR TITLE
fix using unbundled libuv

### PR DESCRIPTION
**Pull request by dperson**
Currently even when `USE_BUNDLED_LIBUV` is false, the bundled path is hard coded, leading to a build failure. This fixes the `cmake` logic to do the right thing.

### CODE REVIEW

**Comment by mhinz** [comment]
Is this working locally for you?

**Comment by mhinz** [comment]
Maybe like this?

```diff
diff --git c/third-party/cmake/BuildLuarocks.cmake i/third-party/cmake/BuildLuarocks.cmake
index 069c94e..5e9576e 100644
--- c/third-party/cmake/BuildLuarocks.cmake
+++ i/third-party/cmake/BuildLuarocks.cmake
@@ -142,9 +142,13 @@ if(USE_BUNDLED_BUSTED)
   if(MINGW AND CMAKE_CROSSCOMPILING)
     set(LUV_DEPS ${LUV_DEPS} libuv_host)
   endif()
+  set(LUV_ARGS make ${LUAROCKS_BUILDARGS} CFLAGS='-O0 -g3 -fPIC')
+  if(USE_BUNDLED_ON)
+    set(LUV_ARGS ${LUV_ARGS} LIBUV_DIR=${HOSTDEPS_INSTALL_DIR})
+  endif()
   add_custom_command(OUTPUT ${HOSTDEPS_LIB_DIR}/luarocks/rocks/luv
     COMMAND ${LUAROCKS_BINARY}
-    ARGS make ${LUAROCKS_BUILDARGS} LIBUV_DIR=${HOSTDEPS_INSTALL_DIR} CFLAGS='-O0 -g3 -fPIC'
+    ARGS ${LUV_ARGS}
     WORKING_DIRECTORY ${DEPS_BUILD_DIR}/src/luv
     DEPENDS ${LUV_DEPS})
   add_custom_target(luv
```

**Comment by dperson** [comment]
Oops, sorry that I messed up the `cmake` syntax. LGTM, Thank you.

**Comment by mhinz** [comment]
Feel free to update your commit, you found the bug after all. ;-)

**Comment by dperson** [comment]
Okay, I've updated the `cmake` code as you suggested. Thanks for the help. =)

**Comment by mhinz** [comment]
Merged. Thank you!

**Pull request closed without merging**
