### PR TITLE
[RFC] job control: allow not sending final newline in jobsend

### PR DESCRIPTION
**Pull request by bfredl**
This implements #1838 

I opted for allowed to send EOF in `jobsend` instead of a separate `jobclose` as it turned to be much simpler to do in a explicitly race-free manner (meaning all data is guaranteed to be sent before close)

There is some missing error handling I should clean up, and I should also check that this allows a WIP fix I have for some discussed problems in #1908  before merging.

### CODE REVIEW

**Comment by bfredl** [comment]
Though, if someone that actually understands `libuv` and this entire business of needing the `w/rstream` layer in _between_ `libuv` and job control (I do not) wants to supersede this effort and implement `jobclose` I'll be just as happy (then only the first commit here should be merged)

**Comment by tarruda** [comment]
@bfredl if you prefer I will do it after #2076

**Comment by bfredl** [comment]
@tarruda Ok, then I will remove the 2nd commit and only fix the endhl issue in this PR.

**Comment by bfredl** [comment]
Now it only does the fix to allow binary data without final endline. Updated docs and tests.

**Comment by justinmk** [comment]
Doesn't this overlap https://github.com/neovim/neovim/pull/1584 ? Is there anything in #1584 that doesn't satisfy your goal here? My fault for not merging #1584 sooner...

**Comment by bfredl** [comment]
My understanding was that #1584 fixes the analogous problem on the _output_ side. To be consistent with that PR, `nofinalhl` should perhaps be default, in which case it could be just removed, but on the on the other hand, if someone does `jobsend(job, ["some command", "second command"])` they might expect that `second command` also should be executed (instead of just waiting indefinitely...)

**Comment by bfredl** [comment]
Nevermind, that was done by #2037 (but the question of consistent defaults still stands)

**Comment by bfredl** [comment]
(To clarify, this PR is still necessary)

**Comment by bfredl** [comment]
>-- Output to stderr:
>
>/opt/neovim-deps/linux-x86/usr/bin/luajit: /opt/neovim-deps/linux-x86/usr/share/lua/5.1/pl/path.lua:38: pl.path requires LuaFileSystem

Is this a "temporarily unavailable dependency" problem? Trying again...

**Comment by bfredl** [comment]
`gcc-32` is consistently broken the last 22 hours

**Comment by bfredl** [comment]
I added a variant where no final newline is sent by default, this is simpler (no option needed) and consistent with how output is represented (with this variant, `jobsend(cat_job, [ some list of strings])` gives the response `['stdout', [ same list of strings] ]` ). this of course contradicts with existing expectations of jobsend, but is OTOH more consistent with `systemlist` and IMHO as the list form is made to fully support binary data is better to be explicit with newlines (needs to be anyway with the output format). What do you think @justinmk @tarruda ?

**Comment by justinmk** [comment]
@bfredl Much better IMO. LGTM after travis.

**Comment by bfredl** [comment]
Unrelated `screen` failure (`legacy/107_adjust_window_and_contents_spec.lua:42`). Anyway, squashing (no code change)

**Comment by tarruda** [comment]
> I added a variant where no final newline is sent by default, this is simpler (no option needed) and consistent with how output is represented (with this variant, jobsend(cat_job, [ some list of strings]) gives the response ['stdout', [ same list of strings] ] ). this of course contradicts with existing expectations of jobsend, but is OTOH more consistent with system[list] input and IMHO as the list form is made to fully support binary data is better to be explicit with newlines (needs to be anyway with the output format). What do you think @justinmk @tarruda ?

:+1:

**Pull request merged**
