### PR TITLE
[RFC] vim-patch:7.4.773

### PR DESCRIPTION
**Pull request by mhinz**
```
Problem:  'langmap' is used in command-line mode when checking for mappings.
Solution: Do not use 'langmap' in command-line mode. (Larry Velazquez)
```

Original patch:
  https://code.google.com/p/vim/source/detail?r=5b1eefbf9a532f32a66fa13abbd671488aaafd5c

### CODE REVIEW

**Comment by Pyrohh** [comment]
@mhinz is this description generated with #2999's version of `vim-patch.sh`?

Also, was marking some patches as `NA` intentional?

**Comment by mhinz** [comment]
@Pyrohh Nope, I didn't use the script, since it tries to clone the entire Vim repo to a fixed directory, but I already have it around. I might whip up a patch for an optional argument.

And yup. I was going through the list of patches and when something didn't apply to our codebase, I just marked it as `NA`.

**Comment by Pyrohh** [comment]
> I might whip up a patch for an optional argument.

:+1: 

> I was going through the list of patches and when something didn't apply to our codebase, I just marked it as NA.

Got it. With that said, could you please mention why they're being set as NA, perhaps like how it was done in 7341b285d08c103f4dc58665b2268ab727c5c2ff?

**Comment by justinmk** [comment]
Merged

**Pull request closed without merging**
