### PR TITLE
vim-patch:8.2.{3378,3379,3384,3386,3398,3400}

### PR DESCRIPTION
**Pull request by seandewar**

### CODE REVIEW

**Comment by clason** [comment]
Did we even port that patch yet?
> Problem:    No test for what 8.2.3391 fixes.

**Comment by seandewar** [comment]
No, but it was safe to include as the regression isn't introduced yet:

> Regression in v8.2.2903 and the fix in v8.2.3391 aren't ported yet, but
this test can be included now in preparation for that, I guess?

Maybe not a good idea?

**Comment by clason** [comment]
Yeah, I guess it's fine since it's not failing (and more tests are always better); we just have to remember to port those two patches in a single PR (which is one of the situations I alluded to in my comment on the other issue) -- but the test will remind us ;)

**Comment by seandewar** [comment]
As I have some free time, I'll investigate porting those patches (if I can, I'll probably do it in a seperate PR and move v8.2.3397 to it).

**Comment by clason** [comment]
If you're _really_ bored, you could also look at the missing patches that https://github.com/neovim/neovim/pull/15599 depends on (and add the tiny doc fixes so we can mark that runtime update as fully ported).

**Comment by seandewar** [comment]
> If you're _really_ bored, you could also look at the missing patches that #15599 depends on (and add the tiny doc fixes so we can mark that runtime update as fully ported).

Don't think I can fully port those yet (i.e: `eval.txt` changes need `:scriptversion`; I have a PR #14611).

Maybe a partial port might be enough to fully port the RT. I'll have a lil' look in a bit. :+1:

**Comment by clason** [comment]
Those updates are really, _really_, trivial, so don't do any more work on their account.

**Review by janlazo — APPROVED** [review]
LGTM

Any last-minute changes or bug fixes?

**Comment by seandewar** [comment]
I think it's good. Feel free to merge. :+1:

**Pull request merged**
