### PR TITLE
fix(lsp): use notify_once on hover

### LINKED ISSUE #20457: allow me to disable notifications in vim.lsp.buf.hover
### Feature already in Vim?

_No response_

### Feature description

Since <https://github.com/neovim/neovim/pull/18308>, every call to `vim.lsp.buf.hover()` that results in an empty response emits a notification. When it is called on hover (`CursorHold`), notifications are spammed constantly.

Please allow me to disable that.

### PR DESCRIPTION
**Pull request by ObserverOfTime**
Closes #20457

### CODE REVIEW

**Comment by glepnir** [comment]
make it  optional will better . if use `notify_once` that means you will only see the prompt once. you'll lose hints in later uses. The reason he thinks it's noise is because he uses hover in the CursorHold event.

**Comment by mfussenegger** [comment]
I don't think showing the notification only once during the lifetime of a neovim instance makes sense. 
Either it should show it all the time or never.

But given how the hover handler is currently just plumbing 3 exposed utils method I wonder if it's worth adding an option. The use case doesn't appear very common to me (?) Overriding the handler to customize it wouldn't be too difficult

**Comment by ObserverOfTime** [comment]
Yeah, I suppose copy-pasting the code and removing the `vim.notify` calls would be a better solution.

**Comment by glepnir** [comment]
yup  do it in custom handler will be better. maybe there has do nothing in upstream . use in an event such as `CursorHold` not  make sense .

**Pull request closed without merging**
